### ISSUE TITLE
'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by ndemeshchenko** [PokemonGoF/PokemonGo-Bot#1001]
### Expected Behavior
bot.take_step complete successfully 

### Actual Behavior
exit with the following exception

```
[17:04:27] Scanning area for objects....
[17:04:27] Walking from (40.7068758, -74.00946479999999) to [40.705075799999996, -74.00946479999999] 0.20km
Traceback (most recent call last):
  File "./pokecli.py", line 250, in <module>
    main()
  File "./pokecli.py", line 241, in main
    bot.take_step()
  File "/Users/ndemeshchenko/pobot_neveragny/pokemongo_bot/__init__.py", line 41, in take_step
    location = self.navigator.take_step()
  File "/Users/ndemeshchenko/pobot_neveragny/pokemongo_bot/spiral_navigator.py", line 80, in take_step
    if self._step_walker.step():
  File "/Users/ndemeshchenko/pobot_neveragny/pokemongo_bot/step_walker.py", line 63, in step
    self.bot.heartbeat()
  File "/Users/ndemeshchenko/pobot_neveragny/pokemongo_bot/__init__.py", line 504, in heartbeat
    self.update_web_location() # updates every tick
  File "/Users/ndemeshchenko/pobot_neveragny/pokemongo_bot/__init__.py", line 81, in update_web_location
    fort['gym_details'] = response_gym_details['responses']['GET_GYM_DETAILS']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

### Steps to Reproduce
just a regular run

### Other Information
OS: Mac OS 10.11.4
Git Commit: 8964c0a6c1b5b98d1059a10f19ca9f7d6568b588
Auth type: google

**Comment by hklcf** [comment]
someone say its server problem

**Comment by hklcf** [comment]
#915

**Comment by cassiuschen** [comment]
I've the same problem. Though it might be a server problem, I think the program should not break down because of that. Instead, it may be able to rescue the problem.

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
