### ISSUE TITLE
Init.py Arguments

### ISSUE THREAD

**Issue by Brom91k** [PokemonGoF/PokemonGo-Bot#1012]
unable to start, got this error no matter what i try :(

$ python pokecli.py
[2016-07-26 18:22:23] [x] PokemonGO Bot v1.0
[2016-07-26 18:22:23] [x] Configuration initialized
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "C:\users\Pokemon Go\Bot Pokemon\PokemonGo-Bot\pokemongo_bot\__init__.py", line 31, in start
    self._setup_api()
  File "C:\users\Pokemon Go\Bot Pokemon\PokemonGo-Bot\pokemongo_bot\__init__.py", line 120, in _setup_api
    self.api = PGoApi()
TypeError: __init__() takes exactly 3 arguments (1 given)

**Comment by hklcf** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#installation

**Comment by Brom91k** [comment]
thx, solved
