### ISSUE TITLE
Expecting property name: line 43 column 5 (char 1366)

### ISSUE THREAD

**Issue by BoGnY** [PokemonGoF/PokemonGo-Bot#1016]
### Error:

> [18:29:37]
> 
>  PokemonGO Bot v1.0
> Traceback (most recent call last):
>   File "pokecli.py", line 250, in <module>
>     main()
>   File "pokecli.py", line 229, in main
>     config = init_config()
>   File "pokecli.py", line 57, in init_config
>     load.update(json.load(data))
>   File "C:\Python\Python27\lib\json\__init__.py", line 291, in load
>     **kw)
>   File "C:\Python\Python27\lib\json\__init__.py", line 339, in loads
>     return _default_decoder.decode(s)
>   File "C:\Python\Python27\lib\json\decoder.py", line 364, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "C:\Python\Python27\lib\json\decoder.py", line 380, in raw_decode
>     obj, end = self.scan_once(s, idx)
> ValueError: Expecting property name: line 43 column 5 (char 1366)

### Steps to Reproduce
I think that error is in my config.json files, but I don't find where is it...
I have searched many times....
This is my config.json file:
```
{
    "auth_service": "google",
    "username": "xxxxx00@gmail.com",
    "password": "xxxx1111",
    "location": "Silea, TV, Italia",
    "gmapkey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "max_steps": 5,
    "mode": "all",
    "walk": 3.90,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "",
    "evolve_all": "none",
    "cp_min": 300,
    "use_lucky_egg": false,
    "evolve_captured": false,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Rattata": { "always_catch" : true },

      "// Legendary pokemons (Goes under S-Tier)": {},
      "Lapras": { "always_catch": true },
      "Moltres": { "always_catch": true },
      "Zapdos": { "always_catch": true },
      "Articuno": { "always_catch": true },

      "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
      "Mewtwo": { "always_catch": true },
      "Dragonite": { "always_catch": true },
      "Snorlax": { "always_catch": true },
      "// Mew evolves to Mewtwo": {},
      "Mew": { "always_catch": true },
      "Arcanine": { "always_catch": true },
      "Vaporeon": { "always_catch": true },
      "Gyarados": { "always_catch": true },
      "Exeggutor": { "always_catch": true },
      "Muk": { "always_catch": true },
      "Weezing": { "always_catch": true },
      "Flareon": { "always_catch": true },
      "Blastoise": { "always_catch": true },
      "Venusaur": { "always_catch": true },
      "Charizard": { "always_catch": true },

    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Rattata": { "always_release" : true },

      "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
      "Exeggcute": { "release_below_cp": 250, "release_below_iv": 0.8, "cp_iv_logic": "or" },
      "Eevee": { "release_below_cp": 50, "release_below_iv": 0.8, "cp_iv_logic": "or" },

      "// A-Tier pokemons": {},
      "Scyther": { "release_below_cp": 200, "release_below_iv": 0.8, "cp_iv_logic": "or" },
      "Pinsir": { "release_below_cp": 100, "release_below_iv": 0.8, "cp_iv_logic": "or" },

      "// Below is B-tier and lower pokemons": {},
      "Pidgey": { "release_below_cp": 120, "release_below_iv": 0.8, "cp_iv_logic": "or" },
      "Rattata": { "release_below_cp": 120, "release_below_iv": 0.8, "cp_iv_logic": "or" },
      "Caterpie": { "release_below_cp": 50, "release_below_iv": 0.8, "cp_iv_logic": "or" },
      "Weedle": { "release_below_cp": 50, "release_below_iv": 0.8, "cp_iv_logic": "or" },
      "Zubat": { "release_below_cp": 120, "release_below_iv": 0.8, "cp_iv_logic": "or" },
      "Spearow": { "release_below_cp": 50, "release_below_iv": 0.8, "cp_iv_logic": "or" },
      "Doduo": { "release_below_cp": 100, "release_below_iv": 0.8, "cp_iv_logic": "or" },
      "Horsea": { "release_below_cp": 50, "release_below_iv": 0.8, "cp_iv_logic": "or" },
      "Staryu": { "release_below_cp": 50, "release_below_iv": 0.8, "cp_iv_logic": "or" },
      "Goldeen": { "release_below_cp": 50, "release_below_iv": 0.8, "cp_iv_logic": "or" },
      "Magikarp": { "release_below_cp": 50, "release_below_iv": 0.8, "cp_iv_logic": "or" },
      "Dodrio": { "release_below_cp": 100, "release_below_iv": 0.8, "cp_iv_logic": "or" },
      "Dratini": { "release_below_cp": 50, "release_below_iv": 0.8, "cp_iv_logic": "or" },

	  }
}
```
I've installed the bot using the installation instruction, all step, and all without error..
Thanks a lot for help!

### Other Information
OS: Windows 10, Python 2.7.12
Git Commit: latest of dev branch

**Comment by BoGnY** [comment]
Problem solved...
I've changed:
`      "Charizard": { "always_catch": true },`
to:
`      "Charizard": { "always_catch": true }`

and:
`"Dratini": { "release_below_cp": 50, "release_below_iv": 0.8, "cp_iv_logic": "or" },`
to:
`"Dratini": { "release_below_cp": 50, "release_below_iv": 0.8, "cp_iv_logic": "or" }`
