### ISSUE TITLE
Arrives at pokestop, loots then traceback error

### ISSUE THREAD

**Issue by ayiire** [PokemonGoF/PokemonGo-Bot#1022]
### Expected Behavior
Arrives at pokestop, loots and continues

### Actual Behavior
Arrives at pokestop, loots then traceback error

### Steps to Reproduce
Run bot, error comes up a few minutes later
Traceback (most recent call last):
  File "C:\pgbot3\pokecli.py", line 246, in <module>
    main()
  File "C:\pgbot3\pokecli.py", line 237, in main
    bot.take_step()
  File "C:\pgbot3\pokemongo_bot\__init__.py", line 45, in take_step
    self.work_on_cell(cell, location)
  File "C:\pgbot3\pokemongo_bot\__init__.py", line 216, in work_on_cell
    hack_chain = worker.work()
  File "C:\pgbot3\pokemongo_bot\cell_workers\seen_fort_worker.py", line 76, in work
    id_filter = self.config.item_filter.get(str(item_id), 0)
AttributeError: 'list' object has no attribute 'get'

### Other Information
Dev release
OS: Windows 10 64bit
Git Commit: 0ebdfc0fe6d23898f47db0674cf892b060a0e06b

**Comment by ayiire** [comment]
Nevermind, I think it's because I left my item filter blank with the new commit

**Comment by ayiire** [comment]
Nevermind, still having the same error message.

[13:16:50] Loot:
[13:16:50] 50 xp
[13:16:50] - 1x Max Potion (Total: 22)
Traceback (most recent call last):
  File "C:\pgbot3\pokecli.py", line 246, in <module>
    main()
  File "C:\pgbot3\pokecli.py", line 237, in main
    bot.take_step()
  File "C:\pgbot3\pokemongo_bot\__init__.py", line 45, in take_step
    self.work_on_cell(cell, location)
  File "C:\pgbot3\pokemongo_bot\__init__.py", line 216, in work_on_cell
    hack_chain = worker.work()
  File "C:\pgbot3\pokemongo_bot\cell_workers\seen_fort_worker.py", line 76, in work
    id_filter = self.config.item_filter.get(str(item_id), 0)
AttributeError: 'list' object has no attribute 'get'


[14:09:31] -- Recycled Hyper Potion!
[14:09:31] PokeStop on cooldown. Time left: 4.96 minutes
[14:09:33] Found fort 48ae7ad586e442ee8c092eec0b483f5b.16 at distance 0.06km
[14:09:33] Need to move closer to Pokestop
[ΓûêΓûêΓûê                                     ] 8%Traceback (most recent call last):
  File "C:\pgbot3\pokecli.py", line 246, in <module>
    main()
  File "C:\pgbot3\pokecli.py", line 237, in main
    bot.take_step()
  File "C:\pgbot3\pokemongo_bot\__init__.py", line 45, in take_step
    self.work_on_cell(cell, location)
  File "C:\pgbot3\pokemongo_bot\__init__.py", line 213, in work_on_cell
    worker.work()
  File "C:\pgbot3\pokemongo_bot\cell_workers\move_to_fort_worker.py", line 42, in work
    if step_walker.step():
  File "C:\pgbot3\pokemongo_bot\step_walker.py", line 78, in step
    self.bot.heartbeat()
  File "C:\pgbot3\pokemongo_bot\__init__.py", line 504, in heartbeat
    self.update_web_location() # updates every tick
  File "C:\pgbot3\pokemongo_bot\__init__.py", line 67, in update_web_location
    status = map_objects.get('status', None)
AttributeError: 'str' object has no attribute 'get'



[14:13:41] Loot:
[14:13:41] 50 xp
[14:13:41] - 1x Revive (Total: 1)
Traceback (most recent call last):
  File "C:\pgbot3\pokecli.py", line 246, in <module>
    main()
  File "C:\pgbot3\pokecli.py", line 237, in main
    bot.take_step()
  File "C:\pgbot3\pokemongo_bot\__init__.py", line 45, in take_step
    self.work_on_cell(cell, location)
  File "C:\pgbot3\pokemongo_bot\__init__.py", line 216, in work_on_cell
    hack_chain = worker.work()
  File "C:\pgbot3\pokemongo_bot\cell_workers\seen_fort_worker.py", line 76, in work
    id_filter = self.config.item_filter.get(str(item_id), 0)
AttributeError: 'list' object has no attribute 'get'

**Comment by shaosh** [comment]
Same issue here

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
