### ISSUE TITLE
The progress bar shows random characters

### ISSUE THREAD

**Issue by Ryurem** [PokemonGoF/PokemonGo-Bot#1029]
### Expected Behavior  
Showing a progress bar 
 
### Actual Behavior  
Showing random characters instead of the progress bar
![bar](https://cloud.githubusercontent.com/assets/17828142/17150248/fd983b02-536e-11e6-8859-0ec6bea25cb6.png)

  

### Steps to Reproduce  
start the bot and let it go to a pokestop

### Other Information  
OS:   Windows 10
Git Commit: 3364aa39d50dbc7e34541007e66ed67ab4071c35

**Comment by TheGoGlider** [comment]
same, but when it reaches the pokestop and gets the item it crashes ```Traceback (most recent call last):
  File "pokecli.py", line 246, in <module>
    main()
  File "pokecli.py", line 237, in main
    bot.take_step()
  File "C:\Users\thego\Desktop\Pokemon GO\Bot Dev TheGoGlider\pokemongo_bot\__init__.py", line 45, in take_step
    self.work_on_cell(cell, location)
  File "C:\Users\thego\Desktop\Pokemon GO\Bot Dev TheGoGlider\pokemongo_bot\__init__.py", line 216, in work_on_cell
    hack_chain = worker.work()
  File "C:\Users\thego\Desktop\Pokemon GO\Bot Dev TheGoGlider\pokemongo_bot\cell_workers\seen_fort_worker.py", line 76, in work
    id_filter = self.config.item_filter.get(str(item_id), 0)
AttributeError: 'list' object has no attribute 'get'```

**Comment by KLVN** [comment]
#1032
