### ISSUE TITLE
Protobuf Error

### ISSUE THREAD

**Issue by palakz** [PokemonGoF/PokemonGo-Bot#1033]
OS: Ubuntu 16.04 LTS

Error:

```
python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 37, in <module>
    from pokemongo_bot import PokemonGoBot
  File "/home/area51/Stuff/PokemonGo-Bot/pokemongo_bot/__init__.py", line 12, in <module>
    from pgoapi import PGoApi
  File "/home/area51/Stuff/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 17, in <module>
    raise PleaseInstallProtobufVersion3()
pgoapi.exceptions.PleaseInstallProtobufVersion3
```
Tried pip install python-protobuf. Still not fixed.
What to do?

**Comment by alexanderrock** [comment]
sudo apt-get install python-protobuf

**Comment by palakz** [comment]
Been there, done that.

```
area51@XXXXXXXXX:~/Stuff/PokemonGo-Bot$ sudo apt-get install python-protobuf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-protobuf is already the newest version (2.6.1-1.3).
The following packages were automatically installed and are no longer required:
  caribou cjs cups-browsed cups-core-drivers cups-daemon
  cups-filters-core-drivers cups-server-common empathy-common gir1.2-cmenu-3.0
  gir1.2-gconf-2.0 gir1.2-keybinder-3.0 guile-2.0-libs hexchat-common
  hexchat-perl hexchat-plugins hexchat-python hplip-data
  libandroid-properties1 libcinnamon-control-center1 libcinnamon-menu-3-0
  libcjs0 libclutter-gst-2.0-0 libcupscgi1 libcupsmime1 libdiscid0
  libfontembed1 libgle3 libgutenprint2 libhpmud0 libjpeg-progs libjpeg9
  libkeybinder-3.0-0 liblouisutdml-bin liblouisutdml-data liblouisutdml6
  libnemo-extension1 liboxideqt-qmlplugin liboxideqtcore0 liboxideqtquick0
  libqpdf17 libqqwing2v5 libqt5positioning5 libsane-hpaio libsensors4
  libsnmp-base libsnmp30 libtelepathy-farstream3 libwebpmux1 nemo-data
  oxideqt-codecs python-imaging python-pam python-pexpect python-pil
  python-ptyprocess python-pyatspi python-pyinotify python3-pexpect
  python3-pil python3-ptyprocess python3-renderpm python3-reportlab
  python3-reportlab-accel qml-module-qt-labs-folderlistmodel
  qml-module-qt-labs-settings qml-module-ubuntu-onlineaccounts
  qml-module-ubuntu-web qpdf qtdeclarative5-accounts-plugin
  qtdeclarative5-qtquick2-plugin telepathy-gabble telepathy-logger
  telepathy-salut unity-webapps-qml xscreensaver-data xscreensaver-data-extra
  xscreensaver-gl xscreensaver-gl-extra
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
area51@XXXXXXXX:~/Stuff/PokemonGo-Bot$ python pokecli.py -a google -u XXXXXXXXX -p XXXXXXXXX -l "Santa Monica Pier" -c 10 -k XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Traceback (most recent call last):
  File "pokecli.py", line 37, in <module>
    from pokemongo_bot import PokemonGoBot
  File "/home/area51/Stuff/PokemonGo-Bot/pokemongo_bot/__init__.py", line 12, in <module>
    from pgoapi import PGoApi
  File "/home/area51/Stuff/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 17, in <module>
    raise PleaseInstallProtobufVersion3()
pgoapi.exceptions.PleaseInstallProtobufVersion3
```
Still the same problem exists. :/

**Comment by rlking** [comment]
version mismatch

**Comment by palakz** [comment]
Yep. Of course.

**Comment by buettner123** [comment]
try it with `sudo pip install --upgrade protobuf`. This did the trick for me.

**Comment by ddrght12345** [comment]
I noticed this on dev. Strangely, I actually REMOVED protobuf through apt, and it started working. So, perhaps try that

**Comment by sargentgills** [comment]
I rewrote the requirements.txt such that the first line "-e git+https://github.com/tejado/pgoapi.git@3787ffbe2e80ebce8a02d48eebceb9edf40179c1#egg=pgoapi" was moved to be the last line, and it solved this error for me. 

Similarly, you could probably just use "pip install -e git+https://github.com/tejado/pgoapi.git@3787ffbe2e80ebce8a02d48eebceb9edf40179c1#egg=pgoapi" after running the requirements.txt

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
