### ISSUE TITLE
Unable to start up bot

### ISSUE THREAD

**Issue by rkodali22** [PokemonGoF/PokemonGo-Bot#1035]
Receiving error:
```
Traceback (most recent call last):
  File "pokecli.py", line 246, in <module>
    main()
  File "pokecli.py", line 225, in main
    config = init_config()
  File "pokecli.py", line 61, in init_config
    load.update(json.load(data))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 22 column 5 (char 598)
```
Config File:
```
{
    "auth_service": "google",
    "username": "xxx",
    "password": "xxx",
    "location": "34.01081704299407,-118.48437309265137",
    "gmapkey": "xxx",
    "max_steps": 50,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 400,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": {
      "1": { "keep" : 100 },
      "101": { "keep" : 1 },
      "102": { "keep" : 1 },
      "103": { "keep" : 48 },
      "201": { "keep" : 50 },
      "701": { "keep" : 100 },
    },
    "evolve_all": "NONE",
    "use_lucky_egg": false,
    "evolve_captured": false,
    "catch": { ... }
```

**Comment by LasseSkogland** [comment]
Something is wrong in your config.json file.
Cross check config.json.example with your config file.
Every bracket needs to be in place, or it will fail.

Try adding
`}`
the the end of your file

**Comment by Sirhyro** [comment]
```
{
    "auth_service": "ptc",
    "username": "user",
    "password": "xxx",
    "location": "xx.xxxxx,-yy.yyyyyy",
    "gmapkey": "xxx",
    "max_steps": 5,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "101,102,103,104",
    "evolve_all": "NONE",
    "use_lucky_egg": false,
    "evolve_captured": false
}
```

I'm receiving the same error, copied the example config over and just changed the auth/user/pass/location/key. Win7x32,Python2.7.

**Comment by Drambuie** [comment]
Make sure there are no comments e.g. // in your config.json file
