### ISSUE TITLE
Integer out of range on startup

### ISSUE THREAD

**Issue by gaz492** [PokemonGoF/PokemonGo-Bot#1041]
### Expected Behavior
Bot to start up and walk around as intended

### Actual Behavior
Starts scanning area for objects then crashes

### Other Information
Error: `[2016-07-26 21:59:30] [#] Scanning area for objects (1 / 25)
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "/home/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/home/PokemonGo-Bot/pokemongo_bot/stepper.py", line 53, in take_step
    self._walk_to(self.config.walk, *position)
  File "/home/PokemonGo-Bot/pokemongo_bot/stepper.py", line 67, in _walk_to
    i2f(self.api._position_lat), i2f(self.api._position_lng), lat, lng)
  File "/home/PokemonGo-Bot/pokemongo_bot/cell_workers/utils.py", line 98, in i2f
    return struct.unpack('<d', struct.pack('<Q', int))[0]
struct.error: integer out of range for 'Q' format code
`
OS: Ubuntu 16.04
Git Commit: 3aca6d798f8a3e173dce0beb7b13c9505cc5b251

EDIT:

Happens in both master and dev branch

**Comment by chadsaun** [comment]
Same here...

```
Traceback (most recent call last):
  File "pokecli.py", line 250, in <module>
    main()
  File "pokecli.py", line 236, in main
    bot.start()
  File "/Users/me/Development/Personal/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in start
    self._setup_api()
  File "/Users/me/Development/Personal/PokemonGo-Bot/pokemongo_bot/__init__.py", line 275, in _setup_api
    self.login()
  File "/Users/me/Development/Personal/PokemonGo-Bot/pokemongo_bot/__init__.py", line 255, in login
    lat, lng = self.position[0:2]
  File "/Users/me/Development/Personal/PokemonGo-Bot/pokemongo_bot/__init__.py", line 27, in position
    return (i2f(self.api._position_lat), i2f(self.api._position_lng), 0)
  File "/Users/me/Development/Personal/PokemonGo-Bot/pokemongo_bot/cell_workers/utils.py", line 118, in i2f
    return struct.unpack('<d', struct.pack('<Q', int))[0]
struct.error: integer out of range for 'Q' format code
```

**Comment by Sirhyro** [comment]
Same issue here as well. 
No modifications to source made, just straight out of the box with only a setup config.json.

My config:
```
{
    "auth_service": "ptc",
    "username": "xxx",
    "password": "xxx",
    "location": "40.783003,-73.965902",
    "gmapkey": "xxx",
    "max_steps": 5,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "101,102,103,104",
    "evolve_all": "NONE"
}
```

**Comment by mushi8** [comment]
ideas? it worked for me a second ago

**Comment by jring314** [comment]
Same error for me. Was working 30 minutes ago, I changed the location in the config.json file, and bam, now it's not working. I went and changed the loc again, still not working.

[2016-07-26 15:14:29] [x] Initial Transfer.
[2016-07-26 15:14:29] [x] Preparing to transfer all duplicate Pokemon, keeping the highest CP of each type.
[2016-07-26 15:14:29] [x] Will NOT transfer anything above CP 400
[2016-07-26 15:14:29] [x] Transferring Done.
[2016-07-26 15:14:29] [#]
[2016-07-26 15:14:29] [x] Starting PokemonGo Bot....
[2016-07-26 15:14:29] [#] Scanning area for objects (1 / 25)
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "C:\Users\jring_000\Downloads\Pokemon\PokemonGo-Bot-master\PokemonGo-Bot-master\pokemongo_bot\__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "C:\Users\jring_000\Downloads\Pokemon\PokemonGo-Bot-master\PokemonGo-Bot-master\pokemongo_bot\stepper.py", line 53, in take_step
    self._walk_to(self.config.walk, *position)
  File "C:\Users\jring_000\Downloads\Pokemon\PokemonGo-Bot-master\PokemonGo-Bot-master\pokemongo_bot\stepper.py", line 67, in _walk_to
    i2f(self.api._position_lat), i2f(self.api._position_lng), lat, lng)
  File "C:\Users\jring_000\Downloads\Pokemon\PokemonGo-Bot-master\PokemonGo-Bot-master\pokemongo_bot\cell_workers\utils.py", line 98, in i2f
    return struct.unpack('<d', struct.pack('<Q', int))[0]
struct.error: integer out of range for 'Q' format code

**Comment by roytz** [comment]
same here...
![image](https://cloud.githubusercontent.com/assets/16700423/17154371/a131fbac-5335-11e6-8068-256db9c6e5cc.png)

**Comment by mushi8** [comment]
Ok so its working on my ubuntu but failes in my win 10...

**Comment by chadsaun** [comment]
In mine, the "int" parameter being passed in is actualy a float.

**Comment by etamity** [comment]
I have same error, it was working fine couple hours ago, is it new bug?

**Comment by Sirhyro** [comment]
The history shows that the last update was 19 hours ago and that was only to the readme, so it seems that people who it was working with earlier today and now it's not.. Maybe the server was updated and is responding with a different value than the script expects?

**Comment by kriswong** [comment]
Can we confirm that #1046 solves? I cannot seem to implement it

**Comment by gaz492** [comment]
The latest dev branch works for me now havent tried the master

**Comment by surfaace** [comment]
Commit has been reverted, please repull. #1065
