### ISSUE TITLE
struct.error: integer out of range for 'Q' format code

### ISSUE THREAD

**Issue by Jenishpoke** [PokemonGoF/PokemonGo-Bot#1042]
### Expected Behavior
Bot starts running.

### Actual Behavior
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "C:\Users\USER\Desktop\PokemonGO\PoGo Bot\PokemonGo-Bot\pokemongo_bot\__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "C:\Users\USER\Desktop\PokemonGO\PoGo Bot\PokemonGo-Bot\pokemongo_bot\stepper.py", line 53, in take_step
    self._walk_to(self.config.walk, *position)
  File "C:\Users\USER\Desktop\PokemonGO\PoGo Bot\PokemonGo-Bot\pokemongo_bot\stepper.py", line 67, in _walk_to
    i2f(self.api._position_lat), i2f(self.api._position_lng), lat, lng)
  File "C:\Users\USER\Desktop\PokemonGO\PoGo Bot\PokemonGo-Bot\pokemongo_bot\cell_workers\utils.py", line 98, in i2f
    return struct.unpack('<d', struct.pack('<Q', int))[0]
struct.error: integer out of range for 'Q' format code

### Steps to Reproduce
C:\Python27\python pokecli.py -cf config

### Other Information
OS: Windows 10
Git Commit: 3aca6d798f8a3e173dce0beb7b13c9505cc5b251

**Comment by Jenishpoke** [comment]
My bad this is the same issue as #1401

**Comment by kriswong** [comment]
I'm having the same issue and cannot find #1401

**Comment by 4thelols** [comment]
bump

**Comment by kriswong** [comment]
Doing this as a fix cause other issues and causes the 1 hour death of the bot.

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
