### ISSUE TITLE
BUG DEV crash looting pokestop "ItemFilter"

### ISSUE THREAD

**Issue by leouzz** [PokemonGoF/PokemonGo-Bot#1078]
[01:27:27] Loot: 
[01:27:27] 50 xp
[01:27:27] - 2x Pokeball (Total: 96)
Traceback (most recent call last):
  File "pokecli.py", line 239, in <module>
    main()
  File "pokecli.py", line 230, in main
    bot.take_step()
  File "/path/PokemonGo-Bot/pokemongo_bot/__init__.py", line 43, in take_step
    self.process_cells(work_on_forts=True)
  File "/path/PokemonGo-Bot/pokemongo_bot/__init__.py", line 49, in process_cells
    self.work_on_cell(cell, location, work_on_forts)
  File "/path/PokemonGo-Bot/pokemongo_bot/__init__.py", line 225, in work_on_cell
    hack_chain = worker.work()
  File "/path/PokemonGo-Bot/pokemongo_bot/cell_workers/seen_fort_worker.py", line 76, in work
    id_filter = self.config.item_filter.get(str(item_id), 0)
AttributeError: 'Namespace' object has no attribute 'item_filter'
 
Then Crash

### Other Information
OS: Linux
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
f427bab226e61a535348acdcec0c1ad5e2f2ccc7

**Comment by Zgrkaralar** [comment]
Also i have same problem
<img width="804" alt="screen shot 2016-07-27 at 2 39 26 am" src="https://cloud.githubusercontent.com/assets/879674/17159090/62df7244-53a3-11e6-8b34-ec68b335c3e7.png">

**Comment by Kassadd** [comment]
Os: Windows 10
Commit: 2a75ad252c627755fa5759ce4a7b663075526f16

**Comment by Drambuie** [comment]
[00:39:01] Loot: 
[00:39:01] 50 xp
[00:39:01] - 2x Pokeball (Total: 180)
Traceback (most recent call last):
  File "pokecli.py", line 256, in <module>
    main()
  File "pokecli.py", line 242, in main
    bot.take_step()
  File "/home/rbrittain/PokemonGo-Bot/pokemongo_bot/__init__.py", line 43, in take_step
    self.process_cells(work_on_forts=True)
  File "/home/rbrittain/PokemonGo-Bot/pokemongo_bot/__init__.py", line 49, in process_cells
    self.work_on_cell(cell, location, work_on_forts)
  File "/home/rbrittain/PokemonGo-Bot/pokemongo_bot/__init__.py", line 225, in work_on_cell
    hack_chain = worker.work()
  File "/home/rbrittain/PokemonGo-Bot/pokemongo_bot/cell_workers/seen_fort_worker.py", line 76, in work
    id_filter = self.config.item_filter.get(str(item_id), 0)
AttributeError: 'Namespace' object has no attribute 'item_filter'


OS : Ubuntu

**Comment by J102030** [comment]
Same for me. Could it have to do with trying to recycle items when player already has more than specified in config?

I thought commit f030431 was supposed to handle it?

**Comment by koppa** [comment]
Because of commit f030431546b89cd2c6f3a22dc80555484067a044.

Need to load item_filter from config file

    if 'item_filter' in load:
        config.item_filter = load['item_filter']
    else:
        config.item_filter = {}

**Comment by surfaace** [comment]
thanks @koppa, added missing load code in 07e028292881677c06e1ded51e021d1a8cc9e68f

**Comment by Zgrkaralar** [comment]
@koppa i have this
`"item_filter": {
      "1": { "keep" : 100 },
      "101": { "keep" : 10 },
      "102": { "keep" : 30 },
      "103": { "keep" : 30 },
      "201": { "keep" : 30 },
      "701": { "keep" : 100 }
    },`

**Comment by tzull** [comment]
@surfaace at 07e0282 still got same error
![image](https://cloud.githubusercontent.com/assets/20562271/17160726/69f99a18-53d1-11e6-96a4-ef98616f353f.png)
