### ISSUE TITLE
No config argument specified, checking for /configs/config.json

### ISSUE THREAD

**Issue by tzull** [PokemonGoF/PokemonGo-Bot#1084]
Already configure config.json as another dev
OS: Windows 7
dev branch : 07e0282
Log :

[07:06:01] No config argument specified, checking for /configs/config.json
Traceback (most recent call last):
  File "C:\Python\PokeBot\dev006\pokecli.py", line 256, in <module>
    main()
  File "C:\Python\PokeBot\dev006\pokecli.py", line 227, in main
    config = init_config()
  File "C:\Python\PokeBot\dev006\pokecli.py", line 63, in init_config
    load.update(json.load(data))
  File "C:\Python\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 3 column 47 (char 78)

**Comment by TheGoldenXY** [comment]
@tzull What is the full command you're trying to run?

**Comment by tzull** [comment]
@TheGoldenXY like usualy pokecli.py or pokecli.py -cf /configs/configs

**Comment by RiberoD07** [comment]
@tzull on windows? do pokecli.py -cf .\configs\config.json the error message seems to say you're not using -cf or --config tho but try it out anyways. Seems like it's two errors, the other is that it's Expecting , delimiter: line 3 column 47 (char 78). means it's expecting a comma around line 3. check the end of line 3 might need to put a comma.

**Comment by tzull** [comment]
@RiberoD07 thanks for your info, after recheck i have illegal character at username field. And now working normally.

Thanks all.
