### ISSUE TITLE
How to install newest lure version AttributeError: 'PokemonGoBot' object has no attribute 'navigator'

### ISSUE THREAD

**Issue by OVO647** [PokemonGoF/PokemonGo-Bot#1085]
The Bot seems to run fine but then runs into this problem

Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "/Users/User/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/Users/User/Desktop/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/Users/User/Desktop/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/Users/User/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 92, in work_on_cell
    worker = MoveToFortWorker(fort, self)
  File "/Users/User/Desktop/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 11, in __init__
    self.navigator = bot.navigator
AttributeError: 'PokemonGoBot' object has no attribute 'navigator'

**Comment by TheGoldenXY** [comment]
When you say that the bot runs fine, can you please be more specific? For how long has the bot been working until you received this error?

I would also appreciate it if you ran this command: `git log -n 1 --pretty=format:"%H"`. This will help me identify your issue.

**Comment by OVO647** [comment]
Only works for about a minute.

**Comment by OVO647** [comment]
git log -n 1 --pretty=format:"%H"
fatal: Not a git repository (or any of the parent directories): .git
