### ISSUE TITLE
Crashing on every Pokestop Spin

### ISSUE THREAD

**Issue by Saik19922** [PokemonGoF/PokemonGo-Bot#1089]
### Expected Behavior
Listing items that the spin gave

### Actual Behavior
Crashing instantly

### Steps to Reproduce
Just let it spin any stop

### Other Information
OS: Win10
Git Commit: 9d2535001b92772c6b797183b1cf4df768806af3

Heres what it states

Traceback (most recent call last):
  File "C:\PBot\PokemonGo-Bot\pokecli.py", line 261, in <module>
    main()
  File "C:\PBot\PokemonGo-Bot\pokecli.py", line 247, in main
    bot.take_step()
  File "C:\PBot\PokemonGo-Bot\pokemongo_bot\__init__.py", line 43, in take_step
    self.process_cells(work_on_forts=True)
  File "C:\PBot\PokemonGo-Bot\pokemongo_bot\__init__.py", line 49, in process_cells
    self.work_on_cell(cell, location, work_on_forts)
  File "C:\PBot\PokemonGo-Bot\pokemongo_bot\__init__.py", line 225, in work_on_cell
    hack_chain = worker.work()
  File "C:\PBot\PokemonGo-Bot\pokemongo_bot\cell_workers\seen_fort_worker.py", line 76, in work
    id_filter = self.config.item_filter.get(str(item_id), 0)
AttributeError: 'unicode' object has no attribute 'get'

**Comment by shaosh** [comment]
Same issue here

**Comment by Jie211** [comment]
Same issue

**Comment by Snorbitz** [comment]
Same Issue

Win 10

**Comment by ayiire** [comment]
I have the same issue too. My pokemon encounter also repeats.

[21:04:43] A Wild Growlithe appeared! [CP 93] [Potential 0.64]
[21:04:43] IV [Stamina/Attack/Defense] = [8/15/6]
[21:04:47] A Wild Growlithe appeared! [CP 93] [Potential 0.64]
[21:04:47] IV [Stamina/Attack/Defense] = [8/15/6]
[====================                    ] 50%[21:04:54] Something rustles nearby!
[21:04:54] A Wild Growlithe appeared! [CP 93] [Potential 0.64]
[21:04:54] IV [Stamina/Attack/Defense] = [8/15/6]
[21:04:58] A Wild Growlithe appeared! [CP 93] [Potential 0.64]
[21:04:58] IV [Stamina/Attack/Defense] = [8/15/6]
[=====================                   ] 53%[21:05:04] Something rustles nearby!
[21:05:04] A Wild Growlithe appeared! [CP 93] [Potential 0.64]
[21:05:04] IV [Stamina/Attack/Defense] = [8/15/6]
[21:05:06] A Wild Growlithe appeared! [CP 93] [Potential 0.64]
[21:05:06] IV [Stamina/Attack/Defense] = [8/15/6]
[======================                  ] 55%[21:05:14] Something rustles nearby!
[21:05:14] A Wild Growlithe appeared! [CP 93] [Potential 0.64]
[21:05:14] IV [Stamina/Attack/Defense] = [8/15/6]
[21:05:18] A Wild Growlithe appeared! [CP 93] [Potential 0.64]
[21:05:18] IV [Stamina/Attack/Defense] = [8/15/6]
[======================                  ] 57%Traceback (most recent call last):
  File "H:\pgbot\pokecli.py", line 261, in <module>
    main()
  File "H:\pgbot\pokecli.py", line 247, in main
    bot.take_step()
  File "H:\pgbot\pokemongo_bot\__init__.py", line 43, in take_step
    self.process_cells(work_on_forts=True)
  File "H:\pgbot\pokemongo_bot\__init__.py", line 49, in process_cells
    self.work_on_cell(cell, location, work_on_forts)
  File "H:\pgbot\pokemongo_bot\__init__.py", line 222, in work_on_cell
    worker.work()
  File "H:\pgbot\pokemongo_bot\cell_workers\move_to_fort_worker.py", line 45, in work
    self.bot.process_cells(work_on_forts=False)
  File "H:\pgbot\pokemongo_bot\__init__.py", line 47, in process_cells
    cells = self.find_close_cells(*location)
  File "H:\pgbot\pokemongo_bot\__init__.py", line 121, in find_close_cells
    status = map_objects.get('status', None)
AttributeError: 'str' object has no attribute 'get'

**Comment by Code-Slave** [comment]
update config worked for me. specifically adding item filter

    "distance_unit": "km",
   "item_filter": {
      "1": { "keep" : 100 },
      "101": { "keep" : 10 },
      "102": { "keep" : 30 },
      "103": { "keep" : 30 },
      "201": { "keep" : 30 },
      "701": { "keep" : 100 }
    },
    "evolve_all": "true",
    "use_lucky_egg": false,

**Comment by ariefbayu** [comment]
I can confirm as @Code-Slave stated, seems to be running well by patching config.

**Comment by AndyBean** [comment]
Updating the config as @Code-Slave mentions worked just fine.
