### ISSUE TITLE
struct.error: integer out of range for 'Q' format code in pokemongo_bot/cell_workers/utils.py

### ISSUE THREAD

**Issue by bigdrizzle13** [PokemonGoF/PokemonGo-Bot#1094]
[2016-07-26 18:10:24] [x] Coordinates found in passed in location, not geocoding.
[2016-07-26 18:10:24] 
[2016-07-26 18:10:24] [x] Address found: 37.322149,-122.002152
[2016-07-26 18:10:24] [x] Position in-game set as: (37.322149, -122.002152, 0.0)
[2016-07-26 18:10:24] 
...
[2016-07-26 18:10:26] [x] Starting PokemonGo Bot....
[2016-07-26 18:10:26] [#] Scanning area for objects (1 / 25)
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "/Users/.../Downloads/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/Users/.../Downloads/PokemonGo-Bot/pokemongo_bot/stepper.py", line 53, in take_step
    self._walk_to(self.config.walk, *position)
  File "/Users/.../Downloads/PokemonGo-Bot/pokemongo_bot/stepper.py", line 67, in _walk_to
    i2f(self.api._position_lat), i2f(self.api._position_lng), lat, lng)
  File "/Users/.../Downloads/PokemonGo-Bot/pokemongo_bot/cell_workers/utils.py", line 98, in i2f
    return struct.unpack('<d', struct.pack('<Q', int))[0]
struct.error: integer out of range for 'Q' format code

Removed some stuff to stay anonymous, but anyone know whats happening here?

**Comment by bigdrizzle13** [comment]
{
    "location": "37.322149,-122.002152",
    "max_steps": 5,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "101,102,103,104",
    "evolve_all": "NONE"
}

**Comment by TheGoldenXY** [comment]
Please run this command: `git log -n 1 --pretty=format:"%H"` and tell me your result.

**Comment by bigdrizzle13** [comment]
893483778366075aa9f3b80e090b448088439b93

**Comment by PokemonGoSucks** [comment]
The problem is i2f function takes unsigned long long and tries to convert it to double. unsigned long long range is >0. Your longitudinal cordinate is -122

**Comment by bigdrizzle13** [comment]
Is there another format that I'm not familiar with:

37.322393, -122.001461

Thats my location according to google maps.

**Comment by PokemonGoSucks** [comment]
stepper.py needs to be modified:

```
dist = distance(
i2f(self.api._position_lat), i2f(self.api._position_lng), lat, lng)
```

**Comment by bigdrizzle13** [comment]
How am I the first person to run into this? It seems that a many many using this would have a negative long cord.

**Comment by CadeBrown** [comment]
You need to update your requirements.txt

**Comment by PokemonGoSucks** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/1042

**Comment by kriswong** [comment]
in the main fold type:
type `git pull`
Then when that has completed, 
type `pip install --upgrade -r requirements.txt`

This will resolve your issues.

**Comment by TheGoldenXY** [comment]
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/1042

**Comment by naisho** [comment]
updating pgo api to 1.1.0 fixed this for me. thanks

**Comment by TheGoldenXY** [comment]
Since this is a duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/1042 I'm closing this.

/closed
