### ISSUE TITLE
google login issue

### ISSUE THREAD

**Issue by tq01m4m** [PokemonGoF/PokemonGo-Bot#1106]
### Expected Behavior
I check out dev branch.It works well in pic account.But it does not work in google account.

### Actual Behavior
[10:01:33] PokemonGO Bot v1.0
[10:01:33] No config argument specified, checking for /configs/config.json
[10:01:33] Configuration initialized
[10:01:33] [x] Coordinates found in passed in location, not geocoding.
[10:01:33] 
[10:01:33] Location Found: 37.795739,-122.426599
[10:01:33] GeoPosition: (37.795739, -122.426599, 0)
[10:01:33] 
[10:01:33] Attempting login to Pokemon Go.
Traceback (most recent call last):
  File "pokecli.py", line 261, in <module>
    main()
  File "pokecli.py", line 242, in main
    bot.start()
  File "/Users/kelingqiu/Desktop/PokemonGo-Bot-dev/pokemongo_bot/__init__.py", line 37, in start
    self._setup_api()
  File "/Users/kelingqiu/Desktop/PokemonGo-Bot-dev/pokemongo_bot/__init__.py", line 284, in _setup_api
    self.login()
  File "/Users/kelingqiu/Desktop/PokemonGo-Bot-dev/pokemongo_bot/__init__.py", line 269, in login
    str(self.config.password)):
  File "/Users/kelingqiu/Desktop/PokemonGo-Bot-dev/src/pgoapi/pgoapi/pgoapi.py", line 144, in login
    if not self._auth_provider.login(username, password):
  File "/Users/kelingqiu/Desktop/PokemonGo-Bot-dev/src/pgoapi/pgoapi/auth_google.py", line 47, in login
    login = perform_master_login(username, password, self.GOOGLE_LOGIN_ANDROID_ID)
  File "/Users/kelingqiu/Desktop/PokemonGo-Bot-dev/lib/python2.7/site-packages/gpsoauth/__init__.py", line 66, in perform_master_login
    return _perform_auth_request(data)
  File "/Users/kelingqiu/Desktop/PokemonGo-Bot-dev/lib/python2.7/site-packages/gpsoauth/__init__.py", line 22, in _perform_auth_request
    headers={'User-Agent': useragent})
  File "/Users/kelingqiu/Desktop/PokemonGo-Bot-dev/lib/python2.7/site-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/kelingqiu/Desktop/PokemonGo-Bot-dev/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/kelingqiu/Desktop/PokemonGo-Bot-dev/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/kelingqiu/Desktop/PokemonGo-Bot-dev/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/Users/kelingqiu/Desktop/PokemonGo-Bot-dev/lib/python2.7/site-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='android.clients.google.com', port=443): Max retries exceeded with url: /auth (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x106d39150>: Failed to establish a new connection: [Errno 60] Operation timed out',))

### Other Information
OS: OSX 10.11.3
Git Commit: db5b719dba2faebf9401b929811d0308e2561317

**Comment by TheGoldenXY** [comment]
Version check. Please run `git log -n 1 --pretty=format:"%H"` and reply here.

**Comment by tq01m4m** [comment]
db5b719dba2faebf9401b929811d0308e2561317
