### ISSUE TITLE
[master][bug] pgoapi.exceptions.NotLoggedInException

### ISSUE THREAD

**Issue by Hatsunyan** [PokemonGoF/PokemonGo-Bot#1116]
### Actual Behavior
```
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "C:\PokemonGo-Bot\pokemongo_bot\__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "C:\PokemonGo-Bot\pokemongo_bot\stepper.py", line 53, in take_step
    self._walk_to(self.config.walk, *position)
  File "C:\PokemonGo-Bot\pokemongo_bot\stepper.py", line 88, in _walk_to
    alt, False)
  File "C:\PokemonGo-Bot\pokemongo_bot\stepper.py", line 102, in _work_at_position
    response_dict = self.api.call()
  File "c:\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 81, in call
    response = request.request(api_endpoint, self._req_method_list, player_position)
  File "c:\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 98, in request
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
```
### Steps to Reproduce
after 1-2 hours working

### Other Information
OS: WIN10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by globeriz** [comment]
Proposed fix in #1114,
cause is unknown at the moment, maybe the server is unstable or to prevent addiction
