### ISSUE TITLE
Looping "Something rustles nearby!" no Pokemon appear

### ISSUE THREAD

**Issue by kaoztheory** [PokemonGoF/PokemonGo-Bot#1122]
### Expected Behavior
Pokemon should appear after Something rustles nearby!

### Actual Behavior

[2016-07-27 00:22:36] [#] Something rustles nearby!
[2016-07-27 00:23:08] [#] Something rustles nearby!
[2016-07-27 00:23:41] [#] Something rustles nearby!
[2016-07-27 00:24:23] [#] Something rustles nearby!
[2016-07-27 00:25:05] [#] Something rustles nearby!
[2016-07-27 00:25:48] [#] Something rustles nearby!
[2016-07-27 00:26:19] [#] Something rustles nearby!
[2016-07-27 00:26:43] [#] Something rustles nearby!
[2016-07-27 00:27:04] [#] Something rustles nearby!
[2016-07-27 00:27:27] [#] Something rustles nearby!
[2016-07-27 00:27:48] [#] Something rustles nearby!
[2016-07-27 00:28:09] [#] Something rustles nearby!
[2016-07-27 00:28:22] [#] Something rustles nearby!

### Steps to Reproduce

Using master build

### Other Information
OS: Windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

Note spins working fine.

**Comment by bradhuffman** [comment]
Same.

**Comment by CadeBrown** [comment]
Try recopying the example config, and only change the username, password, and apikey
Leave all the pokemon stuff alone.

**Comment by kaoztheory** [comment]
Trying sec

**Comment by bradhuffman** [comment]
I did have to modify 
`def i2f(int):
    return struct.unpack('<d', struct.pack('<Q', int))[0]`

to 
`def i2f(int):
    return struct.unpack('<d', struct.pack('<d', int))[0]`

in utils.py to get bot to run.

**Comment by kaoztheory** [comment]
same

**Comment by CadeBrown** [comment]
Then you guys  should upgrade to the latest version

**Comment by bradhuffman** [comment]
Also, 
`spawnpoint_id = self.pokemon['spawnpoint_id']`
to
`spawnpoint_id = self.pokemon['spawn_point_id']`
in pokemon_catch_worker.py

**Comment by kaoztheory** [comment]
Dev version?? Copied new config didn't work either

**Comment by CadeBrown** [comment]
The dev branch

**Comment by bradhuffman** [comment]
Dev branch kept flaking on the location I tried to give it.  Any secrets there?

**Comment by kaoztheory** [comment]
Same

**Comment by bradhuffman** [comment]
`[23:39:42] PokemonGO Bot v1.0
[23:39:42] No config argument specified, checking for /configs/config.json
[23:39:42] Configuration initialized
[23:39:43] 
[23:39:43] Location Found: 30.5508,-89.0110
[23:39:43] [x] The location given using -l could not be parsed. Checking for a cached location.
[23:39:43] [x] Parsing cached location...
No cached Location. Please specify initial location.`

**Comment by bradhuffman** [comment]
Any ideas?

**Comment by krypttr** [comment]
Same problem on dev branch

**Comment by TheHaliax** [comment]
try doing this
before:            self.api.encounter(encounter_id=encounter_id, spawn_point_id=spawnpoint_id,
                               player_latitude=player_latitude, player_longitude=player_longitude)
after:            self.api.encounter(encounter_id=encounter_id, spawnpoint_id=spawnpoint_id,
                               player_latitude=player_latitude, player_longitude=player_longitude)
it brings up an error when trying to catch but it actually tries to catch instead of just rustling.
error is as follows
[2016-07-27 04:56:15] [#] Something rustles nearby!
[2016-07-27 04:56:15] A Wild Kingler appeared! [CP 129] [Potential 0.8]
[2016-07-27 04:56:15] IV [Stamina/Attack/Defense] = [14/7/15]
Traceback (most recent call last):
  File "./pokecli.py", line 220, in <module>
    main()
  File "./pokecli.py", line 211, in main
    bot.take_step()
  File "/home/ubuntu/workspace/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/home/ubuntu/workspace/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/home/ubuntu/workspace/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/home/ubuntu/workspace/pokemongo_bot/__init__.py", line 63, in work_on_cell
    if self.catch_pokemon(pokemon) == PokemonCatchWorker.NO_POKEBALLS:
  File "/home/ubuntu/workspace/pokemongo_bot/__init__.py", line 190, in catch_pokemon
    return_value = worker.work()
  File "/home/ubuntu/workspace/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 98, in work
    if not self.should_capture_pokemon(pokemon_name, cp, pokemon_potential, response_dict):
  File "/home/ubuntu/workspace/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 292, in should_capture_pokemon
    catch_config = self._get_catch_config_for(pokemon_name)
  File "/home/ubuntu/workspace/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 333, in _get_catch_config_for
    catch_config = self.config.catch.get(pokemon)
AttributeError: 'Namespace' object has no attribute 'catch'

**Comment by kaoztheory** [comment]
likely has to do with the spawnpoint issue?

**Comment by bradhuffman** [comment]
Seems to be some inconsistencies in the naming.

**Comment by VictorChen** [comment]
looks like this commit broke it: https://github.com/PokemonGoF/PokemonGo-Bot/commit/6a2833322ae77daf7ac3d3f3aa5c621b2543e8aa

**Comment by TheHaliax** [comment]
sorry i'm not really good with github but my above change and doing this https://github.com/PokemonGoF/PokemonGo-Bot/issues/1121

returns this
[2016-07-27 05:23:25] [#] Something rustles nearby!
Traceback (most recent call last):
  File "./pokecli.py", line 220, in <module>
    main()
  File "./pokecli.py", line 211, in main
    bot.take_step()
  File "/home/ubuntu/workspace/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/home/ubuntu/workspace/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/home/ubuntu/workspace/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/home/ubuntu/workspace/pokemongo_bot/__init__.py", line 63, in work_on_cell
    if self.catch_pokemon(pokemon) == PokemonCatchWorker.NO_POKEBALLS:
  File "/home/ubuntu/workspace/pokemongo_bot/__init__.py", line 190, in catch_pokemon
    return_value = worker.work()
  File "/home/ubuntu/workspace/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 31, in work
    response_dict = self.create_encounter_api_call()
AttributeError: 'PokemonCatchWorker' object has no attribute 'create_encounter_api_call'

**Comment by kaoztheory** [comment]
reinstall of latest dev fixed it guys...FYI

**Comment by VictorChen** [comment]
@kaoztheory still does not work

**Comment by bradhuffman** [comment]
Master appears to be working for me now.  Did a git pull, then pip install
-r requirements.txt

**Comment by VietAnhh** [comment]
Yeah dev isn't working still. Master is though

**Comment by aTadTasty** [comment]
this is the latest dev i can get working as of right now. https://github.com/PokemonGoF/PokemonGo-Bot/commit/db5b719dba2faebf9401b929811d0308e2561317

and no 1.1 will not work with the latest dev.

**Comment by VictorChen** [comment]
this is now fixed: https://github.com/PokemonGoF/PokemonGo-Bot/pull/1137

**Comment by TheSavior** [comment]
Should be fixed in https://github.com/PokemonGoF/PokemonGo-Bot/commit/72b1218962291e5d487df3e55de3bfa4b28ec4cf

**Comment by surfaace** [comment]
Should be fixed in 72b1218
