### ISSUE TITLE
minimum maxsteps

### ISSUE THREAD

**Issue by skydrome** [PokemonGoF/PokemonGo-Bot#113]
when setting maxsteps to 1 i get
looping: step 1 of 1
`looping: step 1 of 1
steplimit: 1 x: 1 y: 0 pos: 1 dx: 1 dy 0
Traceback (most recent call last):
  File "pokecli.py", line 107, in <module>
    main()
  File "pokecli.py", line 104, in main
    bot.take_step()
  File "/home/chris/Desktop/PokemonGo-Bot/bot.py", line 28, in take_step
    self.stepper.take_step()
  File "/home/chris/Desktop/PokemonGo-Bot/stepper.py", line 46, in take_step
    cellid = self._get_cellid(position[0], position[1])
UnboundLocalError: local variable 'position' referenced before assignment`

**Comment by PokemonGoF** [comment]
let me check it.

**Comment by PokemonGoF** [comment]
should be fixed.
