### ISSUE TITLE
RuntimeError: Pokemon Bag is full!

### ISSUE THREAD

**Issue by HBSpy** [PokemonGoF/PokemonGo-Bot#1147]
### Expected Behavior
Change mode when Pokemon Bag is full!
Perhaps it will add a new Mode: walk only, when both Bag and Inventory are full.
I use it to hatch egg

### Actual Behavior
RuntimeError: Pokemon Bag is full!

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by Zgrkaralar** [comment]
When bag and Invertory are full bot is stopped about that clean your pokemon bag 

You can use **initial_transfer** set on config.json

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

If the problem persists, open a new issue.

/closed

**Comment by ShapeShifter499** [comment]
@TheGoldenXY  and @Zgrkaralar I'm seeing this error and changing "initial_transfer" to true isn't working.  

```
[22:41:24] Attempting login to Pokemon Go.
[22:41:25] Login to Pokemon Go successful.
[22:41:25] 
[22:41:25] --- ShapeShifter499 ---
[22:41:25] Level: 20 (Next Level: 42085 XP) (Total: 217915 XP)
[22:41:25] Pokemon Captured: 766 | Pokestops Visited: 749
[22:41:25] Pokemon Bag: 450/450
[22:41:25] Items: 419/450
[22:41:25] Stardust: 16169 | Pokecoins: 30
[22:41:25] PokeBalls: 100 | GreatBalls: 209 | UltraBalls: 4
[22:41:25] RazzBerries: 2 | BlukBerries: 0 | NanabBerries: 0
[22:41:25] LuckyEgg: 0 | Incubator: 1 | TroyDisk: 1
[22:41:25] Potion: 10 | SuperPotion: 30 | HyperPotion: 30
[22:41:25] Incense: 0 | IncenseSpicy: 0 | IncenseCool: 0
[22:41:25] Revive: 30 | MaxRevive: 0
[22:41:25] 
[22:41:25] 
[22:41:26] Starting PokemonGo Bot....
[22:41:27] Something rustles nearby!
Traceback (most recent call last):
  File "pokecli.py", line 281, in <module>
    main()
  File "pokecli.py", line 247, in main
    bot.take_step()
  File "/home/raansu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 47, in take_step
    self.process_cells()
  File "/home/raansu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 67, in process_cells
    "catchable_pokemons": catchable_pokemons}, location)
  File "/home/raansu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 174, in work_on_cell
    if worker.work() == WorkerResult.RUNNING:
  File "/home/raansu/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokmeon_worker.py", line 39, in work
    return self.catch_pokemon(self.cell['catchable_pokemons'][0])
  File "/home/raansu/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokmeon_worker.py", line 51, in catch_pokemon
    return_value = worker.work()
  File "/home/raansu/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 43, in work
    raise RuntimeError('Pokemon Bag is full!')
RuntimeError: Pokemon Bag is full!
```

**Other Information**

OS: Arch Linux 64bit
Git Commit: d9085fbf502b27601573bb7935a36647a9673f6f

**Comment by ShapeShifter499** [comment]
"release_pokemon"  set to true seems be a workaround assuming you have release configurations set up or are using the default "config.json.pokemons.example" release and catch parameters.

**Comment by AlexBailey** [comment]
@ShapeShifter499 That's not a work around for me, experiencing this same issue. Have followed @TheGoldenXY steps and still experience the issue.
