### ISSUE TITLE
After re-logging crash

### ISSUE THREAD

**Issue by matrix14** [PokemonGoF/PokemonGo-Bot#1152]
### Expected Behavior
Bot should still working...

### Actual Behavior
Bot crashes...

```
[10:15:07] Something rustles nearby!
[10:15:07] A Wild Weedle appeared! [CP 67] [Potential 0.38]
[10:15:07] IV [Stamina/Attack/Defense] = [12/2/3]
[10:15:11] Using Pokeball (chance: 57.27%)... (65 left!)
[10:15:12] Captured Weedle! [CP 67] [12/2/3]
[10:15:22] Session stale, re-logging in
[10:15:22] Attempting login to Pokemon Go.
[10:15:23] Login to Pokemon Go successful.
[10:15:23] Scanning area for objects....
[10:15:23] Walking from (52.410534999999996, 16.935286) to (52.410534999999996, 16.935286) 0.00m
Traceback (most recent call last):
  File "pokecli.py", line 236, in <module>
    main()
  File "pokecli.py", line 227, in main
    bot.take_step()
  File "/home/PokemonGo-Bot/pokemongo_bot/__init__.py", line 37, in take_step
    cells = self.find_close_cells(*location)
  File "/home/PokemonGo-Bot/pokemongo_bot/__init__.py", line 119, in find_close_cells
    self.update_web_location(map_cells,lat,lng)
  File "/home/PokemonGo-Bot/pokemongo_bot/__init__.py", line 49, in update_web_location
    alt = self.position[2]
IndexError: tuple index out of range
```

### Steps to Reproduce
Run bot and wait to 
```
Session stale, re-logging in
[10:15:22] Attempting login to Pokemon Go.
[10:15:23] Login to Pokemon Go successful.
```
Bot will scan to find nearby pokemons or forts and it want to move to place where actually it is.
`Walking from (52.410534999999996, 16.935286) to (52.410534999999996, 16.935286) 0.00m
`
### Other Information
OS: Debian GNU/Linux 8.2
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
3b970f14e3386177c4a611caf7c165e2d8a94ba7

**Comment by tstumm** [comment]
Please update to the latest version. This bug is already fixed.
