### ISSUE TITLE
KeyError: 'player_data'

### ISSUE THREAD

**Issue by dragonalvaro** [PokemonGoF/PokemonGo-Bot#1154]
### Expected Behavior
bot doesn't works. Error after login

### Actual Behavior
crash 

### Steps to Reproduce
```
[10:25:38] PokemonGO Bot v1.0
[10:25:38] No config argument specified, checking for /configs/config.json
[10:25:38] Configuration initialized
[10:25:38] [x] Coordinates found in passed in location, not geocoding.
[10:25:38] 
[10:25:38] Location Found: 40.417119, -3.682773
[10:25:38] GeoPosition: (40.417119, -3.682773, 0)
[10:25:38] 
[10:25:38] Attempting login to Pokemon Go.
[10:25:39] Login to Pokemon Go successful.
Traceback (most recent call last):
  File "pokecli.py", line 283, in <module>
    main()
  File "pokecli.py", line 243, in main
    bot.start()
  File "/home/alvaro/Pokemon/PokemonGo-Bot.git/pokemongo_bot/__init__.py", line 40, in start
    self._setup_api()
  File "/home/alvaro/Pokemon/PokemonGo-Bot.git/pokemongo_bot/__init__.py", line 248, in _setup_api
    self._print_character_info()
  File "/home/alvaro/Pokemon/PokemonGo-Bot.git/pokemongo_bot/__init__.py", line 264, in _print_character_info
    player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'player_data'
```

### Other Information
OS: UBUNTU
Git Commit: 519f77abd72f5ee8204da368947de2db229e85d9

**Comment by Zgrkaralar** [comment]
Is this new registered  ?

**Comment by dragonalvaro** [comment]
Nope, level 13 using this bot. Works in mobile without problem. Suddenly it stops working

**Comment by Zgrkaralar** [comment]
re-install bot and don't forgot **pip install -r requirements.txt**

**Comment by dragonalvaro** [comment]
Seems to work again now. Thanks. Don't know what happend.
