### ISSUE TITLE
Error when in walking or something

### ISSUE THREAD

**Issue by simonsmh** [PokemonGoF/PokemonGo-Bot#1157]
### Expected Behavior
run

### Actual Behavior
Traceback (most recent call last):                 File "pokecli.py", line 220, in <module>           main()                                         File "pokecli.py", line 211, in main               bot.take_step()                                File "/storage/emulated/0/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step           self.stepper.take_step()                       File "/storage/emulated/0/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step            self._work_at_position(position[0], position[1], position[2], True)                             File "/storage/emulated/0/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position                                                    self.bot.work_on_cell(cell, position, pokemon_only)                                             File "/storage/emulated/0/PokemonGo-Bot/pokemongo_bot/__init__.py", line 93, in work_on_cell        worker.work()
  File "/storage/emulated/0/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 30, in work                                         self.stepper._walk_to(self.config.walk, *position)                                              File "/storage/emulated/0/PokemonGo-Bot/pokemongo_bot/stepper.py", line 84, in _walk_to             self.bot.heartbeat()                           File "/storage/emulated/0/PokemonGo-Bot/pokemongo_bot/__init__.py", line 395, in heartbeat          self.api.call()                                File "/storage/emulated/0/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 81, in call              response = request.request(api_endpoint, self._req_method_list, player_position)                File "/storage/emulated/0/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 100, in request         raise NotLoggedInException()                 pgoapi.exceptions.NotLoggedInException           (PokemonGo-Bot)

### Steps to Reproduce
keep it running and "walking"

### Other Information
OS: Android termux && Debian 8
Git Commit: 9ea015e1fd9c5d269276de8a8e822ee8eb0afa0f

**Comment by simonsmh** [comment]
it is running like this 
[2016-07-27 16:27:34] [#] Walking from (-33.861021999999998, 151.21598800000001) to (-33.861924999999999, 151.21419499999999) for approx. 47.00 seconds
and then the error occur.

**Comment by unequaled86** [comment]
add to pokecli.py
from pgoapi.exceptions import NotLoggedInException

**Comment by TheGoldenXY** [comment]
Solution above. If the problem persists, open a new issue. Closing this for now.

/closed
