### ISSUE TITLE
Git unknows command

### ISSUE THREAD

**Issue by plokiii** [PokemonGoF/PokemonGo-Bot#1186]
### Expected Behavior
Idunno

### Actual Behavior
C:\Users\Ilan\Desktop\PokemonGo-Bot-dev>pip2 install -r requirements.txt
Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@v1.1.0#egg=pgoapi (from -r requirements.txt (line 1))
  Cloning https://github.com/tejado/pgoapi.git (to v1.1.0) to c:\users\ilan\desktop\pokemongo-bot-dev\src\pgoapi
  Error [Error 2] Le fichier spécifié est introuvable while executing command git clone -q https://github.com/tejado/pgoapi.git C:\Users\Ilan\Desktop\PokemonGo-Bot-dev\src\pgoapi
Cannot find command 'git'

### Steps to Reproduce
pip2 install -r requirements.txt

### Other Information
OS: W10
Git Commit: 
C:\Users\Ilan\Desktop\PokemonGo-Bot-dev>git log -n 1 --pretty=format:"%H"
'git' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

**Comment by thehawkes** [comment]
git is not installed
https://git-for-windows.github.io/

**Comment by plokiii** [comment]
i install github and still same problem

**Comment by plokiii** [comment]
Ok so i try from bash : 

$ pip2 install -r "C:\Users\Ilan\Desktop\PokemonGo-Bot-dev\requirements.txt"
Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@v1.1.0#egg=pgoapi (from -r C:\Users\Ilan\Desktop\PokemonGo-Bot-dev\requirements.txt (line 1))
Exception:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\pip\commands\install.py", line 310, in run
    wb.build(autobuilding=True)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 486, in _prepare_file
    req_to_install.ensure_has_source_dir(self.src_dir)
  File "c:\python27\lib\site-packages\pip\req\req_install.py", line 942, in ensure_has_source_dir
    self.source_dir = self.build_location(parent_dir)
  File "c:\python27\lib\site-packages\pip\req\req_install.py", line 321, in build_location
    _make_build_dir(build_dir)
  File "c:\python27\lib\site-packages\pip\utils\__init__.py", line 758, in _make_build_dir
    os.makedirs(build_dir)
  File "c:\python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 5] Accès refus: 'C:\\Program Files\\Git\\src'

**Comment by Snorflake** [comment]
you need to add the git directory to your PATH and then run it from cmd again

**Comment by plokiii** [comment]
Ok ty
