### ISSUE TITLE
crash: AttributeError: 'bool' object has no attribute 'get'

### ISSUE THREAD

**Issue by mehdi-S** [PokemonGoF/PokemonGo-Bot#1190]
### Expected Behavior
continue to scan and bot the area

### Actual Behavior
```
Traceback (most recent call last):
  File "pokecli.py", line 283, in <module>
    main()
  File "pokecli.py", line 249, in main
    bot.take_step()
  File "/root/PokemonGo-Bot-pokemonbot94/pokemongo_bot/__init__.py", line 46, in take_step
    location = self.navigator.take_step()
  File "/root/PokemonGo-Bot-pokemonbot94/pokemongo_bot/spiral_navigator.py", line 80, in take_step
    if self._step_walker.step():
  File "/root/PokemonGo-Bot-pokemonbot94/pokemongo_bot/step_walker.py", line 78, in step
    self.bot.heartbeat()
  File "/root/PokemonGo-Bot-pokemonbot94/pokemongo_bot/__init__.py", line 487, in heartbeat
    self.update_web_location() # updates every tick
  File "/root/PokemonGo-Bot-pokemonbot94/pokemongo_bot/__init__.py", line 88, in update_web_location
    map_objects = response_dict.get('responses', {}).get('GET_MAP_OBJECTS', {})
AttributeError: 'bool' object has no attribute 'get'

```
### Steps to Reproduce
configure and launch pokemonbot
after few pokestop it show me this
setting that can help
```
location : "48.893828, 2.390272"
step : 3
walk speed : default (4.16)
```

### Other Information
OS: Debian x86_64
Git Commit: 18f232bffb8df487654e6c52ff3eea859a120925

**Comment by qfdk** [comment]
the same problem here, i think it's problem of dev breanch

**Comment by TheGoldenXY** [comment]
@mehdi-S @qfdk Please upgrade to the latest branch by running this command:
```
git reset --hard
git pull -f
```
