### ISSUE TITLE
descriptor '__getitem__' requires a 'dict' object but received a 'bool'

### ISSUE THREAD

**Issue by RolfKoenders** [PokemonGoF/PokemonGo-Bot#1192]
### Expected Behavior
It should recycle/walk further/ do its bot thing.

### Actual Behavior
Crashed all of a suden.

### Other Information
OS: Linux, Ubuntu
Git Commit: 893483778366075aa9f3b80e090b448088439b93

#### Stacktrace
```
[2016-07-27 12:40:15] [#] Something rustles nearby!
[2016-07-27 12:40:30] [#] A Wild Starmie appeared! [CP 339] [Potential 0.6]
[2016-07-27 12:40:30] [#] IV [Stamina/Attack/Defense] = [10/11/6]
[2016-07-27 12:40:48] [x] Using Ultraball (chance: 43.62%)... (40 left!)
[2016-07-27 12:41:38] [x] Captured Starmie! [CP 339] [IV 0.6]
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 93, in work_on_cell
    worker.work()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 30, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/stepper.py", line 88, in _walk_to
    alt, False)
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 63, in work_on_cell
    if self.catch_pokemon(pokemon) == PokemonCatchWorker.NO_POKEBALLS:
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 190, in catch_pokemon
    return_value = worker.work()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 144, in work
    id_list2 = self.count_pokemon_inventory()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 211, in count_pokemon_inventory
    return self.counting_pokemon(response_dict, id_list)
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 216, in counting_pokemon
    "responses", "GET_INVENTORY", "inventory_delta", "inventory_items"], response_dict)
TypeError: descriptor '__getitem__' requires a 'dict' object but received a 'bool'
```

**Comment by TheOssi** [comment]
Might be also caused by the current server issues.

**Comment by kriswong** [comment]
No I had the same thing happen and don't believe it is a server issue. This happens when the bot counts pokemon in your inventory.

**Comment by TheGoldenXY** [comment]
Version check. Please run this command: `git log -n 1 --pretty=format:"%H"` and show me your output.

**Comment by ayozebarrera** [comment]
Same here

```
[18:54:45] A Wild Pidgey appeared! [CP 215] [Potential 0.6]
[18:54:45] IV [Stamina/Attack/Defense] = [11/1/15]
[19:17:29] Using Pokeball (chance: 41.52%)... (80 left!)
Traceback (most recent call last):
  File "pokecli.py", line 283, in <module>
    main()
  File "pokecli.py", line 249, in main
    bot.take_step()
  File "/Users/ayozebarrera/Proyectos/PokemonGo-Bot/pokemongo_bot/__init__.py", line 47, in take_step
    self.process_cells(work_on_forts=True)
  File "/Users/ayozebarrera/Proyectos/PokemonGo-Bot/pokemongo_bot/__init__.py", line 67, in process_cells
    "catchable_pokemons": catchable_pokemons}, location, work_on_forts)
  File "/Users/ayozebarrera/Proyectos/PokemonGo-Bot/pokemongo_bot/__init__.py", line 174, in work_on_cell
    if worker.work() == WorkerResult.RUNNING:
  File "/Users/ayozebarrera/Proyectos/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokmeon_worker.py", line 39, in work
    return self.catch_pokemon(self.cell['catchable_pokemons'][0])
  File "/Users/ayozebarrera/Proyectos/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokmeon_worker.py", line 51, in catch_pokemon
    return_value = worker.work()
  File "/Users/ayozebarrera/Proyectos/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 163, in work
    id_list1 = self.count_pokemon_inventory()
  File "/Users/ayozebarrera/Proyectos/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 262, in count_pokemon_inventory
    return self.counting_pokemon(response_dict, id_list)
  File "/Users/ayozebarrera/Proyectos/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 267, in counting_pokemon
    "responses", "GET_INVENTORY", "inventory_delta", "inventory_items"], response_dict)
TypeError: descriptor '__getitem__' requires a 'dict' object but received a 'NoneType'
```

Commit : 3b51bddc5f11f6f54fd4348579a0e54134f7cea1

**Comment by RolfKoenders** [comment]
@TheGoldenXY ```893483778366075aa9f3b80e090b448088439b93```

**Comment by juriw** [comment]
Same problem happened to me @ around 3 am CET, today. Bot was in Japan.

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
