### ISSUE TITLE
[dev] error when session goes stale

### ISSUE THREAD

**Issue by BarryReid** [PokemonGoF/PokemonGo-Bot#1201]
[13:03:21] Session stale, re-logging in
[13:03:21] Attempting login to Pokemon Go. 
Traceback (most recent call last): File "/tools/PokemonGo-Bot/pokecli.py", line 283, in main() File "/tools/PokemonGo-Bot/pokecli.py", line 249, in main 
bot.take_step() 
File "/tools/PokemonGo-Bot/pokemongo_bot/__init__.py", line 47, in take_step self.process_cells(work_on_forts=True) File "/tools/PokemonGo-Bot/pokemongo_bot/__init__.py", line 67, in process_cells 
"catchable_pokemons": catchable_pokemons}, location, work_on_forts) File "/tools/PokemonGo-Bot/pokemongo_bot/__init__.py", line 161, in work_on_cell 
self.check_session(position) 
File "/tools/PokemonGo-Bot/pokemongo_bot/__init__.py", line 227, in check_session 
self.login() 
File "/tools/PokemonGo-Bot/pokemongo_bot/__init__.py", line 240, in login 
str(self.config.password)): File "/tools/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 157, in login response = self.call() 
File "/tools/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 80, in call response = request.request(api_endpoint, self._req_method_list, player_position) File "/tools/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 93, in request 
response_dict = self._parse_main_response(response, subrequests) File "/tools/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 201, in _parse_main_response 
response_proto_dict = self._parse_sub_responses(response_proto, subrequests, response_proto_dict) File "/tools/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 208, in _parse_sub_responses 
del response_proto_dict['returns'] KeyError
: 'returns'

**Comment by BarryReid** [comment]
Looks like this has been fixed 5 days ago https://github.com/tejado/pgoapi/commit/1f25e907f3e5f1b603330e71041e1ad7bee7580f so we just need to bring the copy of pgoapi up to date.

**Comment by xskeeperx** [comment]
same error here. any solutions yet?

**Comment by xskeeperx** [comment]
pip.exe install  --upgrade git+https://github.com/tejado/pgoapi.git

fixed it for me.

**Comment by TheGoldenXY** [comment]
Solution above. Closing this.

/closed
