### ISSUE TITLE
run python pokecli.py and coming out with Error pokecli.py line 220,206 etc

### ISSUE THREAD

**Issue by NeoVilsonWong** [PokemonGoF/PokemonGo-Bot#1216]
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "/Users/wongweizhen/Downloads/PokemonGo-Bot/pokemongo_bot/__init__.py", line 32, in start
    self.stepper = Stepper(self)
  File "/Users/wongweizhen/Downloads/PokemonGo-Bot/pokemongo_bot/stepper.py", line 32, in __init__
    self.origin_lat = self.bot.position[0]
AttributeError: 'PokemonGoBot' object has no attribute 'position'

**Comment by mrseeker** [comment]
Most likely a failure on the Pokemon Go server... Try again and see if you can reproduce the error.

**Comment by LasseSkogland** [comment]
Try:
```
git reset --hard
git pull -f
```

**Comment by dmateusp** [comment]
looks like an old error that has been solved, please use master branch or dev branch

**Comment by TheGoldenXY** [comment]
This issue has been solved in the latest branch. 

Please run this command:
```git reset --hard
git pull -f```

/closed
