### ISSUE TITLE
Crash related to Gym details, or something.

### ISSUE THREAD

**Issue by pmwoodward3** [PokemonGoF/PokemonGo-Bot#1218]
Happens randomly sometimes while moving to next location, in both poke, farm, and all modes. This particular one below is from poke mode. Running on the newest dev commit, but it was also happening before that. Ubuntu x64 as well if that helps.

```
Traceback (most recent call last):
  File "pokecli.py", line 283, in <module>
    main()
  File "pokecli.py", line 249, in main
    bot.take_step()
  File "/opt/dev/pokemongo_bot/__init__.py", line 46, in take_step
    self.process_cells(work_on_forts=True)
  File "/opt/dev/pokemongo_bot/__init__.py", line 66, in process_cells
    "catchable_pokemons": catchable_pokemons}, location, work_on_forts)
  File "/opt/dev/pokemongo_bot/__init__.py", line 200, in work_on_cell
    self.navigator.take_step()
  File "/opt/dev/pokemongo_bot/spiral_navigator.py", line 76, in take_step
    if step_walker.step():
  File "/opt/dev/pokemongo_bot/step_walker.py", line 61, in step
    self.bot.heartbeat()
  File "/opt/dev/pokemongo_bot/__init__.py", line 486, in heartbeat
    self.update_web_location() # updates every tick
  File "/opt/dev/pokemongo_bot/__init__.py", line 102, in update_web_location
    fort['gym_details'] = response_gym_details['responses']['GET_GYM_DETAILS']
TypeError: 'bool' object has no attribute '__getitem__'


```

**Comment by dmateusp** [comment]
It says 'bool' object has no attribute __getitem__ which suggests that the response you get from the server call : response_gym_details failed and returned "false". I'd say the server was either unstable or you were softbanned, can someone confirm ?

**Comment by DimaVIII** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/1220

**Comment by pmwoodward3** [comment]
@dmateusp I can confirm I was NOT softbanned before this error or after. I immediately restarted the bot and everything was normal.

**Comment by pmwoodward3** [comment]
@DimaVIII You're correct, exactly the same as your issue, thanks. :)

**Comment by DimaVIII** [comment]
###Same for map_objects response function: 

[00:04:35] Now at Pokestop: Unknown - Spinning...
[00:04:39] Unknown spin result: -1
[00:04:39] Possibly searching too often - taking a short rest :)
Traceback (most recent call last):
  File "pokecli.py", line 283, in <module>
    main()
  File "pokecli.py", line 249, in main
    bot.take_step()
  File "/Users/XXX/PokemonGo-Bot/4/PokemonGo-Bot/pokemongo_bot/__init__.py", line 46, in take_step
    self.process_cells(work_on_forts=True)
  File "/Users/XXX/PokemonGo-Bot/4/PokemonGo-Bot/pokemongo_bot/__init__.py", line 50, in process_cells
    cells = self.find_close_cells(*location)
  File "/Users/XXX/PokemonGo-Bot/4/PokemonGo-Bot/pokemongo_bot/__init__.py", line 142, in find_close_cells
    map_objects = response_dict.get('responses', {}).get('GET_MAP_OBJECTS', {})
AttributeError: 'bool' object has no attribute 'get'

### Additional Information
I have observe, that this issue is server/connectivity related.
This issue appears for two bots at the same time.
Seams like the response functions have no fallback if the server refuse the connection or the internet connection is gone for a sec.

**Comment by mrseeker** [comment]
I can only assume that this is a server-related issue, since I am running this on a datacenter VM and had time-out issues & "weird errors" from the niantic server before I got this error. I am not softbanned for sure, bot ran for over an hour before it simply crashed.

```
[05:39:37] [x] Found fort c6da307179d6418bb59377bd7172fb3c.16 at distance 0.07km
[05:39:37] [x] Need to move closer to Pokestop
Traceback (most recent call last):
  File "pokecli.py", line 291, in <module>
    main()
  File "pokecli.py", line 257, in main
    bot.take_step()
  File "/home/pokemon/PokemonGo-Bot/pokemongo_bot/__init__.py", line 48, in take_step
    self.process_cells()
  File "/home/pokemon/PokemonGo-Bot/pokemongo_bot/__init__.py", line 68, in process_cells
    "catchable_pokemons": catchable_pokemons}, location)
  File "/home/pokemon/PokemonGo-Bot/pokemongo_bot/__init__.py", line 175, in work_on_cell
    if worker(self).work() == WorkerResult.RUNNING:
  File "/home/pokemon/PokemonGo-Bot/pokemongo_bot/cell_workers/spin_nearest_fort_worker.py", line 24, in work
    if MoveToFortWorker(nearest_fort, self.bot).work() == WorkerResult.RUNNING:
  File "/home/pokemon/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 39, in work
    if not step_walker.step():
  File "/home/pokemon/PokemonGo-Bot/pokemongo_bot/step_walker.py", line 61, in step
    self.bot.heartbeat()
  File "/home/pokemon/PokemonGo-Bot/pokemongo_bot/__init__.py", line 467, in heartbeat
    self.update_web_location() # updates every tick
  File "/home/pokemon/PokemonGo-Bot/pokemongo_bot/__init__.py", line 104, in update_web_location
    fort['gym_details'] = response_gym_details['responses']['GET_GYM_DETAILS']
TypeError: 'bool' object has no attribute '__getitem__'

```
OS: Linux Ubuntu 12.04 LTS
Git commit on dev: 8f77214ee409ae05c18887f771f84fb01b09bbee
