### ISSUE TITLE
Reinitialize upon NotLoggedInException

### ISSUE THREAD

**Issue by kennycoc** [PokemonGoF/PokemonGo-Bot#1219]
### Expected Behavior
 I think there may be an issue with the pgoapi version we're using that causes the login to expire every so often.

When the bot gets a NotLoggedInException from pgoapi, it could re-initialize itself.
I see no downsides to doing this.

### Actual Behavior
When there is a NotLoggedInException, the app crashes.

### Other Information
OS: Windows
Version: 9ea015e1fd9c5d269276de8a8e822ee8eb0afa0f

Trace:
``` python
Traceback (most recent call last):
  File "C:\Users\kscochran\pokemon\PokemonGo-Bot\pokecli.py", line 220, in <module>
    main()
  File "C:\Users\kscochran\pokemon\PokemonGo-Bot\pokecli.py", line 211, in main
    bot.take_step()
  File "C:\Users\kscochran\pokemon\PokemonGo-Bot\pokemongo_bot\__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "C:\Users\kscochran\pokemon\PokemonGo-Bot\pokemongo_bot\stepper.py", line 53, in take_step
    self._walk_to(self.config.walk, *position)
  File "C:\Users\kscochran\pokemon\PokemonGo-Bot\pokemongo_bot\stepper.py", line 84, in _walk_to
    self.bot.heartbeat()
  File "C:\Users\kscochran\pokemon\PokemonGo-Bot\pokemongo_bot\__init__.py", line 395, in heartbeat
    self.api.call()
  File "c:\users\kscochran\pokemon\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 81, in call
    response = request.request(api_endpoint, self._req_method_list, player_position)
  File "c:\users\kscochran\pokemon\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 100, in request
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
```

**Comment by dmateusp** [comment]
The app is already refreshing the connection token when it expires. Can someone see where that NotLoggedInException could come from ?

**Comment by kennycoc** [comment]
ah. I haven't had a chance to look at the code yet, but I assumed we didn't refresh since it's happened to me several times this morning.

I updated the initial comment with the stack trace.

**Comment by kennycoc** [comment]
I should have a PR for this either later today or tomorrow
