### ISSUE TITLE
Bug - IndexError: list index out of range

### ISSUE THREAD

**Issue by jocelyndrean** [PokemonGoF/PokemonGo-Bot#122]
Hey huys,
I always got errors since my last ggpull. When bot tries to exchange for a candy, I got a IndexError: list index out of range
Thanks for this amazing work ! :)

I Launched this command : ./pokecli.py -a ptc -u *** -p *** -l Paris -c 100

logs :
[#] A Wild Rattata appeared! [CP36]
[x] Using Pokeball...
[x] Captured Rattata! [CP36] - exchanging for candy
[x] Exchanged successfuly!
Traceback (most recent call last):
  File "./pokecli.py", line 116, in <module>
    main()
  File "./pokecli.py", line 113, in main
    bot.take_step()
  File "/Users/jd/dev/pokemon/original/PokemonGo-Bot/bot.py", line 29, in take_step
    self.stepper.take_step()
  File "/Users/jd/dev/pokemon/original/PokemonGo-Bot/stepper.py", line 65, in take_step
    self.bot.work_on_cell(cell,position)
  File "/Users/jd/dev/pokemon/original/PokemonGo-Bot/bot.py", line 36, in work_on_cell
    worker.work()
  File "/Users/jd/dev/pokemon/original/PokemonGo-Bot/cell_workers/pokemon_catch_worker.py", line 77, in work
    self.transfer_pokemon(list(Set(id_list2) - Set(id_list1))[0])
IndexError: list index out of range

**Comment by TheGoldenXY** [comment]
Your inventory is full.

**Comment by jocelyndrean** [comment]
Oh ? :( 
I got this in my log :
[#] Bag Storage: 118/350
[#] Pokemon Storage: 51/250

**Comment by CtrlAltDefeat94** [comment]
Same error. Both my bag and my pokemon storage were NOT full

**Comment by psillar** [comment]
+1 same for me and my inventory doesn't show as full:
[#] Bag Storage: 205/350
[#] Pokemon Storage: 22/250

Launched with command
`python2 pokecli.py -a ptc -u *** -p *** --location '-33.858961, 151.213380' -w 2.8 -c 100`

**Comment by Apoloser** [comment]
confirm

**Comment by FGRibreau** [comment]
```python
>>> list()[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
```

that's why

**Comment by Unit731** [comment]
^ What should be done?

**Comment by millejosh** [comment]
@Unit731 download the latest zip. This issue was resolved
