### ISSUE TITLE
[DEV] Traceback after walking

### ISSUE THREAD

**Issue by ShapeShifter499** [PokemonGoF/PokemonGo-Bot#1241]
Newest Git Pull from DEV and I get a traceback, full log below.

```
(PokemonGo-Bot) [raansu@Y40-80 PokemonGo-Bot]$ ./run.sh 

[11:31:50] PokemonGO Bot v1.0

[11:31:50] Configuration initialized

[11:31:51] 

[11:31:51] Location Found: 38.58119,-121.5068579

[11:31:51] GeoPosition: (4630626627109571165, 13861622747868610567L, 0)

[11:31:51] 

[11:31:51] Attempting login to Pokemon Go.

[11:31:52] Login to Pokemon Go successful.

[11:31:52] 

[11:31:52] --- ShapeShifter499 ---

[11:31:52] Level: 17 (Next Level: 155 XP) (Total: 159845 XP)

[11:31:52] Pokemon Captured: 489 | Pokestops Visited: 491

[11:31:52] Pokemon Bag: 312/450

[11:31:52] Items: 322/450

[11:31:52] Stardust: 3242 | Pokecoins: 30

[11:31:52] PokeBalls: 100 | GreatBalls: 110 | UltraBalls: 0

[11:31:52] RazzBerries: 8 | BlukBerries: 0 | NanabBerries: 0

[11:31:52] LuckyEgg: 0 | Incubator: 1 | TroyDisk: 1

[11:31:52] Potion: 10 | SuperPotion: 30 | HyperPotion: 30

[11:31:52] Incense: 0 | IncenseSpicy: 0 | IncenseCool: 0

[11:31:52] Revive: 30 | MaxRevive: 0

[11:31:52] 

[11:31:52] 

[11:31:52] Starting PokemonGo Bot....

[11:31:53] Scanning area for objects....

[11:31:53] Walking from (4886424092385154355, 4893173966179345880) to [4886424092385154355, 4893173966179345880] 0.00km

[11:31:53] Scanning area for objects....

[11:31:53] Walking from (4886673894597337541, 4886680486270964681) to [4.886424092385154e+18, 4.893173966179345e+18] 17276.51km

Traceback (most recent call last):

  File "pokecli.py", line 283, in <module>

    main()

  File "pokecli.py", line 249, in main

    bot.take_step()

  File "/home/raansu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 47, in take_step

    self.process_cells(work_on_forts=True)

  File "/home/raansu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 67, in process_cells

    "catchable_pokemons": catchable_pokemons}, location, work_on_forts)

  File "/home/raansu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 201, in work_on_cell

    self.navigator.take_step()

  File "/home/raansu/PokemonGo-Bot/pokemongo_bot/spiral_navigator.py", line 85, in take_step

    point['lng']

  File "/home/raansu/PokemonGo-Bot/pokemongo_bot/cell_workers/utils.py", line 33, in distance

    return 12742 * asin(sqrt(a)) * 1000

ValueError: math domain error
```

### Other Information
OS: Arch Linux 64bit
Git Commit: 15a034427d805e0bacb79fc0a1f3c96a6c93f0e3

**Comment by DayBr3ak** [comment]
redo `pip install -r requirements.txt`

**Comment by w1sht0l1v3** [comment]
you need to:
```pip install -r requirements.txt```

**Comment by ShapeShifter499** [comment]
@DayBr3ak @w1sht0l1v3 so was this a new python module requirement?

**Comment by ShapeShifter499** [comment]
It appears to be working now so I'll close this.

**Comment by ShapeShifter499** [comment]
I see it wasn't a new command but a update to a required python module called "pgoapi". Thank you for the help guys.
