### ISSUE TITLE
KeyError 'returns'

### ISSUE THREAD

**Issue by RolfKoenders** [PokemonGoF/PokemonGo-Bot#1243]
### Expected Behavior
It should continue doing its thing 😄 

### Actual Behavior
Crashing.. 

### Steps to Reproduce
It just all of a sudden crashed without that i was doing anyhting, not even on that machine.

### Other Information
OS: Linux, Ubuntu
Git Commit: `893483778366075aa9f3b80e090b448088439b93`

#### Stacktrace
```
[2016-07-27 18:45:13] [#] Finished walking
[2016-07-27 18:45:13] [#] Arrived at Pokestop
[2016-07-27 18:45:14] [#] Now at Pokestop: Goede Herder Kapel - Spinning...
[2016-07-27 18:45:15] [+] Loot:
[2016-07-27 18:45:15] [+] 50 xp
[2016-07-27 18:45:16] [+] 2x Pokeball (Total: 108)
[2016-07-27 18:45:16] [+] 1x Greatball (Total: 89)
[2016-07-27 18:45:16] [#] PokeStop on cooldown. Time left: 4.63 minutes
[2016-07-27 18:45:18] [#] Found fort 92fa8552caaa4b0ba62a9ba882851836.16 at distance 1.25km
[2016-07-27 18:45:18] [#] Need to move closer to Pokestop
[2016-07-27 18:45:18] [#] Walking from (52.249525, 5.230607) to (52.247013, 5.235736) for approx. 1.80 minutes
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 93, in work_on_cell
    worker.work()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 30, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/stepper.py", line 84, in _walk_to
    self.bot.heartbeat()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 395, in heartbeat
    self.api.call()
  File "/home/ubuntu/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 80, in call
    response = request.request(api_endpoint, self._req_method_list, player_position)
  File "/home/ubuntu/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 93, in request
    response_dict = self._parse_main_response(response, subrequests)
  File "/home/ubuntu/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 201, in _parse_main_response
    response_proto_dict = self._parse_sub_responses(response_proto, subrequests, response_proto_dict)
  File "/home/ubuntu/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 208, in _parse_sub_responses
    del response_proto_dict['returns']
KeyError: 'returns'
```

**Comment by heckfi** [comment]
Same issue

**Comment by kennycoc** [comment]
@RolfKoenders it looks like you're one update behind master. 
The last update fixed some issues with pgoapi; run this, and you should be good.
```
git pull
pip install -r requirements.txt
```

**Comment by RolfKoenders** [comment]
Ok, updated and installed new requirements. Don't know if that comes back soon. Close till it happens again?

**Comment by RolfKoenders** [comment]
Got a new error now after few minutes running:
```
[2016-07-27 20:05:57] [#] PokeStop on cooldown. Time left: 4.61 minutes
[2016-07-27 20:05:59] [#] Found fort d950340f722c4111936a83d7282a3037.16 at distance 0.20km
[2016-07-27 20:05:59] [#] Need to move closer to Pokestop
[2016-07-27 20:05:59] [#] Walking from (52.296738, 5.250926) to (52.295504, 5.245426) for approx. 1.60 minutes
[2016-07-27 20:06:56] [#] Something rustles nearby!
[2016-07-27 20:06:57] [#] A Wild Rattata appeared! [CP 183] [Potential 0.44]
[2016-07-27 20:06:57] [#] IV [Stamina/Attack/Defense] = [8/10/2]
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 93, in work_on_cell
    worker.work()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 30, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/stepper.py", line 88, in _walk_to
    alt, False)
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 63, in work_on_cell
    if self.catch_pokemon(pokemon) == PokemonCatchWorker.NO_POKEBALLS:
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 190, in catch_pokemon
    return_value = worker.work()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 74, in work
    balls_stock = self.bot.pokeball_inventory()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 234, in pokeball_inventory
    inventory_dict = inventory_req['responses']['GET_INVENTORY'][
TypeError: 'bool' object has no attribute '__getitem__'
```
