### ISSUE TITLE
ValueError 

### ISSUE THREAD

**Issue by Balauue** [PokemonGoF/PokemonGo-Bot#1248]
### Expected Behavior

Do bot stuff as usual.

### Actual Behavior
 
Crashes and has strange Geo Coordinates (config did not change).

```
[21:18:51] Starting PokemonGo Bot....
[21:18:52] Scanning area for objects....
[21:18:52] Walking from (4886422710388524743, 4893173150020695035) to [4886422710388524743, 4893173150020695035] 0.00km

[21:18:54] Scanning area for objects....
[21:18:54] Walking from (4886673893247731458, 4886680485473934749) to [4.886422710388525e+18, 4.893173150020695e+18] 8335.56km
Traceback (most recent call last):
  File "pokecli.py", line 283, in <module>
    main()
  File "pokecli.py", line 249, in main
    bot.take_step()
  File "/PokemonGo-Bot/pokemongo_bot/__init__.py", line 47, in take_step
    self.process_cells(work_on_forts=True)
  File "/PokemonGo-Bot/pokemongo_bot/__init__.py", line 67, in process_cells
    "catchable_pokemons": catchable_pokemons}, location, work_on_forts)
  File "/PokemonGo-Bot/pokemongo_bot/__init__.py", line 201, in work_on_cell
    self.navigator.take_step()
  File "/PokemonGo-Bot/pokemongo_bot/spiral_navigator.py", line 85, in take_step
    point['lng']
  File "/PokemonGo-Bot/pokemongo_bot/cell_workers/utils.py", line 33, in distance
    return 12742 * asin(sqrt(a)) * 1000
ValueError: math domain error
```
### Steps to Reproduce

start bot

### Other Information
OS: OS X 10.11.6
Git Commit: 15a034427d805e0bacb79fc0a1f3c96a6c93f0e3

The previous commit works just fine

**Comment by Balauue** [comment]
i did run install.sh to update the dependencies

**Comment by feedthejim** [comment]
i did 
sudo pip install -r requirements.txt 

to reinstall the new updated pgo api

**Comment by Orrielel** [comment]
Same problem here, and reinstalling dependencies didn't help.
I do get this error when doing it tho:
> Could not find a tag or branch '3787ffbe2e80ebce8a02d48eebceb9edf40179c1', assuming commit.

And manual update from `tejado/pgoapi` doesn't help it either.

**Comment by parifuture** [comment]
for some reason after logging in my charter has not moved a bit

**Comment by oinquer** [comment]
same here, did pip upgrade command and tejado pgoapi update. nothing helped.

**Comment by Orrielel** [comment]
My solution for Windows 7 is deleting any folders for `pgoapi` in `Python27\Lib\site-packages`. (I had 2 of them)
After that I did `pip install -r requirements.txt` just be sure and it ran without problems.
