### ISSUE TITLE
KeyError: 'spawnpoint_id'

### ISSUE THREAD

**Issue by AidanB1702** [PokemonGoF/PokemonGo-Bot#1258]
### Expected Behavior
Bot continues

### Actual Behavior
KeyError: 'spawnpoint_id'

### Steps to Reproduce
python pokecli.py

### Other Information
OS: OSX

The bot launches fine but all of a sudden i just get

Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "/Users/christopherboebel/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/Users/christopherboebel/Desktop/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/Users/christopherboebel/Desktop/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/Users/christopherboebel/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 63, in work_on_cell
    if self.catch_pokemon(pokemon) == PokemonCatchWorker.NO_POKEBALLS:
  File "/Users/christopherboebel/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 190, in catch_pokemon
    return_value = worker.work()
  File "/Users/christopherboebel/Desktop/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 25, in work
    spawnpoint_id = self.pokemon['spawnpoint_id']
KeyError: 'spawnpoint_id'

**Comment by AidanB1702** [comment]
Just Ran it again and got

Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "/Users/christopherboebel/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/Users/christopherboebel/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 151, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
TypeError: 'bool' object has no attribute '__getitem__'

**Comment by Calcyfer** [comment]
I'm assuming you're running the master branch.

You most likely have the wrong version of the pgoapi, since the new version returns `spawn_point_id` instead of `spawnpoint_id`.

The second error you got is because the API didn't get a response from the server. The servers are slow/offline at the moment.

Try pulling a fresh copy of the repo and running `pip install -r requirements.txt` again.

**Comment by AidanB1702** [comment]
didnt seem to do anything still getting it

**Comment by AidanB1702** [comment]
getting a new error now


[2016-07-30 13:19:00] [#] Walking from (4.629983160802776e+18, 1.3861410980078404e+19) to (34.009016, -118.4975856) for approx. 32.00 seconds
Traceback (most recent call last):
  File "./pokecli.py", line 220, in <module>
    main()
  File "./pokecli.py", line 211, in main
    bot.take_step()
  File "/Users/christopherboebel/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/Users/christopherboebel/Desktop/PokemonGo-Bot/pokemongo_bot/stepper.py", line 53, in take_step
    self._walk_to(self.config.walk, *position)
  File "/Users/christopherboebel/Desktop/PokemonGo-Bot/pokemongo_bot/stepper.py", line 84, in _walk_to
    self.bot.heartbeat()
  File "/Users/christopherboebel/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 395, in heartbeat
    self.api.call()
  File "/Users/christopherboebel/Desktop/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 80, in call
    response = request.request(api_endpoint, self._req_method_list, player_position)
  File "/Users/christopherboebel/Desktop/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 93, in request
    response_dict = self._parse_main_response(response, subrequests)
  File "/Users/christopherboebel/Desktop/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 201, in _parse_main_response
    response_proto_dict = self._parse_sub_responses(response_proto, subrequests, response_proto_dict)
  File "/Users/christopherboebel/Desktop/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 208, in _parse_sub_responses
    del response_proto_dict['returns']
KeyError: 'returns'
