### ISSUE TITLE
Gym details crash

### ISSUE THREAD

**Issue by koltziver** [PokemonGoF/PokemonGo-Bot#1266]
Bot getting this error
Traceback (most recent call last):
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot\pokecli.py", line 272, in <module>
    main()
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot\pokecli.py", line 238, in main
    bot.take_step()
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot\pokemongo_bot\__init__.py", line 47, in take_step
    self.process_cells()
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot\pokemongo_bot\__init__.py", line 67, in process_cells
    "catchable_pokemons": catchable_pokemons}, location)
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot\pokemongo_bot\__init__.py", line 199, in work_on_cell
    if MoveToFortWorker(forts[0], self).work() == WorkerResult.RUNNING:
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot\pokemongo_bot\cell_workers\move_to_fort_worker.py", line 39, in work
    if not step_walker.step():
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot\pokemongo_bot\step_walker.py", line 61, in step
    self.bot.heartbeat()
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot\pokemongo_bot\__init__.py", line 495, in heartbeat
    self.update_web_location() # updates every tick
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot\pokemongo_bot\__init__.py", line 103, in update_web_location
    fort['gym_details'] = response_gym_details['responses']['GET_GYM_DETAILS']
TypeError: 'NoneType' object has no attribute '__getitem__'

OS: Windows 10 
Git Commit: 15e0161d32c7a78c230c6e75cfd6867663c985d1

**Comment by eggins** [comment]
`pip install -r requirements.txt`
