### ISSUE TITLE
Bot crashes when there's no loot in the Pokestop

### ISSUE THREAD

**Issue by Agusum** [PokemonGoF/PokemonGo-Bot#1280]
### Expected Behavior
Bot does not crash.

### Actual Behavior
The bot crashes when there's nothing to loot in the Pokestop.

### Steps to Reproduce
[19:01:36] Now at Pokestop: Male Venus Statue
[19:01:36] Spinning ...
[19:01:37] Loot:
[19:01:37] [#] Nothing found.
Traceback (most recent call last):
  File "pokecli.py", line 272, in <module>
    main()
  File "pokecli.py", line 238, in main
    bot.take_step()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 47, in take_step
    self.process_cells()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 67, in process_cells
    "catchable_pokemons": catchable_pokemons}, location)
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 201, in work_on_cell
    if SeenFortWorker(forts[0], self).work() == WorkerResult.RUNNING:
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/seen_fort_worker.py", line 118, in work
    raise RuntimeError(message)
RuntimeError: Stopped at Pokestop and did not find experience, items or information about the stop cooldown. You are probably softbanned. Try to play on your phone, if pokemons always ran away and you find nothing in PokeStops you are indeed softbanned. Please try again in a few hours.

No, I did not received a soft ban. I ran the bot right after and it works. But the issue keeps happening every ~10 minutes.

### Other Information
OS: 
Git Commit: 15e0161d32c7a78c230c6e75cfd6867663c985d1

**Comment by Calcyfer** [comment]
Seems like a server issue to me. When the servers are stable again, this error won't happen.

**Comment by Agusum** [comment]
No, it has been happening for a couple of days already and at different times.

**Comment by Calcyfer** [comment]
You're right, the code catches the API not returning a result code.

I can't reproduce it since it's not happening for me, 

Apply this patch to get some extra debugging info : 
http://pastebin.com/raw/i0HRWt1a

**Comment by Agusum** [comment]
Here is the output:
{'result': 1}
Traceback (most recent call last):
  File "pokecli.py", line 357, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 63, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/spin_nearest_fort_worker.py", line 26, in work
    if SeenFortWorker(nearest_fort, self.bot).work() == WorkerResult.RUNNING:
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/seen_fort_worker.py", line 119, in work
    raise RuntimeError(message)
RuntimeError: Stopped at Pokestop and did not find experience, items or information about the stop cooldown. You are probably softbanned. Try to play on your phone, if pokemons always ran away and you find nothing in PokeStops you are indeed softbanned. Please try again in a few hours.

Running on Dev. Commit: 34caa002a464b7665cdcfb531ea3d302632898ac

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
