### ISSUE TITLE
cos not defined

### ISSUE THREAD

**Issue by thomaswelton** [PokemonGoF/PokemonGo-Bot#129]
Traceback (most recent call last):
  File "pokecli.py", line 120, in <module>
    main()
  File "pokecli.py", line 117, in main
    bot.take_step()
  File "/Users/administrator/PokemonGo-Bot/bot.py", line 29, in take_step
    self.stepper.take_step()
  File "/Users/administrator/PokemonGo-Bot/stepper.py", line 39, in take_step
    self.api.walk(self.config.walk, *position,walking_hook=self.walking_hook)
  File "/Users/administrator/PokemonGo-Bot/pgoapi/pgoapi.py", line 114, in walk
    dist = distance(i2f(self._position_lat), i2f(self._position_lng), lat, lng)
  File "/Users/administrator/PokemonGo-Bot/pgoapi/utilities.py", line 46, in distance
    a = 0.5 - cos((lat2 - lat1) * p)/2 + cos(lat1 * p) * cos(lat2 * p) * (1 - cos((lon2 - lon1) * p)) / 2
NameError: global name 'cos' is not defined

**Comment by Staubteufel** [comment]
#126
