### ISSUE TITLE
List index out of range before exchanging 

### ISSUE THREAD

**Issue by dragonalvaro** [PokemonGoF/PokemonGo-Bot#131]
Currently I have 0 pokemons, that might be the issue?

```
[#] Something rustles nearby!
[#] A Wild Scyther appeared! [CP25]
[x] Using Pokeball...
[x] Captured Scyther! [CP25] - exchanging for candy
[x] Exchanged successfuly!
Traceback (most recent call last):
  File "pokecli.py", line 116, in <module>
    main()
  File "pokecli.py", line 113, in main
    bot.take_step()
  File "/home/alvaro/Pokemon/PokemonGo-Bot.git/bot.py", line 29, in take_step
    self.stepper.take_step()
  File "/home/alvaro/Pokemon/PokemonGo-Bot.git/stepper.py", line 64, in take_step
    self.bot.work_on_cell(cell,position)
  File "/home/alvaro/Pokemon/PokemonGo-Bot.git/bot.py", line 36, in work_on_cell
    worker.work()
  File "/home/alvaro/Pokemon/PokemonGo-Bot.git/cell_workers/pokemon_catch_worker.py", line 77, in work
    self.transfer_pokemon(list(Set(id_list2) - Set(id_list1))[0])
IndexError: list index out of range
```

**Comment by CtrlAltDefeat94** [comment]
#122

**Comment by dragonalvaro** [comment]
Sorry
