### ISSUE TITLE
Unable to start pokecli.py

### ISSUE THREAD

**Issue by rkodali22** [PokemonGoF/PokemonGo-Bot#1314]
I'm trying to run the bot but I keep getting this error:
```
(venv) :PokemonGo-Bot $ python pokecli.py -cf config.json
[21:53:51] PokemonGO Bot v1.0
Traceback (most recent call last):
  File "pokecli.py", line 274, in <module>
    main()
  File "pokecli.py", line 224, in main
    config = init_config()
  File "pokecli.py", line 60, in init_config
    load.update(json.load(data))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 106 column 5 (char 4269)
```
Here's my config file:
```
{
    "auth_service": "google",
    "username": "xxx@gmail.com",
    "password": "xxx",
    "location": "40.79204409933513,-73.95747184753418",
    "gmapkey": "xxx",
    "max_steps": 50,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 450,
    "location_cache": true,
    "distance_reunit": "km",
    "item_filter": {
      "1": { "keep" : 90 },
      "101": { "keep" : 0 },
      "102": { "keep" : 0 },
      "103": { "keep" : 40 },
      "201": { "keep" : 40 },
      "701": { "keep" : 100 }
    },
    "evolve_all": "NONE",
    "use_lucky_egg": false,
    "evolve_captured": falrese,
    "catch": {},
    "release":{}
}
```

**Comment by iPression** [comment]
post the whole config file, please

**Comment by rkodali22** [comment]
```
{
    "auth_service": "google",
    "username": "xxx@gmail.com",
    "password": "xxx",
    "location": "40.79204409933513,-73.95747184753418",
    "gmapkey": "xxx",
    "max_steps": 50,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 450,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": {
      "1": { "keep" : 90 },
      "101": { "keep" : 0 },
      "102": { "keep" : 0 },
      "103": { "keep" : 40 },
      "201": { "keep" : 40 },
      "701": { "keep" : 100 }
    },
    "evolve_all": "NONE",
    "use_lucky_egg": false,
    "evolve_captured": false,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or" },

      "// Pokemons with example": { "always_catch": true },
      "// Gets filtered with release parameters": {},

      "// Ledgendary pokemons (Goes under S-Tier)": {},
      "Lapras": { "always_catch": true },
      "Moltres": { "always_catch": true },
      "Zapdos": { "always_catch": true },
      "Articuno": { "always_catch": true },

      "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
      "Mewtwo": { "always_catch": true },
      "Dragonite": { "always_catch": true },
      "Snorlax": { "always_catch": true },
      "// Mew evolves to Mewtwo": {},
      "Mew": { "always_catch": true },
      "Arcanine": { "always_catch": true },
      "Vaporeon": { "always_catch": true },
      "Gyarados": { "always_catch": true },
      "Exeggutor": { "always_catch": true },
      "Muk": { "always_catch": true },
      "Weezing": { "always_catch": true },
      "Flareon": { "always_catch": true },

      "// Growlithe evolves to Arcanine": {},
      "Growlithe": { "catch_above_cp": 465, "catch_above_iv": 0.8, "cp_iv_logic": "and" },
      "// Dragonair evolves to Dragonite": {},
      "Dragonair": { "catch_above_cp": 0, "catch_above_iv": 0.8, "cp_iv_logic": "and" },
      "// Munchlax evolves to Snorlax": {},
      "Munchlax": { "catch_above_cp": 0, "catch_above_iv": 0.8, "cp_iv_logic": "and" },
      "// Grimer evolves to Muk": {},
      "Grimer": { "catch_above_cp": 448, "catch_above_iv": 0.8, "cp_iv_logic": "and" },

      "// Magikarp evolves to Gyarados": {},
      "Magikarp": { "catch_above_cp": 91, "catch_above_iv": 0.9, "cp_iv_logic": "and" },
      "// Exeggcute evolves to Exeggutor": {},
      "Exeggcute": { "catch_above_cp": 384, "catch_above_iv": 0.8, "cp_iv_logic": "and" },
      "// Eevee evolves to many versions, like Vaporeon, Flareon": {},
      "Eevee": { "catch_above_cp": 376, "catch_above_iv": 0.8, "cp_iv_logic": "and"},

      "// A-Tier pokemons": {},
      "Slowbro": { "always_catch": true },
      "Victreebel": { "always_catch": true },
      "Machamp": { "always_catch": true },
      "Poliwrath": { "always_catch": true },
      "Clefable": { "always_catch": true },
      "Nidoking": { "always_catch": true },
      "Venusaur": { "always_catch": true },
      "Charizard": { "always_catch": true },
      "Golduck": { "always_catch": true },
      "Nidoqueen": { "always_catch": true },
      "Vileplume": { "always_catch": true },
      "Blastoise": { "always_catch": true },
      "Omastar":  { "always_catch": true },
      "Aerodactyl": { "always_catch": true },
      "Golem": { "always_catch": true },
      "Wigglytuff": { "always_catch": true },
      "Dewgong": { "always_catch": true },
      "Ninetales": { "always_catch": true },
      "Magmar": { "always_catch": true },
      "Kabutops": { "always_catch": true },
      "Electabuzz": { "always_catch": true },
      "Starmie": { "always_catch": true },
      "Jolteon": { "always_catch": true },
      "Rapidash": { "always_catch": true },
      "Pinsir": { "always_catch": true },
      "Scyther": { "always_catch": true },
      "Tentacruel": { "always_catch": true },
      "Gengar": { "always_catch": true },
      "Hypno": { "always_catch": true },
      "Pidgeot": { "always_catch": true },
      "Rhydon": { "always_catch": true },
      "Seaking": { "always_catch": true },
      "Kangaskhan": { "always_catch": true }
    },
    "release": {
      "any": {"release_below_cp": 100, "release_below_iv": 0.4, "logic": "or" },

    }
}
```

**Comment by anziclone** [comment]
Remove the # , after "any": {"release_below_cp": 100, "release_below_iv": 0.4, "logic": "or" },

This should resolve the issue. Its in the "release" tag.

**Comment by rkodali22** [comment]
what #?

**Comment by rkodali22** [comment]
removed it but got this error:
```
[22:24:57] PokemonGO Bot v1.0
Traceback (most recent call last):
  File "pokecli.py", line 274, in <module>
    main()
  File "pokecli.py", line 224, in main
    config = init_config()
  File "pokecli.py", line 60, in init_config
    load.update(json.load(data))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 106 column 5 (char 4269)
```

**Comment by rkodali22** [comment]
it was a mistake, i had 2 config.json files
