### ISSUE TITLE
Error after some time running pokecli.py

### ISSUE THREAD

**Issue by kimdotnet** [PokemonGoF/PokemonGo-Bot#1319]
I got this error on CMD:

Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "C:\Users\KIM\Documents\PokemonGo-Bot\pokemongo_bot\__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "C:\Users\KIM\Documents\PokemonGo-Bot\pokemongo_bot\stepper.py", line 53, in take_step
    self._walk_to(self.config.walk, *position)
  File "C:\Users\KIM\Documents\PokemonGo-Bot\pokemongo_bot\stepper.py", line 88, in _walk_to
    alt, False)
  File "C:\Users\KIM\Documents\PokemonGo-Bot\pokemongo_bot\stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "C:\Users\KIM\Documents\PokemonGo-Bot\pokemongo_bot\__init__.py", line 76, in work_on_cell
    if self.catch_pokemon(pokemon) == PokemonCatchWorker.NO_POKEBALLS:
  File "C:\Users\KIM\Documents\PokemonGo-Bot\pokemongo_bot\__init__.py", line 190, in catch_pokemon
    return_value = worker.work()
  File "C:\Users\KIM\Documents\PokemonGo-Bot\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 30, in work
    response_dict = self.api.call()
  File "c:\users\KIM\documents\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 81, in call
    response = request.request(api_endpoint, self._req_method_list, player_position)
  File "c:\users\KIM\documents\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 98, in request
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException

### Other Information
OS: 
WINDOWS 10
commit 3aca6d798f8a3e173dce0beb7b13c9505cc5b251
Author: Simba Zhang <solderzzc@gmail.com>
Date:   Mon Jul 25 19:10:32 2016 -0700

    Update README.md (#896)

**Comment by eggins** [comment]
Fixed this now - please get the newest version of `dev`
