### ISSUE TITLE
Bot not moving exits with exception

### ISSUE THREAD

**Issue by anovosiolov** [PokemonGoF/PokemonGo-Bot#1338]
At Dev branch:

[09:15:28] Starting PokemonGo Bot....
[09:15:29] Scanning area for objects....
[09:15:29] Walking from (4886423131554777007, 4886423549759934507) to [4886423131554777007, 4886423549759934507] 0.00km

[09:15:30] Scanning area for objects....
[09:15:30] Walking from (4886673893659026626, 4886673894067430100) to [4.886423131554777e+18, 4.886423549759934e+18] 10961.22km
Traceback (most recent call last):
  File "pokecli.py", line 291, in <module>
    main()
  File "pokecli.py", line 257, in main
    bot.take_step()
  File "/root/Pokebot/PokemonGo-Bot/pokemongo_bot/__init__.py", line 47, in take_step
    self.process_cells()
  File "/root/Pokebot/PokemonGo-Bot/pokemongo_bot/__init__.py", line 67, in process_cells
    "catchable_pokemons": catchable_pokemons}, location)
  File "/root/Pokebot/PokemonGo-Bot/pokemongo_bot/__init__.py", line 191, in work_on_cell
    self.navigator.take_step()
  File "/root/Pokebot/PokemonGo-Bot/pokemongo_bot/spiral_navigator.py", line 85, in take_step
    point['lng']
  File "/root/Pokebot/PokemonGo-Bot/pokemongo_bot/cell_workers/utils.py", line 33, in distance
    return 12742 * asin(sqrt(a)) * 1000
ValueError: math domain error

### Other Information
OS: Ubuntu 14.04
Git Commit: 4c46ad7e6b41f4d66400aee82be469cdbbb26f80

**Comment by rahadiancs** [comment]
you need to update the requirements.

**Comment by anovosiolov** [comment]
Thanks that solved it
