### ISSUE TITLE
undefined global  - 'cos'

### ISSUE THREAD

**Issue by data2700** [PokemonGoF/PokemonGo-Bot#134]
PokemonGo-Bot/pgoapi/utilities.py", line 46, in distance
    a = 0.5 - cos((lat2 - lat1) * p)/2 + cos(lat1 * p) * cos(lat2 * p) * (1 - cos((lon2 - lon1) * p)) / 2
NameError: global name 'cos' is not defined

**Comment by CtrlAltDefeat94** [comment]
#128

**Comment by pawelorzech** [comment]
Unfortunately not, in the newest build the error still exists.

`Traceback (most recent call last):
  File "pokecli.py", line 120, in <module>
    main()
  File "pokecli.py", line 117, in main
    bot.take_step()
  File "/Users/pawelorzech/.Trash/PokemonGo-Bot-master/bot.py", line 29, in take_step
    self.stepper.take_step()
  File "/Users/pawelorzech/.Trash/PokemonGo-Bot-master/stepper.py", line 38, in take_step
    self.api.walk(self.config.walk, *position,walking_hook=self.walking_hook)
  File "/Users/pawelorzech/.Trash/PokemonGo-Bot-master/pgoapi/pgoapi.py", line 114, in walk
    dist = distance(i2f(self._position_lat), i2f(self._position_lng), lat, lng)
  File "/Users/pawelorzech/.Trash/PokemonGo-Bot-master/pgoapi/utilities.py", line 46, in distance
    a = 0.5 - cos((lat2 - lat1) * p)/2 + cos(lat1 * p) * cos(lat2 * p) * (1 - cos((lon2 - lon1) * p)) / 2
NameError: global name 'cos' is not defined`

**Comment by jtdroste** [comment]
This was fixed.  Thanks for reporting.
