### ISSUE TITLE
[dev]ValueError: math domain error

### ISSUE THREAD

**Issue by Snorflake** [PokemonGoF/PokemonGo-Bot#1341]
### Expected Behavior
Bot runs fine.

### Actual Behavior

```
[14:24:37] Attempting login to Pokemon Go.
[14:24:39] Login to Pokemon Go successful.
[14:24:41]
[14:24:41] --- plsnianticnoban!!---
[14:24:41] Level: 15 (Next Level: 2800 XP) (Total: 117200 XP)
[14:24:41] Pokemon Captured: 401 | Pokestops Visited: 199
[14:24:41] Pokemon Bag: 88/250
[14:24:41] Items: 339/350
[14:24:41] Stardust: 44299 | Pokecoins: 0
[14:24:41] PokeBalls: 87 | GreatBalls: 93 | UltraBalls: 0
[14:24:41] RazzBerries: 71 | BlukBerries: 0 | NanabBerries: 0
[14:24:41] LuckyEgg: 3 | Incubator: 3 | TroyDisk: 3
[14:24:41] Potion: 10 | SuperPotion: 5 | HyperPotion: 26
[14:24:41] Incense: 6 | IncenseSpicy: 0 | IncenseCool: 0
[14:24:41] Revive: 30 | MaxRevive: 0
[14:24:41]
[14:24:41]
[14:24:42] Starting PokemonGo Bot....
[14:24:45] Scanning area for objects....
[14:24:45] Walking from (4893169811561860743, 4886431139812945858) to [4893169811561860743, 4886431139812945858] 0.00km

Traceback (most recent call last):
  File "./pokecli.py", line 291, in <module>
    main()
  File "./pokecli.py", line 257, in main
    bot.take_step()
  File "/home/aria/PokemonGo-Bot/pokemongo_bot/__init__.py", line 47, in take_step
    self.process_cells()
  File "/home/aria/PokemonGo-Bot/pokemongo_bot/__init__.py", line 67, in process_cells
    "catchable_pokemons": catchable_pokemons}, location)
  File "/home/aria/PokemonGo-Bot/pokemongo_bot/__init__.py", line 191, in work_on_cell
    self.navigator.take_step()
  File "/home/aria/PokemonGo-Bot/pokemongo_bot/spiral_navigator.py", line 85, in take_step
    point['lng']
  File "/home/aria/PokemonGo-Bot/pokemongo_bot/cell_workers/utils.py", line 33, in distance
    return 12742 * asin(sqrt(a)) * 1000
ValueError: math domain error

```
### Other Information
OS: Ubuntu server
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
4c46ad7e6b41f4d66400aee82be469cdbbb26f80

**Comment by Snorflake** [comment]
Sorry, duplicate of #1338
