### ISSUE TITLE
Geo location problem

### ISSUE THREAD

**Issue by alxnegrila** [PokemonGoF/PokemonGo-Bot#1349]
### Actual Behavior
[07:03:11] Location Found: Santa Monica Pier
[07:03:11] GeoPosition: (4629983192595374175, 13861410981352077207L, 0)
[07:03:11]
[07:03:14] Starting PokemonGo Bot....
[07:03:16] Scanning area for objects....
[07:03:16] Walking from (4886423464031136584, 4893173862777726479) to [4886423464031136584, 4893173862777726479] 0.00km

[07:03:17] Scanning area for objects....
Traceback (most recent call last):
  File "./pokecli.py", line 291, in <module>
    main()
  File "./pokecli.py", line 257, in main
    bot.take_step()
  File "/work/pokemon-go/pokemongo_bot/__init__.py", line 47, in take_step
    self.process_cells()
  File "/work/pokemon-go/pokemongo_bot/__init__.py", line 67, in process_cells
    "catchable_pokemons": catchable_pokemons}, location)
  File "/work/pokemon-go/pokemongo_bot/__init__.py", line 191, in work_on_cell
    self.navigator.take_step()
  File "/work/pokemon-go/pokemongo_bot/spiral_navigator.py", line 61, in take_step
    point['lng']
  File "/work/pokemon-go/pokemongo_bot/step_walker.py", line 21, in __init__
    destLng
  File "/work/pokemon-go/pokemongo_bot/cell_workers/utils.py", line 33, in distance
    return 12742 * asin(sqrt(a)) * 1000
ValueError: math domain error

### Steps to Reproduce
Location "34.00725957832178, -118.49967241287231" or "Santa Monica Pier"

### Other Information
OS: CentOS 7 
Git Commit: 4c46ad7e6b41f4d66400aee82be469cdbbb26f80

**Comment by mouendless** [comment]
Try #1307

**Comment by BarryReid** [comment]
I am getting the same thing. The bot is not picking a new location to walk to.

**Comment by alxnegrila** [comment]
fixed: 6dd0fade877a4e5281156381e8d1eff4d17316b8
git pull && pip install -r requirements.txt && git submodule init && git submodule update
