### ISSUE TITLE
KeyError: 'GET_GYM_DETAILS'

### ISSUE THREAD

**Issue by Marco208** [PokemonGoF/PokemonGo-Bot#1365]
### Expected Behavior
Keep running

### Actual Behavior
Crashing

### Steps to Reproduce
Let it walk past Gyms

### Other Information
OS: CentOS 6 with altinstalled 2.7 pip requirements in virtualenv
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

### Error log
[10:46:22] [x] Found fort 0a6dbdee6a9a42318d693e1ab9b3a144.16 at distance 0.03km
[10:46:22] [x] Need to move closer to Pokestop
Traceback (most recent call last):
  File "pokecli.py", line 291, in <module>
    main()
  File "pokecli.py", line 257, in main
    bot.take_step()
  File "/web/PokemonGo-Bot/pokemongo_bot/__init__.py", line 47, in take_step
    self.process_cells()
  File "/web/PokemonGo-Bot/pokemongo_bot/__init__.py", line 67, in process_cells
    "catchable_pokemons": catchable_pokemons}, location)
  File "/web/PokemonGo-Bot/pokemongo_bot/__init__.py", line 186, in work_on_cell
    if MoveToFortWorker(nearest_fort, self).work() == WorkerResult.RUNNING:
  File "/web/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 39, in work
    if not step_walker.step():
  File "/web/PokemonGo-Bot/pokemongo_bot/step_walker.py", line 61, in step
    self.bot.heartbeat()
  File "/web/PokemonGo-Bot/pokemongo_bot/__init__.py", line 501, in heartbeat
    self.update_web_location() # updates every tick
  File "/web/PokemonGo-Bot/pokemongo_bot/__init__.py", line 103, in update_web_location
    fort['gym_details'] = response_gym_details['responses']['GET_GYM_DETAILS']
KeyError: 'GET_GYM_DETAILS'

**Comment by hklcf** [comment]
server problem

**Comment by hklcf** [comment]
you can check the server down or not via http://ispokemongodownornot.com/

**Comment by Marco208** [comment]
Excuse moi
