### ISSUE TITLE
Invalid Control Character

### ISSUE THREAD

**Issue by yehan77** [PokemonGoF/PokemonGo-Bot#1375]
### Expected Behavior
it to work

### Actual Behavior
PokemonGo-Bot/pokecli.py'  && echo Exit status: $? && exit 1
sooriay:~ sooriay$ cd '/Users/sooriay/PokemonGo-Bot/' && '/usr/local/bin/pythonw'  '/Users/sooriay/PokemonGo-Bot/pokecli.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/sooriay/PokemonGo-Bot/pokecli.py", line 220, in <module>
    main()
  File "/Users/sooriay/PokemonGo-Bot/pokecli.py", line 197, in main
    config = init_config()
  File "/Users/sooriay/PokemonGo-Bot/pokecli.py", line 64, in init_config
    load.update(json.load(data))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 4 column 30 (char 99)

### Other Information
OS: mac os yosemite
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by Bramzor** [comment]
Can you paste your config without login/password/location? Seems that the json loading of the config file is buggy. Same as #1372

**Comment by yehan77** [comment]
@Bramzor  here is my config

{
    "auth_service": "google",
    "username": "@gmail.com",
    "password": "”,
    "location": "Bennelong Point, Sydney NSW 2000",
    "gmapkey": "", 
    "max_steps": 10,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "101,102,103,104",
    "evolve_all": "NONE"
}

**Comment by Bramzor** [comment]
Your error is here:
"password": "”, -> "password": "",

Replace ” with "

**Comment by yehan77** [comment]
done il try now
