### ISSUE TITLE
ValueError: math domain error

### ISSUE THREAD

**Issue by HoaxKey** [PokemonGoF/PokemonGo-Bot#1382]
### Expected Behavior
No Crash

### Actual Behavior
Traceback (most recent call last):
  File "pokecli.py", line 291, in <module>
    main()
  File "pokecli.py", line 257, in main
    bot.tick()
  File "/home/joe/PokemonGo-Bot/pokemongo_bot/__init__.py", line 65, in tick
    self.navigator.take_step()
  File "/home/joe/PokemonGo-Bot/pokemongo_bot/spiral_navigator.py", line 85, in take_step
    point['lng']
  File "/home/joe/PokemonGo-Bot/pokemongo_bot/cell_workers/utils.py", line 40, in distance
    return 12742 * asin(sqrt(a)) * 1000
ValueError: math domain error

### Steps to Reproduce
latest git pull
run with standard example configuration
logs in fine
then produces this error, most likely taking a log of a negative number...

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by friederschueler** [comment]
Did you do a "pip install -r requirements.txt"?

Probably not...

**Comment by tstumm** [comment]
Can you give us a full log?

**Comment by HoaxKey** [comment]
I'm going to close this as a new pip install -r requirements has made me unable to reproduce. good catch friederschueler.
