### ISSUE TITLE
DEV pokemon configuration fails for special settings

### ISSUE THREAD

**Issue by Bramzor** [PokemonGoF/PokemonGo-Bot#1383]
### Expected Behavior

Activating this in the config by copy pasting what is suggested in the config:
      "Rattata": { "always_release" : true },
      "Pidgey": { "keep_best_cp" : true },
      "Zubat": { "keep_best_iv" : true }

### Actual Behavior

Traceback (most recent call last):
  File "pokecli.py", line 291, in <module>
    main()
  File "pokecli.py", line 241, in main
    config = init_config()
  File "pokecli.py", line 64, in init_config
    load.update(json.load(data))
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 43 column 7 (char 1300)
^C

### Other Information
OS:  Mac OSX
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
8d65cdc23035a1d823f471db5f566c3ea5fb8238

**Comment by buettner123** [comment]
Can you post your whole config file please?
The error `ValueError: Expecting , delimiter: line 43 column 7 (char 1300)` looks like you are missing a `,` delimiter in your config file.

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
