### ISSUE TITLE
[Q] new config file and release config

### ISSUE THREAD

**Issue by aradhell** [PokemonGoF/PokemonGo-Bot#1384]
And this "action_wait_min": 1, and max option in seconds ? so i waited for 10 secs to see if it will release pokemeon.

### Expected Behavior

Release of pokemon

### Actual Behavior

[2016-07-28 13:06:36] [#] A Wild Zubat appeared! [CP 320] [Potential 0.38]
[2016-07-28 13:06:36] [#] IV [Stamina/Attack/Defense] = [8/7/2]
[2016-07-28 13:06:41] [x] Using Greatball (chance: 44.75%)... (36 left!)
[2016-07-28 13:06:42] [x] Captured Zubat! [CP 320] [IV 0.38]
[2016-07-28 13:06:42] [x] Captured Zubat! [CP 320]

### Config file
    "auth_service": "google",
    "username": "",
    "password": "",
    "location": "",
    "cp": 100,
    "gmapkey": "",
    "max_steps": 50,
    "mode": "all",
	"catch_pokemon": true,
	"spin_forts": true,
    "walk": 4.16,
    "debug": false,
    "test": false,
	"spin_forts": true,
	"health_record": true,
    "initial_transfer": 1,
	"action_wait_min": 1,
	"action_wait_max": 4,
    "pokemon_potential": 0.8,
	"evolve_all": "Pidgey",
    "location_cache": true,
    "distance_unit": "km",
	"release_pokemon": true,
    "item_filter": "101,102,103,104",
	"release": {
		"any": {"release_below_cp": 500, "release_below_iv": 0.8, "logic": "or"},
		"Pidgey": {"release_below_cp": 100, "release_below_iv": 0.4", "logic": "or"}
	}
}

**Comment by Bramzor** [comment]
In the DEV branch, there is a completely new config system.

**Comment by aradhell** [comment]
i am using master branch at the moment

**Comment by Witzbold** [comment]
couldn't this be the solution (you are using the wrong branch with the wrong config)?

**Comment by aradhell** [comment]
i really confused about releases and branches lel. 

I just tried with dev branch and got

```
Traceback (most recent call last):
  File "C:\Python27\Scripts\pokecli.py", line 291, in <module>
    main()
  File "C:\Python27\Scripts\pokecli.py", line 241, in main
    config = init_config()
  File "C:\Python27\Scripts\pokecli.py", line 60, in init_config
    load.update(json.load(data))
  File "C:\Python27\lib\json\__init__.py", line 270, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 310, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 346, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 362, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 28 column 62 (char 819)
```

**Comment by aradhell** [comment]
OK, i just checked json syntax and found the error. thank you.
