### ISSUE TITLE
When pip install -r  requirements.txt  

### ISSUE THREAD

**Issue by rngrofl** [PokemonGoF/PokemonGo-Bot#1385]
Windows 7 and installed virtualenv

(PokemonGo-Bot) D:\FOSS\PokemonGo-Bot>pip install -r requirements.txt
Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@3787ffbe2e80ebce8a02d48eebceb9edf40179c1#egg=pgoapi (from -r requirements.txt (line 1))
  Cloning https://github.com/tejado/pgoapi.git (to 3787ffbe2e80ebce8a02d48eebceb9edf40179c1) to d:\foss\pokemongo-bot\src\pgoapi
  Could not find a tag or branch '3787ffbe2e80ebce8a02d48eebceb9edf40179c1', assuming commit.
Collecting geopy==1.11.0 (from -r requirements.txt (line 2))
  Downloading geopy-1.11.0-py2.py3-none-any.whl (66kB)
    15% |¨Exception:
Traceback (most recent call last):
  File "d:\foss\pokemongo-bot\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "d:\foss\pokemongo-bot\lib\site-packages\pip\commands\install.py", line 310, in run
    wb.build(autobuilding=True)
  File "d:\foss\pokemongo-bot\lib\site-packages\pip\wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "d:\foss\pokemongo-bot\lib\site-packages\pip\req\req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "d:\foss\pokemongo-bot\lib\site-packages\pip\req\req_set.py", line 587, in _prepare_file
    session=self.session, hashes=hashes)
  File "d:\foss\pokemongo-bot\lib\site-packages\pip\download.py", line 810, in unpack_url
    hashes=hashes
  File "d:\foss\pokemongo-bot\lib\site-packages\pip\download.py", line 649, in unpack_http_url
    hashes)
  File "d:\foss\pokemongo-bot\lib\site-packages\pip\download.py", line 871, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "d:\foss\pokemongo-bot\lib\site-packages\pip\download.py", line 595, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "d:\foss\pokemongo-bot\lib\site-packages\pip\utils\hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "d:\foss\pokemongo-bot\lib\site-packages\pip\download.py", line 563, in written_chunks
    for chunk in chunks:
  File "d:\foss\pokemongo-bot\lib\site-packages\pip\utils\ui.py", line 141, in iter
    self.next(n)
  File "d:\foss\pokemongo-bot\lib\site-packages\pip\_vendor\progress\__init__.py", line 73, in next
    self.update()
  File "d:\foss\pokemongo-bot\lib\site-packages\pip\_vendor\progress\bar.py", line 79, in update
    self.writeln(line)
  File "d:\foss\pokemongo-bot\lib\site-packages\pip\_vendor\progress\helpers.py", line 68, in writeln
    print(line, end='', file=self.file)
  File "d:\foss\pokemongo-bot\lib\site-packages\pip\_vendor\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "d:\foss\pokemongo-bot\lib\site-packages\pip\_vendor\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "d:\foss\pokemongo-bot\lib\site-packages\pip\_vendor\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
IOError: [Errno 0] Error

**Comment by mehdi-S** [comment]
run `pip install --upgrade -r requirements.txt`

**Comment by rngrofl** [comment]
same  error.
looks like  when i pip install anything it will have this kind of error.

**Comment by MeGaPk** [comment]
IOError - maybe harddrive problem?
