### ISSUE TITLE
Location not working anymore

### ISSUE THREAD

**Issue by rihago** [PokemonGoF/PokemonGo-Bot#1390]
### Expected Behavior

The location goes to something totally different in the latest dev build.

[13:20:42] Location Found: 52.950018, 4.720312
[13:20:42] GeoPosition: (4632648869851188800, 4617000617268456024, 0)

13:20:47] Scanning area for objects....
[13:20:47] Walking from (4886673896525898506, 4886673881602561921) to [4.886426067231582e+18, 4.886410785734919e+18] 14639.71km
Traceback (most recent call last):
  File "pokecli.py", line 291, in <module>
    main()
  File "pokecli.py", line 257, in main
    bot.tick()
  File "/Users/harmhartsuiker/Documents/PokemonGo-Bot/pokemongo_bot/__init__.py", line 65, in tick
    self.navigator.take_step()
  File "/Users/harmhartsuiker/Documents/PokemonGo-Bot/pokemongo_bot/spiral_navigator.py", line 85, in take_step
    point['lng']
  File "/Users/harmhartsuiker/Documents/PokemonGo-Bot/pokemongo_bot/cell_workers/utils.py", line 40, in distance
    return 12742 * asin(sqrt(a)) * 1000
ValueError: math domain error

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by Jojo1910** [comment]
+1 atm with the latest commit the bot jumps out of the world xD

**Comment by BScreen** [comment]
I read in another thread to simply `pip install -r requirements.txt` again, which worked for me.

**Comment by proesd** [comment]
I'm working with the latest dev branch and it run smoothly .. :/

**Comment by skorokithakis** [comment]
I'm getting the same thing too. Commit 15a034427d805e0bacb79fc0a1f3c96a6c93f0e3 broke this.

**Comment by Jojo1910** [comment]
Oh i know why we must update the pgoapi xD sry fail

**Comment by skorokithakis** [comment]
Yep, updating pgoapi fixes that for me as well.

**Comment by gpires** [comment]
@skorokithakis: Which commit?

Cause mine have a few issues:

```
[12:36:31] Scanning area for objects....
[12:36:31] Walking from (4886674138783273204, 4886674138783273204) to [4.886674138783273e+18, 4.886674138783273e+18] 0.00km

[12:36:32] Scanning area for objects....
[12:36:32] Walking from (4.886674138783273e+18, 4.886674138783273e+18) to [4.886674138783273e+18, 4.886674138783273e+18] 0.00km

[12:36:33] Scanning area for objects....
[12:36:33] Walking from (4.886674138783273e+18, 4.886674138783273e+18) to [4.886674138783273e+18, 4.886674138783273e+18] 0.00km
```

**Comment by beranPro** [comment]
How do i update the pgo-Api?

**Comment by Jojo1910** [comment]
run pip install -r requirements.txt --upgrade

**Comment by BScreen** [comment]
@beranPro as I said before try `pip install -r requirements.txt ` and see if that works

**Comment by beranPro** [comment]
it doesn't work. I've got the same output as @gpires above

**Comment by gpires** [comment]
I set 

`"location_cache": false,`

And now its working. Its a workaround, but location cache needs to be checked.

**Comment by proesd** [comment]
I'm done with fresh install :D

**Comment by beranPro** [comment]
thanks @gpires 

setting location_cache false worked!

**Comment by cwild** [comment]
Deleting ```data/last-location-USERNAME.json``` should do the trick too.

**Comment by arnogues** [comment]
I confirm that deleting `data/last-location-*` fix the problem.

**Comment by TheGoldenXY** [comment]
Solution above. Closing this.

/closed
