### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by carminaburana123** [PokemonGoF/PokemonGo-Bot#1399]
### Expected Behavior

Catching a pokemon

### Actual Behavior

```
[14:36:21] A Wild Spearow appeared! [CP 175] [Potential 0.62]
[14:36:21] IV [Stamina/Attack/Defense] = [15/11/2]
Traceback (most recent call last):
  File "C:\PokemonGo\PokemonGo-Bot-dev\pokecli.py", line 283, in <module>
    main()
  File "C:\PokemonGo\PokemonGo-Bot-dev\pokecli.py", line 249, in main
    bot.take_step()
  File "C:\PokemonGo\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 47, in take_step
    self.process_cells(work_on_forts=True)
  File "C:\PokemonGo\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 67, in process_cells
    "catchable_pokemons": catchable_pokemons}, location, work_on_forts)
  File "C:\PokemonGo\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 174, in work_on_cell
    if worker.work() == WorkerResult.RUNNING:
  File "C:\PokemonGo\PokemonGo-Bot-dev\pokemongo_bot\cell_workers\catch_visible_pokmeon_worker.py", line 39, in work
    return self.catch_pokemon(self.cell['catchable_pokemons'][0])
  File "C:\PokemonGo\PokemonGo-Bot-dev\pokemongo_bot\cell_workers\catch_visible_pokmeon_worker.py", line 51, in catch_pokemon
    return_value = worker.work()
  File "C:\PokemonGo\PokemonGo-Bot-dev\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 98, in work
    if not self.should_capture_pokemon(pokemon_name, cp, pokemon_potential, response_dict):
  File "C:\PokemonGo\PokemonGo-Bot-dev\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 292, in should_capture_pokemon
    cp_iv_logic = catch_config.get('logic')
AttributeError: 'NoneType' object has no attribute 'get'
```

### Steps to Reproduce

just running the bot as usual

### Other Information

OS:  windows 10
Git Commit: 15a034427d805e0bacb79fc0a1f3c96a6c93f0e3

### What is tried before

+ Changing the config file
+ Reinstalling everything

**Comment by arnogues** [comment]
Same error on OSX 10.11.5 after a long walking time

**Comment by Calcyfer** [comment]
That's a server issue : NoneType means the server didn't respond.
Try again when servers are stable again.

**Comment by carminaburana123** [comment]
Why can i visit pokestops, log in, ... But not catch pokemon then?

**Comment by Calcyfer** [comment]
I'm guessing catching is a "heavier" request server-side.
It's the same bug you get if you use the client and it freezes on the pokeball screen.

**Comment by carminaburana123** [comment]
ahn ok it makes sense then

**Comment by carminaburana123** [comment]
Will close the issue when I get it to work. but for now the servers having issues for over 6 hours

**Comment by carminaburana123** [comment]
At this point i can't even open my inventory
Traceback (most recent call last):
  File "C:\PokemonGo\PokemonGo-Bot-dev\pokecli.py", line 283, in <module>
    main()
  File "C:\PokemonGo\PokemonGo-Bot-dev\pokecli.py", line 243, in main
    bot.start()
  File "C:\PokemonGo\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 42, in start
    self._setup_api()
  File "C:\PokemonGo\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 259, in _setup_api
    self._print_character_info()
  File "C:\PokemonGo\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 289, in _print_character_info
    items_stock = self.current_inventory()
  File "C:\PokemonGo\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 359, in current_inventory
    inventory_dict = inventory_req['responses']['GET_INVENTORY'][
KeyError: 'GET_INVENTORY'

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed

**Comment by Nepoxx** [comment]
How did you resolve this issue? I tried updating to no avail. Was this only a server-side error?

**Comment by Calcyfer** [comment]
It's only a server-side issue. If you're on the latest dev, you shouldn't be seeing this error anymore.
