### ISSUE TITLE
'bool' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by sangwon04** [PokemonGoF/PokemonGo-Bot#1414]
### Expected Behavior
Bot ran just fine for the past 12 hours. Now starting it results in an immediate crash. 

### Actual Behavior
[2016-07-28 07:18:22] [x] PokemonGO Bot v1.0
[2016-07-28 07:18:22] [x] Configuration initialized
[2016-07-28 07:18:22]
[2016-07-28 07:18:22] [x] Address found: Wapato Park
[2016-07-28 07:18:22] [x] Position in-game set as: (47.1962005, -122.4553895, 0.0)
[2016-07-28 07:18:22]
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "C:\Users\Joseph\PokemonGo-Bot\pokemongo_bot\__init__.py", line 31, in start
    self._setup_api()
  File "C:\Users\Joseph\PokemonGo-Bot\pokemongo_bot\__init__.py", line 151, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
TypeError: 'bool' object has no attribute '__getitem__'

### Steps to Reproduce
Just run the bot. 

### Other Information
OS: Windows 10
Git Commit: c7ab5b03cb93b5393bebbc383545a50e8519e57a

**Comment by NicholasMoser** [comment]
Servers are acting iffy. Already discussed in https://github.com/PokemonGoF/PokemonGo-Bot/issues/915

I have confirmed myself that writing a small script to keep retrying to login will eventually work.

**Comment by Messingaroung2323** [comment]
The file I created didn't delete and I just had to delete it to make the bot work correctly.

**Comment by NicholasMoser** [comment]
Try this batch script:

@echo off
:begin
pokecli.py
timeout 180
goto begin

**Comment by sangwon04** [comment]
Then how am I able to log on from my mobile device?

**Comment by sangwon04** [comment]
@Messingaround2323 what file?

**Comment by NicholasMoser** [comment]
¯\_(ツ)_/¯
Try the script for a while and see if it works for you like it did for myself.

**Comment by sangwon04** [comment]
I do have a batch script similar to yours. Only difference is mine sleeps for 5 instead of 180.

**Comment by sangwon04** [comment]
Disregard. There was a zombie cmd process running in the background I had to kill.
