### ISSUE TITLE
NameError: global name 'respone_dict' is not defined

### ISSUE THREAD

**Issue by kennycoc** [PokemonGoF/PokemonGo-Bot#1419]
### Expected Behavior
bot keeps doing it's thing

### Actual Behavior
The Bot crashes with the error "NameError: global name 'respone_dict' is not defined"
I took a look at the source, and it looks like response_dict is defined on line 30, and then it crashes on line 31 of seen_fort_worker.py.

```python
30         response_dict = self.api.call()
31         if respone_dict and 'responses' in response_dict \
32                 and'FORT_DETAILS' in response_dict['responses'] \
33                 and 'name' in response_dict['responses']['FORT_DETAILS']:
34             fort_details = response_dict['responses']['FORT_DETAILS']
35             fort_name = fort_details['name'].encode('utf8', 'replace')
```

I'm confused as to what would cause this, since it's obviously defined on the previous line.

Here's the stack trace:
```python
Traceback (most recent call last):
  File "pokecli.py", line 227, in <module>
    main()
  File "pokecli.py", line 213, in main
    bot.take_step()
  File "C:\Users\kscochran\pokemon\PokemonGo-Bot\pokemongo_bot\__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "C:\Users\kscochran\pokemon\PokemonGo-Bot\pokemongo_bot\stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "C:\Users\kscochran\pokemon\PokemonGo-Bot\pokemongo_bot\stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "C:\Users\kscochran\pokemon\PokemonGo-Bot\pokemongo_bot\__init__.py", line 96, in work_on_cell
    hack_chain = worker.work()
  File "C:\Users\kscochran\pokemon\PokemonGo-Bot\pokemongo_bot\cell_workers\seen_fort_worker.py", line 31, in work
    if respone_dict and 'responses' in response_dict \
NameError: global name 'respone_dict' is not defined
```

### Steps to Reproduce
run the bot

### Other Information
OS: Windows 10
Git Commit: c7ab5b03cb93b5393bebbc383545a50e8519e57a

**Comment by vicch** [comment]
Looks like a typo in the code, `respone` -> `response`.

**Comment by Calcyfer** [comment]
Do a pull, it's fixed in the current version.

**Comment by kennycoc** [comment]
You're right! 
This isn't a problem with the source.

I just needed to do a `git reset upstream/master --hard`
