### ISSUE TITLE
[dev] Appears to break when inspecting gyms

### ISSUE THREAD

**Issue by Vvkmnn** [PokemonGoF/PokemonGo-Bot#1429]
### Expected Behavior
Bot ignores gyms.

### Actual Behavior
Bot attempts to interact with a gym, and then crashes.

Exact issue appears to be `GET_GYM_DETAILS` returning as `none` in the function:

`fort['gym_details'] = response_gym_details.get('responses', {}).get('GET_GYM_DETAILS', None)
AttributeError: 'NoneType' object has no attribute 'get'`

log:
```
[11:39:16] [o] Arrived at Pokestop
[11:39:16] Now at Pokestop: Toronto Star Building Cornerstone
[11:39:16] Spinning ...
[11:39:16] Loot:
[11:39:16] 50 xp
[11:39:17] - 1x Revive (Total: 31)
[11:39:17] - 2x Pokeball (Total: 121)
[11:39:17] PokeStop on cooldown. Time left: 4 minutes, 59 seconds
Traceback (most recent call last):
  File "pokecli.py", line 294, in <module>
    main()
  File "pokecli.py", line 260, in main
    bot.tick()
  File "/Users/vivek.menon/Dropbox/projects/PokemonGo-Bot/pokemongo_bot/__init__.py", line 66, in tick
    self.navigator.take_step()
  File "/Users/vivek.menon/Dropbox/projects/PokemonGo-Bot/pokemongo_bot/spiral_navigator.py", line 76, in take_step
    if step_walker.step():
  File "/Users/vivek.menon/Dropbox/projects/PokemonGo-Bot/pokemongo_bot/step_walker.py", line 61, in step
    self.bot.heartbeat()
  File "/Users/vivek.menon/Dropbox/projects/PokemonGo-Bot/pokemongo_bot/__init__.py", line 467, in heartbeat
    self.update_web_location() # updates every tick
  File "/Users/vivek.menon/Dropbox/projects/PokemonGo-Bot/pokemongo_bot/__init__.py", line 124, in update_web_location
    fort['gym_details'] = response_gym_details.get('responses', {}).get('GET_GYM_DETAILS', None)
AttributeError: 'NoneType' object has no attribute 'get'
```

### Steps to Reproduce
Seems to happen when you just leave it running long enough.

### Other Information
OS: macOS 10.10.5
Git Commit: e25a7091f5f26eef17bc38f6f90df26ad199ffbc

**Comment by xorinzor** [comment]
I have 2 gyms nearby and haven't ran into this issue.

Git commit: 8f0bacebcd172727f7e6ccd8e8861d4d47c7937c

Try doing a `git pull`

**Comment by Vvkmnn** [comment]
Updated to 0a9444bd0da806e2a765af43b4de874146d5faf2.

No issues yet. Will close this in a few hours if it doesn't show up again.

**Comment by xorinzor** [comment]
I got the issue now for the first time too

Commit: 45fa966091af0bbb7121481970fc8d7037888001

```
Traceback (most recent call last):
  File "pokecli.py", line 357, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "C:\Users\xorinzor\Desktop\PokemonGo-Bot\pokemongo_bot\__init__.py", line 66, in tick
    self.navigator.take_step()
  File "C:\Users\xorinzor\Desktop\PokemonGo-Bot\pokemongo_bot\spiral_navigator.py", line 76, in take_step
    if step_walker.step():
  File "C:\Users\xorinzor\Desktop\PokemonGo-Bot\pokemongo_bot\step_walker.py", line 61, in step
    self.bot.heartbeat()
  File "C:\Users\xorinzor\Desktop\PokemonGo-Bot\pokemongo_bot\__init__.py", line 467, in heartbeat
    self.update_web_location() # updates every tick
  File "C:\Users\xorinzor\Desktop\PokemonGo-Bot\pokemongo_bot\__init__.py", line 124, in update_web_location
    fort['gym_details'] = response_gym_details.get('responses', {}).get('GET_GYM_DETAILS', None)
AttributeError: 'bool' object has no attribute 'get'
```

**Comment by NielsvanDijk** [comment]
```
Traceback (most recent call last):
  File "pokecli.py", line 357, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "/Applications/XAMPP/xamppfiles/htdocs/Github/poke/PokemonGo-Bot/pokemongo_bot/__init__.py", line 63, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/Applications/XAMPP/xamppfiles/htdocs/Github/poke/PokemonGo-Bot/pokemongo_bot/cell_workers/spin_nearest_fort_worker.py", line 24, in work
    if MoveToFortWorker(nearest_fort, self.bot).work() == WorkerResult.RUNNING:
  File "/Applications/XAMPP/xamppfiles/htdocs/Github/poke/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 39, in work
    if not step_walker.step():
  File "/Applications/XAMPP/xamppfiles/htdocs/Github/poke/PokemonGo-Bot/pokemongo_bot/step_walker.py", line 61, in step
    self.bot.heartbeat()
  File "/Applications/XAMPP/xamppfiles/htdocs/Github/poke/PokemonGo-Bot/pokemongo_bot/__init__.py", line 467, in heartbeat
    self.update_web_location() # updates every tick
  File "/Applications/XAMPP/xamppfiles/htdocs/Github/poke/PokemonGo-Bot/pokemongo_bot/__init__.py", line 124, in update_web_location
    fort['gym_details'] = response_gym_details.get('responses', {}).get('GET_GYM_DETAILS', None)
AttributeError: 'bool' object has no attribute 'get'
```
