### ISSUE TITLE
incubate_eggs_worker crash

### ISSUE THREAD

**Issue by Maladeras** [PokemonGoF/PokemonGo-Bot#1434]
### Expected Behavior

Bot starting

### Actual Behavior

Crash on start
```Python
[17:42:14] Starting PokemonGo Bot....
Traceback (most recent call last):
  File "pokecli.py", line 294, in <module>
    main()
  File "pokecli.py", line 260, in main
    bot.tick()
  File "/data/PokemonGo-Bot/pokemongo_bot/__init__.py", line 63, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/data/PokemonGo-Bot/pokemongo_bot/cell_workers/incubate_eggs_worker.py", line 34, in work
    incubators.append({"id":incubator.get("id", -1), "used":False})
AttributeError: 'str' object has no attribute 'get'

```

### Steps to Reproduce

Unknown

### Other Information
OS: Debian 8
Git Commit: (8f0bacebcd172727f7e6ccd8e8861d4d47c7937c)

**Comment by llomgui** [comment]
Same issue here.

Try pip install --upgrade -r requirements.txt

And if it doesn't work, re-clone the project and/or set it to false. It will work.

**Comment by Maladeras** [comment]
pip install --upgrade -r requirements.txt solved the issue sorry.
