### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by cmorbaab** [PokemonGoF/PokemonGo-Bot#1442]
### Expected Behavior
to run without errors

### Actual Behavior
whenever I run the pokecli.py file I get this error:
`Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 197, in main
    config = init_config()
  File "pokecli.py", line 64, in init_config
    load.update(json.load(data))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
`
### Steps to Reproduce
I followed the instructions and I installed all the requirements and set up a virtual environment. Is there a reason for this error?

**Comment by DayBr3ak** [comment]
what's your commit?

**Comment by cmorbaab** [comment]
I installed the master version yesterday.

**Comment by fvorez** [comment]
Same error here

**Comment by fvorez** [comment]
seems config.json wasnt formated properly for me, use http://jsonlint.com/, paste the config, and it will format properly
