### ISSUE TITLE
Invalid control character error

### ISSUE THREAD

**Issue by hasiokhasiok** [PokemonGoF/PokemonGo-Bot#1447]
### Expected Behavior
working bot

### Actual Behavior
$ python pokecli.py -cf ./configs/config.json
[19:17:58] PokemonGO Bot v1.0
Traceback (most recent call last):
  File "pokecli.py", line 357, in <module>
    main()
  File "pokecli.py", line 52, in main
    config = init_config()
  File "pokecli.py", line 113, in init_config
    load.update(json.load(data))
  File "/Users/xx/anaconda/envs/snakes/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/Users/xx/anaconda/envs/snakes/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/Users/xx/anaconda/envs/snakes/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/xx/anaconda/envs/snakes/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 15 column 32 (char 395)

### Steps to Reproduce
I installed everything as described.
I run the bot for a while then turned off.
Couldn't run it again since then: I re-installed, this time from dev branch, didn't work.
No idea what could be wrong, as it worked perfectly for a while...

### Other Information
OS: OS X
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by Vvkmnn** [comment]
Hey, random question. How did you close your own issue?

Can't seem to get mine to work.
