### ISSUE TITLE
Picking invalid start location

### ISSUE THREAD

**Issue by Jumbt** [PokemonGoF/PokemonGo-Bot#1452]
### Expected Behavior
Should pick the correct starting coordinates from config.json and start walking from there. 

### Actual Behavior
Instead it seems to be using an invalid coordinate which causes a crash due to maths errors.

 Configuration initialized
[18:30:24] 
[18:30:24] Location Found: [correct coordinates redacted]
[18:30:24] GeoPosition: (4632769980807179285, 13833174024368009129L, 0)
[18:30:24] 
[18:30:24] Attempting login to Pokemon Go.
[18:30:25] Login to Pokemon Go successful.

[omited...]
[18:00:19] Starting PokemonGo Bot....
[18:00:20] Scanning area for objects....
[18:00:20] Walking from (4886426185503999675, 4893160075201074102) to [4886426185503999675, 4893160075201074102] 0.00km

[18:00:21] Scanning area for objects....
Traceback (most recent call last):
  File "pokecli.py", line 294, in <module>
    main()
  File "pokecli.py", line 260, in main
    bot.tick()
  File "/home/user/tmp/PokemonGo-Bot/pokemongo_bot/__init__.py", line 66, in tick
    self.navigator.take_step()
  File "/home/user/tmp/PokemonGo-Bot/pokemongo_bot/spiral_navigator.py", line 61, in take_step
    point['lng']
  File "/home/user/tmp/PokemonGo-Bot/pokemongo_bot/step_walker.py", line 21, in __init__
    destLng
  File "/home/user/tmp/PokemonGo-Bot/pokemongo_bot/cell_workers/utils.py", line 40, in distance
    return 12742 * asin(sqrt(a)) * 1000
ValueError: math domain error

### Steps to Reproduce
With latest dev branch this outcome seems to happen whether "location_cache": is true or false. 

### Other Information
OS: Debian Stretch
Git Commit: 0a9444bd0da806e2a765af43b4de874146d5faf2

**Comment by anovosiolov** [comment]
Did you do a "pip install -r requirements.txt"?

**Comment by Orrielel** [comment]
I had the same problem, just for Win7, and fixed it by deleting the pgoapi folders in `Python27\Lib\site-packages`. (I had 2 of them)

**Comment by Jumbt** [comment]
Yeah sorry that was the issue - the requirements must have updated after I pulled latest from git. As far as I'm concerned you can close the issue.
