### ISSUE TITLE
Sudden crash 

### ISSUE THREAD

**Issue by tokarevi** [PokemonGoF/PokemonGo-Bot#1455]
### Actual Behavior

A bot suddenly crashes with the following output:

[2016-07-28 20:18:18] [x] Captured Weedle! [CP 156] [IV 0.13]
[2016-07-28 20:18:18] [x] Captured Weedle! [CP 156]
Traceback (most recent call last):
  File "./pokecli.py", line 220, in <module>
    main()
  File "./pokecli.py", line 211, in main
    bot.take_step()
  File "/home/tokarevi/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/home/tokarevi/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/home/tokarevi/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/home/tokarevi/PokemonGo-Bot/pokemongo_bot/__init__.py", line 93, in work_on_cell
    worker.work()
  File "/home/tokarevi/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 30, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "/home/tokarevi/PokemonGo-Bot/pokemongo_bot/stepper.py", line 88, in _walk_to
    alt, False)
  File "/home/tokarevi/PokemonGo-Bot/pokemongo_bot/stepper.py", line 102, in _work_at_position
    response_dict = self.api.call()
  File "/home/tokarevi/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 81, in call
    response = request.request(api_endpoint, self._req_method_list, player_position)
  File "/home/tokarevi/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 100, in request
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException

Nothing specific happened before the crash happened.

**Comment by aTadTasty** [comment]
@tokarevi in the error, it says you are not logged in. the server for pokemon is currently experiencing errors and can't seem to log in for a lot of players..

i'm getting this `[13:34:02] The API didn't return player info, servers are unstable - retrying.
` right now

**Comment by tokarevi** [comment]
@aTadTasty i thought about this but was not really sure, thanx for the info!

**Comment by tokarevi** [comment]
If the issue is in being not logged in, it would be great to make the bot try to reconnect until successful and proceed from the last location.
