### ISSUE TITLE
[Fixed]"incubate_eggs_worker.py" errors

### ISSUE THREAD

**Issue by samjack** [PokemonGoF/PokemonGo-Bot#1476]
I tried a couple of things, like: ' pip install -e git+https://github.com/tejado/pgoapi.git@81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b#egg=pgoapi' and
`root@server:~/poke/PokemonGo-Bot# sudo pip install -r requirements.txt
Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b#egg=pgoapi (from -r requirements.txt (line 1))
  Updating ./src/pgoapi clone (to 81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b)
  Could not find a tag or branch '81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b', assuming commit.
  Running setup.py (path:/root/poke/PokemonGo-Bot/src/pgoapi/setup.py) egg_info for package pgoapi

    warning: no previously-included files matching '*.dll' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
  Installing extra requirements: 'egg'
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): protobuf==3.0.0b4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): protobuf-to-dict==0.1.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): googlemaps==2.4.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): colorama==0.3.7 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): enum34==1.1.6 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): pyyaml==3.11 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): haversine==0.4.5 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): polyline==1.3.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): universal-analytics-python==0.2.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/dist-packages (from pgoapi->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in /usr/local/lib/python2.7/dist-packages (from gpsoauth==0.3.0->-r requirements.txt (line 6))
Installing collected packages: pgoapi
  Running setup.py develop for pgoapi

    warning: no previously-included files matching '*.dll' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    Creating /usr/local/lib/python2.7/dist-packages/pgoapi.egg-link (link to .)
    Removing pgoapi 1.1.0 from easy-install.pth file
    Adding pgoapi 1.1.0 to easy-install.pth file

    Installed /root/poke/PokemonGo-Bot/src/pgoapi
Successfully installed pgoapi
Cleaning up...
root@server:~/poke/PokemonGo-Bot# pip install git+https://github.com/tejado/pgoapi.git@81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b#egg=pgoapi
Requirement already satisfied (use --upgrade to upgrade): pgoapi from git+https://github.com/tejado/pgoapi.git@81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in /usr/local/lib/python2.7/dist-packages (from pgoapi)
Requirement already satisfied (use --upgrade to upgrade): protobuf>=3.0.0a3 in /usr/local/lib/python2.7/dist-packages (from pgoapi)
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in /usr/local/lib/python2.7/dist-packages (from pgoapi)
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in /usr/local/lib/python2.7/dist-packages (from pgoapi)
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in /usr/local/lib/python2.7/dist-packages (from pgoapi)
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in /usr/local/lib/python2.7/dist-packages (from gpsoauth==0.3.0->pgoapi)
Cleaning up...
root@server:~/poke/PokemonGo-Bot# ./run.sh
[20:58:03] PokemonGO Bot v1.0
[20:58:03] Configuration initialized
[20:58:03]
[20:58:03] Location Found: #####################
[20:58:03] GeoPosition: (4632406929343815797, 4613756504671155104, 0)
[20:58:03]
[20:58:03] [x] Parsing cached location...
[20:58:03]
[20:58:03] [x] Last location flag used. Overriding passed in location
[20:58:03] [x] Last in-game location was set as: (4886674138783273204, 4886674138783273204, 0)
[20:58:03]
[20:58:03] Attempting login to Pokemon Go.
[20:58:04] Login to Pokemon Go successful.
[20:58:05]
[20:58:05] --- My Username ---
[20:58:05] Level:
.......
[20:58:05] Starting PokemonGo Bot....
Traceback (most recent call last):
  File "pokecli.py", line 294, in <module>
    main()
  File "pokecli.py", line 260, in main
    bot.tick()
  File "/root/poke/PokemonGo-Bot/pokemongo_bot/__init__.py", line 63, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/root/poke/PokemonGo-Bot/pokemongo_bot/cell_workers/incubate_eggs_worker.py", line 34, in work
    incubators.append({"id":incubator.get("id", -1), "used":False})
AttributeError: 'str' object has no attribute 'get'
`
it keep givin me errors
### Other Information
OS: Debian Wheezy
Git Commit: 8852f6222f63b23e400b1df594d780121003edbf

**Comment by samjack** [comment]
fixed: `pip uninstall pgoapi && pip install -r requirements.txt`
