### ISSUE TITLE
TypeError: descriptor '__getitem__' requires a 'dict' object but received a 'NoneType'

### ISSUE THREAD

**Issue by JonathanRosado** [PokemonGoF/PokemonGo-Bot#1479]
`commit b4af57437c219313daa7d5d2f761a491f175507d`

### Expected Behavior
Run without crashing

### Actual Behavior

```
[18:05:31] [x] Need to move closer to Pokestop
[18:05:39] Something rustles nearby!
[18:05:39] A Wild Eevee appeared! [CP 472] [Potential 0.84]
[18:05:39] IV [Stamina/Attack/Defense] = [15/11/12]
[18:05:42] Catch Rate with normal Pokeball is low (29.94%). Throwing Razz Berry... (1 left!)
[18:05:42] Catch Rate with normal Pokeball has increased to 44.91%
[18:05:42] Using Pokeball (chance: 44.91%)... (99 left!)
Traceback (most recent call last):
  File "pokecli.py", line 294, in <module>
    main()
  File "pokecli.py", line 260, in main
    bot.tick()
  File "/home/devops/PokemonGo-Bot/pokemongo_bot/__init__.py", line 63, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/home/devops/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokmeon_worker.py", line 37, in work
    return self.catch_pokemon(self.cell['catchable_pokemons'][0])
  File "/home/devops/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokmeon_worker.py", line 49, in catch_pokemon
    return_value = worker.work()
  File "/home/devops/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 147, in work
    id_list1 = self.count_pokemon_inventory()
  File "/home/devops/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 211, in count_pokemon_inventory
    self._foreach_pokemon_in_inventory(response_dict, callback)
  File "/home/devops/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 217, in _foreach_pokemon_in_inventory
    "responses", "GET_INVENTORY", "inventory_delta", "inventory_items"], response_dict)
TypeError: descriptor '__getitem__' requires a 'dict' object but received a 'NoneType'
```

### Steps to Reproduce
Run for ~1hour

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by ArkBriar** [comment]
Server is done.

**Comment by kdim953** [comment]
`[13:14:56] A Wild Zubat appeared! [CP 161] [Potential 0.6]
[13:14:56] IV [Stamina/Attack/Defense] = [12/8/7]
[13:14:59] Using Pokeball (chance: 47.34%)... (395 left!)
Traceback (most recent call last):
  File "pokecli.py", line 357, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "/home/tohsh/pokemon/PokemonGo-Bot/pokemongo_bot/__init__.py", line 63, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/home/tohsh/pokemon/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokmeon_worker.py", line 37, in work
    return self.catch_pokemon(self.cell['catchable_pokemons'][0])
  File "/home/tohsh/pokemon/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokmeon_worker.py", line 49, in catch_pokemon
    return_value = worker.work()
  File "/home/tohsh/pokemon/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 147, in work
    id_list1 = self.count_pokemon_inventory()
  File "/home/tohsh/pokemon/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 211, in count_pokemon_inventory
    self._foreach_pokemon_in_inventory(response_dict, callback)
  File "/home/tohsh/pokemon/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 217, in _foreach_pokemon_in_inventory
    "responses", "GET_INVENTORY", "inventory_delta", "inventory_items"], response_dict)
TypeError: descriptor '__getitem__' requires a 'dict' object but received a 'bool'`

**Comment by surfaace** [comment]
Server is down.

**Comment by s7726** [comment]
Shouldn't this be triggering retry logic instead of just error'ing out

**Comment by Whoknowsit** [comment]
Good question. Experiencing the same problem every few minutes.
