### ISSUE TITLE
[Dev] Crash when pokemon bag is full

### ISSUE THREAD

**Issue by Kassadd** [PokemonGoF/PokemonGo-Bot#1485]
[16:48:40] Level: 22 (Next Level: 42410 XP) (Total: 392590 XP)
[16:48:40] Pokemon Captured: 1225 | Pokestops Visited: 771
[16:48:40] Pokemon Bag: 250/250
[16:48:40] Items: 345/350
[16:48:40] Stardust: 58957 | Pokecoins: 0
[16:48:40] PokeBalls: 98 | GreatBalls: 100 | UltraBalls: 33
[16:48:40] RazzBerries: 1 | BlukBerries: 0 | NanabBerries: 0
[16:48:40] LuckyEgg: 1 | Incubator: 1 | TroyDisk: 5
[16:48:40] Potion: 10 | SuperPotion: 30 | HyperPotion: 30
[16:48:40] Incense: 4 | IncenseSpicy: 0 | IncenseCool: 0
[16:48:40] Revive: 30 | MaxRevive: 0
[16:48:40]
[16:48:40]
[16:48:42] Starting PokemonGo Bot....
[16:48:43] Something rustles nearby!
Traceback (most recent call last):
  File "pokecli.py", line 357, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "/home/ec2-user/PokemonGo-Bot/pokemongo_bot/__init__.py", line 64, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/home/ec2-user/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokmeon_worker.py", line 37, in work
    return self.catch_pokemon(self.cell['catchable_pokemons'][0])
  File "/home/ec2-user/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokmeon_worker.py", line 49, in catch_pokemon
    return_value = worker.work()
  File "/home/ec2-user/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 37, in work
    raise RuntimeError('Pokemon Bag is full!')
RuntimeError: Pokemon Bag is full!

OS: Linux 3.10.0
Git Commit: c11af09b64df4be77257207dfd147649489c776e

**Comment by Jojo1910** [comment]
Same here

OS: Linux Debian

**Comment by VictorChen** [comment]
I guess it should just switch to farm mode?

**Comment by Kassadd** [comment]
I would change the current raise:

```
  if response_dict['responses'][self.response_key][self.response_status_key] is 7:
                        if self.config.release_pokemon:
                            raise RuntimeError('Pokemon Bag is full!')
```

for something like:

```
  if response_dict['responses'][self.response_key][self.response_status_key] is 7:
                        if self.config.release_pokemon:
                           logger.log('Pokemon Bag is full!', 'red')
                           return False
```

At least as work around, but I guess that the final solution should be not call at all the pokemon catch worker and switch to catch_pokemon=false mode....

**Comment by Henji96** [comment]
Same issue. evolve_all simply doesn't work. On master or dev.

**Comment by AlexBailey** [comment]
Experiencing this issue... Is there literally no automatic transfer like in the master version?
