### ISSUE TITLE
KeyError: returns

### ISSUE THREAD

**Issue by ComposerCookie** [PokemonGoF/PokemonGo-Bot#1490]
### Expected Behavior
Not crashing

### Actual Behavior
Crashing

### Steps to Reproduce
Just run the bot

### Other Information
OS: Ubuntu 16

From git log:
ec2b7add95da6bc580035d8d4c472c1d41e439a6

Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "/home/jacqueline/Documents/Projects/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/home/jacqueline/Documents/Projects/PokemonGo-Bot/pokemongo_bot/__init__.py", line 186, in _setup_api
    self.update_inventory()
  File "/home/jacqueline/Documents/Projects/PokemonGo-Bot/pokemongo_bot/__init__.py", line 208, in update_inventory
    response = self.api.call()
  File "/home/jacqueline/Documents/Projects/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 80, in call
    response = request.request(api_endpoint, self._req_method_list, player_position)
  File "/home/jacqueline/Documents/Projects/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 93, in request
    response_dict = self._parse_main_response(response, subrequests)
  File "/home/jacqueline/Documents/Projects/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 201, in _parse_main_response
    response_proto_dict = self._parse_sub_responses(response_proto, subrequests, response_proto_dict)
  File "/home/jacqueline/Documents/Projects/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 208, in _parse_sub_responses
    del response_proto_dict['returns']
KeyError: 'returns'

Saw another person with the same issue that seemed to be solved by getting the latest commit and reinstall requirement, already done that but still doesn't work

**Comment by banksymate** [comment]
#1491

**Comment by banksymate** [comment]
Run git log -n 1 --pretty=format:"%H"' and send the output, you didn't specify it in the post.

**Comment by ComposerCookie** [comment]
Updated

**Comment by banksymate** [comment]
Most likely a problem with Pokemon GO servers being down, it's happening to multiple people. Assuming your output is a little bit different than #1491 because of you being on dev branch.

**Comment by CattDamon** [comment]
I'm getting this same error.  I updated the requirements and still nothing.

**Comment by ComposerCookie** [comment]
I switched to Dev branch and update requirement and get the new config and it work

**Comment by h8rry** [comment]
Same problem

**Comment by banksymate** [comment]
Please close this issue then.

To fix:
Switch to dev branch.
(git clone -b dev https://github.com/PokemonGoF/PokemonGo-Bot)
cd PokemonGo-Bot
pip install -r requirements.txt
Edit your config(s) and try running.

**Comment by ComposerCookie** [comment]
Well okay, it mean it is only fixed on the dev branch though, master is still messed up.

But if you want me to to close it I will.
