### ISSUE TITLE
Crash on update_web_location

### ISSUE THREAD

**Issue by Marco208** [PokemonGoF/PokemonGo-Bot#1495]
### Expected Behavior
Keep running

### Actual Behavior
Crashing

### Steps to Reproduce
Just walk

### Other Information
OS: CentOS 6
Git Commit: c11af09b64df4be77257207dfd147649489c776e

[23:41:56] [x] Found fort af2bbf58f7f441afb787180a22245841.16 at distance 0.13km
[23:41:56] [x] Need to move closer to Pokestop
[23:41:59] [x] Found fort af2bbf58f7f441afb787180a22245841.16 at distance 0.12km
[23:41:59] [x] Need to move closer to Pokestop
Traceback (most recent call last):
  File "pokecli.py", line 357, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "/web/PokemonGo-Bot/pokemongo_bot/__init__.py", line 63, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/web/PokemonGo-Bot/pokemongo_bot/cell_workers/spin_nearest_fort_worker.py", line 24, in work
    if MoveToFortWorker(nearest_fort, self.bot).work() == WorkerResult.RUNNING:
  File "/web/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 39, in work
    if not step_walker.step():
  File "/web/PokemonGo-Bot/pokemongo_bot/step_walker.py", line 61, in step
    self.bot.heartbeat()
  File "/web/PokemonGo-Bot/pokemongo_bot/__init__.py", line 467, in heartbeat
    self.update_web_location() # updates every tick
  File "/web/PokemonGo-Bot/pokemongo_bot/__init__.py", line 111, in update_web_location
    cells = map_objects['map_cells']
KeyError: 'map_cells'

**Comment by Marco208** [comment]
Unstable servers, invalid issue
