### ISSUE TITLE
KeyError: 'map_cells' on dev

### ISSUE THREAD

**Issue by vanrzuf** [PokemonGoF/PokemonGo-Bot#1500]
![securecrt_2016-07-28_23-51-45](https://cloud.githubusercontent.com/assets/18649425/17230866/fc6ea048-551e-11e6-844e-8a1d056a1fba.png)

### Other Information
OS: Debian Wheezy
Git Commit: c11af09b64df4be77257207dfd147649489c776e

**Comment by DavidTai1** [comment]
Server problem. No idea why there is a server problem XD.

**Comment by inet-pwnZ** [comment]
im experiencing something similar #1496

**Comment by taschana** [comment]
```
[23:47:51] PokemonGO Bot v1.0
[23:47:51] No config argument specified, checking for /configs/config.json
[23:47:51] Configuration initialized
[23:47:51] [x] Coordinates found in passed in location, not geocoding.
[23:47:51]
[23:47:51] Location Found: 48.2026515,16.3894047
[23:47:51] GeoPosition: (48.2026515, 16.3894047, 0)
[23:47:51]
[23:47:51] [x] Parsing cached location...
[23:47:51]
[23:47:51] [x] Last location flag used. Overriding passed in location
[23:47:51] [x] Last in-game location was set as: (48.20258068496052, 16.389218933148467, 0)
[23:47:51]
[23:47:51] Attempting login to Pokemon Go.
[23:47:53] Login to Pokemon Go successful.
[23:47:53]
[23:47:53] --- PrincessT4sch4 ---
[23:47:53] Level: 10 (Next Level: 7595 XP) (Total: 47405 XP)
[23:47:53] Pokemon Captured: 62 | Pokestops Visited: 583
[23:47:53] Pokemon Bag: 33/250
[23:47:53] Items: 244/350
[23:47:53] Stardust: 6793 | Pokecoins: 0
[23:47:53] PokeBalls: 100 | GreatBalls: 0 | UltraBalls: 0
[23:47:53] RazzBerries: 69 | BlukBerries: 0 | NanabBerries: 0
[23:47:53] LuckyEgg: 2 | Incubator: 2 | TroyDisk: 2
[23:47:53] Potion: 10 | SuperPotion: 22 | HyperPotion: 0
[23:47:53] Incense: 5 | IncenseSpicy: 0 | IncenseCool: 0
[23:47:53] Revive: 30 | MaxRevive: 0
[23:47:53]
[23:47:53]
[23:47:55] Starting PokemonGo Bot....
Traceback (most recent call last):
  File "pokecli.py", line 357, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "D:\Games\PokemonGo-Bot\pokemongo_bot\__init__.py", line 64, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "D:\Games\PokemonGo-Bot\pokemongo_bot\cell_workers\recycle_items_worker.py", line 14, in work
    item_count_dict = self.bot.item_inventory_count('all')
  File "D:\Games\PokemonGo-Bot\pokemongo_bot\__init__.py", line 361, in item_inventory_count
    ['inventory_delta']['inventory_items']
TypeError: list indices must be integers, not str

```
I got this and 
```
$ ./run.sh
[23:56:36] PokemonGO Bot v1.0
[23:56:36] No config argument specified, checking for /configs/config.json
[23:56:36] Configuration initialized
[23:56:36] [x] Coordinates found in passed in location, not geocoding.
[23:56:36]
[23:56:36] Location Found: 48.2026515,16.3894047
[23:56:36] GeoPosition: (48.2026515, 16.3894047, 0)
[23:56:36]
[23:56:36] [x] Parsing cached location...
[23:56:36]
[23:56:36] [x] Last location flag used. Overriding passed in location
[23:56:36] [x] Last in-game location was set as: (48.20258068496052, 16.389218933148467, 0)
[23:56:36]
[23:56:36] Attempting login to Pokemon Go.
[23:56:37] Login to Pokemon Go successful.
Traceback (most recent call last):
  File "pokecli.py", line 357, in <module>
    main()
  File "pokecli.py", line 62, in main
    bot.start()
  File "D:\Games\PokemonGo-Bot\pokemongo_bot\__init__.py", line 44, in start
    self._setup_api()
  File "D:\Games\PokemonGo-Bot\pokemongo_bot\__init__.py", line 234, in _setup_api
    self._print_character_info()
  File "D:\Games\PokemonGo-Bot\pokemongo_bot\__init__.py", line 265, in _print_character_info
    items_stock = self.current_inventory()
  File "D:\Games\PokemonGo-Bot\pokemongo_bot\__init__.py", line 335, in current_inventory
    inventory_dict = inventory_req['responses']['GET_INVENTORY'][
KeyError: 'GET_INVENTORY'

```
I figured it is a similar problem and didn't open a separate issue -- hope help comes soon! But thanks for your efforts in advance already!

**Comment by gl1721** [comment]
response_dict = self.api.call()
            map_objects = response_dict.get('responses', {}).get('GET_MAP_OBJECTS', {})
            status = map_objects.get('status', None)
            cells = map_objects.get('map_cells', None)

            #insert detail info about gym to fort
            if cells:
                for cell in cells:
                    if 'forts' in cell:
                        for fort in cell['forts']:
                            if fort.get('type') != 1:
                                self.api.get_gym_details(gym_id=fort.get('id'),
                                                         player_latitude=lng,
                                                         player_longitude=lat,
                                                         gym_latitude=fort.get('latitude'),
                                                         gym_longitude=fort.get('longitude'))
                                response_gym_details = self.api.call()
                                fort['gym_details'] = response_gym_details.get('responses', {}).get('GET_GYM_DETAILS', None)

**Comment by ddrght12345** [comment]
47cf9db53d986f78cf0cce8a2c6aa5863c29a7c8 Seems to be a quick bandaid for the issue

**Comment by taschana** [comment]
thanks,
how about my two issues with the GET_INVENTORY?

**Comment by taschana** [comment]
@gl1721 can you help me too?
