### ISSUE TITLE
TypeError: __init__() takes exactly 7 arguments (5 given)

### ISSUE THREAD

**Issue by JohnnyOmm** [PokemonGoF/PokemonGo-Bot#1506]
I installed the path_navigator and walking progress bar pull requests but got this error

```
[18:28:53] Captured Doduo! [CP 179] [Potential 0.69] [15/13/3]
[18:28:58] [x] Found fort ebb95539badc428885aef95a16492789.16 at distance 0.40km
[18:28:58] [x] Need to move closer to Pokestop
Traceback (most recent call last):
  File "C:\PokeGoBot Dev\PokemonGo-Bot\pokecli.py", line 369, in <module>
    main()
  File "C:\PokeGoBot Dev\PokemonGo-Bot\pokecli.py", line 68, in main
    bot.tick()
  File "C:\PokeGoBot Dev\PokemonGo-Bot\pokemongo_bot\__init__.py", line 69, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "C:\PokeGoBot Dev\PokemonGo-Bot\pokemongo_bot\cell_workers\spin_nearest_fort_worker.py", line 24, in work
    if MoveToFortWorker(nearest_fort, self.bot).work() == WorkerResult.RUNNING:
  File "C:\PokeGoBot Dev\PokemonGo-Bot\pokemongo_bot\cell_workers\move_to_fort_worker.py", line 36, in work
    lng
TypeError: __init__() takes exactly 7 arguments (5 given)
```

**Comment by JohnnyOmm** [comment]
anyone?

**Comment by marksweb** [comment]
Who's PR is it?
