### ISSUE TITLE
 bot.take_step()

### ISSUE THREAD

**Issue by shpapy** [PokemonGoF/PokemonGo-Bot#1517]
### Expected Behavior
Working as usual

### Actual Behavior
errors and exists with the following

Traceback (most recent call last):
  File "./pokecli.py", line 220, in <module>
    main()
  File "./pokecli.py", line 211, in main
    bot.take_step()
  File "/home/shpapy/PokemonGo-Bot-NL/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/home/shpapy/PokemonGo-Bot-NL/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/home/shpapy/PokemonGo-Bot-NL/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/home/shpapy/PokemonGo-Bot-NL/pokemongo_bot/__init__.py", line 93, in work_on_cell
    worker.work()
  File "/home/shpapy/PokemonGo-Bot-NL/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 30, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "/home/shpapy/PokemonGo-Bot-NL/pokemongo_bot/stepper.py", line 88, in _walk_to
    alt, False)
  File "/home/shpapy/PokemonGo-Bot-NL/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/home/shpapy/PokemonGo-Bot-NL/pokemongo_bot/__init__.py", line 63, in work_on_cell
    if self.catch_pokemon(pokemon) == PokemonCatchWorker.NO_POKEBALLS:
  File "/home/shpapy/PokemonGo-Bot-NL/pokemongo_bot/__init__.py", line 190, in catch_pokemon
    return_value = worker.work()
  File "/home/shpapy/PokemonGo-Bot-NL/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 74, in work
    balls_stock = self.bot.pokeball_inventory()
  File "/home/shpapy/PokemonGo-Bot-NL/pokemongo_bot/__init__.py", line 234, in pokeball_inventory
    inventory_dict = inventory_req['responses']['GET_INVENTORY'][
KeyError: 'GET_INVENTORY'

### Steps to Reproduce
./pokecli.py -cf config_2_GOOGLE.json

"auth_service": "google",
    "username": "bla@gmail.com",
    "password": "something",
    "location": "52.391342,4.6442478 ",
    "gmapkey": "MY KEY",
    "max_steps": 15,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": false,
    "distance_unit": "km",
    "item_filter": "101,102,103,104",
    "evolve_all": "NONE"

### Other Information
OS: Elementary os 
Linux  3.16.0-77-generic #99~14.04.1-Ubuntu SMP Tue Jun 28 19:18:41 UTC 2016 i686 i686 i686 GNU/Linux

Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
ec2b7add95da6bc580035d8d4c472c1d41e439a6

**Comment by banksymate** [comment]
This is an issue with Pokemon GO servers.
Please switch to the dev branch.
To do this, make a new directory for the dev branch and run the following:
git clone -b dev https://github.com/PokemonGoF/PokemonGo-Bot
cd PokemonGo-Bot
pip install -r requirements.txt

Once that is finished, edit the configuration(s) in 'configs/' then run python pokecli.py

If this works, please close the issue.

**Comment by sayasemut** [comment]
seems to be working +1

**Comment by shpapy** [comment]
dev works.
thanks

**Comment by rohimkudus** [comment]
thanks guy
