### ISSUE TITLE
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:590)

### ISSUE THREAD

**Issue by AidanB1702** [PokemonGoF/PokemonGo-Bot#1551]
### Expected Behavior

Bot Start up
### Actual Behavior

[2016-07-29 00:24:42] [x] PokemonGO Bot v1.0
[2016-07-29 00:24:42] [x] Configuration initialized
[2016-07-29 00:24:42] [x] Coordinates found in passed in location, not geocoding.
[2016-07-29 00:24:42] 
[2016-07-29 00:24:42] [x] Address found: 34.00901609513044,-118.49758565425873
[2016-07-29 00:24:42] [x] Position in-game set as: (34.009016, -118.4975856, 0.0)
[2016-07-29 00:24:42] 
Traceback (most recent call last):
  File "./pokecli.py", line 220, in <module>
    main()
  File "./pokecli.py", line 206, in main
    bot.start()
  File "/Users/christopherboebel/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/Users/christopherboebel/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 136, in _setup_api
    str(self.config.password)):
  File "/Users/christopherboebel/Desktop/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 144, in login
    if not self._auth_provider.login(username, password):
  File "/Users/christopherboebel/Desktop/PokemonGo-Bot/src/pgoapi/pgoapi/auth_google.py", line 47, in login
    login = perform_master_login(username, password, self.GOOGLE_LOGIN_ANDROID_ID)
  File "/usr/local/lib/python2.7/site-packages/gpsoauth/__init__.py", line 66, in perform_master_login
    return _perform_auth_request(data)
  File "/usr/local/lib/python2.7/site-packages/gpsoauth/__init__.py", line 22, in _perform_auth_request
    headers={'User-Agent': useragent})
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:590)
### Steps to Reproduce

./pokecli.py
### Other Information
OS: OSX

**Comment by arnogues** [comment]
Master branch is old, use dev branch there are a lot of fixes
