### ISSUE TITLE
KeyError: u'AND'

### ISSUE THREAD

**Issue by arnogues** [PokemonGoF/PokemonGo-Bot#1555]
### Expected Behavior
The bot should start

### Actual Behavior
Got this error 
```
[07:47:19] Starting PokemonGo Bot....
Traceback (most recent call last):
  File "./pokecli.py", line 381, in <module>
    main()
  File "./pokecli.py", line 68, in main
    bot.tick()
  File "/Users/XXX/Documents/dev/PokemonGo-Bot/pokemongo_bot/__init__.py", line 65, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/Users/XXX/Documents/dev/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_transfer_worker.py", line 73, in work
    if self.should_release_pokemon(pokemon_name, pokemon_cp, pokemon_potential):
  File "/Users/XXX/Documents/dev/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_transfer_worker.py", line 154, in should_release_pokemon
    if logic_to_function[cp_iv_logic](*release_results.values()):
KeyError: u'AND'
```
### Steps to Reproduce
Use a PTC account, google account seems to work

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by Jojo1910** [comment]
Are you running master or dev? And pls run  " git log -n 1 --pretty=format:"%H" " and paste the out put here. Also paste your config pls.
