### ISSUE TITLE
Value Error 

### ISSUE THREAD

**Issue by wsmigielski** [PokemonGoF/PokemonGo-Bot#1579]
When I run the run.sh file I get this error

Traceback (most recent call last):
  File "pokecli.py", line 389, in <module>
    main()
  File "pokecli.py", line 52, in main
    config = init_config()
  File "pokecli.py", line 113, in init_config
    load.update(json.load(data))
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 8 column 5 (char 217)

It worked earlier. I'm on the dev branch. 

OS - Linux Ubuntu 16.04

**Comment by Jojo1910** [comment]
Paste your config

**Comment by Jojo1910** [comment]
You got a mistake in it. You can validate your config here http://jsonlint.com/

**Comment by wsmigielski** [comment]
Ahh thank you a comma was missing after one of the lines.

**Comment by Jojo1910** [comment]
np :)

Pls Close

**Comment by wsmigielski** [comment]
Close

**Comment by wsmigielski** [comment]
I'm still fairly new to GitHub, how do I close?

**Comment by wsmigielski** [comment]
Close #1579
