### ISSUE TITLE
Error: argument of type 'bool' is not iterable

### ISSUE THREAD

**Issue by ethervoid** [PokemonGoF/PokemonGo-Bot#158]
```
[#] A Wild Pidgey appeared! [CP113]
2016-07-22 08:03:21,086 [   rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 502
Traceback (most recent call last):
  File "pokecli.py", line 120, in <module>
    main()
  File "pokecli.py", line 117, in main
    bot.take_step()
  File "/home/pi/PokemonGo-Bot/bot.py", line 29, in take_step
    self.stepper.take_step()
  File "/home/pi/PokemonGo-Bot/stepper.py", line 63, in take_step
    self.bot.work_on_cell(cell,position)
  File "/home/pi/PokemonGo-Bot/bot.py", line 36, in work_on_cell
    worker.work()
  File "/home/pi/PokemonGo-Bot/cell_workers/pokemon_catch_worker.py", line 36, in work
    id_list1 = self.count_pokemon_inventory()
  File "/home/pi/PokemonGo-Bot/cell_workers/pokemon_catch_worker.py", line 119, in count_pokemon_inventory
    return self.counting_pokemon(response_dict, id_list)
  File "/home/pi/PokemonGo-Bot/cell_workers/pokemon_catch_worker.py", line 122, in counting_pokemon
    if 'responses' in response_dict:
TypeError: argument of type 'bool' is not iterable
```

**Comment by harsh1412** [comment]
Same for me

**Comment by Mordana** [comment]
`2016-07-22`` 08:03:21,086 [   rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 502`

Servers were unstable at this point. The HTTP request returns a 502 (Bad Gateway).
This means the servers are somewhat responding but you're effectively missing data, which results in a false (bool) argument.

Servers are now completely offline.

**Comment by harsh1412** [comment]
ohh

**Comment by jtdroste** [comment]
Server issue.  Closing...
