### ISSUE TITLE
Missing deps socketIO_client

### ISSUE THREAD

**Issue by Lunik** [PokemonGoF/PokemonGo-Bot#1596]
### Actual Behavior
socketIO_client module is missing

### Steps to Reproduce
./install.sh
./run.sh

### Other Information
OS: Centos7
Git Commit: 70bc5935b9ebbbf75f2dc2463f0c9fc82efd669d

**Comment by tstumm** [comment]
Re-rerun `pip install -r requirements.txt`

**Comment by Yanush7** [comment]
After runing pip install -r requirements.txt now i have this when trying to run the bot:
`$ python pokecli.py
[15:34:13] PokemonGO Bot v1.0
[15:34:13] No config argument specified, checking for /configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 408, in <module>
    main()
  File "pokecli.py", line 52, in main
    config = init_config()
  File "pokecli.py", line 117, in init_config
    load.update(json.load(data))
  File "C:\Python27\lib\json\__init__.py", line 290, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 47 column 7 (char 1293)
`
