### ISSUE TITLE
[DEV]IndexError: list index out of range

### ISSUE THREAD

**Issue by micdawg12** [PokemonGoF/PokemonGo-Bot#1607]
### Expected Behavior
For bot to start.

### Actual Behavior
Bot crashes.

### Steps to Reproduce
Start Bot.

### Other Information
OS:  Ubuntu 16.04
Git Commit: 3dc8e8ba39151130e987e39796ad6151c9ee5c67

2016-07-29 05:59:11,859 [pgoapi.rpc_api] [DEBUG] Parsing sub RPC responses...
2016-07-29 05:59:11,859 [pgoapi.rpc_api] [DEBUG] Parsing class: POGOProtos.Networking.Responses_pb2.GetInventoryResponse
2016-07-29 05:59:11,881 [pgoapi.pgoapi] [ INFO] Cleanup of request!
Traceback (most recent call last):
  File "pokecli.py", line 389, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "/home/micdawg/.PokemonGo-Bot/pokemongo_bot/__init__.py", line 92, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/home/micdawg/.PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon_worker.py", line 47, in work
    lured_pokemon = self.get_lured_pokemon()
  File "/home/micdawg/.PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon_worker.py", line 53, in get_lured_pokemon
    fort = forts[0]
IndexError: list index out of range

**Comment by ailyenko** [comment]
Have the same in dev branch

**Comment by micdawg12** [comment]
Sorry, I'm an idiot.  This is the DEV branch.

**Comment by micdawg12** [comment]
Seems to be fixed in d39170553bbeffac4781ab49198bfa2f21b97c8e

**Comment by luki922** [comment]
i hve this same error:
`[14:04:47] Moving towards fort 0e6608e450c249ceafbd17f9659a315e.16, 0.05km left
[14:04:54] Releasing Pinsir with CP 548 and IV 0.51. Matching release rule: CP < 0 OR IV < 0.8. 
[14:04:54] Exchanging Pinsir [CP 548] [Potential 0.51] for candy!
[14:04:56] Releasing Pinsir with CP 252 and IV 0.29. Matching release rule: CP < 0 OR IV < 0.8. 
[14:04:56] Exchanging Pinsir [CP 252] [Potential 0.29] for candy!
Traceback (most recent call last):
  File "pokecli.py", line 408, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "/home/trick/Pobrane/pokemon2/bot/PokemonGo-Bot/pokemongo_bot/__init__.py", line 92, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/home/trick/Pobrane/pokemon2/bot/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon_worker.py", line 47, in work
    lured_pokemon = self.get_lured_pokemon()
  File "/home/trick/Pobrane/pokemon2/bot/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon_worker.py", line 53, in get_lured_pokemon
    fort = forts[0]
IndexError: list index out of range
`
