### ISSUE TITLE
[DEV]self.points[self.ptr] out of range

### ISSUE THREAD

**Issue by salvprest** [PokemonGoF/PokemonGo-Bot#1608]
if in the max_circle_size area there are only forts in cooldown the bot crash:
```
[12:50:38] PokeStop on cooldown. Time left: 4 minutes, 59 seconds
Traceback (most recent call last):
  File "pokecli.py", line 389, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File ".../PokemonGo-Bot/pokemongo_bot/__init__.py", line 92, in tick
    self.navigator.take_step()
  File ".../PokemonGo-Bot/pokemongo_bot/spiral_navigator.py", line 48, in take_step
    point = self.points[self.ptr]
IndexError: list index out of range
```

**Comment by tstumm** [comment]
That actually happens if `max_steps` is too low. Can you post your configuration?

**Comment by salvprest** [comment]
yes maybe max_steps is low
```
    "auth_service": "ptc",
    "username": "...",
    "password": "...",
    "location": "...",
    "gmapkey": "...",
    "max_steps": 1,
    "catch_pokemon": true,
    "websocket_server": false,
    "spin_forts": true,
    "walk": 4.16,
    "action_wait_min": 2,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": false,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "item_filter": {
      "1": { "keep" : 100 },
      "101": { "keep" : 10 },
      "102": { "keep" : 30 },
      "103": { "keep" : 30 },
      "201": { "keep" : 30 },
      "701": { "keep" : 100 }
    },
    "evolve_all": "NONE",
    "evolve_speed": 20,
    "evolve_cp_min": 300,
    "use_lucky_egg": false,
    "hatch_eggs": true,
    "longer_eggs_first": true,
    "evolve_captured": false,
    "release_pokemon": true,
    "spin_forts": {
      "avoid_circles": true,
      "max_circle_size": 5
    },
```
