### ISSUE TITLE
Just got this on the most recent commit

### ISSUE THREAD

**Issue by pmwoodward3** [PokemonGoF/PokemonGo-Bot#1618]
```
Traceback (most recent call last):
  File "pokecli.py", line 408, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "/opt/dev/pokemongo_bot/__init__.py", line 92, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/opt/dev/pokemongo_bot/cell_workers/seen_fort_worker.py", line 28, in work
    if (not self.should_run() or fort == None):
  File "/opt/dev/pokemongo_bot/cell_workers/seen_fort_worker.py", line 23, in should_run
    return self.config.spin_forts and self.bot.has_space_for_loot()
AttributeError: 'Namespace' object has no attribute 'spin_forts'

```

**Comment by xorinzor** [comment]
Do another `git pull` it's fixed already.
