### ISSUE TITLE
Bot doesn't start from fresh install

### ISSUE THREAD

**Issue by aleixsb** [PokemonGoF/PokemonGo-Bot#1620]
### Expected Behavior
I've followed all steps in the readme, but the bot don't start

### Actual Behavior

I'm getting this error:

[2016-07-29 07:57:14] [x] PokemonGO Bot v1.0
[2016-07-29 07:57:14] [x] Configuration initialized
[2016-07-29 07:57:14] 
[2016-07-29 07:57:14] [x] Address found: XXXX
[2016-07-29 07:57:14] [x] Position in-game set as: (XXXX)
[2016-07-29 07:57:14] 
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "/root/pyBot/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/root/pyBot/PokemonGo-Bot/pokemongo_bot/__init__.py", line 159, in _setup_api
    balls_stock = self.pokeball_inventory()
  File "/root/pyBot/PokemonGo-Bot/pokemongo_bot/__init__.py", line 234, in pokeball_inventory
    inventory_dict = inventory_req['responses']['GET_INVENTORY'][
KeyError: 'GET_INVENTORY'

### Steps to Reproduce
clone the master branch and follow the steps in the readme

### Other Information
OS: Ubuntu 16.04
it Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
3f1f8e321da1ee256659ef623730ee1efeb442d0

**Comment by TAiS46** [comment]
add `--config config.json` to your start command

**Comment by aleixsb** [comment]
same result

python pokecli.py --config config.json 
[2016-07-29 08:03:28] [x] PokemonGO Bot v1.0
[2016-07-29 08:03:28] [x] Configuration initialized
[2016-07-29 08:03:28] 
[2016-07-29 08:03:28] [x] Address found: XXXX
[2016-07-29 08:03:28] [x] Position in-game set as: (XXX)
[2016-07-29 08:03:28] 
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "/root/pyBot/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/root/pyBot/PokemonGo-Bot/pokemongo_bot/__init__.py", line 159, in _setup_api
    balls_stock = self.pokeball_inventory()
  File "/root/pyBot/PokemonGo-Bot/pokemongo_bot/__init__.py", line 234, in pokeball_inventory
    inventory_dict = inventory_req['responses']['GET_INVENTORY'][
KeyError: 'GET_INVENTORY'

**Comment by aleixsb** [comment]
I think I got something wrong with the requirements, now it's working.
