### ISSUE TITLE
(DEV) lured pokemon stop crashes cell worker

### ISSUE THREAD

**Issue by Philipp59** [PokemonGoF/PokemonGo-Bot#1625]
#**Error:** 
[14:07:40] Arrived at Pokestop
[14:07:50] [x] Next egg incubates in 4.12 km
[14:07:58] Moving towards fort 03d55664e8824ca69f8fa64c5af9dacc.16, 0.05km left

[14:07:58] Arrived at Pokestop
Traceback (most recent call last):
  File "pokecli.py", line 408, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "/Users/XXXXX/Desktop/bots/PokemonGo-Bot/pokemongo_bot/__init__.py", line 92, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/Users/XXXXX/Desktop/bots/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon_worker.py", line 47, in work
    lured_pokemon = self.get_lured_pokemon()
  File "/Users/XXXXX/Desktop/bots/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon_worker.py", line 53, in get_lured_pokemon
    fort = forts[0]
IndexError: list index out of range

**config used:**
    "max_steps": 5,
    "catch_pokemon": true,
    "forts": {
      "spin": true,
      "avoid_circles": true,
      "max_circle_size": 20
    },
    "websocket_server": true,
    "walk": 40,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": false,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "item_filter": {
      "1": { "keep" : 200 },
      "2": { "keep" : 50 },
      "3": { "keep" : 50 },
      "101": { "keep" : 0 },
      "102": { "keep" : 0 },
      "103": { "keep" : 0 },
      "104": { "keep" : 0 },
      "201": { "keep" : 0 },
      "202": { "keep" : 0 },
      "701": { "keep" : 0 }
    },
    "evolve_all": "Pidgey,Caterpie,Rattata,Weedle",
    "evolve_speed": 4,
    "evolve_cp_min": 10,
    "use_lucky_egg": false,
    "hatch_eggs": true,
    "longer_eggs_first": true,
    "evolve_captured": false,
    "release_pokemon": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"}
    },
    "release": {
      "any": {"release_below_cp": 9, "release_below_iv": 0.93, "logic": "or"},
      "Venusaur": {"keep_best_iv": 20},
      "Charizard": {"keep_best_iv": 20},
      "Blastoise": {"keep_best_iv": 20},
      "Onix": {"keep_best_iv": 2},
      "Hitmonlee": {"keep_best_iv": 3},
      "Hitmonchan": {"keep_best_iv": 3},
      "Chansey": {"keep_best_iv": 5},
      "Gyarados": {"keep_best_iv": 20},
      "Lapras": {"keep_best_iv": 20},
      "Ditto": {"keep_best_iv": 20},
      "Snorlax": {"keep_best_iv": 20},
      "Dragonite": {"keep_best_iv": 25},
      "Aerodactyl": {"keep_best_iv": 5},
      "Kabutops": {"keep_best_iv": 5},
      "Gengar": {"keep_best_iv": 20},
      "Alakazam": {"keep_best_iv": 20},
      "Raichu": {"keep_best_iv": 5},
      "Omastar": {"keep_best_iv": 5},
      "Electabuzz": {"keep_best_iv": 5},
      "Magmar": {"keep_best_iv": 5},
      "Nidoking": {"keep_best_iv": 5},
      "Nidoqueen": {"keep_best_iv": 5},
      "Dratini": {"keep_best_iv": 5},
      "Charmander": {"keep_best_iv": 2},
      "Charmeleon": {"keep_best_iv": 1},
      "Squirtle": {"keep_best_iv": 2},
      "Wartortle": {"keep_best_iv": 1},
      "Bulbasaur": {"keep_best_iv": 2},
      "Ivysaur": {"keep_best_iv": 1},
      "Pikachu": {"keep_best_iv": 2},
      "Abra": {"keep_best_iv": 2},
      "Gastly": {"keep_best_iv": 2},
      "Haunter": {"keep_best_iv": 1},
      "Pidgey": {"keep_best_cp": 10},
      "Caterpie": {"keep_best_cp": 10},
      "Weedle": {"keep_best_cp": 10},
      "Rattata": {"keep_best_cp": 5}
    }
}

might be related to #1607

**Comment by luki922** [comment]
I have this same error :/ 
```
[14:18:54] Moving towards fort 3ec6213cf7eb4a358e7db08a24126fd3.16, 0.11km left
[14:19:07] Moving towards fort 3ec6213cf7eb4a358e7db08a24126fd3.16, 0.11km left
[14:19:23] Moving towards fort 3ec6213cf7eb4a358e7db08a24126fd3.16, 0.11km left
[14:19:37] Moving towards fort 3ec6213cf7eb4a358e7db08a24126fd3.16, 0.10km left
Traceback (most recent call last):
  File "pokecli.py", line 408, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "/home/trick/Pobrane/pokemon2/bot/PokemonGo-Bot/pokemongo_bot/__init__.py", line 92, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/home/trick/Pobrane/pokemon2/bot/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon_worker.py", line 47, in work
    lured_pokemon = self.get_lured_pokemon()
  File "/home/trick/Pobrane/pokemon2/bot/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon_worker.py", line 53, in get_lured_pokemon
    fort = forts[0]
IndexError: list index out of range
```

**Comment by balpoint** [comment]
getting the samen error:

> Traceback (most recent call last):
  File "pokecli.py", line 408, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "/home/ddenouden/PokemonGo-Bot/pokemongo_bot/__init__.py", line 92, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/home/ddenouden/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon_worker.py", line 47, in work
    lured_pokemon = self.get_lured_pokemon()
  File "/home/ddenouden/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon_worker.py", line 53, in get_lured_pokemon
    fort = forts[0]
IndexError: list index out of range

**Comment by luki922** [comment]
I change this from config.json:
`    "spin_forts": true,`

to this:
```
    "forts": {
      "spin": true,
      "avoid_circles": true,
      "max_circle_size": 50
    },
```
and for now everythings working correctly :)

**Comment by djibb** [comment]
this works : 
    def get_lured_pokemon(self):
        forts = self.bot.get_forts(order_by_distance=True)
        try : 
            fort = forts[0]

            self.api.fort_details(fort_id=fort['id'],
                              latitude=fort['latitude'],
                              longitude=fort['longitude'])

            response_dict = self.api.call()
            fort_details = response_dict.get('responses', {}).get('FORT_DETAILS', {})
            fort_name = fort_details.get('name', 'Unknown').encode('utf8', 'replace')

            encounter_id = fort.get('lure_info', {}).get('encounter_id', None)

            pokemon = {
            'encounter_id': encounter_id,
            'fort_id': fort['id'],
            'latitude': fort['latitude'],
            'longitude': fort['longitude']
            }

            return pokemon
        except  IndexError:
            return None

**Comment by balpoint** [comment]
these settings are default in the latest dev version.
