### ISSUE TITLE
Everytime get the following error... Any suggestions:

### ISSUE THREAD

**Issue by Chrisvdberg** [PokemonGoF/PokemonGo-Bot#1626]
[14:20:55] PokemonGO Bot v1.0
[14:20:55] No config argument specified, checking for /configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 408, in <module>
    main()
  File "pokecli.py", line 52, in main
    config = init_config()
  File "pokecli.py", line 117, in init_config
    load.update(json.load(data))
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by vicch** [comment]
Have you read this https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files and created a config file?

**Comment by Chrisvdberg** [comment]
thnx!
