### ISSUE TITLE
KeyError: 'GET_INVENTORY' (full backpack/inventory?)

### ISSUE THREAD

**Issue by fulgidus** [PokemonGoF/PokemonGo-Bot#1633]
### Expected Behavior
Keep running (by deleting items himself I think, but I'm not sure)

### Actual Behavior
Crashing.
To temp fix it you have to open the actual Pokemon Go app and delete an item

### Steps to Reproduce
Not sure, probably when backpack fills up, I tried deleting a loto of stuff and it seems to be more stable (for now)

Trace:
```
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "/Users/myMacUser/Documents/Projects/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/Users/myMacUser/Documents/Projects/PokemonGo-Bot/pokemongo_bot/__init__.py", line 159, in _setup_api
    balls_stock = self.pokeball_inventory()
  File "/Users/myMacUser/Documents/Projects/PokemonGo-Bot/pokemongo_bot/__init__.py", line 234, in pokeball_inventory
    inventory_dict = inventory_req['responses']['GET_INVENTORY'][
KeyError: 'GET_INVENTORY'
```

### Other Information
OS: Mac _El Capitan 10.11.6 (15G31)_
> Python: 2.7.12
> Pip: 8.1.2
> Virtualenv: 15.0.2

Git Commit: ec2b7add95da6bc580035d8d4c472c1d41e439a6 `(ec2b7add95da6bc580035d8d4c472c1d41e439a6)`

**Comment by Lunik** [comment]
Duplicated #1491

**Comment by fulgidus** [comment]
Solved by: https://github.com/PokemonGoF/PokemonGo-Bot/pull/1499
