### ISSUE TITLE
[DEV] TypeError: unsupported operand type(s) for /: 'str' and 'int' 

### ISSUE THREAD

**Issue by h8rry** [PokemonGoF/PokemonGo-Bot#1635]
I am getting this error on linux (heroku), but local is fine

```
Traceback (most recent call last): 
  File "pokecli.py", line 389, in <module> 
    main() 
  File "pokecli.py", line 68, in main 
    bot.tick() 
  File "/app/pokemongo_bot/__init__.py", line 89, in tick 
    self.check_session(self.position[0:2]) 
  File "/app/pokemongo_bot/__init__.py", line 239, in check_session 
    remaining_time = self.api._auth_provider._ticket_expire/1000 - time.time() 
TypeError: unsupported operand type(s) for /: 'str' and 'int' 
```

**Comment by asnelzin** [comment]
Duplicated #1206
