### ISSUE TITLE
RuntimeError: Trying to transfer 0 pokemons!

### ISSUE THREAD

**Issue by tomqwu** [PokemonGoF/PokemonGo-Bot#1648]
### Other Information

```
[2016-07-29 14:57:54] [x] Captured Drowzee! [CP 127] [IV 0.31]
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "/usr/src/app/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/usr/src/app/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/usr/src/app/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/usr/src/app/pokemongo_bot/__init__.py", line 93, in work_on_cell
    worker.work()
  File "/usr/src/app/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 30, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "/usr/src/app/pokemongo_bot/stepper.py", line 88, in _walk_to
    alt, False)
  File "/usr/src/app/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/usr/src/app/pokemongo_bot/__init__.py", line 63, in work_on_cell
    if self.catch_pokemon(pokemon) == PokemonCatchWorker.NO_POKEBALLS:
  File "/usr/src/app/pokemongo_bot/__init__.py", line 190, in catch_pokemon
    return_value = worker.work()
  File "/usr/src/app/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 164, in work
    'Trying to transfer 0 pokemons!')
RuntimeError: Trying to transfer 0 pokemons!
```
OS: 
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
```
Git Commit: 3f1f8e321da1ee256659ef623730ee1efeb442d0

**Comment by millelog** [comment]
Getting the exact same issue consistently. at least every hour!
