### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by ftykazaf** [PokemonGoF/PokemonGo-Bot#1662]
I used http://jsonlint.com to correct format of config.json and it still not work.

Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 197, in main
    config = init_config()
  File "pokecli.py", line 64, in init_config
    load.update(json.load(data))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by ftykazaf** [comment]
And here is my json

{
	"auth_service": "google",
	"username": “name@gmail.com ",
	"password": “pw”,
	"location": "59.744329, 10.204808",
	"gmapkey": "key",
	"max_steps": 5,
	"mode": "all",
	"walk": 4.16,
	"debug": false,
	"test": false,
	"initial_transfer": 0,
	"location_cache": true,
	"distance_unit": "km",
	"item_filter": "101,102,103,104",
	"evolve_all": "NONE"
}

**Comment by FlorianKuehne** [comment]
There is a space behind your user-name and the ". furthermore it looks like there some false quotes.
like “ instead of " 
check the file with http://jsonlint.com/ like @Nihisil mentioned there:
https://github.com/PokemonGoF/PokemonGo-Bot/issues/738

**Comment by xorinzor** [comment]
like @FlorianKuehne mentioned, it's definitly the wrong type of quotes used. Check your configured keyboard layout, or just copy paste them from the other quotes.

**Comment by ftykazaf** [comment]
I corrected all quote and the problem fixed now! 
Thank you bro!
