### ISSUE TITLE
 Server seems to be busy or offline

### ISSUE THREAD

**Issue by TianCNCA** [PokemonGoF/PokemonGo-Bot#1663]
[11:33:46] PokemonGO Bot v1.0
[11:33:46] Configuration initialized
[11:33:46] [x] Coordinates found in passed in lo
[11:33:46]
[11:33:46] Location Found: -35.290398507977315,1
[11:33:46] GeoPosition: (13853535536212223835L,
[11:33:46]
[11:33:46] [x] Parsing cached location...
[11:33:46] [x] Parsing cached location failed, t
.
[11:33:46] Attempting login to Pokemon Go.
[11:33:47] Login to Pokemon Go successful.
[11:33:47] Server seems to be busy or offline -
[11:33:48] Server seems to be busy or offline -
[11:33:50] Server seems to be busy or offline -
[11:33:51] Server seems to be busy or offline -
[11:33:52] Server seems to be busy or offline -
Traceback (most recent call last):
  File "pokecli.py", line 417, in <module>
    main()
  File "pokecli.py", line 62, in main
    bot.start()
  File "C:\Tian\PokemonGo-Bot\pokemongo_bot\__in
    self._setup_api()
  File "C:\Tian\PokemonGo-Bot\pokemongo_bot\__in
i
    self._print_character_info()
  File "C:\Tian\PokemonGo-Bot\pokemongo_bot\__in
aracter_info
    response_dict = self.api.call()
  File "C:\Tian\PokemonGo-Bot\pokemongo_bot\api_
    raise ServerBusyOrOfflineException()
pgoapi.exceptions.ServerBusyOrOfflineException

Although I could log in from phone using the same account.
Anyone else experiencing the same issue?

**Comment by martijnvandijke** [comment]
just run the installation guide from the installation wiki

**Comment by TianCNCA** [comment]
I have all the requirements installed.

Now I'm having this error:
Traceback (most recent call last):
  File "pokecli.py", line 40, in <module>
    from pokemongo_bot import PokemonGoBot
  File "C:\Tian\PokemonGo-Bot\pokemongo_bot\__in
    from pgoapi.utilities import f2i, get_cell_i
ImportError: cannot import name get_cell_ids

**Comment by AlexBailey** [comment]
This issue is persistent and has been posted about a million times, so it's pointless me linking. If you search through the issues you'll find it's not to do with the code - it's that the servers are down at the time of you trying to connect. Try again now or a bit later and it'll work fine.

**Comment by TianCNCA** [comment]
Sorry it turns out my pgoapi was outdated. Reinstall it using pip and the issue is gone.

**Comment by paulohdc** [comment]
git reset --hard


git pull -f

pip install --upgrade -r requirements.txt

Traceback (most recent call last):
  File "pokecli.py", line 455, in <module>
  File "pokecli.py", line 79, in main
  File "pokecli.py", line 87, in report_summary
  File "C:\pk\PokemonGo-Bot-Dev P\pokemongo_bot\metrics.py", line 75, in capture_stats
  File "C:\pk\PokemonGo-Bot-Dev P\pokemongo_bot\api_wrapper.py", line 74, in call
pgoapi.exceptions.ServerBusyOrOfflineException
