### ISSUE TITLE
Error Trace

### ISSUE THREAD

**Issue by kanesharan** [PokemonGoF/PokemonGo-Bot#1687]
### Expected Behavior
I'm not sure what is causing this :( 

### Actual Behavior (ERROR Trace)
Traceback (most recent call last):
  File "./pokecli.py", line 220, in <module>
    main()
  File "./pokecli.py", line 211, in main
    bot.take_step()
  File "/Users/Kanesharan/Documents/POKEMON GIT/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/Users/Kanesharan/Documents/POKEMON GIT/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/Users/Kanesharan/Documents/POKEMON GIT/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/Users/Kanesharan/Documents/POKEMON GIT/PokemonGo-Bot/pokemongo_bot/__init__.py", line 93, in work_on_cell
    worker.work()
  File "/Users/Kanesharan/Documents/POKEMON GIT/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 30, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "/Users/Kanesharan/Documents/POKEMON GIT/PokemonGo-Bot/pokemongo_bot/stepper.py", line 84, in _walk_to
    self.bot.heartbeat()
  File "/Users/Kanesharan/Documents/POKEMON GIT/PokemonGo-Bot/pokemongo_bot/__init__.py", line 395, in heartbeat
    self.api.call()
  File "/Users/Kanesharan/Documents/POKEMON GIT/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 81, in call
    response = request.request(api_endpoint, self._req_method_list, player_position)
  File "/Users/Kanesharan/Documents/POKEMON GIT/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 100, in request
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException

### Steps to Reproduce
Occurs after an hour to 3 hours after running and terminates the bot.  

### Other Information
OS: Mac OS X El Capitan
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by buettner123** [comment]
Refer to this: https://github.com/PokemonGoF/PokemonGo-Bot/issues/948#issuecomment-235229012

**Comment by kanesharan** [comment]
Thanks!
