### ISSUE TITLE
'GET_INVENTORY' crash.

### ISSUE THREAD

**Issue by Zeper666** [PokemonGoF/PokemonGo-Bot#1716]
### Expected Behavior
work

### Actual Behavior
don't work

### Steps to Reproduce
start the bot and wait.

### Other Information
OS: Win10 x64
```

[23:16:16] PokemonGO Bot v1.0
[23:16:16] Configuration initialized
[23:16:16] [x] Coordinates found in passed in location, not geocoding.
[23:16:16]
[23:16:16] Location Found: 48.842606,2.360102
[23:16:16] GeoPosition: (48.842606, 2.360102, 0)
[23:16:16]
[23:16:16] Attempting login to Pokemon Go.
[23:16:18] Login to Pokemon Go successful.
[23:16:19]
[23:16:19] --- _**censure**_ ---
[23:16:19] Level: censure (Next Level: **_censure_** XP) (Total: **_censure_** XP)
[23:16:19] Pokemon Captured: 8928 | Pokestops Visited: 11424
[23:16:19] Pokemon Bag: 140/250
[23:16:19] Items: 255/350
[23:16:19] Stardust: 1802866 | Pokecoins: 30
[23:16:19] PokeBalls: 103 | GreatBalls: 28 | UltraBalls: 6
[23:16:19] RazzBerries: 1 | BlukBerries: 0 | NanabBerries: 0
[23:16:19] LuckyEgg: 3 | Incubator: 0 | TroyDisk: 5
[23:16:19] Potion: 1 | SuperPotion: 1 | HyperPotion: 50
[23:16:19] Incense: 5 | IncenseSpicy: 0 | IncenseCool: 0
[23:16:19] Revive: 50 | MaxRevive: 0
[23:16:19]
[23:16:19]
[23:16:22] Starting PokemonGo Bot....
[23:16:23] [x] Next egg incubates in 1.78 km
[23:16:24] -- Recycled 1x Potion (keeps only 0 maximum)
[23:16:25] -- Recycled 1x Super Potion (keeps only 0 maximum)
[23:16:35] Moving towards fort cdb6e1b07f444fe0b9c834ad0be93511.16, 0.05km left
[23:16:42] Arrived at pokestop.
[23:16:43] Spinning ...
[23:16:43] Loot:
[23:16:43] 50 xp
[23:16:44] - 4x Pokeball (Total: 106)
[23:16:44] PokeStop on cooldown. Time left: 4 minutes, 57 seconds
[23:16:46] Walking from (48.84272104175641, 2.360106320106897) to [48.84272104175641, 2.360106320106897] 0.00km
[23:16:47] Moving towards fort 3619ec64f5854f21b6f04ce76a18b822.16, 0.06km left
[23:16:53] Moving towards fort 3619ec64f5854f21b6f04ce76a18b822.16, 0.05km left
Traceback (most recent call last):
  File "pokecli.py", line 441, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "C:\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 93, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "C:\PokemonGo-Bot-dev\pokemongo_bot\cell_workers\pokemon_transfer_worker.py", line 19, in work
    pokemon_groups = self._release_pokemon_get_groups()
  File "C:\PokemonGo-Bot-dev\pokemongo_bot\cell_workers\pokemon_transfer_worker.py", line 84, in _release_pokemon_get_groups
    inventory_dict = inventory_req['responses']['GET_INVENTORY']['inventory_delta']['inventory_items']
KeyError: 'GET_INVENTORY'



```

**Comment by aTadTasty** [comment]
when was the last time you did a pip install -r requirements.txt?

**Comment by mjmadsen** [comment]
Trying the dev source. They've added a retry portion for the error.

**Comment by Zeper666** [comment]
@aTadTasty ,hum... one hour maybe.

@mjmadsen , okay

**Comment by ConflictWY** [comment]
Getting something similar.

`[16:09:21] Moving towards fort 975805c30dc6403ab07856c607e9e9a9.12, 0.05km left
[16:09:23] Server seems to be busy or offline - try again - 1/5
Traceback (most recent call last):
  File "pokecli.py", line 441, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "C:\Users\alexa\Desktop\PokemonGO\PokemonGo-Bot - Copy\pokemongo_bot\__init__.py", line 93, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "C:\Users\alexa\Desktop\PokemonGO\PokemonGo-Bot - Copy\pokemongo_bot\cell_workers\move_to_fort_worker.py", line 52, in work
    if not step_walker.step():
  File "C:\Users\alexa\Desktop\PokemonGO\PokemonGo-Bot - Copy\pokemongo_bot\step_walker.py", line 59, in step
    self.bot.heartbeat()
  File "C:\Users\alexa\Desktop\PokemonGO\PokemonGo-Bot - Copy\pokemongo_bot\__init__.py", line 494, in heartbeat
    self.update_web_location() # updates every tick
  File "C:\Users\alexa\Desktop\PokemonGO\PokemonGo-Bot - Copy\pokemongo_bot\__init__.py", line 139, in update_web_location
    cells = map_objects['map_cells']
KeyError: `'map_cells'``

**Comment by AwesomeGalS2** [comment]
Yeah, I'm having this problem. It logged you out. So you have to run `python pokecli.py` again until they fix it.

**Comment by h8rry** [comment]
Same

**Comment by gregtampa** [comment]
get the latest and run pip install -r requirments.txt
