### ISSUE TITLE
undefined symbol: _PyTrash_thread_deposit_object

### ISSUE THREAD

**Issue by mizhgan** [PokemonGoF/PokemonGo-Bot#1718]
Got a crash on startup on latest dev release after `git pull` and `sudo pip install -r requirements.txt`

```
Traceback (most recent call last):
  File "./pokecli.py", line 40, in <module>
    from pokemongo_bot import PokemonGoBot
  File "/home/mizhgan/Projects/clones/pogobot-dev/PokemonGo-Bot/pokemongo_bot/__init__.py", line 24, in <module>
    from pokemongo_bot.socketio_server.runner import SocketIoRunner
  File "/home/mizhgan/Projects/clones/pogobot-dev/PokemonGo-Bot/pokemongo_bot/socketio_server/runner.py", line 5, in <module>
    from eventlet import patcher, wsgi
  File "/usr/local/lib/python2.7/dist-packages/eventlet/patcher.py", line 4, in <module>
    from eventlet.support import six
  File "/usr/local/lib/python2.7/dist-packages/eventlet/support/__init__.py", line 4, in <module>
    from eventlet.support import greenlets, six
  File "/usr/local/lib/python2.7/dist-packages/eventlet/support/greenlets.py", line 3, in <module>
    import greenlet
ImportError: /usr/local/lib/python2.7/dist-packages/greenlet.so: undefined symbol: _PyTrash_thread_deposit_object
```

OS: Debian 7 64
Git Commit: 100830618d192ad7d8c15d790a3d1a243ec66362

**Comment by herpicus** [comment]
same

**Comment by hklcf** [comment]
same here

OS: Debian 7 64
79152bc65f8194ee9eb591fa657b99423771409e

**Comment by hklcf** [comment]
![image](https://cloud.githubusercontent.com/assets/410302/17268500/8cf4f984-565d-11e6-933a-abc820463275.png)

**Comment by hklcf** [comment]
![image](https://cloud.githubusercontent.com/assets/410302/17268505/c2afcd1a-565d-11e6-9ef0-6f5b423af54b.png)

**Comment by hklcf** [comment]
There's a quick solution for this.

`pip uninstall greenlet`
`easy_install greenlet`

**Comment by abs07** [comment]
@hklcf i tried reinstalling greenlet : same error
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2023

**Comment by ViaudThomas** [comment]
same
