### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by crusardri** [PokemonGoF/PokemonGo-Bot#172]
```
[#] Acccount Creation: 2016-07-17 11:26:59.748000
2016-07-22 13:42:13,859 [    pgoapi] [ INFO] Create new request...
2016-07-22 13:42:13,865 [    pgoapi] [ INFO] Adding 'GET_INVENTORY' to RPC request
2016-07-22 13:42:13,865 [    pgoapi] [ INFO] Execution of RPC
2016-07-22 13:42:14,072 [    pgoapi] [ INFO] Cleanup of request!
Exception during print player profile
2016-07-22 13:42:14,073 [    pgoapi] [ INFO] Create new request...
2016-07-22 13:42:14,078 [    pgoapi] [ INFO] Adding 'GET_INVENTORY' to RPC request
2016-07-22 13:42:14,078 [    pgoapi] [ INFO] Execution of RPC
2016-07-22 13:42:14,282 [    pgoapi] [ INFO] Cleanup of request!
[#] Scanning area for objects (1 / 25)
Traceback (most recent call last):
  File "C:\Users\Crusa\Desktop\PokemonGo\PokemonGo-Bot-master\pokecli.py", line 120, in <module>
    main()
  File "C:\Users\Crusa\Desktop\PokemonGo\PokemonGo-Bot-master\pokecli.py", line 117, in main
    bot.take_step()
  File "C:\Users\Crusa\Desktop\PokemonGo\PokemonGo-Bot-master\bot.py", line 29, in take_step
    self.stepper.take_step()
  File "C:\Users\Crusa\Desktop\PokemonGo\PokemonGo-Bot-master\stepper.py", line 45, in take_step
    self._walk_to(self.config.walk, *position)
  File "C:\Users\Crusa\Desktop\PokemonGo\PokemonGo-Bot-master\stepper.py", line 86, in _walk_to
    self.api.heartbeat()
  File "c:\users\crusa\desktop\pokemongo\pokemongo-bot-master\src\pgoapi\pgoapi\pgoapi.py", line 127, in __getattr__
    raise AttributeError
AttributeError

```
Anyone know why happen this?

**Comment by michi0987** [comment]
Same problem here
