### ISSUE TITLE
Crash at some pokestops?

### ISSUE THREAD

**Issue by PeteZilla** [PokemonGoF/PokemonGo-Bot#1730]
I keep receiving this error and the bot crashes each time it comes across it. **** = name changed, i'd be extremely grateful if anyone could offer some advice, bot is currently working in New york, central park

[2016-07-29 23:41:28] [#] Now at Pokestop: Strawberry Fields Plaque - Spinning...
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "/Users/*******/Desktop/PokemonGo-Bot-master/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/Users/*******/Desktop/PokemonGo-Bot-master/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/Users/*******/Desktop/PokemonGo-Bot-master/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/Users/*******/Desktop/PokemonGo-Bot-master/pokemongo_bot/__init__.py", line 96, in work_on_cell
    hack_chain = worker.work()
  File "/Users/*******/Desktop/PokemonGo-Bot-master/pokemongo_bot/cell_workers/seen_fort_worker.py", line 51, in work
    if spin_details['result'] == 1:
KeyError: 'result'

**Comment by BobbyWibowo** [comment]
The bot seems to crash occasionally. If you're too bothered with the crash, I recommend making a batch file which automatically restarts the bot upon crash.

Oh, don't get me wrong. It's best if you report the error lines to help development. I was just giving an alternative idea as I honestly have no idea as to what's wrong with those particular lines.

**Comment by PeteZilla** [comment]
im working on a mac so not sure how to make a batch file to do that on this, but thankyou anyhow

**Comment by BobbyWibowo** [comment]
If you're on a Mac, it's actually documented on the wiki: https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Restarting-bot(s)

**Comment by mufahaza** [comment]
I am get that error too. It happened with branch master and dev on my linux mint.
My temporary solution is creating batch file
`#!/bin/bash
while true
do
	python pokecli.py
done`

It is just simple script for infinite loop.
I hope developer can help us to fix this
