### ISSUE TITLE
Bot randomly not working anymore?

### ISSUE THREAD

**Issue by yehan77** [PokemonGoF/PokemonGo-Bot#1735]
### Expected Behavior
it working?

### Actual Behavior
cd '/Users/sooriay/PokemonGo-Bot/' && '/usr/local/bin/pythonw'  '/Users/sooriay/PokemonGo-Bot/pokecli.py'  && echo Exit status: $? && exit 1
sooriay:~ sooriay$ cd '/Users/sooriay/PokemonGo-Bot/' && '/usr/local/bin/pythonw'  '/Users/sooriay/PokemonGo-Bot/pokecli.py'  && echo Exit status: $? && exit 1
[2016-07-30 08:55:59] [x] PokemonGO Bot v1.0
[2016-07-30 08:55:59] [x] Configuration initialized
[2016-07-30 08:56:00] 
[2016-07-30 08:56:00] [x] Address found: Redfern St, Redfern NSW 2016
[2016-07-30 08:56:00] [x] Position in-game set as: (-33.8929081, 151.2048161, 0.0)
[2016-07-30 08:56:00] 
Traceback (most recent call last):
  File "/Users/sooriay/PokemonGo-Bot/pokecli.py", line 220, in <module>
    main()
  File "/Users/sooriay/PokemonGo-Bot/pokecli.py", line 206, in main
    bot.start()
  File "/Volumes/UserData/Users/sooriay/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/Volumes/UserData/Users/sooriay/PokemonGo-Bot/pokemongo_bot/__init__.py", line 151, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
TypeError: 'bool' object has no attribute '__getitem__'
sooriay:PokemonGo-Bot sooriay$ 

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by larssy1** [comment]
Sometimes there is a simple 'miscommunication' between the client and server, trying to re-execute the command might already 'fix' the problem for you :)

Another thing you could do is update to the 'dev' branch, which is not necessarily stable, but I haven't had that issue ever since I jumped to the dev branch myself :)

**Comment by yehan77** [comment]
Okay, also after 30minutes or so of running the bot i get some error which causes me to restart the bot. Il post the log soon once it happens, and il try re execute it now and see

**Comment by yehan77** [comment]
Ok! Thanks, working now. Just re-executed it

**Comment by PeteZilla** [comment]
i'm having the same problem, how do i re-execute?
