### ISSUE TITLE
MissingSchema: No schema supplied

### ISSUE THREAD

**Issue by J102030** [PokemonGoF/PokemonGo-Bot#1736]
### Expected Behavior
Bot to startup

### Actual Behavior
Fails to run before login complete

### Steps to Reproduce
python pokecli.py -cf ./configs/config.json

### Other Information
OS: Windows 7
Git Commit: b9aff7a3ecbd8b1429da593f78d9155790f6cbc2

[19:11:06] Attempting login to Pokemon Go.
Traceback (most recent call last):
  File "pokecli.py", line 450, in <module>
    main()
  File "pokecli.py", line 62, in main
    bot.start()
  File "C:\Users\AndrewNote\Desktop\GoBOT\PKGOBOT\PokemonGo-Bot-dev - Copy\PokemonGo-Bot\pokemongo_bot\__init__.py", line 65, in start
    self._setup_api()
  File "C:\Users\AndrewNote\Desktop\GoBOT\PKGOBOT\PokemonGo-Bot-dev - Copy\PokemonGo-Bot\pokemongo_bot\__init__.py", line 267, in _setup_api
    self.login()
  File "C:\Users\AndrewNote\Desktop\GoBOT\PKGOBOT\PokemonGo-Bot-dev - Copy\PokemonGo-Bot\pokemongo_bot\__init__.py", line 252, in login
    str(self.config.password)):
  File "C:\Users\AndrewNote\Desktop\GoBOT\PKGOBOT\PokemonGo-Bot-dev - Copy\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 83, in login
    return self._api.login(provider, username, password)
  File "C:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 126, in login
    response = request.call()
  File "C:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 182, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "C:\Python27\lib\site-packages\pgoapi\rpc_api.py", line 104, in request
    response = self._make_rpc(endpoint, request_proto)
  File "C:\Python27\lib\site-packages\pgoapi\rpc_api.py", line 92, in _make_rpc
    http_response = self._session.post(endpoint, data=request_proto_serialized)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 461, in request
    prep = self.prepare_request(req)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 394, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Python27\lib\site-packages\requests\models.py", line 295, in prepare
    self.prepare_url(url, params)
  File "C:\Python27\lib\site-packages\requests\models.py", line 355, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?

**Comment by Zeper666** [comment]
i've the same just get the latest and run pip install -r requirments.txt
