### ISSUE TITLE
Syntax error in master

### ISSUE THREAD

**Issue by harsh1412** [PokemonGoF/PokemonGo-Bot#174]
Traceback (most recent call last):
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-master\pokecli.py", line 41, in <
module>
    from bot import PokemonGoBot
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-master\bot.py", line 47
    else if self.noballs and self.ballstock[1] < 50:
          ^
SyntaxError: invalid syntax

**Comment by millejosh** [comment]
Download latest zip. this was fixed with #164

**Comment by harsh1412** [comment]
Thanks working now
