### ISSUE TITLE
Bot Crash Issue

### ISSUE THREAD

**Issue by magieR1337** [PokemonGoF/PokemonGo-Bot#1745]
My Bot crashes after it captures a Pokemon. 

This is the Issue code but i dont know how to handle it xD

[2016-07-30 03:25:04] [x] Captured Charmander! [CP 36] [IV 0.44]
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "E:\Python\pokemongo_bot\__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "E:\Python\pokemongo_bot\stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "E:\Python\pokemongo_bot\stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "E:\Python\pokemongo_bot\__init__.py", line 93, in work_on_cell
    worker.work()
  File "E:\Python\pokemongo_bot\cell_workers\move_to_fort_worker.py", line 30, i
n work
    self.stepper._walk_to(self.config.walk, *position)
  File "E:\Python\pokemongo_bot\stepper.py", line 88, in _walk_to
    alt, False)
  File "E:\Python\pokemongo_bot\stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "E:\Python\pokemongo_bot\__init__.py", line 63, in work_on_cell
    if self.catch_pokemon(pokemon) == PokemonCatchWorker.NO_POKEBALLS:
  File "E:\Python\pokemongo_bot\__init__.py", line 190, in catch_pokemon
    return_value = worker.work()
  File "E:\Python\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 158,
 in work
    if self.should_release_pokemon(pokemon_name, cp, pokemon_potential, response
_dict):
  File "E:\Python\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 238,
 in should_release_pokemon
    release_config = self._get_release_config_for(pokemon_name)
  File "E:\Python\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 280,
 in _get_release_config_for
    release_config = self.config.release_config['any']
KeyError: 'any'

I have Windows 7 
need heeelp!!!

greets

**Comment by gregtampa** [comment]
"NO_POKEBALLS:"
thats your problem

**Comment by magieR1337** [comment]
That can't be the problem because i got 150 pokeballs in my backpack.

**Comment by h4ckm03d** [comment]
@magieR1337 `release_config = self.config.release_config['any']` problem get `any` key from release config. make sure to put `any` rule on config.

example config using dev branch 
```
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
```

if using master branch make sure to rename release_config.json.example to release_config.json
