### ISSUE TITLE
KeyError: 'profile' when running

### ISSUE THREAD

**Issue by Khyol** [PokemonGoF/PokemonGo-Bot#176]
```
Traceback (most recent call last):
  File "pokecli.py", line 120, in <module>
    main()
  File "pokecli.py", line 114, in main
    bot.start()
  File "/home/xxx/PokemonGo-Bot/bot.py", line 24, in start
    self._setup_api()
  File "/home/xxx/PokemonGo-Bot/bot.py", line 155, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['profile']
KeyError: 'profile'
```
I'm having this error whenever i'm trying to run the client , the response doesn't have any "profile" but a "player_data" , so this makes me wondering , is this bot outdated?

**Comment by ferbeb** [comment]
Could it be that this happens if no ingame name has yet been picked? I just created a ptc account, set neither a display name or ever went ingame, except of the java bot that seems to work. I am getting the same error.

**Comment by berend** [comment]
this happen, when servers are flaky and do not deliver proper response. I tried to debug into this, but when I ran it again, it worked.

If somebody has content of the `response`, please post it here

**Comment by ferbeb** [comment]
I think it has been changed to player_data already to accommodate the new API, or am I confusing this with something else? Maybe it would help if people checked the issues when pushing fixes.

**Comment by berend** [comment]
another idea:
Did complete the initial setup in the app? Or just create an account and throw that one into the bot?

WIthout proper setting up, this data might be not complete, thus the key errors

**Comment by jtdroste** [comment]
This is due to an API change.

Please use the latest dev version.
