### ISSUE TITLE
NotLoggedInException

### ISSUE THREAD

**Issue by jnguyen32** [PokemonGoF/PokemonGo-Bot#1785]
I've attempted this in Windows, OSX and CentOS.

Fresh clone using:

git clone https://github.com/PokemonGoF/PokemonGo-Bot.git
cd PokemonGo-Bot
git checkout dev

... run through install systems ...

No issues doing pip install -r requirements.txt or ./install.sh or any of them.

I set up the config.json in ~configs/config.json per the config example

I've attempted both Google and PTC accounts.

When I run, I get:

[22:38:03] PokemonGO Bot v1.0
[22:38:03] No config argument specified, checking for /configs/config.json
[22:38:04] Configuration initialized
[22:38:04] Not logged in!!
Traceback (most recent call last):
  File "pokecli.py", line 454, in <module>
    main()
  File "pokecli.py", line 78, in main
    report_summary(bot)
  File "pokecli.py", line 86, in report_summary
    metrics.capture_stats()
  File "C:\Users\John\Documents\Projects\PokemonGo-Bot\pokemongo_bot\metrics.py", line 75, in capture_stats
    response_dict = self.bot.api.call()
  File "C:\Users\John\Documents\Projects\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 57, in call
    if not self._can_call():
  File "C:\Users\John\Documents\Projects\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 29, in _can_call
    raise NotLoggedInException()

When I look at the code, it fails when

bot.start()

is called, which is a result of:

if self._api._auth_provider is None or not self._api._auth_provider.is_login():
            logger.log('Not logged in', 'red')
            raise NotLoggedInException()

For some reason

self.api.auth_provider is always None and my configuration settings are corretc.

**Comment by jnguyen32** [comment]
I found the issue. The "location" value in config.json MUST be latitude longitude. You can't put in a Google Map description such as "Balboa Park, San Diego, CA"
