### ISSUE TITLE
No module named socketIO_client

### ISSUE THREAD

**Issue by ivivanov** [PokemonGoF/PokemonGo-Bot#1794]
### Actual Behavior
throws an exception

### Steps to Reproduce
just run the pocecli.py

### Other Information
after last git pull
OS: Windows 10

Error:

Traceback (most recent call last):
  File "C:\GitProjects\PokemonGo-Bot\pokecli.py", line 40, in <module>
    from pokemongo_bot import PokemonGoBot
  File "C:\GitProjects\PokemonGo-Bot\pokemongo_bot\__init__.py", line 24, in <module>
    from pokemongo_bot.event_handlers import LoggingHandler, SocketIoHandler
  File "C:\GitProjects\PokemonGo-Bot\pokemongo_bot\event_handlers\__init__.py", line 2, in <module>
    from socketio_handler import SocketIoHandler
  File "C:\GitProjects\PokemonGo-Bot\pokemongo_bot\event_handlers\socketio_handler.py", line 1, in <module>
    from socketIO_client import SocketIO
ImportError: No module named socketIO_client

**Comment by hklcf** [comment]
There's a quick solution for this.

`pip uninstall greenlet`
`easy_install greenlet`

**Comment by ivivanov** [comment]
Sorry i found its a duplicate issue
