### ISSUE TITLE
bot dies printing unicode to console

### ISSUE THREAD

**Issue by mercuriete** [PokemonGoF/PokemonGo-Bot#1813]
### Expected Behavior
Continue moving

### Actual Behavior

Traceback (most recent call last):
  File "pokecli.py", line 464, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "/usr/src/app/pokemongo_bot/__init__.py", line 84, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/usr/src/app/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 43, in work
    logger.log('Moving towards fort {}, {} left'.format(fort_name, format_dist(dist, unit)))
  File "/usr/src/app/pokemongo_bot/logger.py", line 21, in log
    print('[' + time.strftime("%H:%M:%S") + '] ' + string)
  File "/usr/local/lib/python2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 41: ordinal not in range(128)

### Steps to Reproduce

clone commit 2f277fd7d08ff9a7ad45cf46e102a00db7ba9fdf

when a fort have some weird characters... the bot crash

### Other Information
OS: Gentoo Linux x64 + docker
Git Commit: 2f277fd7d08ff9a7ad45cf46e102a00db7ba9fdf

**Comment by mercuriete** [comment]
Sorry for open an issue that is currently being fixed
https://github.com/PokemonGoF/PokemonGo-Bot/pull/1809

Thanks!
