### ISSUE TITLE
Errors installing new bot

### ISSUE THREAD

**Issue by lowwww** [PokemonGoF/PokemonGo-Bot#1832]
updated to the latest dev branch. After pip install requirements I get:
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hCOMwd/pycryptodomex/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-sW5WeQ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-hCOMwd/pycryptodomex/

Running the pokecli script gives me:
root@xxxx:~/PokemonGo-Bot# python pokecli.py --config ./configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException
ImportError: No module named pgoapi.exceptions

Previous version worked fine (also using the install guide, which is now shorter?)

**Comment by hklcf** [comment]
install pgoapi first

**Comment by lowwww** [comment]
more errors:

root@vpsxxx:~/PokemonGo-Bot# python pokecli.py --config ./configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 19, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 36, in <module>
    from pgoapi.auth_google import AuthGoogle
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/auth_google.py", line 31, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "/usr/local/lib/python2.7/dist-packages/gpsoauth-0.3.0-py2.7.egg/gpsoauth/__init__.py", line 4, in <module>
    from . import google
  File "/usr/local/lib/python2.7/dist-packages/gpsoauth-0.3.0-py2.7.egg/gpsoauth/google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
ImportError: No module named Cryptodome.PublicKey

**Comment by larssy1** [comment]
Had the same issue regarding the NotLoggedInException, running the install.sh again fixed it for me :)

**Comment by lowwww** [comment]
install.sh gives me more errors. I even reset my VPS with a clean ubuntu 14 again. installed all the things needed (and where the previous version worked with) and it still isn't working :(

**Comment by lowwww** [comment]
Reinstalled my vps with ubuntu 14. Now requirements seems to install without error. When trying to run I get this error:

root@vps302521:~/PokemonGo-Bot# python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 13, in <module>
    from pgoapi import PGoApi
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 19, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 42, in <module>
    from POGOProtos.Networking.Envelopes_pb2 import RequestEnvelope
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/protos/POGOProtos/Networking/Envelopes_pb2.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
ImportError: cannot import name symbol_database
root@vps302521:~/PokemonGo-Bot#

**Comment by Skeyelab** [comment]
getting the same issue on ubuntu 14
