### ISSUE TITLE
ImportError: No module named googlemaps

### ISSUE THREAD

**Issue by drew93** [PokemonGoF/PokemonGo-Bot#1835]
andrea@ubunturemoto:~/PokemonGo-Bot$ python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "/home/andrea/PokemonGo-Bot/pokemongo_bot/__init__.py", line 4, in <module>
    import googlemaps
ImportError: No module named googlemaps

what i do wrong?

### Other Information
OS: 
ubuntu 14.04

**Comment by AnaCosteira** [comment]
Have you run these commands:
$ virtualenv .
$ source bin/activate
$ pip install -r requirements.txt
$ git submodule init
$ git submodule update
?

The only time I got that error was because I forgot them.

**Comment by marksweb** [comment]
You haven't installed the python requirements if you see a 'no module' error.

Run `pip install -r requirements.txt`

**Comment by drew93** [comment]
ok now it work, but there is another problem


___________________________________
[2016-07-30 14:30:29] [x] PokemonGO Bot v1.0
[2016-07-30 14:30:29] [x] Configuration initialized
[2016-07-30 14:30:29] [x] Coordinates found in passed in location, not geocoding.
[2016-07-30 14:30:29] 
[2016-07-30 14:30:29] [x] Address found: blabla
[2016-07-30 14:30:29] [x] Position in-game set as: (blabla)
[2016-07-30 14:30:29] 
Traceback (most recent call last):
  File "1.py", line 220, in <module>
    main()
  File "1.py", line 206, in main
    bot.start()
  File "/home/andrea/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/home/andrea/PokemonGo-Bot/pokemongo_bot/__init__.py", line 151, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
TypeError: 'bool' object has no attribute '__getitem__'
(PokemonGo-Bot) andrea@ubunturemoto:~/PokemonGo-Bot$

**Comment by drew93** [comment]
nope solved
