### ISSUE TITLE
crash : UnicodeDecodeError:

### ISSUE THREAD

**Issue by mehdi-S** [PokemonGoF/PokemonGo-Bot#1837]
### Expected Behavior
work normally

### Actual Behavior
```
Traceback (most recent call last):
  File "pokecli.py", line 464, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "/root/bot2/pokemongo_bot/__init__.py", line 84, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/root/bot2/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 43, in work
    logger.log('Moving towards fort {}, {} left'.format(fort_name, format_dist(dist, unit)))
  File "/root/bot2/pokemongo_bot/logger.py", line 21, in log
    print('[' + time.strftime("%H:%M:%S") + '] ' + string)
  File "/usr/lib/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 31: ordinal not in range(128)

```

### Steps to Reproduce
pull, config, launch

### Other Information
OS: Debian x86_x64
Git Commit: 2f277fd7d08ff9a7ad45cf46e102a00db7ba9fdf

**Comment by hklcf** [comment]
Duplicate
#1814
