### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Chudopoke** [PokemonGoF/PokemonGo-Bot#1841]
`Traceback (most recent call last):
  File "pokecli.py", line 219, in <module>
    main()
  File "pokecli.py", line 205, in main
    bot.start()
  File "C:\POKEGo\PokemonGo-ChudoA\pokemongo_bot\__init__.py", line 31, in start
    self._setup_api()
  File "C:\POKEGo\PokemonGo-ChudoA\pokemongo_bot\__init__.py", line 145, in _setup_api
    response_dict = self.api.call()
  File "c:\pokego\pokemongo-chudobart3\src\pgoapi\pgoapi\pgoapi.py", line 89, in __getattr__
    raise AttributeError
AttributeError`

**Comment by iDervy** [comment]
This is an issue with Pogoapi. The latest api version is not compatible with the master branch of PoGo-Bot. 

Unfortunately, we'll need to either wait for the API to be fixed, or someone needs to be kind and upload an older version of PogoAPI
