### ISSUE TITLE
Get Inventory Error

### ISSUE THREAD

**Issue by daz3ds** [PokemonGoF/PokemonGo-Bot#1847]
### Expected Behavior
`
Traceback (most recent call last):
  File "pokecli.py", line 291, in <module>
    main()
  File "pokecli.py", line 251, in main
    bot.start()
  File "/home/pokemon/PokemonGo-Bot/pokemongo_bot/__init__.py", line 43, in start
    self._setup_api()
  File "/home/pokemon/PokemonGo-Bot/pokemongo_bot/__init__.py", line 234, in _setup_api
    self._print_character_info()
  File "/home/pokemon/PokemonGo-Bot/pokemongo_bot/__init__.py", line 265, in _print_character_info
    items_stock = self.current_inventory()
  File "/home/pokemon/PokemonGo-Bot/pokemongo_bot/__init__.py", line 335, in current_inventory
    inventory_dict = inventory_req['responses']['GET_INVENTORY'][
KeyError: 'GET_INVENTORY'
`
I get this error after a while of leaving the bot on, it cannot be fixed until i log into the app on my phone and restart the bot. Its normally also comes after a GET_GYM error and I restart the bot

**Comment by LasseSkogland** [comment]
I've got this error several times, seems to have something to do with overloaded servers.
What fixes it for me is to restart the bot (sometimes several times).

**Comment by yyz20002008** [comment]
same issue
