### ISSUE TITLE
Always "Not logged in!"

### ISSUE THREAD

**Issue by kendertas** [PokemonGoF/PokemonGo-Bot#1854]
### Expected Behavior
bot logging in and working

### Actual Behavior
[15:42:45] PokemonGO Bot v1.0
[15:42:45] Configuration initialized
[15:42:45] Not logged in!
Traceback (most recent call last):
  File "./pokecli.py", line 464, in <module>
    main()
  File "./pokecli.py", line 79, in main
    report_summary(bot)
  File "./pokecli.py", line 87, in report_summary
    metrics.capture_stats()
  File "S:\Software\scripts\PokemonGo-Bot\pokemongo_bot\metrics.py", line 75, in capture_stats
    response_dict = self.bot.api.call()
  File "S:\Software\scripts\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 57, in call
    if not self._can_call():
  File "S:\Software\scripts\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 29, in _can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException

### Steps to Reproduce
always running pokecly.py
./pokecli.py --config configs/config-nocache.json
./pokecli.py

### Other Information
OS: Windows 10 Home
Git Commit: 2f277fd7d08ff9a7ad45cf46e102a00db7ba9fdf

Thanks in advanced.

**Comment by kendertas** [comment]
For some reason, location entered in config.json was the problem... Inserted another one, and now it works.

**Comment by MartinTerp** [comment]
yea same here, i wrote a place (which works for the pgoapi) but it worked after i changed it to cordinates

**Comment by Acuchillar** [comment]
There is no way to get an altitude into the "location" string config.  Without it, it will deny login.  Need to add a third required field in location for altitude.

workaround is to change `_get_pos_by_name` function in `__init__.py` early return and place the correct altitude in the third argument, which is currently `float(0.0)`
