### ISSUE TITLE
[dev] Nidoran Error because of special character

### ISSUE THREAD

**Issue by toremielck** [PokemonGoF/PokemonGo-Bot#1855]
**I thibk this error is caused by the special characters for female / male in Nidoran's name**

Traceback (most recent call last):
  File "pokecli.py", line 464, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "/Users/toremielck/Desktop/PokemonGo-Bot-silosilosiloPTC/pokemongo_bot/__init__.py", line 84, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/Users/toremielck/Desktop/PokemonGo-Bot-silosilosiloPTC/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 43, in work
    logger.log('Moving towards fort {}, {} left'.format(fort_name, format_dist(dist, unit)))
  File "/Users/toremielck/Desktop/PokemonGo-Bot-silosilosiloPTC/pokemongo_bot/logger.py", line 21, in log
    print('[' + time.strftime("%H:%M:%S") + '] ' + string)
  File "/Users/toremielck/Desktop/PokemonGo-Bot-silosilosiloPTC/lib/python2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 49: ordinal not in range(128)

**Comment by mercuriete** [comment]
There are some work in progress i think

PR: https://github.com/PokemonGoF/PokemonGo-Bot/pull/1809

**Comment by glitchsnob** [comment]
This is working for me.

change line in logger.py to the following

`print('[' + time.strftime("%H:%M:%S") + '] ' + string.decode('utf-8'))`


credit to another commentator on a previous issues
