### ISSUE TITLE
[Dev] Bot turns of right after start-up

### ISSUE THREAD

**Issue by keklol123** [PokemonGoF/PokemonGo-Bot#1859]
So as soon i load the latest Dev, it just turn off.. Master works fine.
It gives up the status from the run and then this:

[16:25:57] Starting PokemonGo Bot....
[16:25:58] [x] Next egg incubates in 4.78 km
[16:25:59]
[16:25:59] Ran for 0:00:07
[16:25:59] Total XP Earned: 0  Average: 0.00/h
[16:25:59] Travelled 0.00km
[16:25:59] Visited 0 stops
[16:25:59] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
[16:25:59] Threw 0 pokeballs
[16:25:59] Earned 0 Stardust
[16:25:59]
[16:25:59] Highest CP Pokemon:
[16:25:59] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 464, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "C:\go\dev\PokemonGo-Bot\pokemongo_bot\__init__.py", line 84, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "C:\go\dev\PokemonGo-Bot\pokemongo_bot\cell_workers\move_to_fort_worker.py", line 43, in work
    logger.log('Moving towards fort {}, {} left'.format(fort_name, format_dist(dist, unit)))
  File "C:\go\dev\PokemonGo-Bot\pokemongo_bot\logger.py", line 21, in log
    print('[' + time.strftime("%H:%M:%S") + '] ' + string)
  File "C:\Python27\lib\codecs.py", line 357, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 42: ordinal not in range(128)

**Comment by Gregwar** [comment]
This is because `.decode('utf-8')` should be added on line 21 of `logger.py`:
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/logger.py#L21

**Comment by keklol123** [comment]
Thanks, works great now!
