### ISSUE TITLE
Updated bot and now I get AttributeError

### ISSUE THREAD

**Issue by BrianDawson** [PokemonGoF/PokemonGo-Bot#1888]
I have tried reinstalling requirements and I still get this error:

```
PokemonGo-Bot git:(master) python pokecli.py
[2016-07-30 17:28:29] [x] PokemonGO Bot v1.0
[2016-07-30 17:28:29] [x] Configuration initialized
[2016-07-30 17:28:29] [x] Coordinates found in passed in location, not geocoding.
[2016-07-30 17:28:29]
[2016-07-30 17:28:29] [x] Address found: 44.8156213,-91.504391
[2016-07-30 17:28:29] [x] Position in-game set as: (44.8156213, -91.504391, 0.0)
[2016-07-30 17:28:29]
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "/home/nitrous/code/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/home/nitrous/code/PokemonGo-Bot/pokemongo_bot/__init__.py", line 146, in _setup_api
    response_dict = self.api.call()
  File "/home/nitrous/code/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 89, in __getattr__
    raise AttributeError
AttributeError

```

**Comment by mrthrowaway** [comment]
I would try `pip install -r requirements.txt --upgrade`

**Comment by BrianDawson** [comment]
I tried that, no luck. :/
