### ISSUE TITLE
Newest dev throws error ImportError: No module named gpxpy

### ISSUE THREAD

**Issue by Aaranaw** [PokemonGoF/PokemonGo-Bot#1905]
### Expected Behavior
No error

### Actual Behavior
Bot throws error 
`Traceback (most recent call last):
  File "pokecli.py", line 40, in <module>
    from pokemongo_bot import PokemonGoBot
  File "/opt/PokemonGo-Bot/pokemongo_bot/__init__.py", line 18, in <module>
    import navigators
  File "/opt/PokemonGo-Bot/pokemongo_bot/navigators/__init__.py", line 2, in <module>
    from path_navigator import PathNavigator
  File "/opt/PokemonGo-Bot/pokemongo_bot/navigators/path_navigator.py", line 3, in <module>
    import gpxpy
ImportError: No module named gpxpy
`

### Steps to Reproduce
Install latest dev launch bot from terminal 
`mate-terminal -x sh -c '(python pokecli.py -cf configs/account1.json) ; exec /bin/bash -i' &`

**Comment by mrthrowaway** [comment]
Need to update requirements

`pip install -r requirements.txt --upgrade`

**Comment by Aaranaw** [comment]
Thats it thanks.
