### ISSUE TITLE
[DEV] Bot crashing, when using path navigator

### ISSUE THREAD

**Issue by iPression** [PokemonGoF/PokemonGo-Bot#1906]
### Expected Behavior
Bot working correctly

### Actual Behavior
Bot crashing

### Steps to Reproduce
```
Traceback (most recent call last):
  File "pokecli.py", line 497, in <module>
    main()
  File "pokecli.py", line 62, in main
    bot.start()
  File "/Users/Patrick/PokemonGO/dev/PokemonGo-Bot/pokemongo_bot/__init__.py", line 60, in start
    self.navigator=navigators.PathNavigator(self)
  File "/Users/Patrick/PokemonGO/dev/PokemonGo-Bot/pokemongo_bot/navigators/path_navigator.py", line 20, in __init__
    self.points = self.load_path()
  File "/Users/Patrick/PokemonGO/dev/PokemonGo-Bot/pokemongo_bot/navigators/path_navigator.py", line 27, in load_path
    return self.load_json(self.config.navigator_path_file)
  File "/Users/Patrick/PokemonGO/dev/PokemonGo-Bot/pokemongo_bot/navigators/path_navigator.py", line 33, in load_json
    return json.load(data_file)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting : delimiter: line 2 column 10 (char 66)

```
### Other Information
OS: OS X
Git Commit: 9ba808f491b8cd81514c3894820ca515226cf571

**Comment by iPression** [comment]
Wrong format of path.json.

Used 
`   {"lat"=40.773481251816435, "lon"=-73.97303938865662},`
instead of
`        {"lng":8.043531775474547,"lat":52.27777834853098},
`
