### ISSUE TITLE
[DEV] Unable to login

### ISSUE THREAD

**Issue by lucaarce** [PokemonGoF/PokemonGo-Bot#1908]
### Expected Behavior
Successfully login

### Actual Behavior
[21:12:52]  PokemonGO Bot v1.0 
[21:12:52]  No config argument specified, checking for /configs/config.json 
[21:12:52]  Configuration initialized 
[21:12:52]  Not logged in! 
Traceback (most recent call last):
  File "pokecli.py", line 497, in <module>
    main()
  File "pokecli.py", line 79, in main
    report_summary(bot)
  File "pokecli.py", line 87, in report_summary
    metrics.capture_stats()
  File "/home/luca/tmp/PokemonGo-Bot/pokemongo_bot/metrics.py", line 75, in capture_stats
    response_dict = self.bot.api.call()
  File "/home/luca/tmp/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 57, in call
    if not self._can_call():
  File "/home/luca/tmp/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 29, in _can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException

### Steps to Reproduce
Run the bot
python pokecli.py

### Other Information
OS: ArchLinux
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
9ba808f491b8cd81514c3894820ca515226cf571

The bot used to work a few hours ago

**Comment by lucaarce** [comment]
Apparently the problem was caused by the location

**Comment by zwhitchcox** [comment]
What are we supposed to put for the location? I put `San Diego, CA` and `San Francisco, CA`, and neither worked.

**Comment by zwhitchcox** [comment]
Never mind, I see now we're supposed to put in the latitude and longitude manually
