### ISSUE TITLE
Program stops after a while

### ISSUE THREAD

**Issue by xterraforcex** [PokemonGoF/PokemonGo-Bot#1911]
Traceback (most recent call last):
  File "pokecli.py", line 455, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "/home/xterraforcex/PokemonGo-Bot/pokemongo_bot/__init__.py", line 84, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/xterraforcex/PokemonGo-Bot/pokemongo_bot/cell_workers/incubate_eggs_worker.py", line 29, in work
    self._hatch_eggs()
  File "/home/xterraforcex/PokemonGo-Bot/pokemongo_bot/cell_workers/incubate_eggs_worker.py", line 134, in _hatch_eggs
    for pokemon in pokemon_data:
UnboundLocalError: local variable 'pokemon_data' referenced before assignment

what do i need to do to let it keep going

**Comment by mrthrowaway** [comment]
I believe this was fixed recently in commit 9b2450a7d81b33e0b46cf355c3d4ac9c82e92cfa

**Comment by sgitkene** [comment]
loop the command in run.sh
or copy the line that starts with eval a few times
