### ISSUE TITLE
python pokecli.py -cf ./configs/config.json error

### ISSUE THREAD

**Issue by cmorbaab** [PokemonGoF/PokemonGo-Bot#1916]
I keep on getting this error when running the pokecli.py file

`python pokecli.py -cf ./configs/config.json
[22:35:45] PokemonGO Bot v1.0
[22:35:45] No config argument specified, checking for /configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 417, in <module>
    main()
  File "pokecli.py", line 52, in main
    config = init_config()
  File "pokecli.py", line 117, in init_config
    load.update(json.load(data))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 174 column 7 (char 8537)`

I looked over my json files and there were no errors there. Is there a way to fix this?

### Other Information
OS: 10.11.6
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by samjack** [comment]
check your config.json [jsonlint](http://jsonlint.com/)

**Comment by sgitkene** [comment]
It says "no config argument specified". maybe you have mistyped the command or argument or option. also post your config just to be safe?

**Comment by cmorbaab** [comment]
It turns out that my config.json file had a syntax error. I replaced it with file on git hub and it worked. Thanks.

**Comment by CtrlAltDefeat94** [comment]
My json file doesn't work and that site says my file is valid.

**Comment by gregtampa** [comment]
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG
