### ISSUE TITLE
GET_INVENTORY Error

### ISSUE THREAD

**Issue by Distent** [PokemonGoF/PokemonGo-Bot#1920]
python pokecli.py
[2016-07-30 16:20:36] [x] PokemonGO Bot v1.0
[2016-07-30 16:20:36] [x] Configuration initialized
[2016-07-30 16:20:36] 
[2016-07-30 16:20:36] [x] Address found: 200 Santa Monica Pier Santa monica ca 90401
[2016-07-30 16:20:36] [x] Position in-game set as: (34.0098476, -118.4964629, 0.0)
[2016-07-30 16:20:36] 
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "/Users/Willdazzle/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/Users/Willdazzle/PokemonGo-Bot/pokemongo_bot/__init__.py", line 159, in _setup_api
    balls_stock = self.pokeball_inventory()
  File "/Users/Willdazzle/PokemonGo-Bot/pokemongo_bot/__init__.py", line 234, in pokeball_inventory
    inventory_dict = inventory_req['responses']['GET_INVENTORY'][
KeyError: 'GET_INVENTORY'

It gives me an error when I try to do python pokecli.py

**Comment by PraeceptorXS** [comment]
Download the newest dev version. This fixes it.

**Comment by Distent** [comment]
This may sound stupid...but how do I download the latest dev version...

**Comment by antoineneff** [comment]
I suggest to do a clean install, when you clone the repo, you have to change branch master to dev : 
`git clone --recursive -b dev https://github.com/PokemonGoF/PokemonGo-Bot`

**Comment by Distent** [comment]
Thank you that works,
