### ISSUE TITLE
Current dev commit Error at startup

### ISSUE THREAD

**Issue by leckeia** [PokemonGoF/PokemonGo-Bot#1922]
After startup i get:

Traceback (most recent call last):
  File "C:\Users\Admino\Desktop\PoGo.git\beta\PokemonGo-Bot\pokecli.py", line 497, in <module>
    main()
  File "C:\Users\Admino\Desktop\PoGo.git\beta\PokemonGo-Bot\pokecli.py", line 62, in main
    bot.start()
  File "C:\Users\Admino\Desktop\PoGo.git\beta\PokemonGo-Bot\pokemongo_bot\__init__.py", line 60, in start
    self.navigator=navigators.PathNavigator(self)
  File "C:\Users\Admino\Desktop\PoGo.git\beta\PokemonGo-Bot\pokemongo_bot\navigators\path_navigator.py", line 20, in __init__
    self.points = self.load_path()
  File "C:\Users\Admino\Desktop\PoGo.git\beta\PokemonGo-Bot\pokemongo_bot\navigators\path_navigator.py", line 27, in load_path
    return self.load_json(self.config.navigator_path_file)
  File "C:\Users\Admino\Desktop\PoGo.git\beta\PokemonGo-Bot\pokemongo_bot\navigators\path_navigator.py", line 33, in load_json
    points=json.load(data_file)
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 4 column 35 (char 153)

Configs and all should be fine since it worked well a commit ago.

### Steps to Reproduce
Starting the Bot

### Other Information
OS: win10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by lowwww** [comment]
I get: 

root@vps302521:~/PokemonGo-Bot# python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 13, in <module>
    from pgoapi import PGoApi
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 19, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 42, in <module>
    from POGOProtos.Networking.Envelopes_pb2 import RequestEnvelope
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/protos/POGOProtos/Networking/Envelopes_pb2.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
ImportError: cannot import name symbol_database


When starting the bot after fresh install. it was working before they changed the install guide for linux..

**Comment by leckeia** [comment]
Sorry, layer8 problem.
Had a typo in my locations.json after changing to the new format.

My issue is fixed, well, there never was one.

**Comment by gregtampa** [comment]
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG
