### ISSUE TITLE
Dev Branch - Invalid URL 'None': No schema supplied.

### ISSUE THREAD

**Issue by iDervy** [PokemonGoF/PokemonGo-Bot#1924]
```
Traceback (most recent call last):
  File "pokecli.py", line 497, in <module>
    main()
  File "pokecli.py", line 79, in main
    report_summary(bot)
  File "pokecli.py", line 87, in report_summary
    metrics.capture_stats()
  File "C:\Users\Dervi\Desktop\PokemonGo-Bot-dev\pokemongo_bot\metrics.py", line 73, in capture_stats
    self.bot.api.get_inventory()
  File "C:\Users\Dervi\Desktop\PokemonGo-Bot-dev\pgoapi\pgoapi.py", line 84, in function
    return request.call()
  File "C:\Users\Dervi\Desktop\PokemonGo-Bot-dev\pgoapi\pgoapi.py", line 182, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "C:\Users\Dervi\Desktop\PokemonGo-Bot-dev\pgoapi\rpc_api.py", line 104, in request
    response = self._make_rpc(endpoint, request_proto)
  File "C:\Users\Dervi\Desktop\PokemonGo-Bot-dev\pgoapi\rpc_api.py", line 92, in _make_rpc
    http_response = self._session.post(endpoint, data=request_proto_serialized)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 461, in request
    prep = self.prepare_request(req)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 394, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Python27\lib\site-packages\requests\models.py", line 295, in prepare
    self.prepare_url(url, params)
  File "C:\Python27\lib\site-packages\requests\models.py", line 355, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
```

Off topic, does any of the devs have an older version of PogoAPI they could upload? The latest version breaks the master version and I have a feeling it's bugging the Dev version as well.

EDIT: I reran pip install -r requirements.txt then deleted the pogoapi folder and it now works?

**Comment by gregtampa** [comment]
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG
