### ISSUE TITLE
Error at startup on dev branch (MacOSX)

### ISSUE THREAD

**Issue by squiidz** [PokemonGoF/PokemonGo-Bot#1925]
### Expected Behavior
Start the bot

### Actual Behavior
Traceback (most recent call last):
  File "./pokecli.py", line 497, in <module>
    main()
  File "./pokecli.py", line 68, in main
    bot.tick()
  File "/Users/jo/dev/python/PokemonGo-Bot-bck/pokemongo_bot/__init__.py", line 90, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/Users/jo/dev/python/PokemonGo-Bot-bck/pokemongo_bot/cell_workers/recycle_items.py", line 15, in work
    id_filter = self.bot.config.item_filter.get(str(item_id), 0)
AttributeError: 'unicode' object has no attribute 'get'

### Steps to Reproduce
git pull origin dev
pip install -r requirements.txt
./pokecli.py -cf config.json
### Other Information
OS: MacOSX

Git Commit: 8b887a13e162371f3ea057b2c3a3576c90cb11b1

**Comment by CapCap** [comment]
What's the output of running 'python -V' ?

**Comment by squiidz** [comment]
Python 2.7.12

**Comment by gregtampa** [comment]
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG
