### ISSUE TITLE
OSError when update requirements since the last commits

### ISSUE THREAD

**Issue by Kyokoo** [PokemonGoF/PokemonGo-Bot#1926]
When i try to "pip install -r requirements.txt --upgrade --ignore-installed six" on my mac there is an error like that

`Installing collected packages: six, geopy, setuptools, protobuf, requests, future, s2sphere, pycryptodomex, gpsoauth, pgoapi, protobuf-to-dict, googlemaps, colorama, enum34, pyyaml, haversine, polyline, python-engineio, python-socketio, itsdangerous, click, Werkzeug, MarkupSafe, Jinja2, flask, websocket-client, socketIO-client, greenlet, eventlet, universal-analytics-python, gpxpy
  Running setup.py develop for pgoapi
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 378, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 287, in clobber
    ensure_dir(dest)  # common for the 'include' path
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/greenlet'`

I also tried to uninstall all this package for clear re-install but dont affect the bug

OS : OSX El Capitan

**Comment by ddrght12345** [comment]
Not sure what the package for OSX is called, but on ubuntu, you need to install `python-greenlet`.
Maybe OSX has a similarly named package.

**Comment by gregtampa** [comment]
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG
