### ISSUE TITLE
Master, Bot stoped working today without files changes

### ISSUE THREAD

**Issue by Faralax** [PokemonGoF/PokemonGo-Bot#1945]
### Expected Behavior
Bot working as intended
### Actual Behavior
Bot doesnt start

This is the output i get
C:\Users\David\Downloads\PokemonGo-Bot-master>pokecli.py
Traceback (most recent call last):
  File "C:\Users\David\Downloads\PokemonGo-Bot-master\pokecli.py", line 220, in <module>
    main()
  File "C:\Users\David\Downloads\PokemonGo-Bot-master\pokecli.py", line 197, in main
    config = init_config()
  File "C:\Users\David\Downloads\PokemonGo-Bot-master\pokecli.py", line 174, in init_config
    config.release_config.update(json.load(data))
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 9 column 1 (char 218)

**Comment by Cygnus-X3** [comment]
a new pokemongo  update started rolling out hours ago, maybe the reason, update to dev version if possible

**Comment by gregtampa** [comment]
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG
