### ISSUE TITLE
[DEV] IndexError: list index out of range in navigator.take_step()

### ISSUE THREAD

**Issue by MariuszT** [PokemonGoF/PokemonGo-Bot#1948]
Traceback (most recent call last):
  File "./pokecli.py", line 497, in <module>
    main()
  File "./pokecli.py", line 68, in main
    bot.tick()
  File "/opt/pokemonbot/pokemongo_bot/__init__.py", line 93, in tick
    self.navigator.take_step()
  File "/opt/pokemonbot/pokemongo_bot/cell_workers/follow_spiral.py", line 57, in take_step
    point = self.points[self.ptr]
IndexError: list index out of range

### Other Information
OS: Debian
Git Commit: a761db475f22f9db54ba867322c2813277c7a806

**Comment by hero16** [comment]
yes same error and appears a lot shorter than 5 mins

**Comment by gregtampa** [comment]
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG
