### ISSUE TITLE
Traceback (most recent call last) [ERROR]

### ISSUE THREAD

**Issue by fr1tzz** [PokemonGoF/PokemonGo-Bot#195]
```
fr1tz:PokemonGo-Bot/ (dev✗) $ python2 ./pokecli.py -a google -u username@gmail.com -p password -l "LOCATION"                                  [9:27:28]
Traceback (most recent call last):
  File "./pokecli.py", line 41, in <module>
    from bot import PokemonGoBot
  File "/home/fr1tz/PokemonGo-Bot/bot.py", line 8, in <module>
    from pgoapi import PGoApi
  File "/home/fr1tz/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 17, in <module>
    raise PleaseInstallProtobufVersion3()
pgoapi.exceptions.PleaseInstallProtobufVersion3
```

I had a earlier build and it ran fine but I deleted it and cloned the newest build re ran
`pip install -r ./requirements.txt`
and it works fine but I get that error. Any suggestion?

**Comment by Paramon** [comment]
Look like you missed Google Protobuf. Look at https://github.com/google/protobuf/releases

**Comment by deathcoderz** [comment]
pip install --upgrade Protobuf?

**Comment by fr1tzz** [comment]
`pip install --upgrade Protobuf`
Returns
```
fr1tz:PokemonGo-Bot/ (dev✗) $ pip install --upgrade Protobuf                                                                                                                                 [9:27:51]
Collecting Protobuf
Collecting setuptools (from Protobuf)
  Using cached setuptools-24.3.0-py2.py3-none-any.whl
Installing collected packages: setuptools, Protobuf
Successfully installed Protobuf-2.6.1 setuptools-24.3.0

```
The same error persists, nothing has changed.

**Comment by shaneallgeier** [comment]
Try `pip install --upgrade -r requirements.txt`

**Comment by CasBroad** [comment]
I'm also getting this error, i have all the requirments installed and upgraded. Still no luck.

**Comment by fr1tzz** [comment]
Tried 
`pip install --upgrade -r requirements.txt`
Returned this
```
fr1tz:PokemonGo-Bot/ (dev✗) $ pip install --upgrade -r requirements.txt                                                                                                                      [9:50:08]
Obtaining pgoapi from git+git://github.com/tejado/pgoapi.git#egg=pgoapi (from -r requirements.txt (line 1))
  Updating ./src/pgoapi clone
Collecting geopy==1.11.0 (from -r requirements.txt (line 2))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf==3.0.0b4 (from -r requirements.txt (line 3))
Collecting requests==2.10.0 (from -r requirements.txt (line 4))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 5))
  Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 6))
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 7))
Collecting googlemaps==2.4.4 (from -r requirements.txt (line 8))
  Using cached googlemaps-2.4.4-py2-none-any.whl
Collecting six>=1.9 (from protobuf==3.0.0b4->-r requirements.txt (line 3))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting setuptools (from protobuf==3.0.0b4->-r requirements.txt (line 3))
  Using cached setuptools-24.3.0-py2.py3-none-any.whl
Collecting future (from s2sphere==0.2.4->-r requirements.txt (line 5))
Collecting pycryptodomex>=3.0 (from gpsoauth==0.3.0->-r requirements.txt (line 6))
Installing collected packages: geopy, six, setuptools, protobuf, requests, future, s2sphere, pycryptodomex, gpsoauth, pgoapi, protobuf-to-dict, googlemaps
  Running setup.py develop for pgoapi
Successfully installed future-0.15.2 geopy-1.11.0 googlemaps-2.4.4 gpsoauth-0.3.0 pgoapi-1.1.0 protobuf-2.6.1 protobuf-to-dict-0.1.0 pycryptodomex-3.4.2 requests-2.10.0 s2sphere-0.2.4 setuptools-24.3.0 six-1.10.0

```

Still no change in the error.

**Comment by Imbos** [comment]
if you are on mac try:

 brew update && brew install --devel protobuf

**Comment by fr1tzz** [comment]
I am running Debian testing and I just upgraded all my packages a few days ago so this does not apply to me.

**Comment by SwedishBotMafia** [comment]
https://gist.github.com/samklr/0b8a0620f82005e7f556/revisions

I found this for installing protobug to debian

**Comment by fr1tzz** [comment]
I've installed protobuf through pip this is not the issue.
```
fr1tz:PokemonGo-Bot/ (dev✗) $ pip install Protobuf                                                                                                                                           [9:54:52]
Collecting Protobuf
Collecting setuptools (from Protobuf)
  Using cached setuptools-24.3.0-py2.py3-none-any.whl
Installing collected packages: setuptools, Protobuf
Successfully installed Protobuf-2.6.1 setuptools-24.3.0

```

**Comment by Imbos** [comment]
its checking for protobuf version 3 is all

**Comment by Paramon** [comment]
Type 
`pip install protobuf==3.0.0b3`
or:
`pip install protobuf==3.0.0b3 --upgrade`

**Comment by fr1tzz** [comment]
```
fr1tz:PokemonGo-Bot/ (dev✗) $ pip install protobuf==3.0.0b3                                                                                                                                 [10:03:57]
Collecting protobuf==3.0.0b3
  Downloading protobuf-3.0.0b3-py2-none-any.whl (334kB)
    100% |████████████████████████████████| 337kB 2.6MB/s 
Collecting six>=1.9 (from protobuf==3.0.0b3)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting setuptools (from protobuf==3.0.0b3)
  Using cached setuptools-24.3.0-py2.py3-none-any.whl
Installing collected packages: six, setuptools, protobuf
Successfully installed protobuf-2.6.1 setuptools-24.3.0 six-1.10.0

```
Why did it return "Successfully installed protobuf-2.6.1" I dont understand? o.0

**Comment by deathcoderz** [comment]
https://github.com/google/protobuf/releases/download/v3.0.0-beta-4/protobuf-objectivec-3.0.0-beta-4.zip

You can try to download it and replace 2.6.1 by hand with 3.0.0

**Comment by fr1tzz** [comment]
How would I do that?

**Comment by Paramon** [comment]
On My Debian. 
```
$ pip install protobuf==3.0.0b3 --upgrade
Collecting protobuf==3.0.0b3
  Downloading protobuf-3.0.0b3.tar.gz (117kB)
    100% |████████████████████████████████| 122kB 256MB/s
Requirement already satisfied (use --upgrade to upgrade): six>=1.9 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from protobuf==3.0.0b3)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from protobuf==3.0.0b3)
Installing collected packages: protobuf
  Found existing installation: protobuf 2.6.1
    Uninstalling protobuf-2.6.1:
      Successfully uninstalled protobuf-2.6.1
  Running setup.py install for protobuf ... done
Successfully installed protobuf-3.0.0b3
```
You can try to uninstall in first.

**Comment by fr1tzz** [comment]
I get this 
```
fr1tz:PokemonGo-Bot/ (dev✗) $ pip install protobuf==3.0.0b3 --upgrade                                                                                                                       [10:05:59]
Collecting protobuf==3.0.0b3
  Using cached protobuf-3.0.0b3-py2-none-any.whl
Collecting six>=1.9 (from protobuf==3.0.0b3)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting setuptools (from protobuf==3.0.0b3)
  Using cached setuptools-24.3.0-py2.py3-none-any.whl
Installing collected packages: six, setuptools, protobuf
Successfully installed protobuf-2.6.1 setuptools-24.3.0 six-1.10.0

```

Is there a way to uninstall protobuf completely and then reinstall it using pip?

**Comment by fr1tzz** [comment]
That did it, thank you very much. I'm sorry it was such an easy fix. First time using pip and all -~-

**Comment by deathcoderz** [comment]
np :)

**Comment by Paramon** [comment]
`pip uninstall protobuf `.
Do you use virtualenv? If yes
```
pip uninstall protobuf 
deactivate
pip uninstall protobuf
``` 

And then 
`pip install protobuf==3.0.0b3`
