### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by zhousixiang** [PokemonGoF/PokemonGo-Bot#1951]
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 197, in main
    config = init_config()
  File "pokecli.py", line 64, in init_config
    load.update(json.load(data))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by phoenix98787** [comment]
lets have a look at your config file, just hide the personal info :)

**Comment by gregtampa** [comment]
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG
