### ISSUE TITLE
Program error

### ISSUE THREAD

**Issue by A-Charvin** [PokemonGoF/PokemonGo-Bot#1952]
### Expected Behavior
Smooth colored texts with all the details of the bot working.

### Actual Behavior
$ python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 197, in main
    config = init_config()
  File "pokecli.py", line 64, in init_config
    load.update(json.load(data))
  File "F:\Softwares\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "F:\Softwares\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "F:\Softwares\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "F:\Softwares\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 15 column 1 (char 378)

### Steps to Reproduce
Try to run the script and the issue comes up.

### Other Information
OS: Windows 10

**Comment by gregtampa** [comment]
not a bug
please come to slack chat and join #help ask for assistance.
