### ISSUE TITLE
pokemon_catch_worker crash only with bulbasaur

### ISSUE THREAD

**Issue by ConflictWY** [PokemonGoF/PokemonGo-Bot#1959]
```
[18:07:36] Something rustles nearby!
[18:07:37]  A Wild Bulbasaur appeared! [CP 640] [Potential 0.51]
[18:07:37] IV [Stamina/Attack/Defense] = [9/2/12]
[18:07:40] Catch Rate with normal Pokeball is low (17.76%). Thinking to throw a Razz Berry... (18 left!)
[18:07:41] Threw a berry! Catch Rate with normal Pokeball has increased to 26.65%
[18:07:41]
[18:07:41]  Ran for 0:03:32
[18:07:41]  Total XP Earned: 840  Average: 14265.63/h
[18:07:41]  Travelled 0.00km
[18:07:41]  Visited 4 stops
[18:07:41]  Encountered 2 pokemon, 2 caught, 0 released, 0 evolved, 0 never seen before
[18:07:41]  Threw 4 pokeballs
[18:07:41]  Earned 200 Stardust
[18:07:41]
[18:07:41]  Highest CP Pokemon: Nidoran M [CP: 389] [IV: 10/6/13] Potential: 0.64
[18:07:41]  Most Perfect Pokemon: Nidoran M [CP: 389] [IV: 10/6/13] Potential: 0.64
Traceback (most recent call last):
  File "pokecli.py", line 466, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "C:\Users\alexa\Desktop\PokemonGO\PokemonGo-Bot - Copy\pokemongo_bot\__init__.py", line 85, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "C:\Users\alexa\Desktop\PokemonGO\PokemonGo-Bot - Copy\pokemongo_bot\cell_workers\catch_visible_pokemon_worker.py", line 29, in work
    return self.catch_pokemon(self.bot.cell['catchable_pokemons'][0])
  File "C:\Users\alexa\Desktop\PokemonGO\PokemonGo-Bot - Copy\pokemongo_bot\cell_workers\catch_visible_pokemon_worker.py", line 41, in catch_pokemon
    return_value = worker.work()
  File "C:\Users\alexa\Desktop\PokemonGO\PokemonGo-Bot - Copy\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 198, in work
    if catch_rate[pokeball-1]<0.30 and item_stock[3]>0:
NameError: global name 'item_stock' is not defined
```

**Comment by ConflictWY** [comment]
```
[18:00:40]  A Wild Bulbasaur appeared! [CP 640] [Potential 0.51]
[18:00:40] IV [Stamina/Attack/Defense] = [9/2/12]
[18:00:43] Catch Rate with normal Pokeball is low (17.76%). Thinking to throw a Razz Berry... (18 left!)
[18:00:43] Threw a berry! Catch Rate with normal Pokeball has increased to 26.65%
[18:00:43]
[18:00:43]  Ran for 1:11:16
[18:00:43]  Total XP Earned: 14475  Average: 12185.43/h
[18:00:43]  Travelled 3.59km
[18:00:43]  Visited 34 stops
[18:00:43]  Encountered 26 pokemon, 23 caught, 0 released, 1 evolved, 0 never seen before
[18:00:43]  Threw 46 pokeballs
[18:00:43]  Earned 11964 Stardust
[18:00:43]
[18:00:43]  Highest CP Pokemon: Oddish [CP: 746] [IV: 10/15/7] Potential: 0.71
[18:00:43]  Most Perfect Pokemon: Krabby [CP: 103] [IV: 14/15/8] Potential: 0.82
Traceback (most recent call last):
  File "pokecli.py", line 466, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "C:\Users\alexa\Desktop\PokemonGO\PokemonGo-Bot - Copy\pokemongo_bot\__init__.py", line 85, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "C:\Users\alexa\Desktop\PokemonGO\PokemonGo-Bot - Copy\pokemongo_bot\cell_workers\catch_visible_pokemon_worker.py", line 29, in work
    return self.catch_pokemon(self.bot.cell['catchable_pokemons'][0])
  File "C:\Users\alexa\Desktop\PokemonGO\PokemonGo-Bot - Copy\pokemongo_bot\cell_workers\catch_visible_pokemon_worker.py", line 41, in catch_pokemon
    return_value = worker.work()
  File "C:\Users\alexa\Desktop\PokemonGO\PokemonGo-Bot - Copy\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 198, in work
    if catch_rate[pokeball-1]<0.30 and item_stock[3]>0:
NameError: global name 'item_stock' is not defined
```

**Comment by ConflictWY** [comment]
```
[16:47:32]  A Wild Bulbasaur appeared! [CP 533] [Potential 0.27]
[16:47:32] IV [Stamina/Attack/Defense] = [3/2/7]
[16:47:35] Catch Rate with normal Pokeball is low (18.95%). Thinking to throw a Razz Berry... (12 left!)
[16:47:35] Threw a berry! Catch Rate with normal Pokeball has increased to 28.42%
[16:47:35]
[16:47:35]  Ran for 0:31:08
[16:47:35]  Total XP Earned: 11410  Average: 21992.57/h
[16:47:35]  Travelled 2.09km
[16:47:35]  Visited 18 stops
[16:47:35]  Encountered 20 pokemon, 18 caught, 0 released, 4 evolved, 0 never seen before
[16:47:35]  Threw 34 pokeballs
[16:47:35]  Earned 4652 Stardust
[16:47:35]
[16:47:35]  Highest CP Pokemon: Eevee [CP: 654] [IV: 15/4/6] Potential: 0.56
[16:47:35]  Most Perfect Pokemon: Staryu [CP: 181] [IV: 15/14/15] Potential: 0.98
Traceback (most recent call last):
  File "pokecli.py", line 466, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "C:\Users\alexa\Desktop\PokemonGO\PokemonGo-Bot - Copy\pokemongo_bot\__init__.py", line 85, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "C:\Users\alexa\Desktop\PokemonGO\PokemonGo-Bot - Copy\pokemongo_bot\cell_workers\catch_visible_pokemon_worker.py", line 29, in work
    return self.catch_pokemon(self.bot.cell['catchable_pokemons'][0])
  File "C:\Users\alexa\Desktop\PokemonGO\PokemonGo-Bot - Copy\pokemongo_bot\cell_workers\catch_visible_pokemon_worker.py", line 41, in catch_pokemon
    return_value = worker.work()
  File "C:\Users\alexa\Desktop\PokemonGO\PokemonGo-Bot - Copy\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 198, in work
    if catch_rate[pokeball-1]<0.30 and item_stock[3]>0:
NameError: global name 'item_stock' is not defined
```

**Comment by ConflictWY** [comment]
```
[18:20:12]  A Wild Bulbasaur appeared! [CP 501] [Potential 0.42]
[18:20:12] IV [Stamina/Attack/Defense] = [9/3/7]
[18:20:15] Catch Rate with normal Pokeball is low (19.88%). Thinking to throw a Razz Berry... (18 left!)
[18:20:16] Threw a berry! Catch Rate with normal Pokeball has increased to 29.83%
[18:20:16]
[18:20:16]  Ran for 0:07:17
[18:20:16]  Total XP Earned: 570  Average: 4697.28/h
[18:20:16]  Travelled 0.24km
[18:20:16]  Visited 3 stops
[18:20:16]  Encountered 3 pokemon, 1 caught, 0 released, 0 evolved, 0 never seen before
[18:20:16]  Threw 2 pokeballs
[18:20:16]  Earned 100 Stardust
[18:20:16]
[18:20:16]  Highest CP Pokemon: Zubat [CP: 333] [IV: 9/13/6] Potential: 0.62
[18:20:16]  Most Perfect Pokemon: Zubat [CP: 333] [IV: 9/13/6] Potential: 0.62
Traceback (most recent call last):
  File "pokecli.py", line 466, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "C:\Users\alexa\Desktop\PokemonGO\PokemonGo-Bot - Copy\pokemongo_bot\__init__.py", line 85, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "C:\Users\alexa\Desktop\PokemonGO\PokemonGo-Bot - Copy\pokemongo_bot\cell_workers\catch_visible_pokemon_worker.py", line 29, in work
    return self.catch_pokemon(self.bot.cell['catchable_pokemons'][0])
  File "C:\Users\alexa\Desktop\PokemonGO\PokemonGo-Bot - Copy\pokemongo_bot\cell_workers\catch_visible_pokemon_worker.py", line 41, in catch_pokemon
    return_value = worker.work()
  File "C:\Users\alexa\Desktop\PokemonGO\PokemonGo-Bot - Copy\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 198, in work
    if catch_rate[pokeball-1]<0.30 and item_stock[3]>0:
NameError: global name 'item_stock' is not defined
```

**Comment by jaychangs** [comment]
Checkout #1878
