### ISSUE TITLE
ValueError on run

### ISSUE THREAD

**Issue by manu354** [PokemonGoF/PokemonGo-Bot#1960]
On windows 10, no errors with pip or pyYAML. I created the two config.json files and ran `python pokecli.py` and got this error:

Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 197, in main
    config = init_config()
  File "pokecli.py", line 64, in init_config
    load.update(json.load(data))
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 16 column 21 (char 435)

### Other Information
OS: Windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
78c5f2bc8c5aeafb902309583cfab621179bed4e

**Comment by gregtampa** [comment]
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG
