### ISSUE TITLE
NotLoggedInException after 1 hour's running

### ISSUE THREAD

**Issue by blackdog1987** [PokemonGoF/PokemonGo-Bot#1968]
I found that it can only run for 1 hour, after 1 hour it crashed. And always get the exception `NotLoggedInException()`    
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "/Applications/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/Applications/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/Applications/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/Applications/PokemonGo-Bot/pokemongo_bot/__init__.py", line 93, in work_on_cell
    worker.work()
  File "/Applications/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 30, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "/Applications/PokemonGo-Bot/pokemongo_bot/stepper.py", line 88, in _walk_to
    alt, False)
  File "/Applications/PokemonGo-Bot/pokemongo_bot/stepper.py", line 102, in _work_at_position
    response_dict = self.api.call()
  File "/Applications/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 81, in call
    response = request.request(api_endpoint, self._req_method_list, player_position)
  File "/Applications/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 100, in request
    raise NotLoggedInException()

**Comment by wcastello** [comment]
I found that the reason mine was spitting NotLoggedInException() was that I exceeded the number of requests to the Maps API.
