### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by paulohdc** [PokemonGoF/PokemonGo-Bot#1978]
### Actual Behavior
[23:25:59]  Server seems to be busy or offline - try again - 1/5
[23:26:00]  Server seems to be busy or offline - try again - 2/5
[23:26:01]  Server seems to be busy or offline - try again - 3/5
[23:26:02]  Server seems to be busy or offline - try again - 4/5
[23:26:03]  Server seems to be busy or offline - try again - 5/5
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
  File "pokecli.py", line 81, in main
  File "pokecli.py", line 89, in report_summary
  File "C:\pk\PokemonGo-Bot-Dev\pokemongo_bot\metrics.py", line 75, in capture_stats
  File "C:\pk\PokemonGo-Bot-Dev\pokemongo_bot\api_wrapper.py", line 74, in call
pgoapi.exceptions.ServerBusyOrOfflineException

[23:34:29]  Server seems to be busy or offline - try again - 1/5
[23:34:30]  Server seems to be busy or offline - try again - 2/5
[23:34:32]  Server seems to be busy or offline - try again - 3/5
[23:34:33]  Server seems to be busy or offline - try again - 4/5
[23:34:34]  Server seems to be busy or offline - try again - 5/5
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
  File "pokecli.py", line 81, in main
  File "pokecli.py", line 89, in report_summary
  File "C:\pk\PokemonGo-Bot-Dev\pokemongo_bot\metrics.py", line 75, in capture_stats
  File "C:\pk\PokemonGo-Bot-Dev\pokemongo_bot\api_wrapper.py", line 74, in call
pgoapi.exceptions.ServerBusyOrOfflineException

I have done

git reset --hard
git pull -f
pip install -r --upgrade requirements.txt

is like that since yesterday

**Comment by vzaritovsky** [comment]
So, what's the actual question? Why the servers are busy/down? Well, seems they are having some problems.
Of you are sure that servers are okay and this error is just misleading?

**Comment by jayhostan** [comment]
@paulohdc try to start with an other location so there is a chance it picks up an other server

**Comment by paulohdc** [comment]
servers are OK

i have open and check every time  http://ispokemongodownornot.com/

this is happening every 5 or 10, at most 15 min

not only now are already whole two days 

starting in the central park 40.769630, -73.975535

**Comment by CattDamon** [comment]
This is happening to me as well.  Shitty servers, great bot.

**Comment by gregtampa** [comment]
go to the slack chatroom then in #help someone will help you
