### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by Mrpuppup** [PokemonGoF/PokemonGo-Bot#199]
[x] PokemonGO Bot v1.0
[x] Configuration Initialized
[x] Address found: Dublin Airport
[x] Position in-game set as: (53.42608, -6.23912, 0.0)
Traceback (most recent call last):
  File "pokecli.py", line 103, in <module>
    main()
  File "pokecli.py", line 97, in main
    bot.start()
  File "C:\Program Files (x86)\Python2.7\bot.py", line 24, in start
    self._setup_api()
  File "C:\Program Files (x86)\Python2.7\bot.py", line 158, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'player_data'

**Comment by aTadTasty** [comment]
same as issue #175

**Comment by jtdroste** [comment]
Closing this for travking on #175
