### ISSUE TITLE
Crash in farming mode

### ISSUE THREAD

**Issue by mnzt** [PokemonGoF/PokemonGo-Bot#1991]
### Expected Behavior
To work usually in farming mode

### Actual Behavior
Crashing with error

```
Traceback (most recent call last):
  File "./pokecli.py", line 220, in <module>
    main()
  File "./pokecli.py", line 211, in main
    bot.take_step()
  File "/home/tobyjames1234/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/home/tobyjames1234/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/home/tobyjames1234/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/home/tobyjames1234/PokemonGo-Bot/pokemongo_bot/__init__.py", line 96, in work_on_cell
    hack_chain = worker.work()
  File "/home/tobyjames1234/PokemonGo-Bot/pokemongo_bot/cell_workers/seen_fort_worker.py", line 87, in work
    if result is 1: # Request success
UnboundLocalError: local variable 'result' referenced before assignment
```

### Steps to Reproduce
Unsure, maybe enter farming mode?

### Other Information
OS: Arch Linux
Git Commit: 78c5f2bc8c5aeafb902309583cfab621179bed4e

**Comment by Duckylord** [comment]
I had that problem too, but after running script again, have not gotten that.

**Comment by gregtampa** [comment]
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG
