### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by H4xXx0r** [PokemonGoF/PokemonGo-Bot#2010]
[00:45:16]  PokemonGO Bot v1.0
[00:45:16]  No config argument specified, checking for /configs/config.json
[00:45:16]  Configuration initialized
[00:45:17]  Not logged in!
Traceback (most recent call last):
  File "pokecli.py", line 490, in <module>
    main()
  File "pokecli.py", line 81, in main
    report_summary(bot)
  File "pokecli.py", line 89, in report_summary
    metrics.capture_stats()
  File "C:\Python27\PokemonGo-Bot\pokemongo_bot\metrics.py", line 75, in capture_stats
    response_dict = self.bot.api.call()
  File "C:\Python27\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 57, in call
    if not self._can_call():
  File "C:\Python27\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 29, in _can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException

Dev branch
Git pull done
Install requirements done
Tried a clear install done
Changed the google maps api for a new
Tried the autoreconnect

Still haveing same error

**Comment by julien-blanchon** [comment]
Same error please help
