### ISSUE TITLE
ValueError: Expecting property name: line 5 column 1 (char 107)

### ISSUE THREAD

**Issue by Whosdaman** [PokemonGoF/PokemonGo-Bot#2017]
### Expected Behavior
Bot to Start

### Actual Behavior
```
[02:55:57]  PokemonGO Bot v1.0 
Traceback (most recent call last):
  File "pokecli.py", line 494, in <module>
    main()
  File "pokecli.py", line 52, in main
    config = init_config()
  File "pokecli.py", line 120, in init_config
    load.update(json.load(data))
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 5 column 1 (char 107)
```

### Steps to Reproduce
Run bot

### Other Information
OS: MacOS
Git Commit: 81129d394fa7bf7913b2caf5b754d0ff42ed862a

**Comment by gregtampa** [comment]
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG
