### ISSUE TITLE
Waiting 10 seconds to try again, Login Error, server busy

### ISSUE THREAD

**Issue by akbaribnu** [PokemonGoF/PokemonGo-Bot#2024]
after update this morning, my script on server always show, server busy... and i cant connect again, i try for change id dan password but same

[root@pogo pogo]# ./run.sh 
[07:43:39]  PokemonGO Bot v1.0 
[07:43:39]  Configuration initialized 
[07:43:39] 
[07:43:39] Location Found: sydney
[07:43:39] GeoPosition: (-33.8688197, 151.2092955, 0)
[07:43:39] 
[07:43:39] [x] Parsing cached location...
[07:43:39] [x] Parsing cached location failed, try to use the initial location...
[07:43:39] Attempting login to Pokemon Go.
[07:43:39]  [X] Login Error, server busy 
[07:43:39]  [X] Waiting 10 seconds to try again 
[07:43:50]  [X] Login Error, server busy 
[07:43:50]  [X] Waiting 10 seconds to try again 
[07:44:00]  [X] Login Error, server busy 
[07:44:00]  [X] Waiting 10 seconds to try again 
[07:44:11]  [X] Login Error, server busy 
[07:44:11]  [X] Waiting 10 seconds to try again 
[07:44:21]  [X] Login Error, server busy 
[07:44:21]  [X] Waiting 10 seconds to try again 
^C[07:44:24]  Exiting PokemonGo Bot 
[07:44:24]  Server seems to be busy or offline - try again - 1/5 
[07:44:26]  Server seems to be busy or offline - try again - 2/5 
[07:44:27]  Server seems to be busy or offline - try again - 3/5 
[07:44:28]  Server seems to be busy or offline - try again - 4/5 
[07:44:29]  Server seems to be busy or offline - try again - 5/5 
Traceback (most recent call last):
  File "pokecli.py", line 494, in <module>
    main()
  File "pokecli.py", line 75, in main
    report_summary(bot)
  File "pokecli.py", line 89, in report_summary
    metrics.capture_stats()
  File "/root/pogo/pokemongo_bot/metrics.py", line 75, in capture_stats
    response_dict = self.bot.api.call()
  File "/root/pogo/pokemongo_bot/api_wrapper.py", line 74, in call
    raise ServerBusyOrOfflineException()
pgoapi.exceptions.ServerBusyOrOfflineException

**Comment by leovarmak** [comment]
This is something similar to this. Should be fixed soon #2009

**Comment by crowbarto** [comment]
This bug or similar bug was introduced in commit 2805cb75be3d30de272095675316f1bf9138b639
It is not present in commit 50716223fece99832b11d643f0347fe6eec52655


[01:07:14] A Wild Golbat appeared! [CP 516] [Potential 0.58]
[01:07:14] IV [Stamina/Attack/Defense] = [8/13/5]
[01:07:17] Catch Rate with normal Pokeball is low (18.93%). Throwing Razz Berry... (14 left!)
[01:07:17] Catch Rate with normal Pokeball has increased to 28.40%
[01:07:17] Using Greatball (chance: 40.52%)... (73 left!)
[01:07:18] [-] Attempted to capture Golbat - failed.. trying again!
[01:07:20] Catch Rate with normal Pokeball is low (28.40%). Throwing Razz Berry... (14 left!)
[01:07:20] Server seems to be busy or offline - try again - 1/5
[01:07:21] Server seems to be busy or offline - try again - 2/5
[01:07:22] Server seems to be busy or offline - try again - 3/5
[01:07:23] Server seems to be busy or offline - try again - 4/5
[01:07:24] Server seems to be busy or offline - try again - 5/5
Traceback (most recent call last):
  File "pokecli.py", line 389, in <module>
  File "pokecli.py", line 68, in main
  File "C:\PokemonGo-Bot\pokemongo_bot\__init__.py", line 89, in tick
  File "C:\PokemonGo-Bot\pokemongo_bot\cell_workers\catch_visible_pokemon_worker.py", line 37, in work
  File "C:\PokemonGo-Bot\pokemongo_bot\cell_workers\catch_visible_pokemon_worker.py", line 49, in catch_pokemon
  File "C:\PokemonGo-Bot\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 114, in work
  File "C:\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 74, in call
NameError: global name 'ServerBusyOrOfflineException' is not defined

**Comment by tvb** [comment]
Having the same issue after 2 am this morning; Tried to update but with same result:

```
[11:27:53]  PokemonGO Bot v1.0
[11:27:53]  Configuration initialized
[11:27:53] [x] Coordinates found in passed in location, not geocoding.
[11:27:53]
[11:27:53] Location Found: 51.92481682137732,4.469718933105469
[11:27:53] GeoPosition: (51.9248168, 4.4697189, 0)
[11:27:53]
[11:27:53] [x] Parsing cached location...
[11:27:53]
[11:27:53] [x] Last location flag used. Overriding passed in location
[11:27:53] [x] Last in-game location was set as: (51.924885341926576, 4.469722369793058, 0)
[11:27:53]
[11:27:53] Attempting login to Pokemon Go.
[11:27:53]  [X] Login Error, server busy
[11:27:53]  [X] Waiting 10 seconds to try again
[11:28:04]  [X] Login Error, server busy
[11:28:04]  [X] Waiting 10 seconds to try again
[11:28:15]  [X] Login Error, server busy
[11:28:15]  [X] Waiting 10 seconds to try again
[11:28:25]  [X] Login Error, server busy
[11:28:25]  [X] Waiting 10 seconds to try again
[11:28:36]  [X] Login Error, server busy
```

**Comment by pancakeykakes** [comment]
Also experiencing this issue on most recent commit available at time of posting.

**Comment by berong91** [comment]
Experiencing this issue on both of my Amazon EC2 instance, one in US West Oregon server, another in Asia Pacific Sydney server. Straighty, my third bot that that run from my network doesn't have this problem so far.
````
PokemonGO Bot v1.0 
[09:47:13]  Configuration initialized 
[09:47:13] [x] Coordinates found in passed in location, not geocoding.
[09:47:13] 
[09:47:13] Location Found: -33.85813032222973,151.21415734291077
[09:47:13] GeoPosition: (-33.8581303, 151.2141573, 0)
[09:47:13] 
[09:47:13] [x] Parsing cached location...
[09:47:13]  [x] Last location flag used but with a stale starting location 
[09:47:13] [x] Using new starting location, (-33.8581303, 151.2141573, 0)
[09:47:13] Attempting login to Pokemon Go.
[09:47:13]  [X] Login Error, server busy 
[09:47:13]  [X] Waiting 10 seconds to try again 
[09:47:23]  [X] Login Error, server busy 
[09:47:23]  [X] Waiting 10 seconds to try again 
[09:47:34]  Login to Pokemon Go successful. 
[09:47:34]  Server seems to be busy or offline - try again - 1/5 
[09:47:35]  Server seems to be busy or offline - try again - 2/5 
[09:47:36]  Server seems to be busy or offline - try again - 3/5 
[09:47:37]  Server seems to be busy or offline - try again - 4/5 
[09:47:38]  Server seems to be busy or offline - try again - 5/5 
[09:47:39]  Server seems to be busy or offline - try again - 1/5 
[09:47:39]  Server seems to be busy or offline - try again - 2/5 
[09:47:40]  Server seems to be busy or offline - try again - 3/5 
[09:47:41]  Server seems to be busy or offline - try again - 4/5 
[09:47:42]  Server seems to be busy or offline - try again - 5/5 
Traceback (most recent call last):
  File "pokecli.py", line 494, in <module>
    main()
  File "pokecli.py", line 81, in main
    report_summary(bot)
  File "pokecli.py", line 89, in report_summary
    metrics.capture_stats()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/metrics.py", line 75, in capture_stats
    response_dict = self.bot.api.call()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 74, in call
    raise ServerBusyOrOfflineException()
pgoapi.exceptions.ServerBusyOrOfflineException
````

**Comment by slayer1551** [comment]
IP ranges have been banned for amazon and digital ocean etc so it could be that.

**Comment by akbaribnu** [comment]
hai slayer1551, how do you know if digitalocean and amazon have been banned..?

**Comment by slayer1551** [comment]
I hosted a private PokemonGo-Map on Digital Ocean and this morning found it was returning HTTP Error 403 Forbidden. Others reported the same [issue](https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2777) for Amazon too. I tried another droplet in a different location and its up and running again but seem to be running into a different issue now "Server seems to be busy or offline - try again - 1/5"

**Comment by akbaribnu** [comment]
ok thnks for info, i will try from my private server on my country, i will show result after try on my server.. thnks you

**Comment by akbaribnu** [comment]
hai slayer, i think block ip amazon and digitalocean not block, because i try on my private server with my ip service provider, result same like a script on server digitalocean

jagotekno dev # ./run.sh 
[19:22:46]  PokemonGO Bot v1.0 
[19:22:46]  Configuration initialized 
[19:22:46] [x] Coordinates found in passed in location, not geocoding.
[19:22:46] 
[19:22:46] Location Found: -33.8688197,151.2092955
[19:22:46] GeoPosition: (-33.8688197, 151.2092955, 0)
[19:22:46] 
[19:22:46] [x] Parsing cached location...
[19:22:46] [x] Parsing cached location failed, try to use the initial location...
[19:22:46] Attempting login to Pokemon Go.
[19:22:47]  [X] Login Error, server busy 
[19:22:47]  [X] Waiting 10 seconds to try again 
[19:22:59]  [X] Login Error, server busy 
[19:22:59]  [X] Waiting 10 seconds to try again 
[19:23:10]  [X] Login Error, server busy 
[19:23:10]  [X] Waiting 10 seconds to try again 
[19:23:21]  [X] Login Error, server busy 
[19:23:21]  [X] Waiting 10 seconds to try again 
[19:23:32]  [X] Login Error, server busy 
[19:23:32]  [X] Waiting 10 seconds to try again 
[19:23:43]  [X] Login Error, server busy

**Comment by akbaribnu** [comment]
sorry i think you true, i try on my private server with ip from my country celuler, and this problem solved
