### ISSUE TITLE
Bot with web Map APi

### ISSUE THREAD

**Issue by lelbo** [PokemonGoF/PokemonGo-Bot#2040]
Hello All

I have install this bot and work great in my shell (terminal)
but after run httpsimple server in  /botfolder/web/
but in 127.0.0.1:8000 no view my profil

tank you

**Comment by mrthrowaway** [comment]
Its port 8000 by default. not 80000 (one less zero)

**Comment by lelbo** [comment]
error typine

**Comment by mrthrowaway** [comment]
do you get any output with the httpsimpleserver command?

**Comment by lelbo** [comment]
i m go this for the moment 
http://pastebin.com/8f4k2irJ

**Comment by lelbo** [comment]
MacBook-de-Michael:web mica$ 
MacBook-de-Michael:web mica$  python -m SimpleHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...
127.0.0.1 - - [31/Jul/2016 12:53:42] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [31/Jul/2016 12:53:42] "GET /main.js HTTP/1.1" 200 -
127.0.0.1 - - [31/Jul/2016 12:53:42] "GET /main.css HTTP/1.1" 200 -
127.0.0.1 - - [31/Jul/2016 12:53:42] "GET /userdata.js HTTP/1.1" 200 -
127.0.0.1 - - [31/Jul/2016 12:53:48] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:48] "GET /location-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:48] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:48] "GET /location-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:48] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:48] "GET /catchable-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:48] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:48] "GET /catchable-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:48] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:48] "GET /inventory-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:48] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:48] "GET /location-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:48] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:48] "GET /catchable-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:48] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:48] "GET /inventory-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:48] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:48] "GET /inventory-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:48] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:48] "GET /inventory-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:51] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:51] "GET /location-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:51] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:51] "GET /catchable-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:51] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:51] "GET /location-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:51] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:51] "GET /catchable-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:53] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:53] "GET /inventory-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:54] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:54] "GET /location-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:54] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:54] "GET /catchable-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:54] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:54] "GET /inventory-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:55] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:55] "GET /location-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:55] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:55] "GET /catchable-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:55] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:55] "GET /location-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:55] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:55] "GET /catchable-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:55] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:55] "GET /location-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:55] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:55] "GET /catchable-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:56] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:56] "GET /location-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:56] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:56] "GET /catchable-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:57] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:57] "GET /location-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:57] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:57] "GET /catchable-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:58] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:58] "GET /location-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:58] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:58] "GET /catchable-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:58] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:58] "GET /location-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:58] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:58] "GET /catchable-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:58] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:58] "GET /location-lelbo.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 12:53:58] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 12:53:58] "GET /catchable-lelbo.json HTTP/1.1" 404 -
^CTraceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SimpleHTTPServer.py", line 235, in <module>
    test()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SimpleHTTPServer.py", line 231, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 610, in test
    httpd.serve_forever()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

**Comment by mrthrowaway** [comment]
Is your bot running while this happens? And the web directory is inside the bot directory.

The bot will create the files you're getting 404 error for

**Comment by lelbo** [comment]
Bot working great : 

[2016-07-31 12:59:54] [x] Using Greatball (chance: 46.80%)... (111 left!)
[2016-07-31 12:59:55] [-] Attempted to capture Weedle- failed.. trying again!
[2016-07-31 12:59:58] [x] Using Greatball (chance: 46.80%)... (110 left!)
[2016-07-31 12:59:59] [x] Captured Weedle! [CP 202] [IV 0.38]
[2016-07-31 12:59:59] [x] Captured Weedle! [CP 202]

i have just clone repostery of bot

i have /folderBot/web/

i have just edit userdata with my google api login.

error in server shell 
127.0.0.1 - - [31/Jul/2016 13:01:57] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 13:01:57] code 404, message File not found

**Comment by mrthrowaway** [comment]
So the bot is in /folderBot/ and the web map is in /folderBot/web?

**Comment by lelbo** [comment]
![11](https://cloud.githubusercontent.com/assets/20744731/17276134/e29be4b6-571f-11e6-82f7-3cc69b2f572a.png)

**Comment by LasseSkogland** [comment]
You need to create a userdata.js file.
Copy the userdata.js.example to userdata.js.
Then edit the settings in userdata.js

**Comment by LasseSkogland** [comment]
It seems like you have set the wrong username in userdata.js
Look at inventory-USERNAME.json file
You need that exact username or the it won't work.

**Comment by lelbo** [comment]
name of user api ?

**Comment by LasseSkogland** [comment]
It's most likely your email address, the same you have in your config.json file for the bot.

**Comment by lelbo** [comment]
Ok now i m view pokemon catched on me in map  but no view here i m me ? my possitions
and other error 
ul/2016 13:39:59] "GET /catchable-micacatt@gmail.com.json?v=1469965199436 HTTP/1.1" 200 -
127.0.0.1 - - [31/Jul/2016 13:40:00] "GET /inventory-micacatt@gmail.com.json?v=1469965200165 HTTP/1.1" 200 -
127.0.0.1 - - [31/Jul/2016 13:40:00] code 404, message File not found
127.0.0.1 - - [31/Jul/2016 13:40:00] "GET /location-micacatt@gmail.com.json?v=1469965200165 HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 13:40:00] "GET /catchable-micacatt@gmail.com.json?v=1469965200166 HTTP/1.1" 200 -

**Comment by LasseSkogland** [comment]
Seems like your location-micacatt@gmail.com.json file does not exists, thus no location on map.
Might be some buggy code in the bot.

**Comment by lelbo** [comment]
Ok now i m view Bag/ Xp/hours ....  but no locations how to repair this ?
tank you for your Help   :) 
 404, message File not found
127.0.0.1 - - [31/Jul/2016 13:45:39] "GET /location-micacatt@gmail.com.json HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2016 13:45:39] "GET /catchable-micacatt@gmail.com.json HTTP/1.1" 200 -
1

**Comment by buettner123** [comment]
just create the file `location-micacatt@gmail.com.json` in the web folder and put in `{}`
