### ISSUE TITLE
Softban Error (dev)

### ISSUE THREAD

**Issue by alb3rto** [PokemonGoF/PokemonGo-Bot#2049]
### Expected Behavior
Start softban fix

### Actual Behavior
`Traceback (most recent call last):
  File "pokecli.py", line 490, in <module>
    main()
  File "pokecli.py", line 70, in main
    bot.tick()
  File "/home/alb3rto/PokeBot/pokemongo_bot/__init__.py", line 89, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/alb3rto/PokeBot/pokemongo_bot/cell_workers/handle_soft_ban.py", line 34, in work
    MoveToFort(self.bot).work()
TypeError: __init__() takes exactly 3 arguments (2 given)
`

### Steps to Reproduce
Get softban and try to get it fixed.

### Other Information
OS: ArchLinux

**Comment by SMWARREN** [comment]
MoveToFort(self.bot).work() needs to be changed to MoveToFort(self, self.bot).work()

File "/****/PokemonGo-Bot-dev 13/pokemongo_bot/cell_workers/handle_soft_ban.py", line 31, in work
MoveToFort(self.bot).work()
TypeError: init() takes exactly 3 arguments (2 given)
