### ISSUE TITLE
ImportError: No module named gpxpy

### ISSUE THREAD

**Issue by peteoconnell** [PokemonGoF/PokemonGo-Bot#2051]
I've pulled the latest dev branch and firstly noticed the config file had changed so backed mine up and modified the new one with my details. Upon running I get the following error:

$ ./run.sh
Traceback (most recent call last):
  File "pokecli.py", line 40, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "C:\Users\pete\Downloads\PokemonGo-Bot\pokemongo_bot\__init__.py", line 16, in <module>
    import cell_workers
  File "C:\Users\pete\Downloads\PokemonGo-Bot\pokemongo_bot\cell_workers\__init__.py", line 13, in <module>
    from follow_path import FollowPath
  File "C:\Users\pete\Downloads\PokemonGo-Bot\pokemongo_bot\cell_workers\follow_path.py", line 3, in <module>
    import gpxpy
ImportError: No module named gpxpy

**Comment by Pacane** [comment]
have you reinstalled the requirements?

**Comment by peteoconnell** [comment]
No I did not - now I've done that I'm good to go - sorry!
