### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by cbogithub** [PokemonGoF/PokemonGo-Bot#2052]
[2016-07-31 12:18:50] [x] PokemonGO Bot v1.0
[2016-07-31 12:18:50] [x] Configuration initialized
[2016-07-31 12:18:51]
[2016-07-31 12:18:51] [x] Address found: Sydney, New South Wales, Australia
[2016-07-31 12:18:51] [x] Position in-game set as: (-33.8688197, 151.2092955, 0.0)
[2016-07-31 12:18:51]
[2016-07-31 12:18:51] Login Error, server busy
root@vultr:/home/PokemonGo-Bot#

i tried play on moblie it ok , and tried bot ...it not working anymore ?????????????????

**Comment by fishredleung** [comment]
Double check your login information, did u type it correctly?

**Comment by cbogithub** [comment]
2016-07-31 12:52:46,325 [   rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 403
Traceback (most recent call last):
  File "pokecli.py", line 139, in <module>
    main()
  File "pokecli.py", line 119, in main
    if not api.login(config.auth_service, config.username, config.password, app_simulation = True):
  File "/home/pgoapi/pgoapi/pgoapi.py", line 126, in login
    response = request.call()
  File "/home/pgoapi/pgoapi/pgoapi.py", line 182, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/home/pgoapi/pgoapi/rpc_api.py", line 108, in request
    if ('auth_ticket' in response_dict) and ('expire_timestamp_ms' in response_dict['auth_ticket']) and (self._auth_provider.is_new_ticket(response_dict['auth_ticket']['expire_timestamp_ms'])):
TypeError: argument of type 'bool' is not iterable



i tested with lib pgoapi and got HTTP server response - needs 200 got 403

**Comment by deshank** [comment]
Same here, it was working before and suddenly I started getting "Login error, server busy".

**Comment by avallete** [comment]
Do you use any VPS provider ? Niantic has banned AWS,DigitalOcean,Azure etc..

That can lead to an 403 error.
