### ISSUE TITLE
walk position error

### ISSUE THREAD

**Issue by MertcanGokgoz** [PokemonGoF/PokemonGo-Bot#2055]
how can i fix this error 

```
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "/home/mertcan/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/home/mertcan/Desktop/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/home/mertcan/Desktop/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/home/mertcan/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 93, in work_on_cell
    worker.work()
  File "/home/mertcan/Desktop/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 30, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "/home/mertcan/Desktop/PokemonGo-Bot/pokemongo_bot/stepper.py", line 88, in _walk_to
    alt, False)
  File "/home/mertcan/Desktop/PokemonGo-Bot/pokemongo_bot/stepper.py", line 102, in _work_at_position
    response_dict = self.api.call()
  File "/home/mertcan/Desktop/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 81, in call
    response = request.request(api_endpoint, self._req_method_list, player_position)
  File "/home/mertcan/Desktop/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 100, in request
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
```

### Other Information
OS:  Xubuntu 16.04
Git Commit: 78c5f2bc8c5aeafb902309583cfab621179bed4e

**Comment by mzupan** [comment]
I think this is due to the app upgrade.. Without looking my guess is the app silently logs in after a certain amount of time or it notices it isn't logged in anymore.

**Comment by batgun** [comment]
i have same issue.

[2016-07-31 19:20:22] [-] Attempted to capture Psyduck- failed.. trying again!
[2016-07-31 19:20:23] [x] Using Greatball (chance: 44.75%)... (59 left!)
[2016-07-31 19:20:23] [x] Oh no! Psyduck vanished! :(
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "/Users/batuhangundogdu/Desktop/PokemonGo-Bot-master/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/Users/batuhangundogdu/Desktop/PokemonGo-Bot-master/pokemongo_bot/stepper.py", line 53, in take_step
    self._walk_to(self.config.walk, *position)
  File "/Users/batuhangundogdu/Desktop/PokemonGo-Bot-master/pokemongo_bot/stepper.py", line 88, in _walk_to
    alt, False)
  File "/Users/batuhangundogdu/Desktop/PokemonGo-Bot-master/pokemongo_bot/stepper.py", line 102, in _work_at_position
    response_dict = self.api.call()
  File "/Users/batuhangundogdu/Desktop/PokemonGo-Bot-master/src/pgoapi/pgoapi/pgoapi.py", line 81, in call
    response = request.request(api_endpoint, self._req_method_list, player_position)
  File "/Users/batuhangundogdu/Desktop/PokemonGo-Bot-master/src/pgoapi/pgoapi/rpc_api.py", line 100, in request
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
