### ISSUE TITLE
ImportError: no module named enum?

### ISSUE THREAD

**Issue by T7pokemon** [PokemonGoF/PokemonGo-Bot#2078]
when i try to run: python pokecli.py on ubuntu.

it give me this error:

root@cyborg:/home/cyborg/Documents/PokemonGo-Bot# python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "/home/cyborg/Documents/PokemonGo-Bot/pokemongo_bot/__init__.py", line 20, in <module>
    from item_list import Item
  File "/home/cyborg/Documents/PokemonGo-Bot/pokemongo_bot/item_list.py", line 1, in <module>
    from enum import Enum
ImportError: No module named enum

can anyone please help me out? =D
thanks!!

**Comment by tim427** [comment]
Have you upgraded/installed the "pip requirments"?

Hint: `pip install --upgrade -r requirements.txt`

**Comment by helium96** [comment]
This should work 

`pip install enum `
