### ISSUE TITLE
Crashes after 8s

### ISSUE THREAD

**Issue by roach013** [PokemonGoF/PokemonGo-Bot#2093]
##Bot crashes after running 8seconds

[21:51:37]  PokemonGO Bot v1.0 
[21:51:37]  Configuration initialized 
[21:51:38] 
[21:51:38] Location Found: -------------
[21:51:38] GeoPosition: (--------------)
[21:51:38] 
[21:51:38] [x] Parsing cached location...
[21:51:38] [x] Parsing cached location failed, try to use the initial location...
[21:51:38] Attempting login to Pokemon Go.
[21:51:42]  Login to Pokemon Go successful. 
[21:51:44] 
[21:51:44]  --- username --- 
[21:51:44]  Pokemon Bag: 0/250 
[21:51:44]  Items: 54/350 
[21:51:44]  Stardust: 0 | Pokecoins: 0 
[21:51:44]  PokeBalls: 50 | GreatBalls: 0 | UltraBalls: 0 
[21:51:44]  RazzBerries: 0 | BlukBerries: 0 | NanabBerries: 0 
[21:51:44]  LuckyEgg: 0 | Incubator: 0 | TroyDisk: 0 
[21:51:44]  Potion: 0 | SuperPotion: 0 | HyperPotion: 0 
[21:51:44]  Incense: 2 | IncenseSpicy: 0 | IncenseCool: 0 
[21:51:44]  Revive: 0 | MaxRevive: 0 
[21:51:44] 
[21:51:44] 
[21:51:45] 
[21:51:45]  Ran for 0:00:08 
Traceback (most recent call last):
  File "pokecli.py", line 494, in <module>
    main()
  File "pokecli.py", line 81, in main
    report_summary(bot)
  File "pokecli.py", line 92, in report_summary
    logger.log('Total XP Earned: {}  Average: {:.2f}/h'.format(metrics.xp_earned(), metrics.xp_per_hour()), 'cyan')
  File "/root/Downloads/PokemonGo-Bot/pokemongo_bot/metrics.py", line 28, in xp_earned
    return self.xp['latest'] - self.xp['start']
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

**Comment by Pacane** [comment]
What commit/branch?

**Comment by roach013** [comment]
d5e787c/dev

**Comment by julien-blanchon** [comment]
Same error
