### ISSUE TITLE
[dev] handle_soft_ban.py error | one argument missing in __init__()

### ISSUE THREAD

**Issue by toremielck** [PokemonGoF/PokemonGo-Bot#2104]
Traceback (most recent call last):
  File "pokecli.py", line 494, in <module>
    main()
  File "pokecli.py", line 70, in main
    bot.tick()
  File "/Users/toremielck/Desktop/PokemonGo-Bot-kajoschooPTC/pokemongo_bot/__init__.py", line 85, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/Users/toremielck/Desktop/PokemonGo-Bot-kajoschooPTC/pokemongo_bot/cell_workers/handle_soft_ban.py", line 31, in work
    MoveToFort(self.bot).work()
TypeError: __init__() takes exactly 3 arguments (2 given)

**Comment by bigkraig** [comment]
this should fix it
```
diff --git a/pokemongo_bot/cell_workers/handle_soft_ban.py b/pokemongo_bot/cell_workers/handle_soft_ban.py
index 0cfa700..fd12b13 100644
--- a/pokemongo_bot/cell_workers/handle_soft_ban.py
+++ b/pokemongo_bot/cell_workers/handle_soft_ban.py
@@ -28,7 +28,7 @@ class HandleSoftBan(BaseTask):
         )
 
         if fort_distance > Constants.MAX_DISTANCE_FORT_IS_REACHABLE:
-            MoveToFort(self.bot).work()
+            MoveToFort(self.bot, self.bot.config).work()
             self.bot.recent_forts = self.bot.recent_forts[0:-1]
             if forts[0]['id'] in self.bot.fort_timeouts:
                 del self.bot.fort_timeouts[forts[0]['id']]
```

**Comment by toremielck** [comment]
How do i apply the fix?

**Comment by bigkraig** [comment]
sorry, i think its this. open up the file and change the line with a - to look like the line with the +.

```
diff --git a/pokemongo_bot/cell_workers/handle_soft_ban.py b/pokemongo_bot/cell_workers/handle_soft_ban.py
index 0cfa700..f112310 100644
--- a/pokemongo_bot/cell_workers/handle_soft_ban.py
+++ b/pokemongo_bot/cell_workers/handle_soft_ban.py
@@ -28,7 +28,7 @@ class HandleSoftBan(BaseTask):
         )
 
         if fort_distance > Constants.MAX_DISTANCE_FORT_IS_REACHABLE:
-            MoveToFort(self.bot).work()
+            MoveToFort(self.bot, self.config).work()
             self.bot.recent_forts = self.bot.recent_forts[0:-1]
             if forts[0]['id'] in self.bot.fort_timeouts:
                 del self.bot.fort_timeouts[forts[0]['id']]
```

**Comment by toremielck** [comment]
Works! Thank you!
