### ISSUE TITLE
Location parsing error

### ISSUE THREAD

**Issue by jaguar2187** [PokemonGoF/PokemonGo-Bot#2111]
### Expected Behavior
Location is parsed without errors

### Actual Behavior
The location given using -l could not be parsed. Checking for a cached location.
[2016-07-31 20:48:43] [x] PokemonGO Bot v1.0
[2016-07-31 20:48:43] [x] Configuration initialized
[2016-07-31 20:48:44] [x] The location given using -l could not be parsed. Checking for a cached location.
[2016-07-31 20:48:46] [#] Username: Deleted
[2016-07-31 20:48:46] [#] Acccount Creation: Deleted
[2016-07-31 20:48:47] [#] Bag Storage: 393/350
[2016-07-31 20:48:47] [#] Pokemon Storage: 71/250
[2016-07-31 20:48:47] [#] Stardust: 76572
[2016-07-31 20:48:47] [#] Pokecoins: 0
[2016-07-31 20:48:47] [#] PokeBalls: 0
[2016-07-31 20:48:47] [#] GreatBalls: 96
[2016-07-31 20:48:47] [#] UltraBalls: 29
[2016-07-31 20:48:47] [#] -- Level: 21
[2016-07-31 20:48:47] [#] -- Experience: 261009
[2016-07-31 20:48:47] [#] -- Experience until next level: 73991
[2016-07-31 20:48:47] [#] -- Pokemon Captured: 638
[2016-07-31 20:48:47] [#] -- Pokestops Visited: 639
[2016-07-31 20:48:47] [#]
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "/Users/Jack2/PokemonGo-Bot/pokemongo_bot/__init__.py", line 32, in start
    self.stepper = Stepper(self)
  File "/Users/Jack2/PokemonGo-Bot/pokemongo_bot/stepper.py", line 32, in __init__
    self.origin_lat = self.bot.position[0]
AttributeError: 'PokemonGoBot' object has no attribute 'position'

### Steps to Reproduce
First run of bot fails with location error.
Just any location in letters.
Location in coordinates goes fine

### Other Information
OS: OS X El Capitan 10.11.6 
Master branch
Git Commit: 78c5f2bc8c5aeafb902309583cfab621179bed4e

**Comment by sdhormess** [comment]
me too

**Comment by refast** [comment]
+1

**Comment by fmierzwa** [comment]
same here

**Comment by MBlokhuijzen** [comment]
After a day of searching not knowing anything about Python I found a solution.

You get this error because it can't parse the location given in the config file or with the -l keyword, and it doesn't have a cached location.
It says so in the provided log at this line: [2016-07-31 20:48:44] [x] The location given using -l could not be parsed. Checking for a cached location.


**Workaround:** Enter Latitude Longitude location, it can be parsed correctly and the bot will work.

**Example:** "location": "52.091788, 5.118380"
