### ISSUE TITLE
AttributeError: 'HandleSoftBan' object has no attribute 'has_space_for_loot'

### ISSUE THREAD

**Issue by azraelppuk** [PokemonGoF/PokemonGo-Bot#2112]
### Expected Behavior

Softban fix kicks in.

### Actual Behavior

Traceback (most recent call last):
  File "pokecli.py", line 494, in <module>
    main()
  File "pokecli.py", line 70, in main
    bot.tick()
  File "/home/pi/PokemonGo-Bot-Dev-31/PokemonGo-Bot/pokemongo_bot/__init__.py", line 85, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/pi/PokemonGo-Bot-Dev-31/PokemonGo-Bot/pokemongo_bot/cell_workers/handle_soft_ban.py", line 31, in work
    MoveToFort(self, self.bot).work()
  File "/home/pi/PokemonGo-Bot-Dev-31/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort.py", line 14, in work
    if not self.should_run():
  File "/home/pi/PokemonGo-Bot-Dev-31/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort.py", line 11, in should_run
    return (self.bot.has_space_for_loot()) or self.bot.softban
AttributeError: 'HandleSoftBan' object has no attribute 'has_space_for_loot'

### Steps to Reproduce
Get softban.
Wait for softban fix to kick in.

### Other Information
OS: linux
Git Commit: cc3e9545d65fe764602ebb73f557cd797038b374

**Comment by toremielck** [comment]
Second this.

OS: Mac OSX
