### ISSUE TITLE
DEV Bot stop working after 9-20 minutes with ServerBusyorOfflineException

### ISSUE THREAD

**Issue by AcorpBG** [PokemonGoF/PokemonGo-Bot#2115]
### Expected Behavior
Bot should run constantly without problems. Or at least autorecover.

### Actual Behavior
[16:37:21]  PokemonGO Bot v1.0 
After 9 minutes the bot produce the following:
[16:46:17]  Server seems to be busy or offline - try again - 1/5 
[16:46:18]  Server seems to be busy or offline - try again - 2/5 
[16:46:18]  Server seems to be busy or offline - try again - 3/5 
[16:46:20]  Server seems to be busy or offline - try again - 4/5 
[16:46:20]  Server seems to be busy or offline - try again - 5/5 
[16:46:20]  Server seems to be busy or offline - try again - 1/5 
[16:46:21]  Server seems to be busy or offline - try again - 2/5 
[16:46:22]  Server seems to be busy or offline - try again - 3/5 
[16:46:23]  Server seems to be busy or offline - try again - 4/5 
[16:46:25]  Server seems to be busy or offline - try again - 5/5 
Traceback (most recent call last):
  File "pokecli.py", line 494, in <module>
  File "pokecli.py", line 81, in main
  File "pokecli.py", line 89, in report_summary
  File "pokemongo_bot\metrics.py", line 75, in capture_stats
  File "pokemongo_bot\api_wrapper.py", line 74, in call
pgoapi.exceptions.ServerBusyOrOfflineException

### Additional information
The servers are working properly the master branch work properly.
Changing the api_wrapper requests per second to 1 delay the problem for another 9 minutes or so
I tried stoping the SpinForts,MoveForts Tasks.
Also tried both path and spiral.

It seems after some number of API calls the servers stop answering. 
This time may depend on the area where the bot is running. 
From the debug logs it seems that GET MAP OBJECTS requests are the first 5 failing attempts 
status_code: 2
request_id: 8145806132888207460
requests {
  request_type: GET_MAP_OBJECTS

then 5 attempts on 
status_code: 2
request_id: 8145806132888207460
requests {
  request_type: GET_INVENTORY
}
requests {
  request_type: GET_PLAYER
}

### Other Information
OS: Win7
Git Commit: 3fe8eb07c098c45c87db0d643d579ac4f7464cf6

**Comment by raxxon** [comment]
Duplicate issue - See: https://github.com/PokemonGoF/PokemonGo-Bot/issues/2009
