### ISSUE TITLE
NotLoggedInException

### ISSUE THREAD

**Issue by sdhormess** [PokemonGoF/PokemonGo-Bot#2116]
After new checkout of dev branch i get this cant login message.

I'm using the lon, lat string.. 

Please Help me.. Cant developing,

**Comment by Pacane** [comment]
what's your location? It's sometimes due to bad location syntax.

**Comment by aypro** [comment]
Same problem here, tried both PTC and google auth, the bot was working fine last night

> [22:34:43]  PokemonGO Bot v1.0
[22:34:43]  Configuration initialized
2016-07-31 22:34:43,671 [pgoapi.pgoapi] [ INFO] Create new request...
2016-07-31 22:34:43,671 [pgoapi.pgoapi] [ INFO] Adding 'GET_INVENTORY' to RPC request
2016-07-31 22:34:43,671 [pgoapi.pgoapi] [ INFO] Adding 'GET_PLAYER' to RPC request
[22:34:43]  Not logged in!
Traceback (most recent call last):
  File "pokecli.py", line 465, in <module>
    main()
  File "pokecli.py", line 81, in main
    report_summary(bot)
  File "pokecli.py", line 89, in report_summary
    metrics.capture_stats()
  File "C:\PokemonGo-Bot\pokemongo_bot\metrics.py", line 75, in capture_stats
    response_dict = self.bot.api.call()
  File "C:\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 57, in call
    if not self._can_call():
  File "C:\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 29, in _can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException

**Comment by showcheap** [comment]
I have code fix on my fork, but not yet make a Pull Request

**Comment by herukrayz** [comment]
i faced with same error msg after bot running 1hr or more
this is my location config
"location": "-33.857783, 151.215069",

**Comment by showcheap** [comment]
Simple fix : https://github.com/showcheap/PokemonGo-Bot/commit/6350379dd10e9a8b23f0a8dd63cde68b2ecb01d5
