### ISSUE TITLE
Install requirements UnicodeDecodeError

### ISSUE THREAD

**Issue by D4ltaOne** [PokemonGoF/PokemonGo-Bot#2127]
### Expected Behavior
Install requirements

### Actual Behavior
UnicodeDecodeError

### Other Information
OS: Windows

When i try to pip2 install -r requirements.txt i get the following Exception:

Exception:
Traceback (most recent call last):
  File "F:\Python27\lib\site-packages\pip\basecommand.py", line 223, in main
    status = self.run(options, args)
  File "F:\Python27\lib\site-packages\pip\commands\install.py", line 280, in run

    requirement_set.prepare_files(finder)
  File "F:\Python27\lib\site-packages\pip\req\req_set.py", line 317, in prepare_
files
    functools.partial(self._prepare_file, finder))
  File "F:\Python27\lib\site-packages\pip\req\req_set.py", line 304, in _walk_re
q_to_install
    more_reqs = handler(req_to_install)
  File "F:\Python27\lib\site-packages\pip\req\req_set.py", line 439, in _prepare
_file
    req_to_install.populate_link(finder, self.upgrade)
  File "F:\Python27\lib\site-packages\pip\req\req_install.py", line 244, in popu
late_link
    self.link = finder.find_requirement(self, upgrade)
  File "F:\Python27\lib\site-packages\pip\index.py", line 486, in find_requireme
nt
    all_versions = self._find_all_versions(req.name)
  File "F:\Python27\lib\site-packages\pip\index.py", line 404, in _find_all_vers
ions
    index_locations = self._get_index_urls_locations(project_name)
  File "F:\Python27\lib\site-packages\pip\index.py", line 378, in _get_index_url
s_locations
    page = self._get_page(main_index_url)
  File "F:\Python27\lib\site-packages\pip\index.py", line 810, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "F:\Python27\lib\site-packages\pip\index.py", line 920, in get_page
    "Cache-Control": "max-age=600",
  File "F:\Python27\lib\site-packages\pip\_vendor\requests\sessions.py", line 47
7, in get
    return self.request('GET', url, **kwargs)
  File "F:\Python27\lib\site-packages\pip\download.py", line 373, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "F:\Python27\lib\site-packages\pip\_vendor\requests\sessions.py", line 46
5, in request
    resp = self.send(prep, **send_kwargs)
  File "F:\Python27\lib\site-packages\pip\_vendor\requests\sessions.py", line 60
5, in send
    r.content
  File "F:\Python27\lib\site-packages\pip\_vendor\requests\models.py", line 750,
 in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes
()
  File "F:\Python27\lib\site-packages\pip\_vendor\requests\models.py", line 673,
 in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "F:\Python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\resp
onse.py", line 307, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "F:\Python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\resp
onse.py", line 243, in read
    data = self._fp.read(amt)
  File "F:\Python27\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py",
line 54, in read
    self.__callback(self.__buf.getvalue())
  File "F:\Python27\lib\site-packages\pip\_vendor\cachecontrol\controller.py", l
ine 244, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "F:\Python27\lib\site-packages\pip\download.py", line 276, in set
    return super(SafeFileCache, self).set(*args, **kwargs)
  File "F:\Python27\lib\site-packages\pip\_vendor\cachecontrol\caches\file_cache
.py", line 99, in set
    with self.lock_class(name) as lock:
  File "F:\Python27\lib\site-packages\pip\_vendor\lockfile\mkdirlockfile.py", li
ne 18, in __init__
    LockBase.__init__(self, path, threaded, timeout)
  File "F:\Python27\lib\site-packages\pip\_vendor\lockfile\__init__.py", line 18
9, in __init__
    hash(self.path)))
  File "F:\Python27\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 4: ordinal
not in range(128)

Any Fixes?

**Comment by DayBr3ak** [comment]
Has your C:/Users/{name} special characters?
