### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by Cameron1120** [PokemonGoF/PokemonGo-Bot#2158]
### Expected Behavior
Install -r requirements.

### Actual Behavior

**Error is:**
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/vp/048s_4x51jqfq4f73yq253yc0000gn/T/pip-build-uP7IxE/protobuf-to-dict/

**Full Output:** 
`Collecting numpy==1.11.0 (from -r requirements.txt (line 1))
  Using cached numpy-1.11.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting networkx==1.11 (from -r requirements.txt (line 2))
  Using cached networkx-1.11-py2.py3-none-any.whl
Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b#egg=pgoapi (from -r requirements.txt (line 3))
  Skipping because already up-to-date.
Collecting geopy==1.11.0 (from -r requirements.txt (line 4))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf==3.0.0b4 (from -r requirements.txt (line 5))
  Using cached protobuf-3.0.0b4-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in ./lib/python2.7/site-packages (from -r requirements.txt (line 6))
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 7))
  Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 8))
  Using cached gpsoauth-0.3.0.tar.gz
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 9))
  Using cached protobuf-to-dict-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/nosexcover/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    Couldn't find index page for 'nosexcover' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    No local packages or working download links found for nosexcover
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vp/048s_4x51jqfq4f73yq253yc0000gn/T/pip-build-uP7IxE/protobuf-to-dict/setup.py", line 25, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/cameronroland/PokemonGo-Bot/lib/python2.7/site-packages/setuptools/dist.py", line 348, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Users/cameronroland/PokemonGo-Bot/lib/python2.7/site-packages/setuptools/dist.py", line 394, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/cameronroland/PokemonGo-Bot/lib/python2.7/site-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/cameronroland/PokemonGo-Bot/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1098, in best_match
        return self.obtain(req, installer)
      File "/Users/cameronroland/PokemonGo-Bot/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1110, in obtain
        return installer(requirement)
      File "/Users/cameronroland/PokemonGo-Bot/lib/python2.7/site-packages/setuptools/dist.py", line 461, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/cameronroland/PokemonGo-Bot/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 658, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('nosexcover')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/vp/048s_4x51jqfq4f73yq253yc0000gn/T/pip-build-uP7IxE/protobuf-to-dict/`

### Steps to Reproduce
In dev try to $ pip install -r requirements.txt 

### Other Information
OS: mac
Git Commit: d42e32491b675ac75619e9e4cacc6b988049e5c2
Python Version: 2.7.10

**Comment by adamstrawson** [comment]
This ticket solve this for me;

https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1475#issuecomment-234864434

**Comment by longnalou** [comment]
I can't see ticket solve 

> This ticket solve this for me;

https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1475#issuecomment-234864434

**Comment by natvnn** [comment]
See here*
https://github.com/PokemonGoMap/PokemonGo-Map/issues/200
