### ISSUE TITLE
can't run bot due to an error on player_data

### ISSUE THREAD

**Issue by kevlarcade** [PokemonGoF/PokemonGo-Bot#2162]
### Expected Behavior
bot.start()

### Actual Behavior
KeyError: 'player_data'

### Steps to Reproduce
git pull
cp config.json.example config.json
set all information
cp release_config.json.example release_config.json
python pokecli.py --config config.json

### Other Information
OS: 4.6.4-1-ARCH LINUX
Git Commit: 4182e93f9bfbe471d07b74e95c55cdfbacda127b
Python Version: Python 2.7.12

### Full output

[2016-08-01 02:18:26] [x] PokemonGO Bot v1.0
[2016-08-01 02:18:26] [x] Configuration initialized
[2016-08-01 02:18:26] 
[2016-08-01 02:18:26] [x] Address found: <my_location>
[2016-08-01 02:18:26] [x] Position in-game set as: (<my_lat_long_coord>)
[2016-08-01 02:18:26] 
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "/home/kevlar/git/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/home/kevlar/git/PokemonGo-Bot/pokemongo_bot/__init__.py", line 151, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'player_data'

**Comment by eggins** [comment]
`pip install -r requirements.txt`

**Comment by kevlarcade** [comment]
It doesn't resolve this issue
