### ISSUE TITLE
UnboundLocalError: local variable 'itemcount' referenced before assignment

### ISSUE THREAD

**Issue by pokecunt** [PokemonGoF/PokemonGo-Bot#2199]
```
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 169, in _setup_api
    self.get_inventory_count('item'), player['max_item_storage']))
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 425, in get_inventory_count
    return itemcount
UnboundLocalError: local variable 'itemcount' referenced before assignment
```

**Comment by N3W4L** [comment]
Hi, I have the same problem here, did you find the issue ? 
Many thanks :)
