### ISSUE TITLE
pip install googlemaps

### ISSUE THREAD

**Issue by Adiwena0putra** [PokemonGoF/PokemonGo-Bot#2224]
I am trying to install googlemaps module, but this error apears... What should i do ?(sorry i am new to linux and programming)

adiwena@adiwena-Inspiron-3443:~/PokemonGo-Bot$ pip install googlemaps
Downloading/unpacking googlemaps
  Downloading googlemaps-2.4.4-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): requests<=2.10.0 in /usr/lib/python2.7/dist-packages (from googlemaps)
Installing collected packages: googlemaps
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 193, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/googlemaps'

Storing debug log for failure in /home/adiwena/.pip/pip.log

### Other Information
OS: ubuntu 14.04
Python Version:2.7.6

**Comment by tstumm** [comment]
If you don't want to use virtual environments just do `sudo pip install -r requirements.txt`

**Comment by xorinzor** [comment]
This has nothing to do with the bot, next time please dont open the issue here, either seek help in the slack chat or go to the proper channel.

and @tstumm just answered it. whenever you have an permission denied issue in linux it's usually because you need root permissions by prepending `sudo` to the command.
