### ISSUE TITLE
lure attraction breaks softban with followpath

### ISSUE THREAD

**Issue by Philipp59** [PokemonGoF/PokemonGo-Bot#2278]
```
[00:12:17]  Loot:  
[00:12:17]  [#] Nothing found. 
[00:12:17]  Possibly searching too often - taking a short rest :) 
[00:12:17]  [!] Possibly got softban too... 
[00:12:23]  Got softban, fixing... 
[00:12:24] 
[00:12:24]  Ran for 0:11:08 
[00:12:24]  Total XP Earned: 11345  Average: 61102.69/h 
[00:12:24]  Travelled 0.47km 
[00:12:24]  Visited 36 stops 
[00:12:24]  Encountered 35 pokemon, 32 caught, 0 released, 4 evolved, 1 never seen before 
[00:12:24]  Threw 35 poke balls
[00:12:24]  Earned 3200 Stardust 
[00:12:24] 
[00:12:24]  Highest CP Pokemon: Electabuzz [CP: 1314] [IV: 2/12/7] Potential: 0.47  
[00:12:24]  Most Perfect Pokemon: Magikarp [CP: 63] [IV: 15/15/9] Potential: 0.87  
Traceback (most recent call last):
  File "pokecli.py", line 452, in <module>
    main()
  File "pokecli.py", line 71, in main
    bot.tick()
  File "/Users/xxx/Desktop/bots/PokemonGo-BotFix/pokemongo_bot/__init__.py", line 88, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/Users/xxx/Desktop/bots/PokemonGo-BotFix/pokemongo_bot/cell_workers/handle_soft_ban.py", line 31, in work
    MoveToFort(self.bot, config=None).work()
  File "/Users/xxx/Desktop/bots/PokemonGo-BotFix/pokemongo_bot/cell_workers/base_task.py", line 6, in __init__
    self.initialize()
  File "/Users/xxx/Desktop/bots/PokemonGo-BotFix/pokemongo_bot/cell_workers/move_to_fort.py", line 13, in initialize
    self.lure_attraction = self.config.get("lure_attraction", True)
AttributeError: 'NoneType' object has no attribute 'get'
``` 
I use follow path task without a layer of movetofort task,
worked great before lure attraction was pulled. Error with softban task.

proof : (works with movetofort task) removed # from spin 

> [00:22:42]  Now at Pokestop: America's Society 
> [00:22:42]  Spinning ... 
> [00:22:42]  Loot:  
> [00:22:42]  [#] Nothing found. 
> [00:22:42]  Possibly searching too often - taking a short rest :) 
> [00:22:42]  [!] Possibly got softban too... 
> [00:22:44] Moving towards fort Staring Head Statue, 0.08km left (attraction of lure 0.16km)
> [00:22:44] Arrived at pokestop.
> [00:22:45]  Got softban, fixing... 
> [00:22:45] Starting 50 spins...
> [00:22:49] Spin 10
> [00:22:54] Spin 20
> [00:23:01] Spin 30
> [00:23:10] Spin 40
> [00:23:16] Spin 50
> [00:23:16] Softban should be fixed.
> [00:23:16] Something rustles nearby!
> [00:23:17]  A Wild Pidgey appeared! [CP 201] [Potential 0.31] 
> [00:23:17] IV [Attack/Defense/Stamina] = [1/9/4]

**Comment by yungfrancis** [comment]
This happens too when you restart the application with location_cache = true, you defined a followpath and you're in a pokestop, the application glitches because next point is 0.00 km away to the next pokestop because it follows the followpath, rebooted with location_cache = false from another point and everything is ok now.

(I think I explained correctly)

**Comment by Philipp59** [comment]
nope     "location_cache": false,

i changed nothing on my config just pulled the lure attraction setup and run 2bots with move to fort task with lure attraction to test whether its better then just my path file.
Before the lure attraction pull the path setup (with no movetofort layer) were not breaking when spin -> no dict -> softban task

**Comment by yungfrancis** [comment]
I'm not saying that is what happens to you, could happen with my condition too...

Sorry I can't help you :(
