### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'syntax'

### ISSUE THREAD

**Issue by silicite** [PokemonGoF/PokemonGo-Bot#233]
Can not initialize. All requirements met - traceback listed below
Using latest dev branch

Traceback (most recent call last):
  File "pokecli.py", line 42, in <module>
    from pokemongo_bot import PokemonGoBot
  File "/Users/silicite/Desktop/bot/PokemonGo-Bot/pokemongo_bot/__init__.py", line 10, in <module>
    from pgoapi import PGoApi
  File "/Users/silicite/Desktop/bot/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 19, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/Users/silicite/Desktop/bot/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 33, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/Users/silicite/Desktop/bot/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 40, in <module>
    from POGOProtos.Networking.Envelopes_pb2 import RequestEnvelope
  File "/Users/silicite/Desktop/bot/PokemonGo-Bot/src/pgoapi/pgoapi/protos/POGOProtos/Networking/Envelopes_pb2.py", line 16, in <module>
    from POGOProtos.Networking import Requests_pb2 as POGOProtos_dot_Networking_dot_Requests__pb2
  File "/Users/silicite/Desktop/bot/PokemonGo-Bot/src/pgoapi/pgoapi/protos/POGOProtos/Networking/Requests_pb2.py", line 23, in <module>
    ENCOUNTER\x10\x91\x01\x12!\n\x1c\x43OLLECT_DAILY_DEFENDER_BONUS\x10\x92\x01\x12\x14\n\x0fUPGRADE_POKEMON\x10\x93\x01\x12\x19\n\x14SET_FAVORITE_POKEMON\x10\x94\x01\x12\x15\n\x10NICKNAME_POKEMON\x10\x95\x01\x12\x10\n\x0b\x45QUIP_BADGE\x10\x96\x01\x12\x19\n\x14SET_CONTACT_SETTINGS\x10\x97\x01\x12\x15\n\x10GET_ASSET_DIGEST\x10\xac\x02\x12\x16\n\x11GET_DOWNLOAD_URLS\x10\xad\x02\x12\x1c\n\x17GET_SUGGESTED_CODENAMES\x10\x91\x03\x12\x1d\n\x18\x43HECK_CODENAME_AVAILABLE\x10\x92\x03\x12\x13\n\x0e\x43LAIM_CODENAME\x10\x93\x03\x12\x0f\n\nSET_AVATAR\x10\x94\x03\x12\x14\n\x0fSET_PLAYER_TEAM\x10\x95\x03\x12\x1b\n\x16MARK_TUTORIAL_COMPLETE\x10\x96\x03\x12\x16\n\x11LOAD_SPAWN_POINTS\x10\xf4\x03\x12\t\n\x04\x45\x43HO\x10\x9a\x05\x12\x1b\n\x16\x44\x45\x42UG_UPDATE_INVENTORY\x10\xbc\x05\x12\x18\n\x13\x44\x45\x42UG_DELETE_PLAYER\x10\xbd\x05\x12\x17\n\x12SFIDA_REGISTRATION\x10\xa0\x06\x12\x15\n\x10SFIDA_ACTION_LOG\x10\xa1\x06\x12\x18\n\x13SFIDA_CERTIFICATION\x10\xa2\x06\x12\x11\n\x0cSFIDA_UPDATE\x10\xa3\x06\x12\x11\n\x0cSFIDA_ACTION\x10\xa4\x06\x12\x11\n\x0cSFIDA_DOWSER\x10\xa5\x06\x12\x12\n\rSFIDA_CAPTURE\x10\xa6\x06\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'

**Comment by Aiyubi** [comment]
What I had to change to fix this:
* Open requirements and cur out the hash in line 1(but let the egg in)
* Install new requirements with --upgrade

**Comment by douglascamata** [comment]
@Aiyubi instructions should fix the issue. I'm closing this.

**Comment by blg-andreasbraun** [comment]
I still get this error, even with the fix from @Aiyubi
