### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by andruxabr** [PokemonGoF/PokemonGo-Bot#2336]
Traceback (most recent call last):
  File "C:/python/PokemonGo-Bot-master/pokecli.py", line 220, in <module>
    main()
  File "C:/python/PokemonGo-Bot-master/pokecli.py", line 206, in main
    bot.start()
  File "C:\python\PokemonGo-Bot-master\pokemongo_bot\__init__.py", line 31, in start
    self._setup_api()
  File "C:\python\PokemonGo-Bot-master\pokemongo_bot\__init__.py", line 146, in _setup_api
    response_dict = self.api.call()
  File "C:\Python27\lib\site-packages\pgoapi-1.1.6-py2.7.egg\pgoapi\pgoapi.py", line 89, in __getattr__
    raise AttributeError
AttributeError

How to solve problem? Help please

**Comment by maestroi** [comment]
Please update with 
``'pip install -r requirements.txt```
if you not using virtualenv witch we recommend.
``'sudo pip install -r requirements.txt```
or run as administrator

**Comment by ulou** [comment]
same here, @maestroi you comment doesn't solve it

**Comment by reddivision** [comment]
#2357 fixes this. The problem is you're running the newest pgoapi (1.1.6) with a dev branch codebase that wasn't prepared for it. @maestroi's answer would have actually solved your issue as long as you had uninstalled the existing pgoapi module (i.e. deleted the `src/` directory)
