### ISSUE TITLE
Help :(

### ISSUE THREAD

**Issue by JaroSound** [PokemonGoF/PokemonGo-Bot#2373]
[20:04:55]  PokemonGO Bot v1.0
Traceback (most recent call last):
  File "./pokecli.py", line 470, in <module>
    main()
  File "./pokecli.py", line 53, in main
    config = init_config()
  File "./pokecli.py", line 124, in init_config
    load.update(json.load(data))
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 106 column 7 (char 2820)

How to fix it? I cant run bot.

**Comment by Extrememist** [comment]
Check your config at jsonlint.com :)

**Comment by Marco208** [comment]
Check config at line 106 char pos 7, probably need to add a ","
