### ISSUE TITLE
Bot no longer starts

### ISSUE THREAD

**Issue by wait321** [PokemonGoF/PokemonGo-Bot#2376]
I pulled the latest dev commit (https://github.com/PokemonGoF/PokemonGo-Bot/commit/d5622898c0817c7f4913e1cec6076a687e4acf16) and now the bot won't start up

[11:15:57]  PokemonGO Bot v1.0 
[11:15:57]  Configuration initialized 
[11:15:57]  Not logged in! 
Traceback (most recent call last):
  File "pokecli.py", line 442, in <module>
    main()
  File "pokecli.py", line 85, in main
    report_summary(bot)
  File "pokecli.py", line 93, in report_summary
    metrics.capture_stats()
  File "/Users/yitao/Downloads/pokemongo/PokemonGo-Bot/pokemongo_bot/metrics.py", line 75, in capture_stats
    response_dict = self.bot.api.call()
  File "/Users/yitao/Downloads/pokemongo/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 57, in call
    if not self._can_call():
  File "/Users/yitao/Downloads/pokemongo/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 29, in _can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
(PokemonGo-Bot)

**Comment by Marco208** [comment]
Post your config, check your credentials. Be sure to use code tags

**Comment by julien-blanchon** [comment]
Same error and my credential and my location was valid.

**Comment by wait321** [comment]
I resolved it by removing "proxy_ip" configuration

**Comment by kinvaris** [comment]
I got this problem too, for me my password was to long for the bot.
