### ISSUE TITLE
Pokemongobot object has no attribute 'position'

### ISSUE THREAD

**Issue by HelloTroy** [PokemonGoF/PokemonGo-Bot#2389]
### Expected Behavior

When I go to json.config and add a latitude and longitude or city/state combination they do not work.

### Actual Behavior
[2016-08-02 12:56:25] [x] PokemonGO Bot v1.0
[2016-08-02 12:56:25] [x] Configuration initialized
**[2016-08-02 12:56:26] [x] The location given using -l could not be parsed. Checking for a cached location.** 
[2016-08-02 12:56:27] [#] Username: HIDDEN
[2016-08-02 12:56:27] [#] Acccount Creation: HIDDEN
[2016-08-02 12:56:28] [#] Bag Storage: 296/350
[2016-08-02 12:56:28] [#] Pokemon Storage: 234/250
[2016-08-02 12:56:28] [#] Stardust: 56617
[2016-08-02 12:56:28] [#] Pokecoins: 0
[2016-08-02 12:56:28] [#] PokeBalls: 19
[2016-08-02 12:56:28] [#] GreatBalls: 3
[2016-08-02 12:56:28] [#] UltraBalls: 0
[2016-08-02 12:56:28] [#] -- Level: 16
[2016-08-02 12:56:28] [#] -- Experience: 137823
[2016-08-02 12:56:28] [#] -- Experience until next level: 2177
[2016-08-02 12:56:28] [#] -- Pokemon Captured: 430
[2016-08-02 12:56:28] [#] -- Pokestops Visited: 322
[2016-08-02 12:56:28] [#]
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  **File "/Users/tr/PokemonGo-Bot/pokemongo_bot/__init__.py", line 32, in start
    self.stepper = Stepper(self)
  File "/Users/tr/PokemonGo-Bot/pokemongo_bot/stepper.py", line 32, in __init__
    self.origin_lat = self.bot.position[0]
AttributeError: 'PokemonGoBot' object has no attribute 'position'**

### Steps to Reproduce
just type python pokecli.py

### Other Information
OS: OS X YOSEMITE
Git Commit: 
Python Version: 2.7

**Comment by Marco208** [comment]
Did you checkout to dev?

**Comment by HelloTroy** [comment]
@Marco208 meaning? Confused, sorry

**Comment by JSchwerberg** [comment]
That location is likely not precise enough -- a tenth of a degree in latitude is **huge** -- roughly 6.9 miles.

**Comment by HelloTroy** [comment]
Location precision is not an issue, tried it to varying degrees of distance

**Comment by JSchwerberg** [comment]
What is the most precise you've tried?  Also, what commit, and what Python version?

**Comment by HelloTroy** [comment]
Down to exactly what google says

**Comment by yungfrancis** [comment]
I had the error changing my location (since last commit few mins ago to include the new pgoapi), I used another precision (less accurate) and stopped working, I used this format, and it should work for you too:

"location": "43.3696709, -8.396026, 17"

Regards.

**Comment by HelloTroy** [comment]
Starting over with yungfrancis addition, will let you know!

**Comment by HelloTroy** [comment]
@yungfrancis You the man, what location is that?

WORKS.

**Comment by yungfrancis** [comment]
@HelloTroy haha, cheers bud, A Coruña, Spain ;)

**Comment by zchen1018** [comment]
@yungfrancis what does the number 17 at the end mean?

**Comment by yungfrancis** [comment]
@zchen1018 altitude
