### ISSUE TITLE
ValueError:Extra data? :(

### ISSUE THREAD

**Issue by RaizenInstinct** [PokemonGoF/PokemonGo-Bot#2401]
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 197, in main
    config = init_config()
  File "pokecli.py", line 174, in init_config
    config.release_config.update(json.load(data))
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 4 column 6 - line 24 column 1 (char 46 - 397)

JSON file: 
![image](https://cloud.githubusercontent.com/assets/20803732/17347029/082281f0-590e-11e6-999e-5a6c58dd5ee7.png)

**Comment by hackenho** [comment]
Looks like an error on your config file.. Check it with jsonlint

**Comment by RaizenInstinct** [comment]
the screenshot is from jsonlint. It's saying the JSON file is valid...
