### ISSUE TITLE
Key Error: Player Data

### ISSUE THREAD

**Issue by kinesivan** [PokemonGoF/PokemonGo-Bot#2410]
### Expected Behavior
for the app to run in the background without crashing

### Actual Behavior
sometimes when i leave it alone for a while, or when i try to start it up, it gives me this error
```
Traceback (most recent call last):
  File "./pokecli.py", line 220, in <module>
    main()
  File "./pokecli.py", line 206, in main
    bot.start()
  File "/home/kinesivan/Documents/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/home/kinesivan/Documents/PokemonGo-Bot/pokemongo_bot/__init__.py", line 151, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'player_data'
```

### Steps to Reproduce
i followed the installation tutorial

### Other Information
OS: Raspberry Pi 32bit ARM
Git Commit: 4182e93f9bfbe471d07b74e95c55cdfbacda127b
Python Version:2.7

**Comment by Yanush7** [comment]
Same here
