### ISSUE TITLE
"RequirementParseError" On doing pip upgrade

### ISSUE THREAD

**Issue by db-coder** [PokemonGoF/PokemonGo-Bot#2413]
### Error
------------------------------------------------------------
/usr/bin/pip run on Wed Aug  3 04:36:30 2016
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    InstallRequirement.from_line(name, None))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 173, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 71, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/home/dibyendu/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2863, in parse
    req, = parse_requirements(s)
  File "/home/dibyendu/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2811, in parse_requirements
    yield Requirement(line)
  File "/home/dibyendu/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2820, in __init__
    raise RequirementParseError(str(e))
RequirementParseError: Invalid requirement, parse error at "'\xe2\x80\x94upgra'"

### Steps to Reproduce
pip install —upgrade -r requirements.txt

### Other Information
OS: Ubuntu 15.04
Git Commit: bdf2e7d9cc0b2fa5fb04bb9dc4f9f09f967cd9ea
Python Version: Python 2.7.9

**Comment by JSchwerberg** [comment]
Try to run `dos2unix` on your file.  This looks like a formatting error, tbqh.
