### ISSUE TITLE
EvolveAll Issue

### ISSUE THREAD

**Issue by OVO647** [PokemonGoF/PokemonGo-Bot#2425]
Traceback (most recent call last):
  File "pokecli.py", line 446, in <module>
    main()
  File "pokecli.py", line 64, in main
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "/Users/User/Desktop/POGO/pokemongo_bot/tree_config_builder.py", line 27, in build
    raise ConfigException('The EvolveAll task has been renamed to EvolvePokemon')
pokemongo_bot.tree_config_builder.ConfigException: The EvolveAll task has been renamed to EvolvePokemon

**Comment by Marco208** [comment]
Like it said "The EvolveAll task has been renamed to EvolvePokemon"

**Comment by leadboots5** [comment]
What marco said, update your config.
