### ISSUE TITLE
[DEV] NoPlayerPositionSetException on start after latest dev pull

### ISSUE THREAD

**Issue by ChrisHaPunkt** [PokemonGoF/PokemonGo-Bot#2447]
### Expected Behavior

Application start

### Actual Behavior

> Traceback (most recent call last):
  File "pokecli.py", line 446, in <module>
    main()
  File "pokecli.py", line 88, in main
    report_summary(bot)
  File "pokecli.py", line 96, in report_summary
    metrics.capture_stats()
  File "/opt/PokemonGo-Bot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/opt/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 90, in call
    if not self.can_call():
  File "/opt/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 54, in can_call
    raise NoPlayerPositionSetException()
pgoapi.exceptions.NoPlayerPositionSetException

### Steps to Reproduce

`python pokecli.py --config `

### Other Information
OS:  Debian 8
Git Commit: 361c0fa11783085ea201a71a99f6c43859e8c239
Python Version: Python 2.7.9

**Comment by Jarrrk** [comment]
Also getting this exact error.

## Other Information
OS: Ubuntu 16.04.01 LTS

**Comment by ChrisHaPunkt** [comment]
Fixed my error, i set "test" to true, that seem to raise the error in my case. Reverting to "false" and the app started again.

**Comment by Jarrrk** [comment]
@ChrisHaPunkt That doesn't seem to work for me.

**Comment by Baanin** [comment]
Same here 
/b/PokemonGo-Bot# python pokecli.py --config ./configs/config.json
[11:22:52]  PokemonGO Bot v1.0 
[11:22:53]  Configuration initialized 
[11:22:53] Attempting login to Pokemon Go.
Traceback (most recent call last):
  File "pokecli.py", line 446, in <module>
    main()
  File "pokecli.py", line 88, in main
    report_summary(bot)
  File "pokecli.py", line 96, in report_summary
    metrics.capture_stats()
  File "/root/bot/PokemonGo-Bot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/root/bot/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 90, in call
    if not self.can_call():
  File "/root/bot/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 54, in can_call
    raise NoPlayerPositionSetException()
pgoapi.exceptions.NoPlayerPositionSetException

**Comment by TabDambrine** [comment]
Had this too.
I ran
`pip2 install -r requirements.txt`
It loaded some files related to pgoapi and then the application starts again correctly.

**Comment by DayBr3ak** [comment]
yes re run pip after every pull ty

**Comment by Baanin** [comment]
Got the same problem even after pip install -r requirements

**Comment by boltegg** [comment]
have same problem, ubuntu 16.04

**Comment by oliverhitz** [comment]
Got the same error, fixed it by putting location as numbers (47.12312, 11.12332 e.g.) Hope this helps.

**Comment by Baanin** [comment]
OH.... Found the mistake for me, misstyped the google API Key :'(


SORRY

**Comment by ZgrK** [comment]
i still have same problem i try everything new api key pip install but not working :( 


Traceback (most recent call last):
  File "pokecli.py", line 486, in <module>
    main()
  File "pokecli.py", line 121, in main
    report_summary(bot)
  File "pokecli.py", line 129, in report_summary
    metrics.capture_stats()
  File "/var/www/PokemonGo-Bot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/var/www/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 91, in call
    if not self.can_call():
  File "/var/www/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 55, in can_call
    raise NoPlayerPositionSetException()
pgoapi.exceptions.NoPlayerPositionSetException
