### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by IcicleTF** [PokemonGoF/PokemonGo-Bot#2464]
### Expected Behavior
Bot starts and runs.

### Actual Behavior
Traceback (most recent call last):
  File "D:\Github\PokemonGo-Bot\pokecli.py", line 446, in <module>
    main()
  File "D:\Github\PokemonGo-Bot\pokecli.py", line 71, in main
    bot.tick()
  File "D:\Github\PokemonGo-Bot\pokemongo_bot\__init__.py", line 92, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "D:\Github\PokemonGo-Bot\pokemongo_bot\cell_workers\catch_visible_pokemon.py", line 24, in work
    return self.catch_pokemon(self.bot.cell['catchable_pokemons'].pop(0))
  File "D:\Github\PokemonGo-Bot\pokemongo_bot\cell_workers\catch_visible_pokemon.py", line 36, in catch_pokemon
    return_value = worker.work()
  File "D:\Github\PokemonGo-Bot\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 71, in work
    if not self.should_capture_pokemon(pokemon_name, cp, pokemon_potential, response_dict):
  File "D:\Github\PokemonGo-Bot\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 321, in should_capture_pokemon
    cp_iv_logic = catch_config.get('logic')
AttributeError: 'NoneType' object has no attribute 'get'

### Steps to Reproduce
Start the pokecli.py; it will automatically create this error within the first few seconds of the latest dev branch.

### Other Information
OS: Windows 10
Git Commit: 361c0fa11783085ea201a71a99f6c43859e8c239
Python Version: 2.7.12

**Comment by Nepoxx** [comment]
I'm having the same issue, how did you resolve it?

**Comment by Nepoxx** [comment]
Also closed without comment: https://github.com/PokemonGoF/PokemonGo-Bot/issues/2146
