### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by Nepoxx** [PokemonGoF/PokemonGo-Bot#2490]
Latest dev version (`2f91fd0410eeda430aeb9cb956885eda8bf04e22`), when trying to catch a pokemon I get:

```
[11:03:54]  Starting PokemonGo Bot.... 
[11:03:54] Something rustles nearby!
[11:03:54]  A Wild Voltorb appeared! [CP 177] [Potential 0.71] 
[11:03:54] IV [Attack/Defense/Stamina] = [14/10/8]
[11:03:57] 
[11:03:57]  Ran for 0:00:11 
[11:03:57]  Total XP Earned: 0  Average: 0.00/h 
[11:03:57]  Travelled 0.00km 
[11:03:57]  Visited 0 stops 
[11:03:57]  Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before 
[11:03:57]  Threw 0 pokeballs 
[11:03:57]  Earned 0 Stardust 
[11:03:57] 
[11:03:57]  Highest CP Pokemon:  
[11:03:57]  Most Perfect Pokemon:  
Traceback (most recent call last):
  File "pokecli.py", line 446, in <module>
    main()
  File "pokecli.py", line 71, in main
    bot.tick()
  File "/home/nepoxx/dump/PokemonGo-Bot/pokemongo_bot/__init__.py", line 92, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/nepoxx/dump/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 24, in work
    return self.catch_pokemon(self.bot.cell['catchable_pokemons'].pop(0))
  File "/home/nepoxx/dump/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 36, in catch_pokemon
    return_value = worker.work()
  File "/home/nepoxx/dump/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 71, in work
    if not self.should_capture_pokemon(pokemon_name, cp, pokemon_potential, response_dict):
  File "/home/nepoxx/dump/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 321, in should_capture_pokemon
    cp_iv_logic = catch_config.get('logic')
AttributeError: 'NoneType' object has no attribute 'get'
```

I've seen a few issues on here as well but there's no information on the resolution: https://github.com/PokemonGoF/PokemonGo-Bot/issues/2464 https://github.com/PokemonGoF/PokemonGo-Bot/issues/2146 https://github.com/PokemonGoF/PokemonGo-Bot/issues/1994 https://github.com/PokemonGoF/PokemonGo-Bot/issues/1399

I tried capturing a pokemon the "old fashioned way" with my phone/legit app and it worked, so I don't this is a server issue.

**Comment by IcicleTF** [comment]
The way I ended up fixing it was by copy and pasting most of the "release" section in the config.json over top my own after playing with some of the values, and that seemed to fix it.
When it doubt, just git pull and redo your config from scratch.

**Comment by Nepoxx** [comment]
I can't figure out what was wrong with my config/repo, but that did the trick. Much appreciated!
