### ISSUE TITLE
NameError: global name 'id_list1' is not defined

### ISSUE THREAD

**Issue by michi0987** [PokemonGoF/PokemonGo-Bot#251]
### Expected Behavior

to work
### Actual Behavior

stops working and get error: 
```
Traceback (most recent call last):
  File "C:\poke\test\pokecli.py", line 107, in <module>
    main()
  File "C:\poke\test\pokecli.py", line 104, in main
    bot.take_step()
  File "C:\poke\test\pokemongo_bot\__init__.py", line 31, in take_step
    self.stepper.take_step()
  File "C:\poke\test\pokemongo_bot\stepper.py", line 58, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "C:\poke\test\pokemongo_bot\stepper.py", line 100, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "C:\poke\test\pokemongo_bot\__init__.py", line 52, in work_on_cell
    hack_chain = worker.work()
  File "C:\poke\test\pokemongo_bot\cell_workers\seen_fort_worker.py", line 35, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "C:\poke\test\pokemongo_bot\stepper.py", line 79, in _walk_to
    self._work_at_position(i2f(self.api._position_lat), i2f(self.api._position_lng), alt, False)
  File "C:\poke\test\pokemongo_bot\stepper.py", line 100, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "C:\poke\test\pokemongo_bot\__init__.py", line 38, in work_on_cell
    worker.work()
  File "C:\poke\test\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 86, in work
    self.transfer_pokemon(list(Set(id_list2) - Set(id_list1)))
NameError: global name 'id_list1' is not defined
```

### Steps to Reproduce
run program
gett error

### Other Information
OS:  windows 10
Git Commit: adf718f

**Comment by douglascamata** [comment]
Working on it.

**Comment by rkodali22** [comment]
Pull #254 fixes this

**Comment by zgelici** [comment]
I tested it, and its works

**Comment by wcrwcr** [comment]
got same error, global name 'id_list1' is not defined

**Comment by Skeyelab** [comment]
im still getting this error

**Comment by wcrwcr** [comment]
it's not merged yet )

**Comment by douglascamata** [comment]
Fixed in dev already.
