### ISSUE TITLE
Runs for 8 seconds

### ISSUE THREAD

**Issue by Bilters** [PokemonGoF/PokemonGo-Bot#2519]
### Actual Behavior
Starting PokemonGo Bot....

```
[x] Next egg incubates in 0.34 km

No lucky eggs... skipping evolve!

Ran for 0:00:08

Total XP Earned: 0 Average: 0.00/h

Travelled 0.00km

Visited 0 stops

Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before

Threw 0 pokeballs

Earned 0 Stardust

Highest CP Pokemon:

Most Perfect Pokemon:

Traceback (most recent call last):

File "./pokecli.py", line 494, in

main()

File "./pokecli.py", line 70, in main

bot.tick()

File "/Users/bilters/Desktop/POKEMON/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/__init__.py", line 85, in tick

if worker.work() == WorkerResult.RUNNING:

File "/Users/bilters/Desktop/POKEMON/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/cell_workers/follow_spiral.py", line 83, in work

TypeError

:

set_position() takes exactly 4 arguments (3 given)
```

### When did it happen?
This happened as soon as i pulled in the latest state. (just did 5 minutes ago)

**Comment by Bilters** [comment]
After several times retrying it worked for a couple seconds longer; now it did hit 33 seconds; here's the log.

```
PokeStop on cooldown. Time left: 4 minutes, 59 seconds

Ran for 0:00:33

Total XP Earned: 160 Average: 17251.15/h

Travelled 0.00km

Visited 1 stops

Encountered 1 pokemon, 1 caught, 0 released, 0 evolved, 0 never seen before

Threw 3 pokeballs

Earned 100 Stardust

Highest CP Pokemon: Poliwag [CP: 72] [IV: 13/7/3] Potential: 0.51

Most Perfect Pokemon: Poliwag [CP: 72] [IV: 13/7/3] Potential: 0.51

Traceback (most recent call last):

File "./pokecli.py", line 494, in

main()

File "./pokecli.py", line 70, in main

bot.tick()

File "/Users/sandernijssen/Desktop/POKEMON/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/__init__.py", line 85, in tick

if worker.work() == WorkerResult.RUNNING:

File "/Users/sandernijssen/Desktop/POKEMON/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/cell_workers/move_to_fort.py", line 44, in work

lng

File "/Users/sandernijssen/Desktop/POKEMON/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/step_walker.py", line 28, in __init__

self.steps = (self.dist + 0.0) / (speed + 0.0)

TypeError

:
```

**Comment by Happyrain67** [comment]
Hi.
what is your config file ?
You have a error whit walker... Your bot not same to walk.
(sorry for my bad english)

**Comment by Bilters** [comment]
I'm sorry @Happyrain67 this was meant for the Desktop app; I was browsing this repository for getting more info and ended up posting this here. I'm sorry my mistake. Did get the error a couple more time though. But suddenly it started working again. Don't know the reason behind it at all.
