### ISSUE TITLE
Crash after bot restart - Inventory Delta (Dev)

### ISSUE THREAD

**Issue by alb3rto** [PokemonGoF/PokemonGo-Bot#2523]
### Expected Behavior
Run the bot

### Actual Behavior
`File "pokecli.py", line 446, in <module>
    main()
  File "pokecli.py", line 71, in main
    bot.tick()
  File "/home/alb3rto/PokemonGo-Bot/pokemongo_bot/__init__.py", line 92, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/alb3rto/PokemonGo-Bot/pokemongo_bot/cell_workers/spin_fort.py", line 72, in work
    " (Total: " + str(self.bot.item_inventory_count(item_id)) + ")", 'yellow'
  File "/home/alb3rto/PokemonGo-Bot/pokemongo_bot/__init__.py", line 421, in item_inventory_count
    'GET_INVENTORY']['inventory_delta']['inventory_items']
KeyError: 'inventory_delta'`

### Steps to Reproduce
Start bot

### Other Information
OS: ArchLinux
Git Commit: 2f91fd0410eeda430aeb9cb956885eda8bf04e22
Python Version: Python 2.7.12

Inventory is not full (248/350)

**Comment by BartKoppelmans** [comment]
Having the same problem. Also have the following log (separate from the bug above):

```
Traceback (most recent call last):
  File "pokecli.py", line 446, in <module>
    main()
  File "pokecli.py", line 63, in main
    bot.start()
  File "C:\Users\s155643\Desktop\Pokemon Go\PokemonGo-Bot\pokemongo_bot\__init__.py", line 61, in start
    self._setup_api()
  File "C:\Users\s155643\Desktop\Pokemon Go\PokemonGo-Bot\pokemongo_bot\__init__.py", line 285, in _setup_api
    self._print_character_info()
  File "C:\Users\s155643\Desktop\Pokemon Go\PokemonGo-Bot\pokemongo_bot\__init__.py", line 301, in _print_character_info
    self._player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'player_data'
```

**Comment by outofink** [comment]
Similar issue, slightly different traceback:

```
Traceback (most recent call last):
  File "pokecli.py", line 446, in <module>
    main()
  File "pokecli.py", line 71, in main
    bot.tick()
  File "/home/nope/PokemonGo-Bot/pokemongo_bot/__init__.py", line 92, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/nope/PokemonGo-Bot/pokemongo_bot/cell_workers/recycle_items.py", line 21, in work
    item_count_dict = self.bot.item_inventory_count('all')
  File "/home/nope/PokemonGo-Bot/pokemongo_bot/__init__.py", line 421, in item_inventory_count
    'GET_INVENTORY']['inventory_delta']['inventory_items']
KeyError: 'inventory_delta'
```

**Comment by Baconnaise** [comment]
Same issue.
`Traceback (most recent call last):
  File "C:\pokebot1\pokecli.py", line 446, in <module>
    main()
  File "C:\pokebot1\pokecli.py", line 71, in main
    bot.tick()
  File "C:\pokebot1\pokemongo_bot\__init__.py", line 92, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "C:\pokebot1\pokemongo_bot\cell_workers\recycle_items.py", line 21, in wo
rk
    item_count_dict = self.bot.item_inventory_count('all')
  File "C:\pokebot1\pokemongo_bot\__init__.py", line 421, in item_inventory_coun
t
    'GET_INVENTORY']['inventory_delta']['inventory_items']
KeyError: 'inventory_delta'`

**Comment by staffanselander** [comment]
That's it then. Time to go outside and play....
Kidding, ill just start my Nintendo DS and play Pokémon Gold.

Getting 
`KeyError: 'GET_INVENTORY'`

**Comment by NikolayBlokhin** [comment]
I fixed this by it: https://github.com/PokemonGoF/PokemonGo-Bot/issues/2525
