### ISSUE TITLE
"AttributeError" when launching the bot.

### ISSUE THREAD

**Issue by mattleon** [PokemonGoF/PokemonGo-Bot#2545]
Hello,

I'm actually trying to launch the bot, but when i try, i got this message : 

> [2016-08-03 22:35:04] [x] PokemonGO Bot v1.0
[2016-08-03 22:35:04] [x] Configuration initialized
[2016-08-03 22:35:04] [x] Coordinates found in passed in location, not geocoding.
[2016-08-03 22:35:04] 
[2016-08-03 22:35:04] [x] Address found: 48.893494, 2.390154
[2016-08-03 22:35:04] [x] Position in-game set as: (48.893494, 2.390154, 0.0)
[2016-08-03 22:35:04] 
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "/home/matthieu/Documents/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/home/matthieu/Documents/PokemonGo-Bot/pokemongo_bot/__init__.py", line 146, in _setup_api
    response_dict = self.api.call()
  File "/usr/local/lib/python2.7/dist-packages/pgoapi/pgoapi.py", line 89, in __getattr__
    raise AttributeError
AttributeError

Where does this error come from ? Any ideas ?

Thank you !

**Comment by brantje** [comment]
Yea, it means that Niantic is bugging us. They changed the api. So hold on while we debug.
