### ISSUE TITLE
ImportError: No module named pgoapi.exceptions

### ISSUE THREAD

**Issue by havenofear** [PokemonGoF/PokemonGo-Bot#2558]
Can't start bot with error:
Traceback (most recent call last):
  File "./pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions

**Comment by abusalman** [comment]
try
`pip install -r requirements.txt`

**Comment by havenofear** [comment]
Already tried. instal, upgrade and so on..

**Comment by mfkenson** [comment]
virtualenv .

**Comment by havenofear** [comment]
D:\bot\dev\PokemonGo-Bot>virtualenv .
Traceback (most recent call last):
  File "c:\program files (x86)\python\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\program files (x86)\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Program Files (x86)\Python\Scripts\virtualenv.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python\lib\site-packages\virtualenv.py", line 711, in main
    symlink=options.symlink)
  File "c:\program files (x86)\python\lib\site-packages\virtualenv.py", line 924, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "c:\program files (x86)\python\lib\site-packages\virtualenv.py", line 1136, in install_python
    copy_tcltk(prefix, home_dir, symlink)
  File "c:\program files (x86)\python\lib\site-packages\virtualenv.py", line 1077, in copy_tcltk
    copyfileordir(srcdir, dstdir, symlink)
  File "c:\program files (x86)\python\lib\site-packages\virtualenv.py", line 327, in copyfileordir
    shutil.copytree(src, dest, symlink)
  File "c:\program files (x86)\python\lib\shutil.py", line 177, in copytree
    os.makedirs(dst)
  File "c:\program files (x86)\python\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 183] ═хтючьюцэю ёючфрЄ№ Їрщы,: 'D:\\bot\\dev\\PokemonGo-Bot/tcl/tcl8.5'
