### ISSUE TITLE
won't catch and get an error

### ISSUE THREAD

**Issue by blackdog1987** [PokemonGoF/PokemonGo-Bot#2563]
the latest dev branch won't catch now. It just walked, then throw an error log.

I just cp the config.json.example and set the account information so maybe the config.json is right.

Error log:    
    
2016-08-04 12:06:26,379 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-04 12:06:26,380 [       cli] [INFO] No config argument specified, checking for /configs/config.json
2016-08-04 12:06:26,382 [       cli] [INFO] Configuration initialized
2016-08-04 12:06:26,384 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-04 12:06:26,385 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-04 12:06:26,385 [PokemonGoBot] [INFO] [location_found] Location found: 37.782699,-122.511398 (37.782699, -122.511398, 0.0)
2016-08-04 12:06:26,385 [PokemonGoBot] [INFO] [position_update] Now at (37.782699, -122.511398, 0)
2016-08-04 12:06:26,385 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-04 12:06:29,103 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-04 12:06:30,714 [PokemonGoBot] [INFO] 
2016-08-04 12:06:30,714 [PokemonGoBot] [INFO] --- B1ackD0gCha0 ---
2016-08-04 12:06:30,714 [PokemonGoBot] [INFO] Level: 26 (Next Level: 123511 XP) (Total: 976489 XP)
2016-08-04 12:06:30,715 [PokemonGoBot] [INFO] Pokemon Captured: 2759 | Pokestops Visited: 2787
2016-08-04 12:06:30,715 [PokemonGoBot] [INFO] Pokemon Bag: 132/250
2016-08-04 12:06:30,715 [PokemonGoBot] [INFO] Items: 336/550
2016-08-04 12:06:30,716 [PokemonGoBot] [INFO] Stardust: 190633 | Pokecoins: 300
2016-08-04 12:06:30,716 [PokemonGoBot] [INFO] PokeBalls: 23 | GreatBalls: 23 | UltraBalls: 122
2016-08-04 12:06:30,716 [PokemonGoBot] [INFO] RazzBerries: 50 | BlukBerries: 0 | NanabBerries: 0
2016-08-04 12:06:30,716 [PokemonGoBot] [INFO] LuckyEgg: 13 | Incubator: 0 | TroyDisk: 6
2016-08-04 12:06:30,716 [PokemonGoBot] [INFO] Potion: 10 | SuperPotion: 10 | HyperPotion: 10
2016-08-04 12:06:30,716 [PokemonGoBot] [INFO] Incense: 5 | IncenseSpicy: 0 | IncenseCool: 0
2016-08-04 12:06:30,716 [PokemonGoBot] [INFO] Revive: 10 | MaxRevive: 0
2016-08-04 12:06:30,716 [PokemonGoBot] [INFO] 
2016-08-04 12:06:30,716 [PokemonGoBot] [INFO] 
2016-08-04 12:06:31,800 [PokemonGoBot] [INFO] [bot_start] Starting bot...
2016-08-04 12:06:32,737 [CollectLevelUpReward] [INFO] [level_up_reward] Received level up reward: []
2016-08-04 12:06:32,737 [IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 1.71 km
2016-08-04 12:06:33,864 [FollowSpiral] [INFO] [position_update] Walking from (37.77993684412415, -122.5082838663158, 0) to (37.77993684412415, -122.5082838663158, 0) (0.0 m)
2016-08-04 12:06:35,236 [FollowSpiral] [INFO] [position_update] Walking from (37.77993684412415, -122.5082838663158, 0) to (37.78056732051195, -122.5082838663158, 0) (70.1057805474 m)
2016-08-04 12:07:18,911 [FollowSpiral] [INFO] [position_update] Walking from (37.78056732051195, -122.5082838663158, 0) to (37.78056732051195, -122.50746873818179, 0) (71.6369906662 m)
2016-08-04 12:08:05,875 [FollowSpiral] [INFO] [position_update] Walking from (37.78056732051195, -122.50746873818179, 0) to (37.77993684412415, -122.50746873818179, 0) (70.1057805474 m)
2016-08-04 12:08:54,071 [FollowSpiral] [INFO] [position_update] Walking from (37.77993684412415, -122.50746873818179, 0) to (37.77930636773635, -122.50746873818179, 0) (70.1057805474 m)
2016-08-04 12:09:35,260 [FollowSpiral] [INFO] [position_update] Walking from (37.77930636773635, -122.50746873818179, 0) to (37.77930636773635, -122.5082838663158, 0) (71.6382127064 m)
2016-08-04 12:10:23,941 [FollowSpiral] [INFO] [position_update] Walking from (37.77930636773635, -122.5082838663158, 0) to (37.77930636773635, -122.5090989944498, 0) (71.6382127064 m)
2016-08-04 12:11:13,681 [FollowSpiral] [INFO] [position_update] Walking from (37.77930636773635, -122.5090989944498, 0) to (37.77993684412415, -122.5090989944498, 0) (70.1057805474 m)
2016-08-04 12:11:55,426 [FollowSpiral] [INFO] [position_update] Walking from (37.77993684412415, -122.5090989944498, 0) to (37.78056732051195, -122.5090989944498, 0) (70.1057805474 m)
2016-08-04 12:12:41,150 [FollowSpiral] [INFO] [position_update] Walking from (37.78056732051195, -122.5090989944498, 0) to (37.781197796899754, -122.5090989944498, 0) (70.1057805474 m)
2016-08-04 12:13:24,326 [FollowSpiral] [INFO] [position_update] Walking from (37.781197796899754, -122.5090989944498, 0) to (37.781197796899754, -122.5082838663158, 0) (71.636379633 m)
2016-08-04 12:14:11,219 [FollowSpiral] [INFO] [position_update] Walking from (37.781197796899754, -122.5082838663158, 0) to (37.781197796899754, -122.50746873818179, 0) (71.636379633 m)
2016-08-04 12:14:59,024 [FollowSpiral] [INFO] [position_update] Walking from (37.781197796899754, -122.50746873818179, 0) to (37.781197796899754, -122.50665361004778, 0) (71.636379633 m)
2016-08-04 12:15:44,939 [FollowSpiral] [INFO] [position_update] Walking from (37.781197796899754, -122.50665361004778, 0) to (37.78056732051195, -122.50665361004778, 0) (70.1057805474 m)
2016-08-04 12:16:37,800 [FollowSpiral] [INFO] [position_update] Walking from (37.78056732051195, -122.50665361004778, 0) to (37.77993684412415, -122.50665361004778, 0) (70.1057805474 m)
2016-08-04 12:17:47,304 [FollowSpiral] [INFO] [position_update] Walking from (37.77993684412415, -122.50665361004778, 0) to (37.77930636773635, -122.50665361004778, 0) (70.1057805474 m)
2016-08-04 12:18:45,119 [FollowSpiral] [INFO] [position_update] Walking from (37.77930636773635, -122.50665361004778, 0) to (37.77867589134855, -122.50665361004778, 0) (70.1057805474 m)
2016-08-04 12:19:52,730 [FollowSpiral] [INFO] [position_update] Walking from (37.77867589134855, -122.50665361004778, 0) to (37.77867589134855, -122.50746873818179, 0) (71.6388237135 m)
2016-08-04 12:21:02,002 [FollowSpiral] [INFO] [position_update] Walking from (37.77867589134855, -122.50746873818179, 0) to (37.77867589134855, -122.5082838663158, 0) (71.6388237135 m)
2016-08-04 12:21:52,876 [FollowSpiral] [INFO] [position_update] Walking from (37.77867589134855, -122.5082838663158, 0) to (37.77867589134855, -122.5090989944498, 0) (71.6388237135 m)
2016-08-04 12:22:37,464 [FollowSpiral] [INFO] [position_update] Walking from (37.77867589134855, -122.5090989944498, 0) to (37.77867589134855, -122.50991412258381, 0) (71.6388237135 m)
2016-08-04 12:23:24,158 [FollowSpiral] [INFO] [position_update] Walking from (37.77867589134855, -122.50991412258381, 0) to (37.77930636773635, -122.50991412258381, 0) (70.1057805474 m)
2016-08-04 12:24:12,935 [FollowSpiral] [INFO] [position_update] Walking from (37.77930636773635, -122.50991412258381, 0) to (37.77993684412415, -122.50991412258381, 0) (70.1057805474 m)
2016-08-04 12:24:57,458 [FollowSpiral] [INFO] [position_update] Walking from (37.77993684412415, -122.50991412258381, 0) to (37.78056732051195, -122.50991412258381, 0) (70.1057805474 m)
2016-08-04 12:25:47,216 [FollowSpiral] [INFO] [position_update] Walking from (37.78056732051195, -122.50991412258381, 0) to (37.781197796899754, -122.50991412258381, 0) (70.1057805474 m)
2016-08-04 12:26:34,377 [FollowSpiral] [INFO] [position_update] Walking from (37.781197796899754, -122.50991412258381, 0) to (37.78056732051195, -122.50991412258381, 0) (70.1057805474 m)
2016-08-04 12:27:13,556 [FollowSpiral] [INFO] [position_update] Walking from (37.78056732051195, -122.50991412258381, 0) to (37.77993684412415, -122.50991412258381, 0) (70.1057805474 m)
2016-08-04 12:27:56,099 [FollowSpiral] [INFO] [position_update] Walking from (37.77993684412415, -122.50991412258381, 0) to (37.77930636773635, -122.50991412258381, 0) (70.1057805474 m)
2016-08-04 12:28:36,410 [FollowSpiral] [INFO] [position_update] Walking from (37.77930636773635, -122.50991412258381, 0) to (37.77867589134855, -122.50991412258381, 0) (70.1057805474 m)
2016-08-04 12:29:29,135 [FollowSpiral] [INFO] [position_update] Walking from (37.77867589134855, -122.50991412258381, 0) to (37.77867589134855, -122.5090989944498, 0) (71.6388237135 m)
2016-08-04 12:30:17,193 [FollowSpiral] [INFO] [position_update] Walking from (37.77867589134855, -122.5090989944498, 0) to (37.77867589134855, -122.5082838663158, 0) (71.6388237135 m)
2016-08-04 12:31:01,499 [FollowSpiral] [INFO] [position_update] Walking from (37.77867589134855, -122.5082838663158, 0) to (37.77867589134855, -122.50746873818179, 0) (71.6388237135 m)
2016-08-04 12:31:51,278 [FollowSpiral] [INFO] [position_update] Walking from (37.77867589134855, -122.50746873818179, 0) to (37.77867589134855, -122.50665361004778, 0) (71.6388237135 m)
2016-08-04 12:32:54,018 [FollowSpiral] [INFO] [position_update] Walking from (37.77867589134855, -122.50665361004778, 0) to (37.77930636773635, -122.50665361004778, 0) (70.1057805474 m)
2016-08-04 12:34:15,835 [FollowSpiral] [INFO] [position_update] Walking from (37.77930636773635, -122.50665361004778, 0) to (37.77993684412415, -122.50665361004778, 0) (70.1057805474 m)
2016-08-04 12:35:04,548 [FollowSpiral] [INFO] [position_update] Walking from (37.77993684412415, -122.50665361004778, 0) to (37.78056732051195, -122.50665361004778, 0) (70.1057805474 m)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file __init__.py, line 547
2016-08-04 12:35:30,278 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-04 12:35:32,828 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-04 12:36:05,541 [FollowSpiral] [INFO] [position_update] Walking from (37.78056732051195, -122.50665361004778, 0) to (37.781197796899754, -122.50665361004778, 0) (70.1057805474 m)
2016-08-04 12:37:21,417 [FollowSpiral] [INFO] [position_update] Walking from (37.781197796899754, -122.50665361004778, 0) to (37.781197796899754, -122.50746873818179, 0) (71.636379633 m)
2016-08-04 12:38:25,264 [FollowSpiral] [INFO] [position_update] Walking from (37.781197796899754, -122.50746873818179, 0) to (37.781197796899754, -122.5082838663158, 0) (71.636379633 m)
2016-08-04 12:39:15,419 [FollowSpiral] [INFO] [position_update] Walking from (37.781197796899754, -122.5082838663158, 0) to (37.781197796899754, -122.5090989944498, 0) (71.636379633 m)
2016-08-04 12:40:07,146 [FollowSpiral] [INFO] [position_update] Walking from (37.781197796899754, -122.5090989944498, 0) to (37.78056732051195, -122.5090989944498, 0) (70.1057805474 m)

**Comment by liamqma** [comment]
That's because Niantic Server responses changed. 

[Check this thread](https://github.com/AeonLucid/POGOProtos/issues/131)

**Comment by gungoan** [comment]
PokemonGO update new version.

**Comment by iruy** [comment]
Take a look at previous issues before opening new issue https://github.com/PokemonGoF/PokemonGo-Bot/issues/2540
