### ISSUE TITLE
Crash after catching pokémon

### ISSUE THREAD

**Issue by 2spook5me** [PokemonGoF/PokemonGo-Bot#257]
### Expected Behavior
Catching and moving on.

### Actual Behavior
Catching and crashing.

### Steps to Reproduce
Just updated to the latest version, let it run for about 10 sec, when it finds a pokémon and it catches it, it returns this message:

`[#] Something rustles nearby!
[#] A Wild Caterpie appeared! [CP 81]
[x] Using Pokeball...
[x] Captured Caterpie! [CP 81] - exchanging for candy
Traceback (most recent call last):
  File "pokecli.py", line 107, in <module>
    main()
  File "pokecli.py", line 104, in main
    bot.take_step()
  File "C:\Users\?\Desktop\pogobotdev\pokemongo_bot\__init__.py", line 31, i
n take_step
    self.stepper.take_step()
  File "C:\Users\?\Desktop\pogobotdev\pokemongo_bot\stepper.py", line 58, in
 take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "C:\Users\?\Desktop\pogobotdev\pokemongo_bot\stepper.py", line 100, i
n _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "C:\Users\?\Desktop\pogobotdev\pokemongo_bot\__init__.py", line 52, i
n work_on_cell
    hack_chain = worker.work()
  File "C:\Users\?\Desktop\pogobotdev\pokemongo_bot\cell_workers\seen_fort_w
orker.py", line 35, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "C:\Users\?\Desktop\pogobotdev\pokemongo_bot\stepper.py", line 79, in
 _walk_to
    self._work_at_position(i2f(self.api._position_lat), i2f(self.api._position_l
ng), alt, False)
  File "C:\Users\?\Desktop\pogobotdev\pokemongo_bot\stepper.py", line 100, i
n _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "C:\Users\?\Desktop\pogobotdev\pokemongo_bot\__init__.py", line 38, i
n work_on_cell
    worker.work()
  File "C:\Users\?\Desktop\pogobotdev\pokemongo_bot\cell_workers\pokemon_cat
ch_worker.py", line 86, in work
    self.transfer_pokemon(list(Set(id_list2) - Set(id_list1)))
NameError: global name 'id_list1' is not defined
`

### Other Information
OS: Windows 7 64bit
Git Commit: ?

**Comment by zgelici** [comment]
same error here, last changes

**Comment by rkodali22** [comment]
Duplicate of #251

**Comment by 2spook5me** [comment]
Hm aight.
