### ISSUE TITLE
Starting bot error

### ISSUE THREAD

**Issue by ulovehash** [PokemonGoF/PokemonGo-Bot#2579]
### Expected Behavior

Login to Pokemon Go successful. 
Starting PokemonGo Bot

### Actual Behavior
After "Starting PokemonGo Bot" message:

Traceback (most recent call last):
  File "pokecli.py", line 494, in <module>
    main()
  File "pokecli.py", line 70, in main
    bot.tick()
  File "/Users/user/Desktop/bot/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/__init__.py", line 85, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/Users/user/Desktop/bot/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/cell_workers/follow_spiral.py", line 83, in work
    self.bot.api.set_position(point['lat'], point['lng'])
TypeError: set_position() takes exactly 4 arguments (3 given)

### Other Information
OS: X El Capitan
Git Commit: 
Python Version: Python 2.7.12

**Comment by Dunduro** [comment]
#2540 check thisout

**Comment by brantje** [comment]
Read: https://github.com/PokemonGoF/PokemonGo-Bot/issues/2540
