### ISSUE TITLE
Can't open python pokecly.py. PLS HELP T_T

### ISSUE THREAD

**Issue by pensabon** [PokemonGoF/PokemonGo-Bot#2622]
### Expected Behavior
Done installing all the necessary steps and tools to get the python pokecli.py work

### Actual Behavior
(PokemonGo-Bot)pen@pen-HP-15-Notebook-PC ~/PokemonGo-Bot $ python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 197, in main
    config = init_config()
  File "pokecli.py", line 64, in init_config
    load.update(json.load(data))
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 357 column 2 (char 18253)

### Other Information
OS: Linux Mint 17.3
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: 2.7.6 (run 'python -V' and paste it here)

**Comment by brantje** [comment]
Read the READMe ;)
