### ISSUE TITLE
TypeError: __init__() takes exactly 6 arguments (5 given)

### ISSUE THREAD

**Issue by sia84** [PokemonGoF/PokemonGo-Bot#2649]
Getting the following error:

Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "C:\Users\Me\Downloads\PokemonGo-Bot-master\pokemongo_bot\metrics.py", line 73, in capture_stats
    request = self.bot.api.create_request()
  File "C:\Users\Me\Downloads\PokemonGo-Bot-master\pokemongo_bot\api_wrapper.py", line 27, in create_request
    self._position_alt
  File "C:\Users\Me\Downloads\PokemonGo-Bot-master\pokemongo_bot\api_wrapper.py", line 43, in __init__
    PGoApiRequest.__init__(self, *args)
TypeError: __init__() takes exactly 6 arguments (5 given)
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-Break to quit

Is this because I have the wrong encrypt.dll ? 

Thanks

**Comment by sia84** [comment]
Closing this since someone already opened a thread about this while I was typing it!
