### ISSUE TITLE
PTC account failed

### ISSUE THREAD

**Issue by zonghuiyouren** [PokemonGoF/PokemonGo-Bot#2650]
Hi I just tried this bot. It is awesome. BUT I meet a problem. 
My google accounts are all good with this script. However my ptc account can log in and then failed. I can not figure out why. Can anyone help me or anyone meet the same problem?

###The Print LOG is shown as belows:

2016-08-07 14:14:49,647 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 14:14:49,648 [       cli] [INFO] Configuration initialized
2016-08-07 14:14:49,648 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more logrmation:
2016-08-07 14:14:49,648 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-07 14:14:50,095 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-07 14:14:50,330 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-07 14:14:50,330 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-07 14:14:50,330 [PokemonGoBot] [INFO] [location_found] Location found: -33.8748755,151.1987113 (-33.8748755, 151.1987113, 0.0)
2016-08-07 14:14:50,330 [PokemonGoBot] [INFO] [position_update] Now at (-33.8748755, 151.1987113, 0)
2016-08-07 14:14:50,331 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-07 14:14:51,678 [pgoapi.auth] [ERROR] Could not retrieve token: Account is not yet active, please redirect.
2016-08-07 14:14:51,678 [PokemonGoBot] [INFO] [login_successful] Login successful.
Traceback (most recent call last):
  File "./pokecli.py", line 493, in <module>
    main()
  File "./pokecli.py", line 127, in main
    report_summary(bot)
  File "./pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "/Users/yang/Desktop/BotPokemonGo/PokemonGo-Bot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/Users/yang/Desktop/BotPokemonGo/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 90, in call
    if not self.can_call():
  File "/Users/yang/Desktop/BotPokemonGo/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 58, in can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
2016-08-07 14:14:51,683 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 891, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-07 14:14:51,684 [sentry.errors.uncaught] [ERROR] [u'NotLoggedInException', u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", line 127, in main', u'  File "pokecli.py", line 136, in report_summary', u'  File "pokemongo_bot/metrics.py", line 76, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 90, in call', u'  File "pokemongo_bot/api_wrapper.py", line 58, in can_call']

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by InuYashaMX** [comment]
same here
