### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by pranavperfect** [PokemonGoF/PokemonGo-Bot#2655]
### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by AlexandreCassagne** [comment]
Same problem.

**Comment by LHagood** [comment]
In your config file, set "health_record": false.  This solved the recursion problem for me

**Comment by dezayner** [comment]
Other Information

OS: Windows 7
Git Commit: c58bed9d0f66cc093a097d5b2f611981c4602ee6
Python Version: Python 2.7.12

**Comment by dezayner** [comment]
I got this error when set "health_record" to true.

`Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "D:\gamezone\pokebots\PokemonGo-Bot\pokemongo_bot\metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "D:\gamezone\pokebots\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 106, in call
    result = self._call()
  File "D:\gamezone\pokebots\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "d:\gamezone\pokebots\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 209, in call
    request.activate_signature(lib_path)
  File "d:\gamezone\pokebots\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 82, in activate_signature
    ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
`

**Comment by AlexandreCassagne** [comment]
Setting `health_record` to false, I get the following error:

`Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "/Users/Alexandre/Pokemon/PokemonGo-Bot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/Users/Alexandre/Pokemon/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 106, in call
    result = self._call()
  File "/Users/Alexandre/Pokemon/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "/Users/Alexandre/Pokemon/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 209, in call
    request.activate_signature(lib_path)
  File "/Users/Alexandre/Pokemon/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 82, in activate_signature
    ctypes.cdll.LoadLibrary(lib_path)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(encrypt.so, 6): image not found
`

**Comment by AlexandreCassagne** [comment]
@dezayner are you sure you don't mean `false` ?

**Comment by LHagood** [comment]
Different error.  You need to download encrypt.so (there are links in one of the other issue threads) and place it in the PokemonGo-Bot directory.  Be sure you get the correct version of the file for your OS.

**Comment by agastimhatre** [comment]
@AlexandreCassagne @dezayner  i got following after setting health_record to false

Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "C:\Users\agast\PokemonGo-Bot\pokemongo_bot\metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "C:\Users\agast\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 106, in call
    result = self._call()
  File "C:\Users\agast\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "c:\users\agast\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 209, in call
    request.activate_signature(lib_path)
  File "c:\users\agast\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 82, in activate_signature
    ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

**Comment by AlexandreCassagne** [comment]
@LHagood Yep: working perfectly. Thanks !

**Comment by pranavperfect** [comment]
@LHagood PokemonGo-Bot meaning root directory or pokemongo_bot directory?

**Comment by dezayner** [comment]
@LHagood do you have any recommended site to get encrypt.dll for Windows 7 ?

**Comment by pranavperfect** [comment]
Compiled the files. Renamed libencrypt.so to encrypt.so

Kept it in home directory of bot. Got the following error.

Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "/mnt/c/Users/prana/Desktop/Bot/Updated/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/mnt/c/Users/prana/Desktop/Bot/Updated/pokemongo_bot/api_wrapper.py", line 106, in call
    result = self._call()
  File "/mnt/c/Users/prana/Desktop/Bot/Updated/pokemongo_bot/api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "/mnt/c/Users/prana/Desktop/Bot/Updated/src/pgoapi/pgoapi/pgoapi.py", line 209, in call
    request.activate_signature(lib_path)
  File "/mnt/c/Users/prana/Desktop/Bot/Updated/src/pgoapi/pgoapi/rpc_api.py", line 82, in activate_signature
    ctypes.cdll.LoadLibrary(lib_path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: encrypt.so: cannot open shared object file: No such file or directory

**Comment by imvikash00** [comment]
@pranavperfect check it out 
https://github.com/PokemonGoF/PokemonGo-Bot/pull/2643

**Comment by k4n30** [comment]
@pranavperfect are you still experiencing this issue or can it be closed?
