### ISSUE TITLE
TypeError: not all arguments converted

### ISSUE THREAD

**Issue by absalom996** [PokemonGoF/PokemonGo-Bot#2666]
Hi all,

I read all the issue since the new API version, and didn't get mine.
Anyone one know to solve it plz ?

### Steps to Reproduce

$ sudo python pokecli.py

2016-08-07 07:26:36,895 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 07:26:36,923 [       cli] [INFO] No config argument specified, checking for /configs/config.json
2016-08-07 07:26:36,969 [       cli] [INFO] Configuration initialized
2016-08-07 07:26:36,973 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more logrmation:
2016-08-07 07:26:36,977 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-07 07:26:37,083 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-07 07:26:37,277 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-07 07:26:37,286 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-07 07:26:37,291 [PokemonGoBot] [INFO] [location_found] Location found: 40.758582, -73.985069 (40.758582, -73.985069, 0.0)
2016-08-07 07:26:37,295 [PokemonGoBot] [INFO] [position_update] Now at (40.758582, -73.985069, 0)
2016-08-07 07:26:37,302 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-07 07:26:41,877 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-07 07:26:44,112 [PokemonGoBot] [INFO] 
2016-08-07 07:26:44,117 [PokemonGoBot] [INFO] --- tip611104 ---
2016-08-07 07:26:44,122 [PokemonGoBot] [INFO] Level: 14 (Next Level: 10180 XP) (Total: 89820 XP)
2016-08-07 07:26:44,126 [PokemonGoBot] [INFO] Pokemon Captured: 252 | Pokestops Visited: 1942016-08-07 07:26:44,136 [PokemonGoBot] [INFO] Pokemon Bag: 21/250
2016-08-07 07:26:44,144 [PokemonGoBot] [INFO] Items: 298/350
2016-08-07 07:26:44,148 [PokemonGoBot] [INFO] Stardust: 25200 | Pokecoins: 0
2016-08-07 07:26:44,151 [PokemonGoBot] [INFO] PokeBalls: 100 | GreatBalls: 50 | UltraBalls: 0
2016-08-07 07:26:44,155 [PokemonGoBot] [INFO] RazzBerries: 75 | BlukBerries: 0 | NanabBerries: 0
2016-08-07 07:26:44,158 [PokemonGoBot] [INFO] LuckyEgg: 2 | Incubator: 2 | TroyDisk: 2
2016-08-07 07:26:44,162 [PokemonGoBot] [INFO] Potion: 10 | SuperPotion: 20 | HyperPotion: 0
2016-08-07 07:26:44,165 [PokemonGoBot] [INFO] Incense: 5 | IncenseSpicy: 0 | IncenseCool: 0
2016-08-07 07:26:44,168 [PokemonGoBot] [INFO] Revive: 30 | MaxRevive: 0
2016-08-07 07:26:44,171 [PokemonGoBot] [INFO] 
2016-08-07 07:26:44,174 [PokemonGoBot] [INFO] 
2016-08-07 07:26:46,767 [PokemonGoBot] [INFO] [bot_start] Starting bot...
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file __init__.py, line 547

2016-08-07 07:26:47,406 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-07 07:26:50,336 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-07 07:26:51,270 [CollectLevelUpReward] [INFO] [level_up_reward] Received level up reward: []
2016-08-07 07:26:51,278 [IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 5.00 km
2016-08-07 07:26:53,856 [FollowSpiral] [INFO] [position_update] Walking from (40.758773547180574, -73.98507902902782, 0) to (40.758773547180574, -73.98507902902782, 0) (0.0 m)
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file __init__.py, line 547

2016-08-07 07:26:55,237 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-07 07:26:58,214 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-07 07:27:00,706 [FollowSpiral] [INFO] [position_update] Walking from (40.758773547180574, -73.98507902902782, 0) to (40.759403604985216, -73.98507902902782, 0) (70.0592268266 m)
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file __init__.py, line 547

### Other Information
OS: Raspbian (Linux Debian for Raspberry)

**Comment by shoelsch** [comment]
+1

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file __init__.py, line 547
```

**Comment by itgoujie2** [comment]
+1, after this error, the bot just keep walking:

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file __init__.py, line 547
2016-08-07 00:48:21,177 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-07 00:48:22,537 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-07 00:48:23,199 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop 1971 Giants - 0.11km (attraction of lure 0.12km)
2016-08-07 00:48:30,220 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop 1971 Giants - 0.11km (attraction of lure 0.11km)
2016-08-07 00:48:32,054 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop 1971 Giants - 0.10km (attraction of lure 0.11km)
2016-08-07 00:48:34,204 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop 1971 Giants - 0.09km (attraction of lure 0.10km)
2016-08-07 00:48:35,972 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop 1971 Giants - 0.09km (attraction of lure 0.10km)
2016-08-07 00:48:37,768 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop 1971 Giants - 0.09km (attraction of lure 0.10km)
2016-08-07 00:48:39,675 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop 1971 Giants - 0.09km (attraction of lure 0.10km)
2016-08-07 00:48:41,770 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop 1971 Giants - 0.08km (attraction of lure 0.09km)
2016-08-07 00:48:43,805 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop 1971 Giants - 0.08km (attraction of lure 0.09km)
2016-08-07 00:48:45,394 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop 1971 Giants - 0.07km (attraction of lure 0.09km)
2016-08-07 00:48:47,386 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop 1971 Giants - 0.07km (attraction of lure 0.08km)
2016-08-07 00:48:49,321 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop 1971 Giants - 0.06km (attraction of lure 0.08km)
2016-08-07 00:48:50,902 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop 1971 Giants - 0.06km (attraction of lure 0.08km)
2016-08-07 00:48:52,799 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop 1971 Giants - 0.06km (attraction of lure 0.07km)
2016-08-07 00:48:54,603 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop 1971 Giants - 0.05km (attraction of lure 0.07km)
2016-08-07 00:48:57,205 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop 1971 Giants - 0.05km (attraction of lure 0.07km)
2016-08-07 00:48:59,032 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop 1971 Giants - 0.04km (attraction of lure 0.06km)
2016-08-07 00:49:00,896 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop 1971 Giants - 0.04km (attraction of lure 0.06km)
2016-08-07 00:49:03,289 [  SpinFort] [INFO] [pokestop_out_of_range] Pokestop 1971 Giants out of range.
2016-08-07 00:49:03,289 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-07 00:49:03,296 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop China Basin Park - 0.06km (attraction of lure 0.06km)
2016-08-07 00:49:05,447 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop China Basin Park - 0.05km (attraction of lure 0.05km)
2016-08-07 00:49:07,345 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop China Basin Park - 0.05km (attraction of lure 0.05km)
2016-08-07 00:49:09,199 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop China Basin Park - 0.05km (attraction of lure 0.05km)
2016-08-07 00:49:11,174 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop China Basin Park - 0.04km (attraction of lure 0.04km)
2016-08-07 00:49:13,188 [  SpinFort] [INFO] [pokestop_out_of_range] Pokestop China Basin Park out of range.
2016-08-07 00:49:13,188 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.

**Comment by Nik0lashka** [comment]
@absalom996 @itgoujie2 same for me, after this error bot just wanders from one pokemon to another:
[Log.txt](https://github.com/PokemonGoF/PokemonGo-Bot/files/405467/Log.txt)
