### ISSUE TITLE
WindowsError: [Error 126] The specified module could not be found

### ISSUE THREAD

**Issue by bnlucas** [PokemonGoF/PokemonGo-Bot#2670]
### Expected Behavior
Bot runs

### Actual Behavior
Error occurs

### Steps to Reproduce
Install from fresh copy of master

- pip install -r requirements.txt
- python pokecli.py

### Other Information
OS: Windows 10/64bit
Git Commit: c81666d751b9ca8cd338760fdf920194fabf4ee4
Python Version: Python 2.7.10

`WindowsError: [Error 126] The specified module could not be found
2016-08-06 23:53:03,328 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/
store/)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\raven\transport\threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "C:\Python27\lib\site-packages\raven\transport\http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 494, in open
    response = self._open(req, data)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 512, in _open
    '_open', req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python27\lib\httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 891, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-06 23:53:03,335 [sentry.errors.uncaught] [ERROR] [u'WindowsError: [Error 126] The specified module could not be found', u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", li
ne 127, in main', u'  File "pokecli.py", line 136, in report_summary', u'  File "c:\\projects\\python\\PokemonGo-Bot\\pokemongo_bot\\metrics.py", line 76, in capture_stats', u'  File "c:\\projects\\py
thon\\PokemonGo-Bot\\pokemongo_bot\\api_wrapper.py", line 106, in call', u'  File "c:\\projects\\python\\PokemonGo-Bot\\pokemongo_bot\\api_wrapper.py", line 63, in _call', u'  File "c:\\projects\\pyth
on\\pokemongo-bot\\src\\pgoapi\\pgoapi\\pgoapi.py", line 209, in call', u'  File "c:\\projects\\python\\pokemongo-bot\\src\\pgoapi\\pgoapi\\rpc_api.py", line 82, in activate_signature', u'  File "C:\\
Python27\\lib\\ctypes\\__init__.py", line 443, in LoadLibrary', u'  File "C:\\Python27\\lib\\ctypes\\__init__.py", line 365, in __init__']`

**Comment by WaffleMoose** [comment]
Looks like a similar issue to #2641

**Comment by islanderman** [comment]
@WaffleMoose you have two issues; the first one is what you are at here, and the second one has something to do with ``health_record``.  Set ``health_record`` to ``false`` in your ``config`` would solve the second issue.

**Comment by bnlucas** [comment]
@islanderman checking `health_record` to `false` fixed that issue, now I'm getting

```
2016-08-07 00:56:35,397 [PokemonGoBot] [INFO]
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "c:\projects\python\PokemonGo-Bot\pokemongo_bot\metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "c:\projects\python\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 106, in call
    result = self._call()
  File "c:\projects\python\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "C:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 209, in call
    request.activate_signature(lib_path)
  File "C:\Python27\lib\site-packages\pgoapi\rpc_api.py", line 82, in activate_signature
    ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
```

And yes, I have `encrypt.dll`

**Comment by islanderman** [comment]
@bnlucas you might want to look into ``pokemongo_bot/__init__.py`` and change ``self.api.activate_signature("encrypt.so")`` to ``self.api.activate_signature("./encrypt.dll")``

I however do not have a Windows machine to verify.  🎱

**Comment by bnlucas** [comment]
@islanderman that did the trick! Thanks

**Comment by ledesmano365** [comment]
@bnlucas , can you share the link to encrypt.dll, been trying to find it from the other threads. Thanks!

**Comment by aviel600** [comment]
@bnlucas didnt work for me

**Comment by ducminhquan** [comment]
@bnlucas can u share me your working encrypt.dll

**Comment by agastimhatre** [comment]
@bnlucas its in the slack chat, you can get it there.

**Comment by ledesmano365** [comment]
Here.. https://www.sendspace.com/file/bq0hcn
