### ISSUE TITLE
WindowsError after successfull login

### ISSUE THREAD

**Issue by denike** [PokemonGoF/PokemonGo-Bot#2683]
### Expected Behavior
Bot runs normaly

### Actual Behavior
It drops a windows error

### Other Information

`Traceback (most recent call last):
  File "pokecli.py", line 496, in <module>
    main()
  File "pokecli.py", line 130, in main
    report_summary(bot)
  File "pokecli.py", line 139, in report_summary
    metrics.capture_stats()
  File "C:\Users\Dini\Downloads\PokemonGo-Botdev\pokemongo_bot\metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "C:\Users\Dini\Downloads\PokemonGo-Botdev\pokemongo_bot\api_wrapper.py", line 106, in call
    result = self._call()
  File "C:\Users\Dini\Downloads\PokemonGo-Botdev\pokemongo_bot\api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "c:\users\dini\downloads\pokemongo-botdev\src\pgoapi\pgoapi\pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "c:\users\dini\downloads\pokemongo-botdev\src\pgoapi\pgoapi\rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError:`

OS: Win10
Git Commit: 44a6602ceecf202e5ab0bf05a960b8efcb595551
Python Version: Python 2.7.12

**Comment by aviel600** [comment]
same here

**Comment by bigrat69** [comment]
I get this one after successful login:

![encrypt_so](https://cloud.githubusercontent.com/assets/20883113/17461065/9b48b6da-5c87-11e6-841e-578de31a23d6.PNG)

**Comment by bnlucas** [comment]
Look at the fix found on https://github.com/PokemonGoF/PokemonGo-Bot/issues/2670

**Comment by aviel600** [comment]
@bnlucas didnt work for me :(

**Comment by bigrat69** [comment]
u need the dll file too. Copy it in the root. Unfortunately i cant upload it here because file type is not supported. Get it from slack:

https://pokemongo-bot.herokuapp.com/

**Comment by aviel600** [comment]
@bigrat69 i put it in the main folder and it still reply the same error, should i do something different ?

**Comment by denike** [comment]
Just now pulled again and it started working. All I did is the following

> you might want to look into pokemongo_bot/__init__.py and change self.api.activate_signature("encrypt.so") to self.api.activate_signature("./encrypt.dll")

got the dll from slack.

Thanks everybody for your time and help!

**Comment by adamtong1110** [comment]
not working for me
