### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by takenek** [PokemonGoF/PokemonGo-Bot#2686]
After 20 minutes working got crash:

2016-08-07 08:59:48,973 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Fontanna od Alei  - 0.07km (attraction of lure 0.07km)
2016-08-07 08:59:51,018 [       cli] [INFO]
2016-08-07 08:59:51,019 [       cli] [INFO] Ran for 0:30:42
2016-08-07 08:59:51,019 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-07 08:59:51,019 [       cli] [INFO] Travelled 0.00km
2016-08-07 08:59:51,019 [       cli] [INFO] Visited 0 stops
2016-08-07 08:59:51,019 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-07 08:59:51,019 [       cli] [INFO] Threw 0 pokeballs
2016-08-07 08:59:51,019 [       cli] [INFO] Earned 0 Stardust
2016-08-07 08:59:51,019 [       cli] [INFO]
2016-08-07 08:59:51,019 [       cli] [INFO] Highest CP Pokemon: Oddish [CP: 72] [IV: 3/6/5] Potential: 0.31
2016-08-07 08:59:51,020 [       cli] [INFO] Most Perfect Pokemon: Eevee [CP: 14] [IV: 15/9/14] Potential: 0.84
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 129, in main
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 0: ordinal not in range(128)
2016-08-07 08:59:51,024 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/taken/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/taken/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/taken/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/taken/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/taken/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/taken/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/taken/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/taken/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-07 08:59:51,024 [sentry.errors.uncaught] [ERROR] [u"UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 0: ordinal not in range(128)", u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", line 129, in main']

I try run again and:
2016-08-07 09:03:22,149 [PokemonGoBot] [INFO] [bot_start] Starting bot...
2016-08-07 09:03:22,918 [CollectLevelUpReward] [INFO] [level_up_reward] Received level up reward: []
2016-08-07 09:03:22,918 [IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 1.27 km
2016-08-07 09:03:23,556 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Zubat appeared! [CP 41] [Potential 0.56] [S/A/D 7/15/3]
2016-08-07 09:03:26,025 [PokemonCatchWorker] [INFO] [threw_pokeball] Used Pokeball, with chance 92.71 (99 left)
2016-08-07 09:03:26,459 [PokemonCatchWorker] [INFO] [pokemon_caught] Captured Zubat! [CP 41] [Potential 0.56] [7/15/3] [+710 exp]
2016-08-07 09:03:31,857 [       cli] [INFO]
2016-08-07 09:03:31,857 [       cli] [INFO] Ran for 0:00:20
2016-08-07 09:03:31,857 [       cli] [INFO] Total XP Earned: 710  Average: 126887.55/h
2016-08-07 09:03:31,857 [       cli] [INFO] Travelled 0.00km
2016-08-07 09:03:31,857 [       cli] [INFO] Visited 0 stops
2016-08-07 09:03:31,858 [       cli] [INFO] Encountered 1 pokemon, 1 caught, 0 released, 0 evolved, 1 never seen before
2016-08-07 09:03:31,858 [       cli] [INFO] Threw 1 pokeball
2016-08-07 09:03:31,858 [       cli] [INFO] Earned 100 Stardust
2016-08-07 09:03:31,858 [       cli] [INFO]
2016-08-07 09:03:31,858 [       cli] [INFO] Highest CP Pokemon: Zubat [CP: 41] [IV: 7/15/3] Potential: 0.56
2016-08-07 09:03:31,858 [       cli] [INFO] Most Perfect Pokemon: Zubat [CP: 41] [IV: 7/15/3] Potential: 0.56
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 129, in main
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 0: ordinal not in range(128)
2016-08-07 09:03:31,862 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/taken/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/taken/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/taken/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/taken/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/taken/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/taken/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/taken/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/taken/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-07 09:03:31,863 [sentry.errors.uncaught] [ERROR] [u"UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 0: ordinal not in range(128)", u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", line 129, in main']

**Comment by nujabse** [comment]
Same error on Archlinux

**Comment by mushi8** [comment]
Same on ubuntu

**Comment by SuperIguane** [comment]
Same on OSX

**Comment by dkim1000** [comment]
@2677 temporarily fixes it

**Comment by takenek** [comment]
thanks @dkim1000 looks working :-)

**Comment by wilsonlmh** [comment]
@SuperIguane May I know how you make it works under OSX? I mean how where can I get a encrypt.dylib? Thanks

**Comment by nivong** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2776
and @wilsonlmh read around...

**Comment by RedViper9** [comment]
#2808
