### ISSUE TITLE
Bot not starting in windows 

### ISSUE THREAD

**Issue by Animeshm77** [PokemonGoF/PokemonGo-Bot#2697]
$ python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
  File "d:\hacking\bot\pokemongo-bot\src\pgoapi\pgoapi\__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "d:\hacking\bot\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "d:\hacking\bot\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 47, in <module>
    from pgoapi.utilities import to_camel_case, get_time, get_format_time_diff, Rand48, long_to_bytes, generateLocation1, generateLocation2, generateRequestHash, f2i
  File "d:\hacking\bot\pokemongo-bot\src\pgoapi\pgoapi\utilities.py", line 30, in <module>
    import xxhash
ImportError: No module named xxhash

Getting this error after running start command for bot.
Please help.

**Comment by MikeDX** [comment]
This is an issue tracker for bugs, not for help.

Please see the WIKI or join the slack chat for help.

**Comment by agastimhatre** [comment]
Install this 
https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi

**Comment by Animeshm77** [comment]
@agastimhatre than it wil work ?
