### ISSUE TITLE
App Crashes on wrong password.

### ISSUE THREAD

**Issue by M3NTI0N** [PokemonGoF/PokemonGo-Bot#2704]
I don't know if it is only on the updated_pgoapi branch or everywhere ;)

### Expected Behavior
Just stops normally, instead of crashing.

### Actual Behavior
Bot crashes right after the blocked message.

`2016-08-07 10:06:36,068 [pgoapi.auth] [ERROR] Could not retrieve token: As a security measure, your account has been disabled for 15 minutes because you have failed to log in correctly too many times. Please come back and try again in 15 minutes.
2016-08-07 10:06:36,071 [PokemonGoBot] [INFO] [login_successful] Login successful.
Traceback (most recent call last):
  File "./pokecli.py", line 493, in <module>
    main()
  File "./pokecli.py", line 127, in main
    report_summary(bot)
  File "./pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "/home/polichism/PokemonGo-Bot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/home/polichism/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 90, in call
    if not self.can_call():
  File "/home/polichism/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 58, in can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
2016-08-07 10:06:36,127 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-07 10:06:36,138 [sentry.errors.uncaught] [ERROR] [u'NotLoggedInException', u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", line 127, in main', u'  File "pokecli.py", line 136, in report_summary', u'  File "pokemongo_bot/metrics.py", line 76, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 90, in call', u'  File "pokemongo_bot/api_wrapper.py", line 58, in can_call']
`
### Steps to Reproduce
try to login with wrong details of a real account.

### Other Information
OS: Ubuntu 16.04 LTS
Git Commit: a05b542ea71172556cf0eb0e00cbe665607c4319
Python Version: Python 2.7.12

**Comment by k4n30** [comment]
@M3NTI0N Are you still experiencing this issue?
