### ISSUE TITLE
[ERROR] maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by akbaribnu** [PokemonGoF/PokemonGo-Bot#2716]
hello dev, this bot script always error like that, can you solved this, thank you

2016-08-07 08:55:27,121 [sentry.errors.serializer] [ERROR] maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/raven/utils/serializer/manager.py", line 76, in transform
    return repr(value)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 367, in __repr__
    (self._handle & (_sys.maxint*2 + 1)),
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 373, in __getattr__
    func = self.__getitem__(name)

**Comment by Lunik** [comment]
Same here. I'm on dev branch 0b319bc243a1b11b17c8639f8d902b41ec233e6c

I have done `pip install -r requirement.txt` and `./install.sh` with no error.

**Comment by akbaribnu** [comment]
sure, im on dev branch too, and  i have run install.sh and pip install -r requerment.txt but still error

**Comment by Lunik** [comment]
I will try to make a clean install from scratch

**Comment by slaxmtk** [comment]
Add the **encrypt.so** file to the PokemonGo-Bot directory. Here is the download link https://slack-files.com/T1U6G9ZEW-F1YV50RGQ-cc979942b7 . Thx @segflow

**Comment by Lunik** [comment]
@slaxmtk where did you get this ?

**Comment by manthan29jamdagni** [comment]
@slaxmtk Even after adding this encrypt.so file, the problem persists.

**Comment by akbaribnu** [comment]
my problem still same after download and add encrypt.so

**Comment by wesley-ontoforce** [comment]
copied the file and it works now

**Comment by lixam** [comment]
For me @slaxmtk fix worked fine!
Thanks!

**Comment by lucasren** [comment]
add encrypto.so , go another error

encrypt.so is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc000012f.

**Comment by yuftao** [comment]
I had the same issue, adding the encrypt.so file fixes that

**Comment by NerdsMcGee** [comment]
I built encrypt.so, placed it in the project root folder, and I'm still getting:

'OSError: encrypt.so: cannot open shared object file: No such file or directory'

(PokemonGo-Bot) |09:57:30|ubuntu:[PokemonGo-Bot]> ll | grep encrypt.so
-rwxrwxrwx 1 ubuntu ubuntu 250416 Aug  7 09:50 encrypt.so

**Comment by slaxmtk** [comment]
sorry guys. it seems that the encrypt.so only works for MacOS

**Comment by akbaribnu** [comment]
ohh noo.. i use centos 7 64bit, maybe you have link encrypt.so for linux 64bit

**Comment by theLastLivingGhost** [comment]
Yeah, me using Ubuntu 16.04 and unfortunately doesn't run, I'll try on Arch as well.

**Comment by elhanarinc** [comment]
Im on debian 8, its not working on this OS, either.

**Comment by Lunik** [comment]
I have tried: 
```
$ wget http://pgoapi.com/pgoencrypt.tar.gz
$ tar -xf pgoencrypt.tar.gz
$ cd pgoencrypt/src/
$ make
```
But still doesn't work...

**Comment by NerdsMcGee** [comment]
Lunik: Did you rename the .so generated to encrypt.so?

**Comment by NerdsMcGee** [comment]
Got it. Went into __init__.py, changed encrypt.so to "./encrypt.so" to reference the file I built.

**Comment by theLastLivingGhost** [comment]
It ran for 50 seconds and UnicodeDecodeError again, it cleared my pokemons based on iv though so I'm way more happy than I was in the past few days. Did what @NerdsMcGee told to do.

**Comment by NerdsMcGee** [comment]
I wound up pulling the dev branch, and I'm still working.

**Comment by elhanarinc** [comment]
2016-08-07 13:22:37,489 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
I got this message, even after i create an encrypt.so and adding into pokemon-go root

**Comment by akbaribnu** [comment]
@NerdsMcGee  its work for me :D , i use centos 7 64bit
thank you.
after change "encrypt.so" to "./encrypt.so" on file pokemongo_bot/__init__.py

**Comment by elhanarinc** [comment]
@NerdsMcGee Thanks man! Mine is also working now.

**Comment by theLastLivingGhost** [comment]
Here is the error message with full call stack on Ubuntu 16.04:
http://pastebin.com/Ay34zFGN

And now I go and try to install it on my Pi on Arch ARM, I bloody well hope it'll run it. *fingers crossed*

**Comment by NerdsMcGee** [comment]
You'll need to compile encrypt.so on the Pi, since it's per-system

**Comment by theLastLivingGhost** [comment]
@RioRizkyRainey
I did pretty much the same I think, ran into error mentioned above. Except that the init file name project path is `pokemongo_bot/__init__.py`, with underscores.

**Comment by NerdsMcGee** [comment]
Yeah, I forgot markup was applied when I copied the file. Everyone seems to know what I meant though. ;)

**Comment by muratcancicek** [comment]
on cygwin in Windows 10, I got following error when I tried to make

$ make
cc -fPIC -std=gnu99   -c -o encrypt.o encrypt.c
encrypt.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /**
 ^
cc -shared -o libencrypt.so encrypt.o -lm
cc -fPIC -std=gnu99   -c -o main.o main.c
main.c:1:0: warning: -fPIC ignored for target (all code is position independent)

 ^
cc -o test -L. main.o -lencrypt
/usr/lib/gcc/x86_64-pc-cygwin/4.9.3/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lencrypt
collect2: error: ld returned 1 exit status
Makefile:9: recipe for target 'test' failed
make: *** [test] Error 1

**Comment by carl-eis** [comment]
@RioRizkyRainey Thanks so much for clearing this up. Works for me 100%

**Comment by Lunik** [comment]
```
$ wget http://pgoapi.com/pgoencrypt.tar.gz
$ tar -xf pgoencrypt.tar.gz
$ cd pgoencrypt/src/
$ make
$ cp libencryp.o PokemonGo-Bot/encrypt.so
```

This is working :)

**Comment by muratcancicek** [comment]
@Lunik Isn't it "libencrypt.so"?

**Comment by Lunik** [comment]
Yes mispelling ;)

**Comment by k4n30** [comment]
#2768

**Comment by lucasren** [comment]
Still hnaving the same error with encrypt.dll
Found encrypt.dll! Platform: win32 Bot root directory:

 [ERROR] maximum recursion depth exceeded while calling a Python object

**Comment by indiealexh** [comment]
Fix for me (Win 10):
Download https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/pogom/encrypt32bit.dll rename it into encrypt.dll and place it in the project root directory
Then edit _init_.py to use ./encrypt.dll

And boom, working PokeBot!

**Comment by JetP1L0t** [comment]
Fix for OSX:
copied from Pokemon GO Live Map.app/Contents/Resources/app/map/pogom/libencrypt-osx.so to bot root directory. Renamed to encrypt.so
Map app: https://github.com/mchristopher/PokemonGo-DesktopMap/releases

**Comment by tokarevi** [comment]
@RioRizkyRainey sollution with "libencrypt.so" worked just fine for ubuntu 14.04, thanks.

**Comment by jrjhealey** [comment]
As this is the least recently updated issue, I'll assume it was based on an old commit and close. Most if not all of these issues have been resolved in PRs as far as I'm aware.

**Comment by QuanHuynhM** [comment]
Sorry, but i have some errors. But i still not fix it. I am used Windowns 10. I have download encryp.dll. Pls help me!

**Comment by k4n30** [comment]
@QuanHuynhM What is that? Error logs? or code?

Please join the slack server as per the README for help

**Comment by QuanHuynhM** [comment]
My problem: "maximum recursion depth exceeded while calling a Python object". I follow @indiealexh . But i still not working.
