### ISSUE TITLE
Forts all need rest after bot relogs in

### ISSUE THREAD

**Issue by xterraforcex** [PokemonGoF/PokemonGo-Bot#2721]
2016-08-07 03:51:34,660 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop The Church In Milwaukee - 0.14km
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file __init__.py, line 547
2016-08-07 03:51:39,748 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-07 03:51:40,396 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-07 03:51:41,002 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop The Church In Milwaukee - 0.13km
2016-08-07 03:51:47,672 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop The Church In Milwaukee - 0.12km
2016-08-07 03:51:49,391 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop The Church In Milwaukee - 0.11km
2016-08-07 03:51:51,194 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop The Church In Milwaukee - 0.10km
2016-08-07 03:51:53,349 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop The Church In Milwaukee - 0.09km
2016-08-07 03:51:55,053 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop The Church In Milwaukee - 0.09km
2016-08-07 03:51:56,707 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop The Church In Milwaukee - 0.07km
2016-08-07 03:51:58,814 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop The Church In Milwaukee - 0.06km
2016-08-07 03:52:00,875 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop The Church In Milwaukee - 0.05km
2016-08-07 03:52:02,820 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop The Church In Milwaukee - 0.04km
2016-08-07 03:52:04,764 [  SpinFort] [INFO] [pokestop_out_of_range] Pokestop The Church In Milwaukee out of range.
2016-08-07 03:52:04,764 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.

and it will keep doing this till i stop the bot and restart it what do i need to change in the new config file?

**Comment by balpoint** [comment]
I can confirm that this is also happening in my bot instances.
