### ISSUE TITLE
WindowsError:

### ISSUE THREAD

**Issue by Trytotry2** [PokemonGoF/PokemonGo-Bot#2723]
### Actual Behavior
Bot launch, can connect to my account, identify my items, pokemon etc and then, it crash.

Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "C:\Users\Romain\Downloads\Bot Pokemon Go\PokemonGo-Bot\pokemongo_bot\metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "C:\Users\Romain\Downloads\Bot Pokemon Go\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 106, in call
    result = self._call()
  File "C:\Users\Romain\Downloads\Bot Pokemon Go\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "c:\users\romain\downloads\bot pokemon go\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "c:\users\romain\downloads\bot pokemon go\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError:

### Steps to Reproduce
C:\Python27\python.exe pokecli.py

### Other Information
OS: Windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)
I made a new clean install of the bot

**Comment by NoProgramist** [comment]
the same error.
OS: Windows 7
Python version: 2.7.11

**Comment by Calcyfer** [comment]
Same here, I think a dll is missing. Might be the encrypt.dll that's in some other projects.

**Comment by skywalker878** [comment]
same error on windows 7

**Comment by Kosmatik** [comment]
Same on Win 10, fresh Python 2.7.12 with clean git master and dev branches.

**Comment by g2384** [comment]
Same on Ubuntu 16.04

**Comment by Kosmatik** [comment]
Fixed with help of #2706 

put encrypt.dll into main directory

 look into pokemongo_bot/init.py and change self.api.activate_signature("encrypt.so") to self.api.activate_signature("./encrypt.dll")

**Comment by Calcyfer** [comment]
See @Kosmatik 's answer, this line :

`pgoapi/rpc_api.py` line 226 : 
`def _generate_signature(self, signature_plain, lib_path="encrypt.so"):`

**Comment by Calcyfer** [comment]
Here's a folder with the windows 32 and 64 bit : 
https://mega.nz/#fm/Jh1ijT5B

**Comment by bulubebek** [comment]
@Calcyfer your link doesn't work for me. can you re-upload it to another file hosting (eg. mediafire)? thank you.
