### ISSUE TITLE
Can not run it on windows

### ISSUE THREAD

**Issue by skywalker878** [PokemonGoF/PokemonGo-Bot#2726]
### Actual Behavior
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions

### Steps to Reproduce

python pokecli.py

### Other Information
OS: Windows 7
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by dimasnp** [comment]
https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi

**Comment by skywalker878** [comment]
Now I got another error :


 python pokecli.py
2016-08-07 02:45:56,591 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 02:45:56,591 [       cli] [INFO] No config argument specified, checking for /configs/config.json
2016-08-07 02:45:56,591 [       cli] [INFO] Configuration initialized
2016-08-07 02:45:56,591 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-07 02:45:56,591 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-07 02:45:56,591 [PokemonGoBot] [INFO] [location_found] Location found: 37.807665,-122.431196 (37.807665, -122.431196, 0.0)
2016-08-07 02:45:56,591 [PokemonGoBot] [INFO] [position_update] Now at (37.807665, -122.431196, 0)
2016-08-07 02:45:56,591 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-07 02:45:58,650 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-07 02:45:59,789 [PokemonGoBot] [INFO]
2016-08-07 02:45:59,789 [PokemonGoBot] [INFO] --- Shagoma ---
2016-08-07 02:45:59,789 [PokemonGoBot] [INFO] Level: 1 (Next Level: 150 XP) (Total: 850 XP)
2016-08-07 02:45:59,789 [PokemonGoBot] [INFO] Pokemon Captured: 1 | Pokestops Visited: 3
2016-08-07 02:45:59,789 [PokemonGoBot] [INFO] Pokemon Bag: 2/250
2016-08-07 02:45:59,789 [PokemonGoBot] [INFO] Items: 60/350
2016-08-07 02:45:59,789 [PokemonGoBot] [INFO] Stardust: 100 | Pokecoins: 0
2016-08-07 02:45:59,789 [PokemonGoBot] [INFO] PokeBalls: 56 | GreatBalls: 0 | UltraBalls: 0
2016-08-07 02:45:59,789 [PokemonGoBot] [INFO] RazzBerries: 0 | BlukBerries: 0 | NanabBerries: 0
2016-08-07 02:45:59,789 [PokemonGoBot] [INFO] LuckyEgg: 0 | Incubator: 0 | TroyDisk: 0
2016-08-07 02:45:59,789 [PokemonGoBot] [INFO] Potion: 0 | SuperPotion: 0 | HyperPotion: 0
2016-08-07 02:45:59,789 [PokemonGoBot] [INFO] Incense: 2 | IncenseSpicy: 0 | IncenseCool: 0
2016-08-07 02:45:59,789 [PokemonGoBot] [INFO] Revive: 0 | MaxRevive: 0
2016-08-07 02:45:59,789 [PokemonGoBot] [INFO]
2016-08-07 02:45:59,789 [PokemonGoBot] [INFO]
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "C:\pokemongo-bot\pokemongo_bot\metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "C:\pokemongo-bot\pokemongo_bot\api_wrapper.py", line 106, in call
    result = self._call()
  File "C:\pokemongo-bot\pokemongo_bot\api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "c:\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "c:\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

**Comment by dezayner** [comment]
#2706

**Comment by k4n30** [comment]
#2768

**Comment by nivong** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2780
