### ISSUE TITLE
module' object has no attribute 'HTTPSHandler

### ISSUE THREAD

**Issue by Drambuie** [PokemonGoF/PokemonGo-Bot#2730]
### Actual Behavior

Bot should start

Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 129, in main
    raise e
TypeError: emit_event() got an unexpected keyword argument 'formmated'
2016-08-07 10:38:21,996 [sentry.errors] [ERROR] Sentry responded with an error: 'module' object has no attribute 'HTTPSHandler' (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 44, in urlopen
    class ValidHTTPSHandler(urllib2.HTTPSHandler):
AttributeError: 'module' object has no attribute 'HTTPSHandler'
2016-08-07 10:38:21,997 [sentry.errors.uncaught] [ERROR] [u"TypeError: emit_event() got an unexpected keyword argument 'formmated'", u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", line 129, in main']

### Steps to Reproduce
./run.sh

### Other Information
OS: Ubuntu
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by NicholasMolenaar** [comment]
The key formmated in the pokecli.py is wrongly typed, correct it and it shall work.

formmated > formatted

ps: stick to the report template.

**Comment by NicholasMolenaar** [comment]
Ow and disable `health_record` in your config file for now.

**Comment by leadboots5** [comment]
The 'formmated' text was fixed in a merge. git pull will fix this issue.
