### ISSUE TITLE
Many error after my bot say is logged in. I can't show you all error because the windows console is full.

### ISSUE THREAD

**Issue by CackboneDev** [PokemonGoF/PokemonGo-Bot#2739]
result = handler.capture(**kwargs)
  File "C:\Python27\lib\site-packages\raven\events.py", line 65, in capture
    capture_locals=self.client.capture_locals,
  File "C:\Python27\lib\site-packages\raven\utils\stacks.py", line 332, in get_stack_info
    f_vars = get_frame_locals(frame, transformer=transformer)
  File "C:\Python27\lib\site-packages\raven\utils\stacks.py", line 195, in get_frame_locals
    v = transformer(v)
  File "C:\Python27\lib\site-packages\raven\events.py", line 32, in transform
    return self.client.transform(value)
  File "C:\Python27\lib\site-packages\raven\base.py", line 477, in transform
    string_max_length=self.string_max_length)
  File "C:\Python27\lib\site-packages\raven\utils\serializer\manager.py", line 94, in transform
    return serializer.transform(value, **kwargs)
  File "C:\Python27\lib\site-packages\raven\utils\serializer\manager.py", line 78, in transform
    logger.exception(e)
  File "C:\Python27\lib\logging\__init__.py", line 1192, in exception
    self.error(msg, *args, **kwargs)
  File "C:\Python27\lib\logging\__init__.py", line 1185, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\Python27\lib\logging\__init__.py", line 1278, in _log
    self.handle(record)
  File "C:\Python27\lib\logging\__init__.py", line 1288, in handle
    self.callHandlers(record)
  File "C:\Python27\lib\logging\__init__.py", line 1328, in callHandlers
    hdlr.handle(record)
  File "C:\Python27\lib\logging\__init__.py", line 751, in handle
    self.emit(record)
  File "C:\Python27\lib\logging\__init__.py", line 874, in emit
    stream.write(fs % msg)
  File "C:\Python27\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "C:\Python27\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "C:\Python27\lib\site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Python27\lib\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
KeyboardInterrupt

Original exception was:
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "C:\Users\cackbone\Desktop\pokebot\pokebot\pokemongo_bot\metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "C:\Users\cackbone\Desktop\pokebot\pokebot\pokemongo_bot\api_wrapper.py", line 106, in call
    result = self._call()
  File "C:\Users\cackbone\Desktop\pokebot\pokebot\pokemongo_bot\api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "c:\users\cackbone\desktop\pokebot\pokebot\src\pgoapi\pgoapi\pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "c:\users\cackbone\desktop\pokebot\pokebot\src\pgoapi\pgoapi\rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)

**Comment by fari-99** [comment]
are you already login or not?
please refer to this #2683

**Comment by k4n30** [comment]
#2768

**Comment by nivong** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2780
