### ISSUE TITLE
Error during renewing session

### ISSUE THREAD

**Issue by raxxon** [PokemonGoF/PokemonGo-Bot#2748]
Received the following failure in the log, bot logged back in without completely crashing, but can't spin. Looks like it had a moment where it thought it was back at the start point of my loop and tried to spin the stops there and then moved on, but still getting spin errors as it passes other pokestops....

2016-08-07 05:18:13,228 [RecycleItems] [INFO] [item_discarded] Discarded 1x Potion (maximum 0).
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file __init__.py, line 550
2016-08-07 05:18:34,700 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-07 05:18:35,196 [PokemonGoBot] [INFO] [login_successful] Login successful.

**Comment by KotZer** [comment]
Exactly the same problem for me. Happened two times after 29 minutes.

**Comment by raxxon** [comment]
Hrm. Mine was almost 34 minutes... I'll see if it happens again...

**Comment by KotZer** [comment]
I think it is discussed here #2698 and solved with the latest commit.

**Comment by raxxon** [comment]
Yep, 30 minutes and it popped the error.... I'll do a pull and see if that commit is in and resolves things...

**Comment by raxxon** [comment]
Attempted to apply suggested fix, no change, error after 30 min runtime.

**Comment by geek-man** [comment]
@raxxon Which fix did you apply? Fixing the logging turned out to be pointless. The second change of activate_signature did the trick for me. Haven't had the issue since adding that in.

**Comment by raxxon** [comment]
The activate signature call in init

**Comment by geek-man** [comment]
Did you also fix the logging call that causes the exception? Might need both to be fixed for it to work. Would make sense that if the exception is thrown first, then activate signature doesn't get called.

**Comment by brantje** [comment]
Seems to happen after ~30 min. I can confirm this.
```
2016-08-07 13:59:00,412 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Huntington Falls Rock - 0.08km (attraction of lure 0.08km)
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 850, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 723, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file __init__.py, line 550
2016-08-07 13:59:12,660 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-07 13:59:14,487 [PokemonGoBot] [INFO] [login_successful] Login successful.
```
Looks like the session has ended, and extended, however throwing that error isn't nice.
