### ISSUE TITLE
Unknown Error 

### ISSUE THREAD

**Issue by JaydenHamence** [PokemonGoF/PokemonGo-Bot#2751]
### Expected Behaviour
bot logs in and runs

### Actual Behavior
(PokemonGo-Bot) Jaydens-Air:PokemonGo-Bot JaydenHamence$ sh run.sh
2016-08-07 20:33:11,473 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 20:33:11,478 [       cli] [INFO] Configuration initialized
2016-08-07 20:33:11,483 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-07 20:33:11,484 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-07 20:33:11,484 [PokemonGoBot] [INFO] [location_found] Location found: -37.813628, 144.963058 (-37.813628, 144.963058, 0.0)
2016-08-07 20:33:11,484 [PokemonGoBot] [INFO] [position_update] Now at (-37.813628, 144.963058, 0)
2016-08-07 20:33:11,485 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-07 20:33:14,554 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-07 20:33:15,727 [PokemonGoBot] [INFO] 
2016-08-07 20:33:15,728 [PokemonGoBot] [INFO] --- RivalJayden ---
2016-08-07 20:33:15,728 [PokemonGoBot] [INFO] Level: 22 (Next Level: 25671 XP) (Total: 409329 XP)
2016-08-07 20:33:15,728 [PokemonGoBot] [INFO] Pokemon Captured: 1251 | Pokestops Visited: 1411
2016-08-07 20:33:15,729 [PokemonGoBot] [INFO] Pokemon Bag: 148/300
2016-08-07 20:33:15,729 [PokemonGoBot] [INFO] Items: 172/400
2016-08-07 20:33:15,730 [PokemonGoBot] [INFO] Stardust: 8133 | Pokecoins: 140
2016-08-07 20:33:15,730 [PokemonGoBot] [INFO] PokeBalls: 122 | GreatBalls: 13 | UltraBalls: 1
2016-08-07 20:33:15,730 [PokemonGoBot] [INFO] RazzBerries: 9 | BlukBerries: 0 | NanabBerries: 0
2016-08-07 20:33:15,730 [PokemonGoBot] [INFO] LuckyEgg: 3 | Incubator: 0 | TroyDisk: 1
2016-08-07 20:33:15,730 [PokemonGoBot] [INFO] Potion: 1 | SuperPotion: 2 | HyperPotion: 1
2016-08-07 20:33:15,730 [PokemonGoBot] [INFO] Incense: 0 | IncenseSpicy: 0 | IncenseCool: 0
2016-08-07 20:33:15,730 [PokemonGoBot] [INFO] Revive: 17 | MaxRevive: 0
2016-08-07 20:33:15,730 [PokemonGoBot] [INFO] 
2016-08-07 20:33:15,730 [PokemonGoBot] [INFO] 
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "/Users/JaydenHamence/PokemonGo-Bot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/Users/JaydenHamence/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 106, in call
    result = self._call()
  File "/Users/JaydenHamence/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "/Users/JaydenHamence/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "/Users/JaydenHamence/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(encrypt.so, 6): no suitable image found.  Did find:
	encrypt.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
(PokemonGo-Bot) Jaydens-Air:PokemonGo-Bot JaydenHamence$ 
### Other Information
OS: OSX

**Comment by tomalbrc** [comment]
Search on slack or google for the encrypt.so for OS X. I can email you the file if you want

**Comment by JaydenHamence** [comment]
@tomalbrc i have it but it says unknown file type see here 
OSError: dlopen(encrypt.so, 6): no suitable image found. Did find:
encrypt.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

**Comment by tomalbrc** [comment]
Those are my first 8 bytes: `0xCF 0xFA 0xED 0xFE 0x07 0x00 0x00 0x01`

**Comment by JaydenHamence** [comment]
any idea why it isnt working if its the right file?

**Comment by tomalbrc** [comment]
You probably have the wrong file (wrong architecture/os)

**Comment by JaydenHamence** [comment]
im on mac osx link to correct file?

**Comment by tomalbrc** [comment]
In here's a link #2746

**Comment by thisKeeWord** [comment]
it still doesn't work for me...
