### ISSUE TITLE
Bot start fails when running on linux

### ISSUE THREAD

**Issue by licklake** [PokemonGoF/PokemonGo-Bot#2765]
I know there are allready issues open with similar problems open, but maybe this helps:

```
(PokemonGo-Bot) root@XXX:~/pokemon-go/PokemonGo-Bot# ./run.sh
2016-08-07 13:04:37,498 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 13:04:37,500 [       cli] [INFO] Configuration initialized
2016-08-07 13:04:37,500 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more logrmation:
2016-08-07 13:04:37,500 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-07 13:04:37,504 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-07 13:04:37,534 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-07 13:04:37,534 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-07 13:04:37,534 [PokemonGoBot] [INFO] [location_found] Location found: 48.1202638, 11.5299126 (48.1202638, 11.5299126, 0.0)
2016-08-07 13:04:37,535 [PokemonGoBot] [INFO] [position_update] Now at (48.1202638, 11.5299126, 0)
2016-08-07 13:04:37,535 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-07 13:04:38,760 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-07 13:04:39,161 [PokemonGoBot] [INFO]
2016-08-07 13:04:39,161 [PokemonGoBot] [INFO] --- defunknown6 ---
2016-08-07 13:04:39,162 [PokemonGoBot] [INFO] Level: 1 (Next Level: 400 XP) (Total: 600 XP)
2016-08-07 13:04:39,162 [PokemonGoBot] [INFO] Pokemon Bag: 1/250
2016-08-07 13:04:39,162 [PokemonGoBot] [INFO] Items: 54/350
2016-08-07 13:04:39,162 [PokemonGoBot] [INFO] Stardust: 100 | Pokecoins: 0
2016-08-07 13:04:39,162 [PokemonGoBot] [INFO] PokeBalls: 50 | GreatBalls: 0 | UltraBalls: 0
2016-08-07 13:04:39,163 [PokemonGoBot] [INFO] RazzBerries: 0 | BlukBerries: 0 | NanabBerries: 0
2016-08-07 13:04:39,163 [PokemonGoBot] [INFO] LuckyEgg: 0 | Incubator: 0 | TroyDisk: 0
2016-08-07 13:04:39,163 [PokemonGoBot] [INFO] Potion: 0 | SuperPotion: 0 | HyperPotion: 0
2016-08-07 13:04:39,163 [PokemonGoBot] [INFO] Incense: 2 | IncenseSpicy: 0 | IncenseCool: 0
2016-08-07 13:04:39,163 [PokemonGoBot] [INFO] Revive: 0 | MaxRevive: 0
2016-08-07 13:04:39,163 [PokemonGoBot] [INFO]
2016-08-07 13:04:39,164 [PokemonGoBot] [INFO]
2016-08-07 13:04:39,196 [sentry.errors.serializer] [ERROR] maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/root/pokemon-go/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/serializer/manager.py", line 76, in transform
    return repr(value)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 372, in __repr__
    (self._handle & (_sys.maxint*2 + 1)),
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)

... (about 300 lines of the same output)

  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
RuntimeError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "/root/pokemon-go/PokemonGo-Bot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/root/pokemon-go/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 106, in call
    result = self._call()
  File "/root/pokemon-go/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "/root/pokemon-go/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "/root/pokemon-go/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: encrypt.so: cannot open shared object file: No such file or directory
2016-08-07 13:04:39,214 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/root/pokemon-go/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/root/pokemon-go/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/root/pokemon-go/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/root/pokemon-go/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/root/pokemon-go/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/root/pokemon-go/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/root/pokemon-go/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/root/pokemon-go/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 848, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-07 13:04:39,216 [sentry.errors.uncaught] [ERROR] [u'OSError: encrypt.so: cannot open shared object file: No such file or directory', u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", line 127, in main', u'  File "pokecli.py", line 136, in report_summary', u'  File "pokemongo_bot/metrics.py", line 76, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 106, in call', u'  File "pokemongo_bot/api_wrapper.py", line 63, in _call', u'  File "pgoapi/pgoapi.py", line 210, in call', u'  File "pgoapi/rpc_api.py", line 85, in activate_signature', u'  File "ctypes/__init__.py", line 443, in LoadLibrary', u'  File "ctypes/__init__.py", line 365, in __init__']

```
OS: debian 64 bit
Git Commit: ad6c21aa1dc0902c62e4001f9a81ce1fcd8a9f59
Python Version: Python 2.7.9

**Comment by larssy1** [comment]
Same on Windows 10 :)

**Comment by andrewwong2000** [comment]
You have to make the encrypt.so and edit __init.py to point to the local lib.

Download from here http://pgoapi.com/

**Comment by Corecrafts** [comment]
@andrewwong2000 can u explain this plz? im useing osx

**Comment by StarForser** [comment]
same problem

**Comment by kolet** [comment]
@andrewwong2000 
i did download 
and ran 

wget http://pgoapi.com/pgoencrypt.tar.gz && tar -xf pgoencrypt.tar.gz && cd pgoencrypt/src/ && make

and also download it from 

https://slack-files.com/T1U6G9ZEW-F1YV50RGQ-cc979942b7

put the libencrypt.so and encrypt.so on the main directory and same issue happen

**Comment by tomalbrc** [comment]
See #2746 for a link to encrypt.so for OS X 64bit.
Put in your main folder

**Comment by AutopsyMania** [comment]
@kolet I did the same and put encrypt.so under PokemonGo-Bot
Still have:
RuntimeError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "pokecli.py", line 501, in <module>
    main()
  File "pokecli.py", line 130, in main
    report_summary(bot)
  File "pokecli.py", line 139, in report_summary
    metrics.capture_stats()
  File "/home/eeijjmo/android/PokemonGo/PokemonGo-Bot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/home/eeijjmo/android/PokemonGo/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 106, in call
    result = self._call()
  File "/home/eeijjmo/android/PokemonGo/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "/home/eeijjmo/android/PokemonGo/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "/home/eeijjmo/android/PokemonGo/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: encrypt.so: cannot open shared object file: No such file or directory
2016-08-07 13:38:28,134 [sentry.errors] [ERROR] Sentry responded with an error: 'module' object has no attribute 'HTTPSHandler' (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/eeijjmo/android/PokemonGo/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/eeijjmo/android/PokemonGo/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/eeijjmo/android/PokemonGo/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 44, in urlopen
    class ValidHTTPSHandler(urllib2.HTTPSHandler):
AttributeError: 'module' object has no attribute 'HTTPSHandler'
2016-08-07 13:38:28,134 [sentry.errors.uncaught] [ERROR] [u'OSError: encrypt.so: cannot open shared object file: No such file or directory', u'  File "pokecli.py", line 501, in <module>', u'  File "pokecli.py", line 130, in main', u'  File "pokecli.py", line 139, in report_summary', u'  File "pokemongo_bot/metrics.py", line 76, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 106, in call', u'  File "pokemongo_bot/api_wrapper.py", line 63, in _call', u'  File "pgoapi/pgoapi.py", line 210, in call', u'  File "pgoapi/rpc_api.py", line 85, in activate_signature', u'  File "ctypes/__init__.py", line 443, in LoadLibrary', u'  File "ctypes/__init__.py", line 365, in __init__']

**Comment by licklake** [comment]
Did this all but still get the same error... maybe it has something to do with:

`[ERROR] maximum recursion depth exceeded while calling a Python object`

**Comment by licklake** [comment]
the solution of "ErrorFlexXx" in #2769 fixed it!

**Comment by kolet** [comment]
@ErrorFlexXx @tomalbrc 
thanks alot to u  2

here a full fix

ok listen up what u have to do
if u are on linnux or mac

Basically you need to rename the libencrypt.so file the makefile outputs to encrypt.so and copy it to your main folder

Run: wget http://pgoapi.com/pgoencrypt.tar.gz && tar -xf pgoencrypt.tar.gz && cd pgoencrypt/src/ && make && mv libencrypt.so encrypt.so

Then copy encrypt.so into your bots main folder.

if that does not work
edit
in PokemonGo-Bot/pokemongo_bot edit the file `__init__.py` and replace this
self.api.activate_signature("encrypt.so")
with this
encrypt_path = os.path.abspath("./encrypt.so")
self.api.activate_signature(encrypt_path)
Regards

like i did here, i commet #self.api.activate_signature("encrypt.so") and add  
        encrypt_path = os.path.abspath("./encrypt.so")
        self.api.activate_signature(encrypt_path)
http://image.prntscr.com/image/4fc363635d404637b6c3e797cfa13306.png

**Comment by k4n30** [comment]
#2768
