### ISSUE TITLE
Error when starting!

### ISSUE THREAD

**Issue by crilleaz** [PokemonGoF/PokemonGo-Bot#2782]
(PokemonGo-Bot) root@serverx:/home/poke/PokemonGo-Bot# ./run.sh
2016-08-07 13:57:17,887 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 13:57:17,890 [       cli] [INFO] Configuration initialized
2016-08-07 13:57:17,890 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more logrmation:
2016-08-07 13:57:17,890 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-07 13:57:17,901 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-07 13:57:17,939 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "/home/poke/PokemonGo-Bot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/home/poke/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 90, in call
    if not self.can_call():
  File "/home/poke/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 54, in can_call
    raise NoPlayerPositionSetException()
pgoapi.exceptions.NoPlayerPositionSetException
2016-08-07 13:57:17,997 [sentry.errors] [ERROR] Sentry responded with an error: 'module' object has no attribute 'HTTPSHandler' (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/poke/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/poke/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/poke/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 44, in urlopen
    class ValidHTTPSHandler(urllib2.HTTPSHandler):
AttributeError: 'module' object has no attribute 'HTTPSHandler'
2016-08-07 13:57:17,998 [sentry.errors.uncaught] [ERROR] [u'NoPlayerPositionSetException', u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", line 127, in main', u'  File "pokecli.py", line 136, in report_summary', u'  File "pokemongo_bot/metrics.py", line 76, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 90, in call', u'  File "pokemongo_bot/api_wrapper.py", line 54, in can_call']
(PokemonGo-Bot) root@serverx:/home/poke/PokemonGo-Bot#

All the depencies are installed, whats wrong?

**Comment by Projectnsb** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2777
