### ISSUE TITLE
[Error126] Module not found- windows OS issue

### ISSUE THREAD

**Issue by reside** [PokemonGoF/PokemonGo-Bot#2785]
### Expected Behavior
Can launch bot

### Actual Behavior
On windows OS throws:

> Traceback (most recent call last):
  File "C:\Users\Kert\Desktop\PokemonGo-Bot-dev\PokemonGo-Bot-dev\pokecli.py", line 501, in <module>
    main()
  File "C:\Users\Kert\Desktop\PokemonGo-Bot-dev\PokemonGo-Bot-dev\pokecli.py", line 130, in main
    report_summary(bot)
  File "C:\Users\Kert\Desktop\PokemonGo-Bot-dev\PokemonGo-Bot-dev\pokecli.py", line 139, in report_summary
    metrics.capture_stats()
  File "C:\Users\Kert\Desktop\PokemonGo-Bot-dev\PokemonGo-Bot-dev\pokemongo_bot\metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "C:\Users\Kert\Desktop\PokemonGo-Bot-dev\PokemonGo-Bot-dev\pokemongo_bot\api_wrapper.py", line 106, in call
    result = self._call()
  File "C:\Users\Kert\Desktop\PokemonGo-Bot-dev\PokemonGo-Bot-dev\pokemongo_bot\api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "c:\users\kert\desktop\pokemongo-bot-dev\pokemongo-bot-dev\src\pgoapi\pgoapi\pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "c:\users\kert\desktop\pokemongo-bot-dev\pokemongo-bot-dev\src\pgoapi\pgoapi\rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

### Steps to Reproduce
Run pokecli.py on windows 10

### Other Information
Was working ok with old API

**Comment by tomalbrc** [comment]
#2780
