### ISSUE TITLE
Error with locations

### ISSUE THREAD

**Issue by crilleaz** [PokemonGoF/PokemonGo-Bot#2789]
(PokemonGo-Bot) root@serverx:/home/poke/PokemonGo-Bot# ./run.sh
2016-08-07 14:23:09,216 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 14:23:09,220 [       cli] [INFO] Configuration initialized
2016-08-07 14:23:09,224 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "/home/poke/PokemonGo-Bot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/home/poke/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 90, in call
    if not self.can_call():
  File "/home/poke/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 54, in can_call
    raise NoPlayerPositionSetException()
pgoapi.exceptions.NoPlayerPositionSetException
(PokemonGo-Bot) root@serverx:/home/poke/PokemonGo-Bot#

Config.json:
    "location": "xx,xxxxxx,xx,xxxxxx",

**Comment by crilleaz** [comment]
Anyone?

**Comment by tomalbrc** [comment]
Change `,` to `.`
`"location": "xx,xxxxxx,xx,xxxxxx",`
to
`"location": "xx.xxxxxx,xx.xxxxxx",`

**Comment by crilleaz** [comment]
2016-08-07 14:37:48,540 [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "/home/poke/PokemonGo-Bot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/home/poke/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 90, in call
    if not self.can_call():
  File "/home/poke/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 58, in can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException


They just keep coming..

**Comment by Anby29** [comment]
I have the same problem. I tried to change my location, but that change nothing.

2016-08-07 18:03:13,197 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 18:03:13,197 [       cli] [INFO] Configuration initialized
2016-08-07 18:03:13,213 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "C:\Users\Olivier\PokemonGo-Bot\pokemongo_bot\metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "C:\Users\Olivier\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 90, in call
    if not self.can_call():
  File "C:\Users\Olivier\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 54, in can_call
    raise NoPlayerPositionSetException()
pgoapi.exceptions.NoPlayerPositionSetException
