### ISSUE TITLE
Exchanging Crash

### ISSUE THREAD

**Issue by Zeper666** [PokemonGoF/PokemonGo-Bot#279]
### Expected Behavior
exchanging a low CP pokemon

### Actual Behavior
Crash

### Steps to Reproduce
found a low CP pokemon and the bot crash

### Other Information
OS: win10 x64

```
[x] PokemonGO Bot v1.0
[x] Configuration initialized

[x] Address found: 48.842606,2.360102
[x] Position in-game set as: (48.8424039, 2.3599706, 0.0)

[#]
[#] Username: Ekibunnel
[#] Acccount Creation: 2016-07-08 02:08:55.821000
[#] Bag Storage: 348/350
[#] Pokemon Storage: 187/250
[#] Stardust: 19811
[#] Pokecoins: 30
[#] -- Level: 14
[#] -- Experience: 89554
[#] -- Experience until next level: 10446
[#] -- Pokemon Captured: 222
[#] -- Pokestops Visited: 372
[#]
[x] Starting PokemonGo Bot....
[#] Scanning area for objects (1 / 25)
[#] Walking from (48.8424039, 2.3599706) to (48.8424039, 2.3599706) for approx. 0.0 seconds
[#] Finished walking
[#] (48.8424039, 2.3599706, 0)
Found fort 03a51848ad3e4d40aa121ea0d11ccf77.16 at distance 462.390442177m
Need to move closer to Pokestop
[#] Walking from (48.8424039, 2.3599706) to (48.841575, 2.353779) for approx. 185.0 seconds
[#] Something rustles nearby!
[#] A Wild Rattata appeared! [CP 10]
[x] Using Pokeball...
[x] Captured Rattata! [CP 10] - exchanging for candy
Traceback (most recent call last):
  File "pokecli.py", line 107, in <module>
    main()
  File "pokecli.py", line 104, in main
    bot.take_step()
  File "C:\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 31, in take_step
    self.stepper.take_step()
  File "C:\PokemonGo-Bot-dev\pokemongo_bot\stepper.py", line 58, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "C:\PokemonGo-Bot-dev\pokemongo_bot\stepper.py", line 100, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "C:\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 52, in work_on_cell
    hack_chain = worker.work()
  File "C:\PokemonGo-Bot-dev\pokemongo_bot\cell_workers\seen_fort_worker.py", line 35, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "C:\PokemonGo-Bot-dev\pokemongo_bot\stepper.py", line 79, in _walk_to
    self._work_at_position(i2f(self.api._position_lat), i2f(self.api._position_lng), alt, False)
  File "C:\PokemonGo-Bot-dev\pokemongo_bot\stepper.py", line 100, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "C:\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 38, in work_on_cell
    worker.work()
  File "C:\PokemonGo-Bot-dev\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 86, in work
    self.transfer_pokemon(list(Set(id_list2) - Set(id_list1)))
NameError: global name 'id_list1' is not defined

```

**Comment by emhtiwedir** [comment]
This situation occurs with me as well. Lastest dev pull, turned off exchanging of pokemon and it works.

**Comment by Razapo** [comment]
A new commit was pushed roughly an hour ago which fixes it.

**Comment by emhtiwedir** [comment]
Thought I had that one, will go ahead and git pull

**Comment by douglascamata** [comment]
you're running old code, pull from dev again, this was fixed already

**Comment by douglascamata** [comment]
that line of code isn't even on line 86 anymore
