### ISSUE TITLE
ImportError: No module named 'cell_workers'

### ISSUE THREAD

**Issue by CoderFX** [PokemonGoF/PokemonGo-Bot#2794]
### Expected Behavior
Start bot

### Actual Behavior
Traceback (most recent call last):
  File ".\pokecli.py", line 41, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "G:\Pokemon\PokemonGo-Bot\pokemongo_bot\__init__.py", line 17, in <module>
    import cell_workers
**ImportError: No module named 'cell_workers'**

### Steps to Reproduce
> pip install -r requirements.txt
> python .\pokecli.py

### Other Information
OS: Win`10
Version: Dev
Python Version: Python 3.5.1

How to fix this?

**Comment by tomalbrc** [comment]
is python 3 supported? Try with python 2.7

**Comment by CoderFX** [comment]
@tomalbrc 
it worked before

**Comment by tomalbrc** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation says 2.7.x is required

**Comment by brantje** [comment]
This bot runs on Python 2.7, not python 3 (yet?)
