### ISSUE TITLE
Error when Login Procedure starts

### ISSUE THREAD

**Issue by crilleaz** [PokemonGoF/PokemonGo-Bot#2796]
(PokemonGo-Bot) root@serverx:/home/poke/PokemonGo-Bot# ./run.sh
2016-08-07 14:37:48,531 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 14:37:48,535 [       cli] [INFO] Configuration initialized
2016-08-07 14:37:48,539 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-07 14:37:48,539 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-07 14:37:48,539 [PokemonGoBot] [INFO] [location_found] Location found: 59.371257,16.509994 (59.371257, 16.509994, 0.0)
2016-08-07 14:37:48,539 [PokemonGoBot] [INFO] [position_update] Now at (59.371257, 16.509994, 0)
2016-08-07 14:37:48,540 [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "/home/poke/PokemonGo-Bot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/home/poke/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 90, in call
    if not self.can_call():
  File "/home/poke/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 58, in can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
(PokemonGo-Bot) root@serverx:/home/poke/PokemonGo-Bot#

    "auth_service": "google",
    "username": "xxxxxx@gmail.com",
    "password": "xxxxxxx",

**Comment by brantje** [comment]
You have too update your pgoapi. `pip install --upgrade -r requirements.txt`

**Comment by helmut1337** [comment]
For some reason I'm getting this error now too.
The bot worked like a charm for like 2-3 hours..now I get this error with every account.
Tried Location Changes / IP Changes..

**Comment by crilleaz** [comment]
Still not working...
