### ISSUE TITLE
Got errors running pokecli.py. (master branch)

### ISSUE THREAD

**Issue by Anyrainel** [PokemonGoF/PokemonGo-Bot#281]
### Actual Behavior
I encountered an error like this:
```
python2 pokecli.py -a google -u tejado -p 1234 --location "New York, Washington Square"
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from bot import PokemonGoBot
  File "/Users/Vanilain/Files/PokemonGo-Bot/bot.py", line 8, in <module>
    from pgoapi import PGoApi
  File "/Users/Vanilain/Files/PokemonGo-Bot/pgoapi/__init__.py", line 1, in <module>
    from pgoapi      import *
  File "/Users/Vanilain/Files/PokemonGo-Bot/pgoapi/pgoapi.py", line 33, in <module>
    from rpc_api import RpcApi
  File "/Users/Vanilain/Files/PokemonGo-Bot/pgoapi/rpc_api.py", line 33, in <module>
    from protobuf_to_dict import protobuf_to_dict
  File "/usr/local/lib/python2.7/site-packages/protobuf_to_dict.py", line 2, in <module>
    from google.protobuf.descriptor import FieldDescriptor
  File "/usr/local/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 50, in <module>
    from google.protobuf.pyext import _message
AttributeError: 'module' object has no attribute 'MutableMapping'
[1]    70335 segmentation fault  python2 pokecli.py -a google -u tejado -p 1234 --location

```

I'm new to PokemonGo-Bot, and I installed as in the instructions. Also with my own google account, it'll give the exact same error.
I tried to resolve this issue by upgrading protobuf to 3.0.0b4, which results in another error:

```
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from bot import PokemonGoBot
  File "/Users/Vanilain/Files/PokemonGo-Bot/bot.py", line 8, in <module>
    from pgoapi import PGoApi
  File "/Users/Vanilain/Files/PokemonGo-Bot/pgoapi/__init__.py", line 1, in <module>
    from pgoapi      import *
  File "/Users/Vanilain/Files/PokemonGo-Bot/pgoapi/pgoapi.py", line 33, in <module>
    from rpc_api import RpcApi
  File "/Users/Vanilain/Files/PokemonGo-Bot/pgoapi/rpc_api.py", line 33, in <module>
    from protobuf_to_dict import protobuf_to_dict
  File "/usr/local/lib/python2.7/site-packages/protobuf_to_dict.py", line 2, in <module>
    from google.protobuf.descriptor import FieldDescriptor
  File "/usr/local/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 701, in <module>
    class ServiceDescriptor(_NestedDescriptorBase):
  File "/usr/local/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 720, in ServiceDescriptor
    _C_DESCRIPTOR_CLASS = _message.ServiceDescriptor
AttributeError: 'module' object has no attribute 'ServiceDescriptor'
```
Now I reinstalled protobuf to 2.6.1 as in requirements, and the former error stopped me from doing anything else. Could someone help me?

### Other Information
OS: OS X El Capitan

**Comment by deathcoderz** [comment]
wasnt it protobuf 3.0.0b something?

**Comment by aTadTasty** [comment]
you gotta add `--ignore-installed six` into your command

**Comment by surfaace** [comment]
master branch closed, use stable or dev
