### ISSUE TITLE
Bot only moves and doing nothing after some time

### ISSUE THREAD

**Issue by oalmali** [PokemonGoF/PokemonGo-Bot#2813]
### Expected Behavior
Bot collects Pokemon and spins Pokestops correctly.

### Actual Behavior
It only works for a while (like ten minutes) then it hangs and always tries to approach forts. Logs are looking like:

```
2016-08-07 17:00:10,207 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-07 17:00:10,208 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort Olmec Head (7d2c87fd6e3140d7b675393cc3166098.16)
2016-08-07 17:00:15,989 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop New York Times Time Capsule - 0.06km (attraction of lure 0.06km)
2016-08-07 17:00:18,610 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort Megaloceros (caafeea89acf44d59291129613a18c12.16)
2016-08-07 17:00:24,117 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop New York Times Time Capsule - 0.05km (attraction of lure 0.05km)
2016-08-07 17:00:27,890 [  SpinFort] [INFO] [pokestop_out_of_range] Pokestop New York Times Time Capsule out of range.
2016-08-07 17:00:27,890 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-07 17:00:27,892 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort Megaloceros (caafeea89acf44d59291129613a18c12.16)
2016-08-07 17:00:33,267 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop The Galactic Armillary - 0.06km (attraction of lure 0.06km)
2016-08-07 17:00:36,158 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort New York Times Time Capsule (ed20ad2072fd4345825207b8879b0eb8.12)
2016-08-07 17:00:41,547 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop The Galactic Armillary - 0.05km (attraction of lure 0.05km)
2016-08-07 17:00:44,572 [  SpinFort] [INFO] [pokestop_out_of_range] Pokestop The Galactic Armillary out of range.
2016-08-07 17:00:44,572 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-07 17:00:44,574 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort New York Times Time Capsule (ed20ad2072fd4345825207b8879b0eb8.12)
2016-08-07 17:00:49,948 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Theodore Roosevelt Park West Side Entrance - 0.08km (attraction of lure 0.08km)
2016-08-07 17:00:52,720 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort New York Times Time Capsule (ed20ad2072fd4345825207b8879b0eb8.12)
2016-08-07 17:00:58,090 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Theodore Roosevelt Park West Side Entrance - 0.07km (attraction of lure 0.07km)
2016-08-07 17:01:01,976 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort New York Times Time Capsule (ed20ad2072fd4345825207b8879b0eb8.12)
2016-08-07 17:01:07,363 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Theodore Roosevelt Park West Side Entrance - 0.06km (attraction of lure 0.06km)
2016-08-07 17:01:10,206 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort The Galactic Armillary (9836322a9da64e6ea0501d1895d96d25.16)
2016-08-07 17:01:15,575 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Theodore Roosevelt Park West Side Entrance - 0.04km (attraction of lure 0.04km)
2016-08-07 17:01:18,699 [  SpinFort] [INFO] [pokestop_out_of_range] Pokestop Theodore Roosevelt Park West Side Entrance out of range.
2016-08-07 17:01:18,699 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-07 17:01:18,700 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort Theodore Roosevelt Park West Side Entrance (f7b823423fa14d2689722784290d9df4.16)
2016-08-07 17:01:24,083 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Arthur Ross Terrace - 0.08km (attraction of lure 0.09km)
2016-08-07 17:01:26,472 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort The Galactic Armillary (9836322a9da64e6ea0501d1895d96d25.16)
2016-08-07 17:01:31,823 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Arthur Ross Terrace - 0.07km (attraction of lure 0.08km)
2016-08-07 17:01:35,032 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort The Galactic Armillary (9836322a9da64e6ea0501d1895d96d25.16)
2016-08-07 17:01:40,410 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Arthur Ross Terrace - 0.05km (attraction of lure 0.07km)
2016-08-07 17:01:43,403 [  SpinFort] [INFO] [pokestop_out_of_range] Pokestop Arthur Ross Terrace out of range.
2016-08-07 17:01:43,403 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-07 17:01:43,404 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort The Galactic Armillary (9836322a9da64e6ea0501d1895d96d25.16)
2016-08-07 17:01:48,840 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop AMNH - The Educational Travel - 0.06km (attraction of lure 0.06km)
2016-08-07 17:01:51,641 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort The Galactic Armillary (9836322a9da64e6ea0501d1895d96d25.16)
2016-08-07 17:01:56,986 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop AMNH - The Educational Travel - 0.04km (attraction of lure 0.04km)
2016-08-07 17:02:00,245 [  SpinFort] [INFO] [pokestop_out_of_range] Pokestop AMNH - The Educational Travel out of range.
2016-08-07 17:02:00,245 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.

```

### Steps to Reproduce
Part of `config.json` is like:

 "location": "40.782735, -73.965763",
      "tasks": [
        {
          "type": "HandleSoftBan"
        },
        {
          "type": "CollectLevelUpReward"
        },
        {
          "type": "IncubateEggs",
          "config": {
            "longer_eggs_first": true
          }
        },
        {
          "type": "TransferPokemon"
        },
        {
          "type": "EvolvePokemon",
          "config": {
              "evolve_all": "none",
              "first_evolve_by": "cp",
              "evolve_above_cp": 500,
              "evolve_above_iv": 0.8,
              "logic": "or",
              "evolve_speed": 20,
              "use_lucky_egg": true
          }
        },
        {
          "type": "RecycleItems",
          "config": {
            "item_filter": {
              "Pokeball":       { "keep" : 200 },
              "Potion":         { "keep" : 1 },
              "Super Potion":   { "keep" : 1 },
              "Hyper Potion":   { "keep" : 30 },
              "Revive":         { "keep" : 1 },
              "Razz Berry":     { "keep" : 50 }
            }
          }
        },
        {
          "type": "CatchVisiblePokemon"
        },
        {
          "type": "SpinFort"
        },
	{
     	 "type": "CatchLuredPokemon"
    	},
        {
          "type": "MoveToFort"
        },
        {
          "type": "FollowSpiral",
          "config": {
            "diameter": 4,
            "step_size": 70
          }
        }
      ],
      "map_object_cache_time": 5,
      "forts": {
        "avoid_circles": true,
        "max_circle_size": 50
      },

### Other Information
OS:  OSX
Git Commit: 5941cd76fcc498c061ea47d13c365da0c86109b6
Python Version: 2.7

**Comment by sffetlio** [comment]
Same here, restart fixes it temporarily.

**Comment by g0wfv** [comment]
There seems to be something crashing which creates this ...

```
2016-08-07 15:01:01,978 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Poliwag appeared! [CP 436] [Potential 0.38] [S/A/D 4/8/5]
2016-08-07 15:01:05,608 [PokemonCatchWorker] [INFO] [threw_pokeball] Used Greatball, with chance 42.96 (1 left)
2016-08-07 15:01:06,356 [PokemonCatchWorker] [INFO] [pokemon_caught] Captured Poliwag! [CP 436] [Potential 0.38] [4/8/5] [+210 exp]
2016-08-07 15:01:11,745 [  SpinFort] [INFO] [spun_pokestop] Spun pokestop Lincolnshire Echo. Experience awarded: 100. Items awarded: {u'Razz Berry': 1, u'Potion': 1, u'Pokeball': 3, u'Revive': 2}
2016-08-07 15:01:14,138 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Brayford's Wildlife - 0.04km (attraction of lure 0.11km)
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file __init__.py, line 550
2016-08-07 15:01:21,886 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-07 15:01:23,533 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-07 15:01:23,535 [IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 1.53 km
2016-08-07 15:01:23,935 [TransferPokemon] [INFO] [keep_best_release] Keeping best 2 Poliwag, based on cp and iv
2016-08-07 15:01:24,352 [TransferPokemon] [INFO] [pokemon_release] Exchanged Poliwag [CP 436] [IV 0.38] for candy.
2016-08-07 15:01:27,557 [RecycleItems] [INFO] [item_discarded] Discarded 3x Pokeball (maximum 50).
2016-08-07 15:01:27,913 [RecycleItems] [INFO] [item_discarded] Discarded 1x Potion (maximum 5).
2016-08-07 15:01:28,314 [RecycleItems] [INFO] [item_discarded] Discarded 2x Revive (maximum 5).
2016-08-07 15:01:28,680 [  SpinFort] [INFO] [pokestop_out_of_range] Pokestop Brayford's Wildlife out of range.
2016-08-07 15:01:28,680 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-07 15:01:29,000 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Brayford Waterfront - 0.10km (attraction of lure 0.10km)
2016-08-07 15:01:31,266 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Brayford Waterfront - 0.08km (attraction of lure 0.08km)
2016-08-07 15:01:33,482 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Brayford Waterfront - 0.06km (attraction of lure 0.06km)
2016-08-07 15:01:36,106 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort Brayford Waterfront (c3e8f778dd5647ffbebfe8e5957b5e5e.16)
2016-08-07 15:01:41,492 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Brayford Waterfront - 0.04km (attraction of lure 0.04km)
2016-08-07 15:01:44,003 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort Brayford Waterfront (c3e8f778dd5647ffbebfe8e5957b5e5e.16)
2016-08-07 15:01:50,008 [  SpinFort] [INFO] [pokestop_out_of_range] Pokestop Brayford Waterfront out of range.
2016-08-07 15:01:50,008 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-07 15:01:50,435 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Brayford Pool Maps - 0.10km (attraction of lure 0.10km)
```

**Comment by htugsdr** [comment]
similar issue i have set these values like so but it still hasnt made a difference and it still does nothing after about 4 minutes
`"type": "MoveToFort",
        "config": {
            "lure_attraction": false,
            "lure_max_distance": 0`

**Comment by Gandaflux** [comment]
That config is not working, since usage is commented in code.

**Comment by brantje** [comment]
Should be fixed now

**Comment by g0wfv** [comment]
What was the fix??

I've had a look through what was going on, and I've a sneaky suspicion it's related to #2720??

**Comment by scarfield** [comment]
for me, the fix was editing __init__.py, Find this line: "self.login()"
Then add this below:

 self.api.activate_signature("encrypt.so") (or path to wherever your encrypt file is)

**Comment by brantje** [comment]
Fixed in latest developments.

**Comment by brantje** [comment]
Dev. Damn auto correct

**Comment by firzzen** [comment]
@brantje is the latest fix in dev supposed to place the encrypt.so file in the bot root directory as well? If so then it doesn't do it for me. When launching just gives:

 2016-08-07 19:18:52,264 [PokemonGoBot] [ERROR] encrypt.so is not found! Please place it in the bots root directory.

The fix is obvious but just wondering if it should be doing it or not.

**Comment by JarodKY** [comment]
@scarfield Which instance of "self.login()"?

The first one is:


            if remaining_time < 60:
                self.logger.info("Session stale, re-logging in", 'yellow')
                position = self.position
                self.api = ApiWrapper()
                self.position = position
                self.login()

And the second one is:


        # provide player position on the earth
        self._set_starting_position()

        self.login()

**Comment by scarfield** [comment]
First one. Mine is:
` if remaining_time < 60:
                self.logger.info("Session stale, re-logging in", 'yellow')
                position = self.position
                self.api = ApiWrapper()
                self.position = position
                self.login()
                self.api.activate_signature("encrypt.so")
`

**Comment by JarodKY** [comment]
Thank you, I just started it back up. I'll update this post if it works or not.

**Comment by firzzen** [comment]
I'm running on dev now for about 15 minutes, so far working fine. No luredfort errors or anything. Will update if i catch an error or in about an hour if all good.

**Comment by firzzen** [comment]
@oalmali For me this works perfectly fine now after pulling the dev branch and setting it up properly. Imo could close this.

**Comment by sinthu94** [comment]
@firzzen is the bot also catching pokemons?

**Comment by firzzen** [comment]
@sinthu94 yes all works fine after i cloned the latest dev.

**Comment by oalmali** [comment]
@firzzen sorry for late response I was traveling. I am executing script with the latest version dev branch, going to update issue soon.

**Comment by firzzen** [comment]
@oalmali no need to be sorry for anything. All working well for me now after pulling latest dev.
