### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lPLcCp/protobuf-to-dict/

### ISSUE THREAD

**Issue by jcoinas** [PokemonGoF/PokemonGo-Bot#2820]
Relevant info:
**os : raspbian
python 2.7.9
pip 8.1.2
virtualenv 15.0.3**

(PokemonGo-Bot) root@unamedDevice:/home/k0sh/pokemon/PokemonGo-Bot# apt-get install python-protobuf
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-protobuf is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
(PokemonGo-Bot) root@unamedDevice:/home/k0sh/pokemon/PokemonGo-Bot# pip install -r requirements.txt
Collecting numpy==1.11.0 (from -r requirements.txt (line 1))
  Using cached numpy-1.11.0.tar.gz
Collecting networkx==1.11 (from -r requirements.txt (line 2))
  Using cached networkx-1.11-py2.py3-none-any.whl
Obtaining pgoapi from git+https://github.com/keyphact/pgoapi.git@249d3be7fbbdabc7f9adea17cbc899d6549e47a2#egg=pgoapi (from -r requirements.txt (line 3))
  Skipping because already up-to-date.
Collecting geopy==1.11.0 (from -r requirements.txt (line 4))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf==3.0.0b4 (from -r requirements.txt (line 5))
  Using cached protobuf-3.0.0b4-py2.py3-none-any.whl
Collecting requests==2.10.0 (from -r requirements.txt (line 6))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 7))
  Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 8))
  Using cached gpsoauth-0.3.0.tar.gz
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 9))
  Using cached protobuf-to-dict-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:

    Installed /tmp/pip-build-lPLcCp/protobuf-to-dict/.eggs/nosexcover-1.0.10-py2.7.egg
    Searching for coverage
    Reading https://pypi.python.org/simple/coverage/
    Download error on https://pypi.python.org/simple/coverage/: [Errno 104] Connection reset by peer -- Some packages may not be found!
    Couldn't find index page for 'coverage' (maybe misspelled?)
    Scanning index of all packages (this may take a while)
    Reading https://pypi.python.org/simple/
    Download error on https://pypi.python.org/simple/: [Errno 104] Connection reset by peer -- Some packages may not be found!
    No local packages or working download links found for coverage
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lPLcCp/protobuf-to-dict/setup.py", line 25, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/k0sh/pokemon/PokemonGo-Bot/local/lib/python2.7/site-packages/setuptools/dist.py", line 348, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/k0sh/pokemon/PokemonGo-Bot/local/lib/python2.7/site-packages/setuptools/dist.py", line 394, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/k0sh/pokemon/PokemonGo-Bot/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/k0sh/pokemon/PokemonGo-Bot/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1098, in best_match
        return self.obtain(req, installer)
      File "/home/k0sh/pokemon/PokemonGo-Bot/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1110, in obtain
        return installer(requirement)
      File "/home/k0sh/pokemon/PokemonGo-Bot/local/lib/python2.7/site-packages/setuptools/dist.py", line 461, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/k0sh/pokemon/PokemonGo-Bot/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 658, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('coverage')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lPLcCp/protobuf-to-dict/

**Comment by BobbyWibowo** [comment]
```
Download error on https://pypi.python.org/simple/coverage/: [Errno 104] Connection reset by peer -- Some packages may not be found!
Download error on https://pypi.python.org/simple/: [Errno 104] Connection reset by peer -- Some packages may not be found!
No local packages or working download links found for coverage
```
Doesn't that mean that it couldn't connect to any of the links above, thus couldn't download the necessary files?

**Comment by jcoinas** [comment]
It means but the thing is that I can access the links.

**Comment by longnalou** [comment]
`Long-Nalou:PokemonGo-Bot LongNguyen$ clear 

Long-Nalou:PokemonGo-Bot LongNguyen$ sudo -H pip install -r requirements.txt
Collecting numpy==1.11.0 (from -r requirements.txt (line 1))
  Using cached numpy-1.11.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting networkx==1.11 (from -r requirements.txt (line 2))
  Using cached networkx-1.11-py2.py3-none-any.whl
Obtaining pgoapi from git+https://github.com/keyphact/pgoapi.git@249d3be7fbbdabc7f9adea17cbc899d6549e47a2#egg=pgoapi (from -r requirements.txt (line 3))
  Skipping because already up-to-date.
Collecting geopy==1.11.0 (from -r requirements.txt (line 4))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf==3.0.0b4 (from -r requirements.txt (line 5))
  Using cached protobuf-3.0.0b4-py2.py3-none-any.whl
Collecting requests==2.10.0 (from -r requirements.txt (line 6))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 7))
  Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 8))
  Using cached gpsoauth-0.3.0.tar.gz
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 9))
  Using cached protobuf-to-dict-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    
    Installed /private/tmp/pip-build-Yhf6SS/protobuf-to-dict/nosexcover-1.0.10-py2.7.egg
    Searching for coverage
    Reading https://pypi.python.org/simple/coverage/
    Best match: coverage 4.2
    Downloading https://pypi.python.org/packages/f5/47/2e39972c41eb988d551bb2da25c4ee16ea78492ec1b6ffdf09f50cd09b92/coverage-4.2.zip#md5=9841c9e1ddc862144fda3fd7e5ba5106
    Processing coverage-4.2.zip
    Writing /tmp/easy_install-Q9IfQD/coverage-4.2/setup.cfg
    Running coverage-4.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Q9IfQD/coverage-4.2/egg-dist-tmp-KCz6cF
    warning: no previously-included files found matching 'ci/appveyor.token'
    no previously-included directories found matching 'doc/_build'
    no previously-included directories found matching 'tests/eggsrc/build'
    no previously-included directories found matching 'tests/eggsrc/dist'
    no previously-included directories found matching 'tests/eggsrc/*.egg-info'
    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
    
    Installed /private/tmp/pip-build-Yhf6SS/protobuf-to-dict/coverage-4.2-py2.7-macosx-10.11-intel.egg
    Searching for nose>=1.0
    Reading https://pypi.python.org/simple/nose/
    Best match: nose 1.3.7
    Downloading https://pypi.python.org/packages/58/a5/0dc93c3ec33f4e281849523a5a913fa1eea9a3068acfa754d44d88107a44/nose-1.3.7.tar.gz#md5=4d3ad0ff07b61373d2cefc89c5d0b20b
    Processing nose-1.3.7.tar.gz
    Writing /tmp/easy_install-MvI8DS/nose-1.3.7/setup.cfg
    Running nose-1.3.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-MvI8DS/nose-1.3.7/egg-dist-tmp-dKj45m
    no previously-included directories found matching 'doc/.build'
    
    Installed /private/tmp/pip-build-Yhf6SS/protobuf-to-dict/nose-1.3.7-py2.7.egg
    Searching for protobuf>=2.3.0
    Reading https://pypi.python.org/simple/protobuf/
    Best match: protobuf 3.0.0
    Downloading https://pypi.python.org/packages/e7/ff/df198f342f1b6e71be00a4601973297c0399f112327e8d5e48595ba95fe9/protobuf-3.0.0-py2.7.egg#md5=a2aa47b202784121a3d8ea17daee5e25
    Processing protobuf-3.0.0-py2.7.egg
    creating /private/tmp/pip-build-Yhf6SS/protobuf-to-dict/protobuf-3.0.0-py2.7.egg
    Extracting protobuf-3.0.0-py2.7.egg to /private/tmp/pip-build-Yhf6SS/protobuf-to-dict
    
    Installed /private/tmp/pip-build-Yhf6SS/protobuf-to-dict/protobuf-3.0.0-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-Yhf6SS/protobuf-to-dict/setup.py", line 25, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 263, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 580, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (six 1.4.1 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('six>=1.9'))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-Yhf6SS/protobuf-to-dict/`

I have the same issue. Pleas help me

**Comment by eclecticmiraclecat** [comment]
pip install --upgrade six

**Comment by eclecticmiraclecat** [comment]
pip install --upgrade six

**Comment by mondalamit** [comment]
protobuf_dict has a conflict with the package "six": https://github.com/benhodgson/protobuf-to-dict/issues/12

sudo pip uninstall six, and I could successfully install from there.

**Comment by 3kynox** [comment]
This helped here too, tks

**Comment by carlosgino** [comment]
root@LAPTOP-98SB3UC8:~# pip install pandas
Downloading/unpacking pandas
  Downloading pandas-0.20.1.tar.gz (10.3MB): 10.3MB downloaded
  Running setup.py (path:/tmp/pip_build_root/pandas/setup.py) egg_info for package pandas
    Running from numpy source directory.
    /tmp/easy_install-jIuiOc/numpy-1.13.0rc1/setup.py:367: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    /tmp/easy_install-jIuiOc/numpy-1.13.0rc1/numpy/distutils/system_info.py:572: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    /tmp/easy_install-jIuiOc/numpy-1.13.0rc1/numpy/distutils/system_info.py:572: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      self.calc_info()
    /tmp/easy_install-jIuiOc/numpy-1.13.0rc1/numpy/distutils/system_info.py:572: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      self.calc_info()
    /bin/sh: 1: svnversion: not found
    /bin/sh: 1: svnversion: not found
    /tmp/easy_install-jIuiOc/numpy-1.13.0rc1/numpy/distutils/system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    /tmp/easy_install-jIuiOc/numpy-1.13.0rc1/numpy/distutils/system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    non-existing path in 'numpy/distutils': 'site.cfg'
    Could not locate executable gfortran
    Could not locate executable f95
    Could not locate executable ifort
    Could not locate executable ifc
    Could not locate executable lf95
    Could not locate executable pgfortran
    Could not locate executable f90
    Could not locate executable f77
    Could not locate executable fort
    Could not locate executable efort
    Could not locate executable efc
    Could not locate executable g77
    Could not locate executable g95
    Could not locate executable pathf95
    don't know how to compile Fortran code on platform 'posix'
    _configtest.c:1:5: warning: conflicting types for built-in function ‘exp’ [enabled by default]
     int exp (void);
         ^
    _configtest.o: En la función `main':
    /tmp/easy_install-jIuiOc/numpy-1.13.0rc1/_configtest.c:6: referencia a `exp' sin definir
    collect2: error: ld returned 1 exit status
    _configtest.o: En la función `main':
    /tmp/easy_install-jIuiOc/numpy-1.13.0rc1/_configtest.c:6: referencia a `exp' sin definir
    collect2: error: ld returned 1 exit status
    _configtest.c:1:5: warning: conflicting types for built-in function ‘exp’ [enabled by default]
     int exp (void);
         ^
    _configtest.c:1:20: fatal error: Python.h: No existe el archivo o el directorio
     #include <Python.h>
                        ^
    compilation terminated.
    _configtest.c:1:20: fatal error: Python.h: No existe el archivo o el directorio
     #include <Python.h>
                        ^
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/pandas/setup.py", line 727, in <module>
        **setuptools_kwargs)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs
        replace_conflicting=True
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 646, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1025, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 50, in run_setup
        lambda: execfile(
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 100, in run
        return func()
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 52, in <lambda>
        {'__file__':setup_script, '__name__':'__main__'}
      File "setup.py", line 392, in <module>
        """Custom distutils command subclassed from Cython.Distutils.build_ext
      File "setup.py", line 384, in setup_package
        """ % src)
      File "/tmp/easy_install-jIuiOc/numpy-1.13.0rc1/numpy/distutils/core.py", line 169, in setup
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 177, in run
        self.run_command("egg_info")
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-jIuiOc/numpy-1.13.0rc1/numpy/distutils/command/egg_info.py", line 26, in run
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-jIuiOc/numpy-1.13.0rc1/numpy/distutils/command/build_src.py", line 148, in run
      File "/tmp/easy_install-jIuiOc/numpy-1.13.0rc1/numpy/distutils/command/build_src.py", line 165, in build_sources
      File "/tmp/easy_install-jIuiOc/numpy-1.13.0rc1/numpy/distutils/command/build_src.py", line 324, in build_extension_sources
      File "/tmp/easy_install-jIuiOc/numpy-1.13.0rc1/numpy/distutils/command/build_src.py", line 377, in generate_sources
      File "numpy/core/setup.py", line 421, in generate_config_h
        tag = bdist_wheel.get_tag(self)
      File "numpy/core/setup.py", line 47, in check_types
        setuptools_kwargs = {}
      File "numpy/core/setup.py", line 280, in check_types
        pjoin(ujson_python,'JSONtoObj.c'),
    SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
    Complete output from command python setup.py egg_info:
    Running from numpy source directory.

/tmp/easy_install-jIuiOc/numpy-1.13.0rc1/setup.py:367: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates

  run_build = parse_setuppy_commands()

/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'

  warnings.warn(msg)

/tmp/easy_install-jIuiOc/numpy-1.13.0rc1/numpy/distutils/system_info.py:572: UserWarning:

    Atlas (http://math-atlas.sourceforge.net/) libraries not found.

    Directories to search for the libraries can be specified in the

    numpy/distutils/site.cfg file (section [atlas]) or by setting

    the ATLAS environment variable.

  self.calc_info()

/tmp/easy_install-jIuiOc/numpy-1.13.0rc1/numpy/distutils/system_info.py:572: UserWarning:

    Blas (http://www.netlib.org/blas/) libraries not found.

    Directories to search for the libraries can be specified in the

    numpy/distutils/site.cfg file (section [blas]) or by setting

    the BLAS environment variable.

  self.calc_info()

/tmp/easy_install-jIuiOc/numpy-1.13.0rc1/numpy/distutils/system_info.py:572: UserWarning:

    Blas (http://www.netlib.org/blas/) sources not found.

    Directories to search for the sources can be specified in the

    numpy/distutils/site.cfg file (section [blas_src]) or by setting

    the BLAS_SRC environment variable.

  self.calc_info()

/bin/sh: 1: svnversion: not found

/bin/sh: 1: svnversion: not found

/tmp/easy_install-jIuiOc/numpy-1.13.0rc1/numpy/distutils/system_info.py:572: UserWarning:

    Lapack (http://www.netlib.org/lapack/) libraries not found.

    Directories to search for the libraries can be specified in the

    numpy/distutils/site.cfg file (section [lapack]) or by setting

    the LAPACK environment variable.

  self.calc_info()

/tmp/easy_install-jIuiOc/numpy-1.13.0rc1/numpy/distutils/system_info.py:572: UserWarning:

    Lapack (http://www.netlib.org/lapack/) sources not found.

    Directories to search for the sources can be specified in the

    numpy/distutils/site.cfg file (section [lapack_src]) or by setting

    the LAPACK_SRC environment variable.

  self.calc_info()

/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'define_macros'

  warnings.warn(msg)

non-existing path in 'numpy/distutils': 'site.cfg'

Could not locate executable gfortran

Could not locate executable f95

Could not locate executable ifort

Could not locate executable ifc

Could not locate executable lf95

Could not locate executable pgfortran

Could not locate executable f90

Could not locate executable f77

Could not locate executable fort

Could not locate executable efort

Could not locate executable efc

Could not locate executable g77

Could not locate executable g95

Could not locate executable pathf95

don't know how to compile Fortran code on platform 'posix'

_configtest.c:1:5: warning: conflicting types for built-in function ‘exp’ [enabled by default]

 int exp (void);

     ^

_configtest.o: En la función `main':

/tmp/easy_install-jIuiOc/numpy-1.13.0rc1/_configtest.c:6: referencia a `exp' sin definir

collect2: error: ld returned 1 exit status

_configtest.o: En la función `main':

/tmp/easy_install-jIuiOc/numpy-1.13.0rc1/_configtest.c:6: referencia a `exp' sin definir

collect2: error: ld returned 1 exit status

_configtest.c:1:5: warning: conflicting types for built-in function ‘exp’ [enabled by default]

 int exp (void);

     ^

_configtest.c:1:20: fatal error: Python.h: No existe el archivo o el directorio

 #include <Python.h>

                    ^

compilation terminated.

_configtest.c:1:20: fatal error: Python.h: No existe el archivo o el directorio

 #include <Python.h>

                    ^

compilation terminated.

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/pandas/setup.py", line 727, in <module>

    **setuptools_kwargs)

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs

    replace_conflicting=True

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match

    return self.obtain(req, installer) # try and download/install

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain

    return installer(requirement)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg

    return cmd.easy_install(req)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install

    return self.install_item(spec, dist.location, tmpdir, deps)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 646, in install_item

    dists = self.install_eggs(spec, download, tmpdir)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs

    return self.build_and_install(setup_script, setup_base)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install

    self.run_setup(setup_script, setup_base, args)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1025, in run_setup

    run_setup(setup_script, args)

  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 50, in run_setup

    lambda: execfile(

  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 100, in run

    return func()

  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 52, in <lambda>

    {'__file__':setup_script, '__name__':'__main__'}

  File "setup.py", line 392, in <module>

    """Custom distutils command subclassed from Cython.Distutils.build_ext

  File "setup.py", line 384, in setup_package

    """ % src)

  File "/tmp/easy_install-jIuiOc/numpy-1.13.0rc1/numpy/distutils/core.py", line 169, in setup

  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup

    dist.run_commands()

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 177, in run

    self.run_command("egg_info")

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/tmp/easy_install-jIuiOc/numpy-1.13.0rc1/numpy/distutils/command/egg_info.py", line 26, in run

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/tmp/easy_install-jIuiOc/numpy-1.13.0rc1/numpy/distutils/command/build_src.py", line 148, in run

  File "/tmp/easy_install-jIuiOc/numpy-1.13.0rc1/numpy/distutils/command/build_src.py", line 165, in build_sources

  File "/tmp/easy_install-jIuiOc/numpy-1.13.0rc1/numpy/distutils/command/build_src.py", line 324, in build_extension_sources

  File "/tmp/easy_install-jIuiOc/numpy-1.13.0rc1/numpy/distutils/command/build_src.py", line 377, in generate_sources

  File "numpy/core/setup.py", line 421, in generate_config_h

    tag = bdist_wheel.get_tag(self)

  File "numpy/core/setup.py", line 47, in check_types

    setuptools_kwargs = {}

  File "numpy/core/setup.py", line 280, in check_types

    pjoin(ujson_python,'JSONtoObj.c'),

SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.

----------------------------------------
Cleaning up...




Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pandas
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 72: ordinal not in range(128)
