### ISSUE TITLE
local variable 'bot' referenced before assignment

### ISSUE THREAD

**Issue by ytarabyte** [PokemonGoF/PokemonGo-Bot#2821]
### Expected Behavior
Bot runs when ./run.sh executed

### Actual Behavior
2016-08-07 10:43:18,475 [       cli] [INFO] PokemonGO Bot v1.0
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 126, in main
    if bot:
UnboundLocalError: local variable 'bot' referenced before assignment

### Other Information
OS: Mac
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: Python 2.7.11

**Comment by brantje** [comment]
#2780

**Comment by brantje** [comment]
Or #2808
