### ISSUE TITLE
Error after bot working

### ISSUE THREAD

**Issue by helloitu** [PokemonGoF/PokemonGo-Bot#2822]
### Expected Behavior

work
### Actual Behavior
the bot works after some time i get this error 
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
and ...
2016-08-07 09:30:55,226 [  SpinFort] [INFO] [pokestop_out_of_range] Pokestop Praça Dr. Emílio Ribas out of range.
2016-08-07 09:30:55,227 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
.
no more pokemons caṕtured or pokstops flagged. pls help
### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by Yakusari** [comment]
I have the same issue on my Ubuntu 16.04

2016-08-07 16:56:37,237 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Neues Schloss Schild - 0.05km (attraction of lure 0.13km)
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file __init__.py, line 550
2016-08-07 16:56:47,046 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-07 16:56:48,012 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-07 16:56:55,918 [  SpinFort] [INFO] [pokestop_out_of_range] Pokestop Neues Schloss Schild out of range.
2016-08-07 16:56:55,918 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.

**Comment by helloitu** [comment]
i get banned man , take care

**Comment by reconka** [comment]
how? softban?

**Comment by helloitu** [comment]
perma i think , i will wait 1 hour and get back here

**Comment by mico** [comment]
#2849
