### ISSUE TITLE
Getting close to start, what am i missing?

### ISSUE THREAD

**Issue by Dotnl** [PokemonGoF/PokemonGo-Bot#2829]
### Expected Behavior

Start the bot

### Actual Behavior

$ python pokecli.py
2016-08-07 17:03:06,509 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 17:03:06,510 [       cli] [INFO] No config argument specified, checking for /configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 501, in <module>
    main()
  File "pokecli.py", line 132, in main
    raise e

### Steps to Reproduce

Followed the guide and trying to get the bot to run

### Other Information
OS:  W7

Python Version: 2.7.10

**Comment by nivong** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2808
follow that guide.

**Comment by Dotnl** [comment]
Json config file contained errors
