### ISSUE TITLE
CLI colours aren't working 

### ISSUE THREAD

**Issue by pokegirl0** [PokemonGoF/PokemonGo-Bot#2850]

**Comment by maps90** [comment]
after update cli didn't have color anymore..

**Comment by pokegirl0** [comment]
Why? It's so harder to read now.

**Comment by Arderos** [comment]
Yeah, colorized output is much easier to read. Please bring it back

**Comment by pokegirl0** [comment]
Wish they'd stop playing with this unless they have anything major to add.

**Comment by ph3l1x** [comment]
Also, its displaying a whole bunch of extra data. Would be awesome to get the return to be how it was before. Any plans to do this?

**Comment by SingularityIO** [comment]
Upload this to \PokemonGo-Bot\pokemongo_bot\cell_workers 
**## AND RENAME IT FROM transfer_pokemon.txt to transfer_pokemon.py AND REPLACE THE ORIGINAL!!! or backup the original and just name it transfer_pokemon.py**
And it will add temp colours back in until they do an official colour update

[transfer_pokemon.txt](https://github.com/PokemonGoF/PokemonGo-Bot/files/405650/transfer_pokemon.txt)

**Comment by ph3l1x** [comment]
There is no existing file named transfer_pokemon.py and I receive this error when running it.

Traceback (most recent call last):
  File "transfer_pokemon.py", line 7, in <module>
    from cell_workers.base_task import BaseTask
  File "/var/www/h.mindimage.net/PokemonGo-Bot/pokemongo_bot/cell_workers/__init__.py", line 3, in <module>
    from catch_lured_pokemon import CatchLuredPokemon
  File "/var/www/h.mindimage.net/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_lured_pokemon.py", line 4, in <module>
    from pokemongo_bot.cell_workers.utils import fort_details
ImportError: No module named pokemongo_bot.cell_workers.utils


Seems all the files that you have in there are not named properly. I removed some data from the very beginning to match the correct file names but I don't think this is working how you currently have it. 

Traceback (most recent call last):
  File "transfer_pokemon.py", line 5, in <module>
    from pokemongo_bot.human_behaviour import action_delay
ImportError: No module named pokemongo_bot.human_behaviour

there is no pokemongo_bot.human_behaviour however there is a human_behavior. Am I missing something here?

**Comment by SingularityIO** [comment]
Updated the Link

> extract the files inside the "cell_workers" folder in the zip to this directory  \PokemonGo-Bot\pokemongo_bot\cell_workers 

http://puu.sh/qtlX7/570de9c1a3.zip

**Comment by Arderos** [comment]
It's better than before, but should be a part of the branch. As I understand, colors went away because they were defiled in logger.py, which is no longer used.
