### ISSUE TITLE
No config argument

### ISSUE THREAD

**Issue by Elim160** [PokemonGoF/PokemonGo-Bot#2854]
PokemonGO Bot v1.0
2016-08-07 11:14:31,685 [       cli] [INFO] No config argument specified, checking for /configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 501, in <module>
    main()
  File "pokecli.py", line 132, in main
    raise e
ValueError: No JSON object could be decoded

this is the error phrase that I got after setting up my json file.

OS: Mac OS

**Comment by cwild** [comment]
Your JSON is not valid.

**Comment by Elim160** [comment]
Okay when I put my JSON into jsonlint.com , this is the error I get
 Error: Parse error on line 2:
{	"auth_service": “ptc”,	"username": 
------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
@cwild

**Comment by nivong** [comment]
fix the string (retyp the "")

**Comment by antoineneff** [comment]
Your quotes are not regular ones.

**Comment by Elim160** [comment]
Okay I changed them and now I am Getting this error 
PokemonGO Bot v1.0
2016-08-07 11:32:45,545 [       cli] [INFO] No config argument specified, checking for /configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 501, in <module>
    main()
  File "pokecli.py", line 132, in main
    raise e
ValueError: Expecting : delimiter: line 3 column 20 (char 48)

**Comment by Elim160** [comment]
NVM GOT it

**Comment by nivong** [comment]
@Elim160 can you read my question? If you want help than profide the info you are asked.... good to hear that you fixed it, if you can please post the fix and close the issue.
