### ISSUE TITLE
I cannot run script (0x9c)

### ISSUE THREAD

**Issue by 9grit** [PokemonGoF/PokemonGo-Bot#2855]
### Expected Behavior
2016-08-07 16:20:13,462 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 16:20:13,521 [       cli] [INFO] Configuration initialized
2016-08-07 16:20:13,521 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more logrmation:
2016-08-07 16:20:13,521 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-07 16:20:13,737 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-07 16:20:13,930 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-07 16:20:13,931 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-07 16:20:13,931 [PokemonGoBot] [INFO] [location_found] Location found: 13.644827,100.547935 (13.644827, 100.547935, 0.0)
2016-08-07 16:20:13,931 [PokemonGoBot] [INFO] [position_update] Now at (13.644827, 100.547935, 0)
2016-08-07 16:20:13,931 [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "/home/<Username>/PokemonGo-Bot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/home/<Username>/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 106, in call
    result = self._call()
  File "/home/<Username>/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "/home/<Username>/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/home/<Username>/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 129, in request
    response_dict = self._parse_main_response(response, subrequests)
  File "/home/<Username>/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 332, in _parse_main_response
    raise ServerSideAccessForbiddenException("Seems your IP Address is banned or something else went badly wrong...")
pgoapi.exceptions.ServerSideAccessForbiddenException: Seems your IP Address is banned or something else went badly wrong...
2016-08-07 16:20:15,851 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib64/python2.7/httplib.py", line 979, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 833, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-07 16:20:15,953 [sentry.errors.uncaught] [ERROR] [u'ServerSideAccessForbiddenException: Seems your IP Address is banned or something else went badly wrong...', u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", line 127, in main', u'  File "pokecli.py", line 136, in report_summary', u'  File "pokemongo_bot/metrics.py", line 76, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 106, in call', u'  File "pokemongo_bot/api_wrapper.py", line 63, in _call', u'  File "pgoapi/pgoapi.py", line 220, in call', u'  File "pgoapi/rpc_api.py", line 129, in request', u'  File "pgoapi/rpc_api.py", line 332, in _parse_main_response']
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit

### Other Information
OS: CentOS7
Git Commit: ad6c21aa1dc0902c62e4001f9a81ce1fcd8a9f59
Python Version: Python 2.7.5

**Comment by nivong** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2808

**Comment by 9grit** [comment]
I think it already config log in below : 

Requirement already satisfied (use --upgrade to upgrade): numpy==1.11.0 in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): networkx==1.11 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Obtaining pgoapi from git+https://github.com/keyphact/pgoapi.git@249d3be7fbbdabc7f9adea17cbc899d6549e47a2#egg=pgoapi (from -r requirements.txt (line 3))
  Skipping because already up-to-date.
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): protobuf==3.0.0b4 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 8))
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 9))
Collecting googlemaps==2.4.4 (from -r requirements.txt (line 10))
  Using cached googlemaps-2.4.4-py2-none-any.whl
Collecting colorama==0.3.7 (from -r requirements.txt (line 11))
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Collecting enum34==1.1.6 (from -r requirements.txt (line 12))
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting pyyaml==3.11 (from -r requirements.txt (line 13))
Collecting haversine==0.4.5 (from -r requirements.txt (line 14))
Collecting polyline==1.3.1 (from -r requirements.txt (line 15))
  Using cached polyline-1.3.1-py2.py3-none-any.whl
Collecting python-socketio==1.4.2 (from -r requirements.txt (line 16))
Collecting flask==0.11.1 (from -r requirements.txt (line 17))
  Using cached Flask-0.11.1-py2.py3-none-any.whl
Collecting socketIO_client==0.7.0 (from -r requirements.txt (line 18))
Collecting eventlet==0.19.0 (from -r requirements.txt (line 19))
  Using cached eventlet-0.19.0-py2.py3-none-any.whl
Collecting gpxpy==1.1.1 (from -r requirements.txt (line 20))
Collecting mock==2.0.0 (from -r requirements.txt (line 21))
  Using cached mock-2.0.0-py2.py3-none-any.whl
Collecting timeout-decorator==0.3.2 (from -r requirements.txt (line 22))
Collecting raven==5.23.0 (from -r requirements.txt (line 23))
  Using cached raven-5.23.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.4.0 in /usr/lib/python2.7/site-packages (from networkx==1.11->-r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/site-packages (from pgoapi->-r requirements.txt (line 3))
Collecting xxhash (from pgoapi->-r requirements.txt (line 3))
  Using cached xxhash-0.6.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/site-packages (from protobuf==3.0.0b4->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): future in /usr/lib/python2.7/site-packages (from s2sphere==0.2.4->-r requirements.txt (line 7))
Collecting pycryptodomex>=3.0 (from gpsoauth==0.3.0->-r requirements.txt (line 8))
  Using cached pycryptodomex-3.4.2.tar.gz
Collecting python-engineio>=0.8.0 (from python-socketio==1.4.2->-r requirements.txt (line 16))
Collecting click>=2.0 (from flask==0.11.1->-r requirements.txt (line 17))
Collecting Jinja2>=2.4 (from flask==0.11.1->-r requirements.txt (line 17))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting Werkzeug>=0.7 (from flask==0.11.1->-r requirements.txt (line 17))
  Using cached Werkzeug-0.11.10-py2.py3-none-any.whl
Collecting itsdangerous>=0.21 (from flask==0.11.1->-r requirements.txt (line 17))
Collecting websocket-client (from socketIO_client==0.7.0->-r requirements.txt (line 18))
Collecting greenlet>=0.3 (from eventlet==0.19.0->-r requirements.txt (line 19))
  Using cached greenlet-0.4.10-cp27-cp27mu-manylinux1_x86_64.whl
Collecting funcsigs>=1; python_version < "3.3" (from mock==2.0.0->-r requirements.txt (line 21))
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock==2.0.0->-r requirements.txt (line 21))
  Using cached pbr-1.10.0-py2.py3-none-any.whl
Collecting contextlib2 (from raven==5.23.0->-r requirements.txt (line 23))
  Using cached contextlib2-0.5.4-py2.py3-none-any.whl
Collecting MarkupSafe (from Jinja2>=2.4->flask==0.11.1->-r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname in /usr/lib/python2.7/site-packages (from websocket-client->socketIO_client==0.7.0->-r requirements.txt (line 18))
Building wheels for collected packages: xxhash, pycryptodomex
  Running setup.py bdist_wheel for xxhash ... done
  Stored in directory: /root/.cache/pip/wheels/01/4b/34/ed020afed2c3a5b5f0ca2384b37b9d529c517dc632ed101666
  Running setup.py bdist_wheel for pycryptodomex ... done
  Stored in directory: /root/.cache/pip/wheels/68/ab/79/ccf5b816e234c3c5fc1ce31edc2ff4ee23f0b64117e03c267c
Successfully built xxhash pycryptodomex
Installing collected packages: pycryptodomex, gpsoauth, xxhash, pgoapi, protobuf-to-dict, googlemaps, colorama, enum34, pyyaml, haversine, polyline, python-engineio, python-socketio, click, MarkupSafe, Jinja2, Werkzeug, itsdangerous, flask, websocket-client, socketIO-client, greenlet, eventlet, gpxpy, funcsigs, pbr, mock, timeout-decorator, contextlib2, raven
  Running setup.py develop for pgoapi
Successfully installed Jinja2-2.8 MarkupSafe-0.23 Werkzeug-0.11.10 click-6.6 colorama-0.3.7 contextlib2-0.5.4 enum34-1.1.6 eventlet-0.19.0 flask-0.11.1 funcsigs-1.0.2 googlemaps-2.4.4 gpsoauth-0.3.0 gpxpy-1.1.1 greenlet-0.4.10 haversine-0.4.5 itsdangerous-0.24 mock-2.0.0 pbr-1.10.0 pgoapi polyline-1.3.1 protobuf-to-dict-0.1.0 pycryptodomex-3.4.2 python-engineio-0.9.2 python-socketio-1.4.2 pyyaml-3.11 raven-5.23.0 socketIO-client-0.7.0 timeout-decorator-0.3.2 websocket-client-0.37.0 xxhash-0.6.1
