### ISSUE TITLE
No Config Argument

### ISSUE THREAD

**Issue by icecubeice** [PokemonGoF/PokemonGo-Bot#2868]
Ok so when I start the bot this shows:
2016-08-08 01:06:24,885 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-08 01:06:24,887 [       cli] [INFO] No config argument specified, checking for /configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 126, in main
    if bot:
UnboundLocalError: local variable 'bot' referenced before assignment

### Other Information
OS: Windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by icecubeice** [comment]
pls help

**Comment by Ph4i1ur3** [comment]
Bad config file. If this is still an issue seek help on the slack channel.
