### ISSUE TITLE
Error after starting Bot

### ISSUE THREAD

**Issue by pjakubek** [PokemonGoF/PokemonGo-Bot#2870]
I edited the config and added the encrypt.so to the main folder, but when I run the bot with "./run.sh" after logging in the bot crashes.
`Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 139, in report_summary
    logger.info('Total XP Earned: {}  Average: {:.2f}/h'.format(metrics.xp_earned(), metrics.xp_per_hour()))
  File "/home/pjakubek/Documents/Projects/PokemonGo-Bot/pokemongo_bot/metrics.py", line 28, in xp_earned
    return self.xp['latest'] - self.xp['start']
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
2016-08-07 19:12:04,324 [sentry.errors] [ERROR] Sentry responded with an error: 'module' object has no attribute 'HTTPSHandler' (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/pjakubek/Documents/Projects/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/pjakubek/Documents/Projects/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/pjakubek/Documents/Projects/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 44, in urlopen
    class ValidHTTPSHandler(urllib2.HTTPSHandler):
AttributeError: 'module' object has no attribute 'HTTPSHandler'
2016-08-07 19:12:04,324 [sentry.errors.uncaught] [ERROR] [u"TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'", u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", line 127, in main', u'  File "pokecli.py", line 139, in report_summary', u'  File "pokemongo_bot/metrics.py", line 28, in xp_earned']`

### Other Information
OS: elementary OS Freya
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: 2.7.6

**Comment by PraeceptorXS** [comment]
Did you check to see if the config.json was valid?

**Comment by pjakubek** [comment]
yep, config.json is valid

**Comment by CyberMew** [comment]
Probably related to #2596
