### ISSUE TITLE
pgoapi.exceptions.NoPlayerPositionSetException

### ISSUE THREAD

**Issue by Anby29** [PokemonGoF/PokemonGo-Bot#2871]
When I start pokecli.py -cf ./configs/config.json , I got a **pgoapi.exceptions.NoPlayerPositionSetException** error.
Does someone meet this error ? Thanks for your help.

2016-08-07 19:13:06,612 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 19:13:06,612 [       cli] [INFO] Configuration initialized
2016-08-07 19:13:06,628 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "C:\Users\Olivier\PokemonGo-Bot\pokemongo_bot\metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "C:\Users\Olivier\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 90, in call
    if not self.can_call():
  File "C:\Users\Olivier\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 54, in can_call
    raise NoPlayerPositionSetException()
pgoapi.exceptions.NoPlayerPositionSetException

### Other Information
OS: Windows 10 64 bits
Python Version: 2.7.4

**Comment by BobbyWibowo** [comment]
Have you set your location in `/configs/config.json`?

**Comment by Anby29** [comment]
I set     
"location": "Santa Monica",
in the config.json.

**Comment by mjmadsen** [comment]
"location" needs to be GPS coordinates. 

Try "48.856741, 2.350811" for Paris.

**Comment by Anby29** [comment]
I forgot to install the encrypt_64.dll
Now it works ! Thx for your help.
