### ISSUE TITLE
i've this error pls help

### ISSUE THREAD

**Issue by zzphantomzz** [PokemonGoF/PokemonGo-Bot#2872]
[00:17:33] This bot is absolutely free and open-source!
[00:17:33] If you've paid for it. Request a chargeback immediately!
[00:17:33] Starting Execute on login server: Google
[00:17:34] Error: Pokemon.Go.Rocket.API
[00:17:34] PokemonGo.RocketAPI.Exceptions.GoogleException: NeedsBrowser
   at PokemonGo.RocketAPI.Login.GoogleLogin.<GetAccessToken>d__3.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Login\GoogleLogin.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Rpc\Login.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__9.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:line 58
[00:17:34] Trying to Restart.
[00:17:34] Restarting in 10 Seconds.
[00:17:34] Error reloading Pokemon list: NeedsBrowser
[00:17:36] Error reloading Pokemon list: NeedsBrowser
[00:17:37] Error reloading Pokemon list: NeedsBrowser
[00:17:38] Error reloading Pokemon list: NeedsBrowser
[00:17:46] Error: Pokemon.Go.Rocket.API
[00:17:46] PokemonGo.RocketAPI.Exceptions.GoogleException: NeedsBrowser
   at PokemonGo.RocketAPI.Login.GoogleLogin.<GetAccessToken>d__3.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Login\GoogleLogin.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Rpc\Login.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__9.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:line 58
[00:17:46] Trying to Restart.
[00:17:46] Restarting in 10 Seconds.

**Comment by juliosueiras** [comment]
I think you are lookings for this https://github.com/Ar1i/PokemonGo-Bot
