### ISSUE TITLE
Dummies guide for WIN10

### ISSUE THREAD

**Issue by RaizenInstinct** [PokemonGoF/PokemonGo-Bot#2875]
Hello guys,

I have seen many people posting guides on Linux or OS but nothing on WIN10.

I just got the bot running on my PC so I decided to put together a small guide.
**1. Install:**
Python 2.7+
Pip
GitBash
virtualenv
PyYAML-3.11-cp27-cp27m-win32.whl / PyYAML-3.11-cp27-cp27m-win_amd64.whl 
(all links in Read me)
Microsoft visual c++ compiler package for python 2.7

**2.Commands:**
a) in the directory where you have PyYAML run Git Bash and then run command
$ pip2 install PyYAML-3.11-cp27-cp27m-win32.whl 
// $ pip2 install PyYAML-3.11-cp27-cp27m-win_amd64.whl
b) download the bot files - I recommend pulling from dev branch.
$ git clone -b master https://github.com/PokemonGoF/PokemonGo-Bot  
//$ git clone -b dev https://github.com/PokemonGoF/PokemonGo-Bot  
c) close Git Bash and go to the  "PokemonGo-Bot" folder and rerun Git Bash
$ virtualenv .
$ scripts\activate  
$ pip2 install -r requirements.txt
$ git submodule init
$ git submodule update

**3. Join the Pokemon-go Bot Slack team** and download encrypt.dll for your respective version from shared files:
![image](https://cloud.githubusercontent.com/assets/20803732/17463906/5f078d0e-5cd2-11e6-93be-2d6220b848b4.png)

3.a. If you use the 64bit Win rename the file to **"encrypt_64.dll"** 
(this works for the dev branch. for Master you have to modify your init file or you will get error message.
change the line in __init__.py, located in .\PokemonGo-Bot\pokemongo_bot
to
self.api.activate_signature("./encrypt_64.dll")
or
self.api.activate_signature("./encrypt.dll")
Make sure to download the correct encrypt.dll file for your windows OS version (32 or 64 bit)
)
3.b save the encrypt_64.dll file into the "...\PokemonGo-Bot-dev" folder

**4. Create/Modify config.json file.**
4.a Change the "Health_record":true to **false** (this fixes the ascii issue)

**5.** Run Git Bash in the Pokemongo-bot main folder and run command
$ python pokecli.py --config ./configs/config.json

I might have forgotten something so if you encounter any issues let me know

**Comment by ksawerykarwacki** [comment]
Any specific reason to use python in git bash not native?

**Comment by RaizenInstinct** [comment]
sorry I dont understand your question...

**Comment by iHatePython** [comment]
So you copy pasted the installation guide for Windows and put it all under issues section? You didn't even bother fixing the typo with (script\activate), smfh

**Comment by DSFARGEG** [comment]
@RaizenInstinct You forgot the instructions to change the line in __init__.py, located in .\PokemonGo-Bot\pokemongo_bot  
to  
self.api.activate_signature("./encrypt64bit.dll")  
or  
self.api.activate_signature("./encrypt.dll")  
mentioned at the pastery

**Comment by RaizenInstinct** [comment]
half is copied half is not there. I don't think the script/activate is even necessary I don't recall having an issue with it so I just let it there. 
It worked for me so idc what you think :P

**Comment by RaizenInstinct** [comment]
@DSFARGEG if I change it I keep getting WindowError. Without change it works OK...

**Comment by BobbyWibowo** [comment]
@DSFARGEG That's no longer required on the dev branch since this commit: https://github.com/PokemonGoF/PokemonGo-Bot/commit/e927195fec5883c11a8e95dd6046856063c4931c

**Comment by BobbyWibowo** [comment]
@RaizenInstinct The issue that @iHatePython mentioned was that it had to be 'scripts` instead of `script`. Notice the missing `s`? `script` folder doesn't exist after you run `virtualenv .`.

**Comment by RaizenInstinct** [comment]
@BobbyWibowo fixed thx :)

**Comment by Nathanian** [comment]
in which folder should i put the encrypt.dll file?

**Comment by RaizenInstinct** [comment]
@Nathanian I have it in the "....\PokemonGo-Bot-dev" folder, i.e. the main folder.

**Comment by PokePy** [comment]
Still same error. Using Win64 OS

```
$ python pokecli.py --config ./configs/config.json
2016-08-07 20:03:11,128 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 20:03:11,131 [       cli] [INFO] Configuration initialized
2016-08-07 20:03:11,134 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-07 20:03:11,134 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-07 20:03:11,134 [PokemonGoBot] [INFO] [location_found] Location found: 40.758485, -73.985077 (40.758485, -73.985077, 0.0)
2016-08-07 20:03:11,134 [PokemonGoBot] [INFO] [position_update] Now at (40.758485, -73.985077, 0)
2016-08-07 20:03:11,134 [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "C:\Python27\Pokepy\PokemonGo-Bot\pokemongo_bot\metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "C:\Python27\Pokepy\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 106, in call
    result = self._call()
  File "C:\Python27\Pokepy\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "c:\python27\pokepy\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "c:\python27\pokepy\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 126, in request
    request_proto = self._build_main_request(subrequests, player_position)
  File "c:\python27\pokepy\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 180, in _build_main_request
    request.latitude, request.longitude, request.altitude = player_position
  File "C:\python27\lib\site-packages\google\protobuf\internal\python_message.py", line 669, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "C:\python27\lib\site-packages\google\protobuf\internal\type_checkers.py", line 132, in CheckValue
    raise TypeError(message)
TypeError: 40.758485 has type <type 'float'>, but expected one of: (<type 'int'>, <type 'long'>)
```

**Comment by RaizenInstinct** [comment]
@PokePy that looks like an error in your config file. Namely in your coordinates...

**Comment by PokePy** [comment]
I have tried changing to address string, but it converts it to longitude latitude anyway i think

**Comment by chypriote** [comment]
@PokePy 
> TypeError: 40.758485 has type <type 'float'>, but expected one of: (<type 'int'>, <type 'long'>)
is the relevant part, the location must follow the format 'latitude, longitude', ie: 25.215062, 55.190368

**Comment by RaizenInstinct** [comment]
@PokePy yeah write it like "location": "40.765237, -73.973217", if you want to start at Central Park

**Comment by starrett67** [comment]
I followed all the steps above and I am currently seeing this error:

Traceback (most recent call last):
  File ".\pokecli.py", line 502, in <module>
    main()
  File ".\pokecli.py", line 131, in main
    report_summary(bot)
  File ".\pokecli.py", line 140, in report_summary
    metrics.capture_stats()
  File "C:\Users\Commander\Documents\GitHub\PokemonGo-Bot\pokemongo_bot\metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "C:\Users\Commander\Documents\GitHub\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 106, in call
    result = self._call()
  File "C:\Users\Commander\Documents\GitHub\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "C:\Users\Commander\Documents\GitHub\PokemonGo-Bot\lib\site-packages\pgoapi-1.1.6-py2.7.egg\pgoapi\pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "C:\Users\Commander\Documents\GitHub\PokemonGo-Bot\lib\site-packages\pgoapi-1.1.6-py2.7.egg\pgoapi\rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "c:\python27\Lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application

**Comment by BobbyWibowo** [comment]
@starret67 Make sure you're using the same architecture of encrypt.dll as your Python installation (that 32/64 bit thing is the architecture).

**Comment by starrett67** [comment]
Figured it out I was using 64bit when i needed to use 32 bit

**Comment by CipherBear** [comment]
I am getting the below error.  I have tried both branches, both versions of the encrypt.dll for windows, hardcoding it into the init, I am at my wit's end.

2016-08-07 14:11:35,345 [ cli] [INFO] PokemonGO Bot v1.0
2016-08-07 14:11:35,349 [ cli] [INFO] Configuration initialized
2016-08-07 14:11:35,352 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-07 14:11:35,352 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-07 14:11:35,352 [PokemonGoBot] [INFO] [location_found] Location found: 40.713693, -74.032123 (40.713693, -74.032123, 0.0)
2016-08-07 14:11:35,352 [PokemonGoBot] [INFO] [position_update] Now at (40.713693, -74.032123, 0)
2016-08-07 14:11:35,352 [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
File "pokecli.py", line 493, in 
main()
File "pokecli.py", line 127, in main
report_summary(bot)
File "pokecli.py", line 136, in report_summary
metrics.capture_stats()
File "C:\Users\ahirsch.CDCSERVICES\Downloads\PokemonGoafter\PokemonGo-Bot\pokemongo_bot\metrics.py", line 73, in capture_stats
request = self.bot.api.create_request()
File "C:\Users\ahirsch.CDCSERVICES\Downloads\PokemonGoafter\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 27, in create_request
self.position_alt
File "C:\Users\ahirsch.CDCSERVICES\Downloads\PokemonGoafter\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 43, in __init_
PGoApiRequest.init(self, *args)
TypeError: init() takes exactly 6 arguments (5 given)

**Comment by Willsbond** [comment]
How do I "Join the Pokemon-go Bot Slack team and download encrypt.dll for your respective version from shared files"?

**Comment by icecubeice** [comment]
^same

**Comment by iHatePython** [comment]
https://pokemongo-bot.slack.com

**Comment by realquantumsource** [comment]
How do we get an invite to the team?

**Comment by thelord810** [comment]
You can find encrypt.dll on following location:
https://www.sendspace.com/file/bq0hcn

Credit: To some unknown angel for uploading file. I just found it on reddit and sharing it for community use.

**Comment by k4n30** [comment]
Please use the slack chat for support issues
