### ISSUE TITLE
Can't Start

### ISSUE THREAD

**Issue by arya091** [PokemonGoF/PokemonGo-Bot#2882]
When Running Python pokecli.py:

Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions

I've check my account & POkemon Server are running well.

Thank You.

**Comment by kirualex** [comment]
try `virtualenv .` then `pip install requirements.txt`, then launch again

**Comment by arya091** [comment]
It Works! Thanks, but then... i got another error Message:

RuntimeError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "C:\Users\Arya\PokemonGo-Bot\pokemongo_bot\metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "C:\Users\Arya\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 106, in call
    result = self._call()
  File "C:\Users\Arya\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "c:\users\arya\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "c:\users\arya\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2016-08-08 01:28:11,617 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)

**Comment by MrKaralis** [comment]
Had exactly the same errors that Arya091 had.

**Comment by starrett67** [comment]
Also having the top error @arya091 is having

**Comment by philly223** [comment]
having exact same error. any fix?

**Comment by Ph4i1ur3** [comment]
Try "pip install -r requirements.txt --upgrade"

**Comment by leadboots5** [comment]
not properly installed. kirualex provided a solution.
