### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Corecrafts** [PokemonGoF/PokemonGo-Bot#2887]
### Expected Behavior

Flawless workflow

### Actual Behavior

Bot runs for 10sec - 1 min and hits out this error

(yes encrypt.so is located in root folder)

Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 129, in main
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
2016-08-07 20:03:07,957 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/nextlevelsam/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/nextlevelsam/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/nextlevelsam/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/nextlevelsam/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/nextlevelsam/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/nextlevelsam/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/nextlevelsam/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/nextlevelsam/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-07 20:03:07,958 [sentry.errors.uncaught] [ERROR] [u"UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)", u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", line 129, in main']

### Other Information
OS: MAC OSX

**Comment by JWebCoder** [comment]
Same problem here.

OS: Linux Xubuntu

**Comment by thxmxx** [comment]
sys.setdefaultencoding('utf8')

It may solve the problem

**Comment by DimaVIII** [comment]
sys.setdefaultencoding('utf8')

Don't solve it, I tried everything here nothing can stop this error.

**Comment by thxmxx** [comment]
Well... Solved for me

**Comment by GitPupper** [comment]
### Hey there. I had this same problem, here's the fix.
***
### Just run this code:
`wget http://pgoapi.com/pgoencrypt.tar.gz && tar -xf pgoencrypt.tar.gz && cd pgoencrypt/src/ && make && mv libencrypt.so ../../encrypt.so`
***
### If you didn't already, install wget:
`brew install wget`
***
Once you have that go to Spotlight, look up `Encrypt.so` and move it into /PokemonGo-Bot/

**Comment by Corecrafts** [comment]
@GitPupper i did this alrdy... still givin me the error

**Comment by RedViper9** [comment]
Are you still having this issue?
