### ISSUE TITLE
Bot fails on initialization

### ISSUE THREAD

**Issue by CipherBear** [PokemonGoF/PokemonGo-Bot#2890]
### Expected Behavior
I have tried installing and reinstalling the bot multiple times, using multiple configs out of the box.  I have used the dev and master branches, but I keep getting the same error regardless of the init.

I am using windows 7, with python 2.7.12, I have downloaded the encrypt.dll and encrypt64bit.dll from slack and placed them in the root, even hard coded the init, but I keep receiving the same error regardless of what I do, please see the error dump below.

p.s. the gps coordinates were changed to a string as well, but it was still unsuccessful.

### Actual Behavior

2016-08-07 14:11:35,345 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 14:11:35,349 [       cli] [INFO] Configuration initialized
2016-08-07 14:11:35,352 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-07 14:11:35,352 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-07 14:11:35,352 [PokemonGoBot] [INFO] [location_found] Location found: 40.713693, -74.032123 (40.713693, -74.032123, 0.0)
2016-08-07 14:11:35,352 [PokemonGoBot] [INFO] [position_update] Now at (40.713693, -74.032123, 0)
2016-08-07 14:11:35,352 [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "C:\Users\ahirsch.CDCSERVICES\Downloads\PokemonGoafter\PokemonGo-Bot\pokemongo_bot\metrics.py", line 73, in capture_stats
    request = self.bot.api.create_request()
  File "C:\Users\ahirsch.CDCSERVICES\Downloads\PokemonGoafter\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 27, in create_request
    self._position_alt
  File "C:\Users\ahirsch.CDCSERVICES\Downloads\PokemonGoafter\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 43, in __init__
    PGoApiRequest.__init__(self, *args)
TypeError: __init__() takes exactly 6 arguments (5 given)

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by SuperMasterUser** [comment]
i am facing the same problem

**Comment by Stayhomeforever** [comment]
got the same problem.

**Comment by CipherBear** [comment]
for people saying use the wget and brew commands, I have used those as well, they seem to be mac specific.  I have downloaded and installed wget and brew via pip, both commands are useless in git bash.

**Comment by CipherBear** [comment]
Guys,

I just got it to work, I installed the most recent dev environment by using

git clone -b dev https://github.com/PokemonGoF/PokemonGo-Bot

Closed bash and opened up the pokemongo-bot folder and opened bash again

virtualenv .
Scripts/activate
pip2 install -r requirements.txt --update

I noticed that the pokemon go api wasn't installing properly via pip so I ran the following.

pip install -e git+https://github.com/keyphact/pgoapi.git@249d3be7fbbdabc7f9adea17cbc899d6549e47a2#egg=pgoapi --upgrade

git submodule init
git submodule update

Then I put in my updated configs, encrypt.dll from slack, and my batch files.
