### ISSUE TITLE
maximum recursion depth exceeded &  'ascii' codec can't decode byte 0x9c in position

### ISSUE THREAD

**Issue by arya091** [PokemonGoF/PokemonGo-Bot#2896]
Anyone know how to solve this?

it was all fine until **login**: 
2016-08-08 01:32:04,676 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-08 01:32:40,328 [       cli] [INFO] No config argument specified, checking for /configs/config.json
2016-08-08 01:32:40,355 [       cli] [INFO] Configuration initialized
2016-08-08 01:32:40,358 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more logrmation:
2016-08-08 01:32:40,361 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-08 01:32:40,536 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-08 01:32:41,055 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-08 01:32:43,036 [PokemonGoBot] [INFO] [location_found] Location found: monas, jakarta (-6.1761317, 106.822864, 0.0)
2016-08-08 01:32:43,040 [PokemonGoBot] [INFO] [position_update] Now at (-6.1761317, 106.822864, 0)
2016-08-08 01:32:43,043 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-08 01:32:50,763 [PokemonGoBot] [INFO] [login_successful] Login **successful.**

**But Then:**

RuntimeError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "C:\Users\Arya\PokemonGo-Bot\pokemongo_bot\metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "C:\Users\Arya\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 106, in call
    result = self._call()
  File "C:\Users\Arya\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "c:\users\arya\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "c:\users\arya\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2016-08-08 01:28:11,617 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)

**Comment by dezayner** [comment]
Read other issues

**Comment by RaizenInstinct** [comment]
if you pulled from master branch then modify your init file: Error 126
change the line in __init__.py, located in .\PokemonGo-Bot\pokemongo_bot
to
self.api.activate_signature("./encrypt64bit.dll")
or
self.api.activate_signature("./encrypt.dll")
Make sure to download the correct encrypt.dll file for your windows OS version (32 or 64 bit)

for mac
self.api.activate_signature("./encrypt.so")
