### ISSUE TITLE
cant start with ptc credentials

### ISSUE THREAD

**Issue by alexanderrock** [PokemonGoF/PokemonGo-Bot#292]
[x] PokemonGO Bot v1.0
[x] Configuration initialized

[x] Address found: xxx
[x] Position in-game set as: (xx.xxxx, xx.xxxx, 0.0)

Traceback (most recent call last):
  File "pokecli.py", line 107, in <module>
    main()
  File "pokecli.py", line 99, in main
    bot.start()
  File "/var/www/PokemonGo/PokemonGo-Bot/pokemongo_bot/__init__.py", line 26, in start
    self._setup_api()
  File "/var/www/PokemonGo/PokemonGo-Bot/pokemongo_bot/__init__.py", line 81, in _setup_api
    if not self.api.login(self.config.auth_service, str(self.config.username), str(self.config.password)):
  File "/var/www/PokemonGo/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 144, in login
    if not self._auth_provider.login(username, password):
  File "/var/www/PokemonGo/PokemonGo-Bot/src/pgoapi/pgoapi/auth_ptc.py", line 56, in login
    jdata = json.loads(r.content.decode('utf-8'))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by crack00r** [comment]
http://cmmcd.com/PokemonGo/

Down

**Comment by alexanderrock** [comment]
in an previous commit it shows a message that servers are down now just this error message

**Comment by douglascamata** [comment]
Closing as login servers are down.
