### ISSUE TITLE
Encrypt.so on windows

### ISSUE THREAD

**Issue by starrett67** [PokemonGoF/PokemonGo-Bot#2923]
Hey guys I am trying to get the bot working on windows 10. I have seen post on how to install create encrypt.so but I have not been able to do so on windows.

Here is what I have seen: 
wget http://pgoapi.com/pgoencrypt.tar.gz && tar -xf pgoencrypt.tar.gz && cd pgoencrypt/src/ && make

I tried installing MinGW and running this command:
Invoke-WebRequest http://pgoapi.com/pgoencrypt.tar.gz -OutFile pgoencrypt.tar.gz; tar -xf
 pgoencrypt.tar.gz; cd pgoencrypt/src/; make

But I got this:

cc -fPIC -std=gnu99   -c -o encrypt.o encrypt.c
make.exe": cc: Command not found
make.exe": *** [encrypt.o] Error 127

**Comment by BriceSD** [comment]
@starrett67 Take encrypt64bit.dll here : https://github.com/PokemonGoMap/PokemonGo-Map/tree/develop/pogom 
Put it in the PokemonGo-Bot folder, then rename it : encrypt_64.dll

**Comment by starrett67** [comment]
Thanks @BriceSD that fixed my issues. But now i am running into this:

Traceback (most recent call last):
  File ".\pokecli.py", line 493, in <module>
    main()
  File ".\pokecli.py", line 127, in main
    report_summary(bot)
  File ".\pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "C:\Users\Commander\PokemonGo-Bot\pokemongo_bot\metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "C:\Users\Commander\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 106, in call
    result = self._call()
  File "C:\Users\Commander\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "c:\users\commander\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "c:\users\commander\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "c:\python27\Lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application

**Comment by reivmeister** [comment]
I'm having this exact same issue you posted above. Did you manage to fix it?

**Comment by starrett67** [comment]
not yet

**Comment by BriceSD** [comment]
@reivmeister you won't be able to use the makefile on windows.
@starrett67 I didn't have this issue. You're not the first though. Don't forget to give back once you solve the problem

Also on windows you'll need a .dll file, not .so

**Comment by starrett67** [comment]
@reivmeister Hey I was using the wrong encrypt dll. Its not the make sure to use 32bit if python is 32bit and 64 bit if python is 64bit

**Comment by reivmeister** [comment]
@starrett67 Yes, got it working after all. I also noticed I had the wrong encrypt.dll file.

**Comment by BriceSD** [comment]
@starrett67 Glad you found a solution. Please close the issue.
