### ISSUE TITLE
Multiple Issues At Login

### ISSUE THREAD

**Issue by fglo11** [PokemonGoF/PokemonGo-Bot#2930]
### Expected Behavior
Sucessful Login and Execution

### Actual Behavior
`2016-08-07 17:19:46,423 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 17:19:46,425 [       cli] [INFO] No config argument specified, checking for /configs/config.json
2016-08-07 17:19:46,444 [       cli] [INFO] Configuration initialized
2016-08-07 17:19:46,444 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more logrmation:
2016-08-07 17:19:46,445 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-07 17:19:46,579 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-07 17:19:48,258 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-07 17:19:48,258 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-07 17:19:48,258 [PokemonGoBot] [INFO] [location_found] Location found: 34.0087, -118.4982 (34.0087, -118.4982, 0.0)
2016-08-07 17:19:48,259 [PokemonGoBot] [INFO] [position_update] Now at (34.0087, -118.4982, 0)
2016-08-07 17:19:48,259 [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "pokecli.py", line 496, in <module>
    main()
  File "pokecli.py", line 130, in main
    report_summary(bot)
  File "pokecli.py", line 139, in report_summary
    metrics.capture_stats()
  File "/Users/Fglosson/PokemonGo-Bot/pokemongo_bot/metrics.py", line 73, in capture_stats
    request = self.bot.api.create_request()
  File "/Users/Fglosson/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 28, in create_request
    self._position_alt
  File "/Users/Fglosson/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 44, in __init__
    PGoApiRequest.__init__(self, *args)
TypeError: __init__() takes exactly 5 arguments (6 given)
2016-08-07 17:19:53,224 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-07 17:19:53,265 [sentry.errors.uncaught] [ERROR] [u'TypeError: __init__() takes exactly 5 arguments (6 given)', u'  File "pokecli.py", line 496, in <module>', u'  File "pokecli.py", line 130, in main', u'  File "pokecli.py", line 139, in report_summary', u'  File "pokemongo_bot/metrics.py", line 73, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 28, in create_request', u'  File "pokemongo_bot/api_wrapper.py", line 44, in __init__']`

### Steps to Reproduce
`python pokecli.py
 `

### Other Information
OS: MAC OS X 10.11.6
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here) b5b3e7048b4d28f8fa5984dc92c54745db82f75f

Python: Python 2.7.12

**Comment by OzanOs** [comment]
had a bunch of errors, too. Try to completly delete everything and reinstall it. 
Another problem I had was setting "use_lucky_egg" in the config.json to true.

**Comment by RedViper9** [comment]
Are you still having this issue? If so please try setting "health_record": false,
If that still doesn't work, please seek help on the slack forum.
