### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c

### ISSUE THREAD

**Issue by stealdre** [PokemonGoF/PokemonGo-Bot#2935]
Hi,
The bot was working fine. But now I always have this error after Pokemon infos (eggs, stardust,...):

Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 129, in main
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8: ordinal not in range(128)
2016-08-07 23:43:31,176 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/paulbeneteau/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/paulbeneteau/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/paulbeneteau/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/paulbeneteau/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/paulbeneteau/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/paulbeneteau/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/paulbeneteau/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/paulbeneteau/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 891, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-07 23:43:31,177 [sentry.errors.uncaught] [ERROR] [u"UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8: ordinal not in range(128)", u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", line 129, in main']

### Other Information
OS: Mac OS 
Git Commit: fddf30dd64322219c945a1aba3483f603ce55bcc
Python Version: Python 2.7.10

**Comment by GitPupper** [comment]
Add this to your Bot directory. https://slack-files.com/T1U6G9ZEW-F1Z21MTPA-ff23e27163

**Comment by shangguokan** [comment]
here is the fix
#2909

**Comment by stealdre** [comment]
Already done. I did it before my first install...

**Comment by stealdre** [comment]
So i replace the one I had with the one you gave me. The error is there before the bot start...

**Comment by stealdre** [comment]
I use this command: wget http://pgoapi.com/pgoencrypt.tar.gz && tar -xf pgoencrypt.tar.gz && cd pgoencrypt/src/ && make && mv libencrypt.so ../../encrypt.so

And then I put the encrypt.so file in the main bot file.

**Comment by BriceSD** [comment]
@stealdre If you set health_record to false if you haven't : 
```
"health_record": false
```

**Comment by ItsOnlyMeNL** [comment]
Had the same error, but when changing the 
`pokemongo_bot/__init__.py` on line 606:
From:
`
self.api.activate_signature("encrypt.so")
`
To:
`
self.api.activate_signature("./encrypt.so")
`

It worked for me.

**Comment by krishven** [comment]
i just copied the encrypt.so into the pogemongo_bot folder
anyway this fix has been merged to master.

**Comment by DimaVIII** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2928
@shangguokan it's a runtime error... stop posting the same "fix" if yo don't understand the error...

**Comment by stealdre** [comment]
@DimaVIII And you don't know to fix it?
