### ISSUE TITLE
Bot cant start.

### ISSUE THREAD

**Issue by Stayhomeforever** [PokemonGoF/PokemonGo-Bot#2936]
I have downloaded encrypt64bit.dll, renamed it to encrypt_64.dll and placed it into the PokemonGo-Bot\. 

Bot cant start.

### Actual Behavior
---------------------------------------------------------------------------------------------------------------
2016-08-07 23:43:30,016 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 23:43:30,017 [       cli] [INFO] No config argument specified, checking for /configs/config.json
2016-08-07 23:43:30,022 [       cli] [INFO] Configuration initialized
2016-08-07 23:43:30,023 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more logrmation:
2016-08-07 23:43:30,025 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-07 23:43:30,033 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-07 23:43:30,125 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-07 23:43:30,130 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-07 23:43:30,134 [PokemonGoBot] [INFO] [location_found] Location found: 48.132788, 11.589186 (48.132788, 11.589186, 0.0)
2016-08-07 23:43:30,138 [PokemonGoBot] [INFO] [position_update] Now at (48.132788, 11.589186, 0)
2016-08-07 23:43:30,141 [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "D:\pb7\PokemonGo-Bot\pokecli.py", line 501, in <module>
    main()
  File "D:\pb7\PokemonGo-Bot\pokecli.py", line 130, in main
    report_summary(bot)
  File "D:\pb7\PokemonGo-Bot\pokecli.py", line 139, in report_summary
    metrics.capture_stats()
  File "D:\pb7\PokemonGo-Bot\pokemongo_bot\metrics.py", line 73, in capture_stats
    request = self.bot.api.create_request()
  File "D:\pb7\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 27, in create_request
    self._position_alt
  File "D:\pb7\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 43, in __init__
    PGoApiRequest.__init__(self, *args)
TypeError: __init__() takes exactly 6 arguments (5 given)
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-Break to quit

---------------------------------------------------------------------------------------------------------

I didn't press any keys. The program quits itself automatically.

### Other Information
OS: win10
Git Commit: fc4e802dd760508e45c9e2f79cdc9704a514b896
Python Version: 2.7.12

### more Infomation

in my config file I have given "auth_service", "username", "password", "location", "gmapkey", "location_cache". Is there any thing wrong?

**Comment by d0s000m** [comment]
Same problem here

ubuntu 14.4
Python 2.7.6
dev

`
2016-08-08 01:08:20,430 [PokemonGoBot] [INFO] [location_found] Location found: 34.009496, -118.499025 (34.009496, -118.499025, 0.0)
2016-08-08 01:08:20,430 [PokemonGoBot] [INFO] [position_update] Now at (34.009496, -118.499025, 0)
2016-08-08 01:08:20,430 [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 131, in main
    report_summary(bot)
  File "pokecli.py", line 140, in report_summary
    metrics.capture_stats()
  File "/home/kvm1/pokesteve/PokemonGo-Bot/pokemongo_bot/metrics.py", line 73, in capture_stats
    request = self.bot.api.create_request()
  File "/home/kvm1/pokesteve/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 27, in create_request
    self._position_alt
  File "/home/kvm1/pokesteve/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 43, in __init__
    PGoApiRequest.__init__(self, *args)
TypeError: __init__() takes exactly 6 arguments (5 given)
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
`

**Comment by d0s000m** [comment]
With master this starts but no loot 

`2016-08-08 01:37:54,385 [FollowSpiral] [INFO] [position_update] Walking from (34.00921732424619, -118.49838398871044, 0) to (34.00921732424619, -118.49901310945235, 0) (57.9890394002 m)
2016-08-08 01:38:18,749 [FollowSpiral] [INFO] [position_update] Walking from (34.00921732424619, -118.49901310945235, 0) to (34.00921732424619, -118.49964223019425, 0) (57.9890394002 m)
2016-08-08 01:38:41,235 [FollowSpiral] [INFO] [position_update] Walking from (34.00921732424619, -118.49964223019425, 0) to (34.009850376742406, -118.49964223019425, 0) (70.3922028344 m)
2016-08-08 01:39:06,445 [FollowSpiral] [INFO] [position_update] Walking from (34.009850376742406, -118.49964223019425, 0) to (34.010483429238626, -118.49964223019425, 0) (70.3922028344 m)
^C2016-08-08 01:39:20,209 [PokemonGoBot] [INFO] [bot_exit] Exiting bot.
2016-08-08 01:39:20,454 [       cli] [INFO]
2016-08-08 01:39:20,454 [       cli] [INFO] Ran for 0:03:11
2016-08-08 01:39:20,454 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-08 01:39:20,454 [       cli] [INFO] Travelled 0.00km
2016-08-08 01:39:20,454 [       cli] [INFO] Visited 0 stops
2016-08-08 01:39:20,454 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-08 01:39:20,454 [       cli] [INFO] Threw 0 pokeballs
2016-08-08 01:39:20,454 [       cli] [INFO] Earned 0 Stardust
2016-08-08 01:39:20,455 [       cli] [INFO]
2016-08-08 01:39:20,455 [       cli] [INFO] Highest CP Pokemon:
2016-08-08 01:39:20,455 [       cli] [INFO] Most Perfect Pokemon:
`

**Comment by Thedyolf** [comment]
Sorry for asking, but where did you find the encrypt64bit.dll at all? I'm just getting notified that encrypt_64.dll is not found. Really hope that there is an easy solution for my problem

**Comment by kendertas** [comment]
I confirm the error

`TypeError: __init__() takes exactly 6 arguments (5 given)`

Kubuntu 16.04
