### ISSUE TITLE
Randomly stops finding pokemons or spinning pokestops

### ISSUE THREAD

**Issue by carlosbellino** [PokemonGoF/PokemonGo-Bot#2941]
### Expected Behavior
Continously spining pokestops and finding pokemons

### Actual Behavior
After a certain time appears this error:

Traceback (most recent call last):
   File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
     msg = self.format(record)
   File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
     return fmt.format(record)
   File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
     record.message = record.getMessage()
   File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
     msg = msg % self.args
 TypeError: not all arguments converted during string formatting
 Logged from file __init__.py, line 547
 2016-08-07 23:57:31,871 [PokemonGoBot] [INFO] [login_started] Login procedure started.
 2016-08-07 23:57:37,741 [PokemonGoBot] [INFO] [login_successful] Login successful.

And then doesnt find any pokemon or spin pokestop

### Steps to Reproduce

Leaving the bot working around an hour

### Other Information
OS: Archlinux (ARM v6)
Git Commit: 153ea212999e337b54e09761f6defbabb0de4e8c
Python Version: Python 2.7.12

**Comment by SGColdSun** [comment]
Update to the newest dev release.
