### ISSUE TITLE
Error at start

### ISSUE THREAD

**Issue by icecubeice** [PokemonGoF/PokemonGo-Bot#2949]
$ ./pokecli.py -cf configs/config.json
[06:47:31] PokemonGO Bot v1.0
[06:47:31] Configuration initialized
[06:47:33] Not logged in!
Traceback (most recent call last):
  File "./pokecli.py", line 452, in <module>
    main()
  File "./pokecli.py", line 85, in main
    report_summary(bot)
  File "./pokecli.py", line 93, in report_summary
    metrics.capture_stats()
  File "C:\Users\Anthony\Downloads\PokemonGo-Bot\PokemonGo-Bot\pokemongo_bot\metrics.py", line 82, in capture_stats
    response_dict = self.bot.api.call()
  File "C:\Users\Anthony\Downloads\PokemonGo-Bot\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 57, in call
    if not self._can_call():
  File "C:\Users\Anthony\Downloads\PokemonGo-Bot\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 29, in _can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException

need help with this

using this guide: https://github.com/PokemonGoF/PokemonGo-Bot/pull/2491

### Other Information
OS: windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by icecubeice** [comment]
Also when I put source bin/activate it wont work it says no such file or directory

**Comment by ddrght12345** [comment]
Original Question:
- Have you double checked the creds you are using?
- Are you running this from a cloud provider? If so, then it's because the IP is banned. Find a different provider, or run it locally

Second Question:
- You havent created the virtual environment.  
`virtualenv .` <-- Note the period at the end

**Comment by icecubeice** [comment]
I did create the virtual environment, but somehow I cant bypass source bin/activate:
$ source bin/activate
bash: bin/activate: No such file or directory
What do you mean cloud provider?

**Comment by ddrght12345** [comment]
You didnt create it. Otherwise the folder would be there.

Cloud provider: AWS, DigitalOcean, Google Cloud, ect
