### ISSUE TITLE
Bot instantly quits

### ISSUE THREAD

**Issue by Sayujya** [PokemonGoF/PokemonGo-Bot#2952]
### Expected Behavior
Bot should start

### Actual Behavior
Bot quits right after login

```
Console output:
2016-08-07 19:18:51,561 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-07 19:18:54,176 [PokemonGoBot] [INFO] 
2016-08-07 19:18:54,176 [PokemonGoBot] [INFO] --- XXXXXXXXXX ---
2016-08-07 19:18:54,176 [PokemonGoBot] [INFO] Level: 20 (Next Level: 49545 XP) (Total: 210455 XP)
2016-08-07 19:18:54,176 [PokemonGoBot] [INFO] Pokemon Captured: 753 | Pokestops Visited: 446
2016-08-07 19:18:54,177 [PokemonGoBot] [INFO] Pokemon Bag: 66/250
2016-08-07 19:18:54,178 [PokemonGoBot] [INFO] Items: 261/350
2016-08-07 19:18:54,178 [PokemonGoBot] [INFO] Stardust: 75300 | Pokecoins: 0
2016-08-07 19:18:54,178 [PokemonGoBot] [INFO] PokeBalls: 41 | GreatBalls: 12 | UltraBalls: 20
2016-08-07 19:18:54,178 [PokemonGoBot] [INFO] RazzBerries: 62 | BlukBerries: 0 | NanabBerries: 0
2016-08-07 19:18:54,178 [PokemonGoBot] [INFO] LuckyEgg: 5 | Incubator: 5 | TroyDisk: 5
2016-08-07 19:18:54,178 [PokemonGoBot] [INFO] Potion: 1 | SuperPotion: 0 | HyperPotion: 50
2016-08-07 19:18:54,179 [PokemonGoBot] [INFO] Incense: 8 | IncenseSpicy: 0 | IncenseCool: 0
2016-08-07 19:18:54,179 [PokemonGoBot] [INFO] Revive: 50 | MaxRevive: 0
2016-08-07 19:18:54,179 [PokemonGoBot] [INFO] 
2016-08-07 19:18:54,179 [PokemonGoBot] [INFO] Found encrypt.so! Platform: darwin Bot root directory: /Users/XXXXXXX/devbot
2016-08-07 19:18:54,179 [PokemonGoBot] [INFO] 
2016-08-07 19:18:56,112 [       cli] [INFO] 
2016-08-07 19:18:56,113 [       cli] [INFO] Ran for 0:00:06
2016-08-07 19:18:56,113 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-07 19:18:56,113 [       cli] [INFO] Travelled 0.00km
2016-08-07 19:18:56,113 [       cli] [INFO] Visited 0 stops
2016-08-07 19:18:56,113 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-07 19:18:56,113 [       cli] [INFO] Threw 0 pokeballs
2016-08-07 19:18:56,113 [       cli] [INFO] Earned 0 Stardust
2016-08-07 19:18:56,113 [       cli] [INFO] 
2016-08-07 19:18:56,113 [       cli] [INFO] Highest CP Pokemon: 
2016-08-07 19:18:56,114 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 501, in <module>
    main()
  File "pokecli.py", line 132, in main
    raise e
IndexError: list index out of range
2016-08-07 19:18:56,139 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/xxxx/devbot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/xxxx/devbot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/xxxx/devbot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/xxxx/devbot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/xxxx/devbot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/xxxx/devbot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/xxxx/devbot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/xxxx/devbot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 891, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-07 19:18:56,146 [sentry.errors.uncaught] [ERROR] [u'IndexError: list index out of range', u'  File "pokecli.py", line 501, in <module>', u'  File "pokecli.py", line 132, in main']
```

### Steps to Reproduce
Run the bot

### Other Information
OS: OSX 10.11.2 El Capital
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by thebringerofdeath789** [comment]
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 129, in main
    raise e
IndexError: list index out of range
2016-08-07 16:21:33,118 [sentry.errors] [ERROR] Sentry responded with an error: 'module' object has no attribute 'HTTPSHandler' (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/unknown/Downloads/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/unknown/Downloads/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/unknown/Downloads/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 44, in urlopen
    class ValidHTTPSHandler(urllib2.HTTPSHandler):
AttributeError: 'module' object has no attribute 'HTTPSHandler'
2016-08-07 16:21:33,119 [sentry.errors.uncaught] [ERROR] [u'IndexError: list index out of range', u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", line 129, in main']

**Comment by iphonitest** [comment]
```
Python: Traceback (most recent call last):
  File "./pokecli.py", line 495, in <module>

Python:     main()
  File "./pokecli.py", line 131, in main
    raise e
IndexError: list index out of range

Python: 2016-08-08 01:12:34,154 [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte

Python: 2016-08-08 01:12:34,159 [sentry.errors.uncaught] [ERROR] [u'IndexError: list index out of range', u'  File "pokecli.py", line 495, in <module>', u'  File "pokecli.py", line 131, in main']
```

**Comment by Sayujya** [comment]
Sorry, likely a copy of #2951
