### ISSUE TITLE
error start if i use gmail address with dot "." or dash "-" character on email address

### ISSUE THREAD

**Issue by akbaribnu** [PokemonGoF/PokemonGo-Bot#2954]
hello dev, your script error if i run with gmail addres with dot or dash character on my email addres, example : hydra.3head@gmail.com
but your script work fine with email address like this: hydra3head@gmail.com

this is error log

2016-08-07 23:32:48,535 [PokemonGoBot] [INFO] Level: 29 (Next Level: 268598 XP) (Total: 1731402 XP)
2016-08-07 23:32:48,535 [PokemonGoBot] [INFO] Pokemon Captured: 5921 | Pokestops Visited: 13661
2016-08-07 23:32:48,537 [PokemonGoBot] [INFO] Pokemon Bag: 163/250
2016-08-07 23:32:48,539 [PokemonGoBot] [INFO] Items: 344/350
2016-08-07 23:32:48,539 [PokemonGoBot] [INFO] Stardust: 556417 | Pokecoins: 10
2016-08-07 23:32:48,539 [PokemonGoBot] [INFO] PokeBalls: 19 | GreatBalls: 9 | UltraBalls: 96
2016-08-07 23:32:48,539 [PokemonGoBot] [INFO] RazzBerries: 36 | BlukBerries: 0 | NanabBerries: 0
2016-08-07 23:32:48,540 [PokemonGoBot] [INFO] LuckyEgg: 0 | Incubator: 0 | TroyDisk: 6
2016-08-07 23:32:48,540 [PokemonGoBot] [INFO] Potion: 10 | SuperPotion: 20 | HyperPotion: 15
2016-08-07 23:32:48,540 [PokemonGoBot] [INFO] Incense: 0 | IncenseSpicy: 0 | IncenseCool: 0
2016-08-07 23:32:48,540 [PokemonGoBot] [INFO] Revive: 30 | MaxRevive: 0
2016-08-07 23:32:48,541 [PokemonGoBot] [INFO]
2016-08-07 23:32:48,541 [PokemonGoBot] [INFO] Found encrypt.so! Platform: linux2 Bot root directory: /root/akbar
2016-08-07 23:32:48,541 [PokemonGoBot] [INFO]
2016-08-07 23:32:53,594 [       cli] [INFO]
2016-08-07 23:32:53,595 [       cli] [INFO] Ran for 0:00:09
2016-08-07 23:32:53,596 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-07 23:32:53,596 [       cli] [INFO] Travelled 0.00km
2016-08-07 23:32:53,596 [       cli] [INFO] Visited 0 stops
2016-08-07 23:32:53,596 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-07 23:32:53,597 [       cli] [INFO] Threw 0 pokeballs
2016-08-07 23:32:53,597 [       cli] [INFO] Earned 0 Stardust
2016-08-07 23:32:53,597 [       cli] [INFO]
2016-08-07 23:32:53,597 [       cli] [INFO] Highest CP Pokemon:
2016-08-07 23:32:53,598 [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 133, in main
    raise e
IndexError: list index out of range
2016-08-07 23:32:53,621 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):

**Comment by zbyte64** [comment]
Two things: disable `health_record` to get red of the codec error. Second modify `pokecli.py` line 133 and change `raise e` to `raise`. That will preserve the original stack trace and show you the original cause of the error.
