### ISSUE TITLE
Bot not catch any pokemon after sometime

### ISSUE THREAD

**Issue by kimdotnet** [PokemonGoF/PokemonGo-Bot#2969]
### Expected Behavior
Move to fort, spin, catch pokemons.

### Actual Behavior
After sometime, bot only walk to fort without catch any pokemon.

### Steps to Reproduce
Run the bot. After 30 - 40 minutes, it should happen.

### Other Information
OS:  WINDOWS 10
commit 420c1be45dc39c42dcbea16a97975c81323bf9d9
Author: AcorpBG <acorpbg@gmail.com>
Date:   Sun Aug 7 14:13:15 2016 +0300

    Fix For catchable not being displayed on the web (#2719)

    * Fix For catchable not being displayed on the web

    * Update catch_visible_pokemon.py

**Comment by sinthu94** [comment]
pokebag full?

**Comment by kimdotnet** [comment]
I think my bag is fine

**Comment by paulohdc** [comment]
for me is always after this error then stops catch any pokemon

2016-08-07 22:58:23,026 [MoveToFort] [INFO] [arrived_at_fort] Arrived at fort.
Traceback (most recent call last):
  File "c:\python27\Lib\logging\__init__.py", line 859, in emit
    msg = self.format(record)
  File "c:\python27\Lib\logging\__init__.py", line 732, in format
    return fmt.format(record)
 File "c:\python27\Lib\logging\__init__.py", line 471, in format
    record.message = record.getMessage()
  File "c:\python27\Lib\logging\__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file __init__.py, line 550
2016-08-07 22:58:23,576 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-07 22:58:26,812 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-07 22:58:32,213 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort Subway 5th  (f08c2e6d331a4bb7aca4c5cf05ab331d.

**Comment by LuisEduardoPS** [comment]
I am having the same issue!

**Comment by rizalblue** [comment]
Yes, i'm having same issue

#######
2016-08-08 11:26:35,772 [MoveToFort] [INFO] [moving_to_lured_fort] Moving toward
s pokestop Happy Tree - 0.08km (attraction of lure 0.54km)
2016-08-08 11:26:46,332 [IncubateEggs] [INFO] [next_egg_incubates] Next egg incu
bates in 1.59 km
2016-08-08 11:26:47,677 [MoveToFort] [INFO] [moving_to_lured_fort] Moving toward
s pokestop Happy Tree - 0.07km (attraction of lure 0.54km)
2016-08-08 11:27:00,957 [MoveToFort] [INFO] [moving_to_lured_fort] Moving toward
s pokestop Happy Tree - 0.07km (attraction of lure 0.53km)
2016-08-08 11:27:13,627 [MoveToFort] [INFO] [moving_to_lured_fort] Moving toward
s pokestop Happy Tree - 0.07km (attraction of lure 0.53km)
2016-08-08 11:27:25,579 [MoveToFort] [INFO] [moving_to_lured_fort] Moving toward
s pokestop Happy Tree - 0.06km (attraction of lure 0.53km)
2016-08-08 11:27:37,388 [MoveToFort] [INFO] [moving_to_lured_fort] Moving toward
s pokestop Happy Tree - 0.06km (attraction of lure 0.53km)
2016-08-08 11:27:49,246 [MoveToFort] [INFO] [moving_to_lured_fort] Moving toward
s pokestop Happy Tree - 0.06km (attraction of lure 0.53km)
2016-08-08 11:28:00,776 [MoveToFort] [INFO] [moving_to_lured_fort] Moving toward
s pokestop Happy Tree - 0.05km (attraction of lure 0.52km)
2016-08-08 11:28:12,799 [MoveToFort] [INFO] [moving_to_lured_fort] Moving toward
s pokestop Happy Tree - 0.05km (attraction of lure 0.52km)
2016-08-08 11:28:25,273 [MoveToFort] [INFO] [moving_to_lured_fort] Moving toward
s pokestop Happy Tree - 0.04km (attraction of lure 0.52km)
2016-08-08 11:28:37,467 [  SpinFort] [INFO] [spun_pokestop] Spun pokestop Happy
Tree. Experience awarded: 50. Items awarded: {u'Pokeball': 2, u'Greatball': 1}
2016-08-08 11:28:40,572 [MoveToFort] [INFO] [moving_to_lured_fort] Moving toward
s pokestop Sinter Claes - 0.09km (attraction of lure 0.52km)
2016-08-08 11:28:53,154 [MoveToFort] [INFO] [moving_to_lured_fort] Moving toward
s pokestop Sinter Claes - 0.09km (attraction of lure 0.52km)
2016-08-08 11:29:05,118 [MoveToFort] [INFO] [moving_to_lured_fort] Moving toward
s pokestop Sinter Claes - 0.08km (attraction of lure 0.51km)

**Comment by yelnatscoding** [comment]
Found a fix yet?

**Comment by tvpman** [comment]
2016-08-08 12:29:40,503 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Kathleen - 0.10km (attraction of lure 0.60km)
2016-08-08 12:29:51,226 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Kathleen - 0.10km (attraction of lure 0.60km)
2016-08-08 12:30:08,813 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Kathleen - 0.09km (attraction of lure 0.60km)
2016-08-08 12:30:18,636 [IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 4.49 km
2016-08-08 12:30:20,375 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Kathleen - 0.09km (attraction of lure 0.60km)
2016-08-08 12:30:31,857 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Kathleen - 0.08km (attraction of lure 0.60km)
2016-08-08 12:30:43,207 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Cherub Pottery - 0.09km (attraction of lure 0.62km)
2016-08-08 12:30:55,825 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Cherub Pottery - 0.09km (attraction of lure 0.62km)
2016-08-08 12:31:06,208 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Cherub Pottery - 0.08km (attraction of lure 0.61km)
2016-08-08 12:31:16,719 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Kathleen - 0.07km (attraction of lure 0.59km)
2016-08-08 12:31:26,336 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Cherub Pottery - 0.08km (attraction of lure 0.59km)
2016-08-08 12:31:36,063 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Cherub Pottery - 0.08km (attraction of lure 0.58km)
2016-08-08 12:31:46,714 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Cherub Pottery - 0.07km (attraction of lure 0.58km)
2016-08-08 12:31:56,786 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Cherub Pottery - 0.07km (attraction of lure 0.58km)
2016-08-08 12:32:06,273 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Cherub Pottery - 0.07km (attraction of lure 0.57km)
2016-08-08 12:32:15,866 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Cherub Pottery - 0.06km (attraction of lure 0.57km)
2016-08-08 12:32:25,690 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Cherub Pottery - 0.06km (attraction of lure 0.56km)
2016-08-08 12:32:35,797 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Cherub Pottery - 0.05km (attraction of lure 0.56km



same issue here...

**Comment by paulohdc** [comment]
https://github.com/mico/PokemonGo-Bot/commit/513aae3873869f90bd2ca0c5465072ead8c56aaa

**Comment by nealqu** [comment]
I have the same issue. Catches 1-2 pokemons upon starting and just moves around after.
