### ISSUE TITLE
Start Issue

### ISSUE THREAD

**Issue by OVO647** [PokemonGoF/PokemonGo-Bot#2974]
2016-08-07 22:06:09,921 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 22:06:09,922 [       cli] [INFO] No config argument specified, checking for /configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 133, in main
    raise e
ValueError: No JSON object could be decoded

**Comment by OVO647** [comment]
Yes its in the configs folder named config.json

**Comment by SGColdSun** [comment]
Have you tried specifying it just in case?

./pokecli.py -cf configs/config.json

**Comment by OVO647** [comment]
Says permission denied.

**Comment by SGColdSun** [comment]
Make sure the file owner is correct, and that the permissions are 755.

**Comment by OVO647** [comment]
How do I do that?
