### ISSUE TITLE
map cells error from response

### ISSUE THREAD

**Issue by felixgao** [PokemonGoF/PokemonGo-Bot#2981]
### Actual Behavior
2016-08-07 20:22:26,763 [ search_worker_9][        search][   ERROR] Search step 10 map parsing failed, retrying request in 10.5 seconds
Traceback (most recent call last):
  File "/Users/me/Projects/github/PokemonGo-Map/pogom/search.py", line 236, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "/Users/me/Projects/github/PokemonGo-Map/pogom/models.py", line 296, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

### Steps to Reproduce
python2.7 runserver.py -l "37.803884,-122.4291086" -u username -p password -sd 10.5 -st 5

### Other Information
OS:  OSX El Captian
Git Commit: 58795cecae95256a1fcc5830d51b170103b8460d
Python Version: Python 2.7.12

**Comment by k4n30** [comment]
Wrong issue tracker. You're looking for https://github.com/PokemonGoMap/PokemonGo-Map/issues
