### ISSUE TITLE
unable to catch pokemon with 15/15/15 or 100% iv. 

### ISSUE THREAD

**Issue by jelly0648** [PokemonGoF/PokemonGo-Bot#2983]
### Expected Behavior
to catch pokemon with 100% iv

### Actual Behavior
KeyError: 'new_catch_rate'
2016-08-08 11:33:36,215 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/programmer/.local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/programmer/.local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/programmer/.local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/programmer/.local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-08 11:33:36,301 [sentry.errors.uncaught] [ERROR] [u"KeyError: 'new_catch_rate'", u'  File "pokecli.py", line 502, in <module>', u'  File "pokecli.py", line 133, in main']

### Other Information
OS: ubuntu 16.04
Git Commit: 0855dac7c34cc46b69af9bd4e708e6d172498b31
Python Version: Python 2.7.12

**Comment by JaydenHamence** [comment]
is this for everyone?

**Comment by homegrow** [comment]
Same here. OSX 10.11.6

I had it with a lower Pokemon. This may has something to do with VIPs?

2016-08-08 14:36:59,081 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Rattata appeared! [CP 340] [Potential 0.82] [S/A/D 9/15/13]
2016-08-08 14:37:02,294 [PokemonCatchWorker] [INFO] [vip_pokemon] This is a VIP pokemon. Catch!!!
2016-08-08 14:37:02,932 [       cli] [INFO]
2016-08-08 14:37:02,932 [       cli] [INFO] Ran for 0:42:07
2016-08-08 14:37:02,933 [       cli] [INFO] Total XP Earned: 3305  Average: 4708.48/h
2016-08-08 14:37:02,933 [       cli] [INFO] Travelled 3.74km
2016-08-08 14:37:02,933 [       cli] [INFO] Visited 26 stops
2016-08-08 14:37:02,934 [       cli] [INFO] Encountered 10 pokemon, 8 caught, 3 released, 0 evolved, 0 never seen before
2016-08-08 14:37:02,934 [       cli] [INFO] Threw 11 pokeballs
2016-08-08 14:37:02,934 [       cli] [INFO] Earned 1204 Stardust
2016-08-08 14:37:02,934 [       cli] [INFO]
2016-08-08 14:37:02,934 [       cli] [INFO] Highest CP Pokemon: Squirtle [CP: 541] [IV: 0/11/11] Potential: 0.49
2016-08-08 14:37:02,935 [       cli] [INFO] Most Perfect Pokemon: Rattata [CP: 280] [IV: 9/6/13] Potential: 0.62
Traceback (most recent call last):
  File "pokecli.py", line 503, in <module>
    main()
  File "pokecli.py", line 89, in main
    bot.tick()
  File "/Users/~/Applications/PokemonGo-Bot/pokemongo_bot/__init__.py", line 434, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/Users/~/Applications/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 36, in work
    return self.catch_pokemon(self.bot.cell['catchable_pokemons'].pop(0))
  File "/Users/~/Applications/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 48, in catch_pokemon
    return_value = worker.work()
  File "/Users/~/Applications/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 110, in work
    'berry_count': berries_count
  File "/Users/~/Applications/PokemonGo-Bot/pokemongo_bot/base_task.py", line 27, in emit_event
    data=data
  File "/Users/~/Applications/PokemonGo-Bot/pokemongo_bot/event_manager.py", line 61, in emit
    formatted_msg = formatted.format(**data)
KeyError: 'new_catch_rate'
2016-08-08 14:37:02,967 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/~/Applications/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/~/Applications/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/~/Applications/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/~/Applications/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/~/Applications/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/~/Applications/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/~/Applications/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/~/Applications/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 891, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-08 14:37:02,976 [sentry.errors.uncaught] [ERROR] [u"KeyError: 'new_catch_rate'", u'  File "pokecli.py", line 503, in <module>', u'  File "pokecli.py", line 89, in main', u'  File "pokemongo_bot/__init__.py", line 434, in tick', u'  File "pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 36, in work', u'  File "pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 48, in catch_pokemon', u'  File "pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 110, in work', u'  File "pokemongo_bot/base_task.py", line 27, in emit_event', u'  File "pokemongo_bot/event_manager.py", line 61, in emit']

**Comment by ThunderVamp9** [comment]
Encountered this today also. 

If it's something to do with VIP's, perhaps this line in the config?

`"Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},`

Should be 

`"// Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},`

Seems to me that without the //, the config is actually trying to use that line when it's meant to be a comment?

**Comment by DustySky** [comment]
I have the same problem.
Traceback (most recent call last):
  File "pokecli.py", line 503, in <module>
    main()
  File "pokecli.py", line 89, in main
    bot.tick()
  File "/home/scott/PokemonGo-Bot/pokemongo_bot/__init__.py", line 441, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/scott/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 36, in work
    return self.catch_pokemon(self.bot.cell['catchable_pokemons'].pop(0))
  File "/home/scott/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 48, in catch_pokemon
    return_value = worker.work()
  File "/home/scott/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 110, in work
    'berry_count': berries_count
  File "/home/scott/PokemonGo-Bot/pokemongo_bot/base_task.py", line 27, in emit_event
    data=data
  File "/home/scott/PokemonGo-Bot/pokemongo_bot/event_manager.py", line 61, in emit
    formatted_msg = formatted.format(**data)
KeyError: 'new_catch_rate'

I have the cell worker file that adds color. I got this error message when I installed the color files. When removed, there is no problem.

**Comment by homegrow** [comment]
Same for me. It was the cell_worker folder. Dunno where the bug appears. After changing to the old one it worked normal again. Didn't walk it through for any issues, may just wait for the dev implement anyways...

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this has been resolved.
