### ISSUE TITLE
Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by LightAMV** [PokemonGoF/PokemonGo-Bot#2990]
```
2016-08-07 21:02:58,621 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 21:02:58,622 [       cli] [INFO] No config argument specified, checking for /configs/config.json
2016-08-07 21:02:58,625 [       cli] [INFO] Configuration initialized
2016-08-07 21:02:58,625 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more informat                             ion:
2016-08-07 21:02:58,625 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bo                             t/tree/dev#analytics
2016-08-07 21:02:58,688 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.g                             oogle-analytics.com
2016-08-07 21:02:59,017 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-07 21:02:59,990 [PokemonGoBot] [INFO] [location_found] Location found: 100 Aquarium Way, Long Beach, CA 9                             0802 (33.7621452, -118.1969144, 0.0)
2016-08-07 21:02:59,992 [PokemonGoBot] [INFO] [position_update] Now at (33.7621452, -118.1969144, 0)
2016-08-07 21:02:59,992 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-07 21:03:01,490 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-07 21:03:02,703 [PokemonGoBot] [INFO]
2016-08-07 21:03:02,703 [PokemonGoBot] [INFO] --- (CENSORED) ---
2016-08-07 21:03:02,703 [PokemonGoBot] [INFO] Level: 25 (Next Level: 179395 XP) (Total: 720605 XP)
2016-08-07 21:03:02,703 [PokemonGoBot] [INFO] Pokemon Captured: 1853 | Pokestops Visited: 2706
2016-08-07 21:03:02,703 [PokemonGoBot] [INFO] Pokemon Bag: 82/250
2016-08-07 21:03:02,704 [PokemonGoBot] [INFO] Items: 250/350
2016-08-07 21:03:02,704 [PokemonGoBot] [INFO] Stardust: 260 | Pokecoins: 0
2016-08-07 21:03:02,704 [PokemonGoBot] [INFO] PokeBalls: 0 | GreatBalls: 20 | UltraBalls: 75
2016-08-07 21:03:02,704 [PokemonGoBot] [INFO] RazzBerries: 74 | BlukBerries: 0 | NanabBerries: 0
2016-08-07 21:03:02,704 [PokemonGoBot] [INFO] LuckyEgg: 1 | Incubator: 5 | TroyDisk: 6
2016-08-07 21:03:02,704 [PokemonGoBot] [INFO] Potion: 0 | SuperPotion: 0 | HyperPotion: 16
2016-08-07 21:03:02,706 [PokemonGoBot] [INFO] Incense: 9 | IncenseSpicy: 0 | IncenseCool: 0
2016-08-07 21:03:02,706 [PokemonGoBot] [INFO] Revive: 22 | MaxRevive: 0
2016-08-07 21:03:02,706 [PokemonGoBot] [INFO]
2016-08-07 21:03:02,813 [       cli] [INFO]
2016-08-07 21:03:02,813 [       cli] [INFO] Ran for 0:00:04
2016-08-07 21:03:02,815 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-07 21:03:02,815 [       cli] [INFO] Travelled 0.00km
2016-08-07 21:03:02,815 [       cli] [INFO] Visited 0 stops
2016-08-07 21:03:02,815 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-07 21:03:02,815 [       cli] [INFO] Threw 0 pokeballs
2016-08-07 21:03:02,815 [       cli] [INFO] Earned 0 Stardust
2016-08-07 21:03:02,815 [       cli] [INFO]
2016-08-07 21:03:02,815 [       cli] [INFO] Highest CP Pokemon:
2016-08-07 21:03:02,815 [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 75, in main
    bot.start()

2016-08-07 21:03:02,891 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\raven\transport\threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "C:\Python27\lib\site-packages\raven\transport\http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 494, in open
    response = self._open(req, data)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 512, in _open
    '_open', req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python27\lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-07 21:03:02,894 [sentry.errors.uncaught] [ERROR] [u"UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 37: ordinal not in range(128)", u'  File "pokecli.py", line 502, in <module>', u'  File "pokecli.py", line 75, in main', u'  File "C:\\Users\\erdel\\Documents\\LightAMV\\Pok\ufffdmon GO\\PokemonGo-Bot\\pokemongo_bot\\__init__.py", line 75, in start', u'  File "C:\\Users\\erdel\\Documents\\LightAMV\\Pok\ufffdmon GO\\PokemonGo-Bot\\pokemongo_bot\\__init__.py", line 672, in _setup_api', u'  File "C:\\Users\\erdel\\Documents\\LightAMV\\Pok\ufffdmon GO\\PokemonGo-Bot\\pokemongo_bot\\__init__.py", line 650, in get_encryption_lib']
```

**Comment by Sculay** [comment]
Getting the same issue by on cygwin

**Comment by chypriote** [comment]
Same error both on Windows 10 and Ubuntu 15.10
I have `"health_record": false`

**Comment by LightAMV** [comment]
I'll leave this opened until a fixed response.
