### ISSUE TITLE
Import error after update

### ISSUE THREAD

**Issue by rlllam** [PokemonGoF/PokemonGo-Bot#2996]
Gave me this error:

$ python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
  File "c:\users\jeff\desktop\pgb\pokemongo-bot\src\pgoapi\pgoapi\__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "c:\users\jeff\desktop\pgb\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "c:\users\jeff\desktop\pgb\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 47, in <module>
    from pgoapi.utilities import to_camel_case, get_time, get_format_time_diff, Rand48, long_to_bytes, generateLocation1, generateLocation2, generateRequestHash, f2i
  File "c:\users\jeff\desktop\pgb\pokemongo-bot\src\pgoapi\pgoapi\utilities.py", line 30, in <module>
    import xxhash
ImportError: DLL load failed: %1 is not a valid Win32 application.

I'm running windows 10 64bit and python 64bit
Also i've noticed the config.json file has a new line "libencrypt_location": which I dont know what to put in

**Comment by zviper13579** [comment]
same error.

$ python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions

OSX

**Comment by ksiamro** [comment]
(PokemonGo-Bot) ➜  PokemonGo-Bot git:(dev) ✗ python pokecli.py -cf ./configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
  File "/home/konrad/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/home/konrad/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/home/konrad/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 47, in <module>
    from pgoapi.utilities import to_camel_case, get_time, get_format_time_diff, Rand48, long_to_bytes, generateLocation1, generateLocation2, generateRequestHash, f2i
  File "/home/konrad/PokemonGo-Bot/src/pgoapi/pgoapi/utilities.py", line 30, in <module>
    import xxhash
ImportError: No module named xxhash

**Comment by ksiamro** [comment]
up

**Comment by srobayo222** [comment]
Same error for me

**Comment by HelloTroy** [comment]
Same error, Linux.
Worked for about 30 minutes, crashed and now no module named xxhash

**Comment by HelloTroy** [comment]
I was able to fix it by doing:
$git pull
$install -r requirements.txt

Run

**Comment by GitPupper** [comment]
Make sure your encrypt file is correct.
***
**Windows**
`encrypt.dll`
or
`encrypt.so`
***
**macOS / Linux**
`encrypt.so`
