### ISSUE TITLE
Pokecli.py line 501

### ISSUE THREAD

**Issue by Elim160** [PokemonGoF/PokemonGo-Bot#3004]
2016-08-08 01:46:18,612 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-08 01:46:18,613 [       cli] [INFO] No config argument specified, checking for /configs/config.json
2016-08-08 01:46:18,615 [       cli] [INFO] Configuration initialized
2016-08-08 01:46:18,615 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more logrmation:
2016-08-08 01:46:18,615 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-08 01:46:18,717 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-08 01:46:19,316 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
Traceback (most recent call last):
  File "pokecli.py", line 501, in <module>
    main()
  File "pokecli.py", line 130, in main
    report_summary(bot)
  File "pokecli.py", line 139, in report_summary
    metrics.capture_stats()
  File "/Users/Eli/Desktop/PokemoniG/PokemonGo-Bot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/Users/Eli/Desktop/PokemoniG/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 90, in call
    if not self.can_call():
  File "/Users/Eli/Desktop/PokemoniG/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 54, in can_call
    raise NoPlayerPositionSetException()
pgoapi.exceptions.NoPlayerPositionSetException
2016-08-08 01:46:19,757 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/Eli/Desktop/PokemoniG/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/Eli/Desktop/PokemoniG/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/Eli/Desktop/PokemoniG/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/Eli/Desktop/PokemoniG/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/Eli/Desktop/PokemoniG/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/Eli/Desktop/PokemoniG/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/Eli/Desktop/PokemoniG/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/Eli/Desktop/PokemoniG/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-08 01:46:19,768 [sentry.errors.uncaught] [ERROR] [u'NoPlayerPositionSetException', u'  File "pokecli.py", line 501, in <module>', u'  File "pokecli.py", line 130, in main', u'  File "pokecli.py", line 139, in report_summary', u'  File "pokemongo_bot/metrics.py", line 76, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 90, in call', u'  File "pokemongo_bot/api_wrapper.py", line 54, in can_call']

getting this huge error after setting my location to "Pier 39, San Francisco, California"

**Comment by SGColdSun** [comment]
Does the issue come up when you try a different location? If so, use one close by to your desired one.

**Comment by Elim160** [comment]
@SGColdSun No it dose not, I just was using California and it was working great.

**Comment by Elim160** [comment]
Nvm got it, all I had to do was go on google maps and see what it was labeled as.
