### ISSUE TITLE
[ERROR] [u'IndexError: list index out of range'...

### ISSUE THREAD

**Issue by firzzen** [PokemonGoF/PokemonGo-Bot#3008]
### Expected Behavior

1) Bot should reach pokestops, catch pokemon and not crash.
2) Bot should keep trying to log in if servers are too busy.

### Actual Behavior

Bot crashes after some time of walking around trying to get some pokestops but "being too far" to reach them. Eventually either the bot just crashes or the "servers are too busy", keeps trying to login and then crashes. Bot should keep trying to login but it crashes.

This happened last night with three bots, all PTC accounts, but at the same time other PTC accounts were botting just fine. All different regions of the planet.

Two of the crashed bots had problems with spinning pokestops. One simply tried to login and servers were too busy. 

### Steps to Reproduce

Not sure how exactly to reproduce this apart from just running the bot and hoping it would stop reaching pokestops and catching pokemon. There doesn't seem to be any reason why it starts doing so.

**Find logs from three bots since the last pokemon catch below, sorry for the huge amount of logs:**

2016-08-08 01:57:40,226 [PokemonCatchWorker] [INFO] [pokemon_caught] Captured Magikarp! [CP 66] [Potential 0.4] [14/2/2] [+210 exp]
2016-08-08 01:57:40,710 [PokemonCatchWorker] [INFO] [pokemon_evolve_fail] Failed to evolve Magikarp!
2016-08-08 01:57:45,740 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Vanha Kauppahalli - 0.09km (attraction of lure 0.16km)
2016-08-08 01:57:54,244 [TransferPokemon] [INFO] [keep_best_release] Keeping best 1 Magikarp, based on cp
2016-08-08 01:57:54,622 [TransferPokemon] [INFO] [pokemon_release] Exchanged Magikarp [CP 66] [IV 0.4] for candy.
2016-08-08 01:57:57,017 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Vanha Kauppahalli - 0.08km (attraction of lure 0.15km)
2016-08-08 01:58:04,535 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Vanha Kauppahalli - 0.07km (attraction of lure 0.14km)
2016-08-08 01:58:12,906 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Vanha Kauppahalli - 0.05km (attraction of lure 0.14km)
2016-08-08 01:58:21,096 [  SpinFort] [INFO] [pokestop_out_of_range] Pokestop Vanha Kauppahalli out of range.
2016-08-08 01:58:21,096 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
..............................................
2016-08-08 02:07:43,311 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-08 02:07:43,318 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop War Bird - 0.10km (attraction of lure 0.14km)
2016-08-08 02:07:45,569 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop War Bird - 0.09km (attraction of lure 0.14km)
2016-08-08 02:07:47,575 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop War Bird - 0.08km (attraction of lure 0.13km)
2016-08-08 02:07:54,493 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop War Bird - 0.07km (attraction of lure 0.13km)
2016-08-08 02:07:57,126 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Army Of Turtles - 0.13km (attraction of lure 0.13km)
2016-08-08 02:07:59,225 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Army Of Turtles - 0.12km (attraction of lure 0.12km)
2016-08-08 02:08:16,968 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 4/15
2016-08-08 02:09:33,666 [       cli] [INFO]
2016-08-08 02:09:33,667 [       cli] [INFO] Ran for 1:26:41
2016-08-08 02:09:33,667 [       cli] [INFO] Total XP Earned: 20800  Average: 14396.84/h
2016-08-08 02:09:33,668 [       cli] [INFO] Travelled 4.50km
2016-08-08 02:09:33,668 [       cli] [INFO] Visited 83 stops
2016-08-08 02:09:33,668 [       cli] [INFO] Encountered 45 pokemon, 45 caught, 0 released, 7 evolved, 5 never seen before
2016-08-08 02:09:33,668 [       cli] [INFO] Threw 53 pokeballs
2016-08-08 02:09:33,669 [       cli] [INFO] Earned 7072 Stardust
2016-08-08 02:09:33,669 [       cli] [INFO]
2016-08-08 02:09:33,669 [       cli] [INFO] Highest CP Pokemon: Psyduck [CP: 520] [IV: 0/11/10] Potential: 0.47
2016-08-08 02:09:33,669 [       cli] [INFO] Most Perfect Pokemon: Magikarp [CP: 33] [IV: 15/13/10] Potential: 0.84
Traceback (most recent call last):
  File "pokecli.py", line 501, in <module>
    main()
  File "pokecli.py", line 132, in main
    raise e
IndexError: list index out of range
2016-08-08 02:09:33,683 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1048, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1088, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1044, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 886, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-08 02:09:33,686 [sentry.errors.uncaught] [ERROR] [u'IndexError: list index out of range', u'  File "pokecli.py", line 501, in <module>', u'  File "pokecli.py", line 132, in main']

**From the second bot:**

2016-08-08 01:57:59,014 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Pidgey appeared! [CP 217] [Potential 0.27] [S/A/D 4/7/1]
2016-08-08 01:58:02,411 [PokemonCatchWorker] [INFO] [threw_pokeball] Used Pokeball, with chance 40.01 (78 left)
2016-08-08 01:58:03,182 [PokemonCatchWorker] [INFO] [pokemon_fled] Pidgey fled.
2016-08-08 01:58:05,639 [PokemonCatchWorker] [INFO] [threw_pokeball] Used Pokeball, with chance 40.01 (77 left)
2016-08-08 01:58:06,446 [PokemonCatchWorker] [INFO] [pokemon_caught] Captured Pidgey! [CP 217] [Potential 0.27] [4/7/1] [+210 exp]
2016-08-08 01:58:08,022 [PokemonCatchWorker] [INFO] [pokemon_evolve_fail] Failed to evolve Pidgey!
2016-08-08 01:58:13,431 [  SpinFort] [INFO] [spun_pokestop] Spun pokestop City Employees War Memorial Flagpole. Experience awarded: 50. Items awarded: {u'Pokeball': 3}
2016-08-08 01:58:15,804 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Beethoven Statue - 0.07km (attraction of lure 0.09km)
2016-08-08 01:58:27,487 [TransferPokemon] [INFO] [keep_best_release] Keeping best 1 Pidgey, based on cp
2016-08-08 01:58:27,912 [TransferPokemon] [INFO] [pokemon_release] Exchanged Pidgey [CP 217] [IV 0.27] for candy.
2016-08-08 01:58:29,675 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Beethoven Statue - 0.06km (attraction of lure 0.08km)
2016-08-08 01:58:38,211 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Beethoven Statue - 0.04km (attraction of lure 0.07km)
2016-08-08 01:58:40,656 [  SpinFort] [INFO] [pokestop_out_of_range] Pokestop Beethoven Statue out of range.
2016-08-08 01:58:40,657 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-08 01:58:40,662 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Victor Herbert Statue - 0.05km (attraction of lure 0.05km)
2016-08-08 01:58:43,586 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Victor Herbert Statue - 0.04km (attraction of lure 0.04km)
2016-08-08 01:58:45,880 [  SpinFort] [INFO] [pokestop_out_of_range] Pokestop Victor Herbert Statue out of range.
2016-08-08 01:58:45,880 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
..............................
2016-08-08 01:59:30,107 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop John Lennon Quote Memorial Plaque - 0.08km (attraction of lure 0.08km)
2016-08-08 01:59:32,542 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort Big Flower Base Sculpture (5faefd305fef4937b857f39ccd2599c1.16)
2016-08-08 01:59:37,880 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop John Lennon Quote Memorial Plaque - 0.07km (attraction of lure 0.07km)
2016-08-08 01:59:39,419 [PokemonGoBot] [INFO] [api_error] Session stale, re-logging in.
2016-08-08 01:59:39,427 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-08 02:00:10,756 [PokemonGoBot] [INFO] [login_failed] Login error, server busy. Waiting 10 seconds to try again.
2016-08-08 02:00:22,640 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-08 02:00:22,641 [PokemonGoBot] [INFO] Found encrypt.so! Platform: linux2 Bot root directory: /******/PokemonGo-Bot-dev
2016-08-08 02:00:23,771 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort Big Flower Base Sculpture (5faefd305fef4937b857f39ccd2599c1.16)
2016-08-08 02:00:29,111 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop John Lennon Quote Memorial Plaque - 0.06km (attraction of lure 0.06km)
2016-08-08 02:00:31,520 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort John Lennon Quote Memorial Plaque (9f1e301631f143558f8543400956d878.16)
2016-08-08 02:00:36,831 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop John Lennon Quote Memorial Plaque - 0.04km (attraction of lure 0.04km)
2016-08-08 02:00:40,106 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort John Lennon Quote Memorial Plaque (9f1e301631f143558f8543400956d878.16)
2016-08-08 02:00:45,943 [  SpinFort] [INFO] [pokestop_out_of_range] Pokestop John Lennon Quote Memorial Plaque out of range.
2016-08-08 02:00:45,949 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-08 02:00:46,208 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Die Statue des schottischen Di - 0.09km (attraction of lure 0.19km)
2016-08-08 02:00:49,458 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort John Lennon Quote Memorial Plaque (9f1e301631f143558f8543400956d878.16)
2016-08-08 02:00:55,143 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Die Statue des schottischen Di - 0.08km (attraction of lure 0.18km)
.........
2016-08-08 02:08:31,716 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort In Memory (ea4a2f7adba14c86be4badcf33b5f169.16)
2016-08-08 02:08:37,034 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop In Memory - 0.05km (attraction of lure 0.05km)
2016-08-08 02:08:50,302 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Pidgey appeared! [CP 329] [Potential 0.6] [S/A/D 11/12/4]
2016-08-08 02:08:53,856 [PokemonCatchWorker] [INFO] [threw_pokeball] Used Greatball, with chance 46.80 (40 left)
2016-08-08 02:08:54,646 [PokemonCatchWorker] [INFO] [pokemon_caught] Captured Pidgey! [CP 329] [Potential 0.6] [11/12/4] [+210 exp]
2016-08-08 02:08:55,215 [PokemonCatchWorker] [INFO] [pokemon_evolved] Pidgey evolved!
2016-08-08 02:09:00,233 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop In Memory - 0.04km (attraction of lure 0.07km)
2016-08-08 02:09:11,456 [IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 1.10 km
2016-08-08 02:09:12,076 [TransferPokemon] [INFO] [keep_best_release] Keeping best 1 Pidgeotto, based on cp
2016-08-08 02:09:12,483 [TransferPokemon] [INFO] [pokemon_release] Exchanged Pidgeotto [CP 613] [IV 0.6] for candy.
2016-08-08 02:09:21,714 [  SpinFort] [INFO] [spun_pokestop] Spun pokestop In Memory. Experience awarded: 50. Items awarded: {u'Razz Berry': 1, u'Pokeball': 1, u'Revive': 1}
2016-08-08 02:09:23,989 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Columbus - 0.06km (attraction of lure 0.06km)
2016-08-08 02:09:36,866 [RecycleItems] [INFO] [item_discarded] Discarded 1x Pokeball (maximum 80).
2016-08-08 02:09:37,210 [RecycleItems] [INFO] [item_discarded] Discarded 1x Revive (maximum 0).
2016-08-08 02:09:37,231 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Columbus - 0.04km (attraction of lure 0.04km)
2016-08-08 02:09:48,133 [  SpinFort] [INFO] [spun_pokestop] Spun pokestop Columbus. Experience awarded: 50. Items awarded: {u'Razz Berry': 1, u'Pokeball': 2, u'Greatball': 1}
2016-08-08 02:09:50,453 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop The Dairy - 0.10km (attraction of lure 0.10km)
2016-08-08 02:10:14,655 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 4/15
2016-08-08 02:10:16,140 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 5/15
2016-08-08 02:10:17,240 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 6/15
2016-08-08 02:10:18,205 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 7/15
2016-08-08 02:10:19,641 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 8/15
2016-08-08 02:10:52,628 [       cli] [INFO]
2016-08-08 02:10:52,633 [       cli] [INFO] Ran for 1:38:41
2016-08-08 02:10:52,634 [       cli] [INFO] Total XP Earned: 37715  Average: 22930.69/h
2016-08-08 02:10:52,634 [       cli] [INFO] Travelled 2.65km
2016-08-08 02:10:52,634 [       cli] [INFO] Visited 85 stops
2016-08-08 02:10:52,634 [       cli] [INFO] Encountered 107 pokemon, 104 caught, 0 released, 20 evolved, 1 never seen before
2016-08-08 02:10:52,635 [       cli] [INFO] Threw 117 pokeballs
2016-08-08 02:10:52,635 [       cli] [INFO] Earned 13108 Stardust
2016-08-08 02:10:52,635 [       cli] [INFO]
2016-08-08 02:10:52,635 [       cli] [INFO] Highest CP Pokemon: Pinsir [CP: 1293] [IV: 14/6/2] Potential: 0.49
2016-08-08 02:10:52,636 [       cli] [INFO] Most Perfect Pokemon: Tauros [CP: 931] [IV: 15/15/9] Potential: 0.87
Traceback (most recent call last):
  File "pokecli.py", line 501, in <module>
    main()
  File "pokecli.py", line 132, in main
    raise e
IndexError: list index out of range
2016-08-08 02:10:52,660 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1048, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1088, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1044, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 886, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-08 02:10:52,667 [sentry.errors.uncaught] [ERROR] [u'IndexError: list index out of range', u'  File "pokecli.py", line 501, in <module>', u'  File "pokecli.py", line 132, in main']

**Bot number three:**

2016-08-08 01:58:14,789 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Poliwag appeared! [CP 326] [Potential 0.69] [S/A/D 4/12/15]
2016-08-08 01:58:18,318 [PokemonCatchWorker] [INFO] [threw_pokeball] Used Pokeball, with chance 37.43 (79 left)
2016-08-08 01:58:37,364 [PokemonGoBot] [INFO] [api_error] Server is throttling, reconnecting in 30 seconds
2016-08-08 01:59:07,413 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-08 01:59:07,416 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-08 01:59:07,417 [PokemonGoBot] [INFO] [location_found] Location found: *********
2016-08-08 01:59:07,418 [PokemonGoBot] [INFO] [position_update] Now at (************)
2016-08-08 01:59:07,419 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-08 01:59:09,138 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-08 01:59:09,618 [PokemonGoBot] [INFO]
2016-08-08 01:59:09,619 [PokemonGoBot] [INFO] --- *******i ---
2016-08-08 01:59:09,619 [PokemonGoBot] [INFO] Level: 17 (Next Level: 18160 XP) (Total: 141840 XP)
2016-08-08 01:59:09,619 [PokemonGoBot] [INFO] Pokemon Captured: 359 | Pokestops Visited: 372
2016-08-08 01:59:09,620 [PokemonGoBot] [INFO] Pokemon Bag: 56/250
2016-08-08 01:59:09,620 [PokemonGoBot] [INFO] Items: 321/350
2016-08-08 01:59:09,620 [PokemonGoBot] [INFO] Stardust: 48604 | Pokecoins: 0
2016-08-08 01:59:09,621 [PokemonGoBot] [INFO] PokeBalls: 80 | GreatBalls: 176 | UltraBalls: 0
2016-08-08 01:59:09,621 [PokemonGoBot] [INFO] RazzBerries: 50 | BlukBerries: 0 | NanabBerries: 0
2016-08-08 01:59:09,621 [PokemonGoBot] [INFO] LuckyEgg: 3 | Incubator: 1 | TroyDisk: 3
2016-08-08 01:59:09,622 [PokemonGoBot] [INFO] Potion: 0 | SuperPotion: 0 | HyperPotion: 0
2016-08-08 01:59:09,622 [PokemonGoBot] [INFO] Incense: 6 | IncenseSpicy: 0 | IncenseCool: 0
2016-08-08 01:59:09,622 [PokemonGoBot] [INFO] Revive: 0 | MaxRevive: 0
2016-08-08 01:59:09,622 [PokemonGoBot] [INFO]
2016-08-08 01:59:09,622 [PokemonGoBot] [INFO] Found encrypt.so! Platform: linux2 Bot root directory: /********/PokemonGo-Bot-dev
2016-08-08 01:59:09,623 [PokemonGoBot] [INFO]
2016-08-08 01:59:09,866 [SleepSchedule] [INFO] [next_sleep] Next sleep at 2016-08-08 23:44:53.866639
2016-08-08 01:59:10,184 [PokemonGoBot] [INFO] [bot_start] Starting bot...
2016-08-08 01:59:10,543 [CollectLevelUpReward] [INFO] [level_up_reward] Received level up reward: []
2016-08-08 02:07:33,181 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 4/15
2016-08-08 02:07:34,581 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 5/15
2016-08-08 02:08:03,771 [       cli] [INFO]
2016-08-08 02:08:03,772 [       cli] [INFO] Ran for 0:08:56
2016-08-08 02:08:03,772 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-08 02:08:03,772 [       cli] [INFO] Travelled 0.00km
2016-08-08 02:08:03,772 [       cli] [INFO] Visited 0 stops
2016-08-08 02:08:03,773 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-08 02:08:03,773 [       cli] [INFO] Threw 0 pokeballs
2016-08-08 02:08:03,773 [       cli] [INFO] Earned 0 Stardust
2016-08-08 02:08:03,773 [       cli] [INFO]
2016-08-08 02:08:03,773 [       cli] [INFO] Highest CP Pokemon:
2016-08-08 02:08:03,774 [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 501, in <module>
    main()
  File "pokecli.py", line 132, in main
    raise e
IndexError: list index out of range
2016-08-08 02:08:03,787 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1048, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1088, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1044, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 886, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-08 02:08:03,796 [sentry.errors.uncaught] [ERROR] [u'IndexError: list index out of range', u'  File "pokecli.py", line 501, in <module>', u'  File "pokecli.py", line 132, in main']

### Other Information
OS: Ubuntu 15.04
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: Python 2.7.9

**Comment by maestroi** [comment]
Maybe they are to busy? also dev or master?
And please dont spam all your log here.

**Comment by Happyrain67** [comment]
same here.
Once time after catch pokemon.

**Comment by firzzen** [comment]
Sorry, i shortened the logs now and removed most of the "moving to lured fort" parts.

Bot number one in the issue description is using the below and had issues with luredfort:

        "type": "MoveToFort",
        "config": {
          "lure_attraction": false,
          "lure_max_distance": 0

Bot number two in issue description is using the below and had issues with luredfort:

        "type": "MoveToFort",
        "config":{
          "lure_attraction": true,
          "lure_max_distance": 2000

Bot number three is using followpath with a .gpx file <- Had no issues with luredfort:

    "type": "FollowPath",
    "config": {
      "path_mode": "loop",
      "path_file": "configs/path1.gpx"


The fact they all have in common is that they crashed. At the same time i had other bots with identical configurations running with no problems. Only the location was different.

**Comment by Kaijun** [comment]
same +1,

it just happened randomly

**Comment by Aaronucci** [comment]
Been getting this routinely since we came back up.  Time and duration are random but I haven't been able to go more hen 2 hours without it occurring.

**Comment by firzzen** [comment]
To be even more specific about my issue then the unaffected bots i was running had no issues running 9 hours straight. Then i manually cancelled them.

Could it be that Niantic kills the excessive connections from their side if there are too many coming from one server? No proxies. But that wouldn't explain for the actual error in the end would it?

**Comment by Aaronucci** [comment]
@firzzen For me It was two from the same location so I can't imagine that would have been an issue unless they are that touchy.

**Comment by hklcf** [comment]
same here

![image](https://cloud.githubusercontent.com/assets/410302/17483306/109e0666-5db8-11e6-89a9-5cf209e58915.png)

**Comment by firzzen** [comment]
Now i'm getting it basically instantly on three of the accounts, about 10 minutes into it. I'm starting to suspect Niantic's hand in this...

**Comment by TridentNooch** [comment]
firzzen I tried a different bot, and map to check and those worked fine.

Might be worth trying to see if it's a softban or somethign else.
