### ISSUE TITLE
Error At Start

### ISSUE THREAD

**Issue by Eggity** [PokemonGoF/PokemonGo-Bot#3012]
### Expected Behaviour
Run Bot

### Actual Behaviour
Error after 
python pokecli.py

2016-08-08 00:16:31,447 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-08 00:16:31,449 [       cli] [INFO] No config argument specified, checking for /configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 133, in main
    raise e
ValueError: No JSON object could be decoded

### Other Information
OS: MAC
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by ErrorFlexXx** [comment]
[(https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files)]
Regards

**Comment by nivong** [comment]
there is an error in your json follow the link @ErrorFlexXx send to you or use:
https://pokemongof.github.io/botConfig/#/
