### ISSUE TITLE
Syntax Error on Bot Start

### ISSUE THREAD

**Issue by JarodKY** [PokemonGoF/PokemonGo-Bot#3021]
### Expected Behavior
Start bot using python pokecli.py

### Actual Behavior

Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 131, in main
    report_summary(bot)
  File "pokecli.py", line 140, in report_summary
    metrics.capture_stats()
  File "/Users/NAME/PokemonGo-Bot/pokemongo_bot/metrics.py", line 73, in capture_stats
    request = self.bot.api.create_request()
  File "/Users/NAME/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 27, in create_request
    self._position_alt
  File "/Users/NAME/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 43, in __init__
    PGoApiRequest.__init__(self, *args)
TypeError: __init__() takes exactly 6 arguments (5 given)
### Steps to Reproduce
Happens every time

### Other Information
OS:  Mac OSX El Capitan
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here) 5b3fe3d187b6b5fdfdede00f064bf7bcbd5a484d
Python Version: (run 'python -V' and paste it here)
Python 2.7.11

**Comment by nivong** [comment]
has already been mentoined and you should rerun install.sh

**Comment by JarodKY** [comment]
Where do I do that at?

**Comment by nivong** [comment]
dude you should read. It's in the root of your download map. please close this issue.

**Comment by JarodKY** [comment]
I reran it and I'm still getting the issue though.

**Comment by nivong** [comment]
again this has to do that you are using the old api, you should run the installar script. Please do that and it will work....
