### ISSUE TITLE
 [pokestop_searching_too_often] Possibly searching too often, take a rest.

### ISSUE THREAD

**Issue by htugsdr** [PokemonGoF/PokemonGo-Bot#3022]
Hey guys how do i add the 'fix' from #2771 to my bot?

### Expected Behavior
Spin pokestops, catch pokemon for more than 30 minutes

### Actual Behavior
```
16-08-08 17:39:02,887 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop New York Landmark Preservation Foundation - 0.05km (attraction of lure 0.17km)
2016-08-08 17:39:06,339 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop New York Landmark Preservation Foundation - 0.05km (attraction of lure 0.17km)
2016-08-08 17:39:08,885 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop New York Landmark Preservation Foundation - 0.04km (attraction of lure 0.17km)
2016-08-08 17:39:12,849 [  SpinFort] [INFO] [pokestop_out_of_range] Pokestop New York Landmark Preservation Foundation out of range.
2016-08-08 17:39:12,849 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-08 17:39:13,363 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Cartier Building - 0.08km (attraction of lure 0.17km)
2016-08-08 17:39:16,750 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Cartier Building - 0.08km (attraction of lure 0.17km)
2016-08-08 17:39:19,716 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Cartier Building - 0.08km (attraction of lure 0.16km)
2016-08-08 17:39:22,836 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Cartier Building - 0.07km (attraction of lure 0.16km)
2016-08-08 17:39:25,607 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Cartier Building - 0.07km (attraction of lure 0.16km)
2016-08-08 17:39:28,361 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Cartier Building - 0.06km (attraction of lure 0.15km)
2016-08-08 17:39:31,232 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Cartier Building - 0.06km (attraction of lure 0.15km)
2016-08-08 17:39:34,712 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Cartier Building - 0.05km (attraction of lure 0.15km)
2016-08-08 17:39:37,263 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Cartier Building - 0.05km (attraction of lure 0.15km)
2016-08-08 17:39:40,358 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Cartier Building - 0.04km (attraction of lure 0.14km)
2016-08-08 17:39:42,723 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Cartier Building - 0.04km (attraction of lure 0.14km)
2016-08-08 17:39:45,857 [  SpinFort] [INFO] [pokestop_out_of_range] Pokestop Cartier Building out of range.
2016-08-08 17:39:45,857 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-08 17:39:46,354 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Berlin Wall Slabs - 0.14km (attraction of lure 0.14km)
2016-08-08 17:39:49,507 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Berlin Wall Slabs - 0.13km (attraction of lure 0.13km)
2016-08-08 17:39:52,289 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Berlin Wall Slabs - 0.13km (attraction of lure 0.13km)
2016-08-08 17:39:55,639 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Berlin Wall Slabs - 0.13km (attraction of lure 0.13km)
2016-08-08 17:39:58,359 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Berlin Wall Slabs - 0.12km (attraction of lure 0.12km)
2016-08-08 17:40:01,276 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Berlin Wall Slabs - 0.12km (attraction of lure 0.12km)
2016-08-08 17:40:03,869 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Berlin Wall Slabs - 0.12km (attraction of lure 0.12km)
2016-08-08 17:40:07,072 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Berlin Wall Slabs - 0.11km (attraction of lure 0.11km)
2016-08-08 17:40:09,709 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Berlin Wall Slabs - 0.11km (attraction of lure 0.11km)
2016-08-08 17:40:12,774 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Berlin Wall Slabs - 0.11km (attraction of lure 0.11km)
2016-08-08 17:40:15,433 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Berlin Wall Slabs - 0.10km (attraction of lure 0.10km)
2016-08-08 17:40:17,764 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Berlin Wall Slabs - 0.10km (attraction of lure 0.10km)
2016-08-08 17:40:21,079 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Berlin Wall Slabs - 0.10km (attraction of lure 0.10km)

```

### Other Information
OS: MAc osx
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by siembz** [comment]
Git Pull

**Comment by htugsdr** [comment]
thanks ill test to see if it crashes after 30 mins now

**Comment by htugsdr** [comment]
okay so for 2 bots it began looping and gave me the Possibly "searching too often, take a rest." error

**Comment by scalda** [comment]
I am having the same problem after like 30 minutes but i get this in my CMD window before it stops collecting stops and pokemon

i have the latest dev version as of an hour ago. any ideas would be great?

`Traceback (most recent call last):
  File "C:\Python27\lib\logging\__init__.py", line 861, in emit
    msg = self.format(record)
  File "C:\Python27\lib\logging\__init__.py", line 734, in format
    return fmt.format(record)
  File "C:\Python27\lib\logging\__init__.py", line 465, in format
    record.message = record.getMessage()
  File "C:\Python27\lib\logging\__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file __init__.py, line 550`

**Comment by retraut** [comment]
Same here.
Have a 4 bots, after a 30 minutes - "searching too often, take a rest." error.
30 minutes later - all right, pokemons catching, eggs hatching

**Comment by celus** [comment]
is there a fix?

**Comment by mizhgan** [comment]
same here - 30 minutes all right, 30 minutes pokestop out of range, and so on.
commit - 5e3179b9c22d355f5f324751d1e5d6df7c2b1148

**Comment by balpoint** [comment]
confirming i'm also having the same issue on 4 bots on 2 geographically different servers.

**Comment by liwenzhuo1216** [comment]
after i do git pull now, still have the same problem!

**Comment by mizhgan** [comment]
It`s seems to be a sort of sofban by IP with more than two bots on the same IP.

**Comment by glitchsnob** [comment]
6 bots , searching too often loop after ten minutes.
