### ISSUE TITLE
Start up error encrypt.so file not found? 

### ISSUE THREAD

**Issue by moonlight2521** [PokemonGoF/PokemonGo-Bot#3023]
encrypt.so is not found! Please place it in the bots root directory or set libencrypt_location in config

where is the encrypt.so file?

**Comment by enjoyINcoding** [comment]
I met the same problem in the newest dev branch

**Comment by kinvaris** [comment]
I got this when pulling the newest dev branch and updating pip packages via `pip install -r requirements.txt`

**Comment by HelloTroy** [comment]
brew install wget

wget http://pgoapi.com/pgoencrypt.tar.gz && tar -xf pgoencrypt.tar.gz && cd pgoencrypt/src/ && make && mv libencrypt.so ../../encrypt.so

See Gitpupper's post
 https://github.com/PokemonGoF/PokemonGo-Bot/issues/2966

**Comment by moonlight2521** [comment]
can you walk me through step by step

**Comment by maxsolyaris** [comment]
Thanks @HelloTroy this was helped.

**Comment by HowieMowie** [comment]
Ran above full command to get and build encrypt.so and still getting same error.

  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libencrypt.so: cannot open shared object file: No such file or directory
(env) howard@KidsLaptop:~/OpenPoGoBot$ ls -ltra *.so
-rwxrwxr-x 1 howard howard 254402 Aug  8 12:25 libencrypt.so
-rwxrwxr-x 1 howard howard 254402 Aug  8 12:32 encrypt.so

**Comment by brunifrancesco** [comment]
On My Mavericks it works. 
Just run previous command, cd in the main dir project and rename the moved file to `encrypt.so`.

**Comment by HowieMowie** [comment]
Resolved not found libencrypt.so issue by setting LD_LIBRARY_PATH to include . but now getting new issue after the first pokemon found is transferred.

[2016-08-08 14:49:18] [Transfer] Transferring caught Pokemon with CP NOT above 100 and IV NOT above 0.4 and excluding [''].
[2016-08-08 14:49:18] [Transfer] No Pokemon to transfer.
[2016-08-08 14:49:18] [Transfer] Transferred 0 Pokemon.
Traceback (most recent call last):
  File "pokecli.py", line 361, in <module>
    main()
  File "pokecli.py", line 354, in main
    bot.run()
  File "/home/howard/OpenPoGoBot/pokemongo_bot/__init__.py", line 109, in run
    self.stepper.get_route_between(position_lat, position_lng, destination.target_lat, destination.target_lng, destination.target_alt)
  File "/home/howard/OpenPoGoBot/pokemongo_bot/stepper.py", line 75, in get_route_between
    path_points = self.path_finder.path(from_lat, from_lng, to_lat, to_lng)
  File "/home/howard/OpenPoGoBot/pokemongo_bot/navigation/path_finder/google_path_finder.py", line 15, in path
    gmaps = googlemaps.Client(key=self.config.gmapkey)
  File "/home/howard/OpenPoGoBot/env/local/lib/python2.7/site-packages/googlemaps/client.py", line 108, in __init__
    raise ValueError("Must provide API key or enterprise credentials "
ValueError: Must provide API key or enterprise credentials when creating client.

**Comment by snorlaxrazzi** [comment]
Thank you HelloTroy, that solved it for me

**Comment by HowieMowie** [comment]
Will open separate issue ticket since this doesn't appear related to the encrypt.so not found issue.
