### ISSUE TITLE
Linux: command python setup.py egg_info failed with error code 1

### ISSUE THREAD

**Issue by Fr33loader** [PokemonGoF/PokemonGo-Bot#3027]
### Expected Behavior

Fresh install on Linux.

### Actual Behavior

Output from console:

(PokemonGo-Bot)root@AOA150:~/PokemonGo-Bot# virtualenv .
New python executable in ./bin/python
Installing distribute..............................................................................................................................................................................................done.
Installing pip...............done.
(PokemonGo-Bot)root@AOA150:~/PokemonGo-Bot# source bin/activate
(PokemonGo-Bot)root@AOA150:~/PokemonGo-Bot# pip install -r requirements.txt
Downloading/unpacking numpy==1.11.0 (from -r requirements.txt (line 1))
  Running setup.py egg_info for package numpy
    Running from numpy source directory.
    
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
Downloading/unpacking networkx==1.11 (from -r requirements.txt (line 2))
  Running setup.py egg_info for package networkx
    
    warning: no files found matching 'scripts/*'
    warning: no files found matching 'networkx/tests/*.txt'
    warning: no files found matching 'networkx/*/*/tests/*.txt'
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '.svn' found anywhere in distribution
    no previously-included directories found matching 'doc/build'
    no previously-included directories found matching 'doc/source/reference/generated'
    no previously-included directories found matching 'doc/source/examples'
    no previously-included directories found matching 'doc/source/static/examples'
    no previously-included directories found matching 'doc/source/templates/gallery.html'
Obtaining pgoapi from git+https://github.com/keyphact/pgoapi.git@249d3be7fbbdabc7f9adea17cbc899d6549e47a2#egg=pgoapi (from -r requirements.txt (line 3))
  Updating ./src/pgoapi clone (to 249d3be7fbbdabc7f9adea17cbc899d6549e47a2)
  Could not find a tag or branch '249d3be7fbbdabc7f9adea17cbc899d6549e47a2', assuming commit.
  Running setup.py egg_info for package pgoapi
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/root/PokemonGo-Bot/src/pgoapi/setup.py", line 9, in <module>
        install_reqs = parse_requirements(path_req, session=False)
    TypeError: parse_requirements() got an unexpected keyword argument 'session'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/root/PokemonGo-Bot/src/pgoapi/setup.py", line 9, in <module>

    install_reqs = parse_requirements(path_req, session=False)

TypeError: parse_requirements() got an unexpected keyword argument 'session'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /root/PokemonGo-Bot/src/pgoapi
Storing complete log in /root/.pip/pip.log
(PokemonGo-Bot)root@AOA150:~/PokemonGo-Bot# ./run.sh configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions

### Steps to Reproduce

I have tried with and without virtualenv, with and without upgrade flags to my update command, with and without sudo. Always same result.

I know this is very similar to other errors, but I went through the solutions proposed in the other threads, and none of them do the trick for me.

Any help would be much appreciated.

### Other Information
OS: 
Git Commit: dee28d9fb1a973b95019bc07fb1e206872bd986d
Python Version: Python 2.7.3

**Comment by Fr33loader** [comment]
Solved by running in sudo:

"sudo ./run.sh"
