### ISSUE TITLE
ImportError: No module named future.builtins

### ISSUE THREAD

**Issue by BlazeMuisNL** [PokemonGoF/PokemonGo-Bot#3039]
### Expected Behavior

Well.. To run like it has done before?

### Actual Behavior

Not working..

### Steps to Reproduce

I don't know?

### Other Information
OS:  Raspbian Lite
Git Commit: Latest dev (5 hours ago)
Python Version: 2.7.9

Weird thing is, it worked just fine before. I went away from home for 2 hours, came back and logged in at my RPi3, the bot was still working, and then a few minutes later it crashed and I just can not get it back running again.

I ran pip install -r requirements.txt again and I haven't got a single error. But when I start the bot I get the following error:

<pre>root@raspberrypi:/home/pi/PokemonGo-Bot# ./run.sh
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
  File "/home/pi/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/home/pi/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/home/pi/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 47, in <module>
    from pgoapi.utilities import to_camel_case, get_time, get_format_time_diff, Rand48, long_to_bytes, generateLocation1, generateLocation2, generateRequestHash, f2i
  File "/home/pi/PokemonGo-Bot/src/pgoapi/pgoapi/utilities.py", line 39, in <module>
    from s2sphere import LatLng, Angle, Cap, RegionCoverer, math
  File "/usr/local/lib/python2.7/dist-packages/s2sphere/__init__.py", line 5, in <module>
    from .sphere import *
  File "/usr/local/lib/python2.7/dist-packages/s2sphere/sphere.py", line 2, in <module>
    from future.builtins import int
ImportError: No module named future.builtins</pre>

Anyone that can help me with this? I'm clueless right now.

**Comment by BlazeMuisNL** [comment]
Alright I was just being stupid -.-

Fixed it using pip install future.
