### ISSUE TITLE
NotLoggedInException()

### ISSUE THREAD

**Issue by mouendless** [PokemonGoF/PokemonGo-Bot#3046]
### Expected Behavior
I have daemontools to supervise on it, and I haven't change anything.
but it keeps on failed since around 02:00
re-install not help
not the account problem (change account not help, still login-able in mobile)

### Actual Behavior
2016-08-08 07:18:22,367 [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "/usr/share/nginx/PokemonGo-Bot-DL/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/usr/share/nginx/PokemonGo-Bot-DL/pokemongo_bot/api_wrapper.py", line 90, in call
    if not self.can_call():
  File "/usr/share/nginx/PokemonGo-Bot-DL/pokemongo_bot/api_wrapper.py", line 58, in can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
2016-08-08 07:18:22,437 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib64/python2.7/httplib.py", line 979, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 833, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-08 07:18:22,438 [sentry.errors.uncaught] [ERROR] [u'NotLoggedInException', u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", line 127, in main', u'  File "pokecli.py", line 136, in report_summary', u'  File "pokemongo_bot/metrics.py", line 76, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 90, in call', u'  File "pokemongo_bot/api_wrapper.py", line 58, in can_call']

### Other Information
OS: centos 7
Git Commit: 153ea212999e337b54e09761f6defbabb0de4e8c
Python Version: 2.7

**Comment by ewold** [comment]
Same problem, however only google accounts, PTC login doesn't have the error for me and works fine. 

```
2016-08-08 04:37:57,223 [pgoapi.pgoapi] [DEBUG] Set Position - Lat: 0 Long: 0 Alt: 0
2016-08-08 04:37:57,223 [pgoapi.pgoapi] [DEBUG] Auth provider: google
2016-08-08 04:37:57,223 [pgoapi.auth] [INFO] Google User Login for: xxxxxxx@gmail.com
2016-08-08 04:37:57,225 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTPS connection (1): android.clients.google.com
2016-08-08 04:37:57,310 [pgoapi.pgoapi] [INFO] Creating a new request...
2016-08-08 04:37:57,310 [pgoapi.pgoapi] [INFO] Adding 'GET_INVENTORY' to RPC request
2016-08-08 04:37:57,310 [pgoapi.pgoapi] [INFO] Adding 'GET_PLAYER' to RPC request
2016-08-08 04:37:57,310 [pgoapi.pgoapi] [INFO] Not logged in
Traceback (most recent call last):
  File "pokecli.py", line 503, in <module>
    main()
  File "pokecli.py", line 131, in main
    report_summary(bot)
  File "pokecli.py", line 140, in report_summary
    metrics.capture_stats()
  File "/root/pokemon/PokemonGo-Bot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/root/pokemon/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 90, in call
    if not self.can_call():
  File "/root/pokemon/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 58, in can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
2016-08-08 04:37:57,316 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib64/python2.7/httplib.py", line 979, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 833, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-08 04:37:57,318 [sentry.errors.uncaught] [ERROR] [u'NotLoggedInException', u'  File "pokecli.py", line 503, in <module>', u'  File "pokecli.py", line 131, in main', u'  File "pokecli.py", line 140, in report_summary', u'  File "pokemongo_bot/metrics.py", line 76, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 90, in call', u'  File "pokemongo_bot/api_wrapper.py", line 58, in can_call']
```

**Comment by mouendless** [comment]
create new virtualenv and install the pip dependencies can solve.
It's caused because bad dependencies from PokemonGo-Map
