### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by flopk** [PokemonGoF/PokemonGo-Bot#3059]
I've been following this from launch week and have been able to learn little bits of coding to configure/troubleshoot this bot but now am stumped. I have googled and searched the issue thread but can't find this one. 
I am trying to reinstall latest version (commit 563f898) from scratch to keep everything tidy. When I attempt to run with ./run.sh configs/config.json I get this error message. I can't see where i am going wrong.

2016-08-08 13:31:14,931 [       cli] [INFO] PokemonGO Bot v1.0
Traceback (most recent call last):
  File "pokecli.py", line 503, in <module>
    main()
  File "pokecli.py", line 62, in main
    config = init_config()
  File "pokecli.py", line 170, in init_config
    load.update(json.load(data))
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid \escape: line 7 column 31 (char 247)

OS: WIN10
Git Commit: 563f898f61233ff86d38d83b68d8399c1f63051b
Python Version: 2.7

**Comment by PraeceptorXS** [comment]
What does your Config.json look like?

**Comment by flopk** [comment]
{
    "auth_service": "google",
    "username": "*********",
    "password": "***********",
    "location": "location",
    "gmapkey": "A*****************",
    "libencrypt_location": "C:\Users\user\Downloads\PokemonGo-Map-develop\pogom",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
             "Pokeball":       { "keep" : 40 },
             "Greatball":      { "keep" : 40 },
             "Ultraball":      { "keep" : 70 },
             "Potion":         { "keep" : 15 },
             "Super Potion":   { "keep" : 40 },
             "Hyper Potion":   { "keep" : 50 },
             "Revive":         { "keep" : 65 },
             "Razz Berry":     { "keep" : 20 }       
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 6,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "Pikachu": { "always_catch" : true }
    },
    "release": {
      "any": {"keep_best_cp": 3, "keep_best_iv": 3, "release_below_cp": 500, "release_below_iv": 0.9, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this issue has been resolved. If I'm wrong, please reopen.
