### ISSUE TITLE
Starting new HTTP connection (1) doesn't run

### ISSUE THREAD

**Issue by Adrenocortico** [PokemonGoF/PokemonGo-Bot#3065]
### Expected Behavior
Bot starts

### Actual Behavior
```zsh
2016-08-08 15:24:06,770 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-08 15:24:06,772 [       cli] [INFO] No config argument specified, checking for /configs/config.json
2016-08-08 15:24:06,775 [       cli] [INFO] Configuration initialized
2016-08-08 15:24:06,775 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more logrmation:
2016-08-08 15:24:06,775 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-08 15:24:06,911 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 133, in main
    raise e
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
2016-08-08 15:24:07,128 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-08 15:24:07,135 [sentry.errors.uncaught] [ERROR] [u'ConnectionError: (\'Connection aborted.\', BadStatusLine("\'\'",))', u'  File "pokecli.py", line 502, in <module>', u'  File "pokecli.py", line 133, in main']
```

### Steps to Reproduce
Just run `python2 pokecli.py` with right config.json.

### Other Information
OS: macOS Sierra 10.12 (16A270f)
Git Commit: 5b3fe3d187b6b5fdfdede00f064bf7bcbd5a484d
Python Version: Python 2.7.12

**Comment by S3ptikus** [comment]
Same problem

**Comment by m0r0n** [comment]
Why is google-analytics.com called anyway?

**Comment by S3ptikus** [comment]
I resolve my problem. Just set health_record to false
