### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by cbogithub** [PokemonGoF/PokemonGo-Bot#3071]
```

>"E:\WARTER\python\python.v2.7_portable\App\pythonw.exe" -m pip install -r requirements.txt  -vv
Requirement already satisfied (use --upgrade to upgrade): six==1.10.0 in e:\warter\python\python.v2.7_portable\app\lib\site-packages\six-1.10.0-py2.7.egg (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Flask==0.11.1 in e:\warter\python\python.v2.7_portable\app\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.8 in e:\warter\python\python.v2.7_portable\app\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in e:\warter\python\python.v2.7_portable\app\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug==0.11.10 in e:\warter\python\python.v2.7_portable\app\lib\site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): configargparse==0.10.0 in e:\warter\python\python.v2.7_portable\app\lib\site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): click==6.6 in e:\warter\python\python.v2.7_portable\app\lib\site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous==0.24 in e:\warter\python\python.v2.7_portable\app\lib\site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): peewee==2.8.1 in e:\warter\python\python.v2.7_portable\app\lib\site-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): wsgiref==0.1.2 in e:\warter\python\python.v2.7_portable\app\lib\site-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in e:\warter\python\python.v2.7_portable\app\lib\site-packages\geopy-1.11.0-py2.7.egg (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in e:\warter\python\python.v2.7_portable\app\lib\site-packages\s2sphere-0.2.4-py2.7.egg (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in e:\warter\python\python.v2.7_portable\app\lib\site-packages\gpsoauth-0.3.0-py2.7.egg (from -r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): PyMySQL==0.7.5 in e:\warter\python\python.v2.7_portable\app\lib\site-packages (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): flask-cors==2.1.2 in e:\warter\python\python.v2.7_portable\app\lib\site-packages (from -r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): flask-compress==1.3.0 in e:\warter\python\python.v2.7_portable\app\lib\site-packages (from -r requirements.txt (line 16))
Collecting LatLon==1.0.1 (from -r requirements.txt (line 17))
  1 location(s) to search for versions of LatLon:
  * https://pypi.python.org/simple/latlon/
  Getting page https://pypi.python.org/simple/latlon/
  Looking up "https://pypi.python.org/simple/latlon/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  Incremented Retry for (url='/simple/latlon/'): Retry(total=4, connect=None, read=None, redirect=None)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x038B0D50>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))': /simple/latlon/
  Starting new HTTPS connection (2): pypi.python.org
  Incremented Retry for (url='/simple/latlon/'): Retry(total=3, connect=None, read=None, redirect=None)
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x038B0B10>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))': /simple/latlon/
  Starting new HTTPS connection (3): pypi.python.org
  Incremented Retry for (url='/simple/latlon/'): Retry(total=2, connect=None, read=None, redirect=None)
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x038B05F0>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))': /simple/latlon/
  Starting new HTTPS connection (4): pypi.python.org
  Incremented Retry for (url='/simple/latlon/'): Retry(total=1, connect=None, read=None, redirect=None)
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x038B0650>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))': /simple/latlon/
  Starting new HTTPS connection (5): pypi.python.org
  Incremented Retry for (url='/simple/latlon/'): Retry(total=0, connect=None, read=None, redirect=None)
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x038B0DF0>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))': /simple/latlon/
  Starting new HTTPS connection (6): pypi.python.org
  Could not fetch URL https://pypi.python.org/simple/latlon/: connection error: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/latlon/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x038B0450>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))) - skipping
  Could not find a version that satisfies the requirement LatLon==1.0.1 (from -r requirements.txt (line 17)) (from versions: )
Cleaning up...
No matching distribution found for LatLon==1.0.1 (from -r requirements.txt (line 17))
Exception information:
Traceback (most recent call last):
  File "E:\WARTER\python\python.v2.7_portable\App\lib\site-packages\pip\basecommand.py", line 209, in main
    status = self.run(options, args)
  File "E:\WARTER\python\python.v2.7_portable\App\lib\site-packages\pip\commands\install.py", line 310, in run
    wb.build(autobuilding=True)
  File "E:\WARTER\python\python.v2.7_portable\App\lib\site-packages\pip\wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "E:\WARTER\python\python.v2.7_portable\App\lib\site-packages\pip\req\req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "E:\WARTER\python\python.v2.7_portable\App\lib\site-packages\pip\req\req_set.py", line 512, in _prepare_file
    finder, self.upgrade, require_hashes)
  File "E:\WARTER\python\python.v2.7_portable\App\lib\site-packages\pip\req\req_install.py", line 273, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "E:\WARTER\python\python.v2.7_portable\App\lib\site-packages\pip\index.py", line 489, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for LatLon==1.0.1 (from -r requirements.txt (line 17))
```

**Comment by djadstar** [comment]
Maybe try running in a virtual environment, I had an issue with installing requirements but after using a VENV had no problems.

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this issue has been resolved. If I'm wrong, please reopen.
