### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by mrwing1** [PokemonGoF/PokemonGo-Bot#310]
[x] PokemonGO Bot v1.0
[x] Configuration initialized

[x] Address found: XXXXXXXX
[x] Position in-game set as: (XXXXXXXX)

Traceback (most recent call last):
File "pokecli.py", line 120, in 
main()
File "pokecli.py", line 108, in main
bot.start()
File "/Users/test/Downloads/PokemonGo-Bot-dev 2/pokemongo_bot/init.py", line 26, in start
self.setup_api()
File "/Users/test/Downloads/PokemonGo-Bot-dev 2/pokemongo_bot/__init_.py", line 96, in _setup_api
player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'GET_PLAYER'

**Comment by Skeyelab** [comment]
when did you last `git pull`

**Comment by mrwing1** [comment]
skeye last update

**Comment by mrwing1** [comment]
skeye found the bug didnt download the master version

**Comment by mrwing1** [comment]
THANK YOU SO MUCH MATE :D
