### ISSUE TITLE
TypeError: not all arguments ...

### ISSUE THREAD

**Issue by jokoast** [PokemonGoF/PokemonGo-Bot#3101]
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting

On MacOSx.

Can't let the bot running by himself, i have to check what he's doing and restart it ^^.

**Comment by GitPupper** [comment]
[PokeBot.zip](https://github.com/PokemonGoF/PokemonGo-Bot/files/407313/PokeBot.zip)
Open this with terminal. It should run the bot and restart it if it quits.

**Comment by TCB13** [comment]
There are lot's of reasons why this can happen. From my experience I would say pgo servers frequent issues and crash the bot. The code itself it ok.

**Comment by GitPupper** [comment]
@TCB13 True. That's why I run that script. (above) It only works on Mac / Linux though. Windows would require a .bat but basically the same commands. Just change a few things around in the script.
