### ISSUE TITLE
Crashing after "VIP Pokemon" catch.

### ISSUE THREAD

**Issue by PokemonGoZ** [PokemonGoF/PokemonGo-Bot#3111]
### Logs
2016-08-08 12:35:45,365 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort Dragon Head in Santa Monica (11410a03fc7f4c9f9c392e8fb2353fac.16)
2016-08-08 12:35:46,351 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Growlithe appeared! [CP 598] [Potential 0.91] [S/A/D 13/14/14]
2016-08-08 12:35:50,177 [PokemonCatchWorker] [INFO] [vip_pokemon] This is a VIP pokemon. Catch!!!
2016-08-08 12:35:50,651 [       cli] [INFO]
2016-08-08 12:35:50,651 [       cli] [INFO] Ran for 0:00:26
2016-08-08 12:35:50,652 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-08 12:35:50,652 [       cli] [INFO] Travelled 0.00km
2016-08-08 12:35:50,652 [       cli] [INFO] Visited 0 stops
2016-08-08 12:35:50,652 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-08 12:35:50,652 [       cli] [INFO] Threw 0 pokeballs
2016-08-08 12:35:50,652 [       cli] [INFO] Earned 0 Stardust
2016-08-08 12:35:50,653 [       cli] [INFO]
2016-08-08 12:35:50,653 [       cli] [INFO] Highest CP Pokemon:
2016-08-08 12:35:50,653 [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 133, in main
    raise e
KeyError: 'new_catch_rate'
2016-08-08 12:35:50,663 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/bobbyobrien/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/bobbyobrien/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/bobbyobrien/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/bobbyobrien/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/bobbyobrien/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/bobbyobrien/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/bobbyobrien/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/bobbyobrien/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-08 12:35:50,665 [sentry.errors.uncaught] [ERROR] [u"KeyError: 'new_catch_rate'", u'  File "pokecli.py", line 502, in <module>', u'  File "pokecli.py", line 133, in main']
(PokemonGo-Bot) Bobbys-MacBook-Air:PokemonGo-Bot bobbyobrien$
***
### Info
It just stops after I encounter pokemon. It then calls it a VIP then crashes. (No pokemon are in the VIP area except for the preset)

### Other Information
OS: macOS El Capitan
Git Commit: dee28d9fb1a973b95019bc07fb1e206872bd986d
Python Version: Python 2.7.12

**Comment by ThunderVamp9** [comment]
Are you using the updated cell_workers files to add color to the log?

If so, there is a problem in it with pokemon_catch_worker.py

Look for the section:

`formatted="\033[1;32;40m Threw a {berry_name}! Catch rate now: {new_catch_rate} \033[0;37;40m",
                                        data={
                                            'catch_rate': success_percentage,
                                            'berry_name': self.item_list[str(berry_id)],
                                            'berry_count': berries_count
                                        }`

That part is causing the problem. It should be:

`formatted="\033[1;32;40m Threw a {berry_name}! Catch rate now: {new_catch_rate} \033[0;37;40m",
                                        data={
                                            'new_catch_rate': success_percentage,
                                            'berry_name': self.item_list[str(berry_id)],
                                            'berry_count': berries_count
                                        }`

**Comment by k4n30** [comment]
Please update to the latest version and report back if the issue is fixed / still occuring

**Comment by k4n30** [comment]
@GitPupper Assuming this can be closed now? I'll let you do the honours
