### ISSUE TITLE
run all day bot and now some issue

### ISSUE THREAD

**Issue by buzzo123** [PokemonGoF/PokemonGo-Bot#3112]
i run the bott al day but now it crashes:

```
  File "pokecli2.py", line 502, in <module>
    main()
  File "pokecli2.py", line 133, in main
    raise e
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
2016-08-08 19:35:52,710 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-08 19:35:52,870 [sentry.errors.uncaught] [ERROR] [u'ConnectionError: (\'Connection aborted.\', BadStatusLine("\'\'",))', u'  File "pokecli2.py", line 502, in <module>', u'  File "pokecli2.py", line 133, in main']
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```

**Comment by balpoint** [comment]
Confirm, i got the same after a whole day running.

**Comment by buzzo123** [comment]
i've 2 bot, one is still running but this i'm not enable to run

**Comment by buzzo123** [comment]
it's fixed with new commit^

**Comment by k4n30** [comment]
@buzzo123 is it fixed now?

**Comment by buzzo123** [comment]
i don't know

**Comment by k4n30** [comment]
I'm going to suggest due to the nature of the frequent updates, and the unlikelihood the issue still exists, that this issue be closed.  I'd recommend updating to the latest version and if there are any issues, then create a new issue
