### ISSUE TITLE
Need help running the program

### ISSUE THREAD

**Issue by Ballermocha** [PokemonGoF/PokemonGo-Bot#3114]
### Expected Behavior
I followed the instructions and type "python ./pokecli.py -cf=./configs/config.json" to run the program.

### Actual Behavior
There are errors: 

PokemonGO Bot v1.0
Traceback (most recent call last):
  File "./pokecli.py", line 502, in <module>
    main()
  File "./pokecli.py", line 133, in main
    raise e
ValueError: No JSON object could be decoded

### Other Information
OS: Mac 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: 2.7.12

**Comment by djadstar** [comment]
Try python pokecli.py

**Comment by hklcf** [comment]
`python pokecli.py -cf configs/config.json`

**Comment by ErrorFlexXx** [comment]
Please check if the config file config.json actually exists. If not edit config.json.example and save it as config.json in the "configs" directory.

**Comment by Ballermocha** [comment]
I edited the config.json.example with my info and saved it as config.json, but the issue still there. I've also tried the dev version. Here are the errors: 

PokemonGO Bot v1.0
Traceback (most recent call last):
  File "pokecli.py", line 503, in <module>
    main()
  File "pokecli.py", line 62, in main
    config = init_config()
  File "pokecli.py", line 170, in init_config
    load.update(json.load(data))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by hklcf** [comment]
**ValueError: No JSON object could be decoded**

**Comment by SGColdSun** [comment]
As mentioned by hklcf, you're specifying the config incorrectly. 

 "python ./pokecli.py -cf=./configs/config.json"
should be
 "python ./pokecli.py -cf configs/config.json"

**Comment by zviper13579** [comment]
Im getting the same error even when I use python ./pokecli.py -cf configs/config.json. Config.json exists. Could My edits in Config.json be causing a problem, not allowing it to decode?

**Comment by jeffbye** [comment]
Usually it's a screwed up "slanted" quotation mark when I get this.  TextEdit on OSX creates them by default, so scour through your file and see if you can find any.

**Comment by Ballermocha** [comment]
Thanks I fixed it. There was a syntax error.
