### ISSUE TITLE
[dev] codec can't decode byte 0x9c in position 1: ordinal not in range(128) error

### ISSUE THREAD

**Issue by DokterPhill** [PokemonGoF/PokemonGo-Bot#3115]
### Expected Behavior
Bot should regularly start up

### Actual Behavior
After showing account info I get an error: 

2016-08-08 20:06:38,789 [PokemonGoBot] [INFO] Found encrypt.dll! Platform: win32 Bot root directory: C:\Users\Roel\Downloads\PokemonGo-Bot-dev\PokemonGo-Dev\PokemonGo-Bot
2016-08-08 20:06:38,795 [PokemonGoBot] [INFO]
2016-08-08 20:06:44,951 [       cli] [INFO]
2016-08-08 20:06:44,951 [       cli] [INFO] Ran for 0:00:10
2016-08-08 20:06:44,956 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-08 20:06:44,959 [       cli] [INFO] Travelled 0.00km
2016-08-08 20:06:44,961 [       cli] [INFO] Visited 0 stops
2016-08-08 20:06:44,964 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-08 20:06:44,969 [       cli] [INFO] Threw 0 pokeballs
2016-08-08 20:06:44,971 [       cli] [INFO] Earned 0 Stardust
2016-08-08 20:06:44,976 [       cli] [INFO]
2016-08-08 20:06:44,979 [       cli] [INFO] Highest CP Pokemon:
2016-08-08 20:06:44,980 [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "C:\Users\Roel\Downloads\PokemonGo-Bot-dev\PokemonGo-Dev\PokemonGo-Bot\pokecli.py", line 502, in <module>
    main()
  File "C:\Users\Roel\Downloads\PokemonGo-Bot-dev\PokemonGo-Dev\PokemonGo-Bot\pokecli.py", line 133, in main
    raise e
AttributeError: type object 'HandleSoftBan' has no attribute 'SUPPORTED_TASK_API_VERSION'
2016-08-08 20:06:45,007 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\raven\transport\threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "C:\Python27\lib\site-packages\raven\transport\http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 494, in open
    response = self._open(req, data)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 512, in _open
    '_open', req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python27\lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-08 20:06:45,039 [sentry.errors.uncaught] [ERROR] [u"AttributeError: type object 'HandleSoftBan' has no attribute 'SUPPORTED_TASK_API_VERSION'", u'  File "C:\\Users\\Roel\\Downloads\\PokemonGo-Bot-dev\\PokemonGo-Dev\\PokemonGo-Bot\\pokecli.py", line 502, in <module>', u'  File "C:\\Users\\Roel\\Downloads\\PokemonGo-Bot-dev\\PokemonGo-Dev\\PokemonGo-Bot\\pokecli.py", line 133, in main']

### Other Information
OS: win10
Git Commit: ae0ae815089bf1e3b17497b476d524a0468949e2
Python Version: Python 2.7.12

**Comment by DavidTai1** [comment]
same

**Comment by 123marvin123** [comment]
same here, maybe some api changed?

**Comment by iphonitest** [comment]
same

**Comment by BenkaTv** [comment]
same

**Comment by BenkaTv** [comment]
My bot is working now! Runned for: 10 Sec's now 

PTC Problems mabye

**Comment by tr3intaydos** [comment]
```2016-08-08 20:06:45,007 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)```

**Comment by Gregwar** [comment]
Looks like it works for me with PTC but I have the same error with google account

**Comment by netmask** [comment]
same here

**Comment by selmuth** [comment]
you need to update config.json there is a new line  "libencrypt_location": "",

**Comment by tr3intaydos** [comment]
if i disable health_record, the problem disapears

**Comment by DokterPhill** [comment]
@tr3intaydos that worked for one issue. Still got error:
AttributeError: type object 'HandleSoftBan' has no attribute 'SUPPORTED_TASK_API_VERSION'
