### ISSUE TITLE
Server Down | Server Busy

### ISSUE THREAD

**Issue by GitPupper** [PokemonGoF/PokemonGo-Bot#3122]
Update 1
Many people are experiencing their bot being down right now.
***
Update 2
Mine started working for a few seconds then crashed. The server is probably unstable.
***
Update 3
Others are saying it works for them. Might be a server issue.
***
Update 4
Still having errors. @mjmadsen suggests to turn your bots off. Server issue.
***
Update 5
Bot starts up but crashes within a few minutes.
***
Bot works. Update 6. Final.
It works! Health Record `True` or `False` don't actually work. All you have to do is wait :)
Closing this thread soon.
***
### Logs
2016-08-08 13:31:07,175 [PokemonGoBot] [INFO] Found encrypt.so! Platform: darwin Bot root directory: /Users/bobbyobrien/PokemonGo-Bot
2016-08-08 13:31:07,175 [PokemonGoBot] [INFO] 
2016-08-08 13:31:09,404 [       cli] [INFO] 
2016-08-08 13:31:09,404 [       cli] [INFO] Ran for 0:00:05
2016-08-08 13:31:09,404 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-08 13:31:09,405 [       cli] [INFO] Travelled 0.00km
2016-08-08 13:31:09,405 [       cli] [INFO] Visited 0 stops
2016-08-08 13:31:09,405 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-08 13:31:09,405 [       cli] [INFO] Threw 0 pokeballs
2016-08-08 13:31:09,405 [       cli] [INFO] Earned 0 Stardust
2016-08-08 13:31:09,405 [       cli] [INFO] 
2016-08-08 13:31:09,405 [       cli] [INFO] Highest CP Pokemon: 
2016-08-08 13:31:09,406 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 133, in main
    raise e
IndexError: list index out of range
2016-08-08 13:31:09,417 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/bobbyobrien/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/bobbyobrien/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/bobbyobrien/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/bobbyobrien/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/bobbyobrien/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/bobbyobrien/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/bobbyobrien/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/bobbyobrien/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-08 13:31:09,419 [sentry.errors.uncaught] [ERROR] [u'IndexError: list index out of range', u'  File "pokecli.py", line 502, in <module>', u'  File "pokecli.py", line 133, in main']

**Comment by mushi8** [comment]
Same

**Comment by beldar** [comment]
Getting the same error here

**Comment by yzhu09203** [comment]
same here

**Comment by GitPupper** [comment]
Bot works now. Retry. Possibly the server updated.

**Comment by sinthu94** [comment]
nope , does not work

**Comment by z4q** [comment]
still same :(

**Comment by mjmadsen** [comment]
I'd suggest leaving your bots off for a while until more is known.

**Comment by designer2k2** [comment]
Running well here, no issues.

**Comment by celus** [comment]
same

**Comment by kinvaris** [comment]
Got 2 bots running very good here. One having this problem

**Comment by sinthu94** [comment]
it's working for me now :D

**Comment by omeryagmurlu** [comment]
This bot works fine: https://github.com/jabbink/PokemonGoBot
While this map has the same issue: https://github.com/PokemonGoMap/PokemonGo-Map

**Comment by saru95** [comment]
Any work arounds ? same issue for me !

**Comment by yzhu09203** [comment]
The Bot working fine for me now.

**Comment by mjmadsen** [comment]
One of my continued to run fine until throttling messages started to get thrown. Then I killed it. Others get this upon login success:

Traceback (most recent call last):
  File "pokecli.py", line 503, in <module>
    main()
  File "pokecli.py", line 75, in main
    bot.start()
  File "/home/jimbo/PokemonGo-Bot/pokemongo_bot/__init__.py", line 75, in start
    self._setup_api()
  File "/home/jimbo/PokemonGo-Bot/pokemongo_bot/__init__.py", line 678, in _setup_api
    self.update_web_location()
  File "/home/jimbo/PokemonGo-Bot/pokemongo_bot/__init__.py", line 492, in update_web_location
    gym_longitude=fort.get('longitude')
  File "/home/jimbo/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 122, in function
    return request.call()
  File "/home/jimbo/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 106, in call
    result = self._call()
  File "/home/jimbo/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "/home/jimbo/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/home/jimbo/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 129, in request
    response_dict = self._parse_main_response(response, subrequests)
  File "/home/jimbo/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 359, in _parse_main_response
    response_proto_dict = self._parse_sub_responses(response_proto, subrequests, response_proto_dict)
  File "/home/jimbo/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 376, in _parse_sub_responses
    request_entry = subrequests_list[i]
IndexError: list index out of range
2016-08-08 13:40:29,649 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/jimbo/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/jimbo/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/jimbo/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/jimbo/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/jimbo/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/jimbo/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/jimbo/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/jimbo/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-08 13:40:29,651 [sentry.errors.uncaught] [ERROR] [u'IndexError: list index out of range', u'  File "pokecli.py", line 503, in <module>', u'  File "pokecli.py", line 75, in main', u'  File "pokemongo_bot/__init__.py", line 75, in start', u'  File "pokemongo_bot/__init__.py", line 678, in _setup_api', u'  File "pokemongo_bot/__init__.py", line 492, in update_web_location', u'  File "pgoapi/pgoapi.py", line 122, in function', u'  File "pokemongo_bot/api_wrapper.py", line 106, in call', u'  File "pokemongo_bot/api_wrapper.py", line 63, in _call', u'  File "pgoapi/pgoapi.py", line 220, in call', u'  File "pgoapi/rpc_api.py", line 129, in request', u'  File "pgoapi/rpc_api.py", line 359, in _parse_main_response', u'  File "pgoapi/rpc_api.py", line 376, in _parse_sub_responses']

**Comment by saru95** [comment]
@yzhu09203 just randomly or did you pull some changes ?

**Comment by z4q** [comment]
work fine now. :)

**Comment by yzhu09203** [comment]
@saru95 randomly...while..the errer appeared again now...

**Comment by andyjunzi** [comment]
works fine now

**Comment by TheSegfault** [comment]
Ascii error appearing randomly !

**Comment by desert0616** [comment]
The same. No matter how many time I retry, the issue appears repeatedly

**Comment by demesg** [comment]
I has had this problem for 4 hours now..  I switched over to a vpn tunnel and then the bot could login..

**Comment by HelloTroy** [comment]
same ascii problem here suddenly

**Comment by siembz** [comment]
it workes with "health_record": false,

**Comment by yzhu09203** [comment]
@demesg  tried, doesn't work for me..

**Comment by siembz** [comment]
@demesg try "health_record": false,

**Comment by Misha023** [comment]
@siembz had it on false. Switched it to true and the bot started working

**Comment by TheSegfault** [comment]
One is true one is false, both are getting ascii and my third one is not getting error, seems random for me.

**Comment by kinvaris** [comment]
I've put my startup command in a bash while. Seems to work, meh.

**Comment by siembz** [comment]
@Misha023 i had in on true and when the bot started sending error messages i switch it to false and it worked.

**Comment by mitcht** [comment]
Looks like there is some code in there that checks for an item in an array and it doesn't exist, so ya, you will get list index out of range.

**Comment by desert0616** [comment]
health_record -> false really works for me

**Comment by GitPupper** [comment]
The bot works. If you are still facing problems wait or start a new thread with your error. Thank you.

**Comment by mitcht** [comment]
The problem is in /PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py

Replace line 376 
`request_entry = subrequests_list[i]`
with
```

try:
                request_entry = subrequests_list[i]
            except IndexError:
                break

```

**Comment by sinthu94** [comment]
yeah that worked :D

**Comment by JohnAlbert1** [comment]
@mitcht not working for me

**Comment by Quantra** [comment]
If you have this issue please test the repo with mitcht's fix here https://github.com/Quantra/pgoapi

As the problem is intermittent I am not sure this is a solid solution.  If more people test and it works I'll make a PR to the main pgoapi repo.
