### ISSUE TITLE
[BUG] Bot crash after starting with commit (f648be31c15d0143bccc0531571b2d00fd88ec4d)

### ISSUE THREAD

**Issue by DimaVIII** [PokemonGoF/PokemonGo-Bot#3133]
### Actual Behavior
```
2016-08-08 21:15:33,411 [PokemonGoBot] [INFO] [bot_start] Starting bot...
2016-08-08 21:15:34,819 [CollectLevelUpReward] [INFO] [level_up_reward] Received level up reward: []
2016-08-08 21:15:34,820 [IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 1.50 km
2016-08-08 21:15:37,110 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_move_towards] Moving towards Nidoran F, 0.26km, left (6 minutes, 25 seconds)
2016-08-08 21:15:40,595 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_move_towards] Moving towards Nidoran F, 0.24km, left (6 minutes, 22 seconds)
2016-08-08 21:15:44,551 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_move_towards] Moving towards Nidoran F, 0.22km, left (6 minutes, 18 seconds)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/pokemongo_bot/__init__.py", line 994, in update_web_location_worker
    self.update_web_location()
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/pokemongo_bot/__init__.py", line 499, in update_web_location
    gym_longitude=fort.get('longitude')
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 122, in function
    return request.call()
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 106, in call
    result = self._call()
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 129, in request
    response_dict = self._parse_main_response(response, subrequests)
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 359, in _parse_main_response
    response_proto_dict = self._parse_sub_responses(response_proto, subrequests, response_proto_dict)
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 376, in _parse_sub_responses
    request_entry = subrequests_list[i]
IndexError: list index out of range

2016-08-08 21:15:49,995 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_move_towards] Moving towards Nidoran F, 0.20km, left (6 minutes, 13 seconds)
2016-08-08 21:15:54,637 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Tangela appeared! [CP 1122] [Potential 0.64] [S/A/D 11/7/11]
2016-08-08 21:15:57,908 [PokemonCatchWorker] [INFO] [vip_pokemon] This is a VIP pokemon. Catch!!!
2016-08-08 21:15:57,943 [PokemonCatchWorker] [INFO] [threw_pokeball] Used Ultraball, with chance 42.92 (15 left)
2016-08-08 21:15:59,311 [PokemonCatchWorker] [INFO] [pokemon_caught] Captured Tangela! [CP 1122] [Potential 0.64] [11/7/11] [+210 exp]
2016-08-08 21:16:04,357 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_move_towards] Moving towards Nidoran F, 0.18km, left (5 minutes, 58 seconds)
2016-08-08 21:16:07,231 [       cli] [INFO] 
2016-08-08 21:16:07,231 [       cli] [INFO] Ran for 0:00:47
2016-08-08 21:16:07,231 [       cli] [INFO] Total XP Earned: 210  Average: 16070.56/h
2016-08-08 21:16:07,231 [       cli] [INFO] Travelled 0.00km
2016-08-08 21:16:07,231 [       cli] [INFO] Visited 0 stops
2016-08-08 21:16:07,232 [       cli] [INFO] Encountered 1 pokemon, 1 caught, 0 released, 0 evolved, 0 never seen before
2016-08-08 21:16:07,232 [       cli] [INFO] Threw 1 pokeball
2016-08-08 21:16:07,232 [       cli] [INFO] Earned 100 Stardust
2016-08-08 21:16:07,232 [       cli] [INFO] 
2016-08-08 21:16:07,232 [       cli] [INFO] Highest CP Pokemon: Tangela [CP: 1122] [IV: 11/7/11] Potential: 0.64 
2016-08-08 21:16:07,232 [       cli] [INFO] Most Perfect Pokemon: Tangela [CP: 1122] [IV: 11/7/11] Potential: 0.64 
Traceback (most recent call last):
  File "pokecli.py", line 503, in <module>
    main()
  File "pokecli.py", line 89, in main
    bot.tick()
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/pokemongo_bot/__init__.py", line 434, in tick
    self.cell = self.get_meta_cell()
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/pokemongo_bot/__init__.py", line 446, in get_meta_cell
    cells = self.find_close_cells(*location)
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/pokemongo_bot/__init__.py", line 536, in find_close_cells
    response_dict = self.get_map_objects(lat, lng, timestamp, cellid)
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1077, in get_map_objects
    cell_id=cellid
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 122, in function
    return request.call()
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 106, in call
    result = self._call()
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 129, in request
    response_dict = self._parse_main_response(response, subrequests)
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 359, in _parse_main_response
    response_proto_dict = self._parse_sub_responses(response_proto, subrequests, response_proto_dict)
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 376, in _parse_sub_responses
    request_entry = subrequests_list[i]
IndexError: list index out of range
2016-08-08 21:16:07,288 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/DimaPro/PokemonGo-Bot/Master-Bot-4/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-08 21:16:07,297 [sentry.errors.uncaught] [ERROR] [u'IndexError: list index out of range', u'  File "pokecli.py", line 503, in <module>', u'  File "pokecli.py", line 89, in main', u'  File "pokemongo_bot/__init__.py", line 434, in tick', u'  File "pokemongo_bot/__init__.py", line 446, in get_meta_cell', u'  File "pokemongo_bot/__init__.py", line 536, in find_close_cells', u'  File "pokemongo_bot/__init__.py", line 1077, in get_map_objects', u'  File "pgoapi/pgoapi.py", line 122, in function', u'  File "pokemongo_bot/api_wrapper.py", line 106, in call', u'  File "pokemongo_bot/api_wrapper.py", line 63, in _call', u'  File "pgoapi/pgoapi.py", line 220, in call', u'  File "pgoapi/rpc_api.py", line 129, in request', u'  File "pgoapi/rpc_api.py", line 359, in _parse_main_response', u'  File "pgoapi/rpc_api.py", line 376, in _parse_sub_responses']
```

### Other Information
OS: OSx 64Bit
Git Commit: f648be31c15d0143bccc0531571b2d00fd88ec4d

**Comment by pmquan** [comment]
#3121
