### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by anythinguwant2be** [PokemonGoF/PokemonGo-Bot#3136]
### Expected Behavior
Play the Bot
### Actual Behavior
[13:51:01] Exception: System.NullReferenceException: Object reference not set to
 an instance of an object.
   at PokemonGo.RocketAPI.Rpc.Inventory.<GetEggs>d__6.MoveNext() in C:\Users\Ari
\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\
Rpc\Inventory.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.Inventory.<GetEggsCount>d__5.MoveNext() in C:\User
s\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.Rocke
tAPI\Rpc\Inventory.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<StatsLog>d__14.MoveNext() in C:\Users\Ari
\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.
Logic\Logic.cs:line 188
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__17.
MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-N
ewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:line 366
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() in C:\U
sers\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.Ro
cketAPI.Logic\Logic.cs:line 129
### Steps to Reproduce
Nothing I just start up the Bot and this happens 

### Other Information
OS: Windows 7
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by Kassadd** [comment]
>Expected Behavior

>Play the Bot

What bot?
