### ISSUE TITLE
Bot Crash at transfering

### ISSUE THREAD

**Issue by XxHeadSh0T** [PokemonGoF/PokemonGo-Bot#3139]
### Expected Behavior
Transfer the Pokémon with lower cp

### Actual Behavior
```
2016-08-08 21:25:51,560 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-08 21:25:51,563 [       cli] [INFO] Configuration initialized
2016-08-08 21:25:51,563 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-08 21:25:51,563 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-08 21:25:51,568 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-08 21:25:51,595 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-08 21:25:51,596 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-08 21:25:51,596 [PokemonGoBot] [INFO] [location_found] Location found: 35.698103, 139.772043 (35.698103, 139.772043, 0.0)
2016-08-08 21:25:51,596 [PokemonGoBot] [INFO] [position_update] Now at (35.698103, 139.772043, 0)
2016-08-08 21:25:51,596 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-08 21:25:53,001 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-08 21:25:54,597 [PokemonGoBot] [INFO] 
2016-08-08 21:25:54,598 [PokemonGoBot] [INFO] --- ***---
2016-08-08 21:25:54,598 [PokemonGoBot] [INFO] Level: 17 (Next Level: 17210 XP) (Total: 142790 XP)
2016-08-08 21:25:54,599 [PokemonGoBot] [INFO] Pokemon Captured: 346 | Pokestops Visited: 724
2016-08-08 21:25:54,599 [PokemonGoBot] [INFO] Pokemon Bag: 55/250
2016-08-08 21:25:54,600 [PokemonGoBot] [INFO] Items: 188/350
2016-08-08 21:25:54,600 [PokemonGoBot] [INFO] Stardust: 44771 | Pokecoins: 0
2016-08-08 21:25:54,600 [PokemonGoBot] [INFO] PokeBalls: 53 | GreatBalls: 25 | UltraBalls: 0
2016-08-08 21:25:54,601 [PokemonGoBot] [INFO] RazzBerries: 50 | BlukBerries: 0 | NanabBerries: 0
2016-08-08 21:25:54,601 [PokemonGoBot] [INFO] LuckyEgg: 3 | Incubator: 1 | TroyDisk: 3
2016-08-08 21:25:54,601 [PokemonGoBot] [INFO] Potion: 5 | SuperPotion: 10 | HyperPotion: 15 | MaxPotion: 0
2016-08-08 21:25:54,601 [PokemonGoBot] [INFO] Incense: 6 | IncenseSpicy: 0 | IncenseCool: 0
2016-08-08 21:25:54,602 [PokemonGoBot] [INFO] Revive: 15 | MaxRevive: 0
2016-08-08 21:25:54,602 [PokemonGoBot] [INFO] 
2016-08-08 21:25:54,602 [PokemonGoBot] [INFO] Found encrypt.so! Platform: linux2 Encrypt.so directory: /root/PokemonGo-Bot
2016-08-08 21:25:54,602 [PokemonGoBot] [INFO] 
2016-08-08 21:26:01,720 [PokemonGoBot] [INFO] [bot_start] Starting bot...
2016-08-08 21:26:03,295 [CollectLevelUpReward] [INFO] [level_up_reward] Received level up reward: []
2016-08-08 21:26:03,296 [IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 1.90 km
2016-08-08 21:26:04,171 [RecycleItems] [INFO] [item_discarded] Discarded 3x Pokeball (maximum 50).
2016-08-08 21:26:04,429 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Eevee appeared! [CP 14] [Potential 0.64] [S/A/D 15/1/13]
2016-08-08 21:26:07,186 [PokemonCatchWorker] [INFO] [threw_pokeball] Used Pokeball, with chance 100.00 (52 left)
2016-08-08 21:26:07,637 [PokemonCatchWorker] [INFO] [pokemon_caught] Captured Eevee! [CP 14] [Potential 0.64] [15/1/13] [+210 exp]
2016-08-08 21:26:13,114 [  SpinFort] [INFO] [spun_pokestop] Spun pokestop 秋葉原ラジオ会館. Experience awarded: 50. Items awarded: {u'Potion': 1, u'Pokeball': 2}
2016-08-08 21:26:15,513 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop でじこの看板 - 0.06km (attraction of lure 0.36km)
2016-08-08 21:26:18,336 [TransferPokemon] [INFO] [keep_best_release] Keeping best 1 Eevee, based on cp
2016-08-08 21:26:19,271 [TransferPokemon] [INFO] [pokemon_release] Exchanged Eevee [CP 14] [IV 0.64] for candy.
2016-08-08 21:26:22,109 [RecycleItems] [INFO] [item_discarded] Discarded 1x Pokeball (maximum 50).
2016-08-08 21:26:23,236 [RecycleItems] [INFO] [item_discarded] Discarded 1x Potion (maximum 5).
2016-08-08 21:26:23,503 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Eevee appeared! [CP 287] [Potential 0.62] [S/A/D 15/8/5]
2016-08-08 21:26:27,011 [PokemonCatchWorker] [INFO] [threw_pokeball] Used Pokeball, with chance 37.87 (50 left)
2016-08-08 21:26:27,691 [       cli] [INFO] 
2016-08-08 21:26:27,691 [       cli] [INFO] Ran for 0:00:36
2016-08-08 21:26:27,691 [       cli] [INFO] Total XP Earned: 260  Average: 25930.02/h
2016-08-08 21:26:27,691 [       cli] [INFO] Travelled 0.00km
2016-08-08 21:26:27,692 [       cli] [INFO] Visited 1 stops
2016-08-08 21:26:27,692 [       cli] [INFO] Encountered 2 pokemon, 1 caught, 1 released, 0 evolved, 0 never seen before
2016-08-08 21:26:27,692 [       cli] [INFO] Threw 2 pokeballs
2016-08-08 21:26:27,692 [       cli] [INFO] Earned 100 Stardust
2016-08-08 21:26:27,692 [       cli] [INFO] 
2016-08-08 21:26:27,692 [       cli] [INFO] Highest CP Pokemon: Eevee [CP: 14] [IV: 15/1/13] Potential: 0.64 
2016-08-08 21:26:27,692 [       cli] [INFO] Most Perfect Pokemon: Eevee [CP: 14] [IV: 15/1/13] Potential: 0.64 
Traceback (most recent call last):
  File "pokecli.py", line 503, in <module>
    main()
  File "pokecli.py", line 89, in main
    bot.tick()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 441, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 36, in work
    return self.catch_pokemon(self.bot.cell['catchable_pokemons'].pop(0))
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 48, in catch_pokemon
    return_value = worker.work()
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 329, in work
    data={'pokemon': pokemon_name}
  File "/root/PokemonGo-Bot/pokemongo_bot/base_task.py", line 27, in emit_event
    data=data
  File "/root/PokemonGo-Bot/pokemongo_bot/event_manager.py", line 52, in emit
    raise EventNotRegisteredException("Event %s not registered..." % event)
pokemongo_bot.event_manager.EventNotRegisteredException: Event pokemon_escaped not registered...
2016-08-08 21:26:27,706 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 848, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-08 21:26:27,707 [sentry.errors.uncaught] [ERROR] [u'EventNotRegisteredException: Event pokemon_escaped not registered...', u'  File "pokecli.py", line 503, in <module>', u'  File "pokecli.py", line 89, in main', u'  File "pokemongo_bot/__init__.py", line 441, in tick', u'  File "pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 36, in work', u'  File "pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 48, in catch_pokemon', u'  File "pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 329, in work', u'  File "pokemongo_bot/base_task.py", line 27, in emit_event', u'  File "pokemongo_bot/event_manager.py", line 52, in emit']
```

### Steps to Reproduce
Start the Bot, wait for Pokemon to catch, after catch they compare the already exists pokemon with the new and transfer the pokemon with lower cp

### Other Information
OS: Debian 8.5 Jessie
Git Commit: d0f60a221a8af7eaf7b41ffeeb756a636032534e
Python Version: Python 2.7.9

**Comment by XxHeadSh0T** [comment]
Updated Git Commit: f648be31c15d0143bccc0531571b2d00fd88ec4d
Now the Bot works ~10 minutes, then
...
Traceback (most recent call last):
  File "pokecli.py", line 503, in <module>
    main()
  File "pokecli.py", line 89, in main
    bot.tick()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 405, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 36, in work
    return self.catch_pokemon(self.bot.cell['catchable_pokemons'].pop(0))
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 48, in catch_pokemon
    return_value = worker.work()
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 329, in work
    data={'pokemon': pokemon_name}
  File "/root/PokemonGo-Bot/pokemongo_bot/base_task.py", line 27, in emit_event
    data=data
  File "/root/PokemonGo-Bot/pokemongo_bot/event_manager.py", line 52, in emit
    raise EventNotRegisteredException("Event %s not registered..." % event)
pokemongo_bot.event_manager.EventNotRegisteredException: Event pokemon_escaped not registered...
2016-08-08 22:14:26,021 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 848, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-08 22:14:26,023 [sentry.errors.uncaught] [ERROR] [u'EventNotRegisteredException: Event pokemon_escaped not registered...', u'  File "pokecli.py", line 503, in <module>', u'  File "pokecli.py", line 89, in main', u'  File "pokemongo_bot/__init__.py", line 405, in tick', u'  File "pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 36, in work', u'  File "pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 48, in catch_pokemon', u'  File "pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 329, in work', u'  File "pokemongo_bot/base_task.py", line 27, in emit_event', u'  File "pokemongo_bot/event_manager.py", line 52, in emit']
...

**Comment by k4n30** [comment]
Please update again, and post your config (user, pass, gmapkey removed) if you still have the issue

**Comment by XxHeadSh0T** [comment]
I think it is fixxed.

**Comment by k4n30** [comment]
Feel free to reopen the issue if it comes back
