### ISSUE TITLE
Getting errors __init__.py after a few minutes

### ISSUE THREAD

**Issue by bfmramalho** [PokemonGoF/PokemonGo-Bot#3141]
### Expected Behavior
Running without exiting.

### Actual Behavior
Getting errors after a few minutes of running.

```
2016-08-08 20:37:36,320 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Goldeen appeared! [CP 396] [Potential 0.53] [S/A/D 12/10/2]
2016-08-08 20:37:39,227 [PokemonCatchWorker] [INFO] [threw_pokeball] Used Pokeball, with chance 37.43 (40 left)
2016-08-08 20:37:40,226 [       cli] [INFO] 
2016-08-08 20:37:40,227 [       cli] [INFO] Ran for 0:03:14
2016-08-08 20:37:40,227 [       cli] [INFO] Total XP Earned: 1860  Average: 34465.37/h
2016-08-08 20:37:40,227 [       cli] [INFO] Travelled 0.16km
2016-08-08 20:37:40,227 [       cli] [INFO] Visited 2 stops
2016-08-08 20:37:40,227 [       cli] [INFO] Encountered 6 pokemon, 6 caught, 0 released, 0 evolved, 0 never seen before
2016-08-08 20:37:40,227 [       cli] [INFO] Threw 7 pokeballs
2016-08-08 20:37:40,228 [       cli] [INFO] Earned 2200 Stardust
2016-08-08 20:37:40,228 [       cli] [INFO] 
2016-08-08 20:37:40,228 [       cli] [INFO] Highest CP Pokemon: Goldeen [CP: 486] [IV: 12/0/6] Potential: 0.4 
2016-08-08 20:37:40,228 [       cli] [INFO] Most Perfect Pokemon: Paras [CP: 277] [IV: 6/15/6] Potential: 0.6 
Traceback (most recent call last):
  File "pokecli.py", line 503, in <module>
    main()
  File "pokecli.py", line 89, in main
    bot.tick()
  File "/Users/brunoramalho/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 441, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/Users/brunoramalho/Desktop/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 36, in work
    return self.catch_pokemon(self.bot.cell['catchable_pokemons'].pop(0))
  File "/Users/brunoramalho/Desktop/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 48, in catch_pokemon
    return_value = worker.work()
  File "/Users/brunoramalho/Desktop/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 329, in work
    data={'pokemon': pokemon_name}
  File "/Users/brunoramalho/Desktop/PokemonGo-Bot/pokemongo_bot/base_task.py", line 27, in emit_event
    data=data
  File "/Users/brunoramalho/Desktop/PokemonGo-Bot/pokemongo_bot/event_manager.py", line 52, in emit
    raise EventNotRegisteredException("Event %s not registered..." % event)
pokemongo_bot.event_manager.EventNotRegisteredException: Event pokemon_escaped not registered...
2016-08-08 20:37:40,250 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/brunoramalho/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/brunoramalho/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/brunoramalho/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/brunoramalho/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/brunoramalho/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/brunoramalho/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/brunoramalho/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/brunoramalho/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 891, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-08 20:37:40,255 [sentry.errors.uncaught] [ERROR] [u'EventNotRegisteredException: Event pokemon_escaped not registered...', u'  File "pokecli.py", line 503, in <module>', u'  File "pokecli.py", line 89, in main', u'  File "pokemongo_bot/__init__.py", line 441, in tick', u'  File "pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 36, in work', u'  File "pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 48, in catch_pokemon', u'  File "pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 329, in work', u'  File "pokemongo_bot/base_task.py", line 27, in emit_event', u'  File "pokemongo_bot/event_manager.py", line 52, in emit']
```

### Other Information
OS: Mac OS
Git Commit: d0f60a221a8af7eaf7b41ffeeb756a636032534e
Python Version: 2.7.10

**Comment by GitPupper** [comment]
Update your Python to 2.7.12 and update your git commit version. You are WAY down there.

**Comment by JaroSound** [comment]
@GitPupper How to update Python?

**Comment by bfmramalho** [comment]
@GitPupper yes you were right, I updated Python to 2.7.12.
When I cloned the repo, I switched to dev, but forgot to pull.
Now it's running for 10 min without any issue. Closing this issue...

@JaroSound [here](https://www.python.org/downloads/release/python-2712/) you can find this specific version, download the version Mac OS X 64-bit/32-bit installer, and reboot. Check the version running ```python -V```

Then you need to ```pull origin dev``` and run again the installation ```virtualenv .```, ```source bin/activate``` and ```pip install -r requirements.txt```
You may need to recreate the config.json again with your credentials.

**Comment by JaroSound** [comment]
But i use Debian, so there is no linux version?
