### ISSUE TITLE
Error when Lured Pokemon Appear

### ISSUE THREAD

**Issue by zviper13579** [PokemonGoF/PokemonGo-Bot#3145]
PokemonGo-Bot/pokemongo_bot/event_manager.py", line 52, in emit
    raise EventNotRegisteredException("Event %s not registered..." % event)
pokemongo_bot.event_manager.EventNotRegisteredException: Event pokemon_escaped not registered...
2016-08-08 13:18:13,132 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/uuu/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/uuu/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/uuu/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/uuu/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/uuu/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/uuu/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/uuu/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/uuu/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-08 13:18:13,133 [sentry.errors.uncaught] [ERROR] [u'EventNotRegisteredException: Event pokemon_escaped not registered...', u'  File "pokecli.py", line 503, in <module>', u'  File "pokecli.py", line 89, in main', u'  File "pokemongo_bot/__init__.py", line 441, in tick', u'  File "pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 36, in work', u'  File "pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 48, in catch_pokemon', u'  File "pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 329, in work', u'  File "pokemongo_bot/base_task.py", line 27, in emit_event', u'  File "pokemongo_bot/event_manager.py", line 52, in emit']

### Other Information
OS: Mac

**Comment by alxistn** [comment]
I have the same issue on **Ubuntu 16.04**

**Comment by g2384** [comment]
check [https://github.com/PokemonGoF/PokemonGo-Bot/commit/f648be31c15d0143bccc0531571b2d00fd88ec4d](https://github.com/PokemonGoF/PokemonGo-Bot/commit/f648be31c15d0143bccc0531571b2d00fd88ec4d), it may be fixed. I had the same issue, now I'm testing that commit.

**Comment by zviper13579** [comment]
You are the best! That Fixed it

**Comment by alxistn** [comment]
I confirm it's working now

**Comment by TheGoldenXY** [comment]
This issue has been fixed.

/closed
