### ISSUE TITLE
Error after startup and Pokemon capture

### ISSUE THREAD

**Issue by HowieMowie** [PokemonGoF/PokemonGo-Bot#3153]
Please check configuration at http://jsonlint.com/ before posting an issue.

### Expected Behavior
Expected behavior is to find, catch and proceed to next closet pokestop.

### Actual Behavior
Bot starts at location specified and finds a wild evee, catches evee and doesn't transfer then fails.
[2016-08-08 16:46:48] [x] Starting PokemonGo Bot....
[2016-08-08 16:46:49] [Catch] A wild Eevee appeared! [CP 77] [Potential 0.84]
[2016-08-08 16:46:53] [Catch] Using Pokeball... (136 left!)
[2016-08-08 16:46:54] [Catch] Eevee has been caught! (CP 77, IV 0.84)
[2016-08-08 16:46:54] [Catch] Rewards: 210 XP, 100 Stardust, 3 Candy
[2016-08-08 16:46:54] [Transfer] Transferring caught Pokemon with CP NOT above 100 and IV NOT above 0.4 and excluding [''].
[2016-08-08 16:46:54] [Transfer] No Pokemon to transfer.
[2016-08-08 16:46:54] [Transfer] Transferred 0 Pokemon.
Traceback (most recent call last):
  File "pokecli.py", line 361, in <module>
    main()
  File "pokecli.py", line 354, in main
    bot.run()
  File "/home/howard/OpenPoGoBot/pokemongo_bot/__init__.py", line 109, in run
    self.stepper.get_route_between(position_lat, position_lng, destination.target_lat, destination.target_lng, destination.target_alt)
  File "/home/howard/OpenPoGoBot/pokemongo_bot/stepper.py", line 75, in get_route_between
    path_points = self.path_finder.path(from_lat, from_lng, to_lat, to_lng)
  File "/home/howard/OpenPoGoBot/pokemongo_bot/navigation/path_finder/google_path_finder.py", line 15, in path
    gmaps = googlemaps.Client(key=self.config.gmapkey)
  File "/home/howard/OpenPoGoBot/env/local/lib/python2.7/site-packages/googlemaps/client.py", line 108, in __init__
    raise ValueError("Must provide API key or enterprise credentials "
ValueError: Must provide API key or enterprise credentials when creating client.

### Steps to Reproduce
start OpenPoGoBot with -a ptc with user password and location coordinates.

### Other Information
OS: Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here) 050d266aadc208de7656c6062b121a309bf3268f
Python Version: (run 'python -V' and paste it here) Python 2.7.6

**Comment by g2384** [comment]
What is your config.json? Do you have a google map API key?

**Comment by HowieMowie** [comment]
No config.json file specified.  I do not have a google map API key.

**Comment by g2384** [comment]
Then you cannot use this bot. Those are basic requirements.

**Comment by adamvc21** [comment]
https://console.developers.google.com/

Use a new google account generate a Browser API key, copy paste it.

**Comment by HowieMowie** [comment]
I'm assuming this was a change since the update by Niantic.  I didn't see the new requirement in the github page.  Will try to find more info on that requirement.

**Comment by HowieMowie** [comment]
thank you.
