### ISSUE TITLE
Bot will not work on Mac after API change

### ISSUE THREAD

**Issue by Messingaroung2323** [PokemonGoF/PokemonGo-Bot#3184]
### Expected Behavior
Bot commences working.

### Actual Behavior
(PokemonGo-Bot) Seths-MacBook-Pro:PokemonGo-Bot Roessmann$ python pokecli.py
2016-08-08 18:41:24,305 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-08 18:41:24,307 [       cli] [INFO] No config argument specified, checking for /configs/config.json
2016-08-08 18:41:24,325 [       cli] [INFO] Configuration initialized
2016-08-08 18:41:24,326 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more logrmation:
2016-08-08 18:41:24,326 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-08 18:41:24,400 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-08 18:41:24,494 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "/Users/Roessmann/PokemonGo-Bot/PokemonGo-Bot/PokemonGo-Bot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/Users/Roessmann/PokemonGo-Bot/PokemonGo-Bot/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 90, in call
    if not self.can_call():
  File "/Users/Roessmann/PokemonGo-Bot/PokemonGo-Bot/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 54, in can_call
    raise NoPlayerPositionSetException()
pgoapi.exceptions.NoPlayerPositionSetException
2016-08-08 18:41:34,828 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/Roessmann/PokemonGo-Bot/PokemonGo-Bot/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/Roessmann/PokemonGo-Bot/PokemonGo-Bot/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/Roessmann/PokemonGo-Bot/PokemonGo-Bot/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/Roessmann/PokemonGo-Bot/PokemonGo-Bot/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/Roessmann/PokemonGo-Bot/PokemonGo-Bot/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/Roessmann/PokemonGo-Bot/PokemonGo-Bot/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/Roessmann/PokemonGo-Bot/PokemonGo-Bot/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/Roessmann/PokemonGo-Bot/PokemonGo-Bot/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-08 18:41:35,086 [sentry.errors.uncaught] [ERROR] [u'NoPlayerPositionSetException', u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", line 127, in main', u'  File "pokecli.py", line 136, in report_summary', u'  File "pokemongo_bot/metrics.py", line 76, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 90, in call', u'  File "pokemongo_bot/api_wrapper.py", line 54, in can_call']
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
(PokemonGo-Bot) Seths-MacBook-Pro:PokemonGo-Bot Roessmann$ 

### Steps to Reproduce
Entering the python pokecli.py command.

### Other Information
OS: Mac
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
153ea212999e337b54e09761f6defbabb0de4e8c

Alternative methods to get it running have told me access denied. Any help?

**Comment by ChristianYeah** [comment]
Same thing. but it works for ptc auth. have no idea :(

**Comment by fayqiao** [comment]
Same here:


2016-08-09 12:14:26,788 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-09 12:14:26,789 [       cli] [INFO] No config argument specified, checking for /configs/config.json
2016-08-09 12:14:26,791 [       cli] [INFO] Configuration initialized
2016-08-09 12:14:26,791 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more logrmation:
2016-08-09 12:14:26,791 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-09 12:14:26,803 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-09 12:14:27,390 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-09 12:14:27,391 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-09 12:14:27,391 [PokemonGoBot] [INFO] [location_found] Location found: -33.862, 151.206647 (-33.862, 151.206647, 0.0)
2016-08-09 12:14:27,391 [PokemonGoBot] [INFO] [position_update] Now at (-33.862, 151.206647, 0)
2016-08-09 12:14:27,391 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-09 12:14:33,555 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-09 12:14:36,245 [PokemonGoBot] [INFO] 
2016-08-09 12:14:36,246 [PokemonGoBot] [INFO] --- MyAccount ---
2016-08-09 12:14:36,246 [PokemonGoBot] [INFO] Level: 26 (Next Level: 18330 XP) (Total: 1081670 XP)
2016-08-09 12:14:36,246 [PokemonGoBot] [INFO] Pokemon Captured: 4250 | Pokestops Visited: 2235
2016-08-09 12:14:36,247 [PokemonGoBot] [INFO] Pokemon Bag: 113/250
2016-08-09 12:14:36,247 [PokemonGoBot] [INFO] Items: 262/350
2016-08-09 12:14:36,247 [PokemonGoBot] [INFO] Stardust: 448122 | Pokecoins: 0
2016-08-09 12:14:36,247 [PokemonGoBot] [INFO] PokeBalls: 29 | GreatBalls: 6 | UltraBalls: 43
2016-08-09 12:14:36,247 [PokemonGoBot] [INFO] RazzBerries: 29 | BlukBerries: 0 | NanabBerries: 0
2016-08-09 12:14:36,247 [PokemonGoBot] [INFO] LuckyEgg: 5 | Incubator: 0 | TroyDisk: 6
2016-08-09 12:14:36,247 [PokemonGoBot] [INFO] Potion: 0 | SuperPotion: 36 | HyperPotion: 39
2016-08-09 12:14:36,248 [PokemonGoBot] [INFO] Incense: 8 | IncenseSpicy: 0 | IncenseCool: 0
2016-08-09 12:14:36,248 [PokemonGoBot] [INFO] Revive: 10 | MaxRevive: 0
2016-08-09 12:14:36,248 [PokemonGoBot] [INFO] 
2016-08-09 12:14:36,248 [PokemonGoBot] [INFO] Found encrypt.so! Platform: darwin Bot root directory: /Users/Me/Pokemon/PokemonGo-Bot
2016-08-09 12:14:36,248 [PokemonGoBot] [INFO] 
2016-08-09 12:14:47,123 [       cli] [INFO] 
2016-08-09 12:14:47,123 [       cli] [INFO] Ran for 0:00:20
2016-08-09 12:14:47,123 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-09 12:14:47,123 [       cli] [INFO] Travelled 0.00km
2016-08-09 12:14:47,123 [       cli] [INFO] Visited 0 stops
2016-08-09 12:14:47,123 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-09 12:14:47,123 [       cli] [INFO] Threw 0 pokeballs
2016-08-09 12:14:47,123 [       cli] [INFO] Earned 0 Stardust
2016-08-09 12:14:47,124 [       cli] [INFO] 
2016-08-09 12:14:47,124 [       cli] [INFO] Highest CP Pokemon: 
2016-08-09 12:14:47,124 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 133, in main
    raise e
IndexError: list index out of range
2016-08-09 12:14:47,131 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/Me/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/Me/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/Me/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/Me/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/Me/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/Me/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/Me/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/Me/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 891, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-09 12:14:47,132 [sentry.errors.uncaught] [ERROR] [u'IndexError: list index out of range', u'  File "pokecli.py", line 502, in <module>', u'  File "pokecli.py", line 133, in main']

**Comment by ChristianYeah** [comment]
can you guys pls try the ptc auth?
Its working for ptc, but for google, no

**Comment by fayqiao** [comment]
Tried ptc account and works for me

**Comment by fayqiao** [comment]
Ok, it works again.

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this issue has been resolved. If I'm wrong, please reopen.
