### ISSUE TITLE
HTTP Connection Pool: Max Retries exceeded

### ISSUE THREAD

**Issue by andreaem-it** [PokemonGoF/PokemonGo-Bot#3191]
Please check configuration at http://jsonlint.com/ before posting an issue.

### Actual Behavior

2016-08-09 04:32:36,518 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-09 04:32:36,522 [       cli] [INFO] Configuration initialized
2016-08-09 04:32:36,523 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more logrmation:
2016-08-09 04:32:36,523 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-09 04:32:36,542 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 133, in main
    raise e
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.google-analytics.com', port=80): Max retries exceeded with url: /collect (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10f7ef0d0>: Failed to establish a new connection: [Errno 64] EHOSTDOWN',))
2016-08-09 04:32:36,559 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/andreaem/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/andreaem/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/andreaem/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/andreaem/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/andreaem/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/andreaem/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/andreaem/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/andreaem/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 891, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-09 04:32:36,568 [sentry.errors.uncaught] [ERROR] [u"ConnectionError: HTTPConnectionPool(host='www.google-analytics.com', port=80): Max retries exceeded with url: /collect (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10f7ef0d0>: Failed to establish a new connection: [Errno 64] EHOSTDOWN',))", u'  File "pokecli.py", line 502, in <module>', u'  File "pokecli.py", line 133, in main']
### Steps to Reproduce

sh run.sh
### Other Information
OS: macOS 10.12
Git Commit: 5b3fe3d187b6b5fdfdede00f064bf7bcbd5a484d
Python Version: Python 2.7.10

**Comment by mrthrowaway** [comment]
changing health_record to false should prevent this
