### ISSUE TITLE
Sequence contain no matching element

### ISSUE THREAD

**Issue by JigokuTenshou** [PokemonGoF/PokemonGo-Bot#3196]
Please check configuration at http://jsonlint.com/ before posting an issue.

### Expected Behavior
1] Error reloading Pokemon list: Sequence contains no matching element
[10:34:38] Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PokemonGo.RocketAPI.Rpc.Inventory.<>c__DisplayClass2_2.<GetPokemonToEvolve>b__4(Candy x) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\Inventory.cs:line 60
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at PokemonGo.RocketAPI.Rpc.Inventory.<GetPokemonToEvolve>d__2.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\Inventory.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<StatsLog>d__14.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 181
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 115
[10:34:38] Starting again in 10 seconds...
[10:34:49] Export Player Infos and all Pokemon to "\Config\PokemonList.csv"
[10:34:50] Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PokemonGo.RocketAPI.Rpc.Inventory.<GetPlayerStats>d__24.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\Inventory.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<StatsLog>d__14.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 115

### Steps to Reproduce

Just started the bot and then it start working then after 1min the error start

**Comment by mrthrowaway** [comment]
You're using a different bot from the one this issues section is meant for
