### ISSUE TITLE
[sentry.errors.uncaught] [ERROR] Help

### ISSUE THREAD

**Issue by Elim160** [PokemonGoF/PokemonGo-Bot#3199]
Traceback (most recent call last):
  File "pokecli.py", line 501, in <module>
    main()
  File "pokecli.py", line 132, in main
    raise e
IndexError: list index out of range
2016-08-08 22:03:26,677 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/Eli/Desktop/PokemoniG/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/Eli/Desktop/PokemoniG/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/Eli/Desktop/PokemoniG/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/Eli/Desktop/PokemoniG/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/Eli/Desktop/PokemoniG/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/Eli/Desktop/PokemoniG/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/Eli/Desktop/PokemoniG/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/Eli/Desktop/PokemoniG/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-08 22:03:26,683 [sentry.errors.uncaught] [ERROR] [u'IndexError: list index out of range', u'  File "pokecli.py", line 501, in <module>', u'  File "pokecli.py", line 132, in main']

Getting this error dont know what it means.

**Comment by Mortemer** [comment]
I'm getting that error too.  It was working just fine few hours ago.  Now when I start the bot it crashes after 30 seconds.

**Comment by Elim160** [comment]
@Mortemer Exactly just like mine

**Comment by Mortemer** [comment]
I think it's server issues.

**Comment by shivamkalra** [comment]
Similar to: https://github.com/PokemonGoF/PokemonGo-Bot/issues/3176

**Comment by shivamkalra** [comment]
Please look there for temporary solution. If it fixes close this one.

**Comment by Mortemer** [comment]
That update worked.  Thanks!
