### ISSUE TITLE
Dev branch is not working

### ISSUE THREAD

**Issue by msoedov** [PokemonGoF/PokemonGo-Bot#320]
### Expected Behavior

I want to caught some pokemons 

### Actual Behavior

[x] PokemonGO Bot v1.0
[x] Configuration initialized

[x] Address found: Boston MA
[x] Position in-game set as: (42.3600825, -71.0588801, 0.0)

Traceback (most recent call last):
  File "pokecli.py", line 120, in <module>
    main()
  File "pokecli.py", line 108, in main
    bot.start()
  File "/Users/msoedov/misc/PokemonGo-Bot/pokemongo_bot/__init__.py", line 26, in start
    self._setup_api()
  File "/Users/msoedov/misc/PokemonGo-Bot/pokemongo_bot/__init__.py", line 98, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'player_data'
### Other Information
OS: MacOS
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
6d0e579f3223f5210ced6ff34da2c3b92f320b4d

**Comment by solderzzc** [comment]
There's update after that commit, how about now?

**Comment by MaxLeiter** [comment]
This is why a proper review system is needed

**Comment by solderzzc** [comment]
Some time, code breaks here mean server outage.

**Comment by ckrmml** [comment]
@solderzzc nope, servers up, errors the same

`Traceback (most recent call last):
  File "pokecli.py", line 107, in <module>
    main()
  File "pokecli.py", line 99, in main
    bot.start()
  File "/PokemonGo-Bot/pokemongo_bot/__init__.py", line 26, in start
    self._setup_api()
  File "PokemonGo-Bot/pokemongo_bot/__init__.py", line 142, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'player_data'`

**Comment by douglascamata** [comment]
You're running out of date code or in a dirty environment. Please remove your working directory, cleanup your Python environment, use virtualenv and the dev branch. It should work.

**Comment by arberb** [comment]
Run the command: PIP uninstall pgoapi
Then download the latest master branch of PGOAPI: https://github.com/tejado/pgoapi/archive/master.zip extract it and copy the pgoapi folder to bot folder

**Comment by douglascamata** [comment]
@MaxLeiter please, stop talking on issues if you don't know what the problem is about. I've been helping users fix this issue for 2 days already. Stay cool.

**Comment by douglascamata** [comment]
@arberb we're not downloading `pgoapi` directly anymore. It's downloaded through `pip install -r requirements.txt`.

**Comment by Wheaties466** [comment]
i still get this. I have run the pip install -r requirements.txt and I evem tried it with an upgrade.

File "pokecli.py", line 120, in <module>
    main()
  File "pokecli.py", line 108, in main
    bot.start()
  File "/home/mike/PokemonGo-Bot/pokemongo_bot/__init__.py", line 26, in start
    self._setup_api()
  File "/home/mike/PokemonGo-Bot/pokemongo_bot/__init__.py", line 81, in _setup_api
    self._set_starting_position()
  File "/home/mike/PokemonGo-Bot/pokemongo_bot/__init__.py", line 252, in _set_starting_position
    self.position = self._get_pos_by_name(self.config.location)
  File "/home/mike/PokemonGo-Bot/pokemongo_bot/__init__.py", line 262, in _get_pos_by_name
    loc = geolocator.geocode(location_name)
  File "/usr/lib/python2.7/site-packages/geopy/geocoders/googlev3.py", line 217, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/usr/lib/python2.7/site-packages/geopy/geocoders/base.py", line 170, in _call_geocoder
    raise GeocoderTimedOut('Service timed out')
geopy.exc.GeocoderTimedOut: Service timed out


I can't seem to get it to start on the master branch or the dev branch.

**Comment by ubaltaci** [comment]
as @douglascamata previously mentioned, 

in main folder, step by step:

1. `git co dev` 
2. `rm -rf pgoapi`
3. `pip install -r requirements.txt`

-or-

you may completely remove the project folder and clone it again.

**Comment by judsona** [comment]
I had an older version of a dependency as well. 

pip install -U -r requirements.txt

**Comment by solderzzc** [comment]
please reopen if you're still facing this issue.
