### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by jlim0930** [PokemonGoF/PokemonGo-Bot#3200]
was working fine all day then all the sudden started to fail with list index out of range

### Actual Behavior
Traceback (most recent call last):
  File "pokecli.py", line 521, in <module>
    main()
  File "pokecli.py", line 95, in main
    bot.tick()
  File "/home/jlim/newbot/XXXXXX/dev/pokemongo_bot/__init__.py", line 446, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/jlim/newbot/XXXXXX/dev/pokemongo_bot/cell_workers/recycle_items.py", line 22, in work
    item_count_dict = self.bot.item_inventory_count('all')
  File "/home/jlim/newbot/XXXXXX/dev/pokemongo_bot/__init__.py", line 820, in item_inventory_count
    inventory_req = self.get_inventory()
  File "/home/jlim/newbot/XXXXXX/dev/pokemongo_bot/__init__.py", line 781, in get_inventory
    self.latest_inventory = self.api.get_inventory()
  File "/home/jlim/newbot/XXXXXX/dev/src/pgoapi/pgoapi/pgoapi.py", line 122, in function
    return request.call()
  File "/home/jlim/newbot/XXXXXX/dev/pokemongo_bot/api_wrapper.py", line 106, in call
    result = self._call()
  File "/home/jlim/newbot/XXXXXX/dev/pokemongo_bot/api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "/home/jlim/newbot/XXXXXX/dev/src/pgoapi/pgoapi/pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/home/jlim/newbot/XXXXXX/dev/src/pgoapi/pgoapi/rpc_api.py", line 129, in request
    response_dict = self._parse_main_response(response, subrequests)
  File "/home/jlim/newbot/XXXXXX/dev/src/pgoapi/pgoapi/rpc_api.py", line 359, in _parse_main_response
    response_proto_dict = self._parse_sub_responses(response_proto, subrequests, response_proto_dict)
  File "/home/jlim/newbot/XXXXXX/dev/src/pgoapi/pgoapi/rpc_api.py", line 376, in _parse_sub_responses
    request_entry = subrequests_list[i]
IndexError: list index out of range
2016-08-08 23:02:48,605 [sentry.errors] [ERROR] Sentry responded with an error: 'module' object has no attribute 'HTTPSHandler' (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/jlim/newbot/XXXXXX/dev/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/jlim/newbot/XXXXXX/dev/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/jlim/newbot/XXXXXX/dev/local/lib/python2.7/site-packages/raven/utils/http.py", line 44, in urlopen
    class ValidHTTPSHandler(urllib2.HTTPSHandler):
AttributeError: 'module' object has no attribute 'HTTPSHandler'
2016-08-08 23:02:48,606 [sentry.errors.uncaught] [ERROR] [u'IndexError: list index out of range', u'  File "pokecli.py", line 521, in <module>', u'  File "pokecli.py", line 95, in main', u'  File "pokemongo_bot/__init__.py", line 446, in tick', u'  File "pokemongo_bot/cell_workers/recycle_items.py", line 22, in work', u'  File "pokemongo_bot/__init__.py", line 820, in item_inventory_count', u'  File "pokemongo_bot/__init__.py", line 781, in get_inventory', u'  File "pgoapi/pgoapi.py", line 122, in function', u'  File "pokemongo_bot/api_wrapper.py", line 106, in call', u'  File "pokemongo_bot/api_wrapper.py", line 63, in _call', u'  File "pgoapi/pgoapi.py", line 220, in call', u'  File "pgoapi/rpc_api.py", line 129, in request', u'  File "pgoapi/rpc_api.py", line 359, in _parse_main_response', u'  File "pgoapi/rpc_api.py", line 376, in _parse_sub_responses']

### Other Information
OS: Ubuntu 14.04.5 LTS
Git Commit: a2b9fe9be9642612420612795a15bc691189f8c9
Python Version: Python 2.7.6

**Comment by ThadeuBrito** [comment]
is it fix?
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3193

**Comment by Ryurem** [comment]
How about looking at the other issues,before making a useless report?

**Comment by mywarr** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3193#issuecomment-238439725

**Comment by liampuddles** [comment]
Having same issue as above after completing #3193 

Originally 
"File "pokecli.py", line 521, in <module>
    main()
  File "pokecli.py", line 81, in main
    bot.start()"


Now 
"File "pokecli.py", line 521, in 
main()
File "pokecli.py", line 95, in main
bot.tick()"

**Comment by shivamkalra** [comment]
Can you try setting `health_record` and `update_map` in your config to `false`?

**Comment by liampuddles** [comment]
'Can you try setting `health_record` and `update_map` in your config to `false`?'

I have changed `health_record` to false but can not find `update_map`


Sorry if this is the wrong way to reply I am new to this

**Comment by shivamkalra** [comment]
@liampuddles So did it fix the problem?

**Comment by LeeRongWen** [comment]
@shivamkalra It`s fix from my side....

**Comment by liampuddles** [comment]
@shivamkalra  this did not fix my issue.

**Comment by mywarr** [comment]
@liampuddles 

there is a new config option in config.json 
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/configs/config.json.example

try to add this line 
```
"libencrypt_location": "",
```
in your config.json just below "gmapkey", for me, it solved the problem.

**Comment by LeeRongWen** [comment]
@mywarr i leave that config blank and just put the crypt .ddl file to the root dir and its also working fine...

**Comment by liampuddles** [comment]
@mywarr  So I just noticed it actually starts and stops after 14 seconds
