### ISSUE TITLE
 File "pokecli.py", line 41, in <module>     from pokemongo_bot import PokemonGoBot, TreeConfigBuilder

### ISSUE THREAD

**Issue by dragonsgomoo** [PokemonGoF/PokemonGo-Bot#3205]
Please check configuration at http://jsonlint.com/ before posting an issue.

### Expected Behavior
For Bot to start login process

### Actual Behavior
Traceback (most recent call last):
  File "pokecli.py", line 41, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "/Users/Wobble/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 19, in <module>
    import cell_workers
  File "/Users/Wobble/Desktop/PokemonGo-Bot/pokemongo_bot/cell_workers/__init__.py", line 3, in <module>
    from catch_lured_pokemon import CatchLuredPokemon
  File "/Users/Wobble/Desktop/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_lured_pokemon.py", line 4, in <module>
    from pokemongo_bot.cell_workers.utils import fort_details
  File "/Users/Wobble/Desktop/PokemonGo-Bot/pokemongo_bot/cell_workers/utils.py", line 6, in <module>
    from colorama import init
ImportError: No module named colorama

### Steps to Reproduce
When I run python pokecli.py

### Other Information
OS: X
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: 2.7.12

**Comment by shivamkalra** [comment]
Perhaps try

```
pip install  --upgrade -r requirements.txt
```

**Comment by dragonsgomoo** [comment]
Worked like a charm! Thanks, closing issue
