### ISSUE TITLE
KeyError: 'GET_MAP_OBJECTS'

### ISSUE THREAD

**Issue by LostDGod** [PokemonGoF/PokemonGo-Bot#321]
...
[#] Something rustles nearby!
[#] A Wild Zubat appeared! [CP 189]
[x] Using Pokeball...
[x] Captured Zubat! [CP 189] - exchanging for candy
[#] Zubat has been exchanged for candy!
Traceback (most recent call last):
  File "C:\Users\GOD\Desktop\PKGO\PokemonGo-Bot-dev\pokecli.py", line 120
, in <module>
    main()
  File "C:\Users\GOD\Desktop\PKGO\PokemonGo-Bot-dev\pokecli.py", line 113
, in main
    bot.take_step()
  File "C:\Users\GOD\Desktop\PKGO\PokemonGo-Bot-dev\pokemongo_bot\__init_
_.py", line 31, in take_step
    self.stepper.take_step()
  File "C:\Users\GOD\Desktop\PKGO\PokemonGo-Bot-dev\pokemongo_bot\stepper
.py", line 56, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "C:\Users\GOD\Desktop\PKGO\PokemonGo-Bot-dev\pokemongo_bot\stepper
.py", line 97, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "C:\Users\GOD\Desktop\PKGO\PokemonGo-Bot-dev\pokemongo_bot\__init_
_.py", line 54, in work_on_cell
    hack_chain = worker.work()
  File "C:\Users\GOD\Desktop\PKGO\PokemonGo-Bot-dev\pokemongo_bot\cell_wo
rkers\seen_fort_worker.py", line 35, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "C:\Users\GOD\Desktop\PKGO\PokemonGo-Bot-dev\pokemongo_bot\stepper
.py", line 75, in _walk_to
    self._work_at_position(i2f(self.api._position_lat), i2f(self.api._position_l
ng), alt, False)
  File "C:\Users\GOD\Desktop\PKGO\PokemonGo-Bot-dev\pokemongo_bot\stepper
.py", line 89, in _work_at_position
    json.dump({'lat': lat, 'lng': lng,'cells':response_dict['responses']['GET_MA
P_OBJECTS']['map_cells']}, outfile)
KeyError: 'GET_MAP_OBJECTS'

C:\Users\GOD\Desktop\PKGO\PokemonGo-Bot-dev>

So I figured this could be due to a server problem and not the bot itself since it worked perfectly for almost an hour. I guess someone should add a restart function starting on the last known position.

**Comment by LostDGod** [comment]
So I figured this could be due to a server problem and not the bot itself since it worked perfectly for almost an hour. I guess someone should add a restart function starting on the last known position.

**Comment by msoedov** [comment]
I had the same issue and this fix works for me https://github.com/PokemonGoF/PokemonGo-Bot/pull/323

**Comment by solderzzc** [comment]
some exception is good for avoid softban or hard ban.
So we need figure out the real policy then deal with it.
Let me close it for now.
