### ISSUE TITLE
Bot running for 14 seconds before stopping

### ISSUE THREAD

**Issue by liampuddles** [PokemonGoF/PokemonGo-Bot#3222]
Please check configuration at http://jsonlint.com/ before posting an issue.

### Expected Behavior
Should run fine, I do believe, was earlier today. API is up to date.

### Actual Behavior
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

2016-08-09 16:50:04,654 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-09 16:50:04,655 [       cli] [INFO] No config argument specified, checking for /configs/config.json
2016-08-09 16:50:04,658 [       cli] [INFO] Configuration initialized
2016-08-09 16:50:04,667 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-09 16:50:04,670 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-09 16:50:04,671 [PokemonGoBot] [INFO] [location_found] Location found: -33.8613,151.2108 (-33.8613, 151.2108, 0.0)
2016-08-09 16:50:04,674 [PokemonGoBot] [INFO] [position_update] Now at (-33.8613, 151.2108, 0)
2016-08-09 16:50:04,677 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-09 16:50:06,651 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-09 16:50:07,901 [PokemonGoBot] [INFO]
2016-08-09 16:50:07,903 [PokemonGoBot] [INFO] --- liampuddles ---
2016-08-09 16:50:07,904 [PokemonGoBot] [INFO] Level: 22 (Next Level: 17319 XP) (Total: 417681 XP)
2016-08-09 16:50:07,907 [PokemonGoBot] [INFO] Pokemon Captured: 1218 | Pokestops Visited: 1479
2016-08-09 16:50:07,910 [PokemonGoBot] [INFO] Pokemon Bag: 169/250
2016-08-09 16:50:07,911 [PokemonGoBot] [INFO] Items: 341/350
2016-08-09 16:50:07,913 [PokemonGoBot] [INFO] Stardust: 55858 | Pokecoins: 70
2016-08-09 16:50:07,914 [PokemonGoBot] [INFO] PokeBalls: 113 | GreatBalls: 78 | UltraBalls: 35
2016-08-09 16:50:07,917 [PokemonGoBot] [INFO] RazzBerries: 54 | BlukBerries: 0 | NanabBerries: 0
2016-08-09 16:50:07,918 [PokemonGoBot] [INFO] LuckyEgg: 2 | Incubator: 0 | TroyDisk: 3
2016-08-09 16:50:07,920 [PokemonGoBot] [INFO] Potion: 1 | SuperPotion: 0 | HyperPotion: 21 | MaxPotion: 0
2016-08-09 16:50:07,923 [PokemonGoBot] [INFO] Incense: 4 | IncenseSpicy: 0 | IncenseCool: 0
2016-08-09 16:50:07,924 [PokemonGoBot] [INFO] Revive: 28 | MaxRevive: 0
2016-08-09 16:50:07,927 [PokemonGoBot] [INFO]
2016-08-09 16:50:07,927 [PokemonGoBot] [INFO] Found encrypt.dll! Platform: win32 Encrypt.so directory: C:\Users\liam\Desktop\PokemonGo-Bot
2016-08-09 16:50:07,930 [PokemonGoBot] [INFO]
2016-08-09 16:50:16,193 [PokemonGoBot] [INFO] [bot_start] Starting bot...
2016-08-09 16:50:17,772 [CollectLevelUpReward] [INFO] [level_up_reward] Received level up reward: []
2016-08-09 16:50:17,776 [IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 1.94 km
2016-08-09 16:50:19,105 [       cli] [INFO]
2016-08-09 16:50:19,105 [       cli] [INFO] Ran for 0:00:14
2016-08-09 16:50:19,108 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-09 16:50:19,108 [       cli] [INFO] Travelled 0.00km
2016-08-09 16:50:19,109 [       cli] [INFO] Visited 0 stops
2016-08-09 16:50:19,111 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-09 16:50:19,114 [       cli] [INFO] Threw 0 pokeballs
2016-08-09 16:50:19,115 [       cli] [INFO] Earned 0 Stardust
2016-08-09 16:50:19,115 [       cli] [INFO]
2016-08-09 16:50:19,117 [       cli] [INFO] Highest CP Pokemon:
2016-08-09 16:50:19,118 [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 521, in <module>
    main()
  File "pokecli.py", line 95, in main
    bot.tick()
  File "C:\Users\liam\Desktop\PokemonGo-Bot\pokemongo_bot\__init__.py", line 441, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "C:\Users\liam\Desktop\PokemonGo-Bot\pokemongo_bot\cell_workers\transfer_pokemon.py", line 72, in work
    if self.should_release_pokemon(pokemon_name, pokemon_cp, pokemon_potential):
  File "C:\Users\liam\Desktop\PokemonGo-Bot\pokemongo_bot\cell_workers\transfer_pokemon.py", line 172, in should_release_pokemon
    if logic_to_function[cp_iv_logic](*release_results.values()):
KeyError: u'AND'

```
{
	"auth_service": "google",
	"username": "------------",
	"password": "----------",
	"location": "--------------",
	"gmapkey": "------------------",
	"libencrypt_location": "",
	"tasks": [{
		"type": "HandleSoftBan"
	}, {
		"type": "CollectLevelUpReward"
	}, {
		"type": "IncubateEggs",
		"config": {
			"longer_eggs_first": true
		}
	}, {
		"type": "TransferPokemon"
	}, {
		"type": "EvolvePokemon",
		"config": {
			"evolve_all": "none",
			"first_evolve_by": "cp",
			"evolve_above_cp": 500,
			"evolve_above_iv": 0.8,
			"logic": "or",
			"evolve_speed": 20,
			"use_lucky_egg": false
		}
	}, {
		"type": "RecycleItems",
		"config": {
			"item_filter": {
				"Pokeball": {
					"keep": 80
				},
				"Greatball": {
					"keep": 80
				},
				"Ultraball": {
					"keep": 80
				},
				"Potion": {
					"keep": 0
				},
				"Super Potion": {
					"keep": 0
				},
				"Hyper Potion": {
					"keep": 30
				},
				"Revive": {
					"keep": 30
				},
				"Razz Berry": {
					"keep": 50
				}
			}
		}
	}, {
		"type": "CatchVisiblePokemon"
	}, {
		"type": "CatchLuredPokemon"
	}, {
		"type": "SpinFort"
	}, {
		"type": "MoveToFort",
		"config": {
			"lure_attraction": false,
			"lure_max_distance": 2000
			}
	}, {
		"type": "FollowSpiral",
		"config": {
			"diameter": 4,
			"step_size": 70
		}
	}],
	"map_object_cache_time": 5,
	"forts": {
		"avoid_circles": true,
		"max_circle_size": 50
	},
	"websocket_server": false,
	"walk": 4.16,
	"action_wait_min": 1,
	"action_wait_max": 4,
	"debug": false,
	"test": false,
	"health_record": false,
	"location_cache": true,
	"distance_unit": "km",
	"reconnecting_timeout": 15,
	"evolve_captured": "NONE",
	"catch_randomize_reticle_factor": 1.0,
	"catch_randomize_spin_factor": 1.0,
	"catch": {
		"any": {
			"catch_above_cp": 0,
			"catch_above_iv": 0,
			"logic": "or"
		},
		"// Example of always catching Rattata:": {},
		"// Rattata": {
			"always_catch": true
		}
	},
	"release": {
		"any": {
			"release_below_cp": 500,
			"release_below_iv": 0.7,
			"logic": "AND"
		},
		"// Example of always releasing Rattata:": {},
		"Rattata": {
			"always_release": true
		},
		"// Example of keeping 3 stronger (based on CP) Pidgey:": {},
		"Pidgey": {
			"keep_best_cp": 1
		},
		"// Example of keeping 2 stronger (based on IV) Zubat:": {},
		"Zubat": {
			"keep_best_iv": 1
		},
		"// Also, it is working with any": {},
		"// any": {
			"keep_best_iv": 3
		},
		"// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
		"// Zubat": {
			"keep_best_cp": 2,
			"keep_best_iv": 3
		},
		"Caterpie": {
			"keep_best_cp": 1
		},
		"Weedle": {
			"keep_best_cp": 2
		},
		"Spearow": {
			"always_release": true
		},
		"Psyduck": {
			"keep_best_cp": 2
		},
		"Poliwag": {
			"keep_best_cp": 2
		},
		"Slowpoke": {
			"keep_best_cp": 2
		},
		"Magnemite": {
			"keep_best_cp": 2
		},
		"Shellder": {
			"keep_best_cp": 2
		},
		"Seel": {
			"keep_best_cp": 2
		},
		"Horsea": {
			"keep_best_cp": 1
		},
		"Golden": {
			"keep_best_cp": 1
		},
		"Staryu": {
			"keep_best_cp": 1
		}
	},
	"vips": {
		"Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
		"any": {
			"catch_above_cp": 1200,
			"catch_above_iv": 0.9,
			"logic": "or"
		},
		"Lapras": {},
		"Moltres": {},
		"Zapdos": {},
		"Articuno": {},

		"// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
		"Mewtwo": {},
		"Dragonite": {},
		"Snorlax": {},
		"// Mew evolves to Mewtwo": {},
		"Mew": {},
		"Arcanine": {},
		"Vaporeon": {},
		"Gyarados": {},
		"Exeggutor": {},
		"Muk": {},
		"Weezing": {},
		"Flareon": {}

	}
}

```

### Steps to Reproduce
python pokecli.py

re-install do it over again, JSON is valid on JSONLint

### Other Information
OS: Windows 10

**Comment by mrthrowaway** [comment]
`KeyError: u'AND'`

Maybe don't write it in caps?

**Comment by sffetlio** [comment]
Try with lowercase "and"
```
"any": {
            "release_below_cp": 500,
            "release_below_iv": 0.7,
            "logic": "AND"
        },
```

**Comment by liampuddles** [comment]
No one show this to my work colleagues okay.
