### ISSUE TITLE
Error when Session stale, re-logging in.

### ISSUE THREAD

**Issue by takenek** [PokemonGoF/PokemonGo-Bot#3228]
hey 
After today morning git pull i saw i get error every reloging but working after error but looks strange:

2016-08-09 09:28:34,172 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop XXXXXXXXXXXXXXXXXXXXXXXX - 0.07km (attraction of lure 0.75km)
2016-08-09 09:28:35,859 [PokemonGoBot] [INFO] [api_error] Session stale, re-logging in.
2016-08-09 09:28:35,859 [PokemonGoBot] [INFO] [login_started] Login procedure started.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/taken/PokemonGo-Bot/pokemongo_bot/__init__.py", line 994, in update_web_location_worker
    self.update_web_location()
  File "/home/taken/PokemonGo-Bot/pokemongo_bot/__init__.py", line 501, in update_web_location
    fort['gym_details'] = response_gym_details.get(
AttributeError: 'NotLoggedInException' object has no attribute 'get'

2016-08-09 09:28:37,644 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-09 09:28:37,645 [PokemonGoBot] [INFO] Found encrypt.so! Platform: linux2 Encrypt.so directory: /home/taken/PokemonGo-Bot
2016-08-09 09:28:38,821 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop XXXXXXXXXXXXXXX  - 0.07km (attraction of lure 0.74km)

**Comment by raxxon** [comment]
Just received the following:

```
2016-08-09 02:39:59,310 [PokemonGoBot] [INFO] [login_started] Login procedure started.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/hazer/PokemonGo-Bot/pokemongo_bot/__init__.py", line 999, in update_web_location_worker
    self.update_web_location()
  File "/home/hazer/PokemonGo-Bot/pokemongo_bot/__init__.py", line 506, in update_web_location
    fort['gym_details'] = response_gym_details.get(
AttributeError: 'NotLoggedInException' object has no attribute 'get'

2016-08-09 02:39:59,865 [PokemonGoBot] [INFO] [api_error] Server is throttling, reconnecting in 30 seconds
2016-08-09 02:40:29,873 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
```

hazer@BREAKPOINT:~/PokemonGo-Bot$ git log -n 1 --pretty=format:"%H" ; python -V
5e3179b9c22d355f5f324751d1e5d6df7c2b1148
Python 2.7.6
hazer@BREAKPOINT:~/PokemonGo-Bot$

**Comment by k4n30** [comment]
@takenek still having this issue on the lastest version?

**Comment by takenek** [comment]
hey everything ok in new git version :-)
