### ISSUE TITLE
can't run .UnicodeDecodeError:

### ISSUE THREAD

**Issue by GucciChen** [PokemonGoF/PokemonGo-Bot#3232]
SubjectAltNameWarning
/usr/local/lib/python2.7/dist-packages/urllib3/connection.py:303: SubjectAltNameWarning: Certificate for pgorelease.nianticlabs.com has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
Traceback (most recent call last):
  File "pokecli.py", line 521, in <module>
    main()
  File "pokecli.py", line 137, in main
    report_summary(bot)
  File "pokecli.py", line 146, in report_summary
    metrics.capture_stats()
  File "/home/gucci/PokemonGo-Bot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/home/gucci/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 106, in call
    result = self._call()
  File "/home/gucci/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "/home/OpenPoGoBot/src/pgoapi/pgoapi/pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/home/OpenPoGoBot/src/pgoapi/pgoapi/rpc_api.py", line 129, in request
    response_dict = self._parse_main_response(response, subrequests)
  File "/home/OpenPoGoBot/src/pgoapi/pgoapi/rpc_api.py", line 332, in _parse_main_response
    raise ServerSideAccessForbiddenException("Seems your IP Address is banned or something else went badly wrong...")
pgoapi.exceptions.ServerSideAccessForbiddenException: Seems your IP Address is banned or something else went badly wrong...
2016-08-09 15:50:40,397 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-09 15:50:40,400 [sentry.errors.uncaught] [ERROR] [u'ServerSideAccessForbiddenException: Seems your IP Address is banned or something else went badly wrong...', u'  File "pokecli.py", line 521, in <module>', u'  File "pokecli.py", line 137, in main', u'  File "pokecli.py", line 146, in report_summary', u'  File "pokemongo_bot/metrics.py", line 76, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 106, in call', u'  File "pokemongo_bot/api_wrapper.py", line 63, in _call', u'  File "pgoapi/pgoapi.py", line 220, in call', u'  File "pgoapi/rpc_api.py", line 129, in request', u'  File "pgoapi/rpc_api.py", line 332, in _parse_main_response']

OS:  deibian 8
Git Commit: e4c54dc593b7202ac95ebd70cfc672e88eb878ee
Python Version: 2.7,11

**Comment by zekone** [comment]
also woke up to 
```
Traceback (most recent call last):
  File "pokecli.py", line 501, in <module>
    main()
  File "pokecli.py", line 130, in main
    report_summary(bot)
  File "pokecli.py", line 139, in report_summary
    metrics.capture_stats()
  File "/usr/src/app/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/usr/src/app/pokemongo_bot/api_wrapper.py", line 106, in call
    result = self._call()
  File "/usr/src/app/pokemongo_bot/api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "/usr/src/app/src/pgoapi/pgoapi/pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/usr/src/app/src/pgoapi/pgoapi/rpc_api.py", line 129, in request
    response_dict = self._parse_main_response(response, subrequests)
  File "/usr/src/app/src/pgoapi/pgoapi/rpc_api.py", line 332, in _parse_main_response
    raise ServerSideAccessForbiddenException("Seems your IP Address is banned or something else went badly wrong...")
pgoapi.exceptions.ServerSideAccessForbiddenException: Seems your IP Address is banned or something else went badly wrong...
```

**Comment by RedViper9** [comment]
Try using a proxy or vpn to get around the ip ban. Closing.
