### ISSUE TITLE
ImportError: No module named pgoapi.exceptions

### ISSUE THREAD

**Issue by havenofear** [PokemonGoF/PokemonGo-Bot#3237]
Reinstalled anything. still got this
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions

**Comment by urbels** [comment]
did you run pip install without errors?

**Comment by havenofear** [comment]
Exception:
Traceback (most recent call last):
  File "c:\program files (x86)\python\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\program files (x86)\python\lib\site-packages\pip\commands\install.py", line 317, in run
    prefix=options.prefix_path,
  File "c:\program files (x86)\python\lib\site-packages\pip\req\req_set.py", line 742, in install
    **kwargs
  File "c:\program files (x86)\python\lib\site-packages\pip\req\req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "c:\program files (x86)\python\lib\site-packages\pip\req\req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "c:\program files (x86)\python\lib\site-packages\pip\wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "c:\program files (x86)\python\lib\site-packages\pip\wheel.py", line 317, in clobber
    ensure_dir(destdir)
  File "c:\program files (x86)\python\lib\site-packages\pip\utils\__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "c:\program files (x86)\python\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 5] : 'c:\\program files (x86)\\python\\Lib\\site-packages\\numpy'

**Comment by nivong** [comment]
sesarch

**Comment by chypriote** [comment]
I had this error and fixed this by rerunning:
`virtualenv .
Scripts/activate.bat
pip install -r requirements.txt`

On Win10

**Comment by spencerby28** [comment]
In this particular case, pip install -r requirements.txt will install all listed package versions to the exact specified version. Most of them work just fine as pip should behave, as they are managed packages of the pypi. The exception here is the pgoapi package, listed on line 3. It is not a pypi package. It is a github repository. Pip handle it badly. In occasions you have to remove the whole repository cloned by pip (rm -rf pgoapi) and do pip install again, i.e. pip install -r requirements.txt

This is a great opportunity to learn python!

**Comment by havenofear** [comment]
i don't know what to do. i uninstalled everything. even Python and pip. Make everything one more time - same error.

**Comment by RedViper9** [comment]
If you did
```
virtualenv .
Scripts\activate
pip install -r requirements.txt
virtualenv .
Scripts\activate
pip install -r requirements.txt
```
then you will need to do
```
Scripts\activate
python pokecli.py
```
to get the bot to run properly.
