### ISSUE TITLE
Latest Dev not starting

### ISSUE THREAD

**Issue by Drambuie** [PokemonGoF/PokemonGo-Bot#3249]
Please check configuration at http://jsonlint.com/ before posting an issue.

### Expected Behavior

Bot to start normally

### Actual Behavior

2016-08-09 10:55:40,493 [       cli] [INFO] Threw 0 pokeballs
2016-08-09 10:55:40,493 [       cli] [INFO] Earned 0 Stardust
2016-08-09 10:55:40,493 [       cli] [INFO] 
2016-08-09 10:55:40,493 [       cli] [INFO] Highest CP Pokemon: 
2016-08-09 10:55:40,493 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "/home/user/PokemonGo-Bot/pokecli.py", line 521, in <module>
    main()
  File "/home/user/PokemonGo-Bot/pokecli.py", line 95, in main
    bot.tick()
  File "/home/user/PokemonGo-Bot/pokemongo_bot/__init__.py", line 449, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/user/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_lured_pokemon.py", line 16, in work
    if len(lured_pokemon) > 0:
TypeError: object of type 'bool' has no len()

### Steps to Reproduce

Starting the bot using latest dev

### Other Information
OS: UBUNTU
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by ariefbayu** [comment]
confirmed on git commit `d42082349736c83616d5c0d42acf43d8abb0b745` branch `dev`
