### ISSUE TITLE
[dev] AttributeError

### ISSUE THREAD

**Issue by DokterPhill** [PokemonGoF/PokemonGo-Bot#3269]
Please check configuration at http://jsonlint.com/ before posting an issue.

### Expected Behavior
Bot startup

### Actual Behavior
error after logging in: 

2016-08-09 14:02:58,997 [PokemonGoBot] [INFO]
2016-08-09 14:02:58,999 [PokemonGoBot] [INFO] Found encrypt.dll! Platform: win32 Encrypt.so directory: C:\Users\Roel\Downloads\PokemonGo-Bot-dev\PokemonGo-Dev\PokemonGo-Bot
2016-08-09 14:02:59,002 [PokemonGoBot] [INFO]
2016-08-09 14:03:06,236 [       cli] [INFO]
2016-08-09 14:03:06,237 [       cli] [INFO] Ran for 0:00:10
2016-08-09 14:03:06,239 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-09 14:03:06,240 [       cli] [INFO] Travelled 0.00km
2016-08-09 14:03:06,240 [       cli] [INFO] Visited 0 stops
2016-08-09 14:03:06,243 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-09 14:03:06,244 [       cli] [INFO] Threw 0 pokeballs
2016-08-09 14:03:06,246 [       cli] [INFO] Earned 0 Stardust
2016-08-09 14:03:06,246 [       cli] [INFO]
2016-08-09 14:03:06,247 [       cli] [INFO] Highest CP Pokemon:
2016-08-09 14:03:06,249 [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "C:\Users\Roel\Downloads\PokemonGo-Bot-dev\PokemonGo-Dev\PokemonGo-Bot\pokecli.py", line 521, in <module>
    main()
  File "C:\Users\Roel\Downloads\PokemonGo-Bot-dev\PokemonGo-Dev\PokemonGo-Bot\pokecli.py", line 82, in main
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "C:\Users\Roel\Downloads\PokemonGo-Bot-dev\PokemonGo-Dev\PokemonGo-Bot\pokemongo_bot\tree_config_builder.py", line 46, in build
    if BaseTask.TASK_API_VERSION < worker.SUPPORTED_TASK_API_VERSION:
AttributeError: type object 'HandleSoftBan' has no attribute 'SUPPORTED_TASK_API_VERSION'

### Other Information
OS: win10
Git Commit: 3c9806b3de71b5c2c38ba92f22ed662901ee700d
Python Version: Python 2.7.12

**Comment by sn3fru** [comment]
i have same problem
( osx, 64bits, py 2.7)

**Comment by k4n30** [comment]
@DokterPhill Please update to the latest version to fix your issue. Report back if you fix / solve the issue
