### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by deathcoderz** [PokemonGoF/PokemonGo-Bot#3295]
getting this error when trying to run the bot any ideas how to fix? (running dev version)

C:\Users\Myron\pokemon\PokemonGo-Bot>pokecli.py
Traceback (most recent call last):
  File "C:\Users\Myron\pokemon\PokemonGo-Bot\pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
  File "c:\users\myron\pokemon\pokemongo-bot\src\pgoapi\pgoapi\__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "c:\users\myron\pokemon\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "c:\users\myron\pokemon\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 47, in <module>
    from pgoapi.utilities import to_camel_case, get_time, get_format_time_diff, Rand48, long_to_bytes, generateLocation1, generateLocation2, generateRequestHash, f2i
  File "c:\users\myron\pokemon\pokemongo-bot\src\pgoapi\pgoapi\utilities.py", line 39, in <module>
    from s2sphere import LatLng, Angle, Cap, RegionCoverer, math
  File "C:\Python27\lib\site-packages\s2sphere\__init__.py", line 5, in <module>
    from .sphere import *
  File "C:\Python27\lib\site-packages\s2sphere\sphere.py", line 2, in <module>
    from future.builtins import int
ImportError: No module named future.builtins

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this issue has been resolved. If I'm wrong, please reopen.
