### ISSUE TITLE
ChunkedEncodingError - Connection broken

### ISSUE THREAD

**Issue by g2384** [PokemonGoF/PokemonGo-Bot#3301]
I have used my config setting for more than 24 hours.

### Actual Behavior

The last event is MoveToFort.

```
Python: Traceback (most recent call last):
  File "./pokecli.py", line 521, in <module>

Python:     main()

Python:   File "./pokecli.py", line 95, in main
    bot.tick()

Python:   File "D:\PokemonGo-Bot-Desktop\gofbot\pokemongo_bot\__init__.py", line 434, in tick
    self.cell = self.get_meta_cell()
  File "D:\PokemonGo-Bot-Desktop\gofbot\pokemongo_bot\__init__.py", line 446, in get_meta_cell

Python:     cells = self.find_close_cells(*location)
  File "D:\PokemonGo-Bot-Desktop\gofbot\pokemongo_bot\__init__.py", line 536, in find_close_cells
    response_dict = self.get_map_objects(lat, lng, timestamp, cellid)
  File "D:\PokemonGo-Bot-Desktop\gofbot\pokemongo_bot\__init__.py", line 1077, in get_map_objects

Python:     cell_id=cellid
  File "d:\pokemongo-bot-desktop\gofbot\src\pgoapi\pgoapi\pgoapi.py", line 122,
in function
    return request.call()
  File "D:\PokemonGo-Bot-Desktop\gofbot\pokemongo_bot\api_wrapper.py", line 106, in call
    result = self._call()
  File "D:\PokemonGo-Bot-Desktop\gofbot\pokemongo_bot\api_wrapper.py", line 63,
in _call
    return PGoApiRequest.call(self)
  File "d:\pokemongo-bot-desktop\gofbot\src\pgoapi\pgoapi\pgoapi.py", line 220,
in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "d:\pokemongo-bot-desktop\gofbot\src\pgoapi\pgoapi\rpc_api.py", line 127, in request

Python:     response = self._make_rpc(endpoint, request_proto)
  File "d:\pokemongo-bot-desktop\gofbot\src\pgoapi\pgoapi\rpc_api.py", line 115, in _make_rpc
    http_response = self._session.post(endpoint, data=request_proto_serialized)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 617, in send
    r.content
  File "C:\Python27\lib\site-packages\requests\models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "C:\Python27\lib\site-packages\requests\models.py", line 667, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: error(10054, '')", error(10054, ''))

Python: 2016-08-09 14:36:19,584 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\raven\transport\threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "C:\Python27\lib\site-packages\raven\transport\http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line
494, in open
    response = self._open(req, data)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line
512, in _open
    '_open', req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line
466, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line
1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python27\Lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\Lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "C:\Python27\Lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "C:\Python27\Lib\httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal
not in range(128)
2016-08-09 14:36:19,592 [sentry.errors.uncaught] [ERROR] [u'ChunkedEncodingError: ("Connection broken: error(10054, \'\')", error(10054, \'\'))', u'  File "pokecli.py", line 521, in <module>', u'  File "pokecli.py", line 95, in main', u'  File "D:\\PokemonGo-Bot-Desktop\\gofbot\\pokemongo_bot\\__init__.py", line 434, in tick', u'  File "D:\\PokemonGo-Bot-Desktop\\gofbot\\pokemongo_bot\\__init__.py", line 446, in get_meta_cell', u'  File "D:\\PokemonGo-Bot-Desktop\\gofbot\\pokemongo_bot\\__init__.py", line 536, in find_close_cells', u'  File "D:\\PokemonGo-Bot-Desktop\\gofbot\\pokemongo_bot\\__init__.py", line 1077, in get_map_objects', u'  File "d:\\pokemongo-bot-desktop\\gofbot\\src\\pgoapi\\pgoapi\\pgoapi.py", line 122, in function', u'  File "D:\\PokemonGo-Bot-Desktop\\gofbot\\pokemongo_bot\\api_wrapper.py", line 106, in call', u'  File "D:\\PokemonGo-Bot-Desktop\\gofbot\\pokemongo_bot\\api_wrapper.py", line 63, in _call', u'  File "d:\\pokemongo-bot-desktop\\gofbot\\src\\pgoapi\\pgoapi\\pgoapi.py", line 220, in call', u'  File "d:\\pokemongo-bot-desktop\\gofbot\\src\\pgoapi\\pgoapi\\rpc_api.py", line 127, in request', u'  File "d:\\pokemongo-bot-desktop\\gofbot\\src\\pgoapi\\pgoapi\\rpc_api.py", line 115, in _make_rpc', u'  File "C:\\Python27\\lib\\site-packages\\requests\\sessions.py", line 518, in post', u'  File "C:\\Python27\\lib\\site-packages\\requests\\sessions.py", line 475, in request', u'  File "C:\\Python27\\lib\\site-packages\\requests\\sessions.py", line 617, in send', u'  File
"C:\\Python27\\lib\\site-packages\\requests\\models.py", line 741, in content',
u'  File "C:\\Python27\\lib\\site-packages\\requests\\models.py", line 667, in generate']

```

### Other Information
OS: Win10 64-bit
Git Commit: 47ab81f5e1e34a36a33cf9c46949b5e51ab6e412
Python Version: 2.7.12

**Comment by bibibkamal** [comment]
yea i have the same error

**Comment by middleagedman** [comment]
From Linux perspective, error seems a little different:
Traceback (most recent call last):
  File "pokecli.py", line 521, in <module>
    main()
  File "pokecli.py", line 95, in main
    bot.tick()
  File "/home/tom/build/PokemonGo-Bot/pokemongo_bot/__init__.py", line 453, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/tom/build/PokemonGo-Bot/pokemongo_bot/cell_workers/transfer_pokemon.py", line 11, in work
    pokemon_groups = self._release_pokemon_get_groups()
  File "/home/tom/build/PokemonGo-Bot/pokemongo_bot/cell_workers/transfer_pokemon.py", line 79, in _release_pokemon_get_groups
    inventory_req = request.call()
  File "/home/tom/build/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 106, in call
    result = self._call()
  File "/home/tom/build/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "/home/tom/build/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/home/tom/build/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 127, in request
    response = self._make_rpc(endpoint, request_proto)
  File "/home/tom/build/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 115, in _make_rpc
    http_response = self._session.post(endpoint, data=request_proto_serialized)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 617, in send
    r.content
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 667, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

**Comment by phphong** [comment]
Same here:

Ubuntu 14.04
Commit 5b3fe3d 
Python 2.7.12 (Anaconda python, with conda virtual ennvironment)

Last event is `MoveToPort`

```
Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 133, in main
    raise e
requests.exceptions.ChunkedEncodingError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))
2016-08-11 19:00:37,097 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/xxx/anaconda2/envs/pokebot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/xxx/anaconda2/envs/pokebot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/xxx/anaconda2/envs/pokebot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/xxx/anaconda2/envs/pokebot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/xxx/anaconda2/envs/pokebot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/xxx/anaconda2/envs/pokebot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/xxx/anaconda2/envs/pokebot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/xxx/anaconda2/envs/pokebot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/home/xxx/anaconda2/envs/pokebot/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/home/xxx/anaconda2/envs/pokebot/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/home/xxx/anaconda2/envs/pokebot/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/home/xxx/anaconda2/envs/pokebot/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-11 19:00:37,098 [sentry.errors.uncaught] [ERROR] [u'ChunkedEncodingError: ("Connection broken: error(104, \'Connection reset by peer\')", error(104, \'Connection reset by peer\'))', u'  File "pokecli.py", line 502, in <module>', u'  File "pokecli.py", line 133, in main']
```

**Comment by LeeRongWen** [comment]
same with me 
`2016-08-11 20:49:52,736 [       cli] [INFO] Ran for 0:32:17
2016-08-11 20:49:52,736 [       cli] [INFO] Total XP Earned: 9555  Average: 17761.50/h
2016-08-11 20:49:52,736 [       cli] [INFO] Travelled 1.95km
2016-08-11 20:49:52,736 [       cli] [INFO] Visited 67 stops
2016-08-11 20:49:52,736 [       cli] [INFO] Encountered 29 pokemon, 28 caught, 26 released, 0 evolved, 0 never seen before
2016-08-11 20:49:52,736 [       cli] [INFO] Threw 36 pokeballs
2016-08-11 20:49:52,736 [       cli] [INFO] Earned 2800 Stardust
2016-08-11 20:49:52,736 [       cli] [INFO]
2016-08-11 20:49:52,736 [       cli] [INFO] Highest CP Pokemon: Jigglypuff [CP: 517] [IV: 8/9/15] Potential: 0.71
2016-08-11 20:49:52,736 [       cli] [INFO] Most Perfect Pokemon: Bellsprout [CP: 79] [IV: 14/14/6] Potential: 0.76
Traceback (most recent call last):
  File "pokecli.py", line 530, in <module>
    main()
  File "pokecli.py", line 96, in main
    bot.tick()
  File "C:\PokemonGoBotJCT\pokemongo_bot\__init__.py", line 465, in tick
    self.cell = self.get_meta_cell()
  File "C:\PokemonGoBotJCT\pokemongo_bot\__init__.py", line 477, in get_meta_cell
    cells = self.find_close_cells(*location)
  File "C:\PokemonGoBotJCT\pokemongo_bot\__init__.py", line 551, in find_close_cells
    response_dict = self.get_map_objects(lat, lng, timestamp, cellid)
  File "C:\PokemonGoBotJCT\pokemongo_bot\__init__.py", line 1095, in get_map_objects
    cell_id=cellid
  File "c:\pokemongobotjct\src\pgoapi\pgoapi\pgoapi.py", line 122, in function
    return request.call()
  File "C:\PokemonGoBotJCT\pokemongo_bot\api_wrapper.py", line 106, in call
    result = self._call()
  File "C:\PokemonGoBotJCT\pokemongo_bot\api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "c:\pokemongobotjct\src\pgoapi\pgoapi\pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "c:\pokemongobotjct\src\pgoapi\pgoapi\rpc_api.py", line 127, in request
    response = self._make_rpc(endpoint, request_proto)
  File "c:\pokemongobotjct\src\pgoapi\pgoapi\rpc_api.py", line 115, in _make_rpc
    http_response = self._session.post(endpoint, data=request_proto_serialized, timeout=30)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 617, in send
    r.content
  File "C:\Python27\lib\site-packages\requests\models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "C:\Python27\lib\site-packages\requests\models.py", line 667, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: error(10054, 'An existing connection was forcibly closed by the remote host')", error(10054, 'An existing connection was forcibly closed by the remote host'))
`

**Comment by LaKrue** [comment]
same here

OS: Ubuntu 14.04
Branch: dev
Git Commit: c450b19a3e44cc660576940009da6e7c85a0121f
Python Version: Python 2.7.6

> 2016-08-13 02:13:09,149 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Naked Sisters  - 0.09km
> 2016-08-13 02:13:49,441 [       cli] [INFO] 
> 2016-08-13 02:13:49,442 [       cli] [INFO] Ran for 0:06:23
> 2016-08-13 02:13:49,442 [       cli] [INFO] Total XP Earned: 425  Average: 3990.91/h
> 2016-08-13 02:13:49,442 [       cli] [INFO] Travelled 0.20km
> 2016-08-13 02:13:49,442 [       cli] [INFO] Visited 8 stops
> 2016-08-13 02:13:49,442 [       cli] [INFO] Encountered 1 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
> 2016-08-13 02:13:49,442 [       cli] [INFO] Threw 1 pokeball
> 2016-08-13 02:13:49,442 [       cli] [INFO] Earned 0 Stardust
> 2016-08-13 02:13:49,442 [       cli] [INFO] 
> 2016-08-13 02:13:49,443 [       cli] [INFO] Highest CP Pokemon: 
> 2016-08-13 02:13:49,443 [       cli] [INFO] Most Perfect Pokemon: 
> Traceback (most recent call last):
>   File "./pokebot.py", line 6, in <module>
>     pokecli.main()
>   File "/opt/pokebot/pokecli.py", line 105, in main
>     bot.tick()
>   File "/opt/pokebot/pokemongo_bot/__init__.py", line 475, in tick
>     self.cell = self.get_meta_cell()
>   File "/opt/pokebot/pokemongo_bot/__init__.py", line 487, in get_meta_cell
>     cells = self.find_close_cells(*location)
>   File "/opt/pokebot/pokemongo_bot/__init__.py", line 561, in find_close_cells
>     response_dict = self.get_map_objects(lat, lng, timestamp, cellid)
>   File "/opt/pokebot/pokemongo_bot/__init__.py", line 1105, in get_map_objects
>     cell_id=cellid
>   File "/opt/pokebot/src/pgoapi/pgoapi/pgoapi.py", line 122, in function
>     return request.call()
>   File "/opt/pokebot/pokemongo_bot/api_wrapper.py", line 106, in call
>     result = self._call()
>   File "/opt/pokebot/pokemongo_bot/api_wrapper.py", line 63, in _call
>     return PGoApiRequest.call(self)
>   File "/opt/pokebot/src/pgoapi/pgoapi/pgoapi.py", line 220, in call
>     response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
>   File "/opt/pokebot/src/pgoapi/pgoapi/rpc_api.py", line 127, in request
>     response = self._make_rpc(endpoint, request_proto)
>   File "/opt/pokebot/src/pgoapi/pgoapi/rpc_api.py", line 115, in _make_rpc
>     http_response = self._session.post(endpoint, data=request_proto_serialized, timeout=30)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 518, in post
>     return self.request('POST', url, data=data, json=json, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 617, in send
>     r.content
>   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 741, in content
>     self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
>   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 667, in generate
>     raise ChunkedEncodingError(e)
> requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

**Comment by sffetlio** [comment]
I got this too:

```
Traceback (most recent call last):
  File "pokecli.py", line 586, in <module>
    main()
  File "pokecli.py", line 104, in main
    bot.tick()
  File "/mnt/d/linux/PokemonGo-Bot/pokemongo_bot/__init__.py", line 475, in tick
    self.cell = self.get_meta_cell()
  File "/mnt/d/linux/PokemonGo-Bot/pokemongo_bot/__init__.py", line 487, in get_meta_cell
    cells = self.find_close_cells(*location)
  File "/mnt/d/linux/PokemonGo-Bot/pokemongo_bot/__init__.py", line 561, in find_close_cells
    response_dict = self.get_map_objects(lat, lng, timestamp, cellid)
  File "/mnt/d/linux/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1105, in get_map_objects
    cell_id=cellid
  File "/mnt/d/linux/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 122, in function
    return request.call()
  File "/mnt/d/linux/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 117, in call
    result = self._call()
  File "/mnt/d/linux/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 66, in _call
    return PGoApiRequest.call(self)
  File "/mnt/d/linux/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/mnt/d/linux/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 127, in request
    response = self._make_rpc(endpoint, request_proto)
  File "/mnt/d/linux/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 115, in _make_rpc
    http_response = self._session.post(endpoint, data=request_proto_serialized, timeout=30)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 617, in send
    r.content
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 667, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(1231 bytes read, 2852 more expected)', IncompleteRead(1231 bytes read, 2852 more expected))
```
on fd9d7e308715e1ca2e57491bf847eeeb7e8f6f78

**Comment by AutopsyMania** [comment]
OS Ubuntu 14.04
Branch dev
commit dab0f2ac00e51baa24f51f9b059e68946e5bdfa5
python 2.7.6

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/eeijjmo/android/PokemonGo/PokemonGo-Bot-CharlesChang/pokemongo_bot/__init__.py", line 1023, in update_web_location_worker
    self.update_web_location()
  File "/home/eeijjmo/android/PokemonGo/PokemonGo-Bot-CharlesChang/pokemongo_bot/__init__.py", line 529, in update_web_location
    cells = self.find_close_cells(*location)
  File "/home/eeijjmo/android/PokemonGo/PokemonGo-Bot-CharlesChang/pokemongo_bot/__init__.py", line 562, in find_close_cells
    response_dict = self.get_map_objects(lat, lng, timestamp, cellid)
  File "/home/eeijjmo/android/PokemonGo/PokemonGo-Bot-CharlesChang/pokemongo_bot/__init__.py", line 1106, in get_map_objects
    cell_id=cellid
  File "/home/eeijjmo/android/PokemonGo/PokemonGo-Bot-CharlesChang/src/pgoapi/pgoapi/pgoapi.py", line 122, in function
    return request.call()
  File "/home/eeijjmo/android/PokemonGo/PokemonGo-Bot-CharlesChang/pokemongo_bot/api_wrapper.py", line 117, in call
    result = self._call()
  File "/home/eeijjmo/android/PokemonGo/PokemonGo-Bot-CharlesChang/pokemongo_bot/api_wrapper.py", line 66, in _call
    return PGoApiRequest.call(self)
  File "/home/eeijjmo/android/PokemonGo/PokemonGo-Bot-CharlesChang/src/pgoapi/pgoapi/pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/home/eeijjmo/android/PokemonGo/PokemonGo-Bot-CharlesChang/src/pgoapi/pgoapi/rpc_api.py", line 127, in request
    response = self._make_rpc(endpoint, request_proto)
  File "/home/eeijjmo/android/PokemonGo/PokemonGo-Bot-CharlesChang/src/pgoapi/pgoapi/rpc_api.py", line 115, in _make_rpc
    http_response = self._session.post(endpoint, data=request_proto_serialized, timeout=30)
  File "/home/eeijjmo/android/PokemonGo/PokemonGo-Bot-CharlesChang/local/lib/python2.7/site-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/eeijjmo/android/PokemonGo/PokemonGo-Bot-CharlesChang/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/eeijjmo/android/PokemonGo/PokemonGo-Bot-CharlesChang/local/lib/python2.7/site-packages/requests/sessions.py", line 617, in send
    r.content
  File "/home/eeijjmo/android/PokemonGo/PokemonGo-Bot-CharlesChang/local/lib/python2.7/site-packages/requests/models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/home/eeijjmo/android/PokemonGo/PokemonGo-Bot-CharlesChang/local/lib/python2.7/site-packages/requests/models.py", line 667, in generate
    raise ChunkedEncodingError(e)
ChunkedEncodingError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))

**Comment by mjmadsen** [comment]
Since we haven't seen any more of these in a while, I'm going to close.
