### ISSUE TITLE
unicodedecodeError 

### ISSUE THREAD

**Issue by buzzo123** [PokemonGoF/PokemonGo-Bot#3304]
i've this error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/buzzo/Desktop/pogo/PokemonGo-Bot-master/pokemongo_bot/__init__.py", line 994, in update_web_location_worker
    self.update_web_location()
  File "/home/buzzo/Desktop/pogo/PokemonGo-Bot-master/pokemongo_bot/__init__.py", line 501, in update_web_location
    fort['gym_details'] = response_gym_details.get(
AttributeError: 'NotLoggedInException' object has no attribute 'get'

2016-08-09 17:18:03,486 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-09 17:18:03,490 [PokemonGoBot] [INFO] Found encrypt.so! Platform: linux2 Encrypt.so directory: /home/buzzo/Desktop/pogo/PokemonGo-Bot-master
2016-08-09 17:18:06,069 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Massafiscaglia. Oratorio - 0.11km
2016-08-09 17:18:11,223 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Massafiscaglia. Oratorio - 0.11km
2016-08-09 17:18:15,344 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Massafiscaglia. Oratorio - 0.10km
2016-08-09 17:18:25,883 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Massafiscaglia. Oratorio - 0.09km
2016-08-09 17:18:29,868 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Massafiscaglia. Oratorio - 0.09km
2016-08-09 17:18:34,861 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Massafiscaglia. Oratorio - 0.08km
2016-08-09 17:18:39,110 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Massafiscaglia. Oratorio - 0.07km
2016-08-09 17:18:44,239 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Massafiscaglia. Oratorio - 0.06km
2016-08-09 17:18:54,012 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Massafiscaglia. Oratorio - 0.05km
2016-08-09 17:18:58,023 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Massafiscaglia. Oratorio - 0.05km
2016-08-09 17:19:21,029 [  SpinFort] [INFO] [spun_pokestop] Spun pokestop Massafiscaglia. Oratorio. Experience awarded: 50. Items awarded: {u'Potion': 1, u'Pokeball': 2}
2016-08-09 17:19:28,821 [FollowSpiral] [INFO] [position_update] Walking from (44.812510695139636, 12.020740420733611, 0) to (44.81334923425776, 12.006404982433933, 0) (1134.65969202 m)
2016-08-09 17:20:04,414 [       cli] [INFO] 
2016-08-09 17:20:04,428 [       cli] [INFO] Ran for 0:31:09
2016-08-09 17:20:04,429 [       cli] [INFO] Total XP Earned: 700  Average: 1348.00/h
2016-08-09 17:20:04,429 [       cli] [INFO] Travelled 2.72km
2016-08-09 17:20:04,430 [       cli] [INFO] Visited 4 stops
2016-08-09 17:20:04,430 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-09 17:20:04,430 [       cli] [INFO] Threw 0 pokeballs
2016-08-09 17:20:04,430 [       cli] [INFO] Earned 1155 Stardust
2016-08-09 17:20:04,431 [       cli] [INFO] 
2016-08-09 17:20:04,431 [       cli] [INFO] Highest CP Pokemon: 
2016-08-09 17:20:04,431 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli2.py", line 521, in <module>
    main()
  File "pokecli2.py", line 95, in main
    bot.tick()
  File "/home/buzzo/Desktop/pogo/PokemonGo-Bot-master/pokemongo_bot/__init__.py", line 433, in tick
    self.health_record.heartbeat()
  File "/home/buzzo/Desktop/pogo/PokemonGo-Bot-master/pokemongo_bot/health_record/bot_event.py", line 65, in heartbeat
    self.track_url('/heartbeat')
  File "/home/buzzo/Desktop/pogo/PokemonGo-Bot-master/pokemongo_bot/health_record/bot_event.py", line 78, in track_url
    'http://www.google-analytics.com/collect', data=data)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.google-analytics.com', port=80): Max retries exceeded with url: /collect (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fc4ab09a790>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2016-08-09 17:20:04,567 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-09 17:20:04,610 [sentry.errors.uncaught] [ERROR] [u"ConnectionError: HTTPConnectionPool(host='www.google-analytics.com', port=80): Max retries exceeded with url: /collect (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fc4ab09a790>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))", u'  File "pokecli2.py", line 521, in <module>', u'  File "pokecli2.py", line 95, in main', u'  File "pokemongo_bot/__init__.py", line 433, in tick', u'  File "pokemongo_bot/health_record/bot_event.py", line 65, in heartbeat', u'  File "pokemongo_bot/health_record/bot_event.py", line 78, in track_url', u'  File "requests/api.py", line 111, in post', u'  File "requests/api.py", line 57, in request', u'  File "requests/sessions.py", line 475, in request', u'  File "requests/sessions.py", line 585, in send', u'  File "requests/adapters.py", line 467, in send']
```

and yes, i do the last commit

**Comment by Sijmenjeromkok** [comment]
I get the same error about after an hour of play

**Comment by k4n30** [comment]
@buzzo123 & @Sijmenjeromkok Are you both still experiencing this issue?
