### ISSUE TITLE
Error when i change location

### ISSUE THREAD

**Issue by meriler** [PokemonGoF/PokemonGo-Bot#3330]
### Expected Behavior

Bot works fine after changing location, avoid softban, collect pokemons etc

### Actual Behavior

when i change location to a point in Milan, Italy — i got error. Point is right, pokemongomap work with this location normally, but when i try it with bot…

2016-08-10 04:35:36,307 [PokemonGoBot] [INFO] [bot_start] Starting bot...
2016-08-10 04:35:37,316 [CatchVisiblePokemon] [INFO] catchable_pokemon: {'pokemon_id': 15, 'expiration_timestamp_ms': 1470764799972L, 'longitude': 9.173905315286083, 'latitude': 45.472957175293416, 'spawn_point_id': u'4786c145e59', 'encounter_id': 3996214042154277117L}
2016-08-10 04:35:37,840 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Beedrill appeared! [CP 166] [Potential 0.31] [A/D/S 1/5/8]
2016-08-10 04:35:41,479 [PokemonCatchWorker] [WARNING] [softban] Failed to use berry. You may be softbanned.
2016-08-10 04:35:42,415 [       cli] [INFO] 
2016-08-10 04:35:42,415 [       cli] [INFO] Ran for 0:00:25
2016-08-10 04:35:42,416 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-10 04:35:42,416 [       cli] [INFO] Travelled 0.00km
2016-08-10 04:35:42,416 [       cli] [INFO] Visited 0 stops
2016-08-10 04:35:42,416 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-10 04:35:42,416 [       cli] [INFO] Threw 0 pokeballs
2016-08-10 04:35:42,417 [       cli] [INFO] Earned 0 Stardust
2016-08-10 04:35:42,417 [       cli] [INFO] 
2016-08-10 04:35:42,417 [       cli] [INFO] Highest CP Pokemon: 
2016-08-10 04:35:42,417 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 521, in <module>
    main()
  File "pokecli.py", line 95, in main
    bot.tick()
  File "/Users/user/bots/bot1/PokemonGo-Bot/pokemongo_bot/__init__.py", line 450, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/Users/user/bots/bot1/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 37, in work
    self.catch_pokemon(pokemon)
  File "/Users/user/bots/bot1/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 63, in catch_pokemon
    return_value = worker.work()
  File "/Users/user/bots/bot1/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 114, in work
    self._do_catch(pokemon, encounter_id, catch_rate_by_ball, is_vip=is_vip)
  File "/Users/user/bots/bot1/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 332, in _do_catch
    'success_percentage': self._pct(catch_rate_by_ball[current_ball]),
IndexError: list index out of range
2016-08-10 04:35:42,489 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-10 04:35:42,624 [sentry.errors.uncaught] [ERROR] [u'IndexError: list index out of range', u'  File "pokecli.py", line 521, in <module>', u'  File "pokecli.py", line 95, in main', u'  File "pokemongo_bot/__init__.py", line 450, in tick', u'  File "pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 37, in work', u'  File "pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 63, in catch_pokemon', u'  File "pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 114, in work', u'  File "pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 332, in _do_catch']
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit

### Steps to Reproduce

change config.json (45.47210, 9.17722)
run bot
wait about 10 sec
got error
???
profit, go back to 40.764900, -73.972676 location

### Other Information

updating pgoapi like in #3193 issue doesn't help. But maybe i made something wrong?
OS: os x 10.11.5 
Git Commit: db1bf4861504c1ae4d64198dfa0dbf6535bda763
Python Version: Python 2.7.12

**Comment by k4n30** [comment]
@meriler do you still have this issue on the latest version?
