### ISSUE TITLE
Suddenly the bot stops working, is there any solution?

### ISSUE THREAD

**Issue by merkon** [PokemonGoF/PokemonGo-Bot#3353]
Whenever i run the bot in terminal, some minutes later it suddenly stops and it writes these:

Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 129, in main
    raise e
requests.exceptions.ChunkedEncodingError: ("Connection broken: error(54, 'Connection reset by peer')", error(54, 'Connection reset by peer'))
2016-08-10 00:06:33,502 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 891, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-10 00:06:33,507 [sentry.errors.uncaught] [ERROR] [u'ChunkedEncodingError: ("Connection broken: error(54, \'Connection reset by peer\')", error(54, \'Connection reset by peer\'))', u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", line 129, in main']

Is there any solution? And basically, what's the problem?

**Comment by chr1spy** [comment]
Lines 6-7 explain it...

**Comment by merkon** [comment]
What's the solution then? I really have no idea about that, can you help me please?

**Comment by merkon** [comment]
Also, what's the problem with that too?

2016-08-10 00:20:16,976 [MoveToFort] [INFO] [inventory_full] Not moving to any forts as there aren't enough space. You might want to change your config to recycle more items if this message appears consistently.

**Comment by rohimkudus** [comment]
seem your internet, try use vpn

**Comment by GitPupper** [comment]
[PokeBot.zip](https://github.com/PokemonGoF/PokemonGo-Bot/files/410058/PokeBot.zip)
Unzip that and run it. Every time your bot crashes because of your internet, it will automatically restart the bot after 5 seconds.

**Comment by vamirineni87** [comment]
error happens in botevent file. Is that related to the Analytics?

https://github.com/PokemonGoF/PokemonGo-Bot/search?utf8=%E2%9C%93&q=https%3A%2F%2Fapp.getsentry.com&type=Code

Can we just disable the Analytics?
https://github.com/PokemonGoF/PokemonGo-Bot#analytics

health_record = false?

**Comment by JoshuaGarrison27** [comment]
@GitPupper Have a solution for windows like that?

**Comment by vamirineni87** [comment]
as a workaround, i just autorestart the bot on failure.

```
@echo off
TITLE pokemongobot-controller
:loop
call scripts/activate.bat
call python pokecli.py
if %ERRORLEVEL% NEQ 0(
	echo There is an error (Error code : %ERRORLEVEL%).
	echo Will restart after a small delay
)
SET /A seconds=%RANDOM% * 600 / 32768 + 300
timeout /t %seconds%
goto loop
pause
```
