### ISSUE TITLE
[Error] File "pokecli.py", line 521; File "pokecli.py", line 81

### ISSUE THREAD

**Issue by Adrenocortico** [PokemonGoF/PokemonGo-Bot#3360]
### Expected Behavior
Bot doesn't crash and stop.

### Actual Behavior
```zsh
2016-08-10 01:12:40,005 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-10 01:12:40,007 [       cli] [INFO] No config argument specified, checking for /configs/config.json
2016-08-10 01:12:40,010 [       cli] [INFO] Configuration initialized
2016-08-10 01:12:40,097 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-10 01:12:40,098 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-10 01:12:40,098 [PokemonGoBot] [INFO] [location_found] Location found: 45.3238557,8.8495937 (45.3238557, 8.8495937, 0.0)
2016-08-10 01:12:40,098 [PokemonGoBot] [INFO] [position_update] Now at (45, 8, 0)
2016-08-10 01:12:40,098 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-10 01:12:42,498 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-10 01:12:43,066 [PokemonGoBot] [INFO]
2016-08-10 01:12:43,066 [PokemonGoBot] [INFO] --- AAA ---
2016-08-10 01:12:43,066 [PokemonGoBot] [INFO] Level: 20 (Next Level: 28151 XP) (Total: 231849 XP)
2016-08-10 01:12:43,066 [PokemonGoBot] [INFO] Pokemon Captured: 664 | Pokestops Visited: 515
2016-08-10 01:12:43,067 [PokemonGoBot] [INFO] Pokemon Bag: 145/250
2016-08-10 01:12:43,067 [PokemonGoBot] [INFO] Items: 207/350
2016-08-10 01:12:43,068 [PokemonGoBot] [INFO] Stardust: 82432 | Pokecoins: 0
2016-08-10 01:12:43,068 [PokemonGoBot] [INFO] PokeBalls: 18 | GreatBalls: 4 | UltraBalls: 0
2016-08-10 01:12:43,068 [PokemonGoBot] [INFO] RazzBerries: 8 | BlukBerries: 0 | NanabBerries: 0
2016-08-10 01:12:43,068 [PokemonGoBot] [INFO] LuckyEgg: 5 | Incubator: 3 | TroyDisk: 5
2016-08-10 01:12:43,068 [PokemonGoBot] [INFO] Potion: 5 | SuperPotion: 21 | HyperPotion: 63 | MaxPotion: 0
2016-08-10 01:12:43,068 [PokemonGoBot] [INFO] Incense: 8 | IncenseSpicy: 0 | IncenseCool: 0
2016-08-10 01:12:43,068 [PokemonGoBot] [INFO] Revive: 65 | MaxRevive: 0
2016-08-10 01:12:43,068 [PokemonGoBot] [INFO]
2016-08-10 01:12:43,399 [       cli] [INFO]
2016-08-10 01:12:43,399 [       cli] [INFO] Ran for 0:00:03
2016-08-10 01:12:43,399 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-10 01:12:43,399 [       cli] [INFO] Travelled 0.00km
2016-08-10 01:12:43,399 [       cli] [INFO] Visited 0 stops
2016-08-10 01:12:43,399 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-10 01:12:43,399 [       cli] [INFO] Threw 0 pokeballs
2016-08-10 01:12:43,399 [       cli] [INFO] Earned 0 Stardust
2016-08-10 01:12:43,399 [       cli] [INFO]
2016-08-10 01:12:43,400 [       cli] [INFO] Highest CP Pokemon:
2016-08-10 01:12:43,400 [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 521, in <module>
    main()
  File "pokecli.py", line 81, in main
    bot.start()
```
### Your config.json (remove your credentials and any other private info)
```json
{
    "auth_service": "google",
    "username": "aaa@gmail.com",
    "password": "aaa",
    "location": "45,8",
    "gmapkey": "aaa",
    "libencrypt_location": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "item_filter": {
            "Pokeball":       { "keep" : 120 },
            "Potion":         { "keep" : 80 },
            "Super Potion":   { "keep" : 80 },
            "Hyper Potion":   { "keep" : 80 },
            "Revive":         { "keep" : 60 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 14,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": false,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    }
}
```

### Steps to Reproduce
Just run `python2 pokecli.py` after upgrade the git repo with `git pull` and `pip2 install --upgrade -r requirements.txt`.

### Other Information
OS: macOS Sierra 10.12 (16A270f)
Git Commit: 63f777bac0c8cdc75d07f9ef491ca8b900c0148a
Python Version: Python 2.7.12

**Comment by leadboots5** [comment]
Is there anymore to the error besides those 2 lines?

**Comment by Adrenocortico** [comment]
No :(

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this issue has been resolved. Try to get the latest version by doing
```
git fetch --all
git reset --hard origin master
```
If I'm wrong, please reopen.
