### ISSUE TITLE
Bot not able to Fix Softban

### ISSUE THREAD

**Issue by db-coder** [PokemonGoF/PokemonGo-Bot#3361]
### Expected Behavior
Bot should Fix the softbans

### Actual Behavior
16-08-10 04:49:37,626 [FollowCluster] [INFO] [found_cluster] Move to destiny 5.  pokestops will be in range of 50. Walking 693.409889318m.
2016-08-10 04:49:39,914 [RecycleItems] [INFO] [item_discard_skipped] Skipping Recycling of Items. 33 space left in bag.
2016-08-10 04:49:40,837 [  SpinFort] [INFO] [pokestop_empty] Found nothing in pokestop Darling Quarter Water Works.
2016-08-10 04:49:40,838 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-10 04:49:40,838 [  SpinFort] [INFO] [softban] Probably got softban.
2016-08-10 04:49:41,116 [FollowCluster] [INFO] [found_cluster] Move to destiny 5.  pokestops will be in range of 50. Walking 638.536676892m.
2016-08-10 04:49:43,510 [       cli] [INFO] 
2016-08-10 04:49:43,510 [       cli] [INFO] Ran for 0:00:13
2016-08-10 04:49:43,510 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-10 04:49:43,511 [       cli] [INFO] Travelled 0.00km
2016-08-10 04:49:43,511 [       cli] [INFO] Visited 0 stops
2016-08-10 04:49:43,511 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-10 04:49:43,511 [       cli] [INFO] Threw 0 pokeballs
2016-08-10 04:49:43,511 [       cli] [INFO] Earned 0 Stardust
2016-08-10 04:49:43,511 [       cli] [INFO] 
2016-08-10 04:49:43,511 [       cli] [INFO] Highest CP Pokemon: 
2016-08-10 04:49:43,511 [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 522, in <module>
    main()
  File "pokecli.py", line 96, in main
    bot.tick()
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/pokemongo_bot/__init__.py", line 454, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/pokemongo_bot/cell_workers/handle_soft_ban.py", line 32, in work
    MoveToFort(self.bot, config=None).work()
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/pokemongo_bot/base_task.py", line 12, in __init__
    self.initialize()
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort.py", line 16, in initialize
    self.lure_attraction = self.config.get("lure_attraction", True)
AttributeError: 'NoneType' object has no attribute 'get'

### Your config.json (remove your credentials and any other private info)
```
your config here
```
{
    "auth_service": "google",
    "username": "",
    "password": "",
    "location": "-33.8753071114,151.2014563751",
    "gmapkey": "",
    "libencrypt_location": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 20,
          "item_filter": {
            "Pokeball":       { "keep" : 120 },
            "Greatball":      { "keep" : 55 },
            "Ultraball":      { "keep" : 55 },
            "Potion":         { "keep" : 5 },
            "Super Potion":   { "keep" : 5 },
            "Max Potion":     { "keep" : 5 },
            "Hyper Potion":   { "keep" : 5 },
            "Revive":         { "keep" : 5 },
            "Razz Berry":     { "keep" : 60 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "FollowCluster",
        "config": {
            "radius": 50,
            "lured": false
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 55,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": false,
    "location_cache": false,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true },
      "// Pokemons with example": { "always_catch": true },
      "// Gets filtered with release parameters": {},

      "// Legendary pokemons (Goes under S-Tier)": {},
      "Lapras": { "always_catch": true },
      "Moltres": { "always_catch": true },
      "Zapdos": { "always_catch": true },
      "Articuno": { "always_catch": true },

      "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
      "Mewtwo": { "always_catch": true },
      "Dragonite": { "always_catch": true },
      "Snorlax": { "always_catch": true },
      "// Mew evolves to Mewtwo": {},
      "Mew": { "always_catch": true },
      "Arcanine": { "always_catch": true },
      "Vaporeon": { "always_catch": true },
      "Gyarados": { "always_catch": true },
      "Exeggutor": { "always_catch": true },
      "Muk": { "always_catch": true },
      "Weezing": { "always_catch": true },
      "Flareon": { "always_catch": true },

      "// Growlithe evolves to Arcanine": {},
      "Growlithe": { "always_catch": true },
      "// Dragonair evolves to Dragonite": {},
      "Dragonair": { "always_catch": true },
      "// Grimer evolves to Muk": {},
      "Grimer": { "always_catch": true },

      "// Magikarp evolves to Gyarados": {},
      "Magikarp": { "always_catch": true },
      "// Exeggcute evolves to Exeggutor": {},
      "Exeggcute": { "always_catch": true },
      "// Eevee evolves to many versions, like Vaporeon, Flareon": {},
      "Eevee": { "always_catch": true },

      "// A-Tier pokemons": {},
      "Slowbro": { "always_catch": true },
      "Victreebel": { "always_catch": true },
      "Machamp": { "always_catch": true },
      "Poliwrath": { "always_catch": true },
      "Clefable": { "always_catch": true },
      "Nidoking": { "always_catch": true },
      "Venusaur": { "always_catch": true },
      "Charizard": { "always_catch": true },
      "Golduck": { "always_catch": true },
      "Nidoqueen": { "always_catch": true },
      "Vileplume": { "always_catch": true },
      "Blastoise": { "always_catch": true },
      "Omastar":  { "always_catch": true },
      "Aerodactyl": { "always_catch": true },
      "Golem": { "always_catch": true },
      "Wigglytuff": { "always_catch": true },
      "Dewgong": { "always_catch": true },
      "Ninetales": { "always_catch": true },
      "Magmar": { "always_catch": true },
      "Kabutops": { "always_catch": true },
      "Electabuzz": { "always_catch": true },
      "Starmie": { "always_catch": true },
      "Jolteon": { "always_catch": true },
      "Rapidash": { "always_catch": true },
      "Pinsir": { "always_catch": true },
      "Scyther": { "always_catch": true },
      "Tentacruel": { "always_catch": true },
      "Gengar": { "always_catch": true },
      "Hypno": { "always_catch": true },
      "Pidgeot": { "always_catch": true },
      "Rhydon": { "always_catch": true },
      "Seaking": { "always_catch": true },
      "Kangaskhan": { "always_catch": true }
    },
    "release": {
      "// any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "Eevee": {"keep_best_cp": 3},
      "Zubat": {"keep_best_cp": 1},
      "Pidgey": {"keep_best_cp": 1},
      "Rattata": {"keep_best_cp": 1},
      "Caterpie": {"keep_best_cp": 1},
      "Weedle": {"keep_best_cp": 1},
      "Metapod": {"keep_best_cp": 1},
      "Kakuna": {"keep_best_cp": 1},
      "Doduo": {"keep_best_cp": 1},
      "Poliwag": {"keep_best_cp": 1},
      "Voltorb": {"keep_best_cp": 1},
      "Paras": {"keep_best_cp": 1},
      "Horsea": {"keep_best_cp": 1},
      "Spearow": {"keep_best_cp": 1},
      "Krabby": {"keep_best_cp": 1},
      "Sandshrew": {"keep_best_cp": 1},
      "Ekans": {"keep_best_cp": 1},
      "Magnemite": {"keep_best_cp": 1},
      "Drowzee": {"keep_best_cp": 1},
      "Cubone": {"keep_best_cp": 1},
      "Machop": {"keep_best_cp": 1},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "any": {"keep_best_cp": 2}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}

### Steps to Reproduce
Get banned once.

### Other Information
OS: Ubuntu 15.04
Git Commit: b94d3695e454b1020775e4b717fe397e18646fce
Python Version: Python 2.7.9

**Comment by GitPupper** [comment]
***
[PokeBot-Updater.zip](https://github.com/PokemonGoF/PokemonGo-Bot/files/410051/PokeBot-Updater.zip)
Use this. One click and it should update your bot.
***
And also use this config.json
http://pastebin.com/UStttHL2
***
Update your Python version.
***

**Comment by db-coder** [comment]
What exactly do you mean by "you have nothing set for HandleSoftBan"? I do have a task : 
{
        "type": "HandleSoftBan"
},

Also, the PokeBot-Updater just does a git pull. But my bot is already the latest version.

**Comment by GitPupper** [comment]
Ah, I see the problem. you have This:
***
{
"type": "FollowCluster",
"config": {
"radius": 50,
"lured": false
}
}
***
When really, it should be this:
***
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
***

**Comment by db-coder** [comment]
I did that and now, but is just stuck doing this infinitely 
`2016-08-10 05:14:23,067 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Arthur Ross Pinetum - 0.08km (attraction of lure 0.08km)
2016-08-10 05:14:23,463 [MoveToFort] [INFO] [arrived_at_fort] Arrived at fort.
2016-08-10 05:14:26,127 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Arthur Ross Pinetum - 0.08km (attraction of lure 0.08km)
2016-08-10 05:14:26,738 [MoveToFort] [INFO] [arrived_at_fort] Arrived at fort.
2016-08-10 05:14:29,794 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Arthur Ross Pinetum - 0.08km (attraction of lure 0.08km)
2016-08-10 05:14:30,183 [MoveToFort] [INFO] [arrived_at_fort] Arrived at fort.
2016-08-10 05:14:33,751 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Arthur Ross Pinetum - 0.08km (attraction of lure 0.08km)
2016-08-10 05:14:34,156 [MoveToFort] [INFO] [arrived_at_fort] Arrived at fort.
2016-08-10 05:14:37,520 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Arthur Ross Pinetum - 0.08km (attraction of lure 0.08km)
2016-08-10 05:14:37,914 [MoveToFort] [INFO] [arrived_at_fort] Arrived at fort.
2016-08-10 05:14:40,873 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Arthur Ross Pinetum - 0.08km (attraction of lure 0.08km)
2016-08-10 05:14:41,270 [MoveToFort] [INFO] [arrived_at_fort] Arrived at fort.
2016-08-10 05:14:44,115 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Arthur Ross Pinetum - 0.08km (attraction of lure 0.08km)
2016-08-10 05:14:44,507 [MoveToFort] [INFO] [arrived_at_fort] Arrived at fort.
2016-08-10 05:14:47,371 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Arthur Ross Pinetum - 0.08km (attraction of lure 0.08km)
2016-08-10 05:14:47,781 [MoveToFort] [INFO] [arrived_at_fort] Arrived at fort.
2016-08-10 05:14:50,980 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Arthur Ross Pinetum - 0.08km (attraction of lure 0.08km)
2016-08-10 05:14:51,372 [MoveToFort] [INFO] [arrived_at_fort] Arrived at fort`

**Comment by GitPupper** [comment]
Do a copy/paste of my pastebin and see if it works.

**Comment by db-coder** [comment]
There's no difference between your config and mine. Just that I've not used the nicknaming task and you forgot "libencrypt_location": ""

**Comment by z4ppy** [comment]
Hi, i have same error some time ago. I don't know why, but sometime TaskWork dont receive config in parameter. In move_to_fort, before self.config.... you must add if self.config:

I seen that with softban.

So quick fix :

if self.config:
    self.lure_attraction = self.config.get("lure_attraction", True)
    self.lure_max_distance = self.config.get("lure_max_distance", 800)
else:
    self.lure_attraction = False
    self.lure_max_distance = 800

**Comment by cmezh** [comment]
#3500

**Comment by k4n30** [comment]
@db-coder does #3500 fix your issue?
