### ISSUE TITLE
Struct() argument 1 must be string, not unicode in colored_loggin_handler.py

### ISSUE THREAD

**Issue by vanishing** [PokemonGoF/PokemonGo-Bot#3373]
### Expected Behavior
Bot should start and run successfully

### Actual Behavior
```
Traceback (most recent call last):
  File "pokecli.py", line 530, in <module>
    main()
  File "pokecli.py", line 96, in main
    bot.tick()
  File "/home/pi/PokemonGo-Bot/pokemongo_bot/__init__.py", line 458, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/pi/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort.py", line 67, in work
    data=fort_event_data
  File "/home/pi/PokemonGo-Bot/pokemongo_bot/base_task.py", line 27, in emit_event
    data=data
  File "/home/pi/PokemonGo-Bot/pokemongo_bot/event_manager.py", line 65, in emit
    handler.handle_event(event, sender, level, formatted_msg, data)
  File "/home/pi/PokemonGo-Bot/pokemongo_bot/event_handlers/colored_logging_handler.py", line 130, in handle_event
    terminal_width = self._terminal_width()
  File "/home/pi/PokemonGo-Bot/pokemongo_bot/event_handlers/colored_logging_handler.py", line 171, in _terminal_width
    struct.pack('HHHH', 0, 0, 0, 0)))
TypeError: Struct() argument 1 must be string, not unicode
```

### Steps to Reproduce
Just run run.sh, maybe wait for a couple of minutes

### Other Information
OS: Raspbian
Git Commit: 8b5af8d766ac161be926932b05e3fc785a33661d
Python Version: 2.7.3

**Comment by vanishing** [comment]
Fix in, can be closed.
