### ISSUE TITLE
Chunked Encoding Error

### ISSUE THREAD

**Issue by nikhil-pandey** [PokemonGoF/PokemonGo-Bot#3374]
```
Traceback (most recent call last):
  File "pokecli.py", line 521, in <module>
    main()
  File "pokecli.py", line 95, in main
    bot.tick()
  File "/home/pi/bot/pokemongo_bot/__init__.py", line 446, in tick
    self.cell = self.get_meta_cell()
  File "/home/pi/bot/pokemongo_bot/__init__.py", line 458, in get_meta_cell
    cells = self.find_close_cells(*location)
  File "/home/pi/bot/pokemongo_bot/__init__.py", line 532, in find_close_cells
    response_dict = self.get_map_objects(lat, lng, timestamp, cellid)
  File "/home/pi/bot/pokemongo_bot/__init__.py", line 1075, in get_map_objects
    cell_id=cellid
  File "/home/pi/bot/src/pgoapi/pgoapi/pgoapi.py", line 122, in function
    return request.call()
  File "/home/pi/bot/pokemongo_bot/api_wrapper.py", line 106, in call
    result = self._call()
  File "/home/pi/bot/pokemongo_bot/api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "/home/pi/bot/src/pgoapi/pgoapi/pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/home/pi/bot/src/pgoapi/pgoapi/rpc_api.py", line 127, in request
    response = self._make_rpc(endpoint, request_proto)
  File "/home/pi/bot/src/pgoapi/pgoapi/rpc_api.py", line 115, in _make_rpc
    http_response = self._session.post(endpoint, data=request_proto_serialized, timeout=30)
  File "/home/pi/bot/local/lib/python2.7/site-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/pi/bot/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/bot/local/lib/python2.7/site-packages/requests/sessions.py", line 617, in send
    r.content
  File "/home/pi/bot/local/lib/python2.7/site-packages/requests/models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/home/pi/bot/local/lib/python2.7/site-packages/requests/models.py", line 667, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))
```

**Comment by Ph4i1ur3** [comment]
What commit are you using? And does this happen frequently? If so, how to reproduce the effect?

**Comment by nikhil-pandey** [comment]
I am using 0f2bddd26675c5232b2e9f4e83dc6525c41a842d

Happened once last night.

**Comment by Ph4i1ur3** [comment]
I'm thinking this could be the result of the API change that occurred last night. I'd update to the latest release and make sure your requirements are up to date
