### ISSUE TITLE
[DEV] Event threw_pokeball does not require parameter pokeball

### ISSUE THREAD

**Issue by MikeDX** [PokemonGoF/PokemonGo-Bot#3423]
When bot encounters a pokemon, bot crashes.

```
[05:35:50] Starting bot...
[05:35:50] Received level up reward: []
[05:35:50] Next egg incubates in 1.54 km
[05:35:52] Something rustles nearby!
[05:35:53] A wild Goldeen appeared! [CP 11] [Potential 0.44] [S/A/D 4/9/7]2016-08-10 05:35:55,983 [       cli] [INFO] 
2016-08-10 05:35:55,993 [       cli] [INFO] Ran for 0:00:10
2016-08-10 05:35:55,993 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-10 05:35:55,993 [       cli] [INFO] Travelled 0.00km
2016-08-10 05:35:55,993 [       cli] [INFO] Visited 0 stops
2016-08-10 05:35:55,994 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-10 05:35:55,994 [       cli] [INFO] Threw 0 pokeballs
2016-08-10 05:35:55,994 [       cli] [INFO] Earned 0 Stardust
2016-08-10 05:35:55,994 [       cli] [INFO] 
2016-08-10 05:35:55,994 [       cli] [INFO] Highest CP Pokemon: 
2016-08-10 05:35:55,994 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "./pokecli.py", line 530, in <module>
    main()
  File "./pokecli.py", line 96, in main
    bot.tick()
  File "/home/mike/pbot4/pokemongo_bot/__init__.py", line 458, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/mike/pbot4/pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 49, in work
    self.catch_pokemon(self.bot.cell['catchable_pokemons'].pop(0))
  File "/home/mike/pbot4/pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 70, in catch_pokemon
    return_value = worker.work()
  File "/home/mike/pbot4/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 301, in work
    'count_left': items_stock[pokeball]
  File "/home/mike/pbot4/pokemongo_bot/base_task.py", line 27, in emit_event
    data=data
  File "/home/mike/pbot4/pokemongo_bot/event_manager.py", line 59, in emit
    raise EventMalformedException("Event %s does not require parameter %s" % (event, k))
pokemongo_bot.event_manager.EventMalformedException: Event threw_pokeball does not require parameter pokeball
```
### Other Information
OS: LINUX
Git Commit: 01bc14de0543196de6688dc6bd560739db59fd14
Python Version: Python 2.7.9

**Comment by icecubeice** [comment]
try pulling the latest commit: git pull in your directory, worked for me :)
