### ISSUE TITLE
Unable to login anymore

### ISSUE THREAD

**Issue by tvb** [PokemonGoF/PokemonGo-Bot#3424]
I can login with the app, so I guess am not banned.

### Expected Behavior

Logged in successfully.

### Actual Behavior

```
2016-08-10 11:42:10,266 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-10 11:42:10,285 [       cli] [INFO] Configuration initialized
2016-08-10 11:42:10,286 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-10 11:42:10,287 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-10 11:42:10,339 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com

[11:42:10] Setting start location.2016-08-10 11:42:10,414 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.

[11:42:10] Location found: 51.8527712,4.3377733 (51.8527712, 4.3377733, 0.0)
[11:42:10] Now at (51.8527712, 4.3377733, 0)
[11:42:10] Login procedure started.Traceback (most recent call last):
  File "pokecli.py", line 530, in <module>
    main()
  File "pokecli.py", line 138, in main
    report_summary(bot)
  File "pokecli.py", line 147, in report_summary
    metrics.capture_stats()
  File "/home/pi/PokemonGo-Bot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/home/pi/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 90, in call
    if not self.can_call():
  File "/home/pi/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 58, in can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
2016-08-10 11:44:18,344 [sentry.errors] [ERROR] Sentry responded with an error: 'module' object has no attribute 'HTTPSHandler' (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 44, in urlopen
    class ValidHTTPSHandler(urllib2.HTTPSHandler):
AttributeError: 'module' object has no attribute 'HTTPSHandler'
2016-08-10 11:44:18,348 [sentry.errors.uncaught] [ERROR] [u'NotLoggedInException', u'  File "pokecli.py", line 530, in <module>', u'  File "pokecli.py", line 138, in main', u'  File "pokecli.py", line 147, in report_summary', u'  File "pokemongo_bot/metrics.py", line 76, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 90, in call', u'  File "pokemongo_bot/api_wrapper.py", line 58, in can_call']
Process crashed with exit code 1.  Respawning..
```

### Your config.json (remove your credentials and any other private info)
```
{
	"auth_service": "google",
	"username": "xxx",
	"password": "xxx",
	"location": "51.8527712,4.3377733",
	"gmapkey": "xxx",
	"libencrypt_location": "",
	"tasks": [{
		"type": "HandleSoftBan"
	}, {
		"type": "CollectLevelUpReward"
	}, {
		"type": "IncubateEggs",
		"config": {
			"longer_eggs_first": true
		}
	}, {
		"type": "TransferPokemon"
	}, {
		"type": "EvolvePokemon",
		"config": {
			"evolve_all": "none",
			"first_evolve_by": "cp",
			"evolve_above_cp": 500,
			"evolve_above_iv": 0.8,
			"logic": "or",
			"evolve_speed": 20,
			"use_lucky_egg": false
		}
	}, {
		"type": "RecycleItems",
		"config": {
			"item_filter": {
				"Pokeball": {
					"keep": 50
				},
				"Greatball": {
					"keep": 65
				},
				"Ultraball": {
					"keep": 75
				},
				"Potion": {
					"keep": 10
				},
				"Super Potion": {
					"keep": 20
				},
				"Hyper Potion": {
					"keep": 30
				},
				"Revive": {
					"keep": 30
				},
				"Incense": {
					"keep": 10
				},
				"Razz Berry": {
					"keep": 40
				}
			}
		}
	}, {
		"type": "CatchVisiblePokemon"
	}, {
		"type": "CatchLuredPokemon"
	}, {
		"type": "SpinFort"
	}, {
		"type": "MoveToFort",
		"config": {
			"lure_attraction": true,
			"lure_max_distance": 2000
		}
	}, {
		"type": "FollowSpiral",
		"config": {
			"diameter": 4,
			"step_size": 70
		}
	}],
	"map_object_cache_time": 5,
	"forts": {
		"avoid_circles": true,
		"max_circle_size": 50
	},
	"websocket_server": false,
	"walk": 4.6,
	"action_wait_min": 1,
	"action_wait_max": 4,
	"debug": false,
	"test": false,
	"health_record": true,
	"location_cache": false,
	"distance_unit": "km",
	"reconnecting_timeout": 15,
	"evolve_captured": "NONE",
	"catch_randomize_reticle_factor": 1.0,
	"catch_randomize_spin_factor": 1.0,
	"logging_color": true,
	"catch": {
		"any": {
			"catch_above_cp": 0,
			"catch_above_iv": 0,
			"logic": "or"
		}
	},
	"release": {
		"any": {
			"release_below_cp": 1200,
			"release_below_iv": 0.9,
			"logic": "and"
		}
	},
	"vips": {
		"Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
		"any": {
			"catch_above_cp": 1200,
			"catch_above_iv": 0.9,
			"logic": "or"
		},
		"Lapras": {},
		"Moltres": {},
		"Zapdos": {},
		"Articuno": {},

		"// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
		"Mewtwo": {},
		"Dragonite": {},
		"Snorlax": {},
		"// Mew evolves to Mewtwo": {},
		"Mew": {},
		"Arcanine": {},
		"Vaporeon": {},
		"Gyarados": {},
		"Exeggutor": {},
		"Muk": {},
		"Weezing": {},
		"Flareon": {}
	}
}
```

### Steps to Reproduce

Latest dev, restart bot?

### Other Information
OS: Pi
Git Commit: 01bc14de0543196de6688dc6bd560739db59fd14
Python Version: Python 2.7.3

**Comment by tvb** [comment]
Pokemon Go is not down
<img width="995" alt="screen shot 2016-08-10 at 11 48 28" src="https://cloud.githubusercontent.com/assets/1263414/17549421/658c3768-5ef0-11e6-9655-c3609248c576.png">

**Comment by tvb** [comment]
```
[11:55:42] Login procedure started.
[11:55:44] Login successful.2016-08-10 11:55:45,201 [PokemonGoBot] [INFO]
2016-08-10 11:55:45,202 [PokemonGoBot] [INFO] --- vivan46 ---
2016-08-10 11:55:45,204 [PokemonGoBot] [INFO] Level: 28 (Next Level: 199273 XP) (Total: 1450727 XP)
2016-08-10 11:55:45,205 [PokemonGoBot] [INFO] Pokemon Captured: 5724 | Pokestops Visited: 3657
2016-08-10 11:55:45,208 [PokemonGoBot] [INFO] Pokemon Bag: 31/250
2016-08-10 11:55:45,212 [PokemonGoBot] [INFO] Items: 343/350
2016-08-10 11:55:45,212 [PokemonGoBot] [INFO] Stardust: 3473 | Pokecoins: 20
2016-08-10 11:55:45,213 [PokemonGoBot] [INFO] PokeBalls: 50 | GreatBalls: 0 | UltraBalls: 71
2016-08-10 11:55:45,214 [PokemonGoBot] [INFO] RazzBerries: 2 | BlukBerries: 0 | NanabBerries: 0
2016-08-10 11:55:45,215 [PokemonGoBot] [INFO] LuckyEgg: 6 | Incubator: 0 | TroyDisk: 5
2016-08-10 11:55:45,216 [PokemonGoBot] [INFO] Potion: 10 | SuperPotion: 20 | HyperPotion: 30 | MaxPotion: 108
2016-08-10 11:55:45,216 [PokemonGoBot] [INFO] Incense: 9 | IncenseSpicy: 0 | IncenseCool: 0
2016-08-10 11:55:45,217 [PokemonGoBot] [INFO] Revive: 30 | MaxRevive: 0
2016-08-10 11:55:45,218 [PokemonGoBot] [INFO]
2016-08-10 11:55:45,219 [PokemonGoBot] [INFO] Found encrypt.so! Platform: linux2 Encrypt.so directory: /home/pi/PokemonGo-Bot
2016-08-10 11:55:45,219 [PokemonGoBot] [INFO]

[11:55:47] Starting bot...
```

It took multiple tries, but I am logged in again.
