### ISSUE TITLE
NotLoggedInException - bot doesn't want to login

### ISSUE THREAD

**Issue by Sztucznooki** [PokemonGoF/PokemonGo-Bot#3439]
### Expected Behavior

Bot should login and play

### Actual Behavior

It raises "NotLoggedInException()" pgoapi.exceptions.NotLoggedInException

when I attempt to run it.

```
2016-08-10 13:04:31,825 [PokemonGoBot] [INFO] [login_started] Login procedure st
arted.
Traceback (most recent call last):
  File "pokecli.py", line 521, in <module>
    main()
  File "pokecli.py", line 137, in main
    report_summary(bot)
  File "pokecli.py", line 146, in report_summary
    metrics.capture_stats()
  File "C:\POGO\BOT\PokemonGo-Bot\pokemongo_bot\metrics.py", line 76, in capture
_stats
    response_dict = request.call()
  File "C:\POGO\BOT\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 90, in cal
l
    if not self.can_call():
  File "C:\POGO\BOT\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 58, in can
_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
```

### Your config.json (remove your credentials and any other private info)
```
{
    "auth_service": "google",
    "username": "@gmail.com",
    "password": "",
    "location": "",
    "gmapkey": "",
    "libencrypt_location": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "item_filter": {
            "Pokeball":       { "keep" : 50 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config":{
          "lure_attraction": true,
          "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 10.27,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": false,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or" },

      "// Pokemons with example": { "always_catch": true },
      "// Gets filtered with release parameters": {},

      "// Legendary pokemons (Goes under S-Tier)": {},
      "Lapras": { "always_catch": true },
      "Moltres": { "always_catch": true },
      "Zapdos": { "always_catch": true },
      "Articuno": { "always_catch": true },

      "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
      "Mewtwo": { "always_catch": true },
      "Dragonite": { "always_catch": true },
      "Snorlax": { "always_catch": true },
      "// Mew evolves to Mewtwo": {},
      "Mew": { "always_catch": true },
      "Arcanine": { "always_catch": true },
      "Vaporeon": { "always_catch": true },
      "Gyarados": { "always_catch": true },
      "Exeggutor": { "always_catch": true },
      "Muk": { "always_catch": true },
      "Weezing": { "always_catch": true },
      "Flareon": { "always_catch": true },

      "// Growlithe evolves to Arcanine": {},
      "Growlithe": { "always_catch": true },
      "// Dragonair evolves to Dragonite": {},
      "Dragonair": { "always_catch": true },
      "// Grimer evolves to Muk": {},
      "Grimer": { "always_catch": true },

      "// Magikarp evolves to Gyarados": {},
      "Magikarp": { "always_catch": true },
      "// Exeggcute evolves to Exeggutor": {},
      "Exeggcute": { "always_catch": true },
      "// Eevee evolves to many versions, like Vaporeon, Flareon": {},
      "Eevee": { "always_catch": true },

      "// A-Tier pokemons": {},
      "Slowbro": { "always_catch": true },
      "Victreebel": { "always_catch": true },
      "Machamp": { "always_catch": true },
      "Poliwrath": { "always_catch": true },
      "Clefable": { "always_catch": true },
      "Nidoking": { "always_catch": true },
      "Venusaur": { "always_catch": true },
      "Charizard": { "always_catch": true },
      "Golduck": { "always_catch": true },
      "Nidoqueen": { "always_catch": true },
      "Vileplume": { "always_catch": true },
      "Blastoise": { "always_catch": true },
      "Omastar":  { "always_catch": true },
      "Aerodactyl": { "always_catch": true },
      "Golem": { "always_catch": true },
      "Wigglytuff": { "always_catch": true },
      "Dewgong": { "always_catch": true },
      "Ninetales": { "always_catch": true },
      "Magmar": { "always_catch": true },
      "Kabutops": { "always_catch": true },
      "Electabuzz": { "always_catch": true },
      "Starmie": { "always_catch": true },
      "Jolteon": { "always_catch": true },
      "Rapidash": { "always_catch": true },
      "Pinsir": { "always_catch": true },
      "Scyther": { "always_catch": true },
      "Tentacruel": { "always_catch": true },
      "Gengar": { "always_catch": true },
      "Hypno": { "always_catch": true },
      "Pidgeot": { "always_catch": true },
      "Rhydon": { "always_catch": true },
      "Seaking": { "always_catch": true },
      "Kangaskhan": { "always_catch": true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or" },

      "// Legendary pokemons (Goes under S-Tier)": {},
      "Lapras": { "release_below_cp": 1041, "release_below_iv": 0.1, "logic": "and" },
      "Moltres": { "release_below_cp": 1132, "release_below_iv": 0.1, "logic": "and" },
      "Zapdos": { "release_below_cp": 1087, "release_below_iv": 0.1, "logic": "and" },
      "Articuno": { "release_below_cp": 1039, "release_below_iv": 0.1, "logic": "and" },

      "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
      "Mewtwo": { "release_below_cp": 1447, "release_below_iv": 0.1, "logic": "and"},
      "Dragonite": { "release_below_cp": 1221, "release_below_iv": 0.1, "logic": "and" },
      "Snorlax": { "release_below_cp": 1087, "release_below_iv": 0.1, "logic": "and" },
      "// Mew evolves to Mewtwo": {},
      "Mew": { "release_below_cp": 1152, "release_below_iv": 0.1, "logic": "and" },
      "Arcanine": { "release_below_cp": 1041, "release_below_iv": 0.1, "logic": "and" },
      "Vaporeon": { "release_below_cp": 984, "release_below_iv": 0.1, "logic": "and" },
      "Gyarados": { "release_below_cp": 938, "release_below_iv": 0.1, "logic": "and" },
      "Exeggutor": { "release_below_cp": 1032, "release_below_iv": 0.1, "logic": "and" },
      "Muk": { "release_below_cp": 909, "release_below_iv": 0.1, "logic": "and" },
      "Weezing": { "release_below_cp": 784, "release_below_iv": 0.1, "logic": "and" },
      "Flareon": { "release_below_cp": 924, "release_below_iv": 0.1, "logic": "and" },

      "// Growlithe evolves to Arcanine": {},
      "Growlithe": { "release_below_cp": 465, "release_below_iv": 0.1, "logic": "and" },
      "// Dragonair evolves to Dragonite": {},
      "Dragonair": { "release_below_cp": 609, "release_below_iv": 0.1, "logic": "and" },
      "// Grimer evolves to Muk": {},
      "Grimer": { "release_below_cp": 448, "release_below_iv": 0.1, "logic": "and" },
      "// Magikarp evolves to Gyarados": {},
      "Magikarp": { "release_below_cp": 91, "release_below_iv": 0.1, "logic": "and" },
      "// Exeggcute evolves to Exeggutor": {},
      "Exeggcute": { "release_below_cp": 384, "release_below_iv": 0.1, "logic": "and" },
      "// Eevee evolves to many versions, like Vaporeon, Flareon": {},
      "Eevee": { "release_below_cp": 376, "release_below_iv": 0.1, "logic": "and" },

      "// A-Tier pokemons": {},
      "Slowbro": { "release_below_cp": 907, "release_below_iv": 0.1, "logic": "and" },
      "Victreebel": { "release_below_cp": 883, "release_below_iv": 0.1, "logic": "and" },
      "Machamp": { "release_below_cp": 907, "release_below_iv": 0.1, "logic": "and" },
      "Poliwrath": { "release_below_cp": 876, "release_below_iv": 0.1, "logic": "and" },
      "Clefable": { "release_below_cp": 837, "release_below_iv": 0.1, "logic": "and" },
      "Nidoking": { "release_below_cp": 864, "release_below_iv": 0.1, "logic": "and" },
      "Venusaur": { "release_below_cp": 902, "release_below_iv": 0.1, "logic": "and" },
      "Charizard": { "release_below_cp": 909, "release_below_iv": 0.1, "logic": "and" },
      "Golduck": { "release_below_cp": 832, "release_below_iv": 0.1, "logic": "and" },
      "Nidoqueen": { "release_below_cp": 868, "release_below_iv": 0.1, "logic": "and" },
      "Vileplume": { "release_below_cp": 871, "release_below_iv": 0.1, "logic": "and" },
      "Blastoise": { "release_below_cp": 888, "release_below_iv": 0.1, "logic": "and" },
      "Omastar":  { "release_below_cp": 780, "release_below_iv": 0.1, "logic": "and" },
      "Aerodactyl": { "release_below_cp": 756, "release_below_iv": 0.1, "logic": "and" },
      "Golem": { "release_below_cp": 804, "release_below_iv": 0.1, "logic": "and" },
      "Wigglytuff": { "release_below_cp": 760, "release_below_iv": 0.1, "logic": "and" },
      "Dewgong": { "release_below_cp": 748, "release_below_iv": 0.1, "logic": "and" },
      "Ninetales": { "release_below_cp": 763, "release_below_iv": 0.1, "logic": "and" },
      "Magmar": { "release_below_cp": 792, "release_below_iv": 0.1, "logic": "and" },
      "Kabutops": { "release_below_cp": 744, "release_below_iv": 0.1, "logic": "and" },
      "Electabuzz": { "release_below_cp": 739, "release_below_iv": 0.1, "logic": "and" },
      "Starmie": { "release_below_cp": 763, "release_below_iv": 0.1, "logic": "and" },
      "Jolteon": { "release_below_cp": 746, "release_below_iv": 0.1, "logic": "and" },
      "Rapidash": { "release_below_cp": 768, "release_below_iv": 0.1, "logic": "and" },
      "Pinsir": { "release_below_cp": 741, "release_below_iv": 0.1, "logic": "and" },
      "Scyther": { "release_below_cp": 724, "release_below_iv": 0.1, "logic": "and" },
      "Tentacruel": { "release_below_cp": 775, "release_below_iv": 0.1, "logic": "and" },
      "Gengar": { "release_below_cp": 724, "release_below_iv": 0.1, "logic": "and" },
      "Hypno": { "release_below_cp": 763, "release_below_iv": 0.1, "logic": "and" },
      "Pidgeot": { "release_below_cp": 729, "release_below_iv": 0.1, "logic": "and" },
      "Rhydon": { "release_below_cp": 782, "release_below_iv": 0.1, "logic": "and" },
      "Seaking": { "release_below_cp": 712, "release_below_iv": 0.1, "logic": "and" },
      "Kangaskhan": { "release_below_cp": 712, "release_below_iv": 0.1, "logic": "and" },

      "// Koffing evolves to Weezing (A-Tier)": {},
      "Koffing": { "release_below_cp": 403, "release_below_iv": 0.1, "logic": "and" },

      "// Below is B-tier and lower pokemons": {},
      "Caterpie": { "release_below_cp": 156, "release_below_iv": 0.1, "logic": "and" },
      "Weedle": { "release_below_cp": 156, "release_below_iv": 0.1, "logic": "and" },
      "Diglett": { "release_below_cp": 158, "release_below_iv": 0.1, "logic": "and" },
      "Metapod": { "release_below_cp": 168, "release_below_iv": 0.1, "logic": "and" },
      "Kakuna": { "release_below_cp": 170, "release_below_iv": 0.1, "logic": "and" },
      "Rattata": { "release_below_cp": 204, "release_below_iv": 0.1, "logic": "and" },
      "Abra": { "release_below_cp": 208, "release_below_iv": 0.1, "logic": "and" },
      "Zubat": { "release_below_cp": 225, "release_below_iv": 0.1, "logic": "and" },
      "Chansey": { "release_below_cp": 235, "release_below_iv": 0.1, "logic": "and" },
      "Pidgey": { "release_below_cp": 237, "release_below_iv": 0.1, "logic": "and" },
      "Spearow": { "release_below_cp": 240, "release_below_iv": 0.1, "logic": "and" },
      "Meowth": { "release_below_cp": 264, "release_below_iv": 0.1, "logic": "and" },
      "Krabby": { "release_below_cp": 276, "release_below_iv": 0.1, "logic": "and" },
      "Sandshrew": { "release_below_cp": 278, "release_below_iv": 0.1, "logic": "and" },
      "Poliwag": { "release_below_cp": 278, "release_below_iv": 0.1, "logic": "and" },
      "Horsea": { "release_below_cp": 278, "release_below_iv": 0.1, "logic": "and" },
      "Gastly": { "release_below_cp": 280, "release_below_iv": 0.1, "logic": "and" },
      "Ekans": { "release_below_cp": 288, "release_below_iv": 0.1, "logic": "and" },
      "Shellder": { "release_below_cp": 288, "release_below_iv": 0.1, "logic": "and" },
      "Vulpix": { "release_below_cp": 290, "release_below_iv": 0.1, "logic": "and" },
      "Voltorb": { "release_below_cp": 292, "release_below_iv": 0.1, "logic": "and" },
      "Geodude": { "release_below_cp": 297, "release_below_iv": 0.1, "logic": "and" },
      "Doduo": { "release_below_cp": 297, "release_below_iv": 0.1, "logic": "and" },
      "Onix": { "release_below_cp": 300, "release_below_iv": 0.1, "logic": "and" },
      "Mankey": { "release_below_cp": 307, "release_below_iv": 0.1, "logic": "and" },
      "Pikachu": { "release_below_cp": 309, "release_below_iv": 0.1, "logic": "and" },
      "Magnemite": { "release_below_cp": 312, "release_below_iv": 0.1, "logic": "and" },
      "Tentacool": { "release_below_cp": 316, "release_below_iv": 0.1, "logic": "and" },
      "Paras": { "release_below_cp": 319, "release_below_iv": 0.1, "logic": "and" },
      "Jigglypuff": { "release_below_cp": 321, "release_below_iv": 0.1, "logic": "and" },
      "Ditto": { "release_below_cp": 321, "release_below_iv": 0.1, "logic": "and" },
      "Staryu": { "release_below_cp": 326, "release_below_iv": 0.1, "logic": "and" },
      "Charmander": { "release_below_cp": 333, "release_below_iv": 0.1, "logic": "and" },
      "Goldeen": { "release_below_cp": 336, "release_below_iv": 0.1, "logic": "and" },
      "Squirtle": { "release_below_cp": 352, "release_below_iv": 0.1, "logic": "and" },
      "Cubone": { "release_below_cp": 352, "release_below_iv": 0.1, "logic": "and" },
      "Venonat": { "release_below_cp": 360, "release_below_iv": 0.1, "logic": "and" },
      "Bulbasaur": { "release_below_cp": 374, "release_below_iv": 0.1, "logic": "and" },
      "Drowzee": { "release_below_cp": 374, "release_below_iv": 0.1, "logic": "and" },
      "Machop": { "release_below_cp": 381, "release_below_iv": 0.1, "logic": "and" },
      "Psyduck": { "release_below_cp": 386, "release_below_iv": 0.1, "logic": "and" },
      "Seel": { "release_below_cp": 386, "release_below_iv": 0.1, "logic": "and" },
      "Kabuto": { "release_below_cp": 386, "release_below_iv": 0.1, "logic": "and" },
      "Bellsprout": { "release_below_cp": 391, "release_below_iv": 0.1, "logic": "and" },
      "Omanyte": { "release_below_cp": 391, "release_below_iv": 0.1, "logic": "and" },
      "Kadabra": { "release_below_cp": 396, "release_below_iv": 0.1, "logic": "and" },
      "Oddish": { "release_below_cp": 400, "release_below_iv": 0.1, "logic": "and" },
      "Dugtrio": { "release_below_cp": 408, "release_below_iv": 0.1, "logic": "and" },
      "Rhyhorn": { "release_below_cp": 412, "release_below_iv": 0.1, "logic": "and" },
      "Clefairy": { "release_below_cp": 420, "release_below_iv": 0.1, "logic": "and" },
      "Slowpoke": { "release_below_cp": 424, "release_below_iv": 0.1, "logic": "and" },
      "Pidgeotto": { "release_below_cp": 427, "release_below_iv": 0.1, "logic": "and" },
      "Farfetch'd": { "release_below_cp": 441, "release_below_iv": 0.1, "logic": "and" },
      "Poliwhirl": { "release_below_cp": 468, "release_below_iv": 0.1, "logic": "and" },
      "Nidorino": { "release_below_cp": 480, "release_below_iv": 0.1, "logic": "and" },
      "Haunter": { "release_below_cp": 482, "release_below_iv": 0.1, "logic": "and" },
      "Nidorina": { "release_below_cp": 489, "release_below_iv": 0.1, "logic": "and" },
      "Graveler": { "release_below_cp": 501, "release_below_iv": 0.1, "logic": "and" },
      "Beedrill": { "release_below_cp": 504, "release_below_iv": 0.1, "logic": "and" },
      "Raticate": { "release_below_cp": 504, "release_below_iv": 0.1, "logic": "and" },
      "Butterfree": { "release_below_cp": 508, "release_below_iv": 0.1, "logic": "and" },
      "Hitmonlee": { "release_below_cp": 520, "release_below_iv": 0.1, "logic": "and" },
      "Ponyta": { "release_below_cp": 530, "release_below_iv": 0.1, "logic": "and" },
      "Hitmonchan": { "release_below_cp": 530, "release_below_iv": 0.1, "logic": "and" },
      "Charmeleon": { "release_below_cp": 544, "release_below_iv": 0.1, "logic": "and" },
      "Wartortle": { "release_below_cp": 552, "release_below_iv": 0.1, "logic": "and" },
      "Persian": { "release_below_cp": 568, "release_below_iv": 0.1, "logic": "and" },
      "Lickitung": { "release_below_cp": 568, "release_below_iv": 0.1, "logic": "and" },
      "Ivysaur": { "release_below_cp": 571, "release_below_iv": 0.1, "logic": "and" },
      "Electrode": { "release_below_cp": 576, "release_below_iv": 0.1, "logic": "and" },
      "Marowak": { "release_below_cp": 578, "release_below_iv": 0.1, "logic": "and" },
      "Gloom": { "release_below_cp": 590, "release_below_iv": 0.1, "logic": "and" },
      "Porygon": { "release_below_cp": 590, "release_below_iv": 0.1, "logic": "and" },
      "Seadra": { "release_below_cp": 597, "release_below_iv": 0.1, "logic": "and" },
      "Jynx": { "release_below_cp": 600, "release_below_iv": 0.1, "logic": "and" },
      "Weepinbell": { "release_below_cp": 602, "release_below_iv": 0.1, "logic": "and" },
      "Tangela": { "release_below_cp": 607, "release_below_iv": 0.1, "logic": "and" },
      "Fearow": { "release_below_cp": 609, "release_below_iv": 0.1, "logic": "and" },
      "Parasect": { "release_below_cp": 609, "release_below_iv": 0.1, "logic": "and" },
      "Machoke": { "release_below_cp": 614, "release_below_iv": 0.1, "logic": "and" },
      "Arbok": { "release_below_cp": 616, "release_below_iv": 0.1, "logic": "and" },
      "Sandslash": { "release_below_cp": 631, "release_below_iv": 0.1, "logic": "and" },
      "Alakazam": { "release_below_cp": 633, "release_below_iv": 0.1, "logic": "and" },
      "Kingler": { "release_below_cp": 636, "release_below_iv": 0.1, "logic": "and" },
      "Dodrio": { "release_below_cp": 640, "release_below_iv": 0.1, "logic": "and" },
      "Tauros": { "release_below_cp": 643, "release_below_iv": 0.1, "logic": "and" },
      "Primeape": { "release_below_cp": 650, "release_below_iv": 0.1, "logic": "and" },
      "Magneton": { "release_below_cp": 657, "release_below_iv": 0.1, "logic": "and" },
      "Venomoth": { "release_below_cp": 660, "release_below_iv": 0.1, "logic": "and" },
      "Golbat": { "release_below_cp": 672, "release_below_iv": 0.1, "logic": "and" },
      "Raichu": { "release_below_cp": 708, "release_below_iv": 0.1, "logic": "and" },
      "Cloyster": { "release_below_cp": 717, "release_below_iv": 0.1, "logic": "and"},
      "Mr. Mime": { "release_below_cp": 650, "release_below_iv": 0.1, "logic": "and" }
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}

```

### Steps to Reproduce

stuck on
python pokecli.py -cf po
(my config file is named "PO" and is in root folder)

### Other Information
OS: Windows 8.1
Git Commit: 63f777bac0c8cdc75d07f9ef491ca8b900c0148a
Python Version: Python 2.7.10

**Comment by Ph4i1ur3** [comment]
Have you updated ran "pip install -r requirements.txt --upgrade" after using "git pull"?
