### ISSUE TITLE
pgoapi.exceptions import NotLoggedInException  ISSUE

### ISSUE THREAD

**Issue by focamonca** [PokemonGoF/PokemonGo-Bot#3445]
### Expected Behavior

bot to works

### Actual Behavior

stuck on : 

```
Last login: Wed Aug 10 13:30:24 on ttys000
MacBook-Pro-di-Gianmaria:~ focamonca$ cd /Users/focamonca/PokemonGo-Bot
MacBook-Pro-di-Gianmaria:PokemonGo-Bot focamonca$ python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions
MacBook-Pro-di-Gianmaria:PokemonGo-Bot focamonca$ 
```

### Your config.json (remove your credentials and any other private info)
```
{
    "auth_service": "google",
    "username": "@gmail.com",
    "password": "",
    "location": "39.4079661,-0.5019423",
    "gmapkey": "",
    "libencrypt_location": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": true
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "FollowCluster",
        "config": {
            "radius": 50,
            "lured": true
        }
      }
    ],
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}

```

### Steps to Reproduce

```
Last login: Wed Aug 10 13:30:24 on ttys000
MacBook-Pro-di-Gianmaria:~ focamonca$ **cd /Users/focamonca/PokemonGo-Bot**
MacBook-Pro-di-Gianmaria:PokemonGo-Bot focamonca$ **python pokecli.py**
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions
MacBook-Pro-di-Gianmaria:PokemonGo-Bot focamonca$ 
```

### Other Information
OS: el ca[ital 10.11.6
Git Commit: 
```
MacBook-Pro-di-Gianmaria:~ focamonca$ git log -n 1 --pretty=format:"%H"
fatal: Not a git repository (or any of the parent directories): .git
```

Python Version:  Python 2.7.12

**Comment by focamonca** [comment]
solved
