### ISSUE TITLE
Bot suddenly stops after 30 minutes

### ISSUE THREAD

**Issue by merkon** [PokemonGoF/PokemonGo-Bot#3453]
Does anyone else have this problem?

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file __init__.py, line 547

**Comment by Nik0lashka** [comment]
@merkon use search or just check #3406

**Comment by merkon** [comment]
it says that I'm searching too often and should take a rest, i only have 1 bot account in my ip.

**Comment by Ph4i1ur3** [comment]
Are you on the latest dev version?

**Comment by adeshinichi** [comment]
Same here, using centos 7 everything work find until 30min and suddendly stuck.... Pressed ctrl+c result of invalid token and logout.... Wait 900 sec then....
