### ISSUE TITLE
error starting

### ISSUE THREAD

**Issue by vinay-ellore** [PokemonGoF/PokemonGo-Bot#3454]
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-10 17:56:14,085 [sentry.errors.uncaught] [ERROR] [u'NoPlayerPositionSetException', u'  File "pokecli.py", line 521, in <module>', u'  File "pokecli.py", line 137, in main', u'  File "pokecli.py", line 146, in report_summary', u'  File "pokemongo_bot/metrics.py", line 76, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 90, in call', u'  File "pokemongo_bot/api_wrapper.py", line 54, in can_call']

**Comment by Slayslot** [comment]
A little different, but facing the same problem
```bash
2016-08-10 18:24:44,286 [PokemonGoBot] [INFO] 
2016-08-10 18:25:02,634 [PokemonGoBot] [INFO] [bot_start] Starting bot...
2016-08-10 18:25:14,499 [CollectLevelUpReward] [INFO] [level_up_reward] Received level up reward: []
2016-08-10 18:25:14,501 [IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 4.56 km
2016-08-10 18:25:32,628 [       cli] [INFO] 
2016-08-10 18:25:32,629 [       cli] [INFO] Ran for 0:01:13
2016-08-10 18:25:32,630 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-10 18:25:32,630 [       cli] [INFO] Travelled 0.00km
2016-08-10 18:25:32,630 [       cli] [INFO] Visited 0 stops
2016-08-10 18:25:32,630 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-10 18:25:32,630 [       cli] [INFO] Threw 0 pokeballs
2016-08-10 18:25:32,631 [       cli] [INFO] Earned 0 Stardust
2016-08-10 18:25:32,631 [       cli] [INFO] 
2016-08-10 18:25:32,631 [       cli] [INFO] Highest CP Pokemon: 
2016-08-10 18:25:32,631 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 521, in <module>
    main()
  File "pokecli.py", line 95, in main
    bot.tick()
  File "/home/slayslot/github/pokbot/nikhil/PokemonGo-Bot/pokemongo_bot/__init__.py", line 453, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/slayslot/github/pokbot/nikhil/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_map_pokemon.py", line 258, in work
    if self.config['snipe_high_prio_only']:
KeyError: 'snipe_high_prio_only'
2016-08-10 18:25:32,652 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/slayslot/github/pokbot/nikhil/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/slayslot/github/pokbot/nikhil/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/slayslot/github/pokbot/nikhil/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/slayslot/github/pokbot/nikhil/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/slayslot/github/pokbot/nikhil/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/slayslot/github/pokbot/nikhil/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/slayslot/github/pokbot/nikhil/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/slayslot/github/pokbot/nikhil/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-10 18:25:32,654 [sentry.errors.uncaught] [ERROR] [u"KeyError: 'snipe_high_prio_only'", u'  File "pokecli.py", line 521, in <module>', u'  File "pokecli.py", line 95, in main', u'  File "pokemongo_bot/__init__.py", line 453, in tick', u'  File "pokemongo_bot/cell_workers/move_to_map_pokemon.py", line 258, in work']
Press any button or wait 20 seconds.Wed Aug 10 18:25:36 IST 2016Pokebot Stopped.
`

**Comment by Ph4i1ur3** [comment]
These seem like two separate issues.

**Comment by Slayslot** [comment]
Should I open a new issue then?

**Comment by Ph4i1ur3** [comment]
I'll defer you to #3466

**Comment by Ph4i1ur3** [comment]
As for the OP: I would recommend the latest dev build if you aren't and maybe try pip install -r requirements.txt --upgrade

**Comment by k4n30** [comment]
@vinay-ellore your issue is related to your player position not being set, can you post your config with username, password, gmapkey removed

@Slayslot your issue is related to your sniping config, check #3609 . Update your config with the new options here
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/configs/config.json.map.example#L65
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/configs/config.json.map.example#L66

**Comment by Slayslot** [comment]
Actually, shifting to dev branch fixed this for me.
