### ISSUE TITLE
Can't start the bot

### ISSUE THREAD

**Issue by merkon** [PokemonGoF/PokemonGo-Bot#3462]
When i type python pokecli.py -c config.json and then enter it tries to login and then this happens and the bot can't start:

(pokemonEnv) konstaninossmbp:pokemongo-bot-master merkon$ python pokecli.py -c config.all
2016-08-10 16:19:41,855 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-10 16:19:41,856 [       cli] [INFO] No config argument specified, checking for /configs/config.json
2016-08-10 16:19:41,857 [       cli] [INFO] Configuration initialized
2016-08-10 16:19:41,857 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more logrmation:
2016-08-10 16:19:41,857 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-10 16:19:41,924 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-10 16:19:42,631 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-10 16:19:42,631 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-10 16:19:42,632 [PokemonGoBot] [INFO] [location_found] Location found: 40.7679709,-73.9725929,17 (40.7679709, -73.9725929, 0.0)
2016-08-10 16:19:42,632 [PokemonGoBot] [INFO] [position_update] Now at (40.7679709, -73.9725929, 0)
2016-08-10 16:19:42,632 [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemongo_bot/api_wrapper.py", line 106, in call
    result = self._call()
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemongo_bot/api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemonEnv/src/pgoapi/pgoapi/pgoapi.py", line 219, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemonEnv/src/pgoapi/pgoapi/rpc_api.py", line 125, in request
    request_proto = self._build_main_request(subrequests, player_position)
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemonEnv/src/pgoapi/pgoapi/rpc_api.py", line 215, in _build_main_request
    request.auth_info.token.contents = self._auth_provider.get_access_token()
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 669, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 176, in CheckValue
    raise TypeError(message)
TypeError: None has type <type 'NoneType'>, but expected one of: (<type 'str'>, <type 'unicode'>)
2016-08-10 16:19:45,144 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 891, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-10 16:19:45,145 [sentry.errors.uncaught] [ERROR] [u"TypeError: None has type <type 'NoneType'>, but expected one of: (<type 'str'>, <type 'unicode'>)", u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", line 127, in main', u'  File "pokecli.py", line 136, in report_summary', u'  File "pokemongo_bot/metrics.py", line 76, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 106, in call', u'  File "pokemongo_bot/api_wrapper.py", line 63, in _call', u'  File "pgoapi/pgoapi.py", line 219, in call', u'  File "pgoapi/rpc_api.py", line 125, in request', u'  File "pgoapi/rpc_api.py", line 215, in _build_main_request', u'  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 669, in field_setter', u'  File "/Users/merkon/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 176, in CheckValue']

What's going on? Running only one account in the ip.

**Comment by Ph4i1ur3** [comment]
I would recommend using the latest dev branch, it would appear you are on the master branch. (Also the flag for config is -cf)

**Comment by merkon** [comment]
Because i don't know what to write in the terminal (I'm in mac OS X), can you help me with the commands for the dev?

**Comment by Ph4i1ur3** [comment]
git clone -b dev https://github.com/PokemonGoF/PokemonGo-Bot

**Comment by merkon** [comment]
I have downloaded the dev files, but what are the commands for the terminal in mac OS X?

**Comment by Ph4i1ur3** [comment]
Check out the wiki, it should have a guide for OSX
