### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1

### ISSUE THREAD

**Issue by igoldny** [PokemonGoF/PokemonGo-Bot#3466]
Hey,

i just got this error while running for some time

`
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-10 16:29:29,642 [sentry.errors.uncaught] [ERROR] [u'ConnectionError: (\'Connection aborted.\', BadStatusLine("\'\'",))', u'  File "pokecli.py", line 530, in <module>', u'  File "pokecli.py", line 96, in main', u'  File "pokemongo_bot/__init__.py", line 450, in tick', u'  File "pokemongo_bot/health_record/bot_event.py", line 65, in heartbeat', u'  File "pokemongo_bot/health_record/bot_event.py", line 78, in track_url', u'  File "requests/api.py", line 111, in post', u'  File "requests/api.py", line 57, in request', u'  File "requests/sessions.py", line 475, in request', u'  File "requests/sessions.py", line 585, in send', u'  File "requests/adapters.py", line 453, in send']
`

**Comment by Ph4i1ur3** [comment]
Are you running the latest dev version?

**Comment by Lordedi** [comment]
yes same just happened

**Comment by Ph4i1ur3** [comment]
My guess would be an API error, how should I go about reproducing the effect?

**Comment by igoldny** [comment]
yes, latest dev branch.
where is the logs file? i can share it with you or anything else i can do?

**Comment by Ph4i1ur3** [comment]
Not sure of the bot outputs logs by default, truthfully. Id recommend setting "health_record": false, in your config, that may solve your issue

**Comment by igoldny** [comment]
ok, i will try, thnx.
it's not urgent bug because after restart it keep on running just thought it might be good to have a record of it.

**Comment by emilhe** [comment]
I get the same error. Sometimes the bot can go on for 10 hours before the bug occurs, some times it's just a matter of minutes.

**Comment by igoldny** [comment]
@Lordedi attach your log

**Comment by Lordedi** [comment]
[17:28:34] Going to a new place, ignoring cached location.
[17:28:34] Login procedure started.Traceback (most recent call last):
  File "pokecli.py", line 530, in <module>
    main()
  File "pokecli.py", line 138, in main
    report_summary(bot)
  File "pokecli.py", line 147, in report_summary
    metrics.capture_stats()
  File "/home/raviss_e/PokemonGo-Bot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/home/raviss_e/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 90, in call
    if not self.can_call():
  File "/home/raviss_e/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 58, in can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException

(I changed health_record: false)

**Comment by Lordedi** [comment]
no one has solved this issue ?

**Comment by Ph4i1ur3** [comment]
NotLoggedIn is usually called when you've entered some part of your login information wrong, or the server is abnormally busy

**Comment by Lordedi** [comment]
My login is good maybe server is busy.
Thank you to reply me mister

**Comment by Ph4i1ur3** [comment]
Also, just to be sure. You've used "pip install -r requirements.txt --upgrade" when you run new versions of the bot right? The --upgrade tag is important

**Comment by Lordedi** [comment]
Yes I did.

**Comment by GitPupper** [comment]
This happens when the servers are busy and your bot disconnects. Try using my macOS script 
[PokeBot.zip](https://github.com/PokemonGoF/PokemonGo-Bot/files/411859/PokeBot.zip). It's code taken from the Wiki, edited, and made to restart the bot after 5 seconds if it crashes. You can edit the script using TextEdit or Atom (basically, anything that can edit text/scripts. But ScriptEditor does not work). If you want one on Windows just copy/paste that into a .txt and save it as a .bat

**Comment by Lordedi** [comment]
ok thanks I will try this ;)

**Comment by Lordedi** [comment]
Still doesn't work

**Comment by k4n30** [comment]
OP is due to a connection error, not related to the bot
