### ISSUE TITLE
Does not require parameter ball

### ISSUE THREAD

**Issue by icecubeice** [PokemonGoF/PokemonGo-Bot#3471]
Config is valid, running on dev, no other issues

### Expected Behavior
Catch pokemon

### Actual Behavior
after throwing, error:

2016-08-10 22:23:24,648 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Kr                                                                                                                                                      abby appeared! [CP 129] [Potential 0.98] [S/A/D 14/15/15]
2016-08-10 22:23:26,835 [PokemonCatchWorker] [INFO] [vip_pokemon] This is a VIP pokemon. Catch!!!
2016-08-10 22:23:28,111 [PokemonCatchWorker] [INFO] [threw_berry] Threw a Razz Berry! Catch rate now: 93.43
2016-08-10 22:23:28,707 [       cli] [INFO]
2016-08-10 22:23:28,707 [       cli] [INFO] Ran for 0:00:26
2016-08-10 22:23:28,707 [       cli] [INFO] Total XP Earned: 50  Average: 6929.47/h
2016-08-10 22:23:28,709 [       cli] [INFO] Travelled 0.00km
2016-08-10 22:23:28,709 [       cli] [INFO] Visited 1 stops
2016-08-10 22:23:28,709 [       cli] [INFO] Encountered 1 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-10 22:23:28,709 [       cli] [INFO] Threw 0 pokeballs
2016-08-10 22:23:28,709 [       cli] [INFO] Earned 0 Stardust
2016-08-10 22:23:28,709 [       cli] [INFO]
2016-08-10 22:23:28,709 [       cli] [INFO] Highest CP Pokemon:
2016-08-10 22:23:28,709 [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 503, in <module>
    main()
  File "pokecli.py", line 89, in main
    bot.tick()
  File "C:\Users\Anthony\downloads\pokemongo-bot\pokemongo_bot\__init__.py", line 450, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "C:\Users\Anthony\downloads\pokemongo-bot\pokemongo_bot\cell_workers\catch_visible_pokemon.py", line 37, in work
    self.catch_pokemon(pokemon)
  File "C:\Users\Anthony\downloads\pokemongo-bot\pokemongo_bot\cell_workers\catch_visible_pokemon.py", line 63, in catch_pokemon
    return_value = worker.work()
  File "C:\Users\Anthony\downloads\pokemongo-bot\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 301, in work
    'count_left': items_stock[pokeball]
  File "C:\Users\Anthony\downloads\pokemongo-bot\pokemongo_bot\base_task.py", line 39, in emit_event
    data=data
  File "C:\Users\Anthony\downloads\pokemongo-bot\pokemongo_bot\event_manager.py", line 59, in emit
    raise EventMalformedException("Event %s does not require parameter %s" % (event, k))
pokemongo_bot.event_manager.EventMalformedException: Event threw_pokeball does not require parameter pokeball

### Other Information
OS: Windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by Ph4i1ur3** [comment]
Duplicate issue. #3423

**Comment by icecubeice** [comment]
sorry didn't find it though
