### ISSUE TITLE
Bot random crash

### ISSUE THREAD

**Issue by koltziver** [PokemonGoF/PokemonGo-Bot#348]
Great work guys!

Bot randomly crashes can run for an hour or just a few mins and get a crash, the run command im using is:

pokecli.py -a google -u xxx -p xxx  -l "10.39868000, -75.55679500" -w 4 -m all -c 600 --maxstep 100

Traceback (most recent call last):
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot-dev\pokecli.py", line 121, in <module>
    main()
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot-dev\pokecli.py", line 114, in main
    bot.take_step()
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 31, in take_step
    self.stepper.take_step()
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot-dev\pokemongo_bot\stepper.py", line 56, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot-dev\pokemongo_bot\stepper.py", line 97, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 56, in work_on_cell
    hack_chain = worker.work()
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot-dev\pokemongo_bot\cell_workers\seen_fort_worker.py", line 38, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot-dev\pokemongo_bot\stepper.py", line 75, in _walk_to
    self._work_at_position(i2f(self.api._position_lat), i2f(self.api._position_lng), alt, False)
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot-dev\pokemongo_bot\stepper.py", line 89, in _work_at_position
    json.dump({'lat': lat, 'lng': lng,'cells':response_dict['responses']['GET_MAP_OBJECTS']['map_cells']}, outfile)
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by gagas3113** [comment]
same issue

**Comment by IcyZKunGz** [comment]
same here too. mine is

> python pokecli.py -a google -u xxxx@gmail.com -p xxxx -l "-33.8663, 151.20929" -m "all" --maxstep 6 -c 400 -w 4

Error code

> File "pokecli.py", line 107, in <module>
    main()
  File "pokecli.py", line 104, in main
    bot.take_step()
  File "/Users/Arsapol/Downloads/PokemonGo-Bot-dev/pokemongo_bot/__init__.py", line 31, in take_step
    self.stepper.take_step()
  File "/Users/Arsapol/Downloads/PokemonGo-Bot-dev/pokemongo_bot/stepper.py", line 58, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/Users/Arsapol/Downloads/PokemonGo-Bot-dev/pokemongo_bot/stepper.py", line 100, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/Users/Arsapol/Downloads/PokemonGo-Bot-dev/pokemongo_bot/__init__.py", line 52, in work_on_cell
    hack_chain = worker.work()
  File "/Users/Arsapol/Downloads/PokemonGo-Bot-dev/pokemongo_bot/cell_workers/seen_fort_worker.py", line 45, in work
    fort_details = response_dict['responses']['FORT_DETAILS']
KeyError: 'FORT_DETAILS'

**Comment by ludicures** [comment]
I have encountered the same error as IcyZKunGz.

dev/pokemongo_bot/cell_workers/seen_fort_worker.py", line 45, in work
fort_details = response_dict['responses']['FORT_DETAILS']
KeyError: 'FORT_DETAILS'

I have added a little bit of debug code and the output of response_dict['responses'] when FORT_DETAILS is not set looks like the following. I hope this helps.

{
  "status_code": 102, 
  "responses": {}
}

**Comment by surfaace** [comment]
Please clarify if issue still persists for you with latest dev

**Comment by surfaace** [comment]
#338 confirmed fixed
