### ISSUE TITLE
Error using snipping feature

### ISSUE THREAD

**Issue by ocoot** [PokemonGoF/PokemonGo-Bot#3494]
what this is?

[00:35:36] Updated PokemonGo-Map to 37.791534, -122.389811
[00:35:38] Moving towards pokestop Party Octopus of Ursidae Animal Family against Skateboarding. - 0.05km (attraction of lure 0.05km)2016-08-11 00:35:39,567 [       cli] [INFO] 
2016-08-11 00:35:39,568 [       cli] [INFO] Ran for 0:00:28
2016-08-11 00:35:39,568 [       cli] [INFO] Total XP Earned: 25  Average: 3244.92/h
2016-08-11 00:35:39,568 [       cli] [INFO] Travelled 0.00km
2016-08-11 00:35:39,568 [       cli] [INFO] Visited 0 stops
2016-08-11 00:35:39,568 [       cli] [INFO] Encountered 1 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-11 00:35:39,569 [       cli] [INFO] Threw 1 pokeball
2016-08-11 00:35:39,569 [       cli] [INFO] Earned 0 Stardust
2016-08-11 00:35:39,569 [       cli] [INFO] 
2016-08-11 00:35:39,569 [       cli] [INFO] Highest CP Pokemon: 
2016-08-11 00:35:39,569 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 530, in <module>
    main()
  File "pokecli.py", line 96, in main
    bot.tick()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 472, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort.py", line 80, in work
    lng
  File "/root/PokemonGo-Bot/pokemongo_bot/step_walker.py", line 28, in __init__
    self.steps = (self.dist + 0.0) / (speed + 0.0)
ZeroDivisionError: float division by zero
2016-08-11 00:35:39,612 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-11 00:35:39,614 [sentry.errors.uncaught] [ERROR] [u'ZeroDivisionError: float division by zero', u'  File "pokecli.py", line 530, in <module>', u'  File "pokecli.py", line 96, in main', u'  File "pokemongo_bot/__init__.py", line 472, in tick', u'  File "pokemongo_bot/cell_workers/move_to_fort.py", line 80, in work', u'  File "pokemongo_bot/step_walker.py", line 28, in __init__']
run.sh: 18: read: Illegal option -s
Thu Aug 11 00:35:39 WIB 2016 Pokebot Stopped

**Comment by ocoot** [comment]
i dont know how to use sniping feature. why always give me errors when to try. here is no guide how to use it. installation step or anything. btw, i'm already success to install pokemon go map. and how to implement to the bot. no one can help me step by step. lol :/

**Comment by Ph4i1ur3** [comment]
I'm working through it in my spare time, patience is a virtue

**Comment by Ph4i1ur3** [comment]
I'm assuming you're using the most recent versions of both repos? also: please post your config.json

**Comment by ocoot** [comment]
this is my config

`{
    "auth_service": "google",
    "username": "xxx@gmail.com",
    "password": "xxx",
    "location": "37.791534, -122.389811",
    "gmapkey": "GOOGLE_MAPS_API_KEY",
    "libencrypt_location": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "evolve_all": "NONE",
          "evolve_cp_min": 300,
          "evolve_speed": 20,
          "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToMapPokemon",
        "config": {
          "address": "http://localhost:5000",
          "max_distance": 500,
          "min_time": 60,
          "min_ball": 50,
          "prioritize_vips": true,
          "snipe": true,
          "snipe_high_prio_only": true,
          "snipe_high_prio_threshold": 400,
          "update_map": true,
          "mode": "priority",
          "map_path": "raw_data",
          "catch": {
            "==========Legendaries==========": 0,
            "Aerodactyl": 1500,
            "Snorlax": 1500,
            "Dragonite": 1500,
            "Charizard": 1500,
	    "Arcanine": 1500,
	    "Vaporeon": 1500,
	    "Muk": 1500,
	    "Flareon": 1500,
	    "Slowbro": 1500,
	    "Venusaur": 1500,
	    "Blastoise": 1500,
            "Gyarados": 1500,
            "Exeggutor": 1500,
            "Dragonair": 1500,
            "Lapras": 1500
          }
        }
      },
      {
        "type": "MoveToFort"
      },
      {
        "type": "FollowSpiral"
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 0,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}
`

**Comment by ocoot** [comment]
@Ph4i1ur3

**Comment by Ph4i1ur3** [comment]
Your "walk": is set to 0. This is a no-no. I'd recommend 4.16

**Comment by ocoot** [comment]
@Ph4i1ur3 when i try to change the location on pokemon go map, it didn't load. it just stuck on the first place. its like hard to move different location :|

**Comment by k4n30** [comment]
it doesnt move because ur walk speed is set to 0 (i.e 0 km/h), make this any number above 0.00 and your problem should disappear because the crash is due to:
`self.steps = (self.dist + 0.0) / (speed + 0.0)
ZeroDivisionError: float division by zero`
