### ISSUE TITLE
Handle Soft Ban error

### ISSUE THREAD

**Issue by crazyonerob** [PokemonGoF/PokemonGo-Bot#3504]
I am having a crash happen when i run pokecli.py right now. This was working this morning but then I stopped the bot and it started happening. So i updated to the most recent. I have tried it both on Dev and Master.
### Expected Behavior

Softban to be fixed
### Actual Behavior
Crashed with error 
here is a the last log for this 

> (PokemonGo-Bot) rob:~/PokemonGo-Bot$ python pokecli.py
2016-08-10 11:53:55,281 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-10 11:53:55,287 [       cli] [INFO] No config argument specified, checking for /configs/config.json
2016-08-10 11:53:55,296 [       cli] [INFO] Configuration initialized
(22854) wsgi starting up on http://0.0.0.0:4000
2016-08-10 11:53:55,332 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): 0.0.0.0
2016-08-10 11:53:55,362 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): 0.0.0.0
2016-08-10 11:53:55,391 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-10 11:53:55,393 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-10 11:53:55,394 [PokemonGoBot] [INFO] [location_found] Location found:  (redacted)
2016-08-10 11:53:55,396 [PokemonGoBot] [INFO] [position_update] Now at (redacted)
2016-08-10 11:53:55,400 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-10 11:53:56,730 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-10 11:53:58,391 [PokemonGoBot] [INFO]
2016-08-10 11:53:58,392 [PokemonGoBot] [INFO] --- redacted ---
2016-08-10 11:53:58,393 [PokemonGoBot] [INFO] Level: redacted
2016-08-10 11:53:58,394 [PokemonGoBot] [INFO] Pokemon Captured: redacted
2016-08-10 11:53:58,396 [PokemonGoBot] [INFO] Pokemon Bag: redacted
2016-08-10 11:53:58,398 [PokemonGoBot] [INFO] Items: redacted
2016-08-10 11:53:58,398 [PokemonGoBot] [INFO] Stardust:redacted
2016-08-10 11:53:58,399 [PokemonGoBot] [INFO] PokeBalls: redacted
2016-08-10 11:53:58,399 [PokemonGoBot] [INFO] RazzBerries: redacted
2016-08-10 11:53:58,400 [PokemonGoBot] [INFO] LuckyEgg: redacted
2016-08-10 11:53:58,400 [PokemonGoBot] [INFO] Potion: redacted
2016-08-10 11:53:58,401 [PokemonGoBot] [INFO] Incense: redacted
2016-08-10 11:53:58,401 [PokemonGoBot] [INFO] Revive: redacted
2016-08-10 11:53:58,401 [PokemonGoBot] [INFO]
2016-08-10 11:53:58,402 [PokemonGoBot] [INFO] Found encrypt.so! Platform: linux2 Encrypt.so directory: /home/rob/PokemonGo-Bot
2016-08-10 11:53:58,402 [PokemonGoBot] [INFO]
2016-08-10 11:53:59,691 [PokemonGoBot] [INFO] [bot_start] Starting bot...
2016-08-10 11:54:00,304 [CollectLevelUpReward] [INFO] [level_up_reward] Received level up reward: []
2016-08-10 11:54:00,308 [IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 3.25 km
2016-08-10 11:54:02,999 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop redacted - 0.05km
2016-08-10 11:54:05,319 [  SpinFort] [INFO] [pokestop_empty] Found nothing in pokestop redacted.
2016-08-10 11:54:05,321 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-10 11:54:05,323 [  SpinFort] [INFO] [softban] Probably got softban.
2016-08-10 11:54:06,742 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop redacted - 0.20km
2016-08-10 11:54:08,540 [       cli] [INFO]
2016-08-10 11:54:08,540 [       cli] [INFO] Ran for 0:00:13
2016-08-10 11:54:08,541 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-10 11:54:08,541 [       cli] [INFO] Travelled 0.00km
2016-08-10 11:54:08,542 [       cli] [INFO] Visited 0 stops
2016-08-10 11:54:08,542 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-10 11:54:08,542 [       cli] [INFO] Threw 0 pokeballs
2016-08-10 11:54:08,543 [       cli] [INFO] Earned 0 Stardust
2016-08-10 11:54:08,543 [       cli] [INFO]
2016-08-10 11:54:08,544 [       cli] [INFO] Highest CP Pokemon:
2016-08-10 11:54:08,544 [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 521, in <module>
    main()
  File "pokecli.py", line 95, in main
    bot.tick()
  File "/home/rob/PokemonGo-Bot/pokemongo_bot/__init__.py", line 453, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/rob/PokemonGo-Bot/pokemongo_bot/cell_workers/handle_soft_ban.py", line 32, in work
    MoveToFort(self.bot, config=None).work()
  File "/home/rob/PokemonGo-Bot/pokemongo_bot/base_task.py", line 12, in __init__
    self.initialize()
  File "/home/rob/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort.py", line 16, in initialize
    self.lure_attraction = self.config.get("lure_attraction", True)
AttributeError: 'NoneType' object has no attribute 'get'

### Your config.json (remove your credentials and any other private info)

> {
    "auth_service": "google",
    "username": "redacted",
    "password": "redacted",
    "location": "redacted",
    "gmapkey": "redacted",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "all",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.9,
            "logic": "and",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 50 },
            "Greatball":       { "keep" : 90 },
            "Ultraball":       { "keep" : 60 },
            "Potion":         { "keep" : 20 },
            "Super Potion":   { "keep" : 10 },
            "Hyper Potion":   { "keep" : 20 },
            "Revive":         { "keep" : 20 },
            "Razz Berry":     { "keep" : 40 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket": {
   "start_embedded_server": true,
   "server_url": "0.0.0.0:4000",
   "remote_control": true
    },
    "walk": 14.5,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": false,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true },
      "Pidgey":{"catch_above_iv": 9.6},
      "Rattata":{"catch_above_iv": 9.6},
      "Spearow":{"catch_above_iv": 9.6},
      "Weedle":{"catch_above_iv": 9.6},
      "Zubat":{"catch_above_iv": 9.6},
      "Caterpie":{"catch_above_iv": 9.6},
      "Venonat":{"catch_above_iv": 9.6},
      "Meowth":{"catch_above_iv": 9},
      "Magnemite":{"catch_above_iv": 9},
      "Goldeen":{"catch_above_iv": 9},
      "Bellsprout":{"catch_above_iv": 9},
      "Abra":{"catch_above_iv": 9},
      "Doduo":{"catch_above_iv": 9},
      "Ekans":{"catch_above_iv": 9},
      "Nidoran":{"catch_above_iv": 9},
      "Oddish":{"catch_above_iv": 9},
      "Paras":{"catch_above_iv": 9}
    },
    "release": {
          "// any": {"keep_best_cp": 2, "keep_best_iv": 2},
          "Bulbasaur": {"keep_best_iv": 1},
          "Ivysaur": {"keep_best_iv": 1},
          "Venusaur": {"keep_best_iv": 1},
          "Charmander": {"keep_best_iv": 1},
          "Charmeleon": {"keep_best_iv": 1},
          "Charizard": {"keep_best_iv": 1},
          "Squirtle": {"keep_best_iv": 1},
          "Wartortle": {"keep_best_iv": 1},
          "Blastoise": {"keep_best_iv": 1},
          "Caterpie": {"keep_best_iv": 1},
          "Metapod": {"keep_best_iv": 1},
          "Butterfree": {"keep_best_iv": 1},
          "Weedle": {"keep_best_iv": 1},
          "Kakuna": {"keep_best_iv": 1},
          "Beedrill": {"keep_best_iv": 1},
          "Pidgey": {"keep_best_iv": 1},
          "Pidgeotto": {"keep_best_iv": 1},
          "Pidgeot": {"keep_best_iv": 1},
          "Rattata": {"keep_best_iv": 1},
          "Raticate": {"keep_best_iv": 1},
          "Spearow": {"keep_best_iv": 1},
          "Fearow": {"keep_best_iv": 1},
          "Ekans": {"keep_best_iv": 1},
          "Arbok": {"keep_best_iv": 1},
          "Pikachu": {"keep_best_iv": 1},
          "Raichu": {"keep_best_iv": 1},
          "Sandshrew": {"keep_best_iv": 1},
          "Sandslash": {"keep_best_iv": 1},
          "Nidoran F": {"keep_best_iv": 1},
          "Nidorina": {"keep_best_iv": 1},
          "Nidoqueen": {"keep_best_iv": 1},
          "Nidoran M": {"keep_best_iv": 1},
          "Nidorino": {"keep_best_iv": 1},
          "Nidoking": {"keep_best_iv": 1},
          "Clefairy": {"keep_best_iv": 1},
          "Clefable": {"keep_best_iv": 1},
          "Vulpix": {"keep_best_iv": 1},
          "Ninetales": {"keep_best_iv": 1},
          "Jigglypuff": {"keep_best_iv": 1},
          "Wigglytuff": {"keep_best_iv": 1},
          "Zubat": {"keep_best_iv": 1},
          "Golbat": {"keep_best_iv": 1},
          "Oddish": {"keep_best_iv": 1},
          "Gloom": {"keep_best_iv": 1},
          "Vileplume": {"keep_best_iv": 1},
          "Paras": {"keep_best_iv": 1},
          "Parasect": {"keep_best_iv": 1},
          "Venonat": {"keep_best_iv": 1},
          "Venomoth": {"keep_best_iv": 1},
          "Diglett": {"keep_best_iv": 1},
          "Dugtrio": {"keep_best_iv": 1},
          "Meowth": {"keep_best_iv": 1},
          "Persian": {"keep_best_iv": 1},
          "Psyduck": {"keep_best_iv": 1},
          "Golduck": {"keep_best_iv": 1},
          "Mankey": {"keep_best_iv": 1},
          "Primeape": {"keep_best_iv": 1},
          "Growlithe": {"keep_best_iv": 1},
          "Arcanine": {"keep_best_iv": 1},
          "Poliwag": {"keep_best_iv": 1},
          "Poliwhirl": {"keep_best_iv": 1},
          "Poliwrath": {"keep_best_iv": 1},
          "Abra": {"keep_best_iv": 1},
          "Kadabra": {"keep_best_iv": 1},
          "Alakazam": {"keep_best_iv": 1},
          "Machop": {"keep_best_iv": 1},
          "Machoke": {"keep_best_iv": 1},
          "Machamp": {"keep_best_iv": 1},
          "Bellsprout": {"keep_best_iv": 1},
          "Weepinbell": {"keep_best_iv": 1},
          "Victreebel": {"keep_best_iv": 1},
          "Tentacool": {"keep_best_iv": 1},
          "Tentacruel": {"keep_best_iv": 1},
          "Geodude": {"keep_best_iv": 1},
          "Graveler": {"keep_best_iv": 1},
          "Golem": {"keep_best_iv": 1},
          "Ponyta": {"keep_best_iv": 1},
          "Rapidash": {"keep_best_iv": 1},
          "Slowpoke": {"keep_best_iv": 1},
          "Slowbro": {"keep_best_iv": 1},
          "Magnemite": {"keep_best_iv": 1},
          "Magneton": {"keep_best_iv": 1},
          "Farfetch’d": {"keep_best_iv": 1},
          "Doduo": {"keep_best_iv": 1},
          "Dodrio": {"keep_best_iv": 1},
          "Seel": {"keep_best_iv": 1},
          "Dewgong": {"keep_best_iv": 1},
          "Grimer": {"keep_best_iv": 1},
          "Muk": {"keep_best_iv": 1},
          "Shellder": {"keep_best_iv": 1},
          "Cloyster": {"keep_best_iv": 1},
          "Gastly": {"keep_best_iv": 1},
          "Haunter": {"keep_best_iv": 1},
          "Gengar": {"keep_best_iv": 1},
          "Onix": {"keep_best_iv": 1},
          "Drowzee": {"keep_best_iv": 1},
          "Hypno": {"keep_best_iv": 1},
          "Krabby": {"keep_best_iv": 1},
          "Kingler": {"keep_best_iv": 1},
          "Voltorb": {"keep_best_iv": 1},
          "Electrode": {"keep_best_iv": 1},
          "Exeggcute": {"keep_best_iv": 1},
          "Exeggutor": {"keep_best_iv": 1},
          "Cubone": {"keep_best_iv": 1},
          "Marowak": {"keep_best_iv": 1},
          "Hitmonlee": {"keep_best_iv": 1},
          "Hitmonchan": {"keep_best_iv": 1},
          "Lickitung": {"keep_best_iv": 1},
          "Koffing": {"keep_best_iv": 1},
          "Weezing": {"keep_best_iv": 1},
          "Rhyhorn": {"keep_best_iv": 1},
          "Rhydon": {"keep_best_iv": 1},
          "Chansey": {"keep_best_iv": 1},
          "Tangela": {"keep_best_iv": 1},
          "Kangaskhan": {"keep_best_iv": 1},
          "Horsea": {"keep_best_iv": 1},
          "Seadra": {"keep_best_iv": 1},
          "Goldeen": {"keep_best_iv": 1},
          "Seaking": {"keep_best_iv": 1},
          "Staryu": {"keep_best_iv": 1},
          "Starmie": {"keep_best_iv": 1},
          "Mr.Mime": {"keep_best_iv": 1},
          "Scyther": {"keep_best_iv": 1},
          "Jynx": {"keep_best_iv": 1},
          "Electabuzz": {"keep_best_iv": 1},
          "Magmar": {"keep_best_iv": 1},
          "Pinsir": {"keep_best_iv": 1},
          "Tauros": {"keep_best_iv": 1},
          "Magikarp": {"keep_best_iv": 1},
          "Gyarados": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
          "Lapras": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
          "Ditto": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
          "Eevee": {"keep_best_iv": 2},
          "Vaporeon": {"keep_best_iv": 1},
          "Jolteon": {"keep_best_iv": 1},
          "Flareon": {"keep_best_iv": 1},
          "Porygon": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
          "Omanyte": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
          "Omastar": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
          "Kabuto": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
          "Kabutops": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
          "Aerodactyl": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
          "Snorlax": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
          "Articuno": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
          "Zapdos": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
          "Moltres": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
          "Dratini": {"keep_best_iv": 1},
          "Dragonair": {"keep_best_iv": 1},
          "Dragonite": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
          "Mewtwo": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
          "Mew": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1100, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},
        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Dratini": {},
        "Dragonair": {},
        "Evee":{},
        "Flareon": {}
    }
}

### Steps to Reproduce
Get softbanned and then have the step to Handle soft ban

### Other Information
OS: OSX and also tired Ubuntu 16.04
Git Commit: 63f777bac0c8cdc75d07f9ef491ca8b900c0148a
Python Version: Python 2.7.10 on OSX and Python 2.7.12 on ubuntu 16.04

**Comment by lhung** [comment]
I'm running the latest dev build  9ae1b78 and softban is working for me.
```
[13:24:38] Possibly searching too often, take a rest.
[13:24:38] Probably got softban.
[13:24:38] Moving towards pokestop Shatin College - 0.17km
[13:24:38] {'distance_unit': '', 'distance': '', 'current_position': (22.39140778876808, 114.18929649920942), 'last_position': (22.391355520155365, 114.18932463922391)}
[13:24:40] Fixing softban.
[13:25:10] Spun fort 7a88fb25fae042e09ab9ffff9a93d2b2.16                                                                                                                                                                                     
[13:25:10] Softban should be fixed
```

By the way, is your "catch" config working? I think iv goes between 0 to 1.

**Comment by bigkraig** [comment]
it's because of this commit https://github.com/PokemonGoF/PokemonGo-Bot/commit/10589b0efdc2e31b3c478fd16df8c0f753be061b
