### ISSUE TITLE
IOError: [Errno 25] Inappropriate ioctl for device

### ISSUE THREAD

**Issue by caylorme** [PokemonGoF/PokemonGo-Bot#3508]
Running in a docker container based on the DockerFile:
```
Traceback (most recent call last):
  File "/usr/src/app/pokecli.py", line 530, in <module>
    main()
  File "/usr/src/app/pokecli.py", line 96, in main
    bot.tick()
  File "/usr/src/app/pokemongo_bot/__init__.py", line 472, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/usr/src/app/pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 45, in work
    'expiration_timestamp_ms': pokemon['expiration_timestamp_ms'],
  File "/usr/src/app/pokemongo_bot/base_task.py", line 28, in emit_event
    data=data
  File "/usr/src/app/pokemongo_bot/event_manager.py", line 65, in emit
    handler.handle_event(event, sender, level, formatted_msg, data)
  File "/usr/src/app/pokemongo_bot/event_handlers/colored_logging_handler.py", line 130, in handle_event
    terminal_width = self._terminal_width()
  File "/usr/src/app/pokemongo_bot/event_handlers/colored_logging_handler.py", line 171, in _terminal_width
    struct.pack(str('HHHH'), 0, 0, 0, 0)))
IOError: [Errno 25] Inappropriate ioctl for device
```
Git Commit: 9ae1b785f0836d8769d011626d2bc071ed338bff

This happens after encountering a pokemon.
Looks like it is now having a problem printing colors to the screen.

**Comment by atmdev** [comment]
I have the same problem when I run the bot. It occurs when running the bot in non-interactive mode (with nohup in my case) and it is not able to get the size of the terminal as there is none.

**Comment by caylorme** [comment]
to elaborate, I am also backgrounding my instance.

I run a custom script that will build the docker container and run it with a different entry point to start the webserver and bot at the same time while also binding the port for the web.

I'm able to see the standard output stream still until I exit, but the app should still continue to run in the background and have the logs accessible via docker.

**Comment by carlosbellino** [comment]
Set "logging_color": false

**Comment by k4n30** [comment]
@caylorme @carlosbellino @atmdev Try the latest version as logging_color has had some changes to it in the last 24 hours which may have fixed your problem

**Comment by engrjislam** [comment]
> I had the same problem.. Fixed by setting: "logging_color": false

How do you did that? Can you explain a bit more in detail?
