### ISSUE TITLE
Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range

### ISSUE THREAD

**Issue by jnguyen32** [PokemonGoF/PokemonGo-Bot#3522]
[root@localhost pogobot]# ./run.sh
2016-08-10 16:37:31,720 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-10 16:37:31,722 [       cli] [INFO] Configuration initialized
2016-08-10 16:37:31,722 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-10 16:37:31,722 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-10 16:37:31,729 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com

[16:37:31] Setting start location.2016-08-10 16:37:31,875 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.

[16:37:31] Location found: 48.8583736,2.2922926 (48.8583736, 2.2922926, 0.0)
[16:37:31] Now at (48.8583736, 2.2922926, 0)
[16:37:31] Login procedure started.Traceback (most recent call last):
  File "pokecli.py", line 530, in <module>
    main()
  File "pokecli.py", line 138, in main
    report_summary(bot)
  File "pokecli.py", line 147, in report_summary
    metrics.capture_stats()
  File "/mnt/hgfs/PhpstormProjects/pogobot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/mnt/hgfs/PhpstormProjects/pogobot/pokemongo_bot/api_wrapper.py", line 90, in call
    if not self.can_call():
  File "/mnt/hgfs/PhpstormProjects/pogobot/pokemongo_bot/api_wrapper.py", line 58, in can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
2016-08-10 16:37:32,032 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib64/python2.7/httplib.py", line 979, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 833, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-10 16:37:32,033 [sentry.errors.uncaught] [ERROR] [u'NotLoggedInException', u'  File "pokecli.py", line 530, in <module>', u'  File "pokecli.py", line 138, in main', u'  File "pokecli.py", line 147, in report_summary', u'  File "pokemongo_bot/metrics.py", line 76, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 90, in call', u'  File "pokemongo_bot/api_wrapper.py", line 58, in can_call']
Wed Aug 10 16:37:32 EDT 2016 Pokebot  Stopped.

**Comment by Ph4i1ur3** [comment]
Did this happen once, or every time you log the bot? Could you have a ip/soft ban?

**Comment by jnguyen32** [comment]
Every time. No ip/soft ban, I was able to log in via phone.

**Comment by Ph4i1ur3** [comment]
double check your credentials, that's an odd error

**Comment by ajaysinghi** [comment]
2016-08-11 03:01:38,615 [PokemonGoBot] [INFO] [bot_start] Starting bot...
2016-08-11 03:01:39,676 [CollectLevelUpReward] [INFO] [level_up_reward] Received level up reward: []
2016-08-11 03:01:39,676 [IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 0.62 km
2016-08-11 03:01:40,868 [       cli] [INFO]
2016-08-11 03:01:40,868 [       cli] [INFO] Ran for 0:00:18
2016-08-11 03:01:40,868 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-11 03:01:40,868 [       cli] [INFO] Travelled 0.00km
2016-08-11 03:01:40,884 [       cli] [INFO] Visited 0 stops
2016-08-11 03:01:40,884 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-11 03:01:40,884 [       cli] [INFO] Threw 0 pokeballs
2016-08-11 03:01:40,884 [       cli] [INFO] Earned 0 Stardust
2016-08-11 03:01:40,884 [       cli] [INFO]
2016-08-11 03:01:40,884 [       cli] [INFO] Highest CP Pokemon:
2016-08-11 03:01:40,884 [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 133, in main
    raise e
KeyError: u'And'
2016-08-11 03:01:40,898 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https:
0254/store/)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\raven\transport\threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "C:\Python27\lib\site-packages\raven\transport\http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 494, in open
    response = self._open(req, data)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 512, in _open
    '_open', req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python27\lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-11 03:01:40,914 [sentry.errors.uncaught] [ERROR] [u"KeyError: u'And'", u'  File "pokecli.py", line 502, in <module>', u'  File "pokecli.py", line 133, in main']

**Comment by jnguyen32** [comment]
Credentials and running latest on dev branch, yes.

**Comment by ajaysinghi** [comment]
I had the above mentioned issue, then i found that i did something wrong in config. Check your config once again and make sure it is up to date and correct

**Comment by fabke** [comment]
same problem 

config
```
{
   "username": "xxxxxxx",
    "password": "xxxxxxx",
    "location": "xxxxxxxxxxxxxxx",
    "gmapkey": "xxxxxxxxxxxxxxxxxx",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": true
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       	{ "keep" : 50 },
            "Greatball":       	{ "keep" : 70 },
            "Ultraball":       	{ "keep" : 90 },
            "Potion":       	{ "keep" : 0 },
            "Super Potion":	{ "keep" : 0 },
            "Hyper Potion":	{ "keep" : 30 },
            "Max Potion":	{ "keep" : 50 },
            "Revive":         	{ "keep" : 25 },
            "Razz Berry":     	{ "keep" : 30 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 37,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 150
    },
    "websocket_server": false,
    "walk": 3.5,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "// any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "any": {"keep_best_iv": 2,"keep_best_cp": 2},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}
```


Log 
2016-08-10 23:40:36,472 [       cli] [INFO] Ran for 0:02:13
2016-08-10 23:40:36,472 [       cli] [INFO] Total XP Earned: 410  Average: 11122.87/h
2016-08-10 23:40:36,473 [       cli] [INFO] Travelled 0.03km
2016-08-10 23:40:36,473 [       cli] [INFO] Visited 4 stops
2016-08-10 23:40:36,473 [       cli] [INFO] Encountered 1 pokemon, 1 caught, 1 released, 0 evolved, 0 never seen before
2016-08-10 23:40:36,473 [       cli] [INFO] Threw 1 pokeball
2016-08-10 23:40:36,473 [       cli] [INFO] Earned 100 Stardust
2016-08-10 23:40:36,473 [       cli] [INFO] 
2016-08-10 23:40:36,473 [       cli] [INFO] Highest CP Pokemon: Drowzee [CP: 41] [IV: 10/6/0] Potential: 0.36 
2016-08-10 23:40:36,473 [       cli] [INFO] Most Perfect Pokemon: Drowzee [CP: 41] [IV: 10/6/0] Potential: 0.36 
Traceback (most recent call last):
  File "./pokecli.py", line 530, in <module>
    main()
  File "./pokecli.py", line 96, in main
    bot.tick()
  File "/var/www/USERDIR/PokemonGo-Bot/pokemongo_bot/__init__.py", line 472, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/var/www/USERDIR/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 45, in work
    'expiration_timestamp_ms': pokemon['expiration_timestamp_ms'],
  File "/var/www/USERDIR/PokemonGo-Bot/pokemongo_bot/base_task.py", line 27, in emit_event
    data=data
  File "/var/www/USERDIR/PokemonGo-Bot/pokemongo_bot/event_manager.py", line 65, in emit
    handler.handle_event(event, sender, level, formatted_msg, data)
  File "/var/www/USERDIR/PokemonGo-Bot/pokemongo_bot/event_handlers/colored_logging_handler.py", line 130, in handle_event
    terminal_width = self._terminal_width()
  File "/var/www/USERDIR/PokemonGo-Bot/pokemongo_bot/event_handlers/colored_logging_handler.py", line 171, in _terminal_width
    struct.pack('HHHH', 0, 0, 0, 0)))
IOError: [Errno 25] Inappropriate ioctl for device
2016-08-10 23:40:36,479 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/var/www/USERDIR/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/var/www/USERDIR/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/var/www/USERDIR/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/var/www/USERDIR/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/var/www/USERDIR/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/var/www/USERDIR/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/var/www/USERDIR/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/var/www/USERDIR/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-10 23:40:36,480 [sentry.errors.uncaught] [ERROR] [u'IOError: [Errno 25] Inappropriate ioctl for device', u'  File "pokecli.py", line 530, in <module>', u'  File "pokecli.py", line 96, in main', u'  File "pokemongo_bot/__init__.py", line 472, in tick', u'  File "pokemongo_bot/cell_workers/catch_visible_pokemon.py", line 45, in work', u'  File "pokemongo_bot/base_task.py", line 27, in emit_event', u'  File "pokemongo_bot/event_manager.py", line 65, in emit', u'  File "pokemongo_bot/event_handlers/colored_logging_handler.py", line 130, in handle_event', u'  File "pokemongo_bot/event_handlers/colored_logging_handler.py", line 171, in _terminal_width']

**Comment by ajaysinghi** [comment]
Have you started getting this issue after getting the latest updated clone or you faced this issue before taking the latest updates?

**Comment by Ph4i1ur3** [comment]
What happens right before the crash? (Working from a phone so it's hard to trace using the error)

**Comment by jnguyen32** [comment]
Looks like my account is banned. I can log in with another PTC account. Logging in with the phone, I get 100% vanish rate & no poke stop rewards. Maybe the bot can display a message when this happens? I can't tell if it's a time-based ban or permanent yet. I do know it's not IP based.

**Comment by Tohrment** [comment]
I had this error pop a couple times today on 2 different accounts. I restarted the bots and they went on their way. I had this error pop up while running only 1 bot and while running 2. I updated to the latest dev branch today but have had this error before.

**Comment by emilhe** [comment]
The last task (that i can see in the log) that was executed prior to the crash was a [MoveToFort] task, or actually multiple of them. Below is the exact error that i get. 

```
Traceback (most recent call last):
  File "pokecli.py", line 521, in <module>
    main()
  File "pokecli.py", line 95, in main
    bot.tick()
  File "/home/emher/PycharmProjects/PokemonGo-Bot/pokemongo_bot/__init__.py", line 453, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/emher/PycharmProjects/PokemonGo-Bot/pokemongo_bot/cell_workers/transfer_pokemon.py", line 11, in work
    pokemon_groups = self._release_pokemon_get_groups()
  File "/home/emher/PycharmProjects/PokemonGo-Bot/pokemongo_bot/cell_workers/transfer_pokemon.py", line 79, in _release_pokemon_get_groups
    inventory_req = request.call()
  File "/home/emher/PycharmProjects/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 106, in call
    result = self._call()
  File "/home/emher/PycharmProjects/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "/home/emher/PycharmProjects/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/home/emher/PycharmProjects/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 127, in request
    response = self._make_rpc(endpoint, request_proto)
  File "/home/emher/PycharmProjects/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 115, in _make_rpc
    http_response = self._session.post(endpoint, data=request_proto_serialized, timeout=30)
  File "/home/emher/PycharmProjects/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/emher/PycharmProjects/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/emher/PycharmProjects/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/sessions.py", line 617, in send
    r.content
  File "/home/emher/PycharmProjects/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/home/emher/PycharmProjects/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/models.py", line 667, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))
2016-08-11 00:09:33,446 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/emher/PycharmProjects/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/emher/PycharmProjects/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/emher/PycharmProjects/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/emher/PycharmProjects/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/emher/PycharmProjects/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/emher/PycharmProjects/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/emher/PycharmProjects/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/emher/PycharmProjects/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-11 00:09:33,447 [sentry.errors.uncaught] [ERROR] [u'ChunkedEncodingError: ("Connection broken: error(104, \'Connection reset by peer\')", error(104, \'Connection reset by peer\'))', u'  File "pokecli.py", line 521, in <module>', u'  File "pokecli.py", line 95, in main', u'  File "pokemongo_bot/__init__.py", line 453, in tick', u'  File "pokemongo_bot/cell_workers/transfer_pokemon.py", line 11, in work', u'  File "pokemongo_bot/cell_workers/transfer_pokemon.py", line 79, in _release_pokemon_get_groups', u'  File "pokemongo_bot/api_wrapper.py", line 106, in call', u'  File "pokemongo_bot/api_wrapper.py", line 63, in _call', u'  File "pgoapi/pgoapi.py", line 220, in call', u'  File "pgoapi/rpc_api.py", line 127, in request', u'  File "pgoapi/rpc_api.py", line 115, in _make_rpc', u'  File "requests/sessions.py", line 518, in post', u'  File "requests/sessions.py", line 475, in request', u'  File "requests/sessions.py", line 617, in send', u'  File "requests/models.py", line 741, in content', u'  File "requests/models.py", line 667, in generate']

```

**Comment by takenek** [comment]
I think my IP address in OVH get a ban so i got same error... looks like You get ban too.

**Comment by medienoekonom** [comment]
well i tget the same error but i dont think its ban because its fresh account and first try

**Comment by k4n30** [comment]
There are others experiencing ban issues here:
#3682 - META Server busy or offline issues
#3308 - META Stuck between two forts / Moving to 2 forts at the same time / Constant Loop
#3700 - META Soft bans - Try again spins / Pokemon vanishing

These are not related to OPs issue though
