### ISSUE TITLE
Error starting after new dev update

### ISSUE THREAD

**Issue by JarodKY** [PokemonGoF/PokemonGo-Bot#3548]
### Expected Behavior
Start bot normally

### Actual Behavior
`Traceback (most recent call last):
  File "pokecli.py", line 530, in <module>
    main()
  File "pokecli.py", line 82, in main
    bot.start()
  File "/Users/XXX/PokemonGo-Bot/pokemongo_bot/__init__.py", line 86, in start
    self._setup_api()
  File "/Users/XXX/PokemonGo-Bot/pokemongo_bot/__init__.py", line 698, in _setup_api
    self.update_inventory()
  File "/Users/XXX/PokemonGo-Bot/pokemongo_bot/__init__.py", line 796, in update_inventory
    init_inventory(self)
  File "/Users/XXX/PokemonGo-Bot/pokemongo_bot/inventory.py", line 799, in init_inventory
    _inventory = Inventory(bot)
  File "/Users/XXX/PokemonGo-Bot/pokemongo_bot/inventory.py", line 741, in __init__
    self.refresh()
  File "/Users/XXX/PokemonGo-Bot/pokemongo_bot/inventory.py", line 749, in refresh
    i.refresh(inventory)
  File "/Users/XXX/PokemonGo-Bot/pokemongo_bot/inventory.py", line 62, in refresh
    self._data = self.retrieve_data(inventory)
  File "/Users/XXX/PokemonGo-Bot/pokemongo_bot/inventory.py", line 58, in retrieve_data
    ret[key] = self.parse(item)
  File "/Users/XXX/PokemonGo-Bot/pokemongo_bot/inventory.py", line 292, in parse
    return Pokemon(item)
  File "/Users/XXX/PokemonGo-Bot/pokemongo_bot/inventory.py", line 505, in __init__
    self.moveset = self._get_moveset()
  File "/Users/XXX/PokemonGo-Bot/pokemongo_bot/inventory.py", line 611, in _get_moveset
    move1, move2, self.pokemon_id, self.name))
Exception: Unexpected moveset [Confusion, Signal Beam] for #48 Venonat`

### Your config.json (remove your credentials and any other private info)
`{
    "auth_service": "google",
    "username": "REMOVED",
    "password": "REMOVED",
    "location": "XX.259879, -YY.745093",
    "gmapkey": "REMOVED",
    "tasks": [
    {
      "type": "CollectLevelUpReward"
    },
    {
      "type": "IncubateEggs",
      "config": {
        "longer_eggs_first": true
      }
    },
    {
      "type": "RecycleItems",
      "config": {
        "run_interval": 60,
        "item_filter": {
          "Pokeball": {
            "keep": 40
          },
          "Greatball": {
            "keep": 40
          },
          "Ultraball": {
            "keep": 60
          },
          "Masterball": {
            "keep": 60
          },
          "Potion": {
            "keep": 0
          },
          "Super Potion": {
            "keep": 10
          },
          "Hyper Potion": {
            "keep": 15
          },
          "Max Potion": {
            "keep": 80
          },
          "Revive": {
            "keep": 10
          },
          "Max Revive": {
            "keep": 30
          },
          "Razz Berry": {
            "keep": 30
          }
        }
      }
    },
    {
      "type": "EvolvePokemon",
      "config": {
        "evolve_all": "Pidgey,Rattata,Zubat,Weedle,Drowzee,Spearow,Venonat,Caterpie,Krabby,Paras,Jigglypuff,Sandshrew,Vulpix,Meowth,Psyduck,Mankey,Tentacool,Ponyta,Slowpoke,Magnemite,Doduo,Seel,Voltorb,Horsea,Goldeen,Staryu,Ekans",
        "first_evolve_by": "cp",
        "evolve_above_cp": 0,
        "evolve_above_iv": 0,
        "logic": "or",
        "evolve_speed": 1,
        "use_lucky_egg": false,
        "run_interval": 180
      }
    },
    {
      "type": "TransferPokemon",
      "config": {
        "run_interval": 180
      }
    },
    {
      "type": "MoveToFort",
      "config": {
        "lure_attraction": true,
        "lure_max_distance": 2000,
        "ignore_item_count": true
      }
    },
    {
      "type": "SpinFort",
      "config": {
        "ignore_item_count": true
      }
    },
    {
      "type": "CatchVisiblePokemon"
    },
    {
      "type": "CatchLuredPokemon"
    }
  ],
  "map_object_cache_time": 5,
  "forts": {
    "avoid_circles": true,
    "max_circle_size": 500
  },
  "websocket_server": false,
  "walk": 50,
  "action_wait_min": 0,
  "action_wait_max": 1,
  "debug": false,
  "test": false,
  "health_record": false,
  "location_cache": false,
  "distance_unit": "m",
  "reconnecting_timeout": 15,
  "evolve_captured": "NONE",
  "catch_randomize_reticle_factor": 1.0,
  "catch_randomize_spin_factor": 1.0,
  "catch": {
    "any": {
      "always_catch": true
    }
  },
  "release": {
    "any": {
      "keep_best_iv": 1
    },
    "Moltres": {
      "keep_best_iv": 3
    },
    "Eevee": {
      "keep_best_cp": 3
    },
    "Zapdos": {
      "keep_best_iv": 3
    },
    "Articuno": {
      "keep_best_iv": 3
    },
    "Mewtwo": {
      "keep_best_iv": 3
    },
    "Dragonite": {
      "keep_best_iv": 3
    },
    "Dratini": {
      "keep_best_iv": 3
    },
    "Dragonair": {
      "keep_best_iv": 3
    },
    "Snorlax": {
      "keep_best_iv": 3
    }
  },
  "vips": {
    "any": {
      "catch_above_cp": 1200,
      "catch_above_iv": 0.9,
      "logic": "or"
    },
    "Lapras": {},
    "Moltres": {},
    "Zapdos": {},
    "Articuno": {},
    "Mewtwo": {},
    "Dragonite": {},
    "Snorlax": {},
    "Mew": {},
    "Arcanine": {},
    "Vaporeon": {},
    "Gyarados": {},
    "Exeggutor": {},
    "Muk": {},
    "Weezing": {},
    "Flareon": {}
  }
}`

### Steps to Reproduce
git pull new dev update, start bot

### Other Information
OS: Mac OS X El Capitan
Git Commit: 00a5b2fa136a5e4b8228743a25bfb2228bda692f
Python Version: (run 'python -V' and paste it here)
Python 2.7.11

**Comment by GitPupper** [comment]
Currently running the bot fine. Just did a git pull.
***
### Logs
***
2016-08-10 22:14:46,437 [PokemonGoBot] [INFO] Found encrypt.so! Platform: darwin Encrypt.so directory: /Users/bobbyobrien/PokemonGo-Bot
2016-08-10 22:14:46,437 [PokemonGoBot] [INFO] 

[22:14:47] Starting bot...
[22:14:49] Received level up reward:
[22:14:49] Next egg incubates in 2.10 km
[22:14:49] Keeping best 2 Caterpie, based on cp
[22:14:50] Exchanged Caterpie [CP 23] [IV 0.18] for candy.
[22:14:53] Discarded 1x Revive (maximum 0).
[22:14:54] Discarded 2x Pokeball (maximum 50).
[22:14:54] Something rustles nearby!                                            
[22:14:54] A wild Nidoran F appeared! [CP 428] [Potential 0.73] [A/D/S 4/14/15]
[22:14:57] Used Greatball, with chance 46.80 (23 left)
[22:14:58] Captured Nidoran F! [CP 428] [Potential 0.73] [4/14/15] [+210 exp]
[22:14:58] You now have 819 Nidoran F candy!
[22:15:04] Keeping best 2 Nidoran F, based on cp
[22:15:04] Exchanged Nidoran F [CP 428] [IV 0.73] for candy.
[22:15:07] Something rustles nearby!                                                                                                                                                                        
[22:15:07] A wild Magnemite appeared! [CP 485] [Potential 0.18] [A/D/S 4/1/3]
[22:15:11] Used Greatball, with chance 42.14 (22 left)
[22:15:12] Captured Magnemite! [CP 485] [Potential 0.18] [4/1/3] [+210 exp]
[22:15:12] You now have 85 Magnemite candy!
***

**Comment by TheRyRyGuy1** [comment]
I am having this issue as well.

Could this be the culprit:
Exception: Unexpected moveset [Confusion, Signal Beam] for #48 Venonat

**Comment by rajulbhatnagar** [comment]
I get this too on the dev build

> Build  00a5b2f
> Windows 10
> Python 2.7

**Comment by nikhil-pandey** [comment]
Same here
```
Traceback (most recent call last):
  File "pokecli.py", line 530, in <module>
    main()
  File "pokecli.py", line 82, in main
    bot.start()
  File "/home/pi/bot-dev/pokemongo_bot/__init__.py", line 86, in start
    self._setup_api()
  File "/home/pi/bot-dev/pokemongo_bot/__init__.py", line 698, in _setup_api
    self.update_inventory()
  File "/home/pi/bot-dev/pokemongo_bot/__init__.py", line 796, in update_inventory
    init_inventory(self)
  File "/home/pi/bot-dev/pokemongo_bot/inventory.py", line 799, in init_inventory
    _inventory = Inventory(bot)
  File "/home/pi/bot-dev/pokemongo_bot/inventory.py", line 741, in __init__
    self.refresh()
  File "/home/pi/bot-dev/pokemongo_bot/inventory.py", line 749, in refresh
    i.refresh(inventory)
  File "/home/pi/bot-dev/pokemongo_bot/inventory.py", line 62, in refresh
    self._data = self.retrieve_data(inventory)
  File "/home/pi/bot-dev/pokemongo_bot/inventory.py", line 58, in retrieve_data
    ret[key] = self.parse(item)
  File "/home/pi/bot-dev/pokemongo_bot/inventory.py", line 292, in parse
    return Pokemon(item)
  File "/home/pi/bot-dev/pokemongo_bot/inventory.py", line 505, in __init__
    self.moveset = self._get_moveset()
  File "/home/pi/bot-dev/pokemongo_bot/inventory.py", line 611, in _get_moveset
    move1, move2, self.pokemon_id, self.name))
Exception: Unexpected moveset [Bug Bite, Signal Beam] for #48 Venonat
```

**Comment by abusalman** [comment]
+1 for this issue, got this error too
but it works with other ptc account, maybe some account got banned?
try with your other account

**Comment by mohit1337** [comment]
I am facing this error after bot update too

**Comment by nikhil-pandey** [comment]
Might be related to #3336 #3455 ?

**Comment by JarodKY** [comment]
Definitely not banned, doesn't work on other accounts and I can use the official app just fine.

**Comment by islanderman** [comment]
``git reset --hard e60da103cc40c68be8b401f2bc4c63e696210047`` and works again.  It's related to https://github.com/PokemonGoF/PokemonGo-Bot/commit/00a5b2fa136a5e4b8228743a25bfb2228bda692f

**Comment by amal** [comment]
Fixed list of charged attacks for Venonat #3550

**Comment by JarodKY** [comment]
Thanks, locking this!

**Comment by abusalman** [comment]
@islanderman why is it like this?
```
(PokemonGo-Bot) c:\pokebot\PokemonGo-Bot-main>git reset --hard e60da103cc40c68be8b401f2bc4c63e696210047
HEAD is now at e60da10 Ensure recycling happens if bag is over capacity. (#3531)

(PokemonGo-Bot) c:\pokebot\PokemonGo-Bot-main>git reset --hard e60da103cc40c68be8b401f2bc4c63e696210047
HEAD is now at e60da10 Ensure recycling happens if bag is over capacity. (#3531)

```

**Comment by leadboots5** [comment]
Lets leave this open till its actually fixed so people see it.

**Comment by JarodKY** [comment]
It's working for me after a git pull, I agree probably best we leave this open to make sure it's working for everyone.

**Comment by abusalman** [comment]
@islanderman oh nevermind, its ok now, thx

**Comment by leadboots5** [comment]
The change was reverted so git pull will fix the issue.

**Comment by nisit15** [comment]
I did git pull already but still have error.

Traceback (most recent call last):
  File "pokecli.py", line 530, in <module>
    main()
  File "pokecli.py", line 96, in main
    bot.tick()
  File "/Users/Ninenox/PokemonGo-Bot/pokemongo_bot/__init__.py", line 464, in tick
    self.health_record.heartbeat()
  File "/Users/Ninenox/PokemonGo-Bot/pokemongo_bot/health_record/bot_event.py", line 65, in heartbeat
    self.track_url('/heartbeat')
  File "/Users/Ninenox/PokemonGo-Bot/pokemongo_bot/health_record/bot_event.py", line 78, in track_url
    'http://www.google-analytics.com/collect', data=data)
  File "/Users/Ninenox/PokemonGo-Bot/lib/python2.7/site-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/Ninenox/PokemonGo-Bot/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/Ninenox/PokemonGo-Bot/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Ninenox/PokemonGo-Bot/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Ninenox/PokemonGo-Bot/lib/python2.7/site-packages/requests/adapters.py", line 479, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='www.google-analytics.com', port=80): Read timed out. (read timeout=None)
2016-08-11 13:58:59,129 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/Ninenox/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/Ninenox/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/Ninenox/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/Ninenox/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/Ninenox/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/Ninenox/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/Ninenox/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/Ninenox/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 891, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-11 13:58:59,132 [sentry.errors.uncaught] [ERROR] [u"ReadTimeout: HTTPConnectionPool(host='www.google-analytics.com', port=80): Read timed out. (read timeout=None)", u'  File "pokecli.py", line 530, in <module>', u'  File "pokecli.py", line 96, in main', u'  File "pokemongo_bot/__init__.py", line 464, in tick', u'  File "pokemongo_bot/health_record/bot_event.py", line 65, in heartbeat', u'  File "pokemongo_bot/health_record/bot_event.py", line 78, in track_url', u'  File "requests/api.py", line 111, in post', u'  File "requests/api.py", line 57, in request', u'  File "requests/sessions.py", line 475, in request', u'  File "requests/sessions.py", line 585, in send', u'  File "requests/adapters.py", line 479, in send']

**Comment by nourz02** [comment]
same as @nisit15

**Comment by nisit15** [comment]
"health_record": false , this work for me.
