### ISSUE TITLE
UpdateTitleStats broken

### ISSUE THREAD

**Issue by keugnu** [PokemonGoF/PokemonGo-Bot#3573]
### Expected Behavior
Print Stats

### Actual Behavior
```
Traceback (most recent call last):
  File "pokecli.py", line 530, in <module>
    main()
  File "pokecli.py", line 83, in main
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "c:\dir\dir\dir\PokemonGO-Bot-dev\PokemonGo-Bot\pokemongo_bot\tree_config_builder.py", line 43, in build
    worker = self._get_worker_by_name(task_type)
  File "c:\dir\dir\dir\PokemonGO-Bot-dev\PokemonGo-Bot\pokemongo_bot\tree_config_builder.py", line 21, in _get_worker_by_name
    raise ConfigException('No worker named {} defined'.format(name))
pokemongo_bot.tree_config_builder.ConfigException: No worker named UpdateTitleStats defined
```

### Your config.json (remove your credentials and any other private info)
```
	  {
        "type": "UpdateTitleStats",
        "config": {
           "min_interval": 60,
           "stats": ["login", "uptime", "km_walked", "level_stats", "xp_earned", "xp_per_hour"]
       }
      },
```

### Steps to Reproduce
Use above task

### Other Information
OS: Windows 10
Git Commit: 350148e8443e35a6f5b74169b7ac5fd26815fe7b
Python Version: 2.7.12

**Comment by adamvc21** [comment]
This is mine and after trying to get it to work for a while I cannot. It's only this. Latest Commit, Window 10

` {
        "type": "UpdateTitleStats",
        "config": {
          "min_interval": 5,
          "stats": ["uptime", "km_walked", "level_stats", "xp_earned", "xp_per_hour", "stops_visited", "pokeballs_thrown", "stardust_earned", "pokemon_stats", "highest_cp_pokemon", "most_perfect_pokemon"],
          "terminal_log": true,
          "terminal_title": true
        }
      },`

**Comment by denike** [comment]
It's UpdateLiveStats now.

**Comment by adamvc21** [comment]
That does not work for me. Returns

```
Traceback (most recent call last):
  File "pokecli.py", line 521, in <module>
    main()
  File "pokecli.py", line 82, in main
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "C:\PokemonGo-Bot-master\pokemongo_bot\tree_config_builder.py", line 43, in build
    worker = self._get_worker_by_name(task_type)
  File "C:\PokemonGo-Bot-master\pokemongo_bot\tree_config_builder.py", line 21, in _get_worker_by_name
    raise ConfigException('No worker named {} defined'.format(name))
pokemongo_bot.tree_config_builder.ConfigException: No worker named UpdateLiveStats defined
```
