### ISSUE TITLE
Attribute Error: CollectLevelUpReward object has no attribute

### ISSUE THREAD

**Issue by icecubeice** [PokemonGoF/PokemonGo-Bot#3603]
### Expected Behavior
bot working

### Actual Behavior
shows this error:
Traceback (most recent call last):
  File "pokecli.py", line 514, in <module>
    main()
  File "pokecli.py", line 96, in main
    bot.tick()
  File "C:\Users\Anthony\downloads\pokemongo-bot\pokemongo_bot\__init__.py", line 468, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "C:\Users\Anthony\downloads\pokemongo-bot\pokemongo_bot\cell_workers\collect_level_up_reward.py", line 15, in work
    if not self._time_to_run():
AttributeError: 'CollectLevelUpReward' object has no attribute '_time_to_run'

### Other Information
OS: Windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by nivong** [comment]
please follow the steps of the issue template and post the output that is being asked or close the issue, we cant help you right now.
