### ISSUE TITLE
HandleSoftBan makes bot crash

### ISSUE THREAD

**Issue by Slayslot** [PokemonGoF/PokemonGo-Bot#3623]
### Expected Behavior
When the bot finds nothing at a pokestop for two times consecutively, it should attempt at fixing the softban.  

### Actual Behavior
I jumped from Hong Kong to Ohio and I get the following output on running the bot.

```bash
[20:46:03] Starting bot...
[20:46:04] Received level up reward: []
[20:46:04] Next egg incubates in 0.78 km
[20:46:06] Moving towards pokestop National Natural Landmark - 0.12km
[20:46:06] {'distance_unit': '', 'distance': '', 'current_position': (40.14959040264607, -83.02680305150429), 'last_position': (40.1495866, -83.0263423)}
[20:46:11] Moving towards pokestop National Natural Landmark - 0.08km
[20:46:11] {'distance_unit': '', 'distance': '', 'current_position': (40.149608280710524, -83.02727619068483), 'last_position': (40.14959040264607, -83.02680305150429)}
[20:46:15] Moving towards pokestop National Natural Landmark - 0.04km
[20:46:16] Arrived at fort.
[20:46:19] Found nothing in pokestop National Natural Landmark.
[20:46:19] Possibly searching too often, take a rest.
[20:46:19] Probably got softban.
[20:46:20] Moving towards pokestop Hawthorn - 0.08km
[20:46:20] {'distance_unit': '', 'distance': '', 'current_position': (40.149646315493364, -83.02826159112763), 'last_position': (40.149663, -83.027774)}2016-08-11 20:46:24,226 [       cli] [INFO] 
2016-08-11 20:46:24,226 [       cli] [INFO] Ran for 0:00:29
2016-08-11 20:46:24,226 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-11 20:46:24,226 [       cli] [INFO] Travelled 0.00km
2016-08-11 20:46:24,226 [       cli] [INFO] Visited 0 stops
2016-08-11 20:46:24,227 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-11 20:46:24,227 [       cli] [INFO] Threw 0 pokeballs
2016-08-11 20:46:24,227 [       cli] [INFO] Earned 0 Stardust
2016-08-11 20:46:24,227 [       cli] [INFO] 
2016-08-11 20:46:24,227 [       cli] [INFO] Highest CP Pokemon: 
2016-08-11 20:46:24,227 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 514, in <module>
    main()
  File "pokecli.py", line 96, in main
    bot.tick()
  File "/home/slayslot/github/pokbot/nikhil/PokemonGo-Bot/pokemongo_bot/__init__.py", line 468, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/slayslot/github/pokbot/nikhil/PokemonGo-Bot/pokemongo_bot/cell_workers/handle_soft_ban.py", line 32, in work
    MoveToFort(self.bot, config=None).work()
  File "/home/slayslot/github/pokbot/nikhil/PokemonGo-Bot/pokemongo_bot/base_task.py", line 12, in __init__
    self.enabled = config.get('enabled', True)
AttributeError: 'NoneType' object has no attribute 'get'
2016-08-11 20:46:24,245 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/slayslot/github/pokbot/nikhil/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/slayslot/github/pokbot/nikhil/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/slayslot/github/pokbot/nikhil/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/slayslot/github/pokbot/nikhil/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/slayslot/github/pokbot/nikhil/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/slayslot/github/pokbot/nikhil/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/slayslot/github/pokbot/nikhil/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/slayslot/github/pokbot/nikhil/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-11 20:46:24,246 [sentry.errors.uncaught] [ERROR] [u"AttributeError: 'NoneType' object has no attribute 'get'", u'  File "pokecli.py", line 514, in <module>', u'  File "pokecli.py", line 96, in main', u'  File "pokemongo_bot/__init__.py", line 468, in tick', u'  File "pokemongo_bot/cell_workers/handle_soft_ban.py", line 32, in work', u'  File "pokemongo_bot/base_task.py", line 12, in __init__']
Thu Aug 11 20:46:24 IST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
```

### Your config.json (remove your credentials and any other private info)
```json
{
    "auth_service": "google",
    "username": "****",
    "password": "*****",
    "location": "40.14958661537503, -83.02634239196777",
    "gmapkey": "******",
    "libencrypt_location": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "evolve_all": "NONE",
          "evolve_cp_min": 0,
          "evolve_speed": 5,
          "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 210 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 10 },
            "Hyper Potion":   { "keep" : 10 },
            "Revive":         { "keep" : 10 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 40,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 5,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Caterpie":     { "release_below_cp": 100, "release_below_iv": 0.8, "logic": "and" },
      "Weedle":       { "release_below_cp": 100, "release_below_iv": 0.8, "logic": "and" },
      "Pidgey":       { "release_below_cp": 100, "release_below_iv": 0.8, "logic": "and" },
      "Rattata":      { "release_below_cp": 200, "release_below_iv": 0.8, "logic": "and" },
      "Spearow":      { "release_below_cp": 300, "release_below_iv": 0.8, "logic": "and" },
      "Ekans":        { "release_below_cp": 200, "release_below_iv": 0.8, "logic": "and" },
      "Zubat":        { "release_below_cp": 300, "release_below_iv": 0.8, "logic": "and" },
      "Magikarp":     { "release_below_cp": 145, "release_below_iv": 0.93, "logic": "or" }
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}

```

### Steps to Reproduce
1. Get a softban.
2. Run the bot near a pokestop. The bot will find the first pokestop and crash while going to the second one.

### Other Information
OS: Ubuntu 16.04 LTS
Git Commit: 138b66413e45efcef1ae015388b80a2725e7a7d8
Python Version: Python 2.7.12

Edit: Also, when I remove `HandleSoftBan` task from `config.json`, there's no crash.

**Comment by joaodragao** [comment]
It's because of `MoveToFort(self.bot, config=None).work()`. It should be `MoveToFort(self.bot, config={}).work()` because `config` has to be existed to check `enable` feature whenever the bot ticks. I will open the PR later.

**Comment by Chofoteddy** [comment]
I have this problem, after `git pull`:

    $ git pull                                                                                                                                                                         

    remote: Counting objects: 144, done.
    remote: Compressing objects: 100% (14/14), done.
    remote: Total 144 (delta 58), reused 55 (delta 55), pack-reused 75
    Receiving objects: 100% (144/144), 90.41 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (79/79), completed with 41 local objects.
    From https://github.com/PokemonGoF/PokemonGo-Bot
       63f777b..d7cb7df  master     -> origin/master
       4c324ad..53c9ff7  add_mqtt_social_event -> origin/add_mqtt_social_event
     * [new branch]      app-emulation-delays -> origin/app-emulation-delays
     * [new branch]      appveyor   -> origin/appveyor
       e60da10..138b664  dev        -> origin/dev
     * [new branch]      devn0ll-patch-1 -> origin/devn0ll-patch-1
     * [new branch]      moveToFortPosition -> origin/moveToFortPosition
     * [new tag]         TAG_08102016_BEFORE_DEV_MERGE_TAG_ON_MASTER -> TAG_08102016_BEFORE_DEV_MERGE_TAG_ON_MASTER
    Updating 63f777b..d7cb7df
    Fast-forward
     .gitignore                                              |    1 +
     .mention-bot                                            |    3 +
     CONTRIBUTORS.md                                         |    3 +
     configs/config.json.cluster.example                     |    1 +
     configs/config.json.example                             |    8 +
     configs/config.json.map.example                         |    2 +
     configs/config.json.path.example                        |    1 +
     configs/config.json.pokemon.example                     |    1 +
     data/charged_moves.json                                 |   91 +++
     data/fast_moves.json                                    |   41 ++
     data/level_to_cpm.json                                  |   81 +++
     data/pokemon.json                                       | 5901 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-
     docs/auto_restart.md                                    |   73 +++
     docs/configuration_files.md                             |  271 ++++++++
     docs/develop.md                                         |   28 +
     docs/docker.md                                          |   25 +
     docs/faq.md                                             |   49 ++
     docs/google_map.md                                      |   54 ++
     docs/installation.md                                    |   93 +++
     docs/pokemon_iv.md                                      |   58 ++
     install.sh                                              |   10 +-
     pokecli.py                                              |   11 +-
     pokemongo_bot/__init__.py                               |   68 +-
     pokemongo_bot/base_dir.py                               |    4 +
     pokemongo_bot/base_task.py                              |    1 +
     pokemongo_bot/cell_workers/catch_visible_pokemon.py     |    4 +-
     pokemongo_bot/cell_workers/evolve_pokemon.py            |    5 -
     pokemongo_bot/cell_workers/move_to_fort.py              |   12 +-
     pokemongo_bot/cell_workers/move_to_map_pokemon.py       |    8 +-
     pokemongo_bot/cell_workers/pokemon_catch_worker.py      |   20 +-
     pokemongo_bot/cell_workers/recycle_items.py             |    5 +-
     pokemongo_bot/cell_workers/spin_fort.py                 |   11 +-
     pokemongo_bot/cell_workers/transfer_pokemon.py          |  204 +++---
     pokemongo_bot/cell_workers/update_title_stats.py        |   53 +-
     pokemongo_bot/event_handlers/__init__.py                |    1 +
     pokemongo_bot/event_handlers/colored_logging_handler.py |  172 ++++++
     pokemongo_bot/inventory.py                              |  704 +++++++++++++++++++--
     pokemongo_bot/socketio_server/app.py                    |    8 +-
     pokemongo_bot/step_walker.py                            |   11 +
     pokemongo_bot/tree_config_builder.py                    |    3 +-
     pokemongo_bot/websocket_remote_control.py               |    9 +-
     run.bat                                                 |   10 +
     run.sh                                                  |   13 +-
     setup.sh                                                |   23 +-
     tests/inventory_test.py                                 |  183 ++++++
     tests/tree_config_builder_test.py                       |   19 +
     46 files changed, 8087 insertions(+), 270 deletions(-)
     create mode 100644 .mention-bot
     create mode 100644 data/charged_moves.json
     create mode 100644 data/fast_moves.json
     create mode 100644 data/level_to_cpm.json
     create mode 100644 docs/auto_restart.md
     create mode 100644 docs/configuration_files.md
     create mode 100644 docs/develop.md
     create mode 100644 docs/docker.md
     create mode 100644 docs/faq.md
     create mode 100644 docs/google_map.md
     create mode 100644 docs/installation.md
     create mode 100644 docs/pokemon_iv.md
     create mode 100644 pokemongo_bot/base_dir.py
     create mode 100644 pokemongo_bot/event_handlers/colored_logging_handler.py
     create mode 100644 run.bat
     create mode 100644 tests/inventory_test.py

Now, it prints:

    [09:58:44] Starting bot...
    [09:58:45] Received level up reward: []
    [09:58:45] Next egg incubates in 3.06 km
    [09:58:46] Skipping Recycling of Items. 66 space left in bag.
    [09:58:46] Walking from (19.4044479, -99.169677, 0) to (19.4044479, -99.169677, 0) (0.0 m)
    [09:58:46] Skipping Recycling of Items. 66 space left in bag.
    [09:58:46] Walking from (19.4044479, -99.169677, 0) to (19.405075166690565, -99.169677, 0) (69.748892993 m)
    [09:58:46] {'distance_unit': '', 'distance': '', 'current_position': (19.40448355191118, -99.16965496596451), 'last_position': (19.4044479, -99.169677)}
    [09:58:48] Skipping Recycling of Items. 66 space left in bag.
    [09:58:48] {'distance_unit': '', 'distance': '', 'current_position': (19.404537492117843, -99.16966263768857), 'last_position': (19.40448355191118, -99.16965496596451)}
    [09:58:51] Skipping Recycling of Items. 66 space left in bag.
    [09:58:51] {'distance_unit': '', 'distance': '', 'current_position': (19.404573125518453, -99.16966805359172), 'last_position': (19.404537492117843, -99.16966263768857)}
    [09:58:54] Skipping Recycling of Items. 66 space left in bag.
    [09:58:54] {'distance_unit': '', 'distance': '', 'current_position': (19.40459960524222, -99.1696704668828), 'last_position': (19.404573125518453, -99.16966805359172)}
    [09:58:56] Skipping Recycling of Items. 66 space left in bag.
    [09:58:56] {'distance_unit': '', 'distance': '', 'current_position': (19.404648159508923, -99.16965556158895), 'last_position': (19.40459960524222, -99.1696704668828)}
    [09:58:58] Skipping Recycling of Items. 66 space left in bag.
    [09:58:58] {'distance_unit': '', 'distance': '', 'current_position': (19.404685318643597, -99.16964510786491), 'last_position': (19.404648159508923, -99.16965556158895)}
    [09:59:00] Skipping Recycling of Items. 66 space left in bag.
    [09:59:00] {'distance_unit': '', 'distance': '', 'current_position': (19.40472245904957, -99.16963555664415), 'last_position': (19.404685318643597, -99.16964510786491)}
    [09:59:03] Skipping Recycling of Items. 66 space left in bag.
    [09:59:03] {'distance_unit': '', 'distance': '', 'current_position': (19.404753417000574, -99.16964446008745), 'last_position': (19.40472245904957, -99.16963555664415)}
    [09:59:06] Skipping Recycling of Items. 66 space left in bag.
    [09:59:06] {'distance_unit': '', 'distance': '', 'current_position': (19.40479646893577, -99.1696554820782), 'last_position': (19.404753417000574, -99.16964446008745)}
    [09:59:08] Skipping Recycling of Items. 66 space left in bag.
    [09:59:08] {'distance_unit': '', 'distance': '', 'current_position': (19.404826303686782, -99.16963970746589), 'last_position': (19.40479646893577, -99.1696554820782)}
    [09:59:10] Skipping Recycling of Items. 66 space left in bag.
    [09:59:10] {'distance_unit': '', 'distance': '', 'current_position': (19.404861853314745, -99.1696284639372), 'last_position': (19.404826303686782, -99.16963970746589)}
    [09:59:13] Skipping Recycling of Items. 66 space left in bag.
    [09:59:13] {'distance_unit': '', 'distance': '', 'current_position': (19.404893370262375, -99.16966007649972), 'last_position': (19.404861853314745, -99.1696284639372)}
    [09:59:16] Skipping Recycling of Items. 66 space left in bag.
    [09:59:16] {'distance_unit': '', 'distance': '', 'current_position': (19.404952824879725, -99.16968357610632), 'last_position': (19.404893370262375, -99.16966007649972)}
    [09:59:18] Skipping Recycling of Items. 66 space left in bag.
    [09:59:18] {'distance_unit': '', 'distance': '', 'current_position': (19.404990252279056, -99.16968431161088), 'last_position': (19.404952824879725, -99.16968357610632)}
    [09:59:20] Skipping Recycling of Items. 66 space left in bag.
    [09:59:22] Skipping Recycling of Items. 66 space left in bag.
    [09:59:22] Walking from (19.405075166690565, -99.169677, 0) to (19.405075166690565, -99.1717970691014, 0) (222.349239075 m)
    [09:59:22] {'distance_unit': '', 'distance': '', 'current_position': (19.40505039611995, -99.16970607880337), 'last_position': (19.405075166690565, -99.169677)}
    [09:59:24] Skipping Recycling of Items. 66 space left in bag.
    [09:59:24] {'distance_unit': '', 'distance': '', 'current_position': (19.40503387678362, -99.16977920194523), 'last_position': (19.40505039611995, -99.16970607880337)}
    [09:59:26] Skipping Recycling of Items. 66 space left in bag.
    [09:59:26] {'distance_unit': '', 'distance': '', 'current_position': (19.405010172736752, -99.16980899529806), 'last_position': (19.40503387678362, -99.16977920194523)}
    [09:59:28] Skipping Recycling of Items. 66 space left in bag.
    [09:59:28] {'distance_unit': '', 'distance': '', 'current_position': (19.405005252392446, -99.16983629978708), 'last_position': (19.405010172736752, -99.16980899529806)}
    [09:59:30] Skipping Recycling of Items. 66 space left in bag.
    [09:59:30] {'distance_unit': '', 'distance': '', 'current_position': (19.40500862078381, -99.16986657741224), 'last_position': (19.405005252392446, -99.16983629978708)}
    [09:59:33] Skipping Recycling of Items. 66 space left in bag.
    [09:59:33] {'distance_unit': '', 'distance': '', 'current_position': (19.405015515776466, -99.16993643126969), 'last_position': (19.40500862078381, -99.16986657741224)}
    [09:59:36] Skipping Recycling of Items. 66 space left in bag.
    [09:59:36] {'distance_unit': '', 'distance': '', 'current_position': (19.40501270418972, -99.169991311282), 'last_position': (19.405015515776466, -99.16993643126969)}
    [09:59:37] Skipping Recycling of Items. 66 space left in bag.
    [09:59:37] {'distance_unit': '', 'distance': '', 'current_position': (19.40503601310093, -99.17003134592396), 'last_position': (19.40501270418972, -99.169991311282)}
    [09:59:39] Skipping Recycling of Items. 66 space left in bag.
    [09:59:39] {'distance_unit': '', 'distance': '', 'current_position': (19.40505272643302, -99.17009777043975), 'last_position': (19.40503601310093, -99.17003134592396)}
    [09:59:42] Skipping Recycling of Items. 66 space left in bag.
    [09:59:42] {'distance_unit': '', 'distance': '', 'current_position': (19.405066758639077, -99.1701663412571), 'last_position': (19.40505272643302, -99.17009777043975)}
    [09:59:45] Skipping Recycling of Items. 66 space left in bag.
    [09:59:45] {'distance_unit': '', 'distance': '', 'current_position': (19.405065675562618, -99.1702275300881), 'last_position': (19.405066758639077, -99.1701663412571)}
    [09:59:47] Skipping Recycling of Items. 66 space left in bag.
    [09:59:47] {'distance_unit': '', 'distance': '', 'current_position': (19.40507839318948, -99.1702973551982), 'last_position': (19.405065675562618, -99.1702275300881)}
    [09:59:49] Skipping Recycling of Items. 66 space left in bag.
    [09:59:49] {'distance_unit': '', 'distance': '', 'current_position': (19.40510254510286, -99.17036520623117), 'last_position': (19.40507839318948, -99.1702973551982)}
    [09:59:51] Skipping Recycling of Items. 66 space left in bag.
    [09:59:51] {'distance_unit': '', 'distance': '', 'current_position': (19.40511637817848, -99.17040484147282), 'last_position': (19.40510254510286, -99.17036520623117)}
    [09:59:54] Skipping Recycling of Items. 66 space left in bag.
    [09:59:54] {'distance_unit': '', 'distance': '', 'current_position': (19.40510068759598, -99.17043101797456), 'last_position': (19.40511637817848, -99.17040484147282)}
    [09:59:57] Skipping Recycling of Items. 66 space left in bag.
    [09:59:57] {'distance_unit': '', 'distance': '', 'current_position': (19.405103312706903, -99.17047045029956), 'last_position': (19.40510068759598, -99.17043101797456)}
    [09:59:59] Skipping Recycling of Items. 66 space left in bag.
    [09:59:59] {'distance_unit': '', 'distance': '', 'current_position': (19.405111569866083, -99.17050388511619), 'last_position': (19.405103312706903, -99.17047045029956)}^C
    [09:59:59] Exiting bot.2016-08-11 10:00:05,868 [       cli] [INFO] 
    2016-08-11 10:00:05,869 [       cli] [INFO] Ran for 0:01:28
    2016-08-11 10:00:05,869 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
    2016-08-11 10:00:05,869 [       cli] [INFO] Travelled 0.00km
    2016-08-11 10:00:05,869 [       cli] [INFO] Visited 0 stops
    2016-08-11 10:00:05,869 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
    2016-08-11 10:00:05,869 [       cli] [INFO] Threw 0 pokeballs
    2016-08-11 10:00:05,870 [       cli] [INFO] Earned 0 Stardust
    2016-08-11 10:00:05,870 [       cli] [INFO] 
    2016-08-11 10:00:05,870 [       cli] [INFO] Highest CP Pokemon: 
    2016-08-11 10:00:05,870 [       cli] [INFO] Most Perfect Pokemon:

**Comment by Slayslot** [comment]
>It should be MoveToFort(self.bot, config={}).work()

@joaodragao Yup, I can confirm. It works now.

**Comment by lightyoruichi** [comment]
Is there a flag that triggers fixing soft ban?

**Comment by Slayslot** [comment]
Closing, since a PR has been merged. Thank you, @joaodragao
