### ISSUE TITLE
Mac - El Capitan PyCLI Error

### ISSUE THREAD

**Issue by brandonhon** [PokemonGoF/PokemonGo-Bot#3632]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config.json is valid JSON? Use http://jsonlint.com/ to check.

 **YES**

2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.

 **Yes, but this seems to be different from the other issues.**

3. Are you running `master`? We work on the `dev` branch and then add that functionality to `master`. Your issue may be fixed on `dev` and there is no need for this issue, just wait and it will eventually be merged to `master`.

 **I have ran both `master` and `dev` and the issues is with both.**

### Actual Behavior

Shortly after running I get an the below error.

```
Traceback (most recent call last):
  File "pokecli.py", line 514, in <module>
    main()
  File "pokecli.py", line 83, in main
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "/Users/toastmaster/projects/PokemonGo-Bot/pokemongo_bot/tree_config_builder.py", line 43, in build
    worker = self._get_worker_by_name(task_type)
  File "/Users/toastmaster/projects/PokemonGo-Bot/pokemongo_bot/tree_config_builder.py", line 21, in _get_worker_by_name
    raise ConfigException('No worker named {} defined'.format(name))
pokemongo_bot.tree_config_builder.ConfigException: No worker named SpinFortWorker defined
2016-08-11 11:43:08,140 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/toastmaster/projects/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/toastmaster/projects/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/toastmaster/projects/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/toastmaster/projects/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/toastmaster/projects/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/toastmaster/projects/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/toastmaster/projects/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/toastmaster/projects/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 891, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-11 11:43:08,142 [sentry.errors.uncaught] [ERROR] [u'ConfigException: No worker named SpinFortWorker defined', u'  File "pokecli.py", line 514, in <module>', u'  File "pokecli.py", line 83, in main', u'  File "pokemongo_bot/tree_config_builder.py", line 43, in build', u'  File "pokemongo_bot/tree_config_builder.py", line 21, in _get_worker_by_name']
Thu Aug 11 11:43:08 CDT 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
```

### Your config.json (remove your credentials and any other private info)
```
{
    "auth_service": "google",
    "username": "",
    "password": "",
    "location": "",
    "gmapkey": "",
    "libencrypt_location": "",
    "tasks": [
          {
            "type": "RecycleItems"
          },
          {
            "type": "SpinFortWorker"
          },
          {
            "type": "MoveToFortWorker"
          }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 6,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}
```

### Steps to Reproduce

**Master Repo**

> git clone --recursive -b master https://github.com/PokemonGoF/PokemonGo-Bot
> cd PokemonGo-Bot
> virtualenv .
> source bin/activate
> pip install -r requirements.txt
> cp ../../encrypt.so .
> ./run.sh

**DEV Repo**

> git clone --recursive -b dev https://github.com/PokemonGoF/PokemonGo-Bot
> cd PokemonGo-Bot
> virtualenv .
> source bin/activate
> pip install -r requirements.txt
> cp ../../encrypt.so .
> ./run.sh

### Other Information
OS: **OSX El Capitan**
Git Commit: **138b66413e45efcef1ae015388b80a2725e7a7d8**
Python Version: **Python 2.7.10**

**Comment by peter-bonanni** [comment]
The error message explains your problem. You're using an outdated config. See this [file](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/configs/config.json.example) and update your tasks.
SpinFortWorker & MoveToFortWorker are not valid.

**Comment by DiegoRBaquero** [comment]
Unrelated to the unicode issue:

The tasks names are `MoveToFort` and `SpinFort`

**Comment by GitPupper** [comment]
Run the following:

`cd PokemonGo-Bot`
`git pull`

You are running an outdated Bot.

**Comment by brandonhon** [comment]
Thanks! That was my issue. I got that task from your wiki... Might need to update that. BTW, what happened to the wiki?
