### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by davidschoerkmayr** [PokemonGoF/PokemonGo-Bot#3664]
Can someone please help me with this problem?
```
Traceback (most recent call last):
  File "pokecli.py", line 514, in <module>
    main()
  File "pokecli.py", line 82, in main
    bot.start()
  File "/Users/davidschorkmayr/projekte/neu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 86, in start
    self._setup_api()
  File "/Users/davidschorkmayr/projekte/neu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 701, in _setup_api
    self.update_inventory()
  File "/Users/davidschorkmayr/projekte/neu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 799, in update_inventory
    init_inventory(self)
  File "/Users/davidschorkmayr/projekte/neu/PokemonGo-Bot/pokemongo_bot/inventory.py", line 809, in init_inventory
    _inventory = Inventory(bot)
  File "/Users/davidschorkmayr/projekte/neu/PokemonGo-Bot/pokemongo_bot/inventory.py", line 751, in __init__
    self.refresh()
  File "/Users/davidschorkmayr/projekte/neu/PokemonGo-Bot/pokemongo_bot/inventory.py", line 759, in refresh
    i.refresh(inventory)
  File "/Users/davidschorkmayr/projekte/neu/PokemonGo-Bot/pokemongo_bot/inventory.py", line 63, in refresh
    self._data = self.retrieve_data(inventory)
  File "/Users/davidschorkmayr/projekte/neu/PokemonGo-Bot/pokemongo_bot/inventory.py", line 59, in retrieve_data
    ret[key] = self.parse(item)
  File "/Users/davidschorkmayr/projekte/neu/PokemonGo-Bot/pokemongo_bot/inventory.py", line 293, in parse
    return Pokemon(item)
  File "/Users/davidschorkmayr/projekte/neu/PokemonGo-Bot/pokemongo_bot/inventory.py", line 501, in __init__
    assert max(int(self.cp_exact), 10) == self.cp
AssertionError
```

**Comment by keugnu** [comment]
@davidschoerkmayr Could you please follow the format for posting an issue?

**Comment by k4n30** [comment]
As mentioned, please use the issue template
