### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by davidschoerkmayr** [PokemonGoF/PokemonGo-Bot#3667]
1. My config is valid.
2. Habe not found an issue like this.
3. I use the master branch.

### Actual Behavior
I started 2 bots. One of them is working fine, in the other one I have an unknown Error after the login process.

```
$ python pokecli.py
2016-08-12 08:20:45,854 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-12 08:20:45,855 [       cli] [INFO] No config argument specified, checking for /configs/config.json
2016-08-12 08:20:45,856 [       cli] [WARNING] The evolve_captured argument is no longer supported. Please use the EvolvePokemon task instead
2016-08-12 08:20:45,857 [       cli] [INFO] Configuration initialized

[08:20:45] Setting start location.
[08:20:46] Location found: 1 Beard St, Brooklyn, NY 11231, Vereinigte Staaten (40.67197549999999, -74.0114608, 0.0)
[08:20:46] Now at (40.67197549999999, -74.0114608, 0)
[08:20:46] Loading cached location...
[08:20:46] Loaded location (40.67011355454398, -73.96397507829333, 0.0) from cache
[08:20:46] Login procedure started.
[08:20:50] Login successful.2016-08-12 08:20:52,386 [PokemonGoBot] [INFO] 
2016-08-12 08:20:52,386 [PokemonGoBot] [INFO] --- ---
2016-08-12 08:20:52,387 [PokemonGoBot] [INFO] Level: 25 (Next Level: 134330 XP) (Total: 765670 XP)
2016-08-12 08:20:52,387 [PokemonGoBot] [INFO] Pokemon Captured: 1759 | Pokestops Visited: 2028
2016-08-12 08:20:52,387 [PokemonGoBot] [INFO] Pokemon Bag: 222/250
2016-08-12 08:20:52,388 [PokemonGoBot] [INFO] Items: 290/350
2016-08-12 08:20:52,388 [PokemonGoBot] [INFO] Stardust: 72109 | Pokecoins: 0
2016-08-12 08:20:52,388 [PokemonGoBot] [INFO] PokeBalls: 80 | GreatBalls: 63 | UltraBalls: 30
2016-08-12 08:20:52,388 [PokemonGoBot] [INFO] RazzBerries: 38 | BlukBerries: 0 | NanabBerries: 0
2016-08-12 08:20:52,389 [PokemonGoBot] [INFO] LuckyEgg: 0 | Incubator: 1 | TroyDisk: 6
2016-08-12 08:20:52,389 [PokemonGoBot] [INFO] Potion: 10 | SuperPotion: 10 | HyperPotion: 10 | MaxPotion: 21
2016-08-12 08:20:52,389 [PokemonGoBot] [INFO] Incense: 9 | IncenseSpicy: 0 | IncenseCool: 0
2016-08-12 08:20:52,389 [PokemonGoBot] [INFO] Revive: 10 | MaxRevive: 0
2016-08-12 08:20:52,389 [PokemonGoBot] [INFO] 
2016-08-12 08:20:52,389 [PokemonGoBot] [INFO] Found encrypt.so! Platform: darwin Encrypt.so directory: /Users/projekte/neu/PokemonGo-Bot
2016-08-12 08:20:52,389 [PokemonGoBot] [INFO] 
2016-08-12 08:20:53,953 [       cli] [INFO] 
2016-08-12 08:20:53,953 [       cli] [INFO] Ran for 0:00:08
2016-08-12 08:20:53,953 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-12 08:20:53,953 [       cli] [INFO] Travelled 0.00km
2016-08-12 08:20:53,953 [       cli] [INFO] Visited 0 stops
2016-08-12 08:20:53,954 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-12 08:20:53,954 [       cli] [INFO] Threw 0 pokeballs
2016-08-12 08:20:53,954 [       cli] [INFO] Earned 0 Stardust
2016-08-12 08:20:53,954 [       cli] [INFO] 
2016-08-12 08:20:53,954 [       cli] [INFO] Highest CP Pokemon: 
2016-08-12 08:20:53,954 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 514, in <module>
    main()
  File "pokecli.py", line 82, in main
    bot.start()
  File "/Users/projekte/neu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 86, in start
    self._setup_api()
  File "/projekte/neu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 701, in _setup_api
    self.update_inventory()
  File "/Users/projekte/neu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 799, in update_inventory
    init_inventory(self)
  File "/Users/projekte/neu/PokemonGo-Bot/pokemongo_bot/inventory.py", line 809, in init_inventory
    _inventory = Inventory(bot)
  File "/Users/projekte/neu/PokemonGo-Bot/pokemongo_bot/inventory.py", line 751, in __init__
    self.refresh()
  File "/Users/projekte/neu/PokemonGo-Bot/pokemongo_bot/inventory.py", line 759, in refresh
    i.refresh(inventory)
  File "/Users/projekte/neu/PokemonGo-Bot/pokemongo_bot/inventory.py", line 63, in refresh
    self._data = self.retrieve_data(inventory)
  File "/Users/projekte/neu/PokemonGo-Bot/pokemongo_bot/inventory.py", line 59, in retrieve_data
    ret[key] = self.parse(item)
  File "/Users/projekte/neu/PokemonGo-Bot/pokemongo_bot/inventory.py", line 293, in parse
    return Pokemon(item)
  File "/Users/projekte/neu/PokemonGo-Bot/pokemongo_bot/inventory.py", line 501, in __init__
    assert max(int(self.cp_exact), 10) == self.cp
AssertionError
```
### Your config.json (remove your credentials and any other private info)
```
{
    "auth_service": "google",
    "username": "",
    "password": "",
    "location": "1 Beard St, Brooklyn, NY 11231, Vereinigte Staaten",
    "gmapkey": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "iv",
            "evolve_above_cp": 0,
            "evolve_above_iv": 0,
            "logic": "and",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 80 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 10 },
            "Hyper Potion":   { "keep" : 10 },
            "Revive":         { "keep" : 10 },
            "Razz Berry":     { "keep" : 40 },
            "Greatball":      { "keep" : 70 },
            "Ultraball":      { "keep" : 30 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 14.19,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": false,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"keep_best_cp": 2, "keep_best_iv": 2},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "Pidgey": {"keep_best_cp": 30},
      "Zubat": {"keep_best_cp": 30},
      "Rattata": {"keep_best_cp": 30},
      "Weedle": {"keep_best_cp": 30},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}
```
### Steps to Reproduce
I pulled the newest version with the command git pull and pip install --upgrade -r requirements.txt .

### Other Information
OS: OSX Yosemite 10.10.5
Python Version: Python 2.7.12

**Comment by nrinaudo** [comment]
Note that as a temporary workaround, you need only comment out [this](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/inventory.py#L545) line in `inventory.py` for everything to work fine.

**Comment by GitPupper** [comment]
@nrinaudo Has a temporary solution for you. Most of the problems are fixed in the dev branch. If you would like to change over, just follow reinstallation instructions but instead of cloning the master branch change it to dev.
