### ISSUE TITLE
PokeStop: Soft ban error.

### ISSUE THREAD

**Issue by Zeper666** [PokemonGoF/PokemonGo-Bot#368]
### Expected Behavior
work

### Actual Behavior
crash randomly

### Steps to Reproduce
wait the bot try to spin a pokestop for the X time.

### Other Information
OS: win10
The msg error say I'm soft banned but i'm not and after reboot the bot work again.

I use this to lunch the bot:
`C:\Python27\python pokecli.py -a ptc -u zeper -p "lol nope" -l "48.842606,2.360102" -c 100 -m all -k "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" --initial-transfer --distance_unit km --maxstep 5 -w 13 -iv "0.8"`

```

[x] PokemonGO Bot v1.0
[x] Configuration initialized

[x] Address found: 48.842606,2.360102
[x] Position in-game set as: (48.8424039, 2.3599706, 0.0)

[#]
[#] Username: Ekibunnel
[#] Acccount Creation: 2016-07-08 02:08:55.821000
[#] Bag Storage: 344/350
[#] Pokemon Storage: 104/250
[#] Stardust: 19111
[#] Pokecoins: 30
[#] PokeBalls: 36
[#] GreatBalls: 29
[#] UltraBalls: 0
[#] -- Level: 15
[#] -- Experience: 119549
[#] -- Experience until next level: 451
[#] -- Pokemon Captured: 340
[#] -- Pokestops Visited: 449
[x] Initial Transfer.
[x] Will NOT transfer anything above CP 100
[x] Releasing Pokemon #129 and CP 17
[x] Releasing Pokemon #16 and CP 78
[x] Releasing Pokemon #16 and CP 77
[x] Releasing Pokemon #16 and CP 58
[x] Releasing Pokemon #41 and CP 10
[x] Releasing Pokemon #60 and CP 100
[x] Releasing Pokemon #60 and CP 78
[x] Releasing Pokemon #60 and CP 10
[x] Releasing Pokemon #19 and CP 65
[x] Releasing Pokemon #19 and CP 35
[x] Transfering Done.
[#]
[x] Starting PokemonGo Bot....
[#] Scanning area for objects (1 / 25)
[#] Walking from (48.8424039, 2.3599706) to (48.8424039, 2.3599706) for approx. 0.0 seconds
[#] Finished walking
[#] (48.8424039, 2.3599706, 0)
 [#] Found fort 03a51848ad3e4d40aa121ea0d11ccf77.16 at distance 0.462390442177km
[#] Need to move closer to Pokestop
[#] Walking from (48.8424039, 2.3599706) to (48.841575, 2.353779) for approx. 10.0 seconds
[#] Now at Pokestop: La Geisha de Bercy - Spinning...
[+] Loot:
[#] Nothing found.
Traceback (most recent call last):
  File "pokecli.py", line 126, in <module>
    main()
  File "pokecli.py", line 119, in main
    bot.take_step()
  File "C:\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 31, in take_step
    self.stepper.take_step()
  File "C:\PokemonGo-Bot-dev\pokemongo_bot\stepper.py", line 56, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "C:\PokemonGo-Bot-dev\pokemongo_bot\stepper.py", line 100, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "C:\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 56, in work_on_cell
    hack_chain = worker.work()
  File "C:\PokemonGo-Bot-dev\pokemongo_bot\cell_workers\seen_fort_worker.py", line 97, in work
    raise RuntimeError(message)
RuntimeError: Stopped at Pokestop and did not find experience, items or information about the stop cooldown. You are probably softbanned. Try to play on your phone, if pokemons always ran away and you find nothing in PokeStops you are indeed softbanned. Please try again in a few hours.
```

**Comment by julienkessels** [comment]
yes program should just wait some time and relaunch after! having the same problem

**Comment by surfaace** [comment]
not a code issue
