### ISSUE TITLE
Assertion failure when calculating the "exact value of current CP"

### ISSUE THREAD

**Issue by nrinaudo** [PokemonGoF/PokemonGo-Bot#3701]
### Expected Behavior
Bot boots normally.

### Actual Behavior
Bot fails with the following stack trace:
```
Traceback (most recent call last):
  File "pokecli.py", line 559, in <module>
    main()
  File "pokecli.py", line 82, in main
    bot.start()
  File "/path/to/PokemonGo-Bot/pokemongo_bot/__init__.py", line 86, in start
    self._setup_api()
  File "/path/to/PokemonGo-Bot/pokemongo_bot/__init__.py", line 694, in _setup_api
    self.update_inventory()
  File "/path/to/PokemonGo-Bot/pokemongo_bot/__init__.py", line 792, in update_inventory
    init_inventory(self)
  File "/path/to/PokemonGo-Bot/pokemongo_bot/inventory.py", line 870, in init_inventory
    _inventory = Inventory(bot)
  File "/path/to/PokemonGo-Bot/pokemongo_bot/inventory.py", line 800, in __init__
    self.refresh()
  File "/path/to/PokemonGo-Bot/pokemongo_bot/inventory.py", line 809, in refresh
    i.refresh(inventory)
  File "/path/to/PokemonGo-Bot/pokemongo_bot/inventory.py", line 62, in refresh
    self._data = self.retrieve_data(inventory)
  File "/path/to/PokemonGo-Bot/pokemongo_bot/inventory.py", line 58, in retrieve_data
    ret[key] = self.parse(item)
  File "/path/to/PokemonGo-Bot/pokemongo_bot/inventory.py", line 337, in parse
    return Pokemon(item)
  File "/path/to/PokemonGo-Bot/pokemongo_bot/inventory.py", line 550, in __init__
    assert max(int(self.cp_exact), 10) == self.cp/path/to/
```

I've tracked this to a single Weezing with:
- `max_cp`: 2250.1508738
- `base_attack`: 190
- `base_defense`: 198
- `base_stamina`: 130
- `iv_attack`: 15
- `iv_defense`: 13
- `iv_stamina`: 13
- `cp_m`: 0.6876849047839642

Which turns, when executing `assert max(int(self.cp_exact), 10) == self.cp`, into `assert 1684 == 1683`.

### Your config.json (remove your credentials and any other private info)

```
{
    "auth_service": "foo",
    "username": "bar",
    "password": "baz",
    "location": "48.822482, 2.338132",
    "gmapkey": "ohmypretties",
    "tasks": [
        {
            "type": "HandleSoftBan"
        },
        {
            "type": "CollectLevelUpReward"
        },
        {
            "type": "IncubateEggs",
            "config": {
                "longer_eggs_first": true
            }
        },
        {
            "type": "TransferPokemon"
        },
        {
            "type": "EvolvePokemon",
            "config": {
                "evolve_cp_min": 1,
                "evolve_speed": 20,
                "use_lucky_egg": false
            }
        },
        {
            "type": "RecycleItems",
            "config": {
                "item_filter": {
                    "Pokeball":       { "keep" : 60  },
                    "Greatball":      { "keep" : 100 },
                    "Ultraball":      { "keep" : 100 },
                    "Potion":         { "keep" : 0 },
                    "Super Potion":   { "keep" : 0 },
                    "Hyper Potion":   { "keep" : 0 },
                    "Max Potion":     { "keep" : 20 },
                    "Revive":         { "keep" : 0 },
                    "Max Revive":     { "keep" : 20 },
                    "Razz Berry":     { "keep" : 20 }
                }
            }
        },
        {
            "type": "CatchVisiblePokemon"
        },
        {
            "type": "CatchLuredPokemon"
        },
        {
            "type": "SpinFort"
        },
        {
            "type": "MoveToFort"
        },
        {
            "type": "FollowSpiral",
            "config": {
                "diameter": 4,
                "step_size": 70
            }
        }
    ],
    "map_object_cache_time": 5,
    "forts": {
        "avoid_circles": false,
        "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 8,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": false,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "logging_color": true,
    "catch": {
        "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or" }
    },
    "release": {
        "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or" },
        "Bulbasaur": { "release_below_cp": 788, "release_below_iv": 0.8, "logic": "and" },
        "Ivysaur": { "release_below_cp": 953, "release_below_iv": 0.8, "logic": "and" },
        "Blastoise": { "release_below_cp": 1426, "release_below_iv": 0.91, "logic": "and" },
        "Charmander": { "release_below_cp": 593, "release_below_iv": 0.8, "logic": "and" },
        "Charmeleon": { "release_below_cp": 924, "release_below_iv": 0.8, "logic": "and" },
        "Squirtle": { "release_below_cp": 730, "release_below_iv": 0.8, "logic": "and" },
        "Wartortle": { "release_below_cp": 891, "release_below_iv": 0.91, "logic": "and" },
        "Caterpie": { "release_below_cp": 316, "release_below_iv": 0.8, "logic": "and" },
        "Metapod": { "release_below_cp": 354, "release_below_iv": 0.84, "logic": "and" },
        "Butterfree": { "release_below_cp": 799, "release_below_iv": 0.84, "logic": "and" },
        "Weedle": { "release_below_cp": 315, "release_below_iv": 0.8, "logic": "and" },
        "Kakuna": { "release_below_cp": 307, "release_below_iv": 0.8, "logic": "and" },
        "Beedrill": { "release_below_cp": 859, "release_below_iv": 0.8, "logic": "and" },
        "Pidgey": { "release_below_cp": 507, "release_below_iv": 0.8, "logic": "and" },
        "Pidgeotto": { "release_below_cp": 918, "release_below_iv": 0.8, "logic": "and" },
        "Pidgeot": { "release_below_cp": 1565, "release_below_iv": 0.93, "logic": "and" },
        "Rattata": { "release_below_cp": 469, "release_below_iv": 0.89, "logic": "and" },
        "Raticate": { "release_below_cp": 1056, "release_below_iv": 0.96, "logic": "and" },
        "Spearow": { "release_below_cp": 548, "release_below_iv": 0.91, "logic": "and" },
        "Fearow": { "release_below_cp": 1559, "release_below_iv": 1, "logic": "and" },
        "Ekans": { "release_below_cp": 581, "release_below_iv": 0.84, "logic": "and" },
        "Arbok": { "release_below_cp": 731, "release_below_iv": 0.8, "logic": "and" },
        "Pikachu": { "release_below_cp": 487, "release_below_iv": 0.82, "logic": "and" },
        "Sandshrew": { "release_below_cp": 448, "release_below_iv": 0.8, "logic": "and" },
        "Nidoran F": { "release_below_cp": 0, "release_below_iv": 0.8, "logic": "and" },
        "Nidorina": { "release_below_cp": 891, "release_below_iv": 0.8, "logic": "and" },
        "Nidoqueen": { "release_below_cp": 1407, "release_below_iv": 0.8, "logic": "and" },
        "Nidoran M": { "release_below_cp": 649, "release_below_iv": 0.8, "logic": "and" },
        "Nidorino": { "release_below_cp": 847, "release_below_iv": 0.8, "logic": "and" },
        "Clefairy": { "release_below_cp": 937, "release_below_iv": 0.8, "logic": "and" },
        "Vulpix": { "release_below_cp": 631, "release_below_iv": 0.8, "logic": "and" },
        "Jigglypuff": { "release_below_cp": 676, "release_below_iv": 0.8, "logic": "and" },
        "Wigglytuff": { "release_below_cp": 1525, "release_below_iv": 0.89, "logic": "and" },
        "Zubat": { "release_below_cp": 488, "release_below_iv": 0.93, "logic": "and" },
        "Golbat": { "release_below_cp": 1485, "release_below_iv": 0.98, "logic": "and" },
        "Oddish": { "release_below_cp": 807, "release_below_iv": 0.84, "logic": "and" },
        "Gloom": { "release_below_cp": 1055, "release_below_iv": 0.89, "logic": "and" },
        "Vileplume": { "release_below_cp": 1397, "release_below_iv": 0.89, "logic": "and" },
        "Paras": { "release_below_cp": 710, "release_below_iv": 0.87, "logic": "and" },
        "Parasect": { "release_below_cp": 982, "release_below_iv": 0.91, "logic": "and" },
        "Venonat": { "release_below_cp": 841, "release_below_iv": 0.89, "logic": "and" },
        "Venomoth": { "release_below_cp": 1014, "release_below_iv": 0.91, "logic": "and" },
        "Diglett": { "release_below_cp": 272, "release_below_iv": 0.8, "logic": "and" },
        "Meowth": { "release_below_cp": 473, "release_below_iv": 0.82, "logic": "and" },
        "Psyduck": { "release_below_cp": 821, "release_below_iv": 0.91, "logic": "and" },
        "Golduck": { "release_below_cp": 1744, "release_below_iv": 0.8, "logic": "and" },
        "Mankey": { "release_below_cp": 516, "release_below_iv": 0.8, "logic": "and" },
        "Growlithe": { "release_below_cp": 730, "release_below_iv": 0.8, "logic": "and" },
        "Poliwag": { "release_below_cp": 606, "release_below_iv": 0.89, "logic": "and" },
        "Poliwhirl": { "release_below_cp": 895, "release_below_iv": 0.89, "logic": "and" },
        "Poliwrath": { "release_below_cp": 1936, "release_below_iv": 0.91, "logic": "and" },
        "Abra": {"release_below_cp": 234, "release_below_iv": 0.8, "logic": "or" },
        "Kadabra": { "release_below_cp": 732, "release_below_iv": 0.8, "logic": "and" },
        "Alakazam": { "release_below_cp": 1157, "release_below_iv": 0.8, "logic": "and" },
        "Machop": { "release_below_cp": 870, "release_below_iv": 0.87, "logic": "and" },
        "Machoke": { "release_below_cp": 0, "release_below_iv": 0.8, "logic": "and" },
        "Bellsprout": { "release_below_cp": 771, "release_below_iv": 0.8, "logic": "and" },
        "Weepinbell": { "release_below_cp": 1160, "release_below_iv": 0.8, "logic": "and" },
        "Tentacool": { "release_below_cp": 643, "release_below_iv": 0.8, "logic": "and" },
        "Tentacruel": { "release_below_cp": 1378, "release_below_iv": 0.8, "logic": "and" },
        "Geodude": { "release_below_cp": 459, "release_below_iv": 0.8, "logic": "and" },
        "Graveler": { "release_below_cp": 54, "release_below_iv": 0.8, "logic": "and" },
        "Ponyta": { "release_below_cp": 1113, "release_below_iv": 0.8, "logic": "and" },
        "Slowpoke": { "release_below_cp": 911, "release_below_iv": 0.8, "logic": "and" },
        "Slowbro": { "release_below_cp": 0, "release_below_iv": 0.8, "logic": "and" },
        "Magnemite": { "release_below_cp": 559, "release_below_iv": 0.8, "logic": "and" },
        "Doduo": { "release_below_cp": 544, "release_below_iv": 0.8, "logic": "and" },
        "Dodrio": { "release_below_cp": 1469, "release_below_iv": 0.8, "logic": "and" },
        "Seel": { "release_below_cp": 613, "release_below_iv": 0.8, "logic": "and" },
        "Dewgong": { "release_below_cp": 1259, "release_below_iv": 0.8, "logic": "and" },
        "Grimer": { "release_below_cp": 816, "release_below_iv": 0.8, "logic": "and" },
        "Shellder": { "release_below_cp": 592, "release_below_iv": 0.8, "logic": "and" },
        "Cloyster": { "release_below_cp": 1378, "release_below_iv": 0.8, "logic": "and"},
        "Gastly": { "release_below_cp": 612, "release_below_iv": 0.89, "logic": "and" },
        "Haunter": { "release_below_cp": 862, "release_below_iv": 0.8, "logic": "and" },
        "Gengar": { "release_below_cp": 1461, "release_below_iv": 0.91, "logic": "and" },
        "Onix": { "release_below_cp": 557, "release_below_iv": 0.8, "logic": "and" },
        "Drowzee": { "release_below_cp": 877, "release_below_iv": 0.91, "logic": "and" },
        "Hypno": { "release_below_cp": 0, "release_below_iv": 0.96, "logic": "and" },
        "Krabby": { "release_below_cp": 605, "release_below_iv": 0.89, "logic": "and" },
        "Kingler": { "release_below_cp": 1253, "release_below_iv": 0.93, "logic": "and" },
        "Voltorb": { "release_below_cp": 542, "release_below_iv": 0.8, "logic": "and" },
        "Exeggcute": { "release_below_cp": 854, "release_below_iv": 0.84, "logic": "and" },
        "Exeggutor": { "release_below_cp": 1075, "release_below_iv": 0.84, "logic": "and" },
        "Cubone": { "release_below_cp": 695, "release_below_iv": 0.96, "logic": "and" },
        "Marowak": { "release_below_cp": 901, "release_below_iv": 0.96, "logic": "and" },
        "Hitmonlee": { "release_below_cp": 326, "release_below_iv": 0.84, "logic": "and" },
        "Koffing": { "release_below_cp": 908, "release_below_iv": 0.89, "logic": "and" },
        "Weezing": { "release_below_cp": 1683, "release_below_iv": 0.91, "logic": "and" },
        "Rhyhorn": { "release_below_cp": 987, "release_below_iv": 0.84, "logic": "and" },
        "Rhydon": { "release_below_cp": 1247, "release_below_iv": 0.93, "logic": "and" },
        "Tangela": { "release_below_cp": 1282, "release_below_iv": 0.84, "logic": "and" },
        "Horsea": { "release_below_cp": 623, "release_below_iv": 0.96, "logic": "and" },
        "Seadra": { "release_below_cp": 1505, "release_below_iv": 1, "logic": "and" },
        "Goldeen": { "release_below_cp": 760, "release_below_iv": 0.93, "logic": "and" },
        "Seaking": { "release_below_cp": 1357, "release_below_iv": 0.93, "logic": "and" },
        "Staryu": { "release_below_cp": 732, "release_below_iv": 0.96, "logic": "and" },
        "Starmie": { "release_below_cp": 1910, "release_below_iv": 0.98, "logic": "and" },
        "Scyther": { "release_below_cp": 1225, "release_below_iv": 0.89, "logic": "and" },
        "Jynx": { "release_below_cp": 1383, "release_below_iv": 0.93, "logic": "and" },
        "Electabuzz": { "release_below_cp": 1550, "release_below_iv": 0.89, "logic": "and" },
        "Magmar": { "release_below_cp": 1772, "release_below_iv": 0.8, "logic": "and" },
        "Pinsir": { "release_below_cp": 1691, "release_below_iv": 0.98, "logic": "and" },
        "Magikarp": { "release_below_cp": 200, "release_below_iv": 0.98, "logic": "and" },
        "Gyarados": { "release_below_cp": 2082, "release_below_iv": 0.87, "logic": "and" },
        "Lapras": { "release_below_cp": 1662, "release_below_iv": 0.87, "logic": "and" },
        "Eevee": { "release_below_cp": 851, "release_below_iv": 0.89, "logic": "and" },
        "Vaporeon": { "release_below_cp": 1421, "release_below_iv": 0.84, "logic": "and" },
        "Jolteon": { "release_below_cp": 1403, "release_below_iv": 0.96, "logic": "and" },
        "Flareon": { "release_below_cp": 1916, "release_below_iv": 0.82, "logic": "and" },
        "Porygon": { "release_below_cp": 485, "release_below_iv": 0.8, "logic": "and" },
        "Omanyte": { "release_below_cp": 862, "release_below_iv": 0.8, "logic": "and" },
        "Aerodactyl": { "release_below_cp": 1662, "release_below_iv": 0.8, "logic": "and" },
        "Snorlax": { "release_below_cp": 1308, "release_below_iv": 0.8, "logic": "and" },
        "Kabuto": { "release_below_cp": 602, "release_below_iv": 0.8, "logic": "and" },
        "Dratini": { "release_below_cp": 710, "release_below_iv": 0.8, "logic": "and" },
        "Dragonair": { "release_below_cp": 0, "release_below_iv": 0.8, "logic": "and" },
        "Dragonite": { "release_below_cp": 1691, "release_below_iv": 0.96, "logic": "and" }
    },
    "vips" : {
        "any": {"catch_above_cp": 1600, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    }
}
```

### Steps to Reproduce
Start the bot

### Other Information
OS: OS X
Git Commit: `b8ea3681013b152f472fcec89b9d83436e33cff8`
Python Version: `Python 2.7.12`

**Comment by kimonniez** [comment]
Have same problem after git pull few minutes ago. Total reinstall not helps too.

My OS Ubuntu 14.04.4 LTS 
Commit ac07ad368c3d11d8b2cca2cdd9e18b7395054514
Python 2.7.6

```
Traceback (most recent call last):
  File "pokecli.py", line 559, in <module>
    main()
  File "pokecli.py", line 83, in main
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "/home/ka_brus/pogo/dev/kirill/PokemonGo-Bot/pokemongo_bot/tree_config_builder.py", line 43, in build
    worker = self._get_worker_by_name(task_type)
  File "/home/ka_brus/pogo/dev/kirill/PokemonGo-Bot/pokemongo_bot/tree_config_builder.py", line 21, in _get_worker_by_name
    raise ConfigException('No worker named {} defined'.format(name))
pokemongo_bot.tree_config_builder.ConfigException: No worker named UpdateTitleStats defined
2016-08-12 11:53:08,034 [sentry.errors] [ERROR] Sentry responded with an error: 'module' object has no attribute 'HTTPSHandler' (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/ka_brus/pogo/dev/kirill/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/ka_brus/pogo/dev/kirill/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/ka_brus/pogo/dev/kirill/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 44, in urlopen
    class ValidHTTPSHandler(urllib2.HTTPSHandler):
AttributeError: 'module' object has no attribute 'HTTPSHandler'
2016-08-12 11:53:08,034 [sentry.errors.uncaught] [ERROR] [u'ConfigException: No worker named UpdateTitleStats defined', u'  File "pokecli.py", line 559, in <module>', u'  File "pokecli.py", line 83, in main', u'  File "pokemongo_bot/tree_config_builder.py", line 43, in build', u'  File "pokemongo_bot/tree_config_builder.py", line 21, in _get_worker_by_name']

```

**Comment by kimonniez** [comment]
this commit throw exception too 50cd7bf243eab90b88a2d8bd99e105b39647f331 (last commit)

**Comment by k4n30** [comment]
#3667
