### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by angnaybr** [PokemonGoF/PokemonGo-Bot#3713]
Hello there,

After succesful login i'm getting this message, i searched all issues but cannot succeeded.
Any help is appreciated
```
2016-08-12 12:17:50,272 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-12 12:17:50,291 [       cli] [INFO] Configuration initialized
2016-08-12 12:17:50,291 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-12 12:17:50,291 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-12 12:17:50,629 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-12 12:17:53,142 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-12 12:17:53,143 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-12 12:17:53,143 [PokemonGoBot] [INFO] [location_found] Location found: 41.007782, 28.979013 (41.007782, 28.979013, 0.0)
2016-08-12 12:17:53,143 [PokemonGoBot] [INFO] [position_update] Now at (41.007782, 28.979013, 0)
2016-08-12 12:17:53,153 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-12 12:18:02,205 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-12 12:18:03,980 [PokemonGoBot] [INFO] 
2016-08-12 12:18:03,981 [PokemonGoBot] [INFO] --- userxxx ---
2016-08-12 12:18:03,981 [PokemonGoBot] [INFO] Level: 21 (Next Level: 55143 XP) (Total: 279857 XP)
2016-08-12 12:18:03,981 [PokemonGoBot] [INFO] Pokemon Captured: 882 | Pokestops Visited: 1126
2016-08-12 12:18:03,982 [PokemonGoBot] [INFO] Pokemon Bag: 16/250
2016-08-12 12:18:03,982 [PokemonGoBot] [INFO] Items: 248/350
2016-08-12 12:18:03,982 [PokemonGoBot] [INFO] Stardust: 50095 | Pokecoins: 10
2016-08-12 12:18:03,982 [PokemonGoBot] [INFO] PokeBalls: 50 | GreatBalls: 98 | UltraBalls: 43
2016-08-12 12:18:03,982 [PokemonGoBot] [INFO] RazzBerries: 50 | BlukBerries: 0 | NanabBerries: 0
2016-08-12 12:18:03,983 [PokemonGoBot] [INFO] LuckyEgg: 2 | Incubator: 0 | TroyDisk: 3
2016-08-12 12:18:03,983 [PokemonGoBot] [INFO] Potion: 0 | SuperPotion: 0 | HyperPotion: 0 | MaxPotion: 0
2016-08-12 12:18:03,983 [PokemonGoBot] [INFO] Incense: 0 | IncenseSpicy: 0 | IncenseCool: 0
2016-08-12 12:18:03,983 [PokemonGoBot] [INFO] Revive: 0 | MaxRevive: 0
2016-08-12 12:18:03,983 [PokemonGoBot] [INFO] 
2016-08-12 12:18:03,983 [PokemonGoBot] [INFO] Found encrypt.so! Platform: darwin Encrypt.so directory: /Users/userxxx/Downloads/PokemonGo-Bot-master
2016-08-12 12:18:03,983 [PokemonGoBot] [INFO] 
2016-08-12 12:18:07,845 [SleepSchedule] [INFO] [next_sleep] Next sleep at 2016-08-12 22:50:45.826621
2016-08-12 12:18:09,406 [       cli] [INFO] 
2016-08-12 12:18:09,407 [       cli] [INFO] Ran for 0:00:16
2016-08-12 12:18:09,407 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-12 12:18:09,407 [       cli] [INFO] Travelled 0.00km
2016-08-12 12:18:09,407 [       cli] [INFO] Visited 0 stops
2016-08-12 12:18:09,407 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-12 12:18:09,407 [       cli] [INFO] Threw 0 pokeballs
2016-08-12 12:18:09,407 [       cli] [INFO] Earned 0 Stardust
2016-08-12 12:18:09,407 [       cli] [INFO] 
2016-08-12 12:18:09,407 [       cli] [INFO] Highest CP Pokemon: 
2016-08-12 12:18:09,408 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 514, in <module>
    main()
  File "pokecli.py", line 83, in main
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "/Users/userxxx/Downloads/PokemonGo-Bot-master/pokemongo_bot/tree_config_builder.py", line 43, in build
    worker = self._get_worker_by_name(task_type)
  File "/Users/userxxx/Downloads/PokemonGo-Bot-master/pokemongo_bot/tree_config_builder.py", line 21, in _get_worker_by_name
    raise ConfigException('No worker named {} defined'.format(name))
pokemongo_bot.tree_config_builder.ConfigException: No worker named UpdateLiveStats defined
2016-08-12 12:18:09,494 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/userxxx/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/userxxx/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/userxxx/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/userxxx/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/userxxx/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/userxxx/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/userxxx/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/userxxx/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-12 12:18:09,569 [sentry.errors.uncaught] [ERROR] [u'ConfigException: No worker named UpdateLiveStats defined', u'  File "pokecli.py", line 514, in <module>', u'  File "pokecli.py", line 83, in main', u'  File "pokemongo_bot/tree_config_builder.py", line 43, in build', u'  File "pokemongo_bot/tree_config_builder.py", line 21, in _get_worker_by_name']
```

### Your config.json (remove your credentials and any other private info)
```
{
    "auth_service": "google",
    "username": "userxxx@gmail.com",
    "password": "userxxx",
    "location": "location",
    "gmapkey": "gmapkey",
    "libencrypt_location": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "22:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 10 },
            "Hyper Potion":   { "keep" : 10 },
            "Revive":         { "keep" : 10 },
            "Razz Berry":     { "keep" : 50 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}
```

### Other Information
OS: OSX Yosemite 10.10.5
Git Commit: fatal: Not a git repository (or any of the parent directories): .git
Python Version: Python 2.7.12

**Comment by nivong** [comment]
Git Commit: fatal: Not a git repository (or any of the parent directories): .git
are you running the latest version?

**Comment by angnaybr** [comment]
i installed 2.9.2 of Git for the Mac
but when i entered command - git log -n 1 --pretty=format:"%H" - in terminal i get message "Not a git repository (or any of the parent directories): .git"

**Comment by nivong** [comment]
are you doing that command in the root of the bot folder ?

**Comment by angnaybr** [comment]
in which folder i have to try? i tried in PokemonGo-Bot-master folder too

**Comment by nivong** [comment]
I would suggest than to restart.

**Comment by angnaybr** [comment]
i reinstalled and get this error, any suggestions?

2016-08-12 13:21:00,610 [PokemonGoBot] [ERROR] encrypt.so is not found! Please place it in the bots root directory or set libencrypt_location in config.
2016-08-12 13:21:00,610 [PokemonGoBot] [INFO] Platform: darwin Encrypt.so directory: /Users/userxxx/PokemonGo-Bot

**Comment by fari-99** [comment]
use slack chat. there is file you need in there.

**Comment by nivong** [comment]
or just follow the install instructions...

**Comment by angnaybr** [comment]
yep i succeeded thanks!
