### ISSUE TITLE
bot exits unexpectedly.

### ISSUE THREAD

**Issue by spoxus** [PokemonGoF/PokemonGo-Bot#3745]
I think it's a bug.

2016-08-12 04:39:34,595 [TransferPokemon] [INFO] [pokemon_release] Exchanged Weedle [CP 99] [IV 0.42] for candy.
2016-08-12 04:39:37,177 [       cli] [INFO]
2016-08-12 04:39:37,177 [       cli] [INFO] Ran for 2:35:34
2016-08-12 04:39:37,177 [       cli] [INFO] Total XP Earned: 21660  Average: 8353.90/h
2016-08-12 04:39:37,177 [       cli] [INFO] Travelled 3.48km
2016-08-12 04:39:37,177 [       cli] [INFO] Visited 93 stops
2016-08-12 04:39:37,177 [       cli] [INFO] Encountered 68 pokemon, 66 caught, 68 released, 5 evolved, 0 never seen before
2016-08-12 04:39:37,177 [       cli] [INFO] Threw 79 pokeballs
2016-08-12 04:39:37,177 [       cli] [INFO] Earned 7093 Stardust
2016-08-12 04:39:37,177 [       cli] [INFO]
2016-08-12 04:39:37,177 [       cli] [INFO] Highest CP Pokemon: Exeggcute [CP: 797] [IV: 10/12/12] Potential: 0.76
2016-08-12 04:39:37,177 [       cli] [INFO] Most Perfect Pokemon: Venonat [CP: 490] [IV: 14/14/13] Potential: 0.91
Traceback (most recent call last):
  File "pokecli.py", line 559, in <module>
    main()
  File "pokecli.py", line 96, in main
    bot.tick()
  File "E:\downloads\PokemonGo-Bot\pokemongo_bot\__init__.py", line 468, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "E:\downloads\PokemonGo-Bot\pokemongo_bot\cell_workers\evolve_pokemon.py", line 38, in work
    self._execute_pokemon_evolve(pokemon, cache)
  File "E:\downloads\PokemonGo-Bot\pokemongo_bot\cell_workers\evolve_pokemon.py", line 101, in _execute_pokemon_evolve
    response_dict = self.api.evolve_pokemon(pokemon_id=pokemon.id)
  File "e:\downloads\pokemongo-bot-desktop\gofbot\src\pgoapi\pgoapi\pgoapi.py", line 122, in function
    return request.call()
  File "E:\downloads\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 106, in call
    result = self._call()
  File "E:\downloads\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "e:\downloads\pokemongo-bot-desktop\gofbot\src\pgoapi\pgoapi\pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "e:\downloads\pokemongo-bot-desktop\gofbot\src\pgoapi\pgoapi\rpc_api.py", line 126, in request
    request_proto = self._build_main_request(subrequests, player_position)
  File "e:\downloads\pokemongo-bot-desktop\gofbot\src\pgoapi\pgoapi\rpc_api.py", line 216, in _build_main_request
    request.auth_info.token.contents = self._auth_provider.get_access_token()
  File "D:\p\Python\lib\site-packages\google\protobuf\internal\python_message.py", line 669, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "D:\p\Python\lib\site-packages\google\protobuf\internal\type_checkers.py", line 176, in CheckValue
    raise TypeError(message)
TypeError: None has type <type 'NoneType'>, but expected one of: (<type 'str'>, <type 'unicode'>)

**Comment by k4n30** [comment]
Please read before you delete the text in the issue template, you're missing key information which would help us to help you

**Comment by IanFang** [comment]
This seems same as #3078 
It also happens to me as I posted in #3078
