### ISSUE TITLE
geopy/format.py

### ISSUE THREAD

**Issue by cywang886** [PokemonGoF/PokemonGo-Bot#3752]
[root@cnetos6 PokemonGo-Bot]# ./run.sh 
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 47, in <module>
    from pgoapi.utilities import to_camel_case, get_time, get_format_time_diff, Rand48, long_to_bytes, generateLocation1, generateLocation2, generateRequestHash, f2i
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/utilities.py", line 38, in <module>
    from geopy.geocoders import GoogleV3
  File "/usr/lib/python2.6/site-packages/geopy/__init__.py", line 11, in <module>
    from geopy.point import Point
  File "/usr/lib/python2.6/site-packages/geopy/point.py", line 9, in <module>
    from geopy.format import (
  File "/usr/lib/python2.6/site-packages/geopy/format.py", line 119
    for n, d
      ^
SyntaxError: invalid syntax
Fri Aug 12 23:59:50 CST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

==============================
What's wrong ?

**Comment by DayBr3ak** [comment]
You are using python2.6 that's what is wrong. go and install the latest python 2.7

**Comment by GitPupper** [comment]
#3682 - [**META** Server busy or offline issues](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3682) **Your issue**
#3308 - [**META** Stuck between two forts / Moving to 2 forts at the same time / Constant Loop](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3308)
#3700 - [**META** Soft bans - Try again spins / Pokemon vanishing](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3700)
#3746 - [**META** Banwaves - Permanent Bans](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3746)
