### ISSUE TITLE
ERROR  File "pokecli.py", line 41, in <module>

### ISSUE THREAD

**Issue by daybreakgaming** [PokemonGoF/PokemonGo-Bot#3757]
(PokemonGo-Bot) sh-3.2# ./run.sh
Traceback (most recent call last):
  File "pokecli.py", line 41, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "/Users/lars/PokemonGo-Bot/pokemongo_bot/__init__.py", line 309
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
Fri Aug 12 18:44:13 CEST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

I get this whenever I do ./run.sh
whats wrong?

**Comment by Biromain** [comment]
Merge conflict? Simple way is backup configs, delete all and clone again.

**Comment by daybreakgaming** [comment]
I deleted all, and reinstalled.
now I get this error
`2016-08-12 19:55:56,321 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-12 19:55:56,434 [       cli] [INFO] Configuration initialized
2016-08-12 19:55:56,434 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-12 19:55:56,434 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-12 19:55:56,829 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com

[19:55:57] Setting start location.Traceback (most recent call last):
  File "pokecli.py", line 514, in <module>
    main()
  File "pokecli.py", line 138, in main
    report_summary(bot)
  File "pokecli.py", line 147, in report_summary
    metrics.capture_stats()
  File "/Users/lars/PokemonGo-Bot/pokemongo_bot/metrics.py", line 84, in capture_stats
    response_dict = request.call()
  File "/Users/lars/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 90, in call
    if not self.can_call():
  File "/Users/lars/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 54, in can_call
    raise NoPlayerPositionSetException()
pgoapi.exceptions.NoPlayerPositionSetException
2016-08-12 19:55:57,325 [sentry.errors] [ERROR] Sentry responded with an error: 'module' object has no attribute 'HTTPSHandler' (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Library/Python/2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Library/Python/2.7/site-packages/raven/utils/http.py", line 44, in urlopen
    class ValidHTTPSHandler(urllib2.HTTPSHandler):
AttributeError: 'module' object has no attribute 'HTTPSHandler'
2016-08-12 19:55:57,326 [sentry.errors.uncaught] [ERROR] [u'NoPlayerPositionSetException', u'  File "pokecli.py", line 514, in <module>', u'  File "pokecli.py", line 138, in main', u'  File "pokecli.py", line 147, in report_summary', u'  File "pokemongo_bot/metrics.py", line 84, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 90, in call', u'  File "pokemongo_bot/api_wrapper.py", line 54, in can_call']`

**Comment by leadboots5** [comment]
try "health_record": false in your config.

**Comment by k4n30** [comment]
#3679
