### ISSUE TITLE
Server seems to be busy or offline

### ISSUE THREAD

**Issue by harrylevn** [PokemonGoF/PokemonGo-Bot#3768]
Hi all

Please help me!

2016-08-13 01:10:15,992 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 15/15
Traceback (most recent call last):
  File "pokecli.py", line 530, in <module>
    main()
  File "pokecli.py", line 138, in main
    report_summary(bot)
  File "pokecli.py", line 147, in report_summary
    metrics.capture_stats()
  File "/Users/harry/Documents/PokemonBOT/PokemonGo-Bot-master/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/Users/harry/Documents/PokemonBOT/PokemonGo-Bot-master/pokemongo_bot/api_wrapper.py", line 133, in call
    raise ServerBusyOrOfflineException()
pgoapi.exceptions.ServerBusyOrOfflineException
Sat Aug 13 01:10:16 ICT 2016 Pokebot  Stopped.

**Comment by DayBr3ak** [comment]
You are banned?

**Comment by larssy1** [comment]
Same here,, it just makes 15 attempts to connect and then fails .

2016-08-12 20:12:42,921 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 4/15
2016-08-12 20:12:44,282 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 5/15
2016-08-12 20:12:45,372 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 6/15
2016-08-12 20:12:46,490 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 7/15
2016-08-12 20:12:47,664 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 8/15
2016-08-12 20:12:49,082 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 9/15
2016-08-12 20:12:50,315 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 10/15
2016-08-12 20:12:51,601 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 11/15
2016-08-12 20:12:52,815 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 12/15
2016-08-12 20:12:54,214 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 13/15
2016-08-12 20:12:55,207 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 14/15
2016-08-12 20:12:56,299 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 15/15
Traceback (most recent call last):

**Comment by iidanielmontes** [comment]
I'm banned too...

**Comment by vicheanak** [comment]
http://www.polygon.com/2016/8/12/12454478/pokemon-go-permanent-ban-bot-programs-shut-down

**Comment by ponytails** [comment]
i create new account and still cant connect... using new ip..

**Comment by GitPupper** [comment]
#3682 - [**META** Server busy or offline issues](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3682)
#3308 - [**META** Stuck between two forts / Moving to 2 forts at the same time / Constant Loop](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3308)
#3700 - [**META** Soft bans - Try again spins / Pokemon vanishing](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3700)
#3746 - [**META** Banwaves - Permanent Bans](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3746)
