### ISSUE TITLE
bot stop with error

### ISSUE THREAD

**Issue by buzzo123** [PokemonGoF/PokemonGo-Bot#3769]
the bot crash with this error:

```
Traceback (most recent call last):
  File "pokecli.py", line 514, in <module>
    main()
  File "pokecli.py", line 96, in main
    bot.tick()
  File "/home/buzzo/Desktop/pogo/PokemonGo-Bot-master/pokemongo_bot/__init__.py", line 468, in tick
    self.cell = self.get_meta_cell()
  File "/home/buzzo/Desktop/pogo/PokemonGo-Bot-master/pokemongo_bot/__init__.py", line 480, in get_meta_cell
    cells = self.find_close_cells(*location)
  File "/home/buzzo/Desktop/pogo/PokemonGo-Bot-master/pokemongo_bot/__init__.py", line 554, in find_close_cells
    response_dict = self.get_map_objects(lat, lng, timestamp, cellid)
  File "/home/buzzo/Desktop/pogo/PokemonGo-Bot-master/pokemongo_bot/__init__.py", line 1098, in get_map_objects
    cell_id=cellid
  File "/home/buzzo/Desktop/pogo/PokemonGo-Bot-master/src/pgoapi/pgoapi/pgoapi.py", line 122, in function
    return request.call()
  File "/home/buzzo/Desktop/pogo/PokemonGo-Bot-master/pokemongo_bot/api_wrapper.py", line 106, in call
    result = self._call()
  File "/home/buzzo/Desktop/pogo/PokemonGo-Bot-master/pokemongo_bot/api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "/home/buzzo/Desktop/pogo/PokemonGo-Bot-master/src/pgoapi/pgoapi/pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/home/buzzo/Desktop/pogo/PokemonGo-Bot-master/src/pgoapi/pgoapi/rpc_api.py", line 127, in request
    response = self._make_rpc(endpoint, request_proto)
  File "/home/buzzo/Desktop/pogo/PokemonGo-Bot-master/src/pgoapi/pgoapi/rpc_api.py", line 115, in _make_rpc
    http_response = self._session.post(endpoint, data=request_proto_serialized, timeout=30)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 617, in send
    r.content
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 664, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 349, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 501, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 461, in _handle_chunk
    value = self._fp._safe_read(amt)
  File "/usr/lib/python2.7/httplib.py", line 703, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/green/ssl.py", line 200, in recv
    read = self.read(buflen)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/green/ssl.py", line 139, in read
    super(GreenSSLSocket, self).read, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/green/ssl.py", line 119, in _call_trampolining
    timeout_exc=timeout_exc('timed out'))
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/__init__.py", line 162, in trampoline
    return hub.switch()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/hub.py", line 294, in switch
    return self.greenlet.switch()
ssl.SSLError: ('timed out',)
2016-08-12 20:08:57,044 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-12 20:08:57,045 [sentry.errors.uncaught] [ERROR] [u"SSLError: ('timed out',)", u'  File "pokecli.py", line 514, in <module>', u'  File "pokecli.py", line 96, in main', u'  File "pokemongo_bot/__init__.py", line 468, in tick', u'  File "pokemongo_bot/__init__.py", line 480, in get_meta_cell', u'  File "pokemongo_bot/__init__.py", line 554, in find_close_cells', u'  File "pokemongo_bot/__init__.py", line 1098, in get_map_objects', u'  File "pgoapi/pgoapi.py", line 122, in function', u'  File "pokemongo_bot/api_wrapper.py", line 106, in call', u'  File "pokemongo_bot/api_wrapper.py", line 63, in _call', u'  File "pgoapi/pgoapi.py", line 220, in call', u'  File "pgoapi/rpc_api.py", line 127, in request', u'  File "pgoapi/rpc_api.py", line 115, in _make_rpc', u'  File "requests/sessions.py", line 518, in post', u'  File "requests/sessions.py", line 475, in request', u'  File "requests/sessions.py", line 617, in send', u'  File "requests/models.py", line 741, in content', u'  File "requests/models.py", line 664, in generate', u'  File "requests/packages/urllib3/response.py", line 349, in stream', u'  File "requests/packages/urllib3/response.py", line 501, in read_chunked', u'  File "requests/packages/urllib3/response.py", line 461, in _handle_chunk', u'  File "python2.7/httplib.py", line 703, in _safe_read', u'  File "python2.7/socket.py", line 384, in read', u'  File "eventlet/green/ssl.py", line 200, in recv', u'  File "eventlet/green/ssl.py", line 139, in read', u'  File "eventlet/green/ssl.py", line 119, in _call_trampolining', u'  File "eventlet/hubs/__init__.py", line 162, in trampoline', u'  File "eventlet/hubs/hub.py", line 294, in switch']

```

**Comment by nivong** [comment]
use the template that is being provided for you or we can't help you....

**Comment by GitPupper** [comment]
Search the closed issues for encrypt.so. Duplicate.
