### ISSUE TITLE
urllib3

### ISSUE THREAD

**Issue by srobayo222** [PokemonGoF/PokemonGo-Bot#3777]
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
  File "c:\users\juan sebastian\downloads\pokemongo-bot\src\pgoapi\pgoapi\__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "c:\users\juan sebastian\downloads\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 31, in <module>
    import requests
  File "C:\Python27\lib\site-packages\requests\__init__.py", line 61, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "C:\Python27\lib\site-packages\requests\packages\__init__.py", line 29, in <module>
    import urllib3
ImportError: No module named urllib3

his errors happens when i run the bot D: 
Anyone knows?

**Comment by nivong** [comment]
use the template that is being provided for you or we can't help you....
