### ISSUE TITLE
Pokecil.py error

### ISSUE THREAD

**Issue by xLemonice** [PokemonGoF/PokemonGo-Bot#3818]
### Your config.json (remove your credentials and any other private info)
```
"tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "item_filter": {
          
          
            "Pokeball":       { "keep" : 50 },
            "Greatball":      { "keep" : 50 },
            "Ultraball":      { "keep" : 50 },
            
         
            "Potion":         { "keep" : 1 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            
       
            "Revive":         { "keep" : 10 },
            "Razz Berry":     { "keep" : 50 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "//any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or" , "keep_best_cp": 3 },
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "any": {"keep_best_iv": 2},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}
```

###Error on cmd

> Traceback (most recent call last):
>   File "pokecli.py", line 514, in <module>
>     main()
>   File "pokecli.py", line 96, in main
>     bot.tick()
>   File "C:\Users\xLemonX\PokemonGo-Bot\pokemongo_bot\__init__.py", line 475, in tick
>     if worker.work() == WorkerResult.RUNNING:
>   File "C:\Users\xLemonX\PokemonGo-Bot\pokemongo_bot\cell_workers\transfer_pokemon.py", line 14, in work
>     pokemon_groups = self._release_pokemon_get_groups()
>   File "C:\Users\xLemonX\PokemonGo-Bot\pokemongo_bot\cell_workers\transfer_pokemon.py", line 69, in _release_pokemon_get_groups
>     for pokemon in inventory.pokemons(True).all():
>   File "C:\Users\xLemonX\PokemonGo-Bot\pokemongo_bot\inventory.py", line 828, in pokemons
>     refresh_inventory()
>   File "C:\Users\xLemonX\PokemonGo-Bot\pokemongo_bot\inventory.py", line 813, in refresh_inventory
>     _inventory.refresh()
>   File "C:\Users\xLemonX\PokemonGo-Bot\pokemongo_bot\inventory.py", line 757, in refresh
>     inventory = self.bot.get_inventory()['responses']['GET_INVENTORY']['inventory_delta']['inventory_items']
>   File "C:\Users\xLemonX\PokemonGo-Bot\pokemongo_bot\__init__.py", line 794, in get_inventory
>     self.latest_inventory = self.api.get_inventory()
>   File "c:\users\xlemonx\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 122, in function
>     return request.call()
>   File "C:\Users\xLemonX\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 106, in call
>     result = self._call()
>   File "C:\Users\xLemonX\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 63, in _call
>     return PGoApiRequest.call(self)
>   File "c:\users\xlemonx\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 220, in call
>     response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
>   File "c:\users\xlemonx\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 127, in request
>     response = self._make_rpc(endpoint, request_proto)
>   File "c:\users\xlemonx\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 115, in _make_rpc
>     http_response = self._session.post(endpoint, data=request_proto_serialized, timeout=30)
>   File "D:\Python27\lib\site-packages\requests\sessions.py", line 518, in post
>     return self.request('POST', url, data=data, json=json, **kwargs)
>   File "D:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
>     resp = self.send(prep, **send_kwargs)
>   File "D:\Python27\lib\site-packages\requests\sessions.py", line 617, in send
>     r.content
>   File "D:\Python27\lib\site-packages\requests\models.py", line 741, in content
>     self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
>   File "D:\Python27\lib\site-packages\requests\models.py", line 664, in generate
>     for chunk in self.raw.stream(chunk_size, decode_content=True):
>   File "D:\Python27\lib\site-packages\requests\packages\urllib3\response.py", line 349, in stream
>     for line in self.read_chunked(amt, decode_content=decode_content):
>   File "D:\Python27\lib\site-packages\requests\packages\urllib3\response.py", line 501, in read_chunked
>     chunk = self._handle_chunk(amt)
>   File "D:\Python27\lib\site-packages\requests\packages\urllib3\response.py", line 470, in _handle_chunk
>     returned_chunk = self._fp._safe_read(self.chunk_left)
>   File "D:\Python27\lib\httplib.py", line 703, in _safe_read
>     chunk = self.fp.read(min(amt, MAXAMOUNT))
>   File "D:\Python27\lib\socket.py", line 384, in read
>     data = self._sock.recv(left)
>   File "D:\Python27\lib\site-packages\eventlet\green\ssl.py", line 200, in recv
>     read = self.read(buflen)
>   File "D:\Python27\lib\site-packages\eventlet\green\ssl.py", line 139, in read
>     super(GreenSSLSocket, self).read, *args, **kwargs)
>   File "D:\Python27\lib\site-packages\eventlet\green\ssl.py", line 113, in _call_trampolining
>     return func(*a, **kw)
>   File "D:\Python27\lib\ssl.py", line 643, in read
>     v = self._sslobj.read(len)
> ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1754)
> 2016-08-13 11:43:16,078 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
> Traceback (most recent call last):
>   File "D:\Python27\lib\site-packages\raven\transport\threaded.py", line 174, in send_sync
>     super(ThreadedHTTPTransport, self).send(data, headers)
>   File "D:\Python27\lib\site-packages\raven\transport\http.py", line 47, in send
>     ca_certs=self.ca_certs,
>   File "D:\Python27\lib\site-packages\raven\utils\http.py", line 66, in urlopen
>     return opener.open(url, data, timeout)
>   File "D:\Python27\lib\site-packages\future\backports\urllib\request.py", line 494, in open
>     response = self._open(req, data)
>   File "D:\Python27\lib\site-packages\future\backports\urllib\request.py", line 512, in _open
>     '_open', req)
>   File "D:\Python27\lib\site-packages\future\backports\urllib\request.py", line 466, in _call_chain
>     result = func(*args)
>   File "D:\Python27\lib\site-packages\raven\utils\http.py", line 46, in https_open
>     return self.do_open(ValidHTTPSConnection, req)
>   File "D:\Python27\lib\site-packages\future\backports\urllib\request.py", line 1284, in do_open
>     h.request(req.get_method(), req.selector, req.data, headers)
>   File "D:\Python27\lib\httplib.py", line 1057, in request
>     self._send_request(method, url, body, headers)
>   File "D:\Python27\lib\httplib.py", line 1097, in _send_request
>     self.endheaders(body)
>   File "D:\Python27\lib\httplib.py", line 1053, in endheaders
>     self._send_output(message_body)
>   File "D:\Python27\lib\httplib.py", line 895, in _send_output
>     msg += message_body
> UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
> 2016-08-13 11:43:16,079 [sentry.errors.uncaught] [ERROR] [u'SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1754)', u'  File "pokecli.py", line 514, in <module>', u'  File "pokecli.py", line 96, in main', u'  File "C:\\Users\\xLemonX\\PokemonGo-Bot\\pokemongo_bot\\__init__.py", line 475, in tick', u'  File "C:\\Users\\xLemonX\\PokemonGo-Bot\\pokemongo_bot\\cell_workers\\transfer_pokemon.py", line 14, in work', u'  File "C:\\Users\\xLemonX\\PokemonGo-Bot\\pokemongo_bot\\cell_workers\\transfer_pokemon.py", line 69, in _release_pokemon_get_groups', u'  File "C:\\Users\\xLemonX\\PokemonGo-Bot\\pokemongo_bot\\inventory.py", line 828, in pokemons', u'  File "C:\\Users\\xLemonX\\PokemonGo-Bot\\pokemongo_bot\\inventory.py", line 813, in refresh_inventory', u'  File "C:\\Users\\xLemonX\\PokemonGo-Bot\\pokemongo_bot\\inventory.py", line 757, in refresh', u'  File "C:\\Users\\xLemonX\\PokemonGo-Bot\\pokemongo_bot\\__init__.py", line 794, in get_inventory', u'  File "c:\\users\\xlemonx\\pokemongo-bot\\src\\pgoapi\\pgoapi\\pgoapi.py", line 122, in function', u'  File "C:\\Users\\xLemonX\\PokemonGo-Bot\\pokemongo_bot\\api_wrapper.py", line 106, in call', u'  File "C:\\Users\\xLemonX\\PokemonGo-Bot\\pokemongo_bot\\api_wrapper.py", line 63, in _call', u'  File "c:\\users\\xlemonx\\pokemongo-bot\\src\\pgoapi\\pgoapi\\pgoapi.py", line 220, in call', u'  File "c:\\users\\xlemonx\\pokemongo-bot\\src\\pgoapi\\pgoapi\\rpc_api.py", line 127, in request', u'  File "c:\\users\\xlemonx\\pokemongo-bot\\src\\pgoapi\\pgoapi\\rpc_api.py", line 115, in _make_rpc', u'  File "D:\\Python27\\lib\\site-packages\\requests\\sessions.py", line 518, in post', u'  File "D:\\Python27\\lib\\site-packages\\requests\\sessions.py", line 475, in request', u'  File "D:\\Python27\\lib\\site-packages\\requests\\sessions.py", line 617, in send', u'  File "D:\\Python27\\lib\\site-packages\\requests\\models.py", line 741, in content', u'  File "D:\\Python27\\lib\\site-packages\\requests\\models.py", line 664, in generate', u'  File "D:\\Python27\\lib\\site-packages\\requests\\packages\\urllib3\\response.py", line 349, in stream', u'  File "D:\\Python27\\lib\\site-packages\\requests\\packages\\urllib3\\response.py", line 501, in read_chunked', u'  File "D:\\Python27\\lib\\site-packages\\requests\\packages\\urllib3\\response.py", line 470, in _handle_chunk', u'  File "D:\\Python27\\lib\\httplib.py", line 703, in _safe_read', u'  File "D:\\Python27\\lib\\socket.py", line 384, in read', u'  File "D:\\Python27\\lib\\site-packages\\eventlet\\green\\ssl.py", line 200, in recv', u'  File "D:\\Python27\\lib\\site-packages\\eventlet\\green\\ssl.py", line 139, in read', u'  File "D:\\Python27\\lib\\site-packages\\eventlet\\green\\ssl.py", line 113, in _call_trampolining', u'  File "D:\\Python27\\lib\\ssl.py", line 643, in read']
> Sat Aug 13 11:43:16 MPST 2016 Pokebot  Stopped.
> Press any button or wait 20 seconds to continue.
> 2016-08-13 11:43:37,256 [       cli] [INFO] PokemonGO Bot v1.0
> 2016-08-13 11:43:37,256 [       cli] [WARNING] The evolve_captured argument is no longer supported. Please use the EvolvePokemon task instead
> 2016-08-13 11:43:37,257 [       cli] [INFO] Configuration initialized
> 2016-08-13 11:43:37,257 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
> 2016-08-13 11:43:37,257 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
> 2016-08-13 11:43:37,260 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
> 
> [11:43:37] Setting start location.2016-08-13 11:43:37,305 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.

### Other Information
OS: window 10 64bit
Branch: master
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by keugnu** [comment]
What is your current commit?

**Comment by xLemonice** [comment]
Git Commit : d4200e9b34ef6ec9826eb81a6ceb420162b8c674

**Comment by unnhao** [comment]
i have same problem :( OSX

**Comment by muskosan** [comment]
it's the new config. There are some bonked values in it.

**Comment by adityad123** [comment]
whats this error??????????????
Running pokecli.py for count: 0
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\eventlet\__init__.py", line 5, in <module>
    from eventlet import greenthread
  File "C:\Python27\lib\site-packages\eventlet\greenthread.py", line 4, in <module>
    from eventlet import event
  File "C:\Python27\lib\site-packages\eventlet\event.py", line 3, in <module>
    from eventlet import hubs
  File "C:\Python27\lib\site-packages\eventlet\hubs\__init__.py", line 3, in <module>
    from eventlet import patcher
  File "C:\Python27\lib\site-packages\eventlet\patcher.py", line 4, in <module>
    from eventlet.support import six
  File "C:\Python27\lib\site-packages\eventlet\support\__init__.py", line 4, in <module>
    from eventlet.support import greenlets, six
  File "C:\Python27\lib\site-packages\eventlet\support\greenlets.py", line 3, in <module>
    import greenlet
ImportError: DLL load failed: The specified procedure could not be found.
Traceback (most recent call last):
  File "pokecli.py", line 41, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "C:\Windows\System32\PokemonGo-Bot\pokemongo_bot\__init__.py", line 29, in <module>
    from pokemongo_bot.socketio_server.runner import SocketIoRunner
  File "C:\Windows\System32\PokemonGo-Bot\pokemongo_bot\socketio_server\runner.py", line 5, in <module>
    from eventlet import patcher, wsgi
  File "C:\Python27\lib\site-packages\eventlet\patcher.py", line 4, in <module>
    from eventlet.support import six
  File "C:\Python27\lib\site-packages\eventlet\support\__init__.py", line 4, in <module>
    from eventlet.support import greenlets, six
  File "C:\Python27\lib\site-packages\eventlet\support\greenlets.py", line 3, in <module>
    import greenlet
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by k4n30** [comment]
@xLemonice you can't be on master if that is your commit - it hasn't been merged to master yet. It is however the latest commit on dev.

@unnhao I see you are having the same issue, are you as well @muskosan ? Are you both on the latest dev commit?

**Comment by unnhao** [comment]
@k4n30  yes, but i use OSX
i trace the step ...
Is it possible that google api wrong? or....?

```


2016-08-13 23:07:55,268 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-13 23:07:55,271 [       cli] [INFO] Configuration initialized
2016-08-13 23:07:55,271 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-13 23:07:55,271 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-13 23:07:55,314 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com

[23:07:55] Setting start location.Traceback (most recent call last):
  File "pokecli.py", line 514, in <module>
    main()
  File "pokecli.py", line 138, in main
    report_summary(bot)
  File "pokecli.py", line 147, in report_summary
    metrics.capture_stats()
  File "/Users/lihao/Documents/node/PokemonGo-Bot/pokemongo_bot/metrics.py", line 84, in capture_stats
    response_dict = request.call()
  File "/Users/lihao/Documents/node/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 90, in call
    if not self.can_call():
  File "/Users/lihao/Documents/node/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 54, in can_call
    raise NoPlayerPositionSetException()
pgoapi.exceptions.NoPlayerPositionSetException
2016-08-13 23:07:56,534 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/lihao/Documents/node/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/lihao/Documents/node/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/lihao/Documents/node/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/lihao/Documents/node/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/lihao/Documents/node/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/lihao/Documents/node/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/lihao/Documents/node/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/lihao/Documents/node/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 891, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-13 23:07:56,540 [sentry.errors.uncaught] [ERROR] [u'NoPlayerPositionSetException', u'  File "pokecli.py", line 514, in <module>', u'  File "pokecli.py", line 138, in main', u'  File "pokecli.py", line 147, in report_summary', u'  File "pokemongo_bot/metrics.py", line 84, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 90, in call', u'  File "pokemongo_bot/api_wrapper.py", line 54, in can_call']
2016年 8月13日 周六 23時07分56秒 CST Pokebot configs/config.json Stopped.
Press any button or wait 20 seconds to continue.
```

**Comment by xLemonice** [comment]
any update for this?
still get error..but diffrent error

> Traceback (most recent call last):
  File "pokecli.py", line 609, in <module>
    main()
  File "pokecli.py", line 104, in main
    bot.tick()
  File "C:\Users\xLemonX\PokemonGo-Bot\pokemongo_bot\__init__.py", line 492, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "C:\Users\xLemonX\PokemonGo-Bot\pokemongo_bot\cell_workers\recycle_items.py", line 90, in work
    inventory.refresh_inventory()
  File "C:\Users\xLemonX\PokemonGo-Bot\pokemongo_bot\inventory.py", line 1172, in refresh_inventory
    _inventory.refresh()
  File "C:\Users\xLemonX\PokemonGo-Bot\pokemongo_bot\inventory.py", line 1069, in refresh
    inventory = self.bot.get_inventory()['responses']['GET_INVENTORY']['inventory_delta']['inventory_items']
  File "C:\Users\xLemonX\PokemonGo-Bot\pokemongo_bot\__init__.py", line 812, in get_inventory
    self.latest_inventory = self.api.get_inventory()
  File "c:\users\xlemonx\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 122, in function
    return request.call()
  File "C:\Users\xLemonX\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 117, in call
    result = self._call()
  File "C:\Users\xLemonX\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 66, in _call
    return PGoApiRequest.call(self)
  File "c:\users\xlemonx\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "c:\users\xlemonx\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 127, in request
    response = self._make_rpc(endpoint, request_proto)
  File "c:\users\xlemonx\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 115, in _make_rpc
    http_response = self._session.post(endpoint, data=request_proto_serialized, timeout=30)
  File "D:\Python27\lib\site-packages\requests\sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "D:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python27\lib\site-packages\requests\sessions.py", line 617, in send
    r.content
  File "D:\Python27\lib\site-packages\requests\models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "D:\Python27\lib\site-packages\requests\models.py", line 664, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "D:\Python27\lib\site-packages\requests\packages\urllib3\response.py", line 349, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "D:\Python27\lib\site-packages\requests\packages\urllib3\response.py", line 501, in read_chunked
    chunk = self._handle_chunk(amt)
  File "D:\Python27\lib\site-packages\requests\packages\urllib3\response.py", line 470, in _handle_chunk
    returned_chunk = self._fp._safe_read(self.chunk_left)
  File "D:\Python27\lib\httplib.py", line 703, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "D:\Python27\lib\socket.py", line 384, in read
    data = self._sock.recv(left)
  File "D:\Python27\lib\site-packages\eventlet\green\ssl.py", line 200, in recv
    read = self.read(buflen)
  File "D:\Python27\lib\site-packages\eventlet\green\ssl.py", line 139, in read
    super(GreenSSLSocket, self).read, *args, **kwargs)
  File "D:\Python27\lib\site-packages\eventlet\green\ssl.py", line 113, in _call_trampolining
    return func(*a, **kw)
  File "D:\Python27\lib\ssl.py", line 643, in read
    v = self._sslobj.read(len)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1754)
Tue, Aug 16, 2016 10:30:35 PM Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

>

**Comment by k4n30** [comment]
There have been some considerable changes and these errors have not been seen for a long time. Going to suggest a fresh install for you all (make sure you keep your config).

If you experience errors, please create a new issue as this one is rather long with lots of people with differing issues
