### ISSUE TITLE
Failed at startup: UnicodeDecodeError

### ISSUE THREAD

**Issue by tolinwei** [PokemonGoF/PokemonGo-Bot#3821]
The newest version after `git pull origin master`, configuration file has been checked online. Can anyone give me some idea about this? Thanks.
```
raceback (most recent call last):
  File "pokecli.py", line 514, in <module>
    main()
  File "pokecli.py", line 83, in main
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "/Users/linwei/Projects/PokemonGo-Bot/pokemongo_bot/tree_config_builder.py", line 63, in build
    instance = worker(self.bot, task_config)
  File "/Users/linwei/Projects/PokemonGo-Bot/pokemongo_bot/base_task.py", line 13, in __init__
    self.initialize()
  File "/Users/linwei/Projects/PokemonGo-Bot/pokemongo_bot/cell_workers/sleep_schedule.py", line 37, in initialize
    self._process_config()
  File "/Users/linwei/Projects/PokemonGo-Bot/pokemongo_bot/cell_workers/sleep_schedule.py", line 47, in _process_config
    self.time = datetime.strptime(self.config.get('time', '01:00'), '%H:%M')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '27:54' does not match format '%H:%M'
2016-08-12 22:02:31,803 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/linwei/Envs/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/linwei/Envs/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/linwei/Envs/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/linwei/Envs/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/linwei/Envs/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/linwei/Envs/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/linwei/Envs/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/linwei/Envs/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 891, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-12 22:02:31,804 [sentry.errors.uncaught] [ERROR] [u"ValueError: time data '27:54' does not match format '%H:%M'", u'  File "pokecli.py", line 514, in <module>', u'  File "pokecli.py", line 83, in main', u'  File "pokemongo_bot/tree_config_builder.py", line 63, in build', u'  File "pokemongo_bot/base_task.py", line 13, in __init__', u'  File "pokemongo_bot/cell_workers/sleep_schedule.py", line 37, in initialize', u'  File "pokemongo_bot/cell_workers/sleep_schedule.py", line 47, in _process_config', u'  File "python2.7/_strptime.py", line 325, in _strptime']
Fri Aug 12 22:02:31 PDT 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
```

**Comment by keugnu** [comment]
#3304 #2807 #3343 #3818 #3811 #3785 #3770 #3735 ..... this list goes on.

**Comment by k4n30** [comment]
> ValueError: time data '27:54' does not match format '%H:%M'
> [ERROR] [u"ValueError: time data '27:54' does not match format '%H:%M'",

Fix your time format in your config for sleep schedule
