### ISSUE TITLE
Error when starting due to PokemonOptimizer

### ISSUE THREAD

**Issue by scalp42** [PokemonGoF/PokemonGo-Bot#3840]
```
2016-08-13 13:34:48,763 [PokemonGoBot] [INFO]
2016-08-13 13:34:49,647 [SleepSchedule] [INFO] [next_sleep] Next sleep at 2016-08-13 23:05:13.647168
2016-08-13 13:34:50,104 [PokemonGoBot] [INFO] [bot_start] Starting bot...
2016-08-13 13:34:50,344 [CollectLevelUpReward] [INFO] [level_up_reward] Received level up reward: []
2016-08-13 13:34:50,345 [IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 9.36 km
2016-08-13 13:34:50,354 [PokemonOptimizer] [INFO] Pokemon Bag: 445/450
2016-08-13 13:34:50,806 [       cli] [INFO]
2016-08-13 13:34:50,806 [       cli] [INFO] Ran for 0:00:06
2016-08-13 13:34:50,806 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-13 13:34:50,806 [       cli] [INFO] Travelled 0.00km
2016-08-13 13:34:50,806 [       cli] [INFO] Visited 0 stops
2016-08-13 13:34:50,806 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-13 13:34:50,807 [       cli] [INFO] Threw 0 pokeballs
2016-08-13 13:34:50,807 [       cli] [INFO] Earned 0 Stardust
2016-08-13 13:34:50,807 [       cli] [INFO]
2016-08-13 13:34:50,807 [       cli] [INFO] Highest CP Pokemon:
2016-08-13 13:34:50,807 [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 578, in <module>
    main()
  File "pokecli.py", line 103, in main
    bot.tick()
  File "/Users/scalp/pokemon/new-dev-pokemongo-bot/pokemongo_bot/__init__.py", line 482, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/Users/scalp/pokemon/new-dev-pokemongo-bot/pokemongo_bot/cell_workers/pokemon_optimizer.py", line 49, in work
    transfer, evo_best, evo_crap = self.get_family_optimized(family_id, family)
  File "/Users/scalp/pokemon/new-dev-pokemongo-bot/pokemongo_bot/cell_workers/pokemon_optimizer.py", line 75, in get_family_optimized
    return self.get_multi_family_optimized(family_id, family, 3)
  File "/Users/scalp/pokemon/new-dev-pokemongo-bot/pokemongo_bot/cell_workers/pokemon_optimizer.py", line 101, in get_multi_family_optimized
    transfer_senior += self.get_family_optimized(senior_pid, senior_family)[0]
  File "/Users/scalp/pokemon/new-dev-pokemongo-bot/pokemongo_bot/cell_workers/pokemon_optimizer.py", line 82, in get_family_optimized
    evolve_best += self.get_top_rank(family, criteria)
  File "/Users/scalp/pokemon/new-dev-pokemongo-bot/pokemongo_bot/cell_workers/pokemon_optimizer.py", line 135, in get_top_rank
    worst = sorted_family[criteria.get("top", 1) - 1]
IndexError: list index out of range
```

```json
    {
        "type": "PokemonOptimizer",
        "config": {
                "// the 'transfer' parameter activate or deactivate the transfer of pokemons": {},
                "// at false, no pokemon is going to be transfered, ever": {},
                "// at false, you will still get the log information of what the optimizer": {},
                "// would have transfered if the parameter was true": {},
            "transfer": true,
                "// the 'evolve' parameter activate or deactivate the evolution of pokemons": {},
                "// at false, no pokemon is going to be evolved, ever": {},
                "// at false, you will still get the log information of what the": {},
                "// optimizer would have evolved if the parameter was true": {},
            "evolve": true,
                "// the 'use_candies_for_xp' parameter let you choose if you want the optimizer": {},
                "// to use your candies to evolve low quality pokemons in order to maximize your xp": {},
                "// at false, the optimizer will still use candies to evolve your best Pokemons": {},
            "use_candies_for_xp": false,
                "// the 'use_lucky_egg' parameter let you choose if you want the optimizer": {},
                "// to use a lucky egg right before evolving Pokemons. At false; the optimizer": {},
                "// is free to evolve Pokemons even if you do not have any lucky egg.": {},
            "use_lucky_egg": true,
                "// the 'evolve_only_with_lucky_egg' parameter let you choose if you want the optimizer": {},
                "// to only Evolve Pokemons when a lucky egg is available": {},
            "evolve_only_with_lucky_egg": true,
                "// the 'minimum_evolve_for_lucky_egg' parameter let you define the minimum": {},
                "// number of Pokemons that must evolve before using a lucky egg": {},
                "// If that number is not reached, and evolve_only_with_lucky_egg is true, evolution will be skipped": {},
                "// If that number is not reached, and evolve_only_with_lucky_egg is false,": {},
                "// evolution will be performed without using a lucky egg": {},
            "minimum_evolve_for_lucky_egg": 90,
                "// the 'keep' parameter let you define what pokemons you consider are the 'best'. These Pokemons": {},
                "// will be keep and evolved. Note that Pokemons are evaluated inside their whole family": {},
                "// Multiple way of ranking can be defined. Following configuration let you keep the best iv,": {},
                "// the best ncp and the best cp": {},
            "keep": [
                {
                        "// Following setting let you keep the best iv of the family": {},
                        "// the 'top' parameter allow you to define how many Pokemons you want to keep": {},
                        "// at the top of your ranking. If several Pokemons get the same score, they are": {},
                        "// considered equal. Thus, top=1 might result in keeping more than 1 Pokemon.": {},
                    "top": 1,
                        "// the 'evolve' parameter let you choose if you want to evolve the Pokemons you keep": {},
                    "evolve": true,
                        "// the 'sort' parameter define how you want to rank your pokemons": {},
                        "// Critera are sorted fro, the most important to the least important.": {},
                        "// Available criteria are:": {},
                        "// 'iv' = individual value": {},
                        "// 'ivcp' = iv weigted so that for equal iv, attack > defense > stamina": {},
                        "// 'cp' = combat power (can be increased with candies)": {},
                        "// 'cp_exact' = combar power (not rounded)": {},
                        "// 'ncp' (normalized cp) or 'cp_percent' = ratio cp / max_cp": {},
                        "// iv_attack = attach component of iv": {},
                        "// iv_defense = defense component of iv": {},
                        "// iv_stamina = stamina component of iv": {},
                        "// dps = raw dps based on the moves of the pokemon": {},
                        "// dps_attack = average dps when attacking": {},
                        "// dps_defense = average dps when defending": {},
                        "// Note that the more criteria you add to this list, the less likely Pokemons": {},
                        "// will be equals": {},
                    "sort": ["iv"]
                },
                {
                    "// Following setting let you keep keep the best normalized cp of the family": {},
                    "// That is the Pokemon with higher CP once fully evolved": {},
                    "top": 2,
                    "evolve": true,
                    "sort": ["ncp"]
                },
                {
                    "// Following setting let you keep keep the best cp of the family.": {},
                    "// But will not evolve it further (in favor of the best ncp)": {},
                    "top": 2,
                    "evolve": false,
                    "sort": ["cp"]
                }
            ]
        }
    },
```

Branch: dev
Git Commit: `d4200e9b34ef6ec9826eb81a6ceb420162b8c674`
Python Version: `2.7.12`

**Comment by Anakin5** [comment]
Fixed in https://github.com/PokemonGoF/PokemonGo-Bot/pull/3823

**Comment by k4n30** [comment]
Issue resolved, waiting on PR to be merged before closing issue
