### ISSUE TITLE
[ERROR] Sentry responded with an error: 'module' object has no attribute 'HTTPSHandler' (Not sure what this error is)

### ISSUE THREAD

**Issue by StuffToBeDone111** [PokemonGoF/PokemonGo-Bot#3870]
### Expected Behavior
Expecting bot to log in, display user data, and continue from where it was located previously.

### Actual Behavior
Bot gets the Server busy warning and then errors out.

2016-08-14 03:38:58,374 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-14 03:38:58,377 [       cli] [INFO] Configuration initialized
2016-08-14 03:38:58,377 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-14 03:38:58,377 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-14 03:38:58,386 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-14 03:38:58,424 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-14 03:38:58,425 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-14 03:38:58,425 [PokemonGoBot] [INFO] [location_found] Location found: --removed-- (--removed--)
2016-08-14 03:38:58,425 [PokemonGoBot] [INFO] [position_update] Now at (--removed--)
2016-08-14 03:38:58,426 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-14 03:38:59,923 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-14 03:39:05,719 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 4/15
2016-08-14 03:39:06,598 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 5/15
2016-08-14 03:39:08,312 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 6/15
2016-08-14 03:39:09,281 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 7/15
2016-08-14 03:39:10,702 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 8/15
2016-08-14 03:39:12,171 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 9/15
2016-08-14 03:39:13,377 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 10/15
2016-08-14 03:39:14,305 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 11/15
2016-08-14 03:39:15,507 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 12/15
2016-08-14 03:39:16,749 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 13/15
2016-08-14 03:39:18,117 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 14/15
2016-08-14 03:39:19,299 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 15/15
Traceback (most recent call last):
  File "pokecli.py", line 578, in <module>
    main()
  File "pokecli.py", line 145, in main
    report_summary(bot)
  File "pokecli.py", line 180, in report_summary
    metrics.capture_stats()
  File "/home/GIT/PokemonGo-Bot/pokemongo_bot/metrics.py", line 84, in capture_stats
    response_dict = request.call()
  File "/home/GIT/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 133, in call
    raise ServerBusyOrOfflineException()
pgoapi.exceptions.ServerBusyOrOfflineException
2016-08-14 03:39:19,323 [sentry.errors] [ERROR] Sentry responded with an error: 'module' object has no attribute 'HTTPSHandler' (url: https://app.getsentry.                  com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 44, in urlopen
    class ValidHTTPSHandler(urllib2.HTTPSHandler):
AttributeError: 'module' object has no attribute 'HTTPSHandler'
2016-08-14 03:39:19,324 [sentry.errors.uncaught] [ERROR] [u'ServerBusyOrOfflineException', u'  File "pokecli.py", line 578, in <module>', u'  File "pokecli.                  py", line 145, in main', u'  File "pokecli.py", line 180, in report_summary', u'  File "pokemongo_bot/metrics.py", line 84, in capture_stats', u'  File "pok                  emongo_bot/api_wrapper.py", line 133, in call']

I have never had such a persistent error before. This crash has remained through multiple GIT pulls for this specific account. My other accounts are fine.

I have not tried this account on the official app yet, is this indicative of a permanent ban perhaps?

### Your config.json (remove your credentials and any other private info)
{
    "auth_service": "google",
    "username": "--removed--",
    "password": "--removed--",
    "location": "--removed--",
    "gmapkey": "--removed--",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "iv",
            "evolve_above_cp": 100,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
		  "item_filter": {
			  "Pokeball": { "keep" : 20 },
			  "Greatball": { "keep" : 40 },
			  "Ultraball": { "keep" : 70 },
			  "Potion": { "keep" : 0 },
			  "Super Potion": { "keep" : 0 },
			  "Hyper Potion": { "keep" : 0 },
			  "Max Potion": { "keep" : 60 },
			  "Revive": { "keep" : 0 },
			  "Max Revive": { "keep" : 20 },
			  "Razz Berry": { "keep" : 80 }
		  }
		}
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 60,
      "cache_recent_forts": true
    },
    "websocket_server": false,
    "walk": 3.56,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": false,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "catch_randomize_reticle_factor": 0.7,
    "catch_randomize_spin_factor": 0.6,
    "logging_color": false,
    "catch_throw_parameters": {
      "excellent_rate": 0.45,
      "great_rate": 0.35,
      "nice_rate": 0.15,
      "normal_rate": 0.05,
      "spin_success_rate" : 0.6
    },
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or" }
    },
    "release": {
      "any": {"keep_best_iv": 1},

      "// Legendary pokemons keep_best_cp: 1,  (Goes under S-Tier)": {},
      "Lapras": { "release_below_cp": 1041, "release_below_iv": 0.8, "logic": "and" },
      "Moltres": { "release_below_cp": 1132, "release_below_iv": 0.8, "logic": "and" },
      "Zapdos": { "release_below_cp": 1087, "release_below_iv": 0.8, "logic": "and" },
      "Articuno": { "release_below_cp": 1039, "release_below_iv": 0.8, "logic": "and" },

      "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
      "Mewtwo": { "release_below_cp": 1447, "release_below_iv": 0.8, "logic": "and"},
      "Dragonite": { "keep_best_iv": 3 },
      "Snorlax": { "keep_best_iv": 3 },
	  
      "// Mew evolves to Mewtwo": {},
	  
      "Mew": { "keep_best_iv": 2 },
      "Arcanine": { "keep_best_iv": 2 },
      "Vaporeon": { "keep_best_iv": 2 },
      "Gyarados": { "keep_best_iv": 2 },
      "Exeggutor": { "keep_best_iv": 2 },
      "Muk": { "keep_best_iv": 2 },
      "Weezing": { "keep_best_iv": 2},
      "Flareon": { "keep_best_iv": 2 },

      "Caterpie": { "release_below_cp": 190, "release_below_iv": 0.8, "logic": "and" },
      "Weedle": { "release_below_cp": 180, "release_below_iv": 0.8, "logic": "and" },
	  
		"Rattata": { "release_below_cp": 204, "release_below_iv": 0.75, "logic": "or" },
		
		"Zubat": { "release_below_cp": 175, "release_below_iv": 0.85, "logic": "or" },
		
      "Pidgey": { "release_below_cp": 350, "release_below_iv": 0.8, "logic": "and" },
		"Spearow": { "release_below_cp": 240, "release_below_iv": 0.8, "logic": "or" }
		
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 900, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
        
    }  
}

### Steps to Reproduce
Just run as per usual

### Other Information
OS: Linux
Branch: dev 
Git Commit: 1817d008db17c79447763c9708bb402526a5d338
Python Version: Python 2.7.6

**Comment by k4n30** [comment]
#3682
