### ISSUE TITLE
Connecting to OpenPoGoWeb

### ISSUE THREAD

**Issue by ph3l1x** [PokemonGoF/PokemonGo-Bot#3900]
I am receiving this error with fresh install from develop branch.. Is this happening to anyone else or anyone know whats up? on dev branch

[MoveToMapPokemon] [INFO] [move_to_map_pokemon_fail] Failure! Map location data was not valid

Traceback (most recent call last):
File "pokecli.py", line 578, in 
main()
File "pokecli.py", line 103, in main
bot.tick()
File "/var/www/p4999.copz.net/PokemonGo-Bot/pokemongo_bot/init.py", line 482, in tick
if worker.work() == WorkerResult.RUNNING:
File "/var/www/p4999.copz.net/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_map_pokemon.py", line 240, in work
self.update_map_location()
File "/var/www/p4999.copz.net/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_map_pokemon.py", line 179, in update_map_location
return log.logger(err, 'red')
NameError: global name 'log' is not defined

Whhy is log not defined? This used to work it seemed to break over the last day or so.

**Comment by k4n30** [comment]
Please use issue template
