### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by j2kan** [PokemonGoF/PokemonGo-Bot#3905]
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)

**Comment by abiran** [comment]
I have the same issue.

[02:08:30] Login successful.2016-08-14 02:08:35,083 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 4/15
2016-08-14 02:08:36,131 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 5/15
2016-08-14 02:08:37,242 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 6/15
2016-08-14 02:08:38,389 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 7/15
2016-08-14 02:08:39,603 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 8/15
2016-08-14 02:08:40,488 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 9/15
2016-08-14 02:08:41,840 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 10/15
2016-08-14 02:08:43,218 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 11/15
2016-08-14 02:08:44,050 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 12/15
2016-08-14 02:08:45,394 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 13/15
2016-08-14 02:08:46,393 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 14/15
2016-08-14 02:08:47,526 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 15/15
Traceback (most recent call last):
  File "pokecli.py", line 514, in <module>
    main()
  File "pokecli.py", line 138, in main
    report_summary(bot)
  File "pokecli.py", line 147, in report_summary
    metrics.capture_stats()
  File "/root/PokemonGo-Bot/pokemongo_bot/metrics.py", line 84, in capture_stats
    response_dict = request.call()
  File "/root/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 133, in call
    raise ServerBusyOrOfflineException()
pgoapi.exceptions.ServerBusyOrOfflineException
2016-08-14 02:08:47,538 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/root/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/root/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/root/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/root/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/root/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/root/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/root/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/root/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/root/.linuxbrew/Cellar/python/2.7.12_1/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/root/.linuxbrew/Cellar/python/2.7.12_1/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/root/.linuxbrew/Cellar/python/2.7.12_1/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/root/.linuxbrew/Cellar/python/2.7.12_1/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-14 02:08:47,541 [sentry.errors.uncaught] [ERROR] [u'ServerBusyOrOfflineException', u'  File "pokecli.py", line 514, in <module>', u'  File "pokecli.py", line 138, in main', u'  File "pokecli.py", line 147, in report_summary', u'  File "pokemongo_bot/metrics.py", line 84, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 133, in call']

**Comment by bay1188** [comment]
same. pretty much banned. Can't login from mobile app too.
tried other accounts both Bot and Apps works fine.

**Comment by foux** [comment]
I have the same issue when nicknaming Pokemons with a French locale.

**Comment by vdubus** [comment]
I was also in the nicknaming pokemon task when his error occurred.
The selected locale was `fr`.

```
2016-08-14 10:25:11,815 [sentry.errors.serializer] [ERROR] 'ascii' codec can't encode character u'\xc9' in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "E:\Dev\Python27\lib\site-packages\raven\utils\serializer\manager.py", line 76, in transform
    return repr(value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc9' in position 0: ordinal not in range(128)
2016-08-14 10:25:11,823 [sentry.errors.serializer] [ERROR] 'ascii' codec can't encode character u'\xc9' in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "E:\Dev\Python27\lib\site-packages\raven\utils\serializer\manager.py", line 76, in transform
    return repr(value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc9' in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "./pokecli.py", line 578, in <module>
    main()
  File "./pokecli.py", line 103, in main
    bot.tick()
  File "E:\Dev\GitHub\PokemonGo-Bot\pokemongo_bot\__init__.py", line 482, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "E:\Dev\GitHub\PokemonGo-Bot\pokemongo_bot\cell_workers\nickname_pokemon.py", line 204, in work
    self._nickname_pokemon(pokemon)
  File "E:\Dev\GitHub\PokemonGo-Bot\pokemongo_bot\cell_workers\nickname_pokemon.py", line 271, in _nickname_pokemon
    data={'old_name': old_nickname, 'current_name': new_nickname}
  File "E:\Dev\GitHub\PokemonGo-Bot\pokemongo_bot\base_task.py", line 28, in emit_event
    data=data
  File "E:\Dev\GitHub\PokemonGo-Bot\pokemongo_bot\event_manager.py", line 61, in emit
    formatted_msg = formatted.format(**data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc9' in position 4: ordinal not in range(128)
2016-08-14 10:25:11,875 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url:
https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "E:\Dev\Python27\lib\site-packages\raven\transport\threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "E:\Dev\Python27\lib\site-packages\raven\transport\http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "E:\Dev\Python27\lib\site-packages\raven\utils\http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "E:\Dev\Python27\lib\site-packages\future\backports\urllib\request.py", line 494, in open
    response = self._open(req, data)
  File "E:\Dev\Python27\lib\site-packages\future\backports\urllib\request.py", line 512, in _open
    '_open', req)
  File "E:\Dev\Python27\lib\site-packages\future\backports\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "E:\Dev\Python27\lib\site-packages\raven\utils\http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "E:\Dev\Python27\lib\site-packages\future\backports\urllib\request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "E:\Dev\Python27\lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "E:\Dev\Python27\lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "E:\Dev\Python27\lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "E:\Dev\Python27\lib\httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-14 10:25:11,930 [sentry.errors.uncaught] [ERROR] [u"UnicodeEncodeError: 'ascii' codec can't encode character u'\\xc9' in position 4: ordinal not in range(128)", u'  File "pokecli.py", line 578, in <module>', u'  File "pokecli.py", line 103, in main', u'  File "E:\\Dev\\GitHub\\PokemonGo-Bot\\pokemongo_bot\\__init__.py", line 482, in tick', u'  File "E:\\Dev\\GitHub\\PokemonGo-Bot\\pokemongo_bot\\cell_workers\\nickname_pokemon.py", line 204, in work', u'  File "E:\\Dev\\GitHub\\PokemonGo-Bot\\pokemongo_bot\\cell_workers\\nickname_pokemon.py", line 271, in _nickname_pokemon', u'  File "E:\\Dev\\GitHub\\PokemonGo-Bot\\pokemongo_bot\\base_task.py", line 28, in emit_event', u'  File "E:\\Dev\\GitHub\\PokemonGo-Bot\\pokemongo_bot\\event_manager.py", line 61, in emit']
```

**Comment by vdubus** [comment]
It seems that there is also the same problem reported on #3845

**Comment by k4n30** [comment]
@j2kan - can you please use the issue template so that we can help you, we need to full output, not just one line. Going to close this issue, so that you can recreate it with the right detail :)
@abiran - your issue is ban related
@ foux & @vdubus - Can one you create an issue for the fr locale nickname issue so that it can be looked at rather than just hijacking other similar issues which your problem is not related to
