### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by abs07** [PokemonGoF/PokemonGo-Bot#3947]
(venv) root@ATOM /var/www/abs/PokemonGo-Bot # ./run.sh
Traceback (most recent call last):
  File "pokecli.py", line 42, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "/var/www/abs/PokemonGo-Bot/pokemongo_bot/__init__.py", line 29, in <module>
    from pokemongo_bot.socketio_server.runner import SocketIoRunner
  File "/var/www/abs/PokemonGo-Bot/pokemongo_bot/socketio_server/runner.py", line 5, in <module>
    from eventlet import patcher, wsgi
  File "/var/www/abs/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/patcher.py", line 4, in <module>
    from eventlet.support import six
  File "/var/www/abs/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/support/__init__.py", line 4, in <module>
    from eventlet.support import greenlets, six
  File "/var/www/abs/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/support/greenlets.py", line 3, in <module>
    import greenlet
ImportError: /var/www/abs/PokemonGo-Bot/local/lib/python2.7/site-packages/greenlet.so: undefined symbol: _PyTrash_thread_deposit_object
Sun Aug 14 20:48:21 CEST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

**Comment by abs07** [comment]
(venv) root@ATOM /var/www/abs/PokemonGo-Bot # python --version
Python 2.7.11

Updated to 2.7.11 still this issue

**Comment by DiegoRBaquero** [comment]
do source bin/activate again and reinstall requirements. They were installed with old python.

**Comment by jrjhealey** [comment]
Please use the issue template. It's designed to help us figure out any problems, random error codes can mean quite a few different issues.

**Comment by simonsmh** [comment]
It seems like dependency error.
Users report that greenlet==0.4.9 is working without problem.

**Comment by k4n30** [comment]
@abs07 Can you please update to the latest version and ensure you follow the procedure to install from scratch as you have installed a new python version
