### ISSUE TITLE
Traceback error 

### ISSUE THREAD

**Issue by xLemonice** [PokemonGoF/PokemonGo-Bot#3996]
config no problem
### Actual Behavior

> Traceback (most recent call last):
  File "pokecli.py", line 578, in <module>
    main()
  File "pokecli.py", line 103, in main
    bot.tick()
  File "C:\Users\xLemonX\PokemonGo-Bot\pokemongo_bot\__init__.py", line 482, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "C:\Users\xLemonX\PokemonGo-Bot\pokemongo_bot\cell_workers\recycle_items.py", line 82, in work
    inventory.refresh_inventory()
  File "C:\Users\xLemonX\PokemonGo-Bot\pokemongo_bot\inventory.py", line 1103, in refresh_inventory
    _inventory.refresh()
  File "C:\Users\xLemonX\PokemonGo-Bot\pokemongo_bot\inventory.py", line 1014, in refresh
    inventory = self.bot.get_inventory()['responses']['GET_INVENTORY']['inventory_delta']['inventory_items']
  File "C:\Users\xLemonX\PokemonGo-Bot\pokemongo_bot\__init__.py", line 802, in get_inventory
    self.latest_inventory = self.api.get_inventory()
  File "c:\users\xlemonx\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 122, in function
    return request.call()
  File "C:\Users\xLemonX\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 106, in call
    result = self._call()
  File "C:\Users\xLemonX\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "c:\users\xlemonx\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "c:\users\xlemonx\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 127, in request
    response = self._make_rpc(endpoint, request_proto)
  File "c:\users\xlemonx\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 115, in _make_rpc
    http_response = self._session.post(endpoint, data=request_proto_serialized, timeout=30)
  File "D:\Python27\lib\site-packages\requests\sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "D:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python27\lib\site-packages\requests\sessions.py", line 617, in send
    r.content
  File "D:\Python27\lib\site-packages\requests\models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "D:\Python27\lib\site-packages\requests\models.py", line 664, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "D:\Python27\lib\site-packages\requests\packages\urllib3\response.py", line 349, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "D:\Python27\lib\site-packages\requests\packages\urllib3\response.py", line 501, in read_chunked
    chunk = self._handle_chunk(amt)
  File "D:\Python27\lib\site-packages\requests\packages\urllib3\response.py", line 470, in _handle_chunk
    returned_chunk = self._fp._safe_read(self.chunk_left)
  File "D:\Python27\lib\httplib.py", line 703, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "D:\Python27\lib\socket.py", line 384, in read
    data = self._sock.recv(left)
  File "D:\Python27\lib\site-packages\eventlet\green\ssl.py", line 200, in recv
    read = self.read(buflen)
  File "D:\Python27\lib\site-packages\eventlet\green\ssl.py", line 139, in read
    super(GreenSSLSocket, self).read, *args, **kwargs)
  File "D:\Python27\lib\site-packages\eventlet\green\ssl.py", line 113, in _call_trampolining
    return func(*a, **kw)
  File "D:\Python27\lib\ssl.py", line 643, in read
    v = self._sslobj.read(len)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1754)
Mon, Aug 15, 2016 8:58:54 PM Pokebot  Stopped. 

> 

### Other Information
OS: win10 64bit
Git Commit: d6c5bb32865bc70ab804005c968e8ef608a3d6ab
Python Version: Python 2.7.12

**Comment by xLemonice** [comment]
why close T_T
