### ISSUE TITLE
OS Detection crashes when running on another platform then linux/win32/darwin

### ISSUE THREAD

**Issue by cliffalbert** [PokemonGoF/PokemonGo-Bot#3998]
### Expected Behavior

Starting up app

### Actual Behavior

2016-08-15 15:46:28,120 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "./pokecli.py", line 595, in <module>
    main()
  File "./pokecli.py", line 90, in main
    bot.start()
  File "/export/home/cliff/PGBot/PokemonGo-Bot/pokemongo_bot/__init__.py", line 86, in start
    self._setup_api()
  File "/export/home/cliff/PGBot/PokemonGo-Bot/pokemongo_bot/__init__.py", line 710, in _setup_api
    self.api.activate_signature(self.get_encryption_lib())
  File "/export/home/cliff/PGBot/PokemonGo-Bot/pokemongo_bot/__init__.py", line 689, in get_encryption_lib
    full_path = path + '/'+ file_name
UnboundLocalError: local variable 'file_name' referenced before assignment

### Steps to Reproduce

Run on different OS (Solaris, FreeBSD, etc)

Patch to report unsupported OS, altough most unices could be but under the darwin linux header.

[patch-pokemongo-os-detection.diff.txt](https://github.com/PokemonGoF/PokemonGo-Bot/files/418150/patch-pokemongo-os-detection.diff.txt)

### Other Information
OS: Solaris 11
Git Commit: 40ea94202d76c46dbc457d83621954d863a36452
Python Version: 

Python 2.7.9

**Comment by simonsmh** [comment]
#4068
