### ISSUE TITLE
Something error from Traceback

### ISSUE THREAD

**Issue by titellergetlinks** [PokemonGoF/PokemonGo-Bot#4011]
After i run ./run.sh (this working) and Login successful.
and then something error and log show this message
(before this config is working and running)

### Expected Behavior
```
2016-08-16 00:28:01,725 [       cli] [INFO] 
2016-08-16 00:28:01,725 [       cli] [INFO] Ran for 0:00:07
2016-08-16 00:28:01,726 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-16 00:28:01,726 [       cli] [INFO] Travelled 0.00km
2016-08-16 00:28:01,726 [       cli] [INFO] Visited 0 stops
2016-08-16 00:28:01,726 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-16 00:28:01,726 [       cli] [INFO] Threw 0 pokeballs
2016-08-16 00:28:01,727 [       cli] [INFO] Earned 0 Stardust
2016-08-16 00:28:01,727 [       cli] [INFO] 
2016-08-16 00:28:01,727 [       cli] [INFO] Highest CP Pokemon: 
2016-08-16 00:28:01,727 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 595, in <module>
    main()
  File "pokecli.py", line 90, in main
    bot.start()
  File "/Users/kittipiyapan/Downloads/PokemonGo-Bot/pokemongo_bot/__init__.py", line 87, in start
    self._load_recent_forts()
  File "/Users/kittipiyapan/Downloads/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1121, in _load_recent_forts
    cached_recent_forts = json.load(f)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
2016-08-16 00:28:01,758 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/kittipiyapan/Downloads/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/kittipiyapan/Downloads/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/kittipiyapan/Downloads/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/kittipiyapan/Downloads/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/kittipiyapan/Downloads/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/kittipiyapan/Downloads/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/kittipiyapan/Downloads/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/kittipiyapan/Downloads/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
```

UnicodeDecodeError
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-15 23:46:40,490 [sentry.errors.uncaught] [ERROR] [u'ValueError: No JSON object could be decoded', u'  File "pokecli.py", line 595, in <module>', u'  File "pokecli.py", line 90, in main', u'  File "pokemongo_bot/__init__.py", line 87, in start', u'  File "pokemongo_bot/__init__.py", line 1121, in _load_recent_forts', u'  File "json/__init__.py", line 291, in load', u'  File "json/__init__.py", line 339, in loads', u'  File "json/decoder.py", line 364, in decode', u'  File "json/decoder.py", line 382, in raw_decode']
```

### Other Information
OS: OSX 10.10.5
Git Commit: 98e17146a8d6a72e4708c3b0d1b46ce732febc7c
Python Version: Python 2.7.12

**Comment by keugnu** [comment]
I believe this issue has been posted about 100 times. Could you do a search?

**Comment by titellergetlinks** [comment]
I don't know how to fix that and not found that solution

I try to copy json format from config.json.example to config.json and just change username,password,location,gmapkey
but log error is same that

**Comment by titellergetlinks** [comment]
@keugnu 

oki i fixed from setting config

set cache_recent_forts to false

thank you for power up
