### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by jjn12** [PokemonGoF/PokemonGo-Bot#402]
got this error when running python pokecli.py

Traceback (most recent call last):
  File "pokecli.py", line 126, in <module>
    main()
  File "pokecli.py", line 114, in main
    bot.start()
  File "C:\PokemonGo-Bot-dev\pokemongo_bot\__init__.py",
line 28, in start
    self._setup_api()
  File "C:\PokemonGo-Bot-dev\pokemongo_bot\__init__.py",
line 167, in _setup_api
    self.get_player_info()
  File "C:\PokemonGo-Bot-dev\pokemongo_bot\__init__.py",
line 363, in get_player_info
    nextlvlxp = (int(playerdata['next_level_xp']) - int(playerdata['experience']
))
KeyError: 'experience'

help pls

**Comment by DrWiebe** [comment]
try 
`sudo pip install -r requirements.txt ` before python pokecli.py ....

**Comment by Sharpienero** [comment]
Also try  `python2 pokecli.py -a ptc -u Sharpienero -p password --location "xx.xx, -yy.yy"`

**Comment by s1x** [comment]
If you still have the issue, please feel free the open a new issue.
