### ISSUE TITLE
Bot crashes as it starts

### ISSUE THREAD

**Issue by yweitkemper** [PokemonGoF/PokemonGo-Bot#4021]
### Expected Behavior

Start bot
### Actual Behavior

Bot starts logins in. after 5 seconds of waking gives me this error 
```
Traceback (most recent call last):
  File "pokecli.py", line 609, in <module>
    main()
  File "pokecli.py", line 104, in main
    bot.tick()
  File "/Users/naturalhealingways/PokemonGo-Bot/pokemongo_bot/__init__.py", line 483, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/Users/naturalhealingways/PokemonGo-Bot/pokemongo_bot/cell_workers/follow_spiral.py", line 117, in work
    if dist <= 1 or (self.bot.config.walk > 0 and step_walker == None):
AttributeError: 'Namespace' object has no attribute 'walk'
2016-08-15 11:53:23,128 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/naturalhealingways/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/naturalhealingways/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/naturalhealingways/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/naturalhealingways/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/naturalhealingways/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/naturalhealingways/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/naturalhealingways/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/naturalhealingways/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-15 11:53:23,130 [sentry.errors.uncaught] [ERROR] [u"AttributeError: 'Namespace' object has no attribute 'walk'", u'  File "pokecli.py", line 609, in <module>', u'  File "pokecli.py", line 104, in main', u'  File "pokemongo_bot/__init__.py", line 483, in tick', u'  File "pokemongo_bot/cell_workers/follow_spiral.py", line 117, in work']
Mon Aug 15 11:53:23 PDT 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.


### Your config.json (remove your credentials and any other private info)

 "encrypt_location": "",
    "websocket_server": false,
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "22:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "evolve_all": "Pidgey, Rattata, Weedle, Caterpie, Zubat, Golbat, Tentacool, Krabby, Spearow, Psyduck, Goldeen, Nidoran F, Nidoran M, Staryu, Paras",

            "first_evolve_by": "iv",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "max_balls_keep": 150,
          "max_potions_keep": 50,
          "max_berries_keep": 70,
          "max_revives_keep": 70,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "walk_max": 4.16,
    "walk_min": 2.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "min_ultraball_to_keep": 10,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "catch_throw_parameters": {
      "excellent_rate": 0.1,
      "great_rate": 0.5,
      "nice_rate": 0.3,
      "normal_rate": 0.1,
      "spin_success_rate" : 0.6
    },
    "release": {
		"any": {
			"keep_best_iv": 2,
			"keep_best_cp": 1,
			"release_below_cp": 2000,
			"release_below_iv": 0.1,
			"logic": "or"
		},
		"vips": {
			"Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
			"any": {
				"catch_above_cp": 1200,
				"catch_above_iv": 0.9,
				"logic": "or"
			},
			"Lapras": {},
			"Moltres": {},
			"Zapdos": {},
			"Articuno": {},

			"// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
			"Mewtwo": {},
			"Dragonite": {},
			"Snorlax": {},
			"// Mew evolves to Mewtwo": {},
			"Mew": {},
			"Arcanine": {},
			"Vaporeon": {},
			"Gyarados": {},
			"Exeggutor": {},
			"Muk": {},
			"Weezing": {},
			"Flareon": {}

		}
	}
}
```
### Other Information
OS: IOS
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by fehgab** [comment]
"walk_max": 4.16,
"walk_min": 2.16,

Write "walk":4.16, to the config file, instead of the above lines.

**Comment by yweitkemper** [comment]
tried that, didn't work :/ still the same error

**Comment by fehgab** [comment]
Is there an other error message?

**Comment by BriceSD** [comment]
Remove follow spiral for now.

**Comment by yweitkemper** [comment]
I am using the latest release, and thanks removing follow spiral seemed to fix it.

**Comment by Vvkmnn** [comment]
Got the same error for the `FollowPath` task in 603aca6a0f1aa900a5b9c356445b2ab363a88fc6

I guess some of the cell_workers need updates:
```
Traceback (most recent call last):
  File "pokecli.py", line 609, in <module>
    main()
  File "pokecli.py", line 104, in main
    bot.tick()
  File ".../PokemonGo-Bot/pokemongo_bot/__init__.py", line 483, in tick
    if worker.work() == WorkerResult.RUNNING:
  File ".../PokemonGo-Bot/pokemongo_bot/cell_workers/follow_path.py", line 129, in work
    if dist <= 1 or (self.bot.config.walk > 0 and is_at_destination):
AttributeError: 'Namespace' object has no attribute 'walk'

2016-08-15 16:29:03,613 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
```

**Comment by yweitkemper** [comment]
Seems like the bot doesn't move at all now, just ran it for 30 mins and this is the result 
2016-08-15 13:12:25,511 [PokemonGoBot] [INFO] [bot_start] Starting bot...

2016-08-15 13:12:25,762 [CollectLevelUpReward] [INFO] [level_up_reward] Received level up reward: []

2016-08-15 13:12:25,763 [IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 4.60 km

 2016-08-15 13:41:22,675 [PokemonGoBot] [INFO] [api_error] Session stale, re-logging in.

2016-08-15 13:41:22,675 [PokemonGoBot] [INFO] [login_started] Login procedure started.

2016-08-15 13:41:24,143 [PokemonGoBot] [INFO] [login_successful] Login successful.

2016-08-15 13:41:24,144 [PokemonGoBot] [INFO] Found encrypt.so! Platform: darwin Encrypt.so directory: /Users/naturalhealingways/PokemonGo-Bot

2016-08-15 13:42:15,589 [       cli] [INFO] 

2016-08-15 13:42:15,589 [       cli] [INFO] Ran for 0:29:57

2016-08-15 13:42:15,590 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h

2016-08-15 13:42:15,590 [       cli] [INFO] Travelled 0.00km

2016-08-15 13:42:15,590 [       cli] [INFO] Visited 0 stops

2016-08-15 13:42:15,590 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before

2016-08-15 13:42:15,590 [       cli] [INFO] Threw 0 pokeballs

2016-08-15 13:42:15,590 [       cli] [INFO] Earned 0 Stardust

2016-08-15 13:42:15,591 [       cli] [INFO] 

2016-08-15 13:42:15,591 [       cli] [INFO] Highest CP Pokemon: 

2016-08-15 13:42:15,591 [       cli] [INFO] Most Perfect Pokemon: 

Traceback (most recent call last):

**Comment by yweitkemper** [comment]
After i took out follow spiral it doesn't seem to move at all this is what i get for running the bot for 30 mins. 

2016-08-15 13:12:25,511 [PokemonGoBot] [INFO] [bot_start] Starting bot...
2016-08-15 13:12:25,762 [CollectLevelUpReward] [INFO] [level_up_reward] Received level up reward: []
2016-08-15 13:12:25,763 [IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 4.60 km
 2016-08-15 13:41:22,675 [PokemonGoBot] [INFO] [api_error] Session stale, re-logging in.
2016-08-15 13:41:22,675 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-15 13:41:24,143 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-15 13:41:24,144 [PokemonGoBot] [INFO] Found encrypt.so! Platform: darwin Encrypt.so directory: /Users/naturalhealingways/PokemonGo-Bot
2016-08-15 13:42:15,589 [       cli] [INFO] 
2016-08-15 13:42:15,589 [       cli] [INFO] Ran for 0:29:57
2016-08-15 13:42:15,590 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-15 13:42:15,590 [       cli] [INFO] Travelled 0.00km
2016-08-15 13:42:15,590 [       cli] [INFO] Visited 0 stops
2016-08-15 13:42:15,590 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-15 13:42:15,590 [       cli] [INFO] Threw 0 pokeballs
2016-08-15 13:42:15,590 [       cli] [INFO] Earned 0 Stardust
2016-08-15 13:42:15,591 [       cli] [INFO] 
2016-08-15 13:42:15,591 [       cli] [INFO] Highest CP Pokemon: 
2016-08-15 13:42:15,591 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):

**Comment by dogauzun** [comment]
None of the above solutions working for me. I cannot use the bot with my custom path. Can anybody please refer to the last commit that works ok with custom paths?

**Comment by alexyaoyang** [comment]
For those having this error, follow the fixes in https://github.com/PokemonGoF/PokemonGo-Bot/pull/4025/files for now until it is merged into dev branch.

**Comment by avexus** [comment]
What's the status on this? Is it merged in code right now?
I went on to change 2 python files to make it work. But don't want to miss out on other parts of the update. Coz I cannot do a 'git pull' now.

**Comment by erdnaxela02** [comment]
Hello , sorry for my English , I use google translation .
I had the same problem yesterday.
I create my Path by adding several Paths following each other .
And I forget to add a comma after symbol "}".
Searched and checked in your file path for missing comma. Me it solved my problem ;-)

**Comment by alexyaoyang** [comment]
This issue has been fixed on latest dev branch. 👍
