### ISSUE TITLE
Seems to get an error after running for an hour. [Master]

### ISSUE THREAD

**Issue by harsh1412** [PokemonGoF/PokemonGo-Bot#404]
### Expected Behavior

Run continously without stoping.
### Actual Behavior

[#] Walking from (30.326818300000003, 78.04180029999999) to (30.324002, 78.03706
2) for approx. 139.0 seconds
another walking_hook  422016-07-23 15:30:43,428 [    pgoapi] [ INFO] Server seem
s to be busy or offline - try again!
another walking_hook  137 [#] Finished walking to (30.324002, 78.037062)
Arrived at Pokestop
Traceback (most recent call last):
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-master\pokecli.py", line 126, in
<module>
    main()
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-master\pokecli.py", line 121, in
main
    bot.take_step()
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-master\bot.py", line 34, in take_
step
    self.stepper.take_step()
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-master\stepper.py", line 49, in t
ake_step
    self.bot.work_on_cell(cell,position)
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-master\bot.py", line 63, in work_
on_cell
    hack_chain = worker.work()
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-master\cell_workers\seen_fort_wor
ker.py", line 38, in work
    fort_details = response_dict['responses']['FORT_DETAILS']
KeyError: 'FORT_DETAILS'

C:\Users\DrDeath\Desktop\PokemonGo-Bot-master>

**Comment by hnq90** [comment]
Same mine.

**Comment by buusc0** [comment]
Can confirm this issue exists. Ran multiple sessions last night before bed, all of them ended with the above error a few hours later.

**Comment by dominikue** [comment]
Can confirm too.

**Comment by harsh1412** [comment]
Make this issue an urgent one please @eggins

**Comment by s1x** [comment]
@hnq90 @harsh1412 @dominikue If you still enocunter this issue under the current master/dev branch please comment on this, Ill reopen then. I assume this issue is fixed with the newst dev branch.
