### ISSUE TITLE
Quit after 1 hour of running

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#4041]
### Expected Behavior
It should keep running.
Even if the inventory is full.

### Actual Behavior
2016-08-15 16:00:30,177 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Sheep Meadow - 0.04km
2016-08-15 16:00:32,622 [  SpinFort] [INFO] [spun_pokestop] Spun pokestop Sheep Meadow. Experience awarded: 50. Items awarded: {u'Pokeball': 1, u'Revive': 1, u'Greatball': 1}
2016-08-15 16:00:34,622 [MoveToFort] [INFO] [inventory_full] Inventory is full. You might want to change your config to recycle more items if this message appears consistently.
2016-08-15 16:00:34,622 [FollowSpiral] [INFO] [position_update] Walking from (40.771038906023016, -73.97307874376351, 0) to (40.768874, -73.979419, 0) (585.684676518 m)
2016-08-15 16:00:36,190 [       cli] [INFO]
2016-08-15 16:00:36,190 [       cli] [INFO] Ran for 0:14:03
2016-08-15 16:00:36,190 [       cli] [INFO] Total XP Earned: 1000  Average: 4268.01/h
2016-08-15 16:00:36,190 [       cli] [INFO] Travelled 0.79km
2016-08-15 16:00:36,190 [       cli] [INFO] Visited 19 stops
2016-08-15 16:00:36,190 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 1 released, 0 evolved, 0 never seen before
2016-08-15 16:00:36,190 [       cli] [INFO] Threw 0 pokeballs
2016-08-15 16:00:36,190 [       cli] [INFO] Earned 0 Stardust
2016-08-15 16:00:36,190 [       cli] [INFO]
2016-08-15 16:00:36,190 [       cli] [INFO] Highest CP Pokemon:
2016-08-15 16:00:36,190 [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 609, in <module>
    main()
  File "pokecli.py", line 104, in main
    bot.tick()
  File "E:\downloads\PokemonGo-Bot\pokemongo_bot\__init__.py", line 483, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "E:\downloads\PokemonGo-Bot\pokemongo_bot\cell_workers\follow_spiral.py", line 117, in work
    if dist <= 1 or (self.bot.config.walk > 0 and step_walker == None):
AttributeError: 'Namespace' object has no attribute 'walk'

**Comment by Setsu-BHMT** [comment]
Duplicate #4021
