### ISSUE TITLE
Exception when arrived at Pokestop and "spinning"

### ISSUE THREAD

**Issue by saberone** [PokemonGoF/PokemonGo-Bot#406]
### Expected Behaviour
No crash. And collect items from Pokestop ;)

### Actual Behaviour
```
[#] Now at Pokestop: De Dansers - Spinning...
[+] Loot:
[+] 50 xp
[+] 3x Pokeball
[#] PokeStop on cooldown. Time left: 4.99 minutes
 [#] Found fort 0fde42d46d1640bbbc18aa9bacadfebf.16 at distance 6.52m
[#] Now at Pokestop: Odilla Art - Spinning...
Traceback (most recent call last):
  File "pokecli.py", line 126, in <module>
    main()
  File "pokecli.py", line 119, in main
    bot.take_step()
  File "/Users/saber/Dev/PokemonGo-Bot/pokemongo_bot/__init__.py", line 33, in take_step
    self.stepper.take_step()
  File "/Users/saber/Dev/PokemonGo-Bot/pokemongo_bot/stepper.py", line 56, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/Users/saber/Dev/PokemonGo-Bot/pokemongo_bot/stepper.py", line 104, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/Users/saber/Dev/PokemonGo-Bot/pokemongo_bot/__init__.py", line 97, in work_on_cell
    hack_chain = worker.work()
  File "/Users/saber/Dev/PokemonGo-Bot/pokemongo_bot/cell_workers/seen_fort_worker.py", line 52, in work
    self.api.fort_search(fort_id=self.fort['id'], fort_latitude=lat, fort_longitude=lng, player_latitude=f2i(position[0]), player_longitude=f2i(position[1]))
UnboundLocalError: local variable 'position' referenced before assignment
```

### Steps to Reproduce
My config.json looks like this
```
{
    "auth_service": "google",
    "username": "e-mail",
    "password": "password",
    "location": "Odilia van Salmstraat, Breda",
    "cp": 10,
    "gmapkey": "use your own ;)",
    "maxsteps": 5,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false
}
```

### Other Information
OS: OSX
Git Commit: 6681d7c10ad3e694db62b9dd0a10f6b1bac918d3

**Comment by s1x** [comment]
@saberone Are you still experiencing this problem with the newest branches *master/dev* ?

**Comment by saberone** [comment]
No the issue is gone I can't remember what commit fixed it. But you can close this one.
