### ISSUE TITLE
Crash after startup

### ISSUE THREAD

**Issue by n0ah01** [PokemonGoF/PokemonGo-Bot#4063]
I made an update of the bot (git pull) from the dev branch and anything was working normaly. Then suddently the bot crashes when i start it, right after the next_egg_incubates message. I have updated all dependencys, created a fresh config file via the web-config-generator but still no chance to get it up and running again. I also complettle deleted the bot and downloaded it freshly, without any luck. Fixes like in #4021 did not help me...

### Expected Behavior
Bot should start/work normaly.

### Actual Behavior
(PokemonGo-Bot) root@poke:~/PokemonGo-Bot# ./run.sh 
2016-08-16 07:43:42,183 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-16 07:43:42,186 [       cli] [INFO] Configuration initialized
2016-08-16 07:43:42,193 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-16 07:43:42,193 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-16 07:43:42,193 [PokemonGoBot] [INFO] [location_found] Location found: 47.22679624955804,8.818995952606201 (47.2267962, 8.8189959, 0.0)
2016-08-16 07:43:42,193 [PokemonGoBot] [INFO] [position_update] Now at (47.2267962, 8.8189959, 0)
2016-08-16 07:43:42,193 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-16 07:43:44,442 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-16 07:43:45,092 [PokemonGoBot] [INFO] 
2016-08-16 07:43:45,092 [PokemonGoBot] [INFO] --- n0ah0110 ---
2016-08-16 07:43:45,092 [PokemonGoBot] [INFO] Level: 23 (Next Level: 112845 XP) (Total: 447155 XP)
2016-08-16 07:43:45,092 [PokemonGoBot] [INFO] Pokemon Captured: 1167 | Pokestops Visited: 2295
2016-08-16 07:43:45,093 [PokemonGoBot] [INFO] Pokemon Bag: 73/250
2016-08-16 07:43:45,093 [PokemonGoBot] [INFO] Items: 346/350
2016-08-16 07:43:45,093 [PokemonGoBot] [INFO] Stardust: 9011 | Pokecoins: 0
2016-08-16 07:43:45,094 [PokemonGoBot] [INFO] PokeBalls: 67 | GreatBalls: 55 | UltraBalls: 46 | MasterBalls: 0
2016-08-16 07:43:45,094 [PokemonGoBot] [INFO] RazzBerries: 50 | BlukBerries: 0 | NanabBerries: 0
2016-08-16 07:43:45,094 [PokemonGoBot] [INFO] LuckyEgg: 2 | Incubator: 0 | TroyDisk: 4
2016-08-16 07:43:45,094 [PokemonGoBot] [INFO] Potion: 24 | SuperPotion: 5 | HyperPotion: 52 | MaxPotion: 0
2016-08-16 07:43:45,094 [PokemonGoBot] [INFO] Incense: 4 | IncenseSpicy: 0 | IncenseCool: 0
2016-08-16 07:43:45,094 [PokemonGoBot] [INFO] Revive: 35 | MaxRevive: 0
2016-08-16 07:43:45,094 [PokemonGoBot] [INFO] 
2016-08-16 07:43:45,094 [PokemonGoBot] [INFO] Found encrypt.so! Platform: linux2 Encrypt.so directory: /root/PokemonGo-Bot
2016-08-16 07:43:45,094 [PokemonGoBot] [INFO] 
2016-08-16 07:43:46,159 [PokemonGoBot] [INFO] [bot_start] Starting bot...
2016-08-16 07:43:47,843 [CollectLevelUpReward] [INFO] [level_up_reward] Received level up reward: []
2016-08-16 07:43:47,844 [IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 4.39 km
2016-08-16 07:43:49,557 [       cli] [INFO] 
2016-08-16 07:43:49,558 [       cli] [INFO] Ran for 0:00:07
2016-08-16 07:43:49,558 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-16 07:43:49,559 [       cli] [INFO] Travelled 0.00km
2016-08-16 07:43:49,559 [       cli] [INFO] Visited 0 stops
2016-08-16 07:43:49,559 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-16 07:43:49,559 [       cli] [INFO] Threw 0 pokeballs
2016-08-16 07:43:49,559 [       cli] [INFO] Earned 0 Stardust
2016-08-16 07:43:49,559 [       cli] [INFO] 
2016-08-16 07:43:49,559 [       cli] [INFO] Highest CP Pokemon: 
2016-08-16 07:43:49,559 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 609, in <module>
    main()
  File "pokecli.py", line 104, in main
    bot.tick()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 492, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/recycle_items.py", line 110, in work
    action_delay(self.bot.config.action_wait_min, self.bot.config.action_wait_max)
  File "/root/PokemonGo-Bot/pokemongo_bot/human_behaviour.py", line 18, in action_delay
    longNum = uniform(low, high)
  File "/usr/lib/python2.7/random.py", line 360, in uniform
    return a + (b-a) * self.random()
TypeError: unsupported operand type(s) for -: 'unicode' and 'unicode'
Tue Aug 16 07:43:49 UTC 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

(PokemonGo-Bot) root@poke:~/PokemonGo-Bot# 

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
https://transfer.sh/scwRQ/config.json

### Steps to Reproduce
./run.sh

#### OS: 
Ubuntu 16.04
#### Branch: 
dev
#### Git Commit: 
7d0da5a2a400e3dc9f7696d9886de039d7b890ab
#### Python Version: 
Python 2.7.12
#### Any other relevant files/configs (eg: path files)
none

**Comment by DanielVolz** [comment]
Maybe try running the bot with a config provided by the bot itself, rather than a generated one.

**Comment by simonsmh** [comment]
remove human behaviour config in your config.json and try again.

**Comment by k4n30** [comment]
Also, the use of an external service is supposed to help the process (with the reduction in spam), not hinder by having to download the config locally. What happened to using good old Pastebin :(

**Comment by n0ah01** [comment]
woohoo, thank you @DanielVOlz, with the example-config-file provided by the repo let the bot run again. Now I will add my modifications step by step. Thank you all and have a nice day! :-)
