### ISSUE TITLE
Exception: Google Maps API key over requests limit.

### ISSUE THREAD

**Issue by Carlito007** [PokemonGoF/PokemonGo-Bot#4080]
2016-08-16 16:51:45,993 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-16 16:51:45,996 [       cli] [INFO] Configuration initialized
2016-08-16 16:51:46,020 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
Traceback (most recent call last):
  File "C:\Users\user\bot\pokecli.py", line 609, in <module>
    main()
  File "C:\Users\user\bot\pokecli.py", line 149, in main
    raise Exception("Google Maps API key over requests limit.")
Exception: Google Maps API key over requests limit.
2016-08-16 16:51:50,198 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-16 16:51:50,214 [       cli] [INFO] Configuration initialized
2016-08-16 16:51:50,230 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
Traceback (most recent call last):
  File "C:\Users\user\bot\pokecli.py", line 609, in <module>
    main()
  File "C:\Users\user\bot\pokecli.py", line 149, in main
    raise Exception("Google Maps API key over requests limit.")
Exception: Google Maps API key over requests limit.

any one know how to fix this error?

**Comment by GitPupper** [comment]
This just means that you have exceeded your 2,500 API request limit quota set by Google. You have to pay a subscription fee to get a higher limit. Each day this resets, so you should be fine in 24 hours. But, if you want to continue botting just remove the Google API key. You should be fine, but just add it back tomorrow.

**Comment by Carlito007** [comment]
i am not using google api key :\
