### ISSUE TITLE
Bot crash when using movetomap 

### ISSUE THREAD

**Issue by Tagada22** [PokemonGoF/PokemonGo-Bot#4113]
Hello i have problems with my bot 

My bot working great.

I want update the bot, so 

Git pull 
Pip install -r requirements.txt 

Successful 

Virtualenv .
Source bon/activate 
Python pokecli.py 

Bot launch good , transfert my pokemon .

When movetomap come my bot crash.

2016-08-16 23:18:54,641 [TransferPokemon] [INFO] [future_pokemon_release] Releasing Electrode [CP 1028] [IV 0.49] based on rule: CP < 0 OR IV < 0.9
2016-08-16 23:18:55,055 [TransferPokemon] [INFO] [pokemon_release] Exchanged Electrode [CP 1028] [IV 0.49] for candy.
2016-08-16 23:18:56,448 [TransferPokemon] [INFO] [future_pokemon_release] Releasing Weezing [CP 1414] [IV 0.36] based on rule: CP < 0 OR IV < 0.9
2016-08-16 23:18:56,803 [TransferPokemon] [INFO] [pokemon_release] Exchanged Weezing [CP 1414] [IV 0.36] for candy.
2016-08-16 23:18:59,465 [TransferPokemon] [INFO] [future_pokemon_release] Releasing Rhydon [CP 863] [IV 0.73] based on rule: CP < 0 OR IV < 0.9
2016-08-16 23:18:59,848 [TransferPokemon] [INFO] [pokemon_release] Exchanged Rhydon [CP 863] [IV 0.73] for candy.
2016-08-16 23:19:02,019 [TransferPokemon] [INFO] [future_pokemon_release] Releasing Seaking [CP 930] [IV 0.6] based on rule: CP < 0 OR IV < 0.9
2016-08-16 23:19:02,364 [TransferPokemon] [INFO] [pokemon_release] Exchanged Seaking [CP 930] [IV 0.6] for candy.
2016-08-16 23:19:06,485 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_updated_map] Updated PokemonGo-Map to -33.8611061584, 151.221225983
2016-08-16 23:19:06,777 [       cli] [INFO] 
2016-08-16 23:19:06,778 [       cli] [INFO] Ran for 0:01:32
2016-08-16 23:19:06,778 [       cli] [INFO] Total XP Earned: 3490794  Average: 137277665.94/h
2016-08-16 23:19:06,779 [       cli] [INFO] Travelled 685.57km
2016-08-16 23:19:06,779 [       cli] [INFO] Visited 15369 stops
2016-08-16 23:19:06,779 [       cli] [INFO] Encountered 12847 pokemon, 9850 caught, 28 released, 743 evolved, 145 never seen before
2016-08-16 23:19:06,779 [       cli] [INFO] Threw 18120 pokeballs
2016-08-16 23:19:06,780 [       cli] [INFO] Earned 86847 Stardust
2016-08-16 23:19:06,780 [       cli] [INFO] 
2016-08-16 23:19:06,780 [       cli] [INFO] Highest CP Pokemon: 
2016-08-16 23:19:06,780 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 626, in <module>
    main()
  File "pokecli.py", line 104, in main
    bot.tick()
  File "/home/PokemonGo-Bot/pokemongo_bot/__init__.py", line 498, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_map_pokemon.py", line 248, in work
    pokemon_list = self.get_pokemon_from_map()
  File "/home/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_map_pokemon.py", line 147, in get_pokemon_from_map
    if pokemon['dist'] > ((pokemon['expire'] - now) * mean_walk_speed) and not self.config['snipe']:
KeyError: 'expire'
(PokemonGo-Bot) root@vps302994:/home/PokemonGo-Bot#

Bot working great 5 minute Before , have you got a solution please ?

Thanks

**Comment by thereyrey** [comment]
Got the same issue and error. Was hoping it wasn't something I did wrong.

**Comment by Tagada22** [comment]
I have this lssue with the lastest update

**Comment by thereyrey** [comment]
Yeah same.. pulled an hour ago to get some new features. Then it happens as soon as move to pokemon task starts.

**Comment by Raiven66** [comment]
will be fixed in #4115, sorry for the inconvenience

**Comment by jane0815** [comment]
When can we pull new update to fix it? Have the same problem.

**Comment by Raiven66** [comment]
once my pull request is approved by the mod team... you can revert to the previous state if you desperately need it.

FollowCluster fix is in that pull request as well ;)

**Comment by Raiven66** [comment]
should be fixed @jane0815 , please check
