### ISSUE TITLE
Crash after start 

### ISSUE THREAD

**Issue by MERR0N** [PokemonGoF/PokemonGo-Bot#412]
2016-07-23 13:41:42,790 [   rpc_api] [DEBUG] Decode raw over protoc (protoc has to be in your PATH):
Couldn't find protoc in your environment OR other issue...
2016-07-23 13:41:42,793 [   rpc_api] [DEBUG] Parsing sub RPC responses...
2016-07-23 13:41:42,795 [   rpc_api] [DEBUG] Parsing class: POGOProtos.Networking.Responses_pb2.GetInventoryResponse
2016-07-23 13:41:42,811 [    pgoapi] [ INFO] Cleanup of request!
Traceback (most recent call last):
  File "pokecli.py", line 126, in <module>
    main()
  File "pokecli.py", line 114, in main
    bot.start()
  File "H:\scripts\python\PokemonGo-Bot\pokemongo_bot\__init__.py", line 29, in start
    self.stepper = Stepper(self)
  File "H:\scripts\python\PokemonGo-Bot\pokemongo_bot\stepper.py", line 30, in __init__
    self.steplimit2 = self.steplimit**2
TypeError: unsupported operand type(s) for ** or pow(): 'unicode' and 'int'

**Comment by MERR0N** [comment]
And i run script without debug flag, why i see debug info?

**Comment by s1x** [comment]
Please add protoc to your path, follow the readme guide if you encounter any more problems. Maybe check closed issues too.

Please feel free the open a new issue when necessary!
