### ISSUE TITLE
Path broken commit #805930d 

### ISSUE THREAD

**Issue by balpoint** [PokemonGoF/PokemonGo-Bot#4139]
### Expected Behavior

Bot walking along pre configured coordinates

### Actual Behavior

Bot not starting since last pull

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

[http://pastebin.com/raw/AN9kFXDm](url)

### Output when issue occurred

2016-08-17 08:10:43,755 [PokemonGoBot] [INFO] PokeBalls: 79 | GreatBalls: 55 | UltraBalls: 0 | MasterBalls: 0
2016-08-17 08:10:43,755 [PokemonGoBot] [INFO] RazzBerries: 86 | BlukBerries: 0 | NanabBerries: 0
2016-08-17 08:10:43,755 [PokemonGoBot] [INFO] LuckyEgg: 3 | Incubator: 1 | TroyDisk: 3
2016-08-17 08:10:43,755 [PokemonGoBot] [INFO] Potion: 8 | SuperPotion: 5 | HyperPotion: 1 | MaxPotion: 0
2016-08-17 08:10:43,755 [PokemonGoBot] [INFO] Incense: 6 | IncenseSpicy: 0 | IncenseCool: 0
2016-08-17 08:10:43,755 [PokemonGoBot] [INFO] Revive: 5 | MaxRevive: 0
2016-08-17 08:10:43,755 [PokemonGoBot] [INFO]
2016-08-17 08:10:43,756 [PokemonGoBot] [INFO] Found encrypt.so! Platform: linux2 Encrypt.so directory: /home/ddenouden/PokemonGo-Bot
2016-08-17 08:10:43,756 [PokemonGoBot] [INFO]
2016-08-17 08:10:44,326 [SleepSchedule] [INFO] [next_sleep] Next sleep at 2016-08-17 22:43:02.326048
2016-08-17 08:10:44,326 [SleepSchedule] [INFO] [next_sleep] Next sleep at 2016-08-17 10:11:28.326378
2016-08-17 08:10:44,326 [SleepSchedule] [INFO] [next_sleep] Next sleep at 2016-08-17 13:37:46.326632
2016-08-17 08:10:44,327 [SleepSchedule] [INFO] [next_sleep] Next sleep at 2016-08-17 18:40:55.327181
2016-08-17 08:10:45,447 [       cli] [INFO]
2016-08-17 08:10:45,447 [       cli] [INFO] Ran for 0:00:04
2016-08-17 08:10:45,447 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-17 08:10:45,447 [       cli] [INFO] Travelled 0.00km
2016-08-17 08:10:45,448 [       cli] [INFO] Visited 0 stops
2016-08-17 08:10:45,448 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-17 08:10:45,448 [       cli] [INFO] Threw 0 pokeballs
2016-08-17 08:10:45,448 [       cli] [INFO] Earned 0 Stardust
2016-08-17 08:10:45,448 [       cli] [INFO]
2016-08-17 08:10:45,448 [       cli] [INFO] Highest CP Pokemon:
2016-08-17 08:10:45,448 [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 572, in <module>
    main()
  File "pokecli.py", line 91, in main
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "/home/ddenouden/PokemonGo-Bot/pokemongo_bot/tree_config_builder.py", line 74, in build
    instance = worker(self.bot, task_config)
  File "/home/ddenouden/PokemonGo-Bot/pokemongo_bot/base_task.py", line 13, in __init__
    self.initialize()
  File "/home/ddenouden/PokemonGo-Bot/pokemongo_bot/cell_workers/follow_path.py", line 18, in initialize
    self.points = self.load_path()
  File "/home/ddenouden/PokemonGo-Bot/pokemongo_bot/cell_workers/follow_path.py", line 36, in load_path
    return self.load_json()
  File "/home/ddenouden/PokemonGo-Bot/pokemongo_bot/cell_workers/follow_path.py", line 41, in load_json

### Steps to Reproduce

Starting bot with normal MoveToFort task works fine.

### Other Information
OS: Ubuntu 16.04
 
Branch: Dev
Git Commit: 805930d
Python Version: Python 2.7.12

**Comment by k4n30** [comment]
@balpoint Can you update as there were some key changes since you made this issue, and update your OP if the information / errors have changed, and indicate if it's resolved or still present

Can you also please provide your path file

**Comment by balpoint** [comment]
@k4n30 man i'm sorry for wasting your time, i just figured out that i placed a , at the end of the last coordinate of the path file......it's working!

**Comment by k4n30** [comment]
No worries - I assumed it was your path file hence why I asked for it, glad u got it sorted.
