### ISSUE TITLE
MoveToMapPokemon erorr

### ISSUE THREAD

**Issue by cbogithub** [PokemonGoF/PokemonGo-Bot#4149]
branch: dev
python : 2.7.12

```
2016-08-17 17:04:28,849 [EvolvePokemon] [INFO] [skip_evolve] Skipping evolve because has no lucky egg.
2016-08-17 17:04:32,878 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_teleport_to] Teleporting to Magikarp. (0.46km)
2016-08-17 17:04:32,878 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_encounter] Encountered Pokemon: Magikarp
2016-08-17 17:04:33,125 [       cli] [INFO] 
2016-08-17 17:04:33,125 [       cli] [INFO] Ran for 0:00:12
2016-08-17 17:04:33,125 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-17 17:04:33,125 [       cli] [INFO] Travelled 0.00km
2016-08-17 17:04:33,125 [       cli] [INFO] Visited 0 stops
2016-08-17 17:04:33,125 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-17 17:04:33,125 [       cli] [INFO] Threw 0 pokeballs
2016-08-17 17:04:33,125 [       cli] [INFO] Earned 0 Stardust
2016-08-17 17:04:33,125 [       cli] [INFO] 
2016-08-17 17:04:33,125 [       cli] [INFO] Highest CP Pokemon: 
2016-08-17 17:04:33,125 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 570, in <module>
    main()
  File "pokecli.py", line 104, in main
    bot.tick()
  File "P:\pokemon go\PokemonGo-Bot\pokemongo_bot\__init__.py", line 501, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "P:\pokemon go\PokemonGo-Bot\pokemongo_bot\cell_workers\move_to_map_pokemon.py", line 267, in work
    self.snipe(pokemon)
  File "P:\pokemon go\PokemonGo-Bot\pokemongo_bot\cell_workers\move_to_map_pokemon.py", line 220, in snipe
    catch_worker = PokemonCatchWorker(pokemon, self.bot)
TypeError: __init__() takes exactly 4 arguments (3 given)
```

**Comment by k4n30** [comment]
fixed in latest dev
