### ISSUE TITLE
Bot not working after opening it from the phone app

### ISSUE THREAD

**Issue by bilalkamoon** [PokemonGoF/PokemonGo-Bot#4210]
### Steps to Reproduce
The bot was working fine, until I stopped the script, opened it from my phone, accepted ToS, caught my started, looked at my inventory then signed out again.
I tried to run the bot script again but I got this message. My bot isn't banned.

### Output when issue occurred
2016-08-18 14:36:20,434 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be
 busy or offline - try again - 4/15
.
.
.
2016-08-18 14:37:38,040 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be
 busy or offline - try again - 15/15
Traceback (most recent call last):
  File "pokecli.py", line 578, in <module>
    main()
  File "pokecli.py", line 145, in main
    report_summary(bot)
  File "pokecli.py", line 180, in report_summary
    metrics.capture_stats()
  File "C:\Users\Win8\Downloads\PokemonGo-Bot-dev - Leb\PokemonGo-Bot-dev\pokemo
ngo_bot\metrics.py", line 84, in capture_stats
    response_dict = request.call()
  File "C:\Users\Win8\Downloads\PokemonGo-Bot-dev - Leb\PokemonGo-Bot-dev\pokemo
ngo_bot\api_wrapper.py", line 133, in call
    raise ServerBusyOrOfflineException()
pgoapi.exceptions.ServerBusyOrOfflineException

### Other Information
OS: 
Win 8
Branch: 
dev
Python Version: 
2.17

**Comment by k4n30** [comment]
The server is either Busy or Offline or you have "some type" of the ban - soft / IP / permanent. There are so many possible types and they aren't all well known yet

Not a bot issue
