### ISSUE TITLE
NameError: global name 'alt' is not defined

### ISSUE THREAD

**Issue by cbogithub** [PokemonGoF/PokemonGo-Bot#4260]
```
Traceback (most recent call last):
  File "pokecli.py", line 611, in <module>
    main()
  File "pokecli.py", line 105, in main
    bot.tick()
  File "P:\pokemon go\PokemonGo-Bot\pokemongo_bot\__init__.py", line 532, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "P:\pokemon go\PokemonGo-Bot\pokemongo_bot\cell_workers\move_to_map_pokemon.py", line 275, in work
    self.snipe(pokemon)
  File "P:\pokemon go\PokemonGo-Bot\pokemongo_bot\cell_workers\move_to_map_pokemon.py", line 226, in snipe
    self._teleport_to(pokemon)
  File "P:\pokemon go\PokemonGo-Bot\pokemongo_bot\cell_workers\move_to_map_pokemon.py", line 339, in _teleport_to
    self.bot.api.set_position(pokemon['latitude'], pokemon['longitude'], alt)
NameError: global name 'alt' is not defined
```

```{
    "auth_service": "ptc",
    "username": "xxxx",
    "password": "xxxxx",
    "location": "xxxxx",
    "gmapkey": "xxxxx",
    "encrypt_location": "",
    "websocket_server": false,
    "heartbeat_threshold": 10,
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "22:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },
      {
        "type": "CompleteTutorial",
        "config": {
          "enabled": false,
          "// set a name": "",
          "nickname": ""
        }
      },
      {
         "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": true,
          "min_interval": 10,
          "stats": ["uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "UpdateLiveInventory",
        "config": {
          "enabled": true,
          "min_interval": 120,
          "show_all_multiple_lines": false,
          "items": ["space_info", "pokeballs", "greatballs", "ultraballs", "razzberries", "luckyegg"]
        }
      },
      {
        "type": "TransferPokemon",
        "config": {
          "transfer_wait_min": 1,
          "transfer_wait_max": 4
        }
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": true,
          "nickname_template": "{name:.8s}-{iv_pct}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": true
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "max_balls_keep": 150,
          "max_potions_keep": 50,
          "max_berries_keep": 70,
          "max_revives_keep": 70,
          "item_filter": {
				"Pokeball": {"keep": 50},
				"Greatball": {"keep": 100},
				"Ultraball": {"keep": 50},
				"Potion": {"keep": 0},
				"Super Potion": {"keep": 0},
				"Hyper Potion": {"keep": 0},
				"Revive": {"keep": 0},
				"Max Potion": {"keep": 50},
				"Max Revive": {"keep": 50},
				"Razz Berry": {"keep": 50}
            },
          "recycle_wait_min": 1,
          "recycle_wait_max": 4
        }
      },
	    {
	      "type": "CatchPokemon",
	      "config": {
	        "catch_visible_pokemon": true,
	        "catch_lured_pokemon": true,
	        "min_ultraball_to_keep": 5,
	        "catch_throw_parameters": {
	          "excellent_rate": 0.1,
	          "great_rate": 0.5,
	          "nice_rate": 0.3,
	          "normal_rate": 0.1,
	          "spin_success_rate" : 0.6
	        },
				  "catch_simulation": {
				    "flee_count": 3,
				    "flee_duration": 2,
				    "catch_wait_min": 2,
				    "catch_wait_max": 6,
				    "berry_wait_min": 2,
				    "berry_wait_max": 3,
				    "changeball_wait_min": 2,
				    "changeball_wait_max": 3
				  }
	      }
	    },
      {
        "type": "SpinFort",
        "config": {
          "spin_wait_min": 2,
          "spin_wait_max": 3
        }
      },
      {
        "type": "MoveToMapPokemon",
        "config": {
          "address": "http://localhost:5000",
          "max_distance": 500,
          "min_ball": 50,
          "prioritize_vips": true,
          "snipe": true,
          "snipe_high_prio_only": true,
          "snipe_high_prio_threshold": 400,
          "update_map": true,
          "mode": "priority",
          "map_path": "raw_data",
          "walker": "StepWalker",
"catch": {
                "Mewtwo": 990,
                "Mew": 980,
                "Moltres": 970,
                "Zapdos": 960,
                "Articuno": 950,

                "Snorlax": 940,
                "Lapras": 930,
                "Dragonite": 920,
                "Dragonair": 910,
                "Dratini": 900,

                "Vaporeon": 890,
                "Eevee": 885,
                "Arcanine": 880,
                "Growlithe": 875,
                "Exeggutor": 870,
                "Exeggcute": 865,
                "Gyarados": 860,
                "Magikarp": 855,
                "Muk": 850,
                "Grimer": 845,

                "Machamp": 790,
                "Machop": 797,
                "Machoke": 785,
                "Victreebel": 780,
                "Weepinbell": 787,
                "Bellsprout": 775,
                "Cloyster": 770,
                "Shellder": 765,
                "Golduck": 750,
                "Psyduck": 745,

                "Chansey": 100
            }
        }
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "pokemon_bag": {
      "// if 'show_at_start' is true, it will log all the pokemons in the bag (not eggs) at bot start": {},
      "show_at_start": false,
      "// if 'show_count' is true, it will show the amount of each pokemon (minimum 1)": {},
      "show_count": false,
      "// 'pokemon_info' parameter define which info to show for each pokemon": {},
      "// the available options are": {},
      "// ['cp', 'iv_ads', 'iv_pct', 'ivcp', 'ncp', 'level', 'hp', 'moveset', 'dps']": {},
      "pokemon_info": ["cp", "iv_pct"]
    },
    "walk_max": 50.16,
    "walk_min": 5.16,
    "alt_min": 0.75,
    "alt_max": 2.5,
    "debug": false,
    "test": false,
    "health_record": false,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging_color": true,
    "daily_catch_limit": 800,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
"release": {
        "//100 / 97.7 / 95.5 / 93.3 /  91.1 / 88.8 / 86.6 / 84.4 / 82.2 / 80.0 / 77.7 / 75.5 / 73.3 / 71.1": {},
        "any": {"release_below_cp": 0,"release_below_iv": 0.99,"logic": "or"},

        "Snorlax": {"never_release": true},
        "Lapras": {"never_release": true},
        "Dragonite": {"never_release": true},
        "Dragonair": {"keep_best_iv": 3},
        "Dratini": {"keep_best_iv": 3},

        "Vaporeon": {"never_release": true},
        "Eevee": {"keep_best_iv": 3},
        "Arcanine": {"never_release": true},
        "Growlithe": {"keep_best_iv": 3},
        "Exeggutor": {"never_release": true},
        "Exeggcute": {"keep_best_iv": 3},
        "Gyarados": {"never_release": true},
        "Magikarp": {"keep_best_iv": 3},
        "Muk": {"never_release": true},
        "Grimer": {"keep_best_iv": 3},

        "Machamp": {"never_release": true},
        "Machoke": {"keep_best_iv": 3},
        "Machop": {"keep_best_iv": 3},
        "Victreebel": {"never_release": true},
        "Weepinbell": {"keep_best_iv": 3},
        "Bellsprout": {"keep_best_iv": 3},
        "Cloyster": {"never_release": true},
        "Shellder": {"keep_best_iv": 3},
        "Golduck": {"release_below_iv": 0.77},
        "Psyduck": {"release_below_iv": 0.77},
        "Mew": {"never_release": true},
        "Mewtwo": {"never_release": true},
        "Articuno": {"never_release": true},
        "Zapdos": {"never_release": true},
        "Moltres": {"never_release": true},
        "Chansey": {"keep_best_iv": 3},

        "Caterpie": {"always_release": true},
        "Metapod": {"always_release": true},
        "Butterfree": {"always_release": true},
        "Weedle": {"always_release": true},
        "Kakuna": {"always_release": true},
        "Beedrill": {"always_release": true},
        "Pidgey": {"always_release": true},
        "Pidgeotto": {"always_release": true},
        "Pidgeot": {"always_release": true},
        "Rattata": {"always_release": true},
        "Raticate": {"always_release": true},
        "Spearow": {"always_release": true},
        "Fearow": {"always_release": true},
        "Ekans": {"always_release": true},
        "Arbok": {"always_release": true},
        "Sandshrew": {"always_release": true},
        "Sandslash": {"always_release": true},
        "Vulpix": {"always_release": true},
        "Ninetails": {"always_release": true},
        "Zubat": {"always_release": true},
        "Golbat": {"always_release": true},
        "Paras": {"always_release": true},
        "Parasect": {"always_release": true},
        "Venonat": {"always_release": true},
        "Venomoth": {"always_release": true},
        "Diglett": {"always_release": true},
        "Dugtrio": {"always_release": true},
        "Meowth": {"always_release": true},
        "Persian": { "always_release": true},
        "Mankey": {"always_release": true},
        "Primeape": {"always_release": true},
        "Ponyta": {"always_release": true},
        "Rapidash": {"always_release": true},
        "Doduo": {"always_release": true},
        "Dodrio": {"always_release": true},
        "Drowzee": {"always_release": true},
        "Hypno": {"always_release": true},
        "Krabby": {"always_release": true},
        "Kingler": {"always_release": true},
        "Goldeen": {"always_release": true},
        "Seaking": {"always_release": true}
    },
	"vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}
```

**Comment by mjmadsen** [comment]
Should be fixed now. Closing.
