### ISSUE TITLE
help

### ISSUE THREAD

**Issue by danielocampbells** [PokemonGoF/PokemonGo-Bot#4267]
any idea ? 

(pokemonEnv) DANIELO-LION:pokemongo-bot-master usuario$ python pokecli.py -cf config.json
2016-08-19 11:19:22,349 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-19 11:19:22,353 [       cli] [INFO] Configuration initialized
2016-08-19 11:19:22,353 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-19 11:19:22,354 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-19 11:19:22,365 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-19 11:19:22,504 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-19 11:19:22,504 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-19 11:19:22,504 [PokemonGoBot] [INFO] [location_found] Location found: 34.011044, -118.497244 (34.011044, -118.497244, 0.0)
2016-08-19 11:19:22,505 [PokemonGoBot] [INFO] [position_update] Now at (34.011044, -118.497244, 0)
2016-08-19 11:19:22,505 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-19 11:19:24,995 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-19 11:19:27,376 [PokemonGoBot] [INFO] 
2016-08-19 11:19:27,377 [PokemonGoBot] [INFO] --- Danielocampbell ---
2016-08-19 11:19:27,377 [PokemonGoBot] [INFO] Level: 23 (Next Level: 33010 XP) (Total: 526990 XP)
2016-08-19 11:19:27,377 [PokemonGoBot] [INFO] Pokemon Captured: 1834 | Pokestops Visited: 2841
2016-08-19 11:19:27,378 [PokemonGoBot] [INFO] Pokemon Bag: 169/250
2016-08-19 11:19:27,379 [PokemonGoBot] [INFO] Items: 225/350
2016-08-19 11:19:27,379 [PokemonGoBot] [INFO] Stardust: 12067 | Pokecoins: 0
2016-08-19 11:19:27,379 [PokemonGoBot] [INFO] PokeBalls: 83 | GreatBalls: 66 | UltraBalls: 17 | MasterBalls: 0
2016-08-19 11:19:27,379 [PokemonGoBot] [INFO] RazzBerries: 14 | BlukBerries: 0 | NanabBerries: 0
2016-08-19 11:19:27,379 [PokemonGoBot] [INFO] LuckyEgg: 0 | Incubator: 0 | TroyDisk: 0
2016-08-19 11:19:27,379 [PokemonGoBot] [INFO] Potion: 12 | SuperPotion: 3 | HyperPotion: 10 | MaxPotion: 0
2016-08-19 11:19:27,379 [PokemonGoBot] [INFO] Incense: 1 | IncenseSpicy: 0 | IncenseCool: 0
2016-08-19 11:19:27,380 [PokemonGoBot] [INFO] Revive: 17 | MaxRevive: 0
2016-08-19 11:19:27,380 [PokemonGoBot] [INFO] 
2016-08-19 11:19:27,380 [PokemonGoBot] [INFO] Found encrypt.so! Platform: darwin Encrypt.so directory: /Users/usuario/Downloads/PokemonGo-Bot-master
2016-08-19 11:19:27,380 [PokemonGoBot] [INFO] 
2016-08-19 11:19:28,278 [SleepSchedule] [INFO] [next_sleep] Next sleep at 2016-08-19 22:55:47.278622
2016-08-19 11:19:28,620 [       cli] [INFO] 
2016-08-19 11:19:28,621 [       cli] [INFO] Ran for 0:00:06
2016-08-19 11:19:28,621 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-19 11:19:28,621 [       cli] [INFO] Travelled 0.00km
2016-08-19 11:19:28,621 [       cli] [INFO] Visited 0 stops
2016-08-19 11:19:28,621 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-19 11:19:28,621 [       cli] [INFO] Threw 0 pokeballs
2016-08-19 11:19:28,622 [       cli] [INFO] Earned 0 Stardust
2016-08-19 11:19:28,622 [       cli] [INFO] 
2016-08-19 11:19:28,622 [       cli] [INFO] Highest CP Pokemon: 
2016-08-19 11:19:28,622 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 578, in <module>
    main()
  File "pokecli.py", line 90, in main
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "/Users/usuario/Downloads/PokemonGo-Bot-master/pokemongo_bot/tree_config_builder.py", line 43, in build
    worker = self._get_worker_by_name(task_type)
  File "/Users/usuario/Downloads/PokemonGo-Bot-master/pokemongo_bot/tree_config_builder.py", line 21, in _get_worker_by_name
    raise ConfigException('No worker named {} defined'.format(name))
pokemongo_bot.tree_config_builder.ConfigException: No worker named CatchPokemon defined
2016-08-19 11:19:28,633 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/usuario/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/usuario/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/usuario/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/usuario/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/usuario/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/usuario/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/usuario/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/usuario/Downloads/PokemonGo-Bot-master/pokemonEnv/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 891, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-19 11:19:28,634 [sentry.errors.uncaught] [ERROR] [u'ConfigException: No worker named CatchPokemon defined', u'  File "pokecli.py", line 578, in <module>', u'  File "pokecli.py", line 90, in main', u'  File "pokemongo_bot/tree_config_builder.py", line 43, in build', u'  File "pokemongo_bot/tree_config_builder.py", line 21, in _get_worker_by_name']

**Comment by drricksanchez321** [comment]
"No worker named CatchPokemon defined" sounds like your config was updated to have that new task that replaces catchluredpokemon and catchvisiblepokemon, but your codebase is not the latest dev branch. update your code from the dev branch.

**Comment by danielocampbells** [comment]
i still have no idea what have to do :/ if anybody have the file or files update, or a new reinstaller help me please

**Comment by danielocampbells** [comment]
a new pokecli.py file update ?

**Comment by rovmelek** [comment]
run "git pull" or ./setup.sh -u

**Comment by danielocampbells** [comment]
(pokemonEnv) DANIELO-LION:PokemonGo-Bot-master usuario$ ./setup.sh
usage:
	-i,--install.		Install PokemonGo-Bot.
	-b,--backup.		Backup config files.
	-c,--config.		Easy config generator.
	-e,--encrypt.		Make encrypt.so.
	-r,--reset.		Force sync dev branch.
	-u,--update.		Command git pull to update.

whats next ?

**Comment by danielocampbells** [comment]
lol look like gonna update

**Comment by sediyama** [comment]
If only the update not work, try deleting the pokemongo_bot/ folder and then:
./setup.sh -r

**Comment by danielocampbells** [comment]
Installing collected packages: numpy, decorator, networkx, geopy, six, protobuf, requests, future, s2sphere, pycryptodomex, gpsoauth, xxhash, pgoapi, protobuf-to-dict, googlemaps, colorama, enum34, pyyaml, haversine, polyline, python-engineio, python-socketio, itsdangerous, click, Werkzeug, MarkupSafe, Jinja2, flask, websocket-client, socketIO-client, greenlet, eventlet, gpxpy, funcsigs, pbr, mock, timeout-decorator, contextlib2, raven, demjson
  Running setup.py develop for pgoapi
Successfully installed Jinja2-2.8 MarkupSafe-0.23 Werkzeug-0.11.10 click-6.6 colorama-0.3.7 contextlib2-0.5.4 decorator-4.0.10 demjson-2.2.4 enum34-1.1.6 eventlet-0.19.0 flask-0.11.1 funcsigs-1.0.2 future-0.15.2 geopy-1.11.0 googlemaps-2.4.4 gpsoauth-0.3.0 gpxpy-1.1.1 greenlet-0.4.10 haversine-0.4.5 itsdangerous-0.24 mock-2.0.0 networkx-1.11 numpy-1.11.0 pbr-1.10.0 pgoapi polyline-1.3.1 protobuf-3.0.0b4 protobuf-to-dict-0.1.0 pycryptodomex-3.4.2 python-engineio-0.9.2 python-socketio-1.4.2 pyyaml-3.11 raven-5.23.0 requests-2.10.0 s2sphere-0.2.4 six-1.10.0 socketIO-client-0.7.0 timeout-decorator-0.3.2 websocket-client-0.37.0 xxhash-0.6.1
(pokemonEnv) DANIELO-LION:PokemonGo-Bot-master usuario$ 




ok well then ?? whats next ???

**Comment by danielocampbells** [comment]
now i have this 








2016-08-19 12:25:24,661 [       cli] [INFO] Error: No /configs/config.json or specified config
usage: pokecli.py [-h] [-cf CONFIG] -a AUTH_SERVICE [-u USERNAME]
                  [-ws WEBSOCKET.SERVER_URL]
                  [-wss WEBSOCKET.START_EMBEDDED_SERVER]
                  [-wsr WEBSOCKET.REMOTE_CONTROL] [-p PASSWORD] [-l LOCATION]
                  [-lc LOCATION_CACHE] [--forts.spin FORTS.SPIN] [-w WALK]
                  [-k GMAPKEY] [-e SHOW_EVENTS] [-d DEBUG] [-t TEST]
                  [-du DISTANCE_UNIT] [-rt RECONNECTING_TIMEOUT]
                  [-hr HEALTH_RECORD] [-ac FORTS.AVOID_CIRCLES]
                  [-mcs FORTS.MAX_CIRCLE_SIZE] [-crf FORTS.CACHE_RECENT_FORTS]
                  [--map_object_cache_time MAP_OBJECT_CACHE_TIME]
                  [--logging_color LOGGING_COLOR]
                  [-cte CATCH_THROW_PARAMETERS.EXCELLENT_RATE]
                  [-ctg CATCH_THROW_PARAMETERS.GREAT_RATE]
                  [-ctn CATCH_THROW_PARAMETERS.NICE_RATE]
                  [-ctm CATCH_THROW_PARAMETERS.NORMAL_RATE]
                  [-cts CATCH_THROW_PARAMETERS.SPIN_SUCCESS_RATE]
pokecli.py: error: argument -a/--auth_service is required
(pokemonEnv) DANIELO-LION:pokemongo-bot-master usuario$

**Comment by Sterkoel** [comment]
[RTFM](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/configuration_files.md)

**Comment by mjmadsen** [comment]
@danielocampbells You do not have a config file setup. Please join the slack chat for assistance"
https://pokemongo-bot.slack.com/messages/help/
