### ISSUE TITLE
Starting the bot!

### ISSUE THREAD

**Issue by ia7maxd** [PokemonGoF/PokemonGo-Bot#4326]
When i try to start the bot `python pokecli.py`

this what i get : 

```
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions
```

I searched for a solution and i read that is should put this ` pip install -r requirements.txt` 
this what i get : 

```
Collecting numpy==1.11.0 (from -r requirements.txt (line 1))
  Using cached numpy-1.11.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting networkx==1.11 (from -r requirements.txt (line 2))
  Using cached networkx-1.11-py2.py3-none-any.whl
Obtaining pgoapi from git+https://github.com/keyphact/pgoapi.git@a2755eb42dfe49e359798d2f4defefc97fb8163d#egg=pgoapi (from -r requirements.txt (line 3))
  Skipping because already up-to-date.
Collecting geopy==1.11.0 (from -r requirements.txt (line 4))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf==3.0.0b4 (from -r requirements.txt (line 5))
  Using cached protobuf-3.0.0b4-py2.py3-none-any.whl
Collecting requests==2.10.0 (from -r requirements.txt (line 6))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 7))
  Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 8))
  Using cached gpsoauth-0.3.0.tar.gz
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 9))
  Using cached protobuf-to-dict-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/nosexcover/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    Couldn't find index page for 'nosexcover' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    No local packages or working download links found for nosexcover
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/xp/28dgx_1s5r19gnscydmz1f89pr91nz/T/pip-build-vYQx4f/protobuf-to-dict/setup.py", line 25, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/st1011140355/Desktop/PokemonCheat/PokemonGo-Bot/lib/python2.7/site-packages/setuptools/dist.py", line 348, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Users/st1011140355/Desktop/PokemonCheat/PokemonGo-Bot/lib/python2.7/site-packages/setuptools/dist.py", line 394, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/st1011140355/Desktop/PokemonCheat/PokemonGo-Bot/lib/python2.7/site-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/st1011140355/Desktop/PokemonCheat/PokemonGo-Bot/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1098, in best_match
        return self.obtain(req, installer)
      File "/Users/st1011140355/Desktop/PokemonCheat/PokemonGo-Bot/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1110, in obtain
        return installer(requirement)
      File "/Users/st1011140355/Desktop/PokemonCheat/PokemonGo-Bot/lib/python2.7/site-packages/setuptools/dist.py", line 461, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/st1011140355/Desktop/PokemonCheat/PokemonGo-Bot/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 658, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('nosexcover')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/xp/28dgx_1s5r19gnscydmz1f89pr91nz/T/pip-build-vYQx4f/protobuf-to-dict/
```

i get error when i try this code `pip install pgoapi`

```
Collecting pgoapi
  Could not find a version that satisfies the requirement pgoapi (from versions: )
No matching distribution found for pgoapi
```

What should i do ?

**Comment by houkop** [comment]
1) run ./setup.sh -i
2) start bot with ./run.sh

**Comment by ia7maxd** [comment]
tried doing that and this is what i got `Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions
Sat Aug 20 13:28:04 GST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.`

**Comment by ia7maxd** [comment]
anyone ? :(

**Comment by ia7maxd** [comment]
Tried to reinstall everything again, and now every time when I try to start the bot this is what i get 

`2016-08-20 15:26:45,890 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-20 15:26:45,894 [       cli] [INFO] Configuration initialized
2016-08-20 15:26:45,894 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-20 15:26:45,894 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-20 15:26:46,359 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-20 15:26:46,932 [yoyo.migrations] [INFO] Applying pokemongobot
2016-08-20 15:26:46,933 [yoyo.migrations] [INFO]  - applying step 0
2016-08-20 15:26:46,933 [yoyo.migrations] [INFO] Marking pokemongobot applied
2016-08-20 15:26:46,969 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
Traceback (most recent call last):
  File "pokecli.py", line 570, in <module>
    main()
  File "pokecli.py", line 162, in main
    report_summary(bot)
  File "pokecli.py", line 197, in report_summary
    metrics.capture_stats()
  File "/Users/st1011140355/PokemonGo-Bot/pokemongo_bot/metrics.py", line 84, in capture_stats
    response_dict = request.call()
  File "/Users/st1011140355/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 101, in call
    if not self.can_call():
  File "/Users/st1011140355/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 57, in can_call
    raise NoPlayerPositionSetException()
pgoapi.exceptions.NoPlayerPositionSetException
2016-08-20 15:26:48,022 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-20 15:26:48,052 [sentry.errors.uncaught] [ERROR] [u'NoPlayerPositionSetException', u'  File "pokecli.py", line 570, in <module>', u'  File "pokecli.py", line 162, in main', u'  File "pokecli.py", line 197, in report_summary', u'  File "pokemongo_bot/metrics.py", line 84, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 101, in call', u'  File "pokemongo_bot/api_wrapper.py", line 57, in can_call']
Sat Aug 20 15:26:48 GST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
2016-08-20 15:27:09,111 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-20 15:27:09,115 [       cli] [INFO] Configuration initialized
2016-08-20 15:27:09,115 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-20 15:27:09,115 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-20 15:27:09,133 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-20 15:27:09,634 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
Traceback (most recent call last):
  File "pokecli.py", line 570, in <module>
    main()
  File "pokecli.py", line 162, in main
    report_summary(bot)
  File "pokecli.py", line 197, in report_summary
    metrics.capture_stats()
  File "/Users/st1011140355/PokemonGo-Bot/pokemongo_bot/metrics.py", line 84, in capture_stats
    response_dict = request.call()
  File "/Users/st1011140355/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 101, in call
    if not self.can_call():
  File "/Users/st1011140355/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 57, in can_call
    raise NoPlayerPositionSetException()
pgoapi.exceptions.NoPlayerPositionSetException
2016-08-20 15:27:10,343 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-20 15:27:10,383 [sentry.errors.uncaught] [ERROR] [u'NoPlayerPositionSetException', u'  File "pokecli.py", line 570, in <module>', u'  File "pokecli.py", line 162, in main', u'  File "pokecli.py", line 197, in report_summary', u'  File "pokemongo_bot/metrics.py", line 84, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 101, in call', u'  File "pokemongo_bot/api_wrapper.py", line 57, in can_call']
Sat Aug 20 15:27:10 GST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
2016-08-20 15:27:31,484 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-20 15:27:31,487 [       cli] [INFO] Configuration initialized
2016-08-20 15:27:31,487 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-20 15:27:31,488 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-20 15:27:31,503 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-20 15:27:31,913 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
Traceback (most recent call last):
  File "pokecli.py", line 570, in <module>
    main()
  File "pokecli.py", line 162, in main
    report_summary(bot)
  File "pokecli.py", line 197, in report_summary
    metrics.capture_stats()
  File "/Users/st1011140355/PokemonGo-Bot/pokemongo_bot/metrics.py", line 84, in capture_stats
    response_dict = request.call()
  File "/Users/st1011140355/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 101, in call
    if not self.can_call():
  File "/Users/st1011140355/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 57, in can_call
    raise NoPlayerPositionSetException()
pgoapi.exceptions.NoPlayerPositionSetException
2016-08-20 15:27:32,510 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/st1011140355/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-20 15:27:32,512 [sentry.errors.uncaught] [ERROR] [u'NoPlayerPositionSetException', u'  File "pokecli.py", line 570, in <module>', u'  File "pokecli.py", line 162, in main', u'  File "pokecli.py", line 197, in report_summary', u'  File "pokemongo_bot/metrics.py", line 84, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 101, in call', u'  File "pokemongo_bot/api_wrapper.py", line 57, in can_call']
Sat Aug 20 15:27:32 GST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.`

**Comment by k4n30** [comment]
Please take this discussion to the slackserver as per README
