### ISSUE TITLE
Bot Stops after loggin in ?!

### ISSUE THREAD

**Issue by ia7maxd** [PokemonGoF/PokemonGo-Bot#4363]
When i start the bot it logged in successfully after that the bot stops immediately

```
2016-08-20 17:41:50,760 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-20 17:41:50,762 [       cli] [INFO] No config argument specified, checking for /configs/config.json
2016-08-20 17:41:50,764 [       cli] [INFO] Configuration initialized
2016-08-20 17:41:50,764 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-20 17:41:50,764 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-20 17:41:51,182 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-20 17:41:51,618 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-20 17:41:52,645 [PokemonGoBot] [INFO] [location_found] Location found: Central Park, New York (40.7711329, -73.97418739999999, 0.0)
2016-08-20 17:41:52,645 [PokemonGoBot] [INFO] [position_update] Now at (40.7711329, -73.97418739999999, 0)
2016-08-20 17:41:52,645 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-20 17:41:55,955 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-20 17:41:57,291 [PokemonGoBot] [INFO] 
2016-08-20 17:41:57,291 [PokemonGoBot] [INFO] --- ******** ---

2016-08-20 17:41:57,291 [PokemonGoBot] [INFO] Level: 25 (Next Level: 79620 XP) (Total: 820380 XP)

2016-08-20 17:41:57,292 [PokemonGoBot] [INFO] Pokemon Captured: 2000 | Pokestops Visited: 3379

2016-08-20 17:41:57,292 [PokemonGoBot] [INFO] Pokemon Bag: 110/250

2016-08-20 17:41:57,293 [PokemonGoBot] [INFO] Items: 280/350

2016-08-20 17:41:57,293 [PokemonGoBot] [INFO] Stardust: 231585 | Pokecoins: 0

2016-08-20 17:41:57,293 [PokemonGoBot] [INFO] PokeBalls: 12 | GreatBalls: 38 | UltraBalls: 100 | MasterBalls: 0
2016-08-20 17:41:57,293 [PokemonGoBot] [INFO] RazzBerries: 47 | BlukBerries: 0 | NanabBerries: 0
2016-08-20 17:41:57,293 [PokemonGoBot] [INFO] LuckyEgg: 0 | Incubator: 0 | TroyDisk: 6
2016-08-20 17:41:57,294 [PokemonGoBot] [INFO] Potion: 1 | SuperPotion: 0 | HyperPotion: 0 | MaxPotion: 44
2016-08-20 17:41:57,294 [PokemonGoBot] [INFO] Incense: 0 | IncenseSpicy: 0 | IncenseCool: 0
2016-08-20 17:41:57,294 [PokemonGoBot] [INFO] Revive: 30 | MaxRevive: 0
2016-08-20 17:41:57,294 [PokemonGoBot] [INFO] 
2016-08-20 17:41:57,294 [PokemonGoBot] [INFO] Found encrypt.so! Platform: darwin Encrypt.so directory: /Users/st1011140355/Desktop/poke/PokemonGo-Bot
2016-08-20 17:41:57,294 [PokemonGoBot] [INFO] 
2016-08-20 17:42:01,617 [SleepSchedule] [INFO] [next_sleep] Next sleep at 2016-08-20 22:50:20.617778
2016-08-20 17:42:02,335 [       cli] [INFO] 
2016-08-20 17:42:02,335 [       cli] [INFO] Ran for 0:00:11
2016-08-20 17:42:02,335 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-20 17:42:02,335 [       cli] [INFO] Travelled 0.00km
2016-08-20 17:42:02,336 [       cli] [INFO] Visited 0 stops
2016-08-20 17:42:02,336 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-20 17:42:02,336 [       cli] [INFO] Threw 0 pokeballs
2016-08-20 17:42:02,336 [       cli] [INFO] Earned 0 Stardust
2016-08-20 17:42:02,336 [       cli] [INFO] 
2016-08-20 17:42:02,336 [       cli] [INFO] Highest CP Pokemon: 
2016-08-20 17:42:02,336 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 570, in <module>
    main()
  File "pokecli.py", line 91, in main
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "/Users/st1011140355/Desktop/poke/PokemonGo-Bot/pokemongo_bot/tree_config_builder.py", line 74, in build
    instance = worker(self.bot, task_config)
  File "/Users/st1011140355/Desktop/poke/PokemonGo-Bot/pokemongo_bot/base_task.py", line 13, in __init__
    self.initialize()
  File "/Users/st1011140355/Desktop/poke/PokemonGo-Bot/pokemongo_bot/cell_workers/recycle_items.py", line 57, in initialize
    self._validate_item_filter()
  File "/Users/st1011140355/Desktop/poke/PokemonGo-Bot/pokemongo_bot/cell_workers/recycle_items.py", line 72, in _validate_item_filter
    config_item_name))
pokemongo_bot.tree_config_builder.ConfigException: item Great Ball does not exist, spelling mistake? (check for valid item names in data/items.json)
2016-08-20 17:42:02,349 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/st1011140355/Desktop/poke/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/st1011140355/Desktop/poke/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/st1011140355/Desktop/poke/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/st1011140355/Desktop/poke/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/st1011140355/Desktop/poke/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/st1011140355/Desktop/poke/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/st1011140355/Desktop/poke/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/st1011140355/Desktop/poke/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-20 17:42:02,351 [sentry.errors.uncaught] [ERROR] [u'ConfigException: item Great Ball does not exist, spelling mistake? (check for valid item names in data/items.json)', u'  File "pokecli.py", line 570, in <module>', u'  File "pokecli.py", line 91, in main', u'  File "pokemongo_bot/tree_config_builder.py", line 74, in build', u'  File "pokemongo_bot/base_task.py", line 13, in __init__', u'  File "pokemongo_bot/cell_workers/recycle_items.py", line 57, in initialize', u'  File "pokemongo_bot/cell_workers/recycle_items.py", line 72, in _validate_item_filter']
```

**Comment by Calcyfer** [comment]
Last line of your log explains it.

**Comment by ia7maxd** [comment]
@Calcyfer Thank you I didn't see that 💯

**Comment by Calcyfer** [comment]
Anytime. Don't forget to close the issue if it's solved now :)
