### ISSUE TITLE
[move-to-map] bot got erorr after 10 minutes

### ISSUE THREAD

**Issue by cbogithub** [PokemonGoF/PokemonGo-Bot#4374]
```
2016-08-20 22:01:04,200 [PokemonCatchWorker] [INFO] [gained_candy] You now have 1461 Psyduck candy!
2016-08-20 22:01:09,204 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_move_towards] Moving towards Psyduck, 1.19km, left (4 minutes, 49 seconds)
2016-08-20 22:01:10,806 [PokemonGoBot] [INFO] [api_error] Session stale, re-logging in.
2016-08-20 22:01:10,806 [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "pokecli.py", line 674, in <module>
    main()
  File "pokecli.py", line 176, in main
    report_summary(bot)
  File "pokecli.py", line 211, in report_summary
    metrics.capture_stats()
  File "P:\pokemon go\PokemonGo-Bot\pokemongo_bot\metrics.py", line 84, in capture_stats
    response_dict = request.call()
  File "P:\pokemon go\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 217, in call
    if not self.can_call():
  File "P:\pokemon go\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 118, in can_call
    raise NoPlayerPositionSetException()
pgoapi.exceptions.NoPlayerPositionSetException
>Exit code: 1
```

**Comment by mjmadsen** [comment]
#4364 was merged into the dev branch and should have fixed this. Please reopen if current dev branch does not work.
