### ISSUE TITLE
'utf8' codec can't decode byte 0x9c in position 1: invalid start byte

### ISSUE THREAD

**Issue by neohunter** [PokemonGoF/PokemonGo-Bot#4380]
I'm receiving utf-8 errors, seems to be while sending statistics.

```
2016-08-20 10:59:51,041 [PokemonGoBot] [INFO] [api_error] Session stale, re-logging in.
Traceback (most recent call last):
  File "pokecli.py", line 674, in <module>
    main()
  File "pokecli.py", line 176, in main
    report_summary(bot)
  File "pokecli.py", line 211, in report_summary
    metrics.capture_stats()
  File "/usr/src/app/pokemongo_bot/metrics.py", line 84, in capture_stats
    response_dict = request.call()
  File "/usr/src/app/pokemongo_bot/api_wrapper.py", line 217, in call
    if not self.can_call():
  File "/usr/src/app/pokemongo_bot/api_wrapper.py", line 118, in can_call
    raise NoPlayerPositionSetException()
pgoapi.exceptions.NoPlayerPositionSetException
2016-08-20 10:59:51,054 [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)



  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
  File "/usr/local/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
2016-08-20 10:59:51,056 [sentry.errors.uncaught] [ERROR] [u'NoPlayerPositionSetException', u'  File "pokecli.py", line 674, in <module>', u'  File "pokecli.py", line 176, in main', u'  File "pokecli.py", line 211, in report_summary', u'  File "pokemongo_bot/metrics.py", line 84, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 217, in call', u'  File "pokemongo_bot/api_wrapper.py", line 118, in can_call']
```

running with dev a1c9419521c9ed28e361aaecc87581addfce6ba8

**Comment by thereyrey** [comment]
#4368

**Comment by chrisle** [comment]
The previous suggestion to update pgoapi to 1.1.8 doesn't work (#4368). I have version 1.1.8 and I'm getting this error. Details reported in #4477

**Comment by Eastkap** [comment]
same on OS X darwin...

**Comment by macpaul** [comment]
After bi-secting, this issue happened after commit "695ca70305be244a5c6fc12464d5242f14f648e7".
While "d02152308882c31329df72a2de1309b978fdfcef" was the last okay commit.

**Comment by macpaul** [comment]
After bi-secting, this issue happened after commit "695ca70305be244a5c6fc12464d5242f14f648e7".
While "d02152308882c31329df72a2de1309b978fdfcef" was the last okay commit.

**Comment by macpaul** [comment]
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
2016-08-22 13:28:06,025 [sentry.errors.uncaught] [ERROR] [u"NameError: global name 'fort_details' is not defined", u'  File "pokecli.py", line 685, in <module>', u'  File "pokecli.py", line 118, in main', u'  File "pokemongo_bot/__init__.py", line 565, in tick', u'  File "pokemongo_bot/cell_workers/catch_pokemon.py", line 29, in work', u'  File "pokemongo_bot/cell_workers/catch_pokemon.py", line 91, in get_lured_pokemon']

**Comment by macpaul** [comment]
It looks like this issue can be duplicate to (#4528).

**Comment by k4n30** [comment]
@mjmadsen close this?

**Comment by mjmadsen** [comment]
Yeah.
