### ISSUE TITLE
"Pokemon not present in the inventory" while transfering with PokemonOptimizer

### ISSUE THREAD

**Issue by NovaDev94** [PokemonGoF/PokemonGo-Bot#4386]
### Expected Behavior

Pokemon transferred by sending `release_pokemon` API request and removed from the cached inventory.  

### Actual Behavior

`release_pokemon` API request sent but error raised when removing from cached inventory

### Output when issue occurred

```
2016-08-20 23:51:37,320 [PokemonOptimizer] [INFO] [pokemon_release] Exchanged Weedle [IV 0.56] [CP 70] [307 candies]
2016-08-20 23:51:37,860 [       cli] [INFO]
2016-08-20 23:51:37,860 [       cli] [INFO] Ran for 0:00:17
2016-08-20 23:51:37,860 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-20 23:51:37,860 [       cli] [INFO] Travelled 0.00km
2016-08-20 23:51:37,860 [       cli] [INFO] Visited 0 stops
2016-08-20 23:51:37,860 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-20 23:51:37,860 [       cli] [INFO] Threw 0 pokeballs
2016-08-20 23:51:37,860 [       cli] [INFO] Earned 0 Stardust
2016-08-20 23:51:37,861 [       cli] [INFO]
2016-08-20 23:51:37,861 [       cli] [INFO] Highest CP Pokemon:
2016-08-20 23:51:37,861 [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 674, in <module>
    main()
  File "pokecli.py", line 118, in main
    bot.tick()
  File "/research/pokemon/PokemonGo-Bot/pokemongo_bot/__init__.py", line 541, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/research/pokemon/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_optimizer.py", line 80, in work
    self.apply_optimization(transfer_all, evo_all)
  File "/research/pokemon/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_optimizer.py", line 268, in apply_optimization
    self.transfer_pokemon(pokemon)
  File "/research/pokemon/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_optimizer.py", line 321, in transfer_pokemon
    inventory.pokemons().remove(pokemon.unique_id)
  File "/research/pokemon/PokemonGo-Bot/pokemongo_bot/inventory.py", line 338, in remove
    raise ValueError("Pokemon not present in the inventory")
```

**Comment by NovaDev94** [comment]
Seems like the reason is the Pokemons are put twice to the transfer list 

```
2016-08-20 23:59:07,723 [PokemonOptimizer] [INFO] [pokemon_release] Exchanged Venomoth [IV 0.87] [CP 1000] [191 candies]
2016-08-20 23:59:10,933 [PokemonOptimizer] [INFO] [pokemon_release] Exchanged Venomoth [IV 0.87] [CP 1000] [191 candies]
Pokemon not present in the inventory
2016-08-20 23:59:13,840 [PokemonOptimizer] [INFO] [pokemon_release] Exchanged Poliwag [IV 0.38] [CP 306] [156 candies]
2016-08-20 23:59:16,969 [PokemonOptimizer] [INFO] [pokemon_release] Exchanged Poliwag [IV 0.38] [CP 306] [156 candies]
Pokemon not present in the inventory
2016-08-20 23:59:20,754 [PokemonOptimizer] [INFO] [pokemon_release] Exchanged Weepinbell [IV 0.69] [CP 741] [130 candies]
2016-08-20 23:59:25,002 [PokemonOptimizer] [INFO] [pokemon_release] Exchanged Weepinbell [IV 0.69] [CP 741] [130 candies]
Pokemon not present in the inventory
2016-08-20 23:59:27,570 [PokemonOptimizer] [INFO] [pokemon_release] Exchanged Graveler [IV 0.62] [CP 640] [19 candies]
2016-08-20 23:59:31,124 [PokemonOptimizer] [INFO] [pokemon_release] Exchanged Graveler [IV 0.62] [CP 640] [19 candies]
```

**Comment by NovaDev94** [comment]
Closed due to config problems... Sorry for wasting your time guys...
