### ISSUE TITLE
TypeError: call() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by Arcasss** [PokemonGoF/PokemonGo-Bot#4398]
### Expected Behavior
Actualy using bot.

### Actual Behavior
After successful login, I am getting this error 

2016-08-20 20:37:39,650 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-20 20:37:42,552 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-20 20:37:42,553 [PokemonGoBot] [INFO] Found encrypt.dll! Platform: win32 encrypt.dll directory: C:\Programy\PokemonGo-Bot
2016-08-20 20:37:42,553 [PokemonGoBot] [INFO]
Traceback (most recent call last):
  File "pokecli.py", line 674, in <module>
    main()
  File "pokecli.py", line 176, in main
    report_summary(bot)
  File "pokecli.py", line 211, in report_summary
    metrics.capture_stats()
  File "C:\Programy\PokemonGo-Bot\pokemongo_bot\metrics.py", line 84, in capture_stats
    response_dict = request.call()
  File "C:\Programy\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 233, in call
    result = self._call()
  File "C:\Programy\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 182, in _call
    return PGoApiRequest.call(self, signature)
TypeError: call() takes exactly 1 argument (2 given)
Sat, Aug 20, 2016 8:37:42 PM Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

### Steps to Reproduce
I tried with my standard config, but it stopped work. Also tried full reinstall, but same issue.

### Other Information
OS: Windows 10, gitbash
Branch: dev
 
Git Commit: ff331ea0cfae988a0937b8b091f2fbf51271c240
 
Python Version: Python 2.7.12

**Comment by Arcasss** [comment]
I removed signature from api_wrapper.py
return PGoApiRequest.call(self, signature) -> return PGoApiRequest.call(self), but it is temporary workaround, anyone knows what is going on?

**Comment by josegrobles** [comment]
You need to do 

> pip  -r install requirements.txt

**Comment by Arcasss** [comment]
I did, but it doesnt work. I opened project in PyCharm and it says, that wrong dependency is used. Project uses depedency from site-packages/pgoapi and not from pgoapi in project folder.

**Comment by Arcasss** [comment]
It always downloads wrong version 1.1.6 

...
Requirement already up-to-date: MarkupSafe in c:\programy\python27\lib\site-packages (from Jinja2>=2.4->flask==0.11.1->-r requirements.txt (line 17))
Requirement already up-to-date: Unidecode>=0.04.16 in c:\programy\python27\lib\site-packages (from python-slugify->yoyo-migrations==5.0.3->-r requirements.txt (line 26))
Installing collected packages: pgoapi
  Running setup.py develop for pgoapi
Successfully installed pgoapi-1.1.6

**Comment by Arcasss** [comment]
I had to manually delete pgoapi package in Python\Lib\site-packages to force download the newest version.
Solved for now.
