### ISSUE TITLE
bot doenst start

### ISSUE THREAD

**Issue by mrwing1** [PokemonGoF/PokemonGo-Bot#440]
full start
XXXXXX:PokemonGo-Bot XXXX$ python pokecli.py -a google -u XXXXXXXX -p XXXXXXXX --location "XXXXXXXX, XXXXXXXXX“ -m farm
> 
and thats forever

**Comment by millejosh** [comment]
@mrwing1 we can not help you if you do not provide more information 

IE - OS, Master or Dev, Full error message

**Comment by vladlaptev** [comment]
Very detailed description of the error. Where is error log?

**Comment by mrwing1** [comment]
fixed that im now softbanned

2016-07-23 16:24 GMT+02:00 Vlad <notifications@github.com>:

**Comment by seorniyc** [comment]
[x] Initializing PokemonGO Bot v1.0
[x] PokemonGo Bot [@PokemonGoF | @eggins | @crack00r | @ethervoid | /r/pokemongodev]
[x] Configuration Initialized

Traceback (most recent call last):
  File "pokecli.py", line 128, in <module>
    main()
  File "pokecli.py", line 120, in main
    bot.start()
  File "C:\Users\Ayhan\PokemonGo-Bot\bot.py", line 26, in start
    self._setup_api()
  File "C:\Users\Ayhan\PokemonGo-Bot\bot.py", line 85, in _setup_api
    self._set_starting_position()
  File "C:\Users\Ayhan\PokemonGo-Bot\bot.py", line 220, in _set_starting_position
    self.position = self._get_pos_by_name(self.config.location)
  File "C:\Users\Ayhan\PokemonGo-Bot\bot.py", line 238, in _get_pos_by_name
    return (loc.latitude, loc.longitude, loc.altitude)
AttributeError: 'NoneType' object has no attribute 'latitude'

Adress type cannot work with coordinates on me.

**Comment by millejosh** [comment]
@seorniyc what coor'ds are you entering?

@mrwing1 if the error is resolved please close the issue

**Comment by Sharpienero** [comment]
Full the most recent repo and try again.

**Comment by seorniyc** [comment]
"33.812051,-117.919263" coordinates
