### ISSUE TITLE
bot crashes after login

### ISSUE THREAD

**Issue by agetnc313** [PokemonGoF/PokemonGo-Bot#4404]
--------------------Starting bot--------------------

2016-08-20 12:20:25,842 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-20 12:20:25,844 [       cli] [INFO] No config argument specified, checking for /configs/config.json
2016-08-20 12:20:25,846 [       cli] [INFO] Configuration initialized
2016-08-20 12:20:25,846 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-20 12:20:25,848 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-20 12:20:25,858 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-20 12:20:26,084 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-20 12:20:27,349 [PokemonGoBot] [INFO] [location_found] Location found: Santa Monica (34.0194543, -118.4911912, 0.0)
2016-08-20 12:20:27,351 [PokemonGoBot] [INFO] [position_update] Now at (34.0194543, -118.4911912, 0)
2016-08-20 12:20:27,352 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-20 12:20:28,474 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-20 12:20:29,802 [PokemonGoBot] [INFO]
2016-08-20 12:20:29,803 [PokemonGoBot] [INFO] --- Chriscrutt ---
2016-08-20 12:20:29,805 [PokemonGoBot] [INFO] Level: 20 (Next Level: 24810 XP) (Total: 235190 XP)
2016-08-20 12:20:29,805 [PokemonGoBot] [INFO] Pokemon Captured: 886 | Pokestops Visited: 1002
2016-08-20 12:20:29,805 [PokemonGoBot] [INFO] Pokemon Bag: 214/250
2016-08-20 12:20:29,806 [PokemonGoBot] [INFO] Items: 175/350
2016-08-20 12:20:29,808 [PokemonGoBot] [INFO] Stardust: 407 | Pokecoins: 110
2016-08-20 12:20:29,808 [PokemonGoBot] [INFO] PokeBalls: 76 | GreatBalls: 24 | UltraBalls: 10 | MasterBalls: 0
2016-08-20 12:20:29,808 [PokemonGoBot] [INFO] RazzBerries: 34 | BlukBerries: 0 | NanabBerries: 0
2016-08-20 12:20:29,809 [PokemonGoBot] [INFO] LuckyEgg: 2 | Incubator: 2 | TroyDisk: 2
2016-08-20 12:20:29,809 [PokemonGoBot] [INFO] Potion: 12 | SuperPotion: 2 | HyperPotion: 3 | MaxPotion: 0
2016-08-20 12:20:29,809 [PokemonGoBot] [INFO] Incense: 2 | IncenseSpicy: 0 | IncenseCool: 0
2016-08-20 12:20:29,809 [PokemonGoBot] [INFO] Revive: 4 | MaxRevive: 0
2016-08-20 12:20:29,809 [PokemonGoBot] [INFO]
2016-08-20 12:20:29,811 [PokemonGoBot] [INFO] Found encrypt_64.dll! Platform: win32 Encrypt.so directory: C:\Users\chris\Desktop\PokemonGo-Bot
2016-08-20 12:20:29,811 [PokemonGoBot] [INFO]
2016-08-20 12:20:30,023 [   Pokemon] [ERROR] Unexpected moveset [Mud Shot, Rock Slide] for #139 Omastar, please update info in pokemon.json and create issue/PR
2016-08-20 12:20:31,766 [       cli] [INFO]
2016-08-20 12:20:31,766 [       cli] [INFO] Ran for 0:00:06
2016-08-20 12:20:31,766 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-20 12:20:31,767 [       cli] [INFO] Travelled 0.00km
2016-08-20 12:20:31,767 [       cli] [INFO] Visited 0 stops
2016-08-20 12:20:31,767 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-20 12:20:31,769 [       cli] [INFO] Threw 0 pokeballs
2016-08-20 12:20:31,769 [       cli] [INFO] Earned 0 Stardust
2016-08-20 12:20:31,769 [       cli] [INFO]
2016-08-20 12:20:31,769 [       cli] [INFO] Highest CP Pokemon:
2016-08-20 12:20:31,769 [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 570, in <module>
    main()
  File "pokecli.py", line 91, in main
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "C:\Users\chris\Desktop\PokemonGo-Bot\pokemongo_bot\tree_config_builder.py", line 74, in build
    instance = worker(self.bot, task_config)
  File "C:\Users\chris\Desktop\PokemonGo-Bot\pokemongo_bot\base_task.py", line 13, in __init__
    self.initialize()
  File "C:\Users\chris\Desktop\PokemonGo-Bot\pokemongo_bot\cell_workers\sleep_schedule.py", line 37, in initialize
    self._process_config()
  File "C:\Users\chris\Desktop\PokemonGo-Bot\pokemongo_bot\cell_workers\sleep_schedule.py", line 59, in _process_config
    duration_random_offset = datetime.strptime(self.config.get('duration_random_offset', '00:30'), '%H:%M')
  File "c:\python27\Lib\_strptime.py", line 335, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: 1
2016-08-20 12:20:31,792 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\PokemonGo-Bot\lib\site-packages\raven\transport\threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "C:\Users\chris\Desktop\PokemonGo-Bot\lib\site-packages\raven\transport\http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "C:\Users\chris\Desktop\PokemonGo-Bot\lib\site-packages\raven\utils\http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\chris\Desktop\PokemonGo-Bot\lib\site-packages\future\backports\urllib\request.py", line 494, in open
    response = self._open(req, data)
  File "C:\Users\chris\Desktop\PokemonGo-Bot\lib\site-packages\future\backports\urllib\request.py", line 512, in _open
    '_open', req)
  File "C:\Users\chris\Desktop\PokemonGo-Bot\lib\site-packages\future\backports\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Users\chris\Desktop\PokemonGo-Bot\lib\site-packages\raven\utils\http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "C:\Users\chris\Desktop\PokemonGo-Bot\lib\site-packages\future\backports\urllib\request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "c:\python27\Lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "c:\python27\Lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "c:\python27\Lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "c:\python27\Lib\httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-20 12:20:31,796 [sentry.errors.uncaught] [ERROR] [u'ValueError: unconverted data remains: 1', u'  File "pokecli.py", line 570, in <module>', u'  File "pokecli.py", line 91, in main', u'  File "C:\\Users\\chris\\Desktop\\PokemonGo-Bot\\pokemongo_bot\\tree_config_builder.py", line 74, in build', u'  File "C:\\Users\\chris\\Desktop\\PokemonGo-Bot\\pokemongo_bot\\base_task.py", line 13, in __init__', u'  File "C:\\Users\\chris\\Desktop\\PokemonGo-Bot\\pokemongo_bot\\cell_workers\\sleep_schedule.py", line 37, in initialize', u'  File "C:\\Users\\chris\\Desktop\\PokemonGo-Bot\\pokemongo_bot\\cell_workers\\sleep_schedule.py", line 59, in _process_config', u'  File "c:\\python27\\Lib\\_strptime.py", line 335, in _strptime']

 Something went wrong and the bot needed to be restarted. Please investigate the cause.

**Comment by agetnc313** [comment]
i fixed it by re-downloading the bot and changing the API Key
