### ISSUE TITLE
follow_path error in dev branch

### ISSUE THREAD

**Issue by Holzberg** [PokemonGoF/PokemonGo-Bot#4427]
### Expected Behavior

Follow path should work

### Actual Behavior

Immediate error on startup.  It seems to happen when it tries to update your guy to walk to the first path.  The path was working this morning so it must have broke with a commit to dev within the last 10 hours.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

{
        "type": "FollowPath",
        "config": {
          "path_mode": "loop",
          "path_file": "/home/tony/pokemon/bot/tony/path.json"
        }
      }

### Output when issue occurred

Traceback (most recent call last):
  File "pokecli.py", line 674, in <module>
    main()
  File "pokecli.py", line 118, in main
    bot.tick()
  File "/home/tony/pokemon/bot/PokemonGo-Bot/pokemongo_bot/__init__.py", line 541, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/tony/pokemon/bot/PokemonGo-Bot/pokemongo_bot/cell_workers/follow_path.py", line 143, in work
    'current_position': (lat, lng, alt),
UnboundLocalError: local variable 'alt' referenced before assignment
2016-08-20 13:28:46,686 [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/tony/pokemon/bot/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/tony/pokemon/bot/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/tony/pokemon/bot/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/tony/pokemon/bot/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/tony/pokemon/bot/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/tony/pokemon/bot/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/tony/pokemon/bot/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/tony/pokemon/bot/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
  File "/home/tony/pokemon/bot/PokemonGo-Bot/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
2016-08-20 13:28:46,689 [sentry.errors.uncaught] [ERROR] [u"UnboundLocalError: local variable 'alt' referenced before assignment", u'  File "pokecli.py", line 674, in <module>', u'  File "pokecli.py", line 118, in main', u'  File "pokemongo_bot/__init__.py", line 541, in tick', u'  File "pokemongo_bot/cell_workers/follow_path.py", line 143, in work']

### Steps to Reproduce

Use path and start bot

### Other Information
OS: ubuntu 14 server
 
Branch:  dev
 
Git Commit: latest as of this posr
 
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by Holzberg** [comment]
In follow_path.py Line 143

Currently it is:
 `'current_position': (lat, lng, alt),`

And I think it should be: 
`'current_position': (point['lat'], point['lng'], alt),`

At least that's what it is in follow_spiral.py

**Comment by kanemasa1987** [comment]
lat and lng are fine.
place

_, _, alt = self.bot.api.get_position()

right before emit.

**Comment by kanemasa1987** [comment]
#4390

**Comment by Holzberg** [comment]
oh sorry... can close this then

**Comment by kanemasa1987** [comment]
yeah might be better close this since it's dupulicate

**Comment by Holzberg** [comment]
Closing... duplicate of #4390. 

Sorry
