### ISSUE TITLE
Bot  crashes after restart using followPath : UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte

### ISSUE THREAD

**Issue by nicobr75000** [PokemonGoF/PokemonGo-Bot#4449]
### Expected Behavior
The bot should resume were it was .

### Actual Behavior
Crashs

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastie.org/private/g9hdck1e2usx5hviyvtq

### Output when issue occurred

```
(PokemonGo-Bot) administrators-Mac-mini:PokemonGo-Bot administrator$ python pokecli.py --config ./configs/config.###.json 
2016-08-21 02:43:59,786 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-21 02:43:59,795 [       cli] [INFO] commit: 6f9ae7dc06c6518d2cc8db13ad3dc2dec167e22a
2016-08-21 02:43:59,804 [       cli] [INFO] Configuration initialized
2016-08-21 02:43:59,804 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-21 02:43:59,804 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-21 02:44:00,220 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-21 02:44:00,382 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-21 02:44:00,383 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-21 02:44:01,733 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-21 02:44:01,733 [PokemonGoBot] [INFO] Found encrypt.so! Platform: darwin encrypt.so directory: /Users/administrator/Documents/PokemonGo-Bot
2016-08-21 02:44:01,733 [PokemonGoBot] [INFO] 
2016-08-21 02:44:02,622 [PokemonGoBot] [INFO] Level: 24 (Next Level: 24255 XP) (Total: 685745 XP)
2016-08-21 02:44:02,623 [PokemonGoBot] [INFO] Pokemon Captured: 2277 | Pokestops Visited: 4573
2016-08-21 02:44:03,773 [PokemonGoBot] [INFO] 
2016-08-21 02:44:03,773 [PokemonGoBot] [INFO] --- ###### ---
2016-08-21 02:44:03,843 [PokemonGoBot] [INFO] Pokemon Bag: 185/250
2016-08-21 02:44:03,844 [PokemonGoBot] [INFO] Items: 319/350
2016-08-21 02:44:03,844 [PokemonGoBot] [INFO] Stardust: 287799 | Pokecoins: 0
2016-08-21 02:44:03,845 [PokemonGoBot] [INFO] PokeBalls: 35 | GreatBalls: 34 | UltraBalls: 74 | MasterBalls: 0
2016-08-21 02:44:03,845 [PokemonGoBot] [INFO] RazzBerries: 61 | BlukBerries: 0 | NanabBerries: 0
2016-08-21 02:44:03,845 [PokemonGoBot] [INFO] LuckyEgg: 5 | Incubator: 0 | TroyDisk: 5
2016-08-21 02:44:03,845 [PokemonGoBot] [INFO] Potion: 17 | SuperPotion: 13 | HyperPotion: 26 | MaxPotion: 0
2016-08-21 02:44:03,845 [PokemonGoBot] [INFO] Incense: 8 | IncenseSpicy: 0 | IncenseCool: 0
2016-08-21 02:44:03,845 [PokemonGoBot] [INFO] Revive: 39 | MaxRevive: 0
2016-08-21 02:44:03,846 [PokemonGoBot] [INFO] 
2016-08-21 02:44:03,849 [SleepSchedule] [INFO] [next_sleep] Next sleep at 2016-08-21 23:15:18.849715
2016-08-21 02:44:03,850 [RandomPause] [INFO] [next_random_pause] Next random pause at 03:28:32, for a duration of 0:01:23
2016-08-21 02:44:05,193 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-21 02:44:05,194 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-21 02:44:05,194 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-21 02:44:05,375 [       cli] [INFO] 
2016-08-21 02:44:05,376 [       cli] [INFO] Ran for 0:00:05
2016-08-21 02:44:05,376 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-21 02:44:05,376 [       cli] [INFO] Travelled 0.00km
2016-08-21 02:44:05,376 [       cli] [INFO] Visited 0 stops
2016-08-21 02:44:05,376 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-21 02:44:05,377 [       cli] [INFO] Threw 0 pokeballs
2016-08-21 02:44:05,377 [       cli] [INFO] Earned 0 Stardust
2016-08-21 02:44:05,377 [       cli] [INFO] Hatched eggs 0
2016-08-21 02:44:05,377 [       cli] [INFO] 
2016-08-21 02:44:05,377 [       cli] [INFO] Highest CP Pokemon: 
2016-08-21 02:44:05,377 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 677, in <module>
    main()
  File "pokecli.py", line 105, in main
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "/Users/administrator/Documents/PokemonGo-Bot/pokemongo_bot/tree_config_builder.py", line 74, in build
    instance = worker(self.bot, task_config)
  File "/Users/administrator/Documents/PokemonGo-Bot/pokemongo_bot/base_task.py", line 20, in __init__
    self.initialize()
  File "/Users/administrator/Documents/PokemonGo-Bot/pokemongo_bot/cell_workers/follow_path.py", line 22, in initialize
    self.ptr = self.find_closest_point_idx(self.points)
  File "/Users/administrator/Documents/PokemonGo-Bot/pokemongo_bot/cell_workers/follow_path.py", line 88, in find_closest_point_idx
    alt = float(point['alt'])
KeyError: 'alt'
2016-08-21 02:44:05,394 [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/administrator/Documents/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/administrator/Documents/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/administrator/Documents/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/administrator/Documents/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/administrator/Documents/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/administrator/Documents/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/administrator/Documents/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/administrator/Documents/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 891, in _send_output
    msg += message_body
  File "/Users/administrator/Documents/PokemonGo-Bot/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
2016-08-21 02:44:05,396 [sentry.errors.uncaught] [ERROR] [u"KeyError: 'alt'", u'  File "pokecli.py", line 677, in <module>', u'  File "pokecli.py", line 105, in main', u'  File "pokemongo_bot/tree_config_builder.py", line 74, in build', u'  File "pokemongo_bot/base_task.py", line 20, in __init__', u'  File "pokemongo_bot/cell_workers/follow_path.py", line 22, in initialize', u'  File "pokemongo_bot/cell_workers/follow_path.py", line 88, in find_closest_point_idx']
```
### Other Information
OS: 
 
Branch: 
dev
Git Commit: 
6f9ae7dc06c6518d2cc8db13ad3dc2dec167e22a
Python Version: 
Python 2.7.10
Any other relevant files/configs (eg: path files) 

Does not crash on cc3b4c92b94b9e6b8f23f08eae93189a82d5cfd0
Path file 
```
[
  {"location": "48.892767, 2.387508"},
  {"location": "48.892148, 2.388629"},
  {"location": "48.892607, 2.390936"}
]
```

**Comment by nicobr75000** [comment]
PS : I have 2 bots in the same folder, the other one seems to work fine. 
Maybe I missed a step to run 2 bots in parallel

**Comment by oralunal** [comment]
I think API responses have been changed and bot cannot decode it.

**Comment by kanemasa1987** [comment]
try replacing
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/cell_workers/follow_path.py#L111
with
```
if 'alt' in point:
    alt = float(point['alt'])
else:
    alt = uniform(self.bot.config.alt_min, self.bot.config.alt_max)
```

**Comment by nicobr75000** [comment]
Had to change in `find_closest_point_idx` too and it works thanks !
Should I pass the alt in the locations? Maybe the doc can but updated on that 

Thanks a lot

Nicolas
