### ISSUE TITLE
Cryptodome

### ISSUE THREAD

**Issue by AngerN** [PokemonGoF/PokemonGo-Bot#447]
C:\Python27\PokemonGo-Bot>pokecli.py - -l "53.012808, 18.597326" -lc -cp100 -m all -w 4.16 -du km -c 200
Traceback (most recent call last):
  File "C:\Python27\PokemonGo-Bot\pokecli.py", line 43, in <module>
    from pokemongo_bot import PokemonGoBot
  File "C:\Python27\PokemonGo-Bot\pokemongo_bot\__init__.py", line 10, in <module>
    from pgoapi import PGoApi
  File "c:\python27\pokemongo-bot\src\pgoapi\pgoapi\__init__.py", line 19, in <module>
    from pgoapi.pgoapi import PGoApi
  File "c:\python27\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 35, in <module>
    from pgoapi.auth_google import AuthGoogle
  File "c:\python27\pokemongo-bot\src\pgoapi\pgoapi\auth_google.py", line 31, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 4, in <module>
    from . import google
  File "C:\Python27\lib\site-packages\gpsoauth\google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
  File "C:\Python27\lib\site-packages\Cryptodome\PublicKey\RSA.py", line 79, in <module>
    from Cryptodome.IO import PKCS8, PEM
  File "C:\Python27\lib\site-packages\Cryptodome\IO\PKCS8.py", line 73, in <module>
    from Cryptodome.IO._PBES import PBES1, PBES2, PbesError
  File "C:\Python27\lib\site-packages\Cryptodome\IO\_PBES.py", line 44, in <module>
    from Cryptodome.Cipher import DES, ARC2, DES3, AES
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\__init__.py", line 78, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\_mode_ecb.py", line 46, in <module>
    """
  File "C:\Python27\lib\site-packages\Cryptodome\Util\_raw_api.py", line 168, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s'" % name)
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb'

I got this error. What should I do? BTW I installed pip install -r requirements.txt

**Comment by douglascamata** [comment]
Install Linux. lol

**Comment by AngerN** [comment]
;]

**Comment by Aiyubi** [comment]
you should use python to execute the files

**Comment by s1x** [comment]
@AngerN Check the https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/README.md Installation on Windows/Linux & Co. :-)

**Comment by s1x** [comment]
@AngerN Reopend as you wished. Help wanted.

**Comment by AngerN** [comment]
Thanks

**Comment by Tozic** [comment]
Alight oml i have been trying to fix this for hours, When i try to launch it i get the same error as the guy who made the post thing,  
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb

Please help it's been bugging me for ages, Im trying to run of Windows using python this is my start script 
python pokecli.py -a google -u email -p password -w 4.16 -m all --location "New York, Washington Square"

**Comment by kriswong** [comment]
This is because you are using 64-bit python and not 32-bit python. please uninstall 64 bit version, install 32-bit version.  

Please respond to this when you have so we can close it.

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
