### ISSUE TITLE
ERROR MESSAGE

### ISSUE THREAD

**Issue by willestx** [PokemonGoF/PokemonGo-Bot#4502]
**PLEASE help, my bot keeps showing up this message,
barely catches pokemon, and misses pokestops and doesnt show walking patterns?**

[10:36:15] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[10:42:38] (ERROR) Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 246
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchLurePokemonsTask.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchLurePokemonsTask.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 57

**Comment by josegrobles** [comment]
this is not the droid you're looking for

**Comment by BriceSD** [comment]
This isn’t our bot.
