### ISSUE TITLE
RandomPause & CompleteTutorial & UpdateLiveInventory Not Defined Error

### ISSUE THREAD

**Issue by oralunal** [PokemonGoF/PokemonGo-Bot#4514]
In config.json.example there is RandomPause task but if I add that task to my config file bot doesn't start. It throws error: "**No worker named RandomPause defined**"

My config file: http://pastebin.com/ccCGSQKz

```
Traceback (most recent call last):
  File "pokecli.py", line 570, in <module>
    main()
  File "pokecli.py", line 91, in main
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "C:\Users\oralu\Desktop\pokebot\PokemonGo-Bot\pokemongo_bot\tree_config_builder.py", line 54, in build
    worker = self._get_worker_by_name(task_type)
  File "C:\Users\oralu\Desktop\pokebot\PokemonGo-Bot\pokemongo_bot\tree_config_builder.py", line 21, in _get_worker_by_name
    raise ConfigException('No worker named {} defined'.format(name))
pokemongo_bot.tree_config_builder.ConfigException: No worker named RandomPause defined
2016-08-22 04:03:01,782 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "C:\Users\oralu\Desktop\pokebot\PokemonGo-Bot\lib\site-packages\raven\transport\threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "C:\Users\oralu\Desktop\pokebot\PokemonGo-Bot\lib\site-packages\raven\transport\http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "C:\Users\oralu\Desktop\pokebot\PokemonGo-Bot\lib\site-packages\raven\utils\http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\oralu\Desktop\pokebot\PokemonGo-Bot\lib\site-packages\future\backports\urllib\request.py", line 494, in open
    response = self._open(req, data)
  File "C:\Users\oralu\Desktop\pokebot\PokemonGo-Bot\lib\site-packages\future\backports\urllib\request.py", line 512, in _open
    '_open', req)
  File "C:\Users\oralu\Desktop\pokebot\PokemonGo-Bot\lib\site-packages\future\backports\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Users\oralu\Desktop\pokebot\PokemonGo-Bot\lib\site-packages\raven\utils\http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "C:\Users\oralu\Desktop\pokebot\PokemonGo-Bot\lib\site-packages\future\backports\urllib\request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python27\Lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\Lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "C:\Python27\Lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "C:\Python27\Lib\httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-22 04:03:01,848 [sentry.errors.uncaught] [ERROR] [u'ConfigException: No worker named RandomPause defined', u'  File "pokecli.py", line 570, in <module>', u'  File "pokecli.py", line 91, in main', u'  File "C:\\Users\\oralu\\Desktop\\pokebot\\PokemonGo-Bot\\pokemongo_bot\\tree_config_builder.py", line 54, in build', u'  File "C:\\Users\\oralu\\Desktop\\pokebot\\PokemonGo-Bot\\pokemongo_bot\\tree_config_builder.py", line 21, in _get_worker_by_name']

 Something went wrong and the bot needed to be restarted. Please investigate the cause.
```

If I delete RandomPause task from my config then Complete Tutorial throws the same error, no worker found. And UpdateLiveInventory....

**Comment by k4n30** [comment]
Please use issue template as intended so we can determine the actual cause
