### ISSUE TITLE
No module named RecycleInventoryItemMessage_pb2

### ISSUE THREAD

**Issue by OVO647** [PokemonGoF/PokemonGo-Bot#4516]
===============ISSUE SECTION===============

Before you create an Issue, please check the following:

1. Have you validated that your config.json is valid JSON? Yes
2. Have you [searched our issue tracker](https://github.com/PokemonGoF/PokemonGo-Bot/issues? Yes
3. Are you running on the `master` branch? No I'm on Dev.

### Expected Behavior

Bot to work fine

### Actual Behavior

Bot stops running.

### Output when issue occurred
Traceback (most recent call last):
  File "pokecli.py", line 685, in <module>
    main()
  File "pokecli.py", line 118, in main
    bot.tick()
  File "/Users/User/Desktop/POGO/pokemongo_bot/__init__.py", line 565, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/Users/User/Desktop/POGO/pokemongo_bot/cell_workers/recycle_items.py", line 95, in work
    worker_result = self.recycle_excess_category_max(self.max_balls_keep, [1,2,3,4])
  File "/Users/User/Desktop/POGO/pokemongo_bot/cell_workers/recycle_items.py", line 131, in recycle_excess_category_max
    if ItemRecycler(self.bot, inventory.items().get(item[0]), item[1]).work() == WorkerResult.ERROR:
  File "/Users/User/Desktop/POGO/pokemongo_bot/services/item_recycle_worker.py", line 36, in work
    self.request_recycle()
  File "/Users/User/Desktop/POGO/pokemongo_bot/services/item_recycle_worker.py", line 62, in request_recycle
    count=self.amount_to_recycle)
  File "/Users/User/Desktop/POGO/src/pgoapi/pgoapi/pgoapi.py", line 137, in function
  File "/Users/User/Desktop/POGO/pokemongo_bot/api_wrapper.py", line 237, in call
    result = self._call()
  File "/Users/User/Desktop/POGO/pokemongo_bot/api_wrapper.py", line 186, in _call
    return PGoApiRequest.call(self, signature)
  File "/Users/User/Desktop/POGO/src/pgoapi/pgoapi/pgoapi.py", line 236, in call
  File "/Users/User/Desktop/POGO/src/pgoapi/pgoapi/rpc_api.py", line 124, in request
  File "/Users/User/Desktop/POGO/src/pgoapi/pgoapi/rpc_api.py", line 183, in _build_main_request
  File "/Users/User/Desktop/POGO/src/pgoapi/pgoapi/rpc_api.py", line 288, in _build_sub_requests
  File "/Users/User/Desktop/POGO/src/pgoapi/pgoapi/rpc_api.py", line 105, in get_class
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named RecycleInventoryItemMessage_pb2

**Comment by ganagus** [comment]
In my case I resolved similar error by running the following command: pip install upgrade -r requirements.txt.
