### ISSUE TITLE
keep getting this Traceback after about 3 mins.

### ISSUE THREAD

**Issue by LoadCroc** [PokemonGoF/PokemonGo-Bot#4555]
keep getting this call back after about 3 mins, 
"health_record": false.

Traceback (most recent call last):
  File "C:\Program Files (x86)\pokemon\FileChecker\pokecli.py", line 674, in <module>
    main()
  File "C:\Program Files (x86)\pokemon\FileChecker\pokecli.py", line 118, in main
    bot.tick()
  File "C:\Program Files (x86)\pokemon\FileChecker\pokemongo_bot\__init__.py", line 541, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "C:\Program Files (x86)\pokemon\FileChecker\pokemongo_bot\cell_workers\follow_path.py", line 143, in work
    'current_position': (lat, lng, alt),
UnboundLocalError: local variable 'alt' referenced before assignment

**Comment by LoadCroc** [comment]
I don't think its walking

**Comment by mjmadsen** [comment]
What commit are you using?

**Comment by LoadCroc** [comment]
this #4493 didn't work

Traceback (most recent call last):
  File "C:\Program Files (x86)\pokemon\FileChecker\pokecli.py", line 46, in <module>
    from pokemongo_bot import inventory
  File "C:\Program Files (x86)\pokemon\FileChecker\pokemongo_bot\__init__.py", line 19, in <module>
    import cell_workers
  File "C:\Program Files (x86)\pokemon\FileChecker\pokemongo_bot\cell_workers\__init__.py", line 16, in <module>
    from follow_path import FollowPath
  File "C:\Program Files (x86)\pokemon\FileChecker\pokemongo_bot\cell_workers\follow_path.py", line 115
    alt = 0
    ^
IndentationError: unexpected indent

**Comment by LoadCroc** [comment]
@mjmadsen didn't work #4493

**Comment by mjmadsen** [comment]
Are you in the dev branch? If so, git pull as your follow_path looks outdated.

**Comment by LoadCroc** [comment]
@mjmadsen just pulled dev then was in the main b4.

**Comment by mjmadsen** [comment]
@LoadCroc Ah, we're pushing from dev to main about every 12-24 hours now. Quite often we'll have a bugs like this slip into main, which is why we always ask for commit (most true bugs are solved pretty quickly in dev). We just pushed dev to main, so either is fine for you at the moment. Let me know how it goes.

**Comment by LoadCroc** [comment]
ok running the dev now no fail atm, it was just the main pull of git.

**Comment by LoadCroc** [comment]
cant see it walking but just luring pokemon from the 3 stops its at

**Comment by mjmadsen** [comment]
No problem. A few tips for future issue posts:
List your commit (the bot changes rapidly and has many contributors).
Post your config (just so we don't default it to human error)
Post the log from the bot (we can usually find where the issue is pretty quick)

Anyway, thanks for using the bot!
