### ISSUE TITLE
BOT can't start

### ISSUE THREAD

**Issue by Amzix** [PokemonGoF/PokemonGo-Bot#4557]
I use Master branch, when i start the bot i have this : 
Traceback (most recent call last):
  File "pokecli.py", line 43, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions
lundi 22 août 2016, 15:49:02 (UTC+0200) Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

My config.json : 
{
    "auth_service": "ptc",
    "username": "xx,
    "password": "xxx",
    "location": "xxx",
    "gmapkey": "xxx",
    "libencrypt_location": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "SleepSchedule",
        "config": {
          "time": "21:00",
          "duration":"8:00",
          "time_random_offset": "00:30",
          "duration_random_offset": "00:30"
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all" : "Pidgey,Weedle,Rattata,Zubat,Pidgey,Caterpie,Spearow",
            "//evolve_all": "all",
            "//first_evolve_by": "cp",
            "//evolve_above_cp": 200,
            "evolve_cp_min": 10,
            "evolve_above_iv": 0,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 30 },
            "Greatball":       { "keep" : 70 },
            "Ultraball": { "keep" : 50 },
            "Potion":         { "keep" : 0 },
            "Super Potion":   { "keep" : 0 },
            "Hyper Potion":   { "keep" : 30 },
            "Max Potion":   { "keep" : 50 },
            "Revive":         { "keep" : 0 },
            "Razz Berry":     { "keep" : 50 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToMapPokemon",
        "config": {
          "address": "xxxxxxxxxxx",
          "max_distance": 500,
          "min_ball": 50,
          "prioritize_vips": true,
          "snipe": false,
          "snipe_high_prio_only": true,
          "snipe_high_prio_threshold": 400,
          "update_map": true,
          "mode": "priority",
          "map_path": "raw_data",
          "catch": {
            "==========Legendaries==========": 0,
            "Aerodactyl": 1000,
            "Snorlax": 1000,
            "Articuno": 1000,
            "Zapdos": 1000,
            "Moltres": 1000,
            "Dratini": 1000,
            "Dragonair": 1000,
            "Dragonite": 1000,
            "Mewtwo": 1000,
            "Mew": 1000,

            "==========Region Locked==========": 0,
            "Farfetch'd": 1000,
            "Kangaskhan": 1000,
            "Mr. Mime": 1000,
            "Tauros": 1000,

            "==========Very Rare==========": 0,
            "Lapras": 900,
            "Electabuzz": 900,
            "Magmar": 900,
            "Ditto": 900,

            "==========Starters==========": 0,
            "Bulbasaur": 400,
            "Ivysaur": 600,
            "Venusaur": 1000,

            "Charmander": 400,
            "Charmeleon": 600,
            "Charizard": 1000,

            "Squirtle": 400,
            "Wartortle": 600,
            "Blastoise": 1000,

            "Pikachu": 600,
            "Raichu": 1000,

            "==========Semi Rare==========": 0,
            "Porygon": 200,
            "Scyther": 200,
            "Jynx": 200,

            "==========Uncommon==========": 0,

            "Omanyte": 150,
            "Omastar": 500,

            "Seel": 300,
            "Dewgong": 500,

            "Grimer": 200,
            "Muk": 500,

            "Shellder": 200,
            "Cloyster": 500,

            "Gastly": 200,
            "Haunter": 500,
            "Gengar": 1000,

            "Onix": 600,

            "Drowzee": 600,

            "Hypno": 600,

            "Vulpix": 200,
            "Ninetales": 600,

            "Paras": 100,
            "Parasect": 500,

            "Growlithe": 200,
            "Arcanine": 700,

            "Tentacool": 200,
            "Tentacruel": 500,

            "Mankey": 150,
            "Primeape": 500,

            "Clefairy": 150,
            "Clefable": 500,

            "Jigglypuff": 150,
            "Wigglytuff": 500,

            "Venonat": 100,
            "Venomoth": 500,

            "Diglett": 200,
            "Dugtrio": 500,

            "Meowth": 250,
            "Persian": 500,

            "Psyduck": 150,
            "Golduck": 500,

            "Geodude": 100,
            "Graveler": 500,
            "Golem": 800,

            "Eevee": 200,
            "Vaporeon": 800,
            "Jolteon": 800,
            "Flareon": 800,

            "Kabuto": 150,
            "Kabutops": 500,

            "Magikarp": 150,
            "Gyarados": 800,

            "Pinsir": 150,

            "Ponyta": 200,
            "Rapidash": 500,

            "Slowpoke": 200,
            "Slowbro": 500,

            "Magnemite": 250,
            "Magneton": 500,

            "Krabby": 100,
            "Kingler": 500,

            "Voltorb": 200,
            "Electrode": 500,

            "Exeggcute": 250,
            "Exeggcutor": 500,

            "Cubone": 300,
            "Marowak": 800,

            "Hitmonlee": 400,

            "Hitmonchan": 400,

            "Lickitung": 500,

            "Koffing": 200,
            "Weezing": 500,

            "Rhyhorn": 200,
            "Rhydon": 500,

            "Chansey": 800,

            "Tangela": 300,

            "Horsea": 200,
            "Seadra": 600,

            "Goldeen": 150,
            "Seaking": 500,

            "Staryu": 200,
            "Starmie": 800,

            "==========T1 Evolvers==========": 0,
            "Caterpie": 10,
            "Metapod": 10,
            "Butterfree": 500,

            "Weedle": 10,
            "Kakuna": 10,
            "Beedrill": 500,

            "Pidgey": 10,
            "Pidgeotto": 10,
            "Pidgeot": 300,

            "==========T2 Evolvers==========": 0,
            "Nidoran F": 10,
            "Nidorina": 10,
            "Nidoqueen": 10,

            "Nidoran M": 10,
            "Nidorino": 10,
            "Nidoking": 10,

            "Oddish": 100,
            "Gloom": 200,
            "Vileplume": 600,

            "Poliwag": 200,
            "Poliwhirl": 400,
            "Poliwrath": 800,

            "Abra": 300,
            "Kadabra": 600,
            "Alakazam": 800,

            "Machop": 150,
            "Machoke": 400,
            "Machamp": 800,

            "Bellsprout": 100,
            "Weepinbell": 400,
            "Victreebel": 800,

            "==========Trash==========": 0,

            "Rattata": 10,
            "Raticate": 10,

            "Spearow": 10,
            "Fearow": 10,

            "Ekans": 10,
            "Arbok": 10,

            "Sandshrew": 10,
            "Sandslash": 10,

            "Zubat": 10,
            "Golbat": 10,

            "Doduo": 10,
            "Dodrio": 10
          }
        }
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
	"type": "FollowSpiral",
	"config": {
	    "diameter": 4,
	    "step_size": 70
	}
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk_max": 6.16,
    "walk_min": 5.16,
    "//walk": 8.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "//evolve_captured" : "Pidgey,Weedle,Rattata,Zubat,Pidgey,Caterpie,Spearow",
    "//catch_randomize_reticle_factor": 1.0,
    "//catch_randomize_spin_factor": 1.0,
    "catch_throw_parameters": {
       "excellent_rate": 0.4,
       "great_rate": 0.2,
       "nice_rate": 0.1,
       "normal_rate": 0.3,
       "spin_success_rate" : 0.5
     },
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "//Rattata": { "always_catch" : true },
      "//Zubat": {"always_catch": true},
      "//Pidgey": {"always_catch": true},
      "//Weedle": { "always_catch": true }
    },
    "release": {
      "any": {"release_below_cp": 120, "release_below_iv": 0.85, "keep_best_cp": 3, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "Rattata": {"always_release": true},
      "Raticate": { "always_release": true },
      "Zubat": {"always_release": true},
      "Golbat": { "always_release": true },
      "Pidgey": {"always_release": true},
      "Pidgeot": { "always_release": true },
      "Pidgeotto": { "always_release": true },
      "Caterpie": {"always_release": true},
      "Spearow": {"always_release": true},
      "Nidoran F": { "always_release": true },
      "Nidoran M": { "always_release": true },
      "Fearow": { "always_release": true },
      "Weedle": { "always_release": true },
      "Kakuna": { "always_release": true },
      "Beedrill": { "always_release": true },
      "//Example of keeping 3 stronger (based on CP) Pidgey:": {},
      " Pidgey": {"keep_best_cp": 3},
      "//Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 2},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "//any": {"keep_best_cp": 1, "keep_best_iv": 2}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "//any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
	"Lapras": {},
        "//any": {},
        "Moltres": {},
        "Zapdos": {},
        "Snorlax": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}

Thanks for ur help

**Comment by Amzix** [comment]
After doing this : 
pip install -r requirements

I have a new error : 

Traceback (most recent call last):
  File "pokecli.py", line 674, in <module>
    main()
  File "pokecli.py", line 176, in main
    report_summary(bot)
  File "pokecli.py", line 211, in report_summary
    metrics.capture_stats()
  File "/home/pokebot/PokemonGo-Bot/pokemongo_bot/metrics.py", line 84, in capture_stats
    response_dict = request.call()
  File "/home/pokebot/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 233, in call
    result = self._call()
  File "/home/pokebot/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 157, in _call
    accelerometer_axes=3
  File "/home/pokebot/PokemonGo-Bot/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 533, in init
    setattr(self, field_name, field_value)
  File "/home/pokebot/PokemonGo-Bot/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 669, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "/home/pokebot/PokemonGo-Bot/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 134, in CheckValue
    raise ValueError('Value out of range: %d' % proposed_value)
ValueError: Value out of range: -54
2016-08-22 16:04:56,052 [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/pokebot/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/pokebot/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/pokebot/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/pokebot/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/pokebot/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/pokebot/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/pokebot/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/pokebot/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 848, in _send_output
    msg += message_body
  File "/home/pokebot/PokemonGo-Bot/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
2016-08-22 16:04:56,055 [sentry.errors.uncaught] [ERROR] [u'ValueError: Value out of range: -54', u'  File "pokecli.py", line 674, in <module>', u'  File "pokecli.py", line 176, in main', u'  File "pokecli.py", line 211, in report_summary', u'  File "pokemongo_bot/metrics.py", line 84, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 233, in call', u'  File "pokemongo_bot/api_wrapper.py", line 157, in _call', u'  File "/home/pokebot/PokemonGo-Bot/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 533, in init', u'  File "/home/pokebot/PokemonGo-Bot/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 669, in field_setter', u'  File "/home/pokebot/PokemonGo-Bot/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 134, in CheckValue']
lundi 22 août 2016, 16:04:56 (UTC+0200) Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

**Comment by Amzix** [comment]
any help ?

**Comment by iidanielmontes** [comment]
when I start the bot I get this output:

--------------------Starting bot--------------------


Traceback (most recent call last):
  File "pokecli.py", line 43, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
  File "C:\Python27\lib\site-packages\pgoapi\__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "C:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 36, in <module>
    from pgoapi.auth_google import AuthGoogle
  File "C:\Python27\lib\site-packages\pgoapi\auth_google.py", line 31, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 4, in <module>
    from . import google
  File "C:\Python27\lib\site-packages\gpsoauth\google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
  File "C:\Python27\lib\site-packages\Cryptodome\PublicKey\RSA.py", line 79, in <module>
    from Cryptodome.IO import PKCS8, PEM
  File "C:\Python27\lib\site-packages\Cryptodome\IO\PKCS8.py", line 73, in <module>
    from Cryptodome.IO._PBES import PBES1, PBES2, PbesError
  File "C:\Python27\lib\site-packages\Cryptodome\IO\_PBES.py", line 44, in <module>
    from Cryptodome.Cipher import DES, ARC2, DES3, AES
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\__init__.py", line 78, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\_mode_ecb.py", line 46, in <module>
    """
  File "C:\Python27\lib\site-packages\Cryptodome\Util\_raw_api.py", line 168, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s'" % name)
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb'

 Something went wrong and the bot needed to be restarted. Please investigate the cause.

**Comment by andirapandi** [comment]
Installation instructions are not perfect. Some packages need to be installed manually. See

https://github.com/PokemonGoF/PokemonGo-Bot/issues/3846#issuecomment-239631665

**Comment by Amzix** [comment]
I reinstall the game many time, but still have the same problem

**Comment by andirapandi** [comment]
Installed what game? The bot is not dependent on a game installation.

Additionally to installing the requirements via requirements.txt, you also need to install protobuf and encrypt.so manually, like in the post I have linked to. It is the last answer on a ticket with the same problem I had.

**Comment by iidanielmontes** [comment]
I have protobuf and everything up to date, I've followed the instructions in manual installation, I have the correct encrypt dll on the bot folder and still not working

**Comment by Amzix** [comment]
same for me, still not working

**Comment by Amzix** [comment]
still not workinf, any idea ?

**Comment by Amzix** [comment]
2016-08-24 10:00:35,595 [PokemonGoBot] [INFO] [position_update] Now at (48.892128, 2.3874703, 8.0)
2016-08-24 10:00:35,596 [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "pokecli.py", line 703, in <module>
    main()
  File "pokecli.py", line 186, in main
    report_summary(bot)
  File "pokecli.py", line 221, in report_summary
    metrics.capture_stats()
  File "/home/hhmama/PokemonGo-Bot/pokemongo_bot/metrics.py", line 96, in capture_stats
    response_dict = request.call()
  File "/home/hhmama/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 239, in call
    result = self._call()
  File "/home/hhmama/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 163, in _call
    accelerometer_axes=3
  File "/home/hhmama/PokemonGo-Bot/local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 533, in init
    setattr(self, field_name, field_value)
  File "/home/hhmama/PokemonGo-Bot/local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 669, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "/home/hhmama/PokemonGo-Bot/local/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 134, in CheckValue
    raise ValueError('Value out of range: %d' % proposed_value)
ValueError: Value out of range: -5
2016-08-24 10:00:36,849 [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/hhmama/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/hhmama/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/hhmama/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/hhmama/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/hhmama/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/hhmama/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/hhmama/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/hhmama/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 848, in _send_output
    msg += message_body
  File "/home/hhmama/PokemonGo-Bot/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
2016-08-24 10:00:36,854 [sentry.errors.uncaught] [ERROR] [u'ValueError: Value out of range: -5', u'  File "pokecli.py", line 703, in <module>', u'  File "pokecli.py", line 186, in main', u'  File "pokecli.py", line 221, in report_summary', u'  File "pokemongo_bot/metrics.py", line 96, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 239, in call', u'  File "pokemongo_bot/api_wrapper.py", line 163, in _call', u'  File "/home/hhmama/PokemonGo-Bot/local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 533, in init', u'  File "/home/hhmama/PokemonGo-Bot/local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 669, in field_setter', u'  File "/home/hhmama/PokemonGo-Bot/local/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 134, in CheckValue']

**Comment by kevinsmendes** [comment]
Be sure to run `pip install -r requirements.txt`. That usually fix most of the problems.

**Comment by iidanielmontes** [comment]
if you are in windows uninstall python and install the 86x one (even if your system is 64x) then reinstall the bot following the manual instructions, that works to me.

-you need to download the PyYAML-3.11-cp27-cp27m-win32.whl searching it on google
-if still dosent  work then run the setup.sh on the root folder using C:\Python27\PokemonGo-Bot\setup.sh -i on the console

**Comment by Amzix** [comment]
Hello @kevinsmendes already done it, still have the problem

**Comment by Amzix** [comment]
@iidanielmontes  I use  debian

**Comment by mjmadsen** [comment]
pip install -r requirements.txt --upgrade

**Comment by Jcolomar** [comment]
2016-08-24 21:42:18,102 [SleepSchedule] [INFO] [next_sleep] Next sleep at 2016-08-24 22:36:12.103000
2016-08-24 21:42:18,105 [RandomPause] [INFO] [next_random_pause] Next random pause at 21:50:53, for a duration of 0:00:57
....
2016-08-24 21:42:19,369 [       cli] [INFO]
2016-08-24 21:42:19,371 [       cli] [INFO] Ran for 0:00:06
2016-08-24 21:42:19,372 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-24 21:42:19,375 [       cli] [INFO] Travelled 0.00km
2016-08-24 21:42:19,375 [       cli] [INFO] Visited 0 stops
2016-08-24 21:42:19,377 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-24 21:42:19,380 [       cli] [INFO] Threw 0 pokeballs
2016-08-24 21:42:19,381 [       cli] [INFO] Earned 0 Stardust
2016-08-24 21:42:19,381 [       cli] [INFO] Hatched eggs 0
2016-08-24 21:42:19,384 [       cli] [INFO]
2016-08-24 21:42:19,384 [       cli] [INFO] Highest CP Pokemon:
2016-08-24 21:42:19,385 [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "C:\Juegos\PokemonGO\PokemonGo-Bot\pokecli.py", line 703, in <module>
    main()
  File "C:\Juegos\PokemonGO\PokemonGo-Bot\pokecli.py", line 105, in main
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "C:\Juegos\PokemonGO\PokemonGo-Bot\pokemongo_bot\tree_config_builder.py", line 74, in build
    instance = worker(self.bot, task_config)
  File "C:\Juegos\PokemonGO\PokemonGo-Bot\pokemongo_bot\base_task.py", line 20, in __init__
    self.initialize()
  File "C:\Juegos\PokemonGO\PokemonGo-Bot\pokemongo_bot\cell_workers\follow_path.py", line 20, in initialize
    self.points = self.load_path()
  File "C:\Juegos\PokemonGO\PokemonGo-Bot\pokemongo_bot\cell_workers\follow_path.py", line 48, in load_path
    return self.load_json()
  File "C:\Juegos\PokemonGO\PokemonGo-Bot\pokemongo_bot\cell_workers\follow_path.py", line 54, in load_json
    points=json.load(data_file)
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 38 - line 84 column 45 (char 37 - 3236)
2016-08-24 21:42:19,476 [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\raven\transport\threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "C:\Python27\lib\site-packages\raven\transport\http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 494, in open
    response = self._open(req, data)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 512, in _open
    '_open', req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python27\lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 895, in _send_output
    msg += message_body
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
2016-08-24 21:42:19,510 [sentry.errors.uncaught] [ERROR] [u'ValueError: Extra data: line 1 column 38 - line 84 column 45 (char 37 - 3236)', u'  File "C:\\Juegos\\PokemonGO\\PokemonGo-Bot\\pokecli.py", line 703, in <module>', u'  File "C:\\Juegos\\PokemonGO\\PokemonGo-Bot\\pokecli.py", line 105, in main', u'  File "C:\\Juegos\\PokemonGO\\PokemonGo-Bot\\pokemongo_bot\\tree_config_builder.py", line 74, in build', u'  File "C:\\Juegos\\PokemonGO\\PokemonGo-Bot\\pokemongo_bot\\base_task.py", line 20, in __init__', u'  File "C:\\Juegos\\PokemonGO\\PokemonGo-Bot\\pokemongo_bot\\cell_workers\\follow_path.py", line 20, in initialize', u'  File "C:\\Juegos\\PokemonGO\\PokemonGo-Bot\\pokemongo_bot\\cell_workers\\follow_path.py", line 48, in load_path', u'  File "C:\\Juegos\\PokemonGO\\PokemonGo-Bot\\pokemongo_bot\\cell_workers\\follow_path.py", line 54, in load_json', u'  File "C:\\Python27\\lib\\json\\__init__.py", line 291, in load', u'  File "C:\\Python27\\lib\\json\\__init__.py", line 339, in loads', u'  File "C:\\Python27\\lib\\json\\decoder.py", line 367, in decode']


i tryed with 32 and 64 pyton and same error

pip install -r requirements.txt --upgrade ----> all ok

pokecly.py -cf /configs/config.json

**Comment by kevinsmendes** [comment]
Can you try to do a clean install of the bot? Just delete everything and
start from zero. See if it works.



2016-08-24 16:59 GMT-03:00 Jcolomar <notifications@github.com>:

**Comment by Jcolomar** [comment]
1 git clone https://github.com/PokemonGoF/PokemonGo-Bot.git
2 cd pokemongo-bot
3 pip install -r requirements.txt
4 put encryt libraries on pokemongo-bot directory
5 pokecly.py  -cf /configs/basiconfig.json (very basic one seems go good)
6 pokecly.py  -cf /configs/goodconfig.json (personal one with no warnings)  ---> same error

**Comment by kevinsmendes** [comment]
Try:


   - git clone https://github.com/PokemonGoF/PokemonGo-Bot.git
   - cd PokemonGo-Bot
   - pip install --upgrade pip
   - pip install -r requirements.txt
   - ./setup.sh -i
   - ./run.sh


All I do is that, and it works flawlessly.



2016-08-24 17:42 GMT-03:00 Jcolomar <notifications@github.com>:

**Comment by Jcolomar** [comment]
im on windows :)

**Comment by Jcolomar** [comment]
i discover the section gives me error. When i insert this part:

{
        "type": "FollowPath",
        "config": {
          "enabled": true,
          "walker": "StepWalker",
          "path_mode": "loot",
          "path_start_mode": "first",
          "path_file": "configs/espigon.json",
          "number_lap": 1,
          "timer_restart_min": "00:10:00",
          "timer_restart_max": "00:20:00"
        }

i tryed to put "single" but no works

config/espigon.json in /config/folder

**Comment by mjmadsen** [comment]
@Jcolomar Did you get it working?

**Comment by Jcolomar** [comment]
mjmadsen YES! i was testing and testing and the problem was in how to type the route to the config file to path file. If u type "path_file": "/configs/espigon.json" gives error, but if u type the complete path like "path_file": "C:/Juegos/PokemonGO/PokemonGo-Bot/configs/espigon.json" works.

**Comment by mjmadsen** [comment]
Ah yes, pathing on a cross platform application can be tricky. :+1:

**Comment by Amzix** [comment]
Why you closed the issue, i'm the one who created it , and i still have the problem ???

**Comment by mjmadsen** [comment]
My bad, I was looking at the wrong username.

**Comment by Amzix** [comment]
thank you :)

**Comment by mjmadsen** [comment]
Sorry you're still having troubles. Have you tried the following (I'm sure you're tired of hearing that):
git reset --hard
git checkout dev
git pull
pip install -r requirements.txt --upgrade

**Comment by Amzix** [comment]
already tried it, can you tell me when Niantic ban an IP adress  of a server, what answer/message we have when we start the bot ?

**Comment by mjmadsen** [comment]
I think that just send us garbage or info we don't break down well / respond well to (pgo not us). Or they only send some info (maybe no stops, pokemon, etc). 

As far as the API and the network traffic, I'm well out of my realm of knowledge. Hopefully I can learn from the fine folks working on that end (at some point in time). 

Since none of the solutions have worked for you, I would lean to say IP ban. Have you tried running the bot through TOR?

**Comment by Amzix** [comment]
Thanks for the reply, i tested the bot in 4 servers, the same bot works fine in two of them but not in the others.

N.B : the two servers where the bot can't start are in the same subnet of public adress, i think that Niantic ban all the subnet of  these VPS.

**Comment by mjmadsen** [comment]
Ah, there we go.

**Comment by Amzix** [comment]
:D we can close this issue and thanks for your help

**Comment by mjmadsen** [comment]
Glad to help (and sorry about the bans)
