### ISSUE TITLE
bot don't startup

### ISSUE THREAD

**Issue by MeGaPk** [PokemonGoF/PokemonGo-Bot#457]
I try start bot with my login & password and get this error:
```
[x] Address found: Punane 35
[x] Position in-game set as: (59.43365029999999, 24.8267388, 0.0)
Traceback (most recent call last):
  File "C:/Users/Ivan/Documents/Projects/PokemonGo-Bot/pokecli.py", line 138, in <module>
    main()
  File "C:/Users/Ivan/Documents/Projects/PokemonGo-Bot/pokecli.py", line 125, in main
    bot.start()
  File "C:\Users\Ivan\Documents\Projects\PokemonGo-Bot\pokemongo_bot\__init__.py", line 31, in start
    self._setup_api()
  File "C:\Users\Ivan\Documents\Projects\PokemonGo-Bot\pokemongo_bot\__init__.py", line 154, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'player_data'
```

In response_dict['responses']['GET_PLAYER'] i have:
```
{'profile': {'avatar': {'unknown10': 1, 'unknown3': 4, 'unknown9': 4},
             'creation_time': 1468897660664L,
             'currency': [{'type': u'POKECOIN'},
                          {'amount': 500, 'type': u'STARDUST'}],
             'daily_bonus': {},
             'item_storage': 350,
             'poke_storage': 250,
             'tutorial': 'AAEDBAc=\n',
             'unknown12': '',
             'unknown13': 'CAE=\n',
             'username': u'lMeGaPkl'},
 'unknown1': 1}
```

What problem? 
Thanks for answer!

**Comment by gsarrica** [comment]
I get the same issue on dev branch. Master branch is fine.

**Comment by s1x** [comment]
Should be fixed with the reclone mentioned by @gsarrica
