### ISSUE TITLE
[Docker] bot startup issue utf-8 decoding

### ISSUE THREAD

**Issue by farahfa** [PokemonGoF/PokemonGo-Bot#4571]
```
2016-08-22 10:47:45,935 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-22 10:47:45,954 [       cli] [INFO] commit: not found
2016-08-22 10:47:45,956 [       cli] [INFO] No config argument specified, checking for /configs/config.json
2016-08-22 10:47:45,959 [       cli] [INFO] Configuration initialized
2016-08-22 10:47:45,959 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-22 10:47:45,959 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-22 10:47:45,968 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-22 10:47:46,121 [yoyo.migrations] [INFO] Applying pokemongobot
2016-08-22 10:47:46,122 [yoyo.migrations] [INFO]  - applying step 0
2016-08-22 10:47:46,123 [yoyo.migrations] [INFO] Marking pokemongobot applied
2016-08-22 10:47:46,138 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-22 10:47:46,139 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-22 10:47:46,139 [PokemonGoBot] [INFO] [location_found] Location found: 34.009129, -118.497000 (34.009129, -118.497, 8.0)
2016-08-22 10:47:46,140 [PokemonGoBot] [INFO] [position_update] Now at (34.009129, -118.497, 8.0)
2016-08-22 10:47:46,140 [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "pokecli.py", line 685, in <module>
    main()
  File "pokecli.py", line 176, in main
    report_summary(bot)
  File "pokecli.py", line 211, in report_summary
    metrics.capture_stats()
  File "/usr/src/app/pokemongo_bot/metrics.py", line 96, in capture_stats
    response_dict = request.call()
  File "/usr/src/app/pokemongo_bot/api_wrapper.py", line 237, in call
    result = self._call()
  File "/usr/src/app/pokemongo_bot/api_wrapper.py", line 141, in _call
    location_type=1
  File "/usr/local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 533, in init
    setattr(self, field_name, field_value)
  File "/usr/local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 669, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "/usr/local/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 134, in CheckValue
    raise ValueError('Value out of range: %d' % proposed_value)
ValueError: Value out of range: -107
2016-08-22 10:47:46,698 [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
  File "/usr/local/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
2016-08-22 10:47:46,704 [sentry.errors.uncaught] [ERROR] [u'ValueError: Value out of range: -107', u'  File "pokecli.py", line 685, in <module>', u'  File "pokecli.py", line 176, in main', u'  File "pokecli.py", line 211, in report_summary', u'  File "pokemongo_bot/metrics.py", line 96, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 237, in call', u'  File "pokemongo_bot/api_wrapper.py", line 141, in _call', u'  File "/usr/local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 533, in init', u'  File "/usr/local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 669, in field_setter', u'  File "/usr/local/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 134, in CheckValue']
```

Followed the installation instructions to the teeth!

**Comment by krummrey** [comment]
Got the same with a fresh install. Not even using Docker.

**Comment by noqcks** [comment]
Same

**Comment by mjmadsen** [comment]
Follow the steps listed in #4477

**Comment by noqcks** [comment]
Thanks. It was an issue of my IP being banned as well. This issue comment fixed it https://github.com/PokemonGoF/PokemonGo-Bot/issues/4477#issuecomment-241269808

**Comment by MartinTerp** [comment]
For me this error occurs when this happends:
`2016-08-23 08:54:02,812 [pgoapi.pgoapi] [ERROR] Request for new Access Token failed! Logged out...
2016-08-23 08:54:02,813 [PokemonGoBot] [INFO] [api_error] Log logged in, reconnecting in 900
`

also with this error:
`Traceback (most recent call last):
  File "pokecli.py", line 695, in <module>
    main()
  File "pokecli.py", line 118, in main
    bot.tick()
  File "/usr/src/app/pokemongo_bot/__init__.py", line 566, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/usr/src/app/pokemongo_bot/cell_workers/update_live_stats.py", line 101, in work
    self._update_title(line, _platform)
  File "/usr/src/app/pokemongo_bot/cell_workers/update_live_stats.py", line 170, in _update_title
    formatted="Unable to write window title"
  File "/usr/src/app/pokemongo_bot/base_task.py", line 35, in emit_event
    data=data
  File "/usr/src/app/pokemongo_bot/event_manager.py", line 59, in emit
    raise EventMalformedException("Event %s does not require parameter %s" % (event, k))
pokemongo_bot.event_manager.EventMalformedException: Event log_stats does not require parameter msg
`

**Comment by MartinTerp** [comment]
disabling the livestats plugin, kept it alive
