### ISSUE TITLE
Help Error

### ISSUE THREAD

**Issue by xGine** [PokemonGoF/PokemonGo-Bot#4614]
$ python pokecli.py -cf ./configs/config.json_tut.example
Traceback (most recent call last):
  File "pokecli.py", line 46, in <module>
    from pokemongo_bot import inventory
  File "C:\Users\troy112233l\Desktop\Pokemon Botters\PokemonGo-Bot\pokemongo_bot\__init__.py", line 22, in <module>
    from api_wrapper import ApiWrapper
  File "C:\Users\troy112233l\Desktop\Pokemon Botters\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 12, in <module>
    from pgoapi.protos.POGOProtos.Networking.Requests.RequestType_pb2 import RequestType
ImportError: No module named RequestType_pb2

**Comment by k4n30** [comment]
Please use issue template
