### ISSUE TITLE
Bot Crashing (using social feature)

### ISSUE THREAD

**Issue by rafzx2** [PokemonGoF/PokemonGo-Bot#4647]
when the robot finds a Ratata it stops working , follows the application debug.

 stop Graffiti Box 716 - 0.04km
2016-08-23 23:31:50,052 [  SpinFort] [INFO] [spun_pokestop] Spun pokestop Graffi                                                                                ti Box 716. Experience awarded: 50. Items awarded: {u'Pokeball': 3}
2016-08-23 23:31:54,564 [MoveToFort] [INFO] [moving_to_fort] Moving towards poke                                                                                stop Golfinho Dourado - 0.49km
2016-08-23 23:31:56,738 [IncubateEggs] [INFO] [next_egg_incubates] Eggs incubati                                                                                ng: [-8998.85/-8996.0 km, 0.91/10.0 km] (Eggs left: 7, Incubating: 2)
2016-08-23 23:31:57,046 [       cli] [INFO]
2016-08-23 23:31:57,047 [       cli] [INFO] Ran for 0:04:12
2016-08-23 23:31:57,047 [       cli] [INFO] Total XP Earned: 200  Average: 2860.                                                                                78/h
2016-08-23 23:31:57,048 [       cli] [INFO] Travelled 0.08km
2016-08-23 23:31:57,048 [       cli] [INFO] Visited 4 stops
2016-08-23 23:31:57,048 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 r                                                                                eleased, 0 evolved, 0 never seen before
2016-08-23 23:31:57,048 [       cli] [INFO] Threw 0 pokeballs
2016-08-23 23:31:57,048 [       cli] [INFO] Earned 0 Stardust
2016-08-23 23:31:57,048 [       cli] [INFO] Hatched eggs 0
2016-08-23 23:31:57,048 [       cli] [INFO] Next egg hatches in 2.85 km
2016-08-23 23:31:57,048 [       cli] [INFO]
2016-08-23 23:31:57,048 [       cli] [INFO] Highest CP Pokemon:
2016-08-23 23:31:57,048 [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 703, in <module>
    main()
  File "pokecli.py", line 118, in main
    bot.tick()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 568, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_pokemon.py", line 3                                                                                4, in work
    self.get_visible_pokemon()
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_pokemon.py", line 7                                                                                5, in get_visible_pokemon
    'expiration_timestamp_ms': pokemon['expiration_timestamp_ms'],
  File "/root/PokemonGo-Bot/pokemongo_bot/base_task.py", line 35, in emit_event
    data=data
  File "/root/PokemonGo-Bot/pokemongo_bot/event_manager.py", line 65, in emit
    handler.handle_event(event, sender, level, formatted_msg, data)
  File "/root/PokemonGo-Bot/pokemongo_bot/event_handlers/social_handler.py", lin                                                                                e 59, in handle_event
    self.mqttc.publish("pgomapgeo/"+geo_hash+"/"+str(data['pokemon_id']), str(da                                                                                ta['latitude'])+","+str(data['longitude'])+","+str(data['encounter_id'])+","+str                                                                                (data['pokemon_id'])+","+str(data['expiration_timestamp_ms'])+","+str(data['poke                                                                                mon_name']))
KeyError: 'pokemon_name'
2016-08-23 23:31:57,068 [sentry.errors] [ERROR] Sentry responded with an error:                                                                                 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: http                                                                                s://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/th                                                                                readed.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/ht                                                                                tp.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.p                                                                                y", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/u                                                                                rllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/u                                                                                rllib/request.py", line 512, in _open
    '_open', req)
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/u                                                                                rllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.p                                                                                y", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/u                                                                                rllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
  File "/root/PokemonGo-Bot/lib/python2.7/encodings/utf_8.py", line 16, in decod                                                                                e
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid s                                                                                tart byte
2016-08-23 23:31:57,069 [sentry.errors.uncaught] [ERROR] [u"KeyError: 'pokemon_n                                                                                ame'", u'  File "pokecli.py", line 703, in <module>', u'  File "pokecli.py", lin                                                                                e 118, in main', u'  File "pokemongo_bot/__init__.py", line 568, in tick', u'  F                                                                                ile "pokemongo_bot/cell_workers/catch_pokemon.py", line 34, in work', u'  File "                                                                                pokemongo_bot/cell_workers/catch_pokemon.py", line 75, in get_visible_pokemon',                                                                                 u'  File "pokemongo_bot/base_task.py", line 35, in emit_event', u'  File "pokemo                                                                                ngo_bot/event_manager.py", line 65, in emit', u'  File "pokemongo_bot/event_hand                                                                                lers/social_handler.py", line 59, in handle_event']
Tue Aug 23 23:31:57 BRT 2016 Pokebot  Stopped.

**Comment by mjmadsen** [comment]
What commit are you on?

**Comment by Vvkmnn** [comment]
I got the same error on a0cb16fabf243cbf0fd50cc9deb28db5403d704c.

**Comment by k4n30** [comment]
@BreezeRo looks to be social related

**Comment by k4n30** [comment]
Closing in favour of #4654 as they have used the issue template correctly, and we can get more indication of the issue from there
