### ISSUE TITLE
Bug with specifying config on dev

### ISSUE THREAD

**Issue by lbanz** [PokemonGoF/PokemonGo-Bot#4674]
Previously I can just do 'python pokecli.py -cf ./configs/config.json' and specify a config file. Now it breaks and gives me this error. The config file is fine, when I run it with ./run.sh or ./pokecli.py it runs without any problems.

I'm guessing it's because an environmental path is not set correctly?

Traceback (most recent call last):
  File "pokecli.py", line 46, in <module>
    from pokemongo_bot import inventory
  File "/Users/xxx/PokemonGo-Bot/pokemongo_bot/__init__.py", line 28, in <module>
    from pokemongo_bot.event_handlers import LoggingHandler, SocketIoHandler, ColoredLoggingHandler, SocialHandler
  File "/Users/xxx/PokemonGo-Bot/pokemongo_bot/event_handlers/__init__.py", line 4, in <module>
    from social_handler import SocialHandler
  File "/Users/xxx/PokemonGo-Bot/pokemongo_bot/event_handlers/social_handler.py", line 4, in <module>
    import paho.mqtt.client as mqtt
ImportError: No module named paho.mqtt.client

**Comment by supergithubo** [comment]
`pip install -r requirements.txt --upgrade`

**Comment by lbanz** [comment]
That worked! thanks. I thought the ./setup -u script does put the --upgrade parameters. I guess not!
