### ISSUE TITLE
Startup error on newest dev commit

### ISSUE THREAD

**Issue by pmwoodward3** [PokemonGoF/PokemonGo-Bot#4678]
Get this when logging in. re-cloned the bot to another folder and reinstalled it and it still happened. Ubuntu x64 16.04.

```
016-08-24 12:01:57,300 [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "pokecli.py", line 703, in <module>
    main()
  File "pokecli.py", line 186, in main
    report_summary(bot)
  File "pokecli.py", line 221, in report_summary
    metrics.capture_stats()
  File "/opt/dev/pokemongo_bot/metrics.py", line 96, in capture_stats
    response_dict = request.call()
  File "/opt/dev/pokemongo_bot/api_wrapper.py", line 239, in call
    result = self._call()
  File "/opt/dev/pokemongo_bot/api_wrapper.py", line 143, in _call
    location_type=1
  File "/opt/dev/local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 533, in init
    setattr(self, field_name, field_value)
  File "/opt/dev/local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 669, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "/opt/dev/local/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 134, in CheckValue
    raise ValueError('Value out of range: %d' % proposed_value)
ValueError: Value out of range: -117
2016-08-24 12:01:57,874 [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/opt/dev/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/opt/dev/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/opt/dev/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/dev/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/opt/dev/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/opt/dev/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/opt/dev/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/opt/dev/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
  File "/opt/dev/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
2016-08-24 12:01:57,876 [sentry.errors.uncaught] [ERROR] [u'ValueError: Value out of range: -117', u'  File "pokecli.py", line 703, in <module>', u'  File "pokecli.py", line 186, in main', u'  File "pokecli.py", line 221, in report_summary', u'  File "pokemongo_bot/metrics.py", line 96, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 239, in call', u'  File "pokemongo_bot/api_wrapper.py", line 143, in _call', u'  File "/opt/dev/local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 533, in init', u'  File "/opt/dev/local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 669, in field_setter', u'  File "/opt/dev/local/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 134, in CheckValue']
Wed Aug 24 12:01:57 EDT 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

```

**Comment by mjmadsen** [comment]
Follow the steps listed in #4477

**Comment by pmwoodward3** [comment]
neither of the solutions in that thread worked for me.

**Comment by mjmadsen** [comment]
Tried going through tor or changing IP too?

**Comment by krishven** [comment]
@mjmadsen yeah those steps didnt work for me either,
one of the solutions is for docker and another one is for Windows.
I'm on a Mac, my IP has not been banned. So didnt work for me

**Comment by pmwoodward3** [comment]
@mjmadsen Yep, different IPs and using torify.

**Comment by supergithubo** [comment]
What is your pogo api version?

**Comment by krishven** [comment]
1.1.8

**Comment by supergithubo** [comment]
Have you installed requirements with --upgrade flag? `pip install -r requirements.txt --upgrade`. I also had the errors but I can't reproduce after doing: (1) requirements upgrade. (2) remove pogo api and reinstall. (3) change my ip (tor reload). (4) recreate bin folder (virtualenv) and (5) disable social. I'm not sure but one of them fixed it.

**Comment by iakovoszournatzis** [comment]
i have the same problem. Any solution guys?

**Comment by mjmadsen** [comment]
What @supergithubo said.

**Comment by iakovoszournatzis** [comment]
i have done all @supergithubo solutions except "change ip" with no luck. I have static IP, so i cannot change it, but do you really think that IP is the problem?

**Comment by mjmadsen** [comment]
@iakovoszournatzis Sorry, this form of error can be tough to hunt down. From what I've seen it is usually solved by following those steps or is an IP ban. Hopefully as some point we can have better error reporting for such problem.

We'll leave open and hopefully someone can help you out more.

**Comment by lwq008** [comment]
I hit into this and used VPN to resolve it. Looks like to me that my IP address was banned.

**Comment by mjmadsen** [comment]
@lwq008 keep in mind a lot of botters are using VPNs. It's only a matter of time before their IP range is also blocked. Perhaps using the TOR network is a better solution (though recent update seems to get the client's network info).

@iakovoszournatzis Any luck?

**Comment by iakovoszournatzis** [comment]
@mjmadsen you guys are right. i got something like ban...

**Comment by mjmadsen** [comment]
@pmwoodward3 How about you?
