### ISSUE TITLE
[ISSUE] Request for new Access Token failed! Logged out

### ISSUE THREAD

**Issue by kevinlife** [PokemonGoF/PokemonGo-Bot#4726]
I got an error when I bot after 40 mins.
Here is the error message...

2016-08-25 10:46:24,738 [    pgoapi] [ERROR] Request for new Access Token failed! Logged out...
Traceback (most recent call last):
  File "pokecli.py", line 88, in <module>
    main()
  File "pokecli.py", line 80, in main
    bot.run()
  File "/root/OpenPoGoBot/pokemongo_bot/bot.py", line 140, in run
    self.stepper.current_lng
  File "/root/OpenPoGoBot/pokemongo_bot/mapper.py", line 33, in get_cells
    response_dict = self.api_wrapper.call()
  File "/root/OpenPoGoBot/api/__init__.py", line 107, in call
    results = request.call()
  File "/root/OpenPoGoBot/src/pgoapi/pgoapi/pgoapi.py", line 244, in call
    raise NotLoggedInException(error)
pgoapi.exceptions.NotLoggedInException: Request for new Access Token failed! Logged out...

**Comment by kevinlife** [comment]
I am sorry, it seems I post to the wrong project ...
