### ISSUE TITLE
TypeError: gdbm key must be string, not unicode

### ISSUE THREAD

**Issue by orchid666** [PokemonGoF/PokemonGo-Bot#4743]
The last dev gave me this weird error.

2016-08-25 18:17:23,739 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-25 18:17:23,748 [       cli] [INFO] commit: 5e50264e7644b007dff7e0e057375cc433c36805
2016-08-25 18:17:23,751 [       cli] [INFO] Configuration initialized
Traceback (most recent call last):
  File "pokecli.py", line 705, in <module>
    main()
  File "pokecli.py", line 103, in main
    bot = PokemonGoBot(config)
  File "/Users/me/Documents/Pokebot/3_PokemonGo-Bot/pokemongo_bot/__init__.py", line 106, in __init__
    if saved_info.has_key('client_id'):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 107, in has_key
    return key in self.dict
TypeError: gdbm key must be string, not unicode

Any idea?

**Comment by Gobberwart** [comment]
#4741 Looks like a lot of people are getting this at the moment (including me)

**Comment by loflol** [comment]
Hello me too :(
