### ISSUE TITLE
Error when starting bot since dev pull this morning.

### ISSUE THREAD

**Issue by Darkayer** [PokemonGoF/PokemonGo-Bot#4807]
OS: MacOS
Branch : DEV (Pulled this morning)
Standard: Dev Config.example.json (Using auth.json)

Since this morning i'm getting : (PokemonGo-Bot) nieks-mbp:PokemonGo-Bot Niek$ python pokecli.py -cf configs/config.json -af configs/auth.json 
2016-08-27 14:46:54,115 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-27 14:46:54,123 [       cli] [INFO] commit: f0623bd014ac4ef2e119f332a4dc6d73eed09f12
2016-08-27 14:46:54,129 [       cli] [INFO] Configuration initialized
2016-08-27 14:46:54,129 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-27 14:46:54,129 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-27 14:46:54,153 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-27 14:46:54,772 [yoyo.migrations] [INFO] Applying pokemongobot
2016-08-27 14:46:54,773 [yoyo.migrations] [INFO]  - applying step 0
2016-08-27 14:46:54,773 [yoyo.migrations] [INFO] Marking pokemongobot applied
2016-08-27 14:46:54,782 [SleepSchedule] [INFO] [next_sleep] Next sleep at 2016-08-27 18:24:36.781958
2016-08-27 14:46:54,900 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-27 14:46:54,901 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-27 14:46:54,901 [PokemonGoBot] [INFO] [location_found] Location found: 52.113824, 4.276923 (52.113824, 4.276923, 8.0)
2016-08-27 14:46:54,901 [PokemonGoBot] [INFO] [position_update] Now at (52.113824, 4.276923, 8.0)
2016-08-27 14:46:54,902 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-27 14:46:57,349 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-27 14:46:57,350 [PokemonGoBot] [INFO] Found encrypt.so! Platform: darwin encrypt.so directory: /Users/Niek/PokemonGo-Bot
2016-08-27 14:46:57,350 [PokemonGoBot] [INFO] 
Traceback (most recent call last):
  File "pokecli.py", line 749, in <module>
    main()
  File "pokecli.py", line 170, in main
    bot.event_manager.emit(
AttributeError: 'bool' object has no attribute 'event_manager'
2016-08-27 14:46:58,798 [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/Niek/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/Niek/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/Niek/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/Niek/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/Niek/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/Niek/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/Niek/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/Niek/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
  File "/Users/Niek/PokemonGo-Bot/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
2016-08-27 14:46:58,799 [sentry.errors.uncaught] [ERROR] [u"AttributeError: 'bool' object has no attribute 'event_manager'", u'  File "pokecli.py", line 749, in <module>', u'  File "pokecli.py", line 170, in main']

Cant really figure out what is happening.

**Comment by Darkayer** [comment]
Problem solved! Got a permaban but somehow the bot couldnt get the output on screen

**Comment by mjmadsen** [comment]
Sorry about the ban, but whew. I was looking at the code wondering wth was going on.

**Comment by jane0815** [comment]
Same problem here. Bot crashed at the same line with same errors.

I had it running without problems after i pulled the update today. But then i seen it had 0 eggs left on the web ui. So i stopped it to login with a phone to see if it really got no eggs. It has 9 eggs and the account is fine too. But i can not start it with the bot.

Another account is working with the same config.

`2016-08-27 19:36:01,704 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-27 19:36:04,896 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-27 19:36:04,897 [PokemonGoBot] [INFO] Found encrypt.so! Platform: darwin encrypt.so directory: /Users/STONE/PokemonGo-Bot
2016-08-27 19:36:04,897 [PokemonGoBot] [INFO] 
Traceback (most recent call last):
  File "pokecli.py", line 746, in <module>
    main()
  File "pokecli.py", line 115, in main
    bot = initialize(config)
  File "pokecli.py", line 83, in initialize
    bot.start()
  File "/Users/STONE/PokemonGo-Bot/pokemongo_bot/__init__.py", line 123, in start
    init_inventory(self)
  File "/Users/STONE/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1234, in init_inventory
    _inventory = Inventory(bot)
  File "/Users/STONE/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1086, in __init__
    self.refresh()
  File "/Users/STONE/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1096, in refresh
    self.update_web_inventory()
  File "/Users/STONE/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1116, in update_web_inventory
    json_inventory = json.load(infile)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: end is out of bounds
2016-08-27 19:36:05,865 [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
2016-08-27 19:36:05,896 [sentry.errors.uncaught] [ERROR] [u'ValueError: end is out of bounds', u'  File "pokecli.py", line 746, in <module>', u'  File "pokecli.py", line 115, in main', u'  File "pokecli.py", line 83, in initialize', u'  File "pokemongo_bot/__init__.py", line 123, in start', u'  File "pokemongo_bot/inventory.py", line 1234, in init_inventory', u'  File "pokemongo_bot/inventory.py", line 1086, in __init__', u'  File "pokemongo_bot/inventory.py", line 1096, in refresh', u'  File "pokemongo_bot/inventory.py", line 1116, in update_web_inventory', u'  File "json/__init__.py", line 291, in load', u'  File "json/__init__.py", line 339, in loads', u'  File "json/decoder.py", line 364, in decode', u'  File "json/decoder.py", line 380, in raw_decode']`
