### ISSUE TITLE
exception when session stale causing location file for web stopped being updated

### ISSUE THREAD

**Issue by lntn** [PokemonGoF/PokemonGo-Bot#4811]
### Expected Behavior
location-[account name].json get updated while the bot is running

### Actual Behavior
the file stop getting updates after re-logging in (session stale) due to an exception

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
```
{
    "auth_service": "google",
    "username": "",
    "password": "",
    "location": "",
    "favorite_locations":[
        
    ],
    "gmapkey": "",
    "encrypt_location": "",
    "websocket_server": false,
    "heartbeat_threshold": 10,
    "enable_social": true,
    "live_config_update": {
      "enabled": true,
      "tasks_only": true
    },
    "tasks": [
      {
        "//NOTE: This task MUST be placed on the top of task list": {},
        "type": "RandomAlivePause",
        "config": {
          "enabled": false,
          "min_duration": "00:00:10",
          "max_duration": "00:10:00",
          "min_interval": "00:05:00",
          "max_interval": "01:30:00"
        }
      },
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward",
        "config": {
          "collect_reward": true,
          "level_limit": -1
        }
      },
      {
        "type": "IncubateEggs",
        "config": {
          "enabled": true,
          "longer_eggs_first": true,
          "min_interval": 120,
         "infinite": [2,5,10],
         "breakable": [2,5,10]
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": true,
          "min_interval": 600,
          "stats": ["uptime", "km_walked", "stops_visited", "xp_earned", "pokemon_stats", "most_perfect_pokemon"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "TransferPokemon",
        "config": {
          "enabled": true,
          "min_free_slot": 9900,
          "transfer_wait_min": 5,
          "transfer_wait_max": 10
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "enabled": false,
            "evolve_all": "none",
            "evolve_iv_min": 0.8,

            "first_evolve_by": "iv",
            "evolve_above_cp": 0,
            "evolve_above_iv": 0.8,
            "logic": "and",
            "min_evolve_speed": 20,
            "max_evolve_speed": 30,
            "use_lucky_egg": false
        }
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": true,
          "nickname_above_iv": 0,
          "dont_nickname_favorite": true,
          "nickname_template": "{name:.10s}{iv_pct2}"
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "max_balls_keep": 150,
          "max_potions_keep": 50,
          "max_berries_keep": 70,
          "max_revives_keep": 70,
          "item_filter": {
            "Pokeball":       { "keep" : 60 },
            "Potion":         { "keep" : 5 },
            "Super Potion":   { "keep" : 15 },
            "Hyper Potion":   { "keep" : 20 },
            "Revive":         { "keep" : 20 },
            "Razz Berry":     { "keep" : 70 },
            "Greatball":      { "keep" : 60 },
            "Ultraball":      { "keep" : 60 }
          },
          "recycle_wait_min": 1,
          "recycle_wait_max": 4,
          "recycle_force": false,
          "recycle_force_min": "00:01:00",
          "recycle_force_max": "00:05:00"
        }
      },
      {
        "type": "CatchPokemon",
        "config": {
          "daily_catch_limit": 800,
          "treat_unseen_as_vip": true,
          "catch_visible_pokemon": true,
          "catch_lured_pokemon": true,
          "min_ultraball_to_keep": 5,
          "berry_threshold": 0.35,
          "vip_berry_threshold": 0.9,
          "catch_throw_parameters": {
            "excellent_rate": 0.1,
            "great_rate": 0.5,
            "nice_rate": 0.3,
            "normal_rate": 0.1,
            "spin_success_rate" : 0.6,
            "hit_rate": 0.8
          },
          "catch_simulation": {
            "flee_count": 3,
            "flee_duration": 2,
            "catch_wait_min": 2,
            "catch_wait_max": 6,
            "berry_wait_min": 2,
            "berry_wait_max": 3,
            "changeball_wait_min": 2,
            "changeball_wait_max": 3,
            "newtodex_wait_min": 20,
            "newtodex_wait_max": 30
          }
        }
      },
      {
        "type": "SpinFort",
        "config": {
          "enabled": true,
          "spin_wait_min": 2,
          "spin_wait_max": 5
        }
      },
      { "type": "UpdateWebInventory",
        "config": {
          "enabled": true
        }
      },
      {
        "type": "FollowPath",
        "config": {
          "enabled": true,
          "walker": "PolylineWalker",
          "path_mode": "loop",
          "path_start_mode": "first",
          "path_file": "configs/path.q1.json",
          "number_lap": 10,
          "timer_restart_min": "00:10:00",
          "timer_restart_max": "00:20:00",
          "log_interval": 5
        }
      },
      {
        "type": "MoveToFort",
        "config": {
          "enabled": true,
          "lure_attraction": true,
          "lure_max_distance": 2000,
          "walker": "PolylineWalker"
        }
      }
    ],

    "map_object_cache_time": 5,
    "pokemon_bag": {
      "show_at_start": true,
      "show_count": true,
      "show_candies": true,
      "pokemon_info": ["cp", "ivcp", "level"]
    },
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 40,
      "cache_recent_forts": true
    },
    "walk_max": 3.5,
    "walk_min": 1.8,
    "alt_min": 500,
    "alt_max": 1000,
    "gps_default_altitude": 8.0,
    "replicate_gps_xy_noise": false,
    "replicate_gps_z_noise": false,
    "gps_xy_noise_range": 0.000125,
    "gps_z_noise_range": 12.5,
    "walker_limit_output": true,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": false,
    "location_cache": false,
    "distance_unit": "km",
    "reconnecting_timeout": 20,
    "logging_color": true,

    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"}
    },

    "release": {
      "Mewtwo": {"release_below_iv": 0},
      "Dragonite": {"release_below_iv": 0},
      "Mew": {"release_below_iv": 0},
      "Moltres": {"release_below_iv": 0},
      "Snorlax": {"release_below_iv": 0},
      "Zapdos": {"release_below_iv": 0},
      "Lapras": {"release_below_iv": 0},
      "Articuno": {"release_below_iv": 0},
      "Arcanine": {"release_below_iv": 0},
      "Vaporeon": {"release_below_iv": 0},
      "Exeggutor": {"release_below_iv": 0},
      "Gyarados": {"release_below_iv": 0.6},
      "Flareon": {"release_below_iv": 0.6},
      "Muk": {"release_below_iv": 0.6},
      "Slowbro": {"release_below_iv": 0.6},
      "Machamp": {"release_below_iv": 0.6},
      "Venusaur": {"release_below_iv": 0.6},
      "Charizard": {"release_below_iv": 0.6},
      "Victreebel": {"release_below_iv": 0.6},
      "Pollwrath": {"release_below_iv": 0.7},
      "Blastoise": {"release_below_iv": 0.7},
      "Nidoking": {"release_below_iv": 0.7},
      "Nidoqueen": {"release_below_iv": 0.7},
      "Vileplume": {"release_below_iv": 0.7},

      "any": {"release_below_cp": 0, "release_below_iv": 0.9, "logic": "or", "keep_best_iv":1}
    },

    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1500, "catch_above_iv": 0.9, "logic": "or" },

        "Mewtwo": {},
        "Dragonite": {},
        "Mew": {},
        "Moltres": {},
        "Snorlax": {},
        "Zapdos": {},
        "Lapras": {},
        "Articuno": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Exeggutor": {},
        "Gyarados": {},
        "Flareon": {},
        "Muk": {},
        "Slowbro": {},
        "Machamp": {},
        "Venusaur": {},
        "Charizard": {},
        "Victreebel": {},
        "Pollwrath": {},
        "Blastoise": {},
        "Nidoking": {},
        "Nidoqueen": {},
        "Vileplume": {}
    }
}
```

### Output when issue occurred
```
2016-08-27 19:43:19,746 [PokemonGoBot] [INFO] [api_error] Session stale, re-logging in.
2016-08-27 19:43:19,756 [PokemonGoBot] [INFO] [login_started] Login procedure started.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/namle/Downloads/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1245, in update_web_location_worker
    self.update_web_location()
  File "/Users/namle/Downloads/PokemonGo-Bot/pokemongo_bot/__init__.py", line 690, in update_web_location
    cells = self.find_close_cells(*location)
  File "/Users/namle/Downloads/PokemonGo-Bot/pokemongo_bot/__init__.py", line 726, in find_close_cells
    response_dict = self.get_map_objects(lat, lng, timestamp, cellid)
  File "/Users/namle/Downloads/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1300, in get_map_objects
    cell_id=cellid
  File "/Users/namle/Downloads/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 137, in function
    return request.call()
  File "/Users/namle/Downloads/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 219, in call
    raise NotLoggedInException()
NotLoggedInException

2016-08-27 19:43:22,452 [PokemonGoBot] [INFO] [login_successful] Login successful.
```

### Steps to Reproduce
randomly when session stale

### Other Information
OS: 
OSx 10.11.6
Branch: 
master
Git Commit: 
ed095936e8fb2bdb7442c9966630664f0cb739ea
Python Version: 
2.7.10

**Comment by lntn** [comment]
maybe the bot should start the walker thread again after relogging in.

**Comment by mjmadsen** [comment]
Walker isn't going to help much if the API wasn't able to log you back in

**Comment by lntn** [comment]
Log back in just fine. It's the thread/worker (sorry not walker) for updating location file has not been restarted after the exception.

**Comment by mjmadsen** [comment]
@Gobberwart Is this the same as #4841?

**Comment by Gobberwart** [comment]
@mjmadsen It's a bit different, but again has to do with reading/writing json files. Not sure what's going on but will add it to my list to look at.

**Comment by mjmadsen** [comment]
Thanks bud. :+1:

**Comment by mjmadsen** [comment]
Maybe as a bandaid we try reading the file, if it fails we delete and recreate it? At least we can avoid people crashing entirely (but will teleport to their start location).

**Comment by Gobberwart** [comment]
Heh, we're on exactly the same wavelength. I was looking at something like the following as a temporary fix/workaround for the items:

``
        try:
            with open(web_inventory, "r") as infile:
                json_inventory = json.load(infile)
        except ValueError:
            # Unable to read json from web inventory
            # File may be corrupt. Create a new one.            
            json_inventory = []
```

And then continue to build the data from an empty list before dumping to the json file

**Comment by iruy** [comment]
Why would you build the inventory json object from the web file, instead of using the api output inventory file to overwrite it each time?

**Comment by mjmadsen** [comment]
Closing #4811
