### ISSUE TITLE
Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position

### ISSUE THREAD

**Issue by updatesvc** [PokemonGoF/PokemonGo-Bot#4817]
### Expected Behavior
Login as normally it does

### Actual Behavior
`2016-08-27 20:06:46,812 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-27 20:06:46,825 [       cli] [INFO] commit: not found
2016-08-27 20:06:46,846 [       cli] [INFO] No config argument specified, checking for /configs/config.json
2016-08-27 20:06:46,851 [       cli] [WARNING] The daily_catch_limit argument has been moved into the CatchPokemon Task
2016-08-27 20:06:46,862 [       cli] [INFO] Configuration initialized
2016-08-27 20:06:46,864 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-27 20:06:46,865 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-27 20:06:46,881 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-27 20:06:47,660 [SleepSchedule] [INFO] [next_sleep] Next sleep at 2016-08-28 12:09:38.660000
2016-08-27 20:06:47,841 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-27 20:06:47,842 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-27 20:06:47,842 [PokemonGoBot] [INFO] [location_found] Location found: -33.859221,151.208805 (-33.859221, 151.208805, 8.0)
2016-08-27 20:06:47,844 [PokemonGoBot] [INFO] [position_update] Now at (-33.859221, 151.208805, 8.0)
2016-08-27 20:06:47,845 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-27 20:06:51,598 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-27 20:06:51,631 [PokemonGoBot] [INFO] Found encrypt.dll! Platform: win32 encrypt.dll directory: C:\poke\PokemonGo-Bot
2016-08-27 20:06:51,632 [PokemonGoBot] [INFO]
Traceback (most recent call last):
  File "pokecli.py", line 746, in <module>
    main()
  File "pokecli.py", line 170, in main
    bot.event_manager.emit(
AttributeError: 'bool' object has no attribute 'event_manager'
2016-08-27 20:06:52,421 [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\raven\transport\threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "C:\Python27\lib\site-packages\raven\transport\http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 494, in open
    response = self._open(req, data)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 512, in _open
    '_open', req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python27\lib\httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 891, in _send_output
    msg += message_body
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
2016-08-27 20:06:52,424 [sentry.errors.uncaught] [ERROR] [u"AttributeError: 'bool' object has no attribute 'event_manager'", u'  File "pokecli.py", line 746, in <module>', u'  File "pokecli.py", line 170, in main']

 Something went wrong and the bot needed to be restarted. Please investigate the cause.

Waiting for 24 seconds, press a key to continue ...
`

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
`{
    "auth_service": "google",
    "username": "***@gmail.com",
    "password": "*****;",
    "location": "-33.859221,151.208805",
    "favorite_locations":[
        
        {"name": "Sydney", "coords": "-33.859221,151.208805"}
    ],
    "gmapkey": "***",
    "encrypt_location": "",
    "websocket_server": false,
    "heartbeat_threshold": 10,
    "enable_social": true,
    "live_config_update": {
      "enabled": false,
      "tasks_only": false
    },
    "tasks": [
      {
        "//NOTE: This task MUST be placed on the top of task list": {},
        "type": "RandomAlivePause",
        "config": {
          "enabled": false,
          "min_duration": "00:00:10",
          "max_duration": "00:10:00",
          "min_interval": "00:05:00",
          "max_interval": "01:30:00"
        }
      },
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "RandomPause",
        "config": {
          "enabled": false,
          "min_duration": "00:00:10",
          "max_duration": "00:10:00",
          "min_interval": "00:10:00",
          "max_interval": "02:00:00"
        }
      },
      {
        "type": "CompleteTutorial",
        "config": {
          "enabled": false,
          "// set a name": "",
          "nickname": ""
        }
      },
      {
        "type": "CollectLevelUpReward",
        "config": {
          "collect_reward": true,
          "level_limit": -1
        }
      },
      {
        "type": "IncubateEggs",
        "config": {
          "enabled": true,
          "longer_eggs_first": true,
          "min_interval": 120,
         "infinite": [2,5,10],
         "breakable": [2,5,10]
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "UpdateLiveInventory",
        "config": {
          "enabled": false,
          "min_interval": 120,
          "show_all_multiple_lines": false,
          "items": ["pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries", "luckyegg"]
        }
      },
      {
        "type": "ShowBestPokemon",
        "config": {
          "enabled": true,
          "min_interval": 60,
          "amount": 5,
          "order_by": "cp",
          "info_to_show": ["cp", "ivcp", "dps", "hp"]
        }
      },
      {
        "type": "TransferPokemon",
        "config": {
          "enabled": true,
          "min_free_slot": 5,
          "transfer_wait_min": 3,
          "transfer_wait_max": 5
        }
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_above_iv": 0.9,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "enabled": false,
          "evolve_all": "none",
          "first_evolve_by": "cp",
          "evolve_above_cp": 500,
          "evolve_above_iv": 0.8,
          "logic": "or",
          "min_evolve_speed": 25,
          "max_evolve_speed": 30,
          "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "enabled": true,
          "min_empty_space": 15,
          "max_balls_keep": 150,
          "max_potions_keep": 50,
          "max_berries_keep": 70,
          "max_revives_keep": 70,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          },
          "recycle_wait_min": 3,
          "recycle_wait_max": 5,
          "recycle_force": true,
          "recycle_force_min": "00:01:00",
          "recycle_force_max": "00:05:00"
        }
      },
      {
        "type": "CatchPokemon",
        "config": {
          "enabled": true,
          "catch_visible_pokemon": true,
          "catch_lured_pokemon": true,
          "min_ultraball_to_keep": 5,
          "berry_threshold": 0.35,
          "vip_berry_threshold": 0.9,
          "treat_unseen_as_vip": true,
          "catch_throw_parameters": {
            "excellent_rate": 0.1,
            "great_rate": 0.5,
            "nice_rate": 0.3,
            "normal_rate": 0.1,
            "spin_success_rate" : 0.6,
            "hit_rate": 0.75
          },
          "catch_simulation": {
            "flee_count": 3,
            "flee_duration": 2,
            "catch_wait_min": 3,
            "catch_wait_max": 6,
            "berry_wait_min": 3,
            "berry_wait_max": 5,
            "changeball_wait_min": 3,
            "changeball_wait_max": 5,
            "newtodex_wait_min": 20, 
            "newtodex_wait_max": 30
          }
        }
      },
      {
        "type": "SpinFort",
        "config": {
          "enabled": true,
          "spin_wait_min": 3,
          "spin_wait_max": 5
        }
      },
      { "type": "UpdateWebInventory",
        "config": {
          "enabled": true
        }
      },
      {
        "type": "MoveToFort",
        "config": {
          "enabled": true,
          "lure_attraction": true,
          "lure_max_distance": 2000,
          "walker": "StepWalker"
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "enabled": true,
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "pokemon_bag": {
      "// if 'show_at_start' is true, it will log all the pokemons in the bag (not eggs) at bot start": {},
      "show_at_start": true,
      "// if 'show_count' is true, it will show the amount of each pokemon (minimum 1)": {},
      "show_count": false,
      "// if 'show_candies' is true, it will show the amount of candies for each pokemon": {},
      "show_candies": false,
      "// 'pokemon_info' parameter define which info to show for each pokemon": {},
      "// the available options are": {},
      "// ['cp', 'iv_ads', 'iv_pct', 'ivcp', 'ncp', 'level', 'hp', 'moveset', 'dps']": {},
      "pokemon_info": ["cp", "iv_pct"]
    },
    "walk_max": 4.16,
    "walk_min": 2.16,
    "alt_min": 500,
    "alt_max": 1000,
    "sleep_schedule": [
      {
        "time": "12:00",
        "duration": "5:30",
        "time_random_offset": "00:30",
        "duration_random_offset": "00:30",
        "wake_up_at_location": ""
      },
      {
        "time": "17:45",
        "duration": "3:00",
        "time_random_offset": "01:00",
        "duration_random_offset": "00:30",
        "wake_up_at_location": ""
      }
    ],
    "gps_default_altitude": 8.0,
    "replicate_gps_xy_noise": false,
    "replicate_gps_z_noise": false,
    "gps_xy_noise_range": 0.000125,
    "gps_z_noise_range": 12.5,
    "debug": false,
    "test": false,
    "walker_limit_output": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging_color": true,
    "daily_catch_limit": 800,
    "catch": {
      "any": {"candy_threshold" : 400 ,"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Keep no more than 3 best IV pokemon for every pokemon type": {},
      "// any": {"keep_best_iv": 3},
      "// Discard all pokemon in bag except 100 pokemon with best CP": {},
      "// all": {"keep_best_cp": 100},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3},
      "// Example of custom order of static criterion": {},
      "// Zubat": {"keep_best_custom": "iv, cp, hp_max", "amount":2}
    },
    "vips" : {
        "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    }
}
`

### Output when issue occurred
`2016-08-27 20:10:10,471 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-27 20:10:10,482 [       cli] [INFO] commit: not found
2016-08-27 20:10:10,493 [       cli] [INFO] No config argument specified, checking for /configs/config.json
2016-08-27 20:10:10,497 [       cli] [WARNING] The daily_catch_limit argument has been moved into the CatchPokemon Task
2016-08-27 20:10:10,497 [       cli] [INFO] Configuration initialized
2016-08-27 20:10:10,499 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-27 20:10:10,499 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-27 20:10:10,509 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-27 20:10:11,007 [SleepSchedule] [INFO] [next_sleep] Next sleep at 2016-08-28 11:31:03.008000
2016-08-27 20:10:11,209 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-27 20:10:11,210 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-27 20:10:11,210 [PokemonGoBot] [INFO] [location_found] Location found: -33.859221,151.208805 (-33.859221, 151.208805, 8.0)
2016-08-27 20:10:11,211 [PokemonGoBot] [INFO] [position_update] Now at (-33.859221, 151.208805, 8.0)
2016-08-27 20:10:11,213 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-27 20:10:15,051 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-27 20:10:15,052 [PokemonGoBot] [INFO] Found encrypt.dll! Platform: win32 encrypt.dll directory: C:\poke\PokemonGo-Bot
2016-08-27 20:10:15,052 [PokemonGoBot] [INFO]
Traceback (most recent call last):
  File "pokecli.py", line 746, in <module>
    main()
  File "pokecli.py", line 170, in main
    bot.event_manager.emit(
AttributeError: 'bool' object has no attribute 'event_manager'
2016-08-27 20:10:17,365 [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\raven\transport\threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "C:\Python27\lib\site-packages\raven\transport\http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 494, in open
    response = self._open(req, data)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 512, in _open
    '_open', req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python27\lib\httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 891, in _send_output
    msg += message_body
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
2016-08-27 20:10:17,371 [sentry.errors.uncaught] [ERROR] [u"AttributeError: 'bool' object has no attribute 'event_manager'", u'  File "pokecli.py", line 746, in <module>', u'  File "pokecli.py", line 170, in main']

 Something went wrong and the bot needed to be restarted. Please investigate the cause.

Waiting for  0 seconds, press a key to continue`

### Steps to Reproduce
I just ran the bot using windowsstart.bat .. I tried using another account it worked...could this be because I have been banned (I can't login on my phone also "Unable to authenticate .." is what I get on my phone) I haven't received a ban notice from Ninantic in my email... If I this is a ban is there a way you can know for sure in this bot or in another app something like banchecker.com .
Thanks in adavnce.
### Other Information
OS: 
Windows 10 Pro Build 14393.82
Branch: 
Master
Git Commit: 
ed095936e8fb2bdb7442c9966630664f0cb739ea
Python Version: 
Python 2.7.10
Any other relevant files/configs (eg: path files)

**Comment by jane0815** [comment]
Same problem here. Other account is working normal with the bot. No problems on phone.

**Comment by Gobberwart** [comment]
I suspect you're banned. The error you're seeing appears to be in the code to raise a permaban exception.

**Comment by updatesvc** [comment]
I agree @Gobberwart 
I am closing the issue.

**Comment by Gobberwart** [comment]
@updatesvc there's still a bug. There's supposed to be an error message shown, not a complete crash.

**Comment by Gobberwart** [comment]
Looking at it now

**Comment by jane0815** [comment]
No the account is not banned. It is working fine on phone. I can spin stops and catch pokemons.

**Comment by Gobberwart** [comment]
You sure about that @jane0815 ? The code referenced in the error is specifically related to permaban:

```
2016-08-27 20:10:17,371 [sentry.errors.uncaught] [ERROR] [u"AttributeError: 'bool' object has no attribute 'event_manager'", u' File "pokecli.py", line 746, in ', u' File "pokecli.py", line 170, in main']
```

Do you see that exact error?

**Comment by Gobberwart** [comment]
PR being submitted now for this error.

**Comment by jane0815** [comment]
for me the error is a bit different in this line:

2016-08-27 19:53:40,131 [sentry.errors.uncaught] [ERROR] [u'ValueError: end is out of bounds', u' File "pokecli.py", line 746, in ', u' File "pokecli.py", line 115, in main', u' File "pokecli.py", line 83, in initialize', u' File "pokemongo_bot/__init.py", line 123, in start', u' File "pokemongo_bot/inventory.py", line 1234, in init_inventory', u' File "pokemongo_bot/inventory.py", line 1086, in init', u' File "pokemongo_bot/inventory.py", line 1096, in refresh', u' File "pokemongo_bot/inventory.py", line 1116, in update_web_inventory', u' File "json/init.py", line 291, in load', u' File "json/init.py", line 339, in loads', u' File "json/decoder.py", line 364, in decode', u' File "json/decoder.py", line 380, in raw_decode']

**Comment by updatesvc** [comment]
look like it could be another unrelated issue..not sure though

**Comment by Gobberwart** [comment]
Yep, that's a different error. Please log a new issue @jane0815

**Comment by rawgni** [comment]
looks like the inventory file is corrupted.
can you post the inventory file found in web/inventory-<username>.json ?

**Comment by Gobberwart** [comment]
I was thinking that too @rawgni 

You can test by stopping the bot, renaming the inventory file "web/inventory-USERNAME.json" to something like "inventory-USERNAME.test.json" and restart the bot. It should recreate the inventory file on startup.

**Comment by jane0815** [comment]
Bot is working again after i delete all and pulled a new clone.

But your guess is right i think. Bot was stopped after web showed it had 0 eggs left.

**Comment by mjmadsen** [comment]
Please open a new issue if you have problems (it should be showing a new error log).
