### ISSUE TITLE
Invalid Token : Telegram !

### ISSUE THREAD

**Issue by avneetsb** [PokemonGoF/PokemonGo-Bot#4820]
Traceback (most recent call last):
  File "pokecli.py", line 750, in <module>
    main()
  File "pokecli.py", line 115, in main
    bot = initialize(config)
  File "pokecli.py", line 84, in initialize
    initialize_task(bot,config)
  File "pokecli.py", line 78, in initialize_task
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "/Users/avneet/Desktop/PokemonGo-Bot/pokemongo_bot/tree_config_builder.py", line 79, in build
    instance = worker(self.bot, task_config)
  File "/Users/avneet/Desktop/PokemonGo-Bot/pokemongo_bot/base_task.py", line 23, in __init__
    self.initialize()
  File "/Users/avneet/Desktop/PokemonGo-Bot/pokemongo_bot/cell_workers/telegram_task.py", line 21, in initialize
    self.tbot = telegram.Bot(api_key)
  File "/Users/avneet/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/telegram/bot.py", line 51, in __init__
    self.token = self._validate_token(token)
  File "/Users/avneet/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/telegram/bot.py", line 75, in _validate_token
    raise InvalidToken()
telegram.error.InvalidToken: Invalid token
Sat Aug 27 23:08:32 IST 2016 Pokebot  Stopped.

Config.json
{
        "type": "TelegramTask",
        "config": {
            "enabled": false
        }
    },

**Comment by askovpen** [comment]
#4816

**Comment by Gobberwart** [comment]
Until this PR is merged, you can avoid the error by removing the TelegramTask from config.json (not disable, remove the task entirely)

**Comment by mjmadsen** [comment]
Merged

**Comment by R2RM** [comment]
'12345678:ABCDEfgHIDUROVjkLmNOPQRSTUvw-cdEfgHI'

**Comment by LilkingNasser10** [comment]
Why not open the links

**Comment by akk85590-svg** [comment]
12345678:ABCDEfgHIDUROVjkLmNOPQRSTUvw-cdEfgHI'

**Comment by akk85590-svg** [comment]
12345678:ABCDEfgHIDUROVjkLmNOPQRSTUvw-cdEfgHI'
