### ISSUE TITLE
error: bad char in struct format Removing descriptor: 7L, but the bot runs

### ISSUE THREAD

**Issue by loflol** [PokemonGoF/PokemonGo-Bot#4830]
### Expected Behavior

No error message 

### Actual Behavior

Some error messages

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

[config.json.txt](https://github.com/PokemonGoF/PokemonGo-Bot/files/440865/config.json.txt)

### Output when issue occurred

2016-08-27 22:23:54,670 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-27 22:23:54,713 [       cli] [INFO] commit: b7be689c73117eab51ecada295ea2a60c19a1a09
2016-08-27 22:23:54,715 [       cli] [INFO] Error: No /configs/auth.json
2016-08-27 22:23:54,715 [       cli] [INFO] No config argument specified, checking for /Users/lofphotographe/PokemonGo-Bot/pokemongo_bot/../configs/config.json
2016-08-27 22:23:54,719 [       cli] [INFO] Configuration initialized
2016-08-27 22:23:54,719 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-27 22:23:54,719 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-27 22:23:54,814 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-27 22:23:55,529 [SleepSchedule] [INFO] [next_sleep] Next sleep at 2016-08-28 00:11:01.529046
2016-08-27 22:23:55,651 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-27 22:23:55,653 [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/eventlet/hubs/kqueue.py", line 107, in wait
    readers.get(fileno, noop).cb(fileno)
  File "/usr/local/lib/python2.7/site-packages/eventlet/green/select.py", line 55, in on_read
    current.switch(([original], [], []))
  File "/usr/local/lib/python2.7/site-packages/eventlet/green/thread.py", line 41, in __thread_body
    func(*args, **kwargs)
  File "/Users/------/PokemonGo-Bot/pokemongo_bot/event_handlers/social_handler.py", line 67, in run
    self._mqttc.loop_forever(timeout=30.0, max_packets=100, retry_first_connection=False)
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1378, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 897, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1177, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1766, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 2239, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 2391, in _handle_publish
    (message.topic, packet) = struct.unpack(pack_format, packet)
error: bad char in struct format
Removing descriptor: 7L
2016-08-27 22:23:58,797 [PokemonGoBot] [INFO] [login_successful] Login successful.

### Steps to Reproduce

Start the bot

### Other Information
OS: OSX El Capitan Version 10.11.6
 
Branch: Dev
 
Git Commit: 
 
commit b7be689c73117eab51ecada295ea2a60c19a1a09
Author: LuckyMe4Evers <luckyme4evers@hotmail.com>
Date:   Sat Aug 27 22:14:31 2016 +0200

Python Version: 
  Python 2.7.12
Any other relevant files/configs (eg: path files)

**Comment by mjmadsen** [comment]
Luckyme merged a fix for this. Try out the new dev branch.

**Comment by mjmadsen** [comment]
@loflol Please reopen if the problem persists.
