### ISSUE TITLE
Help setting up bot

### ISSUE THREAD

**Issue by uic3hj** [PokemonGoF/PokemonGo-Bot#4850]
Hello! i got errors:
Anyone knows what is the problem here?
2016-08-28 16:46:52,706 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-28 16:46:52,720 [       cli] [INFO] commit: not found
2016-08-28 16:46:52,724 [       cli] [INFO] No auth argument specified, checking for C:\Users\Anthony\Desktop\PokemonGo-Bot-master\pokemongo_bot\..\configs\auth.json
2016-08-28 16:46:52,734 [       cli] [INFO] Error: No /configs/config.json
2016-08-28 16:46:52,740 [      root] [ERROR] No tasks are configured. Did you mean to configure some behaviors? Read https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files#configuring-tasks for more information
Traceback (most recent call last):
  File "pokecli.py", line 764, in <module>
    main()
  File "pokecli.py", line 106, in main
    config, config_file = init_config()
TypeError: 'NoneType' object is not iterable

**Comment by MZorzy** [comment]
have u edited auth.json ?

**Comment by rawgni** [comment]
@uic3hj seems like you are missing a config.json file

**Comment by jrjhealey** [comment]
Check your config.json at jsonlint.com (assuming you have one - if not, that is your issue).

Also you should give us more information as per the issue template, your commit, OS etc.

**Comment by mjmadsen** [comment]
We are missing that wiki the bot prints. But either way, doesn't look like there is a config or auth setup.
