### ISSUE TITLE
After update, i am getting this error below

### ISSUE THREAD

**Issue by igorhrq** [PokemonGoF/PokemonGo-Bot#4867]
Hello to everyone and @PokemonGoF staff/team/guys,

I am getting this error below, after tried **update with -u option**, i have tried reinstall full, removing the old version and start from the begin, but still have same error, look the code : 

`[2016-08-28 15:30:13] [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "pokecli.py", line 768, in <module>
    main()
  File "pokecli.py", line 207, in main
    report_summary(bot)
  File "pokecli.py", line 253, in report_summary
    metrics.capture_stats()
  File "/home/rhodan/PokemonGo-Bot/pokemongo_bot/metrics.py", line 106, in capture_stats
    response_dict = request.call()
  File "/home/rhodan/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 223, in call
    if not self.can_call():
  File "/home/rhodan/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 128, in can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
[2016-08-28 15:30:14] [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/rhodan/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/rhodan/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/rhodan/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/rhodan/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/rhodan/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/rhodan/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/rhodan/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/rhodan/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 848, in _send_output
    msg += message_body
  File "/home/rhodan/PokemonGo-Bot/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
[2016-08-28 15:30:14] [sentry.errors.uncaught] [ERROR] [u'NotLoggedInException', u'  File "pokecli.py", line 768, in <module>', u'  File "pokecli.py", line 207, in main', u'  File "pokecli.py", line 253, in report_summary', u'  File "pokemongo_bot/metrics.py", line 106, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 223, in call', u'  File "pokemongo_bot/api_wrapper.py", line 128, in can_call']
Dom Ago 28 15:30:14 BRT 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
`

Look the [screenshot](http://prnt.sc/cbexk9)

**Anyone have a clue, or can help me with a solution? Please?**

Thanks all!
Best Regards!

**Comment by igorhrq** [comment]
This issue was fixed, thanks!

**Comment by sniperxing** [comment]
how to fix?
