### ISSUE TITLE
[BUG] Error in Telegram: "AttributeError: 'module' object has no attribute 'now'"

### ISSUE THREAD

**Issue by davidspeijer** [PokemonGoF/PokemonGo-Bot#4929]
### Expected Behavior

Bot running with Telegram enabled

### Actual Behavior

Bot not starting due to error message

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

http://pastebin.com/5nQC2ceh

### Output when issue occurred

Traceback (most recent call last):
  File "pokecli.py", line 781, in <module>
    main()
  File "pokecli.py", line 128, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 88, in start_bot
    initialize_task(bot, config)
  File "pokecli.py", line 79, in initialize_task
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "/PokemonGo-Bot/pokemongo_bot/tree_config_builder.py", line 79, in build
    instance = worker(self.bot, task_config)
  File "/PokemonGo-Bot/pokemongo_bot/base_task.py", line 23, in __init__
    self.initialize()
  File "/PokemonGo-Bot/pokemongo_bot/cell_workers/telegram_task.py", line 42, in initialize
    self.next_job=datetime.now() + timedelta(seconds=self.min_interval)
AttributeError: 'module' object has no attribute 'now'

### Steps to Reproduce

Start the bot with the above config.

### Other Information
OS: CentOS
 
Branch: dev
 
Git Commit: 9e81c6ed90d79e181599ec7f0a0cfa2ecd4d09f5
 
Python Version: Python 2.7.5
 
Any other relevant files/configs (eg: path files)

**Comment by mjmadsen** [comment]
Merged fix to dev branch
