### ISSUE TITLE
Default Config not working very vell

### ISSUE THREAD

**Issue by perpysling2** [PokemonGoF/PokemonGo-Bot#4939]
For starters, i think the bot should capture all pokemons it sees, and transfer and save up candy for evolving.

My config capture pokemons until inventory is full then only goes to pokestops. 

Can anyone help me with a usable config? one that i can start today and look on my bot in 2 weeks again or something?

**Comment by davidspeijer** [comment]
http://pastebin.com/5nQC2ceh

You can run it for at least one week without looking to it...

**Comment by mjmadsen** [comment]
@perpysling2 Can we see configs / logs? Bot should be transferring pokemon and continuing fine.

**Comment by perpysling2** [comment]
I can share log if you tell me where to find it :)

Thans davisapeijer, will try this config..

**Comment by perpysling2** [comment]
new config give me this.

`Traceback (most recent call last):
  File "pokecli.py", line 768, in <module>
    main()
  File "pokecli.py", line 119, in main
    bot = start_bot(bot,config)
  File "pokecli.py", line 87, in start_bot
    initialize_task(bot,config)
  File "pokecli.py", line 78, in initialize_task
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "C:\test\PokemonGo-Bot\pokemongo_bot\tree_config_builder.py", line 79, in build
    instance = worker(self.bot, task_config)
  File "C:\test\PokemonGo-Bot\pokemongo_bot\base_task.py", line 23, in __init__
    self.initialize()
  File "C:\test\PokemonGo-Bot\pokemongo_bot\cell_workers\telegram_task.py", line 31, in initialize
    self.tbot = telegram.Bot(api_key)
  File "C:\Python27\lib\site-packages\telegram\bot.py", line 51, in __init__
    self.token = self._validate_token(token)
  File "C:\Python27\lib\site-packages\telegram\bot.py", line 75, in _validate_token
    raise InvalidToken()
telegram.error.InvalidToken: Invalid token

 Something went wrong and the bot needed to be restarted. Please investigate the cause.


Waiting for 56 seconds, press a key to continue ...`

**Comment by davidspeijer** [comment]
You need to set the token in the auth confit file or disable the telegram task of you don't use it

**Comment by perpysling2** [comment]
not sure what token is, but worked when set to false.. dont know where to read abaout everything to config here :|

**Comment by mjmadsen** [comment]
The implementation of telegram is less than ideal. I'd recommend disabling for now.

**Comment by perpysling2** [comment]
ok, will try this config for a little a while and se if it solves my problem. thanks for great support.

looks like i can bot a couple of users based on the web gui? and is it safe?

**Comment by perpysling2** [comment]
1 last thing. it runs with 60% cpu witch is alot? it has 4 core 2.4ghz xenon?

**Comment by doctordo0m** [comment]
I like much the current latest default config, combined with the optimizer:

```json
{
    "websocket_server": false,
    "heartbeat_threshold": 10,
    "enable_social": true,
    "live_config_update": {
        "enabled": false,
        "tasks_only": false
    },
    "tasks": [
        {
            "type": "TelegramTask",
            "config": {
                "enabled": false,
                "master": null,
                "min_interval": 120,
                "// old syntax, still supported: alert_catch": [ "all" ],
                "// new syntax:": { },
                "alert_catch": {
                    "all": {
                        "operator": "and",
                        "cp": 1300,
                        "iv": 0.95
                    },
                    "Snorlax": {
                        "operator": "or",
                        "cp": 900,
                        "iv": 0.9
                    }
                }
            }
        },
        {
            "//NOTE: This task MUST be placed on the top of task list": { },
            "type": "RandomAlivePause",
            "config": {
                "enabled": true,
                "min_duration": "00:00:10",
                "max_duration": "00:10:00",
                "min_interval": "00:05:00",
                "max_interval": "01:30:00"
            }
        },
        {
            "type": "HandleSoftBan"
        },
        {
            "type": "RandomPause",
            "config": {
                "enabled": false,
                "min_duration": "00:00:10",
                "max_duration": "00:10:00",
                "min_interval": "00:10:00",
                "max_interval": "02:00:00"
            }
        },
        {
            "type": "CompleteTutorial",
            "config": {
                "enabled": false,
                "// set a name": "",
                "nickname": ""
            }
        },
        {
            "type": "CollectLevelUpReward",
            "config": {
                "collect_reward": true,
                "level_limit": -1
            }
        },
        {
            "type": "IncubateEggs",
            "config": {
                "enabled": true,
                "infinite_longer_eggs_first": false,
                "breakable_longer_eggs_first": true,
                "min_interval": 120,
                "infinite": [ 2, 5, 10 ],
                "breakable": [ 2, 5, 10 ]
            }
        },
        {
            "type": "UpdateLiveStats",
            "config": {
                "enabled": true,
                "min_interval": 10,
                "stats": [ "username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited" ],
                "terminal_log": true,
                "terminal_title": true
            }
        },
        {
            "type": "UpdateLiveInventory",
            "config": {
                "enabled": false,
                "min_interval": 120,
                "show_all_multiple_lines": false,
                "items": [ "pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries", "luckyegg" ]
            }
        },
        {
            "type": "ShowBestPokemon",
            "config": {
                "enabled": true,
                "min_interval": 60,
                "amount": 5,
                "order_by": "cp",
                "info_to_show": [ "cp", "ivcp", "dps", "hp" ]
            }
        },
        {
            "type": "PokemonOptimizer",
            "config": {
                "enabled": true,
                "transfer": true,
                "transfer_wait_min": 3,
                "transfer_wait_max": 5,
                "evolve": true,
                "evolve_time": 25,
                "evolve_for_xp": true,
                "evolve_only_with_lucky_egg": false,
                "evolve_count_for_lucky_egg": 80,
                "may_use_lucky_egg": true,
                "upgrade": true,
                "groups": {
                    "gym": [ "Dragonite", "Snorlax", "Lapras", "Arcanine", "Vaporeon" ]
                },
                "keep": [
                    {
                        "mode": "by_family",
                        "top": 1,
                        "sort": [ { "iv": 0.9 } ],
                        "evolve": true,
                        "upgrade": false
                    },
                    {
                        "mode": "by_family",
                        "top": 1,
                        "sort": [ { "ncp": "0.9" } ],
                        "evolve": true,
                        "upgrade": false
                    },
                    {
                        "mode": "by_family",
                        "top": 1,
                        "sort": [ "cp" ],
                        "evolve": false,
                        "upgrade": false
                    },
                    {
                        "mode": "by_family",
                        "names": [ "gym" ],
                        "top": 3,
                        "sort": [
                            { "iv": 0.9 },
                            { "ncp": "0.9" }
                        ],
                        "evolve": true,
                        "upgrade": true
                    }
                ]
            }
        },
        {
            "type": "RecycleItems",
            "config": {
                "enabled": true,
                "min_empty_space": 15,
                "max_balls_keep": 150,
                "max_potions_keep": 50,
                "max_berries_keep": 70,
                "max_revives_keep": 70,
                "item_filter": {
                    "Pokeball": { "keep": 100 },
                    "Potion": { "keep": 10 },
                    "Super Potion": { "keep": 20 },
                    "Hyper Potion": { "keep": 30 },
                    "Revive": { "keep": 30 },
                    "Razz Berry": { "keep": 100 }
                },
                "recycle_wait_min": 3,
                "recycle_wait_max": 5,
                "recycle_force": true,
                "recycle_force_min": "00:01:00",
                "recycle_force_max": "00:05:00"
            }
        },
        {
            "type": "CatchPokemon",
            "config": {
                "enabled": true,
                "catch_visible_pokemon": true,
                "catch_lured_pokemon": true,
                "min_ultraball_to_keep": 5,
                "berry_threshold": 0.35,
                "vip_berry_threshold": 0.9,
                "treat_unseen_as_vip": true,
                "daily_catch_limit": 800,
                "catch_throw_parameters": {
                    "excellent_rate": 0.1,
                    "great_rate": 0.4,
                    "nice_rate": 0.3,
                    "normal_rate": 0.2,
                    "spin_success_rate": 0.6,
                    "hit_rate": 0.75
                },
                "catch_simulation": {
                    "flee_count": 3,
                    "flee_duration": 2,
                    "catch_wait_min": 3,
                    "catch_wait_max": 6,
                    "berry_wait_min": 3,
                    "berry_wait_max": 5,
                    "changeball_wait_min": 3,
                    "changeball_wait_max": 5,
                    "newtodex_wait_min": 25,
                    "newtodex_wait_max": 30
                }
            }
        },
        {
            "type": "SpinFort",
            "config": {
                "enabled": true,
                "spin_wait_min": 3,
                "spin_wait_max": 5,
                "daily_spin_limit": 1900
            }
        },
        {
            "type": "UpdateWebInventory",
            "config": {
                "enabled": true
            }
        },
        {
            "type": "MoveToFort",
            "config": {
                "enabled": true,
                "lure_attraction": true,
                "lure_max_distance": 2000,
                "walker": "StepWalker",
                "log_interval": 5
            }
        },
        {
            "type": "FollowSpiral",
            "config": {
                "enabled": true,
                "diameter": 4,
                "step_size": 70
            }
        }
    ],
    "map_object_cache_time": 5,
    "forts": {
        "avoid_circles": true,
        "max_circle_size": 50,
        "cache_recent_forts": true
    },
    "pokemon_bag": {
        "// if 'show_at_start' is true, it will log all the pokemons in the bag (not eggs) at bot start": { },
        "show_at_start": true,
        "// if 'show_count' is true, it will show the amount of each pokemon (minimum 1)": { },
        "show_count": false,
        "// if 'show_candies' is true, it will show the amount of candies for each pokemon": { },
        "show_candies": false,
        "// 'pokemon_info' parameter define which info to show for each pokemon": { },
        "// the available options are": { },
        "// ['cp', 'iv_ads', 'iv_pct', 'ivcp', 'ncp', 'level', 'hp', 'moveset', 'dps']": { },
        "pokemon_info": [ "cp", "iv_pct" ]
    },
    "walk_max": 7.16,
    "walk_min": 5.16,
    "alt_min": 400,
    "alt_max": 500,
    "sleep_schedule": [
        {
            "time": "23:00",
            "duration": "5:30",
            "time_random_offset": "00:30",
            "duration_random_offset": "00:30",
            "wake_up_at_location": ""
        },
        {
            "time": "10:45",
            "duration": "3:00",
            "time_random_offset": "01:00",
            "duration_random_offset": "00:30",
            "wake_up_at_location": ""
        }
    ],
    "gps_default_altitude": 8.0,
    "replicate_gps_xy_noise": true,
    "replicate_gps_z_noise": true,
    "gps_xy_noise_range": 0.000124,
    "gps_z_noise_range": 14.3,
    "debug": false,
    "test": false,
    "walker_limit_output": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging": {
        "color": true,
        "show_datetime": true,
        "show_process_name": true,
        "show_log_level": true
    },
    "catch": {
        "any": {
            "catch_above_cp": 0,
            "catch_above_iv": 0,
            "logic": "or"
        },
        "// Example of always catching Rattata:": { },
        "// Rattata": { "always_catch": true }
    },
    "vips": {
        "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate": { },
        "any": {
            "catch_above_cp": 1200,
            "catch_above_iv": 0.9,
            "logic": "or"
        },
        "Lapras": { },
        "Moltres": { },
        "Zapdos": { },
        "Articuno": { },

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": { },
        "Mewtwo": { },
        "Dragonite": { },
        "Snorlax": { },
        "// Mew evolves to Mewtwo": { },
        "Mew": { },
        "Arcanine": { },
        "Vaporeon": { },
        "Gyarados": { },
        "Exeggutor": { },
        "Muk": { },
        "Weezing": { },
        "Flareon": { }
    }
}

**Comment by perpysling2** [comment]
is this config error?

[2016-08-30 22:44:45] [pgoapi.pgoapi] Request for new Access Token failed! Logged out...
[2016-08-30 22:44:45] [PokemonGoBot] [api_error] Log logged in, reconnecting in 900

**Comment by mjmadsen** [comment]
@perpysling2 Seems like a client to server issue.

**Comment by perpysling2** [comment]
even with this new config i get this onec again.
[2016-08-31 19:32:41] [PokemonCatchWorker] [pokemon_inventory_full] Your Pokemon inventory is full! Could not catch!

**Comment by perpysling2** [comment]
trying second config now. se if that helps. dont understand how it works

**Comment by jrjhealey** [comment]
Not really an issue, just needs optimising the config. Closing.
