### ISSUE TITLE
New kind of ban?

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#4948]
I just got this:
are we going through www.google-analytics.com website at all?

### Actual Behavior
[pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
.. [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
...,481 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
^C... PDT Pokebot  Stopped.

### Output when issue occurred [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "pokecli.py", line 768, in <module>
    main()
  File "pokecli.py", line 207, in main
    report_summary(bot)
  File "pokecli.py", line 253, in report_summary
    metrics.capture_stats()
  File "/Users/ming/Downloads/PokemonGo-Bot/pokemongo_bot/metrics.py", line 109, in capture_stats
    response_dict = request.call()
  File "/Users/ming/Downloads/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 223, in call
    if not self.can_call():
  File "/Users/ming/Downloads/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 128, in can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
[...] [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/ming/Downloads/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/ming/Downloads/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/ming/Downloads/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/ming/Downloads/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/ming/Downloads/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/ming/Downloads/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/ming/Downloads/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/ming/Downloads/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
  File "/Users/ming/Downloads/PokemonGo-Bot/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
[...] [sentry.errors.uncaught] [ERROR] [u'NotLoggedInException', u'  File "pokecli.py", line 768, in <module>', u'  File "pokecli.py", line 207, in main', u'  File "pokecli.py", line 253, in report_summary', u'  File "pokemongo_bot/metrics.py", line 109, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 223, in call', u'  File "pokemongo_bot/api_wrapper.py", line 128, in can_call']
... Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

**Comment by avexus** [comment]
well, this is really strange.
i tried to log in with another account, works. changed back to the account that caused problem, worked too.
so, i'm closing this.
