### ISSUE TITLE
[dev] crash on refresh inventory

### ISSUE THREAD

**Issue by MZorzy** [PokemonGoF/PokemonGo-Bot#4956]
### Expected Behavior
git pull , start bot, bot work

### Actual Behavior
bot don t work anymore

### Your FULL config.json 
config is ok. use config.json.example only with different altitude

### Output when issue occurred

python pokecli.py -af configs/auth.json -cf configs/config.json

2016-08-30 20:23:53,156 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-30 20:23:53,164 [       cli] [INFO] commit: 8c741500
2016-08-30 20:23:53,172 [       cli] [INFO] Configuration initialized
[2016-08-30 20:23:53] [SleepSchedule] [INFO] [next_sleep] Next sleep at 12:07:51, for a duration of 5:14:09
[2016-08-30 20:23:53] [PokemonGoBot] [INFO] [set_start_location] Setting start location.
[2016-08-30 20:23:53] [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
[2016-08-30 20:23:53] [PokemonGoBot] [INFO] [location_found] Location found: -----------------
[2016-08-30 20:23:53] [PokemonGoBot] [INFO] [position_update] Now at -----------
[2016-08-30 20:23:53] [PokemonGoBot] [INFO] [login_started] Login procedure started.
[2016-08-30 20:23:56] [PokemonGoBot] [INFO] [login_successful] Login successful.
[2016-08-30 20:23:56] [PokemonGoBot] [INFO] Found encrypt.so! Platform: linux2 encrypt.so directory: /home/dev/Poke/PokemonGo-Bot
[2016-08-30 20:23:56] [PokemonGoBot] [INFO] 
Traceback (most recent call last):
  File "pokecli.py", line 781, in <module>
    main()
  File "pokecli.py", line 217, in main
    report_summary(bot)
  File "pokecli.py", line 265, in report_summary
    metrics.capture_stats()
  File "/home/dev/Poke/PokemonGo-Bot/pokemongo_bot/metrics.py", line 117, in capture_stats
    inventory.refresh_inventory()
  File "/home/dev/Poke/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1338, in refresh_inventory
    _inventory.refresh(data)
AttributeError: 'NoneType' object has no attribute 'refresh'

### Steps to Reproduce
git pull to dev commit: 8c741500 , same on 0d2e093c
(clean /data don't solve)
run bot

### Other Information
OS: debian Branch: dev Git Commit:  8c741500

**Comment by 03t02** [comment]
Same problem here !

**Comment by drricksanchez321** [comment]
same problem. is it some kind of race condition between the metrics and init_inventory? its trying to refresh the inventory before initializing it?

**Comment by solderzzc** [comment]
Latest code should already fixed this issue, reopen if not pls.

**Comment by MZorzy** [comment]
now ok.
