### ISSUE TITLE
telegram killed in master

### ISSUE THREAD

**Issue by askovpen** [PokemonGoF/PokemonGo-Bot#4958]
@solderzzc 47e1ddd1e0a173cdade790981891a360d5cba42b kill telegram :-)
in dev new version with worked telegram

**Comment by askovpen** [comment]
```
Traceback (most recent call last):
  File "pokecli.py", line 781, in <module>
    main()
  File "pokecli.py", line 139, in main
    bot.tick()
  File "PokemonGo-Bot/pokemongo_bot/__init__.py", line 658, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "PokemonGo-Bot/pokemongo_bot/cell_workers/telegram_task.py", line 58, in work
    if not re.match(r'^[0-9]+$', "{}".format(self.config['master'])): # master was not numeric...
NameError: global name 're' is not defined
```

**Comment by solderzzc** [comment]
Nice . . .

**Comment by solderzzc** [comment]
@askovpen  Dev merged to master, the issue should be fixed.
https://github.com/PokemonGoF/PokemonGo-Bot/pull/4961
