### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'refresh'

### ISSUE THREAD

**Issue by p1n9** [PokemonGoF/PokemonGo-Bot#4989]
### Expected Behavior
Bot running

### Actual Behavior
Crash at start.

### config.json 
[http://pastebin.com/ynJEGiCy](http://pastebin.com/ynJEGiCy)

### Output when issue occurred
```
2016-08-31 09:47:32,187 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-31 09:47:32,194 [       cli] [INFO] commit: 46a32efd
2016-08-31 09:47:32,200 [       cli] [INFO] Configuration initialized
(575) wsgi starting up on http://127.0.0.1:4000
2016-08-31 09:47:32,323 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): 127.0.0.1
[2016-08-31 09:47:32] [SleepSchedule] [next_sleep] Next sleep at 22:44:02, for a duration of 9:53:10
[2016-08-31 09:47:32] [PokemonGoBot] [set_start_location] Setting start location.
[2016-08-31 09:47:32] [PokemonGoBot] [x] Coordinates found in passed in location, not geocoding.
[2016-08-31 09:47:32] [PokemonGoBot] [location_found] Location found: 48.863651, 2.327320 (48.863651, 2.32732, 8.0)
[2016-08-31 09:47:32] [PokemonGoBot] [position_update] Now at (48.863651, 2.32732, 8.0)
[2016-08-31 09:47:32] [PokemonGoBot] [login_started] Login procedure started.
[2016-08-31 09:47:33] [PokemonGoBot] [login_successful] Login successful.
[2016-08-31 09:47:33] [PokemonGoBot] Found encrypt.so! Platform: linux2 encrypt.so directory: /var/www/html/PokemonGo-Bot
[2016-08-31 09:47:33] [PokemonGoBot] 
Traceback (most recent call last):
  File "pokecli.py", line 781, in <module>
    main()
  File "pokecli.py", line 217, in main
    report_summary(bot)
  File "pokecli.py", line 265, in report_summary
    metrics.capture_stats()
  File "/var/www/html/PokemonGo-Bot/pokemongo_bot/metrics.py", line 117, in capture_stats
    inventory.refresh_inventory()
  File "/var/www/html/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1338, in refresh_inventory
    _inventory.refresh(data)
AttributeError: 'NoneType' object has no attribute 'refresh'
mercredi 31 août 2016, 09:47:33 (UTC+0200) Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
```

### Steps to Reproduce
run the bot ?!

### Other Information
OS: ubuntu 14.04
Branch: dev
Git Commit: 46a32efdf942d5ee54e0974bdb7cde9cac4842df 
Python Version: Python 2.7.6

**Comment by p1n9** [comment]
One more thing : I got this error with a google account, with a ptc it's working fine.

**Comment by p1n9** [comment]
One more thing : this error show up with a google account, when I try with ptc it's working fine.

**Comment by sohje** [comment]
git pull

**Comment by p1n9** [comment]
Ok, my bad...
I didn't saw it using setup.sh -u but git told me that I had a merge conflict, corrected it and now it works.
Thx
