### ISSUE TITLE
Error: Bot giving errors after some interval

### ISSUE THREAD

**Issue by db-coder** [PokemonGoF/PokemonGo-Bot#5004]
### Expected Behavior
Bot should run without errors

### Actual Behavior
Bot is giving an error after some intervals

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
```
{
    "websocket_server": false,
    "heartbeat_threshold": 10,
    "enable_social": false,
    "live_config_update": {
      "enabled": false,
      "tasks_only": false
    },
    "tasks": [
      {
        "type": "TelegramTask",
        "config": {
          "enabled": false,
          "master": null,
          "alert_catch": {
            "all": {"operator": "and", "cp": 1300, "iv": 0.95},
            "Snorlax": {"operator": "or", "cp": 900, "iv": 0.9}
          }
        }
      },
      {
        "//NOTE: This task MUST be placed on the top of task list": {},
        "type": "RandomAlivePause",
        "config": {
          "enabled": true,
          "min_duration": "00:00:10",
          "max_duration": "00:00:30",
          "min_interval": "01:00:00",
          "max_interval": "01:30:00"
        }
      },
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "RandomPause",
        "config": {
          "enabled": true,
          "min_duration": "00:00:10",
          "max_duration": "00:00:30",
          "min_interval": "00:10:00",
          "max_interval": "02:00:00"
        }
      },
      {
        "type": "CompleteTutorial",
        "config": {
          "enabled": false,
          "// set a name": "",
          "nickname": ""
        }
      },
      {
        "type": "CollectLevelUpReward",
        "config": {
          "collect_reward": true,
          "level_limit": -1
        }
      },
      {
        "type": "IncubateEggs",
        "config": {
          "enabled": true,
          "infinite_longer_eggs_first": false,
          "breakable_longer_eggs_first": true,
          "min_interval": 60,
         "infinite": [2,5,10],
         "breakable": [2,5,10]
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": true,
          "min_interval": 60,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "UpdateLiveInventory",
        "config": {
          "enabled": true,
          "min_interval": 120,
          "show_all_multiple_lines": false,
          "items": ["pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries"]
        }
      },
      {
        "type": "ShowBestPokemon",
        "config": {
          "enabled": true,
          "min_interval": 120,
          "amount": 15,
          "order_by": "cp",
          "info_to_show": ["cp"]
        }
      },
      {
        "type": "TransferPokemon",
        "config": {
          "enabled": true,
          "min_free_slot": 3,
          "transfer_wait_min": 3,
          "transfer_wait_max": 5
        }
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": true,
          "nickname_above_iv": 0.9,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "enabled": false,
          "evolve_list": "all",
          "donot_evolve_list": "none",
          "first_evolve_by": "cp",
          "evolve_above_cp": 500,
          "evolve_above_iv": 0.8,
          "logic": "or",
          "min_evolve_speed": 25,
          "max_evolve_speed": 30,
          "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "enabled": true,
          "min_empty_space": 5,
          "item_filter": {
            "Pokeball":       { "keep" : 60 },
            "Greatball":      { "keep" : 80 },
            "Ultraball":      { "keep" : 100 },
            "Potion":         { "keep" : 0 },
            "Super Potion":   { "keep" : 0 },
            "Hyper Potion":   { "keep" : 0 },
            "Max Potion":     { "keep" : 0 },
            "Revive":         { "keep" : 0 },
            "Max Revive":     { "keep" : 0 },
            "Razz Berry":     { "keep" : 70 }
          },
          "recycle_wait_min": 3,
          "recycle_wait_max": 5
        }
      },
      {
        "type": "CatchPokemon",
        "config": {
          "enabled": true,
          "catch_visible_pokemon": true,
          "catch_lured_pokemon": true,
          "min_ultraball_to_keep": 5,
          "berry_threshold": 0.35,
          "vip_berry_threshold": 0.9,
          "treat_unseen_as_vip": true,
          "daily_catch_limit": 800,
          "catch_throw_parameters": {
            "excellent_rate": 0.1,
            "great_rate": 0.5,
            "nice_rate": 0.3,
            "normal_rate": 0.1,
            "spin_success_rate" : 0.6,
            "hit_rate": 0.75
          },
          "catch_simulation": {
            "flee_count": 3,
            "flee_duration": 2,
            "catch_wait_min": 3,
            "catch_wait_max": 6,
            "berry_wait_min": 3,
            "berry_wait_max": 5,
            "changeball_wait_min": 3,
            "changeball_wait_max": 5,
            "newtodex_wait_min": 20, 
            "newtodex_wait_max": 30
          }
        }
      },
      {
        "type": "SpinFort",
        "config": {
          "enabled": true,
          "spin_wait_min": 3,
          "spin_wait_max": 5,
          "daily_spin_limit": 1900
        }
      },
      { "type": "UpdateWebInventory",
        "config": {
          "enabled": true
        }
      },
      {
        "type": "MoveToFort",
        "config": {
          "enabled": true,
          "lure_attraction": true,
          "lure_max_distance": 2000,
          "walker": "StepWalker",
          "log_interval": 5
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "enabled": true,
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "pokemon_bag": {
      "// if 'show_at_start' is true, it will log all the pokemons in the bag (not eggs) at bot start": {},
      "show_at_start": false,
      "// if 'show_count' is true, it will show the amount of each pokemon (minimum 1)": {},
      "show_count": false,
      "// if 'show_candies' is true, it will show the amount of candies for each pokemon": {},
      "show_candies": false,
      "// 'pokemon_info' parameter define which info to show for each pokemon": {},
      "// the available options are": {},
      "// ['cp', 'iv_ads', 'iv_pct', 'ivcp', 'ncp', 'level', 'hp', 'moveset', 'dps']": {},
      "pokemon_info": ["cp", "iv_pct"]
    },
    "walk_max": 4.16,
    "walk_min": 2.16,
    "alt_min": 500,
    "alt_max": 1000,
    "sleep_schedule": [
      {
        "time": "22:00",
        "duration": "5:30",
        "time_random_offset": "00:30",
        "duration_random_offset": "00:30",
        "wake_up_at_location": ""
      },
      {
        "time": "10:45",
        "duration": "3:00",
        "time_random_offset": "01:00",
        "duration_random_offset": "00:30",
        "wake_up_at_location": ""
      }
    ],
    "gps_default_altitude": 8.0,
    "replicate_gps_xy_noise": false,
    "replicate_gps_z_noise": false,
    "gps_xy_noise_range": 0.000125,
    "gps_z_noise_range": 12.5,
    "debug": false,
    "test": false,
    "walker_limit_output": false,
    "health_record": false,
    "location_cache": false,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging": {
      "color": true,
      "show_datetime": true,
      "show_process_name": false,
      "show_log_level": false,
      "show_thread_name": false
    },
    "catch": {
      "any": {"candy_threshold" : 1900 ,"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Keep no more than 3 best IV pokemon for every pokemon type": {},
      "// any": {"keep_best_iv": 3},
      "// Discard all pokemon in bag except 100 pokemon with best CP": {},
      "// all": {"keep_best_cp": 100},
      "// Example of custom order of static criterion": {},
      "// Zubat": {"keep_best_custom": "iv, cp, hp_max", "amount":2},
      "Pidgey": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Rattata": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Zubat": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Krabby": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Weedle": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Poliwag": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Magikarp": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Staryu": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Caterpie": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Spearow": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Clefairy": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Abra": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Psyduck": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Eevee": {"keep_best_cp": 3, "keep_best_iv": 1},
      "Voltorb": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Slowpoke": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Magnemite": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Venonat": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Pinsir": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Dratini": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Bulbasaur": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Squirtle": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Charmander": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Golbat": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Paras": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Geodude": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Nidoran M": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Nidoran F": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Sandshrew": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Oddish": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Machop": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Growlithe": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Horsea": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Ekans": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Meowth": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Bellsprout": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Rhyhorn": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Tauros": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Tangela": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Raticate": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Ponyta": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Kakuna": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Gastly": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Koffing": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Nidorina": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Nidorino": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Pidgeotto": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Dodrio": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Scyther": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Exeggcute": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Tentacool": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Cubone": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Poliwhirl": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Jigglypuff": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Goldeen": {"keep_best_cp": 2, "keep_best_iv": 1}
    },
    "vips" : {
        "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Jolteon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    },
    "websocket": {
      "start_embedded_server": true,
      "server_url": "127.0.0.1:4000"
    }
}

```
### Output when issue occurred
```
[2016-08-31 21:48:11] [moving_to_fort] Moving towards pokestop Sekhmet - 0.11km
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1267, in update_web_location_worker
    self.update_web_location()
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/pokemongo_bot/__init__.py", line 708, in update_web_location
    cells = self.find_close_cells(*location)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/pokemongo_bot/__init__.py", line 744, in find_close_cells
    response_dict = self.get_map_objects(lat, lng, timestamp, cellid)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1309, in get_map_objects
    cell_id=cellid
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 137, in function
    return request.call()
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 239, in call
    result = self._call()
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 188, in _call
    return PGoApiRequest.call(self, signature)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 236, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 125, in request
    response = self._make_rpc(endpoint, request_proto)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 113, in _make_rpc
    http_response = self._session.post(endpoint, data=request_proto_serialized, timeout=30)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/sessions.py", line 617, in send
    r.content
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/models.py", line 664, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 349, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 501, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 470, in _handle_chunk
    returned_chunk = self._fp._safe_read(self.chunk_left)
  File "/usr/lib/python2.7/httplib.py", line 702, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/green/ssl.py", line 200, in recv
    read = self.read(buflen)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/green/ssl.py", line 139, in read
    super(GreenSSLSocket, self).read, *args, **kwargs)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/green/ssl.py", line 119, in _call_trampolining
    timeout_exc=timeout_exc('timed out'))
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 162, in trampoline
    return hub.switch()
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 294, in switch
    return self.greenlet.switch()
SSLError: ('timed out',)
```

### Steps to Reproduce
Run the bot in the latest commit.

### Other Information
OS: 
Ubuntu 15.04
Branch: 
dev
Git Commit: 
a674b2681ea5eb9d942a2f5a097eca50e43704a1
Python Version: 
Python 2.4.9

**Comment by sohje** [comment]
pip install requests --upgrade ?
