### ISSUE TITLE
Problem starting bot on new install 

### ISSUE THREAD

**Issue by foster82** [PokemonGoF/PokemonGo-Bot#5011]
Hi guys, 

just done a new install and the bot wont start , this is the error i am getting.

``Traceback (most recent call last):
  File "pokecli.py", line 781, in <module>
    main()
  File "pokecli.py", line 217, in main
    report_summary(bot)
  File "pokecli.py", line 265, in report_summary
    metrics.capture_stats()
  File "/home/jonathan/Poke/h/PokemonGo-Bot/pokemongo_bot/metrics.py", line 108, in capture_stats
    response_dict = request.call()
  File "/home/jonathan/Poke/h/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 223, in call
    if not self.can_call():
  File "/home/jonathan/Poke/h/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 128, in can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
[2016-08-31 20:01:03] [sentry.errors] [ERROR] Sentry responded with an error: 'module' object has no attribute 'HTTPSHandler' (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/jonathan/Poke/h/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/jonathan/Poke/h/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/jonathan/Poke/h/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 44, in urlopen
    class ValidHTTPSHandler(urllib2.HTTPSHandler):
AttributeError: 'module' object has no attribute 'HTTPSHandler'
[2016-08-31 20:01:03] [sentry.errors.uncaught] [ERROR] [u'NotLoggedInException', u'  File "pokecli.py", line 781, in <module>', u'  File "pokecli.py", line 217, in main', u'  File "pokecli.py", line 265, in report_summary', u'  File "pokemongo_bot/metrics.py", line 108, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 223, in call', u'  File "pokemongo_bot/api_wrapper.py", line 128, in can_call']

cheers

**Comment by LUCKASSs** [comment]
try with encrypt.dll 32bit

**Comment by foster82** [comment]
i am using dabian sorry not windows, i should have said
