### ISSUE TITLE
Crash on Level Up

### ISSUE THREAD

**Issue by leadboots5** [PokemonGoF/PokemonGo-Bot#5019]
I'm gonna guess an issue with:
https://github.com/PokemonGoF/PokemonGo-Bot/pull/5016

which is also the version im on

```
Traceback (most recent call last):
  File "pokecli.py", line 781, in <module>
    main()
  File "pokecli.py", line 139, in main
    bot.tick()
  File "C:\Users\Steve\Downloads\PokemonGo-Bot\pokemongo_bot\__init__.py", line 658, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "C:\Users\Steve\Downloads\PokemonGo-Bot\pokemongo_bot\cell_workers\collect_level_up_reward.py", line 37, in work
    self._collect_level_reward()
  File "C:\Users\Steve\Downloads\PokemonGo-Bot\pokemongo_bot\cell_workers\collect_level_up_reward.py", line 70, in _collect_level_reward
    'items': ', '.join(["{}x {}".format(data[x], x) for x in data])
TypeError: list indices must be integers, not dict
```

**Comment by BreezeRo** [comment]
@rawgni

**Comment by DeXtroTip** [comment]
Maybe changing `line 70` to:
`'items': ', '.join(["{}x {}".format(x['item_count'], x['name']) for x in data])`
Might work, haven't tested yet.
