### ISSUE TITLE
<dev> Nickname Pokemon - global name 'action_delay' is not defined

### ISSUE THREAD

**Issue by deception83** [PokemonGoF/PokemonGo-Bot#5032]
### Expected Behavior

Should nickname pokemon with delays

### Actual Behavior

Error out

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

{
        "type": "NicknamePokemon",
        "config": {
          "enabled": true,
          "dont_nickname_favorite": true,
          "nickname_above_iv": 0.8,
          "nickname_template": "{name:.9s}_{iv_pct2}",
          "nickname_wait_min": 3,
          "nickname_wait_max": 5
        }
      },

### Output when issue occurred

Traceback (most recent call last):
  File "pokecli.py", line 781, in <module>
    main()
  File "pokecli.py", line 139, in main
    bot.tick()
  File "/home/ronald/PokemonGo-Bot-Dev/pokemongo_bot/__init__.py", line 658, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/ronald/PokemonGo-Bot-Dev/pokemongo_bot/cell_workers/nickname_pokemon.py", line 214, in work
    action_delay(self.nickname_wait_min, self.nickname_wait_max)
NameError: global name 'action_delay' is not defined
[2016-09-01 08:38:17] [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/ronald/PokemonGo-Bot-Dev/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/ronald/PokemonGo-Bot-Dev/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/ronald/PokemonGo-Bot-Dev/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/ronald/PokemonGo-Bot-Dev/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/ronald/PokemonGo-Bot-Dev/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/ronald/PokemonGo-Bot-Dev/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/ronald/PokemonGo-Bot-Dev/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/ronald/PokemonGo-Bot-Dev/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
  File "/home/ronald/PokemonGo-Bot-Dev/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
[2016-09-01 08:38:17] [sentry.errors.uncaught] [ERROR] [u"NameError: global name 'action_delay' is not defined", u'  File "pokecli.py", line 781, in <module>', u'  File "pokecli.py", line 139, in main', u'  File "pokemongo_bot/__init__.py", line 658, in tick', u'  File "pokemongo_bot/cell_workers/nickname_pokemon.py", line 214, in work']

### Steps to Reproduce

I ran this after commit f73455cb2cf268928c629e456d2e9123dc5ebdbc on dev

### Other Information
OS: 
 
Branch: 
 
Git Commit: 
 
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by deception83** [comment]
Seems to have resolved from this PR
https://github.com/PokemonGoF/PokemonGo-Bot/pull/5031
