### ISSUE TITLE
RuntimeError. IT's bug ?

### ISSUE THREAD

**Issue by clubza1** [PokemonGoF/PokemonGo-Bot#5043]
I got RuntimeError,But bot continue work.

It's bug ??

------------------------------------------------------------------------------

[2016-09-01 15:24:56] [UpdateLiveStats] [INFO] [log_stats] Uptime : 1:40:26 | Level 28 (220,580 / 300,000, 73%) | Earned 9,207 Stardust | +26,275 XP | 15,696 XP/h | Threw 112 pokeballs | Caught 85 pokemon | Visited 89 stops
Exception in thread Thread-9:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\site-packages\socketIO_client\heartbeats.py", line 27, in run
    self._send_heartbeat()
  File "C:\Python27\lib\site-packages\socketIO_client\__init__.py", line 211, in _ping
    engineIO_packet_type, engineIO_packet_data)
  File "C:\Python27\lib\site-packages\socketIO_client\transports.py", line 162, in send_packet
    self._connection.send(packet)
  File "C:\Python27\lib\site-packages\websocket\_core.py", line 239, in send
    return self.send_frame(frame)
  File "C:\Python27\lib\site-packages\websocket\_core.py", line 264, in send_frame
    l = self._send(data)
  File "C:\Python27\lib\site-packages\websocket\_core.py", line 425, in _send
    return send(self.sock, data)
  File "C:\Python27\lib\site-packages\websocket\_socket.py", line 112, in send
    return sock.send(data)
  File "C:\Python27\lib\site-packages\eventlet\greenio\base.py", line 379, in send
    return self._send_loop(self.fd.send, data, flags)
  File "C:\Python27\lib\site-packages\eventlet\greenio\base.py", line 374, in _send_loop
    timeout_exc=socket.timeout("timed out"))
  File "C:\Python27\lib\site-packages\eventlet\greenio\base.py", line 203, in _trampoline
    mark_as_closed=self._mark_as_closed)
  File "C:\Python27\lib\site-packages\eventlet\hubs\__init__.py", line 160, in trampoline
    listener = hub.add(hub.WRITE, fileno, current.switch, current.throw, mark_as_closed)
  File "C:\Python27\lib\site-packages\eventlet\hubs\hub.py", line 177, in add
    evtype, fileno, evtype, cb, bucket[fileno]))
RuntimeError: Second simultaneous write on fileno 1076 detected.  Unless you really know what you're doing, make sure that only one greenthread can write any particular socket.  Consider using a pools.Pool. If you do know what you're doing and want to disable this error, call eventlet.debug.hub_prevent_multiple_readers(False) - MY THREAD=<built-in method switch of greenlet.greenlet object at 0x0715E6C0>; THAT THREAD=FdListener('write', 1076, <built-in method switch of greenlet.greenlet object at 0x04FA9A30>, <built-in method throw of greenlet.greenlet object at 0x04FA9A30>)

[2016-09-01 15:25:58] [IncubateEggs] [INFO] [next_egg_incubates] Eggs incubating: [1.60/5.0 km] (Eggs left: 8, Incubating: 1)
[2016-09-01 15:26:01] [UpdateLiveStats] [INFO] [log_stats] Uptime : 1:41:31 | Level 28 (220,580 / 300,000, 73%) | Earned 9,207 Stardust | +26,275 XP | 15,530 XP/h | Threw 112 pokeballs | Caught 85 pokemon | Visited 89 stops
[2016-09-01 15:26:01] [UpdateLiveInventory] [INFO] [show_inventory] Pokemon: 73/250 | Items: 327/350

**Comment by k4n30** [comment]
Please recreate issue and follow the template so we can actually help you
