### ISSUE TITLE
When running two instances with 2 distinct accounts receive error "Address Already in use"

### ISSUE THREAD

**Issue by rsuzano** [PokemonGoF/PokemonGo-Bot#5050]
### Expected Behavior
Once the account information is present in auth.json I expected to RUN more than one BOT instance/account with the same config.json and distinct auth.json
./run.sh configs/config.json configs/authAccountONE.json
./run.sh configs/config.json configs/authAccountTWO.json

### Actual Behavior
When I run more than one bot instance/account (it's two diferent accounts), the last started instance returns error message:
error: [Errno 98] Address already in use

**I've tried disable websocket setting option "start_embedded_server": false But an Connection refused erros occurs** 

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/uamC7QWq

### Output when issue occurred
2016-09-01 09:14:19,988 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/odroid/PokemonGo-Bot/pokemongo_bot/socketio_server/runner.py", line 33, in _start_listening_blocking
    listener = eventlet.listen((self.host, self.port))
  File "/home/odroid/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/convenience.py", line 43, in listen
    sock.bind(addr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

### Steps to Reproduce
Create two auth.json with two diferent accounts and try to run 2 bot instances

### Other Information
OS: 
Ubuntu 16.04.1 LTS
Branch: 
dev
Git Commit: 
d5059ed2adb569953a3e627b4141b2275b0b1bc5
Python Version: 
Python 2.7.12

**Comment by sohje** [comment]
try to remove "websocket" scope from config file.

**Comment by rsuzano** [comment]
Now is working, tks!
