### ISSUE TITLE
Error on catch with TelegramTask enabled

### ISSUE THREAD

**Issue by rafaellincoln** [PokemonGoF/PokemonGo-Bot#5065]
File "pokecli.py", line 795, in <module>
    main()
  File "pokecli.py", line 153, in main
    bot.tick()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 662, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_pokemon.py", line 44, in work
    if self.catch_pokemon(self.pokemon.pop()) == WorkerResult.ERROR:
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_pokemon.py", line 138, in catch_pokemon
    return_value = worker.work()
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 174, in work
    self._do_catch(pokemon, encounter_id, catch_rate_by_ball, is_vip=is_vip)
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 548, in _do_catch
    'daily_catch_limit': self.daily_catch_limit
  File "/root/PokemonGo-Bot/pokemongo_bot/base_task.py", line 53, in emit_event
    data=data
  File "/root/PokemonGo-Bot/pokemongo_bot/event_manager.py", line 70, in emit
    raise EventMalformedException("Event %s does not require parameter %s" % (event, k))
pokemongo_bot.event_manager.EventMalformedException: Event pokemon_caught does not require parameter msg
[2016-09-01 19:51:10] [MainThread] [sentry.errors] [ERROR] Sentry responded with an error: 'module' object has no attribute 'HTTPSHandler' (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 44, in urlopen
    class ValidHTTPSHandler(urllib2.HTTPSHandler):
AttributeError: 'module' object has no attribute 'HTTPSHandler'
[2016-09-01 19:51:10] [MainThread] [sentry.errors.uncaught] [ERROR] [u'EventMalformedException: Event pokemon_caught does not require parameter msg', u'  File "pokecli.py", line 795, in <module>', u'  File "pokecli.py", line 153, in main', u'  File "pokemongo_bot/__init__.py", line 662, in tick', u'  File "pokemongo_bot/cell_workers/catch_pokemon.py", line 44, in work', u'  File "pokemongo_bot/cell_workers/catch_pokemon.py", line 138, in catch_pokemon', u'  File "pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 174, in work', u'  File "pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 548, in _do_catch', u'  File "pokemongo_bot/base_task.py", line 53, in emit_event', u'  File "pokemongo_bot/event_manager.py", line 70, in emit']

**Comment by k4n30** [comment]
Please use issue template. An error message on it's own can't help us indicate what the issue is
