### ISSUE TITLE
[NeedHelp] AttributeError: 'Requirement' object has no attribute 'project_name'

### ISSUE THREAD

**Issue by dominikue** [PokemonGoF/PokemonGo-Bot#507]
Can sb help me please - im using ubuntu and it workes with the master version..
How can i handle it?

_You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@dominik-ue:~# cd PokemonGo-Bot/
root@dominik-ue:~/PokemonGo-Bot# pip install -r requirements.txt
Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@1f25e907f3e5f1b60                                            3330e71041e1ad7bee7580f#egg=pgoapi (from -r requirements.txt (line 1))
  Cloning https://github.com/tejado/pgoapi.git (to 1f25e907f3e5f1b603330e71041e1                                            ad7bee7580f) to ./src/pgoapi
  Could not find a tag or branch '1f25e907f3e5f1b603330e71041e1ad7bee7580f', ass                                            uming commit.
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in /usr/                                            local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 328, in                                             run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepa                                            re_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 448, in _prep                                            are_file
    req_to_install, finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 387, in _chec                                            k_skip_installed
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1011, in                                             check_if_exists
    self.req.project_name
AttributeError: 'Requirement' object has no attribute 'project_name'
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@dominik-ue:~/PokemonGo-Bot# python pokecli.py -a ptc -u catchthemall2fun -p 123412 --location "Darmstadt, Herrngarten" -m all --cp 10 -iv 0.9
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pokemongo_bot import logger
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 10, in <module>
    import yaml
ImportError: No module named yaml
root@dominik-ue:~/PokemonGo-Bot#_

**Comment by s1x** [comment]
Please check if you have yaml installed.

**Comment by dominikue** [comment]
It is installed now, but i did not work.. I get an "ImportError: No module named pgoapi" and i cannt install the -r requirements.txt correctly. I think the reason is the pgoapi - can i install it manually?

root@dominik-ue:~/PokemonGo-Bot# pip install -r requirements.txt                                                            Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@1f25e907f3e5f1b603330e71041e1ad7bee7580f#egg=pgoapi (from -r requirements.txt (line 1))
  git clone in ./src/pgoapi exists with URL git://github.com/tejado/pgoapi.git
  The plan is to install the git repository https://github.com/tejado/pgoapi.git
What to do?  (s)witch, (i)gnore, (w)ipe, (b)ackup s
  Switching clone ./src/pgoapi to https://github.com/tejado/pgoapi.git (to 1f25e907f3e5f1b603330e71041e1ad7bee7580f)
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 328, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 448, in _prepare_file
    req_to_install, finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 387, in _check_skip_installed
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1011, in check_if_exists
    self.req.project_name
AttributeError: 'Requirement' object has no attribute 'project_name'
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@dominik-ue:~/PokemonGo-Bot#

**Comment by dominikue** [comment]
Idk why, but 'pip install --upgrade pip' fixed it for me.. still ty
