### ISSUE TITLE
[Errno 32] Broken pipe

### ISSUE THREAD

**Issue by jane0815** [PokemonGoF/PokemonGo-Bot#5070]
### Expected Behavior

Bot running without errors.

### Actual Behavior

Bot seem to be running fine but after some time i get [Errno 32] Broken pipe

### Your FULL config.json

Tryed latest map config file still same error.

### Output when issue occurred

random lines with the error message:

[2016-09-02 00:47:00] [MainThread] [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Gyarados appeared! [CP 1438] [NCP 0.54] [Potential 0.87] [A/D/S 15/11/13]
[2016-09-02 00:47:03] [MainThread] [PokemonCatchWorker] [INFO] [vip_pokemon] This is a VIP pokemon. Catch!!!
[2016-09-02 00:47:06] [MainThread] [PokemonCatchWorker] [INFO] [threw_berry] Threw a Razz Berry! Catch rate with Pokeball is now: 10.30
[2016-09-02 00:47:11] [MainThread] [PokemonCatchWorker] [INFO] [threw_pokeball] Great Curveball throw! Used Ultraball, with chance 19.90 (6 left)
[2016-09-02 00:47:12] [MainThread] [PokemonCatchWorker] [INFO] [pokemon_capture_failed] Gyarados capture failed.. trying again!
[Errno 32] Broken pipe
[Errno 32] Broken pipe
[Errno 32] Broken pipe
[2016-09-02 00:47:25] [MainThread] [PokemonCatchWorker] [INFO] [threw_pokeball] Great Curveball throw! Used Ultraball, with chance 13.27 (5 left)
[2016-09-02 00:47:25] [MainThread] [PokemonCatchWorker] [INFO] [pokemon_capture_failed] Gyarados capture failed.. trying again!
[2016-09-02 00:47:36] [MainThread] [PokemonCatchWorker] [INFO] [threw_pokeball] Great throw! Used Ultraball, with chance 13.27 (4 left)
[2016-09-02 00:47:37] [MainThread] [PokemonCatchWorker] [INFO] [pokemon_capture_failed] Gyarados capture failed.. trying again!
[2016-09-02 00:47:46] [MainThread] [PokemonCatchWorker] [INFO] [threw_pokeball] Nice Curveball throw! Used Ultraball, with chance 13.27 (3 left)
[2016-09-02 00:47:46] [MainThread] [PokemonCatchWorker] [INFO] [pokemon_caught] Captured Gyarados! [CP 1438] [NCP 0.54] [Potential 0.87] [15/11/13] (258/800) [+120 exp]
[2016-09-02 00:47:46] [MainThread] [PokemonCatchWorker] [INFO] [gained_candy] You now have 602 Magikarp candy!

### Steps to Reproduce

Run bot for some time with movetomap and social enabled.

### Other Information
OS: Mac OSX
Branch: 7f53d653
Git Commit: dev

**Comment by mitcht** [comment]
I can confirm, I am seeing the same behavior in dev and master. I've done a fresh clone, as well as submodule update.  I've been using the bot since the early days so i've done it manually, as well as using . setup -r.  I'm 100% confident the bot is set up correctly

Python 2.7.9

CONFIG.JSON -> [http://mediaengine.org/PokemonGo-Bot/web/config.json](url)

Error info:
`[Errno 32] Broken pipe
127.0.0.1 - - [02/Sep/2016 13:36:15] code 400, message Bad request syntax ('\x81\xfe\x03\xbfc\xc70\xbdW\xf5k\x9f\x01\xa8D\x87\x01\xb5_\xdc\x07\xa4Q\xce\x17\xe5\x1c\x9d\x18\xe5Q\xde\x00\xa8E\xd3\x17\xe5')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenpool.py", line 82, in _spawn_n_impl
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/wsgi.py", line 719, in process_request
    proto.__init__(sock, address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 342, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/wsgi.py", line 351, in handle_one_request
    if not self.parse_request():
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 286, in parse_request
    self.send_error(400, "Bad request syntax (%r)" % requestline)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 458, in log_message
    format%args))
  File "/usr/lib/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x81 in position 38: invalid start byte


The bot continues to run, but does no work. It continues to do this until stopped and restarted, which at that point it is alright again.`

**Comment by foster82** [comment]
I am getting this also. With default configuration file. This is on rasbian.

**Comment by avexus** [comment]
@mitcht what does FollowCluster exactly?

**Comment by foster82** [comment]
I am still having this problem

**Comment by foster82** [comment]
This is the error I am getting ..

[Errno 32] Broken pipe
[Errno 104] Connection reset by peer

Any ideas?

**Comment by thedruid** [comment]
Same problem here, also running on raspian.

**Comment by prusswan** [comment]
@mitcht I don't have errorno 32, but "[Errno 104] Connection reset by peer", the rest of the error message is very similar to yours: https://github.com/PokemonGoF/PokemonGo-Bot/issues/4718#issuecomment-244913275

Bot is able to run but I wonder what is causing these errors

**Comment by foster82** [comment]
After the error occurs sometime the bot will freeze or just walk
