### ISSUE TITLE
Bot crashes on startup since latest pull

### ISSUE THREAD

**Issue by jannickv** [PokemonGoF/PokemonGo-Bot#5113]
I just pulled latest changes, but bot won't start anymore.

```
Traceback (most recent call last):
  File "pokecli.py", line 795, in <module>
    main()
  File "pokecli.py", line 142, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 102, in start_bot
    initialize_task(bot, config)
  File "pokecli.py", line 93, in initialize_task
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "/Users/jannickvandaele/Sites/prive/bots/a/pokemongo_bot/tree_config_builder.py", line 79, in build
    instance = worker(self.bot, task_config)
  File "/Users/jannickvandaele/Sites/prive/bots/a/pokemongo_bot/base_task.py", line 23, in __init__
    self.initialize()
  File "/Users/jannickvandaele/Sites/prive/bots/a/pokemongo_bot/cell_workers/follow_spiral.py", line 23, in initialize
    self.points = cycle(self.spiral+list(reversed(self.spiral)[1:-1]))
TypeError: 'listreverseiterator' object has no attribute '__getitem__'

```

**Comment by jannickv** [comment]
Error disapears when removing "followspiral" task from config

**Comment by PokemonGoZ** [comment]
Update your current config with the current config.json.example. The one you have is outdated.

**Comment by jannickv** [comment]
nothing changed to the follow spiral config for days

**Comment by tiagoAnon** [comment]
+1, removing Follow Spiral task also fixed the problem

**Comment by jannickv** [comment]
@PokemonGoZ thanks for closing a perfectly legit issue... #5124

**Comment by AlessandroMinoccheri** [comment]
I have removed Follow Spiral task but the problem persist! 
Help me!

**Comment by sohje** [comment]
@AlessandroMinoccheri git pull and restart

**Comment by AlessandroMinoccheri** [comment]
I have already done:
 git pull origin master
./run.sh

But on my OSX I get the error :(

**Comment by sohje** [comment]
git branch -vvv ?

**Comment by AlessandroMinoccheri** [comment]
`* master ca94424 [origin/master] To add gmap in polyline walker. (#5137)`

**Comment by sohje** [comment]
Try to checkout dev version and start bot again, not sure if master was merged.

**Comment by AlessandroMinoccheri** [comment]
I have checkout dev but again the error:

[2016-09-03 21:59:30] [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "pokecli.py", line 802, in <module>
    main()
  File "pokecli.py", line 238, in main
    report_summary(bot)
  File "pokecli.py", line 286, in report_summary
    metrics.capture_stats()
  File "/Users/alessandrominoccheri/Sites/PokemonGo-Bot/pokemongo_bot/metrics.py", line 108, in capture_stats
    response_dict = request.call()
  File "/Users/alessandrominoccheri/Sites/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 221, in call
    if not self.can_call():
  File "/Users/alessandrominoccheri/Sites/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 126, in can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
[2016-09-03 21:59:30] [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/alessandrominoccheri/Sites/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/alessandrominoccheri/Sites/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/alessandrominoccheri/Sites/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/alessandrominoccheri/Sites/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/alessandrominoccheri/Sites/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/alessandrominoccheri/Sites/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/alessandrominoccheri/Sites/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/alessandrominoccheri/Sites/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 848, in _send_output
    msg += message_body
  File "/Users/alessandrominoccheri/Sites/PokemonGo-Bot/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
[2016-09-03 21:59:30] [sentry.errors.uncaught] [ERROR] [u'NotLoggedInException', u'  File "pokecli.py", line 802, in <module>', u'  File "pokecli.py", line 238, in main', u'  File "pokecli.py", line 286, in report_summary', u'  File "pokemongo_bot/metrics.py", line 108, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 221, in call', u'  File "pokemongo_bot/api_wrapper.py", line 126, in can_call']
Sab 3 Set 2016 21:59:30 CEST Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
  2016-09-03 21:59:34,638 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-03 21:59:34,651 [       cli] [INFO] commit: d67de1a5
2016-09-03 21:59:34,657 [       cli] [INFO] Configuration initialized
2016-09-03 21:59:34,657 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-09-03 21:59:34,657 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-09-03 21:59:34,670 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
(12230) wsgi starting up on http://127.0.0.1:4000
2016-09-03 21:59:34,771 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): 127.0.0.1
[2016-09-03 21:59:34] [SleepSchedule] [INFO] [next_sleep] Next sleep at 12:13:55, for a duration of 5:31:28
^C[2016-09-03 21:59:34] [PokemonGoBot] [INFO] [bot_interrupted] Bot caught SIGINT. Shutting down.
[2016-09-03 21:59:34] [       cli] [INFO] 
[2016-09-03 21:59:34] [       cli] [INFO] Ran for 0:00:00
[2016-09-03 21:59:34] [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
[2016-09-03 21:59:34] [       cli] [INFO] Travelled 0.00km
[2016-09-03 21:59:34] [       cli] [INFO] Visited 0 stops
[2016-09-03 21:59:34] [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
[2016-09-03 21:59:34] [       cli] [INFO] Threw 0 pokeballs
[2016-09-03 21:59:34] [       cli] [INFO] Earned 0 Stardust
[2016-09-03 21:59:34] [       cli] [INFO] Hatched eggs 0
[2016-09-03 21:59:34] [       cli] [INFO] 
[2016-09-03 21:59:34] [       cli] [INFO] Highest CP Pokemon: 
[2016-09-03 21:59:34] [       cli] [INFO] Most Perfect Pokemon: 
Sab 3 Set 2016 21:59:34 CEST Pokebot  Stopped.

**Comment by sohje** [comment]
try to run 
```shell
python pokecli.py -af path_to_auth.json -cf path_to_config.json
```

**Comment by AlessandroMinoccheri** [comment]
Traceback (most recent call last):
  File "pokecli.py", line 42, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException, NoPlayerPositionSetException
ImportError: No module named pgoapi.exceptions

**Comment by sohje** [comment]
```shell
virtualenv .
source bin/activate
pip install -r requirements.txt
python pokecli.py -af path_to_auth.json -cf path_to_config.json
```

**Comment by AlessandroMinoccheri** [comment]
I get the error as i run ./run.sh 
:(

**Comment by sohje** [comment]
Did you tried command i posted above?

**Comment by AlessandroMinoccheri** [comment]
Yes all codes

**Comment by AlessandroMinoccheri** [comment]
now If I run again 
virtualenv .

I get:
Please use the *system* python to run this script
Traceback (most recent call last):
  File "/Users/alessandrominoccheri/Sites/PokemonGo-Bot/bin/virtualenv", line 11, in <module>
    load_entry_point('virtualenv==15.0.3', 'console_scripts', 'virtualenv')()
  File "/Users/alessandrominoccheri/Sites/PokemonGo-Bot/lib/python2.7/site-packages/virtualenv-15.0.3-py2.7.egg/virtualenv.py", line 711, in main
    symlink=options.symlink)
  File "/Users/alessandrominoccheri/Sites/PokemonGo-Bot/lib/python2.7/site-packages/virtualenv-15.0.3-py2.7.egg/virtualenv.py", line 924, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Users/alessandrominoccheri/Sites/PokemonGo-Bot/bin/../lib/python2.7/posixpath.py", line 367, in abspath
    if not isabs(path):
  File "/Users/alessandrominoccheri/Sites/PokemonGo-Bot/bin/../lib/python2.7/posixpath.py", line 61, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by sohje** [comment]
Last error looks like python issue. Try to upgrade system level virtualenv module.

**Comment by AlessandroMinoccheri** [comment]
ok how can I upgrade?

**Comment by sohje** [comment]
hmm, can you repeat commands above w/o _virtualenv ._

**Comment by AlessandroMinoccheri** [comment]
without virtualenv . I get the error as  i run ./run.sh

**Comment by sohje** [comment]
show your config file and auth file without credentials.

**Comment by AlessandroMinoccheri** [comment]
AUTH (password and api key removed)
{
    "auth_service": "google",
    "username": "alessandro.minoccheri@gmail.com",
    "password": "MYPASSWORD",
    "location": "Ravenna",
    "favorite_locations":[
        {"name": "Ravenna", "coords": "44.4123367,12.1654898"}
    ],
    "gmapkey": "MYGOOGLEAPYKEY",
    "encrypt_location": "",
    "telegram_token": ""
}

CONFIG:
{
    "websocket_server": false,
    "heartbeat_threshold": 10,
    "enable_social": true,
    "live_config_update": {
      "enabled": false,
      "tasks_only": false
    },
    "tasks": [
      {
        "type": "TelegramTask",
        "config": {
          "enabled": false,
          "master": null,
          "// old syntax, still supported: alert_catch": ["all"],
          "// new syntax:": {},
          "alert_catch": {
            "all": {"operator": "and", "cp": 1300, "iv": 0.95},
            "Snorlax": {"operator": "or", "cp": 900, "iv": 0.9}
          }
        }
      },
      {
        "//NOTE: This task MUST be placed on the top of task list": {},
        "type": "RandomAlivePause",
        "config": {
          "enabled": false,
          "min_duration": "00:00:10",
          "max_duration": "00:10:00",
          "min_interval": "00:05:00",
          "max_interval": "01:30:00"
        }
      },
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "RandomPause",
        "config": {
          "enabled": false,
          "min_duration": "00:00:10",
          "max_duration": "00:10:00",
          "min_interval": "00:10:00",
          "max_interval": "02:00:00"
        }
      },
      {
        "type": "CompleteTutorial",
        "config": {
          "enabled": false,
          "// set a name": "",
          "nickname": "",
          "// 0 = No Team, 1 = Blue, 2 = Red, 3 = Yellow": "",
          "team": 0
        }
      },
      {
        "type": "CollectLevelUpReward",
        "config": {
          "collect_reward": true,
          "level_limit": -1
        }
      },
      {
        "type": "IncubateEggs",
        "config": {
          "enabled": true,
          "infinite_longer_eggs_first": false,
          "breakable_longer_eggs_first": true,
          "min_interval": 120,
         "infinite": [2,5,10],
         "breakable": [2,5,10]
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "UpdateLiveInventory",
        "config": {
          "enabled": false,
          "min_interval": 120,
          "show_all_multiple_lines": false,
          "items": ["pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries", "luckyegg"]
        }
      },
      {
        "type": "ShowBestPokemon",
        "config": {
          "enabled": true,
          "min_interval": 60,
          "amount": 5,
          "order_by": "cp",
          "info_to_show": ["cp", "ivcp", "dps", "hp"]
        }
      },
      {
        "type": "TransferPokemon",
        "config": {
          "enabled": true,
          "min_free_slot": 5,
          "transfer_wait_min": 3,
          "transfer_wait_max": 5
        }
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_above_iv": 0.9,
          "nickname_template": "{iv_pct}_{iv_ads}",
          "nickname_wait_min": 3,
          "nickname_wait_max": 5
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "enabled": false,
            
            "// evolve only pidgey and drowzee": "",
            "// evolve_list": "pidgey, drowzee",
            "// donot_evolve_list": "none",
            
            "// evolve all but pidgey and drowzee": "",
            "// evolve_list": "all",
            "// donot_evolve_list": "pidgey, drowzee",
            
            "evolve_list": "all",
            "donot_evolve_list": "none",
            
          "first_evolve_by": "cp",
          "evolve_above_cp": 500,
          "evolve_above_iv": 0.8,
          "logic": "or",
          "min_evolve_speed": 25,
          "max_evolve_speed": 30,
          "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "enabled": true,
          "min_empty_space": 15,
          "max_balls_keep": 150,
          "max_potions_keep": 50,
          "max_berries_keep": 70,
          "max_revives_keep": 70,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          },
          "recycle_wait_min": 3,
          "recycle_wait_max": 5,
          "recycle_force": true,
          "recycle_force_min": "00:01:00",
          "recycle_force_max": "00:05:00"
        }
      },
      {
        "type": "CatchPokemon",
        "config": {
          "enabled": true,
          "catch_visible_pokemon": true,
          "catch_lured_pokemon": true,
          "min_ultraball_to_keep": 5,
          "berry_threshold": 0.35,
          "vip_berry_threshold": 0.9,
          "treat_unseen_as_vip": true,
          "daily_catch_limit": 800,
          "catch_throw_parameters": {
            "excellent_rate": 0.1,
            "great_rate": 0.5,
            "nice_rate": 0.3,
            "normal_rate": 0.1,
            "spin_success_rate" : 0.6,
            "hit_rate": 0.75
          },
          "catch_simulation": {
            "flee_count": 3,
            "flee_duration": 2,
            "catch_wait_min": 3,
            "catch_wait_max": 6,
            "berry_wait_min": 3,
            "berry_wait_max": 5,
            "changeball_wait_min": 3,
            "changeball_wait_max": 5,
            "newtodex_wait_min": 20, 
            "newtodex_wait_max": 30
          }
        }
      },
      {
        "type": "SpinFort",
        "config": {
          "enabled": true,
          "spin_wait_min": 3,
          "spin_wait_max": 5,
          "daily_spin_limit": 1900
        }
      },
      { "type": "UpdateWebInventory",
        "config": {
          "enabled": true
        }
      },
      {
        "type": "MoveToFort",
        "config": {
          "enabled": true,
          "lure_attraction": true,
          "lure_max_distance": 2000,
          "walker": "StepWalker",
          "log_interval": 5
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "enabled": true,
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "pokemon_bag": {
      "// if 'show_at_start' is true, it will log all the pokemons in the bag (not eggs) at bot start": {},
      "show_at_start": true,
      "// if 'show_count' is true, it will show the amount of each pokemon (minimum 1)": {},
      "show_count": false,
      "// if 'show_candies' is true, it will show the amount of candies for each pokemon": {},
      "show_candies": false,
      "// 'pokemon_info' parameter define which info to show for each pokemon": {},
      "// the available options are": {},
      "// ['cp', 'iv_ads', 'iv_pct', 'ivcp', 'ncp', 'level', 'hp', 'moveset', 'dps']": {},
      "pokemon_info": ["cp", "iv_pct"]
    },
    "walk_max": 4.16,
    "walk_min": 2.16,
    "alt_min": 500,
    "alt_max": 1000,
    "sleep_schedule": [
      {
        "time": "12:00",
        "duration": "5:30",
        "time_random_offset": "00:30",
        "duration_random_offset": "00:30",
        "wake_up_at_location": ""
      },
      {
        "time": "17:45",
        "duration": "3:00",
        "time_random_offset": "01:00",
        "duration_random_offset": "00:30",
        "wake_up_at_location": ""
      }
    ],
    "gps_default_altitude": 8.0,
    "replicate_gps_xy_noise": false,
    "replicate_gps_z_noise": false,
    "gps_xy_noise_range": 0.000125,
    "gps_z_noise_range": 12.5,
    "debug": false,
    "test": false,
    "walker_limit_output": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging": {
      "color": true,
      "show_datetime": true,
      "show_process_name": true,
      "show_log_level": true,
      "show_thread_name": false
    },
    "catch": {
      "any": {"candy_threshold" : 400 ,"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Keep no more than 3 best IV pokemon for every pokemon type": {},
      "// any": {"keep_best_iv": 3},
      "// Discard all pokemon in bag except 100 pokemon with best CP": {},
      "// all": {"keep_best_cp": 100},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3},
      "// Example of custom order of static criterion": {},
      "// Zubat": {"keep_best_custom": "iv, cp, hp_max", "amount":2}
    },
    "vips" : {
        "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    },
  "websocket": {
    "start_embedded_server": true,
    "server_url": "127.0.0.1:4000"
  }
}

**Comment by sohje** [comment]
```shell
python -c 'import pgoapi; print pgoapi.__version__'
```

**Comment by AlessandroMinoccheri** [comment]
1.1.7

**Comment by sohje** [comment]
I'm out of ideas. Still 'NotLoggedInException' on start?

**Comment by AlessandroMinoccheri** [comment]
Same error as i posted when I run  ./run.sh :((((

**Comment by sohje** [comment]
Did you enable two-factor auth on google account? Anyway try to register PTC account and try. Will see if you can login via ptc, mb

**Comment by AlessandroMinoccheri** [comment]
with PTC it works seems!
