### ISSUE TITLE
My bot starts but after login, it tell me that and restart.

### ISSUE THREAD

**Issue by Cephis** [PokemonGoF/PokemonGo-Bot#5118]
My bot starts but after login, it tell me that and restart.

Traceback (most recent call last):
  File "pokecli.py", line 795, in <module>
    main()
  File "pokecli.py", line 142, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 102, in start_bot
    initialize_task(bot, config)
  File "pokecli.py", line 93, in initialize_task
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "/home/cephis/PokemonGo-Bot/pokemongo_bot/tree_config_builder.py", line 79, in build
    instance = worker(self.bot, task_config)
  File "/home/cephis/PokemonGo-Bot/pokemongo_bot/base_task.py", line 23, in __init__
    self.initialize()
  File "/home/cephis/PokemonGo-Bot/pokemongo_bot/cell_workers/follow_spiral.py", line 23, in initialize
    self.points = cycle(self.spiral+list(reversed(self.spiral)[1:-1]))
TypeError: 'listreverseiterator' object has no attribute '__getitem__'
[2016-09-02 23:37:21] [sentry.errors] [ERROR] Sentry responded with an error: 'module' object has no attribute 'HTTPSHandler' (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/cephis/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/cephis/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/cephis/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 44, in urlopen
    class ValidHTTPSHandler(urllib2.HTTPSHandler):
AttributeError: 'module' object has no attribute 'HTTPSHandler'
[2016-09-02 23:37:21] [sentry.errors.uncaught] [ERROR] [u"TypeError: 'listreverseiterator' object has no attribute '__getitem__'", u'  File "pokecli.py", line 795, in <module>', u'  File "pokecli.py", line 142, in main', u'  File "pokecli.py", line 102, in start_bot', u'  File "pokecli.py", line 93, in initialize_task', u'  File "pokemongo_bot/tree_config_builder.py", line 79, in build', u'  File "pokemongo_bot/base_task.py", line 23, in __init__', u'  File "pokemongo_bot/cell_workers/follow_spiral.py", line 23, in initialize']
vendredi 2 septembre 2016, 23:37:21 (UTC+0200) Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

### Other Information
OS: xubuntu

Branch: 
dev 

Python 2.7.6

**Comment by sohje** [comment]
Checkout previous commits
