### ISSUE TITLE
walking to pokestop error [dev]

### ISSUE THREAD

**Issue by tonz134** [PokemonGoF/PokemonGo-Bot#512]
i got this error after done spinning and walking.
so i have to use -m poke to farm pokemon only to fix the problem :(

```
Traceback (most recent call last):
  File "pokecli.py", line 132, in <module>
    main()
  File "pokecli.py", line 123, in main
    bot.take_step()
  File "c:\pokebot2\pokemongo_bot\__init__.py", line 35, in take_step
    self.stepper.take_step()
  File "c:\pokebot2\pokemongo_bot\stepper.py", line 61, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "c:\pokebot2\pokemongo_bot\stepper.py", line 134, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "c:\pokebot2\pokemongo_bot\__init__.py", line 120, in work_on_cell
    hack_chain = worker.work()
  File "c:\pokebot2\pokemongo_bot\cell_workers\seen_fort_worker.py", line 98, in work
    if str(item_id) in self.config.item_filter:
AttributeError: 'Namespace' object has no attribute 'item_filter
```

**Comment by surfaace** [comment]
Please update with git commit version if issue persists

Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by tonz134** [comment]
fixed using latest DEV version.

**Comment by johnw424** [comment]
I am seeing the same issue when I spin at a Pokestop with this config (it has item_filter rules for every single item in the game):

```
"item_filter": {
      "1": { "keep" : 500 },
      "2": { "keep" : 500 },
      "3": { "keep" : 500 },
      "4": { "keep" : 500 },
      "101": { "keep" : 0 },
      "102": { "keep" : 0 },
      "103": { "keep" : 0 },
      "104": { "keep" : 500 },
      "201": { "keep" : 0 },
      "202": { "keep" : 500 },
      "301": { "keep" : 500 },
      "401": { "keep" : 500 },
      "402": { "keep" : 500 },
      "403": { "keep" : 500 },
      "404": { "keep" : 500 },
      "501": { "keep" : 500 },
      "602": { "keep" : 500 },
      "603": { "keep" : 500 },
      "604": { "keep" : 500 },
      "701": { "keep" : 500 },
      "702": { "keep" : 500 },
      "703": { "keep" : 500 },
      "704": { "keep" : 500 },
      "705": { "keep" : 500 },
      "801": { "keep" : 500 },
      "901": { "keep" : 500 },
      "902": { "keep" : 500 },
      "1001": { "keep" : 500 },
      "1002": { "keep" : 500 }
    }
```

**Comment by MonsieurClavet** [comment]
`Traceback (most recent call last):
  File "pokecli.py", line 239, in <module>
    main()
  File "pokecli.py", line 230, in main
    bot.take_step()
  File "/home/debiANUSer/Desktop/PokemonGo-Apps/dev-pokemonBot/pokemongo_bot/__init__.py", line 43, in take_step
    self.process_cells(work_on_forts=True)
  File "/home/debiANUSer/Desktop/PokemonGo-Apps/dev-pokemonBot/pokemongo_bot/__init__.py", line 49, in process_cells
    self.work_on_cell(cell, location, work_on_forts)
  File "/home/debiANUSer/Desktop/PokemonGo-Apps/dev-pokemonBot/pokemongo_bot/__init__.py", line 225, in work_on_cell
    hack_chain = worker.work()
  File "/home/debiANUSer/Desktop/PokemonGo-Apps/dev-pokemonBot/pokemongo_bot/cell_workers/seen_fort_worker.py", line 76, in work
    id_filter = self.config.item_filter.get(str(item_id), 0)
AttributeError: 'Namespace' object has no attribute 'item_filter'
`
`ae855844b0eafa2a973f5771448ff17cba056937`

Both mode (farm|all)

**Comment by MonsieurClavet** [comment]
`Traceback (most recent call last):
  File "pokecli.py", line 239, in <module>
    main()
  File "pokecli.py", line 230, in main
    bot.take_step()
  File "/home/mrclavet/Desktop/PokemonGo-Apps/dev-pokemonBot/pokemongo_bot/__init__.py", line 43, in take_step
    self.process_cells(work_on_forts=True)
  File "/home/mrclavet/Desktop/PokemonGo-Apps/dev-pokemonBot/pokemongo_bot/__init__.py", line 49, in process_cells
    self.work_on_cell(cell, location, work_on_forts)
  File "/home/mrclavet/Desktop/PokemonGo-Apps/dev-pokemonBot/pokemongo_bot/__init__.py", line 225, in work_on_cell
    hack_chain = worker.work()
  File "/home/mrclavet/Desktop/PokemonGo-Apps/dev-pokemonBot/pokemongo_bot/cell_workers/seen_fort_worker.py", line 76, in work
    id_filter = self.config.item_filter.get(str(item_id), 0)
AttributeError: 'Namespace' object has no attribute 'item_filter'
 `

**Comment by DayBr3ak** [comment]
Commit Where i'm getting this error 2a75ad252c627755fa5759ce4a7b663075526f16
The error : http://prntscr.com/bxxqsc

**Comment by surfaace** [comment]
it was a bug, but it has been fixed in dev
