### ISSUE TITLE
RESOLVED - config missing `any`

### ISSUE THREAD

**Issue by doctor-ew** [PokemonGoF/PokemonGo-Bot#514]
[x] Captured Nidoran F! [CP 308] [IV 0.56] - exchanging for candy
Traceback (most recent call last):
  File "pokecli.py", line 187, in <module>
    main()
  File "pokecli.py", line 178, in main
    bot.take_step()
  File "/Users/Sites/shuttlebay/POKEMON/PokemonGo-Bot/pokemongo_bot/__init__.py", line 35, in take_step
    self.stepper.take_step()
  File "/Users/Sites/shuttlebay/POKEMON/PokemonGo-Bot/pokemongo_bot/stepper.py", line 61, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/Users/Sites/shuttlebay/POKEMON/PokemonGo-Bot/pokemongo_bot/stepper.py", line 134, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/Users/Sites/shuttlebay/POKEMON/PokemonGo-Bot/pokemongo_bot/__init__.py", line 120, in work_on_cell
    hack_chain = worker.work()
  File "/Users/Sites/shuttlebay/POKEMON/PokemonGo-Bot/pokemongo_bot/cell_workers/seen_fort_worker.py", line 40, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "/Users/Sites/shuttlebay/POKEMON/PokemonGo-Bot/pokemongo_bot/stepper.py", line 87, in _walk_to
    alt, False)
  File "/Users/Sites/shuttlebay/POKEMON/PokemonGo-Bot/pokemongo_bot/stepper.py", line 134, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/Users/Sites/shuttlebay/POKEMON/PokemonGo-Bot/pokemongo_bot/__init__.py", line 90, in work_on_cell
    if worker.work() == -1:
  File "/Users/Sites/shuttlebay/POKEMON/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 135, in work
    if self.should_release_pokemon(pokemon_name, cp, pokemon_potential, response_dict):
  File "/Users/Sites/shuttlebay/POKEMON/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 213, in should_release_pokemon
    release_config = self._get_release_config_for(pokemon_name)
  File "/Users/Sites/shuttlebay/POKEMON/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 255, in _get_release_config_for
    release_config = self.config.release_config['any']
KeyError: 'any'

### Other Information
OS: osx yosemite
Git Commit: 631b0435d46b77788ad11acb58b810c777f10c60

**Comment by DavidK1m** [comment]
rename release_config.json.example to release_config.json

**Comment by doctor-ew** [comment]
Yep -- did that. Even attempted adding an any object

**Comment by DavidK1m** [comment]
where did you put release_config.json file?

**Comment by doctor-ew** [comment]
1D10T error... I forgot about release_config and was only looking at config.

Thanks for your eyeballs!!
