### ISSUE TITLE
error during bot's search, just after he stops for a pause and after he starts again

### ISSUE THREAD

**Issue by Cephis** [PokemonGoF/PokemonGo-Bot#5143]
[2016-09-03 12:01:57] [RandomAlivePause] [INFO] [bot_random_alive_pause] Taking a random break keeping bot alive for 00:08:21, will resume at 12:10:19
[Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/cephis/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/wsgi.py", line 512, in handle_one_response
    write(b''.join(towrite))
  File "/home/cephis/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/wsgi.py", line 453, in write
    wfile.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  File "/home/cephis/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 385, in sendall
    tail = self.send(data, flags)
  File "/home/cephis/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 379, in send
    return self._send_loop(self.fd.send, data, flags)
  File "/home/cephis/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 374, in _send_loop
    timeout_exc=socket.timeout("timed out"))
  File "/home/cephis/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 203, in _trampoline
    mark_as_closed=self._mark_as_closed)
  File "/home/cephis/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 160, in trampoline
    listener = hub.add(hub.WRITE, fileno, current.switch, current.throw, mark_as_closed)
  File "/home/cephis/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/hubs/epolls.py", line 49, in add
    listener = BaseHub.add(self, evtype, fileno, cb, tb, mac)
  File "/home/cephis/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 177, in add
    evtype, fileno, evtype, cb, bucket[fileno]))
RuntimeError: Second simultaneous write on fileno 10 detected.  Unless you really know what you're doing, make sure that only one greenthread can write any particular socket.  Consider using a pools.Pool. If you do know what you're doing and want to disable this error, call eventlet.debug.hub_prevent_multiple_readers(False) - MY THREAD=<built-in method switch of greenlet.greenlet object at 0x7fb35b6ac910>; THAT THREAD=FdListener('write', 10, <built-in method switch of greenlet.greenlet object at 0x7fb35b6ac7d0>, <built-in method throw of greenlet.greenlet object at 0x7fb35b6ac7d0>)

Traceback (most recent call last):
  File "/home/cephis/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/greenpool.py", line 82, in _spawn_n_impl
    func(*args, **kwargs)
  File "/home/cephis/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/wsgi.py", line 719, in process_request
    proto.__init__(sock, address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/home/cephis/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/wsgi.py", line 631, in finish
    BaseHTTPServer.BaseHTTPRequestHandler.finish(self)
  File "/usr/lib/python2.7/SocketServer.py", line 705, in finish
    self.wfile.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  File "/home/cephis/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 385, in sendall
    tail = self.send(data, flags)
  File "/home/cephis/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 379, in send
    return self._send_loop(self.fd.send, data, flags)
  File "/home/cephis/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 374, in _send_loop
    timeout_exc=socket.timeout("timed out"))
  File "/home/cephis/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 203, in _trampoline
    mark_as_closed=self._mark_as_closed)
  File "/home/cephis/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 160, in trampoline
    listener = hub.add(hub.WRITE, fileno, current.switch, current.throw, mark_as_closed)
  File "/home/cephis/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/hubs/epolls.py", line 49, in add
    listener = BaseHub.add(self, evtype, fileno, cb, tb, mac)
  File "/home/cephis/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 177, in add
    evtype, fileno, evtype, cb, bucket[fileno]))
RuntimeError: Second simultaneous write on fileno 10 detected.  Unless you really know what you're doing, make sure that only one greenthread can write any particular socket.  Consider using a pools.Pool. If you do know what you're doing and want to disable this error, call eventlet.debug.hub_prevent_multiple_readers(False) - MY THREAD=<built-in method switch of greenlet.greenlet object at 0x7fb35b6ac910>; THAT THREAD=FdListener('write', 10, <built-in method switch of greenlet.greenlet object at 0x7fb35b6ac7d0>, <built-in method throw of greenlet.greenlet object at 0x7fb35b6ac7d0>)

dev

python 2.7.6

xubuntu

**Comment by dummyaja** [comment]
im also having the same error message, after sleep and login again.
http://pastebin.com/QJSaPpRe

**Comment by sohje** [comment]
@dummyaja How many bots you running with the same conf?

**Comment by Cephis** [comment]
just one for me

**Comment by dummyaja** [comment]
@sohje in same liinux user i run 1 bot and 1 pokemap
each of it i put in a screen

**Comment by sohje** [comment]
Is this problem permanent? Or its appears time to time?

**Comment by Cephis** [comment]
i've tested a few and it appears that this problem occured when random alive pause is on
