### ISSUE TITLE
Stop after login procedure

### ISSUE THREAD

**Issue by bhaveshrangani** [PokemonGoF/PokemonGo-Bot#5149]
2016-09-03 11:23:44,276 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-03 11:23:44,293 [       cli] [INFO] commit: ca94424f
2016-09-03 11:23:44,299 [       cli] [INFO] Configuration initialized
2016-09-03 11:23:44,299 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-09-03 11:23:44,300 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-09-03 11:23:44,306 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
[2016-09-03 11:23:44] [MainThread] [SleepSchedule] [INFO] [next_sleep] Next sleep at 17:23:00, for a duration of 3:02:53
[2016-09-03 11:23:44] [MainThread] [PokemonGoBot] [INFO] [set_start_location] Setting start location.
[2016-09-03 11:23:44] [MainThread] [PokemonGoBot] [INFO] [location_found] Location found: London Tower (51.50811239999999, -0.0759493, 0.0)
[2016-09-03 11:23:44] [MainThread] [PokemonGoBot] [INFO] [position_update] Now at (51.50811239999999, -0.0759493, 0.0)
[2016-09-03 11:23:44] [MainThread] [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "pokecli.py", line 795, in <module>
    main()
  File "pokecli.py", line 231, in main
    report_summary(bot)
  File "pokecli.py", line 279, in report_summary
    metrics.capture_stats()
  File "/root/Home/pokemongo_bot/metrics.py", line 108, in capture_stats
    response_dict = request.call()
  File "/root/Home/pokemongo_bot/api_wrapper.py", line 239, in call
    result = self._call()
  File "/root/Home/pokemongo_bot/api_wrapper.py", line 188, in _call
    return PGoApiRequest.call(self, signature)
  File "/root/Home/src/pgoapi/pgoapi/pgoapi.py", line 236, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/root/Home/src/pgoapi/pgoapi/rpc_api.py", line 127, in request
    response_dict = self._parse_main_response(response, subrequests)
  File "/root/Home/src/pgoapi/pgoapi/rpc_api.py", line 337, in _parse_main_response
    raise ServerSideAccessForbiddenException("Seems your IP Address is banned or something else went badly wrong...")
pgoapi.exceptions.ServerSideAccessForbiddenException: Seems your IP Address is banned or something else went badly wrong...
[2016-09-03 11:23:47] [MainThread] [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
[2016-09-03 11:23:47] [MainThread] [sentry.errors.uncaught] [ERROR] [u'ServerSideAccessForbiddenException: Seems your IP Address is banned or something else went badly wrong...', u'  File "pokecli.py", line 795, in <module>', u'  File "pokecli.py", line 231, in main', u'  File "pokecli.py", line 279, in report_summary', u'  File "pokemongo_bot/metrics.py", line 108, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 239, in call', u'  File "pokemongo_bot/api_wrapper.py", line 188, in _call', u'  File "pgoapi/pgoapi.py", line 236, in call', u'  File "pgoapi/rpc_api.py", line 127, in request', u'  File "pgoapi/rpc_api.py", line 337, in _parse_main_response']
Sat Sep 3 11:23:47 UTC 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

**Comment by BreezeRo** [comment]
Maybe IP banned, try using the bot from a diff. IP address

**Comment by ravey-davey** [comment]
I'm definitely not IP banned and have literally just updated and now have this issue as well..

**Comment by Shentang** [comment]
Exact same issue. I can't be ip banned - I still run pokemap without any issues.

Traceback (most recent call last):
  File "pokecli.py", line 795, in <module>
    main()
  File "pokecli.py", line 153, in main
    bot.tick()
  File "/root/bot2/PokemonGo-Bot/pokemongo_bot/__init__.py", line 662, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/root/bot2/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_pokemon.py", line 44, in work
    if self.catch_pokemon(self.pokemon.pop()) == WorkerResult.ERROR:
  File "/root/bot2/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_pokemon.py", line 138, in catch_pokemon
    return_value = worker.work()
  File "/root/bot2/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 174, in work
    self._do_catch(pokemon, encounter_id, catch_rate_by_ball, is_vip=is_vip)
  File "/root/bot2/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 583, in _do_catch
    sleep (randrange(self.catchsim_newtodex_wait_min, self.catchsim_newtodex_wait_max))
  File "/usr/lib/python2.7/random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (1,1, 0)
[2016-09-03 16:54:49] [MainThread] [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/root/bot/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/root/bot/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/root/bot/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/root/bot/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/root/bot/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/root/bot/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/root/bot/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/root/bot/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 848, in _send_output
    msg += message_body
  File "/root/bot/PokemonGo-Bot/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
[2016-09-03 16:54:49] [MainThread] [sentry.errors.uncaught] [ERROR] [u'ValueError: empty range for randrange() (1,1, 0)', u'  File "pokecli.py", line 795, in <module>', u'  File "pokecli.py", line 153, in main', u'  File "pokemongo_bot/__init__.py", line 662, in tick', u'  File "pokemongo_bot/cell_workers/catch_pokemon.py", line 44, in work', u'  File "pokemongo_bot/cell_workers/catch_pokemon.py", line 138, in catch_pokemon', u'  File "pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 174, in work', u'  File "pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 583, in _do_catch', u'  File "python2.7/random.py", line 218, in randrange']

@ravey-davey what was your wrong location?

**Comment by alephmelo** [comment]
I was getting this when using:
```json
"location": "Location Name",
```
And now I'm using:
```json
"location": "00.000000,00.000000", # long, lat
```

**Comment by oralunal** [comment]
Use the issue template please.
