### ISSUE TITLE
pgoapi error when fresh installing the bot

### ISSUE THREAD

**Issue by Asafffff** [PokemonGoF/PokemonGo-Bot#5154]
### Expected Behavior
Bot should run

### Actual Behavior
I'm getting this errors

### Output when issue occurred
```
Traceback (most recent call last):
  File "pokecli.py", line 42, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException, NoPlayerPositionSetException
  File "c:\python27\src\pgoapi\pgoapi\__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "c:\python27\src\pgoapi\pgoapi\pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "c:\python27\src\pgoapi\pgoapi\rpc_api.py", line 47, in <module>
    from pgoapi.utilities import to_camel_case, get_time, get_format_time_diff, Rand48, long_to_bytes, generateLocation1, generateLocation2, generateRequestHash, f2i
  File "c:\python27\src\pgoapi\pgoapi\utilities.py", line 30, in <module>
    import xxhash
ImportError: DLL load failed: %1 is not a valid Win32 application.

 Something went wrong and the bot needed to be restarted. Please investigate the cause.
```
### Steps to Reproduce
I just did a fresh install on my another computer. tried searching for a fix, all saying it's something with the "pip install -r requirements.txt", tried that, tried with the --upgrade too, tried deleting pgoapi from both src folder, and python/lib/site-packages/pgoapi.
Right now I do have it installed, I can see it under "pip list", pgoapi 1.1.8 as it should be.
I have all the encrypt files too..
What else can be the problem?
### Other Information
OS: 
Win10 pro, 64bit
Branch: 
dev
Git Commit: 
latest
Python Version: 
python 2.7.12, pip 8.1.2

**Comment by Asafffff** [comment]
After trying alot, what fixed my problem was uninstalling Git, Python and Python visual c++ compiler, and reinstalling it through the .bat file! hope it will help others.
