### ISSUE TITLE
Bot Not Starting, Stuck on Starting New HTTP

### ISSUE THREAD

**Issue by BarrieG14** [PokemonGoF/PokemonGo-Bot#5155]
### Expected Behavior
Bot to start

### Actual Behavior
Gets stuck here - 
2016-09-03 18:47:08,688 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-03 18:47:08,697 [       cli] [INFO] commit: ca94424f
2016-09-03 18:47:08,703 [       cli] [INFO] Configuration initialized
(86963) wsgi starting up on http://0.0.0.0:4000
2016-09-03 18:47:08,876 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): 0.0.0.0

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/AwLeZFL4

### Output when issue occurred
2016-09-03 18:47:08,688 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-03 18:47:08,697 [       cli] [INFO] commit: ca94424f
2016-09-03 18:47:08,703 [       cli] [INFO] Configuration initialized
(86963) wsgi starting up on http://0.0.0.0:4000
2016-09-03 18:47:08,876 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): 0.0.0.0

### Steps to Reproduce
Attempted to run the bot with command ./run.sh

### Other Information
OS: OSX 10.11.2
Branch: 
 
Git Commit: 
ca94424f688bc8080db055d1b9443c3c8d8212fb
Python Version: 
Python 2.7.12
Any other relevant files/configs (eg: path files)

**Comment by sohje** [comment]
Try to remove:
```js
   "websocket": {
      "start_embedded_server": true,
      "server_url": "0.0.0.0:4000"
   }
```
from the end of config and check again.

**Comment by BarrieG14** [comment]
Thank you sohje.  I am now passed that issue, unfortunately I know have another error but I will just have to troubleshoot that myself I imagine, some part of my config.json is incorrect.  I am pretty new to python so I have probably made a mistake.  


2016-09-03 19:06:41,899 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-03 19:06:41,907 [       cli] [INFO] commit: ca94424f
./configs/config.json:783:19: Error: Object literal (dictionary) is not terminated
   |  At line 783, column 19, offset 20099 (AT-END)
   |    near text: True
   |  Object started at line 760, column 11, offset 19406
./configs/config.json:783:19: Error: Object literal (dictionary) is not terminated
   |  At line 783, column 19, offset 20099 (AT-END)
   |    near text: True
   |  Object started at line 1, column 0, offset 0 (AT-START)
./configs/config.json: has errors
2016-09-03 19:06:42,152 [       cli] [CRITICAL] Error with configuration file
Sat 3 Sep 2016 19:06:42 BST Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

**Comment by crvfts** [comment]
validate your config.json http://jsonlint.com/

**Comment by xiatianyu** [comment]
> some part of my config.json is incorrect. I am pretty new to python so I have probably made a mistake.

FYI, JSON is not peculiar to Python. To spot any syntactic errors, you can make use of [JSONLint](http://jsonlint.com/). The most likely cause is an extra comma after the last key-value pair in the object.

**Comment by BarrieG14** [comment]
Thank you everyone for your help.  It is much appreciated.  I am on to another issue with the tree.config.builder now!  But I will try and troubleshoot this one myself.  Thanks again for everyones help.

**Comment by BarrieG14** [comment]
I am now getting this error.  Is it something I am doing or a wider issue after a pause?

 
[2016-09-03 21:10:44] [RandomAlivePause] [next_random_alive_pause] Next random alive pause at 21:53:54, for a duration of 0:04:21
[2016-09-03 21:10:44] [RandomPause] [next_random_pause] Next random pause at 21:53:40, for a duration of 0:05:16
[2016-09-03 21:10:46] [       cli] 
[2016-09-03 21:10:46] [       cli] Ran for 0:00:07
[2016-09-03 21:10:46] [       cli] Total XP Earned: 0  Average: 0.00/h
[2016-09-03 21:10:46] [       cli] Travelled 0.00km
[2016-09-03 21:10:46] [       cli] Visited 0 stops
[2016-09-03 21:10:46] [       cli] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
[2016-09-03 21:10:46] [       cli] Threw 0 pokeballs
[2016-09-03 21:10:46] [       cli] Earned 0 Stardust
[2016-09-03 21:10:46] [       cli] Hatched eggs 0
[2016-09-03 21:10:46] [       cli] 
[2016-09-03 21:10:46] [       cli] Highest CP Pokemon: 
[2016-09-03 21:10:46] [       cli] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 795, in <module>
    main()
  File "pokecli.py", line 142, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 102, in start_bot
    initialize_task(bot, config)
  File "pokecli.py", line 93, in initialize_task
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "/Users/*****/Documents/PokemonGo-Map/PokemonGo-Bot/pokemongo_bot/tree_config_builder.py", line 59, in build
    worker = self._get_worker_by_name(task_type)
  File "/Users/*****/Documents/PokemonGo-Map/PokemonGo-Bot/pokemongo_bot/tree_config_builder.py", line 21, in _get_worker_by_name
    raise ConfigException('No worker named {} defined'.format(name))
pokemongo_bot.tree_config_builder.ConfigException: No worker named UseIncense defined
Sat 3 Sep 2016 21:10:46 BST Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

**Comment by sohje** [comment]
What branch you are using? Try to remove UseIncense from the config.

**Comment by BarrieG14** [comment]
sohje, thank you again.  This has resolved my issue.  I hugely appreciate your help :)
