### ISSUE TITLE
[Errors] Errors on taking RandomAlivePause

### ISSUE THREAD

**Issue by pranavperfect** [PokemonGoF/PokemonGo-Bot#5178]
### Expected Behavior
Take random break, then resume.

### Actual Behavior
takes random break. errors. resumes.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
not dependent

### Output when issue occurred
[2016-09-04 07:30:23] [MainThread] [RandomAlivePause] [INFO] [bot_random_alive_pause] Taking a random break keeping bot alive for 00:09:08, will resume at 07:39:31
[Errno 104] Connection reset by peer
[Errno 104] Connection reset by peer
[Errno 32] Broken pipe
[2016-09-04 07:39:32] [MainThread] [RandomAlivePause] [INFO] [next_random_alive_pause] Next random alive pause at 08:35:08, for a duration of 0:05:08
[Errno 104] Connection reset by peer
[2016-09-04 07:41:25] [MainThread] [IncubateEggs] [INFO] [next_egg_incubates] Eggs incubating: [5.65/10.0 km] (Eggs left: 8, Incubating: 1)
Traceback (most recent call last):
  File "/mnt/c/Users/prana/Desktop/Bot/New/local/lib/python2.7/site-packages/eventlet/wsgi.py", line 481, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/mnt/c/Users/prana/Desktop/Bot/New/local/lib/python2.7/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/mnt/c/Users/prana/Desktop/Bot/New/local/lib/python2.7/site-packages/socketio/server.py", line 308, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/mnt/c/Users/prana/Desktop/Bot/New/local/lib/python2.7/site-packages/engineio/server.py", line 255, in handle_request
    socket = self._get_socket(sid)
  File "/mnt/c/Users/prana/Desktop/Bot/New/local/lib/python2.7/site-packages/engineio/server.py", line 367, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'

### Steps to Reproduce
take randomalivepause

### Other Information
OS: 
Win 10
Branch: 
Master
Git Commit: 
ca94424f
Python Version: 
2.3.6

**Comment by cmezh** [comment]
It is not caused by RandomAlivePause.
