### ISSUE TITLE
Address already in use  / Starting new HTTP connection (1): 127.0.0.1 / handle_sigint

### ISSUE THREAD

**Issue by MZorzy** [PokemonGoF/PokemonGo-Bot#5211]
### Expected Behavior
stop bot 1, start  bot 2, bot 2 work

### Actual Behavior
bot 2 stop

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

config.json.exaple with altidude modded.

### Output when issue occurred
python pokecli.py -cf configs/config.json -af configs/BOT6.json 
2016-09-05 11:11:44,375 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-05 11:11:44,428 [       cli] [INFO] commit: f60a2ecc
2016-09-05 11:11:44,442 [       cli] [INFO] Configuration initialized
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/marco/PokeBotDev/PokemonGo-Bot/pokemongo_bot/socketio_server/runner.py", line 33, in _start_listening_blocking
    listener = eventlet.listen((self.host, self.port))
  File "/usr/local/lib/python2.7/dist-packages/eventlet/convenience.py", line 43, in listen
    sock.bind(addr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

2016-09-05 11:11:44,536 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): 127.0.0.1

### Steps to Reproduce
git pull
stat a bot, stop it
start other bot

### Other Information
OS: Debian , oythin 2,7,12 , last commit f60a2ecc

when close crtl+c a bot the connection still active, so need to manual kill pidof python
missingo some on handle_sigint ?

**Comment by Cephis** [comment]
I got the same problem

**Comment by oralunal** [comment]
Try to remove this from your config or change port:
```
	"websocket": {
		"start_embedded_server": true,
		"server_url": "127.0.0.1:4000"
	}
```
