### ISSUE TITLE
error after login procedure / raspbian

### ISSUE THREAD

**Issue by LeO-Fr** [PokemonGoF/PokemonGo-Bot#5223]
pi@raspberrypi ~/PokemonGo-Bot $ ./run.sh
2016-09-05 22:10:20,795 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-05 22:10:20,870 [       cli] [INFO] commit: ca94424f
2016-09-05 22:10:20,982 [       cli] [INFO] Configuration initialized
2016-09-05 22:10:20,988 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-09-05 22:10:20,992 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-09-05 22:10:21,178 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
(22416) wsgi starting up on http://127.0.0.1:4000
2016-09-05 22:10:26,499 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): 127.0.0.1
[2016-09-05 22:10:26] [SleepSchedule] [INFO] [next_sleep] Next sleep at 12:21:34, for a duration of 5:14:18
[2016-09-05 22:10:26] [PokemonGoBot] [INFO] [set_start_location] Setting start location.
[2016-09-05 22:10:26] [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
[2016-09-05 22:10:26] [PokemonGoBot] [INFO] [location_found] Location found: 47.2303534,-0.7666288 (47.2303534, -0.7666288, 8.0)
[2016-09-05 22:10:26] [PokemonGoBot] [INFO] [position_update] Now at (47.2303534, -0.7666288, 8.0)
[2016-09-05 22:10:26] [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "pokecli.py", line 795, in <module>
    main()
  File "pokecli.py", line 231, in main
    report_summary(bot)
  File "pokecli.py", line 279, in report_summary
    metrics.capture_stats()
  File "/home/pi/PokemonGo-Bot/pokemongo_bot/metrics.py", line 108, in capture_stats
    response_dict = request.call()
  File "/home/pi/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 223, in call
    if not self.can_call():
  File "/home/pi/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 128, in can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
[2016-09-05 22:10:27] [sentry.errors] [ERROR] Sentry responded with an error: 'module' object has no attribute 'HTTPSHandler' (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 44, in urlopen
    class ValidHTTPSHandler(urllib2.HTTPSHandler):
AttributeError: 'module' object has no attribute 'HTTPSHandler'
[2016-09-05 22:10:27] [sentry.errors.uncaught] [ERROR] [u'NotLoggedInException', u'  File "pokecli.py", line 795, in <module>', u'  File "pokecli.py", line 231, in main', u'  File "pokecli.py", line 279, in report_summary', u'  File "pokemongo_bot/metrics.py", line 108, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 223, in call', u'  File "pokemongo_bot/api_wrapper.py", line 128, in can_call']
Mon Sep 5 22:10:28 UTC 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

**Comment by sohje** [comment]
What branch?

**Comment by oralunal** [comment]
Please use the issue template.
