### ISSUE TITLE
newly 1st run bot crashed

### ISSUE THREAD

**Issue by madzul** [PokemonGoF/PokemonGo-Bot#5233]
### Expected Behavior
Bot should run and completing the tutorial

### Actual Behavior
Bot crashed

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
use examples from configs

### Output when issue occurred

Traceback (most recent call last):
  File "pokecli.py", line 802, in <module>
    main()
  File "pokecli.py", line 238, in main
    report_summary(bot)
  File "pokecli.py", line 286, in report_summary
    metrics.capture_stats()
  File "/home/madzul/work/zz/pgb/PGB-Dev0/pokemongo_bot/metrics.py", line 105, in capture_stats
    self.dust['latest'] = self.bot.stardust 
  File "/home/madzul/work/zz/pgb/PGB-Dev0/pokemongo_bot/__init__.py", line 72, in stardust
    return filter(lambda y: y['name'] == 'STARDUST', self._player['currencies'])[0]['amount']
AttributeError: 'PokemonGoBot' object has no attribute '_player'

### Steps to Reproduce
run new bot

### Other Information
OS: 
Linux 2.6.32-279.el6.x86_64
Branch: 
dev
Git Commit: 
d3e0b3a4600fd82b9cf9df4e0696fc6ec4679070
Python Version: 
Python 2.7.12
Any other relevant files/configs (eg: path files)

**Comment by rawgni** [comment]
can you post the whole log ?

**Comment by prettynid888** [comment]
im having the same error from dev

**Comment by madzul** [comment]
@rawgni 
how can I get the whole log?

**Comment by rawgni** [comment]
@madzul should be on the screen where you copy the output above. I just wanted to see more output. Thanks :)

**Comment by madzul** [comment]
@rawgni i've pasted to that (in the output section)

**Comment by rawgni** [comment]
@madzul output from ./run.sh to where it crashes. What you posted is only the Traceback

**Comment by madzul** [comment]
@rawgni like this:
————————
2016-09-06 13:37:13,103 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-06 13:37:13,108 [       cli] [INFO] commit: d3e0b3a4
2016-09-06 13:37:13,111 [       cli] [INFO] Configuration initialized
[2016-09-06 13:37:13] [MainThread] [SleepSchedule] [INFO] Next sleep at 22:22:05, for a duration of 2:42:34
[2016-09-06 13:37:13] [MainThread] [PokemonGoBot] [INFO] Setting start location.
[2016-09-06 13:37:13] [MainThread] [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
[2016-09-06 13:37:13] [MainThread] [PokemonGoBot] [INFO] Location found: 37.808966, -122.410153 (37.808966, -122.410153, 8.0)
[2016-09-06 13:37:13] [MainThread] [PokemonGoBot] [INFO] Now at (37.808966, -122.410153, 8.0)
[2016-09-06 13:37:13] [MainThread] [PokemonGoBot] [INFO] Login procedure started.
Traceback (most recent call last):
  File "pokecli.py", line 802, in <module>
    main()
  File "pokecli.py", line 238, in main
    report_summary(bot)
  File "pokecli.py", line 286, in report_summary
    metrics.capture_stats()
  File "/home/madzul/work/zz/pgb/PGB-Dev0/pokemongo_bot/metrics.py", line 105, in capture_stats
    self.dust['latest'] = self.bot.stardust 
  File "/home/madzul/work/zz/pgb/PGB-Dev0/pokemongo_bot/__init__.py", line 72, in stardust
    return filter(lambda y: y['name'] == 'STARDUST', self._player['currencies'])[0]['amount']
AttributeError: 'PokemonGoBot' object has no attribute '_player'

**Comment by cavaldryg** [comment]
I have exactly that issue too

> 
(poke)root:PokemonGo-Bot$ ./run.sh 
2016-09-06 13:37:38,067 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-06 13:37:38,197 [       cli] [INFO] commit: ca94424f
2016-09-06 13:37:38,202 [       cli] [INFO] Configuration initialized
2016-09-06 13:37:38,203 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-09-06 13:37:38,203 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-09-06 13:37:38,253 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
(17534) wsgi starting up on http://127.0.0.1:4000
2016-09-06 13:37:38,672 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): 127.0.0.1
[2016-09-06 13:37:38] [PokemonGoBot] [INFO] [set_start_location] Setting start location.
[2016-09-06 13:37:38] [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
[2016-09-06 13:37:38] [PokemonGoBot] [INFO] [location_found] Location found: 10.787121, 106.705461 (10.787121, 106.705461, 8.0)
[2016-09-06 13:37:38] [PokemonGoBot] [INFO] [position_update] Now at (10.787121, 106.705461, 8.0)
[2016-09-06 13:37:38] [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "pokecli.py", line 795, in <module>
    main()
  File "pokecli.py", line 231, in main
    report_summary(bot)
  File "pokecli.py", line 279, in report_summary
    metrics.capture_stats()
  File "/root/Downloads/PokemonGo-Bot/pokemongo_bot/metrics.py", line 108, in capture_stats
    response_dict = request.call()
  File "/root/Downloads/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 223, in call
    if not self.can_call():
  File "/root/Downloads/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 128, in can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
[2016-09-06 13:37:38] [sentry.errors] [ERROR] Sentry responded with an error: 'module' object has no attribute 'HTTPSHandler' (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/root/Downloads/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/root/Downloads/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/root/Downloads/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 44, in urlopen
    class ValidHTTPSHandler(urllib2.HTTPSHandler):
AttributeError: 'module' object has no attribute 'HTTPSHandler'
[2016-09-06 13:37:38] [sentry.errors.uncaught] [ERROR] [u'NotLoggedInException', u'  File "pokecli.py", line 795, in <module>', u'  File "pokecli.py", line 231, in main', u'  File "pokecli.py", line 279, in report_summary', u'  File "pokemongo_bot/metrics.py", line 108, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 223, in call', u'  File "pokemongo_bot/api_wrapper.py", line 128, in can_call']
Tuesday, 2016 November 2016 13:37:38 ICT Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

**Comment by rawgni** [comment]
@cvld-poke pgoapi.exceptions.NotLoggedInException. Not logged in

**Comment by madzul** [comment]
I've tried on different machine, on different subnet
The Bot running well. May be that's just login problem (IP Banned, perhaps)
But, why my bot didn't raised NotLoggedInException ???

**Comment by rawgni** [comment]
@madzul i think you did not login successfully. 

```
[2016-09-06 14:51:12] [PokemonGoBot] [INFO] Login procedure started.
[2016-09-06 14:51:15] [PokemonGoBot] [INFO] Login successful.
[2016-09-06 14:51:15] [PokemonGoBot] [INFO] Found encrypt.so! Platform: linux2 encrypt.so ...
[2016-09-06 14:51:15] [PokemonGoBot] [INFO]
```

The login procedure started but not successful.

**Comment by madzul** [comment]
@rawgni Yes, I think so. Is there any handler for failed login condition??

**Comment by cvld-poke** [comment]
@rawgni I try update login information, check google acount setting but nothing change, always throw pgoapi.exceptions.NotLoggedInException.

**Comment by rawgni** [comment]
I think there is. @mjmadsen thoughts?

**Comment by cvld-poke** [comment]
I found the problem, I change to use PTC account, all things work. Please check the feature login with Google account, thanks.

**Comment by prettynid888** [comment]
@c-poke  thanks... I tried with PTC it work but when attempt to pokemon hit another error, anyway thanks
