### ISSUE TITLE
Error when capturing pokemon

### ISSUE THREAD

**Issue by 03t02** [PokemonGoF/PokemonGo-Bot#526]
Impossible to capture pokemon since last `pull master`

```python
[#] A Wild Eevee appeared! [CP 211] [Potential 0.56]
[#] IV [Stamina/Attack/Defense] = [11/1/13]
[x] Using Pokeball...
[x] Captured Eevee! [CP 211] [IV 0.56] - exchanging for candy
Traceback (most recent call last):
  File "./pokecli.py", line 187, in <module>
    main()
  File "./pokecli.py", line 178, in main
    bot.take_step()
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/__init__.py", line 35, in take_step
    self.stepper.take_step()
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/stepper.py", line 61, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/stepper.py", line 134, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/__init__.py", line 120, in work_on_cell
    hack_chain = worker.work()
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/cell_workers/seen_fort_worker.py", line 40, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/stepper.py", line 87, in _walk_to
    alt, False)
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/stepper.py", line 134, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/__init__.py", line 90, in work_on_cell
    if worker.work() == -1:
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 135, in work
    if self.should_release_pokemon(pokemon_name, cp, pokemon_potential, response_dict):
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 213, in should_release_pokemon
    release_config = self._get_release_config_for(pokemon_name)
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 255, in _get_release_config_for
    release_config = self.config.release_config['any']
KeyError: 'any'
```

**Comment by pol0nium** [comment]
Did you rename `release_config.json.example` to `release_config.json`?

**Comment by 03t02** [comment]
No, I didn't, just use command line option.
And now I renamed this file, we'll see

**Comment by pol0nium** [comment]
Don't forget to check if the default config suits your needs.

**Comment by 03t02** [comment]
What should I put in this config exactly ?
This is my config:

```json
{
    "auth_service": "google",
    "username": "My email",
    "password": "And my password",
    "location": "2 Allée Adrienne Lecouvreur, 75007 Paris",
    "cp": 300,
    "max_steps": 50,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": false,
    "pokemon_potential": 0.1,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": ["101","102","103","104"]
}
```

I just edited my email, password and location, it seems not enough to avoid error. It happens every time when capturing pokemon

Error:
```python
[#] A Wild Hitmonchan appeared! [CP 499] [Potential 0.44]
[#] IV [Stamina/Attack/Defense] = [11/3/6]
[x] Using Greatball...
[x] Captured Hitmonchan! [CP 499] [IV 0.44] - exchanging for candy
Traceback (most recent call last):
  File "./pokecli.py", line 187, in <module>
    main()
  File "./pokecli.py", line 178, in main
    bot.take_step()
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/__init__.py", line 35, in take_step
    self.stepper.take_step()
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/stepper.py", line 61, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/stepper.py", line 134, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/__init__.py", line 120, in work_on_cell
    hack_chain = worker.work()
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/cell_workers/seen_fort_worker.py", line 40, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/stepper.py", line 87, in _walk_to
    alt, False)
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/stepper.py", line 134, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/__init__.py", line 90, in work_on_cell
    if worker.work() == -1:
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 135, in work
    if self.should_release_pokemon(pokemon_name, cp, pokemon_potential, response_dict):
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 213, in should_release_pokemon
    release_config = self._get_release_config_for(pokemon_name)
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 255, in _get_release_config_for
    release_config = self.config.release_config['any']
KeyError: 'any'

```

**Comment by pol0nium** [comment]
You're looking at `config.json.example` not `release_config.json.example` ;). You don't need to use `config.json.example` if you pass arguments to the command line.

**Comment by Calcyfer** [comment]
Since commit 8d40a4f90c644d37b5a27db48256280653b6277b, the bot will check if the `release_config.json.example` has been renamed to `release_config.json`.

@03t02 Have you gotten it to work?

**Comment by 03t02** [comment]
Oh Sorry, my bad. misread. It works now :). Thanks you all

**Comment by Calcyfer** [comment]
Anytime. Can you close the issue, please? Thanks!
