### ISSUE TITLE
Exception errror on my Pokemon go Bot

### ISSUE THREAD

**Issue by JerungC** [PokemonGoF/PokemonGo-Bot#5262]
Anybody can help me on this? it will restart and continue online a few step then come again this error.

[19:24:00] Exception: System.ArgumentOutOfRangeException: 'minValue' cannot be greater than maxValue.
Parameter name: minValue
   at System.Random.Next(Int32 minValue, Int32 maxValue)
   at PokemonGo.RocketAPI.Logic.Logic.<fncPokeStop>d__29.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 552
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__28.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 493
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__21.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 265
[19:24:00] Starting again in 10 seconds...
[19:24:11] Export Player Infos and all Pokemon to "\Config\PokemonList.csv"
[19:24:15] FYI - GreatBall Count is Zero
[19:24:15] FYI - UltraBall Count is Zero

**Comment by Gobberwart** [comment]
This appears to be for a different bot.
