### ISSUE TITLE
Logger get erorr : TypeError: encode() argument 1 must be string, not None

### ISSUE THREAD

**Issue by cbogithub** [PokemonGoF/PokemonGo-Bot#5265]
```
2016-09-07 19:47:00,644 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): 127.0.0.1
_inventory was not initialized
_inventory was not initialized
[2016-09-07 19:47:00] [       cli] [INFO] 
[2016-09-07 19:47:00] [       cli] [INFO] Ran for 0:00:00
[2016-09-07 19:47:00] [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
[2016-09-07 19:47:00] [       cli] [INFO] Travelled 0.00km
[2016-09-07 19:47:00] [       cli] [INFO] Visited 0 stops
[2016-09-07 19:47:00] [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
[2016-09-07 19:47:00] [       cli] [INFO] Threw 0 pokeballs
[2016-09-07 19:47:00] [       cli] [INFO] Earned 0 Stardust
[2016-09-07 19:47:00] [       cli] [INFO] Hatched eggs 0
[2016-09-07 19:47:00] [       cli] [INFO] 
[2016-09-07 19:47:00] [       cli] [INFO] Highest CP Pokemon: 
[2016-09-07 19:47:00] [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 803, in <module>
    main()
  File "pokecli.py", line 150, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 107, in start_bot
    bot.start()
  File "P:\pokemon go\PokemonGo-Bot\pokemongo_bot\__init__.py", line 134, in start
    self.sleep_schedule.work()
  File "P:\pokemon go\PokemonGo-Bot\pokemongo_bot\sleep_schedule.py", line 50, in work
    self._sleep()
  File "P:\pokemon go\PokemonGo-Bot\pokemongo_bot\sleep_schedule.py", line 171, in _sleep
    'wake': wake
  File "P:\pokemon go\PokemonGo-Bot\pokemongo_bot\event_manager.py", line 76, in emit
    handler.handle_event(event, sender, level, formatted_msg, data)
  File "P:\pokemon go\PokemonGo-Bot\pokemongo_bot\event_handlers\logging_handler.py", line 140, in handle_event
    getattr(logger, level)(formatted_msg.encode(sys.stdout.encoding, "replace").decode("utf-8"))
TypeError: encode() argument 1 must be string, not None
```

**Comment by ProZer0** [comment]
Same issue here! fresh installation and old dev versions works fine but the latest update broke something!

**Comment by rawgni** [comment]
@Anakin5 any thoughts on this ?

**Comment by sohje** [comment]
```python
sys.stdout.encoding is None => True
```

**Comment by Anakin5** [comment]
I am missing all the info of the issue template to give a though. And also please open a python and type `print sys.stdout.encoding`

**Comment by Anakin5** [comment]
Please provide info on which version of the code you are using

**Comment by MartinTerp** [comment]
@Anakin5 here is my run from fresh docker instance, using latest dev https://github.com/PokemonGoF/PokemonGo-Bot/commit/b0b1e0f5573d1047793f064f63c46450e2565d4a:
```
2016-09-08 17:41:44,547 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-08 17:41:44,565 [       cli] [INFO] commit: b0b1e0f5
2016-09-08 17:41:44,567 [       cli] [INFO] No auth argument specified, checking for /usr/src/app/pokemongo_bot/../configs/auth.json
2016-09-08 17:41:44,567 [       cli] [INFO] No config argument specified, checking for /usr/src/app/pokemongo_bot/../configs/config.json
2016-09-08 17:41:44,571 [       cli] [WARNING] The logging_color argument has been moved into the logging config section
2016-09-08 17:41:44,572 [       cli] [INFO] Configuration initialized
2016-09-08 17:41:44,572 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-09-08 17:41:44,572 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-09-08 17:41:44,582 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
(1) wsgi starting up on http://0.0.0.0:8080
2016-09-08 17:41:44,660 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): 0.0.0.0
2016-09-08 17:41:44,670 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): 0.0.0.0
_inventory was not initialized
_inventory was not initialized
2016-09-08 17:41:44,680 [       cli] [INFO] 
2016-09-08 17:41:44,681 [       cli] [INFO] Ran for 0:00:00
2016-09-08 17:41:44,681 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-09-08 17:41:44,682 [       cli] [INFO] Travelled 0.00km
2016-09-08 17:41:44,682 [       cli] [INFO] Visited 0 stops
2016-09-08 17:41:44,683 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
2016-09-08 17:41:44,683 [       cli] [INFO] Threw 0 pokeballs
2016-09-08 17:41:44,683 [       cli] [INFO] Earned 0 Stardust
2016-09-08 17:41:44,683 [       cli] [INFO] Hatched eggs 0
2016-09-08 17:41:44,684 [       cli] [INFO] 
2016-09-08 17:41:44,684 [       cli] [INFO] Highest CP Pokemon: 
2016-09-08 17:41:44,684 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 803, in <module>
    main()
  File "pokecli.py", line 151, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 107, in start_bot
    bot.start()
  File "/usr/src/app/pokemongo_bot/__init__.py", line 136, in start
    self._setup_api()
  File "/usr/src/app/pokemongo_bot/__init__.py", line 955, in _setup_api
    self._set_starting_position()
  File "/usr/src/app/pokemongo_bot/__init__.py", line 1101, in _set_starting_position
    formatted='Setting start location.'
  File "/usr/src/app/pokemongo_bot/event_manager.py", line 76, in emit
    handler.handle_event(event, sender, level, formatted_msg, data)
  File "/usr/src/app/pokemongo_bot/event_handlers/logging_handler.py", line 140, in handle_event
    getattr(logger, level)(formatted_msg.encode(sys.stdout.encoding, "replace").decode("utf-8"))
TypeError: encode() argument 1 must be string, not None
2016-09-08 17:41:44,701 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90
254/store/)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-09-08 17:41:44,703 [sentry.errors.uncaught] [ERROR] [u'TypeError: encode() argument 1 must be string, not None', u'  File "pokecli.py", line 803, in <module>', u'  File "pokecli.py", line 151
, in main', u'  File "pokecli.py", line 107, in start_bot', u'  File "pokemongo_bot/__init__.py", line 136, in start', u'  File "pokemongo_bot/__init__.py", line 955, in _setup_api', u'  File "pok
emongo_bot/__init__.py", line 1101, in _set_starting_position', u'  File "pokemongo_bot/event_manager.py", line 76, in emit', u'  File "pokemongo_bot/event_handlers/logging_handler.py", line 140, 
in handle_event']
```

**Comment by Anakin5** [comment]
Can you deactivate health check and see what happen ?

**Comment by Anakin5** [comment]
And update to head also to have last fix on logging encoding

**Comment by MartinTerp** [comment]
Now at: https://github.com/PokemonGoF/PokemonGo-Bot/commit/de39997618697179cfa0c06d68be1c69fe1ad7a0 (latest at this time)
and set:     "health_record": false,

```
2016-09-09 06:23:03,853 [       cli] [INFO] PokemonGO Bot v1.0

2016-09-09 06:23:03,874 [       cli] [INFO] commit: de399976
2016-09-09 06:23:03,877 [       cli] [INFO] No auth argument specified, checking for /usr/src/app/pokemongo_bot/../configs/auth.json
2016-09-09 06:23:03,879 [       cli] [INFO] No config argument specified, checking for /usr/src/app/pokemongo_bot/../configs/config.json
2016-09-09 06:23:03,884 [       cli] [WARNING] The logging_color argument has been moved into the logging config section
2016-09-09 06:23:03,885 [       cli] [INFO] Configuration initialized
(1) wsgi starting up on http://0.0.0.0:8080
2016-09-09 06:23:03,925 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): 0.0.0.0
2016-09-09 06:23:03,937 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): 0.0.0.0
_inventory was not initialized
_inventory was not initialized
2016-09-09 06:23:03,951 [       cli] [INFO]
2016-09-09 06:23:03,952 [       cli] [INFO] Ran for 0:00:00
2016-09-09 06:23:03,953 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-09-09 06:23:03,953 [       cli] [INFO] Travelled 0.00km
2016-09-09 06:23:03,954 [       cli] [INFO] Visited 0 stops
2016-09-09 06:23:03,954 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
2016-09-09 06:23:03,955 [       cli] [INFO] Threw 0 pokeballs
2016-09-09 06:23:03,955 [       cli] [INFO] Earned 0 Stardust
2016-09-09 06:23:03,956 [       cli] [INFO] Hatched eggs 0
2016-09-09 06:23:03,956 [       cli] [INFO]
2016-09-09 06:23:03,957 [       cli] [INFO] Highest CP Pokemon:
2016-09-09 06:23:03,957 [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 805, in <module>
    main()
  File "pokecli.py", line 153, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 110, in start_bot
    bot.start()
  File "/usr/src/app/pokemongo_bot/__init__.py", line 137, in start
    self._setup_api()
  File "/usr/src/app/pokemongo_bot/__init__.py", line 956, in _setup_api
    self._set_starting_position()
  File "/usr/src/app/pokemongo_bot/__init__.py", line 1103, in _set_starting_position
    formatted='Setting start location.'
  File "/usr/src/app/pokemongo_bot/event_manager.py", line 76, in emit
    handler.handle_event(event, sender, level, formatted_msg, data)
  File "/usr/src/app/pokemongo_bot/event_handlers/logging_handler.py", line 141, in handle_event
    getattr(logger, level)(formatted_msg.encode(sys.stdout.encoding, "replace").decode("utf-8", "replace"))
TypeError: encode() argument 1 must be string, not None

```

**Comment by Anakin5** [comment]
Can you run that in a command prompt ? ```python -c "import sys; print sys.stdout.encoding"```
What is your platform and version of python ?

**Comment by MartinTerp** [comment]
UTF-8

**Comment by fluxpiada** [comment]
i have the same. it occurs when i have logged in and out frequently in a short space of time (because of errors in a config file i needed to correct and test). 
the encoding is UTF-8. 
I get it on Ubuntu (debian jessie) as well as Osx. Python is 2.7, latest packages installed.
also notice it goes wrong after sentry [https://app.getsentry.com/api/90254/store/](url) gives 
`{"error":"Unable to find authentication information"}`

**Comment by Anakin5** [comment]
ok I can reproduce

**Comment by Anakin5** [comment]
Issue fixed ?

**Comment by MartinTerp** [comment]
Issue fixed for me at least :) thanks for your help @Anakin5

**Comment by Anakin5** [comment]
Fixed
