### ISSUE TITLE
problem when starting bot 

### ISSUE THREAD

**Issue by rut78HR** [PokemonGoF/PokemonGo-Bot#5322]
Yesterday in a hurry i precc CTRL+C and after that can no longer run bot. I try to make new fresh install with master and dev pull but same problem 

./run.sh
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
2016-09-09 10:25:25,871 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-09 10:25:25,878 [       cli] [INFO] commit: unknown
2016-09-09 10:25:25,881 [       cli] [INFO] Configuration initialized
2016-09-09 10:25:25,881 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-09-09 10:25:25,881 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-09-09 10:25:25,887 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
(3696) wsgi starting up on http://127.0.0.1:4000
2016-09-09 10:25:26,013 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): 127.0.0.1
[2016-09-09 10:25:26] [SleepSchedule] [INFO] Next sleep at 11:32:36, for a duration of 05:01:14
[2016-09-09 10:25:26] [PokemonGoBot] [INFO] Setting start location.
[2016-09-09 10:25:26] [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
[2016-09-09 10:25:26] [PokemonGoBot] [INFO] Location found: -34.605626,-56.1686889 (-34.605626, -56.1686889, 8.0)
[2016-09-09 10:25:26] [PokemonGoBot] [INFO] Now at (-34.605626, -56.1686889, 8.0)
[2016-09-09 10:25:26] [PokemonGoBot] [INFO] Login procedure started.
[2016-09-09 10:25:28] [PokemonGoBot] [INFO] Login successful.
[2016-09-09 10:25:28] [PokemonGoBot] [INFO] Found encrypt.so! Platform: freebsd12 encrypt.so directory: /root/PokemonGo-Bot-dev
[2016-09-09 10:25:28] [PokemonGoBot] [INFO] 
[2016-09-09 10:25:28] [PokemonGoBot] [INFO] [x] Error while opening cached forts: [Errno 2] No such file or directory: u'/root/PokemonGo-Bot-dev/pokemongo_bot/../data/recent-forts-xxxxx@gmail.com.json'
_inventory was not initialized
_inventory was not initialized
[2016-09-09 10:25:30] [       cli] [INFO] 
[2016-09-09 10:25:30] [       cli] [INFO] Ran for 0:00:04
[2016-09-09 10:25:30] [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
[2016-09-09 10:25:30] [       cli] [INFO] Travelled 0.00km
[2016-09-09 10:25:30] [       cli] [INFO] Visited 0 stops
[2016-09-09 10:25:30] [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
[2016-09-09 10:25:30] [       cli] [INFO] Threw 0 pokeballs
[2016-09-09 10:25:30] [       cli] [INFO] Earned 0 Stardust
[2016-09-09 10:25:30] [       cli] [INFO] Hatched eggs 0
[2016-09-09 10:25:30] [       cli] [INFO] 
[2016-09-09 10:25:30] [       cli] [INFO] Highest CP Pokemon: 
[2016-09-09 10:25:30] [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 805, in <module>
    main()
  File "pokecli.py", line 153, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 110, in start_bot
    bot.start()
  File "/root/PokemonGo-Bot-dev/pokemongo_bot/__init__.py", line 139, in start
    init_inventory(self)
  File "/root/PokemonGo-Bot-dev/pokemongo_bot/inventory.py", line 1333, in init_inventory
    _inventory = Inventory(bot)
  File "/root/PokemonGo-Bot-dev/pokemongo_bot/inventory.py", line 1180, in __init__
    self.refresh()
  File "/root/PokemonGo-Bot-dev/pokemongo_bot/inventory.py", line 1190, in refresh
    i.refresh(inventory)
  File "/root/PokemonGo-Bot-dev/pokemongo_bot/inventory.py", line 75, in refresh
    self._data = self.retrieve_data(inventory)
  File "/root/PokemonGo-Bot-dev/pokemongo_bot/inventory.py", line 71, in retrieve_data
    ret[key] = self.parse(item)
  File "/root/PokemonGo-Bot-dev/pokemongo_bot/inventory.py", line 406, in parse
    return Pokemon(item)
  File "/root/PokemonGo-Bot-dev/pokemongo_bot/inventory.py", line 912, in __init__
    assert max(int(self.cp_exact), 10) == self.cp
AssertionError
[2016-09-09 10:25:30] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/root/PokemonGo-Bot-dev/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/root/PokemonGo-Bot-dev/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/root/PokemonGo-Bot-dev/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/root/PokemonGo-Bot-dev/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/root/PokemonGo-Bot-dev/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/root/PokemonGo-Bot-dev/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/root/PokemonGo-Bot-dev/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/root/PokemonGo-Bot-dev/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
[2016-09-09 10:25:30] [sentry.errors.uncaught] [ERROR] [u'AssertionError', u'  File "pokecli.py", line 805, in <module>', u'  File "pokecli.py", line 153, in main', u'  File "pokecli.py", line 110, in start_bot', u'  File "pokemongo_bot/__init__.py", line 139, in start', u'  File "pokemongo_bot/inventory.py", line 1333, in init_inventory', u'  File "pokemongo_bot/inventory.py", line 1180, in __init__', u'  File "pokemongo_bot/inventory.py", line 1190, in refresh', u'  File "pokemongo_bot/inventory.py", line 75, in refresh', u'  File "pokemongo_bot/inventory.py", line 71, in retrieve_data', u'  File "pokemongo_bot/inventory.py", line 406, in parse', u'  File "pokemongo_bot/inventory.py", line 912, in __init__']
Fri Sep 9 10:25:30 CEST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

**Comment by db-coder** [comment]
same here:
```
[2016-09-09 15:46:41] Login successful.
_inventory was not initialized
[2016-09-09 15:46:41] Found encrypt.so! Platform: linux2 encrypt.so directory: /home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot
[2016-09-09 15:46:41] 
_inventory was not initialized
```

**Comment by rut78HR** [comment]
nobody else have this problem ?? 
I try with new gmail account and evrithing is OK with bot . Necrobot works with both accounts.

**Comment by LazGit** [comment]
I have the same problem
[2016-09-09 21:53:12] Login successful.
_inventory was not initialized

**Comment by rut78HR** [comment]
Hmm . nobody of developer can check this why inventory can be fetch .. corrupt or something else ?

**Comment by rut78HR** [comment]
commit cb9ebb392eeb711999b0f38c7094ab9a1eb4900c in dev branch fix my problems

**Comment by Gobberwart** [comment]
OP says fixed now. closing.
