### ISSUE TITLE
bot crashes after login

### ISSUE THREAD

**Issue by agetnc313** [PokemonGoF/PokemonGo-Bot#5359]
2016-09-10 06:01:16,816 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-10 06:01:16,816 [       cli] [INFO] No config argument specified, checki
ng for /configs/config.json
2016-09-10 06:01:16,816 [       cli] [INFO] Configuration initialized
2016-09-10 06:01:16,816 [pokemongo_bot.health_record.bot_event] [INFO] Health ch
eck is enabled. For more information:
2016-09-10 06:01:16,816 [pokemongo_bot.health_record.bot_event] [INFO] https://g
ithub.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-09-10 06:01:16,832 [requests.packages.urllib3.connectionpool] [INFO] Starti
ng new HTTP connection (1): www.google-analytics.com
2016-09-10 06:01:16,941 [PokemonGoBot] [INFO] [set_start_location] Setting start
 location.
2016-09-10 06:01:17,628 [PokemonGoBot] [INFO] [location_found] Location found: B
alboa Island (33.6072954, -117.897071, 0.0)
2016-09-10 06:01:17,628 [PokemonGoBot] [INFO] [position_update] Now at (33.60729
54, -117.897071, 0)
2016-09-10 06:01:17,628 [PokemonGoBot] [INFO] [login_started] Login procedure st
arted.
Traceback (most recent call last):
  File "pokecli.py", line 570, in <module>
    main()
  File "pokecli.py", line 162, in main
    report_summary(bot)
  File "pokecli.py", line 197, in report_summary
    metrics.capture_stats()
  File "C:\Users\Administrator\Documents\Git\PokemonGo-Bot\pokemongo_bot\metrics
.py", line 84, in capture_stats
    response_dict = request.call()
  File "C:\Users\Administrator\Documents\Git\PokemonGo-Bot\pokemongo_bot\api_wra
pper.py", line 117, in call
    result = self._call()
  File "C:\Users\Administrator\Documents\Git\PokemonGo-Bot\pokemongo_bot\api_wra
pper.py", line 66, in _call
    return PGoApiRequest.call(self)
  File "c:\users\administrator\documents\git\pokemongo-bot\src\pgoapi\pgoapi\pgo
api.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.g
et_position())
  File "c:\users\administrator\documents\git\pokemongo-bot\src\pgoapi\pgoapi\rpc
_api.py", line 129, in request
    response_dict = self._parse_main_response(response, subrequests)
  File "c:\users\administrator\documents\git\pokemongo-bot\src\pgoapi\pgoapi\rpc
_api.py", line 332, in _parse_main_response
    raise ServerSideAccessForbiddenException("Seems your IP Address is banned or
 something else went badly wrong...")
pgoapi.exceptions.ServerSideAccessForbiddenException: Seems your IP Address is b
anned or something else went badly wrong...
2016-09-10 06:01:19,269 [sentry.errors] [ERROR] Sentry responded with an error:
'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (u
rl: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\Git\PokemonGo-Bot\lib\site-packages\rav
en\transport\threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "C:\Users\Administrator\Documents\Git\PokemonGo-Bot\lib\site-packages\rav
en\transport\http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "C:\Users\Administrator\Documents\Git\PokemonGo-Bot\lib\site-packages\rav
en\utils\http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Administrator\Documents\Git\PokemonGo-Bot\lib\site-packages\fut
ure\backports\urllib\request.py", line 494, in open
    response = self._open(req, data)
  File "C:\Users\Administrator\Documents\Git\PokemonGo-Bot\lib\site-packages\fut
ure\backports\urllib\request.py", line 512, in _open
    '_open', req)
  File "C:\Users\Administrator\Documents\Git\PokemonGo-Bot\lib\site-packages\fut
ure\backports\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Users\Administrator\Documents\Git\PokemonGo-Bot\lib\site-packages\rav
en\utils\http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "C:\Users\Administrator\Documents\Git\PokemonGo-Bot\lib\site-packages\fut
ure\backports\urllib\request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "c:\python27\Lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "c:\python27\Lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "c:\python27\Lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "c:\python27\Lib\httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal
not in range(128)
2016-09-10 06:01:19,269 [sentry.errors.uncaught] [ERROR] [u'ServerSideAccessForb
iddenException: Seems your IP Address is banned or something else went badly wro
ng...', u'  File "pokecli.py", line 570, in <module>', u'  File "pokecli.py", li
ne 162, in main', u'  File "pokecli.py", line 197, in report_summary', u'  File
"C:\\Users\\Administrator\\Documents\\Git\\PokemonGo-Bot\\pokemongo_bot\\metrics
.py", line 84, in capture_stats', u'  File "C:\\Users\\Administrator\\Documents\
\Git\\PokemonGo-Bot\\pokemongo_bot\\api_wrapper.py", line 117, in call', u'  Fil
e "C:\\Users\\Administrator\\Documents\\Git\\PokemonGo-Bot\\pokemongo_bot\\api_w
rapper.py", line 66, in _call', u'  File "c:\\users\\administrator\\documents\\g
it\\pokemongo-bot\\src\\pgoapi\\pgoapi\\pgoapi.py", line 220, in call', u'  File
 "c:\\users\\administrator\\documents\\git\\pokemongo-bot\\src\\pgoapi\\pgoapi\\
rpc_api.py", line 129, in request', u'  File "c:\\users\\administrator\\document
s\\git\\pokemongo-bot\\src\\pgoapi\\pgoapi\\rpc_api.py", line 332, in _parse_mai
n_response']

 Something went wrong and the bot needed to be restarted. Please investigate the
 cause.

**Comment by sohje** [comment]
```
pgoapi.exceptions.ServerSideAccessForbiddenException: Seems your IP Address is b
anned or something else went badly wrong...
```
Try to change IP.
