### ISSUE TITLE
sentry.errors.uncaught] [ERROR] [u"AttributeError: 'PokemonGoBot' object has no attribute '_player'", 

### ISSUE THREAD

**Issue by fluxpiada** [PokemonGoF/PokemonGo-Bot#5403]
> 1. Have you validated that your config.json is valid JSON? Use http://jsonlint.com/ to check. 
Yes, no errors.

> 2. Have you [searched our issue tracker](https://github.com/PokemonGoF/PokemonGo-Bot/issues?q=is%3Aissue+sort%3Aupdated-desc) to see if the issue already exists?.
Yes, only closed found (and different to mine)

> 3. Are you running on the `master` branch? .
Yes

### Expected Behavior

I expect to be able to login and get the bot working with the auth.json and the config.json that worked fine before.

### Actual Behavior
`mycomputername:PokemonGo-Bot usrname$ bash run.sh
2016-09-12 09:42:00,669 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-12 09:42:00,685 [       cli] [INFO] commit: 11123a82
2016-09-12 09:42:00,693 [       cli] [INFO] Configuration initialized
2016-09-12 09:42:00,693 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-09-12 09:42:00,694 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-09-12 09:42:00,710 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
(1004) wsgi starting up on http://127.0.0.1:4000
2016-09-12 09:42:00,772 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): 127.0.0.1
Traceback (most recent call last):
  File "pokecli.py", line 802, in <module>
    main()
  File "pokecli.py", line 238, in main
    report_summary(bot)
  File "pokecli.py", line 286, in report_summary
    metrics.capture_stats()
  File "/Users/xxx/PokemonGo-Bot/pokemongo_bot/metrics.py", line 105, in capture_stats
    self.dust['latest'] = self.bot.stardust 
  File "/Users/xxx/PokemonGo-Bot/pokemongo_bot/__init__.py", line 72, in stardust
    return filter(lambda y: y['name'] == 'STARDUST', self._player['currencies'])[0]['amount']
AttributeError: 'PokemonGoBot' object has no attribute '_player'
[2016-09-12 09:42:00] [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/xxx/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/xxx/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/xxx/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/xxx/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/xxx/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/xxx/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/FloPro/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/FloPro/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
  File "/Users/xxx/PokemonGo-Bot/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
[2016-09-12 09:42:00] [sentry.errors.uncaught] [ERROR] [u"AttributeError: 'PokemonGoBot' object has no attribute '_player'", u'  File "pokecli.py", line 802, in <module>', u'  File "pokecli.py", line 238, in main', u'  File "pokecli.py", line 286, in report_summary', u'  File "pokemongo_bot/metrics.py", line 105, in capture_stats', u'  File "pokemongo_bot/__init__.py", line 72, in stardust']
ma 12 sep 2016 09:42:00 CEST Pokebot  Stopped.
Press any button or wait 20 seconds to continue.`

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

`{
    "websocket_server": false,
    "heartbeat_threshold": 10,
    "enable_social": true,
    "live_config_update": {
      "enabled": false,
      "tasks_only": false
    },
    "tasks": [
      {
        "type": "TelegramTask",
        "config": {
          "enabled": true,
          "master": 192805168,
          "// old syntax, still supported: alert_catch": ["all"],
          "// new syntax:": {},
          "alert_catch": {
            "all": {"operator": "and", "cp": 800, "iv": 0.90},
            "Snorlax": {"operator": "or", "cp": 900, "iv": 0.9}
          }
        }
      },
      {
        "//NOTE: This task MUST be placed on the top of task list": {},
        "type": "RandomAlivePause",
        "config": {
          "enabled": true,
          "min_duration": "00:01:10",
          "max_duration": "00:10:00",
          "min_interval": "00:05:00",
          "max_interval": "01:30:00"
        }
      },
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "RandomPause",
        "config": {
          "enabled": false,
          "min_duration": "00:00:10",
          "max_duration": "00:10:00",
          "min_interval": "00:10:00",
          "max_interval": "02:00:00"
        }
      },
      {
        "type": "CompleteTutorial",
        "config": {
          "enabled": false,
          "// set a name": "",
          "nickname": "",
          "// 0 = No Team, 1 = Blue, 2 = Red, 3 = Yellow": "",
          "team": 0
        }
      },
      {
        "type": "CollectLevelUpReward",
        "config": {
          "collect_reward": true,
          "level_limit": -1
        }
      },
      {
        "type": "IncubateEggs",
        "config": {
          "enabled": true,
          "infinite_longer_eggs_first": false,
          "breakable_longer_eggs_first": true,
          "min_interval": 120,
         "infinite": [2,5,10],
         "breakable": [2,5,10]
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": true,
          "min_interval": 120,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "UpdateLiveInventory",
        "config": {
          "enabled": true,
          "min_interval": 180,
          "show_all_multiple_lines": false,
          "items": ["pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries", "luckyegg"]
        }
      },
      {
        "type": "ShowBestPokemon",
        "config": {
          "enabled": true,
          "min_interval": 300,
          "amount": 5,
          "order_by": "cp",
          "info_to_show": ["cp", "ivcp", "dps", "hp"]
        }
      },
      {
        "type": "TransferPokemon",
        "config": {
          "enabled": true,
          "min_free_slot": 5,
          "transfer_wait_min": 3,
          "transfer_wait_max": 5
        }
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_above_iv": 0.9,
          "nickname_template": "{iv_pct}_{iv_ads}",
          "nickname_wait_min": 3,
          "nickname_wait_max": 5
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "enabled": false,
            
            "// evolve only pidgey and drowzee": "",
            " evolve_list": "pidgey, drowzee, caterpie, slowpoke, spearow, rattata, weedle, staryu, goldeen, polliwhirl, polliwag",
            
            "// evolve all but pidgey and drowzee": "",
            "// evolve_list": "all",
            "// donot_evolve_list": "pidgey, drowzee",
                        
          "// first_evolve_by": "cp",
          "// evolve_above_cp": 500,
          "evolve_above_iv": 0.8,
          "// logic": "or",
          "min_evolve_speed": 25,
          "max_evolve_speed": 30,
          "use_lucky_egg": false
        }
      },
      {
        "type": "UseIncense",
        "config": {
          "use_incense": false,
          "use_order": [
            "ordinary",
            "spicy",
            "cool",
            "floral" 
          ]
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "enabled": true,
          "min_empty_space": 15,
          "max_balls_keep": 200,
          "max_potions_keep": 100,
          "max_berries_keep": 100,
          "max_revives_keep": 50,
          "item_filter": {
            "Pokeball":       { "keep" : 200 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 40 },
            "Hyper Potion":   { "keep" : 50 },
            "Revive":         { "keep" : 50 },
            "Razz Berry":     { "keep" : 150 }
          },
          "recycle_wait_min": 8,
          "recycle_wait_max": 12,
          "recycle_force": true,
          "recycle_force_min": "00:01:00",
          "recycle_force_max": "00:05:00"
        }
      },
      {
        "type": "CatchPokemon",
        "config": {
          "enabled": true,
          "catch_visible_pokemon": true,
          "catch_lured_pokemon": true,
          "min_ultraball_to_keep": 5,
          "berry_threshold": 0.35,
          "vip_berry_threshold": 0.9,
          "treat_unseen_as_vip": true,
          "daily_catch_limit": 800,
          "vanish_settings": {
            "consecutive_vanish_limit": 10,
            "rest_duration_min": "02:00:00",
            "rest_duration_max": "04:00:00"
          },
          "catch_throw_parameters": {
            "excellent_rate": 0.1,
            "great_rate": 0.5,
            "nice_rate": 0.3,
            "normal_rate": 0.1,
            "spin_success_rate" : 0.6,
            "hit_rate": 0.75
          },
          "catch_simulation": {
            "flee_count": 3,
            "flee_duration": 2,
            "catch_wait_min": 3,
            "catch_wait_max": 6,
            "berry_wait_min": 3,
            "berry_wait_max": 5,
            "changeball_wait_min": 3,
            "changeball_wait_max": 5,
            "newtodex_wait_min": 20, 
            "newtodex_wait_max": 30
          }
        }
      },
      {
        "type": "SpinFort",
        "config": {
          "enabled": true,
          "spin_wait_min": 3,
          "spin_wait_max": 5,
          "daily_spin_limit": 1900
        }
      },
      { "type": "UpdateWebInventory",
        "config": {
          "enabled": true
        }
      },
      {
        "type": "MoveToFort",
        "config": {
          "enabled": true,
          "lure_attraction": true,
          "lure_max_distance": 2000,
          "walker": "StepWalker",
          "log_interval": 5
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "enabled": true,
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "pokemon_bag": {
      "// if 'show_at_start' is true, it will log all the pokemons in the bag (not eggs) at bot start": {},
      "show_at_start": true,
      "// if 'show_count' is true, it will show the amount of each pokemon (minimum 1)": {},
      "show_count": false,
      "// if 'show_candies' is true, it will show the amount of candies for each pokemon": {},
      "show_candies": false,
      "// 'pokemon_info' parameter define which info to show for each pokemon": {},
      "// the available options are": {},
      "// ['cp', 'iv_ads', 'iv_pct', 'ivcp', 'ncp', 'level', 'hp', 'moveset', 'dps']": {},
      "pokemon_info": ["cp", "iv_pct"]
    },
    "walk_max": 4.16,
    "walk_min": 2.16,
    "alt_min": 500,
    "alt_max": 1000,
    "sleep_schedule": [
      {
        "time": "23:00",
        "duration": "8:30",
        "time_random_offset": "00:30",
        "duration_random_offset": "00:30",
        "wake_up_at_location": "korpsbrug, haarlem, the netherlands"
      }
    ],
    "gps_default_altitude": 8.0,
    "replicate_gps_xy_noise": false,
    "replicate_gps_z_noise": false,
    "gps_xy_noise_range": 0.000125,
    "gps_z_noise_range": 12.5,
    "debug": false,
    "test": false,
    "walker_limit_output": false,
    "health_record": true,
    "location_cache": false,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging": {
      "color": true,
      "show_datetime": true,
      "show_process_name": true,
      "show_log_level": true,
      "show_thread_name": false
    },
    "catch": {
      "any": {"candy_threshold" : 400 ,"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },

    "release": {
      "any": {"keep_best_cp": 3, "keep_best_iv": 4},
      "// any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 best (based on IV) Zubat:": {},
      "// Keep no more than 3 best IV pokemon for every pokemon type": {},
      "// any": {"keep_best_iv": 3},
      "// Discard all pokemon in bag except 100 pokemon with best CP": {},
      "// all": {"keep_best_cp": 100},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Example of custom order of static criterion": {},
      "// Zubat": {"keep_best_custom": "iv, cp, hp_max", "amount":2}
    },
    "vips" : {
        "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    },
	"websocket": {
		"start_embedded_server": true,
		"server_url": "127.0.0.1:4000"
	}
}
`

### Output when issue occurred

see above

### Steps to Reproduce
bash run.sh
changed user name and password in auth.json (which also worked before, and in the phone app)
tried a different google map api (new or old, doesn't work)
tried other os

### Other Information
OS: 
 
osx and debian jessie
Branch: 
master (tried dev yesterday night 11/9 but didn't work either, same error)
Git Commit: 
11123a82cb18c172a262dc9e46e7b2c175666828
Python Version: 
 Python 2.7.12

**Comment by rawgni** [comment]
@fluxpiada can you post the output when you tried it on dev ?

**Comment by fluxpiada** [comment]
on osx
it's a bit better...
`2016-09-12 13:44:34,307 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-12 13:44:34,368 [       cli] [INFO] commit: 07d9b589
2016-09-12 13:44:34,376 [       cli] [INFO] Configuration initialized
2016-09-12 13:44:34,377 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-09-12 13:44:34,377 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-09-12 13:44:34,408 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
[2016-09-12 13:44:35] [yoyo.migrations] [INFO] Applying pokemongobot
[2016-09-12 13:44:35] [yoyo.migrations] [INFO]  - applying step 0
[2016-09-12 13:44:35] [yoyo.migrations] [INFO] Marking pokemongobot applied
[2016-09-12 13:44:35] [yoyo.migrations] [INFO] Applying catch_log
[2016-09-12 13:44:35] [yoyo.migrations] [INFO]  - applying step 0
[2016-09-12 13:44:35] [yoyo.migrations] [INFO] Marking catch_log applied
[2016-09-12 13:44:35] [yoyo.migrations] [INFO] Applying eggs_hatched_log
[2016-09-12 13:44:35] [yoyo.migrations] [INFO]  - applying step 0
[2016-09-12 13:44:35] [yoyo.migrations] [INFO] Marking eggs_hatched_log applied
[2016-09-12 13:44:35] [yoyo.migrations] [INFO] Applying evolve_log
[2016-09-12 13:44:35] [yoyo.migrations] [INFO]  - applying step 0
[2016-09-12 13:44:35] [yoyo.migrations] [INFO] Marking evolve_log applied
[2016-09-12 13:44:35] [yoyo.migrations] [INFO] Applying pokestop_log
[2016-09-12 13:44:35] [yoyo.migrations] [INFO]  - applying step 0
[2016-09-12 13:44:35] [yoyo.migrations] [INFO] Marking pokestop_log applied
[2016-09-12 13:44:35] [yoyo.migrations] [INFO] Applying softban_log
[2016-09-12 13:44:35] [yoyo.migrations] [INFO]  - applying step 0
[2016-09-12 13:44:35] [yoyo.migrations] [INFO] Marking softban_log applied
[2016-09-12 13:44:35] [yoyo.migrations] [INFO] Applying transfer_log
[2016-09-12 13:44:35] [yoyo.migrations] [INFO]  - applying step 0
[2016-09-12 13:44:35] [yoyo.migrations] [INFO] Marking transfer_log applied
[2016-09-12 13:44:35] [yoyo.migrations] [INFO] Applying vanish_log
[2016-09-12 13:44:35] [yoyo.migrations] [INFO]  - applying step 0
[2016-09-12 13:44:35] [yoyo.migrations] [INFO] Marking vanish_log applied
(4347) wsgi starting up on http://127.0.0.1:4000
[2016-09-12 13:44:35] [PokemonGoBot] [WARNING] SleepSchedule is disabled. Config structure has been changed, see docs/configuration_files.md for more information
[2016-09-12 13:44:35] [PokemonGoBot] [INFO] Setting start location.
_inventory was not initialized
_inventory was not initialized
[2016-09-12 13:44:35] [       cli] [INFO] 
[2016-09-12 13:44:35] [       cli] [INFO] Ran for 0:00:00
[2016-09-12 13:44:35] [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
[2016-09-12 13:44:35] [       cli] [INFO] Travelled 0.00km
[2016-09-12 13:44:35] [       cli] [INFO] Visited 0 stops
[2016-09-12 13:44:35] [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
[2016-09-12 13:44:35] [       cli] [INFO] Threw 0 pokeballs
[2016-09-12 13:44:35] [       cli] [INFO] Earned 0 Stardust
[2016-09-12 13:44:35] [       cli] [INFO] Hatched eggs 0
[2016-09-12 13:44:35] [       cli] [INFO] 
[2016-09-12 13:44:35] [       cli] [INFO] Highest CP Pokemon: 
[2016-09-12 13:44:35] [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 841, in <module>
    main()
  File "pokecli.py", line 189, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 144, in start_bot
    bot.start()
  File "/Users/FloPro/PokemonGo-Bot-dev/pokemongo_bot/__init__.py", line 141, in start
    self._setup_api()
  File "/Users/FloPro/PokemonGo-Bot-dev/pokemongo_bot/__init__.py", line 917, in _setup_api
    self._set_starting_position()
  File "/Users/FloPro/PokemonGo-Bot-dev/pokemongo_bot/__init__.py", line 1110, in _set_starting_position
    location = self.get_pos_by_name(location_str.replace(" ", ""))
  File "/Users/FloPro/PokemonGo-Bot-dev/pokemongo_bot/__init__.py", line 1237, in get_pos_by_name
    return float(loc.latitude), float(loc.longitude), float(loc.altitude)
AttributeError: 'NoneType' object has no attribute 'latitude'
[2016-09-12 13:44:35] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/FloPro/PokemonGo-Bot-dev/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/FloPro/PokemonGo-Bot-dev/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/FloPro/PokemonGo-Bot-dev/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/FloPro/PokemonGo-Bot-dev/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/FloPro/PokemonGo-Bot-dev/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/FloPro/PokemonGo-Bot-dev/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/FloPro/PokemonGo-Bot-dev/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/FloPro/PokemonGo-Bot-dev/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
[2016-09-12 13:44:35] [sentry.errors.uncaught] [ERROR] [u"AttributeError: 'NoneType' object has no attribute 'latitude'", u'  File "pokecli.py", line 841, in <module>', u'  File "pokecli.py", line 189, in main', u'  File "pokecli.py", line 144, in start_bot', u'  File "pokemongo_bot/__init__.py", line 141, in start', u'  File "pokemongo_bot/__init__.py", line 917, in _setup_api', u'  File "pokemongo_bot/__init__.py", line 1110, in _set_starting_position', u'  File "pokemongo_bot/__init__.py", line 1237, in get_pos_by_name']
ma 12 sep 2016 13:44:35 CEST Pokebot  Stopped.

`
now on dev git commit 07d9b589a16e831b95e2c92c3eae1fcd02f6a96c (Author: Simba Zhang <solderzzc@users.noreply.github.com>
Date:   Sun Sep 11 22:31:16 2016 -0700)
but 2 other errors also on: 
`bash setup.sh -e` 
gives 66 errors of type 
`encrypt.c:11349:41: note: place parentheses around the '&' expression to silence this warning`
also during 
`bash.setup.sh -i`
`Error: No devel block is defined for protobuf`

**Comment by rawgni** [comment]
@fluxpiada looks like there is something wrong with setting location. can you post the location inside your auth.json ?

**Comment by fluxpiada** [comment]
thanks, there was an error! so your dev branch has fixed my issue!!
