### ISSUE TITLE
UTF-8 Unicode Error

### ISSUE THREAD

**Issue by ikariya69** [PokemonGoF/PokemonGo-Bot#5424]
Bot seems running but sometimes have this error :

```
127.0.0.1 - - [13/Sep/2016 17:31:58] code 400, message Bad HTTP/0.9 request type ('\x81\xfe\x01"(\xd1\x7f\xbc\x1c\xe3$\x9eJ\xbe')
Traceback (most recent call last):
  File "/home/pi/Documents/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/greenpool.py", line 82, in _spawn_n_impl
    func(*args, **kwargs)
  File "/home/pi/Documents/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/wsgi.py", line 719, in process_request
    proto.__init__(sock, address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 342, in handle
    self.handle_one_request()
  File "/home/pi/Documents/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/wsgi.py", line 351, in handle_one_request
    if not self.parse_request():
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 281, in parse_request
    "Bad HTTP/0.9 request type (%r)" % command)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 458, in log_message
    format%args))
  File "/home/pi/Documents/PokemonGo-Bot/lib/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
  File "/home/pi/Documents/PokemonGo-Bot/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x81 in position 38: invalid start byte
```

looks like it's related to regional settings and websocket, it crashes especially when there's web access to the UI.

tried to change the locales to en_US.UTF-8 but errors still appears

config.json is the original default example

### Steps to Reproduce
install bot via ./setup.sh -i with fr_FR.UTF-8 settings

### Other Information
OS: 
raspbian

Branch: 
master

**Comment by ikariya69** [comment]
looks like it's the web UI causing these errors, if i do not start it they don't appear in the bot console

**Comment by javajohnHub** [comment]
Closing issue. If problem persists submit an issue to the web ui.
