### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by ukos-git** [PokemonGoF/PokemonGo-Bot#5450]
Hi there just wondering. I installed the bot on another pc and it is not working (same config and auth files).

Probably some authentification with the google site is not working. 
I already cleared my ~/.ssh/ and created a new pem.
The name and password in the auth file are fine. Encoding of the file is utf8.
I also created a new auth.json file. Still no work. Has to do something with the system. Some requirements not met or sth.

Anyone any ideas about the error message? I am clueless.

**Output when issue occurred**
matthias@uk-work:~/programs/pokemongo/PokemonGo-Bot$ ./run.sh 
2016-09-15 10:39:18,277 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-15 10:39:18,280 [       cli] [INFO] commit: 9e964199
2016-09-15 10:39:18,282 [       cli] [INFO] Configuration initialized
2016-09-15 10:39:18,282 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-09-15 10:39:18,283 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-09-15 10:39:18,286 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-09-15 10:39:18,346 [PokemonGoBot] [INFO] Setting start location.
2016-09-15 10:39:18,436 [PokemonGoBot] [INFO] Location found I_REMOVED_THIS
2016-09-15 10:39:18,437 [PokemonGoBot] [INFO] Now at (I_REMOVED_THIS)
2016-09-15 10:39:18,437 [PokemonGoBot] [INFO] Login procedure started.
_inventory was not initialized
_inventory was not initialized
2016-09-15 10:39:18,453 [       cli] [INFO] 
2016-09-15 10:39:18,454 [       cli] [INFO] Ran for 0:00:00
2016-09-15 10:39:18,454 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-09-15 10:39:18,454 [       cli] [INFO] Travelled 0.00km
2016-09-15 10:39:18,454 [       cli] [INFO] Visited 0 stops
2016-09-15 10:39:18,454 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
2016-09-15 10:39:18,454 [       cli] [INFO] Threw 0 pokeballs
2016-09-15 10:39:18,454 [       cli] [INFO] Earned 0 Stardust
2016-09-15 10:39:18,454 [       cli] [INFO] Hatched eggs 0
2016-09-15 10:39:18,454 [       cli] [INFO] 
2016-09-15 10:39:18,454 [       cli] [INFO] Highest CP Pokemon: 
2016-09-15 10:39:18,454 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 841, in <module>
    main()
  File "pokecli.py", line 189, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 144, in start_bot
    bot.start()
  File "/home/matthias/programs/pokemongo/PokemonGo-Bot/pokemongo_bot/__init__.py", line 142, in start
    self._setup_api()
  File "/home/matthias/programs/pokemongo/PokemonGo-Bot/pokemongo_bot/__init__.py", line 947, in _setup_api
    self.login()
  File "/home/matthias/programs/pokemongo/PokemonGo-Bot/pokemongo_bot/__init__.py", line 881, in login
    str(self.config.password))
  File "/home/matthias/programs/pokemongo/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 96, in login
    password=password
  File "/home/matthias/programs/pokemongo/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 94, in set_authentication
    if not self._auth_provider.user_login(username, password):
  File "/home/matthias/programs/pokemongo/PokemonGo-Bot/src/pgoapi/pgoapi/auth_google.py", line 58, in user_login
    user_login = perform_master_login(username, password, self.GOOGLE_LOGIN_ANDROID_ID)
  File "/home/matthias/programs/pokemongo/PokemonGo-Bot/lib/python2.7/site-packages/gpsoauth/__init__.py", line 66, in perform_master_login
    return _perform_auth_request(data)
  File "/home/matthias/programs/pokemongo/PokemonGo-Bot/lib/python2.7/site-packages/gpsoauth/__init__.py", line 22, in _perform_auth_request
    headers={'User-Agent': useragent})
  File "/home/matthias/programs/pokemongo/PokemonGo-Bot/lib/python2.7/site-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/matthias/programs/pokemongo/PokemonGo-Bot/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/matthias/programs/pokemongo/PokemonGo-Bot/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/matthias/programs/pokemongo/PokemonGo-Bot/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/matthias/programs/pokemongo/PokemonGo-Bot/lib/python2.7/site-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
2016-09-15 10:39:18,463 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/matthias/programs/pokemongo/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/matthias/programs/pokemongo/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/matthias/programs/pokemongo/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/matthias/programs/pokemongo/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/matthias/programs/pokemongo/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/matthias/programs/pokemongo/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/matthias/programs/pokemongo/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/matthias/programs/pokemongo/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 848, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-09-15 10:39:18,464 [sentry.errors.uncaught] [ERROR] [u'SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)', u'  File "pokecli.py", line 841, in <module>', u'  File "pokecli.py", line 189, in main', u'  File "pokecli.py", line 144, in start_bot', u'  File "pokemongo_bot/__init__.py", line 142, in start', u'  File "pokemongo_bot/__init__.py", line 947, in _setup_api', u'  File "pokemongo_bot/__init__.py", line 881, in login', u'  File "pokemongo_bot/api_wrapper.py", line 96, in login', u'  File "pgoapi/pgoapi.py", line 94, in set_authentication', u'  File "pgoapi/auth_google.py", line 58, in user_login', u'  File "gpsoauth/__init__.py", line 66, in perform_master_login', u'  File "gpsoauth/__init__.py", line 22, in _perform_auth_request', u'  File "requests/api.py", line 111, in post', u'  File "requests/api.py", line 57, in request', u'  File "requests/sessions.py", line 475, in request', u'  File "requests/sessions.py", line 585, in send', u'  File "requests/adapters.py", line 477, in send']
Do 15. Sep 10:39:18 CEST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

### Steps to Reproduce
clone, checkout dev, setup.sh -i, setup.sh -u etc.

### Other Information
OS: debian8
Branch: dev
Git Commit:  9e964199af8c0bbe04d64f56d3b0bd5f83a9d798
Python Version: Python 2.7.9

**Comment by ukos-git** [comment]
maybe something to do with `inventory was not initialized`?

**Comment by Gobberwart** [comment]
Google login appears to be broken at the moment. Unfortunately that's in pgoapi, not in this bot, so we can't fix directly.

**Comment by ukos-git** [comment]
I will try the new fix from https://github.com/PokemonGoF/PokemonGo-Bot/issues/5561 when I have access to the pc again.
