### ISSUE TITLE
Regular Session stale, followed by heartbeat crash

### ISSUE THREAD

**Issue by Anakin5** [PokemonGoF/PokemonGo-Bot#5455]
### Expected Behavior
No session stale. And, if it ever happen, reconnect and continue to work.

### Actual Behavior
Regular session stale and position is not updated anymore after reconnexion.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
```
{
    "auth_service": "ptc",
    "username": "***",
    "password": "***",
    "location": "***",
    "location_cache": true,
    "gmapkey": "***",
    "encrypt_location": "",
    "//websocket": {
        "start_embedded_server": true,
        "server_url": "127.0.0.1:4000"
    },
    "heartbeat_threshold": 10,
    "enable_social": false,
    "live_config_update": {
        "enabled": false,
        "tasks_only": false
    },
    "tasks": [
        {
            "type": "CompleteTutorial",
            "config": {
                "enabled": true,
                "nickname": "***",
                "team": 1
            }
        },
        {
            "type": "CollectLevelUpReward",
            "config": {
                "collect_reward": true,
                "level_limit": -1
            }
        },
        {
            "type": "IncubateEggs",
            "config": {
                "infinite_longer_eggs_first": false,
                "breakable_longer_eggs_first": true,
                "min_interval": 120,
                "infinite": [
                    10,
                    2,
                    5
                ],
                "breakable": [
                    10
                ]
            }
        },
        {
            "type": "PokemonOptimizer",
            "config": {
                "enabled": true,
                "min_slots_left": 5,
                "transfer": true,
                "transfer_wait_min": 3,
                "transfer_wait_max": 5,
                "evolve": true,
                "evolve_time": 25,
                "evolve_for_xp": true,
                "evolve_only_with_lucky_egg": false,
                "evolve_count_for_lucky_egg": 80,
                "may_use_lucky_egg": true,
                "upgrade": true,
                "upgrade_level": 60,
                "buddy": "Dragonite",
                "groups": {
                    "gym": [
                        "Dragonite",
                        "Snorlax",
                        "Lapras",
                        "Arcanine"
                    ]
                },
                "rules": [
                    {
                        "mode": "by_family",
                        "top": 1,
                        "sort": [
                            "iv"
                        ],
                        "evolve": {
                            "iv": 0.9
                        }
                    },
                    {
                        "mode": "by_family",
                        "top": 1,
                        "sort": [
                            "ncp"
                        ],
                        "evolve": {
                            "ncp": 0.9
                        }
                    },
                    {
                        "mode": "by_family",
                        "top": 1,
                        "sort": [
                            "cp"
                        ]
                    },
                    {
                        "mode": "by_family",
                        "names": [
                            "gym"
                        ],
                        "top": 3,
                        "sort": [
                            "cp"
                        ],
                        "evolve": {
                            "iv": 0.9,
                            "ncp": 0.9
                        },
                        "upgrade": {
                            "iv": 0.9,
                            "ncp": 0.9
                        }
                    }
                ]
            }
        },
        {
            "type": "NicknamePokemon",
            "config": {
                "enabled": false,
                "nickname_template": "{iv_pct}_{iv_attack:X}{iv_defense:X}{iv_stamina:X}_{attack_pct}"
            }
        },
        {
            "type": "RecycleItems",
            "config": {
                "enable": true,
                "min_empty_space": 5,
                "max_balls_keep": 180,
                "max_potions_keep": 20,
                "max_berries_keep": 80,
                "max_revives_keep": 20,
                "recycle_wait_min": 3,
                "recycle_wait_max": 5
            }
        },
        {
            "type": "CatchPokemon",
            "config": {
                "enabled": true,
                "catch_visible_pokemon": true,
                "catch_lured_pokemon": true,
                "catch_incensed_pokemon": true,
                "min_ultraball_to_keep": 5,
                "berry_threshold": 0.4,
                "vip_berry_threshold": 0.9,
                "treat_unseen_as_vip": true,
                "daily_catch_limit": 800,
                "catch_throw_parameters": {
                    "excellent_rate": 0.3,
                    "great_rate": 0.5,
                    "nice_rate": 0.1,
                    "normal_rate": 0.1,
                    "spin_success_rate": 0.95,
                    "hit_rate": 0.95
                },
                "catch_simulation": {
                    "flee_count": 3,
                    "flee_duration": 2,
                    "catch_wait_min": 3,
                    "catch_wait_max": 6,
                    "berry_wait_min": 3,
                    "berry_wait_max": 5,
                    "changeball_wait_min": 3,
                    "changeball_wait_max": 5,
                    "newtodex_wait_min": 20,
                    "newtodex_wait_max": 30
                }
            }
        },
        {
            "type": "SpinFort",
            "config": {
                "ignore_item_count": true,
                "spin_wait_min": 3,
                "spin_wait_max": 5,
                "daily_spin_limit": 1900
            }
        },
        {
            "type": "PokemonHunter",
            "config": {
                "enabled": true,
                "max_distance": 1500,
                "hunt_all": false,
                "hunt_vip": true,
                "hunt_pokedex": true
            }
        },
        {
            "type": "CampFort",
            "config": {
                "enabled": true,
                "max_distance": 1500,
                "min_forts_count": 3,
                "min_lured_forts_count": 1,
                "camping_time": 1800,
                "moving_time": 600
            }
        },
        {
            "type": "MoveToFort",
            "config": {
                "enabled": true,
                "lure_attraction": true,
                "lure_max_distance": 300,
                "ignore_item_count": true,
                "walker": "PolylineWalker",
                "log_interval": 5
            }
        }
    ],
    "map_object_cache_time": 10,
    "forts": {
        "avoid_circles": true,
        "max_circle_size": 50,
        "cache_recent_forts": true
    },
    "walk_max": 2,
    "walk_min": 1,
    "alt_min": 2.75,
    "alt_max": 4.5,
    "sleep_schedule": {
        "enabled": true,
        "enable_reminder": false,
        "reminder_interval": 600,
        "entries": [
            {
                "enabled": false,
                "time": "23:54",
                "duration": "7:46",
                "time_random_offset": "00:24",
                "duration_random_offset": "00:43",
                "wake_up_at_location": "***"
            }
        ]
    },
    "gps_default_altitude": 8.0,
    "replicate_gps_xy_noise": false,
    "replicate_gps_z_noise": false,
    "gps_xy_noise_range": 0.00025,
    "gps_z_noise_range": 12.5,
    "debug": false,
    "test": false,
    "walker_limit_output": true,
    "health_record": false,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging": {
        "color": true,
        "show_datetime": true,
        "show_process_name": false,
        "show_log_level": false,
        "show_thread_name": false
    },
    "pokemon_bag": {
        "show_at_start": false,
        "show_count": true,
        "pokemon_info": [
            "cp",
            "ncp",
            "iv_pct"
        ]
    },
    "catch": {
        "any": {
            "always_catch": true
        }
    },
    "vips": {
        "any": {
            "catch_above_cp": 1500,
            "catch_above_ncp": 0.9,
            "catch_above_iv": 0.9,
            "logic": "or"
        },
        "Moltres": {
        },
        "Zapdos": {
        },
        "Articuno": {
        },
        "Mewtwo": {
        },
        "Mew": {
        },
        "Growlithe": {
        },
        "Arcanine": {
        },
        "Muk": {
        },
        "Gyarados": {
        },
        "Lapras": {
        },
        "Vaporeon": {
        },
        "Jolteon": {
        },
        "Flareon": {
        },
        "Snorlax": {
        },
        "Dratini": {
        },
        "Dragonair": {
        },
        "Dragonite": {
        }
    }
}
```

### Output when issue occurred
After relogging, position does not update. Probably because heartbeat dead.

```
[2016-09-15 22:07:45] Moving to destination at 413.27 meters: 4 forts, 1 lured
[2016-09-15 22:08:44] Moving to destination at 342.87 meters: 4 forts, 1 lured
[2016-09-15 22:09:46] Moving to destination at 313.29 meters: 4 forts, 1 lured
[2016-09-15 22:10:38] Session stale, re-logging in.
[2016-09-15 22:10:38] Login procedure started.
Exception in thread Thread-348:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 1073, in run
    self.function(*self.args, **self.kwargs)
  File "G:\Projects\PokemonGo-Bot\pokemongo_bot\__init__.py", line 1300, in heartbeat
    responses = request.call()
  File "g:\projects\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 225, in call
    raise NotLoggedInException()
NotLoggedInException

[2016-09-15 22:11:11] Login successful.
[2016-09-15 22:11:11] Found encrypt.dll! Platform: win32 encrypt.dll directory: G:\Projects\PokemonGo-Bot
[2016-09-15 22:11:11] Moving to destination at 264.71 meters: 4 forts, 1 lured
[2016-09-15 22:12:12] Moving to destination at 264.71 meters: 4 forts, 1 lured
```

### Other Information
OS: Windows
Branch: dev
Git Commit: HEAD
Python Version: 2.7.12

**Comment by clubza1** [comment]
same here
