### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte 2016-09-14 16:40:58,431 [sentry.errors.uncaught]

### ISSUE THREAD

**Issue by maximm98** [PokemonGoF/PokemonGo-Bot#5464]
### Expected Behavior

for the bot to stay running and not crash.

### Actual Behavior

The bot is crashing.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

{
```
	"auth_service": "google",
	"username": "",
	"password": "",
	"location": "52.39037297896968,4.828920364379883",
	"gmapkey": "",
	"tasks": [{
		"type": "HandleSoftBan",
		"$$hashKey": "object:21"
	}, {
		"type": "CollectLevelUpReward",
		"$$hashKey": "object:22"
	}, {
		"type": "IncubateEggs",
		"config": {
			"longer_eggs_first": true
		},
		"$$hashKey": "object:23"
	}, {
		"type": "TransferPokemon",
		"$$hashKey": "object:24"
	}, {
		"type": "EvolveAll",
		"config": {
			"evolve_all": "all",
			"first_evolve_by": "iv",
			"evolve_above_cp": 100,
			"evolve_above_iv": 0.7,
			"logic": "and",
			"evolve_speed": 20,
			"use_lucky_egg": false
		},
		"$$hashKey": "object:25"
	}, {
		"type": "RecycleItems",
		"config": {
			"item_filter": {
				"Pokeball": {
					"keep": 100
				},
				"Potion": {
					"keep": 10
				},
				"Super Potion": {
					"keep": 20
				},
				"Hyper Potion": {
					"keep": 30
				},
				"Revive": {
					"keep": 30
				},
				"Razz Berry": {
					"keep": 100
				}
			}
		},
		"$$hashKey": "object:26"
	}, {
		"type": "CatchVisiblePokemon",
		"$$hashKey": "object:27"
	}, {
		"type": "CatchLuredPokemon",
		"$$hashKey": "object:28"
	}, {
		"type": "SpinFort",
		"$$hashKey": "object:29"
	}, {
		"type": "MoveToFort",
		"config": {
			"lure_attraction": true,
			"lure_max_distance": 2000
		},
		"$$hashKey": "object:30"

	}],
	"map_object_cache_time": 5,
	"forts": {
		"avoid_circles": true,
		"max_circle_size": 50
	},
	"websocket_server": false,
	"walk": "25",
	"action_wait_min": 1,
	"action_wait_max": 4,
	"debug": false,
	"test": false,
	"health_record": true,
	"location_cache": true,
	"distance_unit": "mi",
	"reconnecting_timeout": 15,
	"evolve_captured": "NONE",
	"catch_randomize_reticle_factor": 1,
	"catch_randomize_spin_factor": 1,
	"catch": {
		"any": {
			"catch_above_cp": 0,
			"catch_above_iv": 0,
			"logic": "or"
		}
	},
	"release": {
		"any": {
			"release_below_cp": 0,
			"release_below_iv": 0,
			"logic": "or"
		}
	},
	"vips": {
		"Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
		"any": {
			"catch_above_cp": 1200,
			"catch_above_iv": 0.9,
			"logic": "or"
		},
		"Lapras": {},
		"Moltres": {},
		"Zapdos": {},
		"Articuno": {},
		"// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
		"Mewtwo": {},
		"Dragonite": {},
		"Snorlax": {},
		"// Mew evolves to Mewtwo": {},
		"Mew": {},
		"Arcanine": {},
		"Vaporeon": {},
		"Gyarados": {},
		"Exeggutor": {},
		"Muk": {},
		"Weezing": {},
		"Flareon": {}
	}
}
```

### Output when issue occurred

```
Traceback (most recent call last):
  File "pokecli.py", line 802, in <module>
    main()
  File "pokecli.py", line 149, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 109, in start_bot
    initialize_task(bot, config)
  File "pokecli.py", line 93, in initialize_task
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "C:\Test\PokemonGo-Bot\pokemongo_bot\tree_config_builder.py", line 37, in build
    raise ConfigException('The EvolveAll task has been renamed to EvolvePokemon')
pokemongo_bot.tree_config_builder.ConfigException: The EvolveAll task has been renamed to EvolvePokemon
2016-09-14 16:40:58,397 [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\raven\transport\threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "C:\Python27\lib\site-packages\raven\transport\http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 494, in open
    response = self._open(req, data)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 512, in _open
    '_open', req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python27\lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 895, in _send_output
    msg += message_body
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
2016-09-14 16:40:58,431 [sentry.errors.uncaught] [ERROR] [u'ConfigException: The EvolveAll task has been renamed to EvolvePokemon', u'  File "pokecli.py", line 802, in <module>', u'  File "pokecli.py", line 149, in main', u'  File "pokecli.py", line 109, in start_bot', u'  File "pokecli.py", line 93, in initialize_task', u'  File "C:\\Test\\PokemonGo-Bot\\pokemongo_bot\\tree_config_builder.py", line 37, in build']

 Something went wrong and the bot needed to be restarted. Please investigate the cause.


Waiting for 19 seconds, press a key to continue ...




```

### Steps to Reproduce

Restarting the bot.

### Other Information
OS: Windows 10
 
Branch: 
 
Git Commit: 
 
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by PokemonGoZ** [comment]
Make sure you follow the readme.md file that says you need a **encrypt.dll** file.

**Comment by rawgni** [comment]
```
  File "C:\Test\PokemonGo-Bot\pokemongo_bot\tree_config_builder.py", line 37, in build
    raise ConfigException('The EvolveAll task has been renamed to EvolvePokemon')
pokemongo_bot.tree_config_builder.ConfigException: The EvolveAll task has been renamed to EvolvePokemon
```

**Comment by DBa2016** [comment]
Configuration issue.

**Comment by maximm98** [comment]
I've had a encrypt.dll file

**Comment by Gobberwart** [comment]
Self-explanatory: "ConfigException: The EvolveAll task has been renamed to EvolvePokemon". Fix your config.json as it looks like a very old one.
