### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by Wilbertvn** [PokemonGoF/PokemonGo-Bot#5519]
### Expected Behavior

The script is not loading the "encrypt32bit.dll" nor the "encrypt32bit.dll'. I tried each one and also both inside: /PokemonGo-Bot/, /pokemongo_bot/ and /windows_bat/...

### Actual Behavior

The classic error that it's not a Win32 application.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

Not sure if I have to put my config from the downloaded or the installed one that I get from using the PokemonGo-Bot-Install.bat installer.. But I used clean ones. The renamed .example.

### Output when issue occurred

The usual error:

Waiting for  0 seconds, press a key to continue ...
Traceback (most recent call last):
  File "pokecli.py", line 46, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException, NoPlayerPositionSetException
  File "c:\python27\src\pgoapi\pgoapi\__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "c:\python27\src\pgoapi\pgoapi\pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "c:\python27\src\pgoapi\pgoapi\rpc_api.py", line 47, in <module>
    from pgoapi.utilities import to_camel_case, get_time, get_format_time_diff, Rand48, long_to_bytes, generate_location_hash_by_seed, generate_location_hash, generate_request_hash, f2i
  File "c:\python27\src\pgoapi\pgoapi\utilities.py", line 30, in <module>
    import xxhash
ImportError: DLL load failed: %1 is not a valid Win32 application.

### Steps to Reproduce

I've seen this issue multiple times and followed them. Tried to download all kinds of 'encrypt.dll' and encrypt_64.dll' all over the place, but still getting that same result. 

### Other Information
OS: Win10 x64
 
Branch: master
 
Git Commit: ???
 
Python Version: Python 2.7.12 AND 2.7.12 (64-bits) (in programs) but python -V says the non-64-bits.
 
Any other relevant files/configs (eg: path files) Nothing, it's a clean install..

I've tried to update it. Which didn't work. And now reinstalling doesn't seems to do the trick either.

**Comment by Wilbertvn** [comment]
Ok, I fixed it myself. I uninstalled the 64bits Python and that's it. :P Kinda weird that there's only a option to install 64bit stuff from the installer.
