### ISSUE TITLE
Unsupported operand

### ISSUE THREAD

**Issue by chadsaun** [PokemonGoF/PokemonGo-Bot#554]
```
Traceback (most recent call last):
  File "pokecli.py", line 197, in <module>
    main()
  File "pokecli.py", line 183, in main
    bot.start()
  File "/Users/me/Development/Personal/PokemonGo-Bot/pokemongo_bot/__init__.py", line 32, in start
    self.stepper = Stepper(self)
  File "/Users/me/Development/Personal/PokemonGo-Bot/pokemongo_bot/stepper.py", line 30, in __init__
    self.steplimit2 = self.steplimit**2
TypeError: unsupported operand type(s) for ** or pow(): 'unicode' and 'int'
```

**Comment by chadsaun** [comment]
Problem was in my config.  Some of my number variables were string and should've been integers.
