### ISSUE TITLE
Null Reference - After Account Summary Display

### ISSUE THREAD

**Issue by BenRodney** [PokemonGoF/PokemonGo-Bot#5549]
### Expected Behavior

Journey starts, pokemon transfered, pokestops farmed.

### Actual Behavior

Null reference exception after player summary is written to the console.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

Ptc
xxxxxxxxxxxxxx
xxxxxxxxxxxxxx
37.808966
-122.410153
0
9.5
500
True
True
3
True
800

5000
1
False
True
90
True
True
True
True
False
True
en
True
45
True
True

True
False

### Output when issue occurred

14:55] ItemRazzBerry Qty: 5
[19:14:55] ItemPokeBall Qty: 58
[19:14:55] ItemGreatBall Qty: 24
[19:14:55] ItemUltraBall Qty: 12
[19:14:55] ItemPotion Qty: 19
[19:14:55] ItemSuperPotion Qty: 6
[19:14:55] ItemHyperPotion Qty: 8
[19:14:55] ItemMaxPotion Qty: 5
[19:14:55] ItemIncubatorBasicUnlimited Qty: 1
[19:14:56] ItemIncubatorBasic Qty: 0
[19:14:56] ItemRevive Qty: 14
[19:14:56] ItemIncenseOrdinary Qty: 0
[19:14:56] ItemLuckyEgg Qty: 0
[19:14:56] ItemTroyDisk Qty: 1
[19:14:56] Items: 153/400
[19:14:56] ------------------------------------------------------------
[19:14:57] Egg (5km) need to walk 4.92 km.
[19:14:57] Stoping to transfer some Pokemons.
[19:14:59] Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PokemonGo.RocketAPI.Logic.Logic.<TransferDuplicatePokemon>d__56.MoveNext() in C:\Users\Matt\Source\Repos\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 1618
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__32.MoveNext() in C:\Users\Matt\Source\Repos\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 220
[19:14:59] Starting again in 60 seconds...

### Steps to Reproduce

Start the application...

### Other Information
OS: Windows 10
 
Branch: Main
 
Git Commit: master
 
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by Gobberwart** [comment]
That's not this bot.
