### ISSUE TITLE
When optimizer tried to transfer it crashes bot

### ISSUE THREAD

**Issue by beltoft** [PokemonGoF/PokemonGo-Bot#5563]
### Expected Behavior
optimizer runs

### Actual Behavior
bot crashes when bag limit is reached

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
	{
			"type": "PokemonOptimizer",
			"config": {
				"enabled": true,
				"min_slots_left": 5,
        "action_wait_min": 2,
        "action_wait_max": 4,
        "transfer": true,
				"evolve": true,
        "evolve_to_final": false,
				"evolve_time": 20,
				"evolve_for_xp": true,
				"evolve_only_with_lucky_egg": false,
				"evolve_count_for_lucky_egg": 60,
				"may_use_lucky_egg": true,
				"upgrade": true,
				"upgrade_level": 64,
        "groups": {
					"gym": ["Dragonite", "Snorlax", "Lapras", "Arcanine"]
				},
				"rules": [
					{
						"mode": "by_family",
						"top": 1,
						"sort": ["iv"],
						"evolve": {"iv": 1.0},
						"upgrade": {"iv": 1.0}
					},
					{
						"mode": "by_family",
						"top": 1,
						"sort": ["iv"],
						"evolve": {"iv": 0.9}
					},
                    
          {
						"mode": "by_family",
						"top": 1,
						"sort": ["ncp"],
						"evolve": {"ncp": 0.9}
						
					}
          
				]
			}
		},

### Output when issue occurred

[2016-09-20 13:37:14] [PokemonOptimizer] [INFO] Pokemon Bag: 246 / 250
[2016-09-20 13:37:15] [       cli] [INFO]
[2016-09-20 13:37:15] [       cli] [INFO] Ran for 0:00:12
[2016-09-20 13:37:15] [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
[2016-09-20 13:37:15] [       cli] [INFO] Travelled 0.00km
[2016-09-20 13:37:15] [       cli] [INFO] Visited 0 stops
[2016-09-20 13:37:15] [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
[2016-09-20 13:37:15] [       cli] [INFO] Threw 0 pokeballs
[2016-09-20 13:37:15] [       cli] [INFO] Earned 0 Stardust
[2016-09-20 13:37:15] [       cli] [INFO] Hatched eggs 0
[2016-09-20 13:37:15] [       cli] [INFO] Next egg hatches in 1.35 km
[2016-09-20 13:37:15] [       cli] [INFO]
[2016-09-20 13:37:15] [       cli] [INFO] Highest CP Pokemon:
[2016-09-20 13:37:15] [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 843, in <module>
    main()
  File "pokecli.py", line 202, in main
    bot.tick()
  File "/home/beltoft/PokemonGo-Bot/pokemongo_bot/__init__.py", line 721, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/beltoft/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_optimizer.py", line 186, in work
    transfer, evolve, upgrade, xp = self.get_evolution_plan(family_id, pokemon_list, keep, try_evolve, try_upgrade)
  File "/home/beltoft/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_optimizer.py", line 511, in get_evolution_plan
    for i in range(pokemon.level, upgrade_level, 0.5):
TypeError: range() integer end argument expected, got float.
Tue Sep 20 13:37:15 CEST 2016 Pokebot  Stopped.

### Other Information
OS: 
 
Branch: 
 
Git Commit: 
 
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by Anakin5** [comment]
PR merged
