### ISSUE TITLE
Launch Error

### ISSUE THREAD

**Issue by palakz** [PokemonGoF/PokemonGo-Bot#557]
Getting this error while launching:

```
$ python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 197, in <module>
    main()
  File "pokecli.py", line 174, in main
    config = init_config()
  File "pokecli.py", line 56, in init_config
    load.update(json.load(data))
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 17 column 5 (char 436)
```
OS: Windows 10

**Comment by theebanka** [comment]
Same error here on MacOS

**Comment by surfaace** [comment]
Check your config file(s), i had this problem when my release_config.json was incorrect.

**Comment by palakz** [comment]
Thanks, @surfaace . This issue if fixed for now. :)
