### ISSUE TITLE
Google Login Problem

### ISSUE THREAD

**Issue by jane0815** [PokemonGoF/PokemonGo-Bot#5576]
### Expected Behavior

Bot work with ptc and google login.

### Actual Behavior

ptc working fine, google crashes

### Output when issue occurred

Traceback (most recent call last):
  File "pokecli.py", line 843, in <module>
    main()
  File "pokecli.py", line 191, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 145, in start_bot
    bot.start()
  File "/Users/STONE/PokemonGo-Bot/pokemongo_bot/__init__.py", line 144, in start
    self._setup_api()
  File "/Users/STONE/PokemonGo-Bot/pokemongo_bot/__init__.py", line 983, in _setup_api
    self.login()
  File "/Users/STONE/PokemonGo-Bot/pokemongo_bot/__init__.py", line 917, in login
    str(self.config.password))
  File "/Users/STONE/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 98, in login
    password=password
  File "/Users/STONE/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 94, in set_authentication
    if not self._auth_provider.user_login(username, password):
  File "/Users/STONE/PokemonGo-Bot/src/pgoapi/pgoapi/auth_google.py", line 58, in user_login
    user_login = perform_master_login(username, password, self.GOOGLE_LOGIN_ANDROID_ID, proxy=self._proxy)
AttributeError: AuthGoogle instance has no attribute '_proxy'
[2016-09-20 23:22:39] [MainThread] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
[2016-09-20 23:22:39] [MainThread] [sentry.errors.uncaught] [ERROR] [u"AttributeError: AuthGoogle instance has no attribute '_proxy'", u'  File "pokecli.py", line 843, in <module>', u'  File "pokecli.py", line 191, in main', u'  File "pokecli.py", line 145, in start_bot', u'  File "pokemongo_bot/__init__.py", line 144, in start', u'  File "pokemongo_bot/__init__.py", line 983, in _setup_api', u'  File "pokemongo_bot/__init__.py", line 917, in login', u'  File "pokemongo_bot/api_wrapper.py", line 98, in login', u'  File "pgoapi/pgoapi.py", line 94, in set_authentication', u'  File "pgoapi/auth_google.py", line 58, in user_login']

### Other Information
OS:  Mac OSX
Branch: dev
Git Commit: f4feb098

**Comment by lntn** [comment]
duplicate #5561

**Comment by jane0815** [comment]
Sorry
