### ISSUE TITLE
_inventory was not initialized - Inventory broken!?

### ISSUE THREAD

**Issue by settoger** [PokemonGoF/PokemonGo-Bot#5609]
The bot stopped right after login. It seems that something is broken with the/my inventory.
This happened last night. 
Before this error the bot runs for about 5 hours with no errors at all.

### Actual Behavior
Bot is trying to start, then crashes after login in.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
config is the original **config.json.example** with no changes.

### Output when issue occurred
2016-09-22 13:03:15,188 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-22 13:03:15,196 [       cli] [INFO] commit: 120a20d0
2016-09-22 13:03:15,201 [       cli] [INFO] Configuration initialized
2016-09-22 13:03:15,201 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-09-22 13:03:15,201 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-09-22 13:03:15,213 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
(73188) wsgi starting up on http://0.0.0.0:4000
[2016-09-22 13:03:15] [PokemonGoBot] [INFO] Setting start location.
[2016-09-22 13:03:15] [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
[2016-09-22 13:03:15] [PokemonGoBot] [INFO] Location found: 40.759935, -73.985174 (40.759935, -73.985174, 8.0)
[2016-09-22 13:03:15] [PokemonGoBot] [INFO] Now at (40.759935, -73.985174, 8.0)
[2016-09-22 13:03:15] [PokemonGoBot] [INFO] Login procedure started.
[2016-09-22 13:03:17] [PokemonGoBot] [INFO] Login successful.
[2016-09-22 13:03:17] [PokemonGoBot] [INFO] Found encrypt.so! Platform: darwin encrypt.so directory: /Users/___________/Documents/projects/Pokemon/PokemonGo-Bot
[2016-09-22 13:03:17] [PokemonGoBot] [INFO] 
_inventory was not initialized
_inventory was not initialized
[2016-09-22 13:03:19] [       cli] [INFO] 
[2016-09-22 13:03:19] [       cli] [INFO] Ran for 0:00:04
[2016-09-22 13:03:19] [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
[2016-09-22 13:03:19] [       cli] [INFO] Travelled 0.00km
[2016-09-22 13:03:19] [       cli] [INFO] Visited 0 stops
[2016-09-22 13:03:19] [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
[2016-09-22 13:03:19] [       cli] [INFO] Threw 0 pokeballs
[2016-09-22 13:03:19] [       cli] [INFO] Earned 0 Stardust
[2016-09-22 13:03:19] [       cli] [INFO] Hatched eggs 0
[2016-09-22 13:03:19] [       cli] [INFO] 
[2016-09-22 13:03:19] [       cli] [INFO] Highest CP Pokemon: 
[2016-09-22 13:03:19] [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 843, in <module>
    main()
  File "pokecli.py", line 191, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 145, in start_bot
    bot.start()
  File "/Users/______/Documents/projects/Pokemon/PokemonGo-Bot/pokemongo_bot/__init__.py", line 146, in start
    init_inventory(self)
  File "/Users/______/Documents/projects/Pokemon/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1416, in init_inventory
    _inventory = Inventory(bot)
  File "/Users/______/Documents/projects/Pokemon/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1260, in __init__
    self.refresh()
  File "/Users/______/Documents/projects/Pokemon/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1270, in refresh
    i.refresh(inventory)
  File "/Users/______/Documents/projects/Pokemon/PokemonGo-Bot/pokemongo_bot/inventory.py", line 75, in refresh
    self._data = self.retrieve_data(inventory)
  File "/Users/______/Documents/projects/Pokemon/PokemonGo-Bot/pokemongo_bot/inventory.py", line 71, in retrieve_data
    ret[key] = self.parse(item)
  File "/Users/______/Documents/projects/Pokemon/PokemonGo-Bot/pokemongo_bot/inventory.py", line 490, in parse
    return Pokemon(item)
  File "/Users/______/Documents/projects/Pokemon/PokemonGo-Bot/pokemongo_bot/inventory.py", line 991, in __init__
    assert max(int(self.cp_exact), 10) == self.cp
AssertionError
[2016-09-22 13:03:19] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/______/Documents/projects/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/______/Documents/projects/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/______/Documents/projects/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/______/Documents/projects/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/______/Documents/projects/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/______/Documents/projects/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/______/Documents/projects/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/______/Documents/projects/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
[2016-09-22 13:03:19] [sentry.errors.uncaught] [ERROR] [u'AssertionError', u'  File "pokecli.py", line 843, in <module>', u'  File "pokecli.py", line 191, in main', u'  File "pokecli.py", line 145, in start_bot', u'  File "pokemongo_bot/__init__.py", line 146, in start', u'  File "pokemongo_bot/inventory.py", line 1416, in init_inventory', u'  File "pokemongo_bot/inventory.py", line 1260, in __init__', u'  File "pokemongo_bot/inventory.py", line 1270, in refresh', u'  File "pokemongo_bot/inventory.py", line 75, in refresh', u'  File "pokemongo_bot/inventory.py", line 71, in retrieve_data', u'  File "pokemongo_bot/inventory.py", line 490, in parse', u'  File "pokemongo_bot/inventory.py", line 991, in __init__']
Thu Sep 22 13:03:19 CEST 2016 Pokebot  Stopped.

### Steps to Reproduce
- I have no idea, how to reproduce

### Other Information
OS: 
- OSX 10.11.6
Branch: 
dev and/or master
Git Commit: 
- 120a20d09b3d83fc5c1457cca3735e336b797851
Python Version: 
- 2.7.11
Any other relevant files/configs (eg: path files) 
- Nothing

**Comment by bdevore17** [comment]
I am also experiencing this same issue

**Comment by ukos-git** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/5450#issuecomment-248801011

**Comment by settoger** [comment]
as far as I can see, there is a problem with google login, but I use PTC

**Comment by settoger** [comment]
@bdevore17  any resolving informations?
