### ISSUE TITLE
Nothing works... part 2

### ISSUE THREAD

**Issue by PeshBG** [PokemonGoF/PokemonGo-Bot#5618]
So i was very nervous at my last topic.
here is what i do:
freshly installed win 10(docker didnt worked on win 7(nor the docker tools) some error was displayed)
same error i saw in win 10(so the error is not related to docker)
1. Download the dev zip
2. I run the PokemonGo-Bot-Install.bat(select option 1 then option 2)
3. i run the parts where it asks me for username password location and google key(all 3 options)
 here is the log:

----- Checking OS Architecture ----- 
 
The computer has "64-BIT" architecture. 
 
----- Input Path ----- 
 
The input Path is "c:\pokemon\" 
 
----- Converted Path ----- 
 
The converted Path is "c:\pokemon\" 
 
----- Checking Download Path ----- 
 
 
----- Rechecking Download Path ----- 
 
c:\pokemon\Install-Files exists
 
----- Checking Some Paths ----- 
 
BatchPath is "C:\Users\me\Desktop\PokemonGo-Bot-dev\PokemonGo-Bot-dev\windows_bat\" 
PokemonGo-Bot Path is "c:\pokemon\PokemonGo-Bot" 
 
----- Checking Choice and Bot Installing ----- 
 
Choice was "2" installing Bot 
 
----- Checking Creating Backup ----- 
 
No "c:\pokemon\PokemonGo-Bot\encrypt.so" 
No "c:\pokemon\PokemonGo-Bot\encrypt.dll" 
No "c:\pokemon\PokemonGo-Bot\encrypt_64.dll" 
No "c:\pokemon\PokemonGo-Bot\configs\auth.json" 
No "c:\pokemon\PokemonGo-Bot\configs\config.json" 
No "c:\pokemon\PokemonGo-Bot\web\config\userdata.js" 
 
----- Checking Removing Bot Folder ----- 
 
c:\pokemon\PokemonGo-Bot is removed
 
----- Checking pip2 install or upgrade ----- 
 
Requirement already up-to-date: pip in c:\python27\lib\site-packages
Requirement already up-to-date: virtualenv in c:\python27\lib\site-packages
 
 
----- Checking Clone installed ----- 
 
 Install Bot choice was Master 
Submodule path 'web': checked out 'bd5c2548eadc74de19aca239efefd065b260f4f4'
 
c:\pokemon\PokemonGo-Bot has been made 
 
----- Checking second pip2 install or upgrade ----- 
 
Requirement already satisfied (use --upgrade to upgrade): numpy==1.11.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): networkx==1.11 in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Obtaining pgoapi from git+https://github.com/pogodevorg/pgoapi.git/@5e550f656b318227f021801c796b8a80ad917b93#egg=pgoapi (from -r requirements.txt (line 3))
  Cloning https://github.com/pogodevorg/pgoapi.git/ (to 5e550f656b318227f021801c796b8a80ad917b93) to c:\pokemon\pokemongo-bot\src\pgoapi
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): geographiclib==1.46.3 in c:\python27\lib\site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): protobuf==3.0.0b4 in c:\python27\lib\site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): requests-mock==1.0.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in c:\python27\lib\site-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): protobuf-to-dict==0.1.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): googlemaps==2.4.4 in c:\python27\lib\site-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): colorama==0.3.7 in c:\python27\lib\site-packages (from -r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): enum34==1.1.6 in c:\python27\lib\site-packages (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): pyyaml==3.11 in c:\python27\lib\site-packages (from -r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): haversine==0.4.5 in c:\python27\lib\site-packages (from -r requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): polyline==1.3.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): python-socketio==1.4.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): flask==0.11.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): socketIO_client==0.7.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 20))
Requirement already satisfied (use --upgrade to upgrade): eventlet==0.19.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 21))
Requirement already satisfied (use --upgrade to upgrade): gpxpy==1.1.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 22))
Requirement already satisfied (use --upgrade to upgrade): mock==2.0.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 23))
Requirement already satisfied (use --upgrade to upgrade): timeout-decorator==0.3.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 24))
Requirement already satisfied (use --upgrade to upgrade): raven==5.23.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 25))
Requirement already satisfied (use --upgrade to upgrade): demjson==2.2.4 in c:\python27\lib\site-packages (from -r requirements.txt (line 26))
Requirement already satisfied (use --upgrade to upgrade): greenlet==0.4.9 in c:\python27\lib\site-packages (from -r requirements.txt (line 27))
Requirement already satisfied (use --upgrade to upgrade): yoyo-migrations==5.0.3 in c:\python27\lib\site-packages (from -r requirements.txt (line 28))
Requirement already satisfied (use --upgrade to upgrade): paho-mqtt==1.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 29))
Requirement already satisfied (use --upgrade to upgrade): Geohash==1.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 30))
Requirement already satisfied (use --upgrade to upgrade): python-telegram-bot==5.0.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 31))
Requirement already satisfied (use --upgrade to upgrade): discord_simple==0.0.1.15 in c:\python27\lib\site-packages (from -r requirements.txt (line 32))
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.4.0 in c:\python27\lib\site-packages (from networkx==1.11->-r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): future in c:\python27\lib\site-packages (from pgoapi->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): six in c:\python27\lib\site-packages (from pgoapi->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): xxhash in c:\python27\lib\site-packages (from pgoapi->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\python27\lib\site-packages (from protobuf==3.0.0b4->-r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in c:\python27\lib\site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): python-engineio>=0.8.0 in c:\python27\lib\site-packages (from python-socketio==1.4.2->-r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in c:\python27\lib\site-packages (from flask==0.11.1->-r requirements.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): click>=2.0 in c:\python27\lib\site-packages (from flask==0.11.1->-r requirements.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in c:\python27\lib\site-packages (from flask==0.11.1->-r requirements.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in c:\python27\lib\site-packages (from flask==0.11.1->-r requirements.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): websocket-client in c:\python27\lib\site-packages (from socketIO_client==0.7.0->-r requirements.txt (line 20))
Requirement already satisfied (use --upgrade to upgrade): funcsigs>=1; python_version < "3.3" in c:\python27\lib\site-packages (from mock==2.0.0->-r requirements.txt (line 23))
Requirement already satisfied (use --upgrade to upgrade): pbr>=0.11 in c:\python27\lib\site-packages (from mock==2.0.0->-r requirements.txt (line 23))
Requirement already satisfied (use --upgrade to upgrade): contextlib2 in c:\python27\lib\site-packages (from raven==5.23.0->-r requirements.txt (line 25))
Requirement already satisfied (use --upgrade to upgrade): python-slugify in c:\python27\lib\site-packages (from yoyo-migrations==5.0.3->-r requirements.txt (line 28))
Requirement already satisfied (use --upgrade to upgrade): iniherit in c:\python27\lib\site-packages (from yoyo-migrations==5.0.3->-r requirements.txt (line 28))
Requirement already satisfied (use --upgrade to upgrade): docutils>=0.3 in c:\python27\lib\site-packages (from Geohash==1.0->-r requirements.txt (line 30))
Requirement already satisfied (use --upgrade to upgrade): urllib3>=1.10 in c:\python27\lib\site-packages (from python-telegram-bot==5.0.0->-r requirements.txt (line 31))
Requirement already satisfied (use --upgrade to upgrade): certifi in c:\python27\lib\site-packages (from python-telegram-bot==5.0.0->-r requirements.txt (line 31))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in c:\python27\lib\site-packages (from Jinja2>=2.4->flask==0.11.1->-r requirements.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): Unidecode>=0.04.16 in c:\python27\lib\site-packages (from python-slugify->yoyo-migrations==5.0.3->-r requirements.txt (line 28))
Installing collected packages: pgoapi
  Running setup.py develop for pgoapi
Successfully installed pgoapi-1.1.6
 
----- Checking Restoring Backup ----- 
 
No "C:\Users\me\Desktop\PokemonGo-Bot-dev\PokemonGo-Bot-dev\windows_bat\encrypt.so" 
No "C:\Users\me\Desktop\PokemonGo-Bot-dev\PokemonGo-Bot-dev\windows_bat\encrypt.dll" 
Copying C:\Users\me\Desktop\PokemonGo-Bot-dev\PokemonGo-Bot-dev\windows_bat\encrypt_64.dll to c:\pokemon\PokemonGo-Bot 
        1 file(s) copied.
No "C:\Users\me\Desktop\PokemonGo-Bot-dev\PokemonGo-Bot-dev\windows_bat\auth.json" 
No "C:\Users\me\Desktop\PokemonGo-Bot-dev\PokemonGo-Bot-dev\windows_bat\config.json" 
No "C:\Users\me\Desktop\PokemonGo-Bot-dev\PokemonGo-Bot-dev\windows_bat\userdata.js" 
No "c:\pokemon\Install-Files\encrypt.so" 
No "c:\pokemon\Install-Files\encrypt.dll" 
No "c:\pokemon\Install-Files\encrypt_64.dll" 
No "c:\pokemon\Install-Files\auth.json" 
No "c:\pokemon\Install-Files\config.json" 
No "c:\pokemon\Install-Files\userdata.js" 
 
 ----- End Log ----- 

i then run the start bot bat and get this

--------------------Starting bot--------------------

2016-09-22 12:14:33,878 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-22 12:14:33,888 [       cli] [INFO] commit: unknown
2016-09-22 12:14:33,888 [       cli] [INFO] No auth argument specified, checking for C:\Users\me\Desktop\PokemonGo-Bot-dev\PokemonGo-Bot-dev\pokemongo_bot\..\configs\auth.json
2016-09-22 12:14:33,888 [       cli] [INFO] Error: No /configs/config.json
2016-09-22 12:14:33,891 [      root] [ERROR] No tasks are configured. Did you mean to configure some behaviors? Read https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files#configuring-tasks for more information
Traceback (most recent call last):
  File "pokecli.py", line 843, in <module>
    main()
  File "pokecli.py", line 175, in main
    config, config_file = init_config()
TypeError: 'NoneType' object is not iterable

 Something went wrong and the bot needed to be restarted. Please investigate the cause.

Waiting for 33 seconds, press a key to continue ...

**Comment by PeshBG** [comment]
basically it will be good to include that after you run the install bat you need to run the other ones from the installation dir and not from the other one... anyway seems to work

**Comment by PeshBG** [comment]
2016-09-22 12:25:06,342 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-22 12:25:06,349 [       cli] [INFO] commit: unknown
2016-09-22 12:25:06,351 [       cli] [INFO] No auth argument specified, checking for C:\pokemon\PokemonGo-Bot\pokemongo_bot\..\configs\auth.json
2016-09-22 12:25:06,351 [       cli] [INFO] No config argument specified, checking for C:\pokemon\PokemonGo-Bot\pokemongo_bot\..\configs\config.json
2016-09-22 12:25:06,354 [       cli] [INFO] Configuration initialized
2016-09-22 12:25:06,354 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-09-22 12:25:06,355 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-09-22 12:25:06,361 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
(2352) wsgi starting up on http://127.0.0.1:4000
[2016-09-22 12:25:06] [SleepSchedule] [INFO] Sleeping for 05:00:47, wake at 17:25:53

**Comment by PeshBG** [comment]
C:\pokemon\PokemonGo-Bot>docker build -t pokemongo-bot .
An error occurred trying to connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/build?buildargs=%7B%7D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&rm=1&shmsize=0&t=pokemongo-bot&ulimits=null: open //./pipe/docker_engine: The system cannot find the file specified.

**Comment by olavo1965** [comment]
@PeshBG To me it is going the same mistake.

**Comment by PeshBG** [comment]
no one wants to help :) i decided not to bother and use as much as possible the desktop version.(my goal were just the lures anyway and it is good for that) it crashes a lot unfortunately but level 20 is not that far away :)
