### ISSUE TITLE
Ubuntu 16.04 server start issue.

### ISSUE THREAD

**Issue by VBQL** [PokemonGoF/PokemonGo-Bot#5643]
As title, I reinstalled the bot completely and still got this error.
"
Traceback (most recent call last):
  File "pokecli.py", line 843, in <module>
    main()
  File "pokecli.py", line 191, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 145, in start_bot
    bot.start()
  File "/home/name/PokemonGo-Bot/pokemongo_bot/__init__.py", line 144, in start
    self._setup_api()
  File "/home/name/PokemonGo-Bot/pokemongo_bot/__init__.py", line 983, in _setup_api
    self.login()
  File "/home/name/PokemonGo-Bot/pokemongo_bot/__init__.py", line 917, in login
    str(self.config.password))
  File "/home/name/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 98, in login
    password=password
  File "/home/name/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 94, in set_authentication
    if not self._auth_provider.user_login(username, password):
  File "/home/name/PokemonGo-Bot/src/pgoapi/pgoapi/auth_google.py", line 58, in user_login
    user_login = perform_master_login(username, password, self.GOOGLE_LOGIN_ANDROID_ID, proxy=self._proxy)
AttributeError: AuthGoogle instance has no attribute '_proxy'
[2016-09-23 20:15:09] [MainThread] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/name/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/name/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/name/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/name/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/name/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/name/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/name/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/name/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
[2016-09-23 20:15:09] [MainThread] [sentry.errors.uncaught] [ERROR] [u"AttributeError: AuthGoogle instance has no attribute '_proxy'", u'  File "pokecli.py", line 843, in <module>', u'  File "pokecli.py", line 191, in main', u'  File "pokecli.py", line 145, in start_bot', u'  File "pokemongo_bot/__init__.py", line 144, in start', u'  File "pokemongo_bot/__init__.py", line 983, in _setup_api', u'  File "pokemongo_bot/__init__.py", line 917, in login', u'  File "pokemongo_bot/api_wrapper.py", line 98, in login', u'  File "pgoapi/pgoapi.py", line 94, in set_authentication', u'  File "pgoapi/auth_google.py", line 58, in user_login']
Fri Sep 23 20:15:09 EDT 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
"

**Comment by ricardofiorani** [comment]
+1

**Comment by Gobberwart** [comment]
This is a known issue with the pgoapi, but *should* be fixed in latest dev. Update to latest version and make sure you run `pip install -r requirements.txt --upgrade`

**Comment by VBQL** [comment]
Sorry, updated and retried, still fails :(

**Comment by Gobberwart** [comment]
Reopening then. Maybe there's a new issue.

**Comment by Pjumpod** [comment]
I use Ubuntu as well but I haven't this problem... Maybe if you copy whole logfile since "./run.sh" I can help for more troouble.

**Comment by Gobberwart** [comment]
You are running dev branch, yes?

**Comment by Pjumpod** [comment]
nope, I am running main branch only. (I don't know how to move to dev branch. :D I am new for git command.)
Just latest update have problem with proxy but modify same as an advise in thread so it fixed.

**Comment by Gobberwart** [comment]
Ah, well in that case... PR is ready to merge fix into master. #5645. Once that's done, this issue should be fixed.

**Comment by VBQL** [comment]
Yes, it is fixed now, thanks! :)
