### ISSUE TITLE
[Erorr]   got an unexpected keyword argument 'device_info'

### ISSUE THREAD

**Issue by cbogithub** [PokemonGoF/PokemonGo-Bot#5682]
```
2016-09-26 15:50:36] [MainThread] [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 843, in <module>
    main()
  File "pokecli.py", line 191, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 145, in start_bot
    bot.start()
  File "/home/PokemonGo-Bot/pokemongo_bot/__init__.py", line 147, in start
    self._setup_api()
  File "/home/PokemonGo-Bot/pokemongo_bot/__init__.py", line 986, in _setup_api
    self.api = ApiWrapper(config=self.config)
  File "/home/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 41, in __init__
    PGoApi.__init__(self, device_info=device_info)
TypeError: __init__() got an unexpected keyword argument 'device_info'
```

**Comment by gise88** [comment]
Probable cause: https://github.com/AeonLucid/POGOProtos/issues/233#issuecomment-249489396 (?)

**Comment by Gobberwart** [comment]
Latest dev code doesn't do this.

Apirwrapper.py, line 41 should read:

`        PGoApi.__init__(self)`

If it says, `        PGoApi.__init__(self, device_info)`, edit it.

**Comment by cbogithub** [comment]
@Gobberwart 
thanks 👍

**Comment by Gobberwart** [comment]
A bit more info.... I recently had this happen to me when I installed Pokemongo-Map and its requirements. It installed a copy of pgoapi into site-libraries which generated this error. I ended up fixing permanently by deleting pgoapi folders from site-libraries, then reinstalling Pokemongo-Bot requirements.
