### ISSUE TITLE
Weird error when running bot. "_inventory was not initialized"..?

### ISSUE THREAD

**Issue by minefedt** [PokemonGoF/PokemonGo-Bot#5691]
Just installed bot on ubuntu 16.04. I ran the setup multiple times, reset it and updated it. I still get this really weird error.

```
2016-09-26 17:09:02,911 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-26 17:09:02,922 [       cli] [INFO] commit: fd495448
2016-09-26 17:09:02,927 [       cli] [INFO] Configuration initialized
2016-09-26 17:09:02,928 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-09-26 17:09:02,928 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-09-26 17:09:02,942 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
(4690) wsgi starting up on http://0.0.0.0:4000
[2016-09-26 17:09:02] [PokemonGoBot] [INFO] Setting start location.
[2016-09-26 17:09:03] [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
[2016-09-26 17:09:03] [PokemonGoBot] [INFO] Location found: 40.774678, -73.972711 (40.774678, -73.972711, 8.0)
[2016-09-26 17:09:03] [PokemonGoBot] [INFO] Now at (40.774678, -73.972711, 8.0)
[2016-09-26 17:09:03] [PokemonGoBot] [INFO] Login procedure started.
_inventory was not initialized
_inventory was not initialized
[2016-09-26 17:09:03] [       cli] [INFO] 
[2016-09-26 17:09:03] [       cli] [INFO] Ran for 0:00:01
[2016-09-26 17:09:03] [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
[2016-09-26 17:09:03] [       cli] [INFO] Travelled 0.00km
[2016-09-26 17:09:03] [       cli] [INFO] Visited 0 stops
[2016-09-26 17:09:03] [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
[2016-09-26 17:09:03] [       cli] [INFO] Threw 0 pokeballs
[2016-09-26 17:09:03] [       cli] [INFO] Earned 0 Stardust
[2016-09-26 17:09:03] [       cli] [INFO] Hatched eggs 0
[2016-09-26 17:09:03] [       cli] [INFO] 
[2016-09-26 17:09:03] [       cli] [INFO] Highest CP Pokemon: 
[2016-09-26 17:09:03] [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 843, in <module>
    main()
  File "pokecli.py", line 191, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 145, in start_bot
    bot.start()
  File "/home/ubuntu/workspace/PokemonGo-Bot/pokemongo_bot/__init__.py", line 144, in start
    self._setup_api()
  File "/home/ubuntu/workspace/PokemonGo-Bot/pokemongo_bot/__init__.py", line 983, in _setup_api
    self.login()
  File "/home/ubuntu/workspace/PokemonGo-Bot/pokemongo_bot/__init__.py", line 917, in login
    str(self.config.password))
  File "/home/ubuntu/workspace/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 103, in login
    response = PGoApi.app_simulation_login(self)
  File "/home/ubuntu/workspace/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 158, in app_simulation_login
    response = request.call()
  File "/home/ubuntu/workspace/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 242, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/home/ubuntu/workspace/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 140, in request
    response_dict = self._parse_main_response(response, subrequests)
  File "/home/ubuntu/workspace/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 379, in _parse_main_response
    raise ServerSideAccessForbiddenException("Seems your IP Address is banned or something else went badly wrong...")
pgoapi.exceptions.ServerSideAccessForbiddenException: Seems your IP Address is banned or something else went badly wrong...
[2016-09-26 17:09:03] [sentry.errors] [ERROR] Sentry responded with an error: 'module' object has no attribute 'HTTPSHandler' (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/ubuntu/workspace/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/ubuntu/workspace/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/ubuntu/workspace/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 44, in urlopen
    class ValidHTTPSHandler(urllib2.HTTPSHandler):
AttributeError: 'module' object has no attribute 'HTTPSHandler'
[2016-09-26 17:09:03] [sentry.errors.uncaught] [ERROR] [u'ServerSideAccessForbiddenException: Seems your IP Address is banned or something else went badly wrong...', u'  File "pokecli.py", line 843, in <module>', u'  File "pokecli.py", line 191, in main', u'  File "pokecli.py", line 145, in start_bot', u'  File "pokemongo_bot/__init__.py", line 144, in start', u'  File "pokemongo_bot/__init__.py", line 983, in _setup_api', u'  File "pokemongo_bot/__init__.py", line 917, in login', u'  File "pokemongo_bot/api_wrapper.py", line 103, in login', u'  File "pgoapi/pgoapi.py", line 158, in app_simulation_login', u'  File "pgoapi/pgoapi.py", line 242, in call', u'  File "pgoapi/rpc_api.py", line 140, in request', u'  File "pgoapi/rpc_api.py", line 379, in _parse_main_response']
Mon Sep 26 17:09:03 UTC 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
```

I would really appreciate it if someone could help me with this problem.

**Comment by gise88** [comment]
`[u'ServerSideAccessForbiddenException: Seems your IP Address is banned or something else went badly wrong...'`

**Comment by settoger** [comment]
same here #5609
