### ISSUE TITLE
error

### ISSUE THREAD

**Issue by perpysling2** [PokemonGoF/PokemonGo-Bot#5718]
now i get this error:
`Traceback (most recent call last):
  File "pokecli.py", line 843, in <module>
    main()
  File "pokecli.py", line 202, in main
    bot.tick()
  File "/PokemonGo-Bot/pokemongo_bot/__init__.py", line 744, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort.py", line 94, in work
    lng
  File "/PokemonGo-Bot/pokemongo_bot/walkers/walker_factory.py", line 12, in walker_factory
    return ret
UnboundLocalError: local variable 'ret' referenced before assignment
[2016-09-27 22:08:49] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
[2016-09-27 22:08:49] [sentry.errors.uncaught] [ERROR] [u"UnboundLocalError: local variable 'ret' referenced before assignment", u'  File "pokecli.py", line 843, in <module>', u'  File "pokecli.py", line 202, in main', u'  File "pokemongo_bot/__init__.py", line 744, in tick', u'  File "pokemongo_bot/cell_workers/move_to_fort.py", line 94, in work', u'  File "pokemongo_bot/walkers/walker_factory.py", line 12, in walker_factory']
ti. 27. sep. 22:08:49 +0200 2016 Pokebot  Stopped.
`

**Comment by perpysling2** [comment]
fixed
