### ISSUE TITLE
ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by barna92** [PokemonGoF/PokemonGo-Bot#5719]
Hi, 
I used this fantastic Pokemon Go Bot for a week and all was working very well, but today when I opened it, I found the following error :

Traceback (most recent call last):
  File "pokecli.py", line 50, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "/home/andrea/PokemonGo-Bot/pokemongo_bot/__init__.py", line 23, in <module>
    from . import cell_workers
  File "/home/andrea/PokemonGo-Bot/pokemongo_bot/cell_workers/__init__.py", line 29, in <module>
    from .telegram_task import TelegramTask
  File "/home/andrea/PokemonGo-Bot/pokemongo_bot/cell_workers/telegram_task.py", line 6, in <module>
    from pokemongo_bot.event_handlers import TelegramHandler
  File "/home/andrea/PokemonGo-Bot/pokemongo_bot/event_handlers/__init__.py", line 3, in <module>
    from .socketio_handler import SocketIoHandler
  File "/home/andrea/PokemonGo-Bot/pokemongo_bot/event_handlers/socketio_handler.py", line 5, in <module>
    from socketIO_client import SocketIO
  File "/home/andrea/PokemonGo-Bot/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 9, in <module>
    from .parsers import (
ValueError: bad marshal data (unknown type code)
mar 27 set 2016, 22.34.20, CEST Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

I just changed my location in the auth.json file. 
What can I do to fix the iusse? 
thank you

**Comment by crvfts** [comment]
Try deleting the .pyc of all those files listed above (the ones in bot folders, not the one in the Python directory). make sure the extension is .pyc and NOT .py. You're receiving the error due to a corrupted compiled python file.

**Comment by Gobberwart** [comment]
What he said ^^^

**Comment by barna92** [comment]
It works again!! Thank you very much! :)

**Comment by pganeshGapps** [comment]
Thanks, it works :+1:
