### ISSUE TITLE
bot will not start

### ISSUE THREAD

**Issue by beltoft** [PokemonGoF/PokemonGo-Bot#5722]
### Expected Behavior
bot should start

### Actual Behavior
bot was running fine over night but when i looked at it this morning I see this error:

 ./run.sh
Traceback (most recent call last):
  File "pokecli.py", line 50, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "/home/beltoft/PokemonGo-Bot/pokemongo_bot/__init__.py", line 23, in <module>
    from . import cell_workers
  File "/home/beltoft/PokemonGo-Bot/pokemongo_bot/cell_workers/__init__.py", line 29, in <module>
    from .telegram_task import TelegramTask
  File "/home/beltoft/PokemonGo-Bot/pokemongo_bot/cell_workers/telegram_task.py", line 3, in <module>
    import telegram
  File "/home/beltoft/PokemonGo-Bot/local/lib/python2.7/site-packages/telegram/__init__.py", line 33, in <module>
    from .contact import Contact
EOFError: EOF read where object expected
Wed Sep 28 08:22:44 CEST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/LMGLCnae

### Other Information
OS: 
ubuntu 14.04

Dev branch

**Comment by ukos-git** [comment]
have you tried reinstalling the telegram package of your virtualenv via pip?
