### ISSUE TITLE
cant go web server

### ISSUE THREAD

**Issue by agetnc313** [PokemonGoF/PokemonGo-Bot#5729]
for the python -m SimpleHTTPServer it just stays at "Serving HTTP on 0.0.0.0 on port 8000 ... "
This also comes up after the bot loads and starts doing its stuff:

127.0.0.1 - - [28/Sep/2016 21:44:14] code 400, message Bad request syntax ('\x81\xfe\x05\xafJ4\x93\x11~\x06\xc83([\xe7+(F\xfcp.W\xf2b>\x16\xbf11\x16\xf2r)[\xe6\x7f>\x16\xa91hW\xf0c?@\xe7t$P\xf6\x7f')
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\eventlet\greenpool.py", line 82, in _spawn_n_impl
    func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\eventlet\wsgi.py", line 719, in process_request
    proto.__init__(sock, address, self)
  File "C:\Python27\lib\SocketServer.py", line 652, in __init__
    self.handle()
  File "C:\Python27\lib\BaseHTTPServer.py", line 342, in handle
    self.handle_one_request()
  File "C:\Python27\lib\site-packages\eventlet\wsgi.py", line 351, in handle_one_request
    if not self.parse_request():
  File "C:\Python27\lib\BaseHTTPServer.py", line 286, in parse_request
    self.send_error(400, "Bad request syntax (%r)" % requestline)
  File "C:\Python27\lib\BaseHTTPServer.py", line 365, in send_error
    self.send_response(code, message)
  File "C:\Python27\lib\BaseHTTPServer.py", line 396, in send_response
    self.log_request(code)
  File "C:\Python27\lib\BaseHTTPServer.py", line 433, in log_request
    self.requestline, str(code), str(size))
  File "C:\Python27\lib\BaseHTTPServer.py", line 469, in log_message
    format%args))
  File "C:\Python27\lib\codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)

as well as that, when the bot first loads it says:

--------------------Starting bot--------------------

2016-09-28 21:42:59,532 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-28 21:42:59,545 [       cli] [INFO] commit: unknown
2016-09-28 21:42:59,548 [       cli] [INFO] No auth argument specified, checking for C:\Users\chris\Documents\Git\PokemonGo-Bot\pokemongo_bot\..\configs\auth.json
2016-09-28 21:42:59,549 [       cli] [INFO] No config argument specified, checking for C:\Users\chris\Documents\Git\PokemonGo-Bot\pokemongo_bot\..\configs\config.json
2016-09-28 21:42:59,562 [       cli] [INFO] Configuration initialized
2016-09-28 21:42:59,562 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-09-28 21:42:59,562 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-09-28 21:42:59,575 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\chris\Documents\Git\PokemonGo-Bot\pokemongo_bot\socketio_server\runner.py", line 34, in _start_listening_blocking
    listener = eventlet.listen((self.host, self.port))
  File "C:\Python27\lib\site-packages\eventlet\convenience.py", line 43, in listen
    sock.bind(addr)
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

and when i look up "localhost:8000" it comes up with a 404 error but shows the pokegobot logo in chrome.

**Comment by ukos-git** [comment]
maybe some threaded process was still running on localhost when you started the bot. Try to kill that orphaned python thread before starting the server again.

> Serving HTTP on 0.0.0.0 on port 8000 ... 

Did you look at http://0.0.0.0:8000 when the bot told you this?

**Comment by agetnc313** [comment]
got it
