### ISSUE TITLE
NotLoggedInException

### ISSUE THREAD

**Issue by takenek** [PokemonGoF/PokemonGo-Bot#5730]
### Expected Behavior
Working without errors.

### Actual Behavior
[2016-09-28 10:49:12] [pgoapi.pgoapi] [ERROR] Request for new Access Token failed! Logged out...
[2016-09-28 10:49:13] [PokemonGoBot] [INFO] Not logged in, reconnecting in 900 seconds
Exception in thread Thread-898:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 1082, in run
    self.function(*self.args, **self.kwargs)
  File "/home/taken/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1335, in heartbeat
    responses = request.call()
  File "/home/taken/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 192, in call
    if not self.can_call():
  File "/home/taken/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 151, in can_call
    raise NotLoggedInException()
NotLoggedInException

### Steps to Reproduce
1. Run a bot
2. Every few minutes got errors...

### Other Information
OS: Debian
Branch:  Master
Git Commit:  fd495448a6393e886a74d846ad086e0fed45f986
Python Version:  Python 2.7.9

**Comment by supergithubo** [comment]
Same on latest release. Happens on:  Stale session and Random Pause.

**Comment by jeromelaurens** [comment]
same with latest release on dev and docker-compose

**Comment by bhaveshrangani** [comment]
having same problem

**Comment by DarthKeizer** [comment]
Same problem here!
