### ISSUE TITLE
Bot stuck at wsgi starting up

### ISSUE THREAD

**Issue by nelsyeung** [PokemonGoF/PokemonGo-Bot#5745]
### Expected Behavior
Work

### Actual Behavior
Bot stuck at `wsgi starting up on http://0.0.0.0:4000`

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
Default config

### Output when issue occurred
```
2016-09-30 13:17:49,427 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-30 13:17:49,461 [       cli] [INFO] commit: fd495448
2016-09-30 13:17:49,467 [       cli] [INFO] Configuration initialized
2016-09-30 13:17:49,467 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-09-30 13:17:49,467 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-09-30 13:17:49,496 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): anorien.csc.warwick.ac.uk
[2016-09-30 13:17:49] [yoyo.migrations] [INFO] Applying pokemongobot
[2016-09-30 13:17:49] [yoyo.migrations] [INFO]  - applying step 0
[2016-09-30 13:17:49] [yoyo.migrations] [INFO] Marking pokemongobot applied
[2016-09-30 13:17:49] [yoyo.migrations] [INFO] Applying catch_log
[2016-09-30 13:17:49] [yoyo.migrations] [INFO]  - applying step 0
[2016-09-30 13:17:49] [yoyo.migrations] [INFO] Marking catch_log applied
[2016-09-30 13:17:49] [yoyo.migrations] [INFO] Applying eggs_hatched_log
[2016-09-30 13:17:49] [yoyo.migrations] [INFO]  - applying step 0
[2016-09-30 13:17:49] [yoyo.migrations] [INFO] Marking eggs_hatched_log applied
[2016-09-30 13:17:49] [yoyo.migrations] [INFO] Applying evolve_log
[2016-09-30 13:17:49] [yoyo.migrations] [INFO]  - applying step 0
[2016-09-30 13:17:49] [yoyo.migrations] [INFO] Marking evolve_log applied
[2016-09-30 13:17:49] [yoyo.migrations] [INFO] Applying pokestop_log
[2016-09-30 13:17:49] [yoyo.migrations] [INFO]  - applying step 0
[2016-09-30 13:17:49] [yoyo.migrations] [INFO] Marking pokestop_log applied
[2016-09-30 13:17:49] [yoyo.migrations] [INFO] Applying softban_log
[2016-09-30 13:17:49] [yoyo.migrations] [INFO]  - applying step 0
[2016-09-30 13:17:49] [yoyo.migrations] [INFO] Marking softban_log applied
[2016-09-30 13:17:49] [yoyo.migrations] [INFO] Applying transfer_log
[2016-09-30 13:17:49] [yoyo.migrations] [INFO]  - applying step 0
[2016-09-30 13:17:49] [yoyo.migrations] [INFO] Marking transfer_log applied
[2016-09-30 13:17:49] [yoyo.migrations] [INFO] Applying vanish_log
[2016-09-30 13:17:49] [yoyo.migrations] [INFO]  - applying step 0
[2016-09-30 13:17:49] [yoyo.migrations] [INFO] Marking vanish_log applied
(5129) wsgi starting up on http://0.0.0.0:4000
```

Upon `Ctrl-C`:
```
^CTraceback (most recent call last):
  File "pokecli.py", line 843, in <module>
    main()
  File "pokecli.py", line 268, in main
    bot.event_manager.emit(
AttributeError: 'PokemonGoBot' object has no attribute 'event_manager'
[2016-09-30 13:25:29] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/theory/phukgm/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/theory/phukgm/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/theory/phukgm/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/theory/phukgm/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/theory/phukgm/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/theory/phukgm/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/theory/phukgm/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/theory/phukgm/Pokemon/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/home/theory/phukgm/.local/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/home/theory/phukgm/.local/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/home/theory/phukgm/.local/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/home/theory/phukgm/.local/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
[2016-09-30 13:25:29] [sentry.errors.uncaught] [ERROR] [u"AttributeError: 'PokemonGoBot' object has no attribute 'event_manager'", u'  File "pokecli.py", line 843, in <module>', u'  File "pokecli.py", line 268, in main']
Fri Sep 30 13:25:29 BST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
```

### Steps to Reproduce
```
git clone https://github.com/PokemonGoF/PokemonGo-Bot.git
cd PokemonGo-bot
./setup.sh -i
# Fill in the required information: PTC, username, password, Input Location, Google API Key (gmapkey) and Config Generator.
./run.sh
```

### Other Information
**OS:**
SUSE Enterprise
**Branch:**
master and dev
**Git Commit:** 
fd495448a6393e886a74d846ad086e0fed45f986
**Python Version:** 
Python 2.7.12

**Comment by Gobberwart** [comment]
At the bottom of your config.json, change `"server_url": "0.0.0.0:4000"` to `"server_url": "127.0.0.1:4000"`
