### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Rico22123** [PokemonGoF/PokemonGo-Bot#5747]
With the new update for this bot I get an error that says this
Error: Pokemon.Go.Rocket.API
[15:50:40] PokemonGo.RocketAPI.Exceptions.GoogleException: BadAuthentication
   at PokemonGo.RocketAPI.Login.GoogleLogin.<GetAccessToken>d__3.MoveNext() in C:\Users\nrgne\Documents\GitHub\PokemonGo-Bot\PokemonGo.RocketAPI\Login\GoogleLogin.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in C:\Users\nrgne\Documents\GitHub\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\Login.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__38.MoveNext() in C:\Users\nrgne\Documents\GitHub\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 167
[15:50:40] Trying to Restart.

It works with the older versions of this bot but not the current

**Comment by Gobberwart** [comment]
Have you updated requirements since installing new bot version? PGO Api recent update to google authentication may be the cause of this.

**Comment by rawgni** [comment]
different bot
