### ISSUE TITLE
cant start bot new installed machine

### ISSUE THREAD

**Issue by beltoft** [PokemonGoF/PokemonGo-Bot#5755]
### Expected Behavior
bot runs 

### Actual Behavior
bot crashes after login

just installed bot on a fresh install og ubuntu using ./setup.py -i

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

http://pastebin.com/PTmsjUfG

### Output when issue occurred

Traceback (most recent call last):
  File "pokecli.py", line 843, in <module>
    main()
  File "pokecli.py", line 202, in main
    bot.tick()
  File "/home/beltoft/PokemonGo-Bot/pokemongo_bot/__init__.py", line 756, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/beltoft/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort.py", line 97, in work
    if not step_walker.step():
  File "/home/beltoft/PokemonGo-Bot/pokemongo_bot/walkers/step_walker.py", line 38, in step
    new_position = self.get_next_position(origin_lat, origin_lng, origin_alt, self.dest_lat, self.dest_lng, self.dest_alt, speed)
  File "/home/beltoft/PokemonGo-Bot/pokemongo_bot/walkers/polyline_walker.py", line 11, in get_next_position
    polyline = PolylineObjectHandler.cached_polyline((self.bot.position[0], self.bot.position[1]), (dest_lat, dest_lng), google_map_api_key=self.bot.config.gmapkey)
  File "/home/beltoft/PokemonGo-Bot/pokemongo_bot/walkers/polyline_generator.py", line 52, in cached_polyline
    PolylineObjectHandler._cache = Polyline(origin, destination, google_map_api_key)
  File "/home/beltoft/PokemonGo-Bot/pokemongo_bot/walkers/polyline_generator.py", line 71, in __init__
    self._directions_response = requests.get(self.DIRECTIONS_URL).json()
  File "/home/beltoft/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/home/beltoft/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/beltoft/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/beltoft/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/beltoft/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Mon Oct 3 14:07:05 CEST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

### Other Information
 ubuntu 14.04 
dev branch

**Comment by ukos-git** [comment]
probably related to https://github.com/PokemonGoF/PokemonGo-Bot/issues/5450
`raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (ssl.c:581)`

**Comment by beltoft** [comment]
I'm using a ptc account but the issue you're referring to is talking about Google login
