### ISSUE TITLE
Failing to Transfer Pokemon

### ISSUE THREAD

**Issue by KariHi** [PokemonGoF/PokemonGo-Bot#576]
When going to transfer a pokemon it errors out with the following:

Traceback (most recent call last):
  File "pokecli.py", line 197, in <module>
    main()
  File "pokecli.py", line 188, in main
    bot.take_step()
  File "C:\Users\sbirr\Desktop\PokemonGo-Bot\pokemongo_bot\__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "C:\Users\sbirr\Desktop\PokemonGo-Bot\pokemongo_bot\stepper.py", line 61, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "C:\Users\sbirr\Desktop\PokemonGo-Bot\pokemongo_bot\stepper.py", line 134, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "C:\Users\sbirr\Desktop\PokemonGo-Bot\pokemongo_bot\__init__.py", line 91, in work_on_cell
    if worker.work() == -1:
  File "C:\Users\sbirr\Desktop\PokemonGo-Bot\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 137, in work
    pokemon_to_transfer = list(Set(id_list2) - Set(id_list1))
NameError: global name 'id_list2' is not defined

**Comment by J102030** [comment]
was working fine before merge of new evolve code

**Comment by surfaace** [comment]
fixed in efad5ca94df3eb16045d653cbb9b457e29a3fd3e

**Comment by KariHi** [comment]
Thanks!
