### ISSUE TITLE
don't seen pokespot at 127.0.0.1:8000 then this problem.

### ISSUE THREAD

**Issue by kaiiycta** [PokemonGoF/PokemonGo-Bot#5779]
Hi! I have this problem.
--------------------Starting bot--------------------

2016-10-10 14:53:49,433 [       cli] [INFO] PokemonGO Bot v1.0
2016-10-10 14:53:49,433 [       cli] [INFO] commit: unknown
2016-10-10 14:53:49,433 [       cli] [INFO] No auth argument specified, checking
 for C:\__botPokemonGo-Bot\pokemongo_bot\..\configs\auth.json
2016-10-10 14:53:49,433 [       cli] [INFO] No config argument specified, checki
ng for C:\__botPokemonGo-Bot\pokemongo_bot\..\configs\config.json
2016-10-10 14:53:49,433 [       cli] [INFO] Configuration initialized
2016-10-10 14:53:49,433 [pokemongo_bot.health_record.bot_event] [INFO] Health ch
eck is enabled. For more information:
2016-10-10 14:53:49,433 [pokemongo_bot.health_record.bot_event] [INFO] https://g
ithub.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-10-10 14:53:49,448 [requests.packages.urllib3.connectionpool] [INFO] Starti
ng new HTTP connection (1): www.google-analytics.com
(9088) wsgi starting up on http://127.0.0.1:4000
[2016-10-10 14:53:50] [SleepSchedule] [INFO] Next sleep at 17:22:33, for a durat
ion of 02:58:15
[2016-10-10 14:53:50] [PokemonGoBot] [INFO] Setting start location.
[2016-10-10 14:53:50] [PokemonGoBot] [INFO] [x] Coordinates found in passed in l
ocation, not geocoding.
[2016-10-10 14:53:50] [PokemonGoBot] [INFO] Location found: 55.766192, 37.532168
 (55.766192, 37.532168, 8.0)
[2016-10-10 14:53:50] [PokemonGoBot] [INFO] Now at (55.766192, 37.532168, 8.0)
[2016-10-10 14:53:50] [PokemonGoBot] [INFO] Login procedure started.
[2016-10-10 14:53:54] [PokemonGoBot] [INFO] Login successful.
[2016-10-10 14:53:54] [PokemonGoBot] [INFO] Found encrypt_64.dll! Platform: win3
2 encrypt_64.dll directory: C:\__botPokemonGo-Bot
[2016-10-10 14:53:54] [PokemonGoBot] [INFO]
[2016-10-10 14:53:55] [PokemonGoBot] [INFO] [x] Error while opening cached forts
: [Errno 2] No such file or directory: u'C:\\__botPokemonGo-Bot\\pokemongo_bot\\
..\\data\\recent-forts-login'
[2016-10-10 14:53:56] [PokemonGoBot] [INFO] Level: 1 (Next Level: 400 XP) (Total
: 600 XP)
[2016-10-10 14:53:56] [PokemonGoBot] [INFO] Pokemon Captured: 1 | Pokestops Visi
ted: 0
[2016-10-10 14:53:57] [PokemonGoBot] [INFO]
[2016-10-10 14:53:57] [PokemonGoBot] [INFO] --- Hhhvchjjgfy ---
[2016-10-10 14:53:57] [PokemonGoBot] [INFO] Pokemon Bag: 1/250
[2016-10-10 14:53:57] [PokemonGoBot] [INFO] Items: 54/350
[2016-10-10 14:53:57] [PokemonGoBot] [INFO] Stardust: 100 | Pokecoins: 0
[2016-10-10 14:53:57] [PokemonGoBot] [INFO] PokeBalls: 50 | GreatBalls: 0 | Ultr
aBalls: 0 | MasterBalls: 0
[2016-10-10 14:53:57] [PokemonGoBot] [INFO] RazzBerries: 0 | BlukBerries: 0 | Na
nabBerries: 0
[2016-10-10 14:53:57] [PokemonGoBot] [INFO] LuckyEgg: 0 | Incubator: 0 | TroyDis
k: 0
[2016-10-10 14:53:57] [PokemonGoBot] [INFO] Potion: 0 | SuperPotion: 0 | HyperPo
tion: 0 | MaxPotion: 0
[2016-10-10 14:53:57] [PokemonGoBot] [INFO] Incense: 2 | IncenseSpicy: 0 | Incen
seCool: 0
[2016-10-10 14:53:57] [PokemonGoBot] [INFO] Revive: 0 | MaxRevive: 0
[2016-10-10 14:53:57] [PokemonGoBot] [INFO]
[2016-10-10 14:53:57] [PokemonGoBot] [INFO] Pokemon:
[2016-10-10 14:53:57] [PokemonGoBot] [INFO] #4 Charmander: (CP 12, IV 0.67)
[2016-10-10 14:53:57] [PokemonGoBot] [INFO]
[2016-10-10 14:53:57] [RandomAlivePause] [INFO] Next random alive pause at 15:45
:29, for a duration of 0:03:33
[2016-10-10 14:53:57] [RandomPause] [INFO] Next random pause at 15:17:00, for a
duration of 0:05:41
[2016-10-10 14:53:58] [       cli] [INFO]
[2016-10-10 14:53:58] [       cli] [INFO] Ran for 0:00:08
[2016-10-10 14:53:58] [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
[2016-10-10 14:53:58] [       cli] [INFO] Travelled 0.00km
[2016-10-10 14:53:58] [       cli] [INFO] Visited 0 stops
[2016-10-10 14:53:58] [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 rel
eased, 0 evolved, 0 never seen before ()
[2016-10-10 14:53:58] [       cli] [INFO] Threw 0 pokeballs
[2016-10-10 14:53:58] [       cli] [INFO] Earned 0 Stardust
[2016-10-10 14:53:58] [       cli] [INFO] Hatched eggs 0
[2016-10-10 14:53:58] [       cli] [INFO]
[2016-10-10 14:53:58] [       cli] [INFO] Highest CP Pokemon:
[2016-10-10 14:53:58] [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 843, in <module>
    main()
  File "pokecli.py", line 191, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 146, in start_bot
    initialize_task(bot, config)
  File "pokecli.py", line 98, in initialize_task
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "C:\__botPokemonGo-Bot\pokemongo_bot\tree_config_builder.py", line 80, in
 build
    instance = worker(self.bot, task_config)
  File "C:\__botPokemonGo-Bot\pokemongo_bot\base_task.py", line 23, in __init__
    self.initialize()
  File "C:\__botPokemonGo-Bot\pokemongo_bot\cell_workers\buddy_pokemon.py", line
 73, in initialize
    self._check_old_reward()
  File "C:\__botPokemonGo-Bot\pokemongo_bot\cell_workers\buddy_pokemon.py", line
 205, in _check_old_reward
    km_diff = self._km_walked() - self.buddy['last_km_awarded']
KeyError: 'last_km_awarded'
[2016-10-10 14:53:58] [sentry.errors] [ERROR] Sentry responded with an error: 'a
scii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url
: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\raven\transport\threaded.py", line 174, in
 send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "C:\Python27\lib\site-packages\raven\transport\http.py", line 47, in send

    ca_certs=self.ca_certs,
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line
494, in open
    response = self._open(req, data)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line
512, in _open
    '_open', req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line
466, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 46, in https_op
en
    return self.do_open(ValidHTTPSConnection, req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line
1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python27\lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal
not in range(128)
[2016-10-10 14:53:58] [sentry.errors.uncaught] [ERROR] [u"KeyError: 'last_km_awa
rded'", u'  File "pokecli.py", line 843, in <module>', u'  File "pokecli.py", li
ne 191, in main', u'  File "pokecli.py", line 146, in start_bot', u'  File "poke
cli.py", line 98, in initialize_task', u'  File "C:\\__botPokemonGo-Bot\\pokemon
go_bot\\tree_config_builder.py", line 80, in build', u'  File "C:\\__botPokemonG
o-Bot\\pokemongo_bot\\base_task.py", line 23, in __init__', u'  File "C:\\__botP
okemonGo-Bot\\pokemongo_bot\\cell_workers\\buddy_pokemon.py", line 73, in initia
lize', u'  File "C:\\__botPokemonGo-Bot\\pokemongo_bot\\cell_workers\\buddy_poke
mon.py", line 205, in _check_old_reward']

 Something went wrong and the bot needed to be restarted. Please investigate the
 cause.

before everything worked fine.

**Comment by m2mbr** [comment]
Please read #5773  #5768
