### ISSUE TITLE
[NEWS] Old API, New API

### ISSUE THREAD

**Issue by PokemonGoZ** [PokemonGoF/PokemonGo-Bot#5781]
Most of you have already read by old post
(if not check it out before reading this! #5773 )

The old API 0.35 was cut off recently, but the new API 0.39 is almost done being Reverse Engineered. It should be finished by the end of the weekend, and the bot should be working (if someone updates the PokeAPI) in a week or two. So please stick around, and thank you everyone!

Also, don't thank me, thank the devs working on the API at [reddit](https://www.reddit.com/r/pokemongodev)

**Comment by venney** [comment]
Thanks you all anyway!

One question about CAPTCHA: today I leave my cell phone running Pokemon GO, and I put the cell phone inside a drawer with weak GPS signal. Then after a while, CAPTCHA appear.
Will we pass CAPTCHA automatically in the following release?
Thanks.

**Comment by mmixx** [comment]
On what i've experienced after they cut off the 0.35 api was... My main account, which I stopped few days before their update, didn't receive any warning nor captcha prompt when I log it in on my phone... But with my other account which I tested, and used it after their update, gets a captcha every time I log in... I think they have a flag on who uses third party and 0.35 api on and after the day of the update...

**Comment by Paradoxum** [comment]
> On what i've experienced after they cut off the 0.35 api was... My main account, which I stopped few days before their update, didn't receive any warning nor captcha prompt when I log it in on my phone... But with my other account which I tested, and used it after their update, gets a captcha every time I log in... I think they have a flag on who uses third party and 0.35 api on and after the day of the update...

I don't think so. I botted right up until the api was cut off, and then even tried to connect after (not knowing the api had been cut off), and I haven't had a SINGLE captcha on my game on the phone, not even once. Maybe it's regional? I'm in the UK. Account is still active and has sniped pokemon from allover the world too.

**Comment by mmixx** [comment]
@Paradoxum I guess so... After they have cut off the old API... How much longer have you used your bot? I used mine for almost 3 hours after the update and then it stopped working...

**Comment by Vladoyu** [comment]
I got an idea and it goes like this. 
As u all know,there is a new pokemon bot on the market made by Niantic itself,and its called: 
Pokemon Go PLUS!
It uses the same process as bot once did. As u walk with Pokemon Go PLUS,it collects Pokestops and catches Pokemons on his own as u pass by. Sounds familiar?
So,if someone can replicate its program,and use it as a NEW bot,maybe u got yourself a perma bot.
Just an Idea
cheers

**Comment by DBa2016** [comment]
As far as I know, PoGo+ is connected to PoGo APP running on a cellphone. So yes, of course you could fake this accessoir, but it does not help you because you still are bound to your phone app.

**Comment by mmixx** [comment]
Yeah... And I'm guessing that the PoGo+ is just using the API functions of the PoGo app that is installed on your cellphone...

**Comment by WayneUong** [comment]
How about PoGo++, the tweak that overlays the iOS app? Can't we develop a bot like that?

**Comment by DBa2016** [comment]
no need for that, just take a GPS faker. Would work on jailbroken devices only, of course. Would require a freely available iOS10 jailbreak... Oops :)

**Comment by Nik0lashka** [comment]
@DBa2016 if you have mac, you don't need a JB for iOS - you can use xCode to fake your gps.

**Comment by pranavperfect** [comment]
FastPokeMap claims they've broken the new API. And updates on that?

**Comment by pablossp** [comment]
Apparently they're keeping the API for their own use for now. 
They're talking about not supporting any botting community as it "ruins" the game according to themselves.

**Comment by camnomis** [comment]
FPM is up and running, albeit it throttled at the moment, but seems to be working.

Now the big question is will they share?

**Comment by hklcf** [comment]
why FPM run so fast...

**Comment by unknowkir** [comment]
now will wait for the bot to start working again ? do we know when ?

**Comment by MerlionRock** [comment]
@camnomis I quote the developer Waryas of FPM

> We are releasing the API.
When it is in a "usable" non hacky state.
The person who did 90% of the work on the reversing refuse to release it in its current state. I will respect his wish.
You can call me a scum or w/e you want. I won't backstab the person who did all the work.

**Comment by camnomis** [comment]
@MerlionRock so I guess we just wait!

**Comment by DBa2016** [comment]
@Nik0lashka - your statement does not affect mine in any way.

**Comment by a1russell** [comment]
[It doesn't seem like FPM will be releasing the API.](https://www.reddit.com/r/pokemongodev/comments/59of07/fpm_dev_no_longer_releasing_api_keeping/)

**Comment by camnomis** [comment]
Not completely unexpected, FPM will make a good revenue from ads on their site, releasing the API will put that at risk, it's a shame but hopefully it can be picked up by others

**Comment by mmixx** [comment]
The one who leaked the code just wasted the time and effort of those who did all the work... Tsk...

**Comment by WayneUong** [comment]
It's a step back for FPM, but a step forward to an open source API. Also, only 7 people got the link. I've been searching the whole day for it and still can't find it. Doubt Niantic could find it.

**Comment by mmixx** [comment]
And I've been reading reddit about the leak... And a lot are speculating about FPM doesn't want to share it so they made a false claim that someone leaked the code to prevent others on asking when the ETA for releasing the code to public...

**Comment by MerlionRock** [comment]
We will know eventually if it's a real leak or false claim soon.

The person who got them, if real, won't be sitting there with the source and do nothing, right?

**Comment by camnomis** [comment]
All depends on how much was leaked?

I saw the comments on Reddit questioning if they leaked themselves, to then turn round and have an excuse to cut everyone else and I'm not sure, not seen anyone who can say anything other than referencing someone else who quotes someone. I get people might be unhappy but that's how nastiness starts, if they release it great, but I'm not vilifying them for not doing something that is against their own commercial interests, if I was a dev who worked on #RE to get in fracked they might have comeback, but then again they probably know more than the rest of us are speculating anyway

**Comment by Dr8g0n** [comment]
[Api release] How to get the leaked file to work 
https://www.reddit.com/r/pokemongodev/comments/5a0obu/api_release_how_to_get_the_leaked_file_to_work/?st=iuvfzedh&sh=bd3cfc25

**Comment by solderzzc** [comment]
Good job, UK6 has bean working hard:
https://github.com/laverdet/pcrypt-c

**Comment by MerlionRock** [comment]
Great Job! Hope still got people around here to know that the API is coming soon.

**Comment by gpires** [comment]
Port to python in progress: https://github.com/M4d40/pogo-py-hash/blob/patch-1/pgo_test.py

**Comment by MerlionRock** [comment]
The new API is ready.

Aren't you excited? Hopefully we'll see this site getting busy as it used to be....

**Comment by WayneUong** [comment]
https://github.com/ZeChrales/pgoapi/tree/master
all done??

**Comment by MerlionRock** [comment]
@wayneUong the only way to be sure is get the new libraries and import into this project...

**Comment by WayneUong** [comment]
@PokemonGoZ the python lib seems to be updated now, do you have any idea how we can start this project again?

**Comment by pablossp** [comment]
I got it working but it's poorly coded, you can check on discord. 
Maybe one of the main devs can properly integrate it on the main branch, it was pretty easy.

**Comment by Jcolomar** [comment]
https://github.com/pogodevorg/pgoapi/releases ---> pgoapi 0.43.3-alpha

**Comment by unknowkir** [comment]
if i download the bot now it will work? or i will get baned?

**Comment by Jcolomar** [comment]
in discord i saw some ppl using this api and works. But i dont know how

**Comment by Jcolomar** [comment]
@everyone https://github.com/pogodevorg/pgoapi/ python API is done

**Comment by mmixx** [comment]
I updated my copy with the latest **pgoapi**... I changed the line on `requirements.txt` where it checks for new version of **pgoapi** to this one below...

`-e git+https://github.com/pogodevorg/pgoapi.git/@v0.43.3-alpha#egg=pgoapi`

The current tag used by **pgoapi** is _v0.43.3-alpha_...

```
~/pgoapi$ git describe --tags --abbrev=0
v0.43.3-alpha
```

And it updates the api...

```
Obtaining pgoapi from git+https://github.com/pogodevorg/pgoapi.git/@v0.43.3-alpha#egg=pgoapi (from -r requirements.txt (line 3))
  Updating ./src/pgoapi clone (to v0.43.3-alpha)
```

But after I run the `./setup.sh -u` and executed `./run.sh`... These are the errors I've encountered... 

```
[2016-11-07 00:02:37] [PokemonGoBot] [INFO] Login procedure started.
[2016-11-07 00:02:51] [PokemonGoBot] [INFO] Login successful.
[2016-11-07 00:02:51] [PokemonGoBot] [INFO] Found encrypt.so! Platform: linux2 encrypt.so directory: /home/GObot/PokemonGo-Bot
_inventory was not initialized
_inventory was not initialized
[2016-11-07 00:02:51] [       cli] [INFO] 
[2016-11-07 00:02:51] [       cli] [INFO] Ran for 0:00:14
[2016-11-07 00:02:51] [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
[2016-11-07 00:02:51] [       cli] [INFO] Travelled 0.00km
[2016-11-07 00:02:51] [       cli] [INFO] Visited 0 stops
[2016-11-07 00:02:51] [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
[2016-11-07 00:02:51] [       cli] [INFO] Threw 0 pokeballs
[2016-11-07 00:02:51] [       cli] [INFO] Earned 0 Stardust
[2016-11-07 00:02:51] [       cli] [INFO] Hatched eggs 0
[2016-11-07 00:02:51] [       cli] [INFO] 
[2016-11-07 00:02:51] [       cli] [INFO] Highest CP Pokemon: 
[2016-11-07 00:02:51] [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 843, in <module>
    main()
  File "pokecli.py", line 191, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 145, in start_bot
    bot.start()
  File "/home/GObot/PokemonGo-Bot/pokemongo_bot/__init__.py", line 147, in start
    self._setup_api()
  File "/home/GObot/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1012, in _setup_api
    self.api.activate_signature(self.get_encryption_lib())
  File "/home/GObot/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 133, in activate_signature
    "\r\n Use set_signature_lib and set_hash_lib to override if needed.")
Exception: activate_signature is deprecated, binaries compatible with 0.41 API are now required.
 Comment out all calls to activate_signature to let them be autodetected. 
 Use set_signature_lib and set_hash_lib to override if needed.
```

**Comment by Jcolomar** [comment]
Same error for me. I hope devs read and start work again in this bot

**Comment by WayneUong** [comment]
@mmixx @Jcolomar why don't you join the discord channel, we're discussing this error there.

**Comment by Jcolomar** [comment]
im there also

**Comment by mmixx** [comment]
I think I already joined... But haven't logged in on discord since last week...

**Comment by Cptspal** [comment]
You need to download encrypt64 and niantichash from there : https://github.com/ZeChrales/pgoapi/tree/master/pgoapi/lib
and modify pokemongo-bot/__init__.py :
comment line `self.api.activate_signature(self.get_encryption_lib())`
and add lines : 
`set_signature_lib(path_yo_your_encrypt64_file)
set_hash_lib(path_yo_your_niantichash_file)`

**Comment by crvfts** [comment]
@Cptspal what is the correct syntax to use? I am trying: `# self.api.activate_signature(self.get_encryption_lib())
                self.api.set_signature_lib(C:/TRY/PokemonGo-Bot)
                self.api.set_hash_lib(C:/TRY/PokemonGo-Bot)`

**Comment by crvfts** [comment]
Just wanted to note that I had to rename encrypt64.dll to encrypt_64.dll. 

Bot is working for me! Gotta catch 'em all!

**Comment by mmixx** [comment]
Yep! Bot is working now doing what @Cptspal said... Currently using linux, so I just copied libencrypt and libniantichash for linux on the directory where I installed the bot and modified `pokemongo_bot/init.py` to what was written above and viola! Bot is working!

**Comment by reigelgallarde** [comment]
yeap bot is working... changed this line `self.api.activate_signature(self.get_encryption_lib())` 

to

````
self.api.set_signature_lib(self.get_encryption_lib())
self.api.set_hash_lib(self.get_niantic_hash())
````

and added a function get_niantic_hash... which is basically just a copy of get_encryption_lib with little changes that points to niantichash  .dll or .so file...

**Comment by db-coder** [comment]
Can someone list down all the changes that we need to do to get things started?

**Comment by reigelgallarde** [comment]
@db-coder try my explanation above.. I'm not sure if it's enough but that's what I did...

**Comment by db-coder** [comment]
Finally got it working :D 
These are the changes:

In **requiements.txt**, replace the pgoapi with the latest one:
`-e git+https://github.com/pogodevorg/pgoapi.git/@v0.43.3-alpha#egg=pgoapi`
In **_init_.py**, replace all instances of `self.api.activate_signature(self.get_encryption_lib())` with 
```
self.api.set_signature_lib(self.get_encryption_lib())
self.api.set_hash_lib(self.get_niantic_hash())
```
Download libencrypt and libniantichash .so or .dll from [here](https://github.com/ZeChrales/pgoapi/tree/master/pgoapi/lib) and place them in pgo root directory.

Add this function in **_init_.py** : 

```
def get_niantic_hash(self):
        if _platform == "Windows" or _platform == "win32":
            # Check if we are on 32 or 64 bit
            if sys.maxsize > 2**32:
                file_name = 'niantichash64.dll'
            else:
                file_name = 'niantichash32.dll'
        else:
            file_name = 'libniantichash-linux-x86-64.so'

        if self.config.encrypt_location == '':
            path = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
        else:
            path = self.config.encrypt_location

        full_path = path + '/'+ file_name
        if not os.path.isfile(full_path):
            self.logger.error(file_name + ' is not found! Please place it in the bots root directory or set encrypt_location in config.')
            self.logger.info('Platform: '+ _platform + ' ' + file_name + ' directory: '+ path)
            sys.exit(1)
        else:
            self.logger.info('Found '+ file_name +'! Platform: ' + _platform + ' ' + file_name + ' directory: ' + path)

        return full_path

```

**Comment by pablossp** [comment]
I created a PR (my first ever) earlier today with all the changes that need to be made.

https://github.com/PokemonGoF/PokemonGo-Bot/pull/5784

The only step missing is locating the appropiate library and hashing compiled files onto the root project directory.

**Comment by AlexJones6** [comment]
I'm a little new to this bot and it's fils and whatnot, and not too good (but I can do most basic stuff) with programming, can someone please make a more simplified instruction on what to, or even better, a video? Thanks! It would help a lot, also note I'm on Windows 10 (and a Mac but that's a different story lol)

**Comment by MerlionRock** [comment]
@alexJones6 They have not merge the new API. While I just got it working... it does crash after running for a period of time. Let those who are working on the project to work on it first. I believe with a week, we should see this project running like it use to be.

Hopefully.

**Comment by pablossp** [comment]
@MerlionRock  What kind of crash do you get?
I've experienced the old session expired error which makes the bot automatically restart and do the login procedures, but I wouldn't count this as a crash since it automatically reconnects.
I've been running it 5 hours straight with the default settings with no errors and no captcha pop up either.

**Comment by lukasz138** [comment]
After changes i got:
[sentry.errors] [ERROR] Sentry responded with an error: 'module' object has no attribute 'HTTPSHandler' (url: https://app.getsentry.com/api/90254/store/)

**Comment by Tschlact** [comment]
@pablossp I cloned your repo and installed it using your "pablossp" branch. It builds, installs, login!

It can transfer pokemons, evolve, drop items, do whatever does not require to move. But spinning forts and catching pokemons, no way. It stands still, sat down. 

Any guess?

**Comment by pablossp** [comment]
@Tschlact Yup, I made a mistake and pointed an incorrect library when running on linux, I fixed it on my branch now. Sorry :(, try again now.

**Comment by PratikBodawala** [comment]
I followed @db-coder instruction but got error.
`Traceback (most recent call last):
  File "pokecli.py", line 843, in <module>
    main()
  File "pokecli.py", line 191, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 145, in start_bot
    bot.start()
  File "/home/pratik/Documents/PokemonGo-Bot/pokemongo_bot/__init__.py", line 147, in start
    
  File "/home/pratik/Documents/PokemonGo-Bot/pokemongo_bot/__init__.py", line 999, in _setup_api
    
  File "/home/pratik/Documents/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 133, in activate_signature
    "\r\n Use set_signature_lib and set_hash_lib to override if needed.")
Exception: activate_signature is deprecated, binaries compatible with 0.41 API are now required.
 Comment out all calls to activate_signature to let them be autodetected. 
 Use set_signature_lib and set_hash_lib to override if needed.
[2016-11-07 18:46:31] [MainThread] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/pratik/Documents/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/pratik/Documents/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/pratik/Documents/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/pratik/Documents/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/pratik/Documents/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/pratik/Documents/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/pratik/Documents/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/pratik/Documents/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body

> UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
> [2016-11-07 18:46:31] [MainThread] [sentry.errors.uncaught] [ERROR] [u'Exception: activate_signature is deprecated, binaries compatible with 0.41 API are now required.\r\n Comment out all calls to activate_signature to let them be autodetected. \r\n Use set_signature_lib and set_hash_lib to override if needed.',

 u'  File "pokecli.py", line 843, in <module>', u'  File "pokecli.py", line 191, in main', u'  File "pokecli.py", line 145, in start_bot', u'  File "pokemongo_bot/__init__.py", line 147, in start', u'  File "pokemongo_bot/__init__.py", line 999, in _setup_api', u'  File "pgoapi/pgoapi.py", line 133, in activate_signature']
Mon Nov 7 18:46:31 IST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
  
`
I did download lib*.so file for linux x64, and tried with static path also, same error.

**Comment by JWNS** [comment]
@PratikBodawala I got the exact same error as you do, anyone came up with a solution ?

**Comment by MerlionRock** [comment]
@pablossp you are right.

Shouldn't count as crash, it does auto login.

**Comment by Cptspal** [comment]
`/home/pratik/Documents/PokemonGo-Bot/pokemongo_bot/__init__.py line 999, in _setup_api`
You have a call to activate_signature. If you follow what @db-coder write you have to replace all instance of activate_signature with both set_signature_lib and set_hash_lib

**Comment by JWNS** [comment]
It has already be done the way @db-coder described it ...
This error pops out AFTER all the indicated changes has been made =/

Just like @PratikBodawala I tried my luck with static paths, but it didnt work ...
Wondering why it works for some and not for me :'( :'( :'(

**Comment by Cptspal** [comment]
So maybe you don't have the same error as @PratikBodawala, because he still has a call to activate_signature...

**Comment by JWNS** [comment]
Yeah the error does not pop out at the exact same location but the behavior is quite the same ...
instead of 

File "/home/pratik/Documents/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 133, in activate_signature

I'll have a 

File "/home/pratik/Documents/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 144, in __getattr__ raise AttributeError

The following stuff is the exact same =/
I wildly guess it does not make a big diff ...

**Comment by PratikBodawala** [comment]
@Cptspal Thank you! 
I replace all instance,

> Traceback (most recent call last):
>   File "pokecli.py", line 843, in <module>
>     main()
>   File "pokecli.py", line 191, in main
>     bot = start_bot(bot, config)
>   File "pokecli.py", line 145, in start_bot
>     bot.start()
>   File "/home/pratik/Documents/PokemonGo-Bot/pokemongo_bot/__init__.py", line 172, in start
>     self._setup_api()
>   File "/home/pratik/Documents/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1028, in _setup_api
>     self.update_web_location()
>   File "/home/pratik/Documents/PokemonGo-Bot/pokemongo_bot/__init__.py", line 843, in update_web_location
>     cells = self.find_close_cells(*location)
>   File "/home/pratik/Documents/PokemonGo-Bot/pokemongo_bot/__init__.py", line 899, in find_close_cells
>     response_dict = self.get_map_objects(lat, lng, timestamp, cellid)
>   File "/home/pratik/Documents/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1458, in get_map_objects
>     cell_id=cellid
>   File "/home/pratik/Documents/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 153, in function
>     return request.call()
>   File "/home/pratik/Documents/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 208, in call
>     result = self._call()
>   File "/home/pratik/Documents/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 156, in _call
>     return PGoApiRequest.call(self)
>   File "/home/pratik/Documents/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 260, in call
>     response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
>   File "/home/pratik/Documents/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 140, in request
>     request_proto = self._build_main_request(subrequests, player_position)
>   File "/home/pratik/Documents/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 294, in _build_main_request
>     sig_request.encrypted_signature = self._generate_signature(signal_agglom_proto, sig.timestamp_ms_since_start)
>   File "/home/pratik/Documents/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 314, in _generate_signature
>     signature = b''.join(list(map(lambda x: six.int2byte(x), output.contents)))
> ValueError: NULL pointer access

**Comment by mmixx** [comment]
This is the only error I get...

```
Traceback (most recent call last):
  File "pokecli.py", line 843, in <module>
    main()
  File "pokecli.py", line 202, in main
    bot.tick()
  File "/home/GObot/PokemonGo-Bot/pokemongo_bot/__init__.py", line 749, in tick
    self.cell = self.get_meta_cell()
  File "/home/GObot/PokemonGo-Bot/pokemongo_bot/__init__.py", line 775, in get_meta_cell
    cells = self.find_close_cells(*location)
  File "/home/GObot/PokemonGo-Bot/pokemongo_bot/__init__.py", line 888, in find_close_cells
    response_dict = self.get_map_objects(lat, lng, timestamp, cellid)
  File "/home/GObot/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1475, in get_map_objects
    cell_id=cellid
  File "/home/GObot/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 153, in function
    return request.call()
  File "/home/GObot/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 208, in call
    result = self._call()
  File "/home/GObot/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 156, in _call
    return PGoApiRequest.call(self)
  File "/home/GObot/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 260, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/home/GObot/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 141, in request
    response = self._make_rpc(endpoint, request_proto)
  File "/home/GObot/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 129, in _make_rpc
    http_response = self._session.post(endpoint, data=request_proto_serialized, timeout=30)
  File "/home/GObot/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/GObot/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/GObot/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/sessions.py", line 617, in send
    r.content
  File "/home/GObot/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/home/GObot/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/models.py", line 664, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/GObot/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 349, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/GObot/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 501, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/home/GObot/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 470, in _handle_chunk
    returned_chunk = self._fp._safe_read(self.chunk_left)
  File "/usr/lib/python2.7/httplib.py", line 703, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/GObot/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/green/ssl.py", line 200, in recv
    read = self.read(buflen)
  File "/home/GObot/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/green/ssl.py", line 139, in read
    super(GreenSSLSocket, self).read, *args, **kwargs)
  File "/home/GObot/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/green/ssl.py", line 119, in _call_trampolining
    timeout_exc=timeout_exc('timed out'))
  File "/home/GObot/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 162, in trampoline
    return hub.switch()
  File "/home/GObot/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 294, in switch
    return self.greenlet.switch()
ssl.SSLError: ('timed out',)
Tue Nov 8 03:55:22 PHT 2016 Pokebot  Stopped.
```
It shows up every few minutes or sometimes hour(s) of botting...

**Comment by NoAckUFaka** [comment]
I copied and followed the instructions above but I'm getting the error:
`Traceback (most recent call last):
  File "pokecli.py", line 843, in <module>
    main()
  File "pokecli.py", line 191, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 145, in start_bot
    bot.start()
  File "D:\Bot\PokemonGo-Bot\pokemongo_bot\__init__.py", line 144, in start
    self._setup_api()
  File "D:\Bot\PokemonGo-Bot\pokemongo_bot\__init__.py", line 993, in _setup_api
    self.update_web_location()
  File "D:\Bot\PokemonGo-Bot\pokemongo_bot\__init__.py", line 806, in update_web_location
    cells = self.find_close_cells(*location)
  File "D:\Bot\PokemonGo-Bot\pokemongo_bot\__init__.py", line 862, in find_close_cells
    response_dict = self.get_map_objects(lat, lng, timestamp, cellid)
  File "D:\Bot\PokemonGo-Bot\pokemongo_bot\__init__.py", line 1423, in get_map_objects
    cell_id=cellid
  File "d:\bot\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 153, in function
    return request.call()
  File "D:\Bot\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 208, in call
    result = self._call()
  File "D:\Bot\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 156, in _call
    return PGoApiRequest.call(self)
  File "d:\bot\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 260, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "d:\bot\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 140, in request
    request_proto = self._build_main_request(subrequests, player_position)
  File "d:\bot\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 294, in _build_main_request
    sig_request.encrypted_signature = self._generate_signature(signal_agglom_proto, sig.timestamp_ms_since_start)
  File "d:\bot\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 314, in _generate_signature
    signature = b''.join(list(map(lambda x: six.int2byte(x), output.contents)))
ValueError: NULL pointer access`

**Comment by SoulSkare** [comment]
quick fix is replace self.buddy['last_km_awarded'] in "/PokemonGo-Bot/pokemongo_bot/cell_workers/buddy_pokemon.py" with a default value or fix the key issue by defining it properly.

then save and compile the py 
$ sudo python -m py_compile buddy_pokemon.py

then sudo ./run.sh

*TESTED WITH PTC

**Comment by albert69** [comment]
I'm having this error. please help.
Traceback <most recent call last>:
File "pokecli.py", line 47, in <module>
from pgoapi.exemptions import NotLoggedInExemptions,  .. . . ... and soon.
File "c:\python27\scripts\src\pgoapi\pgoapi.py", line 33, in <module>
from . import __title__, __version__, __copyright__
ValueError: Attempted relative import in non-package.

**Comment by PokemonGoZ** [comment]
The bot should be working now since the new PR. Sorry for inactivity.
