### ISSUE TITLE
Bot Won't Start

### ISSUE THREAD

**Issue by yelnatscoding** [PokemonGoF/PokemonGo-Bot#5798]
// ♥ ./run.sh
2016-11-09 05:02:11,052 [       cli] [INFO] PokemonGO Bot v1.0
2016-11-09 05:02:11,062 [       cli] [INFO] commit: 5439a712
2016-11-09 05:02:11,066 [       cli] [INFO] Configuration initialized
2016-11-09 05:02:11,067 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-11-09 05:02:11,067 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-11-09 05:02:11,083 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
(16640) wsgi starting up on http://127.0.0.1:4000
[2016-11-09 05:02:11] [SleepSchedule] [INFO] Next sleep at 12:17:27, for a duration of 05:15:13
[2016-11-09 05:02:11] [PokemonGoBot] [INFO] Setting start location.
[2016-11-09 05:02:11] [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
[2016-11-09 05:02:11] [PokemonGoBot] [INFO] Location found: 40.772250, -73.971413 (40.77225, -73.971413, 8.0)
[2016-11-09 05:02:11] [PokemonGoBot] [INFO] Now at (40.77225, -73.971413, 8.0)
[2016-11-09 05:02:11] [PokemonGoBot] [INFO] Login procedure started.
_inventory was not initialized
_inventory was not initialized
[2016-11-09 05:02:11] [       cli] [INFO] 
[2016-11-09 05:02:11] [       cli] [INFO] Ran for 0:00:00
[2016-11-09 05:02:11] [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
[2016-11-09 05:02:11] [       cli] [INFO] Travelled 0.00km
[2016-11-09 05:02:11] [       cli] [INFO] Visited 0 stops
[2016-11-09 05:02:11] [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
[2016-11-09 05:02:11] [       cli] [INFO] Threw 0 pokeballs
[2016-11-09 05:02:11] [       cli] [INFO] Earned 0 Stardust
[2016-11-09 05:02:11] [       cli] [INFO] Hatched eggs 0
[2016-11-09 05:02:11] [       cli] [INFO] 
[2016-11-09 05:02:11] [       cli] [INFO] Highest CP Pokemon: 
[2016-11-09 05:02:11] [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 843, in <module>
    main()
  File "pokecli.py", line 191, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 145, in start_bot
    bot.start()
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 147, in start
    self._setup_api()
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1037, in _setup_api
    self.login()
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 944, in login
    str(self.config.password))
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 103, in login
    response = PGoApi.app_simulation_login(self)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 169, in app_simulation_login
    response = request.call()
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 255, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 138, in request
    request_proto = self._build_main_request(subrequests, player_position)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 292, in _build_main_request
    sig_request.encrypted_signature = self._generate_signature(signal_agglom_proto, sig.timestamp_ms_since_start)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 310, in _generate_signature
    signature = b''.join(list(map(lambda x: six.int2byte(x), output.contents)))
ValueError: NULL pointer access
[2016-11-09 05:02:11] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 891, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
[2016-11-09 05:02:11] [sentry.errors.uncaught] [ERROR] [u'ValueError: NULL pointer access', u'  File "pokecli.py", line 843, in <module>', u'  File "pokecli.py", line 191, in main', u'  File "pokecli.py", line 145, in start_bot', u'  File "pokemongo_bot/__init__.py", line 147, in start', u'  File "pokemongo_bot/__init__.py", line 1037, in _setup_api', u'  File "pokemongo_bot/__init__.py", line 944, in login', u'  File "pokemongo_bot/api_wrapper.py", line 103, in login', u'  File "pgoapi/pgoapi.py", line 169, in app_simulation_login', u'  File "pgoapi/pgoapi.py", line 255, in call', u'  File "pgoapi/rpc_api.py", line 138, in request', u'  File "pgoapi/rpc_api.py", line 292, in _build_main_request', u'  File "pgoapi/rpc_api.py", line 310, in _generate_signature']
Wed Nov 9 05:02:11 EST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
  
keep getting this error. Not related to buddy pokemon

**Comment by menegazzo** [comment]
Same here. Already downloaded/installed encrypt libraries but nothing changes.

**Comment by 1240** [comment]
+1

**Comment by oleerik** [comment]
Same here, worked fine yesterday!

**Comment by sirgt** [comment]
same here on Mac

**Comment by MZorzy** [comment]
@jaderalves00 may u post the last commit number of working version pls ?

**Comment by Jcolomar** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/tree/c346f344e6539887876e61eaf4e47b0f0c88e2fc

**Comment by jaderalves00** [comment]
I am not home right now but I clone about 20:00 local time (gmt-3)

**Comment by cbogithub** [comment]
[2016-11-09 22:52:14] [MainThread] [PokemonGoBot] [INFO] Login procedure started.
[2016-11-09 22:53:01] [MainThread] [pgoapi.auth] [ERROR] PTC User Login Error - Field missing in response: No JSON object could be decoded
[2016-11-09 22:53:01] [MainThread] [PokemonGoBot] [INFO] Login process failed: User login failed!

**Comment by MerlionRock** [comment]
The api have moved.

The encypts are at: https://github.com/pokecrypt/pokecrypt-pgoapi

**Comment by menegazzo** [comment]
@MerlionRock so how it should be downloaded/installed?

**Comment by MZorzy** [comment]
if copyed to src/pgoapi/pgoapi/lib still no work, same 0x9c error

**Comment by yelnatscoding** [comment]
Traceback (most recent call last):
  File "pokecli.py", line 843, in <module>
    main()
  File "pokecli.py", line 191, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 145, in start_bot
    bot.start()
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 147, in start
    self._setup_api()
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1037, in _setup_api
    self.login()
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 944, in login
    str(self.config.password))
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 103, in login
    response = PGoApi.app_simulation_login(self)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 169, in app_simulation_login
    response = request.call()
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 255, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 138, in request
    request_proto = self._build_main_request(subrequests, player_position)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 292, in _build_main_request
    sig_request.encrypted_signature = self._generate_signature(signal_agglom_proto, sig.timestamp_ms_since_start)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 310, in _generate_signature
    signature = b''.join(list(map(lambda x: six.int2byte(x), output.contents)))
ValueError: NULL pointer access
[2016-11-09 15:59:07] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 891, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
[2016-11-09 15:59:07] [sentry.errors.uncaught] [ERROR] [u'ValueError: NULL pointer access', u'  File "pokecli.py", line 843, in <module>', u'  File "pokecli.py", line 191, in main', u'  File "pokecli.py", line 145, in start_bot', u'  File "pokemongo_bot/__init__.py", line 147, in start', u'  File "pokemongo_bot/__init__.py", line 1037, in _setup_api', u'  File "pokemongo_bot/__init__.py", line 944, in login', u'  File "pokemongo_bot/api_wrapper.py", line 103, in login', u'  File "pgoapi/pgoapi.py", line 169, in app_simulation_login', u'  File "pgoapi/pgoapi.py", line 255, in call', u'  File "pgoapi/rpc_api.py", line 138, in request', u'  File "pgoapi/rpc_api.py", line 292, in _build_main_request', u'  File "pgoapi/rpc_api.py", line 310, in _generate_signature']

still same issue. tried to update new files. i'm not a new user to this bot either.

**Comment by YangSkyL** [comment]
my bot is now working on ubuntu 16.04

what I have done are:
1. remove pgoapi folder from scr/
2. change api repo in requirements.txt to 
-e git+https://github.com/sebastienvercammen/pgoapi.git#egg=pgoapi
3. run ./setup.sh -u
4 and you are able to run bot again..

credit to @houkup

**Comment by Gobberwart** [comment]
Yep, this works.

**Comment by yelnatscoding** [comment]
did not work for me .

**Comment by yelnatscoding** [comment]
Traceback (most recent call last):
  File "pokecli.py", line 843, in <module>
    main()
  File "pokecli.py", line 191, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 145, in start_bot
    bot.start()
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 147, in start
    self._setup_api()
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1037, in _setup_api
    self.login()
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 944, in login
    str(self.config.password))
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 103, in login
    response = PGoApi.app_simulation_login(self)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 172, in app_simulation_login
    response = request.call()
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 247, in call
    default_libraries = get_encryption_lib_paths()
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/src/pgoapi/pgoapi/utilities.py", line 231, in get_encryption_lib_paths
    raise Exception(err)
Exception: Could not find darwin hashing library /Users/Ticketmaster/Desktop/PokemonGo-Bot/src/pgoapi/pgoapi/lib/libniantichash-osx-64.so
2016-11-09 16:30:53,525 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/Ticketmaster/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 891, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-11-09 16:30:53,527 [sentry.errors.uncaught] [ERROR] [u'Exception: Could not find darwin hashing library /Users/Ticketmaster/Desktop/PokemonGo-Bot/src/pgoapi/pgoapi/lib/libniantichash-osx-64.so', u'  File "pokecli.py", line 843, in <module>', u'  File "pokecli.py", line 191, in main', u'  File "pokecli.py", line 145, in start_bot', u'  File "pokemongo_bot/__init__.py", line 147, in start', u'  File "pokemongo_bot/__init__.py", line 1037, in _setup_api', u'  File "pokemongo_bot/__init__.py", line 944, in login', u'  File "pokemongo_bot/api_wrapper.py", line 103, in login', u'  File "pgoapi/pgoapi.py", line 172, in app_simulation_login', u'  File "pgoapi/pgoapi.py", line 247, in call', u'  File "pgoapi/utilities.py", line 231, in get_encryption_lib_paths']
Wed Nov 9 16:30:53 EST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

**Comment by YangSkyL** [comment]
@yelnatscoding 
seems you bot cant find libniantichash-osx-64.so

**Comment by menegazzo** [comment]
Worked like a charm!

**Comment by yelnatscoding** [comment]
how can i fix it not finding libniantichash

**Comment by jury89** [comment]
I have the same error @yelnatscoding is having...i'm trying to understand why `src/pgoapi/pgoapi/lib/libniantichash-osx-64.so` doesn't exists...someone can help?

**Comment by 1240** [comment]
@jury89 same here

**Comment by krummrey** [comment]
a quickfix is to rename libniantichash-macos-64.dylib to libniantichash-osx-64.so

**Comment by jury89** [comment]
it is working, thank you @krummrey
