### ISSUE TITLE
Unable to pip install reqirments.txt

### ISSUE THREAD

**Issue by foster82** [PokemonGoF/PokemonGo-Bot#5802]
Hi guys trying to run pip install -r requirements.txt 

And getting the 
(PokemonGo-Bot) pi@raspberrypi:~/Poke/PokemonGo-Bot $ pip install -r requirements.txt
Traceback (most recent call last):
  File "/home/pi/Poke/PokemonGo-Bot/bin/pip", line 7, in <module>    from pip import main
  File "/home/pi/Poke/PokemonGo-Bot/local/lib/python2.7/site-packages/pip/__init__.py", line 14, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/home/pi/Poke/PokemonGo-Bot/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/home/pi/Poke/PokemonGo-Bot/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 69, in <module>    __import__('pip._vendor.packaging.version')
  File "/home/pi/Poke/PokemonGo-Bot/local/lib/python2.7/site-packages/pip/_vendor/packaging/version.py", line 10, in <module>
    from ._structures import Infinity
EOFError: EOF read where object expected

Running Linux dabian on my too. Any ideas.

**Comment by Gobberwart** [comment]
try pip install -r ./requirements.txt --upgrade. Same error?

**Comment by foster82** [comment]
Yeah still the same

**Comment by foster82** [comment]
OK this is the error I now get after another git pull


pip install -r requirements.txt --upgrade
Traceback (most recent call last):                                 File "/home/pi/Poke/PokemonGo-Bot/bin/pip", line 7, in <module>    from pip import main                                           File "/home/pi/Poke/PokemonGo-Bot/local/lib/python2.7/site-packages/pip/__init__.py", line 16, in <module>                          from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/pi/Poke/PokemonGo-Bot/local/lib/python2.7/site-packages/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/home/pi/Poke/PokemonGo-Bot/local/lib/python2.7/site-packages/pip/index.py", line 30, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/home/pi/Poke/PokemonGo-Bot/local/lib/python2.7/site-packages/pip/wheel.py", line 39, in <module>
    from pip._vendor.distlib.scripts import ScriptMaker
  File "/home/pi/Poke/PokemonGo-Bot/local/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 15, in <module>
    from .resources import finder
ValueError: bad marshal data (unknown type code)

**Comment by solderzzc** [comment]
Refresh clone should fix it. Reopen if not.
