### ISSUE TITLE
Bot does not start

### ISSUE THREAD

**Issue by Pietr** [PokemonGoF/PokemonGo-Bot#5806]
Hi.
I have a problem running the bot. I have the following errors: http://pastebin.com/tHuTTdW7

### Other Information
OS:  Debian 7 x64
Branch: dev
Git Commit: 665c3b3f06a4202a94874452b7c3098db800f5f8
Python Version: 2.7.12

**Comment by maxer137** [comment]
i got it fixed after reinstalling the auth.js file with ./setup -a

**Comment by Pietr** [comment]
Thanks. New log:
root@vpspietr:~/PokemonGo-Bot# ./run.sh
2016-11-11 18:56:54,281 [       cli] [INFO] PokemonGO Bot v1.0
2016-11-11 18:56:54,289 [       cli] [INFO] commit: 665c3b3f
2016-11-11 18:56:54,294 [       cli] [INFO] Configuration initialized
2016-11-11 18:56:54,294 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-11-11 18:56:54,294 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-11-11 18:56:54,304 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
(9996) wsgi starting up on http://127.0.0.1:4000
[2016-11-11 18:56:54] [PokemonGoBot] [WARNING] SleepSchedule is disabled
[2016-11-11 18:56:54] [PokemonGoBot] [INFO] Setting start location.
_inventory was not initialized
_inventory was not initialized
[2016-11-11 18:56:54] [       cli] [INFO]
[2016-11-11 18:56:54] [       cli] [INFO] Ran for 0:00:00
[2016-11-11 18:56:54] [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h[2016-11-11 18:56:54] [       cli] [INFO] Travelled 0.00km
[2016-11-11 18:56:54] [       cli] [INFO] Visited 0 stops
[2016-11-11 18:56:54] [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
[2016-11-11 18:56:54] [       cli] [INFO] Threw 0 pokeballs
[2016-11-11 18:56:54] [       cli] [INFO] Earned 0 Stardust
[2016-11-11 18:56:54] [       cli] [INFO] Hatched eggs 0
[2016-11-11 18:56:54] [       cli] [INFO]
[2016-11-11 18:56:54] [       cli] [INFO] Highest CP Pokemon:
[2016-11-11 18:56:54] [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 846, in <module>
    main()
  File "pokecli.py", line 194, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 146, in start_bot
    bot.start()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 147, in start
    self._setup_api()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1043, in _setup_api
    self._set_starting_position()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1238, in _set_starting_position
    location = self.get_pos_by_name(location_str.replace(" ", ""))
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1363, in get_pos_by_name
    loc = geolocator.geocode(location_name, timeout=10)
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/geopy/geocoders/googlev3.py", line 217, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/geopy/geocoders/googlev3.py", line 338, in _parse_json
    self._check_status(page.get('status'))
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/geopy/geocoders/googlev3.py", line 369, in _check_status
    'Your request was denied.'
geopy.exc.GeocoderQueryError: Your request was denied.
[2016-11-11 18:56:54] [sentry.errors] [ERROR] Sentry responded with an error: 'module' object has no attribute 'HTTPSHandler' (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 44, in urlopen
    class ValidHTTPSHandler(urllib2.HTTPSHandler):
AttributeError: 'module' object has no attribute 'HTTPSHandler'
[2016-11-11 18:56:54] [sentry.errors.uncaught] [ERROR] [u'GeocoderQueryError: Your request was denied.', u'  File "pokecli.py", line 846, in <module>', u'  File "pokecli.py", line 194, in main', u'  File "pokecli.py", line 146, in start_bot', u'  File "pokemongo_bot/__init__.py", line 147, in start', u'  File "pokemongo_bot/__init__.py", line 1043, in _setup_api', u'  File "pokemongo_bot/__init__.py", line 1238, in _set_starting_position', u'  File "pokemongo_bot/__init__.py", line 1363, in get_pos_by_name', u'  File "geopy/geocoders/googlev3.py", line 217, in geocode', u'  File "geopy/geocoders/googlev3.py", line 338, in _parse_json', u'  File "geopy/geocoders/googlev3.py", line 369, in _check_status']
Fri Nov 11 18:56:54 CET 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue

**Comment by anandphulwani** [comment]
Was facing the same problem, tried for 8-9 times, finally worked, advice you to
1) Do not edit the file via notepad in any case.
2) Use configurator to generate the auth.json file.
3) If you really need to edit, use Notepad++.

**Comment by Pietr** [comment]
I not edited the file. How do I edit I use nano.

**Comment by anandphulwani** [comment]
@Pietr i think you should use vi editor.
Can you send me your auth.json file, so that i can test it on my computer, if there is any problem i can correct it and send it back to you.

**Comment by solderzzc** [comment]
Let me close it. Should be configuration related issue.
