### ISSUE TITLE
Error while updating to latest commit

### ISSUE THREAD

**Issue by db-coder** [PokemonGoF/PokemonGo-Bot#5813]
### Expected Behavior
Bot should update correctly

### Actual Behavior
```
Cleaning up...
Command /usr/bin/git submodule update --init --recursive -q failed with error code 1 in /home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/src/pgoapi
Storing debug log for failure in /home/dibyendu/.pip/pip.log
```

### Output when issue occurred

```
Command /usr/bin/git submodule update --init --recursive -q failed with error code 1 in /home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/src/pgoapi
Exception information:
Traceback (most recent call last):
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/pip/commands/install.py", line 304, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/pip/req.py", line 1141, in prepare_files
    req_to_install.update_editable(not self.is_download)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/pip/req.py", line 484, in update_editable
    vcs_backend.obtain(self.source_dir)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/pip/vcs/git.py", line 109, in obtain
    if self.check_destination(dest, url, rev_options, rev_display):
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/pip/vcs/__init__.py", line 199, in check_destination
    self.update(dest, rev_options)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/pip/vcs/git.py", line 99, in update
    self.update_submodules(dest)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/pip/vcs/git.py", line 192, in update_submodules
    cwd=location)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /usr/bin/git submodule update --init --recursive -q failed with error code 1 in /home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/src/pgoapi
```

### Steps to Reproduce
git pulll the latest commit and run ./setup.sh -u

### Other Information
OS: 
Ubuntu 15.04
Branch: 
dev
Git Commit: 
84670c60f83bcc5b96130e4d6ad3e0d9dfa6775a
Python Version: 
Python 2.7.9

**Comment by joltir** [comment]
I got this error just now during a setup -u:
Requirement already up-to-date: numpy==1.11.0 in ./lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: networkx==1.11 in ./lib/python2.7/site-packages (from -r requirements.txt (line 2))
Obtaining pgoapi from git+https://github.com/pogodevorg/pgoapi.git#egg=pgoapi (from -r requirements.txt (line 3))
  Updating ./src/pgoapi clone
fatal: reference is not a tree: 581d651eca61b654c6866d27dceff2a4818280f1
Unable to checkout '581d651eca61b654c6866d27dceff2a4818280f1' in submodule path 'pgoapi/lib'
Command "git submodule update --init --recursive -q" failed with error code 1 in /home/johan/PokemonGo-Bot/src/pgoapi
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): numpy==1.11.0 in ./lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): networkx==1.11 in ./lib/python2.7/site-packages (from -r requirements.txt (line 2))
Obtaining pgoapi from git+https://github.com/pogodevorg/pgoapi.git#egg=pgoapi (from -r requirements.txt (line 3))
  Updating ./src/pgoapi clone
fatal: reference is not a tree: 581d651eca61b654c6866d27dceff2a4818280f1
Unable to checkout '581d651eca61b654c6866d27dceff2a4818280f1' in submodule path 'pgoapi/lib'
Command "git submodule update --init --recursive -q" failed with error code 1 in /home/johan/PokemonGo-Bot/src/pgoapi

**Comment by solderzzc** [comment]
please try a refresh clone.

**Comment by db-coder** [comment]
Manually downloading the submodule worked for me.

**Comment by db-coder** [comment]
I'm getting this error a lot:
```
Traceback (most recent call last):
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/hubs/poll.py", line 115, in wait
    listener.cb(fileno)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/green/thread.py", line 41, in __thread_body
    func(*args, **kwargs)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/pokemongo_bot/event_handlers/social_handler.py", line 86, in run
    self._mqttc.connect("broker.pikabot.org", 1883, 20)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 686, in connect
    return self.reconnect()
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 808, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/green/socket.py", line 63, in create_connection
    raise err
error: [Errno 110] ETIMEDOUT
Removing descriptor: 14
```
Is there any solution?

**Comment by solderzzc** [comment]
Do you have a firewall blocking 1883 port outgoing ?

**Comment by db-coder** [comment]
Yeah, it might be the case that my univ blocks that port.

Another error I get too frequently:

```
Traceback (most recent call last):
  File "pokecli.py", line 846, in <module>
    main()
  File "pokecli.py", line 205, in main
    bot.tick()
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/pokemongo_bot/__init__.py", line 762, in tick
    self._refresh_inventory()
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1540, in _refresh_inventory
    inventory.refresh_inventory()
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1426, in refresh_inventory
    _inventory.refresh(data)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1266, in refresh
    inventory = self.bot.api.get_inventory()
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 150, in function
    return request.call()
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 208, in call
    result = self._call()
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 156, in _call
    return PGoApiRequest.call(self)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 259, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 139, in request
    response = self._make_rpc(endpoint, request_proto)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 127, in _make_rpc
    http_response = self._session.post(endpoint, data=request_proto_serialized, timeout=30)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/sessions.py", line 617, in send
    r.content
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/models.py", line 664, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 349, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 501, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 461, in _handle_chunk
    value = self._fp._safe_read(amt)
  File "/usr/lib/python2.7/httplib.py", line 702, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/green/ssl.py", line 200, in recv
    read = self.read(buflen)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/green/ssl.py", line 139, in read
    super(GreenSSLSocket, self).read, *args, **kwargs)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/green/ssl.py", line 119, in _call_trampolining
    timeout_exc=timeout_exc('timed out'))
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 162, in trampoline
    return hub.switch()
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 294, in switch
    return self.greenlet.switch()
ssl.SSLError: ('timed out',)

```

**Comment by joltir** [comment]
Thanks, a new install worked.

**Comment by solderzzc** [comment]
let me close it.
