### ISSUE TITLE
Crash on new install launch

### ISSUE THREAD

**Issue by moquette** [PokemonGoF/PokemonGo-Bot#5817]
Press any button or wait 20 seconds to continue.
  2016-11-15 12:11:05,838 [       cli] [INFO] PokemonGO Bot v1.0
2016-11-15 12:11:05,846 [       cli] [INFO] commit: 30dbcc0d
2016-11-15 12:11:05,849 [       cli] [INFO] Configuration initialized
2016-11-15 12:11:05,850 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-11-15 12:11:05,850 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-11-15 12:11:05,858 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
(23653) wsgi starting up on http://127.0.0.1:4000
[2016-11-15 12:11:05] [SleepSchedule] [INFO] Next sleep at 12:26:41, for a duration of 05:54:05
[2016-11-15 12:11:05] [PokemonGoBot] [INFO] Setting start location.
[2016-11-15 12:11:05] [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
[2016-11-15 12:11:05] [PokemonGoBot] [INFO] Location found: 37.809295714,-122.410976772 (37.809295714, -122.410976772, 8.0)
[2016-11-15 12:11:05] [PokemonGoBot] [INFO] Now at (37.809295714, -122.410976772, 8.0)
[2016-11-15 12:11:05] [PokemonGoBot] [INFO] Login procedure started.
[2016-11-15 12:11:07] [PokemonGoBot] [INFO] Login successful.
[2016-11-15 12:11:07] [PokemonGoBot] [INFO] 
[2016-11-15 12:11:07] [PokemonGoBot] [INFO] [x] Error while opening cached forts: [Errno 2] No such file or directory: u'/Users/moquette/Bot/pokemongo_bot/../data/recent-forts-Evolver1K.json'
[2016-11-15 12:11:08] [PokemonGoBot] [INFO] Level: 3 (Next Level: 2860 XP) (Total: 3140 XP)
[2016-11-15 12:11:08] [PokemonGoBot] [INFO] Pokemon Captured: 5 | Pokestops Visited: 0
[2016-11-15 12:11:08] [PokemonGoBot] [INFO] 
[2016-11-15 12:11:08] [PokemonGoBot] [INFO] --- Evolver1K ---
[2016-11-15 12:11:10] [PokemonGoBot] [INFO] Pokemon Bag: 5/250
[2016-11-15 12:11:10] [PokemonGoBot] [INFO] Items: 74/350
[2016-11-15 12:11:10] [PokemonGoBot] [INFO] Stardust: 1100 | Pokecoins: 0
[2016-11-15 12:11:10] [PokemonGoBot] [INFO] PokeBalls: 70 | GreatBalls: 0 | UltraBalls: 0 | MasterBalls: 0
[2016-11-15 12:11:10] [PokemonGoBot] [INFO] RazzBerries: 0 | BlukBerries: 0 | NanabBerries: 0
[2016-11-15 12:11:10] [PokemonGoBot] [INFO] LuckyEgg: 0 | Incubator: 0 | TroyDisk: 0
[2016-11-15 12:11:10] [PokemonGoBot] [INFO] Potion: 0 | SuperPotion: 0 | HyperPotion: 0 | MaxPotion: 0
[2016-11-15 12:11:10] [PokemonGoBot] [INFO] Incense: 2 | IncenseSpicy: 0 | IncenseCool: 0
[2016-11-15 12:11:10] [PokemonGoBot] [INFO] Revive: 0 | MaxRevive: 0
[2016-11-15 12:11:10] [PokemonGoBot] [INFO] 
[2016-11-15 12:11:10] [PokemonGoBot] [INFO] Pokemon:
[2016-11-15 12:11:10] [PokemonGoBot] [INFO] #4 Charmander: (CP 12, IV 0.67)
[2016-11-15 12:11:10] [PokemonGoBot] [INFO] #72 Tentacool: (CP 36, IV 0.67) | (CP 11, IV 0.69)
[2016-11-15 12:11:10] [PokemonGoBot] [INFO] #118 Goldeen: (CP 11, IV 0.36)
[2016-11-15 12:11:10] [PokemonGoBot] [INFO] #147 Dratini: (CP 37, IV 0.47)
[2016-11-15 12:11:10] [PokemonGoBot] [INFO] 
[2016-11-15 12:11:10] [RandomAlivePause] [INFO] Next random alive pause at 13:21:15, for a duration of 0:01:28
[2016-11-15 12:11:10] [RandomPause] [INFO] Next random pause at 12:41:42, for a duration of 0:00:53
[2016-11-15 12:11:10] [RecycleItems] [INFO] Next forced item recycle at 12:15:55
[2016-11-15 12:11:10] [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
[2016-11-15 12:11:10] [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
[2016-11-15 12:11:10] [PokemonGoBot] [INFO] Starting bot...
[2016-11-15 12:11:10] [CollectLevelUpReward] [INFO] Received level up reward: 
[2016-11-15 12:11:11] [       cli] [INFO] 
[2016-11-15 12:11:11] [       cli] [INFO] Ran for 0:00:06
[2016-11-15 12:11:11] [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
[2016-11-15 12:11:11] [       cli] [INFO] Travelled 0.00km
[2016-11-15 12:11:11] [       cli] [INFO] Visited 0 stops
[2016-11-15 12:11:11] [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
[2016-11-15 12:11:11] [       cli] [INFO] Threw 0 pokeballs
[2016-11-15 12:11:11] [       cli] [INFO] Earned 0 Stardust
[2016-11-15 12:11:11] [       cli] [INFO] Hatched eggs 0
[2016-11-15 12:11:11] [       cli] [INFO] 
[2016-11-15 12:11:11] [       cli] [INFO] Highest CP Pokemon: 
[2016-11-15 12:11:11] [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 846, in <module>
    main()
  File "pokecli.py", line 205, in main
    bot.tick()
  File "/Users/moquette/Bot/pokemongo_bot/__init__.py", line 770, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/Users/moquette/Bot/pokemongo_bot/cell_workers/buddy_pokemon.py", line 135, in work
    if self._km_walked() - self.buddy['last_km_awarded'] >= self.buddy_distance_needed:
KeyError: 'last_km_awarded'
[2016-11-15 12:11:11] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/moquette/Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/moquette/Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/moquette/Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/moquette/Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/moquette/Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/moquette/Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/moquette/Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/moquette/Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
[2016-11-15 12:11:11] [sentry.errors.uncaught] [ERROR] [u"KeyError: 'last_km_awarded'", u'  File "pokecli.py", line 846, in <module>', u'  File "pokecli.py", line 205, in main', u'  File "pokemongo_bot/__init__.py", line 770, in tick', u'  File "pokemongo_bot/cell_workers/buddy_pokemon.py", line 135, in work']
Tue Nov 15 12:11:11 PST 2016 Pokebot  Stopped.

**Comment by nachi9211** [comment]
Previous issues haven't exactly explained how to solve, please help.

https://github.com/PokemonGoF/PokemonGo-Bot/issues/5469
@Gobberwart , can you help me fix this?

**Comment by Gobberwart** [comment]
At a glance, I can tell you two things:

1. The error is in this line (135) of buddy_pokemon.py...

`if self._km_walked() - self.buddy['last_km_awarded'] >= self.buddy_distance_needed:`

Looks like 'last_km_awarded' is not a property of self.buddy. 

2. It's not even vaguely related to #5469 

I'd need a little more time to investigate the full cause, which I don't have at the moment, but there's a starting point.

**Comment by nachi9211** [comment]
Thank you @Gobberwart ,
I assumed this to be the same error, as I repeatedly get the same error message, however I have a different traceback leading to the inventory.py file,
The bot worked before the recent update, and this seems to be the only issue with the same error keywords, so I am replying here. The following error message is common in #5469 and #5817(this)

Error while opening cached forts: [Errno 2] No such file or directory: u'/Users/moquette/Bot/pokemongo_bot/../data/recent-forts-<gmail-id-here>
This error shows up every time I try to change the config file, even after using a new installation and gmail id.

**Comment by nachi9211** [comment]
Hey, sorry about the trouble,
Clearly I misunderstood the cause of the error.
This error MAY be appearing due to the recent cp changes,
It is covered here #5832 
Hope it helps.
