### ISSUE TITLE
[ERROR] Without error info

### ISSUE THREAD

**Issue by cierzniak** [PokemonGoF/PokemonGo-Bot#5831]
### Expected Behavior
Want to run bot

### Actual Behavior
Shows error without exact message, yesterday worked fine

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
Doesn't matter - yesterday was workin properly on 3 accounts with different configs

### Output when issue occurred
````
root@FriendlyARM:~/pokemongo-bot# ./run.sh ./configs/config-xxx.json ./configs/auth-xxx.json
2016-11-21 20:33:58,038 [       cli] [INFO] PokemonGO Bot v1.0
2016-11-21 20:33:58,070 [       cli] [INFO] commit: 979fb4d8
2016-11-21 20:33:58,095 [       cli] [INFO] Configuration initialized
(21840) wsgi starting up on http://0.0.0.0:4001
[2016-11-21 20:33:58] Setting start location.
[2016-11-21 20:33:58] Favorite location found: byd([u'xxx', u'xxx'])
[2016-11-21 20:33:58] Location found: XXX(xxx, xxx, 8.0)
[2016-11-21 20:33:58] Now at (xxx, xxx, 8.0)
[2016-11-21 20:33:58] Login procedure started.
[2016-11-21 20:34:00] Login successful.
[2016-11-21 20:34:01]
_inventory was not initialized
_inventory was not initialized
[2016-11-21 20:34:02]
[2016-11-21 20:34:02] Ran for 0:00:04
[2016-11-21 20:34:02] Total XP Earned: 0  Average: 0.00/h
[2016-11-21 20:34:02] Travelled 0.00km
[2016-11-21 20:34:02] Visited 0 stops
[2016-11-21 20:34:02] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
[2016-11-21 20:34:02] Threw 0 pokeballs
[2016-11-21 20:34:02] Earned 0 Stardust
[2016-11-21 20:34:02] Hatched eggs 0
[2016-11-21 20:34:02]
[2016-11-21 20:34:02] Highest CP Pokemon:
[2016-11-21 20:34:02] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 846, in <module>
    main()
  File "pokecli.py", line 194, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 146, in start_bot
    bot.start()
  File "/root/pokemongo-bot/pokemongo_bot/__init__.py", line 149, in start
    init_inventory(self)
  File "/root/pokemongo-bot/pokemongo_bot/inventory.py", line 1416, in init_inventory
    _inventory = Inventory(bot)
  File "/root/pokemongo-bot/pokemongo_bot/inventory.py", line 1260, in __init__
    self.refresh()
  File "/root/pokemongo-bot/pokemongo_bot/inventory.py", line 1270, in refresh
    i.refresh(inventory)
  File "/root/pokemongo-bot/pokemongo_bot/inventory.py", line 75, in refresh
    self._data = self.retrieve_data(inventory)
  File "/root/pokemongo-bot/pokemongo_bot/inventory.py", line 71, in retrieve_data
    ret[key] = self.parse(item)
  File "/root/pokemongo-bot/pokemongo_bot/inventory.py", line 490, in parse
    return Pokemon(item)
  File "/root/pokemongo-bot/pokemongo_bot/inventory.py", line 991, in __init__
    assert max(int(self.cp_exact), 10) == self.cp
AssertionError
Mon Nov 21 20:34:02 CET 2016 Pokebot ./configs/config-xxx.json ./configs/auth-xxx.json Stopped.
Press any button or wait 20 seconds to continue.

root@FriendlyARM:~/pokemongo-bot#
````

### Steps to Reproduce
Didn't know, I didn't change anything, few days ago I've started and today when I back from work I see this error

### Other Information
**OS:** 
Ubuntu 15.04 armhf for Nanopi NEO
Linux FriendlyARM 3.4.39-h3 #1 SMP PREEMPT Thu Aug 4 12:41:33 CST 2016 armv7l armv7l armv7l GNU/Linux
**Branch:** 
dev
**Git Commit:** 
979fb4d899f717c229f66e8619d343e483666501
**Python Version:** 
Python 2.7.12

**Comment by krummrey** [comment]
Same thing here, OS X, lastest version re-installed with git.

**Comment by xiatianyu** [comment]
Potential duplicate of #5830.

For a quick workaround, try commenting the line `assert max(int(self.cp_exact), 10) == self.cp` (line 991) in your `/pokemongo_bot/inventory.py`.

**Comment by 1240** [comment]
same here, comment line 991 work nice

**Comment by cierzniak** [comment]
Ok, thanks for fast reaction, close now as solved.

**Comment by orignguyen** [comment]
Thanks Xiatianyu a lot. I met this fault and could not do anything.
