### ISSUE TITLE
Can't run after fresh install (Linux)

### ISSUE THREAD

**Issue by Crownell** [PokemonGoF/PokemonGo-Bot#5837]
> 2016-11-23 07:19:28,790 [       cli] [INFO] PokemonGO Bot v1.0
2016-11-23 07:19:28,892 [       cli] [INFO] commit: 30dbcc0d
2016-11-23 07:19:28,932 [       cli] [INFO] Configuration initialized
2016-11-23 07:19:28,938 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-11-23 07:19:28,947 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-11-23 07:19:29,009 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
(23490) wsgi starting up on http://127.0.0.1:4000
[2016-11-23 07:19:29] [SleepSchedule] [INFO] Next sleep at 11:40:16, for a duration of 05:11:44
[2016-11-23 07:19:29] [PokemonGoBot] [INFO] Setting start location.
[2016-11-23 07:19:29] [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
[2016-11-23 07:19:29] [PokemonGoBot] [INFO] Location found: 34.009242,-118.497604 (34.009242, -118.497604, 8.0)
[2016-11-23 07:19:29] [PokemonGoBot] [INFO] Now at (34.009242, -118.497604, 8.0)
[2016-11-23 07:19:29] [PokemonGoBot] [INFO] Login procedure started.
[2016-11-23 07:19:31] [PokemonGoBot] [INFO] Login successful.
[2016-11-23 07:19:31] [PokemonGoBot] [INFO] 
[2016-11-23 07:19:33] [PokemonGoBot] [INFO] [x] Error while opening cached forts: [Errno 2] No such file or directory: u'/home/crownell/PokemonGo-Bot/pokemongo_bot/../data/recent-forts-kristynkadrozdikova@gmail.com.json'
_inventory was not initialized
_inventory was not initialized
[2016-11-23 07:19:34] [       cli] [INFO] 
[2016-11-23 07:19:34] [       cli] [INFO] Ran for 0:00:05
[2016-11-23 07:19:34] [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
[2016-11-23 07:19:34] [       cli] [INFO] Travelled 0.00km
[2016-11-23 07:19:34] [       cli] [INFO] Visited 0 stops
[2016-11-23 07:19:34] [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
[2016-11-23 07:19:34] [       cli] [INFO] Threw 0 pokeballs
[2016-11-23 07:19:34] [       cli] [INFO] Earned 0 Stardust
[2016-11-23 07:19:34] [       cli] [INFO] Hatched eggs 0
[2016-11-23 07:19:34] [       cli] [INFO] 
[2016-11-23 07:19:34] [       cli] [INFO] Highest CP Pokemon: 
[2016-11-23 07:19:34] [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 846, in <module>
    main()
  File "pokecli.py", line 194, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 146, in start_bot
    bot.start()
  File "/home/crownell/PokemonGo-Bot/pokemongo_bot/__init__.py", line 149, in start
    init_inventory(self)
  File "/home/crownell/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1416, in init_inventory
    _inventory = Inventory(bot)
  File "/home/crownell/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1260, in __init__
    self.refresh()
  File "/home/crownell/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1270, in refresh
    i.refresh(inventory)
  File "/home/crownell/PokemonGo-Bot/pokemongo_bot/inventory.py", line 75, in refresh
    self._data = self.retrieve_data(inventory)
  File "/home/crownell/PokemonGo-Bot/pokemongo_bot/inventory.py", line 71, in retrieve_data
    ret[key] = self.parse(item)
  File "/home/crownell/PokemonGo-Bot/pokemongo_bot/inventory.py", line 490, in parse
    return Pokemon(item)
  File "/home/crownell/PokemonGo-Bot/pokemongo_bot/inventory.py", line 991, in __init__
    assert max(int(self.cp_exact), 10) == self.cp
AssertionError
[2016-11-23 07:19:34] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/crownell/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/crownell/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/crownell/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/crownell/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/crownell/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/crownell/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/crownell/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/crownell/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
[2016-11-23 07:19:34] [sentry.errors.uncaught] [ERROR] [u'AssertionError', u'  File "pokecli.py", line 846, in <module>', u'  File "pokecli.py", line 194, in main', u'  File "pokecli.py", line 146, in start_bot', u'  File "pokemongo_bot/__init__.py", line 149, in start', u'  File "pokemongo_bot/inventory.py", line 1416, in init_inventory', u'  File "pokemongo_bot/inventory.py", line 1260, in __init__', u'  File "pokemongo_bot/inventory.py", line 1270, in refresh', u'  File "pokemongo_bot/inventory.py", line 75, in refresh', u'  File "pokemongo_bot/inventory.py", line 71, in retrieve_data', u'  File "pokemongo_bot/inventory.py", line 490, in parse', u'  File "pokemongo_bot/inventory.py", line 991, in __init__']
Wed Nov 23 07:19:34 PST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
  ^F^CTraceback (most recent call last):
  File "pokecli.py", line 48, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException, NoPlayerPositionSetException
  File "/home/crownell/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/home/crownell/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 36, in <module>
    from pgoapi.auth_google import AuthGoogle
  File "/home/crownell/PokemonGo-Bot/src/pgoapi/pgoapi/auth_google.py", line 33, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "/home/crownell/PokemonGo-Bot/local/lib/python2.7/site-packages/gpsoauth/__init__.py", line 4, in <module>
    from . import google
  File "/home/crownell/PokemonGo-Bot/local/lib/python2.7/site-packages/gpsoauth/google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
  File "/home/crownell/PokemonGo-Bot/local/lib/python2.7/site-packages/Cryptodome/PublicKey/RSA.py", line 79, in <module>
    from Cryptodome.IO import PKCS8, PEM
  File "/home/crownell/PokemonGo-Bot/local/lib/python2.7/site-packages/Cryptodome/IO/PKCS8.py", line 73, in <module>
    from Cryptodome.IO._PBES import PBES1, PBES2, PbesError
  File "/home/crownell/PokemonGo-Bot/local/lib/python2.7/site-packages/Cryptodome/IO/_PBES.py", line 44, in <module>
    from Cryptodome.Cipher import DES, ARC2, DES3, AES
  File "/home/crownell/PokemonGo-Bot/local/lib/python2.7/site-packages/Cryptodome/Cipher/__init__.py", line 80, in <module>
    from Cryptodome.Cipher._mode_cfb import _create_cfb_cipher
  File "/home/crownell/PokemonGo-Bot/local/lib/python2.7/site-packages/Cryptodome/Cipher/_mode_cfb.py", line 49, in <module>
    int CFB_stop_operation(void *state);"""
  File "/home/crownell/PokemonGo-Bot/local/lib/python2.7/site-packages/Cryptodome/Util/_raw_api.py", line 165, in load_pycryptodome_raw_lib
    return load_lib(pycryptodome_filename(dir_comps, basename + ext), cdecl)
  File "/home/crownell/PokemonGo-Bot/local/lib/python2.7/site-packages/Cryptodome/Util/_raw_api.py", line 109, in load_lib
    return CDLL(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)

Any idea what to do?

**Comment by nachi9211** [comment]
While I do not have the complete debug information, your initial error logs are the same and can be resolved by commenting the assert cp line. See #5830 
However you will trigger the bot activity captcha, it would be best to wait for new patch from mods.

**Comment by Meldi78** [comment]
.
