### ISSUE TITLE
[Error] 'id_list2' is not defined when capturing pokemon

### ISSUE THREAD

**Issue by adhioutlined** [PokemonGoF/PokemonGo-Bot#584]
I've got `NameError: global name 'id_list2' is not defined` when capturing an pokemon, here is the log of error

```
2016-07-24 12:20:31 [#] A Wild Zubat appeared! [CP 62] [Potential 0.76]
[2016-07-24 12:20:31] [#] IV [Stamina/Attack/Defense] = [13/11/10]
[2016-07-24 12:20:34] [x] Using Pokeball... (107 left!)
2016-07-24 12:20:35 [x] Captured Zubat! [CP 62] [IV 0.76] - Checking Release Config
Traceback (most recent call last):
  File "pokecli.py", line 203, in <module>
    main()
  File "pokecli.py", line 194, in main
    bot.take_step()
  File "/Users/adhip/folgit/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/Users/adhip/folgit/PokemonGo-Bot/pokemongo_bot/stepper.py", line 67, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/Users/adhip/folgit/PokemonGo-Bot/pokemongo_bot/stepper.py", line 140, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/Users/adhip/folgit/PokemonGo-Bot/pokemongo_bot/__init__.py", line 121, in work_on_cell
    worker.work()
  File "/Users/adhip/folgit/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 30, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "/Users/adhip/folgit/PokemonGo-Bot/pokemongo_bot/stepper.py", line 93, in _walk_to
    alt, False)
  File "/Users/adhip/folgit/PokemonGo-Bot/pokemongo_bot/stepper.py", line 140, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/Users/adhip/folgit/PokemonGo-Bot/pokemongo_bot/__init__.py", line 91, in work_on_cell
    if worker.work() == -1:
  File "/Users/adhip/folgit/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 137, in work
    pokemon_to_transfer = list(Set(id_list2) - Set(id_list1))
NameError: global name 'id_list2' is not defined
```

and here is my `release_config.json`

```
{
	"any": {
		"release_under_cp": 400,
		"release_under_iv": 0.8,
		"cp_iv_logic": "or"
	},
	"My Pokemon": {
		"release_under_cp": 400,
		"release_under_iv": 0.8,
		"cp_iv_logic": "or"
	},
	"exceptions": {
		"always_capture": [
		    "Arcanine",
		    "Lapras",
			"Dragonite",
			"Snorlax",
			"Blastoise",
			"Moltres",
			"Articuno",
			"Zapdos",
			"Mew",
			"Mewtwo"
		]
	}
}
```

is there any missing config ?

**Comment by surfaace** [comment]
fixed in commit efad5ca94df3eb16045d653cbb9b457e29a3fd3e

**Comment by petercunha** [comment]
Run `git pull` to update to the latest version. This issue was fixed.

**Comment by adhioutlined** [comment]
Great, Thanks
