### ISSUE TITLE
[ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1

### ISSUE THREAD

**Issue by heldertb** [PokemonGoF/PokemonGo-Bot#5851]
Running the bot on a fresh install disabling the niantic api check gives:
[ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)

related to the API?

Full error:
```
File "pokecli.py", line 856, in <module>
    main()
  File "pokecli.py", line 195, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 147, in start_bot
    bot.start()
  File "/Users/Me/PokemonGo-Bot/pokemongo_bot/__init__.py", line 149, in start
    init_inventory(self)
  File "/Users/Me/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1416, in init_inventory
    _inventory = Inventory(bot)
  File "/Users/Me/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1260, in __init__
    self.refresh()
  File "/Users/Me/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1270, in refresh
    i.refresh(inventory)
  File "/Users/Me/PokemonGo-Bot/pokemongo_bot/inventory.py", line 75, in refresh
    self._data = self.retrieve_data(inventory)
  File "/Users/Me/PokemonGo-Bot/pokemongo_bot/inventory.py", line 71, in retrieve_data
    ret[key] = self.parse(item)
  File "/Users/Me/PokemonGo-Bot/pokemongo_bot/inventory.py", line 490, in parse
    return Pokemon(item)
  File "/Users/Me/PokemonGo-Bot/pokemongo_bot/inventory.py", line 991, in __init__
    assert max(int(self.cp_exact), 10) == self.cp
AssertionError
[2016-12-26 11:57:54] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/Me/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/Me/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/Me/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/Me/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/Me/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/Me/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/Me/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/Me/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
[2016-12-26 11:57:54] [sentry.errors.uncaught] [ERROR] [u'AssertionError', u'  File "pokecli.py", line 856, in <module>', u'  File "pokecli.py", line 195, in main', u'  File "pokecli.py", line 147, in start_bot', u'  File "pokemongo_bot/__init__.py", line 149, in start', u'  File "pokemongo_bot/inventory.py", line 1416, in init_inventory', u'  File "pokemongo_bot/inventory.py", line 1260, in __init__', u'  File "pokemongo_bot/inventory.py", line 1270, in refresh', u'  File "pokemongo_bot/inventory.py", line 75, in refresh', u'  File "pokemongo_bot/inventory.py", line 71, in retrieve_data', u'  File "pokemongo_bot/inventory.py", line 490, in parse', u'  File "pokemongo_bot/inventory.py", line 991, in __init__']
ma 26 dec 2016 11:57:54 CET Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
```

**Comment by pogarek** [comment]
check here: #5830
