### ISSUE TITLE
Version Conflict six>=1.10.0

### ISSUE THREAD

**Issue by purado** [PokemonGoF/PokemonGo-Bot#5887]
Trying to install PokemonGo-Bot (Ubuntu 16.04) and get this version conflict:

Installing collected packages: numpy, decorator, networkx, geopy, six, protobuf, requests, future, s2sphere, pycryptodomex, gpsoauth, pgoapi, geographiclib, requests-mock, protobuf-to-dict, googlemaps, colorama, enum34, pyyaml, haversine, polyline, websocket-client, python-engineio, python-socketio, itsdangerous, click, Werkzeug, MarkupSafe, Jinja2, flask, socketIO-client, greenlet, eventlet, gpxpy, funcsigs, pbr, mock, timeout-decorator, contextlib2, raven, demjson, iniherit, Unidecode, python-slugify, yoyo-migrations, paho-mqtt, docutils, Geohash, urllib3, certifi, python-telegram-bot, discord-simple
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Running setup.py install for pgoapi ... error
    Complete output from command /root/PokemonGo-Bot/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-A4CQjq/pgoapi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-UkFRrJ-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/PokemonGo-Bot/include/site/python2.7/pgoapi:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-A4CQjq/pgoapi/setup.py", line 21, in <module>
        package_data={'pgoapi': ['lib_0_45/*', 'lib_0_51/*']}
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/setuptools/dist.py", line 320, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/setuptools/dist.py", line 386, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2306, in require
        items = working_set.resolve(reqs, env, installer)
      File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 853, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.VersionConflict: (six 1.9.0 (/root/PokemonGo-Bot/lib/python2.7/site-packages), Requirement.parse('six>=1.10.0'))

**Comment by ashleykleynhans** [comment]
This is no longer an issue.

**Comment by pogarek** [comment]
try:
pip uninstall six
virtualenv . 
source bin/activate
pip uninstall six
pip2 install --upgrade -r requirements.txt
