### ISSUE TITLE
Telegram Broken

### ISSUE THREAD

**Issue by MerlionRock** [PokemonGoF/PokemonGo-Bot#5891]
Errors occur with telegram with new installation. Assuming some package errors but not able to fins out which one.

Here's the error:
Traceback (most recent call last):
  File "pokecli.py", line 865, in <module>
    main()
  File "pokecli.py", line 202, in main
    formatted='Starting bot...'
  File "/Users/***/PokemonGo-Bot/pokemongo_bot/event_manager.py", line 77, in emit
    handler.handle_event(event, sender, level, formatted_msg, data)
  File "/Users/***/PokemonGo-Bot/pokemongo_bot/event_handlers/telegram_handler.py", line 579, in handle_event
    self.tbot.sendMessage(chat_id=uid, parse_mode='Markdown', text=msg)
  File "/Users/***/PokemonGo-Bot/pokemongo_bot/event_handlers/telegram_handler.py", line 123, in sendMessage
    self._tbot.sendMessage(chat_id=chat_id, parse_mode=parse_mode, text=text)
  File "/Users/***/PokemonGo-Bot/lib/python2.7/site-packages/telegram/bot.py", line 125, in decorator
    result = func(self, *args, **kwargs)
  File "/Users/***/PokemonGo-Bot/lib/python2.7/site-packages/telegram/bot.py", line 151, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/Users/***/PokemonGo-Bot/lib/python2.7/site-packages/telegram/utils/request.py", line 207, in post
    **urlopen_kwargs)
  File "/Users/***/PokemonGo-Bot/lib/python2.7/site-packages/telegram/utils/request.py", line 132, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/Users/***/PokemonGo-Bot/lib/python2.7/site-packages/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/Users/***/PokemonGo-Bot/lib/python2.7/site-packages/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/***/PokemonGo-Bot/lib/python2.7/site-packages/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/***/PokemonGo-Bot/lib/python2.7/site-packages/urllib3/connectionpool.py", line 588, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/Users/***/PokemonGo-Bot/lib/python2.7/site-packages/urllib3/connectionpool.py", line 241, in _get_conn
    if conn and is_connection_dropped(conn):
  File "/Users/***/PokemonGo-Bot/lib/python2.7/site-packages/urllib3/util/connection.py", line 27, in is_connection_dropped
    return bool(wait_for_read(sock, timeout=0.0))
  File "/Users/***/PokemonGo-Bot/lib/python2.7/site-packages/urllib3/util/wait.py", line 33, in wait_for_read
    return _wait_for_io_events(socks, EVENT_READ, timeout)
  File "/Users/***/PokemonGo-Bot/lib/python2.7/site-packages/urllib3/util/wait.py", line 22, in _wait_for_io_events
    with DefaultSelector() as selector:
  File "/Users/***/PokemonGo-Bot/lib/python2.7/site-packages/urllib3/util/selectors.py", line 431, in __init__
    self._kqueue = select.kqueue()
AttributeError: 'module' object has no attribute 'kqueue'

Anyone has the same problem?

The bot seems to work fine when telegram is disabled.

**Comment by davidakachaos** [comment]
I got an similar error, but it was about epoll. But I think it's the same
error...

Op 27 jan. 2017 20:26 schreef "MerlionRock" <notifications@github.com>:

Errors occur with telegram with new installation. Assuming some package
errors but not able to fins out which one.

Here's the error:
Traceback (most recent call last):
File "pokecli.py", line 865, in
main()
File "pokecli.py", line 202, in main
formatted='Starting bot...'
File "/Users/***/PokemonGo-Bot/pokemongo_bot/event_manager.py", line 77, in
emit
handler.handle_event(event, sender, level, formatted_msg, data)
File "/Users/***/PokemonGo-Bot/pokemongo_bot/event_handlers/telegram_handler.py",
line 579, in handle_event
self.tbot.sendMessage(chat_id=uid, parse_mode='Markdown', text=msg)
File "/Users/***/PokemonGo-Bot/pokemongo_bot/event_handlers/telegram_handler.py",
line 123, in sendMessage
self._tbot.sendMessage(chat_id=chat_id, parse_mode=parse_mode, text=text)
File "/Users/***/PokemonGo-Bot/lib/python2.7/site-packages/telegram/bot.py",
line 125, in decorator
result = func(self,
*args, kwargs) File
"/Users/*/PokemonGo-Bot/lib/python2.7/site-packages/telegram/bot.py",
line 151, in decorator
result = self._request.post(url, data, timeout=kwargs.get('timeout'))
File "/Users/***/PokemonGo-Bot/lib/python2.7/site-packages/telegram/utils/request.py",
line 207, in post

*urlopen_kwargs) File
"/Users/**/PokemonGo-Bot/lib/python2.7/site-packages/telegram/utils/request.py",
line 132, in _request_wrapper
resp = self._con_pool.request(
*args, kwargs) File
"/Users/*/PokemonGo-Bot/lib/python2.7/site-packages/urllib3/request.py",
line 70, in request

*urlopen_kw) File
"/Users/**/PokemonGo-Bot/lib/python2.7/site-packages/urllib3/request.py",
line 148, in request_encode_body
return self.urlopen(method, url,
*extra_kw) File
"/Users/**/PokemonGo-Bot/lib/python2.7/site-packages/urllib3/poolmanager.py",
line 244, in urlopen
response = conn.urlopen(method, u.request_uri,
*kw) File "/Users/**/PokemonGo-Bot/lib/python2.7/site-packages/urllib3/connectionpool.py",
line 588, in urlopen
conn = self._get_conn(timeout=pool_timeout)
File "/Users/***/PokemonGo-Bot/lib/python2.7/site-packages/urllib3/connectionpool.py",
line 241, in _get_conn
if conn and is_connection_dropped(conn):
File "/Users/***/PokemonGo-Bot/lib/python2.7/site-packages/urllib3/util/connection.py",
line 27, in is_connection_dropped
return bool(wait_for_read(sock, timeout=0.0))
File "/Users/***/PokemonGo-Bot/lib/python2.7/site-packages/urllib3/util/wait.py",
line 33, in wait_for_read
return _wait_for_io_events(socks, EVENT_READ, timeout)
File "/Users/***/PokemonGo-Bot/lib/python2.7/site-packages/urllib3/util/wait.py",
line 22, in _wait_for_io_events
with DefaultSelector() as selector:
File "/Users/***/PokemonGo-Bot/lib/python2.7/site-packages/urllib3/util/selectors.py",
line 431, in *init*
self._kqueue = select.kqueue()
AttributeError: 'module' object has no attribute 'kqueue'

Anyone has the same problem?

The bot seems to work fine when telegram is disabled.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PokemonGoF/PokemonGo-Bot/issues/5891>, or mute the
thread

**Comment by MerlionRock** [comment]
@davidakachaos I guess same error. Mac uses kqueue, other OS uses epoll.

**Comment by davidakachaos** [comment]
Ah, yes. I'm on Linux (Ubuntu)

Op 27 jan. 2017 20:39 schreef "MerlionRock" <notifications@github.com>:

**Comment by MerlionRock** [comment]
Anyone found any solution yet? I have no idea what causes it.

**Comment by davidakachaos** [comment]
No, I've searched Google but haven't found a solution yet. I updated the Telegram bot dependency to 5.3.0 but that didn't help. So the search continues....

**Comment by ashleykleynhans** [comment]
@MerlionRock The issue lies with version 1.20 of urllib3.

Add the following line to requirements.txt:

`urllib3==1.18`

Then run

`setup.sh  -u`

And the telegram bot will function again.

**Comment by MerlionRock** [comment]
@ashleykleynhans Thank you so much! Finally!

**Comment by ashleykleynhans** [comment]
@MerlionRock I opened a PR for it https://github.com/PokemonGoF/PokemonGo-Bot/pull/5895
