### ISSUE TITLE
The auto evolve need some fix

### ISSUE THREAD

**Issue by zx900930** [PokemonGoF/PokemonGo-Bot#590]
The auto evolve seems to ignore the release config and evolve everthing which have enough candies like this:

```

2016-07-24 08:05:56 [x] Captured Dratini! [CP 83] [IV 0.2] - Checking Release Config
2016-07-24 08:05:57 [x] Release config for Dratini: CP 400 or IV 0.88
2016-07-24 08:05:58 [#] Dratini has been exchanged for candy!
2016-07-24 08:06:03 [#] A Wild Zubat appeared! [CP 148] [Potential 0.69]
[2016-07-24 08:06:03] [#] IV [Stamina/Attack/Defense] = [13/9/9]
[2016-07-24 08:06:05] [x] Using Pokeball... (33 left!)
2016-07-24 08:06:06 [x] Captured Zubat! [CP 148] [IV 0.69] - Checking Release Config
2016-07-24 08:06:07 [#] Zubat has been evolved!
```

Latest commit a634b55

**Comment by surfaace** [comment]
'fixed' in commit 154971c2a5a87738825381e74281ea89943bfd75

Update your config.json with 
	"evolve_all", false,
	"evolve_captured", false

**Comment by zx900930** [comment]
@surfaace 
new error with last commit 1ce23d7

```
Traceback (most recent call last):
  File "pokecli.py", line 219, in <module>
    main()
  File "pokecli.py", line 196, in main
    config = init_config()
  File "pokecli.py", line 168, in init_config
    config.item_filter = [str(item_id) for item_id in config.item_filter.split(',')]
AttributeError: 'list' object has no attribute 'split'
```

**Comment by surfaace** [comment]
@zx900930 paste config values

**Comment by zx900930** [comment]
@surfaace  sorry my fault, i didnt check the new config example for "item_filter"

`    "item_filter": [101,102,103,104] -> "item_filter": "101,102,103,104"`

**Comment by surfaace** [comment]
great, close if you think that its resolved

**Comment by zx900930** [comment]
Thx for help, and u can close this is.
