### ISSUE TITLE
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'"

### ISSUE THREAD

**Issue by azraelppuk** [PokemonGoF/PokemonGo-Bot#5910]
Bot starts, runs [UpdateLiveInventory], runs [ShowBestPokemon], then crashes with:

[Errno 32] Broken pipe
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:14> ignored
Traceback (most recent call last):
  File "pokecli.py", line 865, in <module>
    main()
  File "pokecli.py", line 283, in main
    report_summary(bot)
  File "pokecli.py", line 331, in report_summary
    metrics.capture_stats()
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/pokemongo_bot/metrics.py", line 117, in capture_stats
    inventory.refresh_inventory()
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1432, in refresh_inventory
    _inventory.refresh(data)
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1272, in refresh
    inventory = self.bot.api.get_inventory()
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/local/lib/python2.7/site-packages/pgoapi/pgoapi.py", line 140, in function
    return request.call()
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 237, in call
    result = self._call()
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 185, in _call
    return PGoApiRequest.call(self)
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/local/lib/python2.7/site-packages/pgoapi/pgoapi.py", line 250, in call
    default_libraries = get_lib_paths(version)
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/local/lib/python2.7/site-packages/pgoapi/utilities.py", line 172, in get_lib_paths
    arch = platform.architecture()[0]
  File "/usr/lib/python2.7/platform.py", line 1134, in architecture
    output = _syscmd_file(executable, '')
  File "/usr/lib/python2.7/platform.py", line 1081, in _syscmd_file
    output = proc.communicate()[0]
  File "/usr/lib/python2.7/subprocess.py", line 791, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
  File "/usr/lib/python2.7/socket.py", line 351, in read
    data = self._sock.recv(rbufsize)
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/greenio/py2.py", line 160, in recv
    data = os.read(self._fileno, buflen)
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/green/os.py", line 50, in read
    hubs.trampoline(fd, read=True)
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 162, in trampoline
    return hub.switch()
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 294, in switch
    return self.greenlet.switch()
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 332, in run
    self.close_one()
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 265, in close_one
    listener.tb(IOClosed(errno.ENOTCONN, "Operation on closed file"))
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/green/select.py", line 62, in on_error
    original = ds[get_fileno(d)]['error']
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/green/select.py", line 23, in get_fileno
    raise TypeError("Expected int or long, got %s" % type(obj))
TypeError: Expected int or long, got <class 'eventlet.hubs.IOClosed'>
[2017-02-14 09:54:08] [sentry.errors] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 848, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
[2017-02-14 09:54:08] [sentry.errors.uncaught] [u"TypeError: Expected int or long, got <class 'eventlet.hubs.IOClosed'>", u'  File "pokecli.py", line 865, in <module>', u'  File "pokecli.py", line 283, in main', u'  File "pokecli.py", line 331, in report_summary', u'  File "pokemongo_bot/metrics.py", line 117, in capture_stats', u'  File "pokemongo_bot/inventory.py", line 1432, in refresh_inventory', u'  File "pokemongo_bot/inventory.py", line 1272, in refresh', u'  File "pgoapi/pgoapi.py", line 140, in function', u'  File "pokemongo_bot/api_wrapper.py", line 237, in call', u'  File "pokemongo_bot/api_wrapper.py", line 185, in _call', u'  File "pgoapi/pgoapi.py", line 250, in call', u'  File "pgoapi/utilities.py", line 172, in get_lib_paths', u'  File "python2.7/platform.py", line 1134, in architecture', u'  File "python2.7/platform.py", line 1081, in _syscmd_file', u'  File "python2.7/subprocess.py", line 791, in communicate', u'  File "python2.7/subprocess.py", line 476, in _eintr_retry_call', u'  File "python2.7/socket.py", line 351, in read', u'  File "eventlet/greenio/py2.py", line 160, in recv', u'  File "eventlet/green/os.py", line 50, in read', u'  File "eventlet/hubs/__init__.py", line 162, in trampoline', u'  File "eventlet/hubs/hub.py", line 294, in switch', u'  File "eventlet/hubs/hub.py", line 332, in run', u'  File "eventlet/hubs/hub.py", line 265, in close_one', u'  File "eventlet/green/select.py", line 62, in on_error', u'  File "eventlet/green/select.py", line 23, in get_fileno']
Tue 14 Feb 09:54:09 GMT 2017 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

### Other Information
OS: raspbian/Linux on raspberry pi
Branch: master
Git Commit: eaab3f590feef5ad559fa3461cb05762e260c364
Python Version: Python 2.7.9

**Comment by pogarek** [comment]
is this still valid?

**Comment by davidakachaos** [comment]
No response in a while, closing this issue. If you still encounter this problem, or have anything else to add, let us know! Thank you for reporting this issue, it helps us all make this bot the best of them all!
