### ISSUE TITLE
Bot Crashes after receiving a Sun Stone from Pokestop

### ISSUE THREAD

**Issue by atxfun** [PokemonGoF/PokemonGo-Bot#5919]
### Actual Behavior

After receiving a Sun Stone from a Pokestop, the bot crashed. The bot had been running smoothly for about 20 minutes when this happened.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
I'm running on the master with the addition of pokemon.json, items.json, charged_moves.json, and fast_moves.json provided by MerlionRock in #5917.

### Output when issue occurred
Traceback (most recent call last):
  File "pokecli.py", line 865, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.tick()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 778, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/spin_fort.py", line 92, in work
    items_awarded = self.get_items_awarded_from_fort_spinned(response_dict)
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/spin_fort.py", line 233, in get_items_awarded_from_fort_spinned
    item_awarded_name = inventory.Items.name_for(item_awarded_id)
  File "/root/PokemonGo-Bot/pokemongo_bot/inventory.py", line 283, in name_for
    return cls.STATIC_DATA[str(item_id)]
KeyError: '1101'
[2017-02-18 17:11:06] [MainThread] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/root/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/root/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/root/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/root/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/root/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/root/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/root/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/root/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 862, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)

### Other Information
OS: CentOS 7
 
Branch: Master
 
Git Commit: 26117e6e7ea8f5826b26a84901a9cd5577b5ebdc
 
Python Version: Python 2.7.5
 
Any other relevant files/configs (eg: path files)

**Comment by MerlionRock** [comment]
hahah.... that's why it's still in PR..... I am working on it.

But these few days I will be very busy.... you might have to be slightly patience....

**Comment by MerlionRock** [comment]
I think I know the reason.... You copied my files, but did you upgrade your API with latest protos?

Try again with ./setup.sh

**Comment by atxfun** [comment]
Yes, and I tried it again, just to be sure. I still get the same error.

**Comment by atxfun** [comment]
Issue resolved. I didn't have the latest items.json.
