### ISSUE TITLE
Bot not working after startup

### ISSUE THREAD

**Issue by trevorjudice** [PokemonGoF/PokemonGo-Bot#5925]
I receive this error message right after startup. My bot was working before, however not anymore. I did not see any specific event that triggered this error message. I have done a ./setup.sh -u and am up to date on my version. I also have the updated items.json, pokemon.json, moves.json, etc...
Traceback (most recent call last):
  File "pokecli.py", line 865, in <module>
    main()
  File "pokecli.py", line 195, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 147, in start_bot
    bot.start()
  File "/Users/trevorjudice/PokemonGo-Bot/pokemongo_bot/__init__.py", line 155, in start
    init_inventory(self)
  File "/Users/trevorjudice/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1422, in init_inventory
    _inventory = Inventory(bot)
  File "/Users/trevorjudice/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1266, in __init__
    self.refresh()
  File "/Users/trevorjudice/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1276, in refresh
    i.refresh(inventory)
  File "/Users/trevorjudice/PokemonGo-Bot/pokemongo_bot/inventory.py", line 75, in refresh
    self._data = self.retrieve_data(inventory)
  File "/Users/trevorjudice/PokemonGo-Bot/pokemongo_bot/inventory.py", line 71, in retrieve_data
    ret[key] = self.parse(item)
  File "/Users/trevorjudice/PokemonGo-Bot/pokemongo_bot/inventory.py", line 256, in parse
    return Item(item_id, item_count)
  File "/Users/trevorjudice/PokemonGo-Bot/pokemongo_bot/inventory.py", line 190, in __init__
    self.name = Items.name_for(self.id)
  File "/Users/trevorjudice/PokemonGo-Bot/pokemongo_bot/inventory.py", line 283, in name_for
    return cls.STATIC_DATA[str(item_id)]
KeyError: '1103'
[2017-02-20 14:03:44] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/trevorjudice/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/trevorjudice/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/trevorjudice/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/trevorjudice/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/trevorjudice/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/trevorjudice/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/trevorjudice/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/trevorjudice/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 880, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
[2017-02-20 14:03:44] [sentry.errors.uncaught] [ERROR] [u"KeyError: '1103'", u'  File "pokecli.py", line 865, in <module>', u'  File "pokecli.py", line 195, in main', u'  File "pokecli.py", line 147, in start_bot', u'  File "pokemongo_bot/__init__.py", line 155, in start', u'  File "pokemongo_bot/inventory.py", line 1422, in init_inventory', u'  File "pokemongo_bot/inventory.py", line 1266, in __init__', u'  File "pokemongo_bot/inventory.py", line 1276, in refresh', u'  File "pokemongo_bot/inventory.py", line 75, in refresh', u'  File "pokemongo_bot/inventory.py", line 71, in retrieve_data', u'  File "pokemongo_bot/inventory.py", line 256, in parse', u'  File "pokemongo_bot/inventory.py", line 190, in __init__', u'  File "pokemongo_bot/inventory.py", line 283, in name_for']

**Comment by trevorjudice** [comment]
Any thoughts? Still not working.

**Comment by MerlionRock** [comment]
My PR has been merged. Just update your bot.

Should get the bot running, not perfect but at least the bot will run. Another PR will be raised to correct some values that could affect pokemon optimiser.

**Comment by trevorjudice** [comment]
It works. Thanks.

**Comment by pogarek** [comment]
closing
