### ISSUE TITLE
ImportError: No module named pogoprotos

### ISSUE THREAD

**Issue by htugsdr** [PokemonGoF/PokemonGo-Bot#5944]
### Expected Behavior
I just want the bot to run without errors. Its been a while since ive actually played (5 months) and I thought I might as well give it another go. DId a fresh install by deleting the folder and doing git pull 

### Actual Behavior
Bot just stops automatically

### Output when issue occurred
```
 ./run.sh
2017-03-04 14:38:30,824 [       cli] [INFO] PokemonGO Bot v1.0
2017-03-04 14:38:30,946 [       cli] [INFO] commit: 5e8b2e0c
2017-03-04 14:38:30,962 [       cli] [INFO] Configuration initialized
2017-03-04 14:38:30,962 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2017-03-04 14:38:30,962 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2017-03-04 14:38:31,106 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
(84144) wsgi starting up on http://127.0.0.1:4000
[2017-03-04 14:38:32] [PokemonGoBot] [INFO] Setting start location.
_inventory was not initialized
_inventory was not initialized
[2017-03-04 14:38:32] [       cli] [INFO] 
[2017-03-04 14:38:32] [       cli] [INFO] Ran for 0:00:01
[2017-03-04 14:38:32] [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
[2017-03-04 14:38:32] [       cli] [INFO] Travelled 0.00km
[2017-03-04 14:38:32] [       cli] [INFO] Visited 0 stops
[2017-03-04 14:38:32] [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
[2017-03-04 14:38:32] [       cli] [INFO] Threw 0 pokeballs
[2017-03-04 14:38:32] [       cli] [INFO] Earned 0 Stardust
[2017-03-04 14:38:32] [       cli] [INFO] Hatched eggs 0
[2017-03-04 14:38:32] [       cli] [INFO] 
[2017-03-04 14:38:32] [       cli] [INFO] Highest CP Pokemon: 
[2017-03-04 14:38:32] [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 865, in <module>
    main()
  File "pokecli.py", line 195, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 147, in start_bot
    bot.start()
  File "/Users/hamishtugado/PokemonGo-Bot/pokemongo_bot/__init__.py", line 155, in start
    self._setup_api()
  File "/Users/hamishtugado/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1145, in _setup_api
    self._set_starting_position()
  File "/Users/hamishtugado/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1347, in _set_starting_position
    location = self.get_pos_by_name(location_str.replace(" ", ""))
  File "/Users/hamishtugado/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1474, in get_pos_by_name
    return float(loc.latitude), float(loc.longitude), float(loc.altitude)
AttributeError: 'NoneType' object has no attribute 'latitude'
[2017-03-04 14:38:32] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/hamishtugado/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/hamishtugado/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/hamishtugado/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/hamishtugado/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/hamishtugado/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/hamishtugado/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/hamishtugado/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/hamishtugado/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
[2017-03-04 14:38:32] [sentry.errors.uncaught] [ERROR] [u"AttributeError: 'NoneType' object has no attribute 'latitude'", u'  File "pokecli.py", line 865, in <module>', u'  File "pokecli.py", line 195, in main', u'  File "pokecli.py", line 147, in start_bot', u'  File "pokemongo_bot/__init__.py", line 155, in start', u'  File "pokemongo_bot/__init__.py", line 1145, in _setup_api', u'  File "pokemongo_bot/__init__.py", line 1347, in _set_starting_position', u'  File "pokemongo_bot/__init__.py", line 1474, in get_pos_by_name']
Sat 4 Mar 2017 14:38:32 ACDT Pokebot  Stopped.

```

### Steps to Reproduce
Followed the installation process for mac on the wiki
then just went ./run.sh

### Other Information

Branch: 
i think im on dev i need clarification on how to 
Git Commit: 
 
Python Version: 
2.7.12

**Comment by pogarek** [comment]
try again in clean directory. 
run 
```
pip2 install --upgrade -r requirements.txt
```

**Comment by htugsdr** [comment]
thanks i just did a manual install and all good
