### ISSUE TITLE
inventory was not initialized

### ISSUE THREAD

**Issue by mrsm44** [PokemonGoF/PokemonGo-Bot#5959]
I run the bot on OS X and while it works with one of my accounts it crashes on startup when I use my other account (where I have over 900 items in my inventory). This is the output:

[2017-03-09 13:10:30] [PokemonGoBot] [INFO] Login procedure started.
[2017-03-09 13:10:36] [PokemonGoBot] [INFO] Login successful.
[2017-03-09 13:10:36] [PokemonGoBot] [INFO] 
_inventory was not initialized
_inventory was not initialized
[2017-03-09 13:10:38] [       cli] [INFO] 
[2017-03-09 13:10:38] [       cli] [INFO] Ran for 0:00:08
[2017-03-09 13:10:38] [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
[2017-03-09 13:10:38] [       cli] [INFO] Travelled 0.00km
[2017-03-09 13:10:38] [       cli] [INFO] Visited 0 stops
[2017-03-09 13:10:38] [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
[2017-03-09 13:10:38] [       cli] [INFO] Threw 0 pokeballs
[2017-03-09 13:10:38] [       cli] [INFO] Earned 0 Stardust
[2017-03-09 13:10:38] [       cli] [INFO] Hatched eggs 0
[2017-03-09 13:10:38] [       cli] [INFO] 
[2017-03-09 13:10:38] [       cli] [INFO] Highest CP Pokemon: 
[2017-03-09 13:10:38] [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 865, in <module>
    main()
  File "pokecli.py", line 195, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 147, in start_bot
    bot.start()
  File "/Users/user/Desktop/PokemonGo-Bot-master/pokemongo_bot/__init__.py", line 149, in start
    init_inventory(self)
  File "/Users/user/Desktop/PokemonGo-Bot-master/pokemongo_bot/inventory.py", line 1422, in init_inventory
    _inventory = Inventory(bot)
  File "/Users/user/Desktop/PokemonGo-Bot-master/pokemongo_bot/inventory.py", line 1266, in __init__
    self.refresh()
  File "/Users/user/Desktop/PokemonGo-Bot-master/pokemongo_bot/inventory.py", line 1276, in refresh
    i.refresh(inventory)
  File "/Users/user/Desktop/PokemonGo-Bot-master/pokemongo_bot/inventory.py", line 75, in refresh
    self._data = self.retrieve_data(inventory)
  File "/Users/user/Desktop/PokemonGo-Bot-master/pokemongo_bot/inventory.py", line 71, in retrieve_data
    ret[key] = self.parse(item)
  File "/Users/user/Desktop/PokemonGo-Bot-master/pokemongo_bot/inventory.py", line 256, in parse
    return Item(item_id, item_count)
  File "/Users/user/Desktop/PokemonGo-Bot-master/pokemongo_bot/inventory.py", line 190, in __init__
    self.name = Items.name_for(self.id)
  File "/Users/user/Desktop/PokemonGo-Bot-master/pokemongo_bot/inventory.py", line 283, in name_for
    return cls.STATIC_DATA[str(item_id)]
KeyError: '1101'
Thu Mar 9 13:10:38 EET 2017 Pokebot  Stopped.

**Comment by pogarek** [comment]
enable debug: true in config and let's see. 
if it will not help, then some debugging will be needed :(

**Comment by davidakachaos** [comment]
1101 should be a sunstone. Which branch are you using?

**Comment by pogarek** [comment]
closing. reopen if needed
