### ISSUE TITLE
I got this error help please !!

### ISSUE THREAD

**Issue by testbotpokemon123456** [PokemonGoF/PokemonGo-Bot#5985]
```
--------------------Starting bot--------------------


2017-03-30 23:06:51,400 [       cli] [INFO] PokemonGO Bot v1.0
2017-03-30 23:06:51,400 [       cli] [INFO] commit: unknown
2017-03-30 23:06:51,415 [       cli] [INFO] No auth argument specified, checking for C:\Python27\PokemonGo-Bot\pokemongo_bot\..\configs\auth.json
2017-03-30 23:06:51,415 [       cli] [INFO] No config argument specified, checking for C:\Python27\PokemonGo-Bot\pokemongo_bot\..\configs\config.json
2017-03-30 23:06:51,415 [       cli] [INFO] Configuration initialized
2017-03-30 23:06:51,415 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2017-03-30 23:06:51,415 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2017-03-30 23:06:51,430 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
[2017-03-30 23:06:51] [yoyo.migrations] [INFO] Applying pokemongobot
[2017-03-30 23:06:51] [yoyo.migrations] [INFO]  - applying step 0
[2017-03-30 23:06:51] [yoyo.migrations] [INFO] Marking pokemongobot applied
[2017-03-30 23:06:52] [yoyo.migrations] [INFO] Applying catch_log
[2017-03-30 23:06:52] [yoyo.migrations] [INFO]  - applying step 0
[2017-03-30 23:06:52] [yoyo.migrations] [INFO] Marking catch_log applied
[2017-03-30 23:06:52] [yoyo.migrations] [INFO] Applying eggs_hatched_log
[2017-03-30 23:06:52] [yoyo.migrations] [INFO]  - applying step 0
[2017-03-30 23:06:52] [yoyo.migrations] [INFO] Marking eggs_hatched_log applied
[2017-03-30 23:06:52] [yoyo.migrations] [INFO] Applying evolve_log
[2017-03-30 23:06:52] [yoyo.migrations] [INFO]  - applying step 0
[2017-03-30 23:06:52] [yoyo.migrations] [INFO] Marking evolve_log applied
[2017-03-30 23:06:52] [yoyo.migrations] [INFO] Applying pokestop_log
[2017-03-30 23:06:52] [yoyo.migrations] [INFO]  - applying step 0
[2017-03-30 23:06:52] [yoyo.migrations] [INFO] Marking pokestop_log applied
[2017-03-30 23:06:52] [yoyo.migrations] [INFO] Applying softban_log
[2017-03-30 23:06:52] [yoyo.migrations] [INFO]  - applying step 0
[2017-03-30 23:06:52] [yoyo.migrations] [INFO] Marking softban_log applied
[2017-03-30 23:06:53] [yoyo.migrations] [INFO] Applying transfer_log
[2017-03-30 23:06:53] [yoyo.migrations] [INFO]  - applying step 0
[2017-03-30 23:06:53] [yoyo.migrations] [INFO] Marking transfer_log applied
[2017-03-30 23:06:53] [yoyo.migrations] [INFO] Applying vanish_log
[2017-03-30 23:06:53] [yoyo.migrations] [INFO]  - applying step 0
[2017-03-30 23:06:53] [yoyo.migrations] [INFO] Marking vanish_log applied
(10140) wsgi starting up on http://127.0.0.1:4000
[2017-03-30 23:06:53] [SleepSchedule] [INFO] Next sleep at 01:00:35, for a duration of 05:01:15
[2017-03-30 23:06:53] [PokemonGoBot] [INFO] Setting start location.
[2017-03-30 23:06:54] [PokemonGoBot] [INFO] Location found: Complex KKU (16.477551, 102.823105, 0.0)
[2017-03-30 23:06:54] [PokemonGoBot] [INFO] Now at (16.477551, 102.823105, 0.0)
[2017-03-30 23:06:54] [PokemonGoBot] [INFO] Login procedure started.
_inventory was not initialized
_inventory was not initialized
[2017-03-30 23:06:58] [       cli] [INFO]
[2017-03-30 23:06:58] [       cli] [INFO] Ran for 0:00:05
[2017-03-30 23:06:58] [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
[2017-03-30 23:06:58] [       cli] [INFO] Travelled 0.00km
[2017-03-30 23:06:58] [       cli] [INFO] Visited 0 stops
[2017-03-30 23:06:58] [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
[2017-03-30 23:06:58] [       cli] [INFO] Threw 0 pokeballs
[2017-03-30 23:06:58] [       cli] [INFO] Earned 0 Stardust
[2017-03-30 23:06:58] [       cli] [INFO] Hatched eggs 0
[2017-03-30 23:06:58] [       cli] [INFO]
[2017-03-30 23:06:58] [       cli] [INFO] Highest CP Pokemon:
[2017-03-30 23:06:58] [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 865, in <module>
    main()
  File "pokecli.py", line 195, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 147, in start_bot
    bot.start()
  File "C:\Python27\PokemonGo-Bot\pokemongo_bot\__init__.py", line 155, in start
    self._setup_api()
  File "C:\Python27\PokemonGo-Bot\pokemongo_bot\__init__.py", line 1152, in _setup_api
    self.login()
  File "C:\Python27\PokemonGo-Bot\pokemongo_bot\__init__.py", line 960, in login
    str(self.config.password))
  File "C:\Python27\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 108, in login
    response = PGoApi.app_simulation_login(self)
  File "C:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 152, in app_simulation_login
    response = request.call()
  File "C:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 264, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "C:\Python27\lib\site-packages\pgoapi\rpc_api.py", line 149, in request
    self.request_proto = self.request_proto or self._build_main_request(subrequests, player_position)
  File "C:\Python27\lib\site-packages\pgoapi\rpc_api.py", line 229, in _build_main_request
    self._hash_engine.hash(sig.timestamp, request.latitude, request.longitude, request.accuracy, ticket_serialized, sig.session_hash, request.requests)
  File "C:\Python27\lib\site-packages\pgoapi\hash_server.py", line 48, in hash
    raise BadHashRequestException("400: Bad request, error: {}".format(response.text))
pgoapi.exceptions.BadHashRequestException: 400: Bad request, error: Unauthorized
[2017-03-30 23:06:58] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\raven\transport\threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "C:\Python27\lib\site-packages\raven\transport\http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 494, in open
    response = self._open(req, data)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 512, in _open
    '_open', req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python27\lib\httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 880, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
[2017-03-30 23:06:58] [sentry.errors.uncaught] [ERROR] [u'BadHashRequestException: 400: Bad request, error: Unauthorized', u'  File "pokecli.py", line 865, in <module>', u'  File "pokecli.py", line 195, in main', u'  File "pokecli.py", line 147, in start_bot', u'  File "C:\\Python27\\PokemonGo-Bot\\pokemongo_bot\\__init__.py", line 155, in start', u'  File "C:\\Python27\\PokemonGo-Bot\\pokemongo_bot\\__init__.py", line 1152, in _setup_api', u'  File "C:\\Python27\\PokemonGo-Bot\\pokemongo_bot\\__init__.py", line 960, in login', u'  File "C:\\Python27\\PokemonGo-Bot\\pokemongo_bot\\api_wrapper.py", line 108, in login', u'  File "C:\\Python27\\lib\\site-packages\\pgoapi\\pgoapi.py", line 152, in app_simulation_login', u'  File "C:\\Python27\\lib\\site-packages\\pgoapi\\pgoapi.py", line 264, in call', u'  File "C:\\Python27\\lib\\site-packages\\pgoapi\\rpc_api.py", line 149, in request', u'  File "C:\\Python27\\lib\\site-packages\\pgoapi\\rpc_api.py", line 229, in _build_main_request', u'  File "C:\\Python27\\lib\\site-packages\\pgoapi\\hash_server.py", line 48, in hash']

 Something went wrong and the bot needed to be restarted. Please investigate the cause.


Waiting for 40 seconds, press a key to continue ...
```
How i can fix it ?
How this bot work ?
Thank you.

**Comment by Jcolomar** [comment]
did u buy a server-hash license key?

**Comment by testbotpokemon123456** [comment]
No but i got free server-hash key from Youtube, 
Two weeks ago it worked.

**Comment by Jcolomar** [comment]
BadHashRequestException: 400: Bad request, error: Unauthorized

i think that means ur key no works

**Comment by MerlionRock** [comment]
It's a price of a starbuck coffee.

**Comment by testbotpokemon123456** [comment]
Thank you.
