### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1'

### ISSUE THREAD

**Issue by MadMax-15** [PokemonGoF/PokemonGo-Bot#6014]
### Expected Behavior

run the bot

### Actual Behavior

stuck in this error 

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

default config with new ptc account (toc accepted) and only added coordinates, active hash key & gmapkey

### Output when issue occurred

./run.sh
2017-04-12 21:47:53,376 [       cli] [INFO] PokemonGO Bot v1.0
2017-04-12 21:47:53,393 [       cli] [INFO] commit: 8c176c08
2017-04-12 21:47:53,411 [       cli] [INFO] Configuration initialized
2017-04-12 21:47:53,412 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2017-04-12 21:47:53,412 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2017-04-12 21:47:53,432 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
(17676) wsgi starting up on http://127.0.0.1:4000
[2017-04-12 21:47:53] [SleepSchedule] [INFO] Next sleep at 11:51:10, for a duration of 05:04:41
[2017-04-12 21:47:53] [PokemonGoBot] [INFO] Setting start location.
[2017-04-12 21:47:53] [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
[2017-04-12 21:47:53] [PokemonGoBot] [INFO] Location found: 34.012257773782864,-118.49441528320311 (34.01225777378286, -118.49441528320311, 8)
[2017-04-12 21:47:53] [PokemonGoBot] [INFO] Now at (34.01225777378286, -118.49441528320311, 8)
[2017-04-12 21:47:53] [PokemonGoBot] [INFO] Login procedure started.
_inventory was not initialized
_inventory was not initialized
[2017-04-12 21:47:53] [       cli] [INFO] 
[2017-04-12 21:47:53] [       cli] [INFO] Ran for 0:00:00
[2017-04-12 21:47:53] [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
[2017-04-12 21:47:53] [       cli] [INFO] Travelled 0.00km
[2017-04-12 21:47:53] [       cli] [INFO] Visited 0 stops
[2017-04-12 21:47:53] [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
[2017-04-12 21:47:53] [       cli] [INFO] Threw 0 pokeballs
[2017-04-12 21:47:53] [       cli] [INFO] Earned 0 Stardust
[2017-04-12 21:47:53] [       cli] [INFO] Hatched eggs 0
[2017-04-12 21:47:53] [       cli] [INFO] 
[2017-04-12 21:47:53] [       cli] [INFO] Highest CP Pokemon: 
[2017-04-12 21:47:53] [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 865, in <module>
    main()
  File "pokecli.py", line 195, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 147, in start_bot
    bot.start()
  File "/home/pi/PokemonGo-Bot/pokemongo_bot/__init__.py", line 155, in start
    self._setup_api()
  File "/home/pi/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1152, in _setup_api
    self.login()
  File "/home/pi/PokemonGo-Bot/pokemongo_bot/__init__.py", line 960, in login
    str(self.config.password))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 9: ordinal not in range(128)
[2017-04-12 21:47:53] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 877, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
[2017-04-12 21:47:53] [sentry.errors.uncaught] [ERROR] [u"UnicodeEncodeError: 'ascii' codec can't encode character u'\\xf1' in position 9: ordinal not in range(128)", u'  File "pokecli.py", line 865, in <module>', u'  File "pokecli.py", line 195, in main', u'  File "pokecli.py", line 147, in start_bot', u'  File "pokemongo_bot/__init__.py", line 155, in start', u'  File "pokemongo_bot/__init__.py", line 1152, in _setup_api', u'  File "pokemongo_bot/__init__.py", line 960, in login']

### Steps to Reproduce

installed following the steps of the wiki for linux and when I start it I get this error

### Other Information
OS: Raspbian Jessie (Debian Linux)
 
Branch: master
 
Git Commit: 8c176c089c34b02f6dae372b13b7343cbf19494f
 
Python Version: 2.7.9
 
Any other relevant files/configs (eg: path files) 

default conf

**Comment by TraggerHippy** [comment]
Did you try to update the bot ?

sudo su
cd PokeMonGo-Bot
./setup -u

Try to run the bot from a new lx terminal:
sudo su
cd PokemonGo-Bot
#activate virtualenv and start
source bin/activate
./run.sh


Perhaps install:
sudo apt-get install build-essential autoconf libtool pkg-config make python2.7-dev wget git

sudo apt-get update

I am running the bot now on raspberry raspbian jessie. Only chosen to install the dev branch, using the manual installation instructions, perhaps this helps you a bit, it did get me running again... had similar problems as yours and a few other recently mentioned problems as well. Hope this helps.

**Comment by davidakachaos** [comment]
Are there any strange characters in the password?

**Comment by MadMax-15** [comment]
I followed the steps of the manual installation as you suggested @TraggerHippy and when testing the account I got the same error so I created a new account without using a strange character in the password, as you said @davidakachaos  (I used the character ñ of the Spanish keyboard xD) and the bot is working correctly :)

Thanks for the help guys ;)

**Comment by davidakachaos** [comment]
Haha, stop coming up with such good passwords! :wink:

Op 13 apr. 2017 18:59 schreef "MadMax-15" <notifications@github.com>:

**Comment by davidakachaos** [comment]
Closing old issue, if you think this is an error let me know or open a new issue. Thank you.
