### ISSUE TITLE
str AttributeError

### ISSUE THREAD

**Issue by Kijax** [PokemonGoF/PokemonGo-Bot#6015]
### Expected Behavior
Bot shutdown with no error.

### Actual Behavior
After pressing ctrl+c bot display error as in section "Output when issue occurred".

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
Not related.

### Output when issue occurred
Traceback (most recent call last):
  File "pokecli.py", line 865, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.tick()
  File "/home/.../PokemonGo-Bot/pokemongo_bot/__init__.py", line 785, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/.../PokemonGo-Bot/pokemongo_bot/cell_workers/update_web_inventory.py", line 10, in work
    inventory.update_web_inventory()
  File "/home/.../PokemonGo-Bot/pokemongo_bot/inventory.py", line 1483, in update_web_inventory
    _inventory.update_web_inventory()
  File "/home/.../PokemonGo-Bot/pokemongo_bot/inventory.py", line 1347, in update_web_inventory
    raise FileIOException("Unexpected error writing to {}".web_inventory)
AttributeError: 'str' object has no attribute 'web_inventory'
[2017-04-13 11:29:37] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/.../PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/.../PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/.../PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/.../PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/.../PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/.../PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/.../PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/.../PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 877, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
[2017-04-13 11:29:37] [sentry.errors.uncaught] [ERROR] [u"AttributeError: 'str' object has no attribute 'web_inventory'", u'  File "pokecli.py", line 865, in <module>', u'  File "pokecli.py", line 206, in main', u'  File "pokemongo_bot/__init__.py", line 785, in tick', u'  File "pokemongo_bot/cell_workers/update_web_inventory.py", line 10, in work', u'  File "pokemongo_bot/inventory.py", line 1483, in update_web_inventory', u'  File "pokemongo_bot/inventory.py", line 1347, in update_web_inventory']

### Steps to Reproduce
Stop the bot with key combination ctrl+c.

### Other Information
OS: 
Debian Linux
Branch: 
master
Git Commit: 
8c176c089c34b02f6dae372b13b7343cbf19494f
Python Version: 
Python 2.7.9

**Comment by MerlionRock** [comment]
Ctrl + c is to stop the Bot anyway....

So even if error is encountered... I don't think it matters...

**Comment by walaoaaa1234** [comment]
maybe you should use Ctrl + break

**Comment by davidakachaos** [comment]
Ctrl + C will terminate the bot instantly.
So whatever the bot is doing, it stops instantly. Sometimes when you hit the "break" the bot is doing some calculation or action, but is interrupted by your command. This causes the "crash".
Now mind you, I'm not a big Python programmer, and I don't know if we can do anything to prevent this message/crash. As far as I know we trap the INT signal to shut down the bot gracefully.

If anyone knows a better way to make sure we can stop the bot anytime and still shutdown instantly without these kind of crashes, let us know! 😄

**Comment by davidakachaos** [comment]
Closing old issue, if you think this is an error let me know or open a new issue. Thank you.
