### ISSUE TITLE
exception while reloading config

### ISSUE THREAD

**Issue by ramarro123** [PokemonGoF/PokemonGo-Bot#6067]
with live config enabled, i got this exception when i modify the config file.

```


[2017-06-30 10:26:59] [MainThread] [       cli] [INFO] Config changed! Applying new config.
Exception in thread Thread-89:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/rama/poke/PokemonGo-Bot/pokemongo_bot/socketio_server/runner.py", line 34, in _start_listening_blocking
    listener = eventlet.listen((self.host, self.port))
  File "/Users/rama/poke/PokemonGo-Bot/lib/python2.7/site-packages/eventlet/convenience.py", line 43, in listen
    sock.bind(addr)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 48] Address already in use
```

**Comment by davidakachaos** [comment]
This has to do with the fact a websocket server is already running for the bot. Just leaving this as reference for fixing this issue.
