### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by goedzo** [PokemonGoF/PokemonGo-Bot#6068]
Get this error quite often after a relogin. Full log here:
```javascript
[2017-07-01 16:08:31] [PokemonGoBot] [INFO] Session stale, re-logging in.
[2017-07-01 16:08:31] [PokemonGoBot] [INFO] Login procedure started.
[2017-07-01 16:08:36] [PokemonGoBot] [INFO] Login successful.
[2017-07-01 16:08:36] [PokemonGoBot] [INFO] Checking for captcha challenge.
[2017-07-01 16:08:37] [CaptchaHandler] [INFO] Captcha Check Passed
[2017-07-01 16:08:37] [PokemonGoBot] [INFO] Niantic Official API Version: 0.67.1
[2017-07-01 16:08:38] [       cli] [INFO]
[2017-07-01 16:08:38] [       cli] [INFO] Ran for 2:26:32
[2017-07-01 16:08:38] [       cli] [INFO] Total XP Earned: 117535  Average: 48123.82/h
[2017-07-01 16:08:38] [       cli] [INFO] Travelled 7.87km
[2017-07-01 16:08:38] [       cli] [INFO] Visited 233 stops
[2017-07-01 16:08:38] [       cli] [INFO] Encountered 272 pokemon, 271 caught, 0 released, 0 evolved, 0 never seen before ()
[2017-07-01 16:08:38] [       cli] [INFO] Threw 323 pokeballs
[2017-07-01 16:08:38] [       cli] [INFO] Earned 32525 Stardust
[2017-07-01 16:08:38] [       cli] [INFO] Hatched eggs 4
[2017-07-01 16:08:38] [       cli] [INFO] Next egg hatches in 0.21 km
[2017-07-01 16:08:38] [       cli] [INFO]
[2017-07-01 16:08:38] [       cli] [INFO] Highest CP Pokemon: Octillery [CP: 1646] [IV: 9/1/7] Potential: 0.38
[2017-07-01 16:08:38] [       cli] [INFO] Most Perfect Pokemon: Pidgey [CP: 128] [IV: 15/14/12] Potential: 0.91
Traceback (most recent call last):
  File "pokecli.py", line 885, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.tick()
  File "/usr/src/app/pokemongo_bot/__init__.py", line 801, in tick
    self.check_session(self.position)
  File "/usr/src/app/pokemongo_bot/__init__.py", line 960, in check_session
    self.login()
  File "/usr/src/app/pokemongo_bot/__init__.py", line 1046, in login
    f = urllib2.urlopen(link)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:661)>
[2017-07-01 16:08:38] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 880, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
[2017-07-01 16:08:38] [sentry.errors.uncaught] [ERROR] [u'URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:661)>', u'  File "pokecli.py", line 885, in <module>', u'  File "pokecli.py", line 206, in main', u'  File "pokemongo_bot/__init__.py", line 801, in tick', u'  File "pokemongo_bot/__init__.py", line 960, in check_session', u'  File "pokemongo_bot/__init__.py", line 1046, in login', u'  File "python2.7/urllib2.py", line 154, in urlopen', u'  File "python2.7/urllib2.py", line 429, in open', u'  File "python2.7/urllib2.py", line 447, in _open', u'  File "python2.7/urllib2.py", line 407, in _call_chain', u'  File "python2.7/urllib2.py", line 1241, in https_open', u'  File "python2.7/urllib2.py", line 1198, in do_open']
```

**Comment by walaoaaa1234** [comment]
#6014 
```
davidakachaos commented on Apr 13
Are there any strange characters in the password?
```

**Comment by goedzo** [comment]
No there are not. Also restarting the bot actually works, so I think it is a different kind of issue. Maybe a new way from niantic to detect bots?

**Comment by walaoaaa1234** [comment]
@goedzo sorry, didn't read the log, the error come from the `Analytics` in bot, if you get this error quite often, you may turn it off.
https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics

**Comment by goedzo** [comment]
I don't get this very often, and I think it is good to keep it on so that we can keep botting hapily ;). So this here is just so that it can be fixed in the next update. 

Seems to me that increasing the ordinal to hold 0x9c (=156), would solve it. 

"0x9c in position 1: ordinal not in range(128)"

**Comment by Jcolomar** [comment]
hashing sevice now is giving a lot of issues this weekend

**Comment by fatalerrortan** [comment]
@Jcolomar  @goedzo I got a whole day of "Server Busy or offline" with debug "Api error" But I can still login using my phone.

**Comment by davidakachaos** [comment]
Something seems to be wrong with the pokehash service:
```
[2017-07-03 10:58:22] [INFO] Starting new HTTPS connection (1): pokehash.buddyauth.com
[2017-07-03 10:58:22] [ERROR] Error logging in! ('Connection aborted.', error(54, 'Connection reset by peer'))
```

**Comment by walaoaaa1234** [comment]
hash server still having issue, there is no ETA when it will fixed.

**Comment by Jcolomar** [comment]
Closed
