### ISSUE TITLE
Exception and error when install in Windows 7

### ISSUE THREAD

**Issue by shaosh** [PokemonGoF/PokemonGo-Bot#610]
In my Win7 PC, I installed the PyYAML-3.11.win-amd64-py2.7 and cloned this repo. When I run the command "virtualenv ." in cmd, it showed errors and exceptions:

> New python executable in D:\Documents\Pokemon\PokemonGo-Bot\Scripts\python.exe
Installing setuptools, pip, wheel...
  Complete output from command D:\Documents\Pokemon...t\Scripts\python.exe - setuptools pip wheel:
  Collecting setuptools
Exception:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\virtualenv_support\pip-8.1.2-py2.py3-none-any.whl\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\virtualenv_support\pip-8.1.2-py2.py3-none-any.whl\pip\commands\install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "c:\python27\lib\site-packages\virtualenv_support\pip-8.1.2-py2.py3-none-any.whl\pip\req\req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\python27\lib\site-packages\virtualenv_support\pip-8.1.2-py2.py3-none-any.whl\pip\req\req_set.py", line 522, in _prepare_file
    finder, self.upgrade, require_hashes)
  File "c:\python27\lib\site-packages\virtualenv_support\pip-8.1.2-py2.py3-none-any.whl\pip\req\req_install.py", line 268, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "c:\python27\lib\site-packages\virtualenv_support\pip-8.1.2-py2.py3-none-any.whl\pip\index.py", line 442, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "c:\python27\lib\site-packages\virtualenv_support\pip-8.1.2-py2.py3-none-any.whl\pip\index.py", line 363, in find_all_candidates
    self.find_links, expand_dir=True)
  File "c:\python27\lib\site-packages\virtualenv_support\pip-8.1.2-py2.py3-none-any.whl\pip\index.py", line 213, in _sort_locations
    sort_path(os.path.join(path, item))
  File "c:\python27\lib\site-packages\virtualenv_support\pip-8.1.2-py2.py3-none-any.whl\pip\index.py", line 194, in sort_path
    if mimetypes.guess_type(url, strict=False)[0] == 'text/html':
  File "c:\python27\Lib\mimetypes.py", line 297, in guess_type
    init()
  File "c:\python27\Lib\mimetypes.py", line 358, in init
    db.read_windows_registry()
  File "c:\python27\Lib\mimetypes.py", line 258, in read_windows_registry
    for subkeyname in enum_types(hkcr):
  File "c:\python27\Lib\mimetypes.py", line 249, in enum_types
    ctype = ctype.encode(default_encoding) # omit in 3.x!
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 1: ordinal not in range(128)
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\virtualenv.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\virtualenv.py", line 711, in main
    symlink=options.symlink)
  File "c:\python27\lib\site-packages\virtualenv.py", line 944, in create_environment
    download=download,
  File "c:\python27\lib\site-packages\virtualenv.py", line 900, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "c:\python27\lib\site-packages\virtualenv.py", line 795, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command D:\Documents\Pokemon...t\Scripts\python.exe - setuptools pip wheel failed with error code 2

Besides this issue, I am also wondering what is the equivalence command for "source bin/activate". cmd can't locate either command source or the path bin/activate.

Hope someone can direct me to get around this issue and finish the installation.
Thanks in advance for any suggestions.  

### Other Information
OS: Windows 7
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by shaosh** [comment]
I uninstall the Python 2.7.6, Python 3.2 and Python 3.3, and install the Python 2.7.12, all the problems solved.
