### ISSUE TITLE
Multi Account bot bursting

### ISSUE THREAD

**Issue by rakuuhwa** [PokemonGoF/PokemonGo-Bot#6222]
log:

--------------------Starting bot--------------------

2017-10-11 14:12:12 Thread-0 using account ****
2017-10-11 14:12:12 8A3Q4B7T8H is valid
2017-10-11 14:12:12 Thread-0 using account ****
2017-10-11 14:12:12 8A3Q4B7T8H is valid
2017-10-11 14:12:12 Thread-0 using account ****
2017-10-11 14:12:12 8A3Q4B7T8H is valid
2017-10-11 14:12:12 Thread-0 using account ****
2017-10-11 14:12:12 8A3Q4B7T8H is valid
2017-10-11 14:12:12 Thread-0 using account ****
2017-10-11 14:12:13 8A3Q4B7T8H is valid
2017-10-11 14:12:13 Thread-0 using account ****
2017-10-11 14:12:13 8A3Q4B7T8H is valid
2017-10-11 14:12:13 Thread-0 using account ****
2017-10-11 14:12:13 8A3Q4B7T8H is valid
2017-10-11 14:12:13 Thread-0 using account ****
2017-10-11 14:12:13 8A3Q4B7T8H is valid
2017-10-11 14:12:13 Thread-0 using account ****
2017-10-11 14:12:13 8A3Q4B7T8H is valid
2017-10-11 14:12:13 Thread-0 using account ****
2017-10-11 14:12:13 8A3Q4B7T8H is valid
2017-10-11 14:12:13 Thread-0 using account ****
2017-10-11 14:12:13 8A3Q4B7T8H is valid
2017-10-11 14:12:13 Thread-0 using account ****
2017-10-11 14:12:14 8A3Q4B7T8H is valid
2017-10-11 14:12:14 Thread-0 using account ****
2017-10-11 14:12:14 8A3Q4B7T8H is valid
2017-10-11 14:12:14 Thread-0 using account ****
2017-10-11 14:12:14 8A3Q4B7T8H is valid
2017-10-11 14:12:14 Thread-0 using account ****
2017-10-11 14:12:14 8A3Q4B7T8H is valid
2017-10-11 14:12:14 Thread-0 using account ****
2017-10-11 14:12:14 8A3Q4B7T8H is valid
2017-10-11 14:12:14 Thread-0 using account ****
2017-10-11 14:12:14 8A3Q4B7T8H is valid
2017-10-11 14:12:14 Thread-0 using account ****
2017-10-11 14:12:15 8A3Q4B7T8H is valid
2017-10-11 14:12:15 Thread-0 using account ****
2017-10-11 14:12:15 8A3Q4B7T8H is valid
2017-10-11 14:12:15 Thread-0 using account ****
2017-10-11 14:12:15 8A3Q4B7T8H is valid
2017-10-11 14:12:15 Thread-0 using account ****
2017-10-11 14:12:15 8A3Q4B7T8H is valid
2017-10-11 14:12:15 Thread-0 using account ****
2017-10-11 14:12:15 8A3Q4B7T8H is valid
2017-10-11 14:12:15 Thread-0 using account ****
2017-10-11 14:12:15 8A3Q4B7T8H is valid
2017-10-11 14:12:15 Thread-0 using account ****
2017-10-11 14:12:16 8A3Q4B7T8H is valid
2017-10-11 14:12:16 Thread-0 using account ****
2017-10-11 14:12:16 8A3Q4B7T8H is valid
2017-10-11 14:12:16 Thread-0 using account ****
2017-10-11 14:12:16 8A3Q4B7T8H is valid
2017-10-11 14:12:16 Thread-0 using account ****
2017-10-11 14:12:16 8A3Q4B7T8H is valid
2017-10-11 14:12:16 Thread-0 using account ****
2017-10-11 14:12:17 8A3Q4B7T8H is valid
2017-10-11 14:12:17 Thread-0 using account ****
2017-10-11 14:12:17 8A3Q4B7T8H is valid
2017-10-11 14:12:17 Thread-0 using account ****
2017-10-11 14:12:17 8A3Q4B7T8H is valid
2017-10-11 14:12:17 Thread-0 using account ****
2017-10-11 14:12:17 8A3Q4B7T8H is valid
2017-10-11 14:12:17 Thread-0 using account ****
2017-10-11 14:12:17 8A3Q4B7T8H is valid
2017-10-11 14:12:17 Thread-0 using account ****
2017-10-11 14:12:18 8A3Q4B7T8H is valid
2017-10-11 14:12:18 Thread-0 using account ****
2017-10-11 14:12:18 8A3Q4B7T8H is valid
2017-10-11 14:12:18 Thread-0 using account ****
2017-10-11 14:12:18 8A3Q4B7T8H is valid
2017-10-11 14:12:18 Thread-0 using account ****
2017-10-11 14:12:18 8A3Q4B7T8H is valid
2017-10-11 14:12:18 Thread-0 using account ****
2017-10-11 14:12:18 8A3Q4B7T8H is valid
2017-10-11 14:12:18 Thread-0 using account ****
2017-10-11 14:12:19 8A3Q4B7T8H is valid
2017-10-11 14:12:19 Thread-0 using account ****
2017-10-11 14:12:19 8A3Q4B7T8H is valid
2017-10-11 14:12:19 Thread-0 using account ****
2017-10-11 14:12:19 8A3Q4B7T8H is valid
2017-10-11 14:12:19 Thread-0 using account ****
2017-10-11 14:12:19 8A3Q4B7T8H is valid
2017-10-11 14:12:19 Thread-0 using account ****
2017-10-11 14:12:19 8A3Q4B7T8H is valid
2017-10-11 14:12:19 Thread-0 using account ****
2017-10-11 14:12:20 8A3Q4B7T8H is valid
2017-10-11 14:12:20 Thread-0 using account ****
2017-10-11 14:12:20 8A3Q4B7T8H is valid
2017-10-11 14:12:20 Thread-0 using account ****
2017-10-11 14:12:21 8A3Q4B7T8H is valid
2017-10-11 14:12:21 Thread-0 using account ****
2017-10-11 14:12:21 8A3Q4B7T8H is valid
2017-10-11 14:12:21 Thread-0 using account ****
2017-10-11 14:12:21 8A3Q4B7T8H is valid
2017-10-11 14:12:21 Thread-0 using account ****
2017-10-11 14:12:21 8A3Q4B7T8H is valid
2017-10-11 14:12:21 Thread-0 using account ****
2017-10-11 14:12:22 8A3Q4B7T8H is valid
2017-10-11 14:12:22 Thread-0 using account ****
2017-10-11 14:12:22 8A3Q4B7T8H is valid
2017-10-11 14:12:22 Thread-0 using account ****
2017-10-11 14:12:22 Thread-1 using account ****
2017-10-11 14:12:22 no valid hashkey! exit in 10s
2017-10-11 14:12:22 8A3Q4B7T8H is valid
2017-10-11 14:12:22 Thread-0 using account ****
2017-10-11 14:12:22 8A3Q4B7T8H is valid
2017-10-11 14:12:22 Thread-0 using account ****
2017-10-11 14:12:22 8A3Q4B7T8H is valid
2017-10-11 14:12:22 Thread-0 using account ****
2017-10-11 14:12:22 8A3Q4B7T8H is valid
2017-10-11 14:12:22 Thread-0 using account ****
2017-10-11 14:12:23 8A3Q4B7T8H is valid
2017-10-11 14:12:23 Thread-0 using account ****
2017-10-11 14:12:23 8A3Q4B7T8H is valid
2017-10-11 14:12:23 Thread-0 using account ****
2017-10-11 14:12:23 8A3Q4B7T8H is valid
2017-10-11 14:12:23 Thread-0 using account ****
2017-10-11 14:12:24 8A3Q4B7T8H is valid
2017-10-11 14:12:24 Thread-0 using account ****
2017-10-11 14:12:24 8A3Q4B7T8H is valid
2017-10-11 14:12:24 Thread-0 using account ****
2017-10-11 14:12:24 8A3Q4B7T8H is valid
2017-10-11 14:12:24 Thread-0 using account ****
2017-10-11 14:12:24 8A3Q4B7T8H is valid
2017-10-11 14:12:24 Thread-0 using account ****
2017-10-11 14:12:24 8A3Q4B7T8H is valid
2017-10-11 14:12:24 Thread-0 using account ****
2017-10-11 14:12:24 8A3Q4B7T8H is valid
2017-10-11 14:12:24 Thread-0 using account ****
2017-10-11 14:12:25 8A3Q4B7T8H is valid
2017-10-11 14:12:25 Thread-0 using account ****
2017-10-11 14:12:25 8A3Q4B7T8H is valid
2017-10-11 14:12:25 Thread-0 using account ****
2017-10-11 14:12:25 8A3Q4B7T8H is valid
2017-10-11 14:12:25 Thread-0 using account ****
2017-10-11 14:12:25 8A3Q4B7T8H is valid
2017-10-11 14:12:25 Thread-0 using account ****
2017-10-11 14:12:26 8A3Q4B7T8H is valid
2017-10-11 14:12:26 Thread-0 using account ****
2017-10-11 14:12:26 8A3Q4B7T8H is valid
2017-10-11 14:12:26 Thread-0 using account ****
2017-10-11 14:12:26 8A3Q4B7T8H is valid
2017-10-11 14:12:26 Thread-0 using account ****
2017-10-11 14:12:26 8A3Q4B7T8H is valid
2017-10-11 14:12:26 Thread-0 using account ****
2017-10-11 14:12:27 8A3Q4B7T8H is valid
2017-10-11 14:12:27 Thread-0 using account ****
2017-10-11 14:12:27 8A3Q4B7T8H is valid
2017-10-11 14:12:27 Thread-0 using account ****
2017-10-11 14:12:27 8A3Q4B7T8H is valid
2017-10-11 14:12:27 Thread-0 using account ****
2017-10-11 14:12:27 8A3Q4B7T8H is valid
2017-10-11 14:12:27 Thread-0 using account ****
2017-10-11 14:12:27 8A3Q4B7T8H is valid
2017-10-11 14:12:27 Thread-0 using account ****
2017-10-11 14:12:27 8A3Q4B7T8H is valid
2017-10-11 14:12:27 Thread-0 using account ****
2017-10-11 14:12:27 8A3Q4B7T8H is valid
2017-10-11 14:12:28 Thread-0 using account ****
2017-10-11 14:12:28 8A3Q4B7T8H is valid
2017-10-11 14:12:28 Thread-0 using account ****
2017-10-11 14:12:28 8A3Q4B7T8H is valid
2017-10-11 14:12:28 Thread-0 using account ****
2017-10-11 14:12:28 8A3Q4B7T8H is valid
2017-10-11 14:12:28 Thread-0 using account ****
2017-10-11 14:12:28 8A3Q4B7T8H is valid
2017-10-11 14:12:28 Thread-0 using account ****
2017-10-11 14:12:28 8A3Q4B7T8H is valid
2017-10-11 14:12:28 Thread-0 using account ****
2017-10-11 14:12:28 8A3Q4B7T8H is valid
2017-10-11 14:12:28 Thread-0 using account ****
2017-10-11 14:12:29 8A3Q4B7T8H is valid
2017-10-11 14:12:29 Thread-0 using account ****
2017-10-11 14:12:29 8A3Q4B7T8H is valid
2017-10-11 14:12:29 Thread-0 using account ****
2017-10-11 14:12:29 8A3Q4B7T8H is valid
2017-10-11 14:12:29 Thread-0 using account ****
2017-10-11 14:12:29 8A3Q4B7T8H is valid
2017-10-11 14:12:29 Thread-0 using account ****
2017-10-11 14:12:30 8A3Q4B7T8H is valid
2017-10-11 14:12:30 Thread-0 using account ****
2017-10-11 14:12:30 8A3Q4B7T8H is valid
2017-10-11 14:12:30 Thread-0 using account ****
2017-10-11 14:12:30 8A3Q4B7T8H is valid
2017-10-11 14:12:30 Thread-0 using account ****
2017-10-11 14:12:30 8A3Q4B7T8H is valid
2017-10-11 14:12:30 Thread-0 using account ****
2017-10-11 14:12:30 8A3Q4B7T8H is valid
2017-10-11 14:12:30 Thread-0 using account ****
2017-10-11 14:12:31 8A3Q4B7T8H is valid
2017-10-11 14:12:31 Thread-0 using account ****
2017-10-11 14:12:31 8A3Q4B7T8H is valid
2017-10-11 14:12:31 Thread-0 using account ****
2017-10-11 14:12:31 8A3Q4B7T8H is valid
2017-10-11 14:12:31 Thread-0 using account ****
2017-10-11 14:12:32 8A3Q4B7T8H is valid
2017-10-11 14:12:32 Thread-0 using account ****
2017-10-11 14:12:32 Interrupted stopping
---------------------------
Other Information
OS:
Win10
Branch:
master
Git Commit:
6f6ca78'
config.json:valid
multibotconfig.json: valid
Python Version: Python 2.7.12

I have put up a 6 account batch in the multi account config and the bat just runs trough them and finishes with the interrupted. All accounts are checked multiple times (account names are hidden)
Ssingle instance is working like a charm, but that is needing manual intervention by changing the accounts.
hashkey is valid till the 31th of October

**Comment by Jcolomar** [comment]
8A3Q4B7T8H = hashkey?

**Comment by rakuuhwa** [comment]
@Jcolomar  no. my hashkey has 20 characters, this is only the first part. (that is not changed, the output is showing only a part of the key)

**Comment by Jcolomar** [comment]
ahh.. u scared me xd

**Comment by rakuuhwa** [comment]
Any News on this? why is it bursting trough the accounts, even when the single instance is working?

**Comment by rakuuhwa** [comment]
Looked on the code and there was a line commented.
When the auth.json was generated after it should start with the os.system the cmd itself
The pass was not commented, and the startCMD was commented.
Can anyone with write Access Change the code:
line 265:
               else:
                    pass
                    #os.system(StartCmd)
to line 265
               else:
                    #pass
                    os.system(StartCmd)

It is now working as intended with this change

**Comment by MerlionRock** [comment]
I'm not good with these script stuff.... @nbq or @Xairooo can make the changes when you all are free?

@rakuuhwa You can also make the changes. Just fork this project to under your name. Make the changes at dev branch, come back here to do the PR. Or send me the file in discord, I'll upload it.

**Comment by MerlionRock** [comment]
@rakuuhwa Thank you. PR has been submitted #6224

**Comment by cosmico89** [comment]
i have this problem, when run "python MultiBot.py" (use dev branch)
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "MultiBot.py", line 269, in run
    Lprint((traceback()))
TypeError: 'module' object is not callable

**Comment by rakuuhwa** [comment]
Both issue solved with the latest patches. Good to close.

**Comment by tokar86a** [comment]
Seems to be some sort of problem whit proxy to.

It say Global Name proxy is not defined

**Comment by tokar86a** [comment]
The pr #6227  create a new type of error

http://tinypic.com/view.php?pic=9v8mf5&s=9#.WeWqKDBx2Uk

**Comment by tokar86a** [comment]
https://pastebin.com/0z3dCXrY

**Comment by Xairooo** [comment]
`[u'ProxyError: HTTPConnectionPool(host=\'"http\', port=80): Max retries exceeded with url: http://www.google-analytics.com/collect (Caused by ProxyError(\'Cannot connect to proxy.\', `

**Comment by tokar86a** [comment]
Hope we are going to see a fix for this problem soon.

**Comment by tokar86a** [comment]
It is  nothing wrong whit my proxy i using them whit rocketmaps and they are working 100%
