### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by tokar86a** [PokemonGoF/PokemonGo-Bot#6234]
### Expected Behavior

That it should start the next bot

### Actual Behavior

Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "MultiBot.py", line 248, in run
    self.Account = Manager.GetAccount()
  File "MultiBot.py", line 78, in GetAccount
    AccountTemp = self.Accounts[0]
IndexError: list index out of range

### Output when issue occurred

(16564) wsgi starting up on http://127.0.0.1:4000
[2017-10-22 14:19:09] [SleepSchedule] [INFO] Sleeping for 03:19:23, wake at 17:38:32
2017-10-22 14:19:16 Thread-1 using account 108.186.244.80
2017-10-22 14:19:16 1Z9G8C5Y2K is valid
2017-10-22 14:19:17,763 [       cli] [INFO] PokemonGO Bot v1.0
2017-10-22 14:19:17,770 [       cli] [INFO] commit: unknown
2017-10-22 14:19:17,776 [       cli] [INFO] Configuration initialized
2017-10-22 14:19:17,776 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2017-10-22 14:19:17,776 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2017-10-22 14:19:17,780 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
Message: Bot is now compatible with 0.79.3 API. Please refer to documenations on how to do an update. There are noted issues with the current API and subsequent bans and warnings may very well be issued and you take the risk into your own hands if you follow through.
Do you wish to continue? Y/N
Y
(13944) wsgi starting up on http://127.0.0.1:4001
[2017-10-22 14:19:19] [SleepSchedule] [INFO] Sleeping for 03:18:38, wake at 17:37:57
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "MultiBot.py", line 248, in run
    self.Account = Manager.GetAccount()
  File "MultiBot.py", line 78, in GetAccount
    AccountTemp = self.Accounts[0]
IndexError: list index out of range

### Other Information
OS: Windows 10
 
Branch: dev
 
Git Commit: 
 
Python Version: 2.7.14
 
Any other relevant files/configs (eg: path files)

**Comment by tokar86a** [comment]
Seems to be happen when i running more then 2 threads

**Comment by rakuuhwa** [comment]
How many accounts do you have in the accounts.txt? 
And are there any extra space or unusable characters?
the multibot account txt should be working with username:password formula
(i have tested with the latest build with 5 threads and it is working, until i put there more than 5 valid accounts.)

**Comment by tokar86a** [comment]
I have 5 account in the file and i use the formula that you are talking about. No it dont seems like i have any extra space or something like that. What can be the problem then @rakuuhwa ?
