### ISSUE TITLE
Installation fail: No module named 'pip.req'

### ISSUE THREAD

**Issue by groche97** [PokemonGoF/PokemonGo-Bot#6278]
The actual installer is broken, when i ejecute ./setup.sh -i or ./setup.sh -u the instalation fails installing pgoapi. 
The log is:
Collecting pgoapi from git+https://github.com/MerlionRock/pgoapi.git@develop#egg=pgoapi (from -r requirements.txt (line 4))
  Cloning https://github.com/MerlionRock/pgoapi.git (to revision develop) to /tmp/pip-install-fboa19o8/pgoapi
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fboa19o8/pgoapi/setup.py", line 5, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'

I reproduce it in Arch, gentoo and debian.

**Comment by bejito** [comment]
Same here...
Is this repo still maintained btw ?

**Comment by marclundgren** [comment]
same problem in 2020. RIP

**Comment by olskar** [comment]
Edit setup.sh and add the line `pip install --upgrade pip==9.0.3` above `pip install -r requirements.txt --upgrade` in this file.
