### ISSUE TITLE
ERROR    Cryptodome

### ISSUE THREAD

**Issue by Tozic** [PokemonGoF/PokemonGo-Bot#671]
I am running windows 10 and have followed all the steps for installing onto windows and have come to a hult when i get this error:

Traceback (most recent call last):
  File "C:\Users\amcsp\Desktop\PokemonGo-Bot-dev\pokecli.py", line 38, in <module>
    from pokemongo_bot import logger
  File "C:\Users\amcsp\Desktop\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 13, in <module>
    from pgoapi import PGoApi
  File "c:\users\amcsp\desktop\pokemongo-bot-dev\pokemongo-bot\src\pgoapi\pgoapi\__init__.py", line 19, in <module>
    from pgoapi.pgoapi import PGoApi
  File "c:\users\amcsp\desktop\pokemongo-bot-dev\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 35, in <module>
    from pgoapi.auth_google import AuthGoogle
  File "c:\users\amcsp\desktop\pokemongo-bot-dev\pokemongo-bot\src\pgoapi\pgoapi\auth_google.py", line 31, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 4, in <module>
    from . import google
  File "C:\Python27\lib\site-packages\gpsoauth\google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
  File "C:\Python27\lib\site-packages\Cryptodome\PublicKey\RSA.py", line 79, in <module>
    from Cryptodome.IO import PKCS8, PEM
  File "C:\Python27\lib\site-packages\Cryptodome\IO\PKCS8.py", line 73, in <module>
    from Cryptodome.IO._PBES import PBES1, PBES2, PbesError
  File "C:\Python27\lib\site-packages\Cryptodome\IO\_PBES.py", line 44, in <module>
    from Cryptodome.Cipher import DES, ARC2, DES3, AES
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\__init__.py", line 78, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\_mode_ecb.py", line 46, in <module>
    """
  File "C:\Python27\lib\site-packages\Cryptodome\Util\_raw_api.py", line 168, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s'" % name)
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb'

Please help, I have googled this and found nothing.
### Other Information
OS: Windows 10
Using Python in CMD

**Comment by tstumm** [comment]
Try reinstalling Python or downgrading to 2.7.10

**Comment by Aiyubi** [comment]
it seems your python installation is not working right

the obvious solution for your problem (a missing module) would be : "pip install Cryptodome"

**Comment by mieburungdara** [comment]
same issue

**Comment by surfaace** [comment]
python issue

**Comment by RedViper9** [comment]
Had this problem start after removing 32 bit Python 2.7.12 and installing 64 bit Python. Issue resolved after going back to 32bit Python. Guess the 64 bit libraries are not compatible.
