### ISSUE TITLE
KeyError: 'experience_awarded'

### ISSUE THREAD

**Issue by crack00r** [PokemonGoF/PokemonGo-Bot#73]
C:\Users\Manuel\Desktop\PokemonGo-Bot-master>pokecli.py -c 200 -a google -u jjhgjfg@gmail.com -p hgfdhdf -l "Oldenburg Schlossplatz" -s
2016-07-21 21:58:33,867 [   pokecli] [ INFO] Your given location: Schlo├ƒpl., 26122 Oldenburg, Germany
2016-07-21 21:58:33,868 [   pokecli] [ INFO] lat/long/alt: 53.1381631 8.2163356 0.0
(53.1381631, 8.216335599999999, 0.0)
2016-07-21 21:58:33,871 [auth_google] [ INFO] Google login for: jjhgjfg@gmail.com
2016-07-21 21:58:34,779 [auth_google] [ INFO] Google Login successful.
2016-07-21 21:58:34,780 [    pgoapi] [ INFO] Starting RPC login sequence (app simulation)
2016-07-21 21:58:35,085 [    pgoapi] [ INFO] Finished RPC login sequence (app simulation)
2016-07-21 21:58:35,085 [    pgoapi] [ INFO] Login process completed
Profile:
    Username: jjhgjfg@gmail.com
    Bag size: 750
    Pokemon Storage Size: 550
    Account Creation: 1468090737039
    Currency:
        POKECOIN: 550
        STARDUST: 4307
looping: step 1 of 100
steplimit: 100 x: 0 y: 0 pos: 1 dx: 0 dy -1
(53.1381631, 8.216335599999999, 0)
Found fort cbbdeade14c44c57a3d714ce6af63cff.11 at distance 860.473837527m
Need to move closer to Pokestop
Teleported to Pokestop
Now at Pokestop: Denkmal Des Oldenburgischen Dragoner-Regiments Nr. 19 - Spinning...
- Loot:
- 50 xp
- 1x Pokeball
- 1x Pokeball
- 1x Pokeball
Found fort dc5270b0064745f8a66fdf97d3d00770.16 at distance 1090.80155185m
Need to move closer to Pokestop
Teleported to Pokestop
Now at Pokestop: Tura 1976 - Spinning...
- Loot:
Traceback (most recent call last):
  File "C:\Users\Manuel\Desktop\PokemonGo-Bot-master\pokecli.py", line 244, in <module>
    main()
  File "C:\Users\Manuel\Desktop\PokemonGo-Bot-master\pokecli.py", line 217, in main
    working.work_on_cell(cell,api,position,config)
  File "C:\Users\Manuel\Desktop\PokemonGo-Bot-master\working.py", line 52, in work_on_cell
    hack_chain=search_seen_fort(fort,api,position,config)
  File "C:\Users\Manuel\Desktop\PokemonGo-Bot-master\working.py", line 187, in search_seen_fort
    print("- " + str(spin_details['experience_awarded']) + " xp")
KeyError: 'experience_awarded'

C:\Users\Manuel\Desktop\PokemonGo-Bot-master>

**Comment by PokemonGoF** [comment]
I want to do the quick fix after the code refactor from @douglascamata

**Comment by PokemonGoF** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/commit/9276741e3c33f7f05f5aec99f13ee66aa44dcfe7
This should be fixed
