### ISSUE TITLE
Issue starting(reading config)

### ISSUE THREAD

**Issue by leadboots5** [PokemonGoF/PokemonGo-Bot#733]
### Expected Behavior
The bot to start, or give a helpful error message if i was doing something wrong.

### Actual Behavior
Errors out with:

Traceback (most recent call last):
  File "pokecli.py", line 222, in <module>
    main()
  File "pokecli.py", line 199, in main
    config = init_config()
  File "pokecli.py", line 63, in init_config
    load.update(json.load(data))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

### Steps to Reproduce
Follow setup instructions, create the config files and fill in values and then use 'python pokecli.py'.

### Other Information
OS: OSX
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
f1933d3089b340392780da8fc9356e84e2fa2bf8

**Comment by HeIix** [comment]
I am also having this same issue with the latest dev branch.  Thanks.

**Comment by SteffanLong** [comment]
You're missing a comma in the config.json most likely.

**Comment by LeaklessGfy** [comment]
Can we see your config.json ?

**Comment by HeIix** [comment]
Wow you are right, not sure how I removed a comma.  I appreciate your time, sorry it was such a simple fix.

**Comment by LeaklessGfy** [comment]
To close :)

**Comment by SteffanLong** [comment]
There was a brief moment where the example was missing a comma, not your fault. :)

**Comment by leadboots5** [comment]
mine has proper commas:

{
    "auth_service": “ptc”,
    "username": “username”,
    "password": “pass”,
    "location": "43.number,-89.othernumber",
    "gmapkey": "keyyyyyyy",
    "max_steps": 5,
    "mode": "all",
    "walk": 1.9,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": false,
    "distance_unit": "km",
    "item_filter": “101,701”,
    "evolve_all": "NONE"
}
