### ISSUE TITLE
Issue starting(reading config)

### ISSUE THREAD

**Issue by leadboots5** [PokemonGoF/PokemonGo-Bot#738]
### Expected Behavior
The bot to start, or give a helpful error message if i was doing something wrong.

### Actual Behavior
Errors out with:

Traceback (most recent call last):
File "pokecli.py", line 222, in 
main()
File "pokecli.py", line 199, in main
config = init_config()
File "pokecli.py", line 63, in init_config
load.update(json.load(data))
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/init.py", line 290, in load
**kw)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/init.py", line 338, in loads
return _default_decoder.decode(s)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

### Steps to Reproduce

Follow setup(same that has worked prior to config files) and then run python pokecli.py 

{
    "auth_service": “ptc”,
    "username": “user”,
    "password": “pass”,
    "location": "43.nums,-89.nums",
    "gmapkey": "apikeyhere",
    "max_steps": 5,
    "mode": "all",
    "walk": 1.9,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": false,
    "distance_unit": "km",
    "item_filter": "101,701”,
    "evolve_all": "NONE"
}

### Other Information
OS: OSX
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
55adefeeb580ed8bb51d097e56a506e2973377c9

**Comment by fedden** [comment]
Getting this too. 99% sure config files are correct.. 

Also are the commandline parameters not available anymore?

Thanks

**Comment by Nihisil** [comment]
`“` is not valid character, you can check your json here - http://jsonlint.com/

You need to use `"` instead.

**Comment by leadboots5** [comment]
Wow. Textedit on Mac, simply amazing. Thanks @Nihisil !
