### ISSUE TITLE
Got KeyError: 'player_data' from start

### ISSUE THREAD

**Issue by TheSegfault** [PokemonGoF/PokemonGo-Bot#741]
Traceback (most recent call last):
  File "pokecli.py", line 197, in <module>
    main()
  File "pokecli.py", line 183, in main
    bot.start()
  File "/Users/Admin/xDev/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/Users/Admin/xDev/PokemonGo-Bot/pokemongo_bot/__init__.py", line 179, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'player_data'

Don't know what to do :/

**Comment by aslafy-z** [comment]
Please search before posting an issue: [https://github.com/PokemonGoF/PokemonGo-Bot/search?q=player_data&type=Issues&utf8=%E2%9C%93](https://github.com/PokemonGoF/PokemonGo-Bot/search?q=player_data&type=Issues&utf8=%E2%9C%93)

**Comment by solderzzc** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/pull/727
Will solve this.

Thanks @aslafy-z

**Comment by TheSegfault** [comment]
My bad !
