### ISSUE TITLE
Error while installing requirements 

### ISSUE THREAD

**Issue by JonathanRosado** [PokemonGoF/PokemonGo-Bot#746]
### Expected Behavior
Expecting `install -r requirements.txt` to correctly install packages

### Actual Behavior
```
Extracting nose-1.3.7-py2.7.egg to /tmp/pip_build_root/protobuf-to-dict/.eggs



Installed /tmp/pip_build_root/protobuf-to-dict/.eggs/nose-1.3.7-py2.7.egg

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/protobuf-to-dict/setup.py", line 25, in <module>

    'Topic :: Software Development :: Libraries :: Python Modules',

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 279, in __init__

    self.fetch_build_eggs(attrs['setup_requires'])

  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 323, in fetch_build_eggs

    replace_conflicting=True,

  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 826, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1085, in best_match

    dist = working_set.find(req)

  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 695, in find

    raise VersionConflict(dist, req)

pkg_resources.VersionConflict: (six 1.5.2 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.9'))

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/protobuf-to-dict
Storing debug log for failure in /home/devops/.pip/pip.log
```

**Comment by leadboots5** [comment]
What OS are you on? Did you you the virtualenv stuff?

**Comment by hklcf** [comment]
> (six 1.5.2 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.9'))

**Comment by JulioMansilla** [comment]
I had the same issue, are you running a virtual environment?

**Comment by JonathanRosado** [comment]
Oops! Virtualenv did it for me. Thanks @leadboots5 @JulioMansilla 
closing...
