### ISSUE TITLE
Unicode Decoding Error

### ISSUE THREAD

**Issue by daemonfire300** [PokemonGoF/PokemonGo-Bot#75]
```bash
Found fort 10136cb8825a489ca1e3f189d02b0866.16 at distance 210.889670578m
Need to move closer to Pokestop
Teleported to Pokestop
Traceback (most recent call last):
  File "pokecli.py", line 244, in <module>
    main()
  File "pokecli.py", line 217, in main
    working.work_on_cell(cell,api,position,config)
  File "/usr/src/app/working.py", line 52, in work_on_cell
    hack_chain=search_seen_fort(fort,api,position,config)
  File "/usr/src/app/working.py", line 173, in search_seen_fort
    print('Now at Pokestop: ' + fort_details['name'] + ' - Spinning...')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 18: ordinal not in range(128)

```
```bash
ubuntu@ubuntu-xenial:~/PokemonGo-Bot$ git rev-parse HEAD
4cfd4734c78dd3c8473a1d001729037e6cceb37c
```

Using Docker. Ubuntu 16.04. Just pulled the newest merge, and it stopped working. With the commits from before 30 minutes it worked.

This change probably does not handle non-ASCII letters very well: https://github.com/PokemonGoF/PokemonGo-Bot/commit/a621ab34a376ffe3c19ca8ab66228ee7dfcf51b7

**Comment by Boren** [comment]
This is a problem with a character not known to ascii.

`sys.setdefaultencoding('utf-8')`

This line at the start of the program might fix it.

**Comment by daemonfire300** [comment]
@Boren I also read if `ENV LC_ALL "en_US.utf8"` is not set it might cause this problem. (SO: http://stackoverflow.com/a/20334767/189122) I will check if this fixes the problem, otherwise I will just at the line you proposed. Thank you very much for the quick reply.

**Comment by fwalser** [comment]
[#] Finished walking
Arrived at Pokestop
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Bot\PokemonGo-Bot-dev\pokecli.py", line 1
06, in <module>
    main()
  File "C:\Users\Administrator\Desktop\Bot\PokemonGo-Bot-dev\pokecli.py", line 1
03, in main
    bot.take_step()
  File "C:\Users\Administrator\Desktop\Bot\PokemonGo-Bot-dev\pokemongo_bot\__ini
t__.py", line 29, in take_step
    self.stepper.take_step()
  File "C:\Users\Administrator\Desktop\Bot\PokemonGo-Bot-dev\pokemongo_bot\stepp
er.py", line 70, in take_step
    self.bot.work_on_cell(cell,position)
  File "C:\Users\Administrator\Desktop\Bot\PokemonGo-Bot-dev\pokemongo_bot\__ini
t__.py", line 50, in work_on_cell
    hack_chain = worker.work()
  File "C:\Users\Administrator\Desktop\Bot\PokemonGo-Bot-dev\pokemongo_bot\cell_
workers\seen_fort_worker.py", line 45, in work
    print_yellow('Now at Pokestop: ' + fort_name + ' - Spinning...')
  File "C:\Users\Administrator\Desktop\Bot\PokemonGo-Bot-dev\pokemongo_bot\cell_
workers\utils.py", line 16, in print_yellow
    print('\033[93m' + message + '\033[0m');
  File "C:\Python27\lib\codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
**UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 41: ordinal
 not in range(128)**

C:\Users\Administrator\Desktop\Bot\PokemonGo-Bot-dev>

C:\Users\Administrator\Desktop\Bot\PokemonGo-Bot-dev>

**Comment by s1x** [comment]
This should be fixed.
