### ISSUE TITLE
Can not run the script

### ISSUE THREAD

**Issue by pararang** [PokemonGoF/PokemonGo-Bot#751]
### Expected Behavior
-

### Actual Behavior
Traceback (most recent call last):
  File "./pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "/opt/PokemonGo-Bot/pokemongo_bot/__init__.py", line 14, in <module>
    from pgoapi import PGoApi
  File "/opt/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 19, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/opt/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 33, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/opt/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 40, in <module>
    from POGOProtos.Networking.Envelopes_pb2 import RequestEnvelope
  File "/opt/PokemonGo-Bot/src/pgoapi/pgoapi/protos/POGOProtos/Networking/Envelopes_pb2.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
ImportError: cannot import name symbol_database

### Steps to Reproduce
sudo python ./pokecli.py

### Other Information
OS: Ubuntu 14.04
Git Commit: 55adefeeb580ed8bb51d097e56a506e2973377c9

**Comment by ryuzaki01** [comment]
sudo pip install --upgrade protobuf
