### ISSUE TITLE
KeyError: 'player_data

### ISSUE THREAD

**Issue by lufthansa747** [PokemonGoF/PokemonGo-Bot#760]
### Expected Behavior
Not to error

### Actual Behavior
[2016-07-25 01:12:38] [x] PokemonGO Bot v1.0
[2016-07-25 01:12:38] [x] Configuration initialized
[2016-07-25 01:12:39]
[2016-07-25 01:12:39] [x] Address found: ...
[2016-07-25 01:12:39] [x] Position in-game set as: ()
[2016-07-25 01:12:39]
Traceback (most recent call last):
  File "pokecli.py", line 222, in <module>
    main()
  File "pokecli.py", line 208, in main
    bot.start()
  File "C:\Users\\__init__.py", line 32, in start
    self._setup_api()
  File "C:\Users\\__init__.py", line 153, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'player_data'

### Steps to Reproduce
I followed readme and ran `python pokecli.py`
Ive tried with a google acount and ptc account

### Other Information
OS: Windows 10
Git Commit: c5a7109fd82ea4644d4f8a598f5a83bab4361f63

**Comment by LasseSkogland** [comment]
Delete and Reclone Repo.
