### ISSUE TITLE
AttributeError: 'PokemonGoBot' object has no attribute 'navigator' crash

### ISSUE THREAD

**Issue by jasonleeraert** [PokemonGoF/PokemonGo-Bot#769]
### Expected Behavior
bot runs as intended

### Actual Behavior
bot crashes after ~5 seconds

### Steps to Reproduce
windows 10 - removed local repository, checked out master again. Installed all the requirements.
Changed the config files, tried to run the bot with command python pokecli.py -cf config_custom.json
Sometimes it works for a few seconds and catches a pokemon, but mostly it crashes at the stage "attempting to evolve all pokemons".
[#] Attempting to evolve all pokemons ...
[2016-07-25 09:16:47] [#] Something rustles nearby!
[2016-07-25 09:16:48] [#] A Wild Voltorb appeared! [CP 105] [Potential 0.73]
[2016-07-25 09:16:48] [#] IV [Stamina/Attack/Defense] = [12/11/10]
[2016-07-25 09:16:50] [x] Using Pokeball (chance: 68.91%)... (5 left!)
[2016-07-25 09:16:51] [x] Captured Voltorb! [CP 105] [12/11/10]
[2016-07-25 09:16:52] [#] Voltorb has been exchanged for candy!
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "C:\Repositories\PokemonGo-Bot\pokemongo_bot\__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "C:\Repositories\PokemonGo-Bot\pokemongo_bot\stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "C:\Repositories\PokemonGo-Bot\pokemongo_bot\stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "C:\Repositories\PokemonGo-Bot\pokemongo_bot\__init__.py", line 92, in work_on_cell
    worker = MoveToFortWorker(fort, self)
  File "C:\Repositories\PokemonGo-Bot\pokemongo_bot\cell_workers\move_to_fort_worker.py", line 10, in __init__
    self.navigator = bot.navigator
AttributeError: 'PokemonGoBot' object has no attribute 'navigator'

### Other Information
OS:  Windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
6e99169d963bd8637dfb55426650f2fe15e694bd

**Comment by jasonleeraert** [comment]
Seems to be fixed now, apparently there were some local changes to the worker files (dunno how), after discarding these changes the bot is running again.
