### ISSUE TITLE
KeyError: 'experience_awarded'

### ISSUE THREAD

**Issue by johnc2k** [PokemonGoF/PokemonGo-Bot#79]
Version:   Git Commit ff51a30

```
root@kali:/opt/PokemonGo-Bot# ./pokecli.py -a ptc -u xxx -p xxx --location "xxx" -c 400 -s
2016-07-21 16:23:52,636 [   pokecli] [ INFO] Your given location: xxx
2016-07-21 16:23:52,638 [   pokecli] [ INFO] lat/long/alt: xxx
2016-07-21 16:23:52,640 [  auth_ptc] [ INFO] Login for: xxx
2016-07-21 16:23:53,511 [  auth_ptc] [ INFO] PTC Login successful
2016-07-21 16:23:53,512 [    pgoapi] [ INFO] Starting RPC login sequence (app simulation)
2016-07-21 16:23:53,891 [    pgoapi] [ INFO] Finished RPC login sequence (app simulation)
2016-07-21 16:23:53,892 [    pgoapi] [ INFO] Login process completed
Profile:
    Username: xxx
    Bag size: 350
    Pokemon Storage Size: 250
    Account Creation: xxx
    Currency:
        POKECOIN: 0
        STARDUST: 123456
looping: step 1 of 100
steplimit: 100 x: 0 y: 0 pos: 1 dx: 0 dy -1
(xxx, -xxx, 0)
Found fort xxxxxxxxxxxxxxxxxxxxxxxxx at distance 123m
Need to move closer to Pokestop
Teleported to Pokestop
Now at Pokestop: xxxx - Spinning...
- Loot:
Traceback (most recent call last):
  File "./pokecli.py", line 244, in <module>
    main()
  File "./pokecli.py", line 217, in main
    working.work_on_cell(cell,api,position,config)
  File "/opt/PokemonGo-Bot/working.py", line 52, in work_on_cell
    hack_chain=search_seen_fort(fort,api,position,config)
  File "/opt/PokemonGo-Bot/working.py", line 187, in search_seen_fort
    print("- " + str(spin_details['experience_awarded']) + " xp")
KeyError: 'experience_awarded'
```

**Comment by Bonfire** [comment]
Duplicate issue. One already exists.

**Comment by PokemonGoF** [comment]
Let's wait for the in progress code refactoring a little bit....

**Comment by dominikue** [comment]
Have the same Error.

**Comment by douglascamata** [comment]
btw, my refactoring I almost done. I finished merging the improve pokestop loot information and I'm running the bot until a pokestop is found for testing. PR incoming very very soon.

**Comment by PokemonGoF** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/commit/9276741e3c33f7f05f5aec99f13ee66aa44dcfe7
This should be fixed.
