### ISSUE TITLE
Problem with TAKE STEP

### ISSUE THREAD

**Issue by beedy01** [PokemonGoF/PokemonGo-Bot#790]
### Actual Behavior

[2016-07-25 17:40:09] [#] A Wild Spearow appeared! [CP 26] [Potential 0.47]
[2016-07-25 17:40:09] [#] IV [Stamina/Attack/Defense] = [9/8/4]
[2016-07-25 17:40:11] [x] Using Pokeball (chance: 100.00%)... (215 left!)
[2016-07-25 17:40:12] [x] Captured Spearow! [CP 26] [IV 0.47]
[2016-07-25 17:40:13] [#] Spearow has been exchanged for candy!
[2016-07-25 17:40:31] [#] Something rustles nearby!
[2016-07-25 17:40:31] [#] A Wild Beedrill appeared! [CP 599] [Potential 0.29]
[2016-07-25 17:40:31] [#] IV [Stamina/Attack/Defense] = [10/2/1]
[2016-07-25 17:40:34] [x] Using Greatball (chance: 13.30%)... (23 left!)
[2016-07-25 17:40:34] [x] Captured Beedrill! [CP 599] [IV 0.29]
[2016-07-25 17:40:35] [#] Beedrill has been exchanged for candy!
[2016-07-25 17:40:51] [#] Something rustles nearby!
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "C:\pogomap\current\pokemongo_bot\__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "C:\pogomap\current\pokemongo_bot\stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "C:\pogomap\current\pokemongo_bot\stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "C:\pogomap\current\pokemongo_bot\__init__.py", line 93, in work_on_cell
    worker.work()
  File "C:\pogomap\current\pokemongo_bot\cell_workers\move_to_fort_worker.py", line 30, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "C:\pogomap\current\pokemongo_bot\stepper.py", line 88, in _walk_to
    alt, False)
  File "C:\pogomap\current\pokemongo_bot\stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "C:\pogomap\current\pokemongo_bot\__init__.py", line 63, in work_on_cell
    if self.catch_pokemon(pokemon) == PokemonCatchWorker.NO_POKEBALLS:
  File "C:\pogomap\current\pokemongo_bot\__init__.py", line 190, in catch_pokemon
    return_value = worker.work()
  File "C:\pogomap\current\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 30, in work
    response_dict = self.api.call()
  File "c:\pogomap\current\src\pgoapi\pgoapi\pgoapi.py", line 81, in call
    response = request.request(api_endpoint, self._req_method_list, player_position)
  File "c:\pogomap\current\src\pgoapi\pgoapi\rpc_api.py", line 98, in request
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException

### Steps to Reproduce

just run the master version

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by surfaace** [comment]
it says that you are not logged in: File "c:\pogomap\current\src\pgoapi\pgoapi\rpc_api.py", line 98, in request
raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException

**Comment by beedy01** [comment]
so what should i do?. active the logging? i'll notify again if its happen.

**Comment by surfaace** [comment]
check if issue occures again in dev branch (if not already running) and have up to date branch.

please create a new issue if it occures again
