### ISSUE TITLE
Spinning Unknown Pokestops or Keep walking

### ISSUE THREAD

**Issue by seadog007** [PokemonGoF/PokemonGo-Bot#794]
### Expected Behavior
Keep catch Pokemons and spin the Pokestops.

### Actual Behavior
Spinning Unknown Pokestops or Keep walking.

### Steps to Reproduce
Run the script for a while (usually about one hour).

### Other Information
OS: Ubuntu 14.04 Desktop
Git Commit: b8606bc509ca89902441b213f5ee7996cca29137
Log from the account which location setting is `37.78839,-122.40764`
```
[2016-07-25 18:07:43] [x] PokemonGO Bot v1.0
[2016-07-25 18:07:43] [x] Configuration initialised
Normal Log...
[2016-07-25 19:00:07] [+] 1x Revive (Total: 103)                                                                                                                             
[2016-07-25 19:00:07] [+] 1x Potion (Total: 23)
[2016-07-25 19:00:07] [+] Recycling 1x Potion...
[2016-07-25 19:00:08] [+] Recycling success
[2016-07-25 19:00:08] [+] 1x Pokeball (Total: 51)
[2016-07-25 19:00:08] [#] PokeStop on cooldown. Time left: 3.78 minutes
[2016-07-25 19:00:10] [#] Found fort 6885fa828e014c7b9074f4f3f2a02d58.16 at distance 0.74km
[2016-07-25 19:00:10] [#] Need to move closer to Pokestop
[2016-07-25 19:05:51] [#] Arrived at Pokestop
[2016-07-25 19:05:53] [#] Now at Pokestop: Strong Women - Spinning...
[2016-07-25 19:05:55] [+] Loot:
[2016-07-25 19:05:55] [+] 100 xp
[2016-07-25 19:05:56] [+] 6x Pokeball (Total: 57)
[2016-07-25 19:05:56] [+] 1x Ultraball (Total: 3)
[2016-07-25 19:05:56] [#] PokeStop on cooldown. Time left: 3.78 minutes
[2016-07-25 19:05:58] [#] Found fort 2b3f38b36f184c268a5ae6e92c4b5bd0.16 at distance 0.82km
[2016-07-25 19:05:58] [#] Need to move closer to Pokestop
[2016-07-25 19:09:09] [#] Arrived at Pokestop
[2016-07-25 19:09:11] [#] Now at Pokestop: Tenderloin Children's Playground Characters - Spinning...
[2016-07-25 19:09:13] [+] Loot:
[2016-07-25 19:09:13] [+] 50 xp
[2016-07-25 19:09:14] [+] 1x Revive (Total: 104)
[2016-07-25 19:09:14] [+] 1x Ultraball (Total: 4)
[2016-07-25 19:09:14] [+] 1x Pokeball (Total: 58)
[2016-07-25 19:09:14] [#] PokeStop on cooldown. Time left: 3.79 minutes
[2016-07-25 19:09:16] [#] Scanning area for objects....
[2016-07-25 19:09:16] [#] Walking from (37.784681382500885, -122.4155937955918) to (37.790884299999995, -122.4076388) 0.98km
[2016-07-25 19:09:29] [#] Found fort 721d9b1a74004e18a58a4d5dbcef1705.16 at distance 0.20km
[2016-07-25 19:09:29] [#] Need to move closer to Pokestop
[2016-07-25 19:13:48] [#] Arrived at Pokestop
[2016-07-25 19:13:49] [#] Now at Pokestop: Unknown - Spinning...
[2016-07-25 19:14:01] [#] Found fort d8f34cb719224005b80e41f56c7dd4fa.12 at distance 0.23km
[2016-07-25 19:14:01] [#] Need to move closer to Pokestop
[2016-07-25 19:14:41] [#] Arrived at Pokestop
[2016-07-25 19:14:43] [#] Now at Pokestop: Unknown - Spinning...
[2016-07-25 19:14:52] [#] Found fort dab84afbc8784bd39e00c63747e5227a.16 at distance 0.24km
[2016-07-25 19:14:52] [#] Need to move closer to Pokestop
[2016-07-25 19:15:38] [#] Arrived at Pokestop
[2016-07-25 19:15:41] [#] Now at Pokestop: Unknown - Spinning...
[2016-07-25 19:15:52] [#] Found fort c35a01bf3f264505847d5b63317ea4e6.11 at distance 0.33km
[2016-07-25 19:15:52] [#] Need to move closer to Pokestop
[2016-07-25 19:16:46] [#] Arrived at Pokestop
[2016-07-25 19:16:48] [#] Now at Pokestop: Unknown - Spinning...
[2016-07-25 19:17:00] [#] Found fort 11a6db909c46409280d93fb97ba58d3d.16 at distance 0.34km
[2016-07-25 19:17:00] [#] Need to move closer to Pokestop
^C[2016-07-25 19:17:09] [x] Exiting PokemonGo Bot
```
  
Log from account which location setting is `34.01042157488069, -118.49967097705793`
```
[2016-07-25 18:10:24] [x] PokemonGO Bot v1.0
[2016-07-25 18:10:24] [x] Configuration initialized
Normal Log...
[2016-07-25 19:04:57] [#] Arrived at Pokestop
[2016-07-25 19:04:59] [#] Now at Pokestop: West 4th and Jane - Spinning...
[2016-07-25 19:05:02] [+] Loot:
[2016-07-25 19:05:02] [+] 50 xp
[2016-07-25 19:05:02] [+] 1x Pokeball (Total: 90)
[2016-07-25 19:05:03] [+] 2x Greatball (Total: 32)
[2016-07-25 19:05:03] [+] 1x Ultraball (Total: 9)
[2016-07-25 19:05:03] [#] PokeStop on cooldown. Time left: 3.77 minutes
[2016-07-25 19:05:05] [#] Found fort 471afbc641ef4d4b9a1a41de062983f5.16 at distance 0.73km
[2016-07-25 19:05:05] [#] Need to move closer to Pokestop
[2016-07-25 19:07:58] [#] Arrived at Pokestop
[2016-07-25 19:07:59] [#] Now at Pokestop: Garden Fountains of City Hall  - Spinning...
[2016-07-25 19:08:02] [+] Loot:
[2016-07-25 19:08:02] [+] 50 xp
[2016-07-25 19:08:03] [+] 1x Revive (Total: 40)
[2016-07-25 19:08:03] [+] Recycling 1x Revive...
[2016-07-25 19:08:03] [+] Recycling success
[2016-07-25 19:08:03] [+] 2x Pokeball (Total: 92)
[2016-07-25 19:08:03] [#] PokeStop on cooldown. Time left: 3.77 minutes
[2016-07-25 19:08:05] [#] Found fort adf7a4a0163c400a993f6629e4f5b200.16 at distance 0.71km
[2016-07-25 19:08:05] [#] Need to move closer to Pokestop
[2016-07-25 19:09:53] [#] Arrived at Pokestop
[2016-07-25 19:09:55] [#] Now at Pokestop: A Balanced Life - Spinning...
[2016-07-25 19:09:57] [+] Loot:
[2016-07-25 19:09:57] [+] 50 xp
[2016-07-25 19:09:57] [+] 2x Pokeball (Total: 94)
[2016-07-25 19:09:57] [+] 1x Greatball (Total: 33)
[2016-07-25 19:09:57] [#] PokeStop on cooldown. Time left: 3.79 minutes
[2016-07-25 19:09:59] [#] Found fort 4c8fbd061d674422b41ad32a59e63ac0.12 at distance 0.97km
[2016-07-25 19:09:59] [#] Need to move closer to Pokestop
[2016-07-25 19:11:56] [#] Arrived at Pokestop
[2016-07-25 19:11:58] [#] Now at Pokestop: Civic Center Parking Art - Spinning...
[2016-07-25 19:12:00] [+] Loot:
[2016-07-25 19:12:00] [+] 50 xp
[2016-07-25 19:12:01] [+] 1x Pokeball (Total: 95)
[2016-07-25 19:12:01] [+] 2x Greatball (Total: 35)
[2016-07-25 19:12:01] [#] PokeStop on cooldown. Time left: 3.77 minutes
[2016-07-25 19:12:03] [#] Found fort cc8c005c1d734edb9d98e39ea64446b9.16 at distance 1.10km
[2016-07-25 19:12:03] [#] Need to move closer to Pokestop
[2016-07-25 19:17:14] [#] Arrived at Pokestop
[2016-07-25 19:17:17] [#] Now at Pokestop: Unknown - Spinning...
[2016-07-25 19:17:28] [#] Found fort 208f38b58d39450f96a1dac89617a8df.12 at distance 1.14km
[2016-07-25 19:17:28] [#] Need to move closer to Pokestop
^C[2016-07-25 19:17:35] [x] Exiting PokemonGo Bot
```
  
I run the five account at the same time, but when I run for a while, it happen like the photo below.
<img width="1280" alt="screen shot 2016-07-25 at 7 17 38 pm" src="https://cloud.githubusercontent.com/assets/5138409/17099816/3fb852c4-529d-11e6-939e-f6c21f84fc97.png">
<img width="650" alt="screen shot 2016-07-25 at 7 28 15 pm" src="https://cloud.githubusercontent.com/assets/5138409/17099980/46e11634-529e-11e6-855f-95467d3fc743.png">
<img width="945" alt="screen shot 2016-07-25 at 7 28 22 pm" src="https://cloud.githubusercontent.com/assets/5138409/17099984/49129018-529e-11e6-8b9d-3a7bfaa1d165.png">

**Comment by dmateusp** [comment]
Might be a Soft ban or might be the log in token not be refreshed. Soft ban detection could use that "Unknown" pokestop name to stop and Sleep for a while. The log in token refresh has a Pull request already and should be fixed.

Thanks for the clarity of the issue

**Comment by seadog007** [comment]
@dmateusp I don't think it is softban, because it happened lots time for me.
After I restart that, it become normal, so I think it should be the token expired.

**Comment by douglascamata** [comment]
Should be fixed by 1312ca4aa2b6ea800ac4637d3964ae1a9ab6668b, please text and give feedback. Thanks!

**Comment by seadog007** [comment]
Well....
```
[2016-07-25 19:42:51] [x] Starting PokemonGo Bot....
[2016-07-25 19:42:51] [#] Scanning area for objects....
[2016-07-25 19:42:51] [#] Walking from (34.0104215, -118.4996709) to (34.0104215, -118.4996709) 0.00km
Traceback (most recent call last):
  File "pokecli.py", line 228, in <module>
    main()
  File "pokecli.py", line 219, in main
    bot.take_step()
  File "/home/seadog007/PokemonGo-Bot/pokemongo_bot/__init__.py", line 42, in take_step
    self.work_on_cell(cell, location)
  File "/home/seadog007/PokemonGo-Bot/pokemongo_bot/__init__.py", line 73, in work_on_cell
    self.check_session(location)
NameError: global name 'location' is not defined
```

**Comment by seadog007** [comment]
Fixed in d18f30c341d1ba936c50febf1ab49a6fb0e83ac4

**Comment by seadog007** [comment]
```
[2016-07-25 19:51:37] [x] PokemonGO Bot v1.0
[2016-07-25 19:51:37] [x] Configuration initialized
[2016-07-25 19:51:38]
[2016-07-25 19:51:38] [x] Address found: 37.78839,-122.40764
[2016-07-25 19:51:38] [x] Position in-game set as: (37.7883843, -122.4076388, 0.0)
[2016-07-25 19:51:38]
[2016-07-25 19:51:38] [#] Attempting login to Pokemon Go.
[2016-07-25 19:51:39] [+] Login to Pokemon Go successful.
Normal log....
[2016-07-25 20:16:23] [#] Walking from (37.7907971156702, -122.40766656057974) to (37.8008843, -122.4151388) 1.30km
[2016-07-25 20:16:32] [#] Scanning area for objects....
[2016-07-25 20:16:32] [#] Walking from (37.79081205373609, -122.40771067388484) to (37.8008843, -122.4126388) 1.20km
[2016-07-25 20:16:42] [#] Scanning area for objects....
[2016-07-25 20:16:42] [#] Walking from (37.79083893667029, -122.40772671833331) to (37.8008843, -122.4101388) 1.14km
[2016-07-25 20:16:54] [#] Scanning area for objects....
[2016-07-25 20:16:54] [#] Walking from (37.790890067881705, -122.40773684207075) to (37.8008843, -122.4076388) 1.11km
[2016-07-25 20:17:07] [#] Scanning area for objects....
[2016-07-25 20:17:07] [#] Walking from (37.79094590574343, -122.40776306661508) to (37.8008843, -122.4051388) 1.13km
[2016-07-25 20:17:19] [#] Scanning area for objects....
[2016-07-25 20:17:19] [#] Walking from (37.790966706064275, -122.40776509397527) to (37.8008843, -122.4026388) 1.19km
[2016-07-25 20:17:32] [#] Scanning area for objects....
[2016-07-25 20:17:32] [#] Walking from (37.79098915481349, -122.40779742251549) to (37.8008843, -122.40013880000001) 1.29km
[2016-07-25 20:17:44] [#] Scanning area for objects....
[2016-07-25 20:17:44] [#] Walking from (37.79100063008459, -122.40781316324599) to (37.8008843, -122.3976388) 1.42km
[2016-07-25 20:17:56] [#] Scanning area for objects....
[2016-07-25 20:17:56] [#] Walking from (37.79103385055106, -122.4078150849325) to (37.8008843, -122.3951388) 1.56km
[2016-07-25 20:18:08] [#] Scanning area for objects....
[2016-07-25 20:18:08] [#] Walking from (37.79107686929945, -122.40785070719431) to (37.798384299999995, -122.3951388) 1.38km
[2016-07-25 20:18:22] [#] Scanning area for objects....
[2016-07-25 20:18:22] [#] Walking from (37.79109407438849, -122.40788171941796) to (37.7958843, -122.3951388) 1.24km
[2016-07-25 20:18:37] [#] Scanning area for objects....
[2016-07-25 20:18:37] [#] Walking from (37.791149780115596, -122.40788929462094) to (37.7933843, -122.3951388) 1.15km
[2016-07-25 20:18:47] [#] Scanning area for objects....
[2016-07-25 20:18:47] [#] Walking from (37.79118672859461, -122.40791492991268) to (37.790884299999995, -122.3951388) 1.12km
[2016-07-25 20:19:01] [#] Scanning area for objects....
[2016-07-25 20:19:01] [#] Walking from (37.791200397818265, -122.40793992178116) to (37.7883843, -122.3951388) 1.17km
[2016-07-25 20:19:13] [#] Scanning area for objects....
[2016-07-25 20:19:13] [#] Walking from (37.7912477113037, -122.40796588724562) to (37.7858843, -122.3951388) 1.28km
[2016-07-25 20:19:27] Session stale, re-logging in
[2016-07-25 20:19:27] [#] Attempting login to Pokemon Go.
Traceback (most recent call last):
  File "pokecli.py", line 228, in <module>
    main()
  File "pokecli.py", line 219, in main
    bot.take_step()
  File "/home/seadog007/PokemonGo-Bot/pokemongo_bot/__init__.py", line 42, in take_step
    self.work_on_cell(cell, location)
  File "/home/seadog007/PokemonGo-Bot/pokemongo_bot/__init__.py", line 73, in work_on_cell
    self.check_session(position)
  File "/home/seadog007/PokemonGo-Bot/pokemongo_bot/__init__.py", line 192, in check_session
    self.login()
  File "/home/seadog007/PokemonGo-Bot/pokemongo_bot/__init__.py", line 200, in login
    self.api.set_position(*self.position)
TypeError: set_position() takes exactly 4 arguments (3 given)
```

**Comment by douglascamata** [comment]
@seadog007 updated, test please.

**Comment by douglascamata** [comment]
oh no, wait.

**Comment by douglascamata** [comment]
should work now.
