### ISSUE TITLE
[FIX] Typo in file, crashes program.

### ISSUE THREAD

**Issue by LasseSkogland** [PokemonGoF/PokemonGo-Bot#797]
Typo in code `pokemongo_bot/__init__.py`
On line 73 change location to position.

Dev Branch
https://github.com/PokemonGoF/PokemonGo-Bot/commit/1312ca4aa2b6ea800ac4637d3964ae1a9ab6668b

**Comment by Balauue** [comment]
Full issue is 
```
Traceback (most recent call last):
  File "pokecli.py", line 228, in <module>
    main()
  File "pokecli.py", line 219, in main
    bot.take_step()
  File "/PokemonGo-Bot/pokemongo_bot/__init__.py", line 42, in take_step
    self.work_on_cell(cell, location)
  File "/PokemonGo-Bot/pokemongo_bot/__init__.py", line 73, in work_on_cell
    self.check_session(location)
NameError: global name 'location' is not defined
```

**Comment by dmateusp** [comment]
is being corrected, please close once it's fine

**Comment by eggins** [comment]
Fixed!
