### ISSUE TITLE
ImportError: No module named protos.RpcEnum_pb2

### ISSUE THREAD

**Issue by elsidoi** [PokemonGoF/PokemonGo-Bot#806]
### Expected Behavior
Has to start normally

### Actual Behavior
Traceback (most recent call last):
  File "./pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "/home/alexs/src/PokemonGo-Bot/pokemongo_bot/__init__.py", line 13, in <module>
    from pgoapi import PGoApi
  File "/usr/local/lib/python2.7/dist-packages/pgoapi/__init__.py", line 1, in <module>
    from pgoapi      import *
  File "/usr/local/lib/python2.7/dist-packages/pgoapi/pgoapi.py", line 33, in <module>
    from rpc_api import RpcApi
  File "/usr/local/lib/python2.7/dist-packages/pgoapi/rpc_api.py", line 36, in <module>
    import protos.RpcEnum_pb2 as RpcEnum
ImportError: No module named protos.RpcEnum_pb2

### Steps to Reproduce
remove PokemonGo-Bot dir
git clone -b master https://github.com/PokemonGoF/PokemonGo-Bot.git
sudo pip install -r requirements.txt --upgrade
python pokecli.py

### Other Information
OS: 
Linux Mint
uname -a
Linux alexs-mint 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
32cefeed4760d6b5d2b3eb76d783d0f13d068e83

**Comment by elsidoi** [comment]
Issue solved by updating pgoapi via github.
sudo pip install git+https://github.com/tejado/pgoapi.git --upgrade
install -r rquirements.txt --upgrade couldn't help.
