### ISSUE TITLE
Error when installing (new version only)

### ISSUE THREAD

**Issue by rockthrower69** [PokemonGoF/PokemonGo-Bot#808]
I installed this bot 2 days ago and it worked. Now I'm installing it again (for the updates) and I get this error:

```
Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git#egg=pgoapi (from -r requirements.txt (line 1))

  Found command 'git' at '/usr/bin/git'
  Running command /usr/bin/git config remote.origin.url
  https://github.com/tejado/pgoapi.git
  Clone in ./src/pgoapi exists, and has correct URL (https://github.com/tejado/pgoapi.git)
  Updating ./src/pgoapi clone

  Running command /usr/bin/git fetch -q
  Running command /usr/bin/git tag -l
  v1.1.0
  Running command /usr/bin/git rev-parse v1.1.0
  7ab17c59ebbaf6ec79e694fb3bd76438e1b45480
  Running command /usr/bin/git branch -r
    origin/HEAD -> origin/master
    origin/master
  Running command /usr/bin/git branch -l
  * master
  Running command /usr/bin/git rev-parse origin/HEAD
  e8b35057b3c5031f933a19532e81b927a9f12dc0
  Running command /usr/bin/git rev-parse origin/master
  e8b35057b3c5031f933a19532e81b927a9f12dc0
  Running command /usr/bin/git rev-parse master
  e8b35057b3c5031f933a19532e81b927a9f12dc0
  Running command /usr/bin/git reset --hard -q e8b35057b3c5031f933a19532e81b927a9f12dc0
  Running setup.py egg_info for package pgoapi

    Traceback (most recent call last):

      File "<string>", line 14, in <module>

      File "/root/pokemon/new/PokemonGo-Bot/src/pgoapi/setup.py", line 9, in <module>

        install_reqs = parse_requirements(path_req, session=False)

    TypeError: parse_requirements() got an unexpected keyword argument 'session'

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/root/pokemon/new/PokemonGo-Bot/src/pgoapi/setup.py", line 9, in <module>

    install_reqs = parse_requirements(path_req, session=False)

TypeError: parse_requirements() got an unexpected keyword argument 'session'

----------------------------------------

Command python setup.py egg_info failed with error code 1 in /root/pokemon/new/PokemonGo-Bot/src/pgoapi

Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 964, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 225, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 256, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /root/pokemon/new/PokemonGo-Bot/src/pgoapi
```

Looks like the problems are coming from pgoapi.

Error comes when executing `pip install -r requirements.txt`

Thanks in advance

**Comment by surfaace** [comment]
does your issue remain?

have you tried pip install -r requirements,txt --upgrade --no-cache ?

**Comment by rockthrower69** [comment]
`/usr/bin/pip install: error: no such option: --no-cache`

I got this error. Without the --no-cache tag (with the --upgrade tag) I still get the same error:
`TypeError: parse_requirements() got an unexpected keyword argument 'session'`

**Comment by viruz82** [comment]
I have exactly the same error on python version 2.7.3.

**Comment by viruz82** [comment]
Fixed it using the followjng command:
`pip install --upgrade pip` and after that `pip install -r requirements.txt` seems to work.

**Comment by surfaace** [comment]
try with python version 2.7.12, no issues found there
