### ISSUE TITLE
Exception while the bot is walking

### ISSUE THREAD

**Issue by xorinzor** [PokemonGoF/PokemonGo-Bot#809]
### Expected Behavior
It keeps running

### Actual Behavior
```
[2016-07-25 14:46:20] [#] Walking from (SOMEWHERE, SOMEWHERE) to (SOMEWHERE, SOMEWHERE) for approx. 5.02 minutes
Traceback (most recent call last):
  File "pokecli.py", line 219, in <module>
    main()
  File "pokecli.py", line 210, in main
    bot.take_step()
  File "PokemonGo-Bot\pokemongo_bot\__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "PokemonGo-Bot\pokemongo_bot\stepper.py", line 52, in take_step
    self._walk_to(self.config.walk, *position)
  File "PokemonGo-Bot\pokemongo_bot\stepper.py", line 87, in _walk_to
    alt, False)
  File "PokemonGo-Bot\pokemongo_bot\stepper.py", line 101, in _work_at_position
    response_dict = self.api.call()
  File "pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 81, in call
    response = request.request(api_endpoint, self._req_method_list, player_position)
  File "pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 98, in request
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
```

### Steps to Reproduce
Leave it running, it happens at random, I can't figure out a specific pattern unfortunately.
This is the 3rd time it happened to me over the course of roughly ~11 hours in total.

### Other Information
OS: Windows 10 x64
Git Commit: 1624e5ee3669edd665e76718eef2b30a6b7ab21b

**Comment by xorinzor** [comment]
I just got another one while the bot was attempting to catch a pokemon

```
[2016-07-25 19:46:16] [#] Something rustles nearby!
[2016-07-25 19:46:16] [#] A Wild Goldeen appeared! [CP 133] [Potential 0.29]
[2016-07-25 19:46:16] [#] IV [Stamina/Attack/Defense] = [1/7/5]
[2016-07-25 19:46:20] [x] Using Pokeball (chance: 62.29%)... (109 left!)
Traceback (most recent call last):
  File "pokecli.py", line 219, in <module>
    main()
  File "pokecli.py", line 210, in main
    bot.take_step()
  File "C:\Users\xorinzor\Desktop\PokemonGo-Bot\pokemongo_bot\__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "C:\Users\xorinzor\Desktop\PokemonGo-Bot\pokemongo_bot\stepper.py", line 52, in take_step
    self._walk_to(self.config.walk, *position)
  File "C:\Users\xorinzor\Desktop\PokemonGo-Bot\pokemongo_bot\stepper.py", line 87, in _walk_to
    alt, False)
  File "C:\Users\xorinzor\Desktop\PokemonGo-Bot\pokemongo_bot\stepper.py", line 134, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "C:\Users\xorinzor\Desktop\PokemonGo-Bot\pokemongo_bot\__init__.py", line 62, in work_on_cell
    if self.catch_pokemon(pokemon) == PokemonCatchWorker.NO_POKEBALLS:
  File "C:\Users\xorinzor\Desktop\PokemonGo-Bot\pokemongo_bot\__init__.py", line 189, in catch_pokemon
    return_value = worker.work()
  File "C:\Users\xorinzor\Desktop\PokemonGo-Bot\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 111, in work
    id_list1 = self.count_pokemon_inventory()
  File "C:\Users\xorinzor\Desktop\PokemonGo-Bot\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 209, in count_pokemon_inventory
    response_dict = self.api.call()
  File "c:\users\xorinzor\desktop\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 81, in call
    response = request.request(api_endpoint, self._req_method_list, player_position)
  File "c:\users\xorinzor\desktop\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 98, in request
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
```

**Comment by krypttr** [comment]
Confirmed:
[2016-07-25 23:26:26] [+] 3x Pokeball (Total: 16)
[2016-07-25 23:26:26] [#] PokeStop on cooldown. Time left: 4.89 minutes
[2016-07-25 23:26:28] [#] Found fort c43b5242df1540e6973f1b580fb989db.12 at distance 0.42km
[2016-07-25 23:26:28] [#] Need to move closer to Pokestop
[2016-07-25 23:26:28] [#] Walking from (40.772943, -73.980243) to (40.768129, -73.971169) for approx. 3.75 minutes
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "/home/krypt/builds/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/home/krypt/builds/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/home/krypt/builds/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/home/krypt/builds/PokemonGo-Bot/pokemongo_bot/__init__.py", line 93, in work_on_cell
    worker.work()
  File "/home/krypt/builds/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 30, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "/home/krypt/builds/PokemonGo-Bot/pokemongo_bot/stepper.py", line 84, in _walk_to
    self.bot.heartbeat()
  File "/home/krypt/builds/PokemonGo-Bot/pokemongo_bot/__init__.py", line 395, in heartbeat
    self.api.call()
  File "/home/krypt/builds/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 81, in call
    response = request.request(api_endpoint, self._req_method_list, player_position)
  File "/home/krypt/builds/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 98, in request
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException

**Comment by NicholasMoser** [comment]
Through experimenting with this, I believe it's because of changing your credentials mid-execution. Are you guys modifying the username/password in the config.json during execution? For example to run multiple bots?

**Comment by xorinzor** [comment]
Not at all, I dont even edit a configuration file in the meanwhile

**Comment by krypttr** [comment]
Me neither. I ignored it at first but it happened twice.

**Comment by surfaace** [comment]
a soft reset was implemented in dev that refreshes tokenId 1312ca4aa2b6ea800ac4637d3964ae1a9ab6668b

**Comment by lshaf** [comment]
this problem still happen to me if I use google as login account.

**Comment by xorinzor** [comment]
@lshaf make sure you're on the version or a later version that was mentioned.

**Comment by lshaf** [comment]
@xorinzor yeah, sorry. tried to delete that comment but I didn't find this issue.
this one already fixed on dev branch
