### ISSUE TITLE
TypeError: 'bool' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by jane0815** [PokemonGoF/PokemonGo-Bot#822]
### Expected Behavior

Bot running normal

### Actual Behavior

Bot stopped after some time with this error:

[2016-07-25 15:XX:XX] [#] Poliwag has been exchanged for candy!
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "/Users/Users/PokemonGo-Bot2/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/Users/Users/PokemonGo-Bot2/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/Users/Users/PokemonGo-Bot2/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/Users/Users/PokemonGo-Bot2/PokemonGo-Bot/pokemongo_bot/__init__.py", line 93, in work_on_cell
    worker.work()
  File "/Users/Users/PokemonGo-Bot2/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 30, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "/Users/Users/PokemonGo-Bot2/PokemonGo-Bot/pokemongo_bot/stepper.py", line 84, in _walk_to
    self.bot.heartbeat()
  File "/Users/Users/PokemonGo-Bot2/PokemonGo-Bot/pokemongo_bot/__init__.py", line 395, in heartbeat
    self.api.call()
  File "/Users/Users/PokemonGo-Bot2/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 81, in call
    response = request.request(api_endpoint, self._req_method_list, player_position)
  File "/Users/Users/PokemonGo-Bot2/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 98, in request
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException

When trying to restart the bot the same error message:

(PokemonGo-Bot) MAC:PokemonGo-Bot USER$ python2 pokecli.py --config config.json
[2016-07-25 15:44:40] [x] PokemonGO Bot v1.0
[2016-07-25 15:44:40] [x] Configuration initialized
[2016-07-25 15:44:40] [x] Coordinates found in passed in location, not geocoding.
[2016-07-25 15:44:40] 
[2016-07-25 15:44:40] [x] Address found: X, Y
[2016-07-25 15:44:40] [x] Position in-game set as: (X, Y, 0.0)
[2016-07-25 15:44:40] 
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "/Users/User/PokemonGo-Bot2/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/Users/User/PokemonGo-Bot2/PokemonGo-Bot/pokemongo_bot/__init__.py", line 151, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
TypeError: 'bool' object has no attribute '__getitem__'

### Solution / Workaround 

I found out that the bot worked again after i logged in with the Android App. I had two bots running, both stopped with the same error and both restarted only after logging in with the App.

### Other Information

OS: Mac OSX
Git Commit: 6e99169d963bd8637dfb55426650f2fe15e694bd

**Comment by surfaace** [comment]
are you running two bots with the same login credentials?

**Comment by jane0815** [comment]
I am running wwo different account but with the same password.

**Comment by surfaace** [comment]
your seession has probably timedout or its a server error:

File "/Users/Users/PokemonGo-Bot2/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 98, in request
raise NotLoggedInException()
**pgoapi.exceptions.NotLoggedInException**
