### ISSUE TITLE
__init__.py Error

### ISSUE THREAD

**Issue by t4rif4ri** [PokemonGoF/PokemonGo-Bot#826]
Hello, I updated today and its not working anymore. Configuration is set.

### Actual Behavior
[2016-07-25 17:07:04] [x] Configuration initialized
[2016-07-25 17:07:04] [x] Coordinates found in passed in location, not geocoding.
[2016-07-25 17:07:04]
[2016-07-25 17:07:04] [x] Address found: xxx
[2016-07-25 17:07:04] [x] Position in-game set as: (xxx)
[2016-07-25 17:07:04]
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "/home/pi/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/home/pi/PokemonGo-Bot/pokemongo_bot/__init__.py", line 159, in _setup_api
    balls_stock = self.pokeball_inventory()
  File "/home/pi/PokemonGo-Bot/pokemongo_bot/__init__.py", line 238, in pokeball_inventory
    with open(user_web_inventory, 'w') as outfile:
IOError: [Errno 13] Permission denied: u'web/inventory-xxxxx@gmail.com.json'

**Comment by emhtiwedir** [comment]
Servers are going up and down. Same error for me PTC in USA. Both PTC down and Google EU is going up and down.

**Comment by eggins** [comment]
Please run this as sudo (admin) so you have access to the folder.
