### ISSUE TITLE
Attempting login to Pokemon Go Failed

### ISSUE THREAD

**Issue by mehdi-S** [PokemonGoF/PokemonGo-Bot#829]
### Expected Behavior
starts normally

### Actual Behavior
```
[11:43:58] PokemonGO Bot v1.0
[11:43:58] Configuration initialized
[11:43:58] [x] Coordinates found in passed in location, not geocoding.
[11:43:58]
[11:43:58] Location Found: 48.893666,2.390437
[11:43:58] GeoPosition: (48.893666, 2.390437, 0.0)
[11:43:58]
[11:43:58] Attempting login to Pokemon Go.
Traceback (most recent call last):
  File "pokecli.py", line 223, in <module>
    main()
  File "pokecli.py", line 209, in main
    bot.start()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 32, in start
    self._setup_api()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 257, in _setup_api
    self.login()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 242, in login
    str(self.config.password)):
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 158, in login
    response = self.call()
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 81, in call
    response = request.request(api_endpoint, self._req_method_list, player_position)
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 98, in request
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
```

### Steps to Reproduce
launch with PTC credential

### Other Information
OS: Debian x64_86
Git Commit: eaef8fcb9eb8d7006fcdda8ae289ca87e825773d

**Comment by mehdi-S** [comment]
things sometime result into an : 

```
[11:49:07] Attempting login to Pokemon Go.
2016-07-25 11:49:47,627 [    pgoapi] [ERROR] Login failed - unexpected server response!
[11:49:47] [X] Login Error, server busy
[11:49:47] [X] Waiting 10 seconds to try again
```

**Comment by tpmodding** [comment]
i cant even login with the official app, think it is a server problem from PTC, google works without issues...

**Comment by LeaklessGfy** [comment]
http://ispokemongodownornot.com/

**Comment by alvarogzp** [comment]
I think it is a PTC problem, as their web interface is also down: https://club.pokemon.com/us/pokemon-trainer-club/login

**Comment by mehdi-S** [comment]
ok closed
