### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'split'

### ISSUE THREAD

**Issue by imginya** [PokemonGoF/PokemonGo-Bot#840]
### Expected Behavior
should run

### Actual Behavior
`AttributeError: 'bool' object has no attribute 'split'
`

### Steps to Reproduce
python pokecli.py -cf configs/config.json     

### Other Information
OS: Ubuntu 14.04 
Git Commit: (32cefeed4760d6b5d2b3eb76d783d0f13d068e83
)

**Comment by leadboots5** [comment]
you left off the rest of the error

**Comment by imginya** [comment]
here it is
```
PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py:6: UserWarning: Module _yaml was already imported from /usr/lib/python2.7/dist-packages/_yaml.so, but /usr/local/lib/python2.7/dist-packages is being added to sys.path
  import pkg_resources
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 197, in main
    config = init_config()
  File "pokecli.py", line 184, in init_config
    config.evolve_all = [str(pokemon_name) for pokemon_name in config.evolve_all.split(',')]
AttributeError: 'bool' object has no attribute 'split'

```

**Comment by leadboots5** [comment]
copy/paste the config file without username/pass

**Comment by imginya** [comment]
see
```
{
    "auth_service": "google",
    "username": "email",
    "password": "pass",
    "location": "28.7041, 77.1025",
    "gmapkey": "api",
    "max_steps": 50,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "101,102",
    "evolve_all": true
}
```

**Comment by leadboots5** [comment]
You're using evolve_all wrong.

1. "evolve_all": "all"
  Will evolve ALL pokemons.
2. "evolve_all": "Pidgey,Weedle"
  Will only evolve Pidgey and Weedle.
3. Not setting evolve_all or having any other string would not evolve any pokemons on startup.

**Comment by imginya** [comment]
Thanks a lot!
