### ISSUE TITLE
Couldn't find protoc in your environment OR other issue

### ISSUE THREAD

**Issue by EvilSupahFly** [PokemonGoF/PokemonGo-Bot#849]
### Expected Behavior
The Bot runs

### Actual Behavior
The Bot crashes:
```
WARNING: yacc table file version is out of date
[2016-07-25 15:06:43] [x] PokemonGO Bot v1.0
[2016-07-25 15:06:43] [x] Configuration initialized
[2016-07-25 15:06:43] [x] Coordinates found in passed in location, not geocoding.
[2016-07-25 15:06:43] 
[2016-07-25 15:06:43] [x] Address found: 43.159506, -79.247432
[2016-07-25 15:06:43] [x] Position in-game set as: (43.159506, -79.247432, 0.0)
[2016-07-25 15:06:43] 
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "/home/seann/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/home/seann/PokemonGo-Bot/pokemongo_bot/__init__.py", line 151, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'player_data'
```

### Steps to Reproduce
Run the bot

### Other Information
OS: Ubuntu 15.10 x64, kernel 4.5.3-040503-generic #201605041831
Git Commit: ab604452c2a0a72e13fa6d940fa55902d3b01466

**Comment by surfaace** [comment]
server return message error

**Comment by EvilSupahFly** [comment]
How is this a server error when I can run it fine from Commit 1f426d427d1f258d8fb8d2abdcf4d3dee7a42c7f?

**Comment by dmdque** [comment]
I had the same issue, and recloning the repo fixed it for me.
