### ISSUE TITLE
Random crash master branch

### ISSUE THREAD

**Issue by koltziver** [PokemonGoF/PokemonGo-Bot#856]
Getting some random crashes in the dev and master branch, seems to get the error randomly whenever its getting ready to spin a pokestop or before launching a pokeball.

Traceback (most recent call last):
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot\pokecli.py", line 220, in <module>
    main()
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot\pokecli.py", line 211, in main
    bot.take_step()
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot\pokemongo_bot\__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot\pokemongo_bot\stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot\pokemongo_bot\stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot\pokemongo_bot\__init__.py", line 96, in work_on_cell
    hack_chain = worker.work()
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot\pokemongo_bot\cell_workers\seen_fort_worker.py", line 74, in work
    " (Total: " + str(self.bot.item_inventory_count(item_id)) + ")", 'green')
  File "C:\Users\Alimentosybebidas\Desktop\PokemonGo-Bot\pokemongo_bot\__init__.py", line 268, in item_inventory_count
    inventory_dict = inventory_req['responses'][
TypeError: 'NoneType' object has no attribute '__getitem__'

OS: windows 10 
Git Commit: 32cefeed4760d6b5d2b3eb76d783d0f13d068e83

Thanks for the great work guys.

**Comment by codybaldwin** [comment]
Does this happen _every_ time you spin a pokestop or try to catch a pokemon?

**Comment by koltziver** [comment]
No I can run for a few mins or almost an hour, its totally random.

**Comment by codybaldwin** [comment]
It appears that the request to get the item count comes back in a bad state.

**Comment by surfaace** [comment]
as you stated, you can run it for a few pokestops which means that code is correct as it can 'getitem'. so this is mostlikley a server issue
