### ISSUE TITLE
Tulpe index out of range when updating weblocation

### ISSUE THREAD

**Issue by surfaace** [PokemonGoF/PokemonGo-Bot#864]
### Expected Behavior
Seems to be related to updating web server location?
Anyway it should update accordingly

### Actual Behavior
[21:47:38] Scanning area for objects....
[21:47:38] Walking from (59.335952999999996, 18.060292) to (59.335952999999996, 18.060292) 0.00km
Traceback (most recent call last):
  File "D:\Pokemon stuff\PokemonGo-Bot\pokecli.py", line 223, in <module>
    main()
  File "D:\Pokemon stuff\PokemonGo-Bot\pokecli.py", line 214, in main
    bot.take_step()
  File "D:\Pokemon stuff\PokemonGo-Bot\pokemongo_bot\__init__.py", line 38, in take_step
    cells = self.find_close_cells(*location)
  File "D:\Pokemon stuff\PokemonGo-Bot\pokemongo_bot\__init__.py", line 107, in find_close_cells
    self.update_web_location(map_cells,lat,lng)
  File "D:\Pokemon stuff\PokemonGo-Bot\pokemongo_bot\__init__.py", line 50, in update_web_location
    alt = self.position[2]
IndexError: tuple index out of range

### Steps to Reproduce
N/A, just ran it on git commit below and it occured after 30 min

### Other Information
OS: Win 10 x64
Git Commit: eb931c0a4fd57b65f88873a67506b49f0a3534b0

**Comment by michi0987** [comment]
Same

**Comment by RiberoD07** [comment]
same issue here: Traceback (most recent call last):
  File "pokecli.py", line 223, in <module>
    main()
  File "pokecli.py", line 214, in main
    bot.take_step()
  File "C:\Users\Desktop\TestPokemonDev\PokemonGo-Bot\pokemongo_bot\__init__.py", line 38, in take_step
    cells = self.find_close_cells(*location)
  File "C:\Users\Desktop\TestPokemonDev\PokemonGo-Bot\pokemongo_bot\__init__.py", line 107, in find_close_cells
    self.update_web_location(map_cells,lat,lng)
  File "C:\Users\Desktop\TestPokemonDev\PokemonGo-Bot\pokemongo_bot\__init__.py", line 50, in update_web_location
    alt = self.position[2]
IndexError: tuple index out of range

Happened right after it said session stale, re-logging in, tries to login, says login successful and error occurs shortly after it begins scanning.

**Comment by hakkotsu** [comment]
Try to remove location-*char_name*.json file from web directory

**Comment by shaosh** [comment]
Is this issue fixed?
