### ISSUE TITLE
[Master] walk to pokestop error

### ISSUE THREAD

**Issue by 03t02** [PokemonGoF/PokemonGo-Bot#883]
I got this error on master. I can catch pokemon, pokestop normally, it works well, but I got this error every 1 hour.

```python
Traceback (most recent call last):
  File "./pokecli.py", line 220, in <module>
    main()
  File "./pokecli.py", line 211, in main
    bot.take_step()
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/__init__.py", line 93, in work_on_cell
    worker.work()
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 30, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/stepper.py", line 88, in _walk_to
    alt, False)
  File "/Users/ttran/TMPS/PokemonGo-Bot/pokemongo_bot/stepper.py", line 102, in _work_at_position
    response_dict = self.api.call()
  File "/Users/ttran/TMPS/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 81, in call
    response = request.request(api_endpoint, self._req_method_list, player_position)
  File "/Users/ttran/TMPS/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 98, in request
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException

```

**Comment by beedy01** [comment]
exactly same with my previous error #790

**Comment by 03t02** [comment]
Thanks !

Update: Close duplicated
