### ISSUE TITLE
Report error after 1hr working.

### ISSUE THREAD

**Issue by xiejiachen** [PokemonGoF/PokemonGo-Bot#886]
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "/Users/jiachenxie/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/Users/jiachenxie/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/Users/jiachenxie/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/Users/jiachenxie/PokemonGo-Bot/pokemongo_bot/__init__.py", line 93, in work_on_cell
    worker.work()
  File "/Users/jiachenxie/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 30, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "/Users/jiachenxie/PokemonGo-Bot/pokemongo_bot/stepper.py", line 88, in _walk_to
    alt, False)
  File "/Users/jiachenxie/PokemonGo-Bot/pokemongo_bot/stepper.py", line 102, in _work_at_position
    response_dict = self.api.call()
  File "/Users/jiachenxie/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 81, in call
    response = request.request(api_endpoint, self._req_method_list, player_position)
  File "/Users/jiachenxie/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 98, in request
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
jiachendeMacBook-Pro:PokemonGo-Bot jiachenxie$ python pokecli.py

**Comment by bstpierr** [comment]
This should now be fixed in dev thanks to https://github.com/PokemonGoF/PokemonGo-Bot/pull/735 refreshing the auth token before expiry.

You will still get this error if you change your password while the bot is running.

**Comment by MikeDX** [comment]
Sadly the dev branch is currently unusable, at least for me :(
