### ISSUE TITLE
NameError: global name 'item_list' is not defined

### ISSUE THREAD

**Issue by fvorez** [PokemonGoF/PokemonGo-Bot#89]
Now at Pokestop: Immaculate Conception Catholic Church - Spinning...
- Loot:
- 50 xp
Traceback (most recent call last):
  File "pokecli.py", line 105, in <module>
    main()
  File "pokecli.py", line 102, in main
    bot.take_step()
  File "C:\Users\Orez\Desktop\PokemonGo-Bot-master\bot.py", line 26, in take_ste
p
    self.stepper.take_step()
  File "C:\Users\Orez\Desktop\PokemonGo-Bot-master\stepper.py", line 59, in take
_step
    self.bot.work_on_cell(cell,position)
  File "C:\Users\Orez\Desktop\PokemonGo-Bot-master\bot.py", line 43, in work_on_
cell
    hack_chain = worker.work()
  File "C:\Users\Orez\Desktop\PokemonGo-Bot-master\cell_workers\seen_fort_worker
.py", line 52, in work
    item_name = item_list[item_id]
NameError: global name 'item_list' is not defined

**Comment by douglascamata** [comment]
@fvorez fixing this in a minute.

**Comment by fvorez** [comment]
Thank you sir :)! Great work btw!

**Comment by fvorez** [comment]
I know this probably isnt the right place to ask, but how do i get a hold of copies of this after you make the fixes, or does it just take a few for you to update (merge?) the .py? sorry..a bit new to this python and github stuff

**Comment by douglascamata** [comment]
Oh, I see. Are you using github app or the command-line?
