### ISSUE TITLE
[Error] pgoapi.exceptions.NotLoggedInException

### ISSUE THREAD

**Issue by pararang** [PokemonGoF/PokemonGo-Bot#906]
### Expected Behavior
Bot keep running

### Actual Behavior

[2016-07-26 10:22:50] [#] PokeStop on cooldown. Time left: 4.97 minutes
[2016-07-26 10:22:52] [#] Found fort 70410eded3e9447ea48c487723297efe.16 at distance 0.76km
[2016-07-26 10:22:52] [#] Need to move closer to Pokestop
[2016-07-26 10:22:52] [#] Walking from (34.011937, -118.490611) to (34.012935, -118.490661) for approx. 27.00 seconds
Traceback (most recent call last):
  File "./pokecli.py", line 220, in <module>
    main()
  File "./pokecli.py", line 211, in main
    bot.take_step()
  File "/opt/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/opt/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/opt/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/opt/PokemonGo-Bot/pokemongo_bot/__init__.py", line 93, in work_on_cell
    worker.work()
  File "/opt/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 30, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "/opt/PokemonGo-Bot/pokemongo_bot/stepper.py", line 84, in _walk_to
    self.bot.heartbeat()
  File "/opt/PokemonGo-Bot/pokemongo_bot/__init__.py", line 395, in heartbeat
    self.api.call()
  File "/home/ikhsan/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 81, in call
    response = request.request(api_endpoint, self._req_method_list, player_position)
  File "/home/ikhsan/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 98, in request
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException

### Steps to Reproduce
Run the bot for 4+ hours.

### Other Information
OS: Ubuntu 14.04
Git Commit: 55adefeeb580ed8bb51d097e56a506e2973377c9

**Comment by ironbishop** [comment]
that's the work in progress to fix  #366, #713, #886, etc... all are marked as closed, but the master branch keeps throwing NotLoggedInException after 1h... Maybe #735 is still in dev, you just have to wait for it to be merged in the master branch.

**Comment by pararang** [comment]
@ironbishop ok, waiting for that. :+1:

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
