### ISSUE TITLE
'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by papin97** [PokemonGoF/PokemonGo-Bot#911]
### Expected Behavior
Spinning Pokestop will get loot

### Actual Behavior
This error shown after get EXP
[2016-07-26 10:45:12] [#] Finished walking
[2016-07-26 10:45:16] [#] Arrived at Pokestop
[2016-07-26 10:45:20] [#] Now at Pokestop: Hugging Abstract Statue - Spinning...
[2016-07-26 10:45:23] [+] Loot:
[2016-07-26 10:45:23] [+] 50 xp
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "C:\Users\papin\Documents\GitHub\PokemonGo-Bot\pokemongo_bot\__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "C:\Users\papin\Documents\GitHub\PokemonGo-Bot\pokemongo_bot\stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "C:\Users\papin\Documents\GitHub\PokemonGo-Bot\pokemongo_bot\stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "C:\Users\papin\Documents\GitHub\PokemonGo-Bot\pokemongo_bot\__init__.py", line 96, in work_on_cell
    hack_chain = worker.work()
  File "C:\Users\papin\Documents\GitHub\PokemonGo-Bot\pokemongo_bot\cell_workers\seen_fort_worker.py", line 74, in work
    " (Total: " + str(self.bot.item_inventory_count(item_id)) + ")", 'green')
  File "C:\Users\papin\Documents\GitHub\PokemonGo-Bot\pokemongo_bot\__init__.py", line 268, in item_inventory_count
    inventory_dict = inventory_req['responses'][
TypeError: 'NoneType' object has no attribute '__getitem__'

### Steps to Reproduce
This error is shown during normal usage, especially after spinning pokestop

### Other Information
OS: Windows 10 64-bit
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here) 32cefeed4760d6b5d2b3eb76d783d0f13d068e83

**Comment by hoangnn89** [comment]
Google Account

**Comment by papin97** [comment]
Yeah, Google Account.

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
