### ISSUE TITLE
TypeError: argument of type 'bool' is not iterable

### ISSUE THREAD

**Issue by ugurbor** [PokemonGoF/PokemonGo-Bot#913]
[2016-07-25 23:45:48] [#] Need to move closer to Pokestop
[2016-07-25 23:45:48] [#] Walking from (41.044054, 29.004429) to (41.045247, 29.003073) for approx. 43.00 seconds
[2016-07-26 00:05:58] [#] Finished walking
[2016-07-26 00:06:28] [#] Arrived at Pokestop
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step    self.stepper.take_step()
  File "/root/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/root/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 96, in work_on_cell
    hack_chain = worker.work()
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/seen_fort_worker.py", line 31, in work
    if 'responses' in response_dict \
TypeError: argument of type 'bool' is not iterable

### Other Information
OS: Debian 7 32bit

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
