### ISSUE TITLE
TypeError: 'bool' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by Snorbitz** [PokemonGoF/PokemonGo-Bot#915]
Probably Missing something but a little guidance would be appreciated....

[14:31:35] Attempting login to Pokemon Go.
[14:31:38] Login to Pokemon Go successful.
Traceback (most recent call last):
  File "C:\pokebot\PokemonGo-Bot\pokecli.py", line 224, in <module>
    main()
  File "C:\pokebot\PokemonGo-Bot\pokecli.py", line 210, in main
    bot.start()
  File "C:\pokebot\PokemonGo-Bot\pokemongo_bot\__init__.py", line 31, in start
    self._setup_api()
  File "C:\pokebot\PokemonGo-Bot\pokemongo_bot\__init__.py", line 269, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
TypeError: 'bool' object has no attribute '__getitem__'

OS: 
Windows 10

**Comment by dragonalvaro** [comment]
`Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "/home/alvaro/Pokemon/PokemonGo-Bot.git/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/home/alvaro/Pokemon/PokemonGo-Bot.git/pokemongo_bot/__init__.py", line 151, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'player_data'`

**Comment by hklcf** [comment]
![image](https://cloud.githubusercontent.com/assets/410302/17139917/f5a8d140-5378-11e6-8f59-c4eead9a7f25.png)

6a9e74c91b9f5234f74c0cb09ec2568f1f37f01f

**Comment by TheOssi** [comment]
This is a issue probably caused by the Pokémon Go servers. It only appears when the servers are not reachable for some reason.

**Comment by hklcf** [comment]
@TheOssi can make it retry ?

**Comment by Snorflake** [comment]
run a simple bash script. ``while true; do ./pokecli.py; done``

**Comment by mehdi-S** [comment]
i've make it work by using a **_screen_** session
[more information about screen and how to use screen here (rackaid.com)](https://www.rackaid.com/blog/linux-screen-tutorial-and-how-to/)

but for the basics : 
`screen -S mysessionname` to create a new screen session
Do your business (including clone the repo ,setup it, and launch it) and use CTRL-A-D to exit the screen session
Now from here do the same with a different name for all the bot you want to launch
If you want to get back you your session, use `screen -r mysessionname` or `screen -r` with no argument to show up a list of your active session

**Comment by Snorflake** [comment]
not exactly on topic, but tmux would be a better alternative to screen.

**Comment by mehdi-S** [comment]
@Snorflake can you develop ?

**Comment by Snorflake** [comment]
indeed I can

**Comment by mehdi-S** [comment]
?

**Comment by RolfKoenders** [comment]
Just got the same error, after a few minutes running the latest 'master'

```
[2016-07-27 20:05:57] [#] PokeStop on cooldown. Time left: 4.61 minutes
[2016-07-27 20:05:59] [#] Found fort d950340f722c4111936a83d7282a3037.16 at distance 0.20km
[2016-07-27 20:05:59] [#] Need to move closer to Pokestop
[2016-07-27 20:05:59] [#] Walking from (52.296738, 5.250926) to (52.295504, 5.245426) for approx. 1.60 minutes
[2016-07-27 20:06:56] [#] Something rustles nearby!
[2016-07-27 20:06:57] [#] A Wild Rattata appeared! [CP 183] [Potential 0.44]
[2016-07-27 20:06:57] [#] IV [Stamina/Attack/Defense] = [8/10/2]
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 93, in work_on_cell
    worker.work()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 30, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/stepper.py", line 88, in _walk_to
    alt, False)
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 63, in work_on_cell
    if self.catch_pokemon(pokemon) == PokemonCatchWorker.NO_POKEBALLS:
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 190, in catch_pokemon
    return_value = worker.work()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 74, in work
    balls_stock = self.bot.pokeball_inventory()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 234, in pokeball_inventory
    inventory_dict = inventory_req['responses']['GET_INVENTORY'][
TypeError: 'bool' object has no attribute '__getitem__'
```

**Comment by Yky** [comment]
same as @RolfKoenders here

**Comment by hklcf** [comment]
server problem

**Comment by sangwon04** [comment]
I don't believe this is a server problem--I literally just logged off on my mobile device and tried running the bot but same error.

**Comment by hklcf** [comment]
@sangwon04 So what's the problem?

**Comment by Roydeking52** [comment]
I have the save issue and we are not alone: http://downdetector.com/status/pokemon-go

**Comment by sangwon04** [comment]
@hklcf I was able to resolve the issue--there was a zombie cmd process that I had to kill.

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
