### ISSUE TITLE
After pokemon evolve on start it crashes

### ISSUE THREAD

**Issue by Brown-amazingness** [PokemonGoF/PokemonGo-Bot#916]
### Expected Behavior
use the command with the .json that follows the .example and allow it to evolve_all without crashes

### Actual Behavior
after it evolves all available pokemon, it'll crash with this error

```[#] Evolved 28 pokemons! Checking if any of them needs to be released ...
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "/Users/user/Downloads/PokemonGo-Bot-dev-6/pokemongo_bot/__init__.py", line 40, in take_step
    self.work_on_cell(cell, location)
  File "/Users/user/Downloads/PokemonGo-Bot-dev-6/pokemongo_bot/__init__.py", line 144, in work_on_cell
    worker.work()
  File "/Users/user/Downloads/PokemonGo-Bot-dev-6/pokemongo_bot/cell_workers/evolve_all_worker.py", line 49, in work
    self._release_evolved(release_cand_list_ids)
  File "/Users/user/Downloads/PokemonGo-Bot-dev-6/pokemongo_bot/cell_workers/evolve_all_worker.py", line 72, in _release_evolved
    if self.should_release_pokemon(pokemon_name, pokemon_cp, pokemon_potential):
  File "/Users/user/Downloads/PokemonGo-Bot-dev-6/pokemongo_bot/cell_workers/evolve_all_worker.py", line 156, in should_release_pokemon
    if self._check_always_capture_exception_for(pokemon_name):
  File "/Users/user/Downloads/PokemonGo-Bot-dev-6/pokemongo_bot/cell_workers/evolve_all_worker.py", line 220, in _check_always_capture_exception_for
    always_capture_list = self._get_always_capture_list()
  File "/Users/user/Downloads/PokemonGo-Bot-dev-6/pokemongo_bot/cell_workers/evolve_all_worker.py", line 211, in _get_always_capture_list
    exceptions = self._get_exceptions()
  File "/Users/user/Downloads/PokemonGo-Bot-dev-6/pokemongo_bot/cell_workers/evolve_all_worker.py", line 205, in _get_exceptions
    exceptions = self.config.release_config.get('exceptions')
AttributeError: 'Namespace' object has no attribute 'release_config'```

### Steps to Reproduce

use standard .json from the example and set evolve_all to true. After it evolves all it will crash

### Other Information
OS: OSX 10.11.2
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by Anyrainel** [comment]
I remembered that "evolve_all" should be a list of pokemon names. use "all" if you want to evolve at every possibility. The readme is somewhat broken, it says set to true but gives examples of strings just below.

**Comment by Brown-amazingness** [comment]
Yeah, I did set my evolve_all at start to have a couple pokemon in the strings to make sure it doesn't have issues with no pokemon to evolve

**Comment by Foxy1990** [comment]
can confirm that it doesnt work if u specify pokemon to evole

**Comment by Anyrainel** [comment]
Mine could work with specified pokemon... Are you guys in master branch? I guess master branch may only support "all" or "Pidgey,Weedle". From [https://github.com/PokemonGoF/PokemonGo-Bot#evolve-all-configuration](readme - evolve all)

**Comment by Anyrainel** [comment]
well, mine seems have the same problem now XD.

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
