### ISSUE TITLE
KeyError: 'individual_attack'

### ISSUE THREAD

**Issue by GoMapur** [PokemonGoF/PokemonGo-Bot#926]
Traceback (most recent call last):
  File "pokecli.py", line 232, in <module>
    main()
  File "pokecli.py", line 223, in main
    bot.take_step()
  File "/root/automated_scripts/PokemonGo-Bot/pokemongo_bot/__init__.py", line 40, in take_step
    self.work_on_cell(cell, location)
  File "/root/automated_scripts/PokemonGo-Bot/pokemongo_bot/__init__.py", line 177, in work_on_cell
    if self.catch_pokemon(pokemon) == PokemonCatchWorker.NO_POKEBALLS:
  File "/root/automated_scripts/PokemonGo-Bot/pokemongo_bot/__init__.py", line 322, in catch_pokemon
    return_value = worker.work()
  File "/root/automated_scripts/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 55, in work
    pokemon['pokemon_data']['individual_attack'],
KeyError: 'individual_attack'

**Comment by maestroi** [comment]
Please descripe what you did or how you get this error

**Comment by ritashugisha** [comment]
Should have been fixed in PR #927.

**Comment by GoMapur** [comment]
LOL ty
