### ISSUE TITLE
Empty loot stops the bot

### ISSUE THREAD

**Issue by kevinxh** [PokemonGoF/PokemonGo-Bot#931]
### Expected Behavior
Walks to a PokeStop,
empty loot,
continue to the next stop or catch nearby pokemon

### Actual Behavior
Every time it encounters empty loot, the script stops..

[2016-07-25 23:23:57] [#] Finished walking
[2016-07-25 23:23:57] [#] Arrived at Pokestop
[2016-07-25 23:24:00] [#] Now at Pokestop: Union Square - Spinning...
[2016-07-25 23:24:03] [+] Loot:
[2016-07-25 23:24:03] [#] Nothing found.
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "C:\Users\kevin\PokemonGo-Bot\pokemongo_bot\__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "C:\Users\kevin\PokemonGo-Bot\pokemongo_bot\stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "C:\Users\kevin\PokemonGo-Bot\pokemongo_bot\stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "C:\Users\kevin\PokemonGo-Bot\pokemongo_bot\__init__.py", line 96, in work_on_cell
    hack_chain = worker.work()
  File "C:\Users\kevin\PokemonGo-Bot\pokemongo_bot\cell_workers\seen_fort_worker.py", line 110, in work
    raise RuntimeError(message)
RuntimeError: Stopped at Pokestop and did not find experience, items or information about the stop cooldown. You are probably softbanned. Try to play on your phone, if pokemons always ran away and you find nothing in PokeStops you are indeed softbanned. Please try again in a few hours.

### Steps to Reproduce
Since the location is usually unchanged.
run the script to loot nearby PokeStop and rerun the script within 5 mins.
Loot empty PokeStop will cause this problem.
(the account was not soft banned.)

### Other Information
OS: Win 10

**Comment by oinquer** [comment]
I also noticed that yesterday, solution for now was to put my python inside a bat script with a loop.

**Comment by rguedes** [comment]
Is not a bug. You are softban. Too many teleports.

**Comment by binarydepartment** [comment]
I don't think it's a softban. It's always the same pokestop, and if you restart the script it works again.

**Comment by mboque50** [comment]
It's not a soft banned because I have the same problem and when I retry it's OK...

I don't have exactly, when the system doesn't know the Pokestop I crash : 

[2016-07-26 16:20:49] [#] Arrived at Pokestop
[2016-07-26 16:20:52] [#] Now at Pokestop: Unknown - Spinning...
Traceback (most recent call last):
  File "pokecliSM.py", line 220, in <module>
    main()
  File "pokecliSM.py", line 211, in main
    bot.take_step()
  File "/Users/Mathieu/Documents/Pokemon/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/Users/Mathieu/Documents/Pokemon/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/Users/Mathieu/Documents/Pokemon/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/Users/Mathieu/Documents/Pokemon/PokemonGo-Bot/pokemongo_bot/__init__.py", line 96, in work_on_cell
    hack_chain = worker.work()
  File "/Users/Mathieu/Documents/Pokemon/PokemonGo-Bot/pokemongo_bot/cell_workers/seen_fort_worker.py", line 51, in work
    if spin_details['result'] == 1:
KeyError: 'result'

**Comment by ayozebarrera** [comment]
Same here

```
[2016-07-26 11:44:50] [#] Found fort 975805c30dc6403ab07856c607e9e9a9.12 at distance 0.16km
[2016-07-26 11:44:50] [#] Need to move closer to Pokestop
[2016-07-26 11:44:50] [#] Walking from (34.0106044, -118.4989964) to (34.009034, -118.497669) for approx. 52.00 seconds
[2016-07-26 11:47:03] [#] Finished walking
[2016-07-26 11:47:03] [#] Arrived at Pokestop
[2016-07-26 11:47:05] [#] Now at Pokestop: Unknown - Spinning...
Traceback (most recent call last):
  File "pokecli.py", line 222, in <module>
    main()
  File "pokecli.py", line 213, in main
    bot.take_step()
  File "/Users/ayozebarrera/Proyectos/PokemonGo-Bot/pokemongo_bot/__init__.py", line 37, in take_step
    self.stepper.take_step()
  File "/Users/ayozebarrera/Proyectos/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/Users/ayozebarrera/Proyectos/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/Users/ayozebarrera/Proyectos/PokemonGo-Bot/pokemongo_bot/__init__.py", line 98, in work_on_cell
    hack_chain = worker.work()
  File "/Users/ayozebarrera/Proyectos/PokemonGo-Bot/pokemongo_bot/cell_workers/seen_fort_worker.py", line 51, in work
    if spin_details['result'] == 1:
KeyError: 'result'
```

OS: OSX

Commit: a011bfef24e927c292fa9a9889408f5fc3a93d48

**Comment by kevinxh** [comment]
@rguedes it is not a softban since I can still go to other pokestop and catch pokemons.
If I start the script at the same location, it always happen on exactly same PokeStop.

**Comment by fdelia** [comment]
Same here, it happens at the same pokestop, not with others. I printed `spin_details`: It's empty in this case. OS: OSX, Commit: 3aca6d798f8a3e173dce0beb7b13c9505cc5b251

**Comment by TheGoldenXY** [comment]
Please upgrade to latest `dev` branch by using this command:
```
git reset --hard
git pull -f
```

Then you need to upgrade your deps, you can do so by running this command:
`pip install --upgrade -r requirements.txt`

If the problem persists ==> open a new issue. Locking this.

/closed
