### ISSUE TITLE
Bot crashes: KeyError: 'result'

### ISSUE THREAD

**Issue by ugurbor** [PokemonGoF/PokemonGo-Bot#977]
[2016-07-26 08:07:22] [#] Now at Pokestop: BJK Kartal Heykeli - Spinning...
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/root/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/root/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 96, in work_on_cell
    hack_chain = worker.work()
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/seen_fort_worker.py", line 51, in work
    if spin_details['result'] == 1:
KeyError: 'result'

OS: Debian 7 32bit

**Comment by tstumm** [comment]
Please use the most recent commit
